### ISSUE TITLE
services.nix-serve permission denied

### ISSUE THREAD

**Issue by skvl** [NixOS/nix#1001]
Hello.

I'm trying to setup *services.nix-serve*. I have added lines into my *configuration.nix*:
```
networking.firewall.allowedTCPPorts = [ 80 ];

services.nix-serve = {
      enable = true;
      bindAddress = "";
      port = 80;
};
```
But in systemd I could see error:
```
Can't connect to TCP port 80 on 0.0.0.0 [Permission denied]
```

Also this works:
```
sudo nix-serve --listen :80
```

**Comment by domenkozar** [comment]
This issue belongs to https://github.com/NixOS/nixpkgs (please reopen there).

But in short, it's because nix-serve runs under user `nix-serve`, which can't open ports lower than 2014 (Unix security restriction).

**Comment by skvl** [comment]
@domenkozar thank You very much.
