### ISSUE TITLE
Nix uses only sources when installing packages from behind proxy

### ISSUE THREAD

**Issue by ramboman** [NixOS/nix#10017]
Here is how to reproduce the problem :

1) Have a system without connection except for a proxy at 127.0.0.1:8082
2) Create this script: `proxy.sh`:
```
export all_proxy=127.0.0.1:8082
export http_proxy=$all_proxy
export https_proxy=$all_proxy
```
3) Create this script: `install.sh`
```
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
source "$SCRIPT_DIR/proxy.sh"
sh <(curl -L https://nixos.org/nix/install) --daemon --yes
```
3) Execute to install Nix:
```
$ sudo bash install.sh
```
4) Execute:
```
$ sudo sh -c "echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf"
```
5) Restart terminal
6) Execute:
```
$ source proxy.sh
```
7) Install cowsay to test the install procedure:
```
$ nix profile install nixpkgs#cowsay
warning: you don't have Internet access; disabling some network-dependent features
<downloads sources / builds from sources>
```

Results:
- Nix prints a warning about not having Internet access even though, it can access the internet through the proxy.
- Nix relies on source instead of cache.

When I do this:
1) Create a normal vanilla linux system with internet connection
2) Execute:
```
$ sh <(curl -L https://nixos.org/nix/install) --daemon --yes
$ sudo sh -c "echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf"
```
3) Restart terminal
4) Install cowsay to test the install procedure:
```
$ nix profile install nixpkgs#cowsay
<downloads cache / installs from cache>
```

Results:
- Nix relies on cache as intended.

Question:
- How do I get Nix to work with a proxy in the same way it works without it?

**Comment by thufschmitt** [comment]
That's strange, [the docs](https://nixos.org/manual/nix/stable/installation/env-variables.html#proxy-environment-variables) at least mention that if the proxy-related environment variables are present when running the installer, then it will make sure that the daemon has access to them. Does `etc/systemd/system/nix-daemon.service.d/override.conf` exist and contains the required env var overrides?

Btw, I don't think that's the cause of your issue, but is there any reason you're running the installer as root? If you have `sudo` access, running it as your user is generally preferable.

**Comment by ramboman** [comment]
> Does `etc/systemd/system/nix-daemon.service.d/override.conf` exist and contains the required env var overrides?

```
$ cat /etc/systemd/system/nix-daemon.service.d/override.conf
[Service]
Environment=http_proxy=127.0.0.1:8082
Environment=https_proxy=127.0.0.1:8082
```

> ... but is there any reason you're running the installer as root? If you have `sudo` access, running it as your user is generally preferable.

There is some bug in the installer when installing without a connection except a proxy. I made a bug report [here](https://github.com/NixOS/nix/issues/10016) for more details.

**Comment by ramboman** [comment]
ramboman says [here](https://github.com/NixOS/nix/issues/10017#issue-2135964023):
> 6. Execute:
> ```
> $ source proxy.sh
> ```

This step is necessary, because even though `/etc/systemd/system/nix-daemon.service.d/override.conf` is ok, I still need to explicitly export `http_proxy` and `https_proxy` to make `nix profile install ...` connect to the internet.

It seems logical that if `override.conf` is ok, I should not need to explicitly export the proxy variables to make `nix` connect to the intenet. Am I wrong?

**Comment by thufschmitt** [comment]
> It seems logical that if override.conf is ok, I should not need to explicitly export the proxy variables to make nix connect to the internet. Am I wrong?

It should yes.

The `you don't have Internet access; disabling some network-dependent features` comes from a check that Nix does [here](https://github.com/NixOS/nix/blob/ffcd87fb2b7886aac179594df96e0654ef7f32b0/src/nix/main.cc#L36-L59) which considers that there's no internet if there's no non-loopback interface – which is indeed too eager if the loopback interface exposes a proxy that can talk to the outside world. Is that the case for you? If so, we could make the check more lenient if there's a proxy set.

**Comment by ramboman** [comment]
ramboman says [here](https://github.com/NixOS/nix/issues/10017#issue-2135964023):
> 7. Install cowsay to test the install procedure:
> ```
> $ nix profile install nixpkgs#cowsay
> warning: you don't have Internet access; disabling some network-dependent features
> <downloads sources / builds from sources>
> ```

At step 7, there was that specific warning. It is located [here](https://github.com/NixOS/nix/blob/master/src/nix/main.cc#L470). I wanted to know whether `nix` would work correctly if it detects that there is an Internet access through the proxy.

Here is what I did:
1) Do the steps 1-6 from my first [post](https://github.com/NixOS/nix/issues/10017#issue-2135964023)
2) Connect the system to the internet
3) Execute:
```
$ curl -LO https://github.com/NixOS/nix/archive/refs/tags/2.20.1.tar.gz
$ tar -xzf 2.20.1.tar.gz
$ cd nix-2.20.1
$ nix develop
```
4) Patch `src/nix/main.cc` to comment the section where `nix` disables some network-dependent features because it does not detect an Internet connection:
```
--- main.cc.bak	2024-02-16 03:25:12.441847326 -0500
+++ main.cc	2024-02-16 03:25:38.678846955 -0500
@@ -466,10 +466,10 @@
     experimentalFeatureSettings.require(
         args.command->second->experimentalFeature());
 
-    if (args.useNet && !haveInternet()) {
-        warn("you don't have Internet access; disabling some network-dependent features");
-        args.useNet = false;
-    }
+    //if (args.useNet && !haveInternet()) {
+    //    warn("you don't have Internet access; disabling some network-dependent features");
+    //    args.useNet = false;
+    //}
 
     if (!args.useNet) {
         // FIXME: should check for command line overrides only.
```
5) Execute:
```
$ nix build
```
6) Disconnect the system from the internet except the proxy
7) Try to install a package using the newly built `nix`:
```
$ result/bin/nix profile install nixpkgs#cowsay
<downloads cache / installs from cache>
```
Result:
- Nix relies on cache as intended

Conclusions:
- Nix seems to behave correctly behind a proxy when it does not disable network-depend features
- The function [haveInternet()](https://github.com/NixOS/nix/blob/master/src/nix/main.cc#L36) does not detect whether the system has internet access through a proxy and returns false.
- To solve this issue, the function [haveInternet()](https://github.com/NixOS/nix/blob/master/src/nix/main.cc#L36) should detect whether the system has internet access through a proxy and return true if it does.
