### ISSUE TITLE
'ssh-substituter-hosts' used only if all binary caches are not accessible

### ISSUE THREAD

**Issue by skvl** [NixOS/nix#1003]
In manual it is said:

> This works similar to the binary cache substituter that Nix usually uses, only using SSH instead of HTTP: if a store path P is needed, Nix will first check if it’s available in the Nix store on avalon. If not, it will fall back to using the binary cache substituter, and then to building from source.

But when I try this I could see that it is used last:
- it first checks address from _.nix-defexpr/channels/binary-caches/nixpkgs_;
- then it checks address from _nix.conf_;
- only if both of them are not available then it uses ssh server.

**Comment by jerith666** [comment]
Still seeing this with current `nixos-unstable` @ f0fac3b578.

**Comment by edolstra** [comment]
Closing since `ssh-substituter-hosts` no longer exists.
