### ISSUE TITLE
nix flake update $dir fails but cd $dir; nix flake update works

### ISSUE THREAD

**Issue by LoganBarnett** [NixOS/nix#10041]
**Describe the bug**

If I run `nix flake update $some_dir`, I get a failure from Nix about not being able to update the lock file.  If I run an adapted command (`nix flake update`) from within `$some_dir`, it succeeds.

**Steps To Reproduce**

In my dotfiles repository I have attempted this from its base directory:

``` sh
nix flake update nix
```

Where `nix` is where I keep all of my nix configurations.  `nix` immediately contains a `flake.nix` and `flake.lock`.

I get:

```
error:
       … while updating the lock file of flake 'github:NixOS/nix/60936f28e51bad1cf0a038ebfa24ce9bb97845a9'

       error: cannot write modified lock file of flake 'flake:nix' (use '--no-write-lock-file' to ignore)
```

I can work around this issue by simply changing to the `nix` directory and running `nix flake update`.

```
$ pushd nix          
~/dev/dotfiles/nix ~/dev/dotfiles
$ nix flake update    
warning: Git tree '/Users/logan/dev/dotfiles' is dirty
warning: updating lock file '/Users/logan/dev/dotfiles/nix/flake.lock':
• Updated input 'darwin':
    'github:lnl7/nix-darwin/0dd382b70c351f528561f71a0a7df82c9d2be9a4' (2024-01-03)
  → 'github:lnl7/nix-darwin/0e6857fa1d632637488666c08e7b02c08e3178f8' (2024-02-18)
• Updated input 'flake-utils':
    'github:numtide/flake-utils/4022d587cbbfd70fe950c1e2083a02621806a725' (2023-12-04)
  → 'github:numtide/flake-utils/1ef2e671c3b0c19053962c07dbda38332dcebf26' (2024-01-15)
• Updated input 'home-manager':
    'github:nix-community/home-manager/51e44a13acea71b36245e8bd8c7db53e0a3e61ee' (2024-01-05)
  → 'github:nix-community/home-manager/a54e05bc12d88ff2df941d0dc1183cb5235fa438' (2024-02-18)
• Updated input 'home-manager/nixpkgs':
    'github:NixOS/nixpkgs/b0d36bd0a420ecee3bc916c91886caca87c894e9' (2023-12-30)
  → 'github:NixOS/nixpkgs/5863c27340ba4de8f83e7e3c023b9599c3cb3c80' (2024-02-16)
• Updated input 'nixpkgs':
    'github:nixos/nixpkgs/bd645e8668ec6612439a9ee7e71f7eac4099d4f6' (2024-01-02)
  → 'github:nixos/nixpkgs/b98a4e1746acceb92c509bc496ef3d0e5ad8d4aa' (2024-02-18)
warning: Git tree '/Users/logan/dev/dotfiles' is dirty
```

**Expected behavior**

`nix flake update --help` shows this as the argument form:

```
Synopsis

    nix flake update [option...] flake-url
```

I am assuming my `nix` directory is interpreted as `flake-url` here.  So I expect that the command should succeed regardless of where I run the command from, so long as I address to the `flake.nix`+`flake.lock` directory correctly.

**`nix-env --version` output**

```
$ nix-env --version
nix-env (Nix) 2.18.1
```

**Additional context**

I feel like this has worked at some point in the past, but I have no actual evidence.

There may be some relation here to these tickets, but without knowing the inner mechanisms of lockfile writing, it is hard to say:
1. https://github.com/NixOS/nix/issues/9642
2. https://github.com/NixOS/nix/issues/6050

**Priorities**

Since the workaround is fairly trivial, this is not of high priority to me and unlikely to others.

** Extras **

Thanks for maintaining this wonderful project!

**Comment by thufschmitt** [comment]
The issue is that the `nix` flake url isn't interpreted as a directory, but as the `nix` entry in the flake registry (pointing to `github:NixOS/nix`). If you want the directory, you need to make it unambiguous by using `./nix`

(Note alse that the interface of `nix flake update` has changed in 2.19 (see https://nixos.org/manual/nix/stable/release-notes/rl-2.19), so you'll need `nix flake update --flake ./nix` in the future)

**Comment by LoganBarnett** [comment]
@thufschmitt that makes sense.  Thanks!  I'm happy to close this out.
