### ISSUE TITLE
nix shell shebang support doesn't work

### ISSUE THREAD

**Issue by cdmistman** [NixOS/nix#10053]
**Describe the bug**

using `nix shell` in shebang position as [documented](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix.html?highlight=shebang#shebang-interpreter) doesn't actually work!

**Steps To Reproduce**

1. Create a file `foo.sh` with the following content:
```sh
#!/usr/bin/env nix
#! nix shell nixpkgs#bash nixpkgs#hello nixpkgs#cowsay --command bash

hello | cowsay
```
2. `chmod +x foo.sh`
3. `./foo.sh`
4. Error:
```
error: './foo.sh' is not a recognised command
Try 'nix --help' for more information.
```

**Expected behavior**

Running `foo.sh` should result in the same output as `nix shell nixpkgs#{bash,hello,cowsay} -c bash -c 'hello | cowsay'`

**`nix-env --version` output**
nix-env (Nix) 2.18.1

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by alois31** [comment]
> **`nix-env --version` output**
> nix-env (Nix) 2.18.1

This feature was only introduced in 2.19.

**Comment by tomberek** [comment]
Prior to 2.19 only the previous `nix-shell` shebang worked. Closing as answered.
