### ISSUE TITLE
Building amazon ec2 nixos, linux assertion failed.

### ISSUE THREAD

**Issue by joehenry087** [NixOS/nix#1007]
I have a simple expression that I'm hoping will build NixOs using the amazon config.

os.nix:
`import ./nixpkgs/nixos { system = "x86_64-darwin"; configuration = ./config.nix; }`

config.nix:
`{
  imports = [ <nixpkgs/nixos/modules/virtualisation/amazon-image.nix> ];
  ec2.hvm = true;
}`

Running `nix-build os.nix` gives me:
`error: assertion failed at /Users/joehenry/meal/test/Meals/nixpkgs/pkgs/os-specific/linux/kernel/generic.nix:32:1`

I had run the build command one time previously and I accidentally had the system set to "x86_64-linux". The build started and downloaded all the binaries, then failed telling me that my machine was darwin but system was set to linux. So I changed that and now get the assertion error immediately. Changing the system should make nix re-evaluate the build process though and adapt according though, no?

Side question, what does the system attribute mean when it's used in a place like this, or in mkDerivation?

**Comment by domenkozar** [comment]
Please open an issue at https://github.com/NixOS/nixpkgs/issues/new, which is the correct issue tracker.

**Comment by copumpkin** [comment]
#1008
