### ISSUE TITLE
The sha256 results calculated by nix-prefetch-url and nix are inconsistent

### ISSUE THREAD

**Issue by cathaysia** [NixOS/nix#10127]
The nix-prefetch-url sha256 calculation result for the https://ms-toolsai.gallerycdn.vsassets.io/extensions/ms-toolsai/jupyter/2024.1.2024012502/1706210577096/Microsoft.VisualStudio.Services.VSIXPackage file is inconsistent with the nix calculation result.

```
$ nix-prefetch-url https://ms-toolsai.gallerycdn.vsassets.io/extensions/ms-toolsai/jupyter/2024.1.2024012502/1706210577096/Microsoft.VisualStudio.Services.VSIXPackage
path is '/nix/store/2di7lv008fv7b71zd9p2w94dq3j6lfa9-Microsoft.VisualStudio.Services.VSIXPackage'
11dq86kxm3yqyykrv7xnq8nfim0jx16ni6hj75chbhsynvdjkb8x
```

However, when building, the following error was reported:

```
error: hash mismatch in fixed-output derivation '/nix/store/xbwzr0jq6w1qh38avyzvviwbalfi1nfp-ms-toolsai-jupyter.zip.drv':
         specified: sha256-Ha0p27ZewwVZORKaaE3oEtToLMK2n52n99iP2qdBuIU=
            got:    sha256-q4y8TGEzqd0J6GREvDdXnkL7/xYXOXk+TkvEaX3A40o=
error: 1 dependencies of derivation '/nix/store/11zxdlkwr812z2hh18biwf7bhhgz5cry-vscode-extension-ms-toolsai-jupyter-2024.1.2024012502.drv' failed to build
```

here is the origin issue: https://github.com/nix-community/nix4vscode/issues/18

**Comment by thufschmitt** [comment]
The hash returned by the Nix evaluation is the output of Nixpkgs's fetchurl, which is a separate implementation from Nix's own fetcher (used by `nix-prefetch-url`). And the world being a messy place, it indeed happens that they disagree on some edge-cases[^1].

Can you compare both outputs with `diffoscope` to see what's different between them?

[^1]: And because of that, I'd advise to not use `nix-prefetch-url` to precompute the output hash of `pkgs.fetchurl`. If you need to compute them in advance, you can use a tool like https://github.com/samueldr/nix-universal-prefetch/blob/master/nix-universal-prefetch that actually uses `pkgs.fetchurl`

**Comment by cathaysia** [comment]
I looked at the nix source code and it seems that sha256 is calculated using openssl. I used openssl to calculate the sha256 of the two files respectively, and the results are as follows:

```
SHA2-256(Microsoft.VisualStudio.Services.VSIXPackage)= 1dad29dbb65ec3055939129a684de812d4e82cc2b69f9da7f7d88fdaa741b885
SHA2-256(/nix/store/2di7lv008fv7b71zd9p2w94dq3j6lfa9-Microsoft.VisualStudio.Services.VSIXPackage)= 1dad29dbb65ec3055939129a684de812d4e82cc2b69f9da7f7d88fdaa741b885
```

And the result of `diffoscope Microsoft.VisualStudio.Services.VSIXPackage /nix/store/2di7lv008fv7b71zd9p2w94dq3j6lfa9-Microsoft.VisualStudio.Services.VSIXPackage` is empty.

**Comment by cathaysia** [comment]
note that 1dad29dbb65ec3055939129a684de812d4e82cc2b69f9da7f7d88fdaa741b885(openssl 's result) is eq with 11dq86kxm3yqyykrv7xnq8nfim0jx16ni6hj75chbhsynvdjkb8x(nix-prefetch-url's result)

**Comment by thufschmitt** [comment]
That seems to be an issue in nix4vscode or the VSCode extension registry (see https://github.com/nix-community/nix4vscode/issues/18#issuecomment-1974827527), I'll close this issue in favor of https://github.com/nix-community/nix4vscode/issues/18.

@cathaysia feel free to reopen if there's something more I've been missing.
