### ISSUE TITLE
cannot run nuitka under nix-shell

### ISSUE THREAD

**Issue by geck333** [NixOS/nix#1012]
I got a problem when tried to use [nuitka python compiler](http://www.nuitka.net)  under nix-shell.
Here is section from shell.nix:
``` 
 nuitka = pkgs.python27Packages.buildPythonApplication rec{
      version = "0.5.20";
      name = "Nuitka-${version}";
      src = pkgs.fetchurl {
        url = "https://pypi.python.org/packages/source/N/Nuitka/${name}.tar.gz";
        md5 = "b79beab5943d2b644b97e1439c873ecc";
        };
      doCheck = false;
  };
```

When i enter nix-shell and type "nuitka" in console - i see nuitka's help message, everything seems to be ok. 
But when i try to compile any file, i see this error:
> [nix-shell:~/projects/test_project]$ nuitka test.py
> /nix/store/13rkxv7rzmy1bkr1f6wsxiy2njxybgga-python-2.7.11/bin/python2.7: can't open file 'nuitka': [Errno 2] No such file or directory

Here is content of wrapper file generated by nix:
> #! /nix/store/4y952y95lnyx727rsj70lx9pf3039syn-bash-4.3-p42/bin/bash -e
export PYTHONPATH=/nix/store/h275p7x4r0l8q1ifv004pba7diblqs4l-Nuitka-0.5.20/lib/python2.7/site-packages:/nix/store/13rkxv7rzmy1bkr1f6wsxiy2njxybgga-python-2.7.11/lib/python2.7/site-packages:/nix/store/n0iqvmggn6is24w3pgp0gi6mfqrxd901-python2.7-setuptools-19.4/lib/python2.7/site-packages${PYTHONPATH:+':'}$PYTHONPATH
export PATH=/nix/store/h275p7x4r0l8q1ifv004pba7diblqs4l-Nuitka-0.5.20/bin:/nix/store/13rkxv7rzmy1bkr1f6wsxiy2njxybgga-python-2.7.11/bin:/nix/store/n0iqvmggn6is24w3pgp0gi6mfqrxd901-python2.7-setuptools-19.4/bin:/nix/store/h275p7x4r0l8q1ifv004pba7diblqs4l-Nuitka-0.5.20/bin${PATH:+':'}$PATH
exec -a "$0" /nix/store/h275p7x4r0l8q1ifv004pba7diblqs4l-Nuitka-0.5.20/bin/.nuitka-wrapped "${extraFlagsArray[@]}" "$@"

Nuitka's setup.py can be found [here](https://gitlab.com/kayhayen/Nuitka/blob/develop/setup.py)

**Comment by domenkozar** [comment]
This issue belongs to https://github.com/NixOS/nixpkgs

But in short - it seems to be executing some binary that's not available. Best to use strace or grep around for subprocess usage what's being invoked.

**Comment by copumpkin** [comment]
@domenkozar #1008 😄

**Comment by geck333** [comment]
Sorry guys, my fault!
Thanks for pointing to right repository :)

**Comment by copumpkin** [comment]
Not your fault! I don't really expect newcomers to understand the distinction between nixpkgs and nix, which is why I created that other ticket 😄
