### ISSUE TITLE
Test failure on macOS on hydra

### ISSUE THREAD

**Issue by thufschmitt** [NixOS/nix#10163]
**Describe the bug**

The hydra macOS jobs are failing with `objc[91749]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called`.
This seems to be non-deterministic.

**Steps To Reproduce**

https://hydra.nixos.org/build/252305874/nixlog/1

**Expected behavior**

Have it build

**`nix-env --version` output**

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by thufschmitt** [comment]
Seems to be fixed by https://github.com/NixOS/nix/pull/9900/files#diff-16cddcd6b987528aee0e3d6930f04e9413e1e349c66d385fdc93290af456800dR356-R360 in https://github.com/NixOS/nix/pull/9900 .

Will cherry-pick that

**Comment by roberth** [comment]
> Will cherry-pick that

https://github.com/NixOS/nix/pull/10164
