### ISSUE TITLE
`nix copy` doesn't substitute from binary caches on 2.20 anymore

### ISSUE THREAD

**Issue by Ma27** [NixOS/nix#10182]
**Describe the bug**

When I push a closure to a remote system using `nix-copy --to ssh-ng://root@host /nix/store/...`, Nix 2.19 correctly substituted everything from a binary cache where possible, but Nix 2.20 doesn't.

This is probably related to `builders-use-substitutes`, the `nix.conf` files are added below.

This is a problem when using push-based deployment systems because now you'd have to upload the entire closure from your local network.

**Steps To Reproduce**

1. `nix-2.20 copy --to ssh-ng://root@host $(nix-build -A hello)`

**Expected behavior**

I'd expect a substitution from a remote system to happen.

**`nix-env --version` output**

* Local Client: `nix-env (Nix) 2.20.4`
* Local Daemon: 2.19.3
* Remote Daemon: 2.19.3

**Additional context**

<details><summary>local `nix.conf`</summary>

```
allow-import-from-derivation = false
allowed-uris = github: gitlab: git+https://git.mbosch.me git+https://git.sr.ht https://github.com git+https://github.com https://git.sr.ht
allowed-users = *
auto-optimise-store = false
builders = @/etc/nix/builder-configs/darwin-main;@/etc/nix/builder-configs/roflmayr
builders-use-substitutes = true
cores = 4
experimental-features = nix-command flakes
extra-allowed-users = nixseparatedebuginfod
extra-sandbox-paths = 
log-lines = 0
max-jobs = auto
require-sigs = true
sandbox = true
sandbox-fallback = false
substituters = https://cache.nixos.org/ https://hydra.ist.nicht-so.sexy
system-features = nixos-test benchmark big-parallel kvm
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.ist.nicht-so.sexy-1:E+AwZnzYPdycs1IkHrlG0eJeBleAW/ukX10lcjTc2RQ=
trusted-substituters = 
trusted-users = root @wheel
use-xdg-base-directories = true
keep-derivations = true
keep-outputs = true
system-features = big-parallel builtin nixos-test local kvm benchmark
```

</details>

<details><summary>remote `nix.conf`</summary>

```
allow-import-from-derivation = false
allowed-uris = github: gitlab: git+https://git.mbosch.me git+https://git.sr.ht https://github.com git+https://github.com https://git.sr.ht
allowed-users = *
auto-optimise-store = false
builders = 
builders-use-substitutes = true
cores = 0
experimental-features = nix-command flakes
extra-sandbox-paths = 
log-lines = 0
max-jobs = auto
require-sigs = true
sandbox = true
sandbox-fallback = false
substituters = https://cache.nixos.org/ https://hydra.ist.nicht-so.sexy
system-features = nixos-test benchmark big-parallel kvm
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.ist.nicht-so.sexy-1:E+AwZnzYPdycs1IkHrlG0eJeBleAW/ukX10lcjTc2RQ=
trusted-substituters = 
trusted-users = root @wheel
```

</details>

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by thufschmitt** [comment]
That's likely due to https://github.com/NixOS/nix/pull/9600 (which didn't add a release note, sorry about that :/ )

You need to pass `--substitute-on-destination` to get that behaviour

**Comment by Ma27** [comment]
cc @thufschmitt would you mind confirming my analysis here? If that's correct, I'd update the 2.20 release notes (stable Nix from nixpkgs is still on 2.18, so for others the release notes are probably still interesting) and we can close this issue :)

**Comment by thufschmitt** [comment]
@Ma27 yes, that's exact.

The intention is that `builder-use-substitutes` works for remote building and `--substitute-on-destination` for `nix copy`

**Comment by Ma27** [comment]
@thufschmitt opened #10449 which adds this to the release notes :)
