### ISSUE TITLE
`nix copy --from file://` requires unexpected flake in cwd

### ISSUE THREAD

**Issue by tmplt** [NixOS/nix#10217]
**Describe the bug**

`nix copy --from file://` on a directory created by `nix copy --to file://` fails because it cannot find a `flake.nix` in the current working directory, or above.

**Steps To Reproduce**

```sh
$ pwd
/home/tmplt
$ nix copy --to file:///tmp/nix-copy-hello nixpkgs#hello
$ nix copy --from file:///tmp/nix-copy-hello 
path '/home/tmplt' does not contain a 'flake.nix', searching up
error: could not find a flake.nix file
```

**Expected behavior**

I expect the `nix copy --from` command to import the binary cache to the system's (but effectively being noop because the derivation already exists there?).

**`nix-env --version` output**

```
nix-env (Nix) 2.18.1
```

**Additional context**

I have `nix-command flakes` enabled globally, but overriding using `--experimental-features nix-command` yields the same error.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by thufschmitt** [comment]
`nix copy` copies the store paths specified on the command-line (defaulting to the flake in the current directory like the rest of the command-line).

If you want to copy the whole store, you can use [`--all`](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-copy#opt-all) (I hope, if it doesn't work, that is a bug).

Do you think the [description](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-copy#description) in the manual needs to be altered to make this more explicit? If so feel free to open a PR to fix it

**Comment by tmplt** [comment]
Thanks, I wasn't aware of `--all`. It's a bit too hidden and abstracted in my opinion: https://github.com/NixOS/nix/pull/10227.
