### ISSUE TITLE
nix-prefetch-url seems to uncompress archive if `content-encode: gzip` is set

### ISSUE THREAD

**Issue by a-n-n-a-l-e-e** [NixOS/nix#10254]
**Describe the bug**

nix-prefetch-url is downloading and uncompresing the file sometimes. this appears to happen if the download is uses gzip content encoding. when `content-encode: gzip` is not set (and thus the download not doubly compressed) nix-prefetch-url works as expected.

**Steps To Reproduce**

```sh
nix-prefetch-url --print-path https://releases.warp.dev/stable/v0.2024.03.12.08.02.stable_01/warp-terminal-v0.2024.03.12.08.02.stable_01-1-x86_64.pkg.tar.zst
```
```console
0gwji3934p4c0qmfyirjwyg7dy1rhdlyrvj2x2c2xwllpxd89pw9
/nix/store/biisn805rah1s25smdzpcd4hxqm0vpw3-warp-terminal-v0.2024.03.12.08.02.stable_01-1-x86_64.pkg.tar.zst
$ file /nix/store/biisn805rah1s25smdzpcd4hxqm0vpw3-warp-terminal-v0.2024.03.12.08.02.stable_01-1-x86_64.pkg.tar.zst
/nix/store/biisn805rah1s25smdzpcd4hxqm0vpw3-warp-terminal-v0.2024.03.12.08.02.stable_01-1-x86_64.pkg.tar.zst: POSIX tar archive
```

expect that the file is zstd compressed.

**Expected behavior**

expect that the downloaded file is compressed and the hash is calculated against the compressed file.

**Additional context**
https://github.com/NixOS/nixpkgs/issues/295553#issuecomment-1999896284

tried versions `nix-prefetch-url (Nix) 2.19.3` and `nix-prefetch-url (Nix) 2.17.1` and get same results. also happens on the setup used by r-ryantm.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by thufschmitt** [comment]
Should be fixed by https://github.com/NixOS/nix/pull/10341. Feel free to reopen if it's not the case
