### ISSUE TITLE
Substitution does not work for binary caches behind reverse proxies with compression

### ISSUE THREAD

**Issue by xokdvium** [NixOS/nix#10275]
**Describe the bug**

When a self-hosted binary cache is put behind a reverse proxy with some compression enabled. 
E.g. `Encoding-Type: gzip` in [nginx](https://docs.nginx.com/nginx/admin-guide/web-server/compression/) and [traefik](https://doc.traefik.io/traefik/middlewares/http/compress/). With such setups nix fails to substitute a path with the following error:

```
error: input compression not recognized
```

**Steps To Reproduce**

1. Spin up a binary cache
2. Put it behind a reverse proxy with compression
3. Observe substitution failures for all paths

**Expected behavior**

Nix substitution succeeds for all paths present in the cache.  

**Additional context**

I've debugged this issue and I'm quite certain I understand what is going on. Let's assume the binary cache 
uses `zstd`.

1. All filters for libarchive are enabled in `TarArchive` in any case:

https://github.com/NixOS/nix/blob/346f92aa4c243ac369048a4b84680ed9940013d8/src/libutil/tarfile.cc#L45-L55

2. `makeDecompressionSink` is called both for fetching via curl and when copying to the store. 

https://github.com/NixOS/nix/blob/346f92aa4c243ac369048a4b84680ed9940013d8/src/libutil/compression.cc#L202-L213

3. When the reverse proxy adds the `Encoding-Type: gzip` header `makeDecompressionSink` is called with `method = "gzip"` here

https://github.com/NixOS/nix/blob/346f92aa4c243ac369048a4b84680ed9940013d8/src/libstore/filetransfer.cc#L163

But looking at 1 & 2 it becomes apparent that because all filters are enabled the compressed gzip stream (which is a NAR) gets 
completely decompressed (applying the filter to the actual compressed NAR). Then when `makeDecompressionSink` is called once again to copy to the store, the NAR is uncompressed. But the narinfo reports the `method` to be e.g. `ztd`. Then the exception gets thrown from here because `Source` is not in fact a `ztd` compressed file. 

https://github.com/NixOS/nix/blob/346f92aa4c243ac369048a4b84680ed9940013d8/src/libstore/binary-cache-store.cc#L404

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by thufschmitt** [comment]
(I didn't have time to read the whole issue yet, apologies if this is nonsense, but: ) could that have the same root issue as https://github.com/NixOS/nix/issues/10254 ? That looks fairly similar in the symptoms.

/cc @a-n-n-a-l-e-e

**Comment by xokdvium** [comment]
Indeed, that seems to be the exact same issue. I've spent some time debugging nix under gdb, so I'm quite sure the root cause is what I've described in this issue. I suppose `nix-prefetch-url` works in the same way: i.e. fetch via curl and then copy to store via two `Source` created with `makeDecompressionSink`. Feel free to mark this as duplicate
