### ISSUE TITLE
Simple tool/command to figure out if something is in the binary cache

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#1028]
Currently I don't think I have a clean way to figure out if something I'm running would cause a mass rebuild on another system, because I might already have it in my store. It would be really nice to hand some Nix subcommand an expression, a set of binary caches, and have it run the queries to see what's available for substitution and what isn't, regardless of what's in my local store.

**Comment by edolstra** [comment]
`nix-build --dry-run` shows what will be downloaded and what will be built.

**Comment by copumpkin** [comment]
@edolstra but that's paying attention to the local store on the machine running it, right? It won't help me understand if my stuff has been built by Hydra yet or whether I just built it a few days ago and it's still in my store, but I'll waste five hours recompiling it if I push to another machine.

**Comment by shlevy** [comment]
@edolstra shouldn't `NIX_REMOTE="https://cache.nixos.org" nix-store --check-validity` do it? It doesn't currently though...

**Comment by shlevy** [comment]
(obviously with the new binary cache store stuff)

**Comment by shlevy** [comment]
That is, it doesn't fail when it should

**Comment by cleverca22** [comment]
@copumpkin you can also use nix-serve to turn the 1st machine into a binary cache for the 2nd, then the difference you mentioned will be gone

**Comment by copumpkin** [comment]
@cleverca22 I know I can, but in my desired use case they're in different environments and can't speak to each other. I basically want to make sure I don't build things in production, and that production machines will be able to get to the desired state (almost) entirely from the binary cache.

**Comment by cleverca22** [comment]
```
[root@amd-nixos:~]# nix-store --query --deriver /nix/store/jmk29gdxl1i6j1ancjyysiif38whpyid-linux-config-4.7
/nix/store/7qnx8mbgmfk3gyq302137ivs5psahcn9-linux-config-4.7.drv

[root@amd-nixos:~]# ls /nix/var/log/nix/drvs/7q/nx8mbgmfk3gyq302137ivs5psahcn9-linux-config-4.7.drv.bz2
/nix/var/log/nix/drvs/7q/nx8mbgmfk3gyq302137ivs5psahcn9-linux-config-4.7.drv.bz2
```

these log files only exist for things built locally, it may be possible to make a script that iterates over $(nix-store -qR result) and then names off the closure size of anything with a log

**Comment by edolstra** [comment]
Closing, `nix path-info --store ...` does this.
