### ISSUE TITLE
Provide more nix language examples

### ISSUE THREAD

**Issue by Hyperpolarized** [NixOS/nix#10283]
## Problem

Not enough nix language examples for people starting out with nix or vague examples

## Proposal

- [ ] Add more nix language examples that utilize what the example is showing on https://nixos.org/manual/nix/unstable/language/

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open documentation issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/src
[open documentation issues and pull requests]: https://github.com/NixOS/nix/labels/documentation

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by roberth** [comment]
@Hyperpolarized would this help?
- #10307

It's previously been decided by the documentation team that the manuals should only contain reference material, and learning materials go to `nix.dev`. I'm not 100% convinced, but it's what I have to work with.
