### ISSUE TITLE
[chore] Allow deletion of backport branches

### ISSUE THREAD

**Issue by roberth** [NixOS/nix#10302]
**Describe the bug**

I can't delete the branches that are cluttering the list of refs that would normally show relevant tags that include a commit like https://github.com/NixOS/nix/commit/78fd62139714bc68a682572e303b7e3c52f988f2

This makes it harder than necessary to find out which releases a backport is part of.

Probably a rule for backports in https://github.com/NixOS/nix/settings/branches prevents it.
Open it and tick **Allow deletions**.

**Steps To Reproduce**

1. Visit the commit and see a bunch of useless backport branches instead of tags
2. Have push access but not admin access
3. Can't delete those branches

**Expected behavior**

Branches are deleted automatically and/or I can clean them up.

**`nix-env --version` output**

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by edolstra** [comment]
I've tightened the branch protection rule to `[0-9]*.[0-9]*-maintenance` so backport branches are not longer protected and can be deleted.
