### ISSUE TITLE
macOS .DS_Store files causing updates of nixpkgs to fail

### ISSUE THREAD

**Issue by axman6** [NixOS/nix#10315]
When running pretty much any Nix command, for example `nix run github:nixos/nixpkgs#hello`, I get the following error which seems to be caused by Nix failing to delete directories which contain a `.DS_Store` file

```
error (ignored): error: cannot unlink '/private/tmp/nix-69835-0/nixpkgs-9c48b89b70a53ba783fc0549abb8c322ed2d3298/pkgs/development': Directory not empty
error:
       … while fetching the input 'github:nixos/nixpkgs'

       error: tarball 'https://github.com/nixos/nixpkgs/archive/9c48b89b70a53ba783fc0549abb8c322ed2d3298.tar.gz' contains an unexpected number of top-level files
```

```shell
$ ll -a /private/tmp/nix-69835-0/nixpkgs-9c48b89b70a53ba783fc0549abb8c322ed2d3298/pkgs/development
.rw-r--r--@ 6.1k <REMOVED> 25 Mar 11:17 .DS_Store
```
Removing the .DS_Store file doesn't help as each invocation of Nix uses a new `/private/tmp` directory. This is completely preventing me from using anything related to nix on my machine at the moment.

**Expected behavior**

Nix command should not fail to clean up after themselves on macOS.

**`nix-env --version` output**

```shell
$ nix-env --version 
nix-env (Nix) 2.20.5
$ uname -a    
Darwin <REMOVED> 23.4.0 Darwin Kernel Version 23.4.0: Wed Feb 21 21:44:54 PST 2024; root:xnu-10063.101.15~2/RELEASE_ARM64_T6031 arm64
# Which is macOS Sonoma 14.4
```

**Additional context**

I have seen similar things happening with other tools (like the Haskell ghcup installer sometimes fails to remove old GHC versions for similar reasons).

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by edolstra** [comment]
This is very strange because that Nixpkgs revision does not contain a `.DS_Store` file.

**Comment by axman6** [comment]
Yeah it looks like Finder was adding them nearly immediately after being extracted, which is quite odd. It seems to have stopped that for unknown reasons now, so who knows what's going on. I'll close this for now as I can no longer reproduce it.

**Comment by Gaelan** [comment]
I've been intermittently having this issue for quite a while now.

**Comment by Gaelan** [comment]
Aha! I had a Finder window open to `/tmp`; closing the Finder window allowed `nix shell` to start working.
