### ISSUE TITLE
nix install

### ISSUE THREAD

**Issue by tsubasa-miyazaki** [NixOS/nix#10348]
## Platform

- [ ] Linux: 
- [ ] macOS
- [ ] WSL

## Output

<details><summary>Output</summary>

```log

<!-- paste console output here and remove this comment -->

```

</details>

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by abathur** [comment]
There's no information here to help you with. Happy to reopen if you include an install log.
