### ISSUE TITLE
Nix Flake vs conventional Nix Build discrapancy?

### ISSUE THREAD

**Issue by matejc** [NixOS/nix#10357]
I had a strange issue with current nixos-unstable (nixpkgs commit: 2726f127c15a4cc9810843b96cad73c7eb39e443)

I ran nixos rebuild switch from flake and the fprintd failed with a timeout issue (this one https://github.com/NixOS/nixpkgs/issues/299111#issuecomment-2027383867 ), I went to debug the issue and on same nixpkgs revision I ran nix build (without the flake) and the build succeeded. After that surprise, I ran nixos rebuild switch from flake again and it was a success.

Now thinking about it it was a timeout issue, so, maybe is the case that the nixos rebuild was building several derivations in parallel, and my computer might take too long to run the tests of fprintd, thats why it could timeout. But the timeout happened at 30seconds. And when building only fprind with nix build (without a flake) the build+tests took less than 50 seconds all together.

And I am not the only one: https://github.com/NixOS/nixpkgs/pull/298491#issuecomment-2024563837

**Comment by roberth** [comment]
Did nix evaluate to a different derivation between `nix-build` and flakes?

If not, it is probably just a flaky test in that fprint derivation, as there'd be basically no mechanism for `nix-daemon` to behave differently.

**Comment by matejc** [comment]
Yeah, I came to a similar conclusion. I guess we can close this one
