### ISSUE TITLE
Regression: Edit command broken without --impure

### ISSUE THREAD

**Issue by tobim** [NixOS/nix#10369]
**Describe the bug**

On Nix 2.21 `nix edit` returns an unhelpful error message when it should just work. It does work with the `--impure` flag, but I don't see a reason why adding that to the invocation should be necessary when the path to the package definition is derived correctly in printed as part of the error.

The problem does not exist in Nix 2.18.

**Steps To Reproduce**

```fish
> nix edit nixpkgs#nix
error: cannot open '/nix/store/k5l01g2zwhysjyl5zjvg5zxnj0lyxpp1-source/pkgs/tools/package-management/nix/default.nix' in an editor because it has no physical path
```

**`nix-env --version` output**

```
nix-env (Nix) 2.21.0
```

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by manveru** [comment]
same as https://github.com/NixOS/nix/issues/9652

**Comment by tobim** [comment]
Looks like I didn't use the right keywords when I searched for existing issues.

Closing as duplicate.
