### ISSUE TITLE
warn about unknown flake url paramaters

### ISSUE THREAD

**Issue by lolbinarycat** [NixOS/nix#10370]
**Is your feature request related to a problem? Please describe.**
recently i made a typo and accidentally tried to install a package from `github:nixos/nixpkgs?revnixpkgs-unstable` (notice the lack of `=`), and nix just built the whole thing successfully (i assume using the `master` branch instead)

**Describe the solution you'd like**
a warning should be displayed if there are unknown keys in a url-style flake reference (eg. "warning: unknown flake attribute XXX, check your spelling or update nix")

at least for `github:` or `flake:` urls, i assume for `git+http` url unrecognized paramaters are just passed to the http server.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by bryanhonof** [comment]
Are there currently store types that allow for a query part without it being a key value pair?
I don't recall ever encountering one where the equal sing was missing, and if it was used as some sort of flag, it's more often than not `key=val`.

If the above is the case, maybe we should throw an error if someone tries to use a store URL that includes the key part in the query, but doesn't assign a value.

**Comment by bryanhonof** [comment]
It looks like the type is even a map of string to string.

https://github.com/NixOS/nix/blob/af26fe39344faff70e009d980820b8667c319cb2/src/libutil/url.cc#L76
