### ISSUE TITLE
nix build -vvv doesn't show info that nix-build does

### ISSUE THREAD

**Issue by lolbinarycat** [NixOS/nix#10371]
**Describe the bug**

even at the maximum verbosity setting, nix3 refuses to persistanly show the build log

**Steps To Reproduce**
`nix build -vvv --impure --expr '(import <nixpkgs> {}).runCommandLocal "test1" {} "echo 1234"'`

**Expected behavior**

`1234` should appear somewhere in the terminal backscroll.

**`nix-env --version` output**
nix-env (Nix) 2.18.2

**Additional context**
this is a problem because `nix log` sometimes is unable to find the build log (i experienced this when trying to investigate the build failure of kstars)

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by a-kenji** [comment]
Does that also happen, if you tell `nix build` to show the build log?

```
nix build -Lv
```

or

```
nix build  --print-build-logs 
```

**Comment by lolbinarycat** [comment]
no, that fixes it.
