### ISSUE TITLE
Test `include` and `!include` config file syntax

### ISSUE THREAD

**Issue by Ericson2314** [NixOS/nix#10383]
basic idea:

```bash
NIX_CONFIG='system = foobarbaz' nix show-config --json | jq -e '.system.value == "foobar
baz"'
```
 in `tests/functional/config.sh` but using `include` and `!include`

_Originally posted by @Ericson2314 in https://github.com/NixOS/nix/issues/10358#issuecomment-2027568942_

**Comment by SkamDart** [comment]
Hey @Ericson2314, I looked at this in https://github.com/NixOS/nix/pull/10386
