### ISSUE TITLE
nix-mode: org-mode fontification error after #870 changes

### ISSUE THREAD

**Issue by rzetterberg** [NixOS/nix#1040]
# Issue description

After recent changes in #870 when creating a [code block](http://orgmode.org/manual/Structure-of-code-blocks.html#Structure-of-code-blocks) in `org-mode` with the language set to `nix` and fontification enabled you get the error `org-mode fontification error`.

Note that:
- No other code block languages get this error
- I don't have this problem if I revert to the commit before #870
- Syntax highlight in `nix-mode` works as expected
# Steps to reproduce

Download the specific nix-mode.el file:

``` bash
mkdir emacs-test
cd emacs-test
wget https://raw.githubusercontent.com/NixOS/nix/a828fe5b46c926f943f38040e3b59858e2426e12/misc/emacs/nix-mode.el
```

Create a new org-file:

``` bash
cat << EOF > ./shell-example.org
* Shell example

#+BEGIN_SRC nix
{ system ? builtins.currentSystem }:

let
  pkgs = import <nixpkgs> { inherit system; };
in
  pkgs.callPackage ./default.nix {
    inherit (pkgs);
  }
#+END_SRC
EOF
```

Open emacs without a site file:

``` bash
emacs -Q
```

Paste the following in the scratch buffer:

``` emacs-lisp
(load-file "./nix-mode.el")
(require 'nix-mode)
(setq org-src-fontify-natively t)
(find-file "./shell-example.org")
```

Evaluate the buffer `M-x eval-buffer`, open messages `C-x b *Messages*`.

You should see a line that says `org-mode fontification error`.
# Technical details
- System: NixOS unstable
- Emacs version: 24.5.2

I have tested this with both the built in `org-mode`: `8.2.10 (release_8.2.10 @ /nix/store/...-emacs-24.5/share/emacs/24.5/lisp/org/)` .
And a later version that comes with `org-plus-contrib`: `8.3.5 (8.3.5-1-g589e96-elpaplus @ ~/.emacs.d/elpa/org-plus-contrib-20160822/)`.

I searched the source code of `org-plus-contrib` to try and find where the 
error is triggered. It seems to be triggered in the function 
`org-fontify-meta-lines-and-blocks` on line _5893_.

That function seems to be a wrapper for `org-fontify-meta-lines-and-blocks-1` 
that just catches all errors and outputs `org-mode fontification error`:

``` emacs-lisp
(defun org-fontify-meta-lines-and-blocks (limit)
  (condition-case nil
      (org-fontify-meta-lines-and-blocks-1 limit)
    (error (message "org-mode fontification error"))))
```

To try to get a better error message I changed the function to:

``` emacs-lisp
 (defun org-fontify-meta-lines-and-blocks (limit)
   (org-fontify-meta-lines-and-blocks-1 limit))
```

After doing this I got this error:

```
Error during redisplay: (jit-lock-function 3201) signaled (end-of-buffer)
```

[jit-lock-function](https://github.com/jwiegley/emacs-release/blob/adfd5933358fdf6715423dee8169eb3cd7d982db/lisp/jit-lock.el#L335) seems to be a function shipped with emacs in `jit-lock.el`.

**Comment by matthewbauer** [comment]
Can you try out [nix-mode](https://github.com/matthewbauer/nix-mode)? I think this is fixed in that. The diff is here:

https://github.com/matthewbauer/nix-mode/commit/0624820fd32915539a17bf012cb7f1a789268a5b

**Comment by rzetterberg** [comment]
@matthewbauer, I can confirm that it works. No errors in the `*Messages*` buffer and the syntax highlighting works as expected:

![Screenshot](http://i.imgur.com/8oGakyu.png)

Nice one :+1:

**Comment by rzetterberg** [comment]
# Testing harness

Since there are now two new PRs open in regards to syntax highlighting in
`nix-mode` I decided to create a test script that can be used to check that:

- `nix-mode` buffers has correct syntax highlighting
- `org-mode` buffers with nix source blocks has correct syntax highlighting
- no emacs errors have been printed
- we are not using invalid nix expressions

See *Test script* for the actual source.

## How it works

The script creates a temporary folder where it puts 2 test files: `example.nix`
that contains a valid nix expression and `example.org` that contains a source
block with the whole contents of `example.nix` inside it.

Then `nix-instantiate` is used to parse `example.nix` to make sure that the
test file is always valid.

It then downloads the raw `nix-mode.el` file and puts it in the temporary folder.

After that it creates a `init.el` file that emacs is started with. The
`init.el` file contains code that loads the downloaded `nix-mode.el` file, opens
up both test files in side-by-side split and then opens up the message buffer in
a split below the test files.

A keybinding to the `escape` key is then added that when pressed takes a
screenshot of the window, saves it as `{PR-NUMBER}.png` in the temporary
directory and then quits emacs.

Using this script we can quickly test different `nix-mode.el` changes and get
meaningful results for comparison.

## Example usage

I wanted to test the PRs #1119 and #1120, so I first ran:

```
$ test-nix-mode.sh 1119 https://raw.githubusercontent.com/ttuegel/nix/dda68ffba6a9c3a11d267a0330b9ec7ea9c7d10c/misc/emacs/nix-mode.el
```

And waited for emacs to start and load the files, I then pressed `escape`. Emacs
took the screenshot and then quit.

Here's the output I got from the script:

```
$ test-nix-mode.sh 1119 https://raw.githubusercontent.com/ttuegel/nix/dda68ffba6a9c3a11d267a0330b9ec7ea9c7d10c/misc/emacs/nix-mode.el
>> Starting nix-mode-test for #1120

-- org version:   8.2.10
-- emacs version: 24.5

>> Nix test file parsing: OK
>> Starting emacs
>> Test complete, screenshot created at: /tmp/nix-mode-test/1119.png
```

And here is the actual screenshot for PR #1119 (cc @ttuegel):

![PR #1119 screenshot](http://i.imgur.com/zgyiFuh.png)

Doing the same procedure for the PR #1120 gave me this result:

```
$ test-nix-mode.sh 1120 https://raw.githubusercontent.com/matthewbauer/nix/f3235cd21a8a9530512d45affe574df33443a17a/misc/emacs/nix-mode.el
>> Starting nix-mode-test for #1120

-- org version:   8.2.10
-- emacs version: 24.5

>> Nix test file parsing: OK
>> Starting emacs
>> Test complete, screenshot created at: /tmp/nix-mode-test/1120.png

```

And here is the actual screenshot for PR #1120 (cc @matthewbauer):

![PR #1120 screenshot](http://i.imgur.com/nvsof3H.png)

## Test script

Here's the test script implementation that I created. Note that I'm using
`scrot` to take the screenshot. So if you are not on Linux or use another
program to take the screenshot, you can replace the command in the `init.el`
file.

**test-nix-mode.sh**
```
#======================================================================
# Arguments checking

function usage {
    echo "$0 PR-NUMBER URL-TO-NIX-MODE"
}

if [[ -z $1 ]]; then
    echo "PR reference number not given"
    usage
    exit 1
fi

if [[ -z $2 ]]; then
    echo "URL to nix-mode.el not given"
    usage
    exit 1
fi

#======================================================================
# Constants

PR_ID=$1
NIX_MODE_URL=$2

CURR_DIR=`pwd`
TEST_DIR="/tmp/nix-mode-test"
INIT_FILE="$TEST_DIR/init.el"
NIX_TEST_FILE="$TEST_DIR/example.nix"
ORG_TEST_FILE="$TEST_DIR/example.org"
NIX_MODE_FILE="$TEST_DIR/nix-mode.el"

SCREENSHOT_PATH="$TEST_DIR/$PR_ID.png"

#======================================================================
# Test environment creation

rm -rf $TEST_DIR
mkdir $TEST_DIR

cat << \EOF > $NIX_TEST_FILE
{ stdenv, makeWrapper, emacs, texlive }:
let
  texlive_set = texlive.combine {
    inherit (texlive)
    scheme-tetex titlesec listings;
  };
in
  stdenv.mkDerivation rec {
    name         = "wrapped-emacs-${version}";
    version      = "1.0.0";
    src          = ./src;
    dontBuild    = true;
    buildInputs  = [ makeWrapper emacs texlive_set ];
    installPhase = ''
      runHook preInstall

      mkdir -p "$prefix"
      installTargets=${installTargets:-install}

      mkdir -p $out/{share,bin}
      cp ${src}/* $out/bin/

      wrapProgram $out/bin/wrapped-emacs.sh \
        --suffix PATH : "${emacs}/bin" \
        --suffix PATH : "${texlive_set}/bin"
    '';
    meta = {
      description = "Example package with different syntax parts";
      platforms   = stdenv.lib.platforms.linux;
    };
  }
EOF

echo -e "#+STARTUP: showeverything\n\n* Nix example\n\n#+BEGIN_SRC nix" > $ORG_TEST_FILE
cat $NIX_TEST_FILE >> $ORG_TEST_FILE
echo -e "#+END_SRC" >> $ORG_TEST_FILE

cat << EOF > $INIT_FILE
(message ">> Testing nix-mode in PR #${PR_ID}")
(load-file "${NIX_MODE_FILE}")
(require 'nix-mode)

(setq org-src-fontify-natively t)
(find-file "${ORG_TEST_FILE}")

(split-window-below)
(other-window 1)
(switch-to-buffer "*Messages*")

(other-window 1)
(split-window-right)
(other-window 1)
(find-file "${NIX_TEST_FILE}")

(global-set-key [escape]
  (lambda ()
    (interactive)
    (shell-command "scrot --focused ${SCREENSHOT_PATH}")
    (save-buffers-kill-terminal)))
EOF

#======================================================================
# Test execution

echo -e ">> Starting nix-mode-test for #$PR_ID\n"
emacs --quick --batch --eval="(message (format \"-- org version:   %s\" (org-version)))"
emacs --quick --batch --eval="(message (format \"-- emacs version: %d.%d\" emacs-major-version emacs-minor-version))"

printf "\n>> Nix test file parsing: "
nix-instantiate --parse $NIX_TEST_FILE > /dev/null

res=$?
if [[ $res != 0 ]]; then
    printf "FAIL\n"
    exit $res
else
    printf "OK\n"
fi

echo ">> Starting emacs"

rm -f $NIX_MODE_FILE
wget -q $NIX_MODE_URL -O $NIX_MODE_FILE

res=$?
if [[ $res != 0 ]]; then
    echo "Failed to download raw nix-mode.el file"
    exit $res
fi

emacs --quick --load $INIT_FILE > /dev/null 2>&1

echo ">> Test complete, screenshot created at: $SCREENSHOT_PATH"
```
