### ISSUE TITLE
nix-shell lock file

### ISSUE THREAD

**Issue by mpscholten** [NixOS/nix#1041]
Currently when distributing some code with a `shell.nix` for having an easy to use and reproducable development environment "works on my machine" can still happen. Usually this is caused by having different nixpkgs versions.

To fix this one would have to lock the nixpkgs version to a specific release, `NIX_PATH="nixpkgs=https://nixos.org/releases/nixpkgs/some_release" nix-shell`. As that's a bit long to type it would be very cool to have some kind of file which is read by default to specify this. 

E.g. having a file `nix_path` inside the project directory with the content `nixpkgs=https://nixos.org/releases/nixpkgs/some_release"` and then running `nix-shell` inside the project could be equivalent to `NIX_PATH="nixpkgs=https://nixos.org/releases/nixpkgs/some_release" nix-shell`.

Then projects can be distributed with a `shell.nix` and a `nix_path` file to avoid "works on my machine".

Let me know what you think about this idea :)

**Comment by edolstra** [comment]
This is already possible using just `shell.nix`:
```
with import (fetchTarball https://github.com/NixOS/nixpkgs/archive/8a3eea054838b55aca962c3fbde9c83c102b8bf2.tar.gz) {};

stdenv.mkDerivation {
  name = "my-package";
  buildInputs = [ hello ];
}
```

**Comment by mpscholten** [comment]
Okay thanks :) Didn't know about this trick. I guess then this issue is solved 👍

**Comment by copumpkin** [comment]
I actually use `fetchFromGitHub` for this all over the place:

```
let outer = import <nixpkgs> {}; in
{ pkgs ? import (outer.fetchFromGitHub { ... }) {} }:

...
```

I like it over `fetchTarball` because my source is often not GitHub and it saves me from having to trust the source of the tarballs, since I have to specify the content hash.

**Comment by edolstra** [comment]
@copumpkin FYI Nix master allows specifying a hash in `builtins.fetchTarball`.
