### ISSUE TITLE
manual is harder to nagivate

### ISSUE THREAD

**Issue by ryantm** [NixOS/nix#10425]
**Describe the bug**

Ever since the mdbook started collapsing sections of the table of contents sidebar of the Nix manual, it has become much harder to navigate. For example, if you want to find the page for "nix copy" you can no longer ctrl+f "nix copy" and find a link to it on the page. If you type "nix copy" into the search, the correct page is the 5th search result.

Perhaps we can turn off this feature of mdbook to restore the usability?

**Expected behavior**

The manual is easier to navigate.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by fricklerhandwerk** [comment]
Yeah I'll revert it. I agree on the UX degradation. Currently swamped with other responsibilities, opening a PR for me to merge will make it faster.
