### ISSUE TITLE
`nix develop nix` makes clangd fill up `XDG_RUNTIME_DIR` tmpfs

### ISSUE THREAD

**Issue by roberth** [NixOS/nix#10430]
**Describe the bug**

`nix develop` changes `TMPDIR` to point to `/run/user/1000` (typically), which is a `tmpfs` of limited size.

When programs, such as `clangd`, which we use for hacking on Nix itself, dump non-trivial amounts of information into `TMPDIR`, it causes various issues with not just the nix shell, but desktop programs as well.

**Steps To Reproduce**

1. Use clangd from `.#native-clangStdenvPackages` shell, on NixOS
2. Hack around a bit. `clangd` may generate a bunch of large `.pch` files, and put them in the undersized `/run/user/1000` directory.

**Expected behavior**

Shell uses the normal tmpdir, which is larger.

**`nix-env --version` output**

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by whentze** [comment]
The behaviour of setting `TMPDIR` to  `$XDG_RUNTIME_DIR` is simply busted, and has continued to cause all kinds of problems for nearly a decade now.

I have tried to summarize my feelings about this in https://github.com/NixOS/nix/issues/2957#issuecomment-1812603365.

For now, you can work around this by
- Exporting `TMPDIR=/tmp` before entering `nix develop` or
- Increasing the size and inode limits on `$XDG_RUNTIME_DIR`.
