### ISSUE TITLE
nix-prefetch-url documentation doesn't include 1.11 changes

### ISSUE THREAD

**Issue by DamienCassou** [NixOS/nix#1044]
1.11 release discusses `nix-prefetch-url -A` but this is not in `nix-prefetch-url` documentation (`--help` or man page). I wanted to fix it, but issue https://github.com/NixOS/nix/issues/1043 is blocking me.

**Comment by Anton-Latukha** [comment]
Relevant for Nix 2.0.

**Comment by tomberek** [comment]
Closing as stale. Re-open if needed.
