### ISSUE TITLE
Allow network during eval in restricted-mode

### ISSUE THREAD

**Issue by FRidh** [NixOS/nix#1047]
Could we have a mode that allows network-access during eval which Hydra could then use?
See also https://github.com/NixOS/nixpkgs/issues/16130#issuecomment-229691307 where this was discussed originally.

**Comment by FRidh** [comment]
(possible duplicate of https://github.com/NixOS/nix/issues/1047)

**Comment by danbst** [comment]
> (possible duplicate of #1047)
misspelled PR number?

**Comment by FRidh** [comment]
This can be closed if #1701 happens.

**Comment by tomberek** [comment]
Closing as stale. Re-open if needed.
