### ISSUE TITLE
`nix profile upgrade` does not remember `?submodules=1`

### ISSUE THREAD

**Issue by fgaz** [NixOS/nix#10474]
**Describe the bug**

If I install a git flake that includes `?submodules=1`, when I run `nix profile upgrade '.*'` the upgrade fails because of missing submodules.

**Steps To Reproduce**

1. Install a git flake with submodules, for example `nix profile install git+https://git.sr.ht/~fgaz/orchid?submodules=1 --no-write-lock-file`
2. Run `nix profile upgrade '.*'` (with `--no-write-lock-file` in this case)

**Expected behavior**

`?submodules=1` is preserved and the flake is updated

**`nix-env --version` output**
nix-env (Nix) 2.18.2

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by Atry** [comment]
Seems a duplicate of https://github.com/NixOS/nix/issues/6788

**Comment by fgaz** [comment]
Indeed. For some reason I didn't find it when I looked for existing issues.

Closing as duplicate.
