### ISSUE TITLE
Backport of fix for leading dot in store paths to 2.17?

### ISSUE THREAD

**Issue by Ma27** [NixOS/nix#10497]
**Describe the bug**

Upon reviewing https://github.com/NixOS/nixpkgs/pull/296709, I realized that https://github.com/NixOS/nix/commit/8aaa8749789aceff0b11d97d19ef290e8c26fe9f got backported to 2.17, however there's a followup (https://github.com/NixOS/nix/pull/9867) that wasn't backported.

Would it be possible to take care of that?
Or is the branch considered dead by now?

**Comment by thufschmitt** [comment]
2.17 is technically unsupported. However, since the backport policy was fairly fuzzy until not that long ago, feel free to open a backport PR. I can't guaranty that there'll be a release, but we can at least merge the backport

**Comment by Ma27** [comment]
Change of plans then: the baseline should remain 2.18 for now[1], but I don't see a reason to keep 2.17 (and older versions) in nixpkgs then if they don't receive any maintenance anyways. Thanks for reporting back!

[1] I'll exclude nix_2_3 from this consideration: it still has a broad userbase to my knowledge so I intend to keep it in nixpkgs.
