### ISSUE TITLE
Reverse lookup for binaries and libraries

### ISSUE THREAD

**Issue by danbst** [NixOS/nix#1050]
From time to time I want to find out which package contains given binary. `command-not-found` is triggered only when binary is at unavail. But I'd like something like this:

```
$ nix where locate
findutils
```
So it will replace `readlink -f $(type locate)` (edit: `type -p locate` is better, didn't know about it)

Another common use-case for reverse lookup is finding library package. (https://github.com/NixOS/nix/issues/1010#issuecomment-239352022)
```
$ nix where libz
zlib
$ nix where libev
libev
$ nix where libtbb
tbb
```
Bonus point: show correct output (`out` or `lib`)

**Comment by vcunat** [comment]
I often run `command-not-found foo` explicitly &ndash; what's wrong about that?

**Comment by danbst** [comment]
didn't know about such use case. BTW
```
$ command-not-found eclipse
eclipse: command not found
```

All in all, I think that this and https://github.com/NixOS/nix/issues/1049 shouldn't belong to core Nix, but now I don't know where to share my desires.
