### ISSUE TITLE
nix-instantiate --json does not properly deepSeq the result before trying to convert to json.

### ISSUE THREAD

**Issue by lolbinarycat** [NixOS/nix#10514]
**Describe the bug**

when trying to print a list as json, nix-instantiate does not properly force the elements of that list, and instead fails.

**Steps To Reproduce**

`$ nix-instantiate --json --expr --eval '[ ((x: x + x) 4) ]'`

**Expected behavior**

the command should print `[8]`.

**`nix-env --version` output**
nix-env (Nix) 2.18.1

**Additional context**

`nix eval` does not have this bug.

workaround is to awkwardly call deepSeq on the value in the expression.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by thufschmitt** [comment]
This is unfortunate, but stuck forever for backwards-compatibility reasons. You need to use `--strict` for that.

(the new CLI doesn't inherit that, however, and does the more natural deepSeq thing)
