### ISSUE TITLE
Nix-* commands take 17+ minutes to run...is there a way to increase speed? 

### ISSUE THREAD

**Issue by Mastermjr** [NixOS/nix#10515]
**Describe the bug**

Any nix

If you have a problem with a specific package or NixOS,
you probably want to file an issue at https://github.com/NixOS/nixpkgs/issues. 

**Steps To Reproduce**
follow multi-user installation steps on below macos version: https://nixos.org/download/

```
uname -a
Darwin s1088678 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:10:42 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6000 arm64 arm Darwin
```

Then try running nix-shell -p nix-info and trigger user interrupt with ctrl-c... 
```
nix-shell -vvv -p nix-info --run "nix-info -m"                                                                                    
evaluating file '<nix/derivation-internal.nix>'
resolved search path element '/Users/XX/.nix-defexpr' to '/Users/XX/.nix-defexpr'
fetching flake search path element 'flake:nixpkgs''
performing daemon worker op: 11
acquiring write lock on '/nix/var/nix/temproots/17224'
performing daemon worker op: 1
using cache entry '{"name":"flake-registry.json","type":"file","url":"https://channels.nixos.org/flake-registry.json"}' -> '{"etag":"W/\"c9a771e3c09bed60e229e3c09b0f0958c395e41074010dc1b0e9ab74240bc2a8\"","url":"https://channels.nixos.org/flake-registry.json"}', '/nix/store/ypkhxink7miy8gw2mi88jlacl213cg4d-flake-registry.json'
performing daemon worker op: 11
performing daemon worker op: 12
looked up 'flake:nixpkgs' -> 'github:NixOS/nixpkgs/nixpkgs-unstable'
performing daemon worker op: 11
performing daemon worker op: 1
using cache entry '{"name":"source","type":"file","url":"https://api.github.com/repos/NixOS/nixpkgs/commits/nixpkgs-unstable"}' -> '{"etag":"W/\"fc4d87ef6f9acf947786271a47e40c170a6eee1af4f1527f5a475c90b72b88ba\"","url":"https://api.github.com/repos/NixOS/nixpkgs/commits/nixpkgs-unstable"}', '/nix/store/1lzvvgzr7kmhiqfgs26qsz0jlmwraqq2-source'
HEAD revision for 'github:NixOS/nixpkgs/nixpkgs-unstable' is 2748d22b45a99fb2deafa5f11c7531c212b2cefa
did not find cache entry for '{"_what":"gitRevToTreeHash","rev":"2748d22b45a99fb2deafa5f11c7531c212b2cefa"}'
downloading 'https://github.com/NixOS/nixpkgs/archive/2748d22b45a99fb2deafa5f11c7531c212b2cefa.tar.gz'...
starting download of https://github.com/NixOS/nixpkgs/archive/2748d22b45a99fb2deafa5f11c7531c212b2cefa.tar.gz
download buffer is full; going to sleep
download buffer is full; going to sleep
download buffer is full; going to sleep
download buffer is full; going to sleep
download buffer is full; going to sleep
download buffer is full; going to sleep
download buffer is full; going to sleep
download buffer is full; going to sleep
download buffer is full; going to sleep
download buffer is full; going to sleep
download buffer is full; going to sleep
load: 7.10  cmd: nix 17222 waiting 1.48u 10.13s
download buffer is full; going to sleep
^Cdownload buffer is full; going to sleep
download buffer is full; going to sleep
finished download of 'https://github.com/NixOS/nixpkgs/archive/2748d22b45a99fb2deafa5f11c7531c212b2cefa.tar.gz'; curl status = 42, HTTP status = 200, body = 9801287 bytes
download thread shutting down
```

**Expected behavior**

nix-shell  -p nix-info --run "nix-info -m"   should run and print out nix version information for debugging

```
╰─$ nix-env --version                                                                                                                 
nix-env (Nix) 2.21.1
```

**Additional context**

Let me know what other context I can provide, I'm sure its something small on my side, but I'm new to nix and just learning how to use it... 

This is also blocking an install of nix-darwin :(

**Comment by Mastermjr** [comment]
well I suppose the process does eventually finish, but this takes a total of 17 minutes to run... I've updated the issue

**Comment by Mastermjr** [comment]
using: `nix-shell -vvv -j 10 --cores 10 -p nix-info --run "nix-info -m"` certainly speeds it up, is there a better way to do this?

**Comment by Mastermjr** [comment]
╰─$ time nix-shell -p nix-info --run "nix-info -m"                                                                                       1 ↵
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.4.0, macOS 14.4.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.21.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/qjgi80svyhfcwbnlvzzaqg0nyr7h2w59-source`

nix-shell -p nix-info --run "nix-info -m"  3.23s user 1.08s system 10% cpu 39.250 total

╰─$ time nix-shell -j 10 --cores 10 -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 23.4.0, macOS 14.4.1`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.21.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/store/qjgi80svyhfcwbnlvzzaqg0nyr7h2w59-source`

nix-shell -j 10 --cores 10 -p nix-info --run "nix-info -m"  3.96s user 1.45s system 10% cpu 53.751 total


this adds no speed up... is there a way I can use a cached version of nixpkgs or a cached version of the shell to speed up run time?

**Comment by Mastermjr** [comment]
thanks, I'm not going to close this, as its still an issue I'm having on my corporate mac m1, BUT
I'm working around the issue right now by running a nixos vm with no issues. 

I do need to use the shell on the host to setup a python environment for my vim settings, so at some point I'll probably just need to setup nix-darwin so the proxy settings and everything run right. 
Is there someway I can cache the nixpkgs import in my shell so I can just use a locally pulled copy of nixpkgs? 
```
{ pkgs ? import <nixpkgs> {} }:
pkgs.mkShell {
  packages = [
    (pkgs.python312.withPackages (python-pkgs: [
      # select Python packages here
      python-pkgs.tasklib
      python-pkgs.six
      python-pkgs.packaging
    ]))
    pkgs.python312Packages.pip
  ];
}
```
that way i only have to deal with this 17 minute download once. Thanks in advance, and I'll post on here if I can figure it out as well

**Comment by SrEstegosaurio** [comment]
You could look into `[direnv](https://github.com/direnv/direnvl)`and `[nix-direnv](https://github.com/nix-community/nix-direnv?tab=readme-ov-file#nix-direnv)` that combo would cache your devShell. There's at least a NixOS option for comfortably enabling those tho I don't know about nix-darwin.

**Comment by Mastermjr** [comment]
OK so I'm gonna close this issue... I've got nix-darwin installed and everything is working way better AND its proxy aware!
so I'm going to mark this issue as closed for now. 

For those coming here wondering why this is broke, my reasoning for MY SYSTEM is that the AV is causing nix-build/nix-env/nix-[XXXX] to download programs very slowly due to whatever kernel hooks are running. 

Anyway, I followed the nix-darwin installation instructions: to setup nix-darwin via a flake: [HERE](https://nixcademy.com/2024/01/15/nix-on-macos/#step-2-going-declarative-with-nix-darwin)

I had to setup my `/etc/nix/nix.conf` like so: 
```
experimental-features = nix-command flakes
extra-nix-path = nixpkgs=flake:nixpkgs
```

The only issue I have now is: https://github.com/LnL7/nix-darwin/issues/931 (but everything still works 🤷 ). 

Heres the flake with proxy working as well: 
```nix
{
  description = "mastermjr's nix on mac";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    nix-darwin.url = "github:LnL7/nix-darwin";
    nix-darwin.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs = inputs@{ self, nix-darwin, nixpkgs }:
  let
    configuration = { pkgs, ... }: {
      imports = [
        # CERTS file with: `security.pki.certificates =` defined
      ];
      # List packages installed in system profile. To search by name, run:
      # $ nix-env -qaP | grep wget
      environment.systemPackages =
        [
          ....
        ];

      # Auto upgrade nix package and the daemon service.
      services.nix-daemon.enable = true;

      # Necessary for using flakes on this system.
      nix.settings.experimental-features = "nix-command flakes";
      nix.settings.build-users-group = "nixbld";
      nix.settings.extra-nix-path = "nixpkgs=flake:nixpkgs";
      nix.envVars = {
          HTTP_PROXY = "X";
          HTTPS_PROXY = "X";
          ALL_PROXY = "X";
      };

      # Create /etc/zshrc that loads the nix-darwin environment.
      programs.zsh.enable = true;  # default shell on catalina
      environment.shells = [ pkgs.bashInteractive pkgs.zsh ];
      environment.variables = {
        REQUESTS_CA_BUNDLE="/etc/ssl/certs/ca-certificates.crt";
      };


      # Set Git commit hash for darwin-version.
      system.configurationRevision = self.rev or self.dirtyRev or null;

      # Used for backwards compatibility, please read the changelog before changing.
      # $ darwin-rebuild changelog
      system.stateVersion = 4;

      # The platform the configuration will be used on.
      nixpkgs.hostPlatform = "aarch64-darwin";
      nix.extraOptions = ''
        extra-platforms = x86_64-darwin aarch64-darwin
      '';
    };
  in
  {
    # Build darwin flake using:
    # $ darwin-rebuild build --flake .#s1088678
    darwinConfigurations."X" = nix-darwin.lib.darwinSystem {
      modules = [ configuration ];
    };

    # Expose the package set, including overlays, for convenience.
    darwinPackages = self.darwinConfigurations."X".pkgs;
  };
}

```
