### ISSUE TITLE
Recommend long-shebang for modern-UI replacement of nix-shell -i

### ISSUE THREAD

**Issue by shlevy** [NixOS/nix#1051]
`nix-shell` currently does some shebang-line parsing to handle the multiple args needed to set up a nix-shell driven interpreter. In the replacement, I recommend we defer to https://github.com/shlevy/long-shebang for the multiple argument handling aspect of nix-shell's work.

**Comment by edolstra** [comment]
Hm, I don't see why relying on an external, not widely available program is an improvement over handling this in nix-shell.

**Comment by shlevy** [comment]
It's completely portable, fully generic, and can't become widely available if no one uses it because it's not widely available. I'm happy to push getting this into other major distros if that's the sticking point.

We already have special shebang parsing in perl and ruby, and probably others. We can continue that in nix, or try to stop the proliferation of projects all solving the same problem over and over.

**Comment by zimbatm** [comment]
long-shebang is a good idea but I think in nix's case we should avoid adding external runtime dependencies since it's used to bootstrap the system.

Would it be possible to use long-shebang as a library instead?

**Comment by shlevy** [comment]
Would probably just make more sense to include it in tree and install it with the rest, it's 192 sloc of C code. Included as a library it doesn't really help much.

**Comment by shlevy** [comment]
@edolstra Any chance of this happening either by adding it to a bunch of distros and/or vendoring it?
