### ISSUE TITLE
Nix >=2.19.0 has a regression on fetchGit submodules recursive clone

### ISSUE THREAD

**Issue by pho** [NixOS/nix#10538]
**Describe the bug**

Since ee36a44bf272c8cca62a2ce96a017a8150c4d35b `builtins.fetchGit` only does one level of submodule clone recursion

Eg. If repository A has B as a submodule, and B has C as a submodule, fetching A does not obtain C files

**Steps To Reproduce**

I got hit by this on a private repository which depends on the raspberry/pico-sdk, which also depends on other repositories like tinyusb, so I searched for a public one which also depends on it as an example:

1. `nix run "github:NixOS/nix/2.19.0" --  eval --expr '(builtins.fetchGit { url = "https://github.com/execuc/u2if.git"; submodules = true; rev = "1aaed6ad33fc805e5015898f10c90cb464f71b8f"; allRefs = true;}).outPath'`
2. `/nix/store/dsdaf6n97a3c94i9ncsc33kvkv683dxa-source/firmware/pico-sdk/lib/tinyusb/` should contain files but it does not

**Expected behavior**

1.  `nix run "github:NixOS/nix/2.18.2" --  eval --expr '(builtins.fetchGit { url = "https://github.com/execuc/u2if.git"; submodules = true; rev = "1aaed6ad33fc805e5015898f10c90cb464f71b8f"; allRefs = true;}).outPath'`
2. `/nix/store/bgjprlxm6yg2r5rdlhwrj44ys17xbqn6-source/firmware/pico-sdk/lib/tinyusb/` contains files

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by Princemachiavelli** [comment]
Looks like #10588 fixes this issue. Running the expression on master (rev `87ab3c0e`) gives:
```bash
 >>>> ~/srcs/nix/result/bin/nix eval --expr '(builtins.fetchGit { url = "https://github.com/execuc/u2if.git"; submodules = true; rev = "1aaed6ad33fc805e
5015898f10c90cb464f71b8f"; allRefs = true;}).outPath'
"/nix/store/7i91j9visb6a8v4ji81z4pszbnca75c8-source"
 >>>> ls -lha /nix/store/7i91j9visb6a8v4ji81z4pszbnca75c8-source/firmware/pico-sdk/lib/tinyusb/
Permissions Size User Date Modified Name
.r--r--r--   351 root 31 Dec  1969  .gitattributes
dr-xr-xr-x     - root 31 Dec  1969  .github
.r--r--r--   229 root 31 Dec  1969  .gitignore
.r--r--r--  5.0k root 31 Dec  1969  .gitmodules
.r--r--r--  8.4k root 31 Dec  1969  changelog.md
.r--r--r--  3.3k root 31 Dec  1969  CODE_OF_CONDUCT.md
.r--r--r--  3.3k root 31 Dec  1969  CONTRIBUTORS.md
dr-xr-xr-x     - root 31 Dec  1969  docs
dr-xr-xr-x     - root 31 Dec  1969  examples
dr-xr-xr-x     - root 31 Dec  1969  hw
dr-xr-xr-x     - root 31 Dec  1969  lib
.r--r--r--  1.1k root 31 Dec  1969  LICENSE
.r--r--r--   277 root 31 Dec  1969  pkg.yml
.r--r--r--  5.1k root 31 Dec  1969  README.md
.r--r--r--    78 root 31 Dec  1969  repository.yml
dr-xr-xr-x     - root 31 Dec  1969  src
dr-xr-xr-x     - root 31 Dec  1969  test
.r--r--r--  103k root 31 Dec  1969  tinyusb.Doxyfile
dr-xr-xr-x     - root 31 Dec  1969  tools
.r--r--r--   142 root 31 Dec  1969  version.yml
```

However, the issue still occurs for flake inputs. Using the same repo & rev as a non-flake input gives the following outPath:
 
```nix
{
  inputs = {
    u2if.url = "git+https://github.com/execuc/u2if?submodules=1&1aaed6ad33fc805e5015898f10c90cb464f71b8f&allRefs=1";
    u2if.flake = false;
  };
  outputs = { self, u2if, ... }@outputs: {};
}
```
```nix
nix-repl> :lf .
nix-repl> inputs.u2if
{
  lastModified = 1625000820;
  lastModifiedDate = "20210629210700";
  narHash = "sha256-A7mv2sp3HaeC3Sv5tKnee2KDIB41xZP6Hx2QLG9CCTE=";
  outPath = "/nix/store/dsdaf6n97a3c94i9ncsc33kvkv683dxa-source";
  rev = "1aaed6ad33fc805e5015898f10c90cb464f71b8f";
  revCount = 23;
  shortRev = "1aaed6a";
  submodules = true;
}
nix-repl> inputs.u2if.outPath
"/nix/store/dsdaf6n97a3c94i9ncsc33kvkv683dxa-source"
>>>>> ls -lha /nix/store/dsdaf6n97a3c94i9ncsc33kvkv683dxa-source/firmware/pico-sdk/lib/tinyusb/
"empty folder"
```

**Comment by roberth** [comment]
The backport to 2.19 was non-trivial, and that version is not formally supported anymore. Are you ok to update to a newer version?

**Comment by pho** [comment]
Sure, thanks for your help!
