### ISSUE TITLE
Implement process spawning on Windows

### ISSUE THREAD

**Issue by Ericson2314** [NixOS/nix#10544]
#8901 just stubbed it out for now: we need to put an actual implementation in [`src/libutil/windows/processes.cc`](https://github.com/NixOS/nix/blob/master/src/libutil/windows/processes.cc).

As always, a good resource is what was done in [the original Windows](https://github.com/nix-windows/nix/blob/windows) port:
- [`src/libutil/util.cc`](https://github.com/nix-windows/nix/blob/windows/src/libutil/util.cc)

**Comment by roberth** [comment]
POSIX `spawn` was mentioned in another thread.
It'd be good to look into a generic process invoking interface that's implemented for either platform.

**Comment by Ericson2314** [comment]
Yes. The original port did indeed offer such an interface, and we should too.
