### ISSUE TITLE
emacs highlighting breaks on file from nixos

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nix#1055]
emacs's syntax highlighting gets all screwy on https://github.com/NixOS/nixpkgs/blob/master/lib/modules.nix when it encounters the first `${name}`.

I am honestly not sure if those references to `${name}` shouldn't be `"${name}"` instead or the syntax highlighting is broken.

First reference here:
https://github.com/NixOS/nixpkgs/blob/master/lib/modules.nix#L81

If I apply the following patch to `modules.nix`, syntax highlighting is all good again:
https://gist.github.com/3cee4ef9287f8a355bed4cb615f44e19

**Comment by domenkozar** [comment]
We should probably update highlighting to support that new feature, same for github.

**Comment by peterhoeg** [comment]
cc @matthewbauer who's been working on ```nix-mode```.
