### ISSUE TITLE
Under release notes, add more info on which releases are stable and unstable.

### ISSUE THREAD

**Issue by Hyperpolarized** [NixOS/nix#10574]
## Problem

Release notes not showing which releases are stable and not.

## Proposal

Add more info on which releases are stable or not.

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open documentation issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/src
[open documentation issues and pull requests]: https://github.com/NixOS/nix/labels/documentation

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by fricklerhandwerk** [comment]
@Hyperpolarized what exactly do you mean by stable here? If that means which versions are released with Nixpkgs and NixOS, that information is displayed here: https://nix.dev/reference/nix-manual And arguably, the Nix codebase should not particularly care about that, except that maintainers should ensure that Nix actually works for each release.
