### ISSUE TITLE
Use d-bus for accessing a remote store

### ISSUE THREAD

**Issue by svanderburg** [NixOS/nix#106]
Right now, I believe we are using a custom implemented protocol through Unix domain sockets, which is fairly low-level.

It may also be nice/useful to use d-bus (http://www.freedesktop.org/wiki/Software/dbus) instead of a custom protocol. With d-bus you can clearly define an interface in a D-Bus introspection XML file and the operation signatures.

D-Bus uses Unix domain sockets to communicate among processes, but can also use different protocols such as TCP.

Moreover, there are D-Bus implementations in many programming languages and many operating systems (even Windows and .NET) allowing people to easily integrate with the Nix worker using any programming language that is supported.

**Comment by edolstra** [comment]
Closing as "too much work" :-)
