### ISSUE TITLE
Flake evaluation options documented in help strings are retaining html tags

### ISSUE THREAD

**Issue by oxcabe** [NixOS/nix#10622]
## Problem

Using `nix (Nix) 2.18.1`.

The _Options_ section in the `nix flake <command> --help` message is preserving the HTML tags.
e.g. running `nix flake new --help` will print the following at the end of the help message:
```bash
Options

    · <span id="opt-template">--template</span> / -t template

      The template to use.

    Common evaluation options:

    · <span id="opt-arg">--arg</span> name expr

      Pass the value expr as the argument name to Nix functions.

    · <span id="opt-argstr">--argstr</span> name string

      Pass the string string as the argument name to Nix functions.

    · <span id="opt-debugger">--debugger</span>
 ```

This could be caused by the manpages generation script not properly removing HTML tags.

This code seems relevant, too:
* https://github.com/NixOS/nix/blob/4161f3cfea10e77ad04cc189affeb5291c66c156/src/libcmd/common-eval-args.cc

## Proposal

1. Figure out where the help message template is.
2. Strip the HTML tags when creating manpages.

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open documentation issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/src
[open documentation issues and pull requests]: https://github.com/NixOS/nix/labels/documentation

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by oxcabe** [comment]
I would like to contribute a PR to fix this issue, in case it's consider a valid concern :+1:

**Comment by edolstra** [comment]
This seems to be fixed on master (maybe because the lowdown dependency got updated?).

**Comment by edolstra** [comment]
Actually I can't reproduce it on 2.18 either, e.g.
```
nix run nix/2.18.2 -- flake new --help
```
shows
```
    · --template / -t template The template to use. 

    Common evaluation options:

    · --arg name expr Pass the value expr as the argument name to Nix functions.

    · --argstr name string Pass the string string as the argument name to Nix functions.
```

**Comment by oxcabe** [comment]
It might just be a me thing then. I'll look further into it.

**Comment by oxcabe** [comment]
I wasn't able to figure out what happened. Closing this for now.
