### ISSUE TITLE
using Musl

### ISSUE THREAD

**Issue by AndreyMlashkin** [NixOS/nix#10623]
## Problem

I would like to use musl for all my dependency tree in a project. Is there any way how to archive that?
I am going to link it statically. I know, it may be against the best practices, but still there are reasons to do so.

- [x] checked [latest Nix manual] \([source])
- [x] checked [open documentation issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/src
[open documentation issues and pull requests]: https://github.com/NixOS/nix/labels/documentation

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by edolstra** [comment]
If you're referring to Nix itself, you can get a static musl build by doing: `nix build nix#nix-static`

For building your own stuff, you can use `pkgsStatic` in Nixpkgs. E.g. `nix build nixpkgs#pkgsStatic.hello` gives you a musl build of GNU hello.
