### ISSUE TITLE
nixfmt

### ISSUE THREAD

**Issue by nhooyr** [NixOS/nix#1064]
It would be really cool to have something like gofmt but for nix expressions.

https://blog.golang.org/go-fmt-your-code

**Comment by matthewbauer** [comment]
[Gabriel439/nixfmt](https://github.com/Gabriel439/nixfmt) exists but it's incomplete.

**Comment by olejorgenb** [comment]
Relevant/similar: #832

**Comment by domenkozar** [comment]
This duplicates #832
