### ISSUE TITLE
I deleted the store volume

### ISSUE THREAD

**Issue by Jeverett3000** [NixOS/nix#10643]
## Platform

- [ ] Linux: 
- [x] macOS
- [ ] WSL

## Output

<details><summary>Output</summary>

```log

<!-- paste console output here and remove this comment -->

```

</details>

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by abathur** [comment]
I'd recommend following the uninstall instructions and then try reinstalling nix: https://nixos.org/manual/nix/stable/installation/uninstall.html#macos
