### ISSUE TITLE
Can't create sym link '/etc/tmpfiles.d/nix-daemon.conf'

### ISSUE THREAD

**Issue by Ff-c109** [NixOS/nix#10690]
## Platform

- [x] Linux: 
  - *Linux haneyume-TM1701 6.5.0-28-generic 29~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr  4 14:39:20 UTC 2 x86_64 x86_64 x86_64 GNU/Linux*

- [ ] macOS
- [ ] WSL

## Additional information

I used V2rayA to set up a transparent proxy in tproxy mode. Cause I need it to access internet.

## Output

<details><summary>---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo install -m 0664 /tmp/tmp.dVnwkqAwPc/nix.conf /etc/nix/nix.conf

to place the default nix daemon configuration (part 2)

~~> Setting up the nix-daemon systemd service

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo ln -sfn /nix/var/nix/profiles/default/lib/tmpfiles.d/nix-daemon.conf /etc/tmpfiles.d/nix-daemon.conf

to create the nix-daemon tmpfiles config

ln: 无法创建符号链接 '/etc/tmpfiles.d/nix-daemon.conf': 没有那个文件或目录
    *translation: ln can't create symbol link '/etc/tmpfiles.d/nix-daemon.conf': no such a directory or file.*

---- oh no! --------------------------------------------------------------------
Oh no, something went wrong. If you can take all the output and open
an issue, we'd love to fix the problem so nobody else has this issue.

:(

We'd love to help if you need it.

You can open an issue at
https://github.com/NixOS/nix/issues/new?labels=installer&template=installer.md

Or get in touch with the community: https://nixos.org/community</summary>

```log

<!-- paste console output here and remove this comment -->

```

</details>

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by grahamc** [comment]
We found/fixed this in the Determinate Nix Installer, too. It turns out the installer needs to pre-create /etc/tmpfiles.d: https://github.com/DeterminateSystems/nix-installer/blob/18d265a6ab4fe2b4e0317ee6b449d30178d53073/src/planner/linux.rs#L80-L85

**Comment by abathur** [comment]
Based on graham's comment, you could probably also follow the uninstall instructions (https://nixos.org/manual/nix/stable/installation/uninstall.html#linux), create the folder, and try installing again.

**Comment by Ff-c109** [comment]
> We found/fixed this in the Determinate Nix Installer, too. It turns out the installer needs to pre-create /etc/tmpfiles.d: https://github.com/DeterminateSystems/nix-installer/blob/18d265a6ab4fe2b4e0317ee6b449d30178d53073/src/planner/linux.rs#L80-L85

It's just a simple step, thanks a lot for help!
