### ISSUE TITLE
Expose nix-env and nix-build operations through an API/library

### ISSUE THREAD

**Issue by svanderburg** [NixOS/nix#107]
The current implementation provides libraries, such as libstore (for store access) and libexpr (for evaluating Nix expressions). It may also be useful to expose nix-env and nix-build operations through a library, allowing external tools such as Disnix to integrate with it.

Right now the only way is to invoke the nix-env or nix-build processes, which is not always very convenient/elegant.

It may also be useful for a e.g. future desktop tool providing a nice GUI to Nix.

**Comment by Ericson2314** [comment]
We now have https://github.com/NixOS/nix/blob/master/src/libstore/profiles.hh for the heart of `nix-env`, and a bunch of different things for building, so I'd say this is done?
