### ISSUE TITLE
Tools to update ssl ca break

### ISSUE THREAD

**Issue by EzekielEnns** [NixOS/nix#10719]
I don't know to classify this as a bug or a feature request, all I know is it sucks for my day job.
There is no way for tools to update ssl certs pragmatically, commands like `update-ca-certificates` are not on the 
system this causes things like `mkcert --install` to break and makes it really hard to practically get dev certs up and running
as you have to set them up differently then any other OS

Yes, you can use add these certs to `security.pki.certificates` or `security.pki.certificateFiles`
to add the certs to your ca, but this process is not ideal for local dev environments, not to mention it forces your config to either be impure or for you to copy and paste the cert in. 

The expected behaviour would be to have access to `update-ca-certificates` and enable tools to modify the trust.
Also, maybe use this issues as a way to talk about how to deal with dev ssl certs better on NixOS for new people 

nixos-version
23.11.20240506.27c1399 (Tapir)

let me know if I have to move this, thank you to anyone who responds

**Comment by cole-h** [comment]
This sounds less like a Nix (the package manager) issue and more like a NixOS (the operating system built upon Nix-the-package-manager) issue. For NixOS issues, please report them to https://github.com/NixOS/nixpkgs/issues/. Thanks!

**Comment by EzekielEnns** [comment]
Thank you so much! Moved the post [here](https://github.com/NixOS/nixpkgs/issues/311976)
