### ISSUE TITLE
Update xmonad to 0.18.0

### ISSUE THREAD

**Issue by crftbt** [NixOS/nix#10731]
What would be the process to have xmonad in NixOS Unstable upgraded from 0.17.2 to 0.18.0?

**Comment by NobbZ** [comment]
1. finding the correct repo (github.com/nixos/nixpkgs)
2. reading its [contribution.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md)
3. realize its managed by the haskell poeple and those have their own stackage synced update cycles

I do not know the details of that though.

**Comment by cole-h** [comment]
Closing as this is not a nix-the-package-manager issue, but a Nixpkgs-the-package-set issue. Thanks!
