### ISSUE TITLE
Nested block comments

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/nix#10730]
Nested block comments apparently aren't a thing in the Nix language. How sad.

# Steps to reproduce

```shell-session
$ nix --version
nix (Nix) 2.22.1
```

```nix
# okay.nix
/*
  okay
*/
1
```

```shell-session
$ nix-instantiate --eval okay.nix
1
```

```nix
# nope.nix
/*
  /*
    nope
  */
*/
1
```

```shell-session
$ nix-instantiate --eval nope.nix
error: syntax error, unexpected '*'
       at nope.nix:5:1:
            4|   */
            5| */
             | ^
            6| 1
```

# Trivia

I'm actually surprised how no one seems to have stumbled over this. 

Thanks to @hsjobeki's [RFC 145](https://github.com/NixOS/rfcs/pull/145) there is even a use case for nested block comments: documenting how to document Nix language libraries within a Nix language library!

**Comment by FranciscoTGouveia** [comment]
Hi, my name is Francisco and I'm a computer science student that is fascinated by the wonders of Nix. With that being said, I would like to start contributing to the project and think that this could be a good first issue for me to tackle. I've already delved into the codebase an think that the problem might be in the lexical analysis (the *Flex* file at `src/libexpr/lexer.l`). I've looked into some closed issues and merged PR's and don't find many assigned issues. Could I be assigned to this issue, or issue assignments are not really a part of the project's culture? Thanks in advance!

**Comment by hsjobeki** [comment]
As a reference jsdoc has the same problem. Here is the 10 year old issue: 

https://github.com/jsdoc/jsdoc/issues/821

Many languages seem to just not support nested block comments. 

still would be nice if nix did.

Workarounds:

- use html escape sequences (requires some html processing)
- use single line comments

**Comment by fricklerhandwerk** [comment]
@FranciscoTGouveia great to have you! I assigned the issue to you as requested, please add or ping me as a reviewer for PRs.

Note that since we're very conservative with evolving the language, we'll have to make sure that the change is strictly additive and doesn't break existing expressions. We may therefore want to add a test that evaluates past Nixpkgs releases.

**Comment by roberth** [comment]
Concretely, an expression like this may cease to be valid:

> ```nix
> # regression.nix
> /*
>   ignore src/*
> */
> 1
> ```

This instance could be mitigated by requiring whitespace to precede the nested comment.

We can't  know the true extent of such issues, because of private code bases.

A simpler solution to the doc comments use case is to recommend that the commented text be unescaped by documentation tooling, according to some rules to be specified. For example, `nixdoc` could turn `/\*` could into `/*`, but a more complete scheme would be desirable.

**Comment by hsjobeki** [comment]
Another idea:

```
/**
  comment
  /* nested */
**/
1
```

Then this would work

```
# regression.nix
/**
  ignore src/*
**/
1
```

**Comment by fricklerhandwerk** [comment]
Apparently I'm ignorant and full of wishful thinking about how computer languages work, but apparently saying a naive thing such as "the longest sequence of characters between `/*` and `*/` is a comment" is an instance of greedy matching, which would make parsing a lot less efficient.

**Comment by roberth** [comment]
I don't know where you got that, but the longest sequence would also ignore `2` in `/**/2/**/`, so I don't think we want that anyway.
If we do the unescaping thing, we can keep the parsing (or lexing) the same as it is today. Unescaping is quite cheap and can be done on demand.

**Comment by fricklerhandwerk** [comment]
@roberth agreed, recommending unescaping is the least invasive and simplest thing to do here.
