### ISSUE TITLE
Document that inherit works in let bindings

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nix#1075]
The manual section [_Inheriting attributes_](https://nixos.org/nix/manual/#idm140737318140176) ought to mention that `inherit` can also be used for `let` bindings, not just to define set attributes.

**Comment by Ericson2314** [comment]
Yes, the day I learned one can do this was a good one.

**Comment by grahamc** [comment]
Closed by https://github.com/NixOS/nix/pull/1822
