### ISSUE TITLE
`nix build --system` don't use remote builder

### ISSUE THREAD

**Issue by yihuang** [NixOS/nix#10762]
**Describe the bug**

`nix build --system` don't use remote builder and try to build locally, while `nix-build` with the same derivation correctly use remote builder to build.

**Steps To Reproduce**

1. Run `nix build github:crypto-org-chain/cronos#test-env --system aarch64-linux` on mac
2. Fail:
    ```
    error: builder for '/nix/store/y6lqwxbqbm9p8bwnmmsji7zs2z5pfx5p-python3.11-platformdirs-4.2.0.drv' failed with exit code 126;
       last 1 log lines:
       > /nix/store/rjc60f80jlhm16fvladh6sb5frgx6wc3-bash-5.2p26/bin/bash: /nix/store/rjc60f80jlhm16fvladh6sb5frgx6wc3-bash-5.2p26/bin/bash: cannot execute binary file
       For full logs, run 'nix log /nix/store/y6lqwxbqbm9p8bwnmmsji7zs2z5pfx5p-python3.11-platformdirs-4.2.0.drv'.
    ```
3. But if I manually build the failed derivation like this: `nix-build /nix/store/y6lqwxbqbm9p8bwnmmsji7zs2z5pfx5p-python3.11-platformdirs-4.2.0.drv`, it correctly builds it using remote builder.

**Expected behavior**

`nix build $FLAKE --system aarch64-linux` on mac should use remote builder automatically.

**`nix-env --version` output**

```
nix-env (Nix) 2.19.3
```

**Additional context**

m3 mac laptop

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by yihuang** [comment]
But after I do a few times of manual `nix-build` with the failed derivations, the top level target  eventually builds succesfully.

**Comment by fricklerhandwerk** [comment]
Triagd in Nix team meeting:
- @Ericson2314 there's an [`eval-system`](https://nix.dev/manual/nix/2.22/command-ref/conf-file#conf-eval-system) setting now, please try that
  - it should be less of a footgun though. `--system` only changes what the current builder is considered to support.
  - @fricklerhandwerk documentation is quite clear about it as of 2.22, I'm not sure when the feature actually landed.

**Comment by yihuang** [comment]
> Triagd in Nix team meeting:
> 
> * @Ericson2314 there's an [`eval-system`](https://nix.dev/manual/nix/2.22/command-ref/conf-file#conf-eval-system) setting now, please try that

I don't want to change to default system, I just want to change the system for this particular build.

>   
>   * it should be less of a footgun though. `--system` only changes what the current builder is considered to support.
>   * @fricklerhandwerk documentation is quite clear about it as of 2.22, I'm not sure when the feature actually landed.

I guess the `legacyPackages.${system}.${target}` trick is the expected way to do this?

**Comment by fricklerhandwerk** [comment]
> I don't want to change to default system, I just want to change the system for this particular build.

You can pass any setting as a command-line flag, see the top of that linked nix.conf documentation page. Please try `nix build ... --eval-system aarch64-linux` and check if it does what you originally intended.

**Comment by yihuang** [comment]
> > I don't want to change to default system, I just want to change the system for this particular build.
> 
> You can pass any setting as a command-line flag, see the top of that linked nix.conf documentation page. Please try `nix build ... --eval-system aarch64-linux` and check if it does what you originally intended.

I just confirmed `--eval-system` works, need to update to latest nix version though.

BTW, it seems not mentioned anywhere, but I find the best way to upgrade nix to a particular version seems to be:
```
$ sudo nix profile install github:NixOS/nix/2.22.1 --profile /nix/var/nix/profiles/default --priority 4
```
