### ISSUE TITLE
Include a sysusers config file and a user tmpfiles config file

### ISSUE THREAD

**Issue by poscat0x04** [NixOS/nix#10775]
**Describe the solution you'd like**
Currently nix only provides a [tmpfiles config](https://github.com/NixOS/nix/blob/master/misc/systemd/nix-daemon.conf.in), and the responsibility of creating users and creating symlinks (such as `~/.nix-defexpr` and `~/.nix-profile`) in a user's home are delegated to the downstream packagers. It would be nice to include sensible default configs in nix.

(Unfortunately I'm not very familiar with autotools so I don't know how to contribute)

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by Ericson2314** [comment]
What exactly are you envisioning? I've never heard of https://www.freedesktop.org/software/systemd/man/latest/tmpfiles.d.html being used for user-level configuration. Yes, the installer does set up some of this stuff, but Nix itself can too on the fly when things are needed (and if someone never uses profiles, it's fine to not have these files).

In a world where:

1. The installer didn't create these files (to do)
2. Nix creates these files on demand (already done)

Would we still benefit from tmpfile entries for these files? I don't think so, but I might be missing something...

**Comment by poscat0x04** [comment]
> Nix creates these files on demand

Ah I didn't know that... I thought the user has to create them manually..

**Comment by Ericson2314** [comment]
Yes, it's kind of a hidden feature. I really want it to be shown off more! :)
