### ISSUE TITLE
Add `:doc` for lambdas to repl with `nix-doc`

### ISSUE THREAD

**Issue by roberth** [NixOS/nix#10771]
> Implemented in Lix. Feel free to cherry-pick it. ^.^ https://gerrit.lix.systems/c/lix/+/564

_Originally posted by @lf- in https://github.com/NixOS/nix/issues/3904#issuecomment-2125526345_

----------

The nix-doc dependency is not ideal, unless it could be a start towards doing more Rust.
Reimplementing without rustdoc is highly non-trivial, as we'll want to preserve evaluator performance. I'd spent ~2 days on that rather fruitlessly last year, so I'd just cherry-pick.
We might want to put it behind a `package.nix` flag. Perhaps `buildNoGc` could become a more general `nix_minimal`.
The static build doesn't have to be minimal (and this dependency is linked, so that works), so I'd keep that one similar to the normal build, or add the combination `nix_minimal_static`.

If we agree to do this, it is an alternative to
- #9054
- #1652

**Comment by fricklerhandwerk** [comment]
I'd sure like the minimal Nix idea, which we could eventually use for bootstrapping Nix from vanilla Linux, and then have a Nix-only build setup for Nix itself. Whether we want a very heavy build, and in which order to approach building the complexity tower, should probably be discussed in the team.
