### ISSUE TITLE
Removing static IP Configuration doesnt initiate dhcp renewal

### ISSUE THREAD

**Issue by jason-m** [NixOS/nix#10786]
**Describe the bug**

Switching from static ip on an interface to dhcp breaks connectivity 

**Steps To Reproduce**

1. configure static ip address via networking.interfaces.ethX.ipv4.addresses
2. remove that configuration so that it reverts back to dhcp 
3. nixos-rebuild switch will leave the interface with no configured ip address

**Expected behavior**

given dhcp is the default setting for unconfigured interfaces when doing a rebuild switch i would expect the interface to be reconfigured by dhcp rather than left completely unconfigured 

**`nix-env --version` output**
nix-env (Nix) 2.18.1

**Additional context**

**Priorities**

**Comment by cole-h** [comment]
This sounds less like a Nix (the package manager) issue and more like a NixOS (the operating system built upon Nix-the-package-manager) issue. For NixOS issues, please report them to https://github.com/NixOS/nixpkgs/issues/. Thanks!
