### ISSUE TITLE
Old `bash.bashrc.backup-before-nix` mentions Nix

### ISSUE THREAD

**Issue by seanchen1991** [NixOS/nix#10804]
## Platform

- [ ] Linux: 
- [x] macOS
- [ ] WSL

## Additional information

I've included the contents of `bash.bashrc` and `bash.bashrc.backup-before-nix` below. Another thing to note is that I use the `fish` shell. Not sure if that's relevant to the issue I'm seeing here.

## Output

<details><summary>Output</summary>

`bash.bashrc`
```
# Nix
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
# End Nix


# Nix
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
# End Nix
```

`bash.bashrc.backup-before-nix`
```
# Nix
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
# End Nix
```

</details>

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by abathur** [comment]
See if this gets you sorted:
- https://github.com/NixOS/nix/issues/7069#issuecomment-1252364467
