### ISSUE TITLE
Strange behavior from failing nix build

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#1081]
My understanding is that if a nix build fails (i.e., something returns a nonzero exit code), even if it puts stuff into its `$out` (or other outputs), the output path won't register as valid. Instead, I have a situation where:

```
nix-build foo.nix # returns nonzero exit code
# immediately afterwards
nix-build foo.nix # returns immediately as success without rebuilding
```

Which seems wrong to me, regardless of the contents of foo.nix. Is that correct? [This gist](https://gist.github.com/copumpkin/e0cf2d6749839808cb91347b73e52868) demonstrates that behavior.

I've seen it fail on at least one Linux (non-NixOS) box and one Darwin box, and although it's reproducible on each of those boxes, I also have a NixOS box where it didn't happen, so I'm not sure what's going on.

**Comment by veprbl** [comment]
You've bumped into #998. In this case the build itself is successful, it's only a cleanup that fails, so it is possible that the store path is successfully registered before that.

**Comment by copumpkin** [comment]
Amazing! Thanks for the quick response. I'll close and follow your PR instead 👍
