### ISSUE TITLE
--keep-going should be on by default

### ISSUE THREAD

**Issue by ocharles** [NixOS/nix#1084]
Ok, opinionated issue time, but I have lost a stupid amount of time by not having `--keep-going` on by default. I would like to propose that either `--keep-going` is on by default, or Nix as a whole can be configured to always have this flag on if we don't want to impose my opinion on the world.

Excuse the tersness of this issue, but it should allow you to read a little bit of my frustration from between the lines.

**Comment by domenkozar** [comment]
@edolstra we could make this as default as part of the new UI. Thoguhts? I agree with @ocharles here, I've share the same experience.

**Comment by shlevy** [comment]
It's not on by default now, but you can set it so in nix.conf.

**Comment by ocharles** [comment]
I still think this decision will waste people's time, but hopefully it will waste it less frequently when they learn there is an option ;) Is there a corresponding option in `configuration.nix`?

**Comment by shlevy** [comment]
@ocharles I'm all for having it by default, I just don't want to change that without giving @edolstra time to respond

**Comment by shlevy** [comment]
@ocharles You can set nix.conf lines in configuration.nix.

**Comment by ocharles** [comment]
I know that, but I want more visibility. This is a lot more discoverable if it becomes a blessed option in `configuration.nix`.

**Comment by domenkozar** [comment]
This is something up for the release process of Nix; once release, add new configuration options to NixOS.

**Comment by shlevy** [comment]
Eh, I'm not a fan of configuration options that don't orchestrate anything and just set single config file lines, but whatever

**Comment by shlevy** [comment]
#1116
