### ISSUE TITLE
nix-mode status

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nix#1086]
I've been working on fixing the nix-mode.el file in this repo. Right now, my changes are available at https://github.com/matthewbauer/nix-mode. The changes to nix-mode.el file should fix: #1040, #1054, #1055.

I see two options for incorporating these changes depending on what @edolstra and others prefer:
1. Create a pull request to [NixOS/nix](https://github.com/NixOS/nix) that incorporates the changes in the nix/misc/emacs/nix-mode.el file.
2. Move "nix-mode" to its own repository as NixOS/nix-mode like [NixOS/nix-idea](https://github.com/NixOS/nix-idea), [NixOS/mvn2nix-maven-plugin](https://github.com/NixOS/mvn2nix-maven-plugin), [NixOS/nix-eclipse](https://github.com/NixOS/nix-eclipse). nix/misc/emacs would be deleted and update the MELPA repo to use NixOS/nix-mode.

I prefer the 2nd option because it would mean this repo wouldn't be polluted with changes to nix-mode.

**Comment by domenkozar** [comment]
@matthewbauer for now, let's merge this changes into Nix. I think if you get one review by an emacs user it should be enough.

See also https://github.com/NixOS/nix/issues/1055

For future, make a PR against nixpkgs that adds `nix-mode` from a repository and once it's ready I'll move it to NixOS organization.

**Comment by matthewbauer** [comment]
#1120

**Comment by matthewbauer** [comment]
Okay, so I've got a PR of the best changes that I've got. Right now all of the Emacs packages are autogenerated from MELPA right? The MELPA nix-mode just [points to this repository](https://github.com/melpa/melpa/blob/master/recipes/nix-mode).
