### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by unitop322** [NixOS/nix#10870]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by cole-h** [comment]
Please fill out the template and feel free to re-open once this is actionable. Thanks!
