### ISSUE TITLE
_nixbld 1 through 4 have disappeared

### ISSUE THREAD

**Issue by Dandandooo** [NixOS/nix#10912]
**Describe the bug**

I am trying to rebuild my home-manager config using `home-manager switch` without any flakes. After parsing my code for errors, nix outputs the following:
```
❯ home-manager switch
these 13 derivations will be built:
  /nix/store/jcrd05mlpsw8wmixwd133pv3q3xbm18w-nerdfonts-3.2.1.drv
  /nix/store/0ddr3y50pv5p00v28rs4jcgcibyr98py-home-manager-path.drv
  /nix/store/2j3zpliq26xqbwqxxy4hjf4jn78sq911-nerdfonts-3.2.1-fish-completions.drv
  /nix/store/0jqlw4k6vi2cm6zc8vwbs8s8d27lk1ca-dani-fish-completions.drv
  /nix/store/nwadv2hi8vj00ml8mq9zmnbnbhci51pd-man-paths.drv
  /nix/store/y5r5jmyxknhqcr7vz6bw0hbqyf3sjn99-man-cache.drv
  /nix/store/m3n5bz1a667garxgqj92gafbpml134z3-hm_.manpath.drv
  /nix/store/hg1vna8m7dhiajn41nw965v2ip68vlp1-home-manager-fonts.drv
  /nix/store/ni1c496hgrypy6y5cjakwfmpm158b9bb-hm_LibraryFonts.homemanagerfontsversion.drv
  /nix/store/nq7rcq40vgqgrg9vgkh4xfr43kc0q37g-home-manager-applications.drv
  /nix/store/mp6pyi48s0xi6q8x41srlvg72zjyr2vn-home-manager-files.drv
  /nix/store/qpnkw5s7a39v0r1v40bv1frfbpa6pmh3-activation-script.drv
  /nix/store/20z2x7mrp1rv7yyh8y6jq02sy2zsdinh-home-manager-generation.drv
error: the user '_nixbld1' in the group 'nixbld' does not exist
```

Curious, I then switch to nushell to check out my system. The users are outputted as follows:
```
❯ (((sys).host).sessions).name | sort
╭────┬──────────────╮
│  0 │ _mbsetupuser │
│  1 │ _nixbld10    │
│  2 │ _nixbld11    │
│  3 │ _nixbld12    │
│  4 │ _nixbld13    │
│  5 │ _nixbld14    │
│  6 │ _nixbld15    │
│  7 │ _nixbld16    │
│  8 │ _nixbld17    │
│  9 │ _nixbld18    │
│ 10 │ _nixbld19    │
│ 11 │ _nixbld20    │
│ 12 │ _nixbld21    │
│ 13 │ _nixbld22    │
│ 14 │ _nixbld23    │
│ 15 │ _nixbld24    │
│ 16 │ _nixbld25    │
│ 17 │ _nixbld26    │
│ 18 │ _nixbld27    │
│ 19 │ _nixbld28    │
│ 20 │ _nixbld29    │
│ 21 │ _nixbld30    │
│ 22 │ _nixbld31    │
│ 23 │ _nixbld32    │
│ 24 │ _nixbld5     │
│ 25 │ _nixbld6     │
│ 26 │ _nixbld7     │
│ 27 │ _nixbld8     │
│ 28 │ _nixbld9     │
│ 29 │ dani         │
│ 30 │ gerry        │
│ 31 │ root         │
╰────┴──────────────╯
```

**Steps To Reproduce**

Described above.

**Expected behavior**

I expect it to show me directories (which it does) then tell me that my git tree is dirty 4 times then successfully exit and show how many packages were built.

**`nix-env --version` output**
```
nix-env (Nix) 2.21.1
```

**Additional context**

I'm on the MacOS Sequoia developer beta, and this is my first time building in the new operating system, but I'm not sure if it's the problem.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by cole-h** [comment]
This sounds related to https://github.com/NixOS/nix/issues/10892 (or at least one of the issues linked to/from it) so I'm going to close this as a duplicate. I don't know if there is a migration path for existing installs that have hit this, but fresh installs can use the workaround in https://github.com/NixOS/nix/issues/10892#issuecomment-2163311876.
