### ISSUE TITLE
fetchTarball accepts ISO images (and likely many unexpected archive formats)

### ISSUE THREAD

**Issue by andir** [NixOS/nix#10917]
**Describe the bug**

The documentation states that `fetchTarball` requires the file to be `tar` file. Apparently that isn't entirely true and Nix happily consumes other files.

![image](https://github.com/NixOS/nix/assets/638836/d178d3aa-a732-4322-8cd9-0b0e9e1cc4ff)

**Steps To Reproduce**

1. Open a `nix repl` and paste `nix-repl> builtins.readDir (builtins.fetchTarball "https://releases.nixos.org/nixos/24.05-small/nixos-24.05beta551.6d452319127a/nixos-minimal-24.05beta551.6d452319127a-x86_64-linux.iso")`
4. See that Nix happily downloaded the entire ISO and unpacked it into your store.

**Expected behavior**

It should fail to unpack the archive..
From the `libarchive.org` page it seems like the following formats are supported: tar, pax, cpio, zip, xar, lha, ar, cab, mtree, rar, and ISO images. I chose the `iso` test by random and that succeeded. 

**`nix-env --version` output**

**Additional context**

I was trying to figure out what has to be supported to be feature compatible with `fetchTarball` while working on [`npins`](https://github.com/andir/npins). My objective was to get rid of calling `nix-prefetch-url` as a subprocess in order to ship the program as a single statically linked binary..

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by puckipedia** [comment]
I depend on `mtree` support to replace the usecase for #9911 to some degree. It's also impossible to tell whether any of these have leaked into projects already, either. Someone's definitely used this to fetch rar files, or maybe 7z.
