### ISSUE TITLE
`installer` CI job broken

### ISSUE THREAD

**Issue by abathur** [NixOS/nix#10920]
Not sure what the cause is, but it looks like the `installer` CI job (and thus the installer test jobs) broke sometime between these two runs:
- https://github.com/NixOS/nix/actions/runs/8797566961
- https://github.com/NixOS/nix/actions/runs/8800514890

I don't see anything related in the diff between those two commits.

I've only looked back at the master branch.

For reference after the logs expire, the errors are like:
```
error: a 'x86_64-darwin' with features {} is required to build '/nix/store/piy60v6bajxfgk5n462jgklg1rvx9gqn-nix-2.23.0pre20240423_e3a4e40.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, kvm, nixos-test, uid-range}
```

**Comment by roberth** [comment]
Finally fixed in https://github.com/NixOS/nix/pull/11009
