### ISSUE TITLE
Hacking guide link in the readme doesn't exist

### ISSUE THREAD

**Issue by kjeremy** [NixOS/nix#10978]
## Problem

Click on "Hacking guide" in the github. It takes you to https://nix.dev/manual/nix/2.22/unstable/contributing/hacking.html which doesn't exist.
 
## Proposal

Fix the link.

## Checklist

- [ ] checked [latest Nix manual] \([source])
- [ ] checked [open documentation issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/src
[open documentation issues and pull requests]: https://github.com/NixOS/nix/labels/documentation

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by roberth** [comment]
This seems to have been fixed. When I click the link in the README, I get redirected to https://nix.dev/manual/nix/2.23/contributing/hacking.html

`nix.dev` had a broken redirect rule a while a go. Maybe this is related to that?

I'll assume this also works for you now, but feel free to reopen if it doesn't.
