### ISSUE TITLE
config.h is missing following the hacking guide:

### ISSUE THREAD

**Issue by kjeremy** [NixOS/nix#10979]
**Describe the bug**

nix does not build following the instructions at https://hydra.nixos.org/build/263397466/download/1/manual/contributing/hacking.html

**Steps To Reproduce**
clone nix
```console-session
$ nix develop
$ autoreconfPhase
$ configurePhase
$ make -j $NIX_BUILD_CORES OPTIMIZE=0
  GEN    Makefile.config
  GEN    config.h
  CXX    src/nix/develop.o
  CXX    src/nix/main.o
<command-line>: fatal error: config.h: No such file or directory
compilation terminated.
  CXX    src/libexpr/eval.o
make: *** [mk/patterns.mk:17: src/nix/main.o] Error 1
make: *** Waiting for unfinished jobs....
<command-line>: fatal error: config.h: No such file or directory
compilation terminated.
make: *** [mk/patterns.mk:17: src/nix/develop.o] Error 1
<command-line>: fatal error: config.h: No such file or directory
compilation terminated.
make: *** [mk/patterns.mk:17: src/libexpr/eval.o] Error 1
rm src/nix/generated-doc/files/profiles.md
```
**Expected behavior**

It should build

**`nix-env --version` output**

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by kjeremy** [comment]
`nix develop .#native-ccacheStdenvPackages` works.

**Comment by Ericson2314** [comment]
if you run `make all install -J<whjatever>` do you still have the problem?

I hope to soon be able to close such issues with the Meson rewrite.
