### ISSUE TITLE
nix-prefetch-url: support SRI hashes directly

### ISSUE THREAD

**Issue by eclairevoyant** [NixOS/nix#10990]
**Is your feature request related to a problem? Please describe.**
Currently, using SRI hashes with `nix-prefetch-url` require an invocation such as:
```sh
nix-prefetch-url <url> --type sha256 | xargs nix hash convert --hash-algo sha256
```

**Describe the solution you'd like**
It'd be far more convenient to have a flag to output SRI hashes directly, e.g.

```sh
nix-prefetch-url <url> --type sha256 --as-sri
```

Or alternatively, use SRI hashes by default, since they're the preferred type in nixpkgs anyway.

**Describe alternatives you've considered**
see above

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by Chatchaton** [comment]
having a subcommand `nix prefetch-url` with `--as-sri` as the default behavior would be nice

**Comment by edolstra** [comment]
`nix store prefetch-file` prints an SRI hash, maybe that works for you?
