### ISSUE TITLE
Using `nix-env -i` to install Python libraries should generate a warning message.

### ISSUE THREAD

**Issue by dan-passaro** [NixOS/nix#1100]
New users experimenting with nix might be confused to find this doesn't work:

	$ nix-env -i python3-3.5.2 python3.5-requests
	$ python -c 'import requests'

Since `nix-env -i` is used to imperatively build an environment, perhaps it makes sense that a command like

    $ nix-env -i python3.5-requests

generates a warning message, and points the user to the docs section explaining the how to use Python libraries with Nix.

**Comment by dan-passaro** [comment]
Moving to nixpkgs

**Comment by vcunat** [comment]
Actually, I believe we would need some small nix-env changes to implement this reasonably. Perhaps make it react to `meta.dontInstall` or something similar.

When a nixpkgs package is evaluated, it has no notion of how the result will be used - as dependency, installed by `nix-env`, in shell, put into `systemPackages`, etc. (Exception: `$IN_NIX_SHELL` environment variable.)
