### ISSUE TITLE
[2.23.1] nix sandbox broken on darwin

### ISSUE THREAD

**Issue by utkarshgupta137** [NixOS/nix#11002]
**Describe the bug**

Most nix commands which require building are not working on darwin anymore after upgrading to nix 2.23.1

**Steps To Reproduce**

Run any nix command such as darwin-rebuild, home-manager, nix flake run etc. which tries to trigger a build.

Error on darwin-rebuild switch:
```
error:
       … while setting up the build environment

       error: getting status of '/private/tmp/nix-build-builder.pl.drv-0/build': Permission denied
```

Error on home-manager switch:
```
       … while realising the context of path '/nix/store/v2m51qlv1l2ipahav76bj4j20j946qdh-default-conf.json'

       … while setting up the build environment

       error: getting status of '/private/tmp/nix-build-default-conf.json.drv-0/build': Permission denied
```

**Expected behavior**

No errors. I'm unable to use any nix commands which trigger a build

**`nix-env --version` output**

nix-env (Nix) 2.23.1

**Additional context**

The culprit seems to be: https://github.com/NixOS/nix/commit/20ac7811904d5ee00d1d16ed811544c9d3297e15.
My nix config: https://github.com/utkarshgupta137/nix-config/
P.S. I've enabled nix.settings.sandbox

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by utkarshgupta137** [comment]
Found a fix:
- cd /etc/nix
- sudo mv nix.conf nix.conf1
- sudo cp nix.conf1 nix.conf
- sudo vi nix.conf => change `sandbox = true` to `sandbox = false`
- sudo launchctl unload /Library/LaunchDaemons/org.nixos.nix-daemon.plist
- sudo launchctl load /Library/LaunchDaemons/org.nixos.nix-daemon.plist
- sudo rm nix.conf
- sudo mv nix.conf1 nix.conf

Basically, these are the steps to manually change nix.conf & reload nix-daemon. We also need to undo changes to nix.conf, so that darwin-rebuild can update them.
I would recommend changing your conf to set `nix.settings.sandbox` to false, until this is fixed.

Leaving it open till sandbox option is fixed on darwin.

**Comment by emilazy** [comment]
Seeing this on 2.18.4 too; seems like it must be caused by the recent Linux security fix: https://github.com/NixOS/nix/compare/2.18.3...2.18.4. Ironically this regresses the sandboxing on Darwin.

**Comment by emilazy** [comment]
I believe relaxing the read permissions on the build parent directory, at least on macOS, would address this.

**Comment by emilazy** [comment]
I will try to fix this tomorrow.

**Comment by uncenter** [comment]
> Found a fix:

Thank you @utkarshgupta137! Worked flawlessly for me, reverted to an older Nix version after getting builds working again with that fix.
