### ISSUE TITLE
Outputs from another flake is current flake's outputs

### ISSUE THREAD

**Issue by orzklv** [NixOS/nix#11008]
While trying to make use of my config flake repository from another config flake repository by importing a module, nix repeatedly traced error: attribute 'homeManagerModules' missing, but it's clearly written and tested that homeManagerModules is present at https://github.com/orzklv/nix/blob/0ad07e11ef0a71919624d63788d583a369a5bdb5/flake.nix#L130 and even paths are valid. However, after experimenting a bit, I desperately tried everything that came to my mind and eventually resolved the issue by moving copies of all homeManagerModules to current repo and include it in flake.nix. Call to dependency flake happens here: https://github.com/kolyma-labs/instances/blob/0d832eebcd7370fcd904873b481074c6ad7f070e/nixos/kolyma-3/configuration.nix#L16

Nix flake outputs from another repository is somehow replaced with current flake's outputs.

I don't know whether is this nix issue or not, if I'm mistaken, please I beg for maintainers' forgiveness and please, show me where I was supposed to file this issue.

**Steps To Reproduce**

1. You can clone my repository: https://github.com/kolyma-labs/instances
2. Modify it to fir your machine or simply add yours to nixos configs
3. Remove homeManagerModules from flake.nix
4. Remove /modules/home
5. Run nixos switch/boot from a target

**Expected behavior**

You're most likely to get this error:

```
       error: attribute 'homeManagerModules' missing
       at /nix/store/bvvrianim9rqadkddfqic64bfgnvwbfw-source/home/linux.nix:13:5:
           12|   imports = [
           13|     outputs.homeManagerModules.zsh
             |     ^
           14|     outputs.homeManagerModules.git
```

**Priorities**

I don't know whether how important this might be. My apologies, I will leave this to mods.

**Comment by cole-h** [comment]
I believe you'll need to access it via `inputs.self` -- i.e. `inputs.self.homeManagerModules.zsh`.

**Comment by orzklv** [comment]
> I believe you'll need to access it via `inputs.self` -- i.e. `inputs.self.homeManagerModules.zsh`.

However, there is no self reference at inputs? 
https://github.com/orzklv/nix/blob/0ad07e11ef0a71919624d63788d583a369a5bdb5/flake.nix#L11

Actually, I tried to add this and ended up recursing forever:
```nix
    # Highly Experimental!!!
    self = {
      url = "github:orzklv/nix/master";
      inputs.nixpkgs.follows = "nixpkgs";
    };
```

**Comment by cole-h** [comment]
Nix provides the `self` input: https://github.com/orzklv/nix/blob/0ad07e11ef0a71919624d63788d583a369a5bdb5/flake.nix#L51

**Comment by orzklv** [comment]
well, bad news...

<details>
<summary><b>Logs</b></summary>
<pre>

❯ nix store gc && sudo nixos-rebuild switch --flake github:kolyma-labs/instances --upgrade --show-trace
1 store paths deleted, 0.01 MiB freed
building the system configuration...
error:
       … while calling anonymous lambda

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/attrsets.nix:1571:24:

         1570|     let f = attrPath:
         1571|       zipAttrsWith (n: values:
             |                        ^
         1572|         let here = attrPath ++ [n]; in

       … while calling anonymous lambda

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/attrsets.nix:1205:18:

         1204|         mapAttrs
         1205|           (name: value:
             |                  ^
         1206|             if isAttrs value && cond value

       … from call site

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/attrsets.nix:1208:18:

         1207|             then recurse (path ++ [ name ]) value
         1208|             else f (path ++ [ name ]) value);
             |                  ^
         1209|     in

       … while calling anonymous lambda

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/modules.nix:242:72:

          241|           # For definitions that have an associated option
          242|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          243|

       … while evaluating the option `system.build.toplevel':

       … while calling anonymous lambda

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/modules.nix:824:28:

          823|         # Process mkMerge and mkIf properties.
          824|         defs' = concatMap (m:
             |                            ^
          825|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating definitions from `/nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/nixos/modules/system/activation/top-level.nix':

       … from call site

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/modules.nix:825:137:

          824|         defs' = concatMap (m:
          825|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          826|         ) defs;

       … while calling 'dischargeProperties'

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/modules.nix:896:25:

          895|   */
          896|   dischargeProperties = def:
             |                         ^
          897|     if def._type or "" == "merge" then

       … from call site

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/nixos/modules/system/activation/top-level.nix:71:12:

           70|   # Replace runtime dependencies
           71|   system = foldr ({ oldDependency, newDependency }: drv:
             |            ^
           72|       pkgs.replaceDependency { inherit oldDependency newDependency drv; }

       … while calling 'foldr'

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/lists.nix:121:20:

          120|   */
          121|   foldr = op: nul: list:
             |                    ^
          122|     let

       … from call site

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/lists.nix:128:8:

          127|         else op (elemAt list n) (fold' (n + 1));
          128|     in fold' 0;
             |        ^
          129|

       … while calling 'fold''

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/lists.nix:124:15:

          123|       len = length list;
          124|       fold' = n:
             |               ^
          125|         if n == len

       … while calling anonymous lambda

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/attrsets.nix:1205:18:

         1204|         mapAttrs
         1205|           (name: value:
             |                  ^
         1206|             if isAttrs value && cond value

       … from call site

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/attrsets.nix:1208:18:

         1207|             then recurse (path ++ [ name ]) value
         1208|             else f (path ++ [ name ]) value);
             |                  ^
         1209|     in

       … while calling anonymous lambda

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/modules.nix:242:72:

          241|           # For definitions that have an associated option
          242|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          243|

       … while evaluating the option `assertions':

       … while calling anonymous lambda

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/modules.nix:824:28:

          823|         # Process mkMerge and mkIf properties.
          824|         defs' = concatMap (m:
             |                            ^
          825|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating definitions from `/nix/store/301ykzb54551i5bndh075qc6wyqn50z5-source/nixos/common.nix':

       … from call site

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/modules.nix:825:137:

          824|         defs' = concatMap (m:
          825|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          826|         ) defs;

       … while calling 'dischargeProperties'

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/modules.nix:896:25:

          895|   */
          896|   dischargeProperties = def:
             |                         ^
          897|     if def._type or "" == "merge" then

       … from call site

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/modules.nix:902:11:

          901|         if def.condition then
          902|           dischargeProperties def.content
             |           ^
          903|         else

       … while calling 'dischargeProperties'

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/modules.nix:896:25:

          895|   */
          896|   dischargeProperties = def:
             |                         ^
          897|     if def._type or "" == "merge" then

       … from call site

         at /nix/store/301ykzb54551i5bndh075qc6wyqn50z5-source/nixos/common.nix:110:20:

          109|
          110|       assertions = flatten (flip mapAttrsToList cfg.users (user: config:
             |                    ^
          111|         flip map config.assertions (assertion: {

       … while calling 'flatten'

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/lists.nix:431:13:

          430|   */
          431|   flatten = x:
             |             ^
          432|     if isList x

       … while calling anonymous lambda

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/lists.nix:433:21:

          432|     if isList x
          433|     then concatMap (y: flatten y) x
             |                     ^
          434|     else [x];

       … from call site

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/lists.nix:433:24:

          432|     if isList x
          433|     then concatMap (y: flatten y) x
             |                        ^
          434|     else [x];

       … while calling 'flatten'

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/lists.nix:431:13:

          430|   */
          431|   flatten = x:
             |             ^
          432|     if isList x

       … while calling anonymous lambda

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/attrsets.nix:1096:10:

         1095|     attrs:
         1096|     map (name: f name attrs.${name}) (attrNames attrs);
             |          ^
         1097|

       … from call site

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/attrsets.nix:1096:16:

         1095|     attrs:
         1096|     map (name: f name attrs.${name}) (attrNames attrs);
             |                ^
         1097|

       … while calling anonymous lambda

         at /nix/store/301ykzb54551i5bndh075qc6wyqn50z5-source/nixos/common.nix:110:66:

          109|
          110|       assertions = flatten (flip mapAttrsToList cfg.users (user: config:
             |                                                                  ^
          111|         flip map config.assertions (assertion: {

       … from call site

         at /nix/store/301ykzb54551i5bndh075qc6wyqn50z5-source/nixos/common.nix:111:9:

          110|       assertions = flatten (flip mapAttrsToList cfg.users (user: config:
          111|         flip map config.assertions (assertion: {
             |         ^
          112|           inherit (assertion) assertion;

       … while calling 'flip'

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/trivial.nix:314:16:

          313|   */
          314|   flip = f: a: b: f b a;
             |                ^
          315|

       … while calling anonymous lambda

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/types.nix:584:22:

          583|       merge = loc: defs:
          584|         mapAttrs (n: v: v.value) (filterAttrs (n: v: v ? value) (zipAttrsWith (name: defs:
             |                      ^
          585|             (mergeDefinitions (loc ++ [name]) elemType defs).optionalValue

       … from call site

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/modules.nix:846:59:

          845|       if isDefined then
          846|         if all (def: type.check def.value) defsFinal then type.merge loc defsFinal
             |                                                           ^
          847|         else let allInvalid = filter (def: ! type.check def.value) defsFinal;

       … while calling 'merge'

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/types.nix:888:22:

          887|         check = x: isAttrs x || isFunction x || path.check x;
          888|         merge = loc: defs:
             |                      ^
          889|           (base.extendModules {

       … from call site

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/modules.nix:242:28:

          241|           # For definitions that have an associated option
          242|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                            ^
          243|

       … while calling 'mapAttrsRecursiveCond'

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/attrsets.nix:1201:5:

         1200|     f:
         1201|     set:
             |     ^
         1202|     let

       … from call site

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/modules.nix:234:33:

          233|           ({ inherit lib options config specialArgs; } // specialArgs);
          234|         in mergeModules prefix (reverseList collected);
             |                                 ^
          235|

       … while calling 'reverseList'

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/lists.nix:1116:17:

         1115|   */
         1116|   reverseList = xs:
             |                 ^
         1117|     let l = length xs; in genList (n: elemAt xs (l - n - 1)) l;

       … from call site

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/modules.nix:229:25:

          228|       merged =
          229|         let collected = collectModules
             |                         ^
          230|           class

       … while calling anonymous lambda

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/modules.nix:445:37:

          444|
          445|     in modulesPath: initialModules: args:
             |                                     ^
          446|       filterModules modulesPath (collectStructuredModules unknownModule "" initialModules args);

       … from call site

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/modules.nix:446:7:

          445|     in modulesPath: initialModules: args:
          446|       filterModules modulesPath (collectStructuredModules unknownModule "" initialModules args);
             |       ^
          447|

       … while calling 'filterModules'

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/modules.nix:413:36:

          412|       # modules recursively. It returns the final list of unique-by-key modules
          413|       filterModules = modulesPath: { disabled, modules }:
             |                                    ^
          414|         let

       … while calling anonymous lambda

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/modules.nix:439:31:

          438|           disabledKeys = concatMap ({ file, disabled }: map (moduleKey file) disabled) disabled;
          439|           keyFilter = filter (attrs: ! elem attrs.key disabledKeys);
             |                               ^
          440|         in map (attrs: attrs.module) (builtins.genericClosure {

       … from call site

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/modules.nix:400:22:

          399|           let
          400|             module = checkModule (loadModule args parentFile "${parentKey}:anon-${toString n}" x);
             |                      ^
          401|             collectedImports = collectStructuredModules module._file module.key module.imports args;

       … while calling anonymous lambda

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/modules.nix:359:11:

          358|         then
          359|           m:
             |           ^
          360|             if m._class != null -> m._class == class

       … from call site

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/modules.nix:400:35:

          399|           let
          400|             module = checkModule (loadModule args parentFile "${parentKey}:anon-${toString n}" x);
             |                                   ^
          401|             collectedImports = collectStructuredModules module._file module.key module.imports args;

       … while calling 'loadModule'

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/modules.nix:336:53:

          335|       # Like unifyModuleSyntax, but also imports paths and calls functions if necessary
          336|       loadModule = args: fallbackFile: fallbackKey: m:
             |                                                     ^
          337|         if isFunction m then

       … from call site

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/modules.nix:337:12:

          336|       loadModule = args: fallbackFile: fallbackKey: m:
          337|         if isFunction m then
             |            ^
          338|           unifyModuleSyntax fallbackFile fallbackKey (applyModuleArgs fallbackKey m args)

       … while calling 'isFunction'

         at /nix/store/88ii9yk46c0acdrv14lgvpxn0a23afv8-source/lib/trivial.nix:929:16:

          928|   */
          929|   isFunction = f: builtins.isFunction f ||
             |                ^
          930|     (f ? __functor && isFunction (f.__functor f));

       error: attribute 'homeManagerModules' missing

       at /nix/store/pwracw98mc7lnpsm44klmssw632m8lba-source/home/linux.nix:12:5:

           11|   imports = [
           12|     inputs.self.homeManagerModules.zsh
             |     ^
           13|     inputs.self.homeManagerModules.git

</pre>
</details>

https://github.com/orzklv/nix/blob/fd20d4fed90b2a01c79b9a0bbd8a14bc7505e3fe/home/linux.nix#L11-L20
