### ISSUE TITLE
Website/cloudfront issues

### ISSUE THREAD

**Issue by traleig1** [NixOS/nix#1103]
A lot of the links that are ranking on Google for nixos seem to be pointing to dead pages on old versions of the manual. For example, searching for [network settings](https://www.google.com/search?q=nixos+network+settings):
- top result is http://nixos.org/releases/nixos/14.12/nixos-14.12.374.61adf9e/manual/sec-networking.html'
- this redirects to https://d3g5gsiof5omrk.cloudfront.net/nixos/14.12/nixos-14.12.374.61adf9e/manual/sec-networking.html'
- This is a 404 with an XML body, which seems to be getting issued from cloudfront, rather than the end server

(single quotes at the end of links are in the original, but removing them doesn't change the result)

```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <Key>nixos/14.12/nixos-14.12.374.61adf9e/manual/sec-networking.html'</Key>
  <RequestId>082DB08F12942F51</RequestId>
  <HostId>z0PAZBTTFBZi7yYhGnu8HELk9EAfbuMDiY9myOFYKk75dxcl3VdbXsd0wUtgIEXSDUxK86bm64E=</HostId>
</Error>
```

A side note - if keeping older version of the manual online is a priority, it might be a good idea to provide links to different versions of the manual (as e.g., Postgres does), but set `rel="canonical"` to be the most up-do-date version (to avoid the issue Postgres has of filling search results with duplicates and high-ranking old versions).

**Comment by domenkozar** [comment]
Moved to https://github.com/NixOS/nixos-homepage/issues/107
