### ISSUE TITLE
New expr-c EvalState construction is causing build problems for 24.05.

### ISSUE THREAD

**Issue by roberth** [NixOS/nix#11039]
_Originally posted  in https://github.com/NixOS/nix/pull/10913#discussion_r1665923634_

This is causing problems for 24.05.
Might a simpler solution be feasible?

https://github.com/NixOS/nixpkgs/pull/324408/checks?check_run_id=27026504754

**Comment by emilazy** [comment]
See https://github.com/NixOS/nixpkgs/pull/326172/files for the fix. This is currently broken in the flake, too.

**Comment by emilazy** [comment]
FWIW I think using this C++ feature is totally fine. It’s only `x86_64-darwin`’s ancient SDK situation that even made it a problem in any way. The fix shouldn’t impact macOS version compatibility at all, and I believe @reckenrode mentioned we might as well even just patch out the Clang error that needed working around as it doesn’t apply to the Nixpkgs use‐case.
