### ISSUE TITLE
Nixos cache returns binary/octet-stream content type

### ISSUE THREAD

**Issue by adnelson** [NixOS/nix#1104]
This should be `application/octet-stream`.  Looking at the IANA database, there is an [entry](https://www.iana.org/assignments/media-types/application/octet-stream) for the "application" prefix but not for the "binary". Also using "binary/octet-stream" breaks hitting the API with the Haskell `servant-client` library (without writing a custom media type).

**Comment by adnelson** [comment]
To reproduce:

```
$ curl -v https://cache.nixos.org/0y3h25fh9ssvxcas4zil881llvm6a68f.narinfo
*   Trying 52.84.13.153...
* Connected to cache.nixos.org (52.84.13.153) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
* Server certificate: cache.nixos.org
* Server certificate: RapidSSL SHA256 CA - G3
* Server certificate: GeoTrust Global CA
> GET /0y3h25fh9ssvxcas4zil881llvm6a68f.narinfo HTTP/1.1
> User-Agent: curl/7.40.0
> Host: cache.nixos.org
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: binary/octet-stream
< Content-Length: 1084
< Connection: keep-alive
< Date: Mon, 24 Oct 2016 03:22:09 GMT
< Last-Modified: Sun, 14 Aug 2016 17:48:23 GMT
< ETag: "81386fc0598cf7185ee7e0c35fc19786"
< Accept-Ranges: bytes
< Server: AmazonS3
< Age: 10
< X-Cache: Hit from cloudfront
< Via: 1.1 6b2b8528a8a6d02156c694e5398d8b75.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: kPx6DUU8T6hDNypvTndHye0dBwnpnwA0FnAkeRK1-gzgYBjKEksODA==
<
StorePath: /nix/store/0y3h25fh9ssvxcas4zil881llvm6a68f-ghc-7.10.2
URL: nar/1lmq4yh84axzfagyyj7sm734d3ndr7rql351gkim7as2dk6wsmwf.nar.xz
Compression: xz
FileHash: sha256:1lmq4yh84axzfagyyj7sm734d3ndr7rql351gkim7as2dk6wsmwf
FileSize: 68311196
NarHash: sha256:0z00qn7g2ml1ya5p91qmwjndg7xx8a9hwhfqnv51rjc8idwsr85y
NarSize: 696799032
References: 0y3h25fh9ssvxcas4zil881llvm6a68f-ghc-7.10.2 288zxgs8471z0h5r1p09i9jibilvczj4-gmp-6.1.1 49qbl2kxxd5d9k6wadkz79dsl4hpsvah-ghc-7.10.2-doc 716mpwxqg1n49h34ayc8axx591sw88cm-bash-4.3-p42 agr6kby4s30h1rgbc3qc43wadi46d2d0-Libsystem-osx-10.9.5 gmb9mxkm5mqfnhlav16rx5x7wf070qqf-ncurses-5.9-dev k52bd04ysj82r0kmqz1r473w7ij3kazp-gmp-6.1.1-dev m3fsfc4q13d8mahlix7v2fifmnbqx7lh-cctools-binutils-darwin m7xmj6hb2ar7gvzhp1przpiyami780zk-libiconv-osx-10.9.5 r7kb97r2z8ip28vimxp3sl3k0ihlrb78-ncurses-5.9 szlnx88rj8hrmpfh1wr8gglypl6gdnrc-perl-5.22.2 x1ggsi9mfah810sgga461ylisxp7xmcq-clang-wrapper-3.7.1 znyn4148licl0vx7dgr4i9k3is81p57g-coreutils-8.25
Sig: cache.nixos.org-1:gzSzJgVUn66O/6dP60cL0jWLmYEy/LTgCgmIHykLOVUECCiuPoNevdzTP4tGOCIyXN/kKLQt1kK41PzkqrlWDw==
* Connection #0 to host cache.nixos.org left intact
```

As a side note (though certainly not part of this issue), it would be super awesome if JSON were a supported content type for serving `narinfo` and `nix-cache-info` data.

**Comment by jmitchell** [comment]
I couldn't find `binary/octet-stream` in any NixOS repos. Not sure where it's coming from.

Do we just need to add another `AddType` to the webserver's [`services.httpd.extraConfig`](https://github.com/NixOS/nixos-org-configurations/blob/dd9a582cddee7ab5bf6747106bfbefc434077d0c/nixos-org/webserver.nix#L95)?

**Comment by vcunat** [comment]
cache.nixos.org is served by Amazon S3 (nothing nix-based), so I don't expect we can really do much about the `Content-Type` header.

**Comment by vcunat** [comment]
Actually, it seems one *can* specify the header when uploading to S3: http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html

**Comment by edolstra** [comment]
Nix does not rely on the MIME type anywhere, so this isn't a problem IMHO. Yes it would be nice if S3 didn't have such a strange default but that should be taken up with AWS.

**Comment by vcunat** [comment]
@edolstra: I can't see explicit setter for content type in the [C++ API](http://sdk.amazonaws.com/cpp/api/LATEST/class_aws_1_1_s3_1_1_model_1_1_put_object_request.html), unlike e.g. java, but maybe it would just work to apply this to nix:
```diff
diff --git a/src/libstore/s3-binary-cache-store.cc b/src/libstore/s3-binary-cache-store.cc
index c11f2b0..fcbd4aa 100644
--- a/src/libstore/s3-binary-cache-store.cc
+++ b/src/libstore/s3-binary-cache-store.cc
@@ -143,7 +143,8 @@ struct S3BinaryCacheStoreImpl : public S3BinaryCacheStore
         auto request =
             Aws::S3::Model::PutObjectRequest()
             .WithBucket(bucketName)
-            .WithKey(path);
+            .WithKey(path)
+            .AddMetadata("Content-Type", "application/octet-stream");
 
         auto stream = std::make_shared<std::stringstream>(data);
 
```

**Comment by vcunat** [comment]
... or bug their support to have a valid default value.

**Comment by edolstra** [comment]
Sure, I'm not opposed to setting a MIME type, but it wouldn't fix the millions of files already in the binary cache.

**Comment by vcunat** [comment]
Well, almost all would be fixed after the next stdenv rebuild. That doesn't seem too far future.
