### ISSUE TITLE
"./configure" error

### ISSUE THREAD

**Issue by luckypoem** [NixOS/nix#1105]
hi.

./configure: line 5937: syntax error near unexpected token `OPENSSL,'
./configure: line 5937: `PKG_CHECK_MODULES(OPENSSL, libcrypto, CXXFLAGS="$OPENSSL_CFLAGS $CXXFLAGS")'
root@AR:/home/brite/nix#

how to fix it?

**Comment by domenkozar** [comment]
http://nixos.org/nix/manual/#chap-hacking
