### ISSUE TITLE
Nix Installer tries to install to 301 on MacOS Sequoia but fails due to user being there

### ISSUE THREAD

**Issue by Eveeifyeve** [NixOS/nix#11068]
## Platform

- [x] macOS Sequoia beta 2

## Additional information

Nix tries to install a user on 301 but is taken by `_modelmanagerd           301` which might mean apple intelligence is taking user space I had to specify what user id I want nix to install which 400 which works.

## Output

```log
I am executing:

    $ sudo /usr/bin/dscl . create /Users/_nixbld1 UniqueID 301

Creating the Nix build user (#1), _nixbld1

<main> attribute status: eDSRecordAlreadyExists
<dscl_cmd> DS Error: -14135 (eDSRecordAlreadyExists)
```

</details>

## To get around it 
add `NIX_FIRST_BUILD_UUID=400` to temporarily fix the issue.
and when uninstalling follow the guide to uninstall the users to fix the `_nixbuild1` is a user: https://nix.dev/manual/nix/2.22/installation/uninstall

## The solution
So I would say adjust the user id to something like `400-450` or do what @tomberek is implement the automatic uuid assignment for MacOS.

## Priorities
#2242
#6153
#10892
https://mastodon.social/@ryanbooker/112597391954278800

### Tags 
@tomberek

**Comment by abathur** [comment]
This is already being tracked in the pinned issue you linked:
- #10892

There's also a draft fix open in:
- #10919
