### ISSUE TITLE
installed flox package post-installation script subprocess returned error exit status 1

### ISSUE THREAD

**Issue by barstoolbluz** [NixOS/nix#11067]
## Platform

- [ ] Linux: 
- [ ] macOS
- [Ubuntu 22.04 ] WSL

## Additional information

Clean install in fresh WSL environment. Had pre-installed build-essentials and a bunch of other software development dependencies. This was with a nightly build, but error also occurs with the standard 1.1 build.

## Output

daedalus@anaximander:~/downloads$ sudo dpkg -i flox-1.1.0-37-g23847910%2B1720086158.x86_64-linux.deb
[sudo] password for daedalus:
(Reading database ... 98254 files and directories currently installed.)
Preparing to unpack flox-1.1.0-37-g23847910%2B1720086158.x86_64-linux.deb ...
Unpacking flox (1.1.0-37-g23847910) over (1.1.0) ...
Setting up flox (1.1.0-37-g23847910) ...
Installing new version of config file /etc/apt/sources.list.d/flox.list ...
Installing new version of config file /etc/flox-version ...
Installation failed. See /tmp/flox-installation.log.1720200376 for logs.
dpkg: error processing package flox (--install):
 installed flox package post-installation script subprocess returned error exit status 1
Processing triggers for man-db (2.10.2-1) ...
Errors were encountered while processing:
 flox

```log

<!-- paste console output here and remove this comment -->

```

</details>

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).
[flox-installation.log.1720200376.log](https://github.com/user-attachments/files/16131362/flox-installation.log.1720200376.log)

**Comment by tomberek** [comment]
Please open this as an issue in https://github.com/flox/flox as this is not an upstream Nix issue. I'll take a look. Thanks.
