### ISSUE TITLE
I had nix installed before and attempting to re-install errors out with backup related issue

### ISSUE THREAD

**Issue by enesyilmazer** [NixOS/nix#11074]
## Platform

- [ ] macOS

## Additional information

I have just followed https://nixos.org/download/#nix-install-macos

## Output

<details><summary>Output</summary>

```log

---- oh no! --------------------------------------------------------------------
I back up shell profile/rc scripts before I add Nix to them.
I need to back up /etc/bash.bashrc to /etc/bash.bashrc.backup-before-nix,
but the latter already exists.

Here's how to clean up the old backup file:

1. Back up (copy) /etc/bash.bashrc and /etc/bash.bashrc.backup-before-nix
   to another location, just in case.

2. Ensure /etc/bash.bashrc.backup-before-nix does not have anything
   Nix-related in it. If it does, something is probably quite
   wrong. Please open an issue or get in touch immediately.

3. Once you confirm /etc/bash.bashrc is backed up and
   /etc/bash.bashrc.backup-before-nix doesn't mention Nix, run:
   mv /etc/bash.bashrc.backup-before-nix /etc/bash.bashrc

We'd love to help if you need it.

You can open an issue at
https://github.com/NixOS/nix/issues/new?labels=installer&template=installer.md

Or get in touch with the community: https://nixos.org/community

```

</details>

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by enesyilmazer** [comment]
I forgot to add the contents of

enes.yilmazer-admin$ cat /etc/bash.bashrc.backup-before-nix 

# Nix
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
# End Nix

**Comment by abathur** [comment]
It's a sign nix was installed before the backups were taken, so you may need to clean it up manually.

I'd try:
1. Run `grep "End Nix" /etc/*` and manually remove those lines from any matching files that don't have the backup-before-nix extension.
2. Remove all of the files with the backup-before-nix extension.
3. Follow the remaining appropriate macOS/Linux uninstall instructions before reinstalling it: https://nixos.org/manual/nix/stable/installation/uninstall.html#macos
