### ISSUE TITLE
Can't find Firefox in GNOME on Fedora

### ISSUE THREAD

**Issue by siddharthist** [NixOS/nix#1107]
This is definitely a stupid question, so please have patience. I'm trying nix on a non-NixOS distribution (Fedora) for the first time, and have installed Firefox with Nix and uninstalled it via `dnf`. However, Firefox no longer appears in the Gnome menu. Is there a way to fix this?

**Comment by domenkozar** [comment]
This belongs to nixpkgs repo

**Comment by siddharthist** [comment]
@domenkozar Sorry, about that, thank you for pointing it out! I've opened one there: https://github.com/NixOS/nixpkgs/issues/19934

**Comment by copumpkin** [comment]
@domenkozar https://github.com/NixOS/nix/issues/1008
