### ISSUE TITLE
Support alternative to default.nix names as default files

### ISSUE THREAD

**Issue by danbst** [NixOS/nix#1109]
->dissatisfaction on
I personally have lot's of pain editing Nixpkgs sources, because my editor of choice is currently... Notepad++ for Windows.

This pain goes out from the way how Notepad++ shows filenames of multiple open files. It shows them in a top bar, in horizontal list. And, because of screen width limit, it shows only filename (without path). As a result, when I open multiple `default.nix` files I can spend lot's of time to find the one I want to edit.

And my search service of choice (GitHub nixpkgs code search) often fails to find required package. For example, [searching for nginx](https://github.com/NixOS/nixpkgs/search?utf8=%E2%9C%93&q=nginx) gets `pkgs/servers/monitoring/prometheus/nginx-exporter.nix` first in list and `nixos/modules/services/web-servers/nginx/default.nix` 9th.
->dissatisfaction off

I propose to support the naming of default nix file not only `default.nix`, but `$parent_directory_name.nix` too. After new style released, we wait two-three years and then rename all `default.nix` to `$parent_directory_name.nix`. Thus we will get rid of meaningless `default.nix` filenames in standard nixpkgs.

For example, `nixos/modules/services/web-servers/nginx/default.nix` becomes `nixos/modules/services/web-servers/nginx/nginx.nix`, but usage remains `import <nixos/modules/services/web-servers/nginx>`

PS. We can do the rename even now by renaming all default usages to explicit filenames, but I don't know how much community likes the ability to import folder using `default.nix`.

**Comment by domenkozar** [comment]
I recommend switching the editor. Conventions are going to stay for a reason and it's easier to switch an editor than waste maintainer time renaming files.

**Comment by danbst** [comment]
@domenkozar which editor can you recommend?

**Comment by domenkozar** [comment]
Atom

**Comment by copumpkin** [comment]
I've honestly kind of wanted this for a while too, so I'm kind of sad to see you close it without considering it at all. The prevalence of default.nix in our repos makes filenames effectively useless without considering the complete path to them, which seems undesirable to me regardless of editor.

**Comment by vcunat** [comment]
The parent-name suggestion feels like having lots of magic in it. Moreover, "adding support" for this would mean to have to introduce some switch determining which behavior is used, defaulting to the old one for compatibility, ... altogether I also don't think it's worth pursuing.

**Comment by domenkozar** [comment]
@copumpkin `convention over configuration` is a good default. I think changing that will cause more pain than gain, I've seen it happen in different projects.

**Comment by danbst** [comment]
@vcunat 

>The parent-name suggestion feels like having lots of magic in it

This is subjective. The `default.nix` looks for me fairly arbitrary (akin to `__init__.py`, `Setup.hs`, `readme.md` and `index.html`). It wouldn't be a much a problem, if it wasn't so widely used. 6037/8599 .nix files in nixpkgs are `default.nix`.

But I think, Domen is right here, too late to change smth

**Comment by vcunat** [comment]
Yes, it *is* arbitrary. Starting from scratch would be a different situation.

In non-nixpkgs expressions that fit into one file I typically avoided creating a directory at all and called it just `package-name.nix`, even though importing a directory is a more uniform way.
