### ISSUE TITLE
uncaught exception: eDSRecordAlreadyExists

### ISSUE THREAD

**Issue by jurajpiar** [NixOS/nix#11107]
## Platform

- [ ] Linux: 
- [x] macOS
- [ ] WSL

## Output

<details><summary>Output</summary>

```log

I am executing:

    $ sudo /usr/bin/dscl . create /Users/_nixbld1 UniqueID 301

Creating the Nix build user (#1), _nixbld1

<main> attribute status: eDSRecordAlreadyExists
<dscl_cmd> DS Error: -14135 (eDSRecordAlreadyExists)
```

</details>

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by jurajpiar** [comment]
dup https://github.com/NixOS/nix/issues/11015

**Comment by cole-h** [comment]
If you're on the macOS 15 beta, this may also be related to https://github.com/NixOS/nix/issues/10892.
