### ISSUE TITLE
Missing a device specified in a fileSystem entry will crash the system

### ISSUE THREAD

**Issue by andjscott** [NixOS/nix#1114]
`nixos-generate-config` can add devices to `hardware-configuration.nix` that may not be available every boot.

``` nix
fileSystems."/mnt" =
    { device = "/dev/missing";
    };
```

After booting, the system doesn't start the display-manager and instead shows a tty login. Eventually services are stopped and the system drops to emergency mode.

related:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=743265

Should `nixos-generate-config` add `nofail` as an option to non-essential\* filesystems or show a warning?

*non-essential being mounts in `/mnt`, `/media`, etc.

**Comment by edolstra** [comment]
This looks like a NixOS issue. Could you recreate this issue in the https://github.com/NixOS/nixpkgs repo (with a `nixos` label)? Thanks!

**Comment by copumpkin** [comment]
@edolstra #1008 😄
