### ISSUE TITLE
Please document "tarball-ttl" option

### ISSUE THREAD

**Issue by peti** [NixOS/nix#1115]
https://github.com/NixOS/nix/blob/master/src/libstore/download.cc#L522 uses a config option called `tarball-ttl`, but I cannot find any documentation for that option in the man pages. I suppose this should be documented in the `nix.conf` man page?

**Comment by domenkozar** [comment]
It is documented in https://nixos.org/nix/manual/#ssec-builtins under "builtins.fetchTarball", but I agree it should be in the reference.
