### ISSUE TITLE
Cross-builds failing on "struct statvfs"

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#11164]
**Describe the bug**

A number of cross-builds are failing on `struct statvfs` not being defined despite `statvfs()` having been detected, e.g. https://hydra.nixos.org/build/267279835

**Steps To Reproduce**

**Expected behavior**

**`nix-env --version` output**

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by Ericson2314** [comment]
#11230 should have fixed
