### ISSUE TITLE
daemon socket not found

### ISSUE THREAD

**Issue by Salvi03** [NixOS/nix#11185]
## Platform

- Linux: Debian 12 bookworm (aarch64)

## Additional information

I was trying the quick startup guide, the /nix directory doesn't exist, I'm literally just doing curl -L https://nixos.org/nix/install | sh

## Output

<details><summary> </summary>

```log

% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  4267  100  4267    0     0   6756      0 --:--:-- --:--:-- --:--:--  6756
downloading Nix 2.23.3 binary tarball for aarch64-linux from 'https://releases.nixos.org/nix/nix-2.23.3/nix-2.23.3-aarch64-linux.tar.xz' to '/tmp/nix-binary-tarball-unpack.iKXs6cDP4Z'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20.0M  100 20.0M    0     0  12.8M      0  0:00:01  0:00:01 --:--:-- 12.8M
Note: a multi-user installation is possible. See https://nixos.org/manual/nix/stable/installation/installing-binary.html#multi-user-installation
performing a single-user installation of Nix...
directory /nix does not exist; creating it by running 'mkdir -m 0755 /nix && chown salv1 /nix' using sudo
copying Nix to /nix/store...

error: cannot connect to socket at '/nix/var/nix/daemon-socket/socket': No such file or directory
/tmp/nix-binary-tarball-unpack.iKXs6cDP4Z/unpack/nix-2.23.3-aarch64-linux/install: unable to register valid paths
```

</details>

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by abathur** [comment]
I don't know why that'd be happening during a single-user install, which doesn't even use the daemon.

It sounds like maybe:
- https://github.com/NixOS/nix/issues/2401#issuecomment-1107851332


If that doesn't work, I'd look into whether you have artifacts of an old install, especially one made by another package manager.

**Comment by Salvi03** [comment]
I checked my list of installed packages and I had nix-bin/stable installed, I purged it and I still have the same problem, my env doesn't have anything nix related either

**Comment by Salvi03** [comment]
For whatever reason the installation worked fine when I used sudo sh, I chowned the nix directory and copied all the files I needed in my home directory, I'm now closing the issue.
