### ISSUE TITLE
Progress bar says `N copied (M failed)` but no details

### ISSUE THREAD

**Issue by roberth** [NixOS/nix#11198]
**Describe the bug**

Regularly my progress bar looks as follows:

```
[1/156/210 built, 200 copied (12 failed) (908.4/909.2 MiB), 270.4 MiB DL] building nix-2.24.0pre20240727_dirty on ssh://agent-2:   CXX    tests/unit/libutil/chunked-vecto
                              ^^^^^^^^^ bold red color
```

(Also, shouldn't it say `realised`?)

**Steps To Reproduce**

Build something. I have cache.nixos.org and 3 cachix caches in my substituter configuration.

**Expected behavior**

Depending on the circumstance:

- **HTTP 404 for narinfo**: report nothing at all I _think_ this already works
- **HTTP 4xx/5xx for nar**: print a proper log line so that the problem can be known and fixed

**`nix-env --version` output**

`nix-env (Nix) 2.24.0pre20240718_8ce4287`

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by cole-h** [comment]
I had been noticing this too, but thought it was related to the fact that the machine I was seeing it on has one of those cursed Intel 13th gen processors (the ones that they refuse to recall despite manufacturing issues and voltage issues causing instability.... but that's neither here nor there).

Notably, this doesn't happen on 2.23.3, for me.

**Comment by roberth** [comment]
Also getting this on a 9th gen, and all the way back to Nix 2.4.
