### ISSUE TITLE
`nix dump-path` requires nix-command to be enabled

### ISSUE THREAD

**Issue by flokli** [NixOS/nix#11225]
**Describe the bug**

```
❯ nix dump-path /nix/store/kwmqk7ygvhypxadsdaai27gl6qfxv7za-hello-2.12.1
warning: 'dump-path' is a deprecated alias for 'store dump-path'
error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override
```

Used to work fine in Nix 2.3, and probably a few other recent Nix versions.

Used in `nix-serve` for example: https://github.com/edolstra/nix-serve/blob/master/nix-serve.psgi#L66, effectively breaking it on systems without `nix-command` being enabled.

**Expected behavior**

Don't gate `nix dump-path` behind the `nix-command` xp. It was "stable" before, and there's code (like nix-serve) out there relying on it.

**`nix-env --version` output**
```
nix-env (Nix) 2.18.5
```

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by edolstra** [comment]
I can't reproduce this.
```
nix --experimental-features 'nix-command' store dump-path /nix/store/94d0gz9z6kbc8x5qqisdhjrap6y9casd-coreutils-full-9.5 > /dev/null
```
works fine.

Note that if you run `nix store dump-path` without arguments in a flake directory, it will try to evaluate the flake, which requires the `flakes` experimental feature.

**Comment by flokli** [comment]
See https://github.com/NixOS/nixpkgs/pull/331230, try running the passthru tests from a nixpkgs checkout without adding Nix 2.3 to $PATH, but pkgs.nix.

**Comment by flokli** [comment]
Running it without a parameter indeed exposes the flake behaviour (and error message).

The nixpkgs test is however also failing, due to the `nix-command` commands being made experimental again. I updated the issue accordingly.

**Comment by edolstra** [comment]
The `nix` CLI was always experimental, but wasn't feature-gated initially. It will become stable again in the future (see #7701).
