### ISSUE TITLE
`self` flake input should contain previous commit hash

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [NixOS/nix#11227]
**Is your feature request related to a problem? Please describe.**
When code depends on `self` git commit, it is very annoying to not to have it when the branch is dirty

**Describe the solution you'd like**
`self` input should have `prevRev` and `prevShortRev` attributes representing commit before current one
Alternatively `rev` and `shortRev` in case of branch being dirty could have latest commit hash with postfix `-dirty` but this would be a breaking change 

**Describe alternatives you've considered**
Implement logic where commit hash is required at runtime 

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by roberth** [comment]
IIRC a `dirtyRev` attribute is available in this situation, with the value you suggest.

**Comment by gytis-ivaskevicius** [comment]
Thanks! I really had no idea that this existed, it even has postfix `-dirty`. Either I came up with the same solution or I must have seen this somewhere before :thinking:
