### ISSUE TITLE
Allow disabling import-from-derivation

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#1122]
Mostly for Hydra, it would be useful to have an option to disable import-from-derivation. This would help to catch cases like NixOS/nixpkgs@0ba3d429a758cec15545fc11c9d3fd1424c5c5f8 where we start building all of stdenv from the evaluator rather than the queue runner.

**Comment by Ericson2314** [comment]
Is there an issue open for sending import-from-derivation to the queue runner?

**Comment by domenkozar** [comment]
Done in https://github.com/NixOS/nix/issues/1265
