### ISSUE TITLE
Add a VM test for S3BinaryCacheStore

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#11238]
**Is your feature request related to a problem? Please describe.**

This will help us to avoid regressions like #11237.

The VM test can use `minio` to simulate S3.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by Ericson2314** [comment]
Yes I remember wanting this in the past too, last time we had such a regression.
