### ISSUE TITLE
Unexpected no-op nix-2.24.1 release.

### ISSUE THREAD

**Issue by trofi** [NixOS/nix#11260]
**Describe the bug**

Noticed that `2.24.1` was tagged and planned to package the release for the distribution.
But I found no difference compared to `2.24.0`: https://github.com/NixOS/nix/compare/2.24.0...2.24.1

Updating to it seems like a waste of everyone's time. An accidental release? Worth deleting?

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by roberth** [comment]
This tag seems to have gone unnoticed until the 2.24.2 release.
Deleting the tag will break expressions that fetch it, so I'm inclined to just keep it and ignore it.
Users can upgrade to 2.24.2 now, which does have its own set of changes.
