### ISSUE TITLE
Flake inputs for Github doesn't respect submodules

### ISSUE THREAD

**Issue by myclevorname** [NixOS/nix#11275]
**Describe the bug**

In a flake of mine, I had this:
```nix
  inputs = {
    ndless = {
      flake = false;
      # If build_toolchain.sh updates, I have to update the flake
      url = "github:ndless-nspire/Ndless/78a89950730f3a3c9636e9f8170e8b98276779ed?submodules=1";
    };
    flake-utils.url = "github:numtide/flake-utils";
    nixpkgs.url = "github:NixOS/nixpkgs";
  };
```
When I ran `nix flake update; nix build`, I get this error in the Makefile:
> Makefile:6: *** Run `git submodule init' and `git submodule update' to checkout the submodules.  Stop.

If you have a problem with a specific package or NixOS,
you probably want to file an issue at https://github.com/NixOS/nixpkgs/issues. 

**Steps To Reproduce**

1. Download this flake: [bug.tar.xz.txt](https://github.com/user-attachments/files/16567246/bug.tar.xz.txt) and remove the `.txt` extension because Github didn't let me upload an xzipped tarball.
2. Extract the tarball, and run `git init; git add flake.lock flake.nix` in the directory
3. Run `nix build`
4. Get this error
```
warning: Git tree '/home/clevor/Code/flakes/ndless' is dirty
error: builder for '/nix/store/gbx72cj3gsy2rn53lhilbc1xql7n70ib-ndless-sdk.drv' failed with exit code 2;
       last 10 log lines:
       > source root is source
       > calling 'postUnpack' function hook '_updateSourceDateEpochFromSourceRoot'
       > Running phase: patchPhase
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > calling 'preConfigure' function hook '_multioutConfig'
       > no configure script, doing nothing
       > Running phase: buildPhase
       > build flags: -j4 SHELL=/nix/store/i1x9sidnvhhbbha2zhgpxkhpysw6ajmr-bash-5.2p26/bin/bash
       > Makefile:6: *** Run `git submodule init' and `git submodule update' to checkout the submodules.  Stop.
       For full logs, run 'nix log /nix/store/gbx72cj3gsy2rn53lhilbc1xql7n70ib-ndless-sdk.drv'.
```

**Expected behavior**

The Makefile shouldn't give that error because I set `?submodules=1`. Alternatively, the option `submodules` can be added to the Github (and maybe Gitlab) input type for consistency with the git input type

**`nix-env --version` output**
nix-env (Nix) 2.18.5

**Additional context**

I am trying to turn Ndless into a Nix flake to install on my system. My NixOS system is [here](https://github.com/myclevorname/nix-system). Please use the system `github:myclevorname/nix-system#clevor-laptop-nixos-generic`.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by roberth** [comment]
We have significantly revised fetching since 2.18.
Could you try with release `2.24`?

As a workaround, the `git:` scheme (as opposed to `github:`) supports submodules, and is implemented quite differently.

**Comment by myclevorname** [comment]
Using git worked, thanks.
