### ISSUE TITLE
downloadTarball() returns an uncachable accessor

### ISSUE THREAD

**Issue by Frontear** [NixOS/nix#11271]
**Describe the bug**

This was not found by me, but another fellow Nix/OS user. They were following a guide at https://nix.dev/tutorials/first-steps/reproducible-scripts#the-script when they noticed both very slow speeds, and consistently using up 100MB~ of storage every single time the script was run.

@max-privatevoid ran the script with some extra logging added to it (`#! nix-shell -vvv --log-format bar-with-logs`) and found that the source paths are labelled as uncacheable.

Running with Nix 2.18 (the default on nixpkgs) does NOT have this issue, leaning into the theory that this is a regression, and a fairly significant one at that.

**Reproduction steps:**

1. Write the script below to your system
2. Ensure you're on a newer version of Nix (`nix shell nixpkgs#nixVersions.latest` or master here)
3. `chmod +x script && ./script 2>&1 | grep "uncacheable"`

```bash
#!/usr/bin/env nix-shell
#! nix-shell -i bash --pure
#! nix-shell -p bash cacert curl jq python3Packages.xmljson
#! nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/2a601aafdc5605a5133a2ca506a34a3a73377247.tar.gz
#! nix-shell -vvv --log-format bar-with-logs

curl https://github.com/NixOS/nixpkgs/releases.atom | xml2json | jq .
```

`$ nix-env --version`
nix-env (Nix) 2.23.3

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by max-privatevoid** [comment]
The infinite growth thing is a misinterpretation. It always umpacks to *the same store path*, so disk usage ultimately stays constant. The problem is that it always unpacks, which takes time and might cause some SSD wear.

**Comment by edolstra** [comment]
As a workaround, you can use
```
#! nix-shell -I nixpkgs=flake:https://github.com/NixOS/nixpkgs/archive/2a601aafdc5605a5133a2ca506a34a3a73377247.tar.gz
```
or even better
```
#! nix-shell -I nixpkgs=flake:github:NixOS/nixpkgs/2a601aafdc5605a5133a2ca506a34a3a73377247
```
