### ISSUE TITLE
nix command unavailable after a switch

### ISSUE THREAD

**Issue by deekshith991** [NixOS/nix#11299]
hi i have installed a nix single user on ubuntu 24.04. Few minutes back i have enabled flakes features. and i was able to use nix flake command. previously i had installed nix then uninstalled it. Since i was new i kind of tinkering with it just now i used a command

"nix-env --list-generations"

where it showed me 2 gens so i switched to generation 1 & it gave me notification saying success fully switch but now when i use  nix commands the system isn't responding
![image](https://github.com/user-attachments/assets/0adefb2e-f3f2-4e86-ac0e-6d1f1a0a3785)

**Comment by cole-h** [comment]
What happens if you start a new shell, or run `source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh`?

**Comment by deekshith991** [comment]
> What happens if you start a new shell, or run `source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh`?
can't source as file doesn't exist when i started new shell & looked at this peculaiar thing . look at the last commands
![image](https://github.com/user-attachments/assets/bc2a41a3-f59b-4342-bfd0-718de5f634c6)

**Comment by deekshith991** [comment]
i have used the install command once again and it solved the priobem
