### ISSUE TITLE
https://nix.dev/manual/nix/latest points to 2.23

### ISSUE THREAD

**Issue by roberth** [NixOS/nix#11298]
**Describe the bug**

Seems that the release process is incomplete.

**Steps To Reproduce**

1. Go to https://nix.dev/manual/nix/latest 
2. Land on https://nix.dev/manual/nix/2.23

**Expected behavior**

Land on https://nix.dev/manual/nix/2.24

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by edolstra** [comment]
Seems to work now.
