### ISSUE TITLE
Hide all files from build that are not build inputs

### ISSUE THREAD

**Issue by nh2** [NixOS/nix#1137]
In the context of https://github.com/commercialhaskell/stack/issues/2802 it occurred to me that in general, a software being built inside nix can still introduce non-reproducible builds by reading arbitray files on that the build machine (e.g. by simply hardcoding a use of the contents of `/etc/group`, for example).

To make builds truly isolated, we would need an equivalent of `--pure` that can:

* Restrict file system usage to `/nix/store/...` paths that are declared as build inputs
* Disable networking (force offline builds)
* (potentially too extreme for now) Stop the time so that all timestamps are the same

Which of these does nix already support?

There are a couple methods this could be implemented: FUSE filesystems (e.g. the `tup` build system uses those), `fakeroot-ng` (uses `ptrace`), `seccomp` (like Chromium uses for sandboxing), or `cgroups` (requires root).

With a `patrace` based approach even the "stop the time" bit could be done.

**Comment by copumpkin** [comment]
`build-use-sandbox` already does all of that (and has been for years on Hydra and anyone who turns it own), except `nix-shell` doesn't currently apply that to shells you spin up.

Linux support uses namespaces, and on Darwin the support is currently broken but we generate sandbox specs on the fly and use the built-in sandboxing machinery.

**Comment by copumpkin** [comment]
https://github.com/NixOS/nix/issues/179 is why it isn't turned on by default. https://github.com/NixOS/nix/issues/907 is a proposal to turn the cheap parts of it on by default.

**Comment by domenkozar** [comment]
Closing as we already have sandboxes, please reopen with more specific feature requirement if current situation doesn't work/fit.

**Comment by domenkozar** [comment]
Duplicates https://github.com/NixOS/nix/issues/903
