### ISSUE TITLE
Following the Nix tutorial makes nix-shell seemingly hang on macOS

### ISSUE THREAD

**Issue by crescentrose** [NixOS/nix#11391]
**Describe the bug**

I just installed Nix (`nix-shell (Nix) 2.24.4`) on macOS (14.6.1, M2 Pro) with the intention of learning about Nix. Going [through the tutorial](https://nix.dev/tutorials/first-steps/declarative-shell), I set up the `shell.nix` file exactly as in the example, ran `nix-shell`, then waited for around 8 minutes with no output. Eventually I killed the process because I figured it hung.

My initial idea was to move the `shell.nix` to its own empty folder instead of running it in a directory where I usually keep scratch files and various playground projects for different languages, and then to let it run for however long it wants. This eventually got the example to _only_ take two minutes to run.

When running `nix-shell` with the `-vv` flags, I get this:

```
$ time nix-shell --run "exit" -vv
evaluating file '<nix/derivation-internal.nix>'
copying '«unknown»/' to the store...
```

(about two minutes pass with nothing happening)

```
... lots of other output appears ...
instantiated 'bash52-032' -> '/nix/store/is2jazhz2fzv3dv40s6am6n9l9r5n9n0-bash52-032.drv'
instantiated 'bash-5.2.tar.gz' -> '/nix/store/lzcag5y4x1iim5b0qg5ai7zrkf6ax62i-bash-5.2.tar.gz.drv'
instantiated 'bash-interactive-5.2p32' -> '/nix/store/fy5m5sm9xdi79b6f61yd125dr1m1a2q2-bash-interactive-5.2p32.drv'
nix-shell --run "exit" -vv  4.19s user 8.40s system 9% cpu 2:08.98 total
```

I guess my question is... am I doing something wrong? Or is it normal for `nix-shell` to eat up ~15 seconds of CPU time on an M2 Pro MacBook and ~2 minutes of wall time to set up a shell environment with `cowsay` and `lolcat`?

If I run `nix-shell -p cowsay lolcat --run "exit"`, it only takes about two seconds after the initial set-up, and about 28 seconds to do the initial set-up:

```
$ time nix-shell -p cowsay lolcat --run "exit"
install: skipping file '/dev/fd/63', as it was replaced while being copied
nix-shell -p cowsay lolcat --run "exit"  0.56s user 0.26s system 38% cpu 2.150 total
```

**Steps To Reproduce**

Follow the [Declarative shell environments](https://nix.dev/tutorials/first-steps/declarative-shell) tutorial on the Nix website.

**Expected behavior**

If this is how `nix-shell` is supposed to work, I would expect at least some more useful output while something's happening, and for the documentation to clarify that launching a nix-shell might take a long time.

If it's not how it's supposed to work, I would expect for it to be faster :)

**`nix-env --version` output**

nix-env (Nix) 2.24.4

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by fricklerhandwerk** [comment]
@crescentrose you're not doing anything wrong. You're observing an instance of https://github.com/NixOS/nix/issues/9684, which describes a performance regression introduced to fetching remote sources. It seems to be particularly bad on macOS. A workaround is to downgrade to Nix 2.18 (the Nix release shipped with Nixpkgs).

In the tutorial I've added a note that waiting time is to be expected (this is true regardless, and the reasons for this are a deep UX rabbit hole, but it shouldn't be *that* long) and a hint how to work around that: https://github.com/NixOS/nix.dev/pull/1050
