### ISSUE TITLE
emacs-mode: antiquote used in attribute test mess up syntax highlighting

### ISSUE THREAD

**Issue by montag451** [NixOS/nix#1142]
When using antiquote in the right hand side of the ? operator (attribute test), the part after the antiquote is highlighted as a string as you can see on this screenshot:

![nix-emacs-bug](https://cloud.githubusercontent.com/assets/249317/20775880/8762551e-b75d-11e6-9b61-c91b6442eb68.png)

I think the problem comes from [this function](https://github.com/NixOS/nix/blob/master/misc/emacs/nix-mode.el#L85).

**Comment by matthewbauer** [comment]
This should be fixed in #1119.
