### ISSUE TITLE
`/tmp/env-vars` not cleaned up, and owned by root

### ISSUE THREAD

**Issue by bobrippling** [NixOS/nix#11470]
**Describe the bug**

I see an error about `/tmp/env-vars` not being removable:
```sh
$ nix-shell -p bash
this path will be fetched (0.06 MiB download, 0.31 MiB unpacked):
  /nix/store/9r03kc5pg7ipi4yimkj386jsf34dxcpx-bash-5.2p32-dev
copying path '/nix/store/9r03kc5pg7ipi4yimkj386jsf34dxcpx-bash-5.2p32-dev' from 'https://cache.nixos.org'...
install: cannot remove '/tmp/env-vars': Operation not permitted

(ins)[nix-shell:~]$
```

specifically, `install: cannot remove '/tmp/env-vars': Operation not permitted`

```sh
$ ls -l /tmp/env-vars
-rw------- 1 root root 6515 Sep  2 05:27 /tmp/env-vars
```

**Steps To Reproduce**

1. See above description - any execution of `nix-shell`
1. See error above

**Expected behavior**

No error about `/tmp/env-vars` is emitted

**`nix-env --version` output**

```
nix-env (Nix) 2.18.5
```

**Additional context**

I believe [this is where the error occurs](https://github.com/NixOS/nixpkgs/blob/a9a40a5e5c23aa12cc9738cef60f7f6ed2219245/pkgs/stdenv/generic/setup.sh#L1128-L1129)

See also this old issue: #262

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by voidzero** [comment]
I have this issue too. Additionally, though not sure if this is related, /etc/nix/path is no longer being generated by nixos-rebuild.

**Comment by voidzero** [comment]
Hilighting @flokli (thanks)

**Comment by Ruhrozz** [comment]
same problem here

**Comment by Mic92** [comment]
So `nix develop` creates a temporary directory for this. I think nix-shell should do the same.
The current work around is to do this: `TEMP=$PWD nix-shell -p bash`

**Comment by Mic92** [comment]
I think we need something like this: https://github.com/NixOS/nix/pull/11713
