### ISSUE TITLE
Superfluous space in install script

### ISSUE THREAD

**Issue by Bagfields** [NixOS/nix#1151]
After installation the following instruction is shown:

"Installation finished!  To ensure that the necessary environment
variables are set, either log in again, or type

  . /home/beffa/.nix-profile/etc/profile.d/nix.sh
"
There is a superfluous space after the . (dot) in the command line, this space is also present in the lines added to .profile.

**Comment by danbst** [comment]
That is intentional, because dot is a command in `/bin/sh` (which is known as [`source` in `bash`](http://askubuntu.com/questions/25488/what-is-the-difference-between-source-and-in-bash)).

**Comment by vcunat** [comment]
And it would use a wrong path if without the space (unless the current directory was `/`).
