### ISSUE TITLE
The manpage for `nix flake archive` still displays FIXME for the description

### ISSUE THREAD

**Issue by quatquatt** [NixOS/nix#11525]
**Describe the bug**

See title. Bit of a funny one here, it's been four years since the latest commit to the file, so I doubt anyone has noticed since then. Makes sense, since it's a relatively niche command as far as nix3 commands go.

**Steps To Reproduce**

Run the command `nix flake archive --help` with nix-command enabled. Or, view it on nix.dev [here](https://nix.dev/manual/nix/2.24/command-ref/new-cli/nix3-flake-archive).

nix version: 2.24.6

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by Mic92** [comment]
Documentation lives here: https://github.com/NixOS/nix/blob/master/src/nix/flake-archive.md
