### ISSUE TITLE
NIX_STATE_HOME: unbound variable

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#11535]
**Describe the bug**

Nix's bash profile script is failing on several platforms: https://hydra.nixos.org/eval/1808904#tabs-still-fail, e.g. https://hydra.nixos.org/build/272876158#tabs-summary:
```
/home/vagrant/.nix-profile/etc/profile.d/nix.sh: line 6: NIX_STATE_HOME: unbound variable
```

This was introduced in #11351 (ping @noamraph).

**Steps To Reproduce**

**Expected behavior**

**`nix-env --version` output**

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by noamraph** [comment]
Hi, sorry for the regression. The problem seems to be that I used `if [ -n "$NIX_STATE_HOME" ]` instead of `if [ -n "${NIX_STATE_HOME-}" ]`. I also changed the conditions at the beginning of the file to this form, as they would probably have caused the same issue if $HOME or $USER weren't defined.
