### ISSUE TITLE
Nix produced store path with 700 permissions (should be 755)

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nix#1155]
After a few nixos-rebuild on a new NixOS system my system won't build anymore:

```
$ nixos-rebuil build
...
cannot open `/nix/store/0ppwjlrnk4b7ammpfqkanyjp27nj8nll-xorg-server-1.18.4/share/X11/xkb/compiled/kdecache-root': Permission denied at /nix/store/9g4wc31j7a2xp22xpgwr0qssfxahxdzl-builder.pl line 58.
builder for ‘/nix/store/xrf1j6kw51q91pcp42z8ybxhp303f4nh-system-path.drv’ failed with exit code 13
...
```

The failing store path has permissions 700 instead of the normal 755:

```
[root@nixos:~]# ls -ld /nix/store/0ppwjlrnk4b7ammpfqkanyjp27nj8nll-xorg-server-1.18.4/share/X11/xkb/compiled/kdecache-root
drwx------ 2 root root 4096 Dec 18 14:01 /nix/store/0ppwjlrnk4b7ammpfqkanyjp27nj8nll-xorg-server-1.18.4/share/X11/xkb/compiled/kdecache-root
```

The only thing I've done to the system is abort nixos-rebuild with ctrl-c a few times (to change a command-line flag). Does this mean ctrl-c isn't safe? We should fix that.

Running Nix 1.11.4 on NixOS 16.09.1272.81428dd.

**Comment by vcunat** [comment]
Are you sure the file is in the nix store? There used to be a symlink there.

**Comment by vcunat** [comment]
```
$ ls -l /nix/store/0ppwjlrnk4b7ammpfqkanyjp27nj8nll-xorg-server-1.18.4/share/X11/xkb
lrwxrwxrwx 1 root root 8 Jan  1  1970 compiled -> /var/tmp
```
(as provided by our binary cache)

**Comment by vcunat** [comment]
I suppose we could cherry-pick 33abc705b3 to 16.09.  Your problems seem basically just another instance of #19673 &ndash; buildEnv following symlinks outside the store combined with our xorg setup...

**Comment by bjornfor** [comment]
@vcunat: You are right. (I didn't pay enough attention to the problem.)

Yes, please do cherry-pick to NixOS 16.09, if possible.

Some more info about how I got into this state (if order matters):

1. Provision a headless system with only root user
2. Do various configuration tweaks (add systemPackages): nixos-rebuild swtich + ctrl-c + new nixos-rebuild switch
3. Enable xserver and KDE5.
4. Do "nixos-rebuild ..." and watch it die with permission error (as per first post)

**Comment by vcunat** [comment]
It's in DEs that set `environment.pathsToLink = [ "/share" ];` &ndash; then its' enough to get something unusual into `/var/tmp`.  Linking whole `/share` seems wasteful for other reasons, too, but at least KDE? and GNOME3 do set it currently.

**Comment by vcunat** [comment]
I forgot to say: picked as NixOS/nixpkgs@fa20c0cb5.

**Comment by bjornfor** [comment]
@vcunat: Thanks!
