### ISSUE TITLE
Wifi connection in KDE

### ISSUE THREAD

**Issue by AlexeiKharchev** [NixOS/nix#11608]
**Describe the bug**

After installing KDE Plasma, I want to connect Wifi
And I see a form, that suggests blowfish pass and advanced GPG key
But there is no `gpg` in system!
may be there is another tool to generate GPG key *

**Comment by edolstra** [comment]
This is not directly related to Nix. If this is on NixOS, please create an issue in the https://github.com/NixOS/nixpkgs/ repo.
