### ISSUE TITLE
An "import without angle brackets" mode

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#1161]
My general sense is that it's pretty rare (and error-prone) to use angle-brackets (outside of primitive fetchurl perhaps) except at the "entry point" of a Nix expression. We have an unofficial guideline that nobody should use angle brackets in nixpkgs, but why not make it into a hard requirement?

I'm thinking that all the nix evaluation machinery should default to disallowing most angle brackets except at the file being explicitly evaluated.

So for example, I might write

```nix
{ pkgs ? import <nixpkgs> }:

{
  foo = pkgs.stdenv.mkDerivation {
    name = "foo";
  };
}
```

And run it with `nix-build myentry.nix -A foo`. That `<nixpkgs>` is allowed because it's in the top-level myentry.nix file, but if anything inside it uses other angle brackets, that would fail loudly unless I pass in `--allow-nested-angle-brackets` or something like that.

Is this too restrictive? Are there valid uses for that "invisible global state" that I'm missing?

cc @edolstra @shlevy

**Comment by copumpkin** [comment]
One gotcha might be configuration.nix, which doesn't get explicitly evaluated but people want to refer to channels in it.

**Comment by shlevy** [comment]
Could be achieved with `scopedImport` disabling the findFile primop.

**Comment by edolstra** [comment]
Closing this since in pure mode (flakes) angle brackets don't work anymore.
