### ISSUE TITLE
[macOS 15.0.1] cant run installed pkgs 

### ISSUE THREAD

**Issue by bengiv** [NixOS/nix#11687]
### run pkgs

**Describe the bug**
When i run an already installed pkg (i installed on Sonoma) it does not run

**Steps To Reproduce**

>eza as an example

1. Open your terminal of choice
2. run eza
3. -> zsh: command not found: eza

**Expected behavior**

eza should run without any problems

**additional information**
eza is listed when running nix-env -q
Nix Store is mounted to /nix (according to Disk Utility), my previous pkgs, including eza, from Sonoma are in /nix/store, and i am able to run them as well if i type to path to the command into terminal, but only running the command does not work, it did on Sonoma. 

### Other information

**`nix-env --version` output**
nix-env (Nix) 2.24.6

**Additional context**

I am using macOS 15.0.1, freshly upgraded

**Comment by abathur** [comment]
What does `echo $PATH` report?

**Comment by bengiv** [comment]
> What does `echo $PATH` report?
`
/Users/ben/CLI:/Users/ben/.cargo/env:/Users/ben/.cargo/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/TeX/texbin:/Users/ben/.cargo/bin:/Applications/iTerm.app/Contents/Resources/utilities:/nix/var/nix/profiles/default/bin/`

**Comment by bengiv** [comment]
So i found this folder in /nix/store called, {random letters}-user-environment, in its bin folder it seems like it has all the clis i use, i will try to add it to path to see it that fixes stuff

**Comment by bengiv** [comment]
> So i found this folder in /nix/store called, {random letters}-user-environment, in its bin folder it seems like it has all the clis i use, i will try to add it to path to see it that fixes stuff

well nvm that, the user-env path changes everytime you install or uninstall something

**Comment by bengiv** [comment]
So to correct myself, it seems like that i can uninstall and install pkgs now, nenv -q doesnt seem to update tho, and the user-env isnt getting added to path.

**Comment by bengiv** [comment]
it seems to me that the shortcut manifest.nix in /nix/var/nix/profiles/default isnt updates to the newest build env-manifest.nix in /nix/store

**Comment by bengiv** [comment]
Okay so i fixed everything, i just needed to readd:
`# Nix
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
# End Nix
`
to /etc/zshrc and /etc/bashrc

now everything is working again as intended
