### ISSUE TITLE
Legacy `nix-shell` with a path prefers shell.nix over default.nix

### ISSUE THREAD

**Issue by K900** [NixOS/nix#11699]
**Describe the bug**

```
~/test
❯ cat shell.nix
throw "i'm shell.nix"

~/test
❯ cat default.nix
throw "i'm default.nix"

~/test
❯ nix shell nixpkgs#nixVersions.nix_2_24 --command nix-shell . --attr hello
error:
       … while calling the 'throw' builtin
         at /home/k900/test/shell.nix:1:1:
            1| throw "i'm shell.nix"
             | ^
            2|

       error: i'm shell.nix

~/test
❯ nix shell nixpkgs#nixVersions.nix_2_18 --command nix-shell . --attr hello
error:
       … while calling the 'throw' builtin

         at /home/k900/test/default.nix:1:1:

            1| throw "i'm default.nix"
             | ^
            2|

       error: i'm default.nix
```

This also breaks a common pattern of `nix-shell path/to/nixpkgs -A foo`.

**Steps To Reproduce**

1. Get a nixpkgs checkout
2. `nix-shell . -A hello`
3. See error

**Expected behavior**

A shell.

**`nix-env --version` output**

nix-env (Nix) 2.24.9

**Additional context**

2.18 is not affected, neither is Lix, may bisect later.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by K900** [comment]
Never mind, it's an intentional change: cfe3ee3de84458a8962a6c714e602e6791666101

Whether that was a good idea or not is to be discussed, but this is not a bug.

**Comment by roberth** [comment]
Hi @K900, don't hesitate to ping me next time

> to be discussed

Do you think it should still look for `default.nix` when `-A`/`--attr` is passed?
I think that would still solve the problem in issues such as https://github.com/NixOS/nix/issues/496, without breaking this use case.

**Comment by emilazy** [comment]
It seems sort of odd to me for the meaning of `.` in `nix-shell . …` to change if an `-A`  follows.

**Comment by roberth** [comment]
I agree it seems like an ad hoc extra rule on the face of it, but we could think of it as only changing the shell rule:

Resolve to `shell.nix` when no path, a directory or no attribute are specified.

It's not great, I have to admit, but it's still a manageable rule, and least it wouldn't regress a significant Nixpkgs use case.

**Comment by emilazy** [comment]
FWIW in discussion with @K900 and @alyssais on Matrix I think we considered that it might be reasonable to simply re‐export the entire package set from Nixpkgs’ `shell.nix`, which is kind of gross but IIRC we ultimately decided might be nicer than changing Nix behaviour here. Sadly it was a little while ago now so I don’t have a pointer to the discussion or recollection or the trade‐offs we perceived.

**Comment by roberth** [comment]
@emilazy I just came up with the same thoughts! https://github.com/NixOS/nixpkgs/pull/353240

**Comment by K900** [comment]
Yeah, I think the nixpkgs change is the way to go now. At least that way all the Nix versions work as intended.

**Comment by roberth** [comment]
Complicating the rules to accomodate this usage of `nix-shell` would make its behavior incomprehensible, and probably cause even more bug reports than those that led to #11057
Closing again.
