### ISSUE TITLE
Unable to download update of nixpkgs

### ISSUE THREAD

**Issue by oblivisheee** [NixOS/nix#11696]
**Describe the bug**
I cannot install updates of nixpkgs.
**Steps To Reproduce**

1. Install nix via `sh <(curl -L https://nixos.org/nix/install)`
2. Execute command `sudo -i nix-channel --update nixpkgs`

**Expected behavior**

Successful installation of update of nixpkgs.

**`nix-env --version` output**
nix-env (Nix) 2.18.5
**Additional context**
Macos Sequoia

**Error**
sudo -i nix-channel --update nixpkgs
warning: error: unable to download 'https://nixos.org/channels/nixpkgs-unstable': SSL connect error (35); retrying in 273 ms
warning: error: unable to download 'https://nixos.org/channels/nixpkgs-unstable': SSL connect error (35); retrying in 584 ms
warning: error: unable to download 'https://nixos.org/channels/nixpkgs-unstable': SSL connect error (35); retrying in 1045 ms
warning: error: unable to download 'https://nixos.org/channels/nixpkgs-unstable': SSL connect error (35); retrying in 2133 ms
error: unable to download 'https://nixos.org/channels/nixpkgs-unstable': SSL connect error (35)

**Comment by abathur** [comment]
Do the recommendations in https://github.com/NixOS/nix/issues/8081#issuecomment-1962419263 work for you?
