### ISSUE TITLE
Mysterious TTY-sensitive behavior change in nix-shell in 1.11.5

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#1171]
I often use `nix-shell` in automated builds in my CI systems to run scripts in reproducible environments. In these scenarios, `nix-shell` doesn't get a TTY, which in the past hasn't harmed it at all.

Take this simple default.nix:

```nix
(import <nixpkgs> {}).stdenv
```

and run (`setsid` gets rid of the TTY):

```bash
$ setsid nix-shell --command 'echo "foo"' < /dev/null
```

Up until 1.11.5, that prints out `foo` as you'd expect, but since 1.11.5, it appears to do nothing at all. I'm wondering if a subtle change was introduced since we killed the perl involved here?

cc @shlevy @edolstra @domenkozar

**Comment by copumpkin** [comment]
Hmm, @dezgeg suggested using `--run` instead of `--command`, which seems to fix the issue, although now I'm wondering why they're different...

**Comment by copumpkin** [comment]
I should RTFM:

>        --command cmd
>           In the environment of the derivation, run the shell command cmd. This command is executed in an interactive shell. (Use --run to use a non-interactive shell instead.) However, a call to exit is implicitly added to the command, so the shell will exit after
>           running the command. To prevent this, add return at the end; e.g.  --command "echo Hello; return" will print Hello and then drop you into the interactive shell. This can be useful for doing any additional initialisation.
>
>       --run cmd
>           Like --command, but executes the command in a non-interactive shell. This means (among other things) that if you hit Ctrl-C while the command is running, the shell exits.

**Comment by copumpkin** [comment]
Leaving this open because it's still a behavior change and it might be inadvertent. Curious if someone made the change intentionally and if that's documented anywhere.

**Comment by edolstra** [comment]
The only change to nix-shell between 1.11.4 and 1.11.5 was 8bddc3d406a07fcd10f2d08eaa81a2c4f4d66f1c.

**Comment by copumpkin** [comment]
Not sure, all I know is the change in outcomes 😦

**Comment by dezgeg** [comment]
Maybe some dependency (e.g. `bash` is a runtime dependency of Nix it seems) is different between your Nixes?

**Comment by copumpkin** [comment]
Nah, ran it on the same exact machine just with different Nix versions.

**Comment by copumpkin** [comment]
Has nobody been able to reproduce it?

**Comment by dezgeg** [comment]
Yeah I can. 8bddc3d406a07fcd10f2d08eaa81a2c4f4d66f1c does sound like the culprint once you look up `BASH_ENV` in the manpage.

**Comment by dezgeg** [comment]
#1177 fixes this in master.

**Comment by dezgeg** [comment]
And #1178 in the release branch. There it breaks nix-shell shebang usage when run in a non-interactive shell as well.

**Comment by copumpkin** [comment]
Thanks for the quick fix!
