### ISSUE TITLE
got an error message when install nix package manager

### ISSUE THREAD

**Issue by ArchLang** [NixOS/nix#11720]
when i am trying to install nix package manager on my lenovo legion 5i with i7 cpu  and rtx 4060 gpu (2024) running Pop!_OS 22.04 LTS x86_64  ,i used curl -L https://nixos.org/nix/install | sh -s -- --daemon and i got this error message when installing it on my system.I request the mantainers and the community to fix this problem asap.
![Screenshot-1](https://github.com/user-attachments/assets/be9aa384-68e5-44c4-95ad-5e220ef5d34a)

**Comment by abathur** [comment]
See:
- https://github.com/NixOS/nix/issues/7724#issuecomment-1410770088
