### ISSUE TITLE
Nix should not depend on Nix

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#11741]
**Describe the bug**

It was pointed out in https://github.com/NixOS/nix/pull/11726 that the Meson build of Nix depends on Nix: https://github.com/NixOS/nix/blob/79bbb4a64cb2a1cde48da93718c64352cab61046/doc/manual/meson.build#L7

This is fine when the manual is built in its own derivation, but not when it's built in a dev shell or a single derivation. In the old build system, the manual has a make rule that causes it to depend on the `nix` binary from the same build process.

**Steps To Reproduce**

**Expected behavior**

**`nix-env --version` output**

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by Ericson2314** [comment]
Try it without the `native : true`. The way it's supposed to work is that when one is doing the dev shell / combined meson build, the `find_program` is overridden by the make we define.

**Comment by Ericson2314** [comment]
I thought that would override the `native : true` Nix in a native build, but potentially not?

(I thought I specifically checked though: we might double check we aren't inconsistently using that Nix (and instead looking up one on the PATH) too.)

**Comment by Mic92** [comment]
Ok. I just checked again with a fresh build and put a faulty nix in my PATH and all the builds still succeed. I think what happened is that I was cross-compiling before so maybe that's why it cached my build nix.
