### ISSUE TITLE
Nix flake: error: bind mount from '/etc/resolv.conf' to '...' failed: No such file or directory

### ISSUE THREAD

**Issue by mbekkomo** [NixOS/nix#11758]
**Describe the bug**

When trying to build a package from flake, it returns an error. For example:
```
error:
       … while setting up the build environment

       error: bind mount from '/etc/resolv.conf' to '/nix/store/fn1kg3g2fcib83x1904464c2cazbgv0l-nix-search-v0.2--go-modules.drv.chroot/root/etc/resolv.conf' failed: No such file or directory
```

**Steps To Reproduce**

1. Run `nix profile install ...` or `nix run ...`.

**Expected behavior**

Successfully install or run the package binary.

**`nix-env --version` output**
```
nix-env (Nix) 2.24.9

```

**Additional context**

The steps are reproduced inside VanillaOS distro (in distrobox environment).

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by johnrichardrinehart** [comment]
Can you post the derivation that you're trying to realise? It really looks like you're trying to add your host's `/etc/resolv.conf` to the sandbox which won't work unless you add `/etc/resolv.conf` to `sandbox-paths`.

**Comment by mbekkomo** [comment]
https://github.com/peterldowns/nix-search-cli/blob/main/flake.nix#L26-L72

Yes, it does have `/etc/resolv.conf`. Can be confirmed through `file /etc/resolv.conf` which returned ASCII text.

**Comment by johnrichardrinehart** [comment]
Hmmm, I'm unable to reproduce. I'm on `x86_64-linux` (NixOS).
```bash
$ nix run 'github:nixos/nixpkgs?rev=95d29b24b0568e62514dec4c74a87e91584dca7b#nixVersions.nix_2_24' -- build 'github:peterldowns/nix-search-cli?rev=7b9fbb87e920669998203c0884b3e36f44d78318#nix-search' --print-out-paths
/nix/store/fzq64z034gz2v10m7x0wwf673rpvzwwx-nix-search-0.1-
```

```
accept-flake-config = false
access-tokens = 
allow-dirty = true
allow-import-from-derivation = true
allow-new-privileges = false
allow-symlinked-store = false
allow-unsafe-native-code-during-evaluation = false
allowed-impure-host-deps = 
allowed-uris = 
allowed-users = *
auto-allocate-uids = false
auto-optimise-store = false
bash-prompt = 
bash-prompt-prefix = 
bash-prompt-suffix = 
build-hook = /nix/store/p1l4j192w1abk7mmkg60qmvc18svhky4-nix-2.18.1/bin/nix __build-remote
build-poll-interval = 5
build-users-group = 
builders = 
builders-use-substitutes = false
commit-lockfile-summary = 
compress-build-log = true
connect-timeout = 0
cores = 0
diff-hook = 
download-attempts = 5
download-speed = 0
eval-cache = true
experimental-features = flakes nix-command
extra-platforms = aarch64-linux i686-linux
fallback = false
filter-syscalls = true
flake-registry = /nix/store/8g8ksdk6hk5qxnrsmdgfmw5p7hspqj6b-empty-flake-registry.json
fsync-metadata = true
gc-reserved-space = 8388608
hashed-mirrors = 
http-connections = 25
http2 = true
id-count = 8388608
ignore-try = false
ignored-acls = security.csm security.selinux system.nfs4_acl
impersonate-linux-26 = false
keep-build-log = true
keep-derivations = true
keep-env-derivations = false
keep-failed = false
keep-going = false
keep-outputs = false
log-lines = 10
max-build-log-size = 0
max-free = 18446744073709551615
max-jobs = 8
max-silent-time = 0
max-substitution-jobs = 16
min-free = 0
min-free-check-interval = 5
nar-buffer-size = 33554432
narinfo-cache-negative-ttl = 3600
narinfo-cache-positive-ttl = 2592000
netrc-file = /etc/nix/netrc
nix-path = nixpkgs=/nix/store/5acdh8xyry0kdvp6xla2hw7wf3zkphkl-source
plugin-files = 
post-build-hook = 
pre-build-hook = 
preallocate-contents = false
print-missing = true
pure-eval = true
require-drop-supplementary-groups = false
require-sigs = true
restrict-eval = false
run-diff-hook = false
sandbox = true
sandbox-build-dir = /build
sandbox-dev-shm-size = 50%
sandbox-fallback = false
sandbox-paths = /bin/sh=/nix/store/74hfiba1pszsvwx561nzy70mm521qnn7-busybox-static-x86_64-unknown-linux-musl-1.36.1/bin/busybox /nix/store/vkwnbzv7y0fzfw5rylh5daydspv5fvz4-qemu-aarch64-binfmt-P-x86_64-unknown-linux-musl /run/binfmt
secret-key-files = 
show-trace = false
ssl-cert-file = /etc/ssl/certs/ca-certificates.crt
stalled-download-timeout = 300
start-id = 872415232
store = auto
substitute = true
substituters = https://johnos.cachix.org https://cache.nixos.org/
sync-before-registering = false
system = x86_64-linux
system-features = benchmark big-parallel kvm nixos-test
tarball-ttl = 3600
timeout = 0
trace-function-calls = false
trace-verbose = false
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= johnos.cachix.org-1:wwbcQLNTaO9dx0CIXN+uC3vFl8fvhtkJbZWzMXWLFu0=
trusted-substituters = 
trusted-users = john
use-case-hack = false
use-cgroups = false
use-registries = true
use-sqlite-wal = true
use-xdg-base-directories = false
user-agent-suffix = 
warn-dirty = true
```

This question isn't really about `nix`, apparently, though. It's apparently around a specific package (https://github.com/peterldowns/nix-search-cli). If so, then issues/bug reports should land there.

**Comment by mbekkomo** [comment]
It's also the same for https://github.com/DeterminateSystems/fh.
```
error:
       … while setting up the build environment

       error: bind mount from '/etc/resolv.conf' to '/nix/store/s59f30vqcf3sgxlfzz5irvsf0xjnw2nb-cargo-1.80.1-x86_64-unknown-linux-gnu.tar.gz.drv.chroot/root/etc/resolv.conf' failed: No such file or directory
```

**Comment by mbekkomo** [comment]
I think I found out a possible solution to this. Since I'm using Nix inside A/B partition OS, Nix probably have a stroke when accessing the filesystem.

The solution to that is either installing Nix outside `vso` distrobox (or the container) which might not be end up successfully, or set the Nix store (the `/nix` directory) to `/home/nix` which will persist in the A/B partition.

**Comment by n0099** [comment]
For me this error occurs when inside namespaces created by [`nixos-enter`](https://wiki.nixos.org/wiki/Change_root) that having mountpoint `tmpfs on /etc/resolv.conf type tmpfs (rw,nosuid,nodev,size=8190524k,mode=755,inode64)`, https://github.com/NixOS/nixpkgs/pull/208694 may related.
Exit the `nixos-enter` then re-enter fix this for me.
Also [`nixos --config enter.mount_resolv_conf=false enter`](https://nix-community.github.io/nixos-cli/settings.html#enter) of another program [`nixos-cli`](https://github.com/nix-community/nixos-cli/blob/0d699d6ccc0fbc719e7d684cdce4868e578c7d66/cmd/enter/run.go#L79) can disable mounting that file if you don't need DNS resolve inside `nixos-enter`.
