### ISSUE TITLE
HTTPS cache download hangs

### ISSUE THREAD

**Issue by abbradar** [NixOS/nix#1181]
On current master branch Nix blocks indefinitely for me on fetching from `https://cache.nixos.org`. If I use `http://cache.nixos.org` it works fine. Running CURL on the same HTTPS host works fine too so this doesn't seem to be a network issue.

Output of plain CURL: http://lpaste.net/805006557807902720
Output of Nix's CURL (with a patch to enable verbosity): http://lpaste.net/4113503768102830080

GDB shows that Nix hangs on `pool()` inside `libcurl` -- doesn't help much. Wireshark shows that handshake is performed and then silence ensues. Finally, on stable Nix over the same network (but on another machine) this works fine.

**Comment by vcunat** [comment]
Perhaps related: https://github.com/NixOS/nix/pull/1183

**Comment by abbradar** [comment]
This is a part of the problem though -- I still don't understand why can't it reach HTTPS. Tried today from the office 'net -- fails the same way.

**Comment by edolstra** [comment]
Could you do an strace?
