### ISSUE TITLE
Flake `nix` package

### ISSUE THREAD

**Issue by roberth** [NixOS/nix#11822]
> or perhaps a tested `nix-cli`, like `nix-everything` but without the libs or manual?

> We should probably also add a `nix` attribute with some suggestions of what to pick instead.

_Originally posted in https://github.com/NixOS/nix/pull/11804#discussion_r1831818942_

**Comment by edolstra** [comment]
Fixed in 000d06d85b0b3676b255c466837a00555b39d581.
