### ISSUE TITLE
Nix errors "cannot call 'getFlake' on unlocked flake reference" even when NAR is specified

### ISSUE THREAD

**Issue by KiaraGrouwstra** [NixOS/nix#11834]
**Describe the bug**

Nix seems to yield an unexpected error when using `builtins.getFlake` in `nix build`, even when a NAR hash is specified.

**Steps To Reproduce**

1. run `nix build --expr 'builtins.getFlake "git+file:///etc/nixos?narHash=sha256-0000000000000000000000000000000000000000000="'`
2. find error:
>       … while calling the 'getFlake' builtin
>         at «string»:1:1:
>            1| builtins.getFlake "git+file:///etc/nixos?narHash=sha256-0000000000000000000000000000000000000000000="
>             | ^
>       error: cannot call 'getFlake' on unlocked flake reference 'git+file:///etc/nixos?narHash=sha256-0000000000000000000000000000000000000000000=', at «none»:0 (use --impure to override)

**Expected behavior**

> error: NAR hash mismatch in input [...]

**`nix-env --version` output**

```
nix-env (Nix) 2.18.7
```

**Additional context**

- reported [here](https://github.com/nix-community/nixos-anywhere/pull/418#issuecomment-2462354848)
- on lix 2.91.0 yields the expected "error: NAR hash mismatch in input [...]"

**Comment by threddast** [comment]
I tested all major versions of Nix from 2.6.0 to master and they all have this behavior

**Comment by max-privatevoid** [comment]
A `git` input is considered locked based on the existence of `rev`, not `narHash`, so Nix is right to complain about an unlocked input.
