### ISSUE TITLE
flake: broken .?submodules=1

### ISSUE THREAD

**Issue by widlarizer** [NixOS/nix#11859]
**Describe the bug**

I have been relying on `nix build ".?submodules=1" -L` to build [OpenROAD](https://github.com/The-OpenROAD-Project/OpenROAD/). 

**Steps To Reproduce**

Run `nix build ".?submodules=1" -L`

in [reproducer repo](https://github.com/widlarizer/nix-submodule-bug)

**Expected behavior**

I would expect behavior as it was recently, that is, for `.` to use the current directory as-is, and for `submodules=1` to include all submodules, and therefore to find the C file. Instead you get `       > cc1: fatal error: just-hello-c/hello.c: No such file or directory`

**`nix-env --version` output**

nix-env (Nix) 2.24.10

(on NixOS unstable)

**Comment by widlarizer** [comment]
Adding a hash fixes this: `nix build ".?submodules=1#" -L`

**Comment by donn** [comment]
The hash issue is being tracked here: https://github.com/NixOS/nix/issues/6633
