### ISSUE TITLE
[Packaging] Will you upstream those libgit2 patches?

### ISSUE THREAD

**Issue by darix** [NixOS/nix#11867]
I am packaging nix for openSUSE. I dont think patching intree patches in our libgit2 package to get nix building for openSUSE feels wrong.  Is there any place where i can track the progress of upstreaming those patches?

**Comment by roberth** [comment]
They've been merged, and we're waiting for a release. [John happened to ask](https://github.com/libgit2/libgit2/pull/6875#issuecomment-2468637860) yesterday, but we haven't got a response yet.

Normally we would include PR URLs in [dependencies.nix](https://github.com/NixOS/nix/blob/master/packaging/dependencies.nix), but this time I haven't. Sorry about that.

I'll close this for now, but feel free to ask/respond here or in a new issue, and thank you for working on openSUSE packaging!
