### ISSUE TITLE
nix-store doesn't appear to respect NIX_* variables (consistently?)

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#1188]
I'm attempting to reduce the amount of chroot/VM noise in NixOS image creation (because it's currently a miserable experience in virtualized environments like EC2) and am thus trying to register our store closure into the target database by repointing it with `NIX_STORE_DIR`, `NIX_STATE_DIR`, and so on. Unfortunately, when calling `nix-store --load-db`, I don't think those parameters are being respected. Is there some other way to get those variables to be respected for this purpose?

@edolstra @shlevy

**Comment by shlevy** [comment]
Hmm, I'm skeptical this is an accurate diagnosis. `nix-store` calls `initNix` right away, before switching on flags or anything, which has the `processEnvironment` call...

**Comment by copumpkin** [comment]
Ah, I think you're right and it's trickier than that. If I set `NIX_STORE_DIR` to my fake root, it starts complaining that the store paths from the closure aren't in the store. So I suppose I probably need some sort of tool that knows that the store is in a temporary location and doesn't hardcode the temporary path into the database.
