### ISSUE TITLE
Sensible nix-hash defaults

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#1191]
It currently computes an MD5 by default, and shows it in hex. Pretty much everyone using it nowadays will want SHA256 in base32. Can we change the default?

See also #802

**Comment by edolstra** [comment]
`nix-hash` will be deprecated. The new `nix hash-file` and `nix hash-path` commands default to SHA-512.

**Comment by copumpkin** [comment]
Oh cool. Any reason to do 512 over 256, when they're both of roughly equivalent security (i.e., both impossible to brute force in lifetime of universe, equally likely to be broken since the algorithm is nearly identical) and 512 is more hash noise to paste around?

**Comment by edolstra** [comment]
SHA-512 is a lot faster. And it seems more future-proof. (If it actually had equivalent security, there would be no reason for it to exist in the first place.)

**Comment by copumpkin** [comment]
The speed is nice indeed. Perhaps a truncated SHA-512? I'm mostly just averse to getting even longer strings of garbage in otherwise human-readable text 😄

**Comment by bjornfor** [comment]
Am I the only one who would like to see nix output hashes in the same format as e.g. "sha256sum"? Perhaps that means making a special case for tarballs / flat files, but it's the most common use case, right?

**Comment by copumpkin** [comment]
I quite like base32, and if anything would like base58 or base64 to make them even shorter :P very averse to crap that humans are bad at reading living in files that humans modify all the time.

**Comment by bjornfor** [comment]
Shorter hashes are nice, but it's annoying that the hashes published by upstreams cannot be used directly in nix expressions. You have to download the file and check it both with nix and sha256sum to know for sure you got the right file. I'd like it if I could just copy the sha256/512 right off the web and paste it into nix file.

Or have I missed something?

**Comment by edolstra** [comment]
You missed the fact that you absolutely can use regular base-16 hashes in Nix expressions :-)

**Comment by copumpkin** [comment]
If you do, people like me will come along and replace them with base32 though 😄

**Comment by bjornfor** [comment]
> You missed the fact that you absolutely can use regular base-16 hashes in Nix expressions :-)

Ah, good to know!

**Comment by copumpkin** [comment]
The hash still isn't what upstream would give you though. There are two things here: the "presentation" of the hash, and the bytes that feed into it. I think @bjornfor's bigger issue is that the hashes that upstream might feed us don't match what Nix computes when making a fixed-output derivaiton, because I think Nix is hashing a canonical Nar-based form of the file (which includes executable bit, for example) for consistency with directory hashes.

**Comment by edolstra** [comment]
That's only when using recursive hashes (i.e. `outputHashMode = "recursive"`). `fetchurl` by default uses `flat` hashes, so you can use upstream hashes right away (I do that all the time). For example, the hash in https://github.com/NixOS/nixpkgs/commit/1e17f21b3e844b28cb78142dd304b98a20fc8b3f comes straight from http://releases.mozilla.org/pub/firefox/releases/50.0.2/SHA512SUMS.

**Comment by copumpkin** [comment]
Oh, interesting. Does it switch to the other hashing mode if you set `executable = true;` in the `fetchurl` call then? I noticed the hash changing and assumed it defaulted to recursive.

**Comment by copumpkin** [comment]
Oh, I guess so: https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/fetchurl/default.nix#L117

**Comment by edolstra** [comment]
Closing, `nix hash file` prints SHA-256 hashes by default.

**Comment by AkechiShiro** [comment]
Hi @edolstra 

Why was SHA-512 not chosen ? Since it was deemed faster ? Because, it is longer in files ?

> `nix-hash` will be deprecated. The new `nix hash-file` and `nix hash-path` commands default to SHA-512.
