### ISSUE TITLE
Buid error

### ISSUE THREAD

**Issue by Boria138** [NixOS/nix#11925]
When trying to build nix 2.25.2 I get an error

```
[x86_64] src/libfetchers/git-utils.cc: In member function 'virtual void nix::GitRepoImpl::flush()':
[x86_64] src/libfetchers/git-utils.cc:288:13: error: 'git_mempack_write_thin_pack' was not declared in this scope
[x86_64] 288 | git_mempack_write_thin_pack(mempack_backend, packBuilder.get())
```
As far as I understand it, this is related to the dependency 
libfetchers on the git_mempack_write_thin_pack function, which is not present in any version of libgit2 even in the latest version 1.8.4 only in commit https://github.com/libgit2/libgit2/commit/f9c35fb50998d1c9d26293a18ade3d7c32f6ecb0.

**Comment by Ericson2314** [comment]
Yes you need a patched version of the library. Our build of nix with nix provides it.

**Comment by trofi** [comment]
Reliance on unreleased `libgit2` features makes it very inconvenient to package `nix` on non-`NixOS` systems. Can the feature be made optional? Or can the error message be improved that provided `libgit2` does not meet patched requirement?

**Comment by Mic92** [comment]
That's unfortunate. We got told it was supposed to be released soon.

**Comment by Mic92** [comment]
https://github.com/libgit2/libgit2/pull/6875 I think we can potentially check for the features and use the old code otherwise.

**Comment by darix** [comment]
> Reliance on unreleased `libgit2` features makes it very inconvenient to package `nix` on non-`NixOS` systems. Can the feature be made optional? Or can the error message be improved that provided `libgit2` does not meet patched requirement?

2.24.x still builds without a patched libgit2

**Comment by Mic92** [comment]
We only introduced it in 2.25. It's a performance related patch.

**Comment by alerque** [comment]
This is also [holding back Arch Linux packaging](https://gitlab.archlinux.org/archlinux/packaging/packages/nix/-/issues/5). If it is performance related only, a revert for stable tagged releases and keeping it in a development branch for use when it can be released would be/would have been much appreciated.
