### ISSUE TITLE
--option should exit if option doesn’t exist

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nix#1193]
Right now, `--option asdfgl` just continues, happily ignoring the option.

It should exit with a message that the option doesn’t exist.

**Comment by copumpkin** [comment]
I've been thinking about this for a while, and can think of two possible implementations:

1. Explicitly model all known options in a central location and load them early on at startup, and then query some sort of option struct deeper in the code. This feels like the better long-term path but it might be a bit of a pain to get there.
2. Track readers of options and moan if an option never gets read. So any read of the option map would get tracked somehow, and then the Nix tooling would complain if there exist options in that map that have never been mapped. In the past I've done something like this by making consumers delete the key they're reading from the map and then ensuring that there are no keys left after processing, but that might get ugly.

**Comment by Profpatsch** [comment]
nix is not doing complete option parsing at startup? ouch ouch ouc…

**Comment by copumpkin** [comment]
No, see `settings.get` [here](https://github.com/NixOS/nix/blob/master/src/libstore/build.cc#L1688), for example.
