### ISSUE TITLE
`!IsRoot()` assertion failure in `CanonPath::pop()`

### ISSUE THREAD

**Issue by msanft** [NixOS/nix#11936]
## Describe the bug

Found by [AFL++](https://github.com/AFLplusplus/AFLplusplus).

Contrived inputs can trigger the `!IsRoot()` assertion in `nix::CanonPath::pop()`. I don't know if this is something that should be handled in Nix, as only faulty expressions (on a logical layer, not semantically) can possibly trigger this, if I understand it correctly.

## Steps To Reproduce

Evaluate `""+~/../../..`, where the amount of directory traversals causes Nix to traverse behind `/`.

## Expected behavior

Error might be handled more gracefully, indicating the problem.

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open bug issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open bug issues and pull requests]: https://github.com/NixOS/nix/labels/bug

---

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by Mic92** [comment]
@msanft I would be really interested in the AFL++ setup you have. Could you share it?
It would be great if Nix was also part of https://github.com/google/oss-fuzz

**Comment by msanft** [comment]
> @msanft I would be really interested in the AFL++ setup you have. Could you share it? It would be great if Nix was also part of https://github.com/google/oss-fuzz

It's very primitive as of now, but I'm currently working on it in my master's thesis: https://github.com/msanft/nix-fuzzing

Many TODOs that I eventually want to track in that repo, but I'm open to collaborate on that matter too. 

My plan is to eventually bring my setup to oss-fuzz.

**Comment by Mic92** [comment]
I am on-board with this. We can also run cifuzz in our repository to make sure your setup doesn't break.

**Comment by xokdvium** [comment]
@msanft, this work is very promising. I've been thinking of using https://github.com/klee/klee to generate high coverage unit tests and to facilitate easier refactoring by using symbolic execution for equivalence checking.

**Comment by Mic92** [comment]
Here is the full stacktrace:

```
#0  0x00007ffff6ca2efc in __pthread_kill_implementation () from /nix/store/87848rvrg5c7jmplpi0iapvbxyj9kfid-glibc-2.39-52/lib/libc.so.6
#1  0x00007ffff6c52e86 in raise () from /nix/store/87848rvrg5c7jmplpi0iapvbxyj9kfid-glibc-2.39-52/lib/libc.so.6
#2  0x00007ffff6c3b935 in abort () from /nix/store/87848rvrg5c7jmplpi0iapvbxyj9kfid-glibc-2.39-52/lib/libc.so.6
#3  0x00007ffff6c3b859 in __assert_fail_base.cold () from /nix/store/87848rvrg5c7jmplpi0iapvbxyj9kfid-glibc-2.39-52/lib/libc.so.6
#4  0x00007ffff6c4b6e6 in __assert_fail () from /nix/store/87848rvrg5c7jmplpi0iapvbxyj9kfid-glibc-2.39-52/lib/libc.so.6
#5  0x00007ffff7e79ee9 in nix::CanonPath::pop (this=0x80fd10) at ../src/libutil/canon-path.cc:39
#6  nix::CanonPath::pop (this=this@entry=0x7ffffffe5da0) at ../src/libutil/canon-path.cc:39
#7  0x00007ffff7f14147 in nix::SourceAccessor::resolveSymlinks (this=<optimized out>, path=..., mode=<optimized out>) at ../src/libutil/source-accessor.cc:88
#8  0x00000000006497a0 in nix::SourcePath::resolveSymlinks (this=<optimized out>, mode=<optimized out>) at ../src/libutil/source-path.hh:116
#9  0x00007ffff74ee14c in operator() (__closure=<optimized out>) at ../src/libexpr/eval.cc:2377
#10 nix::EvalState::copyPathToStore (this=this@entry=0x7ffff5032810, context=std::set with 0 elements, path=...) at ../src/libexpr/eval.cc:2387
#11 0x00007ffff74f8494 in nix::EvalState::coerceToString (this=this@entry=0x7ffff5032810, pos=..., v=..., context=std::set with 0 elements, errorCtx="while evaluating a path segment", coerceMore=coerceMore@entry=false, copyToStore=true, canonicalizePath=true) at ../src/libexpr/eval.cc:2296
#12 0x00007ffff74f9741 in nix::ExprConcatStrings::eval (this=<optimized out>, state=..., env=..., v=...) at ../src/libexpr/eval.cc:2029
#13 0x00007ffff736b5cd in nix::NixRepl::evalString (this=this@entry=0x7ffff503eea0, s="\"\"+~/../../..", v=...) at /nix/store/fg7ass3a5m5pgl26qzfdniicbwbgzccy-gcc-13.2.0/include/c++/13.2.0/bits/shared_ptr_base.h:1349
#14 0x00007ffff737262d in nix::NixRepl::processLine (this=this@entry=0x7ffff503eea0, line="\"\"+~/../../..") at ../src/libcmd/repl.cc:693
#15 0x00007ffff7374588 in nix::NixRepl::mainLoop (this=0x7ffff503eea0) at ../src/libcmd/repl.cc:193
#16 0x00000000005d4145 in nix::CmdRepl::run (this=this@entry=0x7f2f80, store=..., rawInstallables=...) at ../src/nix/repl.cc:109
#17 0x00007ffff7345caf in nix::RawInstallablesCommand::run (this=0x7f2f80, store=...) at ../src/libcmd/installables.cc:879
#18 0x00007ffff7319097 in nix::StoreCommand::run (this=0x7f3240) at ../src/libcmd/command.cc:71
#19 0x000000000057e46a in nix::mainWrapped (argc=2, argv=<optimized out>) at /nix/store/fg7ass3a5m5pgl26qzfdniicbwbgzccy-gcc-13.2.0/include/c++/13.2.0/bits/shared_ptr_base.h:1349
#20 0x00007ffff73e7b2c in std::function<void()>::operator() (this=0x7ffffffe7ff0) at /nix/store/fg7ass3a5m5pgl26qzfdniicbwbgzccy-gcc-13.2.0/include/c++/13.2.0/bits/std_function.h:591
#21 nix::handleExceptions (programName="/home/joerg/git/nix/build/src/nix/nix", fun=...) at ../src/libmain/shared.cc:341
#22 0x000000000048afe7 in main (argc=<optimized out>, argv=<optimized out>) at /nix/store/fg7ass3a5m5pgl26qzfdniicbwbgzccy-gcc-13.2.0/include/c++/13.2.0/bits/new_allocator.h:88
```

**Comment by msanft** [comment]
@xokdvium I've created a Matrix room to coordinate any fuzzing efforts. If you want to, send me an email with your Matrix name or drop it here so I can invite you :)

/cc @Mic92 - invited you too.
