### ISSUE TITLE
Shortcut for --option build-use-substitutes false

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nix#1194]
One often uses `--option build-use-substitutes false` when it’s clear that everything is cached locally and the 1–5 second (depending on the speed of your connection and hydra) wait for the `.nar` fetcher to finish is a big overhead.

I suggest adding a `--local` flag or similar.

**Comment by bhipple** [comment]
One possibility for zsh users is to use a gobal alias for nix local builds, i.e.
```
alias -G NL='--option build-use-substitutes false'
```

and then you can use it like `nix-env NL -iA nixpkgs.tmux`.  The zsh global alias isn't context sensitive, so it's not the best solution, but it works today.

**Comment by Profpatsch** [comment]
> One possibility for zsh users is to use a gobal alias for nix local builds

I’m direly missing the global aliases in fish, yes.

**Comment by AleXoundOS** [comment]
Now this option is renamed to the shorter `--substitute` if I'm not mistaken.

**Comment by Profpatsch** [comment]
The newer versions of nix can use `--substituters`.
