### ISSUE TITLE
NarInfo files without an terminating newline are marked as corrupt

### ISSUE THREAD

**Issue by mguentner** [NixOS/nix#1196]
nix currently accepts this
```
a: b\n
c: d\n
e: f\n
```
but rejects
```
a: b\n
c: d\n
e: f
```

This line leads to the `corrupt()`
https://github.com/NixOS/nix/blob/215b70f51e5abd350c9b7db656aedac9d96d0046/src/libstore/nar-info.cc#L30

It's not an issue or bug per se but tooling around nix needs to handle it appropriately.

**Comment by edolstra** [comment]
This is not really a bug since there is no formal grammar for .narinfo files. The only valid .narinfo files by definition are those that Nix accepts :-)

**Comment by mguentner** [comment]
Fair enough :)
