### ISSUE TITLE
NIX_BUILD_GROUP_ID=983

### ISSUE THREAD

**Issue by Ponkk5** [NixOS/nix#11983]
## Platform

- [x] Linux: 
- [ ] macOS
- [ ] WSL

## Output

<details><summary>Output</summary>

```log

```

</details>

## Checklist

- [ ] checked [latest Nix manual] \([source])
- [x] checked [open installer issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open installer issues and pull requests]: https://github.com/NixOS/nix/labels/installer

---

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by abathur** [comment]
There's no information here to help you with. Happy to reopen if you include an install log.
