### ISSUE TITLE
unix

### ISSUE THREAD

**Issue by Ponkk5** [NixOS/nix#11984]
## Platform

- [x] Linux: 
- [ ] macOS
- [ ] WSL

## Output

<details><summary>Output</summary>

```log

```

</details>

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open installer issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open installer issues and pull requests]: https://github.com/NixOS/nix/labels/installer

---

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by cole-h** [comment]
It looks like you forgot to include the output of your installation. If you edit that in, we can reopen this. But for now, I'm closing this, as there is nothing actionable in this issue. Thanks!
