### ISSUE TITLE
A couple of concurrent build improvements

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#1198]
It'd be nice if we could configure Nix to use as many concurrent builds as there are cores or some other "just do something sensible" setting like that. When I create AMIs for EC2, I don't often know ahead of time how many cores will be on the instance, but it's frustrating watching it do single-core downloads.

It might also make sense to separate out a  concurrency option for concurrent binary cache downloads and fixed-output derivation builds, since one is generally tougher on CPU and the other is generally tougher on bandwidth, and there's not a single good answer to those.

**Comment by vcunat** [comment]
Yes, supporting `0` as value for `--jobs` would be nice, similarly to what we have for `--cores`.

**Comment by wizeman** [comment]
Wouldn't `--jobs $(nproc)` work?

**Comment by copumpkin** [comment]
@wizeman I can't run `$(nproc)` in nix.conf or from NixOS config (without shady IFD behavior)
