### ISSUE TITLE
Installer: database disk image is malformed (in '/nix/var/nix/db/db.sqlite')

### ISSUE THREAD

**Issue by soppelmann** [NixOS/nix#11990]
## Platform
- [x] Linux: 

## Additional information
Brand new Debian Bookworm install, attempted to install nix in multi-user mode.
Getting the same issue running the install script as a normal user and as root user.

## Output

```log
curl -L https://nixos.org/nix/install | sh -s -- --daemon

[snip]

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo HOME=/root /nix/store/fsh9vmf1rfnaxv48n20nalfdavzji5sf-nix-2.25.2/bin/nix-store --load-db

to load data for the first time in to the Nix Database

error: executing SQLite statement 'insert or replace into Refs (referrer, reference) values (14, 14);': database disk image is malformed, database disk image is malformed (in '/nix/var/nix/db/db.sqlite')
```
Found no issues when running the following
```
sudo HOME=/root /nix/store/fsh9vmf1rfnaxv48n20nalfdavzji5sf-nix-2.25.2/bin/nix-store --verify --check-contents --repair
reading the Nix store...
checking path existence...
checking link hashes...
checking store hashes...
```

</details>

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open installer issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open installer issues and pull requests]: https://github.com/NixOS/nix/labels/installer

---

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by soppelmann** [comment]
Turns out it was an issue with the hypervisor, was using bhyve on FreeBSD 14.1.

**Comment by abathur** [comment]
Like, a persistent issue with the hypervisor reproducible in any vm? 

I ask since the core issue sounds like:
- #8647

I doubt it's the same exact cause since those were neither consistent nor on install, but your comment made me wonder if a stable repro here may help provide any leverage there.

**Comment by soppelmann** [comment]
It was likely this bug, pinning glibc to a known good version on the debian vm solved it.
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=279901

Reproducible by creating a bhyve vm with latest debian stable or testing and running the nix install script.
