### ISSUE TITLE
expose `nix`, `nixos-rebuild`, etc. via flake `apps` output

### ISSUE THREAD

**Issue by sellout** [NixOS/nix#11993]
## Is your feature request related to a problem?

I have a flake with a recent nixosConfiguration that I want to install on a machine that currently has quite an out-of-date Nix install. Running `nixos-rebuild switch --flake .` fails with an error that has been fixed in newer `nix`, so I figured I could `nix run github:NixOS/nix#nixos-rebuild -- switch --flake .` and wind up with an updated install with the current `nix`, but unfortunately there’s no such app (or package) in the flake, so it doesn’t work.

## Proposed solution

Just add the outputs.

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open feature issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open feature issues and pull requests]: https://github.com/NixOS/nix/labels/feature

---

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by roberth** [comment]
This would be more of a Nixpkgs issue, but the solution is

```diff
-nix run github:NixOS/nix#nixos-rebuild --
+nix run github:NixOS/nixpkgs#nixos-rebuild --
```

**Comment by sellout** [comment]
Ah, of course 🤦 Thanks.
