### ISSUE TITLE
Building legacyPackages output of a flake no longer works

### ISSUE THREAD

**Issue by mschuwalow** [NixOS/nix#12002]
## Describe the bug

Building legacyPackages output of a flake no longer seems to work. Instead, nix seems to only consider the 'packages' flake output. I could not find any documentation regarding the change and the [wiki](https://nixos.wiki/wiki/Flakes) & [manual](https://nix.dev/manual/nix/2.25/command-ref/new-cli/nix3-build) still mention legacyPackages, so I assume this is unintended.

## Steps To Reproduce

  1. Run `nix build nixpkgs#cowsay`
  2. Observe output:
```
error: flake 'flake:nixpkgs' does not provide attribute 'packages.aarch64-darwin.default' or 'defaultPackage.aarch64-darwin'
Exception: nix exited with 1
```

## Expected behavior

The package in legacyPackages gets built.

## Metadata

`nix-env (Nix) 2.24.10`

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open bug issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open bug issues and pull requests]: https://github.com/NixOS/nix/labels/bug

---

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by edolstra** [comment]
I can't reproduce this, e.g. `nix build github:NixOS/nixpkgs/f49f947ec4a6d313697595e17ff06568c65abdab#cowsay` works for me.

What does `nix flake metadata nixpkgs` say?

**Comment by mschuwalow** [comment]
This turned out to be an unrelated issue. I was using the elvish shell, which is interpreting the '#' as the start of a comment.
Closing this
