### ISSUE TITLE
installing 'nix-2.25.3' error:        … while setting up the build environment         error: unable to fork: Permission denied

### ISSUE THREAD

**Issue by snehalg04** [NixOS/nix#12003]
## Platform

- [ ] WSL

## Additional information
I am executing:

    $ sudo HOME=/root /nix/store/3x497rk44p5zpr2vbf155dqw5xfjri1a-nix-2.25.3/bin/nix-env -i /nix/store/3x497rk44p5zpr2vbf155dqw5xfjri1a-nix-2.25.3

to install a bootstrapping Nix in to the default profile

installing 'nix-2.25.3'
error:
       … while setting up the build environment

       error: unable to fork: Permission denied

## Output

```

</details>

## Checklist

<!-- make sure this issue is not redundant or obsolete -->

- [ ] checked [latest Nix manual] \([source])
- [ ] checked [open installer issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open installer issues and pull requests]: https://github.com/NixOS/nix/labels/installer

---

Add :+1: toI am executing:

    $ sudo HOME=/root /nix/store/3x497rk44p5zpr2vbf155dqw5xfjri1a-nix-2.25.3/bin/nix-env -i /nix/store/3x497rk44p5zpr2vbf155dqw5xfjri1a-nix-2.25.3

to install a bootstrapping Nix in to the default profile

installing 'nix-2.25.3'
error:
       … while setting up the build environment

       error: unable to fork: Permission denied

**Comment by abathur** [comment]
I probably can't be much help with WSL issues, but can you confirm this is WSL 2? (I think I remember hearing Nix won't work with WSL 1).

**Comment by snehalg04** [comment]
It is resolved with WS2 thank you
