### ISSUE TITLE
Code Quality: Create C++ unit tests

### ISSUE THREAD

**Issue by mguentner** [NixOS/nix#1200]

**Comment by copumpkin** [comment]
@mguentner can you elaborate? Are you objecting to the shell scripts running the tests? Or you'd prefer tests to be in terms of libstore and libexpr rather than the command-line tools?

**Comment by mguentner** [comment]
The shell scripts mostly do functional testing and making sure that Nix behaves in the way it should. No objection there :)
I suggest to test classes and their methods (if possible) using unit tests with e.g. cppunit or gtest and like you mentioned lib* are good candidates for it. This came up when I ran in to #1196

**Comment by edolstra** [comment]
Closing since we have unit tests now.
