### ISSUE TITLE
nix-push should use xargs for its communication with nix-build

### ISSUE THREAD

**Issue by jwiegley** [NixOS/nix#1208]
On my Mac machine, given an environment with many, many expressions, nix-push fails with:

```
building compressed archives...
Can't exec "/nix/store/x2amq0izpv83rcdf7j1ihmnwdgyr2zn0-nix-1.11.6/bin/nix-store": Argument list too long at /nix/store/x2amq0izpv83rcdf7j1ihmnwdgyr2zn0-nix-1.11.6/bin/nix-build line 337.
readline() on closed filehandle OUTPATHS at /nix/store/x2amq0izpv83rcdf7j1ihmnwdgyr2zn0-nix-1.11.6/bin/nix-build line 339.
nix-build failed: 256 at /Users/johnw/.nix-profile/bin/nix-push line 168.
```

My guess is that `nix-push` is building up a huge list of arguments, and then passing them all to a single invocation of `nix-build`.  It should pass these as input to an invocation of `xargs` that will then invoke `nix-build`.

**Comment by edolstra** [comment]
Closing since `nix-push` has been removed (6e51af80231b2a35ba3f5edffa7e235b239955a0). The replacement (`nix copy`) should not have this problem.
