### ISSUE TITLE
Possibly unescaped error: S3 object '%s' does not exist

### ISSUE THREAD

**Issue by cep21** [NixOS/nix#12090]
## Describe the bug

I'm using nix and an S3 bucket I don't have read permissions to.  I see this error in the logs

```
       error: s3://company/object.whl

       response body:

       S3 object '%s' does not exist
```

My guess is that nix intends it to not literally print `%s`, but instead is trying to do some printf formatting.

```
nix --version
nix (Nix) 2.24.10
```

## Steps To Reproduce

I was trying to run a nix build.  Sorry there aren't complete steps to reproduce but I hope the error is clear?

## Expected behavior

You likely wanted to print something like this
```
       S3 object '<some-name>' does not exist
```

**Comment by cole-h** [comment]
Thanks for the report, will be fixed in https://github.com/NixOS/nix/pull/12091!
