### ISSUE TITLE
Nix 2.25: derivations are able to log in ways that break the oneline status

### ISSUE THREAD

**Issue by philiptaron** [NixOS/nix#12096]
## Describe the bug

Take a look at this:

![image](https://github.com/user-attachments/assets/5eee1841-b014-408c-a944-a31c3fcc8b29)

Super low priority bug, but there you go.

## Steps To Reproduce

**I can't get this to reproduce consistently.** I thought it would be `nix build -f. haskellPackages.doclayout --rebuild` but that doesn't trigger it.

## Expected behavior

No line breaking no matter what the derivation logged.

## Metadata

```
nix-env (Nix) 2.25.3
```

## Additional context

As the screenshot shows, this happened when building a _lot_ of derivations from the `staging` branch. Maybe that's at issue?

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open bug issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open bug issues and pull requests]: https://github.com/NixOS/nix/labels/bug

**Comment by edolstra** [comment]
Could be related to #12014?

**Comment by philiptaron** [comment]
> Could be related to #12014?

Yes, I think that's the exact scenario.
