### ISSUE TITLE
Cannot build nix itself in github actions

### ISSUE THREAD

**Issue by hsjobeki** [NixOS/nix#12104]
## Describe the bug

I was trying to build the current nix version to export all current builtins and their respective documentation in noogle.dev.

https://github.com/nix-community/noogle/actions/runs/12493974015/job/34863066322

It seems some of the functional tests are getting stuck in github actions but run fine on my local machine.

Would be nice if nix can be built in github CI. So i can display latest stats and docs.

## Expected behavior

- Default output of nix should be buildable in github actions.

I  tried using various `nix`, `nix-cli`, `...` attributes which  all lead to the same problem.

Using `doCheck = false` and `doInstallCheck = false` doesnt have any effect since they are `false` already -> same failure.

Tried setting meson flags (i am not as familiar with how nix uses meson)

```nix
nix-cli.overrideAttrs (prev: {
            mesonFlags = prev.mesonFlags or [] ++ [
              "-Dunit-tests=false" # Doesnt work
               "-Dtests=false"  # Doesnt work
            ];
          });
```

- Alternative: provide some output of `language.json` that doesn't require building nix 

## Metadata

Current master branch @ f72752c0dc6547b1568a9ef46deba875e38fada2

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open bug issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open bug issues and pull requests]: https://github.com/NixOS/nix/labels/bug

---

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by Mic92** [comment]
The nix version you are building seems quite old:

`For full logs, run 'nix log /nix/store/vckk3zqq3vwy34yx8fkbd188inbkg8yq-nix-2.20.0pre20240105_cbf99c7.drv'.`

Please try a more resent version. There was recently a change in github's kernel that no longer allows to create usernamespaces. We fixed this in latest master.
