### ISSUE TITLE
`nix-channel --update` masks failures

### ISSUE THREAD

**Issue by grahamc** [NixOS/nix#1211]
This was an issue I ran in to, installing Nix in an environment with a proxy. The version of curl already installed masked a configuration mistake in the `https_proxy` variable. The (much) newer version of Curl packaged with Nix exposed this issue. From the perspective of installing Nix, it would get to the `nix-channel --update` stage and fail like this:

```
nix-channel: unable to check ‘https://nixos.org/channels/nixpkgs-unstable’
```

This is because the underlying curl call in the `nix-channel` perl script was failing. However, the nix-channel code masks the issue and doesn't expose any information as to why or how it failed.

Being familiar enough with Nix, I read the source to `nix-channel` and found it essentially calls:

```
/nix/store/y2dzvy1ji14cfya2rblnmyhcbfjfc75r-curl-7.52.1-bin/bin/curl https://nixos.org/channels/nixpkgs-unstable
```

which yielded the following error:

```
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
```

leading me on to discover the environment's misconfiguration. Having our tools expose more detailed information would more readily allow novice Nix users the ability to start debugging their own problems.

(FWIW the problem is with `https_proxy="https://foobar:1111"` old curl will ignore `https` and substitute in `http`, new curl can handle HTTPS proxies, and will try to negotiate TLS with the proxy server.)

**Comment by mickours** [comment]
I have the same kind of error message but for an other proxy error:
```
sudo nixos-rebuild switch --upgrade --verbose
/run/current-system/sw/bin/nix-channel: unable to check ‘https://nixos.org/channels/nixos-17.03-small’
```
The real problem is the error is mask, and the internal curl error don't show up even with the verbose flag.

I tried manually and I get this:
```
/run/current-system/sw/bin/curl https://nixos.org/channels/nixos-17.03-small
curl: (56) Received HTTP code 407 from proxy after CONNECT
```
Just adding some meaningful message in the ``nix-channel`` Perl script at line 110 can do the trick. I'd like to push a PR but I'm really not familiar with Perl, any idea how to get this message and show it to the user?

For convinience, the code snippet that need to be updated:
```perl
        ($url, $filename) = `cd $tmpdir && $Nix::Config::curl $Nix::Config::curlCaFlag --netrc-file $netrcFile --netrc-optional --silent --write-out '%{url_effective}\n%{filename_effective}' -L '$url' -O`;
        chomp $url;
        die "$0: unable to check ‘$url’\n" if $? != 0;
```

**Comment by kini** [comment]
Looking at `man curl`, I see the following:

```
       -s, --silent
              Silent or quiet mode. Don't show  progress  meter  or  error
              messages.  Makes Curl mute.

       -S, --show-error
              When  used with -s it makes curl show an error message if it
              fails.
```

So probably all that needs to be done is to add `--show-error` to the invocation of `$Nix::Config::curl` on the first line in that snippet.

However, in the meantime it seems that `nix-channel` has been rewritten as a C++ program which links against the same `download.cc` code that other parts of nix use. So maybe this is no longer an issue.

**Comment by therealpxc** [comment]
Yeah, it looks like this issue is indeed still live. I documented [running into it on a ticket](https://github.com/NixOS/nix/issues/1896#issuecomment-378426575) for another issue with Nix and proxy configurations.

Correcting my `https_proxy` variable fixed it.

**Comment by kini** [comment]
> Yeah, it looks like this issue is indeed still live. I documented [running into it on a ticket](https://github.com/NixOS/nix/issues/1896#issuecomment-378426575) for another issue with Nix and proxy configurations.
> 
> Correcting my `https_proxy` variable fixed it.

It seems from looking at the linked ticket that what you're actually saying is that this issue (i.e. #1211) is *not* still live, right? Because the error message was *not* hidden in the output you showed in your comment on the other ticket. If so, that means we can close this ticket, I think, since this ticket was about the message being hidden.

**Comment by kini** [comment]
@therealpxc Please see above.

**Comment by abathur** [comment]
Siding with @kini here, but happy to reopen if anyone objects.
