### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by Krutonium** [NixOS/nix#12123]
## Describe the bug

The other day when I was updating my system on NixOS, I lost internet while it was downloading nixpkgs.
The resulting error contains a spelling error that I was unable to locate in `nix` or `nixpkgs` using ripgrep.

I am *guessing* the error exists here though.

`error: cannot get archive member name: Truncated tar archive detected while reading next heaader`

Specifically, `heaader`.

## Steps To Reproduce

  `nix flake update`
  *disconnect internet during update*
 

## Expected behavior

`header` not `heaader`

## Metadata

nix-env (Nix) 2.24.10

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open bug issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open bug issues and pull requests]: https://github.com/NixOS/nix/labels/bug

---

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by roberth** [comment]
Fix in https://github.com/libarchive/libarchive/commit/cbfe4d9e6dac1c156fab760ccf92c902200c896e
