### ISSUE TITLE
Remove stale branches on this repo

### ISSUE THREAD

**Issue by expipiplus1** [NixOS/nix#1220]
There are several branches which have been abandoned or merged into master already, it would be good to get these removed to make finding interesting branches easier.

**Comment by edolstra** [comment]
No, stale branches should not be removed unless they're merged. We should not throw away work.

**Comment by expipiplus1** [comment]
I agree that in general throwing away work is bad, but surely there's a balance to be found between making this repository a little easier to navigate and keeping 13 year old releases on github. That's up to you to decide :)

There are quite a few branches which have been merged already such as `multiple-outputs-sandbox`, `sqlite`, `gc`, `fast-eval`. These were mostly what this issue was about.

**Comment by edolstra** [comment]
Yeah, deleting merged branches is fine.
