### ISSUE TITLE
nix-build adds a suffix to --output-link

### ISSUE THREAD

**Issue by timbertson** [NixOS/nix#1229]
## Issue description

```
nix-build --out-link dest -A jre '<nixpkgs>'
```

Doesn't produce `dest`, but instead produces `dest-jre`.

I assume this is because `jre` is a secondary output of the `jdk` derivation, so nix-build is adding the output name. This means that when I'm building an arbitrary derivation from a script, I can't rely on what the actual destination will be called without knowing ahead of time whether it's part of a multi-output derivation, and what the output name is.

I couldn't see any documentation about this, is it intentional or a bug? If it's intentional, is there any way to tell nix "no really, put the output here".

* nix-build (Nix) 1.11.6

**Comment by matthewbauer** [comment]
I think it's because the default behavior is just ```nix-build --out-link result```...

If you want to always resolve to ```dest```, you can just use:

```
out=$(nix-store --no-gc-warning -r $(nix-instantiate --no-gc-warning -A jre '<nixpkgs>'))
ln -sf $out dest
```

It's not as clean as nix-build, but you get more control over what's going  on.

**Comment by yegortimoshenko** [comment]
I hope this is intended, I like this behavior.

**Comment by edolstra** [comment]
Yes, this is the intended behaviour. (Not necessarily the *best* behaviour, but I couldn't think of a better way to handle nix-build on multiple output derivations...)

**Comment by timbertson** [comment]
Fair enough - @matthewbauer's workaround seems OK for scripts, thanks for that.
