### ISSUE TITLE
Retry downloading from binary cache before giving up and building the world

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#1236]
I just encountered this on a NixOS EC2 instance that configured itself from userdata:

```
stage-2-init: building the system configuration...
stage-2-init: download-from-binary-cache.pl: could not download ‘https://cache.nixos.org/nix-cache-info’ (Curl error 35)
```

After which, it decided to bootstrap itself from scratch, which was obviously not desirable 😄 

I know that we've since gotten rid of the perl script, but I think the downloader should retry the `nix-cache-info` (perhaps some configurable number of times) before giving up and rebuilding the world.

cc @shlevy @edolstra

**Comment by shlevy** [comment]
:+1:

**Comment by edolstra** [comment]
HttpBinaryCacheStore already retries requests.

**Comment by copumpkin** [comment]
@edolstra does it also handle this sort of thing? I assume it's CloudFront weirdness, but it actually returned a 404, which in some implementations might not trigger a retry.

```
fetching path ‘/nix/store/848zag9wigqq8clnr7nbxjwazcynabrf-vm-browserify-0.0.4.tgz’...
*** Downloading ‘https://cache.nixos.org/nar/0imlh6jy6kld27p4q1vsk9pmzplmxs27h74f84h9k7dsgq0ww6r1.nar.xz’ to ‘/nix/store/848zag9wigqq8clnr7nbxjwazcynabrf-vm-browserify-0.0.4.tgz’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 
/nix/store/5cpnwwnasypdi7p0av6qbaf52y99gmdz-xz-5.2.2-bin/bin/xz: (stdin): File format not recognized
error: unexpected end-of-file
download of ‘https://cache.nixos.org/nar/0imlh6jy6kld27p4q1vsk9pmzplmxs27h74f84h9k7dsgq0ww6r1.nar.xz’ failed: No such file or directory
could not download ‘/nix/store/848zag9wigqq8clnr7nbxjwazcynabrf-vm-browserify-0.0.4.tgz’ from any binary cache
fetching path ‘/nix/store/848zag9wigqq8clnr7nbxjwazcynabrf-vm-browserify-0.0.4.tgz’ failed with exit code 1
```

**Comment by edolstra** [comment]
No, because 404 is not considered a retryable error.

**Comment by edolstra** [comment]
And in fact, the issue here is that CloudFront caches the 404, so retrying wouldn't help.

**Comment by copumpkin** [comment]
Yeah, understandably. It does feel a bit like a https://en.wikipedia.org/wiki/Time_of_check_to_time_of_use issue though, so I'm wondering if there's a more atomic way to do this.
