### ISSUE TITLE
S3 store, retry policy

### ISSUE THREAD

**Issue by rbvermaa** [NixOS/nix#1237]
While uploading some store paths to S3 with nix 1.12 pre-release, I got the following error:

    error: AWS error fetching ‘nar/0pnvk2wyap9pdclvb8fw8sb3hshazbvr05hxx42rdslbzqdi1lcp.nar.xz’: No response body.  Response code: 500

Would it be possible to implement a retry strategy for S3 API calls, as AWS suggest as workaround for such errors?

**Comment by edolstra** [comment]
I've submitted a PR to aws-sdk-cpp that fixes this.
