### ISSUE TITLE
error: syntax error, unexpected INT, expecting ID or OR_KW or DOLLAR_CURLY or '"', at (string):1:74

### ISSUE THREAD

**Issue by davidak** [NixOS/nix#1239]
I installed a package i just created (https://github.com/NixOS/nixpkgs/pull/22981) and started `nix-shell` with it.

```
$ nix-env -i python3.5-PyZufall-0.13.2 -f ~/nixpkgs/
...
$ nix-shell -p python3.5-PyZufall-0.13.2
error: syntax error, unexpected INT, expecting ID or OR_KW or DOLLAR_CURLY or '"', at (string):1:74
```

That error message is not helpful at all since i even don't know where the error is.

@copumpkin had a similar error in https://github.com/NixOS/nix/issues/593

Is it an error with my package (don't have that error with other packages) or with nix-shell? How can i fix it?

**Comment by davidak** [comment]
>Is it an error with my package (don't have that error with other packages) or with nix-shell?

The problem is using the tools wrong and not reading the manpage.

The parameter `-p` (packages) is actually not the package name but the attribution name!

It works now with: `nix-shell -p python35Packages.pyzufall -I ~`

**Comment by bjornfor** [comment]
The error message could be better. For instance, it could highlight which string it failed in, similarly to gcc and clang.
