### ISSUE TITLE
nar executable

### ISSUE THREAD

**Issue by volth** [NixOS/nix#1257]
An executable for ```nar``` archiver is missing.
Something like:

- ```nar -c file.nar FILES``` to create archive
- ```nar -l file.nar``` to list archive content
- ```nar -d file.nar``` to extract files

It would allow to work with ```.nar``` files in bash scripts and add ```nar``` support to orthodox file managers (which allows to look inside archives like into the folders).

**Comment by edolstra** [comment]
Nix 1.12 has commands `nix ls-nar` and `nix cat-nar` to list/extract the contents of a NAR file. (00b2c05749f9777a91543cad9ecafb0981389be6). Creating NARs can be done using `nix-store --dump`.

**Comment by erikd** [comment]
I have started a library/executable to operate on Nix archives here https://github.com/input-output-hk/nix-archive . Its incomplete, but could easily be extended (and probably will be) to provide the required functionality.

**Comment by conferno** [comment]
That's cool!

Although Haskell could be a disadvantage here: one of the use cases is to have such a binary on `initrd`, to perform replacing of existing hosting Linux with NixOS (there are `nixos-infect` and `nixos-lustrate`, but they cannot repartitions disk, make an encrypted volume, etc; a similar tool running on `initrd` can do anything with disks, but then it has to download and unpack `.nar`'s)

**Comment by erikd** [comment]
Yes, that is a use case for which my code is probably useful. I have met my one specific use case. That's it :D.
