### ISSUE TITLE
Feature (removal) request: do not pipe through $PAGER by deafult

### ISSUE THREAD

**Issue by alexeymuranov** [NixOS/nix#1261]
I find it rather inconvenient that i have to set up `$NIX_PAGER` just to *disable* piping trough pager for commands like `nix-env -q`, whose equivalents in other OS do not use pager by default (`apt`, `aptitude`, home`brew`, etc.).  For me, passing the output of commands like `ls` through pager is unexpected and inconvenient.

What do others think?

Does any of the contributors actually enjoy using a pager with `nix-env -q` and such, or was this feature introduced "for the others"?

A side note (as i am arguing against using pager by default, this is not very relevant): with the pager used on my system for `man` output, at least i can scroll with the mouse wheel, but it does not work with the default pager of `nix-env`.

**Comment by vcunat** [comment]
There has already been a lengthy discussion on this very topic, I don't remember where exactly.  It's only done when connected to a terminal; I personally find it a reasonable compromise.  You can very easily set up that variable globally.  I think even `ls` changes behavior when run in a terminal...

**Comment by alexeymuranov** [comment]
`ls` changes behaviour??  I've never seen this.

I only run them in terminal, i do not know where else i can run them.

I think that environment variables should not be needed for just reverting to usual (/expected?) POSIX-like behaviour.  Do there exist any POSIX `ls`-like tools that use pager by default?

The argument that `$NIX_PAGER` variable is easy to set up applies both ways :).

I personally find paging `nix-env -q` plain inconvenient.

I had searched for a previous discussion before opening this issue, but didn't find any.

**Comment by vcunat** [comment]
The point of contention here is that the "usual/expected" way is thought to be to use a pager in this case.  I don't really care about the default personally, exactly because the behavior is so easy to change globally.

As for `ls`, you can e.g. try this command sequence with recent coreutils:
```
$ touch "fragile file name"
$ ls
$ ls | grep fragile
```
Columnizing is also automatically changed in the default setting, I think.  (But with `ls` we're getting off-topic IMO.)

**Comment by alexeymuranov** [comment]
Ok, I see what you mean about `ls`.  Personally, i am in favour of columnizing but not in favour of paging.

**Comment by alexeymuranov** [comment]
I have slightly edited the issue description.  As to why i mentioned `ls` -- because `nix-env -q` reminds me more of `ls` than of `man`, for example.

**Comment by veprbl** [comment]
Having a setting to use pager goes against Unix philosophy. And, yes, ```man``` is not UNIX'y in that respect, but at least it feels natural when it does that. A more relevant example of utility that does similar thing as nix is ```git stash```. Both of these surprise me with unexpected pager almost every time. In addition to this unexpectedness, there is a real usability problem. A command like ```git stash list``` is normally followed by a command that refers to the information in the output like ```git stash apply stash@{3}```, but the command line is blocked until pager quits, when you quit pager the information is hidden from the screen. The user is left to train their memory or to spend time copying info with the mouse. I also often find myself overcoming this by running ```rogue-command | cat```. This is especially annoying if the original output was just a few lines long in the first place.

**Comment by Profpatsch** [comment]
It’s a design flaw in how pipes & shells work, conceptually it would be clearer to never invoke a pager for any program, but in practice it’s just too convenient in many cases (particularly because `$PAGER` is set correctly on most systems).

**Comment by adamtulinius** [comment]
If it was done based on the amount of output, like with git, sure use a pager, but getting one line of output through the pager is just silly.

**Comment by Profpatsch** [comment]
> If it was done based on the amount of output, like with git, sure use a pager,

To prevent a usability nightmare: when paging is decided based on length of output, it’s impossible to build muscle memory.

**Comment by edolstra** [comment]
Paging is *already* based on the length of the output, since we use `less -F` by default (similar to systemd).

**Comment by adamtulinius** [comment]
> To prevent a usability nightmare: when paging is decided based on length of output, it’s impossible to build muscle memory.

That's why I'm in the no-paging camp, and would rather pipe something I know is lengthy through a pager myself if need be. :-)

> Paging is already based on the length of the output, since we use less -F by default (similar to systemd).

Interesting. Then it's just `less` being broken (at least here), or maybe the size that constitutes "one screen" is hard coded.

**Comment by aesyondu** [comment]
For reference, [to disable pager](https://github.com/NixOS/nix/pull/2656#issuecomment-571320152):

>Users who don't want a pager can export NIX_PAGER=cat but the reverse is not true.
