### ISSUE TITLE
nixpath doesn't work

### ISSUE THREAD

**Issue by husnoo** [NixOS/nix#1262]
According to:

http://nixos.org/nixos/manual/options.html#opt-nix.nixPath

I'm setting this in configuration.nix
```
{ config, pkgs, ... }:
{
  nix.nixPath = [ "/home/nawal/data" "nixos-config"=/etc/nixos/configuration.nix" ];
...
}
```

But i get an error:

```
error: syntax error, unexpected '=', at /home/nawal/data/nixos/configuration.nix:10:52
(use â€˜--show-traceâ€™ to show detailed location information)
```

**Comment by bjornfor** [comment]
You have one misplaced quote there: ```"nixos-config"=/etc/nixos/configuration.nix"```

**Comment by bjornfor** [comment]
The error message is actually pretty accurate, it points to the exact place where the problem is (52nd column)

**Comment by husnoo** [comment]
Ugh. I'm so sorry! I really shouldn't do this when I'm this tired.
