### ISSUE TITLE
~/.nix-profile/bin/clang++ is not able to compile a simple test program, OS X, ccmake

### ISSUE THREAD

**Issue by ftpronk** [NixOS/nix#1269]
### Operating system
- OS X 10.11.6, El Capitan
### Problem
I'm trying to compile VTK 6.3.0 using nix as a package manager for my build toolchain. Running ccmake returns the error:
>  CMake Error at /nix/store/72niq2iakqwsillnihzw0qrgq6srqrma-cmake-cursesUI-3.7.2/share/cmake-3.7/Modules/CMakeTestCXXCompiler.cmake:44 (message):
   The C++ compiler "/Users/---/.nix-profile/bin/clang++" is not able to
   compile a simple test program.

This is followed by a long output, ending with:

>   ld: library not found for -lc++
  clang-3.9: error: linker command failed with exit code 1 (use -v to see
   invocation)

### bashrc setup
```
load_nix()
{
  if [ -e /Users/---/.nix-profile/etc/profile.d/nix.sh ]; then
    . /Users/---/.nix-profile/etc/profile.d/nix.sh
  fi 

  export CC=/Users/---/.nix-profile/bin/clang
  export CXX=/Users/---/.nix-profile/bin/clang++
}
export -f load_nix
```

### Packages installed:
- bash-completion-2.5
- clang-wrapper-3.9.1
- cmake-cursesUI-3.7.2
- gnumake-4.2.1
- llvm-3.9.1
- nix-1.11.7
- nss-cacert-3.28.1
- python-2.7.13
- python2.7-ipython-5.2.1
- python2.7-numba-0.30.1
- python2.7-numpy-1.11.3
- python2.7-parsedatetime-2.1
- python2.7-pip-9.0.1
- qt-4.8.7

**Comment by ftpronk** [comment]
### Additional step tried
Explicitly setting DYLD_LIBRARY_PATH to .nix-profile/lib.  That resulted in a segfault 11 whenever trying to run a binary from .nix-profile/bin.

**Comment by copumpkin** [comment]
In general, the Nixpkgs compilers are generally geared towards running builds inside Nix, which will normally set up environment variables appropriately for you to make everything work. I haven't tried using the compiler outside of there.

**Comment by copumpkin** [comment]
Also, this is probably better suited to the nixpkgs issue tracker than the Nix one, which deals exclusively in the package/build manager tool itself.

**Comment by ftpronk** [comment]
Thank you for the return.  So the only way to get all the compilers to work properly would be to work from within a nix-shell environment?

**Comment by ftpronk** [comment]
> Also, this is probably better suited to the nixpkgs issue tracker than the Nix one, which deals exclusively in the package/build manager tool itself.

So any build-related problems are better posted in nixpkgs?

**Comment by copumpkin** [comment]
Yes and yes 😄

**Comment by ftpronk** [comment]
Understood. 👍
