### ISSUE TITLE
firefox and firefox-esr fail to build on unstable

### ISSUE THREAD

**Issue by mogorman** [NixOS/nix#1270]
checking for NSS - version >= 3.28.3... no
configure: error: you don't have NSS installed or your version is too old
DEBUG: <truncated - see config.log for full output>
DEBUG: #include <malloc.h>
DEBUG:                   #include <stddef.h>
DEBUG:                   size_t malloc_usable_size(const void *ptr);
DEBUG: int main() {
DEBUG: return malloc_usable_size(0);
DEBUG: ; return 0; }
DEBUG: configure:9923: checking for valloc in malloc.h
DEBUG: configure:9948: checking for valloc in unistd.h
DEBUG: configure:10103: checking NSPR selection
DEBUG: configure:10203: checking for nspr-config
DEBUG: configure:10238: checking for NSPR - version >= 4.13.1
DEBUG: configure:10314: /nix/store/wgvrkijby0awhqkyfkj0qp9cc4921hd9-gcc-wrapper-5.4.0/bin/gcc -std=gnu99 -c -fno-lifetime-dse  -fno-strict-aliasing -ffunction-sections -fdata-sections -fno-math-errno -pthread -I/nix/store/z1bz064xx99pggzvzx44v3pcn7sxz4x4-nspr-4.13.1-dev/include  conftest.c 1>&5
DEBUG: configure:10333: /nix/store/wgvrkijby0awhqkyfkj0qp9cc4921hd9-gcc-wrapper-5.4.0/bin/gcc -std=gnu99 -c -fno-lifetime-dse  -fno-strict-aliasing -ffunction-sections -fdata-sections -fno-math-errno -pthread -I/nix/store/z1bz064xx99pggzvzx44v3pcn7sxz4x4-nspr-4.13.1-dev/include  conftest.c 1>&5
DEBUG: configure:10381: /nix/store/wgvrkijby0awhqkyfkj0qp9cc4921hd9-gcc-wrapper-5.4.0/bin/gcc -std=gnu99 -c -fno-lifetime-dse  -fno-strict-aliasing -ffunction-sections -fdata-sections -fno-math-errno -pthread -I/nix/store/z1bz064xx99pggzvzx44v3pcn7sxz4x4-nspr-4.13.1-dev/include  conftest.c 1>&5
DEBUG: configure:10420: checking for libevent
DEBUG: configure:10427: checking MOZ_LIBEVENT_CFLAGS
DEBUG: configure:10432: checking MOZ_LIBEVENT_LIBS
DEBUG: configure:10605: checking for nss-config
DEBUG: configure:10640: checking for NSS - version >= 3.28.3
DEBUG: configure: error: you don't have NSS installed or your version is too old
ERROR: old-configure failed
builder for ‘/nix/store/yag51knblmw3zlydgrxy1rhg4qp8lh5h-firefox-esr-unwrapped-52.0esr.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/dyfp6l09n7215p684xvxv7pjs90qf89c-firefox-52.0esr.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/444f6d621mg1fprgkg0chw4dxcjsd71y-system-path.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/c6d6aprdj1bqbmvkffc8fqk8qfsc70v6-nixos-system-toadman-17.09pre102933.26625c9.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/c6d6aprdj1bqbmvkffc8fqk8qfsc70v6-nixos-system-toadman-17.09pre102933.26625c9.drv’ failed

**Comment by mogorman** [comment]
wrong tracker

**Comment by vcunat** [comment]
@mogorman: this has been fixed already.
