### ISSUE TITLE
All of nix's multi-user install methods seem to be broken

### ISSUE THREAD

**Issue by drewm1980** [NixOS/nix#1277]
I'm evaluating nix at a small company (currently on top of Ubuntu 14.04). I followed the single-user instructions, and had some moderate success setting up working, well isolated build environments (yay!). Unfortunately, that all fell apart when I tried to set nix up for a colleague with an account on the same machine. 

Running the single-user installer for multiple users failed for me.  Apparently the install script doesn't even check if nix is already installed before downloading a bunch of stuff.

Following the instructions for multi-user installation also failed for me; the nix tools aren't in root's path, and setting up the paths is non-trivial due to the path mangling.

The last time I tried installing nixos I couldn't even get my machine to boot.

Is there a build farm that is automatically testing your installation instructions? Installation needs to "just work" for nix to go viral.

**Comment by expipiplus1** [comment]
I wrote some instructions a while ago, although they're not scripted.

https://gist.github.com/expipiplus1/e571ce88c608a1e83547c918591b149f

I ran these instructions successfully yesterday on a fresh install of Ubuntu 16.10.

**Comment by drewm1980** [comment]
Thanks! We're not ready to upgrade to Ubuntu 16 yet, but I'll give this a shot when we do.

**Comment by expipiplus1** [comment]
Cool, I can't think of any reason why this wouldn't work on 14.04 too.

**Comment by domenkozar** [comment]
Closing as too old.
