### ISSUE TITLE
Write offsets of files in nar into `.ls.xz`?

### ISSUE THREAD

**Issue by bennofs** [NixOS/nix#1279]
I was just thinking about this: would it be possible to write the byte ranges of the files listed in the `.ls.xz` file that those files have in the `.nar`? If we have this information, we should be able to efficiently fetch single files from potentially huge nars by using http range queries.

Example use case: some tool might want to fetch just `propagated-build-inputs` or `propagated-user-env-pkgs` from a package, without fetching the whole derivation.

**Comment by copumpkin** [comment]
That'd be very cool. Some related work here by a friend of mine: https://github.com/planetbeing/partial-zip

**Comment by matthewbauer** [comment]
So would the byte ranges be post-decompression, or pre-decompression?

**Comment by bennofs** [comment]
oh, the files are compressed. that makes this idea impossible, since you cannot decompress `xz` without starting at the beginning :(

**Comment by matthewbauer** [comment]
I think it's possible, just not as easy as you originally thought.

**Comment by bennofs** [comment]
No, it isn't, since LZMA (the xz compression algorithm) is based on encoding repetitions of previous text in the buffer. So the only way to decode xz is to start from the beginning, since the decoding is dependent on the previous bytes.

**Comment by bennofs** [comment]
I've done some reading, and it appears that XZ supports splitting a file into multiple blocks and separately compressing them. We could use this feature, but I'm not sure if that's still worth it since we probably need a large block size for good compression ratio. Perhaps we should just store a separate NAR for some "interesting" files?

**Comment by bennofs** [comment]
I don't think this is realistic with the current compression scheme.
