### ISSUE TITLE
Only use ASCII with nix output messages

### ISSUE THREAD

**Issue by Unode** [NixOS/nix#1291]
I don't know when this change was introduced but it became more apparent as of nix-1.11.7.

Nix makes use of `‘%1%’` for displaying paths.
When running nix commands (e.g. in cron-jobs) I now get output like this:

```
path Ã¢ÂÂ/nix/store/00ai2akd0m5cnzxn6z68pd8lnhxz2zg5-python3.5-PythonEnv.drvÃ¢ÂÂ is not in the Nix store at /nix/var/nix/gcroots/system/bin/nix-shell line 263.
```

The same character is also shown as `_` or some other symbol when running inside `screen` or `tmux`. This sometimes gets in the way when copy-pasting a path.

The garbled output is likely related to encoding/locale issues but I was wondering if using ASCII backticks instead of ` ‘ ’ ` would be an acceptable solution.

Your thoughts?

**Comment by veprbl** [comment]
#1140 
215b70f51e5abd350c9b7db656aedac9d96d0046

**Comment by Unode** [comment]
@veprbl thanks. Closing as duplicate and moving discussion to #1140
