### ISSUE TITLE
Custom kernel from kernel.org problem

### ISSUE THREAD

**Issue by paolss** [NixOS/nix#1292]
building Nix...
building the system configuration...
these derivations will be built:
  /nix/store/8vckcs0myx1cgfii1l8gcppq0clkhnr5-linux-4.10.6.tar.xz.drv
  /nix/store/9d457af09ywd1i3c9qfz559n695rfrhb-cpupower-4.10.6-custom.drv
  /nix/store/ifx8w9zkgvvchsvbw6nkmvh043ws8kxd-linux-4.10.6-custom.drv
  /nix/store/ldhk2ki8w2bk4idlxp1k23nh42y1qhrx-VirtualBox-GuestAdditions-5.1.14-4.10.6-custom.drv
  /nix/store/kbzlrhjiakgpr1566i1ff3riz18kxshm-system-path.drv
  /nix/store/afsn0cl3bfnmzarvyhfl38mjikjvlpj6-dbus-conf.drv
  /nix/store/3varx1ini8wfww43fqjwf81hrscvqhkc-unit-dbus.service.drv
  /nix/store/4ljrb87wzk14m9y0z7dbrwh80swrhcfa-firmware.drv
  /nix/store/9mlmkkmkikpbx2pv7585z3hak94qdc0g-unit-dbus.service.drv
  /nix/store/kw3vvhw58nfsl4nkww99s9qr2fmcw2i7-unit-cpufreq.service.drv
  /nix/store/l2crjpqd2b6cn9k6yj379qp4wli3nihs-unit-polkit.service.drv
  /nix/store/shkncwk238cfccns208d6g7bxzbrbnwl-unit-virtualbox.service.drv
  /nix/store/8jfgravy30xixswxx4mmxpin8pw6xdhg-system-units.drv
  /nix/store/fska5pq1rknmjxpvd6qvg0bw5mp1vvkl-user-units.drv
  /nix/store/si4g5gr6anz6pv65aaai8k8wym12hhy4-kernel-modules.drv
  /nix/store/i8xm8y80807vq8n0i3gyk3mqaq9zd2l8-kernel-modules-shrunk.drv
  /nix/store/jnq86n200dbi1wa7nqk4k29ma1jw5s96-stage-1-init.sh.drv
  /nix/store/hscw7lb91p6hnv43ppxbxvh7m8f7d290-initrd.drv
  /nix/store/r8xcpfyiin1ndwld3wk1xnmpwq9d1y7s-etc-nixos.conf.drv
  /nix/store/manj1zldczhakqbdcvg4ymkjyw5gblpx-etc.drv
  /nix/store/y7cjnpz8aaaykpzqgjf9g62f7ivza94c-nixos-system-nixos_1-16.09.1836.067e66a.drv
building path(s) ‘/nix/store/v6n64zrqa2s86qrn20j46pmp4s19p060-linux-4.10.6.tar.xz’

trying http://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.10.6.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 89.8M  100 89.8M    0     0  1907k      0  0:00:48  0:00:48 --:--:-- 1974k
output path ‘/nix/store/v6n64zrqa2s86qrn20j46pmp4s19p060-linux-4.10.6.tar.xz’ has sha256 hash ‘1vjdd0i4k6m8nx5npwz5p3czg61j93wchw5amggrqfaarwy2j6j5’ when ‘13m0s2m0zg304w86yvcmxgbjl41c4kc420044avi8rnr1xwcscsq’ was expected
cannot build derivation ‘/nix/store/9d457af09ywd1i3c9qfz559n695rfrhb-cpupower-4.10.6-custom.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/ifx8w9zkgvvchsvbw6nkmvh043ws8kxd-linux-4.10.6-custom.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/y7cjnpz8aaaykpzqgjf9g62f7ivza94c-nixos-system-nixos_1-16.09.1836.067e66a.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/y7cjnpz8aaaykpzqgjf9g62f7ivza94c-nixos-system-nixos_1-16.09.1836.067e66a.drv’ failed

**Comment by globin** [comment]
This ticket should be in https://github.com/nixos/nixpkgs

**Comment by taktoa** [comment]
Someone with the appropriate permissions should close this issue.
