### ISSUE TITLE
How to get verbosity of 0?

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#1298]
The nix-build man page says

```
       --verbose, -v
           Increases the level of verbosity of diagnostic messages printed on standard error. For each Nix operation, the information printed on standard output is
           well-defined; any diagnostic information is printed on standard error, never on standard output.

           This option may be specified repeatedly. Currently, the following verbosity levels exist:

           0
               "Errors only": only print messages explaining why the Nix invocation failed.

           1
               "Informational": print useful messages about what Nix is doing. This is the default.

           2
               "Talkative": print more informational messages.

           3
               "Chatty": print even more informational messages.

           4
               "Debug": print debug information.

           5
               "Vomit": print vast amounts of debug information.
```

So one `-v` is the default, and the number of repetitions is the verbosity. How do I get back down to 0?

cc @edolstra @shlevy 😄

**Comment by dtzWill** [comment]
Haha looks like these are handled here:

https://github.com/NixOS/nix/blob/master/src/libmain/common-args.cc#L13

And that the counter to `-v` is `--quiet`.  Indeed, testing with `nix-build -vvv --quiet --quiet --quiet` vs `nix-build -vvvv --quiet --quiet --quiet` shows this in action (3 vs 4 v's), haha.

**Comment by copumpkin** [comment]
Oh, I don't think `--quiet` is even mentioned in the man page. At first I thought it was equivalent to `-Q` but that seems to be different.

**Comment by michalrus** [comment]
It’s not mentioned, should be!

**Comment by jcrben** [comment]
`This option may be specified repeatedly.` could be called out more with an example or something - I skimmed over it at first and was confused. In the ssh manual you see: `Multiple -v options increase the verbosity.` which is much easier to pick up on.
