### ISSUE TITLE
[nix Mac OS X Sierra 10.12.4] mu-0.9.18 cannot install due to pmccabe-2.6 error

### ISSUE THREAD

**Issue by ag91** [NixOS/nix#1301]
Hello,

Huge thanks for nix! I am trying to use this great package manager with a Mac, and I am having some issues trying to install my favourite email client. When I try to install mu with `nix-env -I mu`, I get the following error:

```
installing ‘mu-0.9.18’
error: Package ‘pmccabe-2.6’ in ‘/nix/store/p95wisxzddaqm41921jg1x9imwfai5jv-nixpkgs-17.09pre104948.c34db6e419/nixpkgs/pkgs/development/tools/misc/pmccabe/default.nix:25’ is not supported on ‘x86_64-darwin’, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.config/nixpkgs/config.nix.

(use ‘--show-trace’ to show detailed location information)
```

I checked the pmccabe derivation, and it has indeed a constraint on the platform: `platforms = platforms.linux;`.
Any way this derivation can work on Mac OS X x64?
Thanks,

Andrea

**Comment by copumpkin** [comment]
You'll want to ask in https://github.com/NixOS/nixpkgs. This is the tracker for the package manager itself, not for packages within it, and as such far fewer people notice issues posted here.

**Comment by ag91** [comment]
My bad, excuse my ignorance.
I am closing it here and opening it there.
Thanks!

**Comment by copumpkin** [comment]
No problem! We should make it clearer in the issue template what the different repositories are for 😄
