### ISSUE TITLE
macOS sporadic SSL errors

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nix#1303]
I've been seeing these on travis-ci, with Nix 1.11.8. They are all sporadic, happening either during Nix install fetching the binary or during substituting:

```
curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 60

...

curl: (56) SSLRead() return error -36 

...

curl: (56) SSLRead() return error -9806 
```

**Comment by copumpkin** [comment]
I've seen curl spitting out that `(56)` on linux fairly recently too. The errno was slightly different though, so it might be a different issue.

**Comment by domenkozar** [comment]
Again on macOS:

```
$ curl https://nixos.org/nix/install | sh
downloading Nix 1.11.8 binary tarball for x86_64-darwin from 'https://nixos.org/releases/nix/nix-1.11.8/nix-1.11.8-x86_64-darwin.tar.bz2' to '/var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/nix-binary-tarball-unpack.XXXXXXXXXX.PWLDUrvT'...
curl: (56) SSLRead() return error -36
sh: failed to download 'https://nixos.org/releases/nix/nix-1.11.8/nix-1.11.8-x86_64-darwin.tar.bz2'
```

**Comment by domenkozar** [comment]
Tbat hints it's a travis-ci issue rather than Nix since it wasn't really installed.

**Comment by matthewbauer** [comment]
This may be related to: https://www.traviscistatus.com/incidents/c742vnxmv3j9

**Comment by domenkozar** [comment]
This is not happening anymore with XCode 8.3, seems to be a problem with older openssl versions shipped with OSX

**Comment by domenkozar** [comment]
This is an openssl error on host, outside of Nix so I'm closing it.
