### ISSUE TITLE
Possible regression in Nix 1.12 behavior with tarball channel URLs

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#1318]
I just spotted this in my logs:

```
Apr 10 16:12:35 my-ip.ec2.internal amazon-init-start[848]: error: unable to download ‘http://s3.amazonaws.com/path/to/my/channel.tar.gz/nixexprs.tar.bz2’: HTTP error 403 (curl error: No error)
```

Judging by [this line](https://github.com/NixOS/nix/blob/master/src/nix-channel/nix-channel.cc#L105), the new C++ `nix-channel` implementation still checks for `.tar.gz` extensions but somehow that isn't taking effect above, as you can clearly see it trying to download `nixexprs.tar.bz2` at the end of the `.tar.gz` URL.

Looking into it more now for a smaller repro.

Edit: TBC, it's a 403 because the file doesn't exist

cc @edolstra @shlevy

**Comment by copumpkin** [comment]
I'm guessing something fails in the unpack, which the empty `catch` ignores, and then it falls back to the other logic

**Comment by dtzWill** [comment]
Hmm, any luck with debugging the unpack?

I'm unable to reproduce myself at least in the simple case:

```console
$ nix-channel --add http://wdtz.org/files/nixexprs.tar.xz wdtz
$ nix-channel --update
downloading ‘http://wdtz.org/files/nixexprs.tar.xz’... [0/0 KiB, 0.0 KiB/s]
```
(I just put an empty channel up for testing purposes)

So it doesn't appear to be entirely broken.

If the URL redirects and the new "effective" URL doesn't contain the right suffix...that might cause the behavior you're seeing?

**Comment by copumpkin** [comment]
I've reproduced it, but only the tarball is corrupt somehow. So you point it at a valid URL that contains an invalid tarball (unsure if it considers subtle things invalid, but easiest is to just corrupt the file); then it will try to hit `nixexprs.tar.xz|bz2`. I think the answer is to just fail loudly in that `catch`, so at least we don't hide the real error.

**Comment by shlevy** [comment]
Hmm, I'm not sure we want to print out a warning there, I don't know if it's the usual case that a channel is a direct tarball vs a channel folder. @edolstra Thoughts?

**Comment by copumpkin** [comment]
I was actually suggesting an error because it seems super unlikely that someone wants us to look for `foo.tar.gz/nixexprs.tar.xz` 😄

**Comment by shlevy** [comment]
Yeah OK :grin:

**Comment by copumpkin** [comment]
Aha, I think I know more about what's going wrong here. Details coming soon.

**Comment by copumpkin** [comment]
So yes, I think this is it. My tarball isn't corrupt, but the machine is on a network that can't speak to cache.nixos.org. In the past, I set `connect-timeout` to a short value (it used to default to infinity IIRC) so that I can use the same image against cloudfront or a private S3 bucket (nix eagerly tries to look for `/nix-cache-info` on all registered binary caches).

With 1.12, Nix seems to be ignoring my value for `connect-timeout`, and is waiting for ages. Running the `runCommand` command by hand with lots of `-v`s, I see this:

```
download thread waiting for 1000000000 ms
starting download of https://cache.nixos.org/nix-cache-info
curl: Couldn't find host cache.nixos.org in the .netrc file; using defaults
curl:   Trying 54.192.192.215...
curl: TCP_NODELAY set
download thread waiting for 1000000000 ms
download thread waiting for 1000000000 ms
download thread waiting for 1000000000 ms
curl:   Trying 2600:9000:2015:ae00:10:dfa4:b0c0:93a1...
curl: TCP_NODELAY set
curl: Immediate connect fail for 2600:9000:2015:ae00:10:dfa4:b0c0:93a1: Network is unreachable
curl:   Trying 2600:9000:2015:e800:10:dfa4:b0c0:93a1...
curl: TCP_NODELAY set
curl: Immediate connect fail for 2600:9000:2015:e800:10:dfa4:b0c0:93a1: Network is unreachable
curl:   Trying 2600:9000:2015:fc00:10:dfa4:b0c0:93a1...
curl: TCP_NODELAY set
curl: Immediate connect fail for 2600:9000:2015:fc00:10:dfa4:b0c0:93a1: Network is unreachable
curl:   Trying 2600:9000:2015:1000:10:dfa4:b0c0:93a1...
curl: TCP_NODELAY set
curl: Immediate connect fail for 2600:9000:2015:1000:10:dfa4:b0c0:93a1: Network is unreachable
curl:   Trying 2600:9000:2015:3000:10:dfa4:b0c0:93a1...
curl: TCP_NODELAY set
curl: Immediate connect fail for 2600:9000:2015:3000:10:dfa4:b0c0:93a1: Network is unreachable
curl:   Trying 2600:9000:2015:4800:10:dfa4:b0c0:93a1...
curl: TCP_NODELAY set
curl: Immediate connect fail for 2600:9000:2015:4800:10:dfa4:b0c0:93a1: Network is unreachable
curl:   Trying 2600:9000:2015:5c00:10:dfa4:b0c0:93a1...
curl: TCP_NODELAY set
curl: Immediate connect fail for 2600:9000:2015:5c00:10:dfa4:b0c0:93a1: Network is unreachable
curl:   Trying 2600:9000:2015:9000:10:dfa4:b0c0:93a1...
curl: TCP_NODELAY set
curl: Immediate connect fail for 2600:9000:2015:9000:10:dfa4:b0c0:93a1: Network is unreachable
download thread waiting for 1000000000 ms
curl: connect to 54.192.192.215 port 443 failed: Connection timed out
curl:   Trying 54.192.192.223...
curl: TCP_NODELAY set
download thread waiting for 1000000000 ms
curl: After 85725ms connect time, move on!
curl:   Trying 2600:9000:2015:ae00:10:dfa4:b0c0:93a1...
curl: TCP_NODELAY set
curl: Immediate connect fail for 2600:9000:2015:ae00:10:dfa4:b0c0:93a1: Network is unreachable
curl:   Trying 2600:9000:2015:e800:10:dfa4:b0c0:93a1...
curl: TCP_NODELAY set
curl: Immediate connect fail for 2600:9000:2015:e800:10:dfa4:b0c0:93a1: Network is unreachable
curl:   Trying 2600:9000:2015:fc00:10:dfa4:b0c0:93a1...
curl: TCP_NODELAY set
curl: Immediate connect fail for 2600:9000:2015:fc00:10:dfa4:b0c0:93a1: Network is unreachable
curl:   Trying 2600:9000:2015:1000:10:dfa4:b0c0:93a1...
curl: TCP_NODELAY set
curl: Immediate connect fail for 2600:9000:2015:1000:10:dfa4:b0c0:93a1: Network is unreachable
curl:   Trying 2600:9000:2015:3000:10:dfa4:b0c0:93a1...
curl: TCP_NODELAY set
curl: Immediate connect fail for 2600:9000:2015:3000:10:dfa4:b0c0:93a1: Network is unreachable
curl:   Trying 2600:9000:2015:4800:10:dfa4:b0c0:93a1...
curl: TCP_NODELAY set
curl: Immediate connect fail for 2600:9000:2015:4800:10:dfa4:b0c0:93a1: Network is unreachable
curl:   Trying 2600:9000:2015:5c00:10:dfa4:b0c0:93a1...
curl: TCP_NODELAY set
curl: Immediate connect fail for 2600:9000:2015:5c00:10:dfa4:b0c0:93a1: Network is unreachable
curl:   Trying 2600:9000:2015:9000:10:dfa4:b0c0:93a1...
curl: TCP_NODELAY set
curl: Immediate connect fail for 2600:9000:2015:9000:10:dfa4:b0c0:93a1: Network is unreachable
curl: connect to 54.192.192.223 port 443 failed: Connection timed out
curl:   Trying 54.192.192.5...
curl: TCP_NODELAY set
download thread waiting for 1000000000 ms
curl: Connection timed out after 345637 milliseconds
curl: stopped the pause stream!
curl: Closing connection 0
finished download of ‘https://cache.nixos.org/nix-cache-info’; curl status = 28, HTTP status = 0, body = 0 bytes
download thread waiting for 1000000000 ms
reaping 1 worker threads
error: unable to download ‘https://cache.nixos.org/nix-cache-info’: Timeout was reached (28)
download thread shutting down
```

So there seem to be two regressions at play here:

1. 1.12 is ignoring `connect-timeout` in my nix.conf (amusingly, my PR for strictly modeled options would've caught this, because nobody asks for the value anymore)
2. When I have multiple binary caches configured, and one of them is inaccessible, 1.12 fails, even if the others are accessible

@edolstra @shlevy does that make sense?

**Comment by shlevy** [comment]
Yep, makes sense.Not really sure how to fix 2 even if 1 is fixed but `connect-timeout` is infinite

**Comment by copumpkin** [comment]
Not quite infinite, but 11.57 days is quite a while. I'm guessing there's some other timeout at play that causes it to end in a normal time.

**Comment by copumpkin** [comment]
For part 2, it seems like `BinaryCacheStore::init()` (or even the underlying store API) might need to be able to return failure so it doesn't get registered? @edolstra

**Comment by copumpkin** [comment]
For now I'll just make tailored images that don't include binary caches that aren't expected to be accessible, but it does seem like a regression.

**Comment by copumpkin** [comment]
@edolstra I think #1321 only addresses the visibility of the issue. The two core issues above are still present. I can create a separate ticket if you'd prefer, since this one got a bit messy.

**Comment by copumpkin** [comment]
Opened separate tickets for those issues in #1340 and #1339
