### ISSUE TITLE
nix-shell doesn't respect system input for packages

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nix#1323]
Passing `system` to nix-shell is not enough to get 32bit packages instead of 64bit. 

```
$ nix-shell -p hello file --argstr system i686-linux --run 'file $(type -P hello)' --pure
/nix/store/3g51yx63zg0jrznhxk4951xczjpw2ph2-hello-2.10/bin/hello: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /nix/store/vn6fkjnfps37wa82ri4mwszwvnnan6sk-glibc-2.25/lib/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, not stripped
```
Using `pkgsi686Linux` does work though:

```
$ nix-shell -p pkgsi686Linux.hello pkgsi686Linux.file --argstr system i686-linux --run 'file $(type -P hello)' --pure
/nix/store/gs9vgrkqqw46pflclciyfnjqvm50irw4-hello-2.10/bin/hello: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /nix/store/vhb4ijd7341pk0py9y5f4ywx80q7hpdi-glibc-2.25/lib/ld-linux.so.2, for GNU/Linux 2.6.32, not stripped
```

**Comment by prusnak** [comment]
This is again very relevant for people wanting to use both `x86_64-darwin` and `aarch64-darwin` at the same time.

**Comment by prusnak** [comment]
Is someone working on this? Or can someone at least point me to why is this not working and what needs to be fixed?

**Comment by regnat** [comment]
> Is someone working on this? Or can someone at least point me to why is this not working and what needs to be fixed?

I don’t think anyone is.

If the error is just about `nix-shell -p`, I’d say that the issue is that it’s actually a hack that expands `nix-shell -p hello` to `nix-shell --expr ''with import <nixpkgs> {}; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ hello ]; } ""'` ([here](https://github.com/NixOS/nix/blob/master/src/nix-build/nix-build.cc#L269-L282). And the generated Nix expression doesn’t take any argument, so `--arg` can’t have any effect.

Possibly changing the Nix expression to something like `{...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ hello ]; } ""` would fix it

**Comment by prusnak** [comment]
> If the error is just about `nix-shell -p`

No, it's not limited to `-p`.

**Comment by regnat** [comment]
Do you have an example of a failing call without `-p`? I just tried with the `shell.nix` below and it seemed to be working just fine:

```nix
{ system ? "x86_64-linux" }:
let pkgs = import <nixpkgs> { inherit system; }; in
pkgs.mkShell {
  buildInputs = [ pkgs.hello ];
}
```

**Comment by prusnak** [comment]
> Do you have an example of a failing call without `-p`?

```
with import <nixpkgs> {};

stdenv.mkDerivation {
  name = "hello-test";
  buildInputs = [ hello ];
  shellHook = ''
    file $(which hello)
  '';
}
```

**Comment by regnat** [comment]
> When I changed system in /etc/nix/nix.conf - the derivation above correctly changes the output. When I use --argstr, the output stays the same.

Oh yes, but that’s expected, `--argstr system` isn’t the same thing, it just passes the `system` argument to the Nix expression if it’s a function (which isn’t the case in your example). But now that I think of it, what you want can be done with `--option system something` which should work in any case

**Comment by prusnak** [comment]
Ah, that's great! I confirm that `--option system foo` solves my problem.
