### ISSUE TITLE
`nix-env -qP` does not quote attributes that need to be quoted

### ISSUE THREAD

**Issue by ahmedtd** [NixOS/nix#1342]
`nix-env -qP` doesn't quote components of attribute paths that need to be quoted.

For example, the attribute `lispPackages."hu.dwim.asdf"` is output as `lispPackages.hu.dwim.asdf`.   Trying to use the output directly results in the error:
````
error: attribute ‘hu’ in selection path ‘nixos.lispPackages.hu.dwim.asdf’ not found
````

This breaks tools that consume `nix-env` output (`nox-review`, for example, dies if the change requires a rebuild of `lispPackages."hu.dwim.asdf"`)

**Comment by edolstra** [comment]
Attribute names should not contain dots. This is a bug in Nixpkgs, which should not use `hu.dwim.asf` as an attribute name.

**Comment by copumpkin** [comment]
Does that mean the sysctl NixOS module is also flawed?

**Comment by 7c6f434c** [comment]
If attribute names should not contain dots, what is the rationale for the attribute name quoting syntax in Nix (that also doesn't warn about wrong names)? Is it a bug that converting list to attribute set doesn't complain on wrong names? I always thought it was added exactly to support sane attribute naming of packages with upstream names starting with a digit.
