### ISSUE TITLE
Can we get a 1.11.9 release?

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#1343]
As someone who flips between 1.11 and 1.12 a lot for testing, I'm getting bitten a lot by the bug I fixed in https://github.com/NixOS/nix/issues/1333, and it'd be nice to have a release that incorporates that (and a few other recent fixes)

**Comment by armijnhemel** [comment]
I guess that this can be closed, as 1.11.9 was released by @edolstra

**Comment by copumpkin** [comment]
Yep, thanks!
