### ISSUE TITLE
--arg doesn't work for functions with ...

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nix#1360]
The ```--arg``` option does not seem to pass args to a function when it isn't explicitly listed as an argument. This breaks when you use "ellipsis" for example in impure.nix:

https://github.com/NixOS/nixpkgs/blob/bdd89faebb2c3d7c291776643de65efbc5172b44/pkgs/top-level/impure.nix#L21

see NixOS/nixpkgs#25215 for more discussion

**Comment by edolstra** [comment]
This is by design. We only want to pass arguments that a function explicitly expects.

**Comment by regnat** [comment]
I must admit I don't really understand the reason for this. Is this a
security feature to prevent accidentally passing unwanted arguments or
is there another reason?

**Comment by matthewbauer** [comment]
@edolstra I guess isn't the function asking for unexpected args when it has the ```...```/ellipsis? I guess the issue is that it only comes into play when you are using ```--arg``` because you can pass other args in as well.

Anyway, if it is by design, can we get it documented? All I see on with is here in the manual:

http://nixos.org/nix/manual/#idm140737318021024

But I definitely could have missed it.

**Comment by Ericson2314** [comment]
@edolstra is that a good design though? Certainly functions without ellipses should not accept unlisted arguments but the whole point of ellipses is that the set of parameter is open-ended. At the very least it should be an error to pass an improper argument.

**Comment by ledettwy** [comment]
@edolstra I'm also not convinced that this was the right decision. There's a usecase where a function can be "built" dynamically in Nix like this: `(args @ { ... }: builtins.getAttr "a" args)`.  Allowing dynamically built functions like these to accept arguments from `--arg` and `--argstr` would be *really* useful. What value are Nix users getting by this not being allowed?

**Comment by zimbatm** [comment]
Is there a use-case where silently dropping unsupported args makes sense? It seems to me like it would be preferable to be explicit about these types of things. The person who writes the nix code is still able to decide whenever arbitrary arguments are allowed or now with the `...` syntax.

Right now it's problematic because it's not possible to detect when an argument is unsupported. This can happen if the key is mistyped and a default value is available in the function attributes for example.

**Comment by zimbatm** [comment]
I found where the logic resides, it's embedded deep into libexpr: https://github.com/NixOS/nix/blob/4ae6e849015fb269414c1544e815aba75085cf7b/src/libexpr/eval.cc#L1205-L1218

**Comment by edolstra** [comment]
Fixed by 626200713bb3cc844a9feb6af583c9b6b42c6dbc.

**Comment by IreneKnapp** [comment]
For anyone reading this who, like me, was confused as to what the outcome of the discussion was: The feb 15 patch resolves the issue by implementing the feature.
