### ISSUE TITLE
HTTP/2 cannot be depended on

### ISSUE THREAD

**Issue by 0xABAB** [NixOS/nix#1362]
I just got the following message while doing a `nixos-rebuild`.
```
curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)
```

I doubt services are `HTTP/2` only, so there should be a HTTP fallback available for robustness for example. 

Just google for the error message: it affects many hosting services, so assuming this will be fixed globally is not a good plan.

**Comment by edolstra** [comment]
What version of `nghttp2` are you using? (`ldd $(type -p nix) | grep libnghttp2`) This may have been fixed already: https://github.com/nghttp2/nghttp2/pull/736

You can already disable HTTP/2 support by setting `enable-http2 = false` in `nix.conf`. Doing automatic fallback sounds tricky - I don't know for what set of curl errors a fallback to HTTP would be appropriate.

**Comment by RdN-MSF** [comment]
@edolstra : what's the status of this? I'm getting http/2-related errors on one of my servers but adding the option you mentioned to nix.conf results in messages about an unknown setting and I don't see any reference in the manpage for nix.conf either.

What's the recommended way for disabling http/2?

For reference, the error I'm getting during nixos-rebuild is the following:
```
HTTP error 200 (curl error: Stream error in the HTTP/2
framing layer)
```

I can reproduce this by downloading the archive manually by curl. The download succeeds without issues when adding the `--http1.1` option.

**Comment by edolstra** [comment]
The option is `http2 = false` (or on the command line, `--no-http2`).

BTW, Nix is supposed to treat this error as transient and retry automatically.

**Comment by RdN-MSF** [comment]
@edolstra : I tried this at the command line with `nixos-rebuild` which complains about an invalid option. I also put the option in `/etc/nix/nix.conf`, restarted the nix deamon, and reran `nixos-rebuild`, but then I get the same http/2-error, which seems to indicate that the option is not being picked up.
I cannot find any documentation about this option either.

I'm running nix version 2.1.3.

**Comment by edolstra** [comment]
Oh yeah, `nixos-rebuild` doesn't support every Nix command line flag. Though `--option http2 false` should work.

I just noticed you wrote

> on one of my servers 

so this is not on `cache.nixos.org`? Maybe the server is misconfigured in some way and you need to disable (or fix) HTTP/2 support serrver-side?

**Comment by RdN-MSF** [comment]
Ah, no, by server I meant the NixOS instance which does not manage to update itself anymore. I'm using the standard settings and `cache.nixos.org`.

With the option you mentioned, `nixos-rebuild` seems to have managed to download a couple of archives before I get time-outs. This is probably related to the network connection (the server is located in a very remote rural area with only a satellite connection).

However, I got an http/2 error again as well and the build fails. This is the output I get: https://pastebin.com/agFUvxkC

You have any suggestions?

**Comment by edolstra** [comment]
Closing, nothing to do here.
