### ISSUE TITLE
𝐍𝐎𝐓 𝐉𝐎𝐊𝐈𝐍𝐆: Port Nix to Windows, Natively or MinGW+MSYS2

### ISSUE THREAD

**Issue by be5invis** [NixOS/nix#1365]
Possible combinations:

- Native. No dependency. This may be very hard for \*nix developers since they do not have any knowledge about how to do native Win32 development (like: avoid using `char*`).
- MinGW/MSYS2. Since `nix` may depend on many Unix external libraries. However the APIs implemented in MinGW may have artifacts on Windows (i.e. Unicode support).
- [Midipix](http://midipix.org/). It is under early development but its’ library design is better.

**Comment by edolstra** [comment]
Closing as too vague. This issue asks for a bunch of things, so it's unclear when it could be closed. Also, Nix (AFAIK) already builds on Cygwin.

There already is #1320 for MinGW support.

**Comment by puffnfresh** [comment]
It also works on the Windows Subsystem for Linux (aka Bash on Ubuntu on Windows)

**Comment by voronoipotato** [comment]
Part of NPM's success is that it worked in windows, mac, and linux without any special configuration. Yes WSL and Cygwin should be considered special configuration. Food for thought.

**Comment by sbourdeauducq** [comment]
If there is funding for this, would there be people willing to take on that job?

Things that I particularly want to get working are:
* No WSL, Cygwin or anything that the user has to install themselves or is buggy (Cygwin I'm looking at you). Midipix or MSYS may be OK if they are reliable and transparent.
* Python and some rather usual packages
* LLVM
* Qt in native mode - none of this X server stuff that doesn't work - and PyQt/PySide
* Yosys, Nextpnr, OpenOCD
* Some GUI installer for newbies that sets up a pre-defined functional environment that more advanced users can tweak later.

**Comment by puffnfresh** [comment]
Why is MSYS acceptable but not WSL?

**Comment by sbourdeauducq** [comment]
AFAIK MSYS applications are simply linked against some special libraries, and then from a user perspective behave as regular Windows applications (but I might be wrong).
WSL requires significant user intervention to set up.

**Comment by puffnfresh** [comment]
Have you tried to compile Nix using MSYS or similar? I'm skeptical Nix won't need a significant rewrite to achieve that but I hope to be wrong.
