### ISSUE TITLE
nix-env -i NEWLINE tries to install the world

### ISSUE THREAD

**Issue by nh2** [NixOS/nix#1373]
I just tried to do something like:

```
nix-env -i $(nix-build --no-out-link -E '(import <stable> {}).texmacs.overrideDerivation (old: { configureFlags = "--with-qt"; })')
```

because of a network failure, the `nix-build` inside the `$()` shell substitution failed, and output nothing.

This made nix try to install *all* nixpkgs packages that exist.

Example to reproduce:

```bash
touch emptyfile
nix-env -i $(cat emptyfile)
```

Interestingly, `nix-env -i ""` doesn't have the problem; it simply says `error: selector ‘’ matches no derivations`.

That's why I think this is a bug.

**Comment by expipiplus1** [comment]
Looks like a duplicate of https://github.com/NixOS/nix/issues/1334

**Comment by nh2** [comment]
Yes, I think you're right, closing as duplicate.
