### ISSUE TITLE
preferLocalBuild documentation incorrect

### ISSUE THREAD

**Issue by shlevy** [NixOS/nix#1378]
`preferLocalBuild` is only checked to determine whether or not to use the build hook, not anything to do with substitutes. `allowSubstitutes` is the relevant attribute for that.

---

Original issue:

I have a `drv` with `preferLocalBuild` set to `1` that was fetched regardless. If it matters, this was during import-from-derivation.

**Comment by domenkozar** [comment]
@shlevy it would help to have a minimal test case and nix version.

**Comment by shlevy** [comment]
It turns out this is just a documentation issue. `preferLocalBuild` is only checked to differentiate build hook vs not build hook, `allowSubstitutes` is the actual attribute I want here.

**Comment by domenkozar** [comment]
If it's documentation issue, let's fix it :)

**Comment by shlevy** [comment]
Closing this to clear up my open issues list, please open a new one if interested in pursuing this.

**Comment by ledettwy** [comment]
I'm confused - why was this issue closed if it's a valid issue?
