### ISSUE TITLE
A way to pass arguments directly to a command under nix-shell

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#1383]
I don't know the best way to do this interface. I seem to remember that the "traditional" `--` wouldn't work for some reason (I don't remember why), but `--command` and `--run` are awkward because quoting the arguments can get pretty ugly. Passing it in the original `argv` is much more pleasant because we don't need a whole shell escape step. Is there a good way to support direct arguments now that we're getting the new Nix UI?

cc @edolstra

**Comment by edolstra** [comment]
See #1189, #534.

**Comment by copumpkin** [comment]
Dupe, thanks!
