### ISSUE TITLE
Documentation refers to "sysconfdir" but does not define it

### ISSUE THREAD

**Issue by chreekat** [NixOS/nix#1385]
Perhaps those references should just be changed to "/etc"? If it's possible to change it, I'm sure the person doing so will know what they are doing. Or add a blurb somewhere (like nix.conf(5) manpage) saying the default for sysconfdir is /etc?

**Comment by david-varela** [comment]
I had trouble figuring this out when reading the manual. A google search led to this issue. Otherwise, I don't think I would be able to determine what directory 'sysconfdir' refers to just by reading the manual.

**Comment by chreekat** [comment]
I now only see one reference to "sysconfdir" in the manual, and it is immediately given an example definition:

> The system-wide configuration file *sysconfdir*/nix/nix.conf (i.e. /etc/nix/nix.conf on most systems), or $NIX_CONF_DIR/nix.conf if NIX_CONF_DIR is set.
>
> —[Nix, Chapter 21: Files](https://nixos.org/nix/manual/#ch-files)

Closing! \o/
