### ISSUE TITLE
`nix-shell -p pkg` does not consider passthru attributes of derivations.

### ISSUE THREAD

**Issue by nbp** [NixOS/nix#1388]
Not having the passthru attribute being considered implies that listing the build inputs of a package would not provide a working environment.

**Comment by edolstra** [comment]
I don't understand. Please add an example.

**Comment by nbp** [comment]
Ok, I mess-up between `passthru` attribute, and the `propagatedBuildInputs` attribute.

The rust issue mentioned above works when I add `propagatedBuildInputs = [ stdenv.cc ];` to the rust compiler expression.
