### ISSUE TITLE
Error when building coreutils on armhf

### ISSUE THREAD

**Issue by ss89** [NixOS/nix#1390]
Hello everyone,

i am relatively new to nix.
What i tried to do was build a docker container using my (on x86_64 working) dockerfile.
When building on arm, i am stuck at coreutils which fails on the "direct" test.
You can see the complete log output here (CAREFUL! ~32MB DATA).
https://code.rhodecode.com/_admin/gists/384/tip/raw

Best regards,
ss89

**Comment by jcrben** [comment]
Looks like you were running nix-1.11.9 - maybe try the new version?

Since you were building from a dockerfile, why not provide the dockerfile?

**Comment by ss89** [comment]
i saw this a little late and have moved away from using arm at all.

If you still want to see if the issue is still there (and fix it), maybe this will be a good starting point:
https://github.com/ss89/docker-rhodecode-ce

Otherwise, feel free to close the issue.

**Comment by vcunat** [comment]
Hmm, I think we'll close.  It's really old, so one would first need to check whether the problem still holds, and then it would belong to [a different repo](https://github.com/nixos/nixpkgs/issues).
