### ISSUE TITLE
nix-env -e does not have correct autocompletion when uninstalling i3lock-color

### ISSUE THREAD

**Issue by savage-engineer** [NixOS/nix#1397]
On NixOS I am unable to uninstall the `i3lock-color` package. The command `nix-env -e i3lock-color{version}` has been run as my user, through sudo and as the root user to no effect. Have tried to make sure that it's not in use by any profile and it's not in any of my NixOS config files.

Following running the command it remains in the `~/.nix-profile/bin` location.

Running the following produces the output shown.
```
λ ~/ nix-env -e i3lock-color-2.7-2016-09 --verbose                                                                                                                                              ~
evaluating file ‘/nix/store/85g53pzfnq6vsn233i2jzjf0ixmh0qd8-nix-1.11.8/share/nix/corepkgs/derivation.nix’
evaluating file ‘/nix/store/k587zw1gfdmy27bxy7f6lfgz7r42cnwv-env-manifest.nix’
evaluating file ‘/nix/store/85g53pzfnq6vsn233i2jzjf0ixmh0qd8-nix-1.11.8/share/nix/corepkgs/buildenv.nix’
evaluating file ‘/nix/store/85g53pzfnq6vsn233i2jzjf0ixmh0qd8-nix-1.11.8/share/nix/corepkgs/config.nix’
```
If I try to reinstall it:
```
λ ~/ nix-env -iA nixos.i3lock-color                                                                                                                                                             ~
replacing old ‘i3lock-color-2.7-2016-09-17’
installing ‘i3lock-color-2.7-2016-09-17’
```
It successfully re-installs/updates the package.

I'm not sure if this is an issue with my configuration, with Nix or with the package in question (as I can seemingly install/uninstall other similar packages such as `i3lock-fancy`. Is there any way to forcibly remove it?

**Note:** I have done deletion of old generations and GC for all users (and NixOS configs) to no avail. I am new to Nix & NixOS so am unsure where to go next with this.

**Comment by bjornfor** [comment]
I think you're missing the "-17" part of the version number.

**Comment by savage-engineer** [comment]
I didn't even think to read that, I just assumed shell completion worked. I manually appended the "-17" to it and it did indeed work. That's odd though, as that was the result of tab completion. It didn't appear to suggest the full name, only that partial name. 

Thanks for the help!

I wonder what might have caused this to be the case...

**Comment by jfrankenau** [comment]
@savage-engineer, this is not i3lock-color's fault but instead due to the shell's completion. I am assuming you are using zsh as well? This problem is fixed in https://github.com/spwhitt/nix-zsh-completions/commit/ad4477be7c63af2167f1e2bc2857127700321341.

**Comment by savage-engineer** [comment]
@jfrankenau Yep, I'm using oh-my-zsh.

_Sent from my HTC U11 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
