### ISSUE TITLE
WSL "error: setting synchronous mode: disk I/O error" with plenty of space on disk

### ISSUE THREAD

**Issue by pikajude** [NixOS/nix#1398]
AFAICT this only happens when running nix-shell.

Output from -vvv is here https://gist.github.com/anonymous/bb793b2146c24e2cccd4848ee81d91b6

**Comment by edolstra** [comment]
WSL == Windows Subsystem for Linux?

**Comment by edolstra** [comment]
Dupe of #1203?

**Comment by pikajude** [comment]
@edolstra looks that way
