### ISSUE TITLE
nix-prefetch-url runs out of memory for large files

### ISSUE THREAD

**Issue by knedlsepp** [NixOS/nix#1400]
I'm currently trying to use the Intel parallel studio from within nix. I'm thus trying to prefetch the 4.4GB download. However on my 8GB RAM machine, with 6.5GB of free memory the program exits with:

```
$ nix-prefetch-url file:///home/jkemet/Downloads/parallel_studio_xe_2017_update4.tgz 
downloading ‘file:///home/jkemet/Downloads/parallel_studio_xe_2017_update4.tgz’... [4170385/4535089 KiB, 118749.4 KiB/s]error: out of memory
```

I'm using nix version 1.11.9.

**Comment by bjornfor** [comment]
Related PR: https://github.com/NixOS/nix/pull/619
