### ISSUE TITLE
How to remove nix

### ISSUE THREAD

**Issue by jarry9** [NixOS/nix#1402]
Hi,

I am using nix on Ubuntu 16. I installed nix by these commands:

bash <(curl https://nixos.org/nix/install)
source ~/.nix-profile/etc/profile.d/nix.sh

I have not started nix-daemon. Or I did not use any extra command...

I will not remove the nix package manager now. But If I should remove it, what should I type on command line? Is there any ready script or something?

I found this topic: https://github.com/NixOS/nix/issues/458 But it is not completely clear about uninstallation. Because there is not only /nix folder. There are link files on HOME + nix has set some directories to PATH variable?

How can I make sure that I remove it completely?

Thank you

**Comment by zimbatm** [comment]
To uninstall nix you will need to do the following things:
* remove the `. "$HOME/.nix-profile/etc/profile.d/nix.sh"` in your `~/.profile` or `~/.bash_profile`
* `rm -rf $HOME/{.nix-channels,.nix-defexpr,.nix-profile,.config/nixpkgs}`
* `sudo rm -rf /nix`
On a multi-user install, also remove all the `nixbld[0-9]` users

**Comment by jarry9** [comment]
Thank you

**Comment by pynixwang** [comment]
no offical uninstaller?

**Comment by pynixwang** [comment]
I find a new way, install again and installer will tell you how to remove it, all included but deleting user.

**Comment by SimSez** [comment]
Hi there, 

I've completed the third step (sudo -fr/nix)

How does one go about these first two steps on OSX, is this from within the terminal? I can't seem to find the .profile or .bash_profile 

>To uninstall nix you will need to do the following things:

remove the . "$HOME/.nix-profile/etc/profile.d/nix.sh" line in your ~/.profile or ~/.bash_profile

rm -rf $HOME/{.nix-channels,.nix-defexpr,.nix-profile,.config/nixpkgs}

sudo rm -rf /nix

**Comment by JamesMcMahon** [comment]
> I find a new way, install again and installer will tell you how to remove it, all included but deleting user.

@pynixwang This didn't work for me under macOS. What command did you run to see the uninstall options?

**Comment by jbyler** [comment]
I followed @zimbatm's instructions, with some tweaks:
- my personal dotfiles didn't have anything to load nix, but I did have to clean up `/etc/{profile,bashrc,zshrc}`
- I didn't bother to remove the `nixbld[0-9]` users (oops?)

But I found one important piece was missing, and which the nix installer did not detect upon reinstallation: there was a lingering `/Library/LaunchDaemons/org.nixos.nix-daemon.plist` pointing to the old version of nix.  After reinstalling, I had to do something like this to get launchctl to pick up the changes in the new version:

```sh
sudo launchctl unload -w /Library/LaunchDaemons/org.nixos.nix-daemon.plist
sudo launchctl load -w /Library/LaunchDaemons/org.nixos.nix-daemon.plist
```

Perhaps better would have been to remove and unload the launchdaemon as part of uninstalling.

**Comment by HaoZeke** [comment]
As I'm sure people know, none of these instructions clean up the large set of users created..

**Comment by allter** [comment]
Yeah, the instructions of upgrading Nix tell just to repeat curl |sh. Then instructions in install script find earlier NIX installation remnants and ask you to delete /nix, profiles etc with only rm -rf

But those instructions don't mention:
1. removing nix remnants in /usr/local (bin and conf)
2. removing users with:
for i in $(seq 1 10); do sudo userdel -f nixbld$i; done
sudo groupdel nixbld

**Comment by mbaltaks** [comment]
Or for macOS:

```
for num in {1..32}; do sudo dscl . -delete /Users/nixbld$num; done
sudo dscl . -delete /Groups/nixbld
```

**Comment by AurevoirXavier** [comment]
@mbaltaks 
Also:
`for num in {1..32}; do sudo dscl . -delete /Groups/staff GroupMembership nixbld$num; done`

**Comment by expelledboy** [comment]
I had a crack at writing a complete uninstall script for [OSx](https://gist.github.com/expelledboy/c00aebb004b178cf78b2c9b344526ff6). Hope someone finds this useful.

**Comment by PaulRBerg** [comment]
Hey @expelledboy, your script contains the following code:

```sh
if [ -L $HOME/Applications ]; then
  rm $HOME/Applications
fi
```

I might be wrong, but that doesn't look safe to me.

**Comment by PaulRBerg** [comment]
@zimbatm's solution always worked for me, except for the `sudo rm -rf /nix` step. Getting this error:

> rm: /nix: Resource busy

This is with nix@2.3.6.

**Comment by expelledboy** [comment]
> Hey @expelledboy, your script contains the following code:
> 
> ```shell
> if [ -L $HOME/Applications ]; then
>   rm $HOME/Applications
> fi
> ```
> 
> I might be wrong, but that doesn't look safe to me.

Why? I am removing a link. Perhaps I could have checked if the link was generated by nix.

**Comment by PaulRBerg** [comment]
It just looks scary to run a script written by someone on the Internet that has a line that contains both "rm" and "$HOME/Applications".

I'm sure that the seasoned programmer would immediately figure out if that's a malicious line or not, but many others (including me) won't.

Maybe worth it to add a comment above that code block :)

**Comment by sambacha** [comment]
Just to update this for people using Mac OS X

You still have to `erase` then `remove` your `nix` partition  under `Disk Utilities`

Running `$ sudo rm -rf ~/nix` may yield a `Resource is Busy` message 

`$ ls -alh /nix` 
will show that there are some mac os x specific files like:
```
.DocumentRevisions-V100
.fseventsd
.Spotlight-V100
.TemporaryItems
.Trashes
.VolumeIcon.icns
```


![](https://ucdbdf1dc2431432d571f90007f3.previews.dropboxusercontent.com/p/thumb/AA_z0KIWwSouO2tHy73pm25Nz5s5gZ10BYMKu9i8rUwiSWBYh3uAm1KToMpisRT0gWg1VVdO4eGot5Zo2TcMNyNQ5hJxzRI0TT1YgxYeEMkmoi8zJDtwocPwLbIOsHd3c2oW4qJCi_6P_xhl1HeHxhBZtVLAOaVtVRm74HN7hBw8JpOsOx-SjhTrexuGZL8INs1xlqleb5K2fPw5pBudzpeUFSQOr8_EBHUhcrdKMOl9HIVeuZap6R8FLQkyLdY1Nfnsd364rQ6NYUmQCU2Pexz5n2r7B-JSigSv3ex4seal3igWSSbZURdqhCtjsFTNWF8XO59lksUzxaHOvS6sUL1kR62uq4yrQ7StnthCYG-OdNGOQlnr8l1wK7me-sSqsQ0ffsejYthMq0N1_9QXe3NEuaFKpN67YI5kIeMZuIAiZA/p.png?fv_content=true&size_mode=5)

Bring up `Disk Utilities` then go and remove 
![](https://ucada4a553e21ef713977f100832.previews.dropboxusercontent.com/p/thumb/AA_rwbYI5xKDdIz9r96B06nnsWrjQ0MDZbBF-ZwMh6uzPlSWMsAqFCWCsrznl2HrFytkLs6NloS0razKGATaz88wUQsJOvNW8aMor1I9ltg6mJMiCQrOg1JgL9S3NLo7YP1M8mrpcByea4NA5_RphjDugIuyZnqOOFKf_n82UHZFfwe3Ul4S3g7CI4Hqa7ikhVZKaERy8j-uPPVJD-Pw1ompMjnVJNzv4gFJ2w2aZEHcVWul4pOLI4dDsHA51iKdBqiFUzh9MMgBMrLGjziLa1tJbmSgd_L1St4j_Nq9vUCOcsWQNoV_GGVAMAHy72iglbLAxJ0K6Gu_RIYOljZ6S3rCDwUWUXzuV8S2FC8owDO98lyANqyGOIQmhlgrR24gdaPNjEo5PfzQ0K6J7fZGEZyAliyWi0LlUyY7jM5oGxUYiA/p.png?fv_content=true&size_mode=5)

After deleting you can `rm -rf ~/nix`
running ` $ lsof +D /nix ` will show nothing, meaning it has been removed

**Comment by lilyball** [comment]
@sambacha Your instructions reference `~/nix`, which isn't a path used by Nix. Assuming you meant `/nix` where you wrote `~/nix`, there should never be any need to run `rm -rf /nix` on macOS since it's now a volume.

The uninstall instructions for macOS are printed during the install. [Currently](https://github.com/NixOS/nix/blob/387f824cab50682e373ade49dcec4e6f99c10a42/scripts/create-darwin-volume.sh#L94-L96) they are

```bash
        echo "  1. Remove the entry from fstab using 'sudo vifs'"
        echo "  2. Destroy the data volume using 'diskutil apfs deleteVolume'"
        echo "  3. Remove the 'nix' line from /etc/synthetic.conf or the file"
```

though this will change slightly with #4181.

**Comment by sambacha** [comment]
My instructions reference ~/nix because of the contents listed in that directory that may persist depending on how nix is removed.

It could be any directory where the end user decided to install ~nix, I included it as a reference not as a definitive how to guide, just so that it may spare someone more time from searching for additional help perhaps.

Excited to see some updates for Nix , thanks for letting me know as well, cheers

**Comment by joehenry087** [comment]
On Big Sur, M1 mac, I have tried removing the `/nix` directory and got an error. Thanks to your help @sambacha I was able to delete the volume. Now the `rm` command succeeds, however there is still a `/nix` directory in Finder and doing `ls /` shows it too. 

Does anyone know how to remove this or proper nix uninstall directions for Catalina and after?

**Comment by lilyball** [comment]
> On Big Sur, M1 mac, I have tried removing the `/nix` directory and got an error. Thanks to your help @sambacha I was able to delete the volume. Now the `rm` command succeeds, however there is still a `/nix` directory in Finder and doing `ls /` shows it too. 
> 
> 
> 
> Does anyone know how to remove this or proper nix uninstall directions for Catalina and after?

You probably have to edit `/etc/synthetic.conf` to remove the line `nix`, and then reboot. The empty directory exists because it's a mount point defined by this file.

**Comment by joehenry087** [comment]
Ah, thank you @lilyball. Same time you posted I just found this very helpful guide for post Mojave uinstalls: https://gist.github.com/chriselsner/3ebe962a4c4bd1f14d39897fc5619732

**Comment by peter-mlabs** [comment]
Would like to add that environment variables, on my system, were also set in `/usr/lib/environment.d/nix-daemon.conf`, including `NIX_REMOTE` which can cause issues if you're trying to move to a single-user install.

**Comment by dhananjaylatkar** [comment]
To remove `nixbldX` users from Linux -
```shell
grep nixbld /etc/passwd | awk -F ":" '{print $1}' > /tmp/nixusers
cat /tmp/nixusers | xargs -t -n 1 sudo userdel -r
```

**Comment by commscheck** [comment]
If you're coming here from Google, official documentation for uninstalling nix is available here: https://nixos.org/manual/nix/stable/installation/installing-binary.html#uninstalling

**Comment by kha84** [comment]
The "official" uninstalling instructions are inaccurate. Like right now, they're suggesting to delete these ones:
```
sudo rm -rf /etc/profile/nix.sh /etc/nix /nix ~root/.nix-profile ~root/.nix-defexpr ~root/.nix-channels ~/.nix-profile ~/.nix-defexpr ~/.nix-channels
```
... whereas on my system I found also /etc/profile.d/nix.sh

**Comment by D7x8** [comment]
I tried to delete /nix from my macbook but its telling me its read only and wont let me

**Comment by Chiitoo** [comment]
> I tried to delete /nix from my macbook but its telling me its read only and wont let me

If you have not yet, see:

https://nixos.org/manual/nix/unstable/installation/uninstall.html

**Comment by D7x8** [comment]
> > I tried to delete /nix from my macbook but its telling me its read only and wont let me
> 
> If you have not yet, see:
> 
> https://nixos.org/manual/nix/unstable/installation/uninstall.html

That worked for me, thanks for helping :)
