### ISSUE TITLE
Nix Install is broken due to removing SELinux file attributes on CentOS

### ISSUE THREAD

**Issue by jammerful** [NixOS/nix#1406]
**Summary**:

Installing Nix via the standard install script: `curl https://nixos.org/nix/install | sh` on CentOS 7 is no longer is successful.

**Steps to Reproduce**:

On a CentOS 7 machine, run `curl https://nixos.org/nix/install | sh`
The exact CentOS version is `CentOS Linux release 7.2.1511 (Core) `

**Output**:
```
curl https://nixos.org/nix/install | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2358  100  2358    0     0   5095      0 --:--:-- --:--:-- --:--:--  5103
downloading Nix 1.11.10 binary tarball for x86_64-linux from 'https://nixos.org/releases/nix/nix-1.11.10/nix-1.11.10-x86_64-linux.tar.bz2' to '/tmp/nix-binary-tarball-unpack.yHy6iHuqu0'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 27.7M  100 27.7M    0     0  11.1M      0  0:00:02  0:00:02 --:--:-- 11.1M
performing a single-user installation of Nix...
copying Nix to /nix/store.................................
initialising Nix database...
installing ‘nix-1.11.10’
error: removing extended attribute ‘security.selinux’ from ‘/nix/store/3rh146gsqybkc7br5lnlk53p1ll4lna7-env-manifest.nix’: Permission denied
/tmp/nix-binary-tarball-unpack.yHy6iHuqu0/unpack/nix-1.11.10-x86_64-linux/install: unable to install Nix into your default profile
```

**Possible cause**: https://github.com/NixOS/nix/commit/d798349ede3d6eb6e92a2e4f95f6b2179407ceb9

**Comment by jammerful** [comment]
@shlevy Is there anyone that can look into the issue? Seems to be a big issue, looks like Nix can't be installed on systems with SELinux installed.

**Comment by jammerful** [comment]
@edolstra Sorry to bother you, but not sure who else to look at this. Let me know if you need any more details.

**Comment by edolstra** [comment]
I don't know anything about SELinux. Where does the security.selinux attribute come from? Is it created by default for all files? In any case, I guess we can ignore it during canonicalization...

**Comment by iainnicol** [comment]
I'm no expert but I agree well have to ignore it.

It seems you can't even remove the attribute if you're root.  It seems the value of the attribute is automagically derived from the SELinux context.

**Comment by jammerful** [comment]
I think we still need to update the hashes here: https://github.com/NixOS/nixos-homepage/blob/master/nix-release.tt ?

**Comment by vadzimt** [comment]
I can confirm I have this issue on Fedora 25 which also has SELinux enabled.

**Comment by copumpkin** [comment]
This appears to be resolved as of https://github.com/NixOS/nixpkgs/commit/5446934b41cf180aa50c2fb69e12593720522036 in nixpkgs
