### ISSUE TITLE
Change sysconfdir for binary tarball to /nix/etc from /etc

### ISSUE THREAD

**Issue by catern** [NixOS/nix#1410]
Installing from the binary tarball rather than the Debian or RPM package should allow the install to be totally separated from the underlying system. The nix install should need write permissions only to /nix. Yet we look for nix.conf in /etc/nix/nix.conf. This complicates any install where the user is only able to write to /nix, including installs under nix-user-chroot or where /nix is installed and managed by a non-privileged user.

If we moved the sysconfdir to be under /nix, the nix install would be self-contained in that directory, simplifying use of the binary tarball.

(I myself rebuilt the binary tarball so I could use it for installing, while having nix.conf under /nix)

**Comment by domenkozar** [comment]
Well, that would break backwards compatibility.

**Comment by edolstra** [comment]
Closing since this has been fixed a long time ago.
