### ISSUE TITLE
Using fast symlinks instead of slow symlink on /nix/store

### ISSUE THREAD

**Issue by Lakshmipathi** [NixOS/nix#1415]
I'm pretty new to NixOS. Just last week installed it. It looks great. I have small suggestion or possible enhancement request.  (I don't know whether its already discussed in NixOS mailing-list anyway here it is):  As NixOS uses lot of symlinks, under /nix/store I have around 2500 symlinks. Out of these 2500 , almost 25% (635) links are slow sym-links which means extra read() call is invoked. (http://www.giis.co.in/symlink.html).

Since ext[234] is most widely used Linux file system at the moment,  If we convert these 25% of symlink to fast symlink it'll provide performance benefits. (I don't have performance numbers but we should see improvements).  thanks.

**Comment by vcunat** [comment]
I don't understand what you suggest to do?  The linked article seems to suggest it only depends on the length of the target path (whether it's < 64).

**Comment by Lakshmipathi** [comment]
Example existing link:
/nix/store/7c3isklgiai88hd5yjcq0vwh1s0n99gb-libpipeline-1.4.1/share/man/man3/pipecmd_chdir.3.gz -> /nix/store/7c3isklgiai88hd5yjcq0vwh1s0n99gb-libpipeline-1.4.1/share/man/man3/libpipeline.3.gz 

I was thinking, If we can reduce the target length from current 94 to less than 64 bytes to something like: 
/nix/store/7c3isklgiai88hd5yjcq0vwh1s0n99gb-libpipeline-1.4.1/share/man/man3/pipecmd_chdir.3.gz -> </nix/store/small-unique-hash>/libpipeline.3.gz  
should help performance. 

</nix/store/small-unique-hash> may be stored in in-memory sqlite db or similar. I don't know complexity of such implementation and obviously something like this needs to done if and only if it provide noticeable performance difference.  Just some random thoughts from Nix newbie :)

**Comment by vcunat** [comment]
That's probably not worth it.  Still, we could prefer using relative links, at least when it's within the same `/nix/store/<hash-pname-version>/`, e.g. via `-r` passed to `ln`.

**Comment by Lakshmipathi** [comment]
Okay. Yes, relative links approach looks much better approach whenever it is possible.

**Comment by edolstra** [comment]
Yeah, I thought about doing this, mostly because of the considerable disk space savings. (Every symlink that doesn't fit in an inode will take up a full block, e.g. 4 KiB. So for example every NixOS sw tree on my system takes up another ~150 MiB.) The speed benefit would also be nice, of course.

**Comment by vcunat** [comment]
For some bad cases like `~/.nix-profile/bin/` I can't see any good approach.

**Comment by vcunat** [comment]
The `/nix/store/<hash>-` part takes 44 characters.  **If** we made nix omit the `-<pname-version>` part, I think many more links would fit under 64, but it would come with decreased readability of some logs, etc.

**Comment by Lakshmipathi** [comment]
@edolstra  Yes,saving disk-space is another advantage especially when there is huge no.of slow symlinks.

**Comment by drudru** [comment]
Just quickly chiming in... This can be achieved without having to change NixOS. It is possible to build your file system with more storage allocated to Inodes. At that point, the problem is solved.

 I don’t know if this can be done on a mounted file system, but I know it can be done off-line.

**Comment by vcunat** [comment]
In any case, I can't see motivation to keep this ticket open, at least not in "nix" repo.  In "nixpkgs" we might consider using more relative symlinks or perhaps even something about inode defaults; feel free to open there (anyone) with more concrete ideas.

**Comment by andir** [comment]
Just for reference in Nixpkgs we are already making symlinks within the same output relative: https://github.com/NixOS/nixpkgs/pull/74253
