### ISSUE TITLE
multiple binary caches from independent rebuilds interact badly via binary-caches-v2.sqlite

### ISSUE THREAD

**Issue by mornfall** [NixOS/nix#142]
If I use two independently-rebuilt binary caches, it can happen that the same output path is in both, with different content sha sums. This throws off the binary cache substituter, which in some circumstances can get the sum from one cache, but the file from other, eventually dying with a hash mismatch on the unpacked output path.

The same presumably happens if you switch from one cache to another without nuking the cache file.

**Comment by edolstra** [comment]
I believe this cannot happen anymore with the new substituter architecture.
