### ISSUE TITLE
Origin of `nix` as project name

### ISSUE THREAD

**Issue by makefu** [NixOS/nix#1421]
I was wondering about the origins of the project name `nix`. Since the beginning the name (in german) is the source of constant positive amusement for people hearing of the project the first time.

Today @bennofs wrote in the [typing nix hackernews article](https://news.ycombinator.com/item?id=14618128):
> I believe that [nix meaning 'nichts' in german] is even intentional, the original author of nix (Eelco Dolstra) is from the Netherlands. The name comes from the fact that by default, nothing is available in build environments in nix.

If this could be confirmed it would be great to have the origin in the website or in the manual of nix.

Cheers

Edit: @dtzWill pointed towards [the paper "Nix: A Safe and Policy-Free System for Software Deployment"](https://pdfs.semanticscholar.org/5fd8/8f89bd8738816e62808a1b7fb12d3ab14a2f.pdf) which confirms the origin.

**Comment by bittner** [comment]
The paper cited above is [available from Eelco Dolstra's website](https://edolstra.github.io/pubs/nspfssd-lisa2004-final.pdf). You can find the explanation at page 81 in footnote 1:

<img width="408" height="65" alt="Image" src="https://github.com/user-attachments/assets/5d13244b-3f0a-49fa-810c-86bfbf6d2c9f" />
