### ISSUE TITLE
Request to backport sha256 for builtins.fetch{url,Tarball} to 1.11

### ISSUE THREAD

**Issue by aneeshusa** [NixOS/nix#1425]
The feature of allowing a `sha256` attribute for these built-ins introduced in 06bbfb6004942bfcddd930e746ee7a2bfe5c3872 would be very helpful to have in `nixStable`.
My use case involves making many builds using the same `fetchTarball` call (of a custom nixpkgs tree), so adding the ability to cache that download would speed up my builds a lot.
I tried to backport this myself, but it seems the downloader-related code has changed quite a bit in the ~year since that commit. I would greatly appreciate it if this could be backported.

**Comment by domenkozar** [comment]
Duplicates https://github.com/NixOS/nix/issues/1299
