### ISSUE TITLE
Can't execute setuid binaries in Nix 1.11.10+

### ISSUE THREAD

**Issue by rimmington** [NixOS/nix#1429]
From what I understand, seccomp rules prevent the creation of setuid binaries in Nix 1.10+. However I didn't read anything about preventing _execution_ of setuid binaries in Nix. We're using `sudo` to set up containers in Hydra for integration testing, and an upgrade caused our tests to start failing (we ended up downgrading). I can replicate the issue in a VM fairly easily.

With a VM provisioned (via [vagrant-nixos-plugin](https://github.com/zimbatm/vagrant-nixos-plugin)) with [Nixpkgs `49e8512100ce12b5990a1bf5371d4d1c558962ab`](https://github.com/NixOS/nixpkgs/commit/49e8512100ce12b5990a1bf5371d4d1c558962ab):

```
[vagrant@nixos:~]$ nix-build --version
nix-build (Nix) 1.11.9

[vagrant@nixos:~]$ nix-build -E 'with import <nixpkgs> {}; runCommand "test" {} "/run/wrappers/bin/sudo echo hello"'
these derivations will be built:
  /nix/store/achlrszr10jifl3iz814s0d8ybxh94nv-test.drv
building path(s) ‘/nix/store/4jdxy3dkvpahax56wysnfss80rcsnb0g-test’
sudo: no tty present and no askpass program specified
builder for ‘/nix/store/achlrszr10jifl3iz814s0d8ybxh94nv-test.drv’ failed with exit code 1
error: build of ‘/nix/store/achlrszr10jifl3iz814s0d8ybxh94nv-test.drv’ failed

[nix-shell:~]$ nix-build -E 'with import <nixpkgs> {}; runCommand "test" {} "/run/wrappers/bin/ping -c 1 google.com"'
these derivations will be built:
  /nix/store/qx6caxlgz6c4wmgfapxwmx7r0x7n2snz-test.drv
building path(s) ‘/nix/store/vnygr4hjxfjy8hx3lvr17jqgmgli3k92-test’
PING google.com (216.58.196.142) 56(84) bytes of data.

--- google.com ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

builder for ‘/nix/store/qx6caxlgz6c4wmgfapxwmx7r0x7n2snz-test.drv’ failed with exit code 1
error: build of ‘/nix/store/qx6caxlgz6c4wmgfapxwmx7r0x7n2snz-test.drv’ failed
```

With [Nixpkgs `7a76e259c88ad5ea6807ed70af51d9196195c690`](https://github.com/NixOS/nixpkgs/commit/7a76e259c88ad5ea6807ed70af51d9196195c690):

```
[nix-shell:~]$ nix-build --version
nix-build (Nix) 1.11.10

[vagrant@nixos:~]$ nix-build -E 'with import <nixpkgs> {}; runCommand "test" {} "/run/wrappers/bin/sudo echo hello"'
these derivations will be built:
  /nix/store/achlrszr10jifl3iz814s0d8ybxh94nv-test.drv
building path(s) ‘/nix/store/4jdxy3dkvpahax56wysnfss80rcsnb0g-test’
sudo: /nix/store/3xsjm8rfpy0ysfjs1pcybj33fsigszgp-wrapper.c:203: main: Assertion `!(st.st_mode & S_ISUID) || (st.st_uid == geteuid())' failed.
/tmp/nix-build-test.drv-0/.attr-0: line 1:  9463 Aborted                 /run/wrappers/bin/sudo echo hello
builder for ‘/nix/store/achlrszr10jifl3iz814s0d8ybxh94nv-test.drv’ failed with exit code 134
error: build of ‘/nix/store/achlrszr10jifl3iz814s0d8ybxh94nv-test.drv’ failed

[vagrant@nixos:~]$ nix-build -E 'with import <nixpkgs> {}; runCommand "test" {} "/run/wrappers/bin/ping -c 1 google.com"'
these derivations will be built:
  /nix/store/qx6caxlgz6c4wmgfapxwmx7r0x7n2snz-test.drv
building path(s) ‘/nix/store/vnygr4hjxfjy8hx3lvr17jqgmgli3k92-test’
cannot raise the capability into the Ambient set
: Operation not permitted
builder for ‘/nix/store/qx6caxlgz6c4wmgfapxwmx7r0x7n2snz-test.drv’ failed with exit code 1
error: build of ‘/nix/store/qx6caxlgz6c4wmgfapxwmx7r0x7n2snz-test.drv’ failed
```

**Comment by vcunat** [comment]
The reason why setuid creation was banned was exactly to avoid the possibility of executing them, as that allow to "partially break out" of the sandbox.

**Comment by edolstra** [comment]
It appears that libseccomp calls `prctl(PR_SET_NO_NEW_PRIVS)` by default, preventing setuid/setgid binaries from working. This could be disabled via the `SCMP_FLTATR_CTL_NNP` seccomp filter attribute, but I'm not sure if that's desirable...

**Comment by lukego** [comment]
> This could be disabled via the SCMP_FLTATR_CTL_NNP seccomp filter attribute

How would that be done? (Patch to nix / add a new configuration option?)

> but I'm not sure if that's desirable...

I reckon that this is desirable for some users/uses and not for others. Sandboxes provide both isolation and security and some people want both while others only want one.

Our [Snabb](https://github.com/snabbco/snabb/) project depends on a [Hydra instance](http://hydra.snabb.co/) for all of our performance testing. This requires root access for a plethora of reasons. For example, our application includes userspace device drivers for network cards and does things like resolve virtual addresses to physical addresses, etc. This means making lots of privileged system calls.

So in our context the software isolation of the sandbox is very valuable - keeping our tests controlled and reproducible - but the security side not so much - potentially preventing our tests from running at all.

**Comment by edolstra** [comment]
@lukego Yeah, an option would be fine. I'll see if I can add that today.

**Comment by lukego** [comment]
Thanks!

**Comment by lukego** [comment]
Sorry if this should be obvious, but where does the `/run/wrappers/bin/ping` setuid binary come from in the example from 6cf23c3? (I'd like to call `sudo` from my nix expression: how should I make `sudo` available?)

I'm basically restating the question from #1436 now that we have resolved that it _is_ possible to run commands as root... Just have to get those commands somehow :)

**Comment by edolstra** [comment]
Oh, I thought you were already doing sudo calls (since you mentioned that you were running things as root - or did you mean that the builders run as root directly?).

`/run/wrappers/bin/ping` is the regular location of the ping binary on NixOS, so my example assumed that either you're not running in a sandbox (`--option build-use-sandbox false`), or you have that file bind-mounted in the sandbox (`--option build-extra-sandbox-paths /run/wrappers/bin/ping`).

**Comment by lukego** [comment]
@edolstra Just now I am running the tests on NixOS but I want to make them run on other distros under Nix. So it seems like I need a portable way to locate a sudo executable to pass in to nix.

The hack that comes to mind is `--option build-extra-sandbox-paths $(which sudo | xargs dirname)` but maybe there is a neater way where nix can provide the `sudo` binary too?
