### ISSUE TITLE
Can't execute x32 programs in Nix 1.11.10+ due to seccomp rejecting all x32 syscalls

### ISSUE THREAD

**Issue by hvdijk** [NixOS/nix#1432]
Testcase:

Provide an x32 build of busybox, including associated echo symlink, in an x32 directory, then:

Nix 1.11.9:

<pre>
# nix-build --no-out-link --expr 'with builtins; derivation {                                                                                                  
    system = currentSystem;
    name = "test";
    builder = toString ./x32 + "/echo";
    args = [ "hello" ];
}'
these derivations will be built:
  /nix/store/gaczxa6glznjjra7wijv721brkjb1crb-test.drv
building path(s) ‘/nix/store/mjap7yav0jwxaakj3qk0ppw6bm78abbx-test’
hello
builder for ‘/nix/store/gaczxa6glznjjra7wijv721brkjb1crb-test.drv’ failed to produce output path ‘/nix/store/mjap7yav0jwxaakj3qk0ppw6bm78abbx-test’
error: build of ‘/nix/store/gaczxa6glznjjra7wijv721brkjb1crb-test.drv’ failed
</pre>

Nix 1.11.11:

<pre>
# nix-build --no-out-link --expr 'with builtins; derivation {                                                                                                 
    system = currentSystem;                                                                         
    name = "test";                                                          
    builder = toString ./x32 + "/echo";                      
    args = [ "hello" ];  
}'
these derivations will be built:
  /nix/store/gaczxa6glznjjra7wijv721brkjb1crb-test.drv
building path(s) ‘/nix/store/mjap7yav0jwxaakj3qk0ppw6bm78abbx-test’
builder for ‘/nix/store/gaczxa6glznjjra7wijv721brkjb1crb-test.drv’ failed due to signal 31 (Bad system call)
error: build of ‘/nix/store/gaczxa6glznjjra7wijv721brkjb1crb-test.drv’ failed
</pre>

**Comment by edolstra** [comment]
With x32, you mean the X32 ABI (https://en.wikipedia.org/wiki/X32_ABI)? I don't think Nix has ever supported that.

If you just mean 32-bit binaries, I cannot reproduce this issue.

Also, please provide a link to the busybox binaries.

**Comment by edolstra** [comment]
For X32, the following patch may help:
```
diff --git a/src/libstore/build.cc b/src/libstore/build.cc
index 355fb3b7..60b0a531 100644
--- a/src/libstore/build.cc
+++ b/src/libstore/build.cc
@@ -2317,6 +2317,10 @@ void setupSeccomp()
         seccomp_arch_add(ctx, SCMP_ARCH_X86) != 0)
         throw SysError("unable to add 32-bit seccomp architecture");
 
+    if (settings.thisSystem == "x86_64-linux" &&
+        seccomp_arch_add(ctx, SCMP_ARCH_X32) != 0)
+        throw SysError("unable to add X32 seccomp architecture");
+
     /* Prevent builders from creating setuid/setgid binaries. */
     for (int perm : { S_ISUID, S_ISGID }) {
         if (seccomp_rule_add(ctx, SCMP_ACT_ERRNO(EPERM), SCMP_SYS(chmod), 1,
```

However my kernel doesn't support X32 so I can't test this.

**Comment by hvdijk** [comment]
Yes, that's the x32 I meant. I don't think I should recommend people run untrusted binaries downloaded from the Internet, but since you asked, here's the binary: [busybox.zip](https://github.com/NixOS/nix/files/1122653/busybox.zip). Unzip it to an x32 directory and create symlinks for the applets you'd like to try.

I'm using Nix (without Nixpkgs) on a regular x64 Ubuntu system, but compiling a few packages to x32 that end up running some of their own generated binaries. This doesn't generally need support from Nix since x32 binaries run natively on x64 kernels, provided the appropriate kernel config option is enabled, that's why it worked until the seccomp restrictions.

Your patch works for me, thanks. And in x32 programs, the setuid restrictions are still applied as expected.

**Comment by edolstra** [comment]
Thanks for testing, I've pushed the patch!
