### ISSUE TITLE
killing process 16123: Operation not permitted

### ISSUE THREAD

**Issue by zimbatm** [NixOS/nix#1435]
The latest nixUnstable on Darwin is emitting this error which is non-fatal:

```
$ nix-env -iA nixpkgs.hello
installing ‘hello-2.10’
building path(s) ‘/nix/store/8m27z8kbkp46lc5c10r648v9c4pj8v2x-user-environment’
created 1232 symlinks in user environment
killing process 16123: Operation not permitted
```

It only happens when derivations are being built (like the user environment in this case).

* `uname -a`: `Darwin mr-johnson.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64`
* `nix --version`: `nix (Nix) 1.12pre5413_b4b1f452`

**Comment by edolstra** [comment]
This is fixed by 177f3996e28967368791ba0e4ec036f3dbbb88d0.
