### ISSUE TITLE
Where is the binary cache priority comparison done in the C++ implementation?

### ISSUE THREAD

**Issue by nh2** [NixOS/nix#1438]
In the old Perl implementation [here](https://github.com/NixOS/nix/blob/1.11.11/scripts/download-from-binary-cache.pl.in#L321) there was the logic for comparing the `Priority: ...` fields of binary caches:

```perl
    @caches = sort { $a->{priority} <=> $b->{priority} } @caches;
```

Where is this logic in the new C++ implementation on `master`?

I haven't been able to find it within reasonable time.

In particular, I want to convince myself that the equivalent sort in C++ is stable, like the Perl one is.

Thanks!

**Comment by edolstra** [comment]
I don't think it's currently done. So binary caches are checked in the order in which they are defined in the `substituters` (aka `binary-caches`) option.

**Comment by nh2** [comment]
Ah, so `Priority` is ignored / it's a bug (== noncomplete feature with the old version)?

**Comment by nh2** [comment]
@edolstra Thanks. and the `std::list.sort()` you [added](https://github.com/NixOS/nix/commit/42c5774e78a9f1422dee9c35adb9c056aa994d3b#diff-5b92c50bdc2ae204030a9a043a9e3df3R815) is stable, so that answers my original concern.
