### ISSUE TITLE
Set immutable bit on store on Darwin

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#1456]
I see that Linux stopped doing this, recommending instead the read-only bind mount approach. Given that Darwin doesn't have a read-only bind mount and I still occasionally find that annoying tools that might run with superuser privileges like to mess with my store, it would be nice to add an additional layer of protection against accidental modification.

Is there any downside to this?

cc @edolstra @grahamc

**Comment by grahamc** [comment]
Sounds pretty good to me, but I'm probably not really aware of the consequences.

**Comment by matthewbauer** [comment]
Maybe also set "hidden" so spotlight doesn't try to index it.

**Comment by copumpkin** [comment]
I checked and the immutable flag suffers from the same store optimization issue as it did on Linux, so this might be too much of a pain. The hidden flag might be nice.
