### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by flyingP0tat0** [NixOS/nix#1458]
When building nix, I get the following error. Since I have no idea what it actually means, I am just posting it here, hoping someone can explain it...
```bash
  GEN    doc/manual/manual.is-valid
I/O error : Attempt to load network entity http://docbook.org/xml/5.0/rng/docbook.rng
warning: failed to load external entity "http://docbook.org/xml/5.0/rng/docbook.rng"
Relax-NG parser error : xmlRelaxNGParse: could not load http://docbook.org/xml/5.0/rng/docbook.rng
Relax-NG schema http://docbook.org/xml/5.0/rng/docbook.rng failed to compile
-:1: parser error : Document is empty

^
make: *** [doc/manual/local.mk:29: doc/manual/manual.is-valid] Error 1
```

**Comment by domenkozar** [comment]
What steps did you take to build Nix?

**Comment by flyingP0tat0** [comment]
@domenkozar I installed
- autoconf
- automake
- pkgconfig
- xzutils
- libseccomp
- sqlite
- perl and the modules
- bdwgc
- bison
- flex
- docbook

Then I did:
```shell
./bootstrap.sh
./configure
make
```
...and at `make` it failed.

System is a Chromebook.

**Comment by DanOlivier** [comment]
You would also need to install package `docbook-xsl` and point `xsltproc` at it, using the `--nonet` flag (see https://github.com/NixOS/nix/pull/1430)
