### ISSUE TITLE
Installation on Darwin broken

### ISSUE THREAD

**Issue by lukeadams** [NixOS/nix#1468]
The installscript errors on a fresh macOS Sierra VM [(full output)](https://gist.github.com/lukeadams/967415f50063644d19a2d5dc9b7c820f):
```
---- oh no! --------------------------------------------------------------------
That is okay, but we can't install.

We'd love to help if you need it.

If you can, open an issue at https://github.com/nixos/nix/issues

Or feel free to contact the team,
 - on IRC #nixos on irc.freenode.net
 - on twitter @nixos_org

```
The issue seems to be with the multiuser [y/n] prompts taking piped input from curl, causing it to default to n for all prompts.

Running 
```
curl https://nixos.org/nix/install > install.sh
chmod +x install.sh
./install.sh
```
allows installation to proceed with no issues.

**Comment by domenkozar** [comment]
@lukeadams we have prepared a fix for this, can you test:

```
curl https://static.domenkozar.com/install-nix-1.11.13 | sh
```

This uses the upcoming Nix 1.11.13 /cc @grahamc

**Comment by lukeadams** [comment]
I can test it later today on a clean VM, but re-running it on my Sierra VM with nix already installed has these where I assume it would have asked for y/n:
`No TTY, assuming you would say yes :)`
Since it assumes yes, it "works" (at least when it warns about nix being already installed)

**Comment by dieideeistgut** [comment]
Hello, in installed this on a clean Sierra machine. Installation worked perfectly as far as i can confirm. Strangely some installed binarys are not working compared to my older El Capitan machine. If i build fish shell via nix it will only open in a debug-mode stating that:

`fish
<W> fish: Could not set up terminal.
<W> fish: TERM environment variable set to 'xterm-256color'.
<W> fish: Check that this terminal type is supported on this system.
<W> fish: Using fallback terminal type 'ansi'.
<W> fish: Could not set up terminal using the fallback terminal type 'ansi'.
<W> fish: Using fallback terminal type 'dumb'.
<W> fish: Could not set up terminal using the fallback terminal type 'dumb'.`

Thought this would be my fault, fixed and double-checked terminfo. I assume my issue with htop is about the same:

`htop
Error opening terminal: xterm-256color.` 

Spent some hours on this without any success or more informations. maybe someone here has an idea?

**Comment by shnarazk** [comment]
Hi, @dieideeistgut 
We need to set TERMINFO to run programs using ncurses:

```
export TERMINFO=/usr/share/terminfo
```

It's a bug in nix 1.11.12, I think.

**Comment by dieideeistgut** [comment]
Wow - Didn't know that - Thanks alot! I even tried this before so i must have had a combination of corrupted macos terminfo files and this issue here. Thanks again!

**Comment by grahamc** [comment]
For what it is worth, 1.11.13 is now released.

The TERMINFO is a problem with Nixpkgs, not Nix. The issue has been patched in Nixpkgs already, however the nixpkgs-unstable channel hasn't updated to contain the fix yet.
