### ISSUE TITLE
NixOS newbie forum

### ISSUE THREAD

**Issue by AttilaVM** [NixOS/nix#1478]
I've just begun with NixOS, so I sought a forum to ask a question. I tried \#nixos on IRC, which channel does not exists. However I found this Google Plus [community]:(https://plus.google.com/communities/113182864761473463138) 

My question:
Where should I ask newbie questions:
1. The aforementioned Google Plus community
2. Github (a bit unorthodox, but why not)
3. other forum

Proposal:
Whatever it is, that forum should be indicated at 

http://nixos.org/nixos/support.html

Instead of the seemingly dead \#nixos channel.

**Comment by vcunat** [comment]
That channel exists and has been relatively alive, as you can see from the logs https://botbot.me/freenode/nixos/ , and it seems the best choice to me.  (But I rarely go there.)

On the other hand, the plus community seems relatively dead, though you can try.  GitHub is not suitable for this.  StackOverflow might be suitable, if you don't need much interactivity (i.e. you know what to ask).

**Comment by fpletz** [comment]
I don't really use web forums but might it be an option to set up a [Discourse](https://www.discourse.org/) instance? I haven't really used it but heard mostly positive things about it. Many people have problems with IRC or mailings lists.

**Comment by vcunat** [comment]
I have and must say Discourse is very nice to use.  I particularly appreciate how it allows one to show new threads and lets you decide whether you want to follow them or not.  I haven't found such workflow as easy with e-mails or github, for example.

**Comment by P-E-Meunier** [comment]
I'm very happy with Discourse, which I setup for a smaller community (discourse.pijul.org). I let them host it, although we should probably package it for NixOS.

I strongly believe it would be an excellent place to discuss issues such as improving documentation, and/or  organising the community around common priorities.

Sure, GitHub issues can serve that purpose, but they are not properly hierarchised, i.e. someone who starts an issue cannot classify it, and it's less trivial to browse issues by tag.

**Comment by fricklerhandwerk** [comment]
This is solved:
- nixos.org indicates where to ask questions: https://nixos.org/community/
- [NixOS Discourse](https://discourse.nixos.org/) is very active
- today we renamed what was previously the "Learn" category to [Help](https://discourse.nixos.org/c/learn/9) to be easier to find
