### ISSUE TITLE
[Q] how to handle package downgrades?

### ISSUE THREAD

**Issue by Mic92** [NixOS/nix#1481]
I recently merged https://github.com/NixOS/nixpkgs/pull/27563, which downgrades spotify from a testing release to a stable one (to fix a crash). Users using attributes to install upgrades will receive this update, however users using `nix-env -u` will probably not. How to handle these cases?

**Comment by bjornfor** [comment]
By deprecating "nix-env -u"?

I don't see how name+version based upgrades align with Nix model of deterministic deployments.

Just now I added "lowPrio" to nixopsUnstable. That was my response after running "nix-env -u \\* --always" and seeing how my (stable) nixops-1.5.1 was upgraded to (unstable) nixops-2017-05-22. Now, that fixed accidentally upgrading, but I think my change will also accidentally _downgrade_ nixops for people _wanting_ the unstable version. Basically, I don't think that model works.

**Comment by vyp** [comment]
So basically newer versions are not higher version numbers, but the most recent nix expressions in nixpkgs?

**Comment by Mic92** [comment]
`nix-env` is no longer recommend. This can be closed.
