### ISSUE TITLE
Nix builds fail in nixpkgs master on Darwin Hydra

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#1487]
See http://hydra.nixos.org/build/56935789/nixlog/1

One test fails, and it fails trying to create `/tmp/result`, which sounds like a bug in picking a deterministic temporary directory when we don't have mount namespaces on Darwin:

```
+ nix-build -o /tmp/result -E 'import (fetchTarball file:///private/tmp/nix-build-nix-1.11.13.drv-0/nix-1.11.13/tests/test-tmp/tarball.tar.xz)'
error: cannot create symlink ‘/tmp/result’; already exists
FAIL: tests/tarball.sh
```

cc @edolstra @domenkozar

**Comment by matthewbauer** [comment]
It should be fixed in 04532ee2c876980b9ceb160ec9ca958867aae372, I think. If we can get #1526, fixed maybe there should be a 1.11.14 release? It's currently blocking nixpkgs-unstable channel: https://hydra.nixos.org/job/nixpkgs/trunk/unstable#tabs-constituents
