### ISSUE TITLE
removal of compressHash

### ISSUE THREAD

**Issue by evrim** [NixOS/nix#1498]
Hello,

Are there any plans to remove compressHash(..., 20)? The longest filename in my store is 112 chars of 255. I am concerned by the security of this so called compression of sha256. It is not meant to be 160 bits.
At least there should be an option to disable it for NixOS. I know that it will sacrifice the binary-caches all together yet at some point I think it should be done.

evrim.

**Comment by edolstra** [comment]
There are no plans for that.

**Comment by copumpkin** [comment]
@evrim what are your specific concerns here? a 2^-80 collision probability is still pretty slim. Truncations of a secure hash are still secure, and I'm struggling to think of how this might affect anything negatively.

**Comment by evrim** [comment]
@copumpkin  I see no theoretical proof of 2^80 in terms of collision resistance. Second preimage is totally a different story.
