### ISSUE TITLE
nix-build in subdirectories

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nix#1507]
It's always bugged my that nix-build only works in the root directory of nixpkgs. Here's the use case I'm thinking of:

```sh
$ cd ~/Projects/nixpkgs/pkgs/applications/editor/emacs/
$ nix-build
/nix/store/g9zpjz4vadqgf29c7ghd897j4jfk4v2h-emacs-25.2
```

To make this work, Nix needs to be able to auto-call with a parent directory expression. Would this be possible to do in a generic way? Here's how I think ```nix-build``` could do this:

1. tries to build default.nix
2. fails because of missing arguments
3. traverse directory tree looking for parent directory with a child folder named "top-level"
4. auto-call default.nix with any args available from top-level/default.nix

Would this be doable within Nix?

**Comment by expipiplus1** [comment]
It's certainly something one could script up external to nix at the very
least.

**Comment by matthewbauer** [comment]
Here's a simple script:

```
#!/bin/sh

# nix-auto.sh

# Wrapper around nix-build to allow building within subdirectories.

nix="."

if [ $# -gt 0 ]
then
    nix="$1"
    shift
fi

get_root () {
    cd ..
    while ! [ -f ./default.nix ]
    do
        cd ..
    done

    if ! [ -f ./default.nix ]
    then
        return 1
    fi

    echo "$(pwd)"
    return 0
}

root="$(get_root)"

if [ $? -eq 0 ]
then
    nix-build -E "with import $root {}; callPackage ./$nix {}" $@
else
    nix-build $@
fi
```

It would be nice to have this builtin to Nix though.
