### ISSUE TITLE
Library not loaded: /usr/lib/system/libsystem_coretls.dylib

### ISSUE THREAD

**Issue by huang47** [NixOS/nix#1510]
saw below after running `curl https://nixos.org/nix/install | sh`

```
~~> Setting up the build user nixbld4
            Exists:	Yes
          IsHidden:	Yes
   Logins Disabled:	Yes
  Member of nixbld:	Yes
    PrimaryGroupID:	30000
      Alright! We have our first nix at /nix/store/z21lvakv1l7lhasmv5fvaz8mlzxia8k9-nix-1.11.13
dyld: Library not loaded: /usr/lib/system/libsystem_coretls.dylib
  Referenced from: /nix/store/v7i520r9c2p8z6vk26n53hfrxgqn8cl9-Libsystem-osx-10.11.6/lib/libSystem.B.dylib
  Reason: image not found
/var/folders/mc/q_fd83q50mg5815l7zvjvxt80000gn/T/nix-binary-tarball-unpack.XXXXXXXXXX.qhWwOx4M/unpack/nix-1.11.13-x86_64-darwin/install-darwin-multi-user: line 229: 14391 Abort trap: 6           sudo "$@"
```

**Comment by copumpkin** [comment]
You're on 10.13 beta? The official installer doesn't support that yet. I made a custom one that does but it's not official, and I can't find the thread now 😦

**Comment by huang47** [comment]
@copumpkin OH! didn't realize its' 10.13 beta

I also tried to install each tools yesterday but ran into the same problem while installing ethabi. will search for your unofficial one to see if it work for me

**Comment by gbaz** [comment]
Is this resolved by https://github.com/NixOS/nix/issues/1414 ?

**Comment by copumpkin** [comment]
Yeah, all recent builds of Nix should work fine, thanks for pointing it out. Post here if you still have issues and I'll reopen.
