### ISSUE TITLE
Tests fail without CONFIG_USER_NS=y

### ISSUE THREAD

**Issue by dezgeg** [NixOS/nix#1521]
The testsuite fails on Arch Linux, presumablu due to lack of user namespaces:
````
error: cloning builder process: Invalid argument
error: unable to start build process
+ outPath=
FAIL: tests/linux-sandbox.sh
````
and
````
error: cloning builder process: Invalid argument
error: build of ‘/tmp/nix-build-nix-1.12pre5511_c94f3d55.drv-0/nix-test/store/qq9v4bnc71y93qpwy18vcm1k2kqylc1w-build-hook-input-1.drv’ on ‘local?root=/tmp/nix-build-nix-1.12pre5511_c94f3d55.drv-0/nix-test/store1’ failed: unable to start build process
cannot build derivation ‘/tmp/nix-build-nix-1.12pre5511_c94f3d55.drv-0/nix-test/store/8mdh71d0mw0y4awqmzmxkf595di4kfza-build-hook.drv’: 1 dependencies couldn't be built
error: build of ‘/tmp/nix-build-nix-1.12pre5511_c94f3d55.drv-0/nix-test/store/8mdh71d0mw0y4awqmzmxkf595di4kfza-build-hook.drv’ failed
+ outPath=
FAIL: tests/build-remote.sh
````

~~Presumably those tests could try calling some trivial `unshare` command and skip those tests if they don't work~~ (except `unshare` comes from `util-linux`, not `coreutils`, sigh...).

**Comment by jcumming** [comment]
... also on SLES11-SP4.

**Comment by edolstra** [comment]
Does `/proc/self/ns/user` exist if CONFIG_USER_NS is disabled? If not, its existence can be used to decide whether to run the test.

**Comment by dezgeg** [comment]
It doesn't but unfortunately that most likely doesn't fix the Debian problem: https://github.com/NixOS/nix/issues/1625#issuecomment-339827495

**Comment by dezgeg** [comment]
But I guess you could check the existence and/or value of `/proc/sys/kernel/unprivileged_userns_clone`...
