### ISSUE TITLE
1.11.x release with fix for macOS .sb removal issue?

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#1526]
It would be nice to get https://github.com/NixOS/nix/commit/c740c3ce500af2b7eb34651b5eeec01288d79dca into a release. I'm not sure why it's started biting us more recently, but I've seen it several times both on my machine and others. Perhaps it's exacerbated by the new multi-user installer? And probably also because we now have an unconditional .sb file.

cc @edolstra @grahamc @LnL7

**Comment by copumpkin** [comment]
Alternately, is there a good workaround I can use and can recommend to others? Simply deleting the .sb file doesn't stop it from happening for other derivations.

**Comment by matthewbauer** [comment]
I think it's only affecting nix-daemon installs. In single-user installs, you would always have ownership of the Nix store. (Not that we should encourage anyone to move back to single-user)

**Comment by copumpkin** [comment]
Yeah, but you have to jump through hoops to get a single-user install nowadays, so if all macOS users get these issues by default, it's pretty awkward 😄

**Comment by FRidh** [comment]
We need c740c3c in a release because its blocking the `nixpkgs` channel.

**Comment by domenkozar** [comment]
🙏

**Comment by matthewbauer** [comment]
Ok @edolstra just merged that commit into 1.11-maintenance.

Can somebody do a 1.11.14 release?
