### ISSUE TITLE
[Question] How to get back at Nix data from closures?

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#1542]
Let's say I'm paranoid about licensing, or want to track vulnerabilities in packages in my closures. I'll query `nix-store` for a runtime closure of some disk image, deployment, or something similar, and now I want to find out the `meta.license` or some other `meta.*` properties on the Nix side. The `.drv` file won't contain that data, and we don't really want it to to avoid unnecessary rebuilds. But also by the time we're in `.drv` space, we don't have a clean way to get back to data like `.meta` on the Nix side.

I recall @shlevy proposed a way of throwing data along exception handling, but that didn't get merged, so I'm wondering how we can track that sort of data reliably. We can obviously approximate it by walking `buildInputs`, but that'll lose any secret string dependencies and stuff that isn't represented explicitly.

Is there a good way to do this sort of thing today?

@edolstra @domenkozar

**Comment by edolstra** [comment]
No, there is no good way to do that today.
