### ISSUE TITLE
src/libstore/build.cc:58:10: fatal error: nlohmann/json.hpp: No such file or directory

### ISSUE THREAD

**Issue by trofi** [NixOS/nix#1544]
Tried to build today's masterto fix unrelated error.
Build fails due to missing file:
```
LANG=C make
  CXX    src/libstore/build.o
src/libstore/build.cc:58:10: fatal error: nlohmann/json.hpp: No such file or directory
 #include <nlohmann/json.hpp>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [mk/patterns.mk:3: src/libstore/build.o] Error 1
```

commit 4af2611bd105f365e568069463b1700d141dd0a8 suggests it should be a part of the repo:
```diff
--- a/local.mk
+++ b/local.mk
@@ -3,7 +3,7 @@ ifeq ($(MAKECMDGOALS), dist)
   dist-files += $(shell git --git-dir=.git ls-files || find * -type f)
 endif

-dist-files += configure config.h.in nix.spec perl/configure
+dist-files += configure config.h.in nix.spec perl/configure src/nlohmann/json.hpp
```

Missing submodule/file?

/cc @edolstra

**Comment by edolstra** [comment]
This package is included in `shell.nix` and in the tarball job.

**Comment by trofi** [comment]
Do I understand correctly nix is not buildable from git on a system without nix
or I've completely misinterpreted "tarball job"?
I'm currently copying `src/nlohmann/json.hpp` from upstream.

**Comment by trofi** [comment]
Do I understand correctly `nix` is not expected to be buildable
from git on a system without `nix` already installed anymore?

Or I've completely misinterpreted "tarball job" reference
and `nlohmann/json` is a new external dependency of `nix`?

I'm currently copying `src/nlohmann/json.hpp` file from upstream
to make `nix` build but a bit puzzled if it's the supposed way to get
a file on a system without `nix` available yet.

**Comment by copumpkin** [comment]
@trofi not 100% sure, but I think the idea is that you aren't necessarily expected to be able to build Nix from source from the git repo (at least not without jumping through some hoops), but it should work from official source tarball releases, which take care of injecting those things into the right places. @edolstra is that right?

**Comment by robstewart57** [comment]
I also fell into this issue. Perhaps it should be made clear in

https://nixos.org/nix/manual/#sec-building-source

That building nix from source, without nix already being installed, is not a possibility.

Aside, why isn't the error:

    src/libexpr/primops/fetchGit.cc:11:29: fatal error: nlohmann/json.hpp: No such file or directory
     #include <nlohmann/json.hpp>

Caught during `./configure`, i.e. why is the json package not listed as a dependency?

**Comment by edolstra** [comment]
Nix now includes a copy of nlohman/json.hpp (7f2c324e).
