### ISSUE TITLE
Documenting uninstall for multi-user on macOS

### ISSUE THREAD

**Issue by grahamc** [NixOS/nix#1551]
This is the script I've used for testing:

```sh
#!/bin/sh

set -x

if [ -f /Library/LaunchDaemons/org.nixos.nix-daemon.plist ]; then
    sudo launchctl unload /Library/LaunchDaemons/org.nixos.nix-daemon.plist
    sudo rm /Library/LaunchDaemons/org.nixos.nix-daemon.plist
fi

if [ -f /etc/profile.backup-before-nix ]; then
    sudo mv /etc/profile.backup-before-nix /etc/profile
fi

if [ -f /etc/bashrc.backup-before-nix ]; then
    sudo mv /etc/bashrc.backup-before-nix /etc/bashrc
fi


if [ -f /etc/zshrc.backup-before-nix ]; then
    sudo mv /etc/zshrc.backup-before-nix /etc/zshrc
fi


for i in $(seq 1 $(sysctl -n hw.ncpu)); do
    sudo /usr/bin/dscl . -delete "/Users/nixbld$i"
done
sudo /usr/bin/dscl . -delete "/Groups/nixbld"
```

**Comment by Anton-Latukha** [comment]
This would close recent: #1561
I also looked around for 'remove' 'uninstall' 'macOS' 'OS X' 'Darwin' tag, not found other reports relating to uninstallation.

**Comment by midfield** [comment]
i had the same problem, it happened because i had a restrictive umask.  when i set umask to 022, everything was fine.

**Comment by zimbatm** [comment]
I made the script a bit more idempotent: https://github.com/NixOS/nix/compare/master...zimbatm:darwin-uninstall-script?expand=1

**Comment by ChALkeR** [comment]
`sysctl -n hw.ncpu` returns 8 for me, but nix created 32 users, so the removal step misses those.
Perhaps `dscl . list /Users` instead?

**Comment by samueldr** [comment]
@grahamc is this still an issue?

 * https://nixos.org/nix/manual/#ch-installing-binary

Coming from https://github.com/NixOS/nixos-homepage/pull/178

**Comment by zimbatm** [comment]
It's much better. It would make sense to group the uninstallation procedure in a new chapter instead.

It also looks like the manual is only listing the first entry of Graham's script. The profile backups and users would remain on the system.

**Comment by domenkozar** [comment]
It's still quite bad experience. Here's what adds up:

- from asia, it takes about 3-5min to download the installer (that on it's own is OK)

- installer fails due to found backups, then gives a bunch of text and commands to run

- forget to run one command like removing bashrc backup (because well, why would you want to remove a backup)

- run installer again, wait 3-5min to break again :) repeat.

**Comment by expelledboy** [comment]
@grahamc  thanks for that little snippet, created a script for uninstalling nix on [OSx](https://gist.github.com/expelledboy/c00aebb004b178cf78b2c9b344526ff6) based on your efforts.

**Comment by jacix** [comment]
After reinstalling MacOS from scratch on my laptop and migrating my data with migration-assistant, Nix was badly broken.  With contributions from this thread (Hi @grahamc!) I cobbled together a simple, rough script that cleaned up everything and let me install Nix without issue. 

 In case anyone else wants to use, or better still, improve it: https://github.com/jacix/nixbits/blob/main/nix-uninstall.sh

**Comment by zimbatm** [comment]
The docs now include the uninstall steps https://github.com/NixOS/nix/blob/master/doc/manual/src/installation/installing-binary.md#uninstalling might help
