### ISSUE TITLE
Docker image don't have man pages so also --help

### ISSUE THREAD

**Issue by Anton-Latukha** [NixOS/nix#1557]
It is important to have the minimal image. For deployment.

But second, maybe hugest topic now. People use Docker images to try-out stuff.

And I got `nixos/nix`.
Logged in it.

And it does not have any `--help` or man pages for Nix.
So user is stuck. He can't learn. He can not look around, like blindfolded.
He has the option to use VM or install Nix on the system (but I am on Arch Linux, and install is not polished for Arch).

And I can't setup Nix man pages, because Nix in Docker installed manually and without man pages.

Maybe to have `nixos/nix:try`/`nixos/nix:tryout`/`nixos/nix:help`.

**Comment by bjornfor** [comment]
A co-worker of mine also hit this some weeks ago. It is still a problem:

```
$ docker run -it nixos/nix
400b4543ccad:/# nix-build --help
error: command 'man nix-build' failed: No such file or directory
400b4543ccad:/#
```

**Comment by edolstra** [comment]
Closing in favor of  #4476.
