### ISSUE TITLE
careful use nix on macOS

### ISSUE THREAD

**Issue by pynixwang** [NixOS/nix#1561]
some day I try to install some tools with nix, then I install nix on my mac, but there is no way to remove it fully, installer can delete some files but build users, then I delete users by command line, then my mac does' nt show login screen, I reinstall it.

**Comment by edolstra** [comment]
What are the steps to reproduce this?

**Comment by pynixwang** [comment]
@edolstra use installer clean some file. and delete build users and group by hand.

**Comment by pynixwang** [comment]
maybe installer cleaner is not a uninstaller.

**Comment by grahamc** [comment]
Here are the steps I follow to uninstall Nix. I'm sorry your system broke.

 https://github.com/NixOS/nix/issues/1551
