### ISSUE TITLE
Option to allow, but not enforce, ssh-substituter-hosts

### ISSUE THREAD

**Issue by nh2** [NixOS/nix#1570]
Non-root users can't use `--option ssh-substituter-hosts example.com` (on NixOS, on my Ubuntu this seems to work as my user owns the nix store?).

To have non-root users be able to pull from an SSH substituter, you have to place `ssh-substituter-hosts = example.com` into the global `/etc/nix/nix.conf`.

I would like to allow my user `jenkins` to use `--option ssh-substituter-hosts example.com` without enforcing the use of that substitutor for the entire machine.

This is for reliability reasons: If the host key of `example.com` changes, then an error will happen like

```
download-via-ssh: Host key verification failed.
download-via-ssh: error: unexpected end-of-file
error: substituter ‘download-via-ssh’ died unexpectedly
```

It's OK if that happens for my `jenkins` user, but if it happens at the system level, my system becomes rather unusable. This is especially grave when using `nixops`, because any `nixops deploy` will fail when that happens on the remote side, so you can't even use nixops to fix the problem.

Thus it would be great to have a whitelisting feature for ssh substituters, that _allows_ the given hosts to be chosen by unprivileged users, instead of mandating them system-wide.

**Comment by nh2** [comment]
(This could be worked around by using a normal binary cache instead of ssh substituter, but ssh substituers are extremely useful because they allow to handle authentication trivially and work for non-public setups.)

**Comment by nh2** [comment]
Another solution would be to allow it to fall back and not use the SSH substituter if it doesn't work (e.g. because the host key changed or because the machine is down).

**Comment by nh2** [comment]
Another brutal workaround is to use `nix.trustedUsers = [ "root" "jenkins" ];` which is what I'm currently using.

**Comment by nh2** [comment]
(If it is decided to implement a requested whitelist feature, we should probably file another bug for falling back when ssh-substituters fail, as I just noticed that that the lack of fallback also problematic independent of any permissions.)

**Comment by edolstra** [comment]
Closing `ssh-substituter-hosts` since it no longer exists. SSH hosts can be added to `trusted-substituters` to allow users to enable them without enabling them globally.

**Comment by nh2** [comment]
@edolstra For clarification, does that work already with nix 1.11 or do I need 1.12/2.0 for that?

**Comment by edolstra** [comment]
That's in 2.0.
