### ISSUE TITLE
It seems odd to fall back on creating an S3 bucket if one doesn't exist

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#1575]
In here https://github.com/NixOS/nix/blob/561e977f51c1d9ec55e4a70791958d4e214df465/src/libstore/s3-binary-cache-store.cc#L186-L204

the code appears to try to create a bucket if one doesn't already exist. It seems like that could obscure typos and cause other unexpected errors and a lot of head-scratching if you accidentally pick the wrong bucket name in your S3 binary cache. The use cases for auto-creating a bucket also seem fairly slim, and folks might want to be more deliberate about picking bucket ACLs and policies when doing that. It seems best to me to leave the bucket creation to an out-of-band operation.

**Comment by endgame** [comment]
I agree. Would a PR to fix this be looked at?

**Comment by endgame** [comment]
I cannot find this code in current `master` - looks like `nix` does not attempt to do this any more. Suggest closing this issue.
