### ISSUE TITLE
Structured output from nix-build/nix-instantiate

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#1581]
Currently, as far as I know, I can ask `nix-build` (or `nix-instantiate`) to build an attrset of derivations but it's hard to tell which produced which output path. It'll drop a bunch of symlinks into the current directory and spit out a bunch of paths on stdout, but there's no linkage between which attribute produced which path.

It would be nice if `nix-build` and `nix-instantiate` had a `--json` flag (`nix-instantiate` already does but only when used with `--eval`) that caused it to show a mapping between an attribute path and the output path (or drv path) associated with it, so that downstream tooling can make use of that information reliably.

**Comment by edolstra** [comment]
These commands are legacy IMHO. It's better to add a `--json` flag to `nix build`.

**Comment by copumpkin** [comment]
Fair enough 😄
