### ISSUE TITLE
`nix-build' freezes system on High Sierra with multi-user install

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nix#1583]
I'm suspecting this has more to do with the new file system than Nix. But this has only happened while Nix is running, so I'm going to report it here.

Basically, running a fairly download intensive Nix build freezes the entire High Sierra OS, causing the mouse and keyboard to not work. The only way to fix once this happens is to force reboot the system.

I'm getting very little information on why this is happening but I've only had it happen when nix-build was running the terminal. The tail of that output (before freezing) is:

```
fetching path ‘/nix/store/ij8nflh8kgbxz9a4zvzqr29qr8qczhkn-hspec-core-2.4.4-doc’...

*** Downloading ‘https://cache.nixos.org/nar/18m7q4fpg4ym69pnbbqk8jlv5zz6x90iq8k8z70b7cs234ihzb24.nar.xz’ (signed by ‘cache.nixos.org-1’) to ‘/nix/store/6g7nmj00asjavdcamjs6ndndkpm3msl1-th-expand-syns-0.4.3.0’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
*** Downloading ‘https://cache.nixos.org/nar/013sygin5zrqgdsw5n1656v3i2c9c2cxp9rcdvmvavkh3xgcxnpm.nar.xz’ (signed by ‘cache.nixos.org-1’) to ‘/nix/store/siz3is7w8qkx1ssmjha5cqg4p1n1ibdg-ChasingBottoms-1.3.1.3-doc’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
*** Downloading ‘https://cache.nixos.org/nar/04qzk7nkl9c707k0w0gv286ajmms055xipfbxvm57w7k1pgkv3gq.nar.xz’ (signed by ‘cache.nixos.org-1’) to ‘/nix/store/ij8nflh8kgbxz9a4zvzqr29qr8qczhkn-hspec-core-2.4.4-doc’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 38576  100 38576    0     0  38576      0  0:00:01 --:--:--  0:00:01  118k

fetching path ‘/nix/store/nzkviwc6yf5g72wgkk5gslqbq5lm9gsc-hspec-meta-2.4.4-doc’...
100 61948  100 61948    0     0  61948      0  0:00:01 --:--:--  0:00:01  177k

fetching path ‘/nix/store/0cwzgwkj6ciy7rgnwqw9il0f54gb3hrn-quickcheck-io-0.2.0-doc’...

*** Downloading ‘https://cache.nixos.org/nar/103pn3xq9076f8p64riy8kyvyag13k4im7pn2r8xnbf250h8pagw.nar.xz’ (signed by ‘cache.nixos.org-1’) to ‘/nix/store/nzkviwc6yf5g72wgkk5gslqbq5lm9gsc-hspec-meta-2.4.4-doc’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
*** Downloading ‘https://cache.nixos.org/nar/03w98rqgk9q8i9lyv11nnscsvj8xbknh4npnnil18mqsfpm76h20.nar.xz’ (signed by ‘cache.nixos.org-1’) to ‘/nix/store/0cwzgwkj6ciy7rgnwqw9il0f54gb3hrn-quickcheck-io-0.2.0-doc’...
100 85348  100 85348    0     0  85348      0  0:00:01 --:--:--  0:00:01  152k

fetching path ‘/nix/store/65q2hsxdmqixwhj1psx3dzl2gxj237rd-quickcheck-unicode-1.0.1.0-doc’...
 63 4365k   63 2764k    0     0  2764k      0  0:00:01  0:00:01 --:--:-- 1538k  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 77096  100 77096    0     0  77096      0  0:00:01 --:--:--  0:00:01  193k

fetching path ‘/nix/store/5dsaw36ikcki8p5kkdaj4lz7qrd0f74c-hspec-2.4.4-doc’...
100 22528  100 22528    0     0  22528      0  0:00:01 --:--:--  0:00:01 77150


*** Downloading ‘https://cache.nixos.org/nar/1ax3rddcv89k107jimgkppklxvsxcjy8lziy8z8n2rjwssh74bd2.nar.xz’ (signed by ‘cache.nixos.org-1’) to ‘/nix/store/65q2hsxdmqixwhj1psx3dzl2gxj237rd-quickcheck-unicode-1.0.1.0-doc’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0fetching path ‘/nix/store/z2i77z1vyghw8n47zhpgh1ia8kcri4ss-hspec-smallcheck-0.4.2-doc’...

*** Downloading ‘https://cache.nixos.org/nar/0mn6hk91ix2khv6q95vpw6ahhyqnagi3wh253l46axmriax42nb4.nar.xz’ (signed by ‘cache.nixos.org-1’) to ‘/nix/store/5dsaw36ikcki8p5kkdaj4lz7qrd0f74c-hspec-2.4.4-doc’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
*** Downloading ‘https://cache.nixos.org/nar/0cvvp36xjrs5cvvph3h6zr6wpmgrn4vyzpkpghkn7cj8a36qx5bk.nar.xz’ (signed by ‘cache.nixos.org-1’) to ‘/nix/store/z2i77z1vyghw8n47zhpgh1ia8kcri4ss-hspec-smallcheck-0.4.2-doc’...
100 26184  100 26184    0     0  26184      0  0:00:01 --:--:--  0:00:01 79105
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
fetching path ‘/nix/store/dm7vy3dgsn9sp7nc8yqd7akjg4c64az8-tasty-quickcheck-0.8.4-doc’...
100 4365k  100 4365k    0     0  2182k      0  0:00:02  0:00:02 --:--:-- 1755k
```

This could just be from just too many writes to the disk at one time. That last file, ```/nix/store/dm7vy3dgsn9sp7nc8yqd7akjg4c64az8-tasty-quickcheck-0.8.4-doc``` does not exist on my system after recovery so I wonder if it is an I/O issue there. I'm going to run a disk diagnostic to see if something is wrong with the hardware, but I've never had the issue before the switch APFS. Any way, I want to see if others have a similar experience on High Sierra.

**Comment by m-idler** [comment]
I'm experiencing similar issues when starting a nix-shell that triggers several downloads via default.nix. After some time the system freezes as you described (sometimes only the mouse keeps responsible a little bit longer, but no clicking is possible). 
The freeze itself is reproducible after hard reboot / new installation of nix. If it helps i can provide a verbose output of the build.

**Comment by edolstra** [comment]
@m-idler Are you also using APFS?

**Comment by m-idler** [comment]
@edolstra yes, it was converted automatically within the upgrade

**Comment by whiteley** [comment]
I just experienced a similar issue on a Mac mini (Mid 2011) with a fusion drive formatted with hfs. I had installed nix 1.11.15 and was running the nix-darwin bootstrap when it failed. Similar to the first report, the last file listed was not present upon reboot thought the previous ones seem to be. I had to force the machine off with the power button.

The following messages were the last in `/var/log/system.log` before the `BOOT_TIME` message.

```
Sep 28 17:29:26 facet com.apple.xpc.launchd[1] (com.apple.mdworker.lsb.02000000-0000-0000-0000-000000000000[1042]): Service exited due to signal: Killed: 9 sent by nix-daemon[1049]
Sep 28 17:29:26 facet com.apple.xpc.launchd[1] (com.apple.mdworker.bundles[1020]): Service exited due to signal: Killed: 9 sent by nix-daemon[1049]
Sep 28 17:29:26 facet com.apple.xpc.launchd[1] (com.apple.mdworker.single.05000000-0000-0000-0000-000000000000[1015]): Service exited due to signal: Killed: 9 sent by nix-daemon[1049]
Sep 28 17:29:26 facet com.apple.xpc.launchd[1] (com.apple.lsd[991]): Service exited due to signal: Killed: 9 sent by nix-daemon[1049]
Sep 28 17:29:26 facet com.apple.xpc.launchd[1] (com.apple.mdworker.single.06000000-0000-0000-0000-000000000000[1016]): Service exited due to signal: Killed: 9 sent by nix-daemon[1049]
Sep 28 17:29:26 facet com.apple.xpc.launchd[1] (com.apple.mdworker.single.08000000-0000-0000-0000-000000000000[1004]): Service exited due to signal: Killed: 9 sent by nix-daemon[1049]
Sep 28 17:29:26 facet com.apple.xpc.launchd[1] (com.apple.secd[1002]): Service exited due to signal: Killed: 9 sent by nix-daemon[1049]
Sep 28 17:29:26 facet com.apple.xpc.launchd[1] (com.apple.trustd.agent[992]): Service exited due to signal: Killed: 9 sent by nix-daemon[1049]
Sep 28 17:29:26 facet com.apple.xpc.launchd[1] (com.apple.mdworker.shared.03000000-0000-0000-0000-000000000000[970]): Service exited due to signal: Killed: 9 sent by nix-daemon[1049]
Sep 28 17:29:26 facet com.apple.xpc.launchd[1] (com.apple.mdworker.shared.04000000-0000-0000-0000-000000000000[969]): Service exited due to signal: Killed: 9 sent by nix-daemon[1049]
Sep 28 17:29:26 facet com.apple.xpc.launchd[1] (com.apple.mdworker.shared.02000000-0000-0000-0000-000000000000[968]): Service exited due to signal: Killed: 9 sent by nix-daemon[1049]
Sep 28 17:29:26 facet com.apple.xpc.launchd[1] (com.apple.mdworker.single.07000000-0000-0000-0000-000000000000[1014]): Service exited due to signal: Killed: 9 sent by nix-daemon[1049]
Sep 28 17:29:26 facet com.apple.xpc.launchd[1] (com.apple.mdworker.shared.01000000-0000-0000-0000-000000000000[971]): Service exited due to signal: Killed: 9 sent by nix-daemon[1049]
Sep 28 17:29:26 facet com.apple.xpc.launchd[1] (com.apple.distnoted.xpc.agent[973]): Service exited due to signal: Killed: 9 sent by nix-daemon[1049]
Sep 28 17:29:41 facet com.apple.xpc.launchd[1] (com.apple.lsd[1076]): Service exited due to signal: Killed: 9 sent by nix-daemon[1309]
Sep 28 17:29:41 facet com.apple.xpc.launchd[1] (com.apple.distnoted.xpc.agent[1071]): Service exited due to signal: Killed: 9 sent by nix-daemon[1309]
Sep 28 17:29:41 facet com.apple.xpc.launchd[1] (com.apple.mdworker.shared.01000000-0000-0000-0000-000000000000[1069]): Service exited due to signal: Killed: 9 sent by nix-daemon[1309]
Sep 28 17:29:41 facet com.apple.xpc.launchd[1] (com.apple.mdworker.shared.04000000-0000-0000-0000-000000000000[1067]): Service exited due to signal: Killed: 9 sent by nix-daemon[1309]
Sep 28 17:29:41 facet com.apple.xpc.launchd[1] (com.apple.mdworker.shared.03000000-0000-0000-0000-000000000000[1070]): Service exited due to signal: Killed: 9 sent by nix-daemon[1309]
Sep 28 17:29:41 facet com.apple.xpc.launchd[1] (com.apple.mdworker.shared.02000000-0000-0000-0000-000000000000[1068]): Service exited due to signal: Killed: 9 sent by nix-daemon[1309]
```

**Comment by matthewbauer** [comment]
I wonder if this syscall is killing more than it should:

https://github.com/NixOS/nix/blob/3ed8290e5331011609de462bda67857837998583/src/libutil/util.cc#L815

**Comment by shlevy** [comment]
@matthewbauer Do you know if the xnu source for high sierra is out yet? That was definitely correct for older versions of the kernel but I wouldn't at all be surprised if it's just changed behavior now. cc @copumpkin

**Comment by shlevy** [comment]
Anyway I'll dig into this this weekend :sob:

**Comment by shlevy** [comment]
Can I get `uname -a` for someone on high sierra please?

**Comment by matthewbauer** [comment]
```
Matthews-MacBook:~ mbauer$ uname -a
Darwin Matthews-MacBook.local 17.0.0 Darwin Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64 x86_64
```

**Comment by shlevy** [comment]
@matthewbauer thanks! Do you by chance have access to a machine with `10.12.6` you can run your test on?

**Comment by shlevy** [comment]
Wait, hold on, you can lock up the system by running that program as `nixbld1`???

**Comment by m-idler** [comment]
@matthewbauer my device is a MacBook Pro, Early 2015 with SSD, APFS with encryption enabled.

I got the same OS Version @matthewbauer posted

**Comment by bjtitus** [comment]
I've had the exact same issue for a while now. I also pulled several logs, some of which seem to include errors about running out of memory but that may be a red herring.

```
Console[25514]: Console(25514,0x7000010b9000) malloc: malloc_memory_event_handler: approaching memory limit. Starting stack-logging.
Console[25514]: Console(25514,0x7000010b9000) malloc: recording malloc (and VM allocation) stacks using lite mode
```

Some system info (10.13 GM Seed 17A362a on late 2016 MacBook Pro with APFS + FileVault):
> 17.0.0 Darwin Kernel Version 17.0.0: Thu Aug 24 22:01:05 PDT 2017; root:xnu-4570.1.46~3/RELEASE_X86_64 x86_64

**Comment by bjtitus** [comment]
@shlevy Not sure if you saw yet but the new xnu source code for the same version listed in the comments here was released yesterday https://opensource.apple.com/source/xnu/xnu-4570.1.46/

**Comment by shlevy** [comment]
@bjtitus Ah, didn't realize it was just released yesterday! Thanks.

**Comment by kirelagin** [comment]
@shlevy 

> Do you by chance have access to a machine with 10.12.6 you can run your test on?

I tried this program on 10.12.6 for 30 times. It blanks the screen, but the system does not freeze.

**Comment by Balletie** [comment]
Macbook Pro Early 2011, I'm having the same issue here after upgrading.

**Comment by shlevy** [comment]
As a workaround for the time being, single user nix mode should work.

**Comment by matthewbauer** [comment]
If anyone has NOT updated to High Sierra, they should try building Nix before installing at this commit:

6ce2d31b27ada95cc5fdd1c241c50ee2bce17171

to see if it fixes this issue for them (if you are on High Sierra most likely you can't even build Nix without getting the hanging issue). Sadly, I can't test it right now, so not sure if it actually avoids the issue.

**Comment by shlevy** [comment]
@matthewbauer See my comment.

**Comment by ktf** [comment]
@shlevy Can you point to instructions on how to install single user on mac? The installer seems to force me in multiuser by default.

**Comment by shlevy** [comment]
@ktf: @grahamc may be able to help with an installer that does this properly from the get-go, but I believe just `chown -R ktf /nix` and then unsetting `NIX_REMOTE` (also in your `~/.profile` probably) should do the trick after installation.

**Comment by shlevy** [comment]
http://zzamboni.org/post/using-nixs-single-user-mode-on-macos/

**Comment by ktf** [comment]
So I managed to build and install (and hopefully switch to) nix 1.11.15 + @matthewbauer patch (3cc1b57). However my mac still freezes. To update I did:

```bash
$ sudo su - # root builds in non-multiuser mode, apparently
$ git clone https://github.com/NixOS/nix
$ cd nix
$ git fetch https://github.com/matthewbauer
$ git reset --hard 1.11.15
$ git cherry-pick 3cc1b57
$ nix-build release.nix -A build.x86_64-darwin
```

which resulted in `/nix/store/2i38s6h7jfx39lfkd4srlv859vkbs7zj-nix-1.11.15pre1234_abcdef` .  I then went on and made it the current nix for root with:

```
$ nix-env -i /nix/store/2i38s6h7jfx39lfkd4srlv859vkbs7zj-nix-1.11.15pre1234_abcdef
$ launchctl unload /Library/LaunchDaemons/org.nixos.nix-daemon.plist
$ launchctl load /Library/LaunchDaemons/org.nixos.nix-daemon.plist
$ sudo launchctl start org.nixos.nix-daemon
```

and checked it actually picked it up:

```
$ nix-env --version
nix-env (Nix) 1.11.15pre1234_abcdef
$ ps auxwww | grep nix
root             13554   0.0  0.0  4275264   1904   ??  Ss    2:31PM   0:00.01 /nix/store/2i38s6h7jfx39lfkd4srlv859vkbs7zj-nix-1.11.15pre1234_abcdef/bin/nix-daemon
```

I then opened a new user shell and changed it to use the new nix as well:

```
$ nix-env -i /nix/store/2i38s6h7jfx39lfkd4srlv859vkbs7zj-nix-1.11.15pre1234_abcdef
```

Finally I started building my top-level package once again:

```
$ nix-env -i all
```

but this still fails when doing "patching interpreter path" of some vim plugin. Am I doing anything wrong?

**Comment by matthewbauer** [comment]
@ktf try running Nix-daemon on its own with ```sudo nix-daemon``` to make sure it’s the right version (don’t use launchd)

**Comment by jbaum98** [comment]
I built `nix` with the new commit and ran the daemon using `sudo nix-daemon`, and now it seems to be building!

**Comment by jbaum98** [comment]
However, it still freezes if I exit a build early with Ctl-C

**Comment by shlevy** [comment]
@jbaum98 Is your nix client the patched nix as well?

**Comment by jbaum98** [comment]
Yeah it is.

**Comment by jrolfs** [comment]
@jbaum98 so you're running Sierra right? Tried @matthewbauer's fix on High Sierra just to see and it still locks up.

**Comment by jbaum98** [comment]
No, I'm running High Sierra. Before the fix I couldn't even begin to compile `hello` without freezing. Now that works but it still freezes when interrupted. But maybe that's all misleading, it has been inconsistent the whole time.

**Comment by matthewbauer** [comment]
It's definitely possible we're dealing with two different macOS freezes here. I can't figure out what else could be causing it though...

To be clear, this really is Apple's problem, it would just be nice if we could have a temporary fix until this is patched.

**Comment by jrolfs** [comment]
@shlevy out of curiosity, how does single user mode get around this issue?

**Comment by edolstra** [comment]
@jrolfs In single user mode, we don't use `kill(-1, ...)` (since that would kill all of the user's processes).

**Comment by jbaum98** [comment]
What did Apple change that caused this problem?

**Comment by grahamc** [comment]
Sorry @jbaum98, we can't get in to that at the moment by request of Apple.

**Comment by peterromfeldhk** [comment]
following http://zzamboni.org/post/using-nixs-single-user-mode-on-macos/ to switch to single user mode resolved the problem for me.
The cleanup however did not work and i could not find build users/group, i installed nix via homebrew cask

**Comment by matthewbauer** [comment]
In case anyone is wondering, the latest High Sierra update does NOT fix this.

**Comment by shlevy** [comment]
Now that we have disclosed the issue: The problem is a fundamental one in the kill(2) syscall on High Sierra. In principle we might be able to cobble together a workaround, but without something like cgroups on Linux (there's no obvious way to kill an entire sandbox, for example) it seems unlikely to be worthwhile when Apple will have to fix this anyway.

**Comment by matthewbauer** [comment]
Here's a Gist with the kernel panic if anyone is interested in trying it at home:

https://gist.github.com/matthewbauer/1563ec69d8f99bbaf6788a8e696c9540

Just run:

```
curl https://matthewbauer.us/kernel-panic.sh | sh
```

and don't switch applications after you press enter, and that should enter a kernel panic on your MacOS.

**Comment by david50407** [comment]
@grahamc any other information that we can get from Apple? Or the only thing we can do is wait for a fix from them?

**Comment by peterromfeldhk** [comment]
it doesnt seem apple plan on fixing it :(
https://groups.google.com/forum/m/#!topic/nix-devel/KV9eomIdxWE

**Comment by shlevy** [comment]
@peterromfeldhk They haven't said anything about not fixing it, just not on a security-issue timeframe.

**Comment by shlevy** [comment]
@edolstra Until Apple fixes this, can we simply add a patch to simply refuse to start in multiuser mode and tell the user to switch to single user mode if it finds itself on high sierra?

**Comment by grahamc** [comment]
I think patching to refuse to start in multi-user mode is a not good idea. @copumpkin, @shlevy, and I have been exploring alternative solutions here.

One idea includes reapplying a tighter sandbox to the build user (if possible, to be determined) which prevents forking, enumerating all the processes (using the atomic syscall KERN_PROC_UID) killing them all, and repeating this loop until there are no processes by the user.

Here are some threads by @copumpkin to watch:

 - http://newosxbook.com/forum/viewtopic.php?f=7&t=17134
 - http://newosxbook.com/forum/viewtopic.php?f=7&t=17135

**Comment by matthewbauer** [comment]
For the people who switched to single-user mode, have there been any weird issues? This could be unrelated but I've also gotten builds that seem to be stuck but not really doing anything. Other weirdness afterwards like Activity Monitor not working:

<img width="870" alt="screen shot 2017-10-20 at 11 02 26 pm" src="https://user-images.githubusercontent.com/19036/31847902-d51a4a8c-b5ea-11e7-9e7e-58c94162ffcf.png">

It's certainly better than the kernel panic thing... Anyway if anyone has had similar issues please give feedback! (I'm still not 100% this is caused by Nix but can't think of anything else I've been doing.

**Comment by peterromfeldhk** [comment]
i dont have any issues since switching (did you updated to latest high
sierra?)

**Comment by matthewbauer** [comment]
So the new issue I'm getting looks like it's the same as hishamhm/htop#682. It only happens after intensive CPU usage in Nix... Must be unrelated though?

**Comment by diclophis** [comment]
I am very interested in what details of the crash overlap between this bug, and the `htop` issue

**Comment by whiteley** [comment]
Running the script @matthewbauer posted no longer causes a kernel panic on my machine after applying the just released 10.13.1 update.

```
$ uname -v
Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64
```

**Comment by matthewbauer** [comment]
@whiteley

Sadly I'm still having the nix-build freeze issue on 10.13.1 when running multi-user Nix. Going to switch back to single-user and see if any issues come up.

**Comment by whiteley** [comment]
@matthewbauer that's unfortunate. I've run the script a few times without a panic. I'll modify it to run longer and try that to see if it changes. I've run a few builds (multi-user) as well without the immediate panic. As a reminder, I'm not using APFS though it would be very odd if we were talking about two different bugs here.

**Comment by pagzamaphone** [comment]
Just a note, I was having this issue, I have since updated to OSX 10.13.2 Beta (17C60c) and nix-1.11.15 and no longer have the freezing system issue.

**Comment by grahamc** [comment]
I've started a build of several hundred drvs on 1.13.2 beta. About 30min in and no freezes. Could this be it? :)

**Comment by periklis** [comment]
great news.

**Comment by matthewbauer** [comment]
Awesome! 10.13.2 works for me so far. I can close this issue as soon as it is released!

**Comment by ryantrinkle** [comment]
@grahamc How did those builds go?

**Comment by grahamc** [comment]
Thus for I’ve had no freezes. I did have the system crash due to an apfs
but though. The system immediately rebooted and ran the crash reporter.

Graham

**Comment by grahamc** [comment]
FWIW I consider this a success. Nix isn't causing horrific crashes anymore.

**Comment by ryantrinkle** [comment]
Awesome!  Sounds like, once the 10.13.2 drops, we're in the clear :)

**Comment by shlevy** [comment]
@grahamc Of course, by any reasonable definition it was never Nix causing the crashes 😉

**Comment by onetom** [comment]
A `nix-env -iA dapphub.{dapp,seth,hevm,evmdis}` just hung my _macOS 10.13.1_ using _Nix 1.11.15_, but after upgrading to _macOS 10.13.2 Beta (17C79a)_, the installation has succeeded.

**Comment by puppe** [comment]
`nix-channel --update` freezes my Mac as well most of the time. Could that be related? I have switched to "single-user mode" as suggested above. That seems to fix it. (I cannot tell for certain because it used to work sometimes without freezing.)

**Comment by matthewbauer** [comment]
Looks like 10.13.2 is released! So far so good.

**Comment by alexvorobiev** [comment]
@shlevy It is actually very easy to install in single user mode since the code is still in the install script. Just comment the if statement which calls the multiuser setup for Darwin and run the script.

I wonder can't we have the single user setup back as an option? In enterprise environments users normally don't have administrator's rights to their laptops. One top level directory (/nix) _could_ be ok but extensive system changes (additional local users, services) are usually out of question.
