### ISSUE TITLE
Using setpgid makes nix-shell hang

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#1585]
Here's a tiny perl script that shows what I'm talking about:

```perl
my $pid = fork();

if ($pid == 0) {
  printf "In child\n";
  setpgrp(0, 0);
  printf "About to exec...\n";
  exec 'nix-shell', '-p', 'hello', '--command', 'hello';
} else {
  printf "Waiting for child...\n";
  waitpid($pid, 0);
  printf "Done waiting!\n";
}
```

I've tried this on all versions of 1.11 and 1.12 and the hang seems consistent. If I switch `--command` to `--run`, it works, and if I comment out the `setpgrp` line, it also works.

This seems related to https://github.com/NixOS/nix/issues/1171 but wasn't fixed by that fix.

I've also noticed the exact same behavior in the `nix-shell` shebang code, but the repro for that was a bit bigger so I'm posting this one.

cc @edolstra @dezgeg who might have ideas, and @akazakov as an interested party

**Comment by dezgeg** [comment]
Same happens in bash, regardless of Nix:
````
my $pid = fork();

if ($pid == 0) {
  printf "In child\n";
  setpgrp(0, 0);
  printf "About to exec...\n";
  exec 'bash';
} else {
  printf "Waiting for child...\n";
  waitpid($pid, 0);
  printf "Done waiting!\n";
}
````

Probably calling setpgid() but keeping stdin/stdout pointing to the existing terminal is a Bad Idea.

**Comment by copumpkin** [comment]
Haha fair enough 😄
