### ISSUE TITLE
Make `nix-store -q --referrers` include GC roots

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#1597]
Sometimes something is marked as alive but querying `--referrers` produces no result. What that means is that there are no store paths referring to the path in question, but it also seems handy to have a flag like `--referrers --include-roots` that would show GC roots as well in the results. This more closely matches what (I think) most people want when they query `--referrers`, which is "why the hell is this thing being used?".

**Comment by LnL7** [comment]
This works https://gist.github.com/LnL7/0e972bc17f9e30c445db5eecbabd4f16, but having a nicer way to find the roots of a path would be great.

**Comment by edolstra** [comment]
`nix-store -q --roots` exists for this.

**Comment by copumpkin** [comment]
Wow, TIL, thanks!

```
$ nix-store -q --roots `which nix-env`
/nix/var/nix/profiles/default-13-link
/nix/var/nix/profiles/per-user/copumpkin/channels-8-link
```
