### ISSUE TITLE
Circular documentation: "The details of the build hook protocol are described in the documentation of the NIX_BUILD_HOOK variable."

### ISSUE THREAD

**Issue by oconnore** [NixOS/nix#1600]
> NIX_BUILD_HOOK
> Specifies the location of the build hook, which is a program (typically some script) that Nix will call whenever it wants to build a derivation. This is used to implement distributed builds (see Chapter 16, Distributed Builds).

**Comment by dezgeg** [comment]
`NIX_BUILD_HOOK` has removed from Nix 2.0, so this should be closable.
