### ISSUE TITLE
file generated by cabal2nix of cabal file depending on assert gets syntax error

### ISSUE THREAD

**Issue by haroldcarr** [NixOS/nix#1602]
Trying to use the `assert` package I get

    $ cabal2nix . > default.nix
    $ nix-shell -A env release.nix
    error: syntax error, unexpected ASSERT, expecting '}', at /Volumes/HC/.sync/.esync/openhc/snippets/nix-assert-bug/default.nix:1:17

If I remove `assert` from the arguments and from `libraryHaskellDepends` I can then do:

    $ nix-shell -A env release.nix

Reproducible example at:  https://github.com/haroldcarr/snippets/tree/master/nix-assert-bug

**Comment by cleverca22** [comment]
a solution: https://gist.github.com/cleverca22/151d974485fdcc3c44719adcc7699544
and also https://github.com/NixOS/cabal2nix/issues/164

**Comment by domenkozar** [comment]
Correct bug tracker is https://github.com/NixOS/cabal2nix/issues/164
