### ISSUE TITLE
Move to "Squash and merge" model

### ISSUE THREAD

**Issue by Anton-Latukha** [NixOS/nix#1606]
From #1549:

It is nature of someone who contribute pull request and waits on acceptance - to better it's pull request. To make fixes, add comments, polish, refactor code and text.

With squash on pull request on side of contributor - he needs to squash all commits every time, at every fix, at every improvement, to keep things clean and ready to merge.

With squash on merge on maintainer side:
1. Maintainer doesn't need to write to me that I need to make squash.
2. Maintainer doesn't need to wait when and do I going to do squash.
3. Maintainer can chose by himself the name of commit. So standardized commit names can be enforced.
4. All can be done as maintainer wants, when maintainer wants.
5. It is already a GUI feature on GitHub. https://help.github.com/articles/merging-a-pull-request/#merging-a-pull-request-on-github

So maybe move to model when maintainer uses "Squash and merge" model in Nix repositories. It would be one less step per pull request, and pull request would go faster.

**Comment by edolstra** [comment]
Not sure I understand the problem. Why would we want to get rid of (accurate) history?

**Comment by bjornfor** [comment]
IMHO the submitter should come up with a good patch series / pull request. A maintainer can come with suggestions and requests along the way, but I don't think it we should leave _all_ responsibility with the maintainer.

The biggest overhead here, I think, is communicating the idea about what a good nixpkgs PR looks like. It's not more work for the submitter to squash than the maintainer, if only the submitter knows (1) how to write commit messages and (2) partition changes into small / logical / atomic commits. (But yeah, there is some overhead there...)

As a maintainer, sometimes I squash and edit commit messages at merge time, but only up to a limit. Beyond that I think the submitter should be involved.

Here is a suggestion:
Add a check-box in the PR template saying "I allow Nixpkgs maintainers to squash/amend/rebase my commits (to possibly speed up integration)". Submitters can chose whether to check it off.

@edolstra: Accurate history may be noisy and break git bisect. I think it's a good idea to clean up as much as possible until patches hit master. Small internal changelogs can also be added in commit messages, for big and long lived patch series.

**Comment by Anton-Latukha** [comment]
Yes.

In PR contributor solves one particular problem.
Commits to PR involve: initial code submit, fixes to code, adding suggestions, refactoring.

And what sense of ping-pong:
1. When committers PR was reviewed, than after some time maintainer comes and asks him to squash commits.
2. Committer maybe sees a message, maybe not.
2.a. Maybe new committer learns what is Git Squash and learns to make squash.
3.  And committer goes and, through his utils or CLI, maybe sincs fork, maybe pulls his code once more, because he forgot where old local code was, or he is on separate machine now. He pulls, makes  manual squash, and pushes back.
4. Maintainer sees or not sees that squash happened.
5. Maintainer comes, and since he forgot what stuff was about - reviews the same code he reviewed previously, to refresh memory.
6. Maintainer merges pull request.
Done.

Or on Squash on merge:
0. Pull requests have name and description, and also first commit name in most PRs is what PR is about.
1. When committers PR was reviewed, than after some time maintainer comes and squashes and merges commit. He does that on the fly, right in the GitHub dialog.
Done

**Comment by Anton-Latukha** [comment]
I wrote my story from real world.

I just see the things this way.

Yes. It is one more action on maintainer. Majority of times it is just one click in the dialog.
But it saves a lot of workflow for maintainer and committer. Saves a lot of time. Shortens communications, and speeds up contributions rate.

You are have more experience and authority in this.

Option is also Ok. But it is one more choice to understand, one more decision, action to committer.
From contributor perspective:
Maintainer knows better and has all authority to merge after he decides that code is accepted.
Contributor gets happy when maintainer merged his contribution, contributor does not really care if maintainer cherry-picked, squashed commits. The main thing - it is accepted and feature is in the code base - "I am happy, thank you maintainer."

**Comment by Anton-Latukha** [comment]
Like happened here:
https://github.com/syl20bnr/spacemacs/pull/9731

**Comment by Anton-Latukha** [comment]
I raised this question verbally on NixCon2017 to main NixPkg maintainers.

Closing.

**Comment by ivan** [comment]
For anyone new to looking at commit history as merge-heavy as nixpkgs:

```
git log -p --first-parent -m
```

or

```
TIG_DIFF_OPTS=--first-parent tig --first-parent -m
```
