### ISSUE TITLE
Feature request: Print backtrace in `trace` output

### ISSUE THREAD

**Issue by bgamari** [NixOS/nix#1610]
The `builtins.trace` function is quite handy for probing state buried deep within a derivation. However, while trying to understand a cross-compiling bug I've seen my trace output printed multiple times. Without a stack backtrace (e.g. what `throw` would produce with `--show-trace`) this is quite difficult to interpret.

**Comment by copumpkin** [comment]
This seems cool and possibly not too hard to add. I'd probably make a new builtin for it though, like `builtins.dumpStack` which behaves like the identity function except dumps a stack trace when forced. I don't necessarily want a stack dump in every trace output, and we can't really change the API much. What you're asking then would be a composition of `builtins.trace` and `builtins.dumpStack`

**Comment by milahu** [comment]
push : )

**Comment by milahu** [comment]
> I'd probably make a new builtin for it though, like `builtins.dumpStack` which behaves like the identity function except dumps a stack trace when forced.

plus: something like `builtins.callStack` to get a list of the current callstack,
which can be manually reduced to, for example, the last 5 entries, to avoid printing "too long" stacktraces

**Comment by 9999years** [comment]
Got most of the way through filing a new issue before noticing this. Here's my experience and my idea for a design:

**Is your feature request related to a problem? Please describe.**

Right now, my project is showing some warnings:

```
$ nix develop
trace: warning: `pythonForBuild` (from `python*`) has been renamed to `pythonOnBuildForHost`
trace: warning: `pythonForBuild` (from `python*`) has been renamed to `pythonOnBuildForHost`
trace: warning: `pythonForBuild` (from `python*`) has been renamed to `pythonOnBuildForHost`
```

So I run `rg pythonForBuild`, but it doesn't turn up any results. The code that uses `pythonForBuild` must be in some other repository we're importing. When Nix is evaluating the code that produces this warning, it knows what the call stack is, but it's not exposed to the user.

**Describe the solution you'd like**

It would be nice if we could have an option to make `builtins.trace` show its call location, like this:

```
$ nix develop --builtins-trace-location
trace: warning: `pythonForBuild` (from `python*`) has been renamed to `pythonOnBuildForHost`
         at /nix/store/qccbdqrhwaaic3kwv9d4zak9fqh7yhlw-source/pkgs/development/interpreters/python/mk-python-derivation.nix:130:22:

          129|   validatePythonMatches = attrName: let
          130|     isPythonModule = drv:
             |                      ^
          131|       # all pythonModules have the pythonModule attribute
```

Perhaps it could compose with `--show-trace` to show a full stack trace as well:

```
$ nix develop --builtins-trace-location --show-trace
trace: warning: `pythonForBuild` (from `python*`) has been renamed to `pythonOnBuildForHost`
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'ghc-shell-for-mwb-0-0'
         whose name attribute is located at /nix/store/qccbdqrhwaaic3kwv9d4zak9fqh7yhlw-source/pkgs/stdenv/generic/make-derivation.nix:352:7

         at /nix/store/qccbdqrhwaaic3kwv9d4zak9fqh7yhlw-source/pkgs/development/interpreters/python/mk-python-derivation.nix:130:22:

          129|   validatePythonMatches = attrName: let
          130|     isPythonModule = drv:
             |                      ^
          131|       # all pythonModules have the pythonModule attribute
```

**Describe alternatives you've considered**

Alternatively or additionally, it would be nice to enter the debugger (`--debugger`) when `builtins.trace` is called.
