### ISSUE TITLE
chown error when running in sandboxed single-user mode

### ISSUE THREAD

**Issue by michaelpj** [NixOS/nix#1613]
My nix setup:
- Single user mode.
- `/nix`, `/nix/store`, `/nix/var` owned by my user and group.
- Sandboxing enabled.
- Nix version 1.11.5.

With this, I get the following error when building a derivation:
```
building path(s) ‘/nix/store/fbf12bhax4jy1qfv3n9a1wdzvy0s4sxd-tzupdate-1.2.0.tar.gz’
error: cannot change ownership of ‘/nix/store/wbivfy4c1xk79i2q2f0s4j20jk6lg01s-tzupdate-1.2.0.tar.gz.drv.chroot’: Operation not permitted
```

Strace shows the following:
```
[pid 31438] lstat("/nix/store/wbivfy4c1xk79i2q2f0s4j20jk6lg01s-tzupdate-1.2.0.tar.gz.drv.chroot", 0x7ffe792cdbe0) = -1 ENOENT (No such file or directory)
[pid 31438] mkdir("/nix/store/wbivfy4c1xk79i2q2f0s4j20jk6lg01s-tzupdate-1.2.0.tar.gz.drv.chroot", 0750) = 0
[pid 31438] chown("/nix/store/wbivfy4c1xk79i2q2f0s4j20jk6lg01s-tzupdate-1.2.0.tar.gz.drv.chroot", 0, 0) = -1 EPERM (Operation not permitted)
```

This looks like the call to chown at [here](https://github.com/NixOS/nix/blob/1.11-maintenance/src/libstore/build.cc#L2053). I'm not using a build user, so it appears that the UID and GID for `buildUser` are 0 (hence why it's attempting to chown to group 0). I think that means that `buildUser.enabled()` is false, and I notice that earlier several uses of the build user GID that look like this: `buildUser.enabled() ? buildUser.getGID() : getgid()`.

My guess is that the chown call (and perhaps also [this one](https://github.com/NixOS/nix/blob/1.11-maintenance/src/libstore/build.cc#L2010)) should also be using the caller's GID if the build user is not enabled. I haven't yet managed to build a version with this patched to see if it fixes it, but I'll see if I can work it out.

**Comment by michaelpj** [comment]
This also doesn't occur with Nix 1.12.

**Comment by ThomasMader** [comment]
I get the same while running _nix-channel --update_ on 1.11.5 with sandboxing enabled on a Fedora machine.

**Comment by edolstra** [comment]
IIRC, sandboxing is not supported for non-root users in Nix < 1.12.

**Comment by knedlsepp** [comment]
@edolstra Does this imply it should work on 1.12? I just tried to run current master's nix-daemon with `--option build-use-sandbox true`, but I get build errors like that:
```
error: cannot change ownership of ‘/nix/store/mzx5kw33lb2qlqzcid14d9x5gmf7hcp0-asdf.drv.chroot’: Operation not permitted
```
