### ISSUE TITLE
Ability to specify binary caches as store URIs

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#1620]
This would allow us to control signature verification on a per-cache basis, by passing in parameters like `?require-sigs=false` on individual URIs.

Relatedly, I was also thinking of possibly adding another optional argument like `?force-priority=10` or something to override the priority specified in `nix-cache-info`.

I'm thinking of an option in addition to `binary-caches` for something like `binary-cache-uris`. Would this be weird?

**Comment by edolstra** [comment]
Substituters already *are* store URIs. Note that `binary-caches` was renamed to `substituters`.

**Comment by copumpkin** [comment]
Oh, awesome, thanks!
