### ISSUE TITLE
Add uninstall information to the manual

### ISSUE THREAD

**Issue by Munksgaard** [NixOS/nix#1623]
The uninstall information in the manual is currently both incomplete and hard to find. I think we should add a separate section to describe the steps necessary to perform a complete uninstall.

Related issues: #1608, #1551. Also discussed in #1402 and #458.

**Comment by expelledboy** [comment]
If anyones interested in a script for [OSx](https://gist.github.com/expelledboy/c00aebb004b178cf78b2c9b344526ff6).

**Comment by vcunat** [comment]
This ticket is about adding uninstallation instructions into the manual, which (as you noticed) has been fixed: https://nixos.org/manual/nix/stable/installation/installing-binary.html#uninstalling

Improving that instruction and similar... can be done separately; actually a pull request sounds better to me than an issue.

**Comment by kha84** [comment]
Okay. Sure.

**Comment by max397574** [comment]
@vcunat I was looking for uninstalling instructions and found this page
the link points to a 404 for me though
