### ISSUE TITLE
nix-env -i firefox provides invalid downlink for SDK

### ISSUE THREAD

**Issue by doublehp** [NixOS/nix#1628]
I am NIX beginner. 

My aim: update Firefox.

What I typed:

```
bash <(curl https://nixos.org/nix/install)
. /home/dhp/.nix-profile/etc/profile.d/nix.sh
nix-env -i firefox
```

Result:

```
Unfortunately, we cannot download file jdk-8u144-linux-x64.tar.gz automatically.
Please go to http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html to download it yourself, and add it to the Nix store
using either
  nix-store --add-fixed sha256 jdk-8u144-linux-x64.tar.gz
or
  nix-prefetch-url --type sha256 file:///path/to/jdk-8u144-linux-x64.tar.gz
```

I hate this problem, but, I know Oracle is very boring about direct download, and nobody ever could workaround this legal issue (especially, I also have it in Gentoo). So, let's hope my old version of Firefox still functions, let's hope that on fresh install it's possible to either use an other browser to download the file, or have a light Firefox to download this dep. => needing a browser to install a browser can quickly become an egg-chicken issue.

The big issue I have met here is that, as of today, october 23rd 2017, the given link to oracle website only offers me SDK 151 and 152; what means, if I download them ... nix-store won't be able to put the file where it's expected, and the dep will remain unsatisfied.

Several solutions:
- find a way to provide a link that would directly point to the good SDK version
- tell if any recent version will do (otherwise, I will assume that non matching number will break the dep, and, I will assume that version 151 will NOT satisfy the need for jdk-8u144-linux-x64.tar.gz
- can't find any other alternative for this issue :/

**Comment by copumpkin** [comment]
This bug probably belongs against https://github.com/nixos/nixpkgs, not nix (which is the package manager tool itself; imagine filing this bug against the rpm/yum bug tracker rather than Red Hat/Centos trackers)

On the specific: It sounds like firefox at some point started depending on oraclejdk, which seems undesirable.

**Comment by doublehp** [comment]
As you wish.

https://github.com/NixOS/nixpkgs/issues/30735
