### ISSUE TITLE
Improve search feature on Nix 1.12

### ISSUE THREAD

**Issue by Ma27** [NixOS/nix#1634]
I just installed Nix 1.12 (`1.12pre5663_c7af84ce`) during your talk on NixCon today :-D
I'm really impressed, however there's one thing I'd like to improve before the stable release.

Before Nix 1.12 I used to run `nox <search-term>` to find a package name. When I compare the results, I currently think that `nox` does its job better:

- the order of `nix search` is a bit confusing. When I run `nix search jq`, the first package I get is `nixpkgs.jquery_ui` although there's a derivation in the nixpkgs package set named `jq` which is the first result in `nox jq` as well.

- `nox` does a better job at displaying the actual search result. It uses bold texts for derivation names and outputs the results in a more compact way. I'm not sure how to change the output of `nix search` yet, but I'm open for a discussion here.

Due to personal limitations I won't be able to join the hackathon, however I'd give it a try in the next weeks :-)

**Comment by davidak** [comment]
A little more intelligent search algorithm would be nice. I'm sure that already exists and only has to be used...

**Comment by Ma27** [comment]
see #1649

**Comment by Ma27** [comment]
@vcunat @shlevy as you stated in #1649 you'd like to "think about better sorting algorithms separately".
Could you elaborate what you have in mind? I'd love to file another patch to improve the stuff I started, however I'm not entirely sure what you'd like to see in the end %)

**Comment by vcunat** [comment]
I suspect it won't be easy to get a good sorting criterion.  Many also wouldn't be implementable simply as a different comparator for the map (if that's what was meant by the separation), as ATM it's just `string -> string`.

**Comment by Ma27** [comment]
understood, so ATM it's the best option to keep the search algorithm as-is, right?

The second feature I requested is improved colorization as I think that results from `nox` are way easier to read. I'm not exactly sure when, but if you're fine with it I'd just file a patch in the next time so we can actually discuss about this based on a simple proposal :-)

**Comment by Ma27** [comment]
@vcunat after #2158 is merged, are you happy with the current state of `nix search` or is there anything I've forgotten? Otherwise I'd close thi sissue %)
