### ISSUE TITLE
error: cannot rename package-search.json, No such file or directory

### ISSUE THREAD

**Issue by davidak** [NixOS/nix#1635]
I just did an update of Nix to the latest version from unstable channel and noticed this error.

It happens everytime i run `nix search` or with argument:

```
$ nix search jq
[...]
error: cannot rename '/home/davidak/.cache/nix/package-search.json.tmp.29746' to '/home/davidak/.cache/nix/package-search.json': No such file or directory
```

After several runs `/home/davidak/.cache/nix/package-search.json` stil not exists.

---

nix (Nix) 1.12pre5663_c7af84ce
Nixpkgs 18.03pre118668.0e4be9e5f0 (unstable)
elementary OS 0.4.1 Loki (based on Ubuntu 16.04.2 LTS)
Linux Kernel 4.10.0-37-generic

**Comment by davidak** [comment]
After executing some commands i can't reproduce it anymore. So maybe something of that solved it.

```
  722  nix channel
  723  nix-channel --list
  724  echo -e "* System: NixOS $(nixos-version)\n* Nix version: $(nix-env --version)\n* Nixpkgs version: $(nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion)\n* Sandboxing enabled: $(grep build-use-sandbox /etc/nix/nix.conf)"
  725  nix build --help
  726  nix search yout
  727  nix build nixpkgs.youtube-dl
  728  nix build youtube-dl
  729  nix build nixpkgs.youtube-dl --json
  730  nix search jq --json
  731  nix search --json
  732  nix search
  733  history
```

Could `--json` have such an effect?

**Comment by Ma27** [comment]
can confirm this.
A workaround for me was to run `mkdir ~/.cache/nix`

**Comment by unode** [comment]
> A workaround for me was to run mkdir ~/.cache/nix

Same here. `~/.cache` can be a volatile location so there's no guarantee that the folder will exist.
