### ISSUE TITLE
download-from-binary-cache.pl: honor NIX_CURL_FLAGS environment variable

### ISSUE THREAD

**Issue by iblech** [NixOS/nix#1636]
In trying to beautify the output of `nixos-rebuild switch`, I wanted to pass the `--progress` option to curl. [fetchurl supports a NIX_CURL_FLAGS environment variable](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/fetchurl/default.nix) which I could use for that purpose.

Unfortunately, download-from-binary-cache.pl doesn't honor that variable. To be more precise, it doesn't pass the contents of that environment variable to curl.

I tried fixing this, by adding `$ENV{NIX_CURL_FLAGS}` to the `system` call in download-from-binary-cache.pl. However, this didn't work, Perl warns about an undefined value. The environment gets scrubbed somewhere along the way.

I'd like to look into that problem a little more in a couple of days. Am I on the right track?

**Comment by iblech** [comment]
I'm the original author of this issue, and I can confirm that it is no longer relevant, that is, the issue had been solved (using other means) in the meantime :-)

**Comment by JohnAZoidberg** [comment]
> using other means

What do you mean? How did you solve your issue?
