### ISSUE TITLE
Create augeas lexical rules for editing nix expression

### ISSUE THREAD

**Issue by offlinehacker** [NixOS/nix#165]
Wouldn't it be awesome if you could edit nix expressions using augeas API, then it would be possible to update some derivations automatically if they pass tests and don't break any other package.

Has anybody done something like this before? Is something like this even sane and possible? Is there any lexical description of nix expression that could assist me in creation of augeas rules?

**Comment by edolstra** [comment]
Closing on account of age, also not clear whether this is really a good idea.
