### ISSUE TITLE
Update builtins documentation in Nix Manual

### ISSUE THREAD

**Issue by LisannaAtHome** [NixOS/nix#1653]
The Nix manual does not contain a full listing of all the builtin functions (https://nixos.org/nix/manual/#ssec-builtins). For example, concatStringsSep is not listed.

**Comment by bjornfor** [comment]
Doesn't concatStringsSep come from nixpkgs lib?

**Comment by zimbatm** [comment]
@bjornfor it's re-exported by nixpkgs but is actually a builtins

**Comment by chris-martin** [comment]
The 2015-09-03 release notes say `concatStringsSep` used to be in nixpkgs but was made a builtin for efficiency.

**Comment by fricklerhandwerk** [comment]
Built-in functions and with https://github.com/NixOS/nix/pull/8330 also built-in constants are documented automatically.
