### ISSUE TITLE
Weird behavior with nix 1.12 and IFD

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#1661]
This might be expected behavior but it confused me:

repro.nix:

```nix
rec {
  outer = import <nixpkgs> {};
  pkgs = import (outer.fetchFromGitHub {
    owner  = "NixOS";
    repo   = "nixpkgs";
    rev    = "90e78aafadba43f9ec1190d9411720d561f1e09b";
    sha256 = "1zyf2b7m0id2ihka5dn6nnvdzwbh6p3m98198l0gyrv8616c5daq";
  }) {};

  path = pkgs.path;

  # Note that this "${pkgs.path}/..." is going to copy the result into the store like a path reference again...
  evalConfig  = import "${pkgs.path}/nixos/lib/eval-config.nix";

  out = evalConfig {
    modules = [ (pkgs.path + /nixos/modules/virtualisation/amazon-image.nix) ];
  };

  topLevel = out.config.system.build.toplevel;
}
```

repro.sh:

```bash
#!/usr/bin/env nix-shell
#!nix-shell -i bash -p nixUnstable

# Force nix to realize the IFD derivation since it doesn't like to when running with a custom store
nix-build --no-out-link repro.nix -A pkgs.hello

STORE_PATH="$(mktemp -d)"
STORE_URI="local?root=$STORE_PATH&require-sigs=false"

nix copy --to "$STORE_URI" /nix/store/lfcki0xb6bd0c3cx223qnflwdcryk1ik-nixpkgs-90e78aafadba43f9ec1190d9411720d561f1e09b-src

export NIX_REMOTE="$STORE_URI"

nix-build repro.nix -A topLevel
```

If you run that script, it should produce the following error message:

```
error: getting status of ‘/nix/store/1mdv77cv4mfg19f9cyzrw8jccb0bydbg-lfcki0xb6bd0c3cx223qnflwdcryk1ik-nixpkgs-90e78aafadba43f9ec1190d9411720d561f1e09b-src/nixos/lib/eval-config.nix’: No such file or directory
```

You'll note a couple of things: it actually ingested the same path into the store twice, once as a normal fixed-output derivation (the `fetchFromGitHub`) and the second time, it copied the entire thing into the store again as if it was a path reference. This arises because of my `import "${pkgs.path}/nixos/lib/eval-config.nix"` which could easily be written with `pkgs.path + /nixos/lib/eval-config.nix` but I didn't think they'd behave any differently in this case so it was confusing.

The second thing is obviously that it fails, even though I'd expect it to succeed. Even though for whatever reason it wants to copy the store path into the store again (as you can see from the error message), it doesn't actually copy it, so then it fails with the error you see. I don't think it's in read-only mode because the IFD above worked, but this time for whatever reason it didn't bother realizing that path.

@edolstra any idea what's going on with those two issues?

P.S: my version is nix-env (Nix) 1.12pre5511_c94f3d55. Everything else is locked down in the repro.

**Comment by roberth** [comment]
I believe an interaction between the evaluator and `--store`/`NIX_REMOTE` has been fixed around the time of 2.3 until 2.9.
Please open a new issue if you encounter something like this again.
