### ISSUE TITLE
nix-shell 1.12 (or nix run) can't take drv as argument anymore

### ISSUE THREAD

**Issue by regnat** [NixOS/nix#1663]
`nix-shell` had the undocumented but nice feature of being able to be called with directly a drv file as argument. The new version of the tool isn't able to do this anymore, which removes some usages and breaks some workflows

**Comment by zimbatm** [comment]
The main use-case is something like https://github.com/direnv/direnv/wiki/Nix#persistent-shell where the .drv is added as a new GC root. This allows to reload the same nix-shell environment even if the input files have changed side, like the nix-channel being updated.
