### ISSUE TITLE
Enhancement: garbage collect based on age

### ISSUE THREAD

**Issue by LisannaAtHome** [NixOS/nix#1680]
The idea of "collecting garbage" is to delete things which aren't useful anymore, i.e., aren't likely to be used.  The most direct heuristic for this is how long it's been since the last time something was used.  For outputs that have no references (i.e., candidates for garbage collection), the ones that are used frequently (in builds) are less useful to garbage collect than the ones that haven't been used in a long time.  So it seems logical that keeping track of the "age" of reference-less entries in the Nix store would be useful for implementing an option like:
<pre>
gc-keep-recent = true|false
gc-recent = (time)
</pre>
As a developer, I would personally find this very useful, and I'm sure others would as well.

**Comment by edolstra** [comment]
Nix once had this feature but it was removed: 8824d60fe549e2fc9b5a852fc1b967eca241ea77

**Comment by copumpkin** [comment]
We could probably maintain times in the database rather than atimes. But I don't know if that causes a bunch of other annoyances.

**Comment by edolstra** [comment]
Yeah, it would mean that every evaluation causes a huge number of upserts in the database. Though I guess that could be done asynchronously.

**Comment by ledettwy** [comment]
But doesn't NixOS still have relatime? Isn't that good enough?

**Comment by bjornfor** [comment]
:cry:
