### ISSUE TITLE
error: derivation ‘/nix/store/xfzsgd0g6bzak43mndw1z8953bgny7sy-aeson-1.1.2.0.drv’ may not be deterministic: output ‘/nix/store/z07gd9fvzr65vp65yjqypldp3zvxar32-aeson-1.1.2.0’ differs

### ISSUE THREAD

**Issue by tanzeelrana** [NixOS/nix#1695]
nix-build -A haskellPackages.aeson --check

Missing documentation for:
    encode (Data/Aeson/Encode.hs:24)
    encodeToTextBuilder (Data/Aeson/Encode.hs:28)
 100% ( 25 / 25) in 'Data.Aeson.TH'
Warning: Data.Aeson.Types: could not find link destinations for:
    CoerceText AllNullary ParseSum FromProduct ProductSize ConsFromJSON SumToJSON WriteProduct ConsToJSON SumToEncoding EncodeProduct ConsToEncoding
Warning: Data.Aeson: could not find link destinations for:
    CoerceText AllNullary ParseSum FromProduct ProductSize ConsFromJSON SumToJSON WriteProduct ConsToJSON SumToEncoding EncodeProduct ConsToEncoding
Warning: Data.Aeson.TH: could not find link destinations for:
    StarKindStatus
Documentation created: dist/doc/html/aeson/index.html,
dist/doc/html/aeson/aeson.txt
installing
Installing library in
/nix/store/1f0ydvha6sf0aaassdyvnwa5g6vk0v0m-aeson-1.1.2.0/lib/ghc-8.0.2/aeson-1.1.2.0
Creating package registration file:
/nix/store/1f0ydvha6sf0aaassdyvnwa5g6vk0v0m-aeson-1.1.2.0/lib/ghc-8.0.2/package.conf.d/aeson-1.1.2.0.conf
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/1f0ydvha6sf0aaassdyvnwa5g6vk0v0m-aeson-1.1.2.0
shrinking /nix/store/1f0ydvha6sf0aaassdyvnwa5g6vk0v0m-aeson-1.1.2.0/lib/ghc-8.0.2/x86_64-linux-ghc-8.0.2/libHSaeson-1.1.2.0-7Re5aZ6MrFBBjqn2gRS4FJ-ghc8.0.2.so
stripping (with flags -S) in /nix/store/1f0ydvha6sf0aaassdyvnwa5g6vk0v0m-aeson-1.1.2.0/lib 
patching script interpreter paths in /nix/store/1f0ydvha6sf0aaassdyvnwa5g6vk0v0m-aeson-1.1.2.0
checking for references to /tmp/nix-build-aeson-1.1.2.0.drv-0 in /nix/store/1f0ydvha6sf0aaassdyvnwa5g6vk0v0m-aeson-1.1.2.0...
shrinking RPATHs of ELF executables and libraries in /nix/store/1qdb93rd0rc6b4hz4gzzhcxdfammn8k7-aeson-1.1.2.0-doc
patching script interpreter paths in /nix/store/1qdb93rd0rc6b4hz4gzzhcxdfammn8k7-aeson-1.1.2.0-doc
checking for references to /tmp/nix-build-aeson-1.1.2.0.drv-0 in /nix/store/1qdb93rd0rc6b4hz4gzzhcxdfammn8k7-aeson-1.1.2.0-doc...
warning: rewriting hashes in ‘/nix/store/dy6fgcgjabf9akc7wkb9pna4nrzjd8ci-aeson-1.1.2.0-doc’; cross fingers
warning: rewriting hashes in ‘/nix/store/z07gd9fvzr65vp65yjqypldp3zvxar32-aeson-1.1.2.0’; cross fingers
error: derivation ‘/nix/store/xfzsgd0g6bzak43mndw1z8953bgny7sy-aeson-1.1.2.0.drv’ may not be deterministic: output ‘/nix/store/z07gd9fvzr65vp65yjqypldp3zvxar32-aeson-1.1.2.0’ differs

**Comment by vcunat** [comment]
Such impurities are almost never a "mistake" in nix itself but in nixpkgs (or upstream).

**Comment by tanzeelrana** [comment]
hmm....any advise ?
I dont mind installing a new OS and doing everything from scratch

**Comment by vcunat** [comment]
By that I meant that the issue https://github.com/NixOS/nixpkgs/issues/31846 should be enough to track this problem.

**Comment by tanzeelrana** [comment]
Aha, I thought it was a different issue. In that case we can reject or close this issue i guess. However you deem fit :)

**Comment by vcunat** [comment]
It might actually be a different issue (I don't know), but it belongs to NixOS/nixpkgs anyway.

**Comment by domenkozar** [comment]
Binary determinism is a "nice to have" feature.
