### ISSUE TITLE
Need option to always build fixed-output derivation for testing

### ISSUE THREAD

**Issue by ThomasMader** [NixOS/nix#1696]
To run tests outside of the sandbox I use a fixed-output derivation.
See the phobosUnittests derivation in https://github.com/ThomasMader/nixpkgs/blob/6e15600b065dfae9c30d6a946ed84b2ba7a334a4/pkgs/development/compilers/dmd/default.nix
This works except that fixed-output derivations are not executed again if they already exist.
But obviously I need the tests to always run if the dependencies change.
I don't see any workarounds for now.

cc @Profpatsch because he seems to be working on the testing capabilities within nixpkgs. (http://profpatsch.de/talks/nix/nixpkgs-tests/#/sec-title-slide)

Also discussed at: https://groups.google.com/forum/#!topic/nix-devel/Q5gYy88ukvE

**Comment by knedlsepp** [comment]
What are the benefits of using a fixed-output derivation for tests? Why don't you simply use a regular one?

**Comment by shlevy** [comment]
I'd like to know the answer to @knedlsepp's question as well, but one hacky way to do this is to do `builtins.hashString "sha256" (toString builtins.currentTime)` to get the hash and then do `echo $builtins.currentTime > $out` after your tests pass.

**Comment by shlevy** [comment]
Or, if instead of "run every time" you want "run when deps change" you can do `builtins.hashString` on some combination of the dependencies (you may need `unsafeDiscardStringContext` as well)

**Comment by shlevy** [comment]
Ah, I see, you use networking in your tests. I'll see if I can't come up with a PR to phobosUnittests to fix this.

**Comment by Profpatsch** [comment]
Once you don’t use networking (which is pretty … interesting for unit tests to say the least), you can use the `withTests` function. I’m not yet ready to submit a PR, but the basics are these two commits:
https://gitlab.techcultivation.org/Profpatsch/nixpkgs-techcultivation/commit/657952813a7af2bbc8d7cc59ceb2d94dbf001ea2
https://gitlab.techcultivation.org/Profpatsch/nixpkgs-techcultivation/commit/f8e34e277629265b1e385881f2ac41a1cf714508

**Comment by ThomasMader** [comment]
> Once you don’t use networking (which is pretty … interesting for unit tests to say the least), you can use the withTests function. I’m not yet ready to submit a PR, but the basics are these two commits:

Thanks for pointing me to your withTests implementation, wasn't able to find it.

Well that's the unittests of the standard library of the D programming language and there are only simple loopback tests. But they fail in sandbox mode.
E.g.: socket.gethostbyaddr('127.0.0.1') is failing which basically is the call to the C library (netdb.h) implementation.

**Comment by ThomasMader** [comment]
Big Thanks to @shlevy for implementing the solution to my problem.

**Comment by Profpatsch** [comment]
> E.g.: socket.gethostbyaddr('127.0.0.1') is failing which basically is the call to the C library (netdb.h) implementation.

Ah, you *can* run stuff in VMs inside the build. See `pkgs/build-support/vm/default.nix` (e.g. the `runInLinuxVM` function) and for an example of usage `pkgs/build-support/docker/default.nix`, the `runWithOverlay` function.
