### ISSUE TITLE
Opt-out of hard-linking on a per-file basis

### ISSUE THREAD

**Issue by srhb** [NixOS/nix#1715]
I've bumped into a piece of proprietary software that refuses to execute if the link counter on itself indicates that it has hard links. It would be useful to be able to make a file exempt from store optimization.

**Comment by shlevy** [comment]
Out of curiosity, do you know of any plausible reason why this check would exist? It seems very bizarre to me.

**Comment by srhb** [comment]
@shlevy Nope, none at all, it seems completely bizarre. I initially considered patching in a version of stat that returns a bogus link count, but then realized that this application actually _does_ use the link counter sensibly for other things.

**Comment by bjornfor** [comment]
You could make the bogus stat conditional on the file path/name, perhaps?

**Comment by srhb** [comment]
@bjornfor I will give that a try, thanks. I can close this issue if it's essentially wontfix. I understand if there's a reluctance to add workarounds for such a unique case of poorly behaving executables.
