### ISSUE TITLE
v1.11.15 install fails on macOS 10.12

### ISSUE THREAD

**Issue by shawnohare** [NixOS/nix#1727]
I have previously installed 1.11.15 on macOS 10.12 on a different machine, but today encountered:

```
downloading Nix 1.11.15 binary tarball for x86_64-darwin from 'https://nixos.org/releases/nix/nix-1.11.15/nix-1.11.15-x86_64-darwin.tar.bz2' to '/var/folders/40/wjtbb7hd3mqb17r69q9ym0sm0000gq/T/nix-binary-tarball-unpack.XXXXXXXXXX.AU8YW7Yx'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 25.8M  100 25.8M    0     0  2708k      0  0:00:09  0:00:09 --:--:-- 3269k
Switching to the Multi-User Darwin Installer
Welcome to the Multi-User Nix Installation

This installation tool will set up your computer with the Nix package
manager. This will happen in a few stages:

1. Make sure your computer doesn't already have Nix. If it does, I
   will show you instructions on how to clean up your old one.

2. Show you what we are going to install and where. Then we will ask
   if you are ready to continue.

3. Create the system users and groups that the Nix daemon uses to run
   builds.

4. Perform the basic installation of the Nix files daemon.

5. Configure your shell to import special Nix Profile files, so you
   can use Nix.

6. Start the Nix daemon.

Would you like to see a more detailed list of what we will do?
[y/n] y


We will:

 - make sure your computer doesn't already have Nix files
   (if it does, I  will tell you how to clean them up.)
 - create local users (see the list above for the users we'll make)
 - create a local group (nixbld)
 - install Nix in to /nix
 - create a configuration file in /etc/nix
 - set up the "default profile" by creating some Nix-related files in
   /var/root
 - back up /etc/profile to /etc/profile.backup-before-nix
 - update /etc/profile to include some Nix configuration
 - back up /etc/bashrc to /etc/bashrc.backup-before-nix
 - update /etc/bashrc to include some Nix configuration
 - back up /etc/zshrc to /etc/zshrc.backup-before-nix
 - update /etc/zshrc to include some Nix configuration
 - load and start a LaunchDaemon (at /Library/LaunchDaemons/org.nixos.nix-daemon.plist) for nix-daemon

Ready to continue?
[y/n] y


---- let's talk about sudo -----------------------------------------------------
This script is going to call sudo a lot. Every time we do, it'll
output exactly what it'll do, and why.

Just like this:

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo echo

to demonstrate how our sudo prompts look


This might look scary, but everything can be undone by running just a
few commands. We used to ask you to confirm each time sudo ran, but it
was too many times. Instead, I'll just ask you this one time:

Can we use sudo?
[y/n] y

Yay! Thanks! Let's get going!

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo test -e /var/root/.nix-defexpr

making sure that /var/root/.nix-defexpr doesn't exist

Password:
Sorry, try again.
Password:

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo test -e /var/root/.nix-channels

making sure that /var/root/.nix-channels doesn't exist


---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo test -e /var/root/.nix-profile

making sure that /var/root/.nix-profile doesn't exist


---- hardware report -----------------------------------------------------------
           Cores:	4

---- Nix config report ---------------------------------------------------------
        Temp Dir:	/var/folders/40/wjtbb7hd3mqb17r69q9ym0sm0000gq/T/tmp.XXXXXXXXXX.qEwcFVb1
        Nix Root:	/nix
     Build Users:	4
  Build Group ID:	30000
Build Group Name:	nixbld

build users:
    Username:	UID
     nixbld1:	30001
     nixbld2:	30002
     nixbld3:	30003
     nixbld4:	30004

Ready to continue?
[y/n] y


~~> Setting up the build group nixbld
            Exists:	Yes

~~> Setting up the build user nixbld1

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/sysadminctl -addUser -fullName Nix build user 1 -home /var/empty -UID 30001 -addUser nixbld1

Creating the Nix build user, nixbld1

2017-12-11 15:13:41.398 sysadminctl[9567:205406] Creating user record…
2017-12-11 15:13:42.012 sysadminctl[9567:205406] Assigning UID: 30001
2017-12-11 15:13:42.058 sysadminctl[9567:205406] Home directory is assigned (not created!) at /var/empty
           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld1 IsHidden 1

in order to make nixbld1 a hidden user

          IsHidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld1 UserShell /sbin/nologin

in order to prevent nixbld1 from logging in

   Logins Disabled:	Yes
  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld1 PrimaryGroupId 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld2

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/sysadminctl -addUser -fullName Nix build user 2 -home /var/empty -UID 30002 -addUser nixbld2

Creating the Nix build user, nixbld2

2017-12-11 15:13:42.419 sysadminctl[9601:205558] Creating user record…
2017-12-11 15:13:43.041 sysadminctl[9601:205558] Assigning UID: 30002
2017-12-11 15:13:43.086 sysadminctl[9601:205558] Home directory is assigned (not created!) at /var/empty
           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld2 IsHidden 1

in order to make nixbld2 a hidden user

          IsHidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld2 UserShell /sbin/nologin

in order to prevent nixbld2 from logging in

   Logins Disabled:	Yes
  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld2 PrimaryGroupId 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld3

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/sysadminctl -addUser -fullName Nix build user 3 -home /var/empty -UID 30003 -addUser nixbld3

Creating the Nix build user, nixbld3

2017-12-11 15:13:43.428 sysadminctl[9635:205665] Creating user record…
2017-12-11 15:13:44.043 sysadminctl[9635:205665] Assigning UID: 30003
2017-12-11 15:13:44.090 sysadminctl[9635:205665] Home directory is assigned (not created!) at /var/empty
           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld3 IsHidden 1

in order to make nixbld3 a hidden user

          IsHidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld3 UserShell /sbin/nologin

in order to prevent nixbld3 from logging in

   Logins Disabled:	Yes
  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld3 PrimaryGroupId 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld4

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/sysadminctl -addUser -fullName Nix build user 4 -home /var/empty -UID 30004 -addUser nixbld4

Creating the Nix build user, nixbld4

2017-12-11 15:13:44.453 sysadminctl[9669:205789] Creating user record…
2017-12-11 15:13:45.068 sysadminctl[9669:205789] Assigning UID: 30004
2017-12-11 15:13:45.118 sysadminctl[9669:205789] Home directory is assigned (not created!) at /var/empty
           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld4 IsHidden 1

in order to make nixbld4 a hidden user

          IsHidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld4 UserShell /sbin/nologin

in order to prevent nixbld4 from logging in

   Logins Disabled:	Yes
  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld4 PrimaryGroupId 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo mkdir -pv -m 0755 /nix /nix/var /nix/var/log /nix/var/log/nix /nix/var/log/nix/drvs /nix/var/nix /nix/var/nix/db /nix/var/nix/gcroots /nix/var/nix/profiles /nix/var/nix/temproots /nix/var/nix/userpool

to make the basic directory structure of Nix (part 1)


---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo mkdir -pv -m 1777 /nix/var/nix/gcroots/per-user /nix/var/nix/profiles/per-user

to make the basic directory structure of Nix (part 2)


---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo mkdir -pv -m 1775 /nix/store

to make the basic directory structure of Nix (part 3)


---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo chgrp nixbld /nix/store

to make the basic directory structure of Nix (part 4)


---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo mkdir -pv -m 0755 /nix/var/nix/profiles/per-user/root

to set up the root user's profile (part 1)


---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo mkdir -pv -m 0700 /var/root/.nix-defexpr

to set up the root user's profile (part 2)


---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo mkdir -pv -m 0555 /etc/nix

to place the default nix daemon configuration (part 1)


---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo install -m 0664 /var/folders/40/wjtbb7hd3mqb17r69q9ym0sm0000gq/T/tmp.XXXXXXXXXX.qEwcFVb1/.nix-channels /var/root/.nix-channels

to set up the default system channel (part 1)


---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo rsync -rlpt /var/folders/40/wjtbb7hd3mqb17r69q9ym0sm0000gq/T/nix-binary-tarball-unpack.XXXXXXXXXX.AU8YW7Yx/unpack/nix-1.11.15-x86_64-darwin/store/ /nix/store/

to copy the basic Nix files to the new store at /nix/store

      Alright! We have our first nix at /nix/store/dgwz3dxdzs2wwd7pg7cdhvl8rv0qpnbj-nix-1.11.15

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /nix/store/dgwz3dxdzs2wwd7pg7cdhvl8rv0qpnbj-nix-1.11.15/bin/nix-store --init

to initialize the Nix Database


---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /nix/store/dgwz3dxdzs2wwd7pg7cdhvl8rv0qpnbj-nix-1.11.15/bin/nix-store --load-db

to load data for the first time in to the Nix Database

      Just finished getting the nix database ready.

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo cp /etc/profile /etc/profile.backup-before-nix

to back up your current /etc/profile to /etc/profile.backup-before-nix


---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo tee -a /etc/profile

extend your /etc/profile with nix-daemon settings


# Nix
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
# End Nix


---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo cp /etc/bashrc /etc/bashrc.backup-before-nix

to back up your current /etc/bashrc to /etc/bashrc.backup-before-nix


---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo tee -a /etc/bashrc

extend your /etc/bashrc with nix-daemon settings


# Nix
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
# End Nix


---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo cp /etc/zshrc /etc/zshrc.backup-before-nix

to back up your current /etc/zshrc to /etc/zshrc.backup-before-nix


---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo tee -a /etc/zshrc

extend your /etc/zshrc with nix-daemon settings


# Nix
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
# End Nix


---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo -i /nix/store/dgwz3dxdzs2wwd7pg7cdhvl8rv0qpnbj-nix-1.11.15/bin/nix-env -i /nix/store/dgwz3dxdzs2wwd7pg7cdhvl8rv0qpnbj-nix-1.11.15

to installing a bootstrapping Nix in to the default Profile

sudo: /Users/xxxxx/.nix-profile/bin/zsh: command not found

---- oh no! --------------------------------------------------------------------
Jeeze, something went wrong. If you can take all the output and open
an issue, we'd love to fix the problem so nobody else has this issue.

:(

We'd love to help if you need it.

If you can, open an issue at https://github.com/nixos/nix/issues

Or feel free to contact the team,
 - on IRC #nixos on irc.freenode.net
 - on twitter @nixos_org
```

**Comment by AlexxNica** [comment]
The same thing is happening to me, except I don't receive any output after the message `to installing a bootstrapping Nix in to the default Profile`; after this, my Mac stops responding, and I have to force a restart manually (I've waited for about 5 minutes).

**Comment by shawnohare** [comment]
@AlexxNica I upgraded the machine in question to 10.3.2 and nix installed properly.

**Comment by AlexxNica** [comment]
I've been able to resolve the problem and install Nix (`nix-1.11.16-x86_64-darwin`) successfully doing the following (be aware that I do not know which step made it work):
1. Updated macOS to 10.13.2
2. Searched for and deleted everything related to Nix from the system, in my case those were (remember these could've been old ones and not from the the recent attempts):
<details>
<summary>Click to see the files found in the system</summary>
/usr/local/bin/nix-prefetch-url;
/usr/local/bin/nix-shell;
/usr/local/bin/nix-copy-closure;
/usr/local/bin/nix;
/usr/local/bin/nix-daemon;
/usr/local/bin/nix-channel;
/usr/local/bin/nix-collect-garbage;
/usr/local/bin/nix-env;
/usr/local/bin/nix-store;
/usr/local/bin/nix-build;
/usr/local/bin/nix-hash;
/usr/local/bin/nix-instantiate;
/usr/local/libexec/nix;
/usr/local/include/nix;
/usr/local/include/nix/nixexpr.hh;
/usr/local/etc/profile.d/nix-daemon.sh;
/usr/local/etc/profile.d/nix.sh;
/usr/local/var/homebrew/locks/nix--1.11.15.tar.bz2.incomplete.lock;
/usr/local/Library/LaunchDaemons/org.nixos.nix-daemon.plist;
/usr/local/lib/pkgconfig/nix-store.pc;
/usr/local/lib/pkgconfig/nix-main.pc;
/usr/local/lib/pkgconfig/nix-expr.pc;
/usr/local/lib/libnixexpr.dylib;
/usr/local/lib/libnixformat.dylib;
/usr/local/lib/libnixutil.dylib;
/usr/local/share/man/man5/nix.conf.5;
/usr/local/share/man/man8/nix-daemon.8;
/usr/local/share/man/man1/nix-channel.1;
/usr/local/share/man/man1/nix-store.1;
/usr/local/share/man/man1/nix-prefetch-url.1;
/usr/local/share/man/man1/nix-hash.1;
/usr/local/share/man/man1/nix-env.1;
/usr/local/share/man/man1/nix-collect-garbage.1;
/usr/local/share/man/man1/nix-copy-closure.1;
/usr/local/share/man/man1/nix-instantiate.1;
/usr/local/share/man/man1/nix-shell.1;
/usr/local/share/man/man1/nix-build.1;
/usr/local/share/nix;
/usr/local/share/nix/corepkgs/buildenv.nix;
/usr/local/share/nix/corepkgs/unpack-channel.nix;
/usr/local/share/nix/corepkgs/config.nix;
/usr/local/share/nix/corepkgs/derivation.nix;
/usr/local/share/nix/corepkgs/imported-drv-to-derivation.nix;
/usr/local/share/nix/corepkgs/fetchurl.nix;
/usr/local/share/doc/nix;
/private/etc/apache2/users/nixbld3.conf;
/private/etc/apache2/users/nixbld2.conf;
/private/etc/apache2/users/nixbld4.conf;
/private/etc/apache2/users/nixbld1.conf;
/private/var/db/dslocal/nodes/Default/groups/nixbld.plist;
/private/var/db/dslocal/nodes/Default/users/nixbld1.plist;
/private/var/db/dslocal/nodes/Default/users/nixbld3.plist;
/private/var/db/dslocal/nodes/Default/users/nixbld2.plist;
/private/var/db/dslocal/nodes/Default/users/nixbld4.plist;
</details>

3. Proceeded to a new install attempt.
4. Succeeded.

I found two diagnostic reports that have been created before I had success installing Nix, I'll post them but remember these could be from other things other than the recent attempts, and I tried installing directly from the source to get a better understanding of what was going on, so everything could be from anything.

<details>
<summary>Click to see the diagnostic log</summary>
Process:               nix-store [20432]
Path:                  /nix/*/nix-store
Identifier:            nix-store
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [20431]
Responsible:           nix-store [20432]
User ID:               0

Date/Time:             2017-12-12 05:52:08.659 -0200
OS Version:            Mac OS X 10.13.1 (17B1003)
Report Version:        12
Anonymous UUID:        FB6293E9-21DF-8671-D610-D0B0842EFA1A


Time Awake Since Boot: 19000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/lib/system/libsystem_coretls.dylib
  Referenced from: /nix/*/libSystem.B.dylib
  Reason: image not found

Binary Images:
       0x10d840000 -        0x10d858fff +nix-store (0) <09C20E4E-9C2B-3A0C-81F0-154AEE027133> /nix/*/nix-store
       0x10d869000 -        0x10d878ffb +libbz2.1.dylib (0) <8FADB434-1F72-33BF-B25C-863E61F8E8FA> /nix/*/libbz2.1.dylib
       0x10d87c000 -        0x10d8dffff +libsodium.18.dylib (0) <54225D6C-E66B-3AD3-93A9-F3B17A42FEF8> /nix/*/libsodium.18.dylib
       0x10d8ef000 -        0x10d8faff7 +libnixmain.dylib (0) <3988356F-F90E-3A63-9D7A-C17DDB46BC09> /nix/*/libnixmain.dylib
       0x10d909000 -        0x10d993ff7 +libnixstore.dylib (0) <C1C8D1CC-DBC4-333B-8150-1D143FE9E7B4> /nix/*/libnixstore.dylib
       0x10d9ca000 -        0x10d9e9ff7 +libnixutil.dylib (0) <ACB1E01A-C656-3D41-B143-35733B8B1642> /nix/*/libnixutil.dylib
       0x10da00000 -        0x10da06ff7 +libnixformat.dylib (0) <341870C4-B6F2-39F2-AA1B-2FF087C0BD83> /nix/*/libnixformat.dylib
       0x10da0e000 -        0x10da7dff3 +libc++.1.0.dylib (0) <6A28EC37-3A6D-3743-9B2C-4CCB4CACE0B3> /nix/*/libc++.1.0.dylib
       0x10dadb000 -        0x10dadbfff +libSystem.B.dylib (1226.10.1) <12CD84D8-B6E9-3901-AE95-A1039CFE2128> /nix/*/libSystem.B.dylib
       0x10dae3000 -        0x10dae3fff +libsystem_c.dylib (0) <936F37C7-8432-3908-8EAD-9D594E39377B> /nix/*/libsystem_c.dylib
       0x10dafb000 -        0x10dafbfff +libsystem_kernel.dylib (0) <C22CA1D6-45B5-39AD-9130-B3E9B05FFC63> /nix/*/libsystem_kernel.dylib
       0x10db17000 -        0x10db17fff +libSystem_internal.dylib (0) <F8C126C8-343F-3D21-B2C9-744A6E622003> /nix/*/libSystem_internal.dylib
       0x11ba80000 -        0x11baca98f  dyld (519.2.1) <CD85EFBA-B9D6-3FD5-B777-A23B2DDEF192> /usr/lib/dyld
    0x7fff5a135000 -     0x7fff5a139ff7  libcache.dylib (80) <354F3B7D-404E-3398-9EBF-65CA2CE65211> /usr/lib/system/libcache.dylib
    0x7fff5a13a000 -     0x7fff5a144ff3  libcommonCrypto.dylib (60118.1.1) <6C502A55-3B54-3B48-BA7B-FA39F56C0B1E> /usr/lib/system/libcommonCrypto.dylib
    0x7fff5a145000 -     0x7fff5a14cfff  libcompiler_rt.dylib (62) <4487CFBA-A5D7-3282-9E6B-94CAD7BE507E> /usr/lib/system/libcompiler_rt.dylib
    0x7fff5a14d000 -     0x7fff5a155fff  libcopyfile.dylib (146) <7E4BD264-5617-339B-AC73-E8D07EF2C51D> /usr/lib/system/libcopyfile.dylib
    0x7fff5a156000 -     0x7fff5a1daff7  libcorecrypto.dylib (562) <7974762C-DEF7-3056-9856-9821C27846DB> /usr/lib/system/libcorecrypto.dylib
    0x7fff5a261000 -     0x7fff5a29aff7  libdispatch.dylib (913.20.5) <389EBBCD-3AA2-3340-AA48-4FBF621401BD> /usr/lib/system/libdispatch.dylib
    0x7fff5a29b000 -     0x7fff5a2b8ff7  libdyld.dylib (519.2.1) <2597D818-42D2-3375-BD9D-451D5942A6BA> /usr/lib/system/libdyld.dylib
    0x7fff5a2b9000 -     0x7fff5a2b9ffb  libkeymgr.dylib (28) <6D84A96F-C65B-38EC-BDB5-21FD2C97E7B2> /usr/lib/system/libkeymgr.dylib
    0x7fff5a2c7000 -     0x7fff5a2c7ff7  liblaunch.dylib (1205.20.31) <0089D38D-868D-3748-A032-934AAE679F0D> /usr/lib/system/liblaunch.dylib
    0x7fff5a2c8000 -     0x7fff5a2ccffb  libmacho.dylib (900.0.1) <756F2553-07B6-3B42-ACEA-2F0F1A5E8D0F> /usr/lib/system/libmacho.dylib
    0x7fff5a2cd000 -     0x7fff5a2cfff3  libquarantine.dylib (86) <6AC8773F-3817-3D82-99C2-01BABB9C3CBB> /usr/lib/system/libquarantine.dylib
    0x7fff5a2d0000 -     0x7fff5a2d1ff3  libremovefile.dylib (45) <912FA211-DD8C-3C92-8424-21B89F8B10FD> /usr/lib/system/libremovefile.dylib
    0x7fff5a2d2000 -     0x7fff5a2e9fff  libsystem_asl.dylib (356.1.1) <94972913-9DF0-3C78-847C-43E58919E3DA> /usr/lib/system/libsystem_asl.dylib
    0x7fff5a2ea000 -     0x7fff5a2eafff  libsystem_blocks.dylib (67) <F2493BB5-B1C6-3C4D-9F1F-1B402E0F1DB7> /usr/lib/system/libsystem_blocks.dylib
    0x7fff5a375000 -     0x7fff5a378ffb  libsystem_configuration.dylib (963) <D7EFEAE6-22A0-348E-BBBE-44FFD41934FA> /usr/lib/system/libsystem_configuration.dylib
    0x7fff5a379000 -     0x7fff5a37cffb  libsystem_coreservices.dylib (51) <21A488D0-2D07-344E-8631-CC8B2A246F35> /usr/lib/system/libsystem_coreservices.dylib
</details>

Now, I do not know what has caused the installation to succeed, and I can't tell if the error is still happening in versions preceding 10.13.2, we may have to check that to be sure no one's getting frustrated.

**Comment by shawnohare** [comment]
It could be a very isolated issue. I'll leave the issue open for awhile longer in case it benefits anyone else.

**Comment by morenoh149** [comment]
For me upgrading to High Sierra may or may not have worked. I was able to run `nix-shell -p nix-info --run "nix-info -m"` after sourcing `source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh`. However it isn't sourced in new terminals so I had to add that explicitly to my .bash_profile

**Comment by abathur** [comment]
I think this can probably be closed at this point :)
