### ISSUE TITLE
store path literals are copied to the store again

### ISSUE THREAD

**Issue by LnL7** [NixOS/nix#1728]
I would expect this to return the same path as a string (with context), since it's in the store already.

```
$ nix repl
nix-repl> "${/nix/store/6vjwsyv4il8f9jm3wylbzmbbsa70qc33-hello-2.10}"'
"/nix/store/gwr8dyg7fzvb7lrq3q5jm9bgnmpw0rqb-6vjwsyv4il8f9jm3wylbzmbbsa70qc33-hello-2.10"
```

**Comment by shlevy** [comment]
This is what `buildins.storePath` is for.

**Comment by copumpkin** [comment]
I get what you're saying, @shlevy, but why is this behavior ever desirable?

**Comment by shlevy** [comment]
I've wanted the double copy behavior before. Not with a top-level store path, admittedly, but with files within a store path. E.g. to get the same output whether building a project from a local checkout or an in-store checkout

**Comment by shlevy** [comment]
Also, it's a bit of a hacky special case *not* to do this

**Comment by LnL7** [comment]
FWIW `store->isStorePath` already returns false for subpaths.
I don't think #1731 is that much of a hack. 😄
