### ISSUE TITLE
For remote builds, don't copy the entire derivation closure

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#173]
When we do remote builds, the remote machine only needs the top-level derivation and its inputs. It doesn't need any other paths in the closure of the derivation. In particular, if x.drv depends on y.drv, and y.drv depends on big-source-file, we shouldn't copy y.drv and big-source-file.  However, currently we *have* to copy those to preserve closure invariant. It would be nice if Nix had a mode to build directly from a .drv file.

**Comment by copumpkin** [comment]
Would changing the hashing scheme be particularly disruptive? It seems like it would invalidate old binary caches, but would otherwise be fairly harmless. Am I missing something?
