### ISSUE TITLE
strange code

### ISSUE THREAD

**Issue by volth** [NixOS/nix#1730]
This seems to be a problematic code, ```forceString``` is a method name:

https://github.com/NixOS/nix/blob/812e027e1d5a4f83394069edd67bdf8404ffa2bb/src/libexpr/eval.cc#L1291

**Comment by shlevy** [comment]
!!!

**Comment by shlevy** [comment]
Oh, no, `forceString` is a member of `ExprConcatStrings`, it's shorthand for `this->forceString`
