### ISSUE TITLE
Crash with large emacsWithPackages expression and myEnvFun

### ISSUE THREAD

**Issue by jwiegley** [NixOS/nix#1733]
I'm using nix-env (Nix) 1.11.16 on macOS 10.12.6, and nixpkgs commit 7de78d3efc865a1941f8f2264580a95f102d8d63.

I'm trying to build an environment containing all of the Emacs packages I use that are available in Nix:

  https://gist.github.com/jwiegley/b76c5460871b11c63c72e678001cb15d

Then I run:

```
nix-build crash.nix
```

This dies after some time (and reaching about 2GB resident memory) with:

```
$ nix-build crash.nix
nix-instantiate killed by signal 11
```

If you comment out enough packages in `crash.nix`, it will start working. It doesn't seem to matter which ones you comment out. Also, when this expression is located within the context of my full `config.nix`, I have to comment out more of them to trigger the bug.  Maybe hitting some sort of internal limit?

With `buildEnv` I cannot manifest the crash, and the command begins compiling packages almost immediately.

**Comment by matthewbauer** [comment]
Have you tried this on Nix 2.0? Running ```nix-build crash.nix``` with Nix 2.0 on my MacBook isn't crashing (it does take a long time though).

**Comment by jwiegley** [comment]
@matthewbauer I haven't been able to reproduce it with 1.12 either.
