### ISSUE TITLE
incorrect sha256 calculation

### ISSUE THREAD

**Issue by samunders-core** [NixOS/nix#1735]
Using nix installed into home directory (I am no root nor can be one) nix-env fails ?randomly? when installing packages. As an example I give https://github.com/NixOS/nixpkgs/commit/1a98fc40e9bbfe6bdf17930b5fa926b3f50e5d27#diff-8223e4a1cb8a4f9a818ccf4b2a88fdbb, which is most recent package (1hour old) as of writing this issue:
```shell
sam_@lighthouse ~ $ curl -Lo - https://github.com/NixOS/nixpkgs/raw/1a98fc40e9bbfe6bdf17930b5fa926b3f50e5d27/pkgs/applications/misc/ipmicfg/default.nix | grep sha256
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   197  100   197    0     0    197      0  0:00:01 --:--:--  0:00:01   386
100  1115  100  1115    0     0   1115      0  0:00:01 --:--:--  0:00:01  1115
    sha256 = "11xhzw36pg4has8857pypf44cni8m2mg8qsqi1s4bfjbxlfgxgwk";
```
```shell
sam_@lighthouse ~ $ nix-prefetch-url ftp://ftp.supermicro.com/utility/IPMICFG/IPMICFG_1.27.1_build.170901.zip
downloading ‘ftp://ftp.supermicro.com/utility/IPMICFG/IPMICFG_1.27.1_build.170901.zip’... [1284/1628 KiB, 195.3 KiB/s]
path is ‘/home/sam_/nix/store/zaslq21fb3g1mrrg7i6k4k4nqyrjfqmn-IPMICFG_1.27.1_build.170901.zip’
1mbia8m8dnlicslv8rx1h4s0wd0d0g4f7n56hzmavmkqii2ii5gg
```
Observe that sha256 hashes do not match with nix-prefetch-url and pkgs/applications/misc/ipmicfg/default.nix. I checked also sha256sum:
```shell
sam_@lighthouse ~ $ curl -Lo IPMICFG_1.27.1_build.170901.zip ftp://ftp.supermicro.com/utility/IPMICFG/IPMICFG_1.27.1_build.170901.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1628k  100 1628k    0     0   232k      0  0:00:07  0:00:07 --:--:--  362k
```
```shell
sam_@lighthouse ~ $ sha256sum IPMICFG_1.27.1_build.170901.zip 
ef9518458c78d6adea87a6d8e3c8030d340e3481a167b4a96691da862a5271d5  IPMICFG_1.27.1_build.170901.zip
```

I'm not sure what you'd need to investigate, so for starters:
```shell
sam_@lighthouse ~ $ ls -lA | grep -i nix
drwxr-xr-x  4 sam_ users     4096 dec 13 23:19 nix
-rw-r--r--  1 sam_ users       97 dec 14 01:49 .nix-channels
drwxr-xr-x  2 sam_ users     4096 dec 14 01:53 .nix-defexpr
lrwxrwxrwx  1 sam_ users       38 dec 14 02:00 nixos -> /home/sam_/.nix-defexpr/channels/nixos
lrwxrwxrwx  1 sam_ users       40 dec 14 02:00 nixpkgs -> /home/sam_/.nix-defexpr/channels/nixpkgs
drwxr-xr-x  2 sam_ users     4096 dec 13 23:19 .nixpkgs
lrwxrwxrwx  1 sam_ users       39 dec 13 23:19 .nix-profile -> /home/sam_/nix/var/nix/profiles/default`
```
```shell
sam_@lighthouse ~ $ uname -a
Linux lighthouse 4.4.6-gentoo #1 SMP Wed Apr 27 08:41:20 CEST 2016 x86_64 Intel(R) Core(TM)2 Duo CPU E7300 @ 2.66GHz GenuineIntel GNU/Linux
```
```shell
sam_@lighthouse ~ $ /home/sam_/nix/store/hncqnv5xxl4sfzh22mj5h1kki5llx2p2-nix-1.11.15/bin/nix-prefetch-url --version
nix-prefetch-url (Nix) 1.11.15
```

**Comment by copumpkin** [comment]
The `nix-prefetch-url` output is in base32, not hex. You'll notice it has letters other than a-f in it, and is shorter. The two formats are interchangeable in most Nix contexts though.

**Comment by orivej** [comment]
Note that the expression uses `fetchzip`, not `fetchurl`: https://github.com/sorki/nixpkgs/blob/f605a8d642725dd6dc58671361307f9efb94cede/pkgs/applications/misc/ipmicfg/default.nix#L8-L12
It unpacks the archive and modifies the contents before calculating the hash.

**Comment by samunders-core** [comment]
Both your statements are correct, I'm sorry for creating confusion by attaching output of sha256sum. Issue here is about 11xhzw36pg4has8857pypf44cni8m2mg8qsqi1s4bfjbxlfgxgwk being expected while nix-prefetch-url reports 1mbia8m8dnlicslv8rx1h4s0wd0d0g4f7n56hzmavmkqii2ii5gg. Shouldn't those 2 be the same provided file contents haven't changed (no change assumption is based on commit being no older than 1 hour and expectation that author of nix expression obtained sha256 hash the same way)?

**Comment by orivej** [comment]
`nix-prefetch-url` outputs the hash compatible with `fetchurl`. `nix-prefetch-url --unpack` outputs the hash compatible with `fetchzip`. ``nix-prefetch-url -A` selects whether to unpack or not based on the original expression, and the result is expected:
```
$ nix-prefetch-url '<nixpkgs>' -A ipmicfg.src                                                                                                                                                      ~
downloading ‘ftp://ftp.supermicro.com/utility/IPMICFG/IPMICFG_1.27.1_build.170901.zip’... [1524/1628 KiB, 103.2 KiB/s]
unpacking...
path is ‘/nix/store/s1vdq9frxx621gg11233dds5bqq1nqrl-source’
11xhzw36pg4has8857pypf44cni8m2mg8qsqi1s4bfjbxlfgxgwk
```
> expectation that author of nix expression obtained sha256 hash the same way
Often it is simpler to run the build with the wrong hash and copy the right one from the error message.

**Comment by samunders-core** [comment]
Thanks for clarification. There's no problem with ipmicfg package them. Actually my report was triggered by problems with fsharp-4.0.1.1 package: https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/fsharp/default.nix:
```shell
sam_@lighthouse ~ $ nix-prefetch-url https://github.com/fsharp/fsharp/archive/4.0.1.1.tar.gz
downloading ‘https://github.com/fsharp/fsharp/archive/4.0.1.1.tar.gz’... [0/0 Ki [34474/38555 KiB, 8524.3 KiB/s]
path is ‘/home/sam_/nix/store/phbd5xf45m67h69wc6hl96vx8wfsg39h-4.0.1.1.tar.gz’
17m2bkv7l2p8i0zmh1pqcvprwd88x28phcfkzcxv346pzvj7m3va
sam_@lighthouse ~ $
```
I have verified also few other versions:
```shell
nix-prefetch-url https://github.com/fsharp/fsharp/archive/4.0.0.4.tar.gz
downloading ‘https://github.com/fsharp/fsharp/archive/4.0.0.4.tar.gz’... [0/0 Ki [37679/0 KiB, 4811.3 KiB/s]
path is ‘/home/sam_/nix/store/rhry3hml79yhpny664dj1644qzkmpn8j-4.0.0.4.tar.gz’
0k3mq17bg1zcx62a8xdncdax2rdix8jcmqwbawgynzb6k1jd5m6c
```
According to https://github.com/NixOS/nixpkgs/commit/5b9de55c26434beae5d4e5f6062b35b46c4c3d95 and your explanation 1m9pwr4xjl3ikaf3pzsa4pb3pr533xa0v34y2cy4pjcc6j0f71av is expected here.
```shell
sam_@lighthouse ~ $ nix-prefetch-url https://github.com/fsharp/fsharp/archive/4.1.7.tar.gz
downloading ‘https://github.com/fsharp/fsharp/archive/4.1.7.tar.gz’... [0/0 KiB, [36864/0 KiB, 4571.7 KiB/s]
path is ‘/home/sam_/nix/store/l7f2slrz5kmpzsbx1fnd8ms1z4hxhg26-4.1.7.tar.gz’
0c9ij9242y2zxqdlr7bnrm471y1xbbmzqbipj94zig0a2yq7ib8v
sam_@lighthouse ~ $
```
Again mismatch, this time to to https://github.com/NixOS/nixpkgs/blob/a982b20c3601e5376aa6508b8cadc809b05542b8/pkgs/development/compilers/fsharp41/default.nix

How is it possible Hydra built those packages? https://hydra.nixos.org/job/nixos/nixup/nixpkgs.fsharp41.x86_64-linux

**Comment by samunders-core** [comment]
One more thing. How can I monkey-patch build which has said fsharp version as dependency? (assuming no bug in nix = devs of fsharp changing those releases 'behind curtains' and yet me believing no malice)

**Comment by orivej** [comment]
All occurrences of `fetchurl { url = "https://github.com/X/Y/archive/Z"; }` in Nixpkgs are incorrect because GitHub does not provide stable archives: only archive contents are the same. This is one of the reasons we have `fetchFromGitHub`. Such issues are usually fixed on a case by case basis (e.g. https://github.com/NixOS/nixpkgs/commit/30fa830633fb29c2cfb704bfe3fdbf76c168aa35), but I hope to fix them all soon. Often they do not cause issues on Hydra because it downloads sources once and subsequently uses the cached copy, and GitHub archives do not change all the time so Hydra has a good chance to download the same archive as the author of the expression.

N.B. Please report issues with Nixpkgs at https://github.com/NixOS/nixpkgs/issues

**Comment by orivej** [comment]
Note that users building from source also do not experience such issues because even sources are downloaded from Hydra cache (when available), not from GitHub.

**Comment by samunders-core** [comment]
Thank you for support, I managed to install/build fsharp with
```shell
    fsharp = pkgs.fsharp.overrideDerivation (oldAttrs: {
      src = pkgs.fetchurl {
        url = "https://github.com/fsharp/fsharp/archive/4.0.1.1.tar.gz";
        sha256 = "17m2bkv7l2p8i0zmh1pqcvprwd88x28phcfkzcxv346pzvj7m3va";
      };
    });
```
present in packageOverrides @ ~/.nixpkgs/config.nix. Continued to build other dependencies of mine only to hit another instance of same issue with dotnetPackages/RestSharp. Reported as https://github.com/NixOS/nixpkgs/issues/32780, just stressing that https://www.nuget.org/api/v2/package/RestSharp/105.2.3 was being fetched instead of github archives.

**Comment by snawaz** [comment]
`nix-hash` is what you probably need: https://www.mankier.com/1/nix-hash

Use this command to compute the sha256 to be used with `fetchurl` or such: 

```bash
$ nix-hash --flat --base32 --type sha256 your-file.zip
```
