### ISSUE TITLE
Any chance for supporting downloading and installing directly from a source repository?

### ISSUE THREAD

**Issue by ShadowCreator** [NixOS/nix#174]
Arch Linux has something shown [here](https://wiki.archlinux.org/index.php/VCS_PKGBUILD_Guidelines) where the package can pull directly from a repository and build it. 

This is useful for when you want the latest development version of something and you don't mind breakages or you want the latest graphic drives for gaming.

Is there any chance of this being somewhere on the roadmap?

**Comment by edolstra** [comment]
This is supported by `builtins.fetchGit` (which doesn't require specifying a hash).
