### ISSUE TITLE
Does not exist

### ISSUE THREAD

**Issue by mightymouse2045** [NixOS/nix#1744]
Hi I am trying to build Cardano-sl and it is failing to load the nix-shell with:

#nix-shell
`build input /nix/store/q8k7r5zbf03ydrpm7imfzds5b2nmdf0a-zlib-1.2.11-dev "......." /nix/store/15axh70yqanvivgi69ns8sx7cjydqdx3-pkg-config-0.29.2 does not exist`

There are quite a few more in the above and they all exist. Is there anyway I can troubleshoot this further to find out what's going on, or hopefully something obvious/easy that anyone knows to work around this?

**Comment by copumpkin** [comment]
This belongs under the nixpkgs tracker, not the Nix one. The Nix tracker is about the package manager itself, whereas nixpkgs is the repository of packages that the community maintains. There's also a lot more eyes over there than over here 😄

**Comment by orivej** [comment]
This might be a report about nix-shell… and cardano-sl is not part of Nixpkgs: https://github.com/input-output-hk/cardano-sl

**Comment by mightymouse2045** [comment]
Hi - yeah I think it is something to do with nix-shell hence the question here.... I have also raised the same question at cardano-sl tracker, something tells me it might be a config issue my side that is causing this, because I get the same error running nix-shell against other non-related packages
