### ISSUE TITLE
nixUnstable recommends use of --show-trace but this no longer works

### ISSUE THREAD

**Issue by bgamari** [NixOS/nix#1749]
When `nix build` encounters an error it helpfully suggests to `(use '--show-trace' to show detailed location information)`. However, this doesn't appear to work with the new `nix` command.

**Comment by bgamari** [comment]
@dtzWill recently added a `show-trace` option quite.

**Comment by dtzWill** [comment]
Commits:
* https://github.com/NixOS/nix/commit/75b9670df61b3e82e6d60a0572316fdacc9cbd91
* https://github.com/NixOS/nix/commit/cfeff3b2731fd7e6dd030d4e4d56ff3a3aeac903

Wasn't me (was @edolstra), just thought I'd mention it was at least an option now :).

**Comment by Ericson2314** [comment]
I'm more interested in what layer violation caused this error message than the error itself :D.

**Comment by Artturin** [comment]
`--show-trace` now works with the new cli
