### ISSUE TITLE
sqlite in wal mode has concurrency bugs

### ISSUE THREAD

**Issue by mornfall** [NixOS/nix#177]
when too many processes try to access a WAL-mode sqlite database at once, some of them fail like this:

```
error: adding reference to database: unable to open database file
```

(this means the database was already opened before by the same process; there may be races in access to the -wal and/or -shm files for all I can tell, or it might be a more involved problem deep in sqlite; cf. http://osdir.com/ml/sqlite-users/2013-10/msg00050.html)

PS: Since WAL can't be disabled due to #176, this makes nix nearly unusable with heavy parallel loads, as processes randomly die with database errors.

**Comment by edolstra** [comment]
Closing because this issue is apparently not seen recently.
