### ISSUE TITLE
lib.concatMap and lib.mapAttrs to be builtins

### ISSUE THREAD

**Issue by volth** [NixOS/nix#1776]
```concatMap``` and ```mapAttrs``` are the most often called library functions.
They could be straightforward implemented in C++ to speed up execution and to avoid generating temporary thunks.
With my nix expressions it saves about 20% of memory.

**Comment by copumpkin** [comment]
@volth does that mean you have an implementation ready?

**Comment by volth** [comment]
@copumpkin yes, but not against the mainline nix.

**Comment by volth** [comment]
It might be one of the simplest yet effective patch independent on other my patches.

Another one could be making ```null```, ```false```, ```true``` literals (similar to digits and strings) instead of vars. But that might break code of those who like to write ```let true = false; in ...```

**Comment by edolstra** [comment]
@volth Sounds good to me.
