### ISSUE TITLE
One Click Installation link in docs is broken.

### ISSUE THREAD

**Issue by beala** [NixOS/nix#1783]
From [Chapter 12: One Click Installation](https://nixos.org/nix/manual/#sec-one-click):

> For instance, you can go to http://hydra.nixos.org/jobset/nixpkgs/trunk/channel/latest and click on any link for the individual packages for your platform.

The link (http://hydra.nixos.org/jobset/nixpkgs/trunk/channel/latest) is broken.

![image](https://user-images.githubusercontent.com/455163/34653306-6e9dcd9c-f3a7-11e7-85c3-b56629150b72.png)

**Comment by vcunat** [comment]
This needs to be fixed in the manual.   For reference, hydra lists the output paths and you can easily get them from cache via `nix-store --realize /nix/store/xnyzwq1qhmjdjya5yln88i4vi8mf7pfx-bash-4.4-p12`.  (Or `nix build /nix/store/xnyzwq1qhmjdjya5yln88i4vi8mf7pfx-bash-4.4-p12` with nix-1.12.)

**Comment by beala** [comment]
Thanks @vcunat! Is there another link that supports the one click installation feature?

**Comment by vcunat** [comment]
I'm confident that none under `nixos.org` and I don't really know about "unofficial" instances.

**Comment by edolstra** [comment]
`nix-install-package` was removed in master a while ago (https://github.com/NixOS/nix/issues/831).
