### ISSUE TITLE
"hello package" example from the documentation is incomplete or wrong

### ISSUE THREAD

**Issue by djoerd** [NixOS/nix#1809]
When trying the "hello" example on:
  https://nixos.org/nix/manual/#chap-writing-nix-expressions

The documentation does not explain where to find the file:  pkgs/top-level/all-packages.nix ?

I find it here:

    /nix/store/8dzsdaqm0gk7r2ablrzradj0xhsq815g-nixpkgs-18.03pre122585.b212125b541/nixpkgs/pkgs/top-level/all-packages.nix

This is a read-only file, but I first edited it anyway (with sudo). I also tried first getting `nixpkgs` from github as follows:

    git clone --depth=1 'https://github.com/NixOS/nixpkgs.git'

(without depth=1, you hava to wait a very long time) and then edit the file here. In any case, adding the following to any or both files:

    rec {
    
      hello = import ../applications/misc/hello/ex-1 2 {
        inherit fetchurl stdenv perl;
      };

      perl = import ../development/interpreters/perl {
        inherit fetchurl stdenv;
      };

      fetchurl = import ../build-support/fetchurl {
        inherit stdenv; ...
      };
    
      stdenv = ...;
    
    }

Then the command:

    nix-build -A hello

gives me the error:

    error: cannot auto-call a function that has an argument without a default value (‘stdenv’)

with default.nix:  

    { stdenv, fetchurl, perl }:
    stdenv.mkDerivation { 
      name = "hello-2.1.1"; 
      builder = ./builder.sh; 
      src = fetchurl {
        url = ftp://ftp.nluug.nl/pub/gnu/hello/hello-2.1.1.tar.gz;
        md5 = "70c9ccf9fac07f762c24f2df2290784d";
      };
      inherit perl;
    }

and builder.sh:

    source $stdenv/setup
    
    PATH=$perl/bin:$PATH
    
    tar xvfz $src
    cd hello-*
    ./configure --prefix=$out
    make
    make install

Last but not least, the error above also seems to be the default error for unknown packages. Now that I did not get the "hello world" example to run, I am  stuck.

**Comment by FRidh** [comment]
Both the first and second line mention the section is about adding an expression to the *Nix packages collection*. In that case, is it not clear that `pkgs/top-level/all-packages.nix` is likely a file in that Nix packages collection?

**Comment by djoerd** [comment]
Does this mean I also have to read the documentation at: https://nixos.org/nixpkgs/manual/ ?
(together with: https://nixos.org/nix/manual/  that makes about 64,000 words!)

I tried to follow the 'hello' example by creating: 'hello2'. I now get the error:

    error: syntax error, unexpected ELLIPSIS

if I add the lines starting with "rec" to pkgs/top-level/all-packages.nix (see issue above). If I remove that again and add:

    hello2 =  callPackage ../applications/misc/hello2 { };

then I get the error:

    error: fetchurl does not support md5 anymore, please use sha256 or sha512

so, I guess, the line with 'md5' in the "hello" example needs to be changed to:

     sha256 = "c510e3ad0200517e3a14534e494b37dc0770efd733fc35ce2f445dd49c96a7d5";

As a last remark, I find the size of the documentation overwhelming, especially because the parts are not self-contained.

**Comment by vcunat** [comment]
I certainly agree the manuals would be worth some overhauling.

**Comment by djoerd** [comment]
So, both the addition to `pkgs/top-level/all-packages.nix`, as well as the `default.nix` part of the 'hello' example in the Nix manual are outdated, am I right? (just checking whether I should RTFM).

**Comment by googya** [comment]
I wrote my own version: 

```nix
{pkgs ? import <nixpkgs> {}
, stdenv ? pkgs.stdenv
, fetchurl ? pkgs.fetchurl
, perl ? pkgs.perl
}:
stdenv.mkDerivation {
	name = "hello-2.1.1";
	builder = ./builder.sh;
	src = fetchurl {
		url = ftp://ftp.nluug.nl/pub/gnu/hello/hello-2.1.1.tar.gz;
		sha256 = "1md7jsfd8pa45z73bz1kszpp01yw6x5ljkjk2hx7wl800any6465";
	};
	inherit perl;
}

```

But I don't think it is as same as the tutorial.

**Comment by nielsegberts** [comment]
The documentation is still confusing. This section is the first thing a user sees under the section 'Writing Nix Expressions', which seems like a reasonable starting point to start learning to write in Nix. However it's not obvious where to edit `pkgs/top-level/all-packages.nix` and run the first expression a user learns.

This reddit thread has the same feedback:
https://www.reddit.com/r/NixOS/comments/8ljkd0/modifying_allpackagesnix_for_tutorial/

**Comment by jeiros** [comment]
I totally agree with the sentiment. I am just trying to learn how to use the nix package manager and this whole section:

https://nixos.org/manual/nix/stable/expressions/writing-nix-expressions.html

Is rather confusing. In particular, this part:

https://nixos.org/manual/nix/stable/expressions/arguments-variables.html

Leaves me wondering what should I even do. To begin with, the syntax presented in that previous link isn't even found in the https://raw.githubusercontent.com/NixOS/nixpkgs/master/pkgs/top-level/all-packages.nix file.

Is this section of the manual really supposed for beginners?

```
This chapter shows you how to write Nix expressions, which instruct Nix how to build packages. It starts with a simple example (a Nix expression for GNU Hello), and then moves on to a more in-depth look at the Nix expression language.
```

I expected this to show me how to locally build a package with nix. I guess I am wrong? I am not even sure of what the purpose of modifying the all-packages.nix file is (or if even that is what we're supposed to do).

It'd also be nice to add a working example at the end of the section, if possible.

**Comment by fricklerhandwerk** [comment]
Removed that chapter in https://github.com/NixOS/nix/pull/6863. It was really confusing indeed.
