### ISSUE TITLE
Add an `exportReferencesGraph`-like builtin

### ISSUE THREAD

**Issue by Ekleog** [NixOS/nix#1818]
Currently, when needing the closure of a derivation in nix, the easiest way I know of is:
```nix
with import <nixpkgs> {};
let
  gcc-closure-derivation = runCommand "gcc-closure-derivation" {
    exportReferencesGraph = [ "closure" gcc ];
  } ''
    echo "[" > $out
    ${perl}/bin/perl ${pathsFromGraph} closure | while read line; do
      echo "$line" >> $out
    done
    echo "]" >> $out
  '';
  gcc-closure = import gcc-closure-derivation;
in
writeScript "display-gcc-closure" ''
  #!/bin/sh
  echo ${toString gcc-closure}
''
```

Adding a `exportReferencesGraph`-like builtin would allow to do all this much more easily, and even to potentially remove the need for `exportReferencesGraph` altogether, allowing to migrate logic from bash code to nix code.

However, I don't know much about nix's internals, so I'm not sure whether it is actually possible?

**Comment by edolstra** [comment]
This requires a closure to be built at evaluation time, so it has all the problems of import-from-derivation.

What's the use case for processing the references graph in Nix?

**Comment by Ekleog** [comment]
Oh, indeed I failed to remember that the closure cannot be inferred without actually building it... so that was a stupid idea, it could just as well be written directly in nix with only minor differences.

The use case was for things like https://github.com/NixOS/nixpkgs/blob/dd2fc990f08da41b81162c83f3aae41ebb6cbd5d/pkgs/build-support/replace-dependency.nix#L26 where this script could just have called the new builtin -- but actually having a nix function would be just equivalent.

Thanks! :)
