### ISSUE TITLE
Installation fails on macOS 10.13.2

### ISSUE THREAD

**Issue by giorgiga** [NixOS/nix#1820]
Installation fails after:

    ---- sudo execution ------------------------------------------------------------
    I am executing:
    
        $ sudo rsync -rlpt /var/folders/rn/33zw8h8s2fn9dl75x0sxgk0r0000gn/T/nix-binary-tarball-unpack.XXXXXXXXXX.IZHbt0JS/unpack/nix-1.11.16-x86_64-darwin/store/ /nix/store/
    
    to copy the basic Nix files to the new store at /nix/store
    
    
    ---- oh no! --------------------------------------------------------------------
    Something went wrong, and I didn't find Nix installed at
    /nix/store/hwpp7kia2f0in5ns2hiw41q38k30jpj2-nix-1.11.16.
    
    We'd love to help if you need it.

(see attached [full log](https://github.com/NixOS/nix/files/1668531/nix-install.log))

**Comment by FRidh** [comment]
cc darwin people @copumpkin @LnL7 @grahamc

**Comment by LnL7** [comment]
This looks like the same problem as https://github.com/NixOS/nix/issues/1582. I also tried to reproduce it without any success IIRC.

**Comment by giorgiga** [comment]
Yep, this is a duplicate of #1582. Sorry guys
