### ISSUE TITLE
Nix fails to build on cygwin64 (thread_local)

### ISSUE THREAD

**Issue by viric** [NixOS/nix#1826]
Building nix master 0167eac571d6d92f18640d05cfb7fa10a4cd0fd9 on cygwin64 fails, with multiple lines like this:

```
src/libstore/build.o:/home/xxxx/3rd/nix/src/libstore/build.cc:4326:(.text+0x                    1553): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `TLS                     init function for nix::curActivity'
```

That seems related to the only thread_local c++11 symbol, and this seems to be a gcc issue since 4.8: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=64697

The last nix on cygwin64 that we use fine is 1.11.3. I remember that 1.11.7 fails because the libexec/ executables cannot find some dlls.

cc @cpages

**Comment by viric** [comment]
Can someone suggest a workaround? Is there any easy way we can take away the thread_local and have it still working?

**Comment by dtzWill** [comment]
If you don't mind:

* What compiler and version(s) have you tried?
* Do you know if it provides full C+14 support?
* Just curious: Have you tried latest 1.11, does that work?

Ideas for possible workarounds:
* Wrapping the variable with a function (hide the thread_local variable entirely in a .c) returning a reference
* Change the initializer of curActivity to a non-zero value (in attempt to cause an initializer to be emitted)

**Comment by viric** [comment]
Well, basically cygwin comes with a gcc, and I don't want to mess with some other gcc. The bug seems open in gcc bugzilla since years, so I guess the problem is still there in any newer gcc.

I tried the last 1.11=1.11.16 and it works fine in cygwin64, if I'm not wrong.

About how to solve this, which seems a gcc long standing bug, I wonder why specifically curActivity has to be in thread_local. I cannot tell with a quick look at the code.

**Comment by viric** [comment]
This seems to be a fix that worked for someone else in the for problem:
https://github.com/tsulej/pbrt-v3/commit/34d77e524b3c2055982247216a31e38b28ffc088

**Comment by viric** [comment]
meh:
```
src/libutil/logging.hh:80:38: warning: ‘thread’ attribute directive ignored [-Wattributes]
 extern __declspec(thread) ActivityId curActivity;
```

**Comment by shlevy** [comment]
@viric Have you tried cross-compiling nix? If it's a gcc issue maybe that will help?

(obviously it would be nice if we could cleanly support the gcc from cygwin, but just to get you around the specific problem...)

**Comment by viric** [comment]
Oh I misread the reference I gave; __thread makes all compile and link.

**Comment by viric** [comment]
So the solution should be a "configure" step that checks this, to handle cygwin.

**Comment by masaeedu** [comment]
@viric What should the configure step do? `-fno-lto`?
