### ISSUE TITLE
sandbox shell: too limited or should derivations provide own shell?

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nix#1832]
The minimal busybox shell may be too limiting-- notably, it's insufficient to build busybox itself since it doesn't support `$(( ))` expressions[1].

This can result in a rather unhappy system as of 700e21d6dac4683ef40f20127a6eb2a74b9bd8c6 .

While these features can be added (this one is controlled by `CONFIG_FEATURE_SH_MATH`),
I thought I'd bring up the issue to ensure things are working as expected and to address related questions:

* What functionality can derivations "expect" from /bin/sh?
* Is it a "bug" for derivations to overly rely on /bin/sh instead of using `stdenv.shell` (which once stdenv bootstrapping is complete should be a full bash shell?)

Depending on the answers, we may need a sprint to fix all broken packages over on nixpkgs before switching to 2.0.  Alternatively it may make sense to (sadface) revert back to using full bash until this is hammered out.

PS: https://github.com/dtzWill/nix/commit/1dcd3b80385c314178e26bf3646000d67c9f75e2 fixes the arith expression issue, FWIW.

<details><summary>[1] busybox build error (may need to use `--check` to force the build)</summary>
```
building
build flags: -j8 -l8 SHELL=/nix/store/i0ay05pqkbnvpfijm52mmlrp6kmkl80c-bash-4.4-p12/bin/bash CC=gcc\ -isystem\ /nix/store/ilr1hvanw8k63bxk4s1djmxbpx2zikii-musl-1.1.18/include\ -B/nix/store/ilr1hvanw8k63bxk4s1djmxbpx2zikii-musl-1.1.18/lib\ -L/nix/store/ilr1hvanw8k63bxk4s1djmxbpx2zikii-musl-1.1.18/lib
  SPLIT   include/autoconf.h -> include/config/*
  HOSTCC  applets/usage
  HOSTCC  applets/applet_tables
  GEN     include/bbconfigopts.h
  GEN     include/common_bufsiz.h
/build/busybox-1.28.0/scripts/generate_BUFSIZ.sh: line 56: syntax error: support for $((arith)) is disabled
make: *** [Makefile:857: include/config/MARKER] Error 2
make: *** Waiting for unfinished jobs....
  GEN     include/usage_compressed.h
  GEN     include/applet_tables.h include/NUM_APPLETS.h
  GEN     include/applet_tables.h include/NUM_APPLETS.h
  CC      applets/applets.o
  HOSTCC  applets/usage_pod
  LD      applets/built-in.o
builder for '/nix/store/k6qjvxpqr2idmnmvbvk3lmsrppzqvqp7-busybox-1.28.0.drv' failed with exit code 2
error: build of '/nix/store/k6qjvxpqr2idmnmvbvk3lmsrppzqvqp7-busybox-1.28.0.drv' failed
```
</details>

**Comment by edolstra** [comment]
Ideally derivations shouldn't rely on the existence of /bin/sh at all. But if they do, they should assume a POSIX shell.

**Comment by dtzWill** [comment]
Tracking things as I run into them, package list is not exhaustive:

Feature | Package(s) | Busybox option
---|---|---
math | busybox, musl |  `CONFIG_FEATURE_SH_MATH`
getopts | attr | `CONFIG_ASH_GETOPTS`


Config options that might be problems if not enabled:

* `CONFIG_CMDCMD` (support "command", something Nix uses a fair bit)
* `CONFIG_ASH_PRINTF` (printf builtin)
* `CONFIG_ASH_TEST` (test builtin)
* `CONFIG_ASH_BASH_COMPAT` (not sure, misc things)

Regardless I think we should do a full rebuild using new Nix and its shell to avoid confused debugging later when users can't build a package locally :).

**Comment by dtzWill** [comment]
Enabling these features seems reasonable and I want to say increased BusyBox binary from 120k to 140k, but that should probably be confirmed.

TBH I'm not 100% sure if they're considered part of a "POSIX" sh or not.  Links posted above seem to suggest they are but I may be missing something.

Anyway adding these as in https://github.com/dtzWill/nix/commit/ed6161d867147ce47d9ed1b9095ee757cea733fd helps a number of packages and I suggest we do so here and over on nixpkgs.

Does that sound good, thoughts?
I can create the PRs if this is the way we want to go.

**Comment by dtzWill** [comment]
Some more testing:

If using builtin echo, recommend setting CONFIG_FEATURE_FANCY_ECHO=y so `-e` and `-n` options are supported--this is behind the breakage in ucl (see mention above) and a number of other packages.

**Comment by dtzWill** [comment]
FWIW enabling a bunch of features (https://github.com/dtzWill/nix/commit/f849d6493aa91098ef35b3b54b593ec5f83341a3) only bumps the binary to 140K and fixes issues I've seen so far.

**Comment by dtzWill** [comment]
Closing this as fixed-- it's about what the intended situation should be and that much has been answered.

(Also the PR mentioned above addresses problems due to lacking features)
