### ISSUE TITLE
builtins.hashFile

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nix#1835]
If I want a hash of a file, I can compose the `readFile` and `hashString` builtins like so:

```
nix-repl> builtins.hashString "sha256" (builtins.readFile /tmp/a)
"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
```

However, this trick only works for text files. Could we add a `hashFile` builtin for hashing any file? Or is there already a way to do this that I'm missing?

**Comment by deliciouslytyped** [comment]
Is there a workaround for this until something shows up in nix?

**Comment by chris-martin** [comment]
My workaround has been to hash the file's nix store path instead, like so:

```
nix-repl> builtins.hashString "sha256" "${/tmp/a}"
"84cadb2ba2c0dc4e1c0242fd0f380a79b736b0d2cb7cecc7bfe3bf66ddcef17c"
```

Since the store path itself includes a hash of the file, this achieves a similar result.

**Comment by deliciouslytyped** [comment]
Yeah, not really what I was going for, but if I just want a file-unique ID I used `baseNameOf hello.outPath`, not sure how bad of an idea that is. It relies on the outpath being in the form of `/a/b/c/d/.../hash-name`.
