### ISSUE TITLE
fetchGit should do shallow fetches when possible

### ISSUE THREAD

**Issue by shlevy** [NixOS/nix#1837]
Especially as many git servers, including github, have allowReachableSHA1InWant, fetchGit should just try fetching the specific rev or the HEAD of the specific ref first, and only then fall back to a fuller fetch.

**Comment by edolstra** [comment]
Are shallow fetches incremental? I.e. if I do a shallow fetch, then the repo receives a few new commits, and I do another shallow fetch, will it fetch only the delta?

**Comment by shlevy** [comment]
Yep

**Comment by kalbasit** [comment]
@shlevy I see this in the backlog, in other words, it's stalled for now? Would you accept a pull request for it?

**Comment by edolstra** [comment]
Shallow clones are now supported. However we can't make it the default because it would break the `revCount` attribute.

**Comment by coderfromhere** [comment]
Documentation doesn't show how to enable shallow cloning, is there a human-readable example of it?

**Comment by CohenCyril** [comment]
Hi, can one tell me in which version of `nix` is the attribute `shallow` accepted by `fetchGit`?
