### ISSUE TITLE
`nix run` doesn't evaluate expressions like `nix-shell -p`

### ISSUE THREAD

**Issue by vaibhavsagar** [NixOS/nix#1838]
```bash
$ nix run "nixpkgs.haskellPackages.ghcWithPackages (p: [ p.lens] )" -c "ghci"
error: don't know what to do with argument 'nixpkgs.haskellPackages.ghcWithPackages (p: [ p.lens] )'
Try 'nix --help' for more information.

$ nix-shell -p "haskellPackages.ghcWithPackages (p: [ p.lens] )" --run "ghci"
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
Prelude>
```

Is this not a use case that the new `nix run` is intended to support?

**Comment by dtzWill** [comment]
The various nix subcommands generally want these things to be wrapped with paren's if they're expressions, so something like this works:

```
$ nix run "((import <nixpkgs> {}).haskellPackages.ghcWithPackages (p: [ p.lens] ))" -c "ghci"
```

**Comment by vaibhavsagar** [comment]
Great, this also seems to work:

```bash
$ nix run "(import <nixpkgs> {}).haskellPackages.ghcWithPackages (p: [ p.lens ])"
```

I would like it if this change in behaviour could be documented somewhere.

**Comment by dtzWill** [comment]
I'm not sure the requirement for parentheses is intentional but maybe necessary as part of other things?

It's a minor nuisance but might be needed to differentiate expressions from attributes?

**Comment by mausch** [comment]
Related: https://github.com/NixOS/nix/issues/2645
