### ISSUE TITLE
nix run should change the prompt

### ISSUE THREAD

**Issue by Mounium** [NixOS/nix#1839]
Issuing `nix run` the prompt stays the same making it difficult to actually now whether or not we are inside a shell. Copying the behaviour from nix-shell would probably be desirable.

Excuse me for writing an issue instead of a pull request featuring it, but I'm not good with C++

**Comment by edolstra** [comment]
I'm not convinced that it should, given that the `nix run` shell is not a dev shell. The only thing it does is adjust the PATH.

**Comment by Mounium** [comment]
Wasn't it planned to replace nix-shell?

**Comment by LnL7** [comment]
nix-shell -A and nix-shell -p have very different behaviour, `nix run` is only supposed to replace the latter.

**Comment by Mounium** [comment]
I see, sorry then.
