### ISSUE TITLE
Adding an operator like Haskell's '$'

### ISSUE THREAD

**Issue by Ekleog** [NixOS/nix#1845]
The title says it all, I'm thinking it would be useful for eg.
```nix
builtins.trace "my debug stuff" $
# some multiline complex code that would require parenthesing otherwise
```

What do you think about it? I guess it's too late for the feature freeze, but $ being already reserved for ${} I guess it wouldn't be a breaking change anyway.

**Comment by dtzWill** [comment]
This would be crazy useful for exactly the use case described here, I run into this often! :grin:

**Comment by lheckemann** [comment]
Also for `(import <nixpkgs> {}).callPackage $`!

**Comment by Ekleog** [comment]
Also for `builtins.seq`.

**Comment by lilyball** [comment]
I really want this operator. And in particular, the right-hand side should support functions, because that's really what I want this for. I want to be able to take an existing

```
{ foo, bar }:
…
```

and change it to

```
lib.makeOverridable $
{ foo, bar }:
…
```

**Comment by lilyball** [comment]
Keywords to improve search discoverability of this issue: infix application operator

**Comment by lilyball** [comment]
On a similar note I'd also like the composition operator (`.`), though I find its lack less annoying than the lack of the application operator.

**Comment by lheckemann** [comment]
We still want this!

**Comment by lilyball** [comment]
I still want this very much!

**Comment by infinisil** [comment]
I think `$` is a hard sell, but here's an alternative that might get wider approval: 
```nix
apply foo;
apply bar;
baz

# Equivalent to
foo (bar baz)
```

Advantages compared to `$`:
- It fits better into the Nix syntax, which already supports `with ...;` and `assert ...;`
- It mirrors both the syntax and semantics of the new experimental CLI's [`--apply` option](https://nixos.org/manual/nix/unstable/command-ref/new-cli/nix3-eval.html?highlight=--apply#options)

Disadvantages:
- It requires a new keyword to be reserved, thus requiring something like NixOS/rfcs#137

**Comment by piegamesde** [comment]
FYI there is now an RFC that proposes something similar, people in here might have opinions about `|>` vs `<|` that I'd be interested in hearing.

https://github.com/NixOS/rfcs/pull/148

**Comment by thufschmitt** [comment]
This is a change with potential impact on the whole ecosystem (similar to NixOS/rfcs#110 or NixOS/rfcs#148), so it wouldn't be right for it to be decided here. Anyone willing for this to happen, please open an RFC about it to bring the discussion to a more visible place.
