### ISSUE TITLE
Placeholders don't work with passAsFile

### ISSUE THREAD

**Issue by shlevy** [NixOS/nix#1846]
Using `writeScriptBin` with a placeholder failed to replace the placeholder string with the output path, presumably because it uses `passAsFile`

**Comment by jtojnar** [comment]
Is this why I cannot use `placeholder` with `substituteAll`?

**Comment by jtojnar** [comment]
Let’s say I have the following expression, when would the placeholder be substituted?

```nix
{ stdenv, writeText }:

stdenv.mkDerivation rec {
  name = "test";

  unpackPhase = ":";
  dontBuild = true;
  outRef = placeholder "out";

  foo = writeText "file-containing-ref" outRef;

  installPhase = ''
    mkdir $out
    echo ${outRef} > $out/internal
    cat ${foo} > $out/external
  '';
}
```

It does not seem to work in `$out/external`.

**Comment by Ninlives** [comment]
It still don't work, is there a plan to fix this?
