### ISSUE TITLE
[Ideas please] A way to distribute Nix expressions without the paths they reference

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#1853]
Consider this scenario:

1. Large monorepo-like internal codebase, built by Nix with derivations using `src = ./path/to/source` all over the place.
2. Distribution of software from that codebase to internal Nix users on multiple platforms: they need some sort of internal "channel" or overlay.
3. Autonomous deployment of that software to production: `nix-copy-closure` to machines over `ssh` isn't autonomous; think autoscaling groups and machines that need to be able to figure out what software to download
4. Shared binary cache/automated builds of the codebase exist

So basically, imagine nixpkgs, but sitting alongside the code it's building/packaging, for internal distribution.

This use case isn't very well supported in Nix right now. Basically, a channel is a tarball of Nix files and you can reproduce its exact contents if you have everything that went into evaluation. In the example above, that means that all users and production boxes could have a channel pointing at `https://path/to/tarball/of/entire/repository.tar.xz` and everything would work fine, but that's inefficient:

1. The source repository can be large, so people don't want to download that tarball all the time
2. None of the end users or production boxes are actually building the code, so they don't need it to be in every channel tarball they download
3. We might not actually want to (or be licensed to) distribute the code to these places

So intuitively, it seems like a slightly more controlled regime for Nix path references is needed: I can set this up in pure Nix code, but for that to work, I need to be able to replace a path reference with _some value_ that produces the exact same hash, even if the path isn't on the filesystem. This would be easy with a fixed-output derivation, except that the hashing scheme for fixed-output paths and path references is different, so I can't just create a fixed-output derivation with the exact same contents as my path reference at deployment time and swap it into my expression.

Now, we recently acquired `builtins.path` which does have a `sha256` argument, so that looks promising, but unfortunately it doesn't behave like a derivation, so it must exist at evaluation time and it doesn't seem possible in the current machinery for it to be lazily retrieved like a derivation would be.

So, how can we do it? If we can solve this problem, I think Nix will be significantly better at managing proprietary codebases.

cc @edolstra @shlevy

**Comment by shlevy** [comment]
@copumpkin Why can't you just use `builtins.storePath /nix/store/hard-coded-path` again?

**Comment by copumpkin** [comment]
That's a good point, perhaps it'll just work. I misunderstood your previous suggestion to be about the derivation paths, but for the source paths it sounds better. I'll tinker with it a bit and reopen if I run into issues. Thanks!
