### ISSUE TITLE
attribute 'nixpkgs' in selection path 'nixpkgs.hello' not found

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nix#1865]
Try running the following with Nix 2.0:

```
$ NIX_PATH=/nix/var/nix/profiles/per-user/root/channels nix run nixpkgs.hello
error: attribute 'nixpkgs' in selection path 'nixpkgs.hello' not found
```

This is different than how previous version of Nix worked.

Oddly settings 'nixpkgs' to anything in NIX_PATH (even something that doesn't exist) will fix this issue:

```
NIX_PATH='nixpkgs=asdf:/nix/var/nix/profiles/per-user/root/channels' nix run nixpkgs.hello
```

**Comment by matthewbauer** [comment]
@edolstra Should this be supported? If not we need to update nix-profile.sh.in:

https://github.com/NixOS/nix/blob/master/scripts/nix-profile-daemon.sh.in#L53

**Comment by kballard** [comment]
This should be supported, because the manual still documents `NIX_PATH` as working this way (see [Chapter 17](https://nixos.org/nix/manual/#sec-common-env)).

**Comment by shlevy** [comment]
This is definitely a bug, not an intentional change. Will look into it.

**Comment by edolstra** [comment]
No, it's not a bug. Rather, the `nix` command does not have a replacement for channels yet, so it's currently left undefined where it gets its inputs from. (This is one of the main reasons why the `nix` CLI is marked experimental.) So currently it only uses prefixed `NIX_PATH` elements like `nixpkgs=...`.

**Comment by shlevy** [comment]
@edolstra IMO it's definitely a bug at least that it works with a dummy `nixpkgs=` argument... #1942 fixes it too.

**Comment by kballard** [comment]
How is it not a bug that the `nix` command is broken on a fresh install of Nix 2.0?

**Comment by matthewbauer** [comment]
> How is it not a bug that the nix command is broken on a fresh install of Nix 2.0?

It also could be a bug in nix-profile-daemon.sh (which is only used by MacOS currently). See #1664 for a potential fix.

**Comment by edolstra** [comment]
Right, the Linux install script sets `nixpkgs=$HOME/.nix-defexpr/channels/nixpkgs`.

**Comment by shlevy** [comment]
Is there a concern with #1942?

**Comment by tilpner** [comment]
> So currently it only uses prefixed NIX_PATH elements like nixpkgs=....

Has this behaviour changed?

@grahamc [has tested NIX_PATH behaviour](https://gist.github.com/grahamc/55a9d8433a80476a6f453176679944aa#file-gistfile1-txt-L28-L31),
```
$ NIX_PATH=/home/grahamc/.nix-defexpr/channels nix build -f '<nixpkgs>' git

$ ls -la result                                                           
lrwxrwxrwx 1 grahamc users 54 Apr 3 08:32 result -> /nix/store/jaani1kx4a4kvz11d0myfkjjiiklfl7w-git-2.16.2
```
 and it seems like the unprefixed `NIX_PATH=/home/grahamc/.nix-defexpr/channels` is still being used for evaluation?

**Comment by kballard** [comment]
Is `nix build` actually a new command or is that just an alias for `nix-build`? Because the issue seems to be the new `nix` command stuff treats `NIX_PATH` differently than the existing commands, but if `nix build` is just an alias for `nix-build` then it stands to reason that you wouldn't see this issue with it.

**Comment by ElvishJerricco** [comment]
This is a major pain on macOS, which does *not* have a prefixed NIX_PATH, and only has the root channels by default. Same issue with the `--daemon` installation on Linux.

**Comment by zimbatm** [comment]
It depends on the content of the NIX_PATH target folder:
```
$ ls /nix/var/nix/profiles/per-user/root/channels
binary-caches  manifest.nix  nixos
```
When NIX_PATH is just a path it will look up thinks from that folder. So in that case the channel doesn't contain `nixpkgs` and it will fail.

```
$ NIX_PATH=/nix/var/nix/profiles/per-user/root/channels nix repl
Welcome to Nix version 2.1.1. Type :? for help.

nix-repl> import <manifest.nix>
[ «derivation ???» ]

nix-repl> import <nixos>
«lambda @ /nix/store/syxm6jgcc0wj2qc7pg6vz44d5s9a42nc-nixos-18.09.1023.06fb0253afa/nixos/pkgs/top-level/impure.nix:15:1»

nix-repl> import <nixpath>
error: file 'nixpath' was not found in the Nix search path (add it using $NIX_PATH or -I), at (string):1:8
```

**Comment by matthewbauer** [comment]
fixed in d7a84d330cc677d3c9e2c5553a861ab9f82245f6

**Comment by matthewbauer** [comment]
Not fixed actually

**Comment by lilyball** [comment]
Definitely broken. Updating to Nix 2.3 just broke `nix run` for me, since I'm not customizing my `NIX_PATH`.

**Comment by akavel** [comment]
Quick hacky workaround that seems to be working for me on a Mac, based on [@edolstra's comment above](https://github.com/NixOS/nix/issues/1865#issuecomment-370231213), is to prefix the command with `NIX_PATH=nixpkgs=$NIX_PATH/nixpkgs`, as shown below:

```console
$ nix run nixpkgs.hello
error: attribute 'nixpkgs' in selection path 'nixpkgs.hello' not found
$ NIX_PATH=nixpkgs=$NIX_PATH/nixpkgs nix run nixpkgs.hello
[1 copied (0.1 MiB), 0.0 MiB DL]
bash-3.2$ exit
```

Seems to also fix `nix search` and `nix eval`.

Question: should I put this `NIX_PATH` adjustment in my `~/.profile` or something?

**Comment by lilyball** [comment]
Yes, put it in your `~/.profile` after sourcing the setup script, except I would write `nixpkgs=$HOME/.nix-defexpr/channels/nixpkgs` rather than `nixpkgs-$NIX_PATH/nixpkgs` in case `NIX_PATH` changes again to include something else.

Personally, I tweaked my profile to make sure `NIX_PATH` didn't have the string `nixpkgs=` in it first, before prepending the new path onto it.

**Comment by ElvishJerricco** [comment]
:/ This is still an issue with the recommended install method on Ubuntu.

```
$ curl https://nixos.org/nix/install | sh
$ . ~/.nix-profile/etc/profile.d/nix.sh
$ nix build nixpkgs.hello
error: attribute 'nixpkgs' in selection path 'nixpkgs.hello' not found
```

**Comment by t184256** [comment]
Are there plans for a release incorporating this fix anytime soon?

**Comment by teozkr** [comment]
@t184256 Nix 2.3.1 was released the day after that commit, and includes the fix. It might not have been in nixpkgs when you posted, but it's definitely in the current nixpkgs-unstable.

**Comment by t184256** [comment]
I've asked because I had to work around in on 2.3.1 specifically (taken from the aarch64 tarball).
