### ISSUE TITLE
Request for a function to get version components

### ISSUE THREAD

**Issue by romildo** [NixOS/nix#1868]
The algorithm for splitting a version string into version components is implemented privately in C++. It is used to implement `compareVersions`.

It would be very helpful to have a public function to split the version components. Something like

```
versionComponents "1.2.3" => [ "1" "2" "3" ]
versionComponents "2..3-4pre12" => [ "2" "3" "4" "pre" "12" ]
```

A function to get a range of the version components would be very helpful too.

**Comment by shlevy** [comment]
@romildo What do you mean "get a range of the version components"?

**Comment by romildo** [comment]
> What do you mean "get a range of the version components"?

After splitting the version string, I would like to be able to select a range, that is, a sublist of the version components. Something like `get_version_component_range <range> [version]` documented in [versionator eclass for gentoo](https://devmanual.gentoo.org/eclass-reference/versionator.eclass/index.html).

It may be useful for instance to get the release version of [Mate packages](http://pub.mate-desktop.org/releases/1.20/) from the version string: it is formed from the first two components of the version string.

**Comment by romildo** [comment]
Thanks.
