### ISSUE TITLE
Can not set option on command line for max-connections or max-connections-age

### ISSUE THREAD

**Issue by puffnfresh** [NixOS/nix#1875]
Running things like:

```
nix-build --option max-connections 3 --option max-connections-age 10
```

Gives:

```
warning: unknown setting 'max-connections'
warning: unknown setting 'max-connections-age'
```

I added a println to `Config::addSetting` and these warnings are printed before the settings are registered. I'm guessing this is a problem with initialisation order between options and stores.

**Comment by edolstra** [comment]
These are store settings, not global settings. So you need to do e.g. `--store 'daemon?max-connections=3`.
