### ISSUE TITLE
"store only" build variant

### ISSUE THREAD

**Issue by shlevy** [NixOS/nix#1877]
For easier porting to new `system`s and to reduce overhead on systems that don't need the expression language or high level nix tooling, a variant of Nix with only `nix-daemon` and `nix-store` (and the associated libraries/dependencies) would be nice to have.

**Comment by edolstra** [comment]
The new UI makes this a lot harder. Previously we could just not build nix-instantiate and nix-env, but the new UI supports evaluation even in "low-level" commands like `nix path-info`.

**Comment by shlevy** [comment]
Unsure if/when this will be practical to pursue, closing for the time being. PRs addressing this still welcome.
