### ISSUE TITLE
The Nix installer script does not support single user installations anymore on macOS

### ISSUE THREAD

**Issue by svanderburg** [NixOS/nix#1889]
Nowadays, Nix also supports multi-user installations on macOS which is great -- we can more safely run multiple builds in parallel, we have more purity guarantees, and (of course) multiple user accounts that can use Nix.

I think it's a good thing that this is the default option in the Nix installer. However, it would be nice if you could still use the single-user installations if this is desired, e.g. by providing a command line parameter, to the install script.

The reason why I still want to use a single-user installation is to do iPhone builds. iPhone IPA files must be signed and in order to sign, the builder needs access to the macOS login keychain (I know this is an impurity, but for practical reasons being able to do this, is very very useful!). I am currently running a Hydra build server that builds many  IPA apps for internal usage.

In multi-user installations, signing is impossible because every build runs as an unprivileged user that has no access to the login keychain.

At the moment, editing the `install` script and commenting out a few lines worked for me to get a single user installation again, but this is not very user friendly.

**Comment by kballard** [comment]
I too was surprise today to discover there's no way to do a single-user install on macOS. I'm the only user of my computer, I don't need a multi-user setup. And it's not very user-friendly. For example, it wasn't until a few days ago that I finally figured out how to actually update the nixpkgs channel (`sudo -EH nix-channel --update`), because my normal user can't even see it in `nix-channel --list`.

**Comment by alexvorobiev** [comment]
The single-user setup is still in the script. See my instructions here: http://zzamboni.org/post/using-nixs-single-user-mode-on-macos/#comment-3750944802

**Comment by lundjordan** [comment]
I got confused by this too. I wondered why the install script was creating all these new users and my own user didn't have nix-env in path.

[docs](https://github.com/NixOS/nix/blob/8af911be5ccb11f05615451fc7e90377ede7fba7/doc/manual/installation/installing-binary.xml#L16) suggest install script uses single user mode.

afaict, [the new default](https://github.com/NixOS/nix/blob/a8c61cef2624ce39abb446e7c46064917f6f6b78/scripts/install-nix-from-closure.sh#L65) is multi user if you are coming from macOS or a Linux system with systemd

**Comment by lundjordan** [comment]
iiuc, passing [`--no-daemon`](https://github.com/NixOS/nix/commit/17b158af85296c1c815af237cf5626e79b6b0a70) will force a single user install

**Comment by onetom** [comment]
I think this issue can be closed now, no?
