### ISSUE TITLE
Fixing build failures when making sandbox builds the default

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nix#1891]
This is inspired by recent commits, in particular:

https://github.com/NixOS/nix/commit/e8d53bfdc94eea142542de92ff0822eb283d293f

Which reverted making sandbox use the default due to the resulting breakage, which makes sense during the release push.

This issue is about fixing those failures so that we can explore making this the default in the future.  It seems unfortunate to leave them disabled "only" because our own self-tests don't work/handle/expect this to be the case, and hopefully isn't too difficult to address.

AFAICT the failures are all because it breaks many of our tests in fundamental ways.

One quickfix would be to simply explicitly disable sandbox usage during tests (except for the sandbox paths test and such).

Thoughts? Mostly just wanted to track this :).

Previously and related: #1821 #179

**Comment by shlevy** [comment]
Gonna be bold and hope we can get this in by the next bugfix release.

**Comment by edolstra** [comment]
Closing, I don't think there is actionable left to do here.
