### ISSUE TITLE
`nix search` throws an error if no package name is provided

### ISSUE THREAD

**Issue by kballard** [NixOS/nix#1893]
If I run `nix search` with no arguments (which the manpage says should show all packages), it just gives me an error.

> error: An empty regex is not allowed in the POSIX grammar.

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.4.0, macOS 10.13.3`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by dtzWill** [comment]
This appears to be a discrepancy (haven't investigated "why") in how Darwin does things vs Linux.

(googling leads to things like: https://stackoverflow.com/questions/34188879/what-does-an-empty-regular-expression-mean-in-posix-bre-ere)

**Comment by kballard** [comment]
The Darwin manpage for `regex(3)` says

```
IMPLEMENTATION CHOICES
     […]

     There are a number of decisions that IEEE Std 1003.2 (``POSIX.2'') leaves
     up to the implementor, either by explicitly saying ``undefined'' or by
     virtue of them being forbidden by the RE grammar.  This implementation
     treats them as follows.

     […]

     […]An empty string is not a legal RE.
```

Looking at the manpage for `re_format(7)` it also says

>      A (modern) RE is one= or more non-empty= branches, separated by `|'.  It matches anything that matches one of the branches.

So it sounds like the POSIX grammar forbids empty regular expressions, and the Darwin implementation continues to forbid it, but I guess the Linux implementation chose to allow it.

**Comment by dtzWill** [comment]
Great, thanks for the information!

That's precisely the sort of thing I expected, although my experience is largely based on clang and libc++, at least when they do the nice thing they do and clearly explain the issue and cite a standard :).

This seems straightforward to workaround, we just need to handle this case ourselves.

And add a test.  Lots more tests. Test all the things!

I would do this myself but will be away until early next week... 
Well I'll try to remember to look at it then if no one else does. Bug me if I don't, please! :)
