### ISSUE TITLE
Nix cannot be installed through SSL intercepting proxy

### ISSUE THREAD

**Issue by makefu** [NixOS/nix#1896]
Installing nix fails when an intercepting SSL proxy is in between the host and the internet.

Running curl manually works as the respective root certificates are added to the ca certificate trust store.

```console
[root@dev ~]# mkdir /etc/nix
[root@dev ~]# echo "build-users-group =" > /etc/nix/nix.conf
[root@dev ~]# curl https://nixos.org/nix/install | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2455  100  2455    0     0   5265      0 --:--:-- --:--:-- --:--:--  5268
downloading Nix 2.0 binary tarball for x86_64-linux from 'https://nixos.org/releases/nix/nix-2.0/nix-2.0-x86_64-linux.tar.bz2' to '/tmp/nix-binary-tarball-unpack.Ml95QP5hQK'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21.0M  100 21.0M    0     0  1901k      0  0:00:11  0:00:11 --:--:-- 3204k
warning: installing Nix as root is not supported by this script!
performing a single-user installation of Nix...
copying Nix to /nix/store...............................
initialising Nix database...
installing 'nix-2.0'
building '/nix/store/ni5hj5bcgqlfpvlyl283jj0x9jmiy5kk-user-environment.drv'...
created 6 symlinks in user environment
warning: unable to download 'https://nixos.org/channels/nixpkgs-unstable': Peer certificate cannot be authenticated with given CA certificates (60); retrying in 275 ms
warning: unable to download 'https://nixos.org/channels/nixpkgs-unstable': Peer certificate cannot be authenticated with given CA certificates (60); retrying in 608 ms
warning: unable to download 'https://nixos.org/channels/nixpkgs-unstable': Peer certificate cannot be authenticated with given CA certificates (60); retrying in 1185 ms
warning: unable to download 'https://nixos.org/channels/nixpkgs-unstable': Peer certificate cannot be authenticated with given CA certificates (60); retrying in 2551 ms
error: unable to download 'https://nixos.org/channels/nixpkgs-unstable': Peer certificate cannot be authenticated with given CA certificates (60)
[root@dev ~]# curl https://nixos.org/channels/nixpkgs-unstable
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://d3g5gsiof5omrk.cloudfront.net/nixpkgs/nixpkgs-18.03pre129106.28e10850d63">here</a>.</p>
</body></html>
```

In the past i somehow managed to install nix, however i was unable to install any packages due to similar SSL errors.

**Comment by therealpxc** [comment]
I am affected by a similar error. Nix installation mostly works (it fetches the tarball successfully, once the appropriate `*_proxy` environment variables are set). But it dies trying to update the channel and so never modifies the user's shell configuration.

I don't know the details of the proxy configuration, but I see a different error message:

    [pcallahan@dal0024 ~]$ nix-channel --add http://nixos.org/channels/nixpkgs-unstable # http gives one error message
    [pcallahan@dal0024 ~]$ nix-channel --update
    warning: unable to download 'http://nixos.org/channels/nixpkgs-unstable': HTTP error 301 (curl error: SSL connect error); retrying in 255 ms
    warning: unable to download 'http://nixos.org/channels/nixpkgs-unstable': HTTP error 301 (curl error: SSL connect error); retrying in 563 ms
    warning: unable to download 'http://nixos.org/channels/nixpkgs-unstable': HTTP error 301 (curl error: SSL connect error); retrying in 1276 ms
    warning: unable to download 'http://nixos.org/channels/nixpkgs-unstable': HTTP error 301 (curl error: SSL connect error); retrying in 2332 ms
    error: unable to download 'http://nixos.org/channels/nixpkgs-unstable': HTTP error 301 (curl error: SSL connect error)
    
    [pcallahan@dal0024 ~]$ nix-channel --add https://nixos.org/channels/nixpkgs-unstable # https gives another
    [pcallahan@dal0024 ~]$ nix-channel --update
    warning: unable to download 'https://nixos.org/channels/nixpkgs-unstable': SSL connect error (35); retrying in 343 ms
    warning: unable to download 'https://nixos.org/channels/nixpkgs-unstable': SSL connect error (35); retrying in 632 ms
    warning: unable to download 'https://nixos.org/channels/nixpkgs-unstable': SSL connect error (35); retrying in 1117 ms
    warning: unable to download 'https://nixos.org/channels/nixpkgs-unstable': SSL connect error (35); retrying in 2219 ms
    error: unable to download 'https://nixos.org/channels/nixpkgs-unstable': SSL connect error (35)

 `NIX_SSL_CERT_FILE` is set, and it points to a file that exists. Manual `curl`s to the same URLs succeed, as with the OP.

**Comment by gunnihinn** [comment]
I spent a while figuring this out, so I'm adding this comment with a link to the docs added in @grahamc's PR that explain how to resolve this issue: https://nixos.org/nix/manual/#sec-nix-ssl-cert-file
