### ISSUE TITLE
`--indirect` no longer valid flag for `nix-build` with 2.0 

### ISSUE THREAD

**Issue by Ericson2314** [NixOS/nix#1913]
In `1.11.x`, `--indirect` affects gc root creation with `nix-build` as it does with `nix-store`, but in 2.0 it isn't recognized.

I have a feeling this might have been an unintentional interface with the way `nix-build` previously was written in Perl. Regardless, there's no reason we should be breaking the legacy interface just before we deprecate it.

CC @ryantrinkle @shlevy

**Comment by matthewbauer** [comment]
I thought it was fixed in #1830.

**Comment by edolstra** [comment]
Indeed `--indirect` works for me. Are you using a prerelease from before commit 19477e8815a7c9b91c82278ec0e22957c97bec16?

**Comment by Ericson2314** [comment]
Oops, that's an exact duplicate. Thanks @matthewbauer!
