### ISSUE TITLE
nixos-rebuild error - unable to start build process

### ISSUE THREAD

**Issue by Izorkin** [NixOS/nix#1915]
I have installed packet manager nix 2.0 using parameter nix.package = pkgs.nixUnstable. After this, "sudo nixos-rebuild switch --upgrade" gives the following error message:

```
unpacking channels...
error: cloning builder process: No space left on device
error: unable to start build process
error: program '/nix/store/r8zhwq9xylxw8a823kpvqy0kfqq4g52f-nix-2.0pre5968_a6c0b773/bin/nix-env' failed with exit code 1
```

"sudo nixos-rebuild switch" command works fine.
"--upgrade" works only after I delete nix 2.0, and stop services: nix-daemon.socket and nix-daemon.service.
I observe this on 2 servers, but unfortunately can not reproduce it on a clean system.

**Comment by Izorkin** [comment]
strace -ff -o logfiles -s 300 nixos-rebuild switch --upgrade - 
http://rgho.st/private/6dsLXPfMz/5b7d5ffea38afb1a935460ada20411ac

**Comment by Izorkin** [comment]
strace -ff -o logfiles -s 300 nix-env -iA nixos.gist                                                                                       
installing 'gist-4.6.1'
error: unable to start build process
http://rgho.st/private/7vbnytv4z/83912e64e9d550543860b6b52229fc2b

**Comment by Izorkin** [comment]
I have changed "nix.useSandbox" from "true" to "false", and can not observe the error anymore.

**Comment by mbrgm** [comment]
Observing identical behaviour here.

**Comment by Izorkin** [comment]
If manual changed /proc/sys/user/max_user_namespaces 0 to 1 - nixos-rebuild worked

**Comment by dtzWill** [comment]
If you're using hardened module, there's a related issue (on mobile sorry, bug me if you can't find it).

**Comment by Izorkin** [comment]
Yes, me using hardened module and sanbox.

**Comment by joachifm** [comment]
See also https://github.com/NixOS/nix/issues/1947#issuecomment-430020810
