### ISSUE TITLE
`nix edit` doesn't work with default install on macOS

### ISSUE THREAD

**Issue by kballard** [NixOS/nix#1922]
I tried running `nix edit nixpkgs.exa` and all it tells me is

> error: attribute 'nixpkgs' in selection path 'nixpkgs.exa' not found

This is an almost entirely stock install of Nix 2.0 on macOS 10.13. The only customization I have is a single package override in `~/.config/nixpkgs/config.nix` (not for `nixpkgs.exa`).

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 17.4.0, macOS 10.13.3`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(root): `"nixpkgs-18.03pre129212.098c7f3d945"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by LnL7** [comment]
I suspect this is because `EDITOR` is not set by default (eg. https://github.com/LnL7/nix-darwin/commit/6f1c1049ddc9eaa33454efacf1bdba6b28bd4074)

**Comment by matthewbauer** [comment]
Does ```nix run nixpkgs.exa``` work? If not, this sounds like what I was talking about in #1865.

**Comment by kballard** [comment]
`nix run nixpkgs.exa` produces the same error. So this is a dupe of #1865. I'll close this ticket out, thanks.
