### ISSUE TITLE
nix repl: "Unexpected linenoise key type: 0"

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nix#1925]
This can be triggered with:

```console
$ :|nix repl
Welcome to Nix version 2.0pre5968_a6c0b773. Type :? for help.

error: Unexpected linenoise keytype: 0
```

Err ignore the version there O:).

This can occur with actual use, although I've yet to pin down what triggers it.  Some combination of tab-completion and control-c/control-d/enter I think.

**Comment by dtzWill** [comment]
No clue what "keyType == 0" is meant to indicate (which is actually why I chose to throw an Error when we encountered it).

Trivial fix for the case where one pipes to nix repl: https://github.com/dtzWill/nix/commit/6fb086688a984678ffc364a0b7d9b54d3bffab46

Which doesn't currently work w/nix on latest nixpkgs master:
```console
$ echo -e "1+2\n"|/nix/store/xxx8cgxqd502b2laiy44qbd3100ji18a-nix-2.0/bin/nix repl
Welcome to Nix version 2.0. Type :? for help.

3


error: Unexpected linenoise keytype: 0
```

But does with commit above.

**Comment by phdoerfler** [comment]
Here is another way to trigger this:

```shell
$ echo 'toString pkgs.glibc' | nix repl '<nixpkgs>'  
Welcome to Nix version 2.1.3. Type :? for help.

Loading '<nixpkgs>'...
Added 9430 variables.

"/nix/store/7gx4kiv5m0i7d7qkixq2cwzbr10lvxwc-glibc-2.27"

error: Unexpected linenoise keytype: 0
```

**Comment by edolstra** [comment]
This seems to work for me on master. Probably because we switched to editline?

**Comment by phdoerfler** [comment]
I'm still on https://nixos.org/channels/nixos-18.09 (because 19.03 crashes X on my machine – it got an old nvidia card)

**Comment by edolstra** [comment]
Closing since we switched to editline.
