### ISSUE TITLE
Flat hashes are incorrect on macOS when files that only differs in case collide on the filesystem.

### ISSUE THREAD

**Issue by Mic92** [NixOS/nix#1931]
Sample URL: https://github.com/linuxdeepin/deepin-icon-theme/archive/15.12.52.tar.gz
linux: 141in9jlflmckd8rg4605dfks84p1p6b1zdbhbiwrg11xbl66f3l 
macOS: 0fgmii3qzdl9n9vh7zq54n75d200w6xw7gbgzdaxjxm3b10bjl38

Also see: https://github.com/NixOS/nixpkgs/pull/36142#issuecomment-369385765

**Comment by Mic92** [comment]
So the root cause is relate to files with different case that become the same file macOS filesystems:
https://github.com/NixOS/nixpkgs/pull/36142#issuecomment-369542655

**Comment by copumpkin** [comment]
Yup, that's the only time I've seen that happen is with differing case

**Comment by Mic92** [comment]
@copumpkin so what is the executive summary? Should we ignore those errors?

**Comment by edolstra** [comment]
I think the best solution is to ask upstream to get rid of the case collision.

**Comment by copumpkin** [comment]
The Linux kernel tree unfortunately suffers extensively from this too 😄 

But yeah, I don't think there's much to do about it short of avoiding the problem in the first place. @shlevy I think did some stuff related to hackage in this space, but it's fundamentally quite finicky and easy to screw up.

**Comment by Mic92** [comment]
I think apfs is widespread now. Do we have the case-sensitive flag enabled on it?

**Comment by Mic92** [comment]
I think most users have now an apfs container so this is solved?
