### ISSUE TITLE
Remote builds via ssh-ng try to use local sandbox shell

### ISSUE THREAD

**Issue by shlevy** [NixOS/nix#1935]
error: build of '/nix/store/4306ksk71wpvrvw23pfhsplfnrzhsfri-binutils-2.30.drv' on 'ssh-ng://nix-ssh@<redacted>?ssh-key=<redacted>' failed: while setting up the build environment: getting attributes of path '/nix/store/mqy29jzrp7dqcivwb919ksg4g75m5lfm-busybox-1.28.0/bin/busybox': No such file or directory

**Comment by LnL7** [comment]
https://github.com/NixOS/nix/pull/1713 Is related to this, but I agree that making a distinction between local and forwardable settings is probably a better solution.
