### ISSUE TITLE
feature: print all of the store paths in a nix store

### ISSUE THREAD

**Issue by ledettwy** [NixOS/nix#1945]
Managing the size of a binary cache requires knowledge of what is in the binary cache, and currently there are no Nix tools for obtaining this information.  There should be some command which given a binary cache (or a live /nix/store, since nix 2 can deal with both kinds interchangeably) will print the store paths for all of the entries in the cache.

Shell workaround (only works in binary caches):
<pre>$ find /store/path -maxdepth 1 -name "*.narinfo" | xargs -n1 grep "^StorePath:" | awk '{print $2}'</pre>

**Comment by shlevy** [comment]
`nix path-info --all` can do this.
