### ISSUE TITLE
nix 2.0: Specifying store when building with Hardened profile

### ISSUE THREAD

**Issue by Izorkin** [NixOS/nix#1947]
When I enable "Hardened" profile in settings:

`  imports = [
    <nixpkgs/nixos/modules/profiles/hardened.nix>
  ];
`
and then try to specify directory when building, e.g. 
`nix build -f /root/mypack nginx --store /temp`
 the build does not work. I get the following error messages:

> [root@nixos-test:~]# nix build -f /root/mypack nginx --store /temp
> [137 copied (698.1 MiB), 126.3 MiB DL]
> error: unable to fork: Cannot allocate memory
> 
> [root@nixos-test:~]# nix build -f /root/mypack nginx --store /temp
> [0/31 built, 1/0/23 copied (0.0/4.5 MiB), 0.0/0.6 MiB DL] fetching libxslt-1.1.32-dev from https://cache.nixos.orgerror: cloning builder process: No space left on device
> [0 copied (0.1 MiB), 0.0 MiB DL]
> error: unable to start build process
> 
> [root@nixos-test:~]# nix build -f /root/mypack nginx --store /temp
> [0.0 MiB DL] querying libressl-2.6.3 on https://cache.nixos.orgerror: cloning builder process: No space left on device
> [0.0 MiB DL]
> error: unable to start build process

**Comment by dtzWill** [comment]
Using local store requires using sandbox via user namespaces, which it looks like the hardened profile disables.  I think if you re-enable them but leave the rest it'll work?

**Comment by Izorkin** [comment]
changed options boot.kernel.sysctl."user.max_user_namespaces" = 1 "nix build" - worked.

**Comment by joachifm** [comment]
With https://github.com/NixOS/nixpkgs/commit/f4ea22e5de572efa9babc7674fdc79fa637a7e31 this is now detected when building the nixos configuration. An option has been added to make overriding the behavior a little more convenient.

**Comment by Izorkin** [comment]
All in all, in which mode it is better to build packets: in "Hardened" mode without using "sandbox" mode, or in "sandbox" mode?

**Comment by joachifm** [comment]
@Izorkin Depends on what you mean by "better".

My opinion is that you should not run builds on security sensitive hosts at all.

Sandboxing is better for development, as it helps detect/prevent impurities.

Whether userns offers much benefit security wise beyond running builds as unprivileged users is unclear to me. Sophisticated attackers will target the kernel.

Please note that the defaults selected by the hardened profile err on the side of paranoia, to the detriment of performance and functionality. There is no guarantee that this materially improves your security. You may be crippling your system for no real benefit, if you choose to stick with the profile defaults. The module is designed to be "maximally hard" without rendering the system *completely* unusable, with the understanding that the admin will relax settings to taste.

If you're comfortable with user namespaces and want that feature then I see no problem with relaxing the restriction.

**Comment by Izorkin** [comment]
Thanks.
Decided to use this option

```
  imports = [
    <nixpkgs/nixos/modules/profiles/hardened.nix>
  ];

  security.allowUserNamespaces = true;
  security.allowSimultaneousMultithreading = true;

  nix.useSandbox = true;
```
