### ISSUE TITLE
man 1 nix

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nix#1950]
```
$ man nix
No manual entry for nix
```

nix help output:
> For full documentation, run `man nix` or `man nix-<COMMAND>`.

The help output lists all commands in alphabetic form, maybe the manpage could group them into `porcelain` and `plumbing` (like Git does) and elaborate a bit.

Stuff like `build`, `eval`, `repl` and `store` is porcelain, while `add-to-store`, `hash-path` and the like are plumbing.

**Comment by samueldr** [comment]
> By default, man will try to interpret pairs of manual page names given on the command line as equivalent to a single manual page name containing a hyphen or an underscore. This supports the common pattern of programs that implement a number of subcommands, allowing them to provide manual pages for each that can be accessed using similar syntax as would be used to invoke the subcommands themselves. For example:
>  
> ```
> $ man -aw git diff
> /usr/share/man/man1/git-diff.1.gz
> ```

**Comment by bhipple** [comment]
What's the status of CLI documentation and manpages for Nix 2.0 CLI commands?  I noticed that a command like `nix-store --help` opens up the man page, which is rich with detail, while the nix 2.0 commands are comparatively terse.  For example, the `optimise` section of `nix optimise --help` just says:

```2
Usage: nix optimise-store <FLAGS>...

Summary: replace identical files in the store by hard links.

Examples:

  To optimise the Nix store:
  $ nix optimise-store

Note: this program is EXPERIMENTAL and subject to change.
```
while the original says:
```
OPERATION --OPTIMISE
   Synopsis
       nix-store --optimise

   Description
       The operation --optimise reduces Nix store disk space usage by finding identical files in the store and hard-linking them to each other. It
       typically reduces the size of the store by something like 25-35%. Only regular files and symlinks are hard-linked in this manner. Files are
       considered identical when they have the same NAR archive serialisation: that is, regular files must have the same contents and permission
       (executable or non-executable), and symlinks must have the same contents.

       After completion, or when the command is interrupted, a report on the achieved savings is printed on standard error.

       Use -vv or -vvv to get some progress indication.

   Example
           $ nix-store --optimise
           hashing files in `/nix/store/qhqx7l2f1kmwihc9bnxs7rc159hsxnf3-gcc-4.1.1'
           ...
           541838819 bytes (516.74 MiB) freed by hard-linking 54143 files;
           there are 114486 files with equal contents out of 215894 files in total
```

**Comment by edolstra** [comment]
Closing, all (?) nix subcommands have manpages now.
