### ISSUE TITLE
display download progress while doing nixos-rebuild

### ISSUE THREAD

**Issue by teto** [NixOS/nix#1952]
I use many different networks (with VPN/with proxy/with multiple routing tables/ per table rules/very lossy ones) and as such often meet network problems. Downloading a huge package from the cache while doing a `nixos-rebuild` can take a long time and without feedback can be a bit stressful. I wish `nixos-rebuild` could show some kind of progress in network speed or percentage, just to show it isn't stuck.
Instead of having 
```
copying path '/nix/store/1fd29bwafkdacskmisn1k9dj8vhd4yfk-nix-2.0pre5968_a6c0b773-man' from 'https://cache.nixos.org'...
copying path '/nix/store/7bfc02z2ayj9h73qwyrbnnzy14xgrazn-nix-2.0pre5968_a6c0b773' from 'https://cache.nixos.org'...
copying path '/nix/store/2zd1y9iij37z72ah97xmalq8j8hqq8mi-nixos-rebuild' from 'https://cache.nixos.org'...
```
we could have
`copying path '/nix/store/1fd29bwafkdacskmisn1k9dj8vhd4yfk-nix-2.0pre5968_a6c0b773-man' from 'https://cache.nixos.org'... [32/45 MB]` (that's a huge man :D)

**Comment by lheckemann** [comment]
As a workaround, do `nix build --no-link -f '<nixpkgs/nixos>' config.system.toplevel` to actually build the system before running nixos-rebuild.

**Comment by varvir** [comment]
Is this feature will be merged? well.. i think `cache.nixos.org` in my locale is slow, but thanks to `nix build --no-link -f '<nixpkgs/nixos>' config.system.toplevel` command, i found that `cache.nixos.org` is not slow... while using `nix-env` with `cache.nixos.org`, showing speed of download will be very helpful...

**Comment by lbkvu** [comment]
@lheckemann Could you please explain what `(160.0/1044.9 MiB)` means in the below picture?
![Example](https://i.imgur.com/lDLR9Ya.jpg)

**Comment by edolstra** [comment]
That's the uncompressed size.

**Comment by lbkvu** [comment]
@edolstra there are 2 numbers here. Which one is the uncompressed size?

**Comment by asbachb** [comment]
Since some time my internet connection is limited I also ran into that issue. From a users perspective who is upgrading the system sometimes quite unclear if there's still some action or download hangs.

**Comment by monomadic** [comment]
My 2c here, I am on an unstable connection in indonesia, and having come from a stable one last week, I can tell you it's like going from a working operating system to a broken one. NixOS sits there sometimes for far too long on packages and I have no idea if they've hung or not. It's taken all night just to rebuild. I highly, highly think a progress meter isn't just a nice to have, it's critical functionality when you need it.

**Comment by asbachb** [comment]
Still relevant.

**Comment by 3nt3** [comment]
bump?

**Comment by edolstra** [comment]
This is really an issue for the nixpkgs repo (which is where `nixos-rebuild` lives). It could use `nix` (which has a progress indicator) once it's no longer experimental.

**Comment by asbachb** [comment]
@edolstra Is there a possibility to activate this somehow? I'm still missing some kind of progress indicator when performing `nixos-rebuild switch`.
