### ISSUE TITLE
eval-only not documented in manpage of Nix 1.*

### ISSUE THREAD

**Issue by coretemp** [NixOS/nix#1960]
This does execute, but it uses the undocumented `--eval-only`.
`nix-instantiate --eval-only '<nixpkgs/nixos>' -A config.system.nixosVersion`

To reproduce:
`man nix-instantiate`, `/`, `eval-only`, `RET`

**Comment by fricklerhandwerk** [comment]
`--eval-only` was renamed to `--eval`. I suppose the old flag was left for compatibility.
