### ISSUE TITLE
Nix 2.0 regression: nix-channel --update does not work with HTTP authentication

### ISSUE THREAD

**Issue by ledettwy** [NixOS/nix#1962]
(somewhat related to: https://github.com/NixOS/nix/issues/1961)

nix-channel --update is not updating my channel if I enable HTTP authentication on the channel.  I've tried both putting the username and password in the URL (`https://username:password@host`) and using Nix's netrc-file option, but both yield the same behavior:

<pre>
$ nix-channel --update mychannel
unpacking channels...
$
</pre>

The command returns success (0), but manually inspecting `/nix/var/nix/profiles/per-user/root/channels/mychannel/` is showing an outdated version.

Disabling the authentication on the nginx instance causes nix-channel --update to actually update the channel.

This issue does not occur with nix-channel from 1.11.

**Comment by dtzWill** [comment]
The `netrc-file` option seems to work here-- since 1.11 through 2.0.  (`username:password@` was problematic on 1.11 for forgotten reasons that motivated switching to that a while back and it's worked since including 2.0 these days)

Maybe give that route another shot? If it doesn't work try using strace or "-vvvvv" to see what's going on?

**Comment by ledettwy** [comment]
@dtzWill nix-channel dosn't seem to have a "-v" flag.  Do you have test results that show channel files getting updated with netrc-file containing the authentication information?

I mentioned this in the other issue as well - netrc-file can't be the long-term solution to this, since the same hostname might host several different channels, each with different authentication details, and netrc-file's smallest level of granularity is one set of authentication details per hostname.

**Comment by ledettwy** [comment]
OK, tarball-ttl was the problem, and was influencing the results of my experiments. It has nothing to do with authentication. I'll open a new issue.
