### ISSUE TITLE
Bug: passing NULL (and null-derived) to memcpy() (via ubsan)

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nix#1976]
```
$ echo "[] ++ []"|./ubsan-gnu/bin/nix repl
Welcome to Nix version 2.0dtz0_0000000. Type :? for help.
 
src/libexpr/eval.cc:1319:16: runtime error: null pointer passed as argument 1, which is declared to never be null
/nix/store/p85kjy91dfvs4in358zyfxlksvibw0zn-glibc-2.26-131-dev/include/string.h:43:28: note: nonnull attribute specified here
src/libexpr/eval.cc:1319:27: runtime error: null pointer passed as argument 2, which is declared to never be null
/nix/store/p85kjy91dfvs4in358zyfxlksvibw0zn-glibc-2.26-131-dev/include/string.h:43:28: note: nonnull attribute specified here
[ ]
```

Looks like the code at the above locations expects listElems() to always be non-null,
which is not the case when the list is empty:

https://github.com/NixOS/nix/blob/14ca85688cdd17dfcf4b2bd8c324f21d6f3d1dde/src/libexpr/eval.cc#L606

BTW, whoever is doing the fuzzing efforts might want to fuzz builds instrumented with ubsan or asan.

**Comment by dtzWill** [comment]
More instances of this:

```
src/libexpr/primops.cc:1605:12: runtime error: null pointer passed as argument 1, which is declared to never be null
/nix/store/p85kjy91dfvs4in358zyfxlksvibw0zn-glibc-2.26-131-dev/include/string.h:43:28: note: nonnull attribute specified here
src/libexpr/primops.cc:1605:33: runtime error: null pointer passed as argument 2, which is declared to never be null
/nix/store/p85kjy91dfvs4in358zyfxlksvibw0zn-glibc-2.26-131-dev/include/string.h:43:28: note: nonnull attribute specified here
src/libexpr/primops.cc:1609:12: runtime error: null pointer passed as argument 1, which is declared to never be null
/nix/store/p85kjy91dfvs4in358zyfxlksvibw0zn-glibc-2.26-131-dev/include/string.h:43:28: note: nonnull attribute specified here
src/libexpr/primops.cc:1609:33: runtime error: null pointer passed as argument 2, which is declared to never be null
/nix/store/p85kjy91dfvs4in358zyfxlksvibw0zn-glibc-2.26-131-dev/include/string.h:43:28: note: nonnull attribute specified here
```

(just pointing instrumented Nix at various `release.nix` files, these were from NixOS's release-small.nix)

**Comment by dtzWill** [comment]
This is undefined behavior, even when (as I believe happens here) the third parameter is 0.

While it is doubtful to directly cause problems (as evidenced by lack of crashing Nix all the time),
compilers can and do make assumptions regarding absence of undefined behavior
and may produce unexpected / broken code as a result.

**Comment by shlevy** [comment]
IMO this is a glibc bug, not a Nix one. From the [last C11 draft spec](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf):

> The memcpy function copies n characters from the object pointed to by s2 into the object pointed to by s1. If copying takes place between objects that overlap, the behavior is undefined.

We may as well fix it, but I don't think glibc is correct to require non-null.

**Comment by shlevy** [comment]
Ah, never mind:

> Where an argument declared as size_t n specifies  the  length  of  the  array  for  a function, n can  have  the value zero on a call to that function. Unless explicitly stated otherwise in the description of a particular function in this subclause, pointer arguments on  such  a  call  shall  still  have  valid  values,  as described in 7.1.

Then from 7.1:

> If an argument to a function has an invalid value (such as... a null  pointer...)... the behavior is undefined

**Comment by dtzWill** [comment]
Thanks!!

There are additional instances to be fixed however, don't think we can close this just yet.

**Comment by shlevy** [comment]
Ah sorry! I'll get those.

**Comment by dtzWill** [comment]
Awesome, thanks!
