### ISSUE TITLE
TTL for failed builds

### ISSUE THREAD

**Issue by rbvermaa** [NixOS/nix#198]
Copied from Hydra#139. @edolstra can this be implemented in nix?

---

It happens quite frequently that some build breaks with a transient failure on some Hydra machine. The most recent example is GHC on i686. The only solution in these situations is to whine on the mailing list and hope that some hydra admin will restart the failed build.

It'd be much better to have a TTL for negative build caching and retry failed builds e.g. every week at least once even if the derivation didn't change. That would ensure that transient errors get fixed even without manual intervention.

**Comment by edolstra** [comment]
Closing because Nix no longer does any build failure caching.
