### ISSUE TITLE
builtins.fetchGit is missing from the manual

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nix#1981]
The [Nix manual](https://nixos.org/nix/manual/) has a list of builtins that seems to be missing `fetchGit`.

The only thing I've really found about it is in the changelog, which links to [this commit](https://github.com/NixOS/nix/commit/38539b943a060d9cdfc24d6e5d997c0885b8aa2f). That commit message sort of has some documentation in it, but I don't think it's correct. It includes this example:

```nix
 (import (builtins.fetchgit {
    url = git://github.com/NixOS/nixpkgs-channels;
    rev = "nixos-16.03";
  }) {}).hello
```

I tried running something like this (fixing the capitalization because the real name seems to be `fetchGit`, not `fetchgit`), but it fails:

```
error: invalid Git revision 'nixos-18.03'
```

I then tried a commit hash

```nix
builtins.fetchGit {
  url = git://github.com/NixOS/nixpkgs-channels;
  rev = "622c5bebbea0b55b615214082a493e4288e1843d";
}
```

but this fails with

```
fatal: Couldn't find remote ref master
error: program 'git' failed with exit code 128
```

This seems odd to me, since I never mentioned `master` anywhere... but I'm just guessing at what the arguments to this function are. I was hoping I could figure this out myself, but I guess `functionArgs` doesn't work on builtins:

```
nix-repl> builtins.functionArgs builtins.fetchGit
error: 'functionArgs' requires a function, at (string):1:1
```

**Comment by shlevy** [comment]
Will try to get this done in the next week or so.

**Comment by dtzWill** [comment]
The bit about master was a bug, your usage is correct.  This was fixed with e89d02bf031277bd81a8ce255f49d352763e5c71.

For the nixos-18.03 you should set `ref = "nixos-18.03"`, since it's a reference not a revision.

Of course documentation is needed, but thought I'd try to clear up in the meantime.

**Comment by nomeata** [comment]
It seems that `fetchGit` support many more options than documented in the manual, including important stuff like `sha256`, but also others, according to https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/fetchgit/default.nix. It would be nice if they were also documented in the manual.

**Comment by grahamc** [comment]
These are two different fetch gits.

**Comment by domenkozar** [comment]
yes probably best to open nixpkgs issue, as pkgs.fetchGit is not even documented.
