### ISSUE TITLE
Multi-user installer (macOS) should support upgrades

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nix#2016]
Currently we advertise the upgrade process as this in Nixpkgs:

```
    This version of Nixpkgs requires Nix >= ${requiredVersion}, please upgrade:
    - If you are running NixOS, use `nixos-rebuild' to upgrade your system.
    - If you installed Nix using the install script (https://nixos.org/nix/install),
      it is safe to upgrade by running it again:
          curl https://nixos.org/nix/install | sh
```

This works fine for single-user installs, but this does not work for multi-user installs (like is done by default for macOS). We need an easy process to upgrade the nix version. Currently this is my easiest way to update Nix on multi-user installs:

```
sudo -i sh -c 'nix-channel --update && nix-env -iA nixpkgs.nix'
sudo launchctl stop org.nixos.nix-daemon
sudo launchctl start org.nixos.nix-daemon
```

Note that ```-i``` is required for this to work. Please resolve this before merging NixOS/nixpkgs#37693!

/cc @grahamc @lnl7

**Comment by matthewbauer** [comment]
A more succinct way to upgrade Nix would be:

```
sudo -i sh -c 'nix-channel --update && nix-env -iA nixpkgs.nix'
launchctl kickstart -k org.nixos.nix-daemon
```

**Comment by LnL7** [comment]
I'm pretty sure an unload/load is required to update the paths and possibly new other options like https://github.com/NixOS/nix/pull/1920/commits/05cb8e5c5a954fa999ac5156cdf19148a05fdb2b, but I really like the idea.

**Comment by jtojnar** [comment]
Could we update the error message for now?

**Comment by matthewbauer** [comment]
This was resolved.
