### ISSUE TITLE
Allow nix-store --add-fixed to specify a hash

### ISSUE THREAD

**Issue by bgamari** [NixOS/nix#2019]
It is currently impossible to add large files to the store due to limitations of `nix`'s hashing mechanism. One useful feature that would alleviate much of the pain caused by this would be to allow the user to add files to the store with a given hash. For instance, one could,
```
$ nix-store --add-fixed --hash-algo sha256 --hash $(sha256 huge-file) huge-file
```
This would free nix from the need to hash the file.

CCing @shlevy, who suggested this mechanism.

**Comment by bgamari** [comment]
Note that `nix-prefetch-url` could also take such an option.

**Comment by grahamc** [comment]
Seems Nix would still need to validate the output anyway, no?

**Comment by Pitometsu** [comment]
+1
Use case: I need a huge (not so, ~2Gb) local directory as a dependency. There's no way to add it to store for now, afaik. I'm able to calculate hash though:  `nice nix-hash --type sha256 --base32 $ARTIFACT_PATH`.

And
```
nix-store --recursive --add-fixed sha256 $ARTIFACT_PATH
warning: dumping very large path (> 256 MiB); this may run out of memory
error: out of memory
```

I guest, it would be useful to be able to reuse that hash there (I expect that coping memory usage is less than linear of file size, so, I guess, it should be copied without any problem with proper hash).

BTW Should I create separate feature request for ability to handle big sources without huge memory usage and such warnings, or it will be ok to just leave it here?

**Comment by Pitometsu** [comment]
Also I found that source of wiki page, but didn't found it anywhere in actual documentation.
https://raw.githubusercontent.com/deepfire/nixos-wiki/master/How%20to%20add%20large%20files%20to%20the%20nix-store.page
Is it actual yet? (Perhaps, no, `nix-store` has no such option as `--print-fixed-path` for now). Any updated guide anywhere?

**Comment by mx00s** [comment]
I recently ran into the out of memory failure while using `nix-prefetch-url` on a large data set archive (~35GB).

After setting `TMPDIR` to a non-tmpfs mounted path and rerunning, the file downloaded successfully. However, soon after the file finished downloading, the process crashed again with "error: out of memory". I'm guessing it ran out of memory while computing the hash.

The same machine was able to successfully execute these commands in about 3m:

```bash
$ fallocate -l 35G ~/tmp/large-file
$ sha256sum ~/tmp/large-file
622e4f287f9840f147bc9e07594c3f01226338d6a609c58017c00d629434bc2d  /home/sage/tmp/large-file
```

Is it well understood yet where the space bottleneck lies? If so, is there some fundamental reason these commands can't be more memory-efficient?

**Comment by tpwrules** [comment]
This should be fixed by at least Nix 2.11.1.

**Comment by tomberek** [comment]
Closing as fixed.

**Comment by con-f-use** [comment]
I'm confused :grin: ? What is the fix? I see no linked merge or anything.
