### ISSUE TITLE
nix run doesn't set IN_NIX_SHELL

### ISSUE THREAD

**Issue by ElvishJerricco** [NixOS/nix#2020]
Title. My shell prompt is set to look different when IN_NIX_SHELL is set, and I have `nix-shell` aliased to include my prompt. Since `nix run` doesn't set `IN_NIX_SHELL`, I often have a hard time remembering if my shell is a `nix run` or not.

**Comment by edolstra** [comment]
It's not clear whether it *should* set `IN_NIX_SHELL`, because `nix run` serves a different purpose than `nix-shell` (it doesn't provide a development environment).

**Comment by ElvishJerricco** [comment]
@edolstra I guess that just depends on the intended semantics of `IN_NIX_SHELL`, and whether we plan to eventually have a mode of `nix run` for development environments.

Regardless, at least *something* should be set.

**Comment by ElvishJerricco** [comment]
I've since found that `$SHLVL` is more appropriate for what I was using `$IN_NIX_SHELL` for. I'll close this, as it doesn't seem to be desired.

**Comment by giodamelio** [comment]
Just running this into myself, it would be nice to have some way to tell.

**Comment by ElvishJerricco** [comment]
@giodamelio Does `SHLVL` help? I found it useful for more than just `nix run`; now I know *any* time I'm in a nested shell, not just a `nix run`.

**Comment by giodamelio** [comment]
That won't really work for what I am doing. I want to simply display a
thing in my prompt when I am in a Nix shell, not when I am in a nested
shell. For example the SHLVL gets incremented when I am in a tmux session
(which makes sense), but it doesn't have anything to do with Nix
specifically.

**Comment by fgaz** [comment]
I ran into this too. I have different prompts for different kinds of subshells, but I have no way to tell the difference from `nix run` and a simple subshell

**Comment by timor** [comment]
Couldn't `nix run` set a different variable, let's say `IN_NIX_RUN`, or have it's own nesting counter?

**Comment by pinpox** [comment]
> Couldn't `nix run` set a different variable, let's say `IN_NIX_RUN`, or have it's own nesting counter?

+1 for this. I'd like to have some way to display it in the prompt e.g. when entering a shell with `nix shell 'nixpkgs#hello'` 
 to fix this https://github.com/starship/starship/issues/2950

**Comment by fgaz** [comment]
Related: #3862
