### ISSUE TITLE
.DS_Store is another forbidden path 

### ISSUE THREAD

**Issue by clacke** [NixOS/nix#2031]
This is another case like #1443 . `.DS_Store` is also a forbidden path:

```
error: cannot link '/nix/store/.links/09rh4zm18xnljq0xk6xdm80rgc3dx667gx5zm7cqh4avbjp7n38h' to '/nix/store/x2w7b8fp98kxb7ndbb2fdiqpmqa4hgsz-electron-1.8.2/Applications/Electron.app/Contents/Frameworks/Squirrel.framework/.DS_Store': Operation not permitted
```

This is when running `nix optimise-store` on:

 - system: `"x86_64-darwin"`
 - host os: `Darwin 16.7.0, macOS 10.12.6`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0`
 - channels(clacke): `"nixpkgs"`

**Comment by matthewbauer** [comment]
If only Apple would document this! But I definitely think a PR adding ".DS_Store" regex would be accepted.

**Comment by clacke** [comment]
Hint taken. :-)

**Comment by matthewbauer** [comment]
I actually don't think it's .DS_Store but the ".app/Contents/" part that is breaking things. .DS_Store shouldn't be in paths anyway.

**Comment by clacke** [comment]
`.DS_Store` is there in some framework on nixpkgs/darwin. I don't know macOS enough to know if it needs to, and I'm not on that computer right now. My patch didn't work -- it still tried to collect it. I ran the patched Nix both for nix-daemon and nix CLI. I'll try your update when I'm back on that computer.

**Comment by copumpkin** [comment]
.DS_Store generally appears after you browse to a location in the finder, and it drops the file there to record its settings for that folder. I'd be surprised if the files were naturally there on a vanilla untouched Mac, but they definitely start showing up after you browse around the filesystem in Finder a bit.
