### ISSUE TITLE
Multi-user install: allow /nix to exist

### ISSUE THREAD

**Issue by jbgi** [NixOS/nix#2042]
Currently multi user installer requires that `/nix` is absent.
However there are many case where one would want to `/nix` to be a mount point, so the installer should just check/ensure it has correct access rights (and modify them if needed).

Cleanup instruction also need to be updated accordingly.

**Comment by fiksn** [comment]
It would be great if it was possible to run the installer on top of any state in a truly idempotent way. It is really frustrating that first time I forgot --daemon and then I had to manually edit bashrc, zshrc & co just to be able to run it again. Sure better safe than sorry, but perhaps for start there could just be a 'force' flag to warn and not stop with an error.

**Comment by abathur** [comment]
This can be closed; the core issue was fixed in #3054.

**Comment by abathur** [comment]
For the record, I noticed after commenting on this one that despite #3054 getting merged, the commit that fixed this issue hasn't made it into 2.3-maintenance. 

So, this is "fixed", but you'll still see this on current installers until that is either cherry picked or there's a new release from master.
