### ISSUE TITLE
`nix repl` and multiline strings

### ISSUE THREAD

**Issue by Ekleog** [NixOS/nix#2057]
`nix repl` appears to have a weird understanding of multiline strings:
```nix
$ nix repl
nix-repl> ''
            foo
            bar
          ''
"foo  bar"
```

While the old `nix-repl` had a behaviour that I deem more sensible:
```nix
$ NIX_REMOTE=daemon nix-repl
nix-repl> ''
            foo
            bar
          ''
"foo\nbar\n"
```

Hope that helps and thanks as always!

**Comment by shlevy** [comment]
Assigned to myself in lieu of being able to assign to @dtzWill . Will are you able to fix this or should I find another assignee?
