### ISSUE TITLE
bison required for building from 2.0 source

### ISSUE THREAD

**Issue by IohannesArnold** [NixOS/nix#2065]
While trying to build nix from source off the 2.0 tarball, neither bison nor flex were present on my system because the manual says:

> [bison and flex] are only required if you modify the parser or when you are building from the Git repository

The configure script noticed that bison and flex were not present and did not complain. However, immediately after running make I get:
```
/bin/sh: 1:  bison: not found
```

I dunno if this is a problem with the configure script, the Makefile, or the particularities of the Linux-From-Scratch-ish system I'm trying to hack together, but I thought I'd raise the issue here. I'm happy to do my best to fix this myself, but I don't even know what's normative here: **ought** I be able to get away with this or are bison and flex now build-time deps for everyone and the docs and autoconf need to be updated?

**Comment by edolstra** [comment]
Yes, this is suposed to work. In fact the Nix expression for Nix 2.0 in Nixpkgs doesn't pass `bison` and `flex` as build inputs.
