### ISSUE TITLE
nix log requires an attr path

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nix#2066]
nix log shouldn't complain if it doesn't get an attr path argument — it should just try and get the log of the derivation at the top level of the file so that `nix build -f foo.nix` can just be changed to `nix log -f foo.nix`.

**Comment by dtzWill** [comment]
Note that `nix log` accepts things like a `./result` (when `./result` is a symlink such as produced by `nix-build` and friends), which `nix build` does not.  It would be "nice" if these all worked:

* `nix log /nix/store/hhaasshh-name`
* `nix build $ARGS` <--> `nix log $ARGS` worked (as you suggest)
* `nix log ./result` worked (currently does)
* `nix log result` worked (maybe) when `./result` exists, but I think this might not be what everyone wants

**Comment by lheckemann** [comment]
FWIW `nix log -f foo.nix ''` works.

**Comment by bobvanderlinden** [comment]
Please see whether #2340 is the right solution for this problem.

**Comment by edolstra** [comment]
Closing since the empty attribute `""` is no longer needed since the flakes branch was merged.
