### ISSUE TITLE
"waiting for locks or build slots" is not a very helpful message

### ISSUE THREAD

**Issue by LisannaAtHome** [NixOS/nix#2069]
I think the message that nix prints when something is blocking the build could be a bit more descriptive. "waiting for locks or build slots" does not indicate whether there is a resource problem that the user needs to go fix (let alone what the resource problem is), or whether the same build is already underway by another process. Even turning the logging up to vomit doens't yield anything particularly insightful.

**Comment by 7c6f434c** [comment]
Possibly related: it _is_ possible to run multiple Nix instances in parallel as root and get an error (instead of blocking to wait for build slots) after running out of build users.

**Comment by shlevy** [comment]
@ledettwy Any interest in providing a patch, or suggested output at least?

**Comment by domenkozar** [comment]
See #1216

**Comment by balsoft** [comment]
See #3577

**Comment by balsoft** [comment]
This should be resolved in 5ed5d7acbd00298df7b4e3a638d731143084da2e
