### ISSUE TITLE
nix-shell shebang won't work with withPackages

### ISSUE THREAD

**Issue by teto** [NixOS/nix#2072]
This is really annoying, for instance this won't work 
```
#! /usr/bin/env nix-shell 
#! nix-shell -p 'python.withPackages(ps:with ps;[secretstorage keyring ])' ~/nixpkgs -i sh
```
You get a 
`syntax error, unexpected $undefined, at (string):1:94`

If you remove spaces on the 2nd line (works only if you have 1 package) than it works

```
#! /usr/bin/env nix-shell 
#! nix-shell -p python.withPackages(ps:[ps.keyring]) ~/nixpkgs -i sh
```
 is fine

**Comment by edolstra** [comment]
The problem is actually 'ps:with', which gets parsed as a URL. Try putting a space in between
```
nix-shell -p 'python.withPackages (ps: with ps; [secretstorage keyring ])'
```
