### ISSUE TITLE
isFunction returns `false` for `primop-app`

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nix#2073]
```
nix-repl> builtins.builtins.isFunction map
false
nix-repl> builtins.typeOf map
"lambda"
nix-repl> map
«primop»

nix-repl> builtins.builtins.isFunction (map (v: v))
false
nix-repl> builtins.typeOf (map (v: v))
"lambda"
nix-repl> map (v: v))
«primop-app»
```

https://github.com/NixOS/nix/blob/master/src/libexpr/primops.cc#L247-L251
https://github.com/NixOS/nix/blob/master/src/libexpr/primops.cc#L270-L275

I’d posit the primop/lambda distinction should be transparent on the nix expression level, `isFunction` should return `true` for `map` as well as `map id`.

cc @cleverca22

**Comment by ledettwy** [comment]
Duplicate of https://github.com/NixOS/nix/issues/1424

**Comment by shlevy** [comment]
@Profpatsch Any interest in giving a patch a shot?

**Comment by Profpatsch** [comment]
@shlevy Ah, I’m sorry, I really don’t have enough C++ experience to fix this in any acceptable timeframe.

**Comment by Profpatsch** [comment]
Thanks!
