### ISSUE TITLE
nix edit does not handle spaces in EDITOR correctly

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nix#2079]
I have `EDITOR` set to `emacs -nw`. `nix edit` does not split this:

```
nix edit nixpkgs.hello
error: cannot run editor 'emacs -nw': No such file or directory
```

**Comment by dezgeg** [comment]
Do other apps split it either? IIRC there was some bug open in Nixpkgs where the default `PAGER='less -R'` causes trouble to many programs.

**Comment by edolstra** [comment]
In my experience most programs do split it.

**Comment by coretemp** [comment]
Since there is no standard for EDITOR (POSIX mentions it, but that's it), the fix should include an environment variables section in which EDITOR's influence on the program NIx is documented.
