### ISSUE TITLE
exportReferencesGraph is impure

### ISSUE THREAD

**Issue by ledettwy** [NixOS/nix#2082]
exportReferencesGraph can be used to introduce impurities into a build when an input has its string context discarded.

If a /nix/store path string is passed into it without the proper string context (i.e., should not be part of the included sandbox paths), exportReferencesGraph seems perfectly happy to lookup the closure of the path and provide those to your build - as long as those paths physically exist. If the specified paths don't already exist on your system, then the below error will be thrown:

https://github.com/NixOS/nix/blob/d34fa2bcc3572fafc893755cee19d97aed7ec649/src/libstore/build.cc#L1745

This introduces an impurity into the build, since the success of the build becomes dependent on whether or not the unsafe path already exists on the system. I think the correct behavior in this case should be a fatal error in all cases of attempting to get the references graph of a /nix/store path that is not in your build's closure.

**Comment by shlevy** [comment]
Eh... I agree this could be a bit more consistent, but I'm not sure how important it is to ensure purity in the case where we discard contetxt.

**Comment by ledettwy** [comment]
I thought the "unsafe" part of unsafeDiscardStringContext was that it might break your build, not that it can be used to introduce build impurities. The bug here is that exportReferencesGraph has too much power. IMO discarding a string context should cause a build to be more likely to fail, not more likely to succeed.

If part of a build involves downloading a file from the Internet that has /nix/store paths in it, and those get put through exportReferencesGraph, you'll be in the same situation.

Nix has builtins that let you circumvent the normal purity protections, like builtins.pathExists, and if you use those then you should know what you're getting into. But I don't think exportReferencesGraph was ever intended to be an "abusable" feature like this.
