### ISSUE TITLE
Trusted substituters stopped working in NixOS 18.03 / Nix 2.0

### ISSUE THREAD

**Issue by chreekat** [NixOS/nix#2088]
I was happily using nix.trustedBinaryCaches and nix.binaryCachePublicKeys on NixOS 17.09 in order to add a local substituter to build commands for a project. I was not listed as a trusted user.

After upgrading to 18.03, this stopped working. I had to add myself as a trusted user as a workaround.

I consider this a Nix issue because NixOS is setting the correct options in /etc/nix/nix.conf:

```
substituters = https://cache.nixos.org/
trusted-substituters = <local-substituter>
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=  <local-key>
```

I am using these trusted substituters like this:

```
$ nix-shell --option binary-caches "https://cache.nixos.org <local-substituter>"
```

**Comment by shlevy** [comment]
@chreekat What happens when you use `--option substituters` instead?

**Comment by chreekat** [comment]
Same:

    nix-build --option substituters "https://cache.nixos.org http://<local-cache>"
    warning: ignoring untrusted substituter 'https://cache.nixos.org'
    warning: ignoring untrusted substituter '<local-cache>'
    building '/nix/store/n8xhdhlriq0w5xb27m0186292p079zxs-source.drv'...

**Comment by dtzWill** [comment]
Was this perhaps fixed along with #1921?

**Comment by chreekat** [comment]
Unlikely. Looking at the fix, all that changed is dynamically loading information supplied to the daemon by a trusted user after startup. This issue is about the daemon ignoring statically-configured info.

**Comment by yorickvP** [comment]
Perhaps you forgot the / that you did put in the config file?
`nix-build --option substituters "https://cache.nixos.org/ http://<local-cache>/"`

It's still working for me on 2.0 and master.

**Comment by nicknovitski** [comment]
I believe I'm having the same problem, though I've only been testing it with an s3 substituter.
```
$ nix-build --version
nix-build (Nix) 2.0.4
$ cat ~/.config/nix/nix.conf
require-sigs = false
trusted-substituters = s3://<bucket>?region=us-west-1
extra-substituters = s3://<bucket>?region=us-west-1
$ nix-build -A whatever
warning: ignoring untrusted substituter 's3://<bucket>?region=us-west-1'
```

**Comment by unode** [comment]
Seeing the same when trying to install [cachix](https://cachix.org/).
```
nix-env -if https://github.com/cachix/cachix/tarball/master --substituters https://cachix.cachix.org --trusted-public-keys cachix.cachix.org-1:<hash>
```

The public key hash has a `/` in it if that affects it in any way.

**Comment by nicknovitski** [comment]
Ah, I also get the error when running the command above, but only on darwin.  It seems to work on linux.

**Comment by LnL7** [comment]
@nicknovitski That's probably something different, I think that doesn't have caches for darwin and `--option substituters` disables cache.nixos.org.

**Comment by unode** [comment]
To confirm, I'm on NixOS 18.03 with nix 2.0.2

**Comment by domenkozar** [comment]
Could you try following workaround: https://github.com/cachix/cachix/issues/26#issuecomment-395516170

**Comment by unode** [comment]
@domenkozar yes that worked.

**Comment by domenkozar** [comment]
I'm pretty confident this was fixed by #1921, @chreekat could you try with newer Nix and make sure you're using a trusted user?

**Comment by chreekat** [comment]
@domenkozar everything already works when I'm a trusted user. :) The error case is:

1. Not a trusted user
2. /etc/nix.conf:
    ```
    trusted-substituters = <local-substituter>
    trusted-public-keys = cache.nixos.org-1:...  <local-key>
    ```
3. `nix-shell --option binary-caches "https://cache.nixos.org <local-substituter>"`

This worked on 17.09, but didn't work on 18.03.

None of the other problems listed in this thread are actually duplicates, afaict.

Is there any reason this shouldn't be possible as a non-trusted user?

**Comment by PombeirP** [comment]
No more developments on this? I'm hitting the same issue.

**Comment by chreekat** [comment]
Update: I don't have this issue anymore. I'm on 19.03 now, fwiw.

@PombeirP fyi

Note that, as far as I can tell, you *must* add a trailing slash whenever you refer to a substituter's url. This seems like a (different) bug.

Since trusted substituters work for me now, I'm gonna close this issue.
