### ISSUE TITLE
Option to specify path used by nix-daemon and builders (for non-NixOS use)

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nix#2098]
Currently Nix looks to various environment variables --particularly `TMPDIR` -- as indications of what paths should be used for things such as scratch used by builder processes.

Builds can require significant disk space, and especially when performing many builds concurrently it's not hard to run out of space on `/tmp` as traditionally configured.

This issue isn't about whether `$TMPDIR` is the "right" place for this use (AFAIK it is? dunno), but unfortunately it's common for `/tmp` to be too small for Nix's use.  Or at least it is for me, which is of course why i'm filing this issue :).

No big deal: Nix respects `$TMPDIR` (and some other locations with some ordering) and indeed I used to resolve my problems with this by simply setting TMPDIR in the environment of the script launching `nix-daemon`.

Now that I have a newer system using systemctl, this no longer seems to be reasonably possible?
(or maybe I'm bad at systemd? :P)

Editing the service file to contain `Environment=TMPDIR=/path/to/nix-tmp` would work... except that this file is symlinked from the store into its place in `/etc`-- so it shouldn't be modified (and will always point to the right `nix`'s service file, JIC it matters).

To mitigate this, how about some sort of nix option (the sort specified in `nix.conf` or via `--option`) that allows specifying path used for at least the primary use of TMPDIR/XDG_RUNTIME_DIR in Nix: build paths.
If specified, this option would probably be preferred over environment variable paths (and of course preferred over the fallback to `/tmp`).

How's that sound? Thoughts?

**Comment by dezgeg** [comment]
Shouldn't the systemd unit files be installed so that the default configuration for the units is in `/usr/lib/systemd/system/foo.service` while `/etc/systemd/system/foo.service` stays available for the sysadmin to configure?

**Comment by shlevy** [comment]
I have this in my configuration.nix and it works fine:

> services.nix-daemon.environment.TMPDIR = "/nix/tmp";

It results in `/etc/systemd/system/nix-daemon.service.d/overrides.conf` with that env setting (among some other things)

**Comment by dtzWill** [comment]
> Shouldn't the systemd unit files be installed so that the default configuration for the units is in /usr/lib/systemd/system/foo.service while /etc/systemd/system/foo.service stays available for the sysadmin to configure?

That sounds great to me! I really don't know how these things "should" work.  But I can try to chase down the relevant documentation or look at how other folks do it if we're unsure....
Or take your word for it, which I'm inclined to do unless you say that's unwise :).

-----

> I have this in my configuration.nix and it works fine:
> 
> services.nix-daemon.environment.TMPDIR = "/nix/tmp";
> 
> It results in /etc/systemd/system/nix-daemon.service.d/overrides.conf with that env setting (among some other things)

Interesting--i hadn't thought to try that--but unfortunately I don't think helps me because the system in question is not NixOS :(.  I somehow completely failed to mention that important fact!

Will edit accordingly shortly, sorry :3.

**Comment by shlevy** [comment]
The overrides.conf thing isn't NixOS specific though...

**Comment by dtzWill** [comment]
> The overrides.conf thing isn't NixOS specific though...

!!!

I'm sorry, I missed that part :(.  Dishonor on me and my family.

I'll look into that, thank you!

-----

Quick bounce through documentation does seem to confirm that we shouldn't be putting immutable things in `/etc` anyway (and now that I say it like that, "duh!" hehe), they should be in `/lib/systemd` or so.

Will check out the overrides, thanks for the tip!

**Comment by dtzWill** [comment]
Ah jeez it's worse than I feared, haha, guess what?

* `$ sudo systemctl edit nix-daemon.service`
* use editor to add overrides, something like:
```
[Service]
Environment=TMPDIR=/path/to/nix-tmp
```
* save

And I suppose `systemctl daemon-reload` and restart or whatever (not sure how to force systemd to restart all existing processes, so I just kill them to ensure the new values "take").

Easy-peasy, TIL!

Happy to hear it too--the primary motivation was "there doesn't seem to be another way"-- my mistake!

Thanks folks!

**Comment by AleXoundOS** [comment]
> I have this in my configuration.nix and it works fine:
> 
> > services.nix-daemon.environment.TMPDIR = "/nix/tmp";

Nowadays, it should be:
```
  systemd.services.nix-daemon.environment.TMPDIR = "/nix/tmp";
```

And after nixos-rebuild it results in:
```
$ systemctl cat nix-daemon.service | grep TMPDIR
Environment="TMPDIR=/nix/tmp"
```

However, nix-build still uses `/tmp/`.

```
$ nix --version
nix (Nix) 2.3.16
```

**Comment by anand-rafay** [comment]
Any inputs on how this can be achieved in a Mac OS??
