### ISSUE TITLE
Nix with custom store

### ISSUE THREAD

**Issue by Ekleog** [NixOS/nix#2107]
So far as I understand, having `nix` with a custom store is currently a pain: it requires recompiling nix, and then all the packages of the binary cache don't fit any longer.

I want to put forward two ideas for improving the story of nix with custom store paths (which are required eg. when not having root rights on a system and wanting to install nix in `$HOME/nix`)

# ~~Add a `--store` option~~
(Hadn't looked down until environment variables in the man pages, please disregard this section)

~~The first feature is to add `--store` and `--var` options to nix commands.~~

~~If not running with a daemon, the `--store` option is used to select the location of the store.~~

~~If running with a daemon, the `--store` option of the daemon tells him where to find the store and related files, and the `--store` option of the commands would be ignored (with a warning/error message). The `--var` option of the commands allow to tell them where to find the daemon.~~

~~`--store` would default to `/nix/store`, and `--var` to `/nix/var`.~~

~~The reason for having two separate options is to handle the case where I want to have a store path that's exactly 10 characters long and only have access to eg. `/tmp` (yes, I know of at least one system where I wanted to run nix where the only place big enough was `/tmp`), thus having `/tmp/store` and `/tmp/var` enforced would cause conflicts.~~

~~The reason for the 10-characters long comes just after~~

# Add a `pretendStoreIsAt` option to `builtins.derivation`

In order not to have to rebuild the world, a solution could be to (beware, gross hack incoming) just pick another 10-characters long path name and `sed` the packages.

In order not to introduce such a hack into `nix`, `nix` could simply add a `pretendStoreIsAt` (or whatever name, I'm lacking inspiration) option to `builtins.derivation`. This way, I could just import `nixpkgs` with an overridden `pretendStoreIsAt`, and then have a second `nixpkgs` with all builders overridden to just take packages from the first nixpkgs and `sed` the paths.

This way, the packages of the first `nixpkgs` would be downloaded from the binary substitutes, and then “fixed” to work with the new path name with the second `nixpkgs`, which I would actually use.

This wouldn't work for eg. java files (as they're compressed and thus not `sed`-able), but this can likely be worked around by looking at the place where `nix` remembers what dependencies are and, if detecting that the dependencies aren't sed-able, falling back to regular build (which would still use the non-java dependencies from the binary cache if the overlay is well-written).

# Use cases

So for the use cases, I can see at least:
 * Installing `nix` as a user when not root and having restricted access to the filesystem (required for eg. managing one's dotfiles through nix in a portable manner)
 * Installing `nix` in eg. `/opt/{nstor,nvar}` when the sysadmin insists on respecting FHS
 * Maybe other use cases I haven't thought of yet

What do you think about these two ideas of addition of configuration options?

**Comment by veprbl** [comment]
If you read man pages you can find useful ```NIX_STORE_DIR``` and ```NIX_STATE_DIR``` environment variables. There is also a real ```--store``` option that may help your case (see the manual). What you describe in the second section is not a new idea either (e.g. see #1971).

**Comment by Ekleog** [comment]
I plead guilty for `NIX_STORE_DIR` and `NIX_STATE_DIR`, I had looked through the man pages of `nix-shell` and `nix-env` looking for arguments, didn't think of checking environment variables. Thanks for the pointer!

About `--store`, it isn't documented anywhere in `man nix-shell` or `man nix-env` (and `nix --help` tells me to run `man nix` for full documentation but `man nix` tells me there is no manual entry for nix on my NixOS machine), so I hadn't any idea it existed, indeed. However, as pointed out in https://github.com/NixOS/nix/issues/1971#issuecomment-372650163, `--store` requires mountns, thus either root or userns, and debian comes with userns disabled.

As for the second idea, I'm not saying it's new, only that I couldn't find any other issue opened on the same topic. For instance, I don't think it's the same one as the one described in https://github.com/NixOS/nix/issues/1971, as with my proposal `nix` wouldn't do the hash rewriting by itself, but would just agree to download a package from a binary cache with the wrong store directory. This should allow for much more flexibility in the handling of compressed or such paths, basically allowing for the pluggable rewriting proposed by https://github.com/NixOS/nix/issues/1971#issuecomment-375326324 with minimal (and non-rewriting-specific) `nix` support.

**Comment by edolstra** [comment]
Closing this for #1971. Note that the second idea doesn't work if the store directories don't have the same length. For example, rewriting `/nix/store` to `/home/alice/nix/store` will break most binaries.
