### ISSUE TITLE
Add an infix reverse-application operator

### ISSUE THREAD

**Issue by pacien** [NixOS/nix#2118]
I couldn't find this handy pipe-like operator:
> `val (|>) : 'a -> ('a -> 'b) -> 'b`
> Reverse-application operator: `x |> f |> g` is exactly equivalent to `g (f (x))`.

Example use case:
```builtins.readDir "/dir" |> builtins.attrNames```
instead of
```buitins.attrNames (builtins.readDir "/dir")```

**Comment by copumpkin** [comment]
The extensive haskell subcommunity in Nix will probably want `$` too, if this goes in 😄

**Comment by regnat** [comment]
@copumpkin you mean https://github.com/NixOS/nix/issues/1845 ? :smile:

**Comment by copumpkin** [comment]
And before you know it, Nix will support Agda-style arbitrary mixfix operators 😄

**Comment by danbst** [comment]
```
nix-repl> let __div = x: y: y x; in
          builtins.readDir "/etc" / builtins.attrNames / builtins.length
77
nix-repl> let __mul = x: y: if builtins.typeOf y != "lambda" then x y else z: x (y z); in 
          builtins.length * builtins.attrNames * builtins.readDir "/etc"
77
```
ans so on (https://github.com/NixOS/nix/issues/861)

**Comment by BadDecisionsAlex** [comment]
Yes please!

**Comment by Ninlives** [comment]
Any progress?

**Comment by edolstra** [comment]
No, there are no plans to add this.

**Comment by WhiteBlackGoose** [comment]
Very sad. May I ask why?

**Comment by aakropotkin** [comment]
Plain and simple backwards compatibility.

Changing the parser/lexer this late in the game is incredibly disruptive. It's something you would only do as a desperate measure, certainly not for a "nice to have".

Functionally it provides nothing of value. I'm not saying that aesthetics don't matter ( they do ), and I'm certainly not saying that expressability doesn't matter ( it do ), but as a practical matter you can't change a mature language's core syntax without an enormous effort.

**Comment by WhiteBlackGoose** [comment]
I see. That's fair. I keep forgetting Nix is two decades old :smile:

**Comment by edolstra** [comment]
Compatibility isn't really the issue here. The more important issue is that it's another bit of syntax that users would need to learn, and the Nix language already has a reputation for being hard to learn.
