### ISSUE TITLE
Trouble installing nix 2.01 (2.0.x ?) on Ubuntu 16.04

### ISSUE THREAD

**Issue by bbarker** [NixOS/nix#2121]
Installing nix in Ubuntu 16.04 (in docker, haven't tried natively) since nix 2.0.1 (haven't tried 2.0.0) always gives the following when I try to `nix-channel --update` after having `nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs`. 

```
error: unable to download 'https://nixos.org/channels/nixos-unstable': Problem with the SSL CA cert (path? access rights?) (77)
```

I'm trying to run these commands as a non root user, which previously worked (my understanding is that this shouldn't be done as root).

**Comment by dezgeg** [comment]
I wonder if the Docker image has some sort reduced set of CA certificates from the distro site. 

Is `$NIX_SSL_CERT_FILE` set in the container? Or maybe none of the candidates for the CA certificates exists? https://github.com/NixOS/nix/blob/5cc5c3fb832fc6fe07a5988ef4728fe2d274bf67/scripts/nix-profile.sh.in#L63-L76

**Comment by bbarker** [comment]
@dezgeg Interesting, your comment led me to the issue. My old Dockerfile that I sort of inherited had some clever things in there, like setting `NIX_SSL_CERT_FILE`. After your comment, I noticed that even in Nix 1.11, what it was set to did not exist, but somehow the old version recovered from this assumption and set it to something that did exist. After setting it properly (I should probably just remove the set), I got much further along. However, one surprise remained near the end:

```
ENV nixenv ". $ENVSDIR/.nix-profile/etc/profile.d/nix.sh"
RUN $nixenv && cd /tmp && nix-env --fallback -if $ENVSDIR/scala-default.nix
```

Normally at this state (i.e. after running `nix-env -if ..`) packages should be added to the environment. However, I see none of the installed binaries in the path: `/home/brandon/.nix-profile/bin` doesn't exist, so there are no symbolic links sitting in it like there normally would be, though I can tell installation of packages certainly occurred into the nix cache.

**Comment by bbarker** [comment]
I fixed the remaining issues I had, see https://github.com/CornellCAC/docker-nix-intellij/pull/5
Actually, most thanks go to `clever` on IRC. The two big issues were needing to create a symbolic link to `.nix-profile` now and also removing a dead link that were installed in libunwind - perhaps this might create some upstream issues.
