### ISSUE TITLE
builtins.add test failures?

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nix#2130]
https://hydra.nixos.org/build/73435087/nixlog/2

Looks to be caused by https://github.com/NixOS/nix/commit/9a714f75af89da5e090f9d3b402b7266d5ec0144 .

I can't comment what the expected behavior is, but either test is wrong or Nix is wrong :).

**Comment by lheckemann** [comment]
I think nix is wrong. I don't think float-ness should be silently discarded.

**Comment by edolstra** [comment]
I fixed the test in 548ad391d96d8922d0f8c35b5dd72bf4fb7e3ed1. Whether we should change how floating point number are displayed should probably be a separate issue.
