### ISSUE TITLE
chroot stores via SSH

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nix#2138]
I've been trying to access a chroot store via ssh using `nix copy`.

- `ssh-ng://user@host?root=/path` tried to access the systemwide store and said that the "root" option was unknown (but this same thing works for `local`, rather inconsistently)
- `ssh-ng://user@host?store=/path` seems to have tried to use `/path` as the nix store location rather than a chroot store, which failed because the store I was copying from is at `/nix/store`
- `ssh-ng://user@host`, with `store = /path` in the remote user's `nix.conf`, tried to access the systemwide store even though nix commands run in an interactive SSH session use the chroot store correctly

And that's all the ideas I've had so far that don't involve hacking around with wrapper scripts and such, which shouldn't be necessary as far as I know! Is there some way to do this currently in nix?

If not, as a suggestion for a nice and general way to make this work, it would be nice if I could do something like `ssh-ng://user@host/STORE_URL`, which would look like `ssh-ng://user@host/local?root=/mnt` in my case, but could also be something like `ssh-ng://user@host/daemon` or `ssh-ng://user@host/file:///some-binary-cache` in order to allow more diverse options. Does anyone see any issues with this?

**Comment by cleverca22** [comment]
i had a thought yesterday, once this bug is fixed, you could use it within something like nixops to deploy to an entirely blank drive, via a boot environment like the livecd

rather then install a bootstrap nixos, and copy-closure an update into it, you can just copy-closure the final build into the empty drive, then run `switch-to-configuration boot` under a chroot, and your install is done!

**Comment by cleverca22** [comment]
https://github.com/NixOS/nix/commit/e268bbc05435d8121275136934a594fc70a73da9
`[clever@amd-nixos:~/apps/nix]$ ./result/bin/nix copy --to ssh://system76?remote-store=local?root=/home/clever/fakeroot/ /nix/store/188avy0j39h7iiw3y7fazgh7wk43diz1-hello-2.10`
after building nix from master, i can copy to a random chroot dir on a remote machine
