### ISSUE TITLE
support ssh:// url literals

### ISSUE THREAD

**Issue by LnL7** [NixOS/nix#2140]
The nix commands support url literals instead of `builtins.fetchTarball` in a number of places, it would be nice if this also worked for `builtins.fetchGit`. Currently this fails with:

```
$ nix build -f ssh://git@github.com:NixOS/nixpkgs.git hello
error: unable to download 'ssh://git@github.com/NixOS/nixpkgs.git': Unsupported protocol (1)
```

**Comment by edolstra** [comment]
I removed git:// support in 6cf7c6a6b0d06d88f2f27daae4febbbdc757841b. The same arguments apply to ssh://. Furthermore, ssh:// is ambiguous because it doesn't specify that it's Git (e.g. it could also be a Mercurial repository).

**Comment by LnL7** [comment]
Yeah, that's fine. I didn't really think about the implications.
