### ISSUE TITLE
How do I set s3 credentials?

### ISSUE THREAD

**Issue by arianvp** [NixOS/nix#2143]
I noticed I can upload to s3 with `nix copy`

```
  To populate the current folder build output to a S3 binary cache:
  $ nix copy --to s3://my-bucket?region=eu-west-1

```

But in the codebase, I never see where  credentials are set in the AWSClientConfiguration. How am I supposed to use `nix copy` if I can't authenticate with aws?

**Comment by arianvp** [comment]
Cool!  Could we add a little note to the `--help` message for this? I can write something up. Could just be a link to that `aws` page . Feel free to close this

**Comment by AmineChikhaoui** [comment]
You could also use, nix copy --to s3://my-bucket?region=eu-west-1&profile=my-profile which will use the profile from the aws config files.
The relevant code for credentials provider setup is in https://github.com/NixOS/nix/blob/master/src/libstore/s3-binary-cache-store.cc#L86.

**Comment by flokli** [comment]
Reading up on https://github.com/NixOS/nix/issues/2161, the documentation should also explain that this might need to be set for multiple users.

**Comment by expipiplus1** [comment]
Would be good to put something clear here too as it's the top result for some relevant searches on this topic

**Comment by flokli** [comment]
Not stale, still relevant.

**Comment by pinpox** [comment]
Is there any possibility to pass credentials as environment variables? That would be very useful for use in CI jobs

**Comment by nghamilton** [comment]
There is now some improved documentation in the manual on how the credential check is managed when [performing authenticated wites](https://nixos.org/manual/nix/stable/package-management/s3-substituter.html#authenticated-writes-to-your-s3-compatible-binary-cache).
