### ISSUE TITLE
Installation instructions not appropriate for Gnome/Wayland desktop

### ISSUE THREAD

**Issue by realcomplex** [NixOS/nix#2148]
Hey!

I just installed Nix on my Debian system using the recommended `curl https://nixos.org/nix/install | sh` method. At the end of the installation, the script recommends the following:
```
Installation finished!  To ensure that the necessary environment
variables are set, please add the line

  . /home/user/.nix-profile/etc/profile.d/nix.sh

to your shell profile (e.g. ~/.profile).
```
However, this instruction is obsolete for desktop systems running Gnome with Wayland: in this kind of session, `~/.profile` and similar files are not sourced anymore. 

In fact, I haven't even managed to make things work at all, looking for recommendations. I tried adding a .desktop file to `~/.config/autostart` pointing to `/home/user/.nix-profile/etc/profile.d/nix.sh` with the following content:
```
[Desktop Entry]
Name=NixSetup
Comment=Sets up the nix environment
Exec="/home/user/.nix-profile/etc/profile.d/nix.sh"
Terminal=false
Type=Application
X-GNOME-Autostart-enabled=true
```
However, this does not seem to work.

Another idea I had was to use the systemd `environment.d` system, see [https://www.freedesktop.org/software/systemd/man/environment.d.html](https://www.freedesktop.org/software/systemd/man/environment.d.html). However, it doesn't seem like a nice thing to maintain by myself (copying the relevant entries from `/home/user/.nix-profile/etc/profile.d/nix.sh` to some systemd config file, keeping track of updates, etc.). I didn't try it yet.

Any suggestions? Thanks in advance for the help.

**Comment by FRidh** [comment]
From what I can tell, the only solution that will work with `wayland` is to remove the logic, and define environment variables that need to be exported, as you concluded yourself.

The scripts `nix.sh` and `nix-daemon.sh` are not that interesting, really. They perform initialization (creating files), and set environment variables based on some state. 

I think this eventually is best split up in a `/etc/environment.d/nix.conf` / `~/.config/environment.d/nix.conf` solution that would contain environment variables, and an executable that does the initialization, e.g. `nix init` (or perhaps already when calling `nix`).

**Comment by dezgeg** [comment]
Add it to `.bashrc` or something else your shell sources.
