### ISSUE TITLE
builtins.fetchGit doesn't fetch submodules

### ISSUE THREAD

**Issue by ElvishJerricco** [NixOS/nix#2151]

**Comment by ElvishJerricco** [comment]
This is a pretty big blocker for me. I can't reasonably use builtins.fetchGit without submodule support.

**Comment by siddharthist** [comment]
At least when building with `nixpkgs`, one can use
```nix
  src = fetchgit {
    url = "https://github.com/GaloisInc/some-repo.git";
    deepClone = true;
    sha256 = ...;
    rev = ...;
  };
```

**Comment by NorfairKing** [comment]
This is also a blocker for me. Specifically when it comes to private git repositories that have submodules.
I looked around in the code to see what would have to be changed to allow for `deepClone = true` in `builtins.fetchGit`: 
https://github.com/NixOS/nix/blob/18b4c53f71dfc626f5f5ffa0282afd1b9faad6a4/src/libexpr/primops/fetchGit.cc#L125

It looks like the current approach with a bare repository and `git fetch` instead of `git clone` will not work because submodules require a working tree and cannot work with a bare repository.
Either we fix up `git`, or we do a full `git clone --recursive` and remove the `.git` directories recursively inside that.


cc @nh2, Thanks for the help!

**Comment by kazcw** [comment]
I also need this. I'm trying to script updating the rev for some unstable packages. To do this with `fetchgit` I'll have to run it once with a dummy `sha256` and *parse the error message* to get the real `sha256`, and that's just awful.

**Comment by tbenst** [comment]
This issue causes difficult to debug error messages when trying to package PyToch 1.1 (https://github.com/NixOS/nixpkgs/issues/63073), and probably elsewhere, too. I took a clumsy stab at getting nested level of 2 to work with no luck: https://github.com/NixOS/nixpkgs/compare/master...tbenst:pytorch11#diff-8c857b370607b23d073067f7df717593

**Comment by qolii** [comment]
Any progress/interest on this one?

**Comment by tbenst** [comment]
@qolii might want to check out https://github.com/NixOS/nixpkgs/issues/61820#issuecomment-515553846. I'm no longer sure if this issue is valid?

**Comment by evanjs** [comment]
> @qolii might want to check out [NixOS/nixpkgs#61820 (comment)](https://github.com/NixOS/nixpkgs/issues/61820#issuecomment-515553846). I'm no longer sure if this issue is valid?

I think fetchGit is still somewhat preferred if private repos are used. Somebody please correct me if I’m wrong.

**Comment by qolii** [comment]
> I think fetchGit is still somewhat preferred if private repos are used.

Exactly. From my reading, https://github.com/NixOS/nixpkgs/issues/61820 is using `pkgs.fetchgit`. But that seems to be very difficult to use with private repos (my use case), whereas `builtsin.fetchGit` is much more amenable.

**Comment by qolii** [comment]
Looking quickly at [`fetchgit.cc`](https://github.com/NixOS/nix/commit/38539b943a060d9cdfc24d6e5d997c0885b8aa2f), this appears like it would be trivial?

* Add another input argument to `builtins.fetchGit`, along the lines of a boolean `fetchSubmodules` or so)
* Then based on it, add a conditional extra call to `runProgram`, to perform a `git submodule init`.

I am sure I am missing something... Please let me know. If it is this easy, I can put a patch together myself.

**Comment by qolii** [comment]
Or even just conditionally add the `--recurse-submodules` option to the existing `git fetch` we are doing?

**Comment by NorfairKing** [comment]
@qolii I made no attempt to 'fix' this issue. I'm working around it by making my repos public :)

**Comment by blitz** [comment]
I've given this a shot after a discussion with @edolstra and @tfc at NixCon. Comments welcome.

**Comment by knedlsepp** [comment]
Finally it's happening. Can't wait for the next release. :heart:

**Comment by jakubgs** [comment]
Any news on when this will be included in a release?
