### ISSUE TITLE
Unable to build dmd with newer nix versions

### ISSUE THREAD

**Issue by ThomasMader** [NixOS/nix#2155]
Continuation of https://github.com/NixOS/nixpkgs/issues/39951 and https://github.com/NixOS/nixpkgs/pull/40228#issuecomment-388414596

Building dmd with `nix-build -A dmd` on branch release-18.03 doesn't work with newer nix versions anymore.
Normally the build command just downloads the cached binary because hydra is able to build the package. I can't figure out the exact version of nix used on hydra but it's somewhere at 2.0.
To rebuild dmd locally I put `echo test` in the buildPhase of the dmdBuild derivation.

It fails with:

> warning: path '/nix/store/3jngv6gzm5qyqdlkicxj48gknhxv033c-phobosUnittests-2.067.1' claims to be content-addressed but isn't
error: unexpected end-of-file

The rebuild works with:

system: `"x86_64-linux"`
host os: `Linux 4.9.71, NixOS, 17.09.2476.53e6d671a96 (Hummingbird)`
multi-user?: `yes`
sandbox: `yes`
version: `nix-env (Nix) 1.11.16`
channels(root): `"nixos-17.09.2476.53e6d671a96"`
nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

The rebuild doesn't work with:

system: `"x86_64-linux"`
host os: `Linux 4.9.71, NixOS, 18.03.132304.45cd6090d9a (Impala)`
multi-user?: `yes`
sandbox: `yes`
version: `nix-env (Nix) 2.0.1`
channels(root): `"nixos-18.03.132304.45cd6090d9a"`
nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

and

system: `"x86_64-linux"`
host os: `Linux 4.14.38, NixOS, 18.03.132229.7cbf6ca1c84 (Impala)`
multi-user?: `yes`
sandbox: `yes`
version: `nix-env (Nix) 2.0.1`
channels(root): `"nixos-18.03"`
channels(thomad): `""`
nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`

and

system: "x86_64-linux"
host os: Linux 4.16.6, NixOS, 18.03.132192.ce0d9d638de (Impala)
multi-user?: yes
sandbox: no
version: nix-env (Nix) 2.0.1
channels(admin): ""
channels(root): "nixos-18.03"
nixpkgs: /nix/store/2kh4bx71ras3bwwlag3919by0d5hgfvs-nixexprs.tar.xz

The same problem exists with ldc but the build takes longer so it's better to reproduce with dmd.
Removing phobosUnittests fixes the problem.

**Comment by ThomasMader** [comment]
GrahamcOfBorg has the problem too by the way as can be seen here: https://github.com/NixOS/nixpkgs/pull/40228#issuecomment-388261874

**Comment by ngortheone** [comment]
@ThomasMader it looks like this was fixed in `2.0.2`. I was able to repro on 2.0.1, and was unable to repo on 2.0.2

@copumpkin I don't know if https://github.com/NixOS/nixpkgs/pull/40228 still necessary

**Comment by ThomasMader** [comment]
That's good to hear. 2.0.2 isn't in release 18.03 yet though and I suspect most people to use that branch including me.
But because the problem is fixed I will close this issue for now.

NixOS/nixpkgs#40228 is still necessary because it fixes compilation with glibc 2.27 and other things unrelated to this.
