### ISSUE TITLE
this.pre-initializes.the.dns.resolvers.invalid resolves as relative domain

### ISSUE THREAD

**Issue by yorickvP** [NixOS/nix#2162]
In order to... something, [nix tries to download an invalid domain](https://github.com/NixOS/nix/blob/master/src/libstore/build.cc#L1773).
Curl recognizes this domain as invalid, and interprets it as a relative domain, (my hostname is *.yori.cc, so it adds .yori.cc and tries to resolve this.pre-initializes.the.dns.resolvers.invalid.yori.cc). I discovered this issue because connections to it currently time out, and no nix installation works.

**Comment by edolstra** [comment]
Ping @copumpkin.

**Comment by vcunat** [comment]
@yorickvP: are you sure that's `curl` doing such ugly magic and not your `/etc/resolv.conf`?  (The `search` lines in there, in particular.)

**Comment by yorickvP** [comment]
```
$ cat /etc/resolv.conf
# Generated by resolvconf
nameserver 12.34.56.78
nameserver 12.34.58.78
nameserver 8.8.8.8
nameserver 8.8.4.4
options edns0
```

```
$ cat /etc/nsswitch.conf 
passwd:    files mymachines systemd
group:     files mymachines systemd
shadow:    files

hosts:     files mymachines dns myhostname
networks:  files

ethers:    files
services:  files
protocols: files
rpc:       files
```

**Comment by vcunat** [comment]
Hmm, that's weird.  I would try wireshark or similar to get closer to what actually happens.

**Comment by copumpkin** [comment]
Not really sure what to do about it, if the final period doesn't work.

**Comment by yorickvP** [comment]
I checked in wireshark.
What happens on `nix-channel --update`:
```
7.39 query A this.pre-initializes.the.dns.resolvers.invalid
7.39 query AAAA this.pre-initializes.the.dns.resolvers.invalid
7.43 NXDOMAIN AAAA this.pre-initializes.the.dns.resolvers.invalid
12.39 query A this.pre-initializes.the.dns.resolvers.invalid
12.39 query A this.pre-initializes.the.dns.resolvers.invalid
12.39 query AAAA this.pre-initializes.the.dns.resolvers.invalid
12.43 NXDOMAIN AAAA this.pre-initializes.the.dns.resolvers.invalid
17.39 query A this.pre-initializes.the.dns.resolvers.invalid
17.39 query A this.pre-initializes.the.dns.resolvers.invalid

17.44 NXDOMAIN A this.pre-initializes.the.dns.resolvers.invalid
17.44 query AAAA this.pre-initializes.the.dns.resolvers.invalid
17.48 NXDOMAIN AAAA this.pre-initializes.the.dns.resolvers.invalid
17.48 query A this.pre-initializes.the.dns.resolvers.invalid.yori.cc
17.53 NXDOMAIN A this.pre-initializes.the.dns.resolvers.invalid.yori.cc
17.53 query AAAA this.pre-initializes.the.dns.resolvers.invalid.yori.cc
17.57 NXDOMAIN A this.pre-initializes.the.dns.resolvers.invalid.yori.cc
19.84 query A github.com
```

This thing, in the best case, delays nix-channel by 10 seconds. When I submitted this bug-report, `this.pre-initializes.the.dns.resolvers.yori.cc` would resolve to an IP that sucked up all packets without sending any response, and the request would take a few minutes to time out. I fixed it because I have control over `yori.cc`.

**Comment by yorickvP** [comment]
I'll make a PR that uses `getaddrinfo` instead of curl, that seems to fix it.

**Comment by vcunat** [comment]
I expect the `.yori.cc` auto-suffixing will still cause problems for SW other than nix, but I'm certainly not against making nix better in this respect.

**Comment by yorickvP** [comment]
a lot of software depends on being able to resolve relative hostnames where the system's default domainname (retrievable using `dnsdomainname`) is appended. http and email are exceptions, so this would then be a curl bug.

It's expected behavior for unix systems since decades, and shouldn't cause problems in software.

**Comment by vcunat** [comment]
I'd think it's expected in browsers as well.
