### ISSUE TITLE
Nix 2.0 broken with read-only /nix/var/nix/db/

### ISSUE THREAD

**Issue by arianvp** [NixOS/nix#2188]
There was an issue in nixpkgs https://github.com/NixOS/nixpkgs/issues/40355 but I think it's actually an issue with Nix.  Nix 1.12 worked in a container where `/nix/var/nix/db` was mounted `read-only`, but  Nix 2.0 does not.    I did some debugging on this issue already, but I must say I am not very familiar with the Nix source code, so perhaps someone else can  chime in on why the behaviour of opening the `big-lock` lock file has changed from 1.12 to 2.0

**Comment by vcunat** [comment]
This is probably very close to #2134.

**Comment by vcunat** [comment]
From a superficial look, the container issue seems better to handle on nixpkgs side.  Even for read-only actions it's reasonable to do (read) locking, and that's probably not worth the effort to support on read-only mounts.

**Comment by arianvp** [comment]
So the solution here would be to mount the directory read/write ?

**Comment by arianvp** [comment]
I actually fixed this on the nixpkgs side of things https://github.com/NixOS/nixpkgs/issues/40355
