### ISSUE TITLE
`nix log` unable to fetch logs from cache.nixos.org (can't decompress data sent to callback)

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nix#2203]
Recent batch of memory-saving changes.
Probably known issue but since it's a blocker wanted to report it here.

Be "careful" testing this, since at least logs are written in binary form (no hashes on these, understandably) so you don't need to fetch them again... .  So use a clean environment or so :).

**Comment by dtzWill** [comment]
Warnimg was meant to say that you might end up with" garbage" in your cache.  I think this won't happen by default since an exception is thrown but just a heads-up :).

**Comment by nh2** [comment]
> Recent batch of memory-saving changes.

@dtzWill I don't understand the issue description.

Do you mean that there's a commit in `master` that makes some problem (which?), or that one of the memory saving commits is directly responsible for such problem (which?)?

Is `unable to fetch logs from cache.nixos.org (can't decompress data sent to callback)` an error message -- that happens when running what?

Please elaborate.

**Comment by dtzWill** [comment]
Thanks for taking a look, apologies for being unclear.  I'll chase down the commits and such shortly but in the meantime:

* Build latest nix 'master' however makes sense, ensure you're using it as your nix-daemon too and not some old version.
* Try using `nix log` on anything that requires fetching logs from `cache.nixos.org` (aka was built by hydra).  For example:
  * `$ nix log -f channel:nixos-18.03 bash`
  * `$ nix log /nix/store/zqh3l3lyw32q1ayb15bnvg9f24j5v2p0-bash-4.4-p12` (same but directly mentions path)

I don't have it handy but you'll see an error regarding failing to decompress -- in the usual setup this will be thrown by your nix-daemon as it tries to decompress the result of the download (as indicated by its reported `content-encoding`) but due to recent changes (`dataCallback`) ends up invoking the decompression routine on an empty string, which fails.

Problem being that the current design of "please decompress based on content-encoding header" is not compatible with the new `dataCallback`, at least in current implementation.  The code expects to be able to pass the data to the decompression bits but it's been fed elsewhere piece-by-piece through the dataCallback instead.  Injecting the appropriate decompression "filter" at the right place might work, but I'm not sure where that should be done.  If I recall this was discussed a long time ago when those patches were originally committed on the experimental branch--and it was decided this should instead be handled by the client anyway, but that requires a bit of plumbing/protocol changes (I believe).

I'll find the relevant commits in a bit.  Don't mean to stand in the way of getting important memory fixes pushed but IMO breaking 'nix log' on every path not user-built is a serious regression.

**Comment by dtzWill** [comment]
Here's a branch that reverts the commits that either directly cause the problem or cause crashing behavior when the directly responsible commits are reverted: https://github.com/dtzWill/nix/tree/debug/nix-log-commits

**Comment by dtzWill** [comment]
Presumably fixed with d3761f5f8bce1e4c8dcfdff3fa77c173157c0346 ? Haven't checked.

**Comment by edolstra** [comment]
Yes, that should have fixed it.
