### ISSUE TITLE
What is wrong with my shebang ?

### ISSUE THREAD

**Issue by teto** [NixOS/nix#2209]
```
nix --version  
nix (Nix) 2.0.2

```
Sadly I am not very lucky when using nix-shell as shebangs;

At the beginning of /home/teto/testbed/script.py, I try to use nix-shell as a shebang
```
#!/usr/bin/env nix-shell 
#!nix-shell -p python '( linuxPackagesFor mptcp-local-stable ).bcc' mptcp-local-stable.dev -i python
```
I get `error: syntax error, unexpected $undefined, at (string):1:103`; ( If I run it in a normal shell without the '-i python' it works).

so I tried to work around it and ran instead :
```
nix-shell -p python '(linuxPackagesFor mptcp-local-stable).bcc' mptcp-local-stable.dev --command \
	'python /home/teto/testbed/script.py' &
BCC_PID=$!

some code

# kill nix-shell and its children 
pkill -TERM -P $BCC_PID  

```
but then pkill triggers a segfault
` 32048 Segmentation fault      pkill -TERM -P $BCC_PID`
I've witnessed segfaults due to a kill in other circumstances
```
stat("/proc/31985/ns/ipc", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
stat("/proc/31985/ns/mnt", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
stat("/proc/31985/ns/net", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
stat("/proc/31985/ns/pid", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
stat("/proc/31985/ns/user", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
stat("/proc/31985/ns/uts", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
stat("/proc/32039", {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
openat(AT_FDCWD, "/proc/32039/status", O_RDONLY) = 4
read(4, "Name:\tzsh\nUmask:\t0022\nState:\tS ("..., 2048) = 1063
close(4)                                = 0
stat("/proc/32039/ns/ipc", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
stat("/proc/32039/ns/mnt", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
stat("/proc/32039/ns/net", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
stat("/proc/32039/ns/pid", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
stat("/proc/32039/ns/user", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
stat("/proc/32039/ns/uts", {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
getdents(3, /* 0 entries */, 32768)     = 0
close(3)                                = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
+++ killed by SIGSEGV +++
Segmentation fault

```

**Comment by lheckemann** [comment]
Not a nix bug. Instance of nixos/nixpkgs#40208

**Comment by teto** [comment]
for the second part the shebang problem still is. Actually I would like to add a few shebangs to the nix testsuite. Not sure how to run specific tests (and the whole testsuite takes time + fails without sudo)

**Comment by teto** [comment]
As a self-reminder pasted from irc: `(cd tests ; NIX_REMOTE= bash -e testname.sh)`.

I've replaced my shebang with the pattern `nix-shell check.nix -i python` which works and seems more bulletproof

**Comment by FRidh** [comment]
Use double quotes instead of single quotes.

**Comment by domenkozar** [comment]
Yeah I lost about 10min as well on this yesterday.

**Comment by FRidh** [comment]
If I recall correctly it is a regression with Nix 2.0. At the same time, it's maybe not too bad to permit only double-quotes. The error message should be a bit more helpful though, and I think we need to fix some examples.

**Comment by teto** [comment]
I really want to use the shebangs because it feels "clean", at least it's practical but most of the time I have (LGTM?) trouble using it (like https://github.com/NixOS/nix/issues/2072). So I really hope that the testsuite can be enriched.
Now I tend to use `nix-shell check.nix -i python` but even with it I have problems  like some python packages seem to behave differently (matplotlib). Anyway I will report these in a separate issue.

**Comment by teto** [comment]
hum I got yet another problem :s 
This shebang works perfectly fine with bash
```
#!/usr/bin/env nix-shell 
#!nix-shell shell-plot.nix -i python --show-trace 

..python code...
```
but as soon as I run it from a zsh shell (even a pure one, aka `zsh -d`), the script is run as python but the shell-plot.nix dependencies are not pulled in.
When I try to strace the program from a zsh interpreter, then shell-plot.nix is executed correctly. So I don't know how to debug this. Did anyone experience something similar ?


For info the shell-plot.nix
```
with import <nixpkgs> {};

runCommand "dummy2" {
  buildInputs = with python3Packages; [
    pandas 
    (matplotlib.override { enableGtk3=true;})
    # pyqt5
]; 
} ""
```

**Comment by teto** [comment]
seems like having ` alias -s py=python3` is a stupid thing  to have since then zsh bypasses the shebang. 2nd pb solved \o/
