### ISSUE TITLE
Run setup hooks by default in shells

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nix#2213]
Some places in Nixpkgs, someone has set a shellHook that just sources the setup hook:

https://github.com/NixOS/nixpkgs/blob/56904d7c423f2b13b37fbd29f39bbb4b52bc7824/pkgs/development/libraries/physics/geant4/g4py/default.nix#L42-L45

This seems like a common enough thing that it might make sense to just always source setupHook in every shellHook? I want to do this to get JAVA_HOME working but currently it is already in setup-hook:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/compilers/openjdk/8.nix#L220-L222

**Comment by dtzWill** [comment]
Can you expand on why this was closed? Just curious :).

**Comment by matthewbauer** [comment]
Yeah I guess this can stay open... I am still not sure if this would be right. There's a lot of different use cases for shell hooks and I thought that it might not make sense with all of them. On the other hand, I think it could be useful in some cases.
