### ISSUE TITLE
Tab completion, backspace and character duplication in nix repl

### ISSUE THREAD

**Issue by bbarker** [NixOS/nix#2217]
After I fire up `nix repl` I can do tab  completion, but the entire string shown on the terminal is concatenated with what I've already typed.

Example: this is what happens after I type `builtin` followed by `TAB`:

```
nix-repl> builtinbuiltins
```

If I press backspace at this point I get:

```
nix-repl> builtinbuiltinsbuiltin
```

If I press it again I get: 

```
nix-repl> builtinbuiltinsbuiltinbuilti
```

This is using nix 2.0.2.

**Comment by dtzWill** [comment]
That's strange, that's not the behavior I'm seeing.  Might be related to shell/term/env? (Can others try reproducing this?)

**Comment by bbarker** [comment]
I'm using emacs ansi-term, will try others.

**Comment by bbarker** [comment]
I upgraded to nix 2.0.4, and the issue seems to have gone away.
