### ISSUE TITLE
Nix cli tools do not print to stdout/err

### ISSUE THREAD

**Issue by antifob** [NixOS/nix#2219]
I'm having a hard time parsing the output of the various nix cli tools.

Usually, a program will print its output to stdout (or stderr in case of errors) and the output can be redirected to a file or piped. However, nix tooling prints to different descriptors (fd 8, AFAICT), which is totally unintuitive and can cause difficult/impossible to trace executions.

For example, only the final closure of `nix-build` is printed to stdout. Since there might not be any way to print the whole output to stdout without breaking compatibility, maybe stderr would be an option? Or maybe adding a `-o` flag to redirect the output to a file? Or, if the `nix` tool is still experimental, maybe a breaking change could be introduced there for better compatibility with other cli tools?

**Comment by edolstra** [comment]
In fact Nix commands write log/error messages to stderr and final output to stdout. I don't think we print on fd 8 anywhere. There is an issue (#2198) about adding logging in JSON format.

**Comment by antifob** [comment]
bump
