### ISSUE TITLE
nix-env fails when HOME is not set, even if passed a profile path

### ISSUE THREAD

**Issue by wizeman** [NixOS/nix#224]
I would expect this to work:
`env -u HOME nix-env -p /nix/var/nix/profiles/default --list-generations`
However, it fails with this error message:
`error: HOME environment variable not set`

In particular, I've seen this problem in NixOS's nix-gc systemd service, which does the following:

`script = "exec ${config.nix.package}/bin/nix-collect-garbage ${cfg.options}";`

If ${cfg.options} is "-d", the actual nix-env commands to delete old generations will fail with the error message above.

The problem seems to be here:
https://github.com/NixOS/nix/blob/25386e5edc2d65c84ce824d2c964a5c029f4c30d/src/nix-env/nix-env.cc#L1336

getDefNixExprPath(), which calls getHomeDir(), gets called regardless of command line arguments, and fails if HOME is not set.

**Comment by gilligan** [comment]
This has meanwhile been fixed

```
$ env -u HOME nix-env -p /nix/var/nix/profiles/per-user/$(whoami)/profile --list-generations
```
This works as expected on Nix 2.3.3
