### ISSUE TITLE
nix ls-lar out of memory

### ISSUE THREAD

**Issue by volth** [NixOS/nix#2245]
```nix ls-lar``` fails with ```out of memory``` on relatively big files (~50Mb .nar file is enough to fail with out of memory on a laptop with 16GB RAM)

**Comment by copumpkin** [comment]
Was this a false alarm? Or what?

**Comment by volth** [comment]
It seems that my .nar file was corrupted

**Comment by copumpkin** [comment]
Scary!

**Comment by shlevy** [comment]
Did you save it by any chance? We should definitely be robust to malformed input...

**Comment by volth** [comment]
@shlevy It is reproducible with any malformed input, just try to feed any .gz file to ```ls-nar```
