### ISSUE TITLE
nix build can't connect to host for remote build

### ISSUE THREAD

**Issue by rnhmjoj** [NixOS/nix#2254]
I'm trying to build a nixos configuration and/or packages on a remote machine.

The connection seems to work:
```
$ nix ping-store --store ssh://user@host
Host key fingerprint is SHA256:<hash>
+--[ED25519 256]--+
|                 |
|                 |
|                 |
|  <random art>   |
|                 |
|                 |
|                 |
|                 |
|                 |
+----[SHA256]-----+
```

however using nix 2.0 --builders option nix says
```
$ nix build -f. --builders 'ssh://user@host'
unable to open SSH connection to 'ssh://user@host': writing to file: Broken pipe; trying other available machines...
```
and the build proceeds locally.

Then I tried using nixos-rebuild --build-host which can connect but also fails:
```
$ nixos-rebuild --build-host user@host
copying path '/nix/store/3mk5pl4l7van3jp6clzwyj11pcd60yd2-brotli-1.0.3.drv' to 'ssh://user@host'...
copying path '/nix/store/ikx35xcfs48rz1xb472x7abqlzchc615-aws-sdk-cpp-1.3.22.drv' to 'ssh://user@host'...
error: cannot add path '/nix/store/3mk5pl4l7van3jp6clzwyj11pcd60yd2-brotli-1.0.3.drv' because it lacks a valid signature
```

Is there any way to disable signature checking in this case? (like --no-check-sigs in nix copy)

**Comment by edolstra** [comment]
Was that `nix ping-store` run as root? When using the Nix daemon, it's the daemon that needs to be able to connect via SSH.

For the second problem, you have to add `user` to `trusted-users` in `nix.conf`.

**Comment by rnhmjoj** [comment]
> Was that nix ping-store run as root? When using the Nix daemon, it's the daemon that needs to be able to connect via SSH.

Oh, I missed the warning in the nix manual, sorry.

> For the second problem, you have to add user to trusted-users in nix.conf.

Ok, I needed to add the user on the host as well.
