### ISSUE TITLE
aarch64 release contains x86_64 busybox (that becomes /bin/sh in build environment)

### ISSUE THREAD

**Issue by twhitehead** [NixOS/nix#2262]
@grahamc Not sure where the _releases/nix_ files are coming from (i.e., if this bug report should be here, nixpkgs, or somewhere else), but the `aarch64` one

https://nixos.org/releases/nix/latest/

has a x86_64 compilation of `busybox` providing `/bin/sh`

```bash
curl -O https://nixos.org/releases/nix/nix-2.0.4/nix-2.0.4-aarch64-linux.tar.bz2
tar -xjf nix-2.0.4-aarch64-linux.tar.bz2
strings nix-2.0.4-aarch64-linux/store/*nix*/lib/*.so | fgrep busybox
```
```
/bin/sh=/nix/store/iqyh9sakh8j4vzal6w0ccipdwn3g44cv-busybox-1.28.1/bin/busybox
```
```bash
readelf -a nix-2.0.4-aarch64-linux/store/iqyh9sakh8j4vzal6w0ccipdwn3g44cv-busybox-1.28.1/bin/busybox
```
```
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x40e6b7
  Start of program headers:          64 (bytes into file)
  Start of section headers:          144000 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         5
  Size of section headers:           64 (bytes)
  Number of section headers:         12
  Section header string table index: 11
...
```

This causes any packages that rely on `/bin/sh` to fail building.when you enable sandboxing.

**Comment by dtzWill** [comment]
Yikes! FWIW building `nix build -f release.nix build.aarch64-linux` on an aarch64 machine from an aarch64 builder (https://github.com/nix-community/aarch64-build-box) and it uses an aarch64 busybox:

```console
$ strings /nix/store/f219l7ws1m5732d9kkspwc1ibjc8q0q5-nix-2.1pre6300_6924bdf/lib/libnixstore.so|grep busybox
/bin/sh=/nix/store/s25r90f9zrrp2bzkl8ng63hx51aimq4w-busybox-1.28.1/bin/busybox
$ file /nix/store/s25r90f9zrrp2bzkl8ng63hx51aimq4w-busybox-1.28.1/bin/busybox
LSB executable, ARM aarch64, version 1 (SYSV), statically linked, stripped
```

Inspecting derivation produced when building from an x86_64-linux host using `nix show-derivation -f release.nix build.aarch64-linux` shows it uses the same (aarch64) busybox.

Both of these were from latest Nix git master, FWIW.

---------

That last comment actually encouraged me to try with the 2.0.4 branch as well and... yep I'm seeing an x86_64 busybox being used! So I guess it's been fixed already:

```console
$ git checkout 2.0.4
$ nix show-derivation -f release.nix build.aarch64-linux|grep busybox
      "/nix/store/lm68l1q9m1dgb3hmpm0bb9hz1rm95arh-busybox-1.28.4.drv": [
      "configureFlags": "--disable-init-state --enable-gc --with-sandbox-shell=/nix/store/rrlmkddixf426saq3sa2jx6ifskird8z-busybox-1.28.4/bin/busybox --sysconfdir=/etc",
$ file /nix/store/rrlmkddixf426saq3sa2jx6ifskird8z-busybox-1.28.4/bin/busybox
/nix/store/rrlmkddixf426saq3sa2jx6ifskird8z-busybox-1.28.4/bin/busybox: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
```

Haven't tried the 2.0 maintenance branch yet...

**Comment by dtzWill** [comment]
Bisected to 44a1b6c0264556d2bc7ac312728421342d92490a, which has a promising commit message :).

**Comment by twhitehead** [comment]
Thanks for looking into this.  I should add, until this gets fixed, it is easy to work around.  Just make sure you install `nix` (fortunately that building `nix` doesn't depend on _/bin/sh_ anywhere) and you will get a version that is free of x86_64 dependencies.  Switch your `nix-daemon` to it and you are good to go.

**Comment by dtzWill** [comment]
cc @NixOS/nix-core -- this definitely seems like something to be certain to address in next release, and may warrant a quick minor bump? Or whatever the release policy is, but just saying this seems moderately important (and low-risk, can push the fix with some confidence I think).
