### ISSUE TITLE
Suspicious-looking gc profiles root in NixOS 18.03

### ISSUE THREAD

**Issue by Ekdohibs** [NixOS/nix#2263]
I installed NixOS 18.03 from a live USB stick on Jun 12, following the manual. When I look at `/nix/var/nix/gcroots/profiles`, it points to `/mnt/nix/var/nix/profiles`, which is very suspicious: presumably, this was the location of the profiles during the live USB installation, as per the manual, but is no longer.
```
$ ls -l /nix/var/nix/gcroots/profiles 
lrwxrwxrwx 1 root root 25 Jun 12 13:55 /nix/var/nix/gcroots/profiles -> /mnt/nix/var/nix/profiles
```
Shouldn't it be `/nix/var/nix/profiles` in the destination instead? If so, there might be a problem in the installation script of NixOS.

**Comment by lheckemann** [comment]
Since this is a NixOS issue, could you please re-report this at https://github.com/nixos/nixpkgs? See also the [guidelines in the issue template](https://raw.githubusercontent.com/NixOS/nix/master/.github/ISSUE_TEMPLATE.md) for this repo.

**Comment by Ekdohibs** [comment]
I will re-report it in nixpkgs. I thought it was a Nix issue since it was related to the GC, sorry for the wrong report.

**Comment by lheckemann** [comment]
Thanks! :)
