### ISSUE TITLE
builtins.toFile Error message should be more explicit

### ISSUE THREAD

**Issue by dingxiangfei2009** [NixOS/nix#2274]
Suggest to rephrase the message to: `... cannot contain a sub-string referring to a potential derivation path (%3%)` where %3% is the violating path string.

https://github.com/NixOS/nix/blob/3defdccf4b46fe678496e5e3430c55b827477d0d/src/libexpr/primops.cc#L1013

**Comment by DavHau** [comment]
I agree! I got this error message and was quite confused until i found my way to this github issue.

**Comment by grahamc** [comment]
Could you send a PR? :)
