### ISSUE TITLE
builtins.toFile throw error when s parameter was retrieved from a function

### ISSUE THREAD

**Issue by countoren** [NixOS/nix#2283]
When trying to create file with builtins.toFile when s parameter is from a function the following error is thrown:
`error: in ‘toFile’: the file ‘file’ cannot refer to derivation outputs, at (string):1:1`

nix-repl log:
```
Welcome to Nix version 1.11.16. Type :? for help.

nix-repl> :l <nixpkgs>
Added 9065 variables.

nix-repl> f = {vim}: "${vim} some more text"

nix-repl> s = f { inherit vim; }

nix-repl> s
"/nix/store/g2nc8f4zd5f8nddiynfha0nfp3f57y59-vim-8.1.0001 some more text"

nix-repl> builtins.toFile "file" s
error: in ‘toFile’: the file ‘file’ cannot refer to derivation outputs, at (string):1:1

nix-repl> builtins.toFile "file" "/nix/store/g2nc8f4zd5f8nddiynfha0nfp3f57y59-vim-8.1.0001 some more text"
"/nix/store/xaa3qjfhmimsvq1a26pafdif3rjmqgvx-file"
```

**Comment by edolstra** [comment]
The error is correct: "source" store paths like `file` cannot refer to derivation outputs like `vim`, because `vim` may not have been built yet. You can use `pkgs.writeText` instead, e.g.
```
nix-repl> :b pkgs.writeText "file" "foo ${glibc} bar"    
these derivations will be built:
  /nix/store/7nqcd13knp2rmkvffg3v60jnyw4ylr24-file.drv
building '/nix/store/7nqcd13knp2rmkvffg3v60jnyw4ylr24-file.drv'...
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
/nix/store/h99vgrbjnk3982lkyfdyhd40harfgp5m-file

this derivation produced the following outputs:
  out -> /nix/store/h99vgrbjnk3982lkyfdyhd40harfgp5m-file
```

**Comment by countoren** [comment]
so s and "/nix/store/g2nc8f4zd5f8nddiynfha0nfp3f57y59-vim-8.1.0001 some more text" are not equivlent? are both eval to string?

**Comment by edolstra** [comment]
No, they're not. `s` has a "context" that tracks the fact that the string has a dependency on a store path, whereas the second string literal is a dangling reference: it refers to `/nix/store/g2nc...`, but Nix doesn't know that, so the latter store path could be garbage-collected and leave a hole in the package closure.
