### ISSUE TITLE
Pip installation problem

### ISSUE THREAD

**Issue by haposik** [NixOS/nix#2284]
Hi, I've encountered a problem during installation of this package: [github](https://github.com/johbo/pip2nix). It requires pip>=8,<10 to be installed and as an option it tries to install pip-9.0.1 as you can see [here](https://github.com/johbo/pip2nix/blob/51e6fdae34d0e8ded9efeef7a8601730249687a6/python-packages.nix#L57).
I attach log of executing command `nix-shell release.nix -A pip2nix.python36 --verbose 2>&1 | tee nix.log`: 
[nix.log](https://github.com/NixOS/nix/files/2177040/nix.log)

As you can see it eveluates 2 files of lines 115-116: 
- [/nix/store/ig7r3d66my6d20xnjdfxwnd5p2gkrf8q-nixpkgs-18.09pre144939.14a9ca27e69/nixpkgs/pkgs/development/python-modules/pip/default.nix](https://github.com/NixOS/nix/files/2177060/pip-default.nix.log)
- [/nix/store/ig7r3d66my6d20xnjdfxwnd5p2gkrf8q-nixpkgs-18.09pre144939.14a9ca27e69/nixpkgs/pkgs/development/python-modules/bootstrapped-pip/default.nix](https://github.com/NixOS/nix/files/2177071/bootstrapped-pip-default.nix.log)

And after that, it downloads pip-10.0.1 from `cache.nixos.org`; lines: 245, 253, and says that they are going to be fetched below.

Also I attach result of `nix-shell -p nix-info --run "nix-info -m"`:
- system: `"x86_64-linux"`
 - host os: `Linux 4.13.0-36-generic, Ubuntu, 16.04.4 LTS (Xenial Xerus)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(user): `"nixpkgs-18.09pre144939.14a9ca27e69"`
 - nixpkgs: `/home/user/.nix-defexpr/channels/nixpkgs`

I tried to make this experiment as clean as possible, so I executed all the process on VM Ubuntu without installing any extra packages

**Comment by FRidh** [comment]
This is not a Nix issue, but more likely a Nixpkgs issue. Please post your issue there.
