### ISSUE TITLE
nix build does not respect --builders flag

### ISSUE THREAD

**Issue by dingxiangfei2009** [NixOS/nix#2286]
With `nix.distributedBuilds = true;` in `/etc/nixos/configurations.nix` but `nix.buildMachines = []`,

calling `nix build '(with import <nixpkgs> { system = "x86_64-darwin"; }; runCommand "foo" {} "uname > $out")' --builders 'ssh://mac x86_64-darwin` does not use the specified remote builder.

At the same time, `ssh mac` works with a properly set up `~/.ssh/config`on a `x86_64-linux` NixOS machine. It seems that the `builder` flag is ignore.

**Comment by lheckemann** [comment]
You need to be in `trusted-users` (only root is trusted by default) in order to specify builders. Unfortunately, settings that require being a trusted user are currently ignored silently rather than raising a warning/error.

arguably dup of #2271. #1761 related

**Comment by dtzWill** [comment]
I think warnings are printed-- they're just below the default log level? Try using `-v` (just once is all that you should need) to see, I think there might be needed for other warnings from nix-daemon but don't remember which.

(Just mentioning it in case it helps, doesn't mean it should/shouldn't be made more clear or something)

**Comment by colemickens** [comment]
I'm in trusted-users and from what I can tell, the build is still not executing remotely. This is nearly verbatim from the manual and still prints out my local machine info when I print result (and that's even after cleaning it up, since `nix build` just doesn't do anything or warn if ./result already exists). Also, there is no verbose output, `--verbose` did nothing.

```
$  rm -f ./result; nix build '(with import <nixpkgs> { }; runCommand "foo" {} "uname -a > $out")' --builders 'ssh://root@kix.cluster.lol'

$ cat result
# the info from localhost, not kix.cluster.lol

$ cat /etc/nix/nix.conf | grep trusted-users
trusted-users = root @wheel cole

$ whoami
cole
```

**Comment by lheckemann** [comment]
Last I checked, `ssh://` stores couldn't build derivations. Try `ssh-ng://…`

**Comment by AmineChikhaoui** [comment]
I think there is a certain format that needs to be followed similar to /etc/nix/machines, for example I'm able to run builds remotely using:
```
nix-build local-integration.nix -A osx.lb_database.build  -I nixpkgs=channel:nixos-18.03 --builders "root@spud x86_64-darwin /home/amine/.ssh/id_rsa 1 1 darwin-playground,LB,any,perf " --option cores 4
```
I don't know if that format is properly documented but you can figure out the fields from https://github.com/NixOS/nix/blob/master/src/libstore/machines.cc#L9
