### ISSUE TITLE
install on Ubuntu

### ISSUE THREAD

**Issue by prettyCoders** [NixOS/nix#2287]
Can  i install Nix on Ubuntu?

**Comment by clojurians-org** [comment]
yes, except docker service can't managed by nix while it's not on nixos.

i always use it on Ubuntu on old days.

**Comment by prettyCoders** [comment]
Can you tell me how to install nix on ubuntu ?please

**Comment by clojurians-org** [comment]
https://nixos.wiki/wiki/Nix_Installation_Guide

**Comment by chrissound** [comment]
I'm sure this issue can now be closed?

**Comment by hmenke** [comment]
Nix has now also arrived in the official Ubuntu repos and will be included in the groovy release.
https://packages.ubuntu.com/groovy/nix-bin
https://packages.ubuntu.com/groovy/nix-setup-systemd
