### ISSUE TITLE
builtins.fetchGit does not update on upstream changes

### ISSUE THREAD

**Issue by netixx** [NixOS/nix#2293]
I am using builtins.fetchGit in my nixos config file this way:
```
imports = [
  (builtins.fetchGit https://github.com/netixx/nixos-settopbox) + "/default.nix"
];
```
It works on the first rebuild, but when I update the `nixos-settopbox` repository, updates are not fetched on the next `nixos-rebuild switch`.

Is this expected behaviour ? Is there an option that I could add for this to happen ?

Thank you.

**Comment by shlevy** [comment]
fetchGit uses the `tarball-ttl` value to determine cache lifetime, so you can do `--option tarball-ttl 0` to turn it off.

**Comment by netixx** [comment]
This works great ! Thank you for your answer.
The `builtins.fetchGit` doesn't have a whole lot of documentation (and I didn't know about this nix option).
