### ISSUE TITLE
is there a command to add /nix/store/* package to .nix-profile/bin?

### ISSUE THREAD

**Issue by clojurians-org** [NixOS/nix#2294]
i use nix-store command to export package to offline location for deploy, then copy and import to product machine to deploy.

```shell
nix-store --export $(nix-store -qR /nix/store/*${nix_package}*) > nix.sh.out/${nix_package}.closure

cat nix.sh.out/${nix_package}.closure | bzip2 | ssh op@${remote_ip} "bunzip2 | .nix-profile/bin/nix-store --import"
```

but those path only import to /nix/store directory, i want to add their bin to ~/.nix-profile/bin.
what shoud i do?

**Comment by vcunat** [comment]
`nix-env -i /nix/store/package`
