### ISSUE TITLE
New outpath of .drv file

### ISSUE THREAD

**Issue by haposik** [NixOS/nix#2315]
What if I created my own .drv file from another one and I want to add it to /nix/store via `nix-store --add <.drv file>`. Assuming that I left old `"out"` attributes I will get an error like:
```
derivation '/nix/store/mcvccrnxbw4ma4sikjf7yma8a2l2k396-<pkg-name>.drv' has incorrect output '/nix/store/hhxyq75jyp6xsrq3gqw62bg12yjqnfkn-<pkg-name>', should be '/nix/store/8lhw3l7nb8rnwhxnjv1pc8flb1sd65rs-<pkg-name>'
```

Well, if you change `"out"` attributes values to "should be" value, `nix-store --add` will succeed. However I wonder if it's possible to get to know the desired out-value of the .drv file in more beautiful way

**Comment by lheckemann** [comment]
Usually you'd want to achieve this by modifying the expressions that resulted in the drv, not the drv itself. Why do you want to do this?

**Comment by haposik** [comment]
There is a task, when it's easier for me to modify dependencies inside the .drv files, rather than .nix one. Actually, I'am okay with parsing stderr, so I think I can close this issue.
