### ISSUE TITLE
nix search uses same cache regardless of `-f' argument

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nix#2316]
Nix search accepts the ```-f``` argument, but it appears it only works with custom paths when you also pass ```-u```. Otherwise the cache will give you the same output regardless. For instance try this file as text.nix:

```
{
  inherit (import <nixpkgs> {}) hello jq clang file;
}
```

and running

```
nix search -f test.nix
```

You will see more than the 4 derivations listed above. You can fix this with the ```-u``` arg but then your cache will have to be updated again when you switch:

```
nix search -u -f test.nix
```

**Comment by dtzWill** [comment]
FWIW you can use `--no-cache` (usually without `-u` since that will write to the same cache normally used) to search custom things.  For small-ish things can still be rather useful :).
