### ISSUE TITLE
nix-env fails when only --json included

### ISSUE THREAD

**Issue by ryantm** [NixOS/nix#2328]
I'm trying to fix a problem building 
https://nixos.org/nixpkgs/packages-unstable.json.gz

Here is a log of the issue:
https://gist.github.com/ryantm/38b6b137ffb876ed477e5e97bd20baa4

I wanted to get the full backtrace so I could better understand why it is failing, so I added --show-trace but it didn't change the error output. Then I simplified it to just the nix-env expression and noticed that if I ran it without `--json` it did not have and stderr output:

https://gist.github.com/ryantm/d1e4c0f352190a93dca0b759918c20ae

I don't really know how --json works, but I was kind of expecting the error to be present in either case. Is there something about the --json error path that does not allow it to output the full stack trace to stderr?

**Comment by lheckemann** [comment]
I think this is because `--json` forces strict evaluation of the whole meta attribute of a package while `-qa` without `--json` only evaluates the name.
