### ISSUE TITLE
Nix backend for PackageKit / Gnome-Software

### ISSUE THREAD

**Issue by heyakyra** [NixOS/nix#233]
This will make Nix much more accessible to a wider audience. 

Also filed there: https://bugs.freedesktop.org/show_bug.cgi?id=76810

**Comment by kevincox** [comment]
This would be really cool, especially for nixos. It would be awesome to integrate with gnome-software's offline update. I don't know how well nix could fit in but it would be awesome if the updates could be completely built then it would just be a trivial switch to activate the new configuration on reboot.

**Comment by vcunat** [comment]
> it would be awesome if the updates could be completely built then it would just be a trivial switch to activate the new configuration on reboot.

That's done by `nixos-rebuild boot`.

**Comment by kevincox** [comment]
Yeah, I get that it is possible but getting it integrated with packagekit would provide an awesome user experience. This way everything could get updated in the background, then when it is all done you get a notification "Updates ready" and you can either reboot now, or the next time you shutdown/reboot you just check the checkbox "Install updates". This means no waiting or thinking which is exactly what I want from my updates. And of course if something fails, you can just roll back.

**Comment by vcunat** [comment]
See `system.autoUpgrade.enable` and related nixos settings.

**Comment by bjornfor** [comment]
Bumped into this just now, GNOME GUI printer configuration apparently depends on PackageKit: https://github.com/NixOS/nixpkgs/issues/12058.

**Comment by vcunat** [comment]
Do you know how it depends on it? I assumed that it detected missing SW so tried to run some dialog to install it.

**Comment by bjornfor** [comment]
@vcunat: I don't know what features depend on it, I just saw it print a warning ```The name org.freedesktop.PackageKit was not provided by any .service files```. Hopefully it's an optional dependency. I guess the real blocker for the GNOME printer GUI is the missing ```org.fedoraproject.Config.Printing``` service.

**Comment by pizzamaker** [comment]
This is a very interesting idea, and it also opens the door for PackageKit to support Guix as well.

**Comment by matthewbauer** [comment]
I've started working on a branch that's still a work-in-progress. But I've come up with a few issues with the implementation:

1. What is a "package" in the context of Nix?
2. Can the "user-env" files be included as a library?
3. Is there any concept of "groups" or "categories" in Nix/nixpkgs?
4. Should installed packages be installed at the "root" level or the "user" level? (PackageKit assumes everything will be "root".

It's certainly not very difficult if we choose to just implement the bare minimum vfuncs. This will probably only work with the "pkcon" client at first.

Right now I'm going to just try to support "Nix" and ignore things like "upgrade system" or "repair system" that only make sense in the context of NixOS. Other things like "update packages" and "get repo list" I'm going to wait until nix-channel is rewritten in C++. Also things like "depends on" and "required by" don't really make sense in the context of Nix although I suppose they wouldn't be hard to implement.

[WiP branch](https://github.com/matthewbauer/PackageKit/tree/nix)

**Comment by vcunat** [comment]
@matthewbauer:
1. I would go for anything recognized by `lib.isDerivation`, though later we might devise a meta flag to hide stuff.
2. I don't understand that one.
3. We don't really have any package classification yet.
4. Let's install as the user who runs the app. Admin can run it as root.

**Comment by matthewbauer** [comment]
I've got an open pull request on the PackageKit repository if anyone wants to review it. I'm wanting to get at least PackageKit and Gnome Software support fully working in time for NixOS release 16.09.

hughsie/PackageKit#126

**Comment by balsoft** [comment]
Doesn't work in 18.03. fails with `Failed to load the backend: opening module nix failed : /nix/store/qjdawq325swj6b77vz3l3bzqsvrcwdav-packagekit-1.1.8/lib/packagekit-backend/libpk_backend_nix.so: cannot open shared object file: No such file or directory`

**Comment by jtojnar** [comment]
@balsoft it is currently disabled since it does not compile, see https://github.com/NixOS/nixpkgs/issues/21230

**Comment by edolstra** [comment]
Closing on account of age.

**Comment by davidak** [comment]
This is still an important feature to have for a user friendly GUI for Nix!

**Comment by zimbatm** [comment]
It's important but is also best implemented as a separate project. Nix itself should provide the primitives that are needed by the GUI process.

**Comment by aviallon** [comment]
Is there any progress on this? It would be awesome, as NixOS with user-friendly installations would be the best grandma-compatible operating system!
