### ISSUE TITLE
Nix http substitutor cannot be a subdirectory

### ISSUE THREAD

**Issue by JohnAZoidberg** [NixOS/nix#2337]
I tried to host a binary cache at https://mydomain.org/binary-cache but it doesn't seem to work until I move it to the top level: https://mydomain.org.

The cache was created with `nix copy --to "file:///srv/binary-cache/" /nix/store/3h30cy54p37ndsdbgm314m4c4a9in101-hello-2.10`.

For now I can host it on a different port or a subdomain but it took me quite a while to figure out that's what I have to do.
Is that the intended behaviour or is this a missing feature?

**Comment by dezgeg** [comment]
I host my binary cache in subdirectory (at http://nixos-arm.dezgeg.me/channel) and everything works just fine for me, e.g.
````
nix-store -r /nix/store/zzzg1919h74p5pvn0f5faw8921hiplgw-dhcp-4.3.3  --substituters http://nixos-arm.dezgeg.me/channel --trusted-public-keys 'nixos-arm.dezgeg.me-1:xBaUKS3n17BZPKeyxL4JfbTqECsT+ysbDJz29kLFRW0=%' 
````

works.

**Comment by JohnAZoidberg** [comment]
That's interesting. Your command indeed works for me.
How did you set up/create your binary cache?
