### ISSUE TITLE
NixInt to become 64-bit on all plaftorms

### ISSUE THREAD

**Issue by volth** [NixOS/nix#2339]
Currently, integer in Nix is platform-dependent, it is 32-bit on 32-bit platforms and 64-bit on 64-bit platforms.
It limits portability of Nix-code across platforms and results in issues like https://github.com/NixOS/nixpkgs/pull/41490

Related: https://github.com/NixOS/nix/commit/a92ed973e569324b55cddb128f6f638f3ea1985c

**Comment by volth** [comment]
Another issue caused by 32/64-bit Nix incompatibility: https://github.com/NixOS/nixpkgs/pull/45722

**Comment by aszlig** [comment]
@volth: See #2378.
