### ISSUE TITLE
nix show-derivation doesn't work on derivations

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nix#2342]
Which is a shame, at least I run into this often :).  Minor UX improvement opportunity :D.

**Comment by AmineChikhaoui** [comment]
Is this a new regression ? I'm on Nix 2.0.4 I think and a big user of `nix show-derivation` :) didn't notice any issues though

**Comment by edolstra** [comment]
Probably caused by 85530bcc0b4c61499f90fa6125c19beeb0f4485e.

**Comment by lheckemann** [comment]
#1918 is related I guess?

**Comment by dtzWill** [comment]
Sorry for slow response, looks like that commit fixes this nicely.  Thanks!!
