### ISSUE TITLE
nix-shell in second #! line only accepts double quotes for package expressions

### ISSUE THREAD

**Issue by cumber** [NixOS/nix#2356]
This works:

```
#! /usr/bin/env nix-shell
#! nix-shell -i runghc -p "ghc.withPackages (ps: [ ps.HTTP ])"
```

This does not:

```
#! /usr/bin/env nix-shell
#! nix-shell -i runghc -p 'ghc.withPackages (ps: [ ps.HTTP ])'
```

Running a script with the above lines produces: `error: syntax error, unexpected $undefined, at (string):1:94`

The syntax of the extra `#! nix-shell` lines looks like we're writing shell command syntax, so people think that bash-like (or at least sh-like) quoting rules would apply.

Ideally single quotes would work as well as double quotes, but either way the manual (https://nixos.org/nix/manual/#ssec-nix-shell-shebang) should at talk about how to properly quote complex arguments; currently none of the examples need quoting, and there is no mention of whether any kind of quoting is supported or not (which leads to the guess that bash-like quotes would be supported from the similar syntax).

**Comment by bhipple** [comment]
This actually just bit me a few days ago while trying to use a `python.withPackages`.  I eventually figured out the right syntax is as you have written above but a quick mention in the manual or a complex example would've been nice!

**Comment by toonn** [comment]
This is a regression. I got the exact same error on a haskell script I've used succesfully before.

**Comment by domenkozar** [comment]
Needs single quote handling in https://github.com/NixOS/nix/blob/a0ef21262f4d5652bfb65cfacaec01d89c475a93/src/nix-build/nix-build.cc#L53

**Comment by AleXoundOS** [comment]
The problem is that inner quotes need to be escaped:

```shell
#! /usr/bin/env nix-shell
#! nix-shell -E "with import <nixpkgs> { }; runCommand \"dummy\" {} \"\""
```

**Comment by AleXoundOS** [comment]
For those, who needs long/complex nix expression in shebang in a single file, I've found a [semi-solution with the help of `/usr/bin/env -S`](https://stackoverflow.com/a/68153465/1663197), what avoids this quotes issue as well.

**Comment by ncfavier** [comment]
https://github.com/NixOS/nix/pull/8470
