### ISSUE TITLE
Use sqlite dotfile vfs to allow use over NFS

### ISSUE THREAD

**Issue by wmertens** [NixOS/nix#2357]
See http://sqlite.1065341.n5.nabble.com/Safe-sqlite-over-remote-filesystem-tp103435p103438.html

Basically, by using the dotfile vfs, it should be safe to share a nix store over NFS.

The easiest way to achieve this is to simply add `"unix-dotfile"` as the fourth parameter at https://github.com/NixOS/nix/blob/19265ed26c5bd25b299896ed851bda6c444cf1a8/src/libstore/sqlite.cc#L31

However, to make this optional, I think the best way would be to instead add `SQLITE_OPEN_URI` as a flag in the third parameter on that same line, and allow specifying the `path` to the db file as an option. That `db-path` could then e.g. be `"file:/nix/store/shared-db?vfs=unix-dotfile"`, protecting against misconfiguration.

**Comment by louisabraham** [comment]
Hi, I don't think that's true, at least with NFS version 3.

**Comment by domenkozar** [comment]
This patch was mentioned in https://rgoswami.me/posts/local-nix-no-root/

**Comment by wmertens** [comment]
I'm going to close this issue, because from the thread it's obvious you can use sqlite over NFS, although the macOS implementation might cause issues.

So it's basically a niche not-quite-a-problem.

**Comment by veprbl** [comment]
Would be nice to introduce this as an option instead of applying patches as suggested in https://nixos.wiki/wiki/Nix_Installation_Guide#NFS .

**Comment by wmertens** [comment]
Now that I see how small the patch and config is, I think it does warrant an option. Perhaps the Nix option `use-sqlite-wal = false` can also open sqlite with unix-dotfile?

Reopening.
