### ISSUE TITLE
Exec nix-instantiate

### ISSUE THREAD

**Issue by haposik** [NixOS/nix#2364]
I've encountered an issue of how to run `nix-instantiate` using C style `fork + execl`.

If you try simple
```
int main() {
  execl(
      "/home/user/.nix-profile/bin/nix-instantiate", 
      "nix-instantiate", 
      "-E", "\'nixpkgs.cmake\'", nullptr
  );
}
```
you will get an error: `error: syntax error, unexpected $undefined, at (string):1:1`

Any ideas how to run nix using exec?

**Comment by shlevy** [comment]
The single quotes are passed as an argument. `'nixpkgs.cmake'` is not a valid nix expression.

**Comment by haposik** [comment]
I forgot to put `with import <nixpkgs> {};`. However.
I tried to pass single quotes as an argument as you said and it gave the same error:
```
execl(
            "/home/user/.nix-profile/bin/nix-instantiate",
            "nix-instantiate",
            "-E",
            "\'",
            "with import <nixpkgs>{}; cmake",
            "\'",
            nullptr
    );
```

**Comment by shlevy** [comment]
No, Imean drop the single quotes altogether.

**Comment by haposik** [comment]
Yup, that helped. Thank you
