### ISSUE TITLE
nix from /nix/store doesn't work outside NixOS

### ISSUE THREAD

**Issue by infinity0** [NixOS/nix#2372]
Some nix packages like nix-prefetch-git declare a dependency on nix, but this is the version of nix that exists in `/nix/store` and not the system nix e.g. the [nix Debian package](https://github.com/KaiHa/nix-debian) which configures different paths e.g. `/var/lib` instead of `/nix/var` for `localstatedir`.

This means nix-prefetch-git fails to run properly under nix-in-debian because it looks for the nix-daemon in `/nix/var` rather than `/var/lib`.

A dirty work-around is to symlink /var/lib to /nix/var.

**Comment by infinity0** [comment]
Not able to test right now but I would guess it does *not* solve the issue as I guess from the path `/var/lib` you are proposing this as a patch to the Debian packaging, but that is not the cause of the problem.

The cause of the problem is that nix-prefetch-git declares a dependency on nix, and nix resolves this to the `nix` binary in `/nix/store` which is *not the Debian packaged-nix* and so hardcodes different paths like `/nix/var` for localstatedir not `/var/lib` as Debian's nix does.

**Comment by infinity0** [comment]
Oh I suppose if the nix in /nix/store reads this environment variable then it could work yes. I'll have to test it on Monday.

Then there is also the issue of the other paths we configure like coreutils-bin and libdir. Not sure if the nix in /nix/store is dynamic enough to adopt the right values here from the system nix.

**Comment by KaiHa** [comment]
> Then there is also the issue of the other paths we configure like coreutils-bin and libdir. Not sure if the nix in /nix/store is dynamic enough to adopt the right values here from the system nix.

If an updated _nix_ is installed into the _store_ it would use the coreutils from its closure, and that should be fine. You can start a nix-shell with a _nix_ installed (`nix-shell -p nix`) and use `nix-store -qR $(readlink -f $(which nix))` to verify this yourself.

**Comment by infinity0** [comment]
Your `NIX_REMOTE` patch seems to work well for `nix-prefetch-git`, haven't noticed any problems yet. I suppose the patch looks general enough to include in Nix itself as well?

> If an updated *nix* is installed into the *store* it would use the coreutils from its closure, and that should be fine. You can start a nix-shell with a *nix* installed (`nix-shell -p nix`) and use nix-store -qR $(readlink -f $(which nix)) to verify this yourself.

I'm not sure what this is supposed to indicate? I get a bunch of paths from `/nix/store` including `/nix/store/jy9knxp7nmw80jkf932axrs1b4p9k4hi-coreutils-8.29`

**Comment by KaiHa** [comment]
> I'm not sure what this is supposed to indicate? I get a bunch of paths from /nix/store including /nix/store/jy9knxp7nmw80jkf932axrs1b4p9k4hi-coreutils-8.29

That is the closure and coreutils is a part of it. If you are interested, somewhere in [here](https://nixos.org/~eelco/pubs/phd-thesis.pdf) you can find some background information on _nix_ closures.
