### ISSUE TITLE
Installer assumes liberal umask

### ISSUE THREAD

**Issue by Valknjoggr** [NixOS/nix#2377]
I attempted to install-multi-user with 2.0.4 on Ubuntu 18.04.

I got the error below.

After scratching my head for a moment, I believe the reason this simple command failed is because of file/directory permissions. By default I believe the default Ubuntu umask is 022. I have set mine, system wide, to be 0077.

The NIX installer should set the umask/file permissions it needs.

Good luck!

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo HOME=/root /nix/store/0d60i73mcv8z1m8d2m74yfn84980gfsa-nix-2.0.4/bin/nix-env -i /nix/store/0d60i73mcv8z1m8d2m74yfn84980gfsa-nix-2.0.4

to installing a bootstrapping Nix in to the default Profile

installing 'nix-2.0.4'
building '/nix/store/9v9rz64kdblx991qw8q7472yhisz0rs2-user-environment.drv'...
while setting up the build environment: executing '/nix/store/0d60i73mcv8z1m8d2m74yfn84980gfsa-nix-2.0.4/libexec/nix/buildenv': Permission denied
builder for '/nix/store/9v9rz64kdblx991qw8q7472yhisz0rs2-user-environment.drv' failed with exit code 1
error: build of '/nix/store/9v9rz64kdblx991qw8q7472yhisz0rs2-user-environment.drv' failed

---- oh no! --------------------------------------------------------------------

**Comment by shlevy** [comment]
I'd much rather the installer error out with a helpful message in this case than set the umask itself. Presumably if the sysadmin sets the umask they have a reason, and automatically overriding that while also taking sudo seems dicey.

**Comment by dckc** [comment]
@shlevy what message would be helpful? That is: what work-around is there?

**Comment by LTArnas** [comment]
Hi,

Ran into the same exact issue just now. Some info on my environment off the bat:
OS: `Arch Linux`
Nix version: `2.3.4`
System-wide default umask (`/etc/profile`): `027`

My workaround was to set the default umask to be `022` which finished installing without throwing any error ...but I think I have to keep it to that umask for nix to keep working (for the builders). It's not really a workaround, but for me personally I can live with it. (Also had to `sudo chmod o+r /etc/profile.d/nix.sh` so doing `source /etc/profile.d/nix.sh` works.)

Just to give some more info in case it's useful. When the error happened and I ran `ls -al /nix/store` it showed that all directories were owned by `root` `user` and the `group` ownership was `root` **_except_** for what the build failed on (the `user-environment`). The `{hash}-user-environment` dir had `nixbld1:nixbld` (user:group) ownership. `{hash}-user-environemnt.lock` file had `root:root` ownership.
After I changed the `umask` to `022` and it installed without error, ownership for all directories/files in `/nix/store` are now `root:root`.

So what happened mostly makes sense to me... except not sure why everything is now `root:root`, was expecting at least `user-environment` to be  something like `nixbld1:nixbld`.
But anyways, I think if the group ownership was `nixbld` for things in `/nix/store` it would be more appropriate and would indirectly solve this? (Assuming group can be set. Don't really know; I'm newbie with linux and nix.)
(Sorry long post.)

**Comment by MartinPotier** [comment]
Hi, I hit this today, installing nix on a CentOS setup by a third party. It took me a while to figure out why the installer was failing on the server, and not in my test VM.

I think at least a message would really help debugging when the installer fails, or at least a warning: “it seems your umask is != 0002, this installation may fail” or something of the sort.

**Comment by MartinPotier** [comment]
Great news! Thx for the fix.
