### ISSUE TITLE
allowSubstitutes not documented in nix manual

### ISSUE THREAD

**Issue by cdepillabout** [NixOS/nix#2379]
The `allowSubstitutes` derivation option is [not documented](https://nixos.org/nix/manual/#sec-advanced-attributes) in the manual, but it appears to be used in quite a few places in nixpkgs.

`allowSubstitutes` appears to have been implemented in commit b64988bb358, and there is a short description of what it does:

https://github.com/NixOS/nix/commit/b64988bb3585478676585a0f0aecbcf4e11d44

There was also an issue opened up about documentation for `allowSubstitutes` a couple months ago, but it seems to have been closed before it was resolved: https://github.com/NixOS/nix/issues/1378

**Comment by cdepillabout** [comment]
There now appears to be a short explanation of this in the manual.

**Comment by samuela** [comment]
@cdepillabout I'm searching through the manual (https://nixos.org/manual/nixpkgs/stable/) but wasn't able to find any explanation of `allowSubstitutes`. Where is the explanation that you're referencing?
