### ISSUE TITLE
Nix single user install broken - 2.1

### ISSUE THREAD

**Issue by mumblez** [NixOS/nix#2401]
ref - https://discourse.nixos.org/t/nix-2-1-released/875, https://nixos.org/nix/manual/#sect-single-user-installation

on macos high sierra, ensured previous nix directories and includes were deleted and /nix dir recreated with myself as owner.

then when running the script:

```sh
$ sh <(curl https://nixos.org/nix/install) --no-daemon
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2464  100  2464    0     0  12851      0 --:--:-- --:--:-- --:--:-- 12900
downloading Nix 2.1 binary tarball for x86_64-darwin from 'https://nixos.org/releases/nix/nix-2.1/nix-2.1-x86_64-darwin.tar.bz2' to '/var/folders/02/r78q_npn2fjcww4ryr21tthr0000gp/T/nix-binary-tarball-unpack.XXXXXXXXXX.X6RMyTyT'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 28.9M  100 28.9M    0     0  4662k      0  0:00:06  0:00:06 --:--:-- 4558k
Note: a multi-user installation is possible. See https://nixos.org/nix/manual/#sect-multi-user-installation
performing a single-user installation of Nix...
copying Nix to /nix/store...................................
initialising Nix database...
error: cannot connect to daemon at '/nix/var/nix/daemon-socket/socket': No such file or directory
/var/folders/02/r78q_npn2fjcww4ryr21tthr0000gp/T/nix-binary-tarball-unpack.XXXXXXXXXX.X6RMyTyT/unpack/nix-2.1-x86_64-darwin/install: unable to register valid paths
```

**Comment by grahamc** [comment]
Your shell still has NIX_REMOTE set probably. Open a new terminal and re run the installer.

**Comment by mumblez** [comment]
@grahamc thanks, that fixed it, (I unset all NIX_* env vars)

**Comment by edolstra** [comment]
I guess we should clear `NIX_REMOTE` in the install script.

**Comment by grahamc** [comment]
Or fail. The user will have a broken Nix install until they reopen their terminals.

**Comment by cyounkins** [comment]
Just encountered this, would like to re-open.

**Comment by mattsawyer77** [comment]
In case this helps anyone, I ran into this issue yesterday but was able to solve it in my case (the hint about environment above was the key). I had done `sudo su -` to switch to the root (which IIRC causes the root session to inherit environment vars) and then the rebuild failed. I exited, and did `sudo su` instead and it worked fine.

**Comment by kiemrong08** [comment]
i just using command `unset NIX_REMOTE` and it work like a charm :)

**Comment by zktosu** [comment]
debian single user installation also raise this same issue and the solution is same: 
`unset NIX_REMOTE`

**Comment by samrose** [comment]
`unset NIX_REMOTE` fixes this problem on WSL2 in case anyone is googling this
