### ISSUE TITLE
Downloading from manifest fails if binary cache returns invalid contents

### ISSUE THREAD

**Issue by wizeman** [NixOS/nix#242]
I'm not sure if this is the right place to report this error or if I even understand it completely.

Yesterday, while the nixos.org domain was hijacked, cache.nixos.org was returning invalid contents and I think this was preventing Nix from downloading from my own Hydra channel during nixos-rebuild.

To clarify: Basically, I have my own private Hydra instance, and I added my channel using `nix-channel --add "http://localserver:3000" channelname`. I use this Hydra instance to build packages with my nixpkgs patches on top.

Normally, when I use nixos-rebuild on my laptop, nix-daemon will automatically download from localserver:3000 the already-built packages (even though I did not add localserver:3000 to /etc/nix/nix.conf, I just added the Nix channel).

However, yesterday nixos-rebuild was trying to rebuild all packages on my laptop, even though localserver already contained built packages. The only out-of-the-ordinary event yesterday was the nixos.org domain hijacking.

Also, I found out that if I used `nixos-rebuild switch --option binary-caches ""`, then Nix would work fine and download from my local server. So I guess this can be used as a workaround, but it would be nice if Nix would be fixed so that the problem didn't happen in the first place (in the event cache.nixos.org is returning invalid contents).

**Comment by edolstra** [comment]
Closing since manifest support has been removed.
