### ISSUE TITLE
Possible command addition: `nix check-references`

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#2426]
I was just thinking it would be nice to automatically add `nativeBuildInputs` (as well as the C compiler) in a derivation to the `disallowedReferences`, with an opt-out mechanism if you're sure you do want a reference. It's so easy to accidentally get a huge closure and by far the most common case is for `nativeBuildInputs` to be build tools that shouldn't appear in the outputs.

That then got me thinking, since `disallowed*` doesn't affect the derivation hash, whether we could treat this a bit like `checkMeta`, where we have a "paranoid mode" evaluation (e.g., in ofBorg) to make sure nothing bad is happening.

It then occurred to me that checking those references doesn't actually need to even perform a build: if I substitute X from a binary cache and my local expression for X says it shouldn't depend on Y, I can check that whether or not I built it. That's where this command comes in, for checking derivations whether or not you've built them, against allowed/disallowed references in your expressions.

It then occurred to me that this could actually fully support a "remote mode" where you don't even need to fetch all the nars, since all the required information is in the .narinfos. This would allow ofBorg to realistically be able to check that our closures are somewhat sensible according to rules TBD that we'd encode in nixpkgs stdenv, without having to download dozens of GB of packages.

Thoughts @NixOS/nix-core @grahamc? Am I missing anything that would make this tricky?

**Comment by 7c6f434c** [comment]
What shoud Nix do differently? Not fail by default when a disallowed reference is used? Or should there be an intermediate level of badness?

Is the extra check better implemented inside Nix or as an external tool?

**Comment by copumpkin** [comment]
I'm saying this is purely additional functionality, because we might not want to always set `disallowedReferences` since they can be a bit of a pain to debug. If we do decide to always set them, this would be less useful.

**Comment by copumpkin** [comment]
Never mind, I thought the (dis)allowed references attribute didn't feed into the derivation hash but it does, so that makes this mostly moot.
