### ISSUE TITLE
--daemon installer assumes the presence of rsync

### ISSUE THREAD

**Issue by srhb** [NixOS/nix#2437]
When `rsync` does not exist, installation fails and the user has to go through uninstalling in order to try again with rsync installed. It would be nice to either not depend on rsync being present, or guard the whole install on its presence earlier.

**Comment by masaeedu** [comment]
Could someone point me to the installer files? Just got bitten by this.

**Comment by zimbatm** [comment]
see `scripts/install-multi-user.sh`

**Comment by tv42** [comment]
Bugs don't disappear just because time passes.

**Comment by nathan-at-least** [comment]
I just encountered this 3+ year old bug while running `sh <(curl -L https://nixos.org/nix/install) --daemon`, which is the very first recommended command on [the install guide](https://nixos.org/guides/install-nix.html).

The target system is:

```
user@penguin:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

**Comment by domenkozar** [comment]
I've hit this one too. A good start would be `require_util` used to guard against rsync.
