### ISSUE TITLE
`nix run --store` doesn't work without /nix, breaking installation without root permissions

### ISSUE THREAD

**Issue by mwu-tow** [NixOS/nix#2439]
The [Installation Guide](https://nixos.wiki/wiki/Nix_Installation_Guide) states that it is possible to install `nix` without root permissions by using `--store` parameter. However I'm not quite able to get it work. 

Basically, the guide currently says that I should either:
* when having root permissions: use it to create `/nix`, chown and then run `https://nixos.org/nix/install`
* when not having root permissions: call `nix run --store` 

However, it is not clear to me how should I obtain the nix binaries without root permissions. I tried extracting them from the [official binaries package](https://nixos.org/releases/nix/nix-2.1.2/nix-2.1.2-i686-linux.tar.bz2). After setting environment (PATH, LD_LIBRARY_PATH, elf interpreter path) I am able to run nix binaries but they still seem to require the global `/nix` directory.

For example when running the command from the Guide:
```
$ nix run --store ~/my-nix nixpkgs.nix nixpkgs.bashInteractive
error: getting status of '/nix': No such file or directory
```

I believe that global `/nix` store should not be needed to create local store — not being able to create `/nix` is my reason to use local store. How can I setup nix with custom store without creating `/nix` (or any other predefined store)?

Context: I'd like to eventually be able to package&ship nix binaries and call them on user machine to setup environment with dependencies my application needs. So I can't assume any particular writable global location. I have not used nix before, so I might be missing some basic issues.

**Comment by cleverca22** [comment]
https://github.com/matthewbauer/nix-bundle is one option for doing that

**Comment by arianvp** [comment]
The documentation is indeed incorrect. I also stumbled into this when trying to install Nix on our compute cluster at the university.  Eventhough `nix run` claims to allow you to select what store to use, It can only do so if `/nix` exists...

**Comment by DavHau** [comment]
Still an issue in nix 2.3.9

**Comment by edolstra** [comment]
This works with Nix 2.4 (tested on Ubuntu 20.10):
```
$ ls -l /nix
ls: cannot access '/nix': No such file or directory

$ ./nix shell --impure -I nix=corepkgs --experimental-features 'nix-command flakes' --store ~/my-nix nixpkgs#bashInteractive -c sh
sh-4.4$ echo /nix/*
/nix/store
```

However it should work with Nix 2.3 as well, see https://github.com/NixOS/nix/blob/8803753666023882515404177b08f3f8bdad52a0/src/nix/run.cc#L207-L247.
