### ISSUE TITLE
'nix search' doesn't show the version number of packages

### ISSUE THREAD

**Issue by sixpointzero** [NixOS/nix#2442]
It's a bit baffling to see that using `$ nix search firefox` doesn't show the version of Firefox present in the channel. FWIW, I think almost all the package managers show the version number of a package which is being searched for.
Additionally, some packages like weechat don't have a version no matter where you look (fixed in master) and I get `<package-name>-unwrapped` and `<package-name>-wrapper` results for many package searches as well which I don't understand.

**Comment by sixpointzero** [comment]
> Versions not showing is a bug mentioned and fixed by PR #2312 .

Any ETA for this PR getting merged?

**Comment by dtzWill** [comment]
(don't mean to not respond, but I can't say about any ETA -- I don't have any information beyond what's on that PR, here's hoping this issue encourages the right folks to give it a look)

**Comment by sixpointzero** [comment]
Looks like the PR got merged. Thanks.

**Comment by sixpointzero** [comment]
Looks like some packages like Firefox and LibreOffice still don't report their version numbers. I guess if the authors don't write the version in the nix file, it won't be reported.

https://github.com/NixOS/nixpkgs/blob/b66d6f404ef73035dfb13acedf360ac796f38ec8/pkgs/applications/office/libreoffice/default.nix#L64

https://github.com/NixOS/nixpkgs/blob/2b5659dc04c4d163aca087bb0653337845bbdf34/pkgs/shells/bash/4.4.nix#L24
