### ISSUE TITLE
__structuredAttrs and __noChroot don't play nicely together

### ISSUE THREAD

**Issue by afldcr** [NixOS/nix#2453]
Seems that `__noChroot` ends up serialized in `env.__json`, but `build.cc` [is checking `drv->env`](https://github.com/NixOS/nix/blob/bba3f0a308cceb56bad4aa1efe13927360ae463f/src/libstore/build.cc#L1812) for the `__noChroot` attribute (which only has `__json` in it).

Thus, I can't escape the sandbox with structured attributes, which is required by a few complicated builds in our toolchain.

**Comment by afldcr** [comment]
Update: in a similar vein, `__structuedAttrs` seems to cause `preferLocalBuild` to be ignored.

**Comment by edolstra** [comment]
Yeah, we need to fix all lookups in `drv->env` (`requiredSystemFeatures`, `__sandboxProfile`, `__impureHostDeps`, `impureEnvVars`, and a bunch of others).

**Comment by afldcr** [comment]
Anything I can do to help? Nix backs our build system and structured attributes are pretty desirable for us.

Looking at the resulting drvs, it seems `out` is also tacked on, so presumably `__json` isn't the only parameter that stays in `env`.
