### ISSUE TITLE
bash: .bash_profile: No such file or directory

### ISSUE THREAD

**Issue by 2mol** [NixOS/nix#2461]
On mac, if I drop into a shell with `nix-shell -p something` from **within a subfolder**, it fails to find the `.bash_profile` in my home directory.

So `~/code $ nix-shell -p ffmpeg` would not have my .bash_profile sourced, while `~ $ nix-shell -p ffmpeg` does.

Not a huge issue, but confusing. Or is it by design?

**Comment by grahamc** [comment]
This isn't coming from Nix, but probably from one of your bashrc / profile scripts. If you enter `code` and run `bash`, do you get the same output?

**Comment by 2mol** [comment]
Yes, I do :)

I don't know why yet, but closed since definitely not nix related. Thanks for the hint though!
