### ISSUE TITLE
Nix does not create `~/.cache/nix` if it does not exist

### ISSUE THREAD

**Issue by mkaito** [NixOS/nix#2465]
I've recently taking to mounting `~/.cache` on tmpfs, which means that after a reboot it's completely empty. This should be fine. Cache should be expected to just evaporate.

```
❯ nix-shell
error: opening lock file '/home/mkaito/.cache/nix/git.lock.lock': No such file or directory
(use '--show-trace' to show detailed location information)

❯ mkdir -p ~/.cache/nix

❯ nix-shell

[nix-shell:~/work/project_thing]$
```

**Comment by yegortimoshenko** [comment]
This actually is a fallout from applied https://github.com/NixOS/nix/pull/2422 patch. @mkaito, please repin.

**Comment by mkaito** [comment]
Sorry for the noise!
