### ISSUE TITLE
Support for SI suffixes for min-free and max-free

### ISSUE THREAD

**Issue by Moredread** [NixOS/nix#2469]
It seems that the `min-free` and `max-free` options don't support suffixes. I.e

```
> nix --version
nix (Nix) 2.1.1
> nix-build '<nixpkgs>' -A hello --option max-free 1G
warning: setting 'max-free' has invalid value '1G'
(...)
```

Have I overlooked something?

**Comment by Profpatsch** [comment]
Good first step is to document the unit in the manpage. I assume its `bytes`? But I’ve seen software that defaults to kilobytes …

**Comment by Moredread** [comment]
> 
> 
> Good first step is to document the unit in the manpage. I assume its `bytes`? But I’ve seen software that defaults to kilobytes …

This has been added in the mean time. :)

https://github.com/NixOS/nix/blob/35205e2e922952fc0654260a07fc3191c5afc2cc/src/libstore/globals.hh#L802-L817
