### ISSUE TITLE
Send public keys when requesting narinfo

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nix#2471]
I'd like to propose a light (backward compatible) change to the binary cache api.

# Motivation

Nowadays cachix configures separate URL (https://"name".cachix.org) for each binary cache,
which can quickly accumulate to 5-10 entries. During development,
this slows down Nix invocations as all of the binary caches will return 404. For example,
building 100 derivations that would result in 500 HTTP queries to be made by Nix.

One possible solution would be that https://cachix.org/"hash".narinfo is requested
for all binary caches hosted, but only different public keys are whitelisted locally.

However, store hash belonging to a nar can be of different fingerprint as nars are often
non-binary deterministic.

# Implementation

When requesting narinfo, pass public keys that Nix considers valid:

https://cachix.org/"hash".narinfo?publicKey="base64"&publicKey="base64"

This would mean static binary caches can ignore query arguments, but
cachix would be able to serve narinfo belonging to the first matching public key.

# Alternative implementations 

Be able for a binary cache to tell what could be "upstream" binary cache,
but that is more complicated and harder to implement.

# Open questions

- Does this affect affect narinfo CDN cache (and does it matter that much anyway)? :)

- Privacy concerns sending public keys to the server?

**Comment by domenkozar** [comment]
@grahamc would you consider information leakage if the identifier was left out? So:

`6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=`

instead of `cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=`.

That would still allow to do filtering without leaking any information (one couldn't associate pubic key with domain, unless it was already really public, but then what's the leakage?).

**Comment by domenkozar** [comment]
Actually, Nix could only set the public keys that match the public key domain prefix.

**Comment by grahamc** [comment]
Yes, I would. Every cache can then build a graph of everyone who trusts 6NCH... and find relationships between them. Domain prefixes are hard, because what is the domain prefix for s3.dualstack.us-east-1.amazonaws.com, or s3-us-east-1.amazonaws.com or s3.amazonaws.com or mybucket.s3.amazonaws.com or mybucket.s3-aws-region.amazonaws.com.

**Comment by domenkozar** [comment]
I'm suggesting no guessing, just the actual domain (prefix of the public key).

So given the keys:

 ```
cachix.org-mycache-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
cachix.org-myothercache-1:7NZBdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
```

And then when querying `cachix.org`, it would only send the first two keys. As the part before the colon is just an identifier I don't see any need for special support for prefixes.

**Comment by grahamc** [comment]
Hmm maybe, it is a bit weird though: I'm not sure there is a very good algorithm for determining what is the suffix vs. prefix of the key. Especially if we enter the realm of custom TLDs inside corporate networks, where it is valid to have the TLD `org-mycache-1`.

**Comment by edolstra** [comment]
Some issues with this:

* It greatly reduces CDN effectiveness. For example, with `http://cache.nixos.org`, narinfo cache hits are about 10 times faster than cache misses (0.06s vs 0.617s).

* The binary cache mechanism is designed for static file servers (like S3). If you have an dynamic server, then you can design a much more efficient protocol. E.g. you can ask the server for all missing paths at the same time, let the server compute closures, compute binary patches from what the client already has, etc.

* It breaks the assumption that store paths are unique for each store. For example, `NarInfoDiskCache` uses a primary key `(cache, hashPart)`.

**Comment by grahamc** [comment]
> The binary cache mechanism is designed for static file servers (like S3). If you have an dynamic server, then you can design a much more efficient protocol. E.g. you can ask the server for all missing paths at the same time, let the server compute closures, compute binary patches from what the client already has, etc.

This could be cool, and even implemented in Nix itself!

**Comment by domenkozar** [comment]
Hmm maybe, it is a bit weird though: I'm not sure there is a very good algorithm for determining what is the suffix vs. prefix of the key. 

```
publicKey.startsWith(domain)
```

> Especially if we enter the realm of custom TLDs inside corporate networks, where it is valid to have the TLD org-mycache-1.

Do you realistically expect someone to match those two up? :)

> It greatly reduces CDN effectiveness. For example, with http://cache.nixos.org, narinfo cache hits are about 10 times faster than cache misses (0.06s vs 0.617s).

Most CDNs allow rules to apply where you can filter out certain things like query flags. I agree this needs to be solved, but most CDNs allow it: https://docs.fastly.com/guides/performance-tuning/making-query-strings-agnostic

> The binary cache mechanism is designed for static file servers (like S3). If you have an dynamic server, then you can design a much more efficient protocol. E.g. you can ask the server for all missing paths at the same time, let the server compute closures, compute binary patches from what the client already has, etc.

Yes in fact I have a prototype implementation for Cachix in a branch. That is orthogonal issue though, you still need to solve the problem of what store path belonds to what public key.

> It breaks the assumption that store paths are unique for each store. For example, NarInfoDiskCache uses a primary key (cache, hashPart).

I don't expect that to be an issue, substitution is deterministic so it should get the first path that matches the store path and public key for the user. Only if they switch the order of keys, it would be an inconvenience.

**Comment by domenkozar** [comment]
@edolstra on second thought, maybe it's better to implement mass lookup with the public key reveal, but I fear that's quite some work.

**Comment by edolstra** [comment]
Maybe the binary cache could be something like `http://cachix.org/<username>` that only serves narinfos to which a user has access?

**Comment by domenkozar** [comment]
That would require users to register on cachix in order to use the binary caches, which I'd consider quite unfortunate.

**Comment by 7c6f434c** [comment]
@domenkozar this suggestion can be reinterpreted in the following way: a registered user is allowed to say that the new cache depends on some old caches and doesn't need to reupload the repeated paths. Then if someone uses the same caches over and over, they can create a dependent cachix cache, not put anything extra in it and maybe even share the link.

The suggestion by @grahamc for creating such union caches on the fly via URLs is sometimes more and sometimes less convenient.

**Comment by domenkozar** [comment]
That is something I call "upstream cache" (see https://github.com/cachix/cachix/issues/16) and I plan to implement it after authenticated caches are finished.

However, I'd like to fix Nit itself talking to many binary caches without having too much performance hit and I do want to make the solution cachix agnostic. That way we all benefit :)

**Comment by 7c6f434c** [comment]
I have an impresssion that what you are proposing is a way for related non-static caches to combine the requests. And any solution will need to be implemented on the Cachix side after being accepted as a roadmap.

Is there an obvious benefit for the Cachix use case if there is something added on the Nix side?

If there is a cachix-side-only implementation, data gathered about it might help to refine and support the requests for Nix-side features…

**Comment by domenkozar** [comment]
Doesn't seem this will land in Nix, so I'll implement something specific to cachix.
