### ISSUE TITLE
Nix does not work on Ubuntu 14.04

### ISSUE THREAD

**Issue by karltk** [NixOS/nix#249]
The 1.6.2 and 1.7 releases of Nix are compiled against Perl v5.14.0, but Ubuntu 14.04 provides v5.18.0. This means that the deb-files won't work on Ubuntu 14.04, due to:

```
Perl API version v5.14.0 of Nix::Store does not match v5.18.0 at /usr/share/perl/5.18/XSLoader.pm line 92.
```

In all fairness, this is to be expected, since the .deb files are only claiming support for 13.10.

Any chance Ubuntu 14.04 could be added to the list of release targets?

**Comment by wmertens** [comment]
This again begs the question of why building distro packages with distro
dependencies that break? Why not simply package nix with all its
dependencies?
