### ISSUE TITLE
preferLocalBuild is ignored when __structuredAttrs = 1

### ISSUE THREAD

**Issue by symphorien** [NixOS/nix#2515]
Steps to reproduce:
* setup remote builds
* this builds locally:
```
nix-build -E 'with import <nixpkgs> {}; runCommand "test" { preferLocalBuild = true; } "echo yay; touch $out"' 
```
* this builds remotely
```
nix-build -E 'with import <nixpkgs> {}; runCommand "test" { preferLocalBuild = true; __structuredAttrs = true; } "echo yay; touch $out"'
```

(with nix 2.1.1)

Motivation: add `preferLocalBuild` on pkgs/build-support/closure-info.nix in nixpkgs. All the dependencies are on the local machine, so it is wasteful to copy them to a remote machine to list them.

**Comment by edolstra** [comment]
This is fixed in 7ae7a38c9a7d0a5679e65c8213cd7b58dfdc1c52.
