### ISSUE TITLE
[nix-mode] Double-single-quoted strings?

### ISSUE THREAD

**Issue by relrod** [NixOS/nix#253]
Sorry for the confusing title :P

It would be nice if `misc/emacs/nix-mode.el` could recognize and highlight strings in the form of:

```
longDescription = ''
some string
within double single-quotes.
'';
```

I tried patching it, but my elisp-fu is just not good enough right now to figure it out and I didn't make much progress.

**Comment by Ericson2314** [comment]
This can be closed because of $870
