### ISSUE TITLE
Timezone Reset on nix-shell

### ISSUE THREAD

**Issue by Gerschtli** [NixOS/nix#2541]
I have ran into the problem that the timezone is reset when entering in **any** `nix-shell` like the following example:

```sh
$ echo $TZ
Europe/Berlin
$ date
Do 15. Nov 18:16:43 CET 2018
$ nix-shell -p bashInteractive                                    
[nix-shell]$ echo $TZ
Europe/Berlin
[nix-shell]$ date
Do 15. Nov 17:17:02 Europe 2018
```

 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0-38-generic, Ubuntu, 18.04.1 LTS (Bionic Beaver)`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.1.3`
 - channels(tobi): `"nixpkgs-19.03pre158285.30707eb8ef0, nixpkgs-php-18.03.133280.862fb5215f0, nixpkgs-unstable-19.03pre154729.938a0ddf4a0"`
 - nixpkgs: `/home/tobi/.nix-defexpr/channels/nixpkgs`

**Comment by 7c6f434c** [comment]
I guess it resets `$TZDIR`.

**Comment by Gerschtli** [comment]
`$TZDIR` is always not set:

```
$ [[ "x${TZDIR}" == "x" ]] && echo "empty"
empty
$ date
Fr 16. Nov 11:37:04 CET 2018
$ nix-shell -p bashInteractive                                    
[nix-shell]$ [[ "x${TZDIR}" == "x" ]] && echo "empty"
empty
[nix-shell]$ date
Fr 16. Nov 10:37:23 Europe 2018
```

**Comment by edolstra** [comment]
This is not really a Nix issue, more a Glibc in Nixpkgs issue. It requires `TZDIR` to be set if `TZ` is used. You can also leave both unset and rely on `/etc/localtime`.

**Comment by Gerschtli** [comment]
I will test it on monday, thank you!

**Comment by Gerschtli** [comment]
@edolstra You are right, `unset TZ` did fix the issue. Thank you!
