### ISSUE TITLE
nix-instantiate re-downloads channel tarball every time

### ISSUE THREAD

**Issue by DzmitrySudnik** [NixOS/nix#2555]
I want to use a particular channel for my nix-instantiate commands, but I didn't expect nix to download the channel every single time I call nix-instantiate. It unpacks it just once.

the first call for a particular channel:
`> nix-instantiate  -vv -I "nixpkgs=https://hydra.nixos.org/build/84557120/download/1/nixpkgs-19.03pre160482.31de7743f8a.tar.xz" --eval --json --strict --expr "<nixpkgs>"
evaluating file '/nix/store/dkjlfkrknmxbjmpfk3dg4q3nmb7m3zvk-nix-2.1.3/share/nix/corepkgs/derivation.nix'
downloading 'https://hydra.nixos.org/build/84557120/download/1/nixpkgs-19.03pre160482.31de7743f8a.tar.xz'...
unpacking 'https://hydra.nixos.org/build/84557120/download/1/nixpkgs-19.03pre160482.31de7743f8a.tar.xz'...
copied source '/nix/store/6iy53pl4dc7kl80m9cll6gphahjkiara-nixpkgs-19.03pre160482.31de7743f8a.tar.xz' -> '/nix/store/krddjqq7898rsfssw9w61q0909la04yd-6iy53pl4dc7kl80m9cll6gphahjkiara-nixpkgs-19.03pre160482.31de7743f8a.tar.xz'
"/nix/store/krddjqq7898rsfssw9w61q0909la04yd-6iy53pl4dc7kl80m9cll6gphahjkiara-nixpkgs-19.03pre160482.31de7743f8a.tar.xz"`

all consequent calls:
`> nix-instantiate  -vv -I "nixpkgs=https://hydra.nixos.org/build/84557120/download/1/nixpkgs-19.03pre160482.31de7743f8a.tar.xz" --eval --json --strict --expr "<nixpkgs>"
evaluating file '/nix/store/dkjlfkrknmxbjmpfk3dg4q3nmb7m3zvk-nix-2.1.3/share/nix/corepkgs/derivation.nix'
downloading 'https://hydra.nixos.org/build/84557120/download/1/nixpkgs-19.03pre160482.31de7743f8a.tar.xz'...
copied source '/nix/store/6iy53pl4dc7kl80m9cll6gphahjkiara-nixpkgs-19.03pre160482.31de7743f8a.tar.xz' -> '/nix/store/krddjqq7898rsfssw9w61q0909la04yd-6iy53pl4dc7kl80m9cll6gphahjkiara-nixpkgs-19.03pre160482.31de7743f8a.tar.xz'
"/nix/store/krddjqq7898rsfssw9w61q0909la04yd-6iy53pl4dc7kl80m9cll6gphahjkiara-nixpkgs-19.03pre160482.31de7743f8a.tar.xz"`

And in few cases it caused the call to fail due to networking issues (this is how I stumbled upon that issue originally), when the tarball was already downloaded and stored in nix/store, but nix-instantiate didn't use it.

If that's expected, I can cache the tarball locally once, but want to make sure that it's intended or a real issue.

Thanks

**Comment by 7c6f434c** [comment]
I think one of the intended use-cases is to use a fixed URL where the channel tarball is updated in-place. For fixed-content URLs I guess a wrapper script that caches the tarball and calls nix-instantiate is simple enough to be the best short-term solution…

**Comment by DzmitrySudnik** [comment]
Thanks @7c6f434c , stable URL for channel makes total sense. And probably making any analysis of url on the nix tooling side is error prone. Closing the issue.
