### ISSUE TITLE
nix-collect-garbage --delete-older-than 12m deletes all but 12 days worth of generations, rather than 12 months

### ISSUE THREAD

**Issue by obadz** [NixOS/nix#2557]
The doc is a bit vague:

> --delete-older-than period, where period is a value such as 30d

You'd think "such as 30d" means you're allowed modifiers other than "d". Not only is that not the case, the `deleteOlderThan` function does not even check that the modifier is `== 'd'` so that basically no matter what you pass, it will be taken as a number of days.

Expected behavior: crash when modifier `!= 'd'` or support more modifiers.

**Comment by 3noch** [comment]
Yikes this is really bad.

**Comment by nielsegberts** [comment]
Likewise `--delete-older-than 10` deletes everything older than a single day. I have sent a pull request.
