### ISSUE TITLE
Instalation on Debian 9

### ISSUE THREAD

**Issue by Zelenyy** [NixOS/nix#2616]
Hello.

I want install Nix manager on Deabian 9, but have some difficulties.

1. Installation wiht curl:
```
curl https://nixos.org/nix/install | sh
```
Print error:
```
/nix/store/cdcia67siabmj6li7vyffgv2cry86fq8-nix-2.1.3/bin/nix-store: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
/tmp/nix-binary-tarball-unpack.O8lLIncpF0/unpack/nix-2.1.3-x86_64-linux/install: failed to initialize the Nix database
```
But zlib alreade installed in system.

2. Installation from source
```
checking for sqlite3 >= 3.6.19... no
configure: error: Package requirements (sqlite3 >= 3.6.19) were not met:

No package 'sqlite3' found
```
But sqlite3 also installed in system.

**Comment by KaiHa** [comment]
Hi @Zelenyy, building on a Debian 9 works for me. Take a look [here][1] for the necessary build dependencies.

[1]: https://github.com/KaiHa/nix-debian/blob/debian/stretch/debian/control

**Comment by Zelenyy** [comment]
@KaiHa Thank you for help. I install dependencies from link and could move forward in installation from source. In current time, I have problem with `libeditline`, I have installed package `libeditline-dev`, but its don't meet requirements of pkg-config.
```
checking for EDITLINE... no
configure: error: Package requirements (libeditline) were not met:

No package 'libeditline' found
```

---


Situation with installation from binary don't change - probability problem is libz.so, or I don't understand which package could install this library (I install all packages from your link) or this library have unusual name or location.

**Comment by Zelenyy** [comment]
@KaiHa I successfully completed installation process. I am grateful for your help.

**Comment by MatrixManAtYrService** [comment]
This didn't work for me, when building I would run into errors like:
```
undefined reference to `rl_readline_name'
```

I ended up building and installing https://github.com/troglobit/editline which seemed to do the trick

**Comment by mallilinux1978** [comment]
i've similar problem but on RHEL 8 though readline RPMs exists.

configure: error: Nix requires libeditline; it was found neither via pkg-config nor its normal header.

# rpm -qa | grep readline
readline-7.0-10.el8.x86_64
readline-devel-7.0-10.el8.x86_64
