### ISSUE TITLE
Nix 2.0 deterministic build options don't do anything

### ISSUE THREAD

**Issue by arianvp** [NixOS/nix#2619]
From the docs:

```
repeat                                      The number of times to repeat a build in order to verify determinism.
enforce-determinism                         Whether to fail if repeated builds produce different output
run-diff-hook                               Whether to run the program specified by the diff-hook setting repeated builds produce a different result.
```

However, all these options seem to be ignored.  Given the following clearly non-deterministic build:

```nix
{ pkgs ? import <nixpkgs> {}}:
pkgs.runCommand "yop" {} 
''
echo "Spawning 100 processes"
for i in {1..100} ; do ( echo $RANDOM >> $out & ) ; done
''
```

A `nix build` just builds it once, instead of 20 times, whilst checking determinism

```
[arian@ryzen:~/Projects/nondet]$  nix build -f . --repeat 20 --enforce-determinism --diff-hook $(nix-build '<nixpkgs>' -A diffoscope) --run-diff-hook
[1 built]
```

**Comment by arianvp** [comment]
This seems sort of related, but not fully: https://github.com/NixOS/nix/issues/1911

**Comment by arianvp** [comment]
This feature was added in `2.0` so I guess it's a regression that it's broken now?
https://github.com/NixOS/nix/blob/master/doc/manual/release-notes/rl-2.0.xml#L531-L541

the original commits, per release notes:
https://github.com/NixOS/nix/commit/8bdf83f936adae6f2c907a6d2541e80d4120f051
https://github.com/NixOS/nix/commit/9a313469a4bdea2d1e8df24d16289dc2a172a169

Ping @edolstra since you introduced it in 2.0.

**Comment by arianvp** [comment]
Theory:  Maybe there's a bug where not all CLI arguments are correctly passed as nix config?

**Comment by fzakaria** [comment]
@arianvp i don't think you can customize nix config as command line.
somewhat related https://github.com/NixOS/nix/issues/3824

**Comment by lheckemann** [comment]
> Theory: Maybe there's a bug where not all CLI arguments are correctly passed as nix config?

Are you a trusted user?

@fzakaria yes you can generally speaking, the problem is that nix will silently ignore settings under some circumstances, the most common being that the invoking user isn't listed in trusted-users. In some cases owning the store doesn't make you a trusted user (#3247); in others, settings passed on the command line are claimed to be ignored due to not being a trusted user, but still take effect (#3536). It's a bit of a mess.

**Comment by Artturin** [comment]
```bash
rm result && nix store delete /nix/store/915gr6v47i68hifzhcn6568h12izlasf-yop

# Respects --repeat because the build result isn't built yet
> $HOME/nixgits/nix/outputs/out/bin/nix build -f $HOME/repeat.nix --repeat 2 --extra-experimental-features 'nix-command' -v -L
building '/nix/store/a3hwlab7y36f3hv76r47472nxrwgn05p-yop.drv' (round 1/3)...
yop> Spawning 100 processes
building '/nix/store/a3hwlab7y36f3hv76r47472nxrwgn05p-yop.drv' (round 2/3)...
yop> Spawning 100 processes
error: output '/nix/store/915gr6v47i68hifzhcn6568h12izlasf-yop' of '/nix/store/a3hwlab7y36f3hv76r47472nxrwgn05p-yop.drv' differs from previous round


# Building yop so that the out path is in the store
> $HOME/nixgits/nix/outputs/out/bin/nix build -f $HOME/repeat.nix --extra-experimental-features 'nix-command' -v -L
building '/nix/store/a3hwlab7y36f3hv76r47472nxrwgn05p-yop.drv'...
yop> Spawning 100 processes


# --repeat does not work anymore
> $HOME/nixgits/nix/outputs/out/bin/nix build -f $HOME/repeat.nix --repeat 2 --extra-experimental-features 'nix-command' -v -L


# Doesn't show the round msg
> $HOME/nixgits/nix/outputs/out/bin/nix build -f $HOME/repeat.nix --repeat 2 --extra-experimental-features 'nix-command' -v -L --rebuild
checking outputs of '/nix/store/a3hwlab7y36f3hv76r47472nxrwgn05p-yop.drv'...
yop> Spawning 100 processes
error: derivation '/nix/store/a3hwlab7y36f3hv76r47472nxrwgn05p-yop.drv' may not be deterministic: output '/nix/store/915gr6v47i68hifzhcn6568h12izlasf-yop' differs
```

i guess https://github.com/NixOS/nix/blob/8ad485ea893862029e02cb560a15fd276753b04f/src/libstore/build/derivation-goal.cc#L539 isn't being reached

also as a sidenote if `--no-enforce-determinism` is not used then a `result` symlink won't be created in the first case

**Comment by libjared** [comment]
If the output already exists in the store, running this will build just one time, even though it displays "(round 1/4)".
```zsh
nix build '.#somepkg' --no-link --rebuild --repeat 3
```

I can confirm the workaround works:
```zsh
nix store delete '.#somepkg'
# because the output doesn't exist yet, don't pass --rebuild
nix build '.#somepkg' --no-link --repeat 3
```

**Comment by Artturin** [comment]
repeat was removed in  https://github.com/NixOS/nix/pull/7099
