### ISSUE TITLE
Nix installation via `curl https://nixos.org/nix/install | sh` fails with hash mismatch

### ISSUE THREAD

**Issue by maxhbr** [NixOS/nix#2623]
Currently, when calling the command `curl https://nixos.org/nix/install | sh`, the installation fails with the following hash mismatch:
<pre>
$ <b>curl https://nixos.org/nix/install | sh</b>
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2416  100  2416    0     0  16231      0 --:--:-- --:--:-- --:--:-- 16214
downloading Nix 2.2 binary tarball for x86_64-linux from 'https://nixos.org/releases/nix/nix-2.2/nix-2.2-x86_64-linux.tar.bz2' to '/tmp/nix-binary-tarball-unpack.sL4pJQLPSw'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 22.5M  100 22.5M    0     0  2944k      0  0:00:07  0:00:07 --:--:-- 3105k
sh: <b>SHA-256 hash mismatch</b> in 'https://nixos.org/releases/nix/nix-2.2/nix-2.2-x86_64-linux.tar.bz2'; expected sha256-R+JUpKAaI7B/bI40beaHpB8tkqPkoQBNE+906QOR4Xk=, got 47e254a4a01a23b07f6c8e346de687a41f2d92a3e4a1004d13ef74e90391e179
</pre>

### More information:
tested on clean debian stretch VM, state of the install script was:
```
$ curl https://nixos.org/nix/install | md5sum -
a3ba6bf7f7b34b18055526b02c02bfc8  -
$ curl https://nixos.org/nix/install
[...]
case "$(uname -s).$(uname -m)" in
    Linux.x86_64) system=x86_64-linux; hash=sha256-R+JUpKAaI7B/bI40beaHpB8tkqPkoQBNE+906QOR4Xk=;;
    Linux.i?86) system=i686-linux; hash=sha256-p21jJmfiSvCgBLXqhpKIcf1dK9WjB3IRXmiS88k0428=;;
    Linux.aarch64) system=aarch64-linux; hash=sha256-6WO5d35Lhb172x96/BlE8sLNyP+c46DxpH1a4DwIaoU=;;
    Darwin.x86_64) system=x86_64-darwin; hash=sha256-1zRgN1HUvaA+FJjOLSVlLv5+f9bdHBbBVKTBYTpSj68=;;
    *) oops "sorry, there is no binary distribution of Nix for your platform";;
esac

url="https://nixos.org/releases/nix/nix-2.2/nix-2.2-$system.tar.bz2"
[...]
```
Tested on multiple machines in the same network.

**Comment by edolstra** [comment]
Thanks, fixed!

**Comment by maxhbr** [comment]
Great!
