### ISSUE TITLE
Regression: error: restoring parent mount namespace: Invalid argument

### ISSUE THREAD

**Issue by mpickering** [NixOS/nix#2646]
There is a regression in `2.2` due to the following two commits.

a32ff2573ba4d0df4e3360c5a96398738da953f6
a0ef21262f4d5652bfb65cfacaec01d89c475a93

Reverting these two commits causes the error not to happen.

It can be reproduced by running this script.

https://github.com/mpickering/ghc-artefact-nix/blob/master/ghc-head-from.sh

```
wget https://github.com/mpickering/ghc-artefact-nix/blob/master/ghc-head-from.sh
nix-shell -p jq
./ghc-head-from.sh
```

**Comment by mpickering** [comment]
@tilpner says this can be reproduced with `nix-shell -p hello` rather than my complicated instructions.

**Comment by edolstra** [comment]
On what system?

**Comment by mpickering** [comment]
@edolstra We are both on NixOS.

**Comment by tilpner** [comment]
@iblech Are you sure it requires 2.? Mounting/unmounting is not necessary here.

**Comment by iblech** [comment]
You are right! Condition 2 is not necessary. Reliably, the following happens:

* A first invocation of `nix-shell -p foo`, for any value of `foo` I've tested, successfully fetches the required derivations and then aborts with `error: restoring parent mount namespace: Invalid argument`.
* A second invocation immediately following the first one works just fine.

This is on Kernel 4.20.6 on a virtual private server.

**Comment by volth** [comment]
```
nix-shell --run git -p git \
  --option binary-caches http://cache.nixos.org \
  -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/18.09.tar.gz
```
as root
100% reproducible

**Comment by iblech** [comment]
Can confirm, @volth's error-inducing approach is 100% reproducible here.

**Comment by 7c6f434c** [comment]
With prefetched `git` from all versions (no builds necessary):
* `NIX_REMOTE=daemon` of course helps
* `-I nixpkgs=` to an `https://` URL fails as reported
* the Nixpkgs tarball being cached doesn't change anything
*  `file:///` URL also fails
* local directory as Nixpkgs path works fine
* local tarball as a file gets interpreted as a Nix file and doesn't provide a data point

**Comment by edolstra** [comment]
This is caused by
> EINVAL The caller is multithreaded and tried to join a new user namespace.
We need to get rid of all other threads before restoring the mount namespace.

**Comment by arianvp** [comment]
I can reproduce this on `19.03`.  Not consistently though

```
[root@nixos1903true-s-1vcpu-1gb-ams3-01:~]# nix run nixpkgs.hello
[1 copied (0.2 MiB), 0.0 MiB DL]
error: restoring parent mount namespace: Invalid argument
```

**Comment by edolstra** [comment]
I've created a 2.2.2 release that contains the fix.

**Comment by arianvp** [comment]
Great!
