### ISSUE TITLE
installation without internet connection

### ISSUE THREAD

**Issue by zoranbosnjak** [NixOS/nix#2650]
Nix installation (via `install-multi-user`) fails if the server is not connected to the Internet.
It seems like the only problem is `/nix-channel --update` step. Please consider making this step optional or some other method, so that the installation is also possible without the Internet.

**Comment by bjornfor** [comment]
Fixed on master: https://github.com/NixOS/nix/commit/989cb3777753024072160776ea37348689b89d44

**Comment by bjornfor** [comment]
(I have don't have rights in this repo to close issues.)

**Comment by zoranbosnjak** [comment]
It works as expected. 
Tested with `nix-2.3.10`, using both `install` and `install-multi-user` scripts.
