### ISSUE TITLE
Nix aborts with "Killed: 9" when I run commands with `nix-build` or `nix-shell`

### ISSUE THREAD

**Issue by gamb** [NixOS/nix#2655]
After a successful install on Mac OS (High Sierra 10.13.6): https://gist.github.com/gamb/4ff732610f1c2c523dd8ca0cfd359628#file-install-result

Any command aborts with `Killed: 9`. Example:
```
bash-3.2$ nix-shell -p python
these paths will be fetched (153.01 MiB download, 755.45 MiB unpacked):
  /nix/store/0b93wc2nw1bwza844xabdzq8rlmwb2af-libc++-5.0.2
  /nix/store/0cx1dwnxhsbsm3y6q8k7r4lknwb71z8d-coreutils-8.30
  /nix/store/1056l5hdg18ci2k70cicgwnvab4ginfp-libxml2-2.9.9
[…]
  /nix/store/yk7sn5gwvw09hp8fs20c35yjji65vj7r-bash-interactive-4.4-p23-doc
  /nix/store/zk205w9w6fd77mv80iydcnp7c8s1him6-Libsystem-osx-10.11.6
copying path '/nix/store/yk7sn5gwvw09hp8fs20c35yjji65vj7r-bash-interactive-4.4-p23-doc' from 'https://cache.nixos.org'...
Killed: 9
```
If I can provide any further debugging info please let me know.

**Comment by gamb** [comment]
It dies quickly, if I `time` the above command:
```
Killed: 9

real	0m0.710s
user	0m0.457s
sys	0m0.087s
```

**Comment by matthewbauer** [comment]
This looks like #1583. I would recommend trying 10.12 or 10.14. High Sierra has some kernel bugs that make it pretty much unusable with Nix.

**Comment by gamb** [comment]
Thanks @matthewbauer, that's a shame. I'll take a look at 10.14.
