### ISSUE TITLE
Request for `nix-build` to have a flag that disables the `checkPhase`

### ISSUE THREAD

**Issue by CMCDragonkai** [NixOS/nix#2691]
I posted this previously on nixpkgs: https://github.com/NixOS/nixpkgs/issues/55425

Transferred the issue here.

**Comment by matthewbauer** [comment]
I wonder if we could put doCheck in impureEnvVars? doCheck should not effect the outputs of a package AFAICT.

**Comment by bjornfor** [comment]
What if checkPhase is used to build test coverage reports? Then the output would differ.

**Comment by lheckemann** [comment]
:-1: on this. It increases coupling between nix and nixpkgs significantly, and there are already mechanisms that allow disabling tests without affecting build purity.

**Comment by CMCDragonkai** [comment]
@lheckemann Can you point out what are these mechanisms that disable tests without affecting build purity? You're not referring to just using the `doCheck` or `doInstallCheck` attribute right?

**Comment by CMCDragonkai** [comment]
@bjornfor Shouldn't a different phase be used to build coverage reports. And why would the coverage reports be part of the out? Multiple outputs could be used to solve this?

**Comment by lheckemann** [comment]
>Because using those would change the derivation hash.

That's the point — different things are happening so it's a different derivation.

IMHO the right solution is to have a separate derivation for the tests, making sure to provide everything needed for the test in the "main" derivation's output paths.

**Comment by CMCDragonkai** [comment]
Why do you think test should be a different derivation? What is the output of the test derivation? If it builds it succeeds? If that's the solution, I'd rather just disable tests entirely and just use nix-shell and enter and run the tests then.

**Comment by lheckemann** [comment]
Or that. But either way, tests tend to have annoying side-effects that give me a strong disinclination towards making it possible to toggle them impurely. But yes, nix-shell sounds like a nice solution as well. A potential other option would be for the test derivation to always succeed and place some sort of test report in its output.

**Comment by CMCDragonkai** [comment]
Even this issue https://github.com/NixOS/nixpkgs/issues/33599 is saying it's controversial to enable checkPhase by default. IMO if checkPhase were to be made so that it is possible to mutate the outputs (perhaps via overlay fs), then enabling it by default would be uncontroversial except for the case where checks take a long time (such as in my case). At the end, if such a feature ever comes online I want to be able to interactively disable checkPhase.

**Comment by Pitometsu** [comment]
Is there such an option available now?

**Comment by Artturin** [comment]
i don't think this will ever be added (nor should it be)


this can be achieved with

`nix build --impure --expr 'with import <nixpkgs> { }; hello.overrideAttrs (_: { doCheck = false; })'`

**Comment by Enovale** [comment]
This is really frustrating when I have 32 bit packages that pull in python dependencies, so they all need to be built from source and all do extremely time consuming tests (especially for cryptography libraries). As a desktop user I see no benefit to running checks at all, so I don't want them taking up time in my builds, but I can't globally disable them as a nixpkgs overlay, because then everything will be built from source. I still think an option for this is needed.

**Comment by ralichkov** [comment]
Can't we just skip the execution of the testPhase at runtime? No change in derivation that way. As previously mentioned, python tests in dependencies can become a major bottleneck and the end user might not care for them. I certainly don't.
