### ISSUE TITLE
nix-store does not resolve symlinks consistently

### ISSUE THREAD

**Issue by marinelli** [NixOS/nix#2702]
The nix-store command does not work consistently when, for example, the `bin` directory inside the user nix profile is a symbolic link.

After a nix multi-user installation on a Debian machine, this is the contents of the _root_ user profile:

```
# ls -lF ~/.nix-profile/ | sed -rn 's/^.*1970 //p' | column -t
bin           ->  /nix/store/5hdmx9yk7gr71b98j4vh9271k0zg5jis-nix-2.2.1/bin/
etc           ->  /nix/store/5hdmx9yk7gr71b98j4vh9271k0zg5jis-nix-2.2.1/etc/
include       ->  /nix/store/5hdmx9yk7gr71b98j4vh9271k0zg5jis-nix-2.2.1/include/
lib           ->  /nix/store/5hdmx9yk7gr71b98j4vh9271k0zg5jis-nix-2.2.1/lib/
libexec       ->  /nix/store/5hdmx9yk7gr71b98j4vh9271k0zg5jis-nix-2.2.1/libexec/
manifest.nix  ->  /nix/store/zr8iyar7k8l6y1frlhbrhygzacmjjabw-env-manifest.nix
share         ->  /nix/store/5hdmx9yk7gr71b98j4vh9271k0zg5jis-nix-2.2.1/share/
```

The only installed package is `nix`:
```
# nix-env -q
nix-2.2.1
```

If I try to print the references for the `nix` command, it returns an error:
```
# nix-store -q --references $(which nix)
error: path '/root/.nix-profile/bin/nix' is not in the Nix store
```

The package is properly installed. Here I print the references of the full store path for `nix`:
```
# nix-store -q --references $(readlink -f $(which nix)) | tail -n1
/nix/store/5hdmx9yk7gr71b98j4vh9271k0zg5jis-nix-2.2.1
```

On the other hand, if I install an other package, like `hello`, nix-store prints the references correctly:
```
# nix-env -i hello
installing 'hello-2.10'
# nix-store -q --references $(which nix) | tail -n1
/nix/store/5hdmx9yk7gr71b98j4vh9271k0zg5jis-nix-2.2.1
```

One of the difference is that the `bin` path inside the nix user profile is no more a symbolik link but a directory. And it's correct due to the fact that the new user derivation depends on `nix` and `hello`.
```
# ls -lF ~/.nix-profile/ | sed -rn 's/^.*1970 //p' | column -t
bin/
etc           ->  /nix/store/5hdmx9yk7gr71b98j4vh9271k0zg5jis-nix-2.2.1/etc/
include       ->  /nix/store/5hdmx9yk7gr71b98j4vh9271k0zg5jis-nix-2.2.1/include/
lib           ->  /nix/store/5hdmx9yk7gr71b98j4vh9271k0zg5jis-nix-2.2.1/lib/
libexec       ->  /nix/store/5hdmx9yk7gr71b98j4vh9271k0zg5jis-nix-2.2.1/libexec/
manifest.nix  ->  /nix/store/wvi4zq99sqc72f4rb0gf6z105qvrl4gg-env-manifest.nix
share/
```

In the end, nix-store seems to be not capable of managing symbolic link resolution inside the user profile, and the query command works inconsistently, depending on the current derivation.

**Comment by PeterWang-dev** [comment]
Same issue occurs on Arch Linux packaged nix.
