### ISSUE TITLE
builtins.exec: Allow setting environment variables for the chilid process.

### ISSUE THREAD

**Issue by ElvishJerricco** [NixOS/nix#2721]
There should be a variant of `builtins.exec` that lets you set environment variables. Lots of programs have features that require environment variables to use.

**Comment by shlevy** [comment]
How bad would it be to have to call a wrapper?

**Comment by LnL7** [comment]
What would this enable that's not possible with `env`?

```
nix-repl> let foo = ''40 + 2''; in
          builtins.exec ["/usr/bin/env" "FOO=${foo}" "sh" "-c" "echo $FOO"]
42
```

**Comment by ElvishJerricco** [comment]
@LnL7's solution is nice. I'll close this until someone comes up with a reason they can't use `env` :P
