### ISSUE TITLE
Suggestion: don't hardlink symlinks

### ISSUE THREAD

**Issue by yotann** [NixOS/nix#2738]
Currently, `nix-store --optimise` treats identical symlinks just like identical regular files: it replaces them with hardlinks to each other. While this is technically correct, hardlinked symlinks are unusual enough to cause problems with buggy tools or nonstandard filesystems. They're also nonportable, needing workarounds for [Darwin](https://github.com/NixOS/nix/commit/e98c029717016dfa3e5c618c9fc46da9b2142dcc) and [IllumOS](https://github.com/joyent/illumos-joyent/issues/84).

I personally ran into problems when using BusyBox `tar` on `/nix/store`, because it didn't handle hardlinked symlinks properly ([fixed in BusyBox 1.29](https://git.busybox.net/busybox/commit/?id=8c24af9dcfe0d89a660c39838eec4d20bc13efbf)). 

The benefits of hardlinking symlinks seem pretty small. On my machine, even optimistically assuming we save 4KiB for each symlink replaced with a hardlink, this only reduces the size of the store by 1.5%. I suggest removing this functionality and leaving symlinks unchanged.

**Comment by edolstra** [comment]
I'm not so sure about this, 4 KiB per symlink really adds up. For example, my NixOS `system-path` is 123 MiB because it contains almost 29500 symlinks. So the `system-paths` of a couple of NixOS generations can easily add up to multiple gigabytes...

**Comment by lheckemann** [comment]
Additionally, this saves a nontrivial amount of inodes.

**Comment by lheckemann** [comment]
Fair to close again, a few arguments were brought in favour of the existing behaviour and the author of the issue hasn't responded.
