### ISSUE TITLE
Have remote builders keep building even after connection loss etc

### ISSUE THREAD

**Issue by teto** [NixOS/nix#2751]
I would like distributed builds to be resilient to connection loss so that I can lose the connection from the computer that triggered the remote build, and yet have the remote build keep going.
Even without losing the connection, I would like to initiate a remote build, get my prompt back so that  after powering off my laptop, the remote builder keeps building and in the morning, after a good night of sleep, my kernels would have finished building on the remote.

Might it already possible but not sure how ?

**Comment by bjornfor** [comment]
This can be done without support from Nix: use screen / tmux / byobu.

**Comment by matthewbauer** [comment]
I think this is the same as https://github.com/NixOS/nix/issues/1953

**Comment by edolstra** [comment]
We currently go through great lengths to make sure that remote builders *don't* keep building after a disconnect. After all, you don't want the remote machine to keep building for hours after the user hits Ctrl-C on the local machine.

**Comment by teto** [comment]
Closing this as a duplicate indeed.
@edolstra ctrl c is a user action with the clear intent of stopping the connection but losing connectivity is not intzntional. I have intermittent connectivity and some local derivatiins so i would like to express my intent to have the builder keep going. I don t think tmux works as these are local derivations.

**Comment by bjornfor** [comment]
> We currently go through great lengths to make sure that remote builders don't keep building after a disconnect. After all, you don't want the remote machine to keep building for hours after the user hits Ctrl-C on the local machine.

https://github.com/NixOS/nix/issues/2653 shows is a corner-case where nix currently continues the build when the client dies (due to nix not aborting when getting SIGPIPE, or aborting on write errors).
