### ISSUE TITLE
builders-use-substitutes only implemented for LegacySSHStore? 

### ISSUE THREAD

**Issue by elaforge** [NixOS/nix#2770]
I have been noticing that our remote builds never seem to pull from the central artifact cache, preferring instead to have the local builder upload the required store paths, which is much slower.  The relevant config option is `builders-use-substitutes`, but as far as I can tell, this is only implemented for LegacySSHStore:

- The flag winds up in buildersUseSubstitutes.
- This is only used in build-remote.cc _main to pass Substitute to copyPaths
- copyPaths passes it to Store::queryValidPaths

That is implemented by:

- LegacySSHStore::queryValidPaths - passes it to a Connection::get()
- LocalStore::queryValidPaths - ignores it
- RemoteStore::queryValidPaths - ignores it
- Store::queryValidPaths - ignores it
- SSHStore doesn't implement queryValidPaths, so it must come from RemoteStore::queryValidPaths, which ignores it.

The implication is that if you use ssh:// in the `builders` option, then the option should work, but if you use ssh-ng://, then it will be ignored.  I did an experiment, and that seems to be the case: I always get a `copying path ... to 'ssh-ng://...'`, but if I clear out the built store paths, then use ssh:// for same operation, I skip all the `copying ... to`.  The remote nix-daemon doesn't seem to log about its copying so as far as I can tell there's no indication about what it did, but the missing "copying to" suggests that it's working as intended.

Is this a known omission?  Is it better to use ssh:// for now?

**Comment by zimbatm** [comment]
this is related to https://github.com/NixOS/nix/pull/2994. Currently all the configuration options are ignored by the ssh-ng protocol.
