### ISSUE TITLE
Document string contexts

### ISSUE THREAD

**Issue by kirelagin** [NixOS/nix#280]
So, based on this [recent discussion](http://lists.science.uu.nl/pipermail/nix-dev/2014-June/013571.html), I feel it might be good to document string contexts, as I couldn't find any reference to them in the Nix manual, while they are pretty tricky (as one can tell from the discussion).

At least, they should be mentioned in the manual with some explanation of their purpose (I'm not sure I got it right from the source). Mentioning some workarounds like `unsafeDiscardStringContext` and concating empty substrings (maybe even have a lib function for this?).

**Comment by kirelagin** [comment]
Well, Mr. Bot, that’s rather unfortunate, huh?

**Comment by fricklerhandwerk** [comment]
Finally closed by https://github.com/NixOS/nix/pull/8595
