### ISSUE TITLE
fetchurl and builtins.fetchTarball disagree on the SHA256 of fetched file

### ISSUE THREAD

**Issue by dingxiangfei2009** [NixOS/nix#2804]
To reproduce this, try the following in `nix repl <nixpkgs>`

```
fetchurl { url=https://crates.io/api/v1/crates/arrayvec/0.4.10/download;sha256="92c7fb76bc8826a8b33b4ee5bb07a247a81e76764ab4d55e8f73e3a4d8808c71"; }
```
versus
```
fetchTarball {url=https://crates.io/api/v1/crates/arrayvec/0.4.10/download;sha256="92c7fb76bc8826a8b33b4ee5bb07a247a81e76764ab4d55e8f73e3a4d8808c71";}
```

`fetchurl` gets a SHA256 that is consistent with the hash of the actual file, but `fetchTarball` does not.

**Comment by LnL7** [comment]
This is normal, if you look at the result of both builds you'll see that they are different. fetchurl just downloads a file while [fetchTarball](https://nixos.org/nix/manual/#builtin-fetchTarball) downloads and unpacks it first, in which case the unpacked content is hashed.

The different hashing modes are described in a bit more detail herehttps://nixos.org/nix/manual/#fixed-output-drvs.

**Comment by edolstra** [comment]
You can get the "unpacked" hash using `nix-prefetch-url --unpack` BTW.
