### ISSUE TITLE
Structured enumeration of buildables

### ISSUE THREAD

**Issue by grahamc** [NixOS/nix#2820]
I would like to have a structured enumeration of all the buildables.

In other words:

```json
{
  "hydraJobs": {
    "nix": ???,
    "nix": ???
  },
  "packages": { "nix": ??? },
  "defaultPackage": ???,
  "devShell": ???
}
```

also I kindly suggest renaming hydraJobs to `checks` or something :)

**Comment by CSVdB** [comment]
Some comments about what we can do:
```{
  "hydraJobs": { # Here, we can list the names of the attributes in this attribute set.
     # What those attributes are though, isn't fixed yet, so I'm not sure what ??? should be.
    "nix": ???,
    "nix": ???
  },
  "packages": { "nix": ??? }, # Same here: yes to "nix", but don't know what ??? could be
  "defaultPackage": ???, # same
  "devShell": ??? # devShell doesn't exist right now, and I'm not sure we want it.
```
To be clear: Do you want to create this from reading in the Nix file and trying to parse things using self-written parsers? If you want to use Nix to evaluate these things, I don't see what we could print on any of the `???`.. And if you are going to try and parse the Nix file using a non-Nix parser to extract some information, I'm not sure what the advantage is compared to looking at the `flake.nix` file itself.

**Comment by grahamc** [comment]
I don't know what the ???'s should be. My interest is in ultimately having a list of things I should try to build, and be able to give names to them. In other words, concretely, something like this...


```
$ build-the-things
OK, building:

 - hydraJobs.nix.x86_64-linux
 - hydraJobs.nix.x86_64-darwin
 - packages.nix
```

where in the background I can do:

```
$ nix build hydraJobs.nix.x86_64-linux
```

or something.

**Comment by CSVdB** [comment]
So the problem seems to be entirely residing in the `provides` attribute. What do you think about taking that apart into an attribute set, and then for each attribute, checking whether it's an attr-set. If so, continue. If not, print the name. That way you know exactly what's in `provides`, and you don't need to make assumptions on types.

**Comment by AmineChikhaoui** [comment]
@CSVdB If I understand @grahamc correctly, what we need is something like what hydra does in findJobs function (https://github.com/NixOS/hydra/blob/master/src/hydra-eval-jobs/hydra-eval-jobs.cc#L88) which is what you described roughly.
Currently if someone wants to build one of the provided packages of `patchelf` without checking the source's `flake.nix`, there is no command line interface that returns the available pkgs, ideally `nix flake info patchelf` should return something like:
```
[amine@nixos:~]$ nix flake info patchelf
ID:          patchelf
URI:         github:NixOS/patchelf/df5538a2d8ac1e434d9f30e7f9d3ad3a691f5a9c
Description: A tool for modifying ELF executables and libraries
Revision:    df5538a2d8ac1e434d9f30e7f9d3ad3a691f5a9c
Path:        /nix/store/r4b8hc13z80prz9mvp08j87rlwly9srz-source
Provides:    patchelf
```
From that I can deduce that I should run `nix build patchelf:patchelf`
