### ISSUE TITLE
Dependencies should be stored in graphs, not trees

### ISSUE THREAD

**Issue by CSVdB** [NixOS/nix#2823]
Currently, the dependency structures, in the Nix codebase, or dealt with using a dependency tree instead of a graph. This causes tons of duplication, especially if some common dependencies (maybe nixpkgs?) start having a ton of (non-)flake dependencies.

Not sure yet how to fix this.

**Comment by edolstra** [comment]
Closing this, we can re-open if it becomes a problem.
