### ISSUE TITLE
Using flakes is not obvious, and no documentation has been written

### ISSUE THREAD

**Issue by grahamc** [NixOS/nix#2825]
Figuring out how to use flakes has been a challenge, mostly reading commits and commit messages. I checked the docs looking for guidance, and didn't find any. I think a good way to go from here would be to write docs as changes happen, but we can talk more Monday.

For the eager readers:

```
nix build
```

seems to build (about half the time, anyway #84)

**Comment by edolstra** [comment]
Closing, `nix flake --help` shows info on flakes now.
