### ISSUE TITLE
Check whether localRegistry and flagRegistry are completely used

### ISSUE THREAD

**Issue by CSVdB** [NixOS/nix#2841]
Each entry in the local and flag registries is there with the purpose of overwriting a specific dependency. If one of these entries is not used, there might be something unexpected going on, and a warning should be issued.

**Comment by CSVdB** [comment]
In addition, note that the flag registry isn't actually used in updating the lockfile, only in recreating it. This must be fixed! Not sure how though.. Essentially we need to be able to detect whether a given `FlakeRef` was before resolved using the same flag or not..

One option would be to the depedencies influenced by the flag-registry always update, even when the rest of the lockfile isn't recreated from scratch.

**Comment by edolstra** [comment]
Closing, not clear whether we actually want this.
