### ISSUE TITLE
Make Hydra flake-based

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#2859]
Flakes remove the need for most Hydra jobset configuration, and for Hydra to fetch dependencies. A Hydra jobset only needs to specify a single flake reference (e.g. `github:my-org/my-project`). Hydra can then rely on Nix to fetch all flake dependencies.

Flakes should also expose a `provides.hydraJobs` attribute to tell Hydra what to build.

**Comment by lukego** [comment]
> Hydra can then rely on Nix to fetch all flake dependencies

How does Hydra fetch flake dependencies?

Can I use the `flake.lock` file to specify that some dependencies should be pinned and others should be polled continuously like normal Hydra inputs?

**Comment by edolstra** [comment]
Hydra doesn't fetch flake dependencies, it just relies on Nix to fetch them. Currently the flake must be locked, i.e. it must have an up-to-date `flake.lock`. In the future we could have Hydra run `nix flake update / lock` first, but for reproducibility, it would have to record the updated lock file somewhere (maybe in the Hydra database).

**Comment by lukego** [comment]
Thanks for the answer!
