### ISSUE TITLE
Prevent unnecessary GitHub redownloads

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#2867]
The ETag header in GitHub archive requests tell us the Git commit hash of the requested `ref`, e.g.:
```
$ curl --head -L https://github.com/NixOS/nix/archive/master.tar.gz
ETag: "25722bd39aece28a3ab8ef05fa14cece37b8c8fe"
```
This can be used to avoid unnecessary redownloads from mutable flake references, if we still have a GC root to a flake with that commit hash.

Note: doing a separate `HEAD` request adds significant latency (sometimes several seconds), so it might be faster to just start the download and abort it once we get a known `ETag`.

**Comment by CSVdB** [comment]
Can we store the storepath in the lockfiles? Then it can be checked whether there's something in the given storepath, and if so, nothing needs to be updated. This might not be nice to reuse on different machines though..

**Comment by edolstra** [comment]
We shouldn't store the store path in lockfiles, since this makes them depend on a specific location of the Nix store, which can be overriden by users. However, the store path can be computed from the content hash and the name (which is always "source"). `Downloader::downloadCached()` uses this to avoid doing a download when the hash is given:
```c++
    Path expectedStorePath;
    if (request.expectedHash) {
        expectedStorePath = store->makeFixedOutputPath(request.unpack, request.expectedHash, name);
        if (store->isValidPath(expectedStorePath)) {
            CachedDownloadResult result;
            result.storePath = expectedStorePath;
            result.path = store->toRealPath(expectedStorePath);
            return result;
        }
    }
```

So we could do something similar in `getFlake()`.

**Comment by edolstra** [comment]
Implemented a while ago.
