### ISSUE TITLE
'nixops deploy' exits with 'Too many heap sections: Increase MAXHINCR or MAX_HEAP_SECTS'

### ISSUE THREAD

**Issue by soenkehahn** [NixOS/nix#287]
After invoking `nixops deploy -j4 ...` I got this error message:

```
Too many heap sections: Increase MAXHINCR or MAX_HEAP_SECTS
nix-instantiate killed by signal 6
```

The same command worked with `-j3`.

The full command was:

```
 nixops deploy -d some_deployment -I .. --read-write --option binary-caches http://hydra.nixos.org -j4
```

**Comment by iElectric** [comment]
The error is back on master: http://hydra.nixos.org/jobset/nixos/trunk-combined

**Comment by aszlig** [comment]
Related: NixOS/nixpkgs#3594

**Comment by domenkozar** [comment]
Back on master: http://hydra.nixos.org/jobset/nixos/trunk-combined#tabs-errors

**Comment by domenkozar** [comment]
I'm got the same error with 100 nodes deployed via NixOps to EC2.

`GC_INITIAL_HEAP_SIZE=$((8*1024*1024*1024))` fixes it, but uses almost 13GB of ram (barely to fit on our 16GB machine).

**Comment by volth** [comment]
Just hit this issue compiling about ~30 closures at once.
Those closures have 99% in common so the memory footprint of the nixops-related cases could be possible optimized by interning strings and common structures in ```nix```?

**Comment by domenkozar** [comment]
@volth see https://ac.els-cdn.com/S157106610900396X/1-s2.0-S157106610900396X-main.pdf?_tid=14162726-dce0-11e7-a77d-00000aacb361&acdnat=1512824242_7e9551614d8141a063f6582e02c10e8f

If I understood @edolstra correctly, it's hard to implement GC on top of it. In Nixops it would probably pay off turning GC off and sharing memory.

Short term solution is to get nixops to evaluate each machine separately, in multiprocess manner.

Currently, NixOS evaluation grows linearly, meaning if one machine takes 100MB of memory to evaluate, once you have 100 machines it takes ~10GB of memory.

**Comment by volth** [comment]
GC could be sacrificed, it is not very effective: it reduces the peak memory consumption only by about 20%, while I hope that more compact and deduplicated implementation of ```Value```s (especially attribute sets) could do more.

My memory consumption is about 1Gb (!) per closure (and yes, 30Gb of RAM required to compile the nixops network), that seems weird taking into account that all .nix-files in ```nixpkgs``` are 40Mb in total and most of them are not used.

**Comment by volth** [comment]
Apparently, the memory consumption gets worse when overlays are used, many slightly different versions of the enormous ```pkgs``` attr set get copied.

**Comment by orivej** [comment]
There is a significant memory usage improvement in Nixpkgs `staging`: https://github.com/NixOS/nixpkgs/pull/32544

**Comment by volth** [comment]
@domenkozar You said on NixCon video [1] that a couple of years ago there was a Nix version which implements "maximal lazyness".
Could you please point to that version? 

1. https://www.youtube.com/watch?v=dlRuMdm6pRU#t=1485

**Comment by volth** [comment]
After some experiments I tent to think that "maximal lazyness" is not a panacea here.
There are too many calls of lambda functions in NixOS module system (arguments of ```foldl```, etc), their memoizing saves 5% in number of calls (mostly cheap calls) at the price of higher memory consumption and slower work because of maintaining ```std::map``` of millions entries.

On the contrary, on low memory condition, GC could discard something that is memoized currently (forcing to recalculate thunks  again if needed) collecting much more garbage memory than current ~20% - up to collecting everything but the parsed expressions.
So to say, some pointer can be treat as "weak" pointers.
In worst case it would work as slow as sequential invocations of per-closure ```nix-instantiate```

**Comment by domenkozar** [comment]
https://nixos.org/~eelco/pubs/laziness-ldta2008-final.pdf

**Comment by volth** [comment]
@domenkozar Nix in this git repo, both the current and 2 years old, are quire far from what is written in the pdf.
You said that 2 years there was a working nix implementation with maximim laziness.
But where???

**Comment by wmertens** [comment]
@edolstra A thought: using eval time as a metric for cache eviction

Would it be hard to keep track of how long it took to evaluate an expression, and use that to decide which expressions to memoize?

So if you could somehow say "cache should be below 100MB", and then when the cache is bigger, you evict items sorted by increasing eval time?

(possibly this is a trivial concept to you and not possible to implement, I just thought of it and wondered if that was a worthwhile approach to improving memory usage)
