### ISSUE TITLE
Manual: "Inheriting attributes" should have example of inherit in a let

### ISSUE THREAD

**Issue by lilyball** [NixOS/nix#2876]
The manual describes `inherit` as being usable while defining local variables in a let-expression, but it doesn't actually have any examples of this. The final snippet under "Summarizing the fragment" is agnostic to sets or let-expressions, but all the full examples just demonstrate its use in sets.

I didn't actually realize it could be used in a let-expression until I did a careful reading of this section and then tried it out locally. It would be great if there was a code sample that demonstrated using it in a let-expression.

**Comment by telotortium** [comment]
See https://discourse.nixos.org/t/the-papercut-thread-post-your-small-annoyances-confusions-here/3100/13 for an example. With this we could deprecate `with lib` (or at least strongly discourage it), which makes it difficult to determine where names are imported from.

**Comment by lilyball** [comment]
`with` is still valuable in many scenarios, such as doing a `with import <nixpkgs> {}` at the top of a `shell.nix`, or the very common `meta = with lib; { … }` (where nearly everything in the meta are strings, so the references to things from lib are fairly obvious), or `maintainers = with lib.maintainers; [ anne mary lisa ]`.

**Comment by fricklerhandwerk** [comment]
@thufschmitt please reopen, this is still relevant.
