### ISSUE TITLE
Building nix master branch 2.2.2 fails multiuser

### ISSUE THREAD

**Issue by t90r** [NixOS/nix#2891]
hi there im trying to follow the build instructions:

`./configure --enable-gc`
looks like worked:
**checking for a sed that does not truncate output... /bin/sed
checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu
checking for the canonical Nix system name... i686-linux
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for struct dirent.d_type... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C preprocessor... gcc -E
checking whether g++ supports C++14 features by default... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... 64
checking for pubsetbuf... yes
checking for statvfs... yes
checking for pipe2... yes
checking for lutimes... yes
checking whether it is possible to create a link to a symlink... yes
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking locale usability... yes
checking locale presence... yes
checking for locale... yes
checking for bash... /bin/bash
checking for patch... /usr/bin/patch
checking for xmllint... /usr/bin/xmllint
checking for xsltproc... false
checking for flex... /usr/bin/flex
checking for bison... /usr/bin/bison
checking for sed... /bin/sed
checking for tar... /bin/tar
checking for bzip2... /root/.guix-profile/bin/bzip2
checking for gzip... /bin/gzip
checking for xz... /root/.guix-profile/bin/xz
checking for dot... no
checking for lsof... /usr/bin/lsof
checking for cat... /bin/cat
checking for tr... /usr/bin/tr
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libcrypto... yes
checking for BZ2_bzWriteOpen in -lbz2... yes
checking bzlib.h usability... yes
checking bzlib.h presence... yes
checking for bzlib.h... yes
checking for sqlite3 >= 3.6.19... yes
checking for libcurl... yes
checking for libeditline... yes
checking for libsodium... no
checking for liblzma... yes
checking for lzma_stream_encoder_mt in -llzma... yes
checking for libbrotlienc libbrotlidec... yes
checking for libseccomp... yes
checking aws/s3/S3Client.h usability... no
checking aws/s3/S3Client.h presence... no
checking for aws/s3/S3Client.h... no
checking for bdw-gc... yes
checking for setresuid... yes
checking for setreuid... yes
checking for lchown... yes
checking for strsignal... yes
checking for posix_fallocate... yes
checking for sysconf... yes
checking if you have a recent GNU tar... yes
configure: creating ./config.status
config.status: creating config.h
config.status: config.h is unchanged**

anyway when doing make trows:
  **GEN    Makefile.config
  GEN    src/libexpr/parser-tab.cc
  GEN    doc/manual/version.txt
  GEN    src/libexpr/parser-tab.hh
  GEN    src/libexpr/lexer-tab.cc
  GEN    src/libexpr/lexer-tab.hh
  CXX    src/libutil/affinity.o
  CXX    src/libutil/archive.o
  CXX    src/libutil/args.o
  CXX    src/libutil/compression.o
  CXX    src/libutil/config.o
  CXX    src/libutil/hash.o
  CXX    src/libutil/json.o
  CXX    src/libutil/logging.o
  CXX    src/libutil/serialise.o
  CXX    src/libutil/thread-pool.o
  CXX    src/libutil/util.o
  CXX    src/libutil/xml-writer.o
  CXX    src/libstore/binary-cache-store.o
  CXX    src/libstore/build.o
  CXX    src/libstore/builtins/buildenv.o
  CXX    src/libstore/builtins/fetchurl.o
  CXX    src/libstore/crypto.o
  CXX    src/libstore/derivations.o
  CXX    src/libstore/download.o
  CXX    src/libstore/export-import.o
  CXX    src/libstore/gc.o
  CXX    src/libstore/globals.o
  CXX    src/libstore/http-binary-cache-store.o
  CXX    src/libstore/legacy-ssh-store.o
  CXX    src/libstore/local-binary-cache-store.o
  CXX    src/libstore/local-fs-store.o
  GEN    src/libstore/schema.sql.gen.hh
  CXX    src/libstore/machines.o
  CXX    src/libstore/misc.o
  CXX    src/libstore/nar-accessor.o
  CXX    src/libstore/nar-info-disk-cache.o
  CXX    src/libstore/nar-info.o
  CXX    src/libstore/optimise-store.o
  CXX    src/libstore/parsed-derivations.o
  CXX    src/libstore/pathlocks.o
  CXX    src/libstore/profiles.o
  CXX    src/libstore/references.o
  CXX    src/libstore/remote-fs-accessor.o
  CXX    src/libstore/remote-store.o
  CXX    src/libstore/s3-binary-cache-store.o
  CXX    src/libstore/sqlite.o
  CXX    src/libstore/ssh-store.o
  CXX    src/libstore/ssh.o
  CXX    src/libstore/store-api.o
  CXX    src/libmain/common-args.o
  CXX    src/libmain/shared.o
  CXX    src/libmain/stack.o
  GEN    scripts/nix-http-export.cgi
  GEN    scripts/nix-profile.sh
  GEN    scripts/nix-reduce-build
  GEN    doc/manual/manual.xmli
  CXX    src/build-remote/build-remote.o
  CXX    src/nix-build/nix-build.o
src/libmain/shared.cc:88:13: warning: 'void nix::opensslLockCallback(int, int, const char*, int)' defined but not used [-Wunused-function]
 static void opensslLockCallback(int mode, int type, const char * file, int line)
             ^~~~~~~~~~~~~~~~~~~
In file included from src/libexpr/nixexpr.hh:3:0,
                 from src/libexpr/attr-set.hh:3,
                 from src/libexpr/eval.hh:3,
                 from src/nix-build/nix-build.cc:14:
src/libexpr/value.hh:6:29: fatal error: gc/gc_allocator.h: No such file or directory
 #include <gc/gc_allocator.h>
                             ^
compilation terminated.
make: *** [src/nix-build/nix-build.o] Error 1
make: *** Waiting for unfinished jobs....**

i have already installed gc, tried the github repo:
https://github.com/ivmai/bdwgc
and this instructions:
https://www.hboehm.info/gc/
nevermind either versions get same error. is there an especific version of gc that needs to be installed to compile? thank you.
maybe i can do the single user installation but im trying to install multiuser. either the command 
  `sh <(curl https://nixos.org/nix/install) --daemon`

**---- oh no! --------------------------------------------------------------------
Sorry, I don't know what to do on Linux

We'd love to help if you need it.

If you can, open an issue at https://github.com/nixos/nix/issues

Or feel free to contact the team,
 - on IRC #nixos on irc.freenode.net
 - on twitter @nixos_org**

**Comment by domenkozar** [comment]
fixed
