### ISSUE TITLE
The manual does not mention NIX_CURRENT_LOAD

### ISSUE THREAD

**Issue by viric** [NixOS/nix#29]
The NIX_BUILD_HOOK distributed with nix, build-remote.pl, requires NIX_CURRENT_LOAD set to work. The manual does not mention NIX_CURRENT_LOAD.

**Comment by spinus** [comment]
would be nice to have that explained

**Comment by armijnhemel** [comment]
Is this one still a valid bug? I can see it explained here:

http://nixos.org/nix/manual/#chap-distributed-builds
