### ISSUE TITLE
Allow Verification of Non-Local Stores

### ISSUE THREAD

**Issue by TravisWhitaker** [NixOS/nix#2900]
As far as I know there is not a good way to verify substituter artifacts that are not in the local Nix store. `nix verify` has an `-s` option, but this indicates that signatures may be fetched from the provided store, not substituted paths themselves. I think there should be an option to verify e.g. the NAR files in an S3 substituter. As far as I know, the only good way to do this right now is to remove the desired paths from one's local store, perform a build that causes them to be substituted, and then use `nix verify` on the local store. I think it'd be nice to have this feature available, even if it's just an automatic way of doing the aforementioned procedure.

**Comment by edolstra** [comment]
This should work:
```
$ nix verify --store https://cache.nixos.org/ /nix/store/y9kxbzvm78zzc9ab3i3rmlxlkgnd7bcw-coreutils-8.30 -r
[9.1 MiB DL, 5 paths verified]
```

**Comment by TravisWhitaker** [comment]
I updated Nix and `verify` seems to have the right behavior now. Apologies for the noise.
