### ISSUE TITLE
Fetch flake input lazily

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#2913]
Flakes could have many inputs, and some might not be needed for certain outputs. So it would be nice to fetch them lazily.

Note: updating the lockfile would still be strict. I.e. we don't lazily fill in missing lockfile entries.

**Comment by kubukoz** [comment]
This is a life saver, thank you! Usecase: I have an input that's behind a VPN and I don't want to pull it on some machines (which don't evaluate it from the argument to `outputs`).
