### ISSUE TITLE
The pan newsreader example  in the manual doesn't build

### ISSUE THREAD

**Issue by JorisE** [NixOS/nix#2922]
The manual uses the Pan newsreader as an [example](https://github.com/NixOS/nix/blob/fb0ad898ed0f1c8d5297f5dc1035b2e6ac7e3632/doc/manual/introduction/about-nix.xml#L20) for showing how Nix sets up a complete build environment. 

```
[nix-shell]$ tar xf $src
[nix-shell]$ cd pan-*
[nix-shell]$ ./configure
[nix-shell]$ make
[nix-shell]$ ./pan/gui/pan
```

However, since gtk2 was removed as a dependency of the nixpkg, the configure script needs the flag `--with-gtk3` to run successful. Even if you add that flag, the derivative for Pan uses wrapProgram to include gpg in it's environment, but that is not available in the nix-shell environment.

Adding gtk2 and gpg to the dependencies to fix the manual is probably not the best solution. Maybe pan could be replaced with a package that doesn't need configure flags? I searched around for a package that fits this purpose, but found that surprisingly difficult.

**Comment by edolstra** [comment]
Needing configure flags is not a problem, we just need to change `./configure` to `configurePhase` or `./configure $configureFlags`.

**Comment by JorisE** [comment]
Cool, thanks! That works, so than `./configure` would become `./configure $configureFlags`. 

I tried to mimic the postInstall wrapper by doing `PATH=${gnupg}/bin/:$PATH ./pan/gui/pan`, but that doesn't work. Am I mistaken in thinking that gnupg should be available in the shell somehow?
