### ISSUE TITLE
readFile cannot handle binary data

### ISSUE THREAD

**Issue by nomeata** [NixOS/nix#2932]
I was wondering if I could write a nix expression that parses `~/.git/index`.

Background: the best solution for defining `src` that I found so far was to filter against a copy of `git ls-files`, as blacklist filtering often still includes files in the src directory that I do not want there, causing unnecessary rebuilds, and whitelists are tedious to maintain. And the git index already is a white list!

But `readFile` complains 

> the contents of the file '…/.git/index' cannot be represented as a Nix string

so I guess working with binary data with `nix` (the langauge) isn’t quite possible yet.

**Comment by bjornfor** [comment]
Did you try Nix 2.0 builtins.fetchGit (and give it a local path)? That should give you "git ls-files" like sources.

**Comment by nomeata** [comment]
Wouldn’t that copy the whole repository to `/nix/store`? That is what I try to avoid.

But I found a work-around; using `toString` on the path I can prevent the copying of `.git` to the store
```
  whitelist_file =
    nixpkgs.runCommand "git-ls-files" {} ''
      ${nixpkgs.git}/bin/git -C ${toString ../.} ls-files > $out
    '';
```

So this is a low priority request.

**Comment by domenkozar** [comment]
See https://github.com/NixOS/nix/issues/1307 for the limitation

See https://blog.hercules-ci.com/nix/2019/05/15/nix-gitignore/ as a solution to your problem :)

**Comment by nomeata** [comment]
I have used nix-gitignore before, but I don't consider it to be a solution.

`.gitignore` is a blacklist; if have random big files in my source directory, or whole directories with other stuff, then `nix` will still copy these huge files to the PATH, and still rebuild everything, even though it didn’t.

It also goes the other way: I can `nix-build` and it passes, but when I push it doesn’t work for my colleagues. Why? Because I forgot to `git add` some new files. `.gitignore`-based approaches don’t help, but using `git ls-files` does.

Anyways, closing this one in favor of #1307, thanks for the pointer!

**Comment by domenkozar** [comment]
I agree it has drawbacks. On the other hand, `.git/` is not available on CIs for reproducibility reasons so the solution doesn't work across the whole toolchain.

**Comment by nomeata** [comment]
My file checks if `.git` is present. If it is not, then one can reasonably assume that this is a clean checkout, e.g. from a revision archive, and the file filter returns constant true.

Sure, this solution also has drawbacks, but I am constantly refining it :-)

**Comment by domenkozar** [comment]
I like it :)
