### ISSUE TITLE
Document  builtins.fetchGit when used on a local path

### ISSUE THREAD

**Issue by nomeata** [NixOS/nix#2936]
TIL that `builtins.fetchGit` will actually get the contents of the (tracked files from the) _working directory_ (and not `HEAD` or the index)  when you point it to a local path.

This is certainly useful in some cases, but wasn’t what I was expecting, so explaining this in the manual at https://nixos.org/nix/manual/#ssec-builtins would be appreciated.

**Comment by nomeata** [comment]
Still relevant, I think.

**Comment by will-ca** [comment]
Still relevant, I think.

Also possibly broken/changed?

**Comment by nomeata** [comment]
> Still relevant, I think.

Just created a PR for that.

> Also possibly broken/changed?

Why do you think? At least judging from the code (`fetchFromWorkdir` in `src/libfetchers.git.cc`) it’s still the case.

**Comment by will-ca** [comment]
> > Still relevant, I think.
> 
> Just created a PR for that.
> 
> > Also possibly broken/changed?
> 
> Why do you think? At least judging from the code (`fetchFromWorkdir` in `src/libfetchers/git.cc`) it’s still the case.

`builtins.fetchGit` isn't actually fetching local paths at all for me. I get `error: 'file:///home/User/Files/Project Files/master' is not a valid URL`. I'm having to use `pkgs.fetchgit` instead.

**Comment by nomeata** [comment]
What if you use a non-file path, i.e. simply an absolute or relative path?

**Comment by will-ca** [comment]
> What if you use a non-file path, i.e. simply an absolute or relative path?

That is indeed what I did. The relative path apparently gets turned into a `file://` URL string at some point:

```Console
$ nix repl
Welcome to Nix 2.12.0. Type :? for help.

nix-repl> builtins.fetchGit ./.
error: 'file:///home/User/Files/Project Files/master' is not a valid URL
```

…Actually I think it's the spaces. It works fine in another repo that doesn't have whitespace in its resolved path. I'll open an issue I guess.

**Comment by nomeata** [comment]
Yes, I think it is. Thanks!
