### ISSUE TITLE
Nix Flake's --no-registries is too pure!

### ISSUE THREAD

**Issue by grahamc** [NixOS/nix#2947]
This works as expected:

```
$ /nix/store/nkwz67mw4bhjjsyq2kagissq9zhqj6vb-nix-2.3pre20190612_06010ea/bin/nix flake check
[2 built, 2 copied (0.0 MiB), 15.7 MiB DL]
```

however, in CI I want all dependencies to be purely defined, so I run

```
/nix/store/nkwz67mw4bhjjsyq2kagissq9zhqj6vb-nix-2.3pre20190612_06010ea/bin/nix flake check --no-registries --show-trace
```

which fails with:

```
error: requested to fetch mutable flake '/home/grahamc/projects/github.com/NixOS/patchelf' in pure mode
```

I was expecting to be able to run this in a checkout and have all of its dependencies except the project's directory in ultra pure mode.

How should I use this tool in this way?

**Comment by edolstra** [comment]
I agree that this is undesirable behaviour (whether the registry is used should be orthogonal to whether the top-level flake can be mutable). As a workaround you can pass an immutable flakeref, e.g.
```
nix flake check --no-registries $(nix flake info --json ~/Dev/patchelf | jq -r .uri)
```
