### ISSUE TITLE
linker errors during build

### ISSUE THREAD

**Issue by aherrmann** [NixOS/nix#295]
Hi,

Today I built nix from source in a non-default location following [this](https://nixos.org/wiki/How_to_install_nix_in_home_%28on_another_distribution%29) guide.

During the build process I encountered a number of linker errors. Namely, `-lsqlite3`, `-lbz2`, and `-lpthread` were failing. The configure script, on the other hand, had finished successfully, and was able to locate all the required libraries.

I was able to finish the build process by manually fixing the linker flags in the corresponding `local.mk` files. I'm not very fluent in autotools, but I assume that a proper fix would be to use `SQLITE3_LDFLAGS` type variables instead of raw linker flags (`-lsqlite3`).

I had to apply these fixes in [`src/nix-store`](https://github.com/NixOS/nix/blob/master/src/nix-store/local.mk#L9), and [`src/bsdiff-43`](https://github.com/NixOS/nix/blob/master/src/bsdiff-4.3/local.mk#L5-L10).

The `-lpthread` issue was a little bit different. I was compiling on a CentOS 6.5 system. And, oddly enough, the pthreads library in `/lib64/libpthread.so.0` doesn't have a link of the form `/lib64/libpthread.so` to it. Hence, the linker couldn't find it given just the `-lpthread` argument. I fixed it by changing the linker flags to `-L/lib64 -l:libpthread.so.0` in `nix-store`, `nix-hash`, `nix-instantiate`, `nix-env`, `nix-daemon`, and `download-via-ssh`. I'm not sure if that is CentOS's fault or an issue with the autotools config. I'm just mentioning it here so that someone who's more familiar with autotools can judge for himself.

Cheers

**Comment by gilligan** [comment]
I think it is safe to close this one, just like #566 was closed.
