### ISSUE TITLE
builds requiring KVM can no longer run in AWS with nix 2.2

### ISSUE THREAD

**Issue by cransom** [NixOS/nix#2964]
Environment:
`system: "x86_64-linux", multi-user?: no, version: nix-env (Nix) 2.2.2, nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos`, m5.2xlarge in AWS
The channel is nixos-19.03 as of a week ago and was previously on a 19.03pre, with nix 2.1.
The machine is a stand alone hydra that builds (among other things) AMI images. One of the requirements of image creation is that it runs a small vm to finish off the image. Since AWS does not support nested virtualization, there is no support for hardware accelerated KVM, and `/dev/kvm` doesn't exist. QEMU runs using software emulation, but it's fast enough for our needs.

After updating to 19.03-release, building images stopped working with the message `possibly transient failure building ‘/nix/store/somepath-image.drv’ on ‘localhost’: a 'x86_64-linux' with features {kvm} is required to build '/nix/store/somepath-image.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, nixos-test}`. I checked and made sure that /etc/nix/machines was correct (it is, `localhost x86_64-linux - 8 1 kvm,nixos-test,big-parallel,benchmark`).

I tracked it back to https://github.com/NixOS/nix/commit/1e7b8deea7e052ed9ebf47d1411bcaf542054b41 which does exactly what the commit message intends, and it breaks functionality we use by checking for /dev/kvm.  I tested the naive work around by symlinking /dev/kvm to /dev/null in order to fake kvm support, but then QEMU attempts to use the device and fails.

It feels counter intuitive to have nix silently revoke a flag from `requiredSystemFeatures`. It's possible that I can remove the kvm requirement from disk image creation in nixpkgs as I have a single builder, but is that my only option?

**Comment by edolstra** [comment]
You could lie and manually set `system-features = kvm` in `nix.conf`. The alternative would indeed be to drop `kvm` from `requiredSystemFeatures`.

Maybe we need a `preferredSystemFeatures` for inessential features...

**Comment by cransom** [comment]
thanks @edolstra , `system-features = kvm` got me back on my feet.

I was looking at nixpkgs master and saw that it reworked the `nix-daemon.nix` module  ( https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/misc/nix-daemon.nix#L491 ) and it would imply that every machine has kvm functionality, which is not the case. I think I can close this and open an issue in nixpkgs for that behavior, right? it should probably be linked into a  `virtualisation.kvm` option.

**Comment by edolstra** [comment]
@cransom Yeah, adding a `virtualisation.kvm` option sounds good.

**Comment by toraritte** [comment]
> I think I can close this and open an issue in nixpkgs for that behavior, right? it should probably be linked into a `virtualisation.kvm` option.
Hey @cransom , did you open an issue for this in the end? Couldn't find it, and it seems that others bump into this as well (see discourse topics [1](https://discourse.nixos.org/t/cannot-build-docker-image), [2](https://discourse.nixos.org/t/cannot-build-azure-image-qemu-system-x86-64-cpu-model-host-requires-kvm/7619)).

**Comment by mschwaig** [comment]
I guess you are talking about this line @cransom: https://github.com/NixOS/nixpkgs/blob/475c007da0232769d26363545b0557c3056ebffa/nixos/modules/services/misc/nix-daemon.nix#L590

I think `kvm` should just get removed from there and Nix should determine the `kvm` system feature at runtime by looking at `/dev/kvm`. I think it tries to do this here: https://github.com/NixOS/nix/blob/7c90552879da4d1df99b50c85e94201981e60123/src/libstore/globals.cc#L128-L130
Of course you can then still add it manually anyways, but `virtualisation.kvm` does not have to add it programmatically if Nix can pick up that `virtualisation.kvm` made `/dev/kvm` accessible. There is more info in my PR linked above.
