### ISSUE TITLE
nix dev-shell / develop fails when SHELL=zsh

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nix#2965]
Using the ```dev-shell``` subcommand available in the nixFlakes branch, I get this:

```
$ nix dev-shell nixpkgs:hello
zsh: no such option: rcfile
```

I believe this is from having set ```SHELL=zsh``` and this:

https://github.com/NixOS/nix/blob/d0a769cb061a13ad880c76e5ea69a76150439853/src/nix/shell.cc#L222

rcfile is not available on zsh.

**Comment by mkenigs** [comment]
Think this was closed by https://github.com/NixOS/nix/pull/3565?

**Comment by zimbatm** [comment]
yep
