### ISSUE TITLE
New builtin: toTOML

### ISSUE THREAD

**Issue by nmattia** [NixOS/nix#2967]
Nix recently got new builtins like `fromTOML`. Unfortunately there is no `toTOML`. Is there a technical limitation or could this be added?

**Comment by edolstra** [comment]
It's mostly because there hasn't been a need for it yet.

**Comment by vcunat** [comment]
It might be enough to write it in nix (fairly simple, I expect) and put into `lib.toTOML`, though the attribute path wouldn't be very consistent with `builtins.fromTOML` and `builtins.toJSON`.

**Comment by domenkozar** [comment]
Some WIP at https://github.com/hercules-ci/hercules-ci-agent/pull/74/files#diff-1df950ddb141ee0cfdfc10a62345dabdR23

**Comment by nmattia** [comment]
👍 

@edolstra looks like there's a need for it :)

**Comment by edolstra** [comment]
Yes, having it as a builtin is definitely better than doing it in Nix.

**Comment by fzakaria** [comment]
If this was at build-time one could maybe leverage https://github.com/dbohdan/remarshal however this is useful for instantiation.

**Comment by fricklerhandwerk** [comment]
Closed as duplicate of https://github.com/NixOS/nix/issues/3929
