### ISSUE TITLE
Cannot disable http2

### ISSUE THREAD

**Issue by nh2** [NixOS/nix#2971]
`nix 2.2.2` on Manjaro

We observe that `http2 = false` in nix.config has no effect

Using `nix-* -vvvvv` still shows that `HTTP/2` is used.

`nix show-config` shows that nix understands that the setting is set to `false`.

I have the suspicion that the code https://github.com/NixOS/nix/blob/64ec087f582cec33733f4102ab42a3e8f291758a/src/libstore/download.cc#L245-L246 only turns it on, but that it's already on by default in libcurl if the server supports it.

We observe that the `curl` seems to default to HTTP/2 also when downloading .nars from cache.nixos.org. Passing `--http1.1` forces it to not do that.

Maybe the docs at https://curl.haxx.se/libcurl/c/libcurl-env.html are wrong when they say

> You have to set this option if you want to use libcurl's HTTP/2 support.

**Comment by nh2** [comment]
Yep, looks like that man page is partially outdated:

While it says

> You have to set this option if you want to use libcurl's HTTP/2 support.

at the top, it says

> ### DEFAULT
>
> Since curl 7.62.0: CURL_HTTP_VERSION_2TLS 
>
> Before that: CURL_HTTP_VERSION_1_1 

below.

**Comment by nh2** [comment]
My `curl` PR to fix the docs: https://github.com/curl/curl/pull/4075

**Comment by nh2** [comment]
@aniketd and me will likely make a PR to fix this in nix.

**Comment by aniketd** [comment]
PR #2977 opened with @nh2
