### ISSUE TITLE
nix-env -u exited with Killed 

### ISSUE THREAD

**Issue by HelSirius** [NixOS/nix#2986]

**Comment by edolstra** [comment]
Probably means it ran out of memory. (There should be something in the system logs about the OOM killer kicking in.) Nixpkgs evaluation is quite a memory hog.

**Comment by HelSirius** [comment]
Yes it turns out to be memory problem. It required more memory, Thank you @edolstra.

**Comment by aesyondu** [comment]
`nix-env -qaP 'binutils'` consumed about 1.5GB of memory from 1.6GB to ~100MB (via `free -h`). I wonder why search needs so much memory.
