### ISSUE TITLE
Uninstall a package by attribute path

### ISSUE THREAD

**Issue by musq** [NixOS/nix#2987]
I can install `pip` using the following command

`nix-env -iA nixpkgs.python37packages.pip`

However when I try to uninstall using `nix -e pip`, it doesn't uninstall. In fact, now I'm unable to uninstall pip because I probably don't know the right package name. I've tried `pip`, `pip3`, `python3-pip`, `python3-pip3`, etc.

This issue has already been raised in #648

Before closing this issue, I would request to let me know how can I uninstall pip.

**Comment by LnL7** [comment]
You can use `--query` to retrieve the name of an attribute.
```
$ nix-env -qa -A nixpkgs.python37Packages.pip
python3.7-pip-18.0
```

So pip can be uninstalled using `python3.7-pip`.

**Comment by musq** [comment]
Got it. It works. Thanks!
