### ISSUE TITLE
builtins.fetchGit fails on (clean) shallow clones

### ISSUE THREAD

**Issue by Kha** [NixOS/nix#2988]
I'm trying to use `fetchGit` as a saner replacement for .gitignore/whitelist sources as detailed in https://github.com/NixOS/nix/issues/2944:

```
  src = if builtins.pathExists ./.git then builtins.fetchGit { url = ./.; } else ./.;
```

Unfortunately, this fails on Travis because Travis (sensibly) does a shallow clone by default. It seems this breaks `fetchGit` iff the working tree is clean:

```
$ git clone https://github.com/parttimenerd/temci.git --depth 1
[...]
$ cd temci
$ nix-build
warning: reject refs/heads/HEAD because shallow roots are not allowed to be updated
error: Could not read 9208ca8e91d8e707baeb3ce99750be94ea5d676d
fatal: Failed to traverse parents of commit 201ae68c5595d111d0605c13471a5c2de33bb3ec
error: program 'git' failed with exit code 128
(use '--show-trace' to show detailed location information)
# make it dirty
$ echo >> default.nix
$ nix-build
these derivations will be built:
[...]
```

My current workaround is to do something like `nix-build --arg src ./.` on Travis, but it would be great if I didn't need that.

**Comment by FRidh** [comment]
I can't do shallow fetches yet, so I suppose it would also fail to check out an already shallow repo
https://github.com/NixOS/nix/issues/1837
