### ISSUE TITLE
Document builtins.mapAttrs

### ISSUE THREAD

**Issue by chreekat** [NixOS/nix#2992]
Followup to #1776. The only mention of a builtin is in the [Nixpkgs manual](https://nixos.org/nixpkgs/manual/#function-library-lib.attrsets.mapAttrs) and the changelog. :)

Should we just copy/paste the manual from Nixpkgs?

**Comment by aij** [comment]
I see it in the Nix manual too, here: https://nixos.org/manual/nix/unstable/expressions/builtins.html

**Comment by edolstra** [comment]
Indeed, this was fixed in b8416779e3c17be819a27f1527a53d83c7eccbcf.
