### ISSUE TITLE
nix-copy-closure should deduplicate list of transferred derivations

### ISSUE THREAD

**Issue by volth** [NixOS/nix#3016]
Here is log ot nix-copy-closure transferring 2 system closures which share most of the derivations
![](https://i.imgur.com/aM15CO1.png)

It seems that the derivations which are present in both system closures are transferred twice

**Comment by volth** [comment]
It is actually "nix-copy-closure --from server --include-outputs one.drv two.drv" if it matters how the list was formed, the bug might be related to how "--include-outputs" works

**Comment by edolstra** [comment]
This is strange because `copyPaths()` takes a `PathSet`:
```c++
        PathSet storePaths2;
        for (auto & path : storePaths)
            storePaths2.insert(from->followLinksToStorePath(path));

        PathSet closure;
        from->computeFSClosure(storePaths2, closure, false, includeOutputs);

        copyPaths(from, to, closure, NoRepair, NoCheckSigs, useSubstitutes);
```
