### ISSUE TITLE
Document the `--system` command line option

### ISSUE THREAD

**Issue by basvandijk** [NixOS/nix#3029]
Various `nix` commands like `nix-build` accept the `--system` option for setting the value of `builtins.currentSystem`.

However this option is not documented in any man page.

**Comment by grahamc** [comment]
* https://github.com/NixOS/nix/blob/master/doc/manual/expressions/builtins.xml#L204
* https://github.com/NixOS/nix/blob/31f5ecfaa5bce2282f50daed1e4f477c64705fb3/doc/manual/expressions/derivations.xml#L17
* https://github.com/NixOS/nix/blob/master/doc/manual/command-ref/conf-file.xml#L63 maybe

**Comment by grahamc** [comment]
So `system` is defined in the conf-file.xml already: https://nixos.org/nix/manual/#conf-system and all of these options are available as `--xxx`. The `builtins.currentSystem` should probably make note of this.

**Comment by edolstra** [comment]
This is documented in the `nix` man page now.
