### ISSUE TITLE
Nix is broken after update to macOS mojave 10.14.6

### ISSUE THREAD

**Issue by brandshaide** [NixOS/nix#3034]
After a update to macOS mojave 10.14.6, Nix is broken and e. g. I cannot to this: 

```
$ nix-shell --packages 'haskellPackages.ghcWithHoogle (pkgs: [ pkgs.text pkgs.safe ])' haskellPackages.ghcid
```
Complaining about 

```
building '/nix/store/ffq5qwcjapiy4yawl9zl2xpnvx97jj4q-CF-osx-10.9.5-private.drv'...
dyld: Library not loaded: /usr/lib/system/libsystem_network.dylib
  Referenced from: /nix/store/3iidpvlcpwk3c08yxl4mxxw8ik78nis7-Libsystem-osx-10.9.5/lib/libSystem.dylib
  Reason: image not found
builder for '/nix/store/ffq5qwcjapiy4yawl9zl2xpnvx97jj4q-CF-osx-10.9.5-private.drv' failed due to signal 6 (Abort trap: 6)
cannot build derivation '/nix/store/q4ghwrmyaqah30ljvhma50c32a34lvsb-apple-framework-CoreText.drv': 1 dependencies couldn't be built
```
in particular: 

```
Referenced from: /nix/store/3iidpvlcpwk3c08yxl4mxxw8ik78nis7-Libsystem-osx-10.9.5/lib/libSystem.dylib
  Reason: image not found
```

Reinstalled nix from scratch - but unfortunately didn't help. Any suggestions about how to solve this? Thanks in advance. 
This is a issue very similar to [this one](https://github.com/NixOS/nix/issues/2444)

**Comment by matthewbauer** [comment]
This issue existed when Mojave came out last August, but has since been resolved. I think you either need to update your channels, modify ```NIX_PATH```, or update your local pin.

To verify, confirm that this works correctly:

```
nix-shell -I nixpkgs=channel:nixpkgs-19.03-darwin --packages 'haskellPackages.ghcWithHoogle (pkgs: [ pkgs.text pkgs.safe ])' haskellPackages.ghcid
```

**Comment by brandshaide** [comment]
Thanks @matthewbauer for your support. I'm pretty new to Nix and indeed I've forgot to add `nixpgks` to the recent channel like this: 

```
$ nix-channel --add http://nixos.org/channels/nixos-19.03 nixpkgs-19.03-darwin
$ nix-channel --update
```
