### ISSUE TITLE
Easing towards typed Nix:  deprecating `with` a warning

### ISSUE THREAD

**Issue by deepfire** [NixOS/nix#3042]
We want to reach the statically typed Nix nirvana.

However, some language features are in conflict with that -- in particular, the `with` is problematic:

The dynamic nature of the scope extension means that it is impossible in general to establish a type environment for the enclosed sub-expression -- since the types of the newly introduced bindings will depend on results of run-time evaluation, rather than on the lexical context.

So, in the end, the `with` operator presents an irreconciliable conflict with the typing mechanism.

As far as we'd want to move towards typed Nix, we'll have to get rid of the `with` operator.

The initial step could be introduction of an optional warning during evaluation of `with` expressions.  The warning could also explain the reason for the undesirability of the operator's use.

This would facilitate a smooth transition to a `with`-free Nixpkgs.

**Comment by edolstra** [comment]
I don't think a statically typed Nix is achievable. There is way too much reliance on dynamic typing in Nixpkgs to make that feasible. It's more realistic to create a new Nix-like language with static typing from the start.

**Comment by Ericson2314** [comment]
Also because our `with` is shadowed by explicit bindings, I think it's way less of an impediment than it would otherwise be.
