### ISSUE TITLE
containers: Allow enabling networking sandbox 

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nix#3059]
Due to how containers work on Linux, we can't allow Nix to use the sandbox as the container would have to be privileged to get access to isolation functionality in kernel.

Currently, all docker images disable the sandbox.

However, being able to enable networking isolation separately would be useful as it's a crucial part of our purity model.

**Comment by zimbatm** [comment]
Docker is filtering out the `unshare` syscall with seccomp by default. Maybe seccomp can be used inside of the container to further restrict the network access. https://docs.docker.com/engine/security/seccomp/

**Comment by domenkozar** [comment]
Ah, seems like all of the sandboxing is done with `unshare`, including networking. So one needs to add sys_admin capabilities.

**Comment by zimbatm** [comment]
yeah. the only other possibilities I see would be to use `seccomp` again if it's available. Or use something heavy like qemu to emulate a whole machine.
