### ISSUE TITLE
builtins.hashString to support "sha0" and "md4" algorithms

### ISSUE THREAD

**Issue by volth** [NixOS/nix#3072]
It would be nice if `builtins.hashString`  support "sha0" and "md4".

Yes, they are old and insecure.
The goal here is not to strengthen the security, but to generate "HashedPassword" entries for config files of various software.

 * `softether` uses `base64(sha0(password + toUpper(username)))`
 * software ported from Windows or interacting with Windows use `md4(unicode_password)` after NTLM

**Comment by edolstra** [comment]
I don't think we should. These are so old that they were already deprecated before this project was even started!

**Comment by volth** [comment]
Yes, but... then the old hash function are to be implement in Nix (+100s lines of Nix code instead of +2 lines of C++ code, because `openssl` already supports them) and that implementation will likely land in `nixpkgs` as part of `softether` module, with good chances to migrate to `lib.` when another module will requere old crypto function.

**Comment by vcunat** [comment]
Why do you need to compute them during evaluation time?  Isn't runtime enough?

**Comment by volth** [comment]
> Why do you need to compute them during evaluation time? Isn't ~runtime~ build-time enough?

Write config file with plain passwords and then in service's `preStart` use `Perl` to convert the passwords to hashes?
Given that `SHA0` provides almost no security it might be a solution, although not sure if more readable/maintenable than implementing `SHA0` in Nix

**Comment by vcunat** [comment]
You don't need as late as `preStart`.  Configs can be built in a derivation &ndash; during that build you can use whatever binary tool to convert the hashes.  I see a disadvantage that you'll still have the plaintext `*.drv` file containing that secret, and it might be a bit more difficult to write the `*.nix` this way.

**Comment by volth** [comment]
> Configs can be built in a derivation – during that build you can use whatever binary tool to convert the hashes. I see a disadvantage

The disadvantage is to write (and maintain) such a code for the only goal to call an `openssl` function.

`nix` is anyway linked with `openssl` and `builtins.hashString` is just a wrapper of `openssl dgst` but  `builtins.hashString` allows hash algorithms from an arbitrarily chosen subset and disallows the rest.
I see no point in such a restriction
Security? Restricting SHA0 in Nix would not force 3rd party software to update its algorithms (especially Windows software), but wrapping `openssl` binary could have more severe security issues (what if the password has ' or " or $ or space?)

Why not just pass `algo` to `openssl` as is to support everything what `openssl` supports?

```nix
  vpn_server_config_file = pkgs.stdenv.mkDerivation {
    name = "vpn_server.config";
    nativeBuildInputs = [ pkgs.perl pkgs.openssl ];
    dontUnpack = true;
    installPhase = ''
      echo -n ${lib.escapeShellArg (treeToString vpn_server_config.root)} > $out
      perl -i -pe 's/\bREPLACE_WITH_SHA0:(.*)$/        open(PIPE, "echo -ne ".($1 =~ s#\$([0-9A-F]{2})#chr(hex($1))#eigr =~ s#(.)#sprintf("\\\\x%02X",        ord($1))#egr)." | openssl dgst -sha -binary | base64 |"); <PIPE>; trim /e' $out
      perl -i -pe 's/\bREPLACE_WITH_MD4_UNICODE:(.*)$/ open(PIPE, "echo -ne ".($1 =~ s#\$([0-9A-F]{2})#chr(hex($1))#eigr =~ s#(.)#sprintf("\\\\x%02X\\\\x00", ord($1))#egr)." | openssl dgst -md4 -binary | base64 |"); <PIPE>; trim /e' $out
    '';
    preferLocalBuild = true;
    allowSubstitutes = false;
  };
```

**Comment by edolstra** [comment]
I'd prefer not to make Nix very tightly coupled to OpenSSL.

**Comment by volth** [comment]
> I'd prefer not to make Nix very tightly coupled to OpenSSL.

for something like https://github.com/intel/isa-l_crypto ?
but OpenSSL will still be linked via libcurl
