### ISSUE TITLE
`nix eval` doesn't understand attribute paths with quoted components

### ISSUE THREAD

**Issue by lilyball** [NixOS/nix#3076]
`nix eval`, when given a dotted attribute path, will look it up with `nixpkgs` in the environment (or rather, I'm guessing `NIX_PATH`, but I haven't checked). Unfortunately it doesn't do this if any of the path components is a quoted string.

```
> nix eval --raw 'nixpkgs.myOverlay.apollo.version'
2.18.0
> nix eval --raw 'nixpkgs.myOverlay."apollo-2.18.0".version'
error: don't know what to do with argument 'nixpkgs.myOverlay."apollo-2.18.0".version'
Try 'nix --help' for more information.
```

 - system: `"x86_64-darwin"`
 - host os: `Darwin 18.7.0, macOS 10.14.6`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.2.2`
 - channels(eridius): `"nixpkgs-19.09pre190327.54f385241e6"`
 - nixpkgs: `/Users/eridius/.nix-defexpr/channels/nixpkgs`

**Comment by edolstra** [comment]
This works on the flakes branch:
```
$ nix eval --raw 'nixpkgs:"hello".version'
2.10
```

**Comment by lilyball** [comment]
Without testing that branch myself, I assume it will also work as `nixpkgs:hello."version"`?
