### ISSUE TITLE
Is there a way to escape `'${` sequence inside ''-string ?

### ISSUE THREAD

**Issue by volth** [NixOS/nix#3082]
Is there a way to escape `'${` sequence inside ''-string ?

`$` needs to be escaped for `${` not to be a magic sequence, but its escaped form `''{` concatenates with preceding `'`, so `'''${` is parsed as [`'''` `$` `{`] and `$` remains unescaped.

Is there a way to escape `$` following `'` ?

**Comment by 7c6f434c** [comment]
There definitely is _a_ way: `'''${"$"}{''`. Not sure if a shorter one exists

**Comment by arcnmx** [comment]
There's the `''\` escape as an option?

```nix
''x = ''\'''${hi}';''
```

Though no solutions will be readable, you may even be better off just switching string styles mid-string!
```nix
''x = '${"\${hi}"}';''
```
