### ISSUE TITLE
nix doctor: actually answer if there are problems or not

### ISSUE THREAD

**Issue by davidak** [NixOS/nix#3084]
```
[davidak@X230:~]$ nix doctor
Store uri: daemon


```

This is the output on my system. I don't understand it.
Please answer the question if there are issues.

I have seen the PR that there can be warnings, but here are none. So i guess i have no problems?

In that case, please output: "No problems found." Maybe add a nice emoji when we support that by default in NixOS. (maybe you can detect if the terminal supports it?)

When problems are found, please output for example "5 problems found." and list them...

Also, please remove the second newline in this output.

cc @LnL7 

---

nix (Nix) 2.2.2
NixOS 19.03.173221.9ca57dc9171 (Koi)

**Comment by dtzWill** [comment]
FWIW on latest nix, `nix doctor` print no output unless `-v` or similar is given.  The exit code matches the success of the checks, is it intentional to drop the output?

Should be easy to make it go either way, just want to check if this was desired or a regression :).

**Comment by dtzWill** [comment]
Okay, thank you!
