### ISSUE TITLE
Nix pure shell PATH includes user locations

### ISSUE THREAD

**Issue by ryanorendorff** [NixOS/nix#3090]
Hi,

I am having a problem using pure nix shells. The shell's `$PATH` seem to have local binary path locations on it.

If you try to start a blank shell with the following command

```
nix-shell --pure -E "with import <nixpkgs> {}; derivation { name = ''Hi''; builder = ''something''; system = ''some system'';}"
```

And run `printenv` I get the following (with newlines added to make it easier to read).

```
__ETC_PROFILE_SOURCED=1
DISPLAY=:0
out=/nix/store/4qyf5wwqcx03515m8cdxyd5lzy3gv8aq-Hi
builder=something
USER=ryan
PAGER=less -R
system=some system
PWD=/home/ryan/code/sw-nix
HOME=/home/ryan
TMP=/run/user/1000
NIX_STORE=/nix/store
TMPDIR=/run/user/1000
name=Hi
IN_NIX_SHELL=pure
TERM=xterm-256color
TEMPDIR=/run/user/1000
SHLVL=2
NIX_BUILD_CORES=0
TEMP=/run/user/1000
LOGNAME=ryan
PATH=
    /nix/store/mn4jdnhkz12a6yd6jg6wvb4mqpxf8q1f-bash-interactive-4.4-p23/bin:
    /home/ryan/bin:
    /run/wrappers/bin:
    /home/ryan/.nix-profile/bin:
    /etc/profiles/per-user/ryan/bin:
    /nix/var/nix/profiles/default/bin:
    /run/current-system/sw/bin:
    /home/ryan/code/sw-nix/crates/configuration/target/release:
    /home/ryan/code/sw-nix/crates/configuration-io/target/release
NIX_BUILD_TOP=/run/user/1000
_=/home/ryan/.nix-profile/bin/printenv
```

The `$PATH` variable include several locations where user binaries might live, such as `/home/ryan/bin` (I don't have this folder) and `/home/ryan/.nix-profile/bin`. I have emacs in `~/.nix-profile/bin/`, and currently I can run emacs from a blank pure shell!

Additionally the pure shell has the environmental variables from my parent shell as well (the `/home/ryan/code/sw-nix/crates/` related paths). Those extra path variables were defined using `direnv`, where the nix command above was executed from a fish shell inside that directory.

**Comment by alexarice** [comment]
I built a version of nix 500 revisions old and it does the same thing

**Comment by zimbatm** [comment]
It's probably related to https://github.com/NixOS/nix/issues/903 . When the subshell loads it loads the ~/.bashrc and other bash-related startup scripts, which then infects the environment.

**Comment by alexarice** [comment]
Currently a pure nix shell appears to have my entire path in it. I can't tell the difference between a pure nix shell and a non pure one

**Comment by alexarice** [comment]
@zimbatm what made your pr "out of date"?

**Comment by matthewbauer** [comment]
See https://github.com/NixOS/nix/pull/3131 for an up to date version.
