### ISSUE TITLE
New builtin: pathType

### ISSUE THREAD

**Issue by roberth** [NixOS/nix#3096]
I'm proposing to add a new `builtins.pathType` that returns the node type, similar to the values returned by `builtins.readDir`.

### Motivation

Avoid having to read a directory when all you need is a single path's node type.

### Spec

Like `builtins.pathExists`, its argument is a path or string that may or may not exist on the filesystem.

Given argument `p` return value is
 - `null` when the path `p` does not point to an existing filesystem node
 - a value equal to `(builtins.readDir (dirOf p))."$(baseNameOf p)"`, such as "directory", "regular", "symlink"

### Advantages

 - Performance: no need to read the entire directory (may be big, like `/nix/store`)
 - Less strict: `readDir (dirOf p)` may not be allowed by dir permissions
 - Decreases the file watch scope for tools like `lorri`

**Comment by roberth** [comment]
`pathType` on a store path is generally not something you'll want to do, because it blocks the evaluator, causing the evaluation heap to exist for longer than necessary (wasting memory not usable by builds) and creating a choke point for parallelism.

Most of the time, it's possible to check the type of the store path in the builder that uses that information.

For example, don't do

```nix
runCommand "foo" { } ''
  ${optionalString (pathType dep == "directory") ''
    echo dep is a directory
  ''}
''
```

but instead do

```nix
runCommand "foo" { } ''
  if [[ -d ${dep} ]]; then
    echo dep is a directory;
  fi
''
```

**Comment by RuRo** [comment]
Unfortunately, this doesn't work for me (and probably won't work for everybody). There are cases, where `pathType` is needed at expression evaluation time, not at build/run time, so it can't be offloaded to the build step. For example, running `lib.filesystem.listFilesRecursive` on some source tree and `import`ing the `.nix` files.

Also, IMHO, it doesn't matter whether getting the `pathType` of store paths is a good practice or not. You should be able to get the type of `whatever/path/foo` without listing the contents of `whatever/path`.

I am currently working around this issue by adding an extra directory level to my flake, so I am not too invested in this issue, but I still think, that this ought to work.

**Comment by roberth** [comment]
Right, it used to be that you could just avoid putting your project sources in the store (except for derivation sources, by necessity). I hope #6530 makes that work a little better, but I don't assume it does. Reopening.

**Comment by mkenigs** [comment]
+1 I ran into this as well

**Comment by thufschmitt** [comment]
Fixed by https://github.com/NixOS/nix/pull/7447

**Comment by roberth** [comment]
@RuRo `lib.pathType` falls back to `builtins.readDir` if your Nix doesn't have the new primop. 

Perhaps we should consider again
 - https://github.com/NixOS/nix/pull/8392
