### ISSUE TITLE
warning: ignoring the user-specified setting 'show-trace'

### ISSUE THREAD

**Issue by arcnmx** [NixOS/nix#3101]
nix 2.3 introduced a spurious warning when providing the CLI with `--show-trace`, despite the option otherwise working as expected (evaluation failures do include a trace when the option is provided). I believe #3037 meant to address this but was closed in favour of 7298a38, which doesn't seem to have covered the same set of options.

```
nix build --show-trace nixpkgs.hello
warning: ignoring the user-specified setting 'show-trace', because it is a restricted setting and you are not a trusted user
```

**Comment by zimbatm** [comment]
`--show-trace` is only used at evaluation and is a client-only feature. It should also be filtered and not forwarded to the daemon.
