### ISSUE TITLE
locked from update

### ISSUE THREAD

**Issue by xruzzz** [NixOS/nix#3109]
Nix installed inside Gentoo.
I've updated nix from version 2 to 2.3.
```
$ nix-channel --update
error: opening lock file '/nix/store/d5w9a2n95nn15d570mhkgr6yxjia0dw8-nixos-unstable.lock': Permission denied
```
A more detailed description of the problem:
http://www.gentoo.ru/node/29676

**Comment by xruzzz** [comment]
After reinstalling and removing the '/nix' directory, I get an error
`$ nix-channel --update
unpacking channels...
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
error: opening file '/proc/1836/uid_map': No such file or directory
error: program '/usr/bin/nix-env' failed with exit code 1
`

**Comment by trofi** [comment]
Dupe of https://github.com/NixOS/nix/issues/2673

Gentoo-specific workaround in https://bugs.gentoo.org/693482 should work.

**Comment by xruzzz** [comment]
> Dupe of #2673
> 
> Gentoo-specific workaround in https://bugs.gentoo.org/693482 should work.

Your instruction for the installation of the actual for Nix 2.3.1?
https://trofi.github.io/posts/196-nix-on-gentoo-howto.html

**Comment by xruzzz** [comment]
> Dupe of #2673
> 
> Gentoo-specific workaround in https://bugs.gentoo.org/693482 should work.

Which first step should I make after your instruction?
(https://trofi.github.io/posts/196-nix-on-gentoo-howto.html)

**Comment by trofi** [comment]
I'm not sure I understand the question. If nix does not work for you I suggest filing a bug in https://bugs.gentoo.org and we can sort it out in full detail.

**Comment by xruzzz** [comment]
Решено установкой "User namespace (USER_NS)" в ядре Linux.
