### ISSUE TITLE
nix search return no packages , but other tools seems to be ok?

### ISSUE THREAD

**Issue by nomoreweirdmachines** [NixOS/nix#3119]
nixuser@host01:~$ cat /etc/issue
Ubuntu 16.04.6 LTS \n \l

https://www.katacoda.com/astralship/scenarios/install-nix

nixuser@host01:~$ nix-channel --update

nix-env -i cowsay

nixuser@host01:~$ nix search cowsay
warning: using cached results; pass '-u' to update the cache
error: no results for the given search term(s)!

nixuser@host01:~$ nix-env -f '<nixpkgs>' -qaP cowsay
cowsay  cowsay-3.03+dfsg2

**Comment by nomoreweirdmachines** [comment]
hmmm.... if i run

NIX_PATH=nixpkgs=$NIX_PATH/nixpkgs
nix search cowsay

it works!

but if i run

nix search cowsay
error: no results for the given search term(s)!
NIX_PATH=nixpkgs=$NIX_PATH/nixpkgs
nix search cowsay
warning: using cached results; pass '-u' to update the cache
error: no results for the given search term(s)!


blimey...is this as broken as it looks?

**Comment by nomoreweirdmachines** [comment]
i forgot, but this is a reference to #1865

**Comment by matthewbauer** [comment]
Hopefully fixed in https://github.com/NixOS/nix/pull/3130.
