### ISSUE TITLE
Flakeify 'nix search'

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#3122]
Currently `nix search` is completely broken on the flakes branch. Some required changes:

* It needs a flake argument, e.g. `nix search nixpkgs hello`.

* The package cache can be removed because we can use the flake evaluation cache instead (though the latter needs to keep track of some more data).

**Comment by manveru** [comment]
I think this can be closed now?

**Comment by edolstra** [comment]
Yes, thanks!
