### ISSUE TITLE
Nix daemon fails to start on macOS 10.15 Catalina

### ISSUE THREAD

**Issue by callahad** [NixOS/nix#3125]
**Describe the bug**
The Nix daemon does not start after boot for multi-user installations on macOS 10.15 (Catalina).

**To Reproduce**
1. Prepare macOS 10.15 (Catalina) for Nix:

    1. `echo 'nix' | sudo tee -a /etc/synthetic.conf`
    2. Reboot
    3. Create the Nix volume:

        ```
        sudo diskutil apfs addVolume disk1 APFSX Nix -mountpoint /nix
        sudo diskutil enableOwnership /nix
        sudo chflags hidden /nix
        echo "LABEL=Nix /nix apfs rw" | sudo tee -a /etc/fstab
        ```

2. Install Nix with `sh <(curl https://nixos.org/nix/install) --daemon`
3. Reboot

**Observed behavior**

Nix stops working after reboot; commands fail with:

    error: cannot connect to daemon at `/nix/var/nix/daemon-socket/socket': Connection refused

Similarly, the Nix daemon is not seen by launchd: `launchctl list | grep nix` finds nothing.

**Root Cause**

Nix installs `/Library/LaunchDaemons/org.nixos.nix-daemon.plist` as a symlink into the Nix store.

At boot, launchd sees this as a dangling symlink as the Nix volume is not mounted early enough. Thus, it is unable to load the plist, and the nix daemon does not start.

**Workaround**

You can manually start the daemon after each boot with `launchctl load /Library/LaunchDaemons/org.nixos.nix-daemon.plist && launchctl start org.nixos.nix-daemon`.

Alternatively, manually copy the plist into `/Library/LaunchDaemons`, replacing the symlink with an actual copy of the file.

If you do the latter, you may want to adjust the paths inside the plist to point to `/nix/var/nix/profiles/default/bin/nix-daemon` rather than a specific derivation inside the Nix store.

**Metadata**
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.0.0, macOS 10.15`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3`
 - channels(root): `"nixpkgs-20.03pre194957.bef773ed53f"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`

**Comment by mroi** [comment]
Isn’t this issue supposed to be fixed by 800fba1037ad97ff5e6d9acf9e820a30f0922f59?

**Comment by callahad** [comment]
That commit is a necessary but incomplete fix.

It only ensures that `org.nixos.nix-daemon.plist` waits until `/nix` is mounted before it tries to run `nix-daemon`.

But none of that matters if launchd can't even read `org.nixos.nix-daemon.plist` at boot. Which it can't, because it's a broken symlink into `/nix`.

**Comment by mroi** [comment]
Damn. Thanks for clearing this up.

**Comment by ElvishJerricco** [comment]
How reasonable would it be to just copy the plist instead of symlinking it?

**Comment by matthewbauer** [comment]
Yeah missed this one. Copying the file would be necessary unfortunately. The reason we do the symlink is to get updates automatically for Nix. Migration step would be:

```
sudo cp --remove-destination `readlink /Library/LaunchDaemons/org.nixos.nix-daemon.plist` /Library/LaunchDaemons/org.nixos.nix-daemon.plist
```

**Comment by matthewbauer** [comment]
Opened https://github.com/NixOS/nix/pull/3128

**Comment by arnalyse** [comment]
Although this issue is closed, I wanted to mention that the installation fails with the copy command, in case the target file exists. I got the following error:

```
---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo cp -f /nix/var/nix/profiles/default/Library/LaunchDaemons/org.nixos.nix-daemon.plist /Library/LaunchDaemons/org.nixos.nix-daemon.plist

to set up the nix-daemon as a LaunchDaemon

cp: /Library/LaunchDaemons/org.nixos.nix-daemon.plist and /nix/var/nix/profiles/default/Library/LaunchDaemons/org.nixos.nix-daemon.plist are identical (not copied).
```

Maybe it would be safer to remove the file and then do the copy.

**Comment by matthewbauer** [comment]
> Although this issue is closed, I wanted to mention that the installation fails with the copy command, in case the target file exists. I got the following error:
> 
> ```
> ---- sudo execution ------------------------------------------------------------
> I am executing:
> 
>     $ sudo cp -f /nix/var/nix/profiles/default/Library/LaunchDaemons/org.nixos.nix-daemon.plist /Library/LaunchDaemons/org.nixos.nix-daemon.plist
> 
> to set up the nix-daemon as a LaunchDaemon
> 
> cp: /Library/LaunchDaemons/org.nixos.nix-daemon.plist and /nix/var/nix/profiles/default/Library/LaunchDaemons/org.nixos.nix-daemon.plist are identical (not copied).
> ```
> 
> Maybe it would be safer to remove the file and then do the copy.

Is that a fatal error? If so,  that sounds like the sane thing to do.

**Comment by domenkozar** [comment]
i also hit this, but I don't think it should be fatal. It's a leftover from previous installation and can be just copied over.

**Comment by domenkozar** [comment]
It would be better to use `install ...`

**Comment by domenkozar** [comment]
https://github.com/NixOS/nix/pull/3532
