### ISSUE TITLE
Can't bootstrap Nix on Ubuntu 18.04

### ISSUE THREAD

**Issue by ElvishJerricco** [NixOS/nix#3127]
I was trying to help out on https://discourse.nixos.org/t/custom-installation-of-nix-unset-nix-build-top/4285/3, and found that you can't bootstrap Nix on Ubuntu.

I would expect the following script (run as root) to install a usable Nix on Ubuntu from source, without a prior installation of Nix, or a binary install from `https://nixos.org/nix/...`. It does build and install fine, but the resulting `/usr/local/etc/profile.d/nix.sh` does not work. It seems some of the `@coreutils@` binaries that [it needs](https://github.com/NixOS/nix/blob/master/scripts/nix-profile.sh.in#L3) are in `/bin`, and some are in `/usr/bin`, but `configure` only sets `coreutils` to `/bin`. Neither single directory contains all that is needed.

**Note:** Probably run this in a VM because... system software.

```bash
#!/usr/bin/env bash

set -eu

cores=$(nproc --all)
echo $cores

apt install \
        tar \
        build-essential \
        pkg-config \
        libssl-dev \
        bzip2 \
        libbz2-dev \
        sqlite3 \
        libsqlite3-dev \
        libcurl4-openssl-dev \
        curl \
        cmake \
        libxslt-dev \
        libxml2 \
        libgc-dev \
        liblzma-dev \
        libbrotli-dev \
        libseccomp-dev

# Boost part, uncomment if boost need to be installed
curl -L https://dl.bintray.com/boostorg/release/1.71.0/source/boost_1_71_0.tar.bz2 \
  | tar x --bzip2
pushd boost_1_71_0
./bootstrap.sh
./b2 install
popd

# Editline part
curl -L https://github.com/troglobit/editline/releases/download/1.16.1/editline-1.16.1.tar.xz \
  | tar x --xz
pushd editline-1.16.1
./configure
make all -j $cores -l $cores
make install
popd 

curl -L https://nixos.org/releases/nix/nix-2.3/nix-2.3.tar.xz \
  | tar x --xz

pushd nix-2.3
./configure --enable-gc

make -j $cores -l $cores
make install
popd
```

In a shell

```
vagrant@ubuntu-bionic:~$ sudo mkdir /nix
vagrant@ubuntu-bionic:~$ sudo chown vagrant /nix
vagrant@ubuntu-bionic:~$ . /usr/local/etc/profile.d/nix.sh 
Command 'stat' is available in '/usr/bin/stat'
The command could not be located because '/usr/bin' is not included in the PATH environment variable.
stat: command not found
Command 'id' is available in '/usr/bin/id'
The command could not be located because '/usr/bin' is not included in the PATH environment variable.
id: command not found
Command 'stat' is available in '/usr/bin/stat'
The command could not be located because '/usr/bin' is not included in the PATH environment variable.
stat: command not found
Command 'id' is available in '/usr/bin/id'
The command could not be located because '/usr/bin' is not included in the PATH environment variable.
id: command not found
```

The `Command 'xyz' is available in '/usr/bin/xyz'` and `The command could not be located because ...` text are coming from Ubuntu's command not found handle.

Why does it use a custom `PATH` anyway? Why not just use what it's given?

**Comment by matthewbauer** [comment]
The reason we set PATH is so that we can use the ```stat --printf``` command in the profile script. Only the coreutils version of stat supports this arg, so we need to make sure that we get that one and not the macOS or Busybox ones. At the same time, I don't think that (https://github.com/NixOS/nix/blob/master/scripts/nix-profile.sh.in#L14) is super valuable. We should expect the Nix commands to ensure that the profiles have the proper settings (we have ```nix doctor``` now!)

**Comment by matthewbauer** [comment]
Opened https://github.com/NixOS/nix/pull/3129 to remove it.
