### ISSUE TITLE
`nix run` crash in 2.3.1

### ISSUE THREAD

**Issue by Ninlives** [NixOS/nix#3140]
running `nix run <whatever-package>` failed with this message after upgrading to 2.3.1:
```
nix: src/libexpr/attr-set.hh:54: void nix::Bindings::push_back(const nix::Attr&): Assertion `size_ < capacity_' failed.
```

Results from `nix run nixpkgs.nix-info -c nix-info -m` if it is needed:

 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.5, NixOS, 20.03pre196480.8b46dcb3db5 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3`
 - channels(mlatus): `"home-manager, nixpkgs-20.03pre196586.b943338ea58, rolling-20.03pre196656.1658beb6a13"`

**Comment by evanjs** [comment]
I am also getting this error, but most of my `nix` commands crash, so for e.g. `nix run nixpkgs.nix-info -c nix-info -m`, I get:
```
nix: src/libexpr/attr-set.hh:54: void nix::Bindings::push_back(const nix::Attr&): Assertion `size_ < capacity_' failed.
[1]    24054 abort (core dumped)  nix run nixpkgs.nix-info -c nix-info -m
```
It seems like I can still use `nix-` commands just fine, though.

Output from `nix-info -m`:
 - system: `"x86_64-linux"`
 - host os: `Linux 5.2.20, NixOS, 20.03pre196586.b943338ea58 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"home-manager, nixos-20.03pre196586.b943338ea58, nixos-stable-19.03.173592.e758436f986, nixos-unstable, nixos-unstable-small-20.03pre196834.33366cce147, nixpkgs-unstable-20.03pre196811.7818f30cc4b, nur"`
 - channels(evanjs): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by evanjs** [comment]
Here's what I got bisecting `61e81621` ~ `master`
```
$ git bisect good
e6e61f0a54dac0174df996e93fcfedcac7769ab4 is the first bad commit
commit e6e61f0a54dac0174df996e93fcfedcac7769ab4
Author: Eelco Dolstra <edolstra@gmail.com>
Date:   Wed Oct 9 15:36:51 2019 +0200

    getSourceExpr(): Handle channels
    
    Fixes #1892.
    Fixes #1865.
    Fixes #3119.

 src/nix/installables.cc | 31 ++++++++++++++++---------------
 1 file changed, 16 insertions(+), 15 deletions(-)
```

**Comment by cleverca22** [comment]
e6e61f0a54dac0174df996e93fcfedcac7769ab4

**Comment by evanjs** [comment]
My current `NIX_PATH`:
```
/home/evanjs/.nix-defexpr/channels:nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos:nixos-config=/etc/nixos/configuration.nix:/nix/var/nix/profiles/per-user/root/channels:nixpkgs-overlays=/etc/nixos/modules/overlays-compat
```
 does not work

removing `/nix/var/nix/profiles/per-user/root/channels:` seems to work
i.e. 
```
/home/evanjs/.nix-defexpr/channels:nixpkgs=/nix/var/nix/profiles/per-user/root/channels/nixos:nixos-config=/etc/nixos/configuration.nix:nixpkgs-overlays=/etc/nixos/modules/overlays-compat
```

Current channels for `evanjs`: None
Current channels for `root`: 
```
home-manager https://github.com/rycee/home-manager/archive/master.tar.gz
nixos https://nixos.org/channels/nixos-19.09
nixos-stable https://nixos.org/channels/nixos-19.09
nixos-unstable https://nixos.org/channels/nixos-unstable
nixos-unstable-small https://nixos.org/channels/nixos-unstable-small
nixpkgs-unstable https://nixos.org/channels/nixpkgs-unstable
nur https://github.com/nix-community/NUR/archive/master.tar.gz
```

**Comment by cleverca22** [comment]
i think the problem, is that it allocates enough room in the attrset, for the number of entries in `NIX_PATH`

but the new code also tries to add all channels, and goes over the size of the set

**Comment by jpotier** [comment]
Hitting this today after update…

```
$ nix repl '<nixpkgs>'
Welcome to Nix version 2.3.1. Type :? for help.

Loading '<nixpkgs>'...
Added 9816 variables.

nix-repl> :b nix-info
[1 copied, 0.0 MiB DL]

this derivation produced the following outputs:
  out -> /nix/store/dqjjvs2zaj7h454k7zr1lyd7mh95k1vm-nix-info

$ /nix/store/dqjjvs2zaj7h454k7zr1lyd7mh95k1vm-nix-info/bin/nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 5.3.6, NixOS, 20.03.git.1c40ee6 (Markhor)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.1`
 - channels(root): `"nixos-19.03pre164715.201d739b0ff, overlay-personal"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

My version of nixos is not in sync with my root channel, because I'm using krops to deploy this machine localy.

**Comment by Ninlives** [comment]
Temporary workaround：register an entry for every channel. Thus on my device, previously `NIX_PATH` is `<home/directory>/.nix-defexprs/channels`, now it's `nixpkgs=<home/directory>/.nix-defexprs/channels:home-manager=<home/directory>/.nix-defexprs/channels/home-manager`

**Comment by avdv** [comment]
FTR, I hit this error today after upgrading my nixos channel from nixos-20.09 to nixos-21.05 and running `nix-channel --update && nix-env -u`:
```
upgrading 'git-hub-1.1.0' to 'git-hub-2.1.0'
upgrading 'stack-2.3.3' to 'stack-2.7.1'
upgrading 'firefox-88.0' to 'firefox-88.0.1'
upgrading 'chromium-90.0.4430.93' to 'chromium-91.0.4472.77'
upgrading 'nix-2.3.10' to 'nix-2.3.11'
nix-env: src/libexpr/attr-set.hh:54: void nix::Bindings::push_back(const nix::Attr&): Assertion `size_ < capacity_' failed.
[1]    9934 IOT instruction (core dumped)  nix-env -f '<nixos>' -u
```

I could fix this by first upgrading `nix` separately.

**Comment by adworacz** [comment]
Awesome, thank you for this @avdv . For anyone else who encounters this, in order to upgrade nix like avdv says, simply run:

```
nix-channel --update && nix upgrade-nix
``` 

Then you can resume any other package upgrades you were doing before.
