### ISSUE TITLE
Nix tools should have exitcode SIGINT, when exited by CTRL-C

### ISSUE THREAD

**Issue by kalhauge** [NixOS/nix#3148]
I would not consider this a bug, merely a suggestion :).

I am writing an interactive tools that call nix-build and nix-store in the background  but I have found it difficult to handle user interrupts because both of these tools both have 
exit code 1 on interrupted runs and not SIGINT. When that happens, it is (almost) impossible to figure out if the build was interrupted by the user or if it failed, two cases that in most 
cases should be handled differently.

To reproduce: 
```
$ nix-build '<nixpkgs>' -A hello
^Cerror: interrupted by the user
$ echo $?
1

$ nix-instantiate '<nixpkgs>' -A hello
^Cerror: interrupted by the user
$ echo $?
1

$ nix-store -r ...
^Cerror: interrupted by the user
$ echo $?
1
```

Examples of "Normal" behavior (SIGINT being 130 on my system): 
```
$ sleep 1
^C
$ echo $?
130

$ cat /dev/random
...
^C
$ echo $?
130

$ runhaskell Main.hs
^C
$ echo $?
130

$ ghc Main.hs
^C
$ echo $?
130
```

**Comment by prusnak** [comment]
This might be the fix, but I leave the real fix to someone who has more knowledge about this codebase

``` patch
diff --git a/src/libutil/util.cc b/src/libutil/util.cc
index 2e416ede..26e7c8d4 100644
--- a/src/libutil/util.cc
+++ b/src/libutil/util.cc
@@ -966,7 +966,7 @@ pid_t startProcess(std::function<void()> fun, const ProcessOptions & options)
             } catch (...) { }
         } catch (...) { }
         if (options.runExitHandlers)
-            exit(1);
+            exit(_isInterrupted ? SIGINT : 1);
         else
             _exit(1);
     };
```

**Comment by edolstra** [comment]
I think strictly speaking, you can't return a signal in this way since any exit status returned by `exit()` will match `WIFEXITED`.
