### ISSUE TITLE
nix-shell shebang with '.nix-shell' suffix executed as nix code.

### ISSUE THREAD

**Issue by nyarly** [NixOS/nix#3153]
Consider this shebang script:

```
#! /usr/bin/env nix-shell
#! nix-shell -i bash

echo "Hello!"
```

If saved has `hello.nix-shell`, when run it will output

`error: undefined variable 'echo' at /tmp/test.nix-shell:4:1`

It seems that the shebang detection code puts us into a nix language execution mode instead of honoring the `-i` flag.

https://github.com/NixOS/nix/blob/906d56a96b442d4dd8f924c1ce0d1eec0e214af3/src/nix-build/nix-build.cc#L73 was identified as potentially related.

**Comment by Infinisil** [comment]
This seems to be the actual cause: https://github.com/NixOS/nix/blob/906d56a96b442d4dd8f924c1ce0d1eec0e214af3/src/nix-build/nix-build.cc#L109

That is, if the filename it was invoked with has "nix-shell" in it, it *doesn't* interpret is as a shebang.

I don't know what this check is for, I suspect it's just an oversight and can probably be removed.

I traced it back to https://github.com/nixos/nix/commit/dc7e8fae48f65da7aea86043a25a9381b678ebe6 by @edolstra

**Comment by zimbatm** [comment]
It's because `nix-shell` is a symlink to `nix`. It's using the busybox-style packing of multiple programs into one by detecting the argv1. The issue is that the regex should be something like `(^|/)nix-shell$`

**Comment by Infinisil** [comment]
@zimbatm The `runEnv` already includes the check on `argv[0]` (which is the executable name, not `argv[1]`).
