### ISSUE TITLE
Update Travis definitions for nix builds

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nix#3157]
The Travis build rules for nix support are defined in https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/nix.rb
This repository has no issue tracker, so I opted to open the issue here.

The last update of these rules was in https://github.com/travis-ci/travis-build/commit/52839b576f80b210770505b8691ecd4626286cca#diff-eb3a8105f9a623d165416989919841b9 (2018-09) to pin nix to 2.0.4.

Issues like https://github.com/NixOS/nix/issues/1958 make testing with nix on macOS quite hard.

There’s two issues that should be fixed:
- [ ] bump nix version to the latest release
- [ ] make the macOS build single-user, like the Linux build

Pinging listed Travis nix maintainers, @domenkozar @garbas @matthewbauer @grahamc

**Comment by zimbatm** [comment]
maybe we should maintain a fork of that repo in the nixos org?

**Comment by domenkozar** [comment]
I highly recommend just moving everyone to github actions or something else.

I don't plan to maintain travis+nix anymore since it's treading water.

**Comment by Profpatsch** [comment]
> I highly recommend just moving everyone to github actions or something else.

How would moving everybody to an alpha-quality implementation of essentially the same software help? It’s a completely orthogonal problem methinks. Travis might be badly designed, but at least we know most of its quirks.

> I don't plan to maintain travis+nix anymore since it's treading water.

What exactly makes it so hard to maintain?

**Comment by Profpatsch** [comment]
> maybe we should maintain a fork of that repo in the nixos org?

That is a good idea I think. A lot of people still depend on Travis, and having good nix support eases the burden considerably.

**Comment by zimbatm** [comment]
@Profpatsch I don't have access to the NixOS org so I invited you to https://github.com/nix-community/travis-build and enabled the issues there.

**Comment by Profpatsch** [comment]
I can’t guarantee I will find the time to update it, but I’ll keep this issue in mind.

**Comment by zimbatm** [comment]
sounds good :)

**Comment by Profpatsch** [comment]
@zimbatm so should I re-open this issue in https://github.com/nix-community/travis-build?
