### ISSUE TITLE
chroot build support on Darwin

### ISSUE THREAD

**Issue by cstrahan** [NixOS/nix#317]
Right now, only linux (perhaps only NixOS to be specific?) has support for chroot builds; it would be nice to have support for Darwin. On linux, this accomplished with bind mounts and `chroot`; on Darwin we could use [`bindfs`](http://bindfs.org/) and `chroot` (assuming the user installed `bindfs`).

I would be willing to take this project on (you can see my level of commitment in my previous [XQuartz](https://github.com/NixOS/nixpkgs/pull/3101) work), especially if one or more core members would be willing to make a best effort to be available for questions/advice.

**Comment by copumpkin** [comment]
I have a first pass at this, and it seems to work fine in my basic tests. Anyone interested, please check out my branch https://github.com/copumpkin/nix/tree/darwin-sandbox and see if it works for you. You'll probably need to use my pure-darwin branch of nixpkgs for it to be any use, given that everything else is pretty impure.

**Comment by copumpkin** [comment]
I think we can close this now that #434 is in, right?

**Comment by cstrahan** [comment]
@copumpkin Yep - closing now that #434 landed.
