### ISSUE TITLE
nix-shell sets unsets LANG and friends

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/nix#318]
In nix-shell

```
LANG=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```

outside of nix-shell

```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

This causes problems when we drop into a shell to hack on a project that expects reasonable LANG settings, such as GHC test-suite:

```
 WarnMinimal.hs:92:1: Warning:
     The MINIMAL pragma does not require:
-      ‘cheater3b’
+      `cheater3b'
     but there is no default implementation.
-    In the class declaration for ‘Cheater3’
+    In the class declaration for `Cheater3'
```

I thought there was an issue open for this somewhere already but I could not find one.

**Comment by mboes** [comment]
We're currently being hit by this issue. Would the above suggested `LOCALE_ARCHIVE` solution even in pure mode be a reasonable fix?

**Comment by mboes** [comment]
cc @ypares

**Comment by Ericson2314** [comment]
Say we added a `--pure-except=<list of env vars>` flag? That way we don't need to decide/anticipate which environment variables are useful to keep around.

**Comment by mboes** [comment]
Just a note: adding `-p glibcLocales` to `nix-shell` and then setting some arbitrary locale works. Arguably, `LOCALE_ARCHIVE` is an impurity, and if the host distro is not NixOS then chances are that variale is not set and so inheriting it won't help anything. So perhaps the fix here is simply to document the need for `-p glibcLocales`, or to include that package by default in the environment?

**Comment by seagreen** [comment]
Has there been any more thought on this issue? I'm also running into problems with it, exacerbated by wanting to use stack with `haskell.lib.buildStackProject`, which doesn't give me a convenient place to set environment variables.

**Comment by chris-martin** [comment]
@seagreen

> `haskell.lib.buildStackProject`, which doesn't give me a convenient place to set environment variables.

Any arguments you pass to `buildStackProject` turn into environment variables, so this works:

```
haskell.lib.buildStackProject {
  name = "foo";
  inherit ghc;
  buildInputs = [ ];
  LANG = "en_US.UTF-8";
}
```

This is *sort of* documented at https://nixos.org/nixpkgs/manual/#how-to-build-a-haskell-project-using-stack in that it is insinuated by "All of the same inputs as `mkDerivation` can be provided."

**Comment by peti** [comment]
I cannot re-produce this issue:

~~~
$ nix-shell --run "echo $LANG" -p hello
en_US.UTF-8
~~~

**Comment by chris-martin** [comment]
@peti fwiw, the way to reproduce the issue (clarified in later comments) is using `--pure`.

This issue, I think, is really a feature request - it ought to be easier to enter a pure shell that has the right locale set, because that's a really common use case.

**Comment by cw789** [comment]
I'm still struggling with this by using `Elixir`. This is reproducible if you run nix on a system without locale available (`musl`). Of course if you ad `glibcLocales` to your build inputs then you can correctly set the locale. But it would be easier for new users if UTF-8 would be default in nix-shell. Or even will be available in addition to C & POSIX from the beginning without needing `glibcLocales`.

**Comment by Fuuzetsu** [comment]
glibcLocales can be quite large, off by default is the sane way

**Comment by cw789** [comment]
@Fuuzetsu: Of course without the whole glibcLocales as default is the better way.
I'm more thinking about a solution where only UTF-8 can be included in addition to C & POSIX into glibc or the nix-shell. But I'm not deep into that kind of programming. So it may be a dumb suggestion. I don't know.

**Comment by Fuuzetsu** [comment]
It's doable fairly easily, I've done it at a client. I don't have the code on hand but should be possible to replicate by someone without much difficulty.

**Comment by jtojnar** [comment]
See also https://github.com/NixOS/nixpkgs/issues/20192
