### ISSUE TITLE
Non-ascii characters in path

### ISSUE THREAD

**Issue by SRGOM** [NixOS/nix#3189]
```nix
		src = /home/dasndfa/XDG/下载/mssql-server-14.0.3238.1-19.x86_64.rpm;
```

```
$nix-build sqlserver.nix                                     
error: path '/home/dasndfa/XDG/' has a trailing slash
```

**Comment by prusnak** [comment]
Use quotes: `src = "foo";`

**Comment by zimbatm** [comment]
yes path literals can only include ASCII characters.

A workaround is to use this construct instead:
```nix
/. + "/home/dasndfa/XDG/下载/mssql-server-14.0.3238.1-19.x86_64.rpm"
```
Appending a path to a string gives a new path.

**Comment by SRGOM** [comment]
Thanks, I wanted to let know... Should I keep this open or is this by design?

**Comment by zimbatm** [comment]
It's up to @edolstra to decide if he wants to expand the syntax. Right now the language is mostly ASCII oriented and higher code points in UTF-8 are not really well supported.
