### ISSUE TITLE
Uninstall a package/derivation group

### ISSUE THREAD

**Issue by Alkeryn** [NixOS/nix#3195]
so you can create a "group" of derivation in your overlay like that

`example = with super; [ neovim ranger ];`
you can install it with `nix-env -f '<nixpkgs>' -iA example`
but `nix-env -e example` won't uninstall anything altough that would be nifty ^

**Comment by zimbatm** [comment]
For that use `example = with super; buildEnv { name = "mygroup"; paths = [ neovim ranger ]; }`. Then you can uninstall the group with `nix-env -e mygroup`.

**Comment by Alkeryn** [comment]
@zimbatm thank you :)

**Comment by zimbatm** [comment]
`-iA` looks at the attribute and `-e` at the package name. So as long as both the attribute and buildEnv name are set to "example" that would work.

**Comment by Alkeryn** [comment]
can you uninstall by attribute ?
a -eA would be neat ^
