### ISSUE TITLE
incompatible with nixpkgs master branch

### ISSUE THREAD

**Issue by matthuszagh** [NixOS/nix#3204]
All package builds fail using the current nix master branch and nixpkgs master branch, with the following error message:
```
~/src/nixpkgs $ nix-build -A hello
error: value is a function while a set was expected
```
I believe this should be filed here instead of the nixpkgs repo, but please correct me if I was mistaken.

**Comment by vyp** [comment]
This might have been to do with nixpkgs, see https://github.com/NixOS/nixpkgs/issues/72754 and related PRs.

**Comment by matthuszagh** [comment]
Sounds right, it's working again. Thanks vyp. Closing.
