### ISSUE TITLE
Precompiled headers don't work with default ./configure

### ISSUE THREAD

**Issue by singron** [NixOS/nix#3209]
./configure sets `CXX=g++ -std=c++17` but mk/precompiled-headers.mk checks `ifeq($(CXX),g++)` leading to this error:

```none
mk/precompiled-headers.mk:38: *** Don't know how to precompile headers on g++ -std=c++17.  Stop.
```

You can work around it by setting `PRECOMPILE_HEADERS=0` when invoking make.

**Comment by edolstra** [comment]
Maybe rerun `autoconf`? Our configure script no longer has `AX_CXX_COMPILE_STDCXX_17` so it shouldn't set `CXX` to include `-std=c++17`.

**Comment by singron** [comment]
That was it. Sorry for the bug noise.
