### ISSUE TITLE
builtins.fetchGit derivation name default

### ISSUE THREAD

**Issue by nomeata** [NixOS/nix#3210]
Relatively minor, but still: `builtins.fetchGit` currently sets a derivation name of `"source"` by default:

https://github.com/NixOS/nix/blob/48f0a76372d5e5be86f6522c760ae1f6c12dbd65/src/libexpr/primops/fetchGit.cc#L197

It might be more helpful (e.g. when trying to make sense of the conten of `/nis/store`) to derive from from the URL (e.g. the last component), similar to what `builtins.path` does.

**Comment by edolstra** [comment]
No, using "source" was done on purpose, see 65b5f177b5fbb1b0778ede047a13a3cee9c59cfe, 23ce4b33932260ad1f1bca4978ea274a1da1e0ad.

**Comment by nomeata** [comment]
Thanks, got it :)
