### ISSUE TITLE
Writable derivations

### ISSUE THREAD

**Issue by Alkeryn** [NixOS/nix#3217]
So some software such as flutter needs to be able to write to their installation directory in order to function properly, there is an option on nix to make the nix store writable but that's not an elegant solution
it would be nice to be able to specify in a derivation that just its install directory is writable or to have a second nix store for softwares that needs to write to their installation directory in order to function correctly, maybe a non multiuser nix store /shrug

point is, it would be nice to be able to package software that needs rw access to their installation directory without having to make the whole nix store rw and or having to run the software as root

**Comment by grahamc** [comment]
Some software already in Nixpkgs wanted something similar. However, that goes against a core tenant of Nix: immutable packages and less writability. The correct way to handle this is correct the software and have it write elsewhere.

**Comment by grahamc** [comment]
> having to run the software as root

side note: on NixOS even root is unable to write to /nix/store, as the store is mounted ro.

**Comment by 7c6f434c** [comment]
And note that if the software is badly written and making it use sane locations is hard, it rarely complains if its installation directory contains symlinks to saner writeable locations.

**Comment by ElvishJerricco** [comment]
FYI: A common way to "fix" the software in `nixpkgs` without editing the software itself is to use `wrapProgram` in the derivation in order to set environment variables or command line arguments to make it use a different directory.

**Comment by he-la** [comment]
FYI: For extremely badly behaved programs where environment variables or command line arguments don't help, you can construct an overlay fs with the read-only nix store path as a base and a writable folder laid on top of it. E.g. you can use `wrapProgram` to wrap some shell script around the program that sets up the overlay fs before invoking the underlying program.
