### ISSUE TITLE
darwin: DEFAULT_ALLOWED_IMPURE_PREFIXES needs to include /bin/bash on macOS 10.15

### ISSUE THREAD

**Issue by lilyball** [NixOS/nix#3223]
On macOS 10.15 and later, executing `/bin/sh` read `/private/var/select/sh`, and if that fails it executes `/bin/bash`. Our current `DEFAULT_ALLOWED_IMPURE_PREFIXES` allows `/bin/sh` but does not allow `/bin/bash`.

We also need to update the sandbox profile itself to include `/bin/bash` for standard packages. Currently nixpkgs [adds `/bin/sh` to `impureHostDeps`](https://github.com/NixOS/nixpkgs/blob/fbfc258f1e60656821999771aa5fc8d175c784cb/pkgs/stdenv/darwin/default.nix#L25). Either we need to extend this to include `/bin/bash`, or we need to tweak Nix to detect when `/bin/sh` [is included](https://github.com/NixOS/nix/blob/aabf5c86c9df1b4e1616a4cf06ee14a6edf2e5e1/src/libstore/build.cc#L3037-L3045) and add `/bin/bash` as well. The former option will rebuild the entire nixpkgs world on darwin because every single stdenv derivation will be modified, whereas the latter will just hack the profile for a macOS 10.15-specific behavior (and we can specialize it to only do this when the current system is macOS 10.15 or later).

**Comment by lilyball** [comment]
Technically we don't need to extend `DEFAULT_ALLOWED_IMPURE_PREFIXES` if we put the hack into Nix to insert `/bin/bash` into the profile instead, but we probably should do it anyway because it's weird to reject a derivation for specifying that they want `/bin/bash` when they have access to it anyway.

Also, we should probably only allow `/bin/bash` as an impure host prefix on macOS 10.15+.

**Comment by lilyball** [comment]
We should also take steps to explicitly deny access to `/private/var/select/sh` in case the user adds it to their `extra-sandbox-paths`; keeping this denied will ensure `/bin/sh` is always `/bin/bash` and can't be pointed at `dash` or `zsh`. I don't know how the sandbox behaves if the profile tries to both deny and allow access to the same literal path, but we'll want to ensure deny takes precedence (if allow always takes precedence, we'll instead want to filter out `/private/var/select/sh` from any attempt to add it to the profile).

**Comment by lilyball** [comment]
For the moment I'm leaning towards patching Nix to insert `/bin/bash` when it sees `/bin/sh` on Catalina, without making any changes to nixpkgs.

**Comment by domenkozar** [comment]
Fixed in https://github.com/NixOS/nix/pull/3429
