### ISSUE TITLE
Nix RPM spec file missed dependencies

### ISSUE THREAD

**Issue by armijnhemel** [NixOS/nix#3226]
It seems the RPM spec file is out of date wrt dependencies. When running rpmbuild I get the following error:

    configure: error: Nix requires libeditline; it was found neither via pkg-config nor its normal header.
    error: Bad exit status from /var/tmp/rpm-tmp.4126qV (%build)

**Comment by armijnhemel** [comment]
It might be worth thinking about whether or not it will be useful to keep the .spec file around.

**Comment by edolstra** [comment]
Yeah, we're not testing/distributing RPMs anymore so maybe it's better to get rid of the .spec file.
