### ISSUE TITLE
Nix sometimes tries to install unspecified packages

### ISSUE THREAD

**Issue by guibou** [NixOS/nix#3227]
I observe a non-reproducible bug.

During the last few days, a few of my co-workers, using nix `2.3.1` on ubuntu have observed nix segmentation fault. Most of the time, the next `nix-shell` or `nix-build` command will fail with an "unfree" licence warning, similar to this one:

```
error: Package '«name-missing»' in /nix/store/xgzxz5y5gb6mks2v18l8rxvbinz53awy-nixpkgs-19.09pre184803.d567c486ca5/nixpkgs/pkgs/applications/misc/1password/default.nix:37 has an unfree license ('unfree'), refusing to evaluate.
a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnfree = true; }
in configuration.nix to override this.
b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnfree = true; }
to ~/.config/nixpkgs/config.nix.
(use '--show-trace' to show detailed location information)
```

However, nowhere in our nix codebase we are doing any reference to `1password`. Our nixpkgs version is pinned and setup with a `config = { allowBroken = true; }`, so as far as I know we are not using the "impure" part of nixpkgs: i.e we are not reading any system / user private config which may alter it in any way and introduce any dependency to `1password`.

The `Package '«name-missing»' ` is surprising because `1password` do have a name.

Even more surprising, that this is not reproducible! The next `nix-shell` or `nix-build` command will just work fine.

I don't know where does the `/nix/store/xgzxz5y5gb6mks2v18l8rxvbinz53awy-nixpkgs-19.09pre184803.d567c486ca5/` comes from. That's not the path of our pinned `nixpkgs`. It may be my co-worker `NIX_PATH` setup through `nix-channel`.

It behaves as if we were trying to build all of nixpkgs and it fails on the first `unfree` licence. I'd like to test this assumption by removing the `allowBroken = true` or adding `allowUnfree = true` in my configuration and see if it fails differently, but because the issue is not reproducible, I had not been able to test that.

I'm opening this issue in nix issue tracker because the segfault and the weird behavior, feel free to reorient me to the nixpkgs issue tracker if needed.

I'll try to add more information when available.

**Comment by guibou** [comment]
cc @flokli who may be interested.

**Comment by edolstra** [comment]
Probably the garbage collector screwing things up because of a missing root. If you run with the environment variable `GC_INITIAL_HEAP_SIZE=128k`, does that make the crash occur more often?

**Comment by guibou** [comment]
@edolstra :

`GC Warning: Bad initial heap size 128k - ignoring it.`

No warning message with `GC_INITIAL_HEAP_SIZE=1M`, Does not work with `xxxK`. I'll try it like that and tell you if the error happen.

**Comment by edolstra** [comment]
Strange, `128k` works for me (but `64k` doesn't).

**Comment by matthewbauer** [comment]
`128k` and `256k` fail for me but `512k` works.

**Comment by cstrahan** [comment]
Maybe the [`rr`](https://rr-project.org/) debugger could be helpful here :thinking:

**Comment by guibou** [comment]
I understood the issue and that's not related to nix at all. Sorry.

Deep in our workflow was a `nix-env -i $(nix-build something)`. However if `something` failed to build, the resulting command was `nix-env -i` which installs everything.

`nix-env -i` does have a really weird semantic, but that's another story ;) I'm closing this issue, sorry for the noise.

**Comment by guibou** [comment]
Note: the proper solution is to use `nix-env` like:

```
nix-env -f path/to/your/nix -i -A something
```
