### ISSUE TITLE
Merge nix-profile.sh and nix-profile-daemon.sh

### ISSUE THREAD

**Issue by lilyball** [NixOS/nix#3232]
I'd really love to find a way to merge `nix-profile.sh` and `nix-profile-daemon.sh` into a single file. If there's any way to detect that we have a multi-user install, we could use that to trigger the correct behavior. If not, we could come up with something (maybe add a file to `/etc/nix`), change the multi-user install to set that, and then figure out some migration path.

Heck, we could take this opportunity to have the single-user install note which user it was installed for such that we can make the `nix-profile.sh` script bail (or Nix itself bail) if it detects it's being run as the wrong user. This can be the same mechanism, such as a file `/etc/nix/mode` whose contents is either `user=<username|uid>` (preferably uid) or `daemon`. Or perhaps better yet is to put a file in `/nix` itself such that uninstalling Nix will delete it (since `rm -rf /nix` is required to uninstall but `rm -rf /etc/nix` is less obvious).

The motivating reason here is I want to use Nix to provide support tooling for an Xcode project. Xcode of course is a graphical IDE and therefore isn't being run from my shell, which means it won't inherit any env variables set up in my shell. So I need the support scripts that Xcode invokes to source the profile. I don't particularly want to have it source my entire `.bash_profile` (which is to say, I don't want the support tooling to be run as a bash login shell). My intended approach is to require users to define a variable somewhere saying "I have a multi-user install" and default to single-user if it's not set, but I don't like relying on users to provide that additional configuration. I could in theory look for the `nix-daemon` process but I'm not really a fan of introspecting the currently running processes just to figure out if I'm a multi-user install.

**Comment by abathur** [comment]
I'm trawling macOS issues and noticed you also have #3630 open. I guess this one can be closed unless there's a distinction.

**Comment by lilyball** [comment]
Haha yes I apparently forgot that I had already opened this one when I wrote #3630. I'll go ahead and close this one in favor of that.
