### ISSUE TITLE
Run nix without access to /proc/stat

### ISSUE THREAD

**Issue by Gerschtli** [NixOS/nix#3237]
Hello,

I am working an porting nix to android phones where I don't have read access to `/proc/stat` and receiving many messages like
```
GC Warning: Couldn't read /proc/stat
```

I grepped through the code but could not find any occurences of this path. Could you give me a pointer, where it is used and if there would be a possible patch to hide these warnings or if any other patches would be needed to make nix fully working under environments without `/proc/stat`?

Thank you very much!

**Comment by zimbatm** [comment]
Related: https://github.com/t184256/nix-in-termux/issues/2

The error comes from boehm-gc, probably because it tries to determine how many CPUs the machine has.

Can you try setting `export GC_NPROCS=1` before running nix?

**Comment by Gerschtli** [comment]
Ah perfect, that works perfectly fine. The fallback to one core seems like a reasonable solution.
