### ISSUE TITLE
Add NetBSD/FreeBSD Support

### ISSUE THREAD

**Issue by 0x4d6165** [NixOS/nix#3280]
Howdy! I'd like to request nix support for NetBSD and/or FreeBSD. There's a [wip port](https://wip.pkgsrc.org/cgi-bin/gitweb.cgi?p=pkgsrc-wip.git;a=tree;f=nix;h=bd6eebe083a9ebc7fa6f13083dd11623cb080fb1;hb=HEAD) but it fails to compile on NetBSD

**Comment by zimbatm** [comment]
Do you know if Rust compiles on NetBSD already? It's a dependency of the latest Nix.

**Comment by gigavinyl** [comment]
[Yep!](http://pkgsrc.se/lang/rust)

**Comment by gigavinyl** [comment]
We have a port in wip already going but the build fails:
```
  LD     src/libutil/libnixutil.so
/usr/pkg/lib: file not recognized: file format not recognized
gmake: *** [mk/lib.mk:104: src/libutil/libnixutil.so] Error 1
gmake: *** Waiting for unfinished jobs....
```

**Comment by gigavinyl** [comment]
OpenBSD support would also be awesome and they're pretty similar to each other.

**Comment by zimbatm** [comment]
There are probably a lot of linux-only assumptions in the code base that need to be fixed. Hopefully another BSD developer will step in.

**Comment by 0mp** [comment]
@l4nn1312, you might be interested in https://github.com/NixOS/nixpkgs/pull/81459 and https://github.com/0mp/freebsd-ports-nix as well.

**Comment by DrSensor** [comment]
On going discussion https://discourse.nixos.org/t/nix-landed-in-freebsd-ports/9140

**Comment by DrSensor** [comment]
not staled

**Comment by Ericson2314** [comment]
Still working on Nixpkgs freebasd cross support which should make this easier to test.

**Comment by Ericson2314** [comment]
Still important.

**Comment by jgod** [comment]
Would be cool

**Comment by Ericson2314** [comment]
I think that thanks to all of @alyssais's polishing that this can be closed. GIve them spins in 23.05!

**Comment by vedranmiletic** [comment]
> On going discussion https://discourse.nixos.org/t/nix-landed-in-freebsd-ports/9140

FWIW, [sysutils/nix](https://www.freshports.org/sysutils/nix/) port on FreeBSD is now marked as unmaintained and broken.
