### ISSUE TITLE
Install script fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by omelkonian** [NixOS/nix#3282]
Running `sh <(curl https://nixos.org/nix/install) --no-daemon` results in the following error on Ubuntu 16.04:
```
/nix/store/6chjfy4j6hjwj5f8zcbbdg02i21x1qsi-nix-2.3.1/bin/nix-store: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /nix/store/ds682770c3i8nawsq6d1p9g5qbf5sgnd-libsodium-1.0.16/lib/libsodium.so.23)
/nix/store/6chjfy4j6hjwj5f8zcbbdg02i21x1qsi-nix-2.3.1/bin/nix-store: /lib/x86_64-linux-gnu/liblzma.so.5: version `XZ_5.2' not found (required by /nix/store/6chjfy4j6hjwj5f8zcbbdg02i21x1qsi-nix-2.3.1/lib/libnixutil.so)
```

When doing a multi-user install `sh <(curl https://nixos.org/nix/install) --daemon` install runs fine, but any nix invocation crashes with the same error.

Have also tried older versions, but the same error occurs...

**Comment by matthewbauer** [comment]
Nix should be using its own libc to run. I'm not sure why it would be picking up `/lib/x86_64-linux-gnu/libc.so.6` and `/lib/x86_64-linux-gnu/liblzma.so.5`. Could LD_LIBRARY_PATH be set?

**Comment by omelkonian** [comment]
You were right, resetting `LD_LIBRARY_PATH` before invoking the install command seems to do the trick; now everything installs fine.

Nonetheless, shouldn't the install script be a bit more robust, i.e. work regardless of whether `LD_LIBRARY_PATH` is set?

**Comment by matthewbauer** [comment]
Perhaps we could reset it. There is always a chance that you are intentionally setting it though.
