### ISSUE TITLE
nix-env --query --attr-path shows unrelated number instead of attribute path

### ISSUE THREAD

**Issue by bcc32** [NixOS/nix#3288]
Running `nix-env --query --attr-path` shows a number next to each package rather than the attribute path I would have expected:

```
$ nix-env -qP
5  binutils-wrapper-2.30
7  direnv-2.15.1
8  fasd-unstable-2016-08-11
3  nethogs-0.8.5
0  perl5.30.0-local-lib-2.000024
2  pv-1.6.6
6  rhash-2018-02-05
1  rxvt-unicode-with-perl-with-unicode3-9.22
4  speedtest-cli-2.0.0
```

The numbers appear to be sequential, decreasing in order of most recently installed packages.  It's not clear why these numbers are displayed, nor how to get it to show the package attribute path instead.

By the way, I'm running:

```
$ nix-env --version
nix-env (Nix) 2.3
```

**Comment by zimbatm** [comment]
the numbering seems to be the position in the list that is defined in `manifest.nix` . See `/nix/var/nix/profiles/per-user/$USER/profile/manifest.nix` where $USER is your username.
