### ISSUE TITLE
Update of oniguruma breaks nixUnstable.x86_64-darwin

### ISSUE THREAD

**Issue by markuskowa** [NixOS/nix#3290]
The update of oniguruma (6.9.3 -> 6.9.4, https://github.com/NixOS/nixpkgs/pull/75302) seems to break a test in nixUnstable.x86_64-darwin. 
So far this bug has been observed on the 19.09 build of the staging branch: https://hydra.nixos.org/build/108689390, https://hydra.nixos.org/eval/1561564#tabs-now-fail

**Comment by zimbatm** [comment]
Is it possible that the clang libc++ depends on oniguruma for the regexp engine? Nix uses `std::regexp` which is provided by libc++.

**Comment by LnL7** [comment]
In that case the entire darwin stdenv would have been rebuilt by that change.

**Comment by zimbatm** [comment]
Also it's failing on `tests/gc-auto.sh` so it seems quite unrelated. Maybe it's a flaky test

**Comment by markuskowa** [comment]
@zimbatm can try to reproduce the error? I am not a darwin user.

**Comment by edolstra** [comment]
Yes, I think it's unrelated, `gc-auto.sh` is flaky.
