### ISSUE TITLE
sign release tarballs directly, not their hash files

### ISSUE THREAD

**Issue by thkoch2001** [NixOS/nix#3293]
related issues: 
https://github.com/NixOS/nix/issues/404 Add an OpenPGP signature for every tarball on nixos.org ( @domenkozar )
https://github.com/NixOS/nix/issues/17 Sign released Nix tarballs

Nix [releases](https://nixos.org/releases/nix/latest/) come with a .sha256 hash file and a .asc signature file over the hash file. This seems strange as gpg could directly make a signature over the original file. The latter is expected by Debian packaging tools. It is still possible to package nix for Debian, but verification of the upstream tarball must be done manually with the current release scheme.

Would you mind to provide a signature (.asc file) over the tarball itself instead of the hash file?

This has previously been discussed here:
https://lists.debian.org/debian-devel/2019/12/msg00081.html

**Comment by zimbatm** [comment]
It seems to work as expected for me:
```
$ curl -o nix.tar.xz https://nixos.org/releases/nix/nix-2.3.1/nix-2.3.1.tar.xz
$ curl -o nix.tar.xz.asc https://nixos.org/releases/nix/nix-2.3.1/nix-2.3.1.tar.xz.asc
$ gpg2 --verify ./nix.tar.xz.asc 
gpg: assuming signed data in './nix.tar.xz'
gpg: Signature made Thu 10 Oct 2019 04:06:58 PM CEST
gpg:                using RSA key B541D55301270E0BCF15CA5D8170B4726D7198DE
gpg: Good signature from "Eelco Dolstra <edolstra@gmail.com>" [unknown]
gpg:                 aka "Eelco Dolstra <eelco.dolstra@logicblox.com>" [unknown]
gpg:                 aka "Eelco Dolstra <eelco.dolstra@tweag.io>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: B541 D553 0127 0E0B CF15  CA5D 8170 B472 6D71 98DE
```

**Comment by edolstra** [comment]
Indeed, the signature is over the tarball, not the hash. You can see the signature generation here: https://github.com/NixOS/nix/blob/b0cadf547bf2f796b550d7555b97761ff1d0a379/maintainers/upload-release.pl#L60-L81

You can ignore the `.sha256` file, it's not needed for verifying the GPG signature.
