### ISSUE TITLE
Run the suit on non-standard storage path.

### ISSUE THREAD

**Issue by siscia** [NixOS/nix#3299]
I keep finding several issues when trying to run nix using a not standard storage path, so anything that is not /nix 

I am wondering if the test suits runs on non-standard storage path.

Is there documentation on how to run the tests? Can we automatically run the test on a not-standard remote path?

**Comment by edolstra** [comment]
The test suite in fact *only* uses a non-standard prefix, namely `$TMPDIR/nix-test/store`. See https://github.com/NixOS/nix/blob/master/tests/common.sh.in.

**Comment by siscia** [comment]
Do we also get documentation on how to run the tests?

**Comment by edolstra** [comment]
Yes, it's in the hacking section of the manual: https://nixos.org/nix/manual/#chap-hacking
