### ISSUE TITLE
Following manual section 2.5.4 results in wrong swap partition being configured.

### ISSUE THREAD

**Issue by trusktr** [NixOS/nix#3310]
Basically the details here: https://discourse.nixos.org/t/wrong-swap-partition-detected-by-nixos-generate-config-on-fresh-install/5355

After running the `nixos-generate-config` step, the generated `hardware-configuration.nix` file contains the wrong swap partition(s).

I'm not sure how to fix this at a higher level so it doesn't happen to people, but luckily I looked in the file and made the manual correction as needed.

I'm sure some people may not look in the file, and assume the installation steps just work.

**Comment by LnL7** [comment]
Same as #3311.

**Comment by edolstra** [comment]
Yes, please reopen in the nixpkgs repo.
