### ISSUE TITLE
Docs needs an update regarding partition creation, so as not to give bad advice.

### ISSUE THREAD

**Issue by trusktr** [NixOS/nix#3311]
More details at https://discourse.nixos.org/t/following-install-gave-warning-the-resulting-partition-is-not-properly-aligned-for-best-performance/5335

Sorry if this question should be obvious, but where are the docs for this section?

**Comment by LnL7** [comment]
This issue belongs in https://github.com/NixOS/nixpkgs, specifically this nixos manual. The section you are referring to is probably defined here https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/installation/installing.xml. 

This repository is the package manager itself.
