### ISSUE TITLE
Incorrect statement in the docs. Where to edit?

### ISSUE THREAD

**Issue by trusktr** [NixOS/nix#3312]
The section [5.3 Modularity](https://nixos.org/nixos/manual/index.html#sec-modularity) says

> Modules have exactly the same syntax as configuration.nix. In fact, configuration.nix is itself a module. You can use other modules by including them from configuration.nix, e.g.:
> 
> ```nix
> { config, pkgs, ... }:
> 
> { imports = [ ./vpn.nix ./kde.nix ];
>   services.httpd.enable = true;
>   environment.systemPackages = [ pkgs.emacs ];
>   ...
> }
> ```
> 
> Here, we include two modules from the same directory, `vpn.nix` and `kde.nix`. The latter might look like this:
> 
> ```nix
> { config, pkgs, ... }:
> 
> { services.xserver.enable = true;
>   services.xserver.displayManager.sddm.enable = true;
>   services.xserver.desktopManager.plasma5.enable = true;
> }
> ```
> 
> Note that both `configuration.nix` and `kde.nix` define the option `environment.systemPackages`. When multiple modules define an option, NixOS will try to _merge_ the definitions.

But the second snippet from `kde.nix` does not contain `environment.systemPackages`.

I'm not sure where in the documentation this is located, to attempt to fix it.

**Comment by infix** [comment]
the source code for "5.3 Modularity" is located in the nipkgs repo at [nixos/doc/manual/configuration/modularity.xml](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/configuration/modularity.xml)

**Comment by zimbatm** [comment]
please re-open in the nixpkgs repo
