### ISSUE TITLE
Impossible to *reliably* find out path to active shell file from a `shellHook` script

### ISSUE THREAD

**Issue by jraygauthier** [NixOS/nix#3339]
Assuming I do:

```bash
$ cd /path/to/other/dir
$ nix-shell /path/to/my/shell.nix
# ..
```

I would expect from `shellHook` to be able to retrieve the path to my *active
shell file* reliably and without regards to the `CWD` the user was in when a
launched `nix-shell` in order for example to perform some development setup with
path relative to that file.

An concrete example of what I mean:

```nix
# ..
mkShell {
  # ..
  shellHook = ''
    shell_dir="$(pwd)"
    # Previous is wrong and returns '/path/to/other/dir' instead of '/path/to/my/'.
  
    shell_file="$0"
    # Previous is wrong and returns 'bash'.
  
    shell_dir="$(dirname "$IN_NIX_SHELL_FILE")"
    # Previous does not exist yet.
  
    #
    # Some examples:
    #
  
    export MY_LOCAL_SRC_CODE="$shell_dir/my/src/dir"

    generate-directory jupyterlab-ihaskell jupyterlab_bokeh
  
    generate-my-nodejs-stuff "$shell_dir/node_modules"
  '';
}
```

### Some ideas:

Some extra variables might be accessible from `shellHook` (and not from other
phases) which would allow some potentially *impure* access to files for
development purposes.

 -  `IN_NIX_SHELL_FILE=/path/to/my/shell.nix`
 -  `NIX_ACTIVE_SHELLS=/path/to/my/shell.nix:/other/nix/shell.nix`
 -  `NIX_PATH="active-shell-file=/path/to/my/shell.nix:nixpkgs=/path/to/nixpkgs"`

**Comment by LnL7** [comment]
Nix resolves paths relative to the current file, you can use that. For builds this is undesirable since the drv now depends on the project dir but for shell expressions that's not really a problem.

```nix
mkShell {
  shellHook = ''
    export FOO_PATH=${toString ./.}/foo
  '';
}
```

**Comment by jraygauthier** [comment]
@LnL7: What you suggest is nice for some use cases. 

However, the environment variable now points to an immutable nix store which couldn't be written to (the jupyterWith `generate-directory`, `generate-my-nodejs-stuff`). It also applies to to `MY_LOCAL_SRC_CODE` case, as when an error occur in the source code, I want the developers to be able to click on the url to the local file and *edit it right away* instead of going through the headache of searching for the corresponding file in the source.

**Comment by LnL7** [comment]
Not with `toString`, interpolating a string or a path behaves differently.

```
nix-repl> "${./.}"
"/nix/store/4scaqq8imyjdp4zkcxj8cdvwrvlggs9l-foo"

nix-repl> "${toString ./.}"
"/tmp/foo"
```

**Comment by jraygauthier** [comment]
Alright, you're right. It works fine! I am positively surprise by this!

```nix
# ..
mkShell {
  # ..
  shellHook = ''
    shell_dir="${toString ./.}"
    # The previous now correctly points to '/path/to/my'!
    export MY_LOCAL_SRC_CODE="$shell_dir/my/src/dir"
  '';
}
```

Thank you. It resolve the issue for me.

**Comment by jraygauthier** [comment]
Some personal notes I took to remember this (if it might serve others):

### Resolve original / local paths instead of nix store copies from a nix file

Assuming the following `/path/to/my/test.nix`:

```nix
{
    nix_file_dir_from_interpolated_string = "${toString ./.}";
    nix_file_dir_from_interpolated_path = "${./.}";
}
```

Opening the file using nix *REPL*, it yields:

```bash
$ nix repl
nix-repl>
```

```nix
nix-repl> :l test.nix
Added 2 variables.

nix-repl> nix_file_dir_from_interpolated_string
"/home/rgauthier/dev/zilia-ocular/nixos-secure-factory/scripts/factory-common-install"

nix-repl> nix_file_dir_from_interpolated_path  
"/nix/store/pgq4vcdjwn4fk4dx61f777iwqg0bx3x0-factory-common-install"
```

Note how converting the path to a string before interpolation
(`nix_file_dir_from_interpolated_string`) yielded the **original/local path**
whereas when directly interpolating the path
(`nix_file_dir_from_interpolated_path`) it yields the **immutable nix store copy
of the path**.

This behaviour is quite surprising as the `toString` function actually **transformed
to the relative path into an absolute path**.

Being a string type now **protected this absolute path from being transformed** into
a nix store path when interpolated.

So this is a nice escape hatch to access local path in nix strings
(configuration files, bash phases / hooks, etc).

**Comment by samuela** [comment]
It seems `echo "${./.}"` and `echo "${toString ./.}"` sometimes run forever-ish:
```
❯ nix-shell
warning: dumping very large path (> 256 MiB); this may run out of memory
...
```

**Comment by deliciouslytyped** [comment]
@samuela You may be unaware that referring to a path pulls the path into the nix store? I.e. the entire `./.` directory is copied to the nix store with what you posted. `toString` drops some internal labeling from from the path object, when turning it into a string. This is what removes the information telling nix to copy a path into the store.

**Comment by AleXoundOS** [comment]
Is it possible to find out filepath to the actual active shell **file.nix** (not containing path)?
