### ISSUE TITLE
Progress bar documentation

### ISSUE THREAD

**Issue by kirelagin** [NixOS/nix#3352]
Is there any documentation on the progress bar that `nix build` outputs? I couldn’t find any, and it’s very confusing. It’s impossible to guess what those numbers between `[` and `]` mean.

I looked at the source code and now _I know_ that blue and green are “running” and “done”, but the white number is “expected” and I still have no idea what it is. It’s going down all the time while the build is running, so my guess is that it is “remaining” but why is it called “expected” then? Why is it [initialised with `done`](https://github.com/NixOS/nix/commit/b29b6feaba715432490e275a025b3361a021a99b#diff-48e015e4afcc53c378b66a83b63ee9beR219) even though there is [a field called `expected`](https://github.com/NixOS/nix/commit/b29b6feaba715432490e275a025b3361a021a99b#diff-48e015e4afcc53c378b66a83b63ee9beR47)?

**Comment by edolstra** [comment]
```
[1/0/4 built, 1/56/58 copied (618.5/895.2 MiB), 133.3/244.4 MiB DL] fetching rustc-1.40.0 from https://cache.nixos.org
```
* 1 = number of active builds
* 0 = number of succeeded builds
* 4 = number of expected builds
* 1 = number of paths being substituted
* 56 = number of paths successfully substituted
* 58 = number of paths expected to be substituted
* 618.5 MiB = bytes written to the Nix store
* 895.2 MiB = bytes expected to be written to the Nix store
* 133.3 MiB = bytes downloaded
* 244.4 MiB = bytes expected to be downloaded
* `fetching rustc-1.40.0 from https://cache.nixos.org` = message from the latest activity (download, build, ...)
```
"Expected" refers to the predicted final total. So it should never be lower than "done".

In the interest of simplification, we could get rid of the "copied" stuff. I.e. the progress bar would become
```
[1/0/4 built, 133.3/244.4 MiB DL] fetching rustc-1.40.0 from https://cache.nixos.org
```

**Comment by kirelagin** [comment]
But why is “expected” going down in the process without any other numbers being incremented? What makes “expected” builds to disappear?

**Comment by edolstra** [comment]
Closing because the new progress indicator (#4296) should be self-explanatory.

**Comment by bobvanderlinden** [comment]
Even though I've looked at the progress of builds a lot of times, I still needed to refer back to this issue to remind myself what the numbers actually mean.

Since the new progress indicator is not yet finalized/merged, I think this issue should stay open.

**Comment by sepiabrown** [comment]
> Even though I've looked at the progress of builds a lot of times, I still needed to refer back to this issue to remind myself what the numbers actually mean.
> 
> Since the new progress indicator is not yet finalized/merged, I think this issue should stay open.

Same here!

**Comment by Gordon01** [comment]
It might also be easier to display a real progress bar or percentage when the number of derivations to be built is large enough to allow for meaningful increments.

**Comment by bobvanderlinden** [comment]
I nowadays use https://github.com/maralorn/nix-output-monitor. It's clear what the numbers mean because of their icons and gives way more context.
