### ISSUE TITLE
ssh-ng:// much slower for copying than ssh://

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nix#3372]
I'm not sure why, but copying drvs with `nix copy --to ssh-ng://$host` takes ~7 times as long as with `nix copy --to ssh://$host`:

```
$ ssh $host nix-store --gc &>/dev/null
$ time nix copy --to ssh://lugn $(nix-instantiate '<nixpkgs>' -A gnupg)
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
[560 copied (1.5 MiB)]

real    0m20.273s
user    0m0.836s
sys     0m0.172s
$ ssh $host nix-store --gc &>/dev/null
$ time nix copy --to ssh-ng://$host $(nix-instantiate '<nixpkgs>' -A gnupg)
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
[560 copied (1.5 MiB)]

real    3m29.906s
user    0m2.171s
sys     0m0.794s
```

This should probably be addressed before ssh-ng replaces ssh.

**Comment by lheckemann** [comment]
This is even worse for bigger, non-drv paths:
```
$ time nix copy --to ssh://$host $(nix-build '<nixpkgs>' -A gnupg)
[39 copied (83.6 MiB)]

real    0m5.005s
user    0m0.465s
sys     0m0.215s

$ ssh $host nix-store --gc &>/dev/null
$ time nix copy --to ssh-ng://$host $(nix-build '<nixpkgs>' -A gnupg)
[39 copied (83.6 MiB)]

real    47m56.251s
user    0m10.558s
sys     0m5.753s

```

**Comment by basvandijk** [comment]
Not sure if the following is causing this but I see that the SSH stores use different remote programs:

* The legacy SSH store (`ssh://`) [uses](https://github.com/NixOS/nix/blob/master/src/libstore/legacy-ssh-store.cc#L19) `nix-store --serve --write`.
* The  new SSH store (`ssh-ng://`) [uses](https://github.com/NixOS/nix/blob/ebb20a5356af023498506324bd0f88a99175e295/src/libstore/ssh-store.cc#L19) `nix-daemon --stdio`.

One suspicion I have is that the legacy SSH store can write a NAR directly to the store using `nix-store` while the new SSH store has to first write the NAR to the socket of the `nix-daemon` which then writes it to the store.

@lheckemann does the user you SSH to have write access to the store?

**Comment by lheckemann** [comment]
@basvandijk no, no write access.
