### ISSUE TITLE
error: opening lock file '/nix/var/nix/profiles/default.lock': Permission denied

### ISSUE THREAD

**Issue by toxynoid** [NixOS/nix#3374]
Starting nix from topgrade on Ubuntu 19.10 I get:
`$ nix upgrade-nix
[0.0 MiB DL]
replacing old 'nix-2.3.3'
installing 'nix-2.3.3'
warning: ignoring the user-specified setting 'sandbox', because it is a restricted setting and you are not a trusted user
error: opening lock file '/nix/var/nix/profiles/default.lock': Permission denied
error: program '/nix/store/ddmmzn4ggz1f66lwxjy64n89864yj9w9-nix-2.3.3/bin/nix-env' failed with exit code 1`

**Comment by toxynoid** [comment]
After correctly updating nix the error is gone:
`nix-channel --update; nix-env -iA nixpkgs.nix`

**Comment by toxynoid** [comment]
Updating/initializing could be done by the installer

**Comment by tabbyrobin** [comment]
I just had this issue on a qubes standalone VM based on debian-11. For install method i used the multi-user one-liner: 
`sh <(curl -L https://nixos.org/nix/install) --daemon` per this page: 
https://nixos.org/download.html#nix-install-linux

After running `nix-channel --update; nix-env -iA nixpkgs.nix`, i no longer get the permissions error for `nix upgrade-nix`.

Note: this is a fresh install, i have not added any channels, `nix-channel --list` is empty on my install
