### ISSUE TITLE
--max-substituter-jobs

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nix#3379]
`-j` is CPU bound, while new proposed setting is IO bound. 

I think often nowadays we have really fast connection speeds, so being able to set the two separately would speed up mostly CI jobs where it needs to fetch 300 store paths and build one thing.

**Comment by Mic92** [comment]
I think should also include fixed-input derivations such as `fetchurl`. To give an example on a typically build it will first try build all fixed-input derivations  while the CPU is idle also it already has the source for some of the non-fixed input derivation one.

**Comment by domenkozar** [comment]
@Mic92 I'm not sure about that. 

https://input-output-hk.github.io/haskell.nix/tutorials/materialization/ for example uses fixed derivations to speed up IFD, but then those are quite rare and shouldn't have that much impact compared speed up of all fetchurl run in parallel.

**Comment by Mic92** [comment]
> @Mic92 I'm not sure about that.
> 
> [input-output-hk.github.io/haskell.nix/tutorials/materialization](https://input-output-hk.github.io/haskell.nix/tutorials/materialization/) for example uses fixed derivations to speed up IFD, but then those are quite rare and shouldn't have that much impact compared speed up of all fetchurl run in parallel.

Is this something the evaluation cache could solve in the future?

**Comment by domenkozar** [comment]
@Ericson2314 given that you're working on the scheduler, how feasible is this?

**Comment by domenkozar** [comment]
Talking to @Ericson2314 the logic happens in `Worker::waitForBuildSlot` which calls `getNrLocalBuilds`, so that should become two counters then.

**Comment by Profpatsch** [comment]
> https://input-output-hk.github.io/haskell.nix/tutorials/materialization/ for example uses fixed derivations to speed up IFD, but then those are quite rare and shouldn't have that much impact compared speed up of all fetchurl run in parallel.

That’s quite the hack around real IfD caching support. Nix should be able to substitute stuff like that as well. Maybe it can, the cabal2nix drv just has `allowSubstitutes = false;` set, which leads us back to https://github.com/NixOS/nix/issues/4364#issuecomment-749515679

I feel like `--ignore-allow-substitutes` already leads quite a ways there.

**Comment by domenkozar** [comment]
Uh, that's even more complexity :/

**Comment by domenkozar** [comment]
Not stale.
