### ISSUE TITLE
Document `import <...>` syntax in "Writing Nix Expressions" chapter of manual

### ISSUE THREAD

**Issue by cantora** [NixOS/nix#338]
I'm just starting to learn nix and I found it confusing that `import <nixpkgs>` appears in many examples, yet the angle bracket syntax is not mentioned in the nix expression syntax documentation. I did end up finding an explanation for it in the "Common environment variables" section, but I think it the syntax should be documented with the rest of the syntax documentation.

EDIT:
I would add the documentation myself, but I actually don't feel that I fully understand the angle bracket syntax from reading the explanation in "Common environment variables".

**Comment by npostavs** [comment]
+1, I thought at first this it was some kind of meta-syntax that should be substituted by the user with some other value. It's used all over the docs, in the [FAQ], but never explained...

[FAQ]: https://nixos.org/wiki/FAQ

**Comment by earksiinni** [comment]
I'm also learning Nix and found this frustrating. Just created this PR to fix it: https://github.com/NixOS/nix/pull/3159

@tobiasBora, I noticed your PR (https://github.com/NixOS/nixpkgs/pull/63033) for the Nixpkgs repo, but I assume that yours fixes the issue in Nixpkgs' docs. My PR is for the Nix manual. Perhaps fixing in both places is the best policy.

**Comment by earksiinni** [comment]
Can we close this now that my PR got merged?
