### ISSUE TITLE
License of style.css is GPL?

### ISSUE THREAD

**Issue by thkoch2001** [NixOS/nix#3392]
@vslavik Maybe you could add a comment here saying that you're fine with your 2003 version of this file to fall under the LGPL-2.1+?

This issue was part of the rejection reasons in the first review of nix for entrance in the Debian archive.

The file doc/manual/style.css has been imported into the nix code on Dec 2 2003 with a comment pointing to bakefile. The file can still be found in the SVN repo on sourceforge:
https://sourceforge.net/p/bakefile/code/HEAD/tree/bakefile/trunk/doc/html/style.css

The file was added in SVN rev 5 on 2003-06-10 by vaclavslavik (Václav Slavík <vaclav@slavik.io>). The COPYING file of the repo contains the GPL 2 text:
https://sourceforge.net/p/bakefile/code/451/tree/trunk/bakefile/COPYING

There is no indication of "or later".

Afterwards more than half of the file was changed by Eelco Dolstra.

So the nitpicking-proof-correct license header would probably be

```
/*
    Copyright 2003 Václav Slavík <vaclav@slavik.io>
    Copyright 2003-2018 Eelco Dolstra

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation in version 2.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
```

Please note that Debian copyright reviews are done by volunteers that are not lawyers. Sometimes the reviews might seem overly nitpicking. This however helps Debian to not have any troubles even with potential lawsuits.

**Comment by vslavik** [comment]
> @vslavik Maybe you could add a comment here saying that you're fine with your 2003 version of this file to fall under the LGPL-2.1+?

I do not appreciate appropriation of my work, however trivial, without permissions and without attribution, nor the implicit implication here that I *should* be fine with it. Therefore I explicitly do not give permission for any relicensing of my work except as permitted by the license attached to it.

*However*, do not despair. The Bakefile code was relicensed later, see https://github.com/vslavik/bakefile/tree/legacy-0.2-branch — to a license that is more permissive and gives you a way to resolve this without hassle. Do note, however, that even the MIT license *still has obligations that you must meet*, such as including a copy of the copyright notice (which is in the `COPYING` file over there), and you still can't be entirely blasé about it.

> Afterwards more than half of the file was changed by Eelco Dolstra.

That is irrelevant, except requiring them to give permission too. It's a derivative work, now with two copyright holders.

> Please note that Debian copyright reviews are done by volunteers that are not lawyers. Sometimes the reviews might seem overly nitpicking. 

Debian does really good work w.r.t. licensing. They are entirely correct to see this as a red flag.

**Comment by grahamc** [comment]
Thank you for bringing this up. We have evidently managed to mess this up several times, as we've duplicated this file a bunch of places:

- https://github.com/NixOS/nixpkgs/blob/e54d71c96fc5ceb8624b974ae3b9899c550fe37c/doc/style.css
- https://github.com/NixOS/hydra/blob/123bee1db599818f34f880a756a44339c57c7ade/doc/manual/style.css
- https://github.com/NixOS/nix/blob/d37dc71e3cf077fa5d24a9bf8395deae21cc4410/doc/manual/style.css
- https://github.com/NixOS/nix-pills/blob/b1c0f7c896b85a5df205db9e67cef7403f00401a/style.css
- https://github.com/NixOS/nixops/blob/c9a174efe7a695ddff8b42b15d603ce8b2c4a0d1/doc/manual/style.css

and so we will need to fix this issue in several places.

**Comment by edolstra** [comment]
Thanks. I've removed this file. It was added back when Nix was still GPL-licensed, so we should have removed it when we changed the license to the LGPL. Apologies to @vslavik!
