### ISSUE TITLE
mk/ folder has no clear copyright

### ISSUE THREAD

**Issue by thkoch2001** [NixOS/nix#3394]
This issue was part of the rejection reasons in the first review of nix for entrance in the Debian archive.

/mk/README.md points to https://github.com/edolstra/make-rules as the source. However the latter does not specify a license.

Since the repo is owned by @edolstra one could assume that he is OK with the same license as the nix repo. It would help a lot if this could quickly be added to the make-rules repo and than copied over to the nix repo.

**Comment by edolstra** [comment]
I've removed mk/README.md and archived the make-rules repo, which was no longer maintained. The current mk/* files are under the same license as the rest of Nix.
