### ISSUE TITLE
Substitutions broken with curl 7.69.0 and nix 2.3.2

### ISSUE THREAD

**Issue by wak-google** [NixOS/nix#3399]
nix just freezes printing `download thread waiting for 100 ms` over and over without making progress. Simply rebuilding against curl 7.68.0 with no other changes resolves this issue. This is with an http/2 host providing the cache with what appears to be multiple streams.
[nix.log](https://github.com/NixOS/nix/files/4316324/nix.log)

**Comment by wak-google** [comment]
Most relevant log lines prior to getting stuck

```
curl: Couldn't find host cache.triton.wak.io in the .netrc file; using defaults
curl: Found bundle for host cache.triton.wak.io: 0x7f6c7807acd0 [can multiplex]
curl: Multiplexed connection found!
curl: Re-using existing connection! (#0) with host cache.triton.wak.io
curl: Transfer was pending, now try another
curl: Using Stream ID: f (easy handle 0x7f6c780ae880)
curl: Couldn't find host cache.triton.wak.io in the .netrc file; using defaults
curl: Found bundle for host cache.triton.wak.io: 0x7f6c7807acd0 [can multiplex]
curl: Multiplexed connection found!
curl: Re-using existing connection! (#0) with host cache.triton.wak.io
curl: Transfer was pending, now try another
curl: Using Stream ID: 11 (easy handle 0x7f6c780c6250)
curl: Couldn't find host cache.triton.wak.io in the .netrc file; using defaults
curl: Found bundle for host cache.triton.wak.io: 0x7f6c7807acd0 [can multiplex]
curl: Multiplexed connection found!
curl: Re-using existing connection! (#0) with host cache.triton.wak.io
curl: Transfer was pending, now try another
curl: Using Stream ID: 13 (easy handle 0x7f6c78226e20)
download thread waiting for 100 ms
download thread waiting for 100 ms
download thread waiting for 100 ms
download thread waiting for 100 ms
download thread waiting for 100 ms
download thread waiting for 100 ms
got header for 'https://cache.triton.wak.io/nar/1k5286rhcd79w720skgzmr02ajq6zzfq2sv6aasvqqh3il9bwnng.nar.xz': HTTP/2 200
got header for 'https://cache.triton.wak.io/nar/1k5286rhcd79w720skgzmr02ajq6zzfq2sv6aasvqqh3il9bwnng.nar.xz': server: nginx/1.16.1
got header for 'https://cache.triton.wak.io/nar/1k5286rhcd79w720skgzmr02ajq6zzfq2sv6aasvqqh3il9bwnng.nar.xz': date: Wed, 11 Mar 2020 06:07:03 GMT
got header for 'https://cache.triton.wak.io/nar/1k5286rhcd79w720skgzmr02ajq6zzfq2sv6aasvqqh3il9bwnng.nar.xz': content-type: application/octet-stream
got header for 'https://cache.triton.wak.io/nar/1k5286rhcd79w720skgzmr02ajq6zzfq2sv6aasvqqh3il9bwnng.nar.xz': content-length: 2244944
got header for 'https://cache.triton.wak.io/nar/1k5286rhcd79w720skgzmr02ajq6zzfq2sv6aasvqqh3il9bwnng.nar.xz': last-modified: Tue, 18 Feb 2020 08:45:16 GMT
got header for 'https://cache.triton.wak.io/nar/1k5286rhcd79w720skgzmr02ajq6zzfq2sv6aasvqqh3il9bwnng.nar.xz': etag: "5e4ba41c-224150"
got header for 'https://cache.triton.wak.io/nar/1k5286rhcd79w720skgzmr02ajq6zzfq2sv6aasvqqh3il9bwnng.nar.xz': strict-transport-security: max-age=31536000; includeSubDomains; preload
got header for 'https://cache.triton.wak.io/nar/1k5286rhcd79w720skgzmr02ajq6zzfq2sv6aasvqqh3il9bwnng.nar.xz': accept-ranges: bytes
got header for 'https://cache.triton.wak.io/nar/1k5286rhcd79w720skgzmr02ajq6zzfq2sv6aasvqqh3il9bwnng.nar.xz':
download thread waiting for 100 ms
download thread waiting for 100 ms
download thread waiting for 100 ms
download thread waiting for 100 ms
download thread waiting for 100 ms
```

**Comment by edolstra** [comment]
This is fixed in 2.3.3.

**Comment by wak-google** [comment]
This is definitely still broken on 2.3.3

**Comment by dtzWill** [comment]
On Wed, 11 Mar 2020 13:08:56 -0700, "William A. Kennington III" <notifications@github.com> wrote:
> This is definitely still broken on 2.3.3
> 

That's my experience as well, but didn't say so immediately as I
generally use a patched version and only minimally tested that this
occurred with stable release before reverting back to curl 7.68.0.

Does the problem occur for you with 7.68.0 (2.3.2 or 2.3.3)?

If this is what I encountered this is new to upgrading to 7.69.0,
just wanted to confirm if that's what you're seeing as well? :)

**Comment by dtzWill** [comment]
Gah, all that said I primarily spoke up to mention this:

Looks like 7.69.1 was released: https://curl.haxx.se/changes.html#7_69_1 .

I haven't tried, but maybe/hopefully the issue is resolved as one of the fixed bugs....? :crossed_fingers:

**Comment by wak-google** [comment]
@dtzWill Looks to be fixed by 7.69.1

**Comment by wkennington** [comment]
Verified that curl 7.69.1 fixes the regression introduced in curl 7.69.0 against nix 2.3.2 and 2.3.3. We can probably close this since it was likely just an upstream bug causing curl request processing to hang.

**Comment by edolstra** [comment]
I see that NixOS 20.03 is using curl 7.68.0, so it would be good to know if it has this issue.

**Comment by vcunat** [comment]
I just looked at a notebook with older 20.03 installation.  It has nix-2.3.2 with curl-7.68.0.  To be sure I re-tried lots of substitutions, and there were no issues.

**Comment by vcunat** [comment]
According to [upstream page](https://curl.haxx.se/docs/security.html), the last vulnerable version was 7.67.0, so even future backports seem very unlikely to introduce 7.69.0.
