### ISSUE TITLE
Get git revision from a tarball

### ISSUE THREAD

**Issue by xzfc** [NixOS/nix#3407]
Is there a way to get git revision inside a derivation built from a tarball URL? (i.e. `nix-env -if https://….tar.gz`)

Github's tarballs contain git revision metadata, but as I can see, it's not accessible from within `default.nix`.

```bash
$ wget -q https://github.com/NixOS/patchelf/archive/master.tar.gz
$ gunzip < master.tar.gz | git get-tar-commit-id
2ba64817ec6f3b714503ea6e6aa8439505bb7393
```

**Comment by edolstra** [comment]
No, this is not possible since we unpack the tarball and discard the commit ID.
