### ISSUE TITLE
Option extra-sandbox-paths takes multiple paths divided by spaces

### ISSUE THREAD

**Issue by jakubgs** [NixOS/nix#3411]
# Description

Currently the `extra-sandbox-paths` can take multiple paths separated by spaces. This is problematic because when assembling options using for example bash scripts you can encounter option parsing issues.

# Example

Here's a script that calls `nix-build` with `--option extra-sandbox-paths` with multiple paths:
```sh
#!/usr/bin/env bash

FIRST_FILE=/tmp/first_file
SECOND_FILE=/tmp/seconf_file

nixOpts=(
  "--pure"
  "--option extra-sandbox-paths ${FIRST_FILE} ${SECOND_FILE}"
)

nix-build ${nixOpts[@]} default.nix
```
Which results in the following error:
```
error: syntax error, unexpected '=', expecting $end, at /tmp/seconf_file:1:X
```
If I try to quote them like this:
```
  "--option extra-sandbox-paths \"${FIRST_FILE} ${SECOND_FILE}\""
```
I get a different error:
```
error: getting status of '/tmp/second_file"': No such file or directory
```
The fact that the files in `extra-sandbox-paths` makes it very hard to use with scripts.

**Comment by edolstra** [comment]
Try something like this:
```
$ nixOpts=("--option" "extra-sandbox-paths" "/foo /bar")
$ nix-build "${nixOpts[@]}" ...
```
Note the quotes around `${nixOpts[@]}`, which ensures that the array is passed without word splitting.

**Comment by jakubgs** [comment]
Okay, that does work, but I still think that using a space as a divider in a multi-word option is bad.
You're just asking for trouble with this kind of format. A more sensible solution would be to make a flag append values if they are set multiple times, so that this works:
```sh
  "--option extra-sandbox-paths ${FIRST_FILE}"
  "--option extra-sandbox-paths ${SECOND_FILE}"
```
Or something similar.

**Comment by zimbatm** [comment]
It's not that simple. If the default is to append to the list then another syntax needs to be added to clear the original list.

**Comment by jakubgs** [comment]
Sure, make it `--option-append` or anything else. Up to you how this is fixed, but as I said, multi word option with space as a separator is just asking for trouble.

Appreciate your bash example.

**Comment by lheckemann** [comment]
This is far from being the only option in which spaces make sense — `builders` for example requires spaces to separate fields. If you must use bash, use shellcheck as well and it'll tell you about such quoting issues.

**Comment by lheckemann** [comment]
Fair to close again -- I think a misunderstanding of bash quoting isn't really a Nix issue and `nix --option extra-sandbox-paths "/foo /bar /baz"` is clear enough

**Comment by jakubgs** [comment]
I think it's fine to close this as this is not a major issue and more of a nitpick. But I do reiterate my point which I think still stands. Using spaces to separate values for CLI arguments is a bad practice in general and should be avoided if possible. Or at least an alternative separate should be available.
