### ISSUE TITLE
Support paths in nixosModules

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#3421]
In https://github.com/NixOS/nixpkgs/commit/64e5f4d53b2740bffb16641f703b9cf0df58b84e#diff-5451c7b5e2e1f7c50be271bf7a786c04L45-R45 we had to change `nixosModules.notDetected` from a path to an import. However, this prevents deduplication of the imports list. So it would be better to support paths in `nix flake check`.

**Comment by Artturin** [comment]
not stale

**Comment by Artturin** [comment]
Unnecessary since https://github.com/NixOS/nix/pull/7559
