### ISSUE TITLE
ca-references should not be experimental

### ISSUE THREAD

**Issue by lovesegfault** [NixOS/nix#3422]
Recently I started running into issues building my aarch64 systems on the community box. The community box is on 19.09, and I'm building systems on unstable. The error I get is the following:
```
experimental Nix feature 'ca-references' is disabled
```
Which in turn comes from this
https://github.com/NixOS/nix/blob/b816515f613b7013ba0d5489841568b8f666f224/src/libstore/local-store.cc#L1010

This is new behavior as I've been doing my system builds on that remote builder for a while now and never faced any issues. 

As of right now this blocks a few people, such as myself and @cleverca22  from successfully using the community box for testing our aarch64 system builds.

cc. @grahamc

**Comment by FRidh** [comment]
https://github.com/NixOS/nix/issues/3406

**Comment by edolstra** [comment]
Please specify what version of Nix you're running and how to reproduce this issue, otherwise it's hard to tell whether b816515f613b7013ba0d5489841568b8f666f224 fixes this.

**Comment by lovesegfault** [comment]
My system is on `nix (Nix) 2.3.3`, the aarch64 box is on `nix (Nix) 2.4pre7250_94c93437`

**Comment by xavierzwirtz** [comment]
Adding on my experience with this issue, something feels broken. I am trying to use `morph` to deploy a NixOS configuration to another machine over ssh, it is running this command:

`$ nix copy /nix/store/4lpq5ll946a7rp887i6qiw49pq1p61sq-nixos-system-hephaestus-20.09pre-git.drv --to ssh://hephaestus.birddogsw.local`

No matter what flags I put in my local nix.conf, I cant get it to stop throwing:
```
[4/0/22 copied (0.0/10.9 MiB)] copying path '/nix/store/lqhs7ai11dnd6djcq38674drdps0h7yv-options.xml.drv' to 'ssh://hephaest error: experimental Nix feature 'ca-references' is disabled
error (ignored): interrupted by the user
```

I then tried checking out b816515f613b7013ba0d5489841568b8f666f224 locally, and adding that nix to my `shell.nix`:

```
$ nix --version
nix (Nix) 2.4pre7289_b816515
$ nix copy /nix/store/4lpq5ll946a7rp887i6qiw49pq1p61sq-nixos-system-hephaestus-20.09pre-git.drv --to ssh://hephaestus.birddogsw.local
[4/0/22 copied (0.0/10.9 MiB)] copying path '/nix/store/lqhs7ai11dnd6djcq38674drdps0h7yv-options.xml.drv' to 'ssh://hephaest error: experimental Nix feature 'ca-references' is disabled
```

Same result. I then tried manually adding the experimental flags:
```
nix --experimental-features "nix-command ca-references"  copy /nix/store/4lpq5ll946a7rp887i6qiw49pq1p61sq-nixos-system-hephaestus-20.09pre-git.drv --to ssh://hephaestus.birddogsw.local
[4/0/22 copied (0.0/10.9 MiB)] copying path '/nix/store/lqhs7ai11dnd6djcq38674drdps0h7yv-options.xml.drv' to 'ssh://hephaest error: experimental Nix feature 'ca-references' is disabled
```

Same result.

**Comment by edolstra** [comment]
@xavierzwirtz Did you upgrade the remote machine as well? That's where the error message comes from.

**Comment by xavierzwirtz** [comment]
I eventually got it upgraded, error message has disappeared. I'm not sure if that's just because it doesn't need to copy the other derivations anymore though. Ill chime back in if my issue shows back up.

**Comment by roblabla** [comment]
I just hit this issue as well, running nix from the `nixpkgs/nix-unstable` docker image. Here's how to reproduce:

```
docker run  --rm -it nixpkgs/nix-unstable
nix --experimental-features "nix-command flakes" profile install 'nixpkgs#skopeo'
```
