### ISSUE TITLE
Can lists in Nix be infinite?

### ISSUE THREAD

**Issue by jameshfisher** [NixOS/nix#345]
The following expression is supposed to define the infinite list of natural numbers and evaluate to the element of that list at index 3, which should be the number `3`.

```
let
  natsFrom = n: [n] ++ natsFrom (n + 1);
  nats = natsFrom 0;
in
  builtins.elemAt nats 3
```

Instead I get a segmentation fault:

```
> nix-instantiate --eval foo.nix
[1]    78348 segmentation fault  nix-instantiate --eval foo.nix
```

I am assuming here that Nix lists are basically just syntactic sugar over sets; i.e. they are implemented under the hood something like this:

```
let
  natsFrom = n: { hd = n; tl = natsFrom (n + 1); };
  nats = natsFrom 0;
  elemAt = l: i: if i == 0 then l.hd
                           else elemAt l.tl (i - 1);
in
  elemAt nats 3
```

Is this not the case? Is the segmentation fault a bug? I didn't find the manual very clear on how exactly lists are _meant_ to behave in this situation.

**Comment by Infinisil** [comment]
Coming back to this, I'm doing some work on lazy attribute names in #4090. Once that is implemented, it will be very easy to also add support for lazy list indexing, allowing you to have infinite lists. In particular @jameshfisher's first example could work with this.
