### ISSUE TITLE
missing deps for perl/lib/Nix/Store.so

### ISSUE THREAD

**Issue by darealshinji** [NixOS/nix#346]
perl/lib/Nix/Store.so uses symbols from libnixutil, libperl and libpthread, but isn't linked against these libraries.
Re-linking it with this command resolves all the symbols:
```
g++ -o perl/lib/Nix/Store.so -shared \
	-Wl,-Bsymbolic-functions \
	-Wl,-z,relro -Wl,--as-needed \
	-Wl,--no-copy-dt-needed-entries \
	perl/lib/Nix/Store.o -Wl,-soname=Store.so \
	-Lsrc/libstore -lnixstore \
	-Lsrc/libutil -lnixutil -lperl -pthread
```

**Comment by domenkozar** [comment]
This appears to be fixed in https://github.com/NixOS/nix/commit/7d7b67986a1f9d78dccd0bd4ad811af7dc65f60f, reopen if issue persists.
