### ISSUE TITLE
Possible regression/behaviour change in master ⇒ path '/nix/store/...' is not in the Nix store

### ISSUE THREAD

**Issue by samueldr** [NixOS/nix#3471]
Hi!

I've been bisecting and looking for multiple hours about this issue.

With current master (a7540294cfae82c098e8691cd5212a9184add574) this minified reproduction case stops working. The nix version needs to be for the daemon (or I guess daemon-less), it happens at build time(?) and not during the evaluation.

 * https://gist.github.com/2778af8153e9a105d05474301d14f55a

```
these derivations will be built:
  /nix/store/7n2769bjh4n0rys7g632v94k4iq3wgn2-repro-1585890320.drv
building '/nix/store/7n2769bjh4n0rys7g632v94k4iq3wgn2-repro-1585890320.drv' on 'ssh://samuel@duffman'...
error: build of '/nix/store/7n2769bjh4n0rys7g632v94k4iq3wgn2-repro-1585890320.drv' on 'ssh://samuel@duffman' failed: path '/nix/store/x2zbwvaqhipkrbf1a2ab4jh94sp8ywl7-extra-utils-extra-utils/bin/sh' is not in the Nix store
builder for '/nix/store/7n2769bjh4n0rys7g632v94k4iq3wgn2-repro-1585890320.drv' failed with exit code 1
error: build of '/nix/store/7n2769bjh4n0rys7g632v94k4iq3wgn2-repro-1585890320.drv' failed
```

With 2.3 and 2.3.3 this is not an issue.

This issue is affecting the Mobile NixOS builds, [as experienced by @dguibert](https://github.com/NixOS/mobile-nixos/pull/89#issuecomment-606071684), and by myself.

* * *

### Observations

This exact error has been happening for a while during the previous git history. At one point the error message changes, I do not know if it is a red herring. It may be the same underlying issue, it may be two issues.

The other expected error:

```
these derivations will be built:
  /nix/store/vmdbakxcxyhahzj5k6jzfhr1pjzxykg5-repro-1585891064.drv
building '/nix/store/vmdbakxcxyhahzj5k6jzfhr1pjzxykg5-repro-1585891064.drv' on 'ssh://samuel@duffman'...
error: build of '/nix/store/vmdbakxcxyhahzj5k6jzfhr1pjzxykg5-repro-1585891064.drv' on 'ssh://samuel@duffman' failed: path 'sh' is not a store path
builder for '/nix/store/vmdbakxcxyhahzj5k6jzfhr1pjzxykg5-repro-1585891064.drv' failed with exit code 1
error: build of '/nix/store/vmdbakxcxyhahzj5k6jzfhr1pjzxykg5-repro-1585891064.drv' failed
```

Here's a brief overview of my observations:

 * a7540294cfae82c098e8691cd5212a9184add574 Current master
 * ...
 * 14d82baba4ebb82df28c2d4e9517f8c3a81d8f6c First with "not in the nix store"
 * 410acd29c046ae7296d882ee4750441d4ff29955 Last with "is not a store path"
 * ...
 * bbe97dff8b3054d96e758f486f9ce3fa09e64de3 First *buildable* commit with the "is not a store path" error
 * ...
 * a1ff43045b3f1d075c67c262ff6f623b2b5d569e Last working as expected commit

My intuition tells me the regression is from something between a1ff43045b3f1d075c67c262ff6f623b2b5d569e...bbe97dff8b3054d96e758f486f9ce3fa09e64de3, though as nix doesn't build with those it's hard to actively test.

> **NOTE**: c502831a1d087a406e80dede8cf14e3e97531006 is required on a bunch of these commits. Otherwise the build will hit that now solved issue. The error `failed: invalid file name 'closure-sh-0' in 'exportReferencesGraph` is fixed by this commit.

* * *

I am not discounting that it's possible that this is exercising a marginal behaviour, but this works for 2.3, likely previous versions too. This makes this either a regression **or** a breaking behaviour change.

If this is a breaking change, I'll need help in figuring out what is that marginal behaviour causing this failure, as I don't understand the issue. (And likely relevant release notes to be written.)

Don't hesitate to ask me for more details.

> Additional note: You will observe that I was using remote builds, the nix version was *only* updated on that remote builder (duffman.local) and my local Nix was 2.3.3. Though this was verified to fail when executed locally.

**Comment by puckipedia** [comment]
The issue seems to be that `exportReferencesGraph` probably no longer takes paths inside of a derivation. I'm not entirely sure this has ever been clearly defined behavior, and `contents` in `makeInitrd` also takes a `suffix` attribute specifically designed for use with paths inside of nix store inputs.. Nothing in nixpkgs uses this either, so I'm not surprised this fell through the cracks either way.

**Comment by dguibert** [comment]
Thx, I confirm that using a `suffix` doest not thrown the error and populates the initrd with a symlink for `/bin/sh`.

I've applied this to `repro.nix`:
````diff
     contents = [
-      { object = "${extraUtils}/bin/sh"; symlink = "/bin/sh"; }
+      { suffix= "/bin/sh"; object = extraUtils; symlink = "/bin/sh"; }
     ];
````

**Comment by samueldr** [comment]
Thanks for looking into it, @dguibert.

At least this would allow working around the change in Mobile NixOS, and it should be possible to handle this while keeping the same ergonomic design (by automatically adding suffix if missing and not in nix store, I guess).

Keeping this open until we have a proper answer as to whether it's the expected beahviour or not.

It would also be interesting to have a more proper error message, as the current one is not helpful; the given path *is* in the nix store.

**Comment by Ninlives** [comment]
Nix determines whether a path is in nix store by checking the parent directory is "/nix/store"
