### ISSUE TITLE
nix-rust should support cross-compiling 

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nix#3479]
We need to pass in `--target` to Cargo to cross-compile. An example of doing this with autoconf is here:

https://github.com/GNOME/librsvg/blob/42b621465dfecbff28131bcd62b593ff74cdfce4/configure.ac

and

https://github.com/GNOME/librsvg/blob/9127d84c7fa94c5e5663b267645d18eda3bed623/Makefile.am

/cc @Ericson2314

**Comment by domenkozar** [comment]
Also would benefit from static compilation support :)

**Comment by edolstra** [comment]
Closed via #3702.
