### ISSUE TITLE
nix-store can't export systemd closure: file has an unsupported type

### ISSUE THREAD

**Issue by clojurians-org** [NixOS/nix#3499]
i have some package have dependency on systemd package.

i want to export it, but it report "file has an unsupported type"

```
[op@my-200 nix]$ nix-store --export $(nix-store -qR /nix/store/4xn6z5k11ixb1sy278jn02bi40lh7aas-systemd-243.7) > larluo.closure
error: file '/nix/store/4xn6z5k11ixb1sy278jn02bi40lh7aas-systemd-243.7/example/systemd/user/systemd/notify' has an unsupported type

[op@my-200 nix]$ ls -l /nix/store/4xn6z5k11ixb1sy278jn02bi40lh7aas-systemd-243.7/example/systemd/user/systemd
total 0
srwxr-xr-x 1 root root 0 Mar 11 10:44 notify
srwxr-xr-x 1 root root 0 Mar 11 10:44 private

```

**Comment by domenkozar** [comment]
That's seems to be setuid. I'm really suprised as `/nix/store/4xn6z5k11ixb1sy278jn02bi40lh7aas-systemd-243.7/example/systemd/user/systemd` doesn't exist for me.

What's your Nix version?

**Comment by LnL7** [comment]
Yeah, I suspect something wrote to the output, try repairing it.

```
nix-store --repair-path /nix/store/4xn6z5k11ixb1sy278jn02bi40lh7aas-systemd-243.7
```

**Comment by clojurians-org** [comment]
> That's seems to be setuid. I'm really suprised as `/nix/store/4xn6z5k11ixb1sy278jn02bi40lh7aas-systemd-243.7/example/systemd/user/systemd` doesn't exist for me.
> 
> What's your Nix version? `nix-env --version`

```
[op@my-200 nix]$ nix-env --version
nix-env (Nix) 2.2.2

[op@my-200 nix]$ nix-channel --list
nixpkgs https://nixos.org/channels/nixos-20.03
```
