### ISSUE TITLE
nix repl :b - looking for a way to display full log

### ISSUE THREAD

**Issue by reactormonk** [NixOS/nix#3504]
When I'm building a derivation from the repl via `:b deriv`, the repl truncates the output, which makes debugging said derivation failure impossible. Is there a way to get access to that information, preferably from within the repl?

**Comment by edolstra** [comment]
There are two things we can do:

* Add a `:log <deriv>` command that invokes `nix log` to show the build log.
* Merge the progress indicator PR so you can interactively toggle whether to show logs for in-progress builds.

**Comment by nikp123** [comment]
This may be an inappropriate place to ask, but can we get a log that follows the build process when invoking ``:b`` in repl or something similar.
