### ISSUE TITLE
Does Nix 2 still use the binary-cache-url in channels?

### ISSUE THREAD

**Issue by Gabriel439** [NixOS/nix#3512]
In Nix 1, Nix would use the `binary-cache-url` included in channels as a substituter:

https://github.com/NixOS/nix/blob/e3128014dbef2f0cd172767ff8904d25f6efccbb/scripts/download-from-binary-cache.pl.in#L243

Specifically, all of the `/nix/var/nix/profiles/per-user/root/channels/binary-caches/*` files were automatically added as substituters.

Does Nix 2 still do so?  The reason I ask is that I ran into a situation where Nix 2 appeared to be ignoring this file completely.  I searched the Nix code and didn't find any logic for referencing the substituter included in the channel, so I wasn't sure if this omission was intentional or not.

This issue appears to be highly related to https://github.com/NixOS/nix/issues/1283.  In that issue the `nixpkgs` channel began to fail due to no longer incorporating the cached pointed to by the `binary-cache-url`.  However, the problem appears to have been masked by a change to hardcode `cache.nixos.org` as a default substituter in https://github.com/NixOS/nix/commit/4bb38591e591e3ef59f7881575ca1f28015a8c47, but as far as I can tell channels other than `nixpkgs` are still broken in the same way.

I ran across this issue because internally at work we create custom channels that specify a substituter that is not `cache.nixos.org` and the substituter appears to have begun being ignored when we upgraded to Nix 2.

I'll give an illustrative example of how I confirmed this empirically.  First, I verified that the substituter listed in the channel was functional (partially changed to anonymize some names):

```
$ cat /nix/var/nix/profiles/per-user/root/channels/binary-caches/awake 
http://example.com/prealpha-3.3.0/cache

$ curl http://example.com/prealpha-3.3.0/cache/nix-cache-info
StoreDir: /nix/store

$ curl http://example.com/prealpha-3.3.0/cache/99cpg8qvfwkcdhdl3svzl13rcixc5kwd.narinfo
StorePath: /nix/store/99cpg8qvfwkcdhdl3svzl13rcixc5kwd-example-0.1.0
URL: nar/0m8hgqr9bnvl6075z975lm7x3qglwl2sl77lb4jys0dfpsasgrfl.nar.xz
Compression: xz
FileHash: sha256:0m8hgqr9bnvl6075z975lm7x3qglwl2sl77lb4jys0dfpsasgrfl
FileSize: 1357300
NarHash: sha256:1ifz7dm1bs71d0m65h904sg6ajpnkbwdjkhgfa7745vzmj4pygff
NarSize: 7394792
References: 3s920c43pgzi6vdabjs90in308jnbckv-zlib-1.2.11 694q307rpfgbq5x5vhjfmrhpynvs2nk4-grpc-1.2.0-e2cfe9d 7gx4kiv5m0i7d7qkixq2cwzbr10lvxwc-glibc-2.27 cxiayilwj3ccnswhqmw00bhnnd0zfrcb-gmp-6.1.2 k03gfmngr1gcir94m5xzqrg9ignb77nd-libffi-3.2.1 zayl6yjayksyha5ndhxm6lmhr51i8sj6-ncurses-6.1-20190112
Deriver: 32v0cbcw0a0vvrlcn1i1sqxlqw7f8zff-example-0.1.0.drv
Sig: example-signing-key:xerao6bBGosvrK/4AMyyFotRIt+w/FhkgCJbcIWIgd3jGsakvSrI1YkaDL6BH7qDhH5OZwOoYc+8XtdOMzcTAg==

$ curl -O http://example.com/prealpha-3.3.0/cache/nar/0m8hgqr9bnvl6075z975lm7x3qglwl2sl77lb4jys0dfpsasgrfl.nar.xz
<Successfully downloads the NAR archive>
```

However, attempting to substitute the desired path fails and with verbose logging the substituter does not appear to have been checked:

```
nix-store --realise /nix/store/99cpg8qvfwkcdhdl3svzl13rcixc5kwd-example-0.1.0 -vvvvv
querying info about missing paths...
starting pool of 35 threads
don't know how to build these paths:
  /nix/store/99cpg8qvfwkcdhdl3svzl13rcixc5kwd-example-0.1.0
querying info about missing paths...
starting pool of 35 threads
substitution of '/nix/store/99cpg8qvfwkcdhdl3svzl13rcixc5kwd-example-0.1.0': created
substitution of '/nix/store/99cpg8qvfwkcdhdl3svzl13rcixc5kwd-example-0.1.0': woken up
entered goal loop
substitution of '/nix/store/99cpg8qvfwkcdhdl3svzl13rcixc5kwd-example-0.1.0': init
acquiring global GC lock '/nix/var/nix/gc.lock'
acquiring read lock on '/nix/var/nix/temproots/301640'
acquiring write lock on '/nix/var/nix/temproots/301640'
downgrading to read lock on '/nix/var/nix/temproots/301640'
substitution of '/nix/store/99cpg8qvfwkcdhdl3svzl13rcixc5kwd-example-0.1.0': trying next substituter
path '/nix/store/99cpg8qvfwkcdhdl3svzl13rcixc5kwd-example-0.1.0' is required, but there is no substituter that can build it
substitution of '/nix/store/99cpg8qvfwkcdhdl3svzl13rcixc5kwd-example-0.1.0': done
substitution of '/nix/store/99cpg8qvfwkcdhdl3svzl13rcixc5kwd-example-0.1.0': goal destroyed
error: build of '/nix/store/99cpg8qvfwkcdhdl3svzl13rcixc5kwd-example-0.1.0' failed
```

... but if I explicitly specify the substituter on the command line then things work:

```
nix-store --realise /nix/store/99cpg8qvfwkcdhdl3svzl13rcixc5kwd-example-0.1.0 --option extra-substituters 'http://example.com/prealpha-3.3.0/cache' 
these paths will be fetched (1.29 MiB download, 7.05 MiB unpacked):
  /nix/store/99cpg8qvfwkcdhdl3svzl13rcixc5kwd-example-0.1.0
copying path '/nix/store/99cpg8qvfwkcdhdl3svzl13rcixc5kwd-example-0.1.0' from 'http://localhost:8872/prealpha-3.3.0/cache'...
…
```

**Comment by Gabriel439** [comment]
@shlevy pointed me towards this commit:

https://github.com/NixOS/nix/commit/88571219d97f2bdfdbafcff25ef6ee424b0b008f

... so this omission appears to be intentional

**Comment by edolstra** [comment]
Right, it's no longer supported.

**Comment by Gabriel439** [comment]
Alright, then I'll close this.
