### ISSUE TITLE
Bug? Using many binary caches slows down every build

### ISSUE THREAD

**Issue by NorfairKing** [NixOS/nix#3515]
I'm using ~15 cachix caches and three more local ones on top of the public nixos cache.
This slows down every build _a lot_.
Could the caches be tried in parallel instead?

**Comment by dhess** [comment]
See https://github.com/NixOS/nix/issues/3019

**Comment by NorfairKing** [comment]
@dhess Yes it could be considered a duplicate issue but that one is phrased as a "possible improvement" and this on as a "bug".

**Comment by edolstra** [comment]
"Slow" is not a bug though :-)
