### ISSUE TITLE
`out` is not declared in `.attrs.sh` with `__structuredAttrs`

### ISSUE THREAD

**Issue by PkmX** [NixOS/nix#3525]
Currently the output paths can only be accessed via the `outputs` array a la `${outputs[out]}`, so existing builders that use `$out` will fail. Is this the intended behavior?

**Comment by edolstra** [comment]
Yes.

**Comment by PkmX** [comment]
Understood.

For those who may stumble upon this: you can add the environment variable back by adding `out = builtins.placeholder "out"` for each output path into the derivation.
