### ISSUE TITLE
nix-env -e silently ignores errors

### ISSUE THREAD

**Issue by rkoe** [NixOS/nix#3531]
**Problem**

If an invalid package name is given to `nix-env -i` or `nix-env -u`, an error-message is printed and nix-env exits with an exit-code !=0.

But `nix-env -e` silently ignores invalid package names, and always exits with exit-code 0.
But silently ignoring errors is a bad idea.

**Solution**

- Print an error-message for each invalid/not installed package, given to `nix-env -e`.
- Exit with exit code != 0, if there was any error.

**Comment by edolstra** [comment]
IIRC, this is by design: the postcondition of `nix-env -e foo` is that there is no package named `foo` in the profile, so it's not an error if there is no `foo`. (In other words, `nix-env -e foo` is idempotent.)
