### ISSUE TITLE
Remove "EXPERIMENTAL" note

### ISSUE THREAD

**Issue by kolloch** [NixOS/nix#3567]
The `nix` command help always ends with this note:

"Note: this program is EXPERIMENTAL and subject to change."

`nix` 2 has been around for a while and I am wondering if this has staid in by accident or on purpose. 

The problem is that this note actively encourages people using the old command line tools since they are stable. I think that the community would benefit by migrating to one set of "standard" command line utilities.

**Describe the solution you'd like**

If it is left around on purpose, I think it would be good to be more specific and only mark options that are likely to change as experimental.

Otherwise, remove the note and commit to the interface.

**Comment by edolstra** [comment]
No, it's still experimental and subject to change. (In fact, the entire `nix` command is now hidden behind an experimental feature flag.)

**Comment by 7c6f434c** [comment]
>`nix` 2 has been around for a while and I am wondering if this has staid in by accident or on purpose. 

I think there was a very recent major rename of a couple of `nix` subcommands, though.

**Comment by edolstra** [comment]
Right, and there are a couple more incoming (e.g. moving all hash-related commands into `nix hash <subcommand>`.

**Comment by LnL7** [comment]
Note, the nix cli is already used in a number of places. The experimental subcommands completely broke ofborg deployment for example https://github.com/NixOS/nixpkgs/blob/40e863aeb31b74c84bac424d178d8ca30675522e/nixos/modules/services/misc/nix-daemon.nix#L514.

For reference, here's something similar I did for darwin but without depending on the new cli. Not very nice bit it works https://github.com/LnL7/nix-darwin/blob/f885aff4c9efca0dcb553fec9a5029f4995adb30/modules/nix/default.nix#L450

**Comment by kolloch** [comment]
Okay, thanks for getting back to me. I fear their might be quite some references out there to the "new" CLI despite the warning. E.g. the "Nix manual" itself:

https://nixos.org/nix/manual/#chap-distributed-builds

It would be unfortunate if these commands broke.

Anyways, looking forward to the stable versions!
