### ISSUE TITLE
install-nix script installs nixpkgs-unstable by default

### ISSUE THREAD

**Issue by prusnak** [NixOS/nix#3575]
While experimenting with `nixos/nix` docker container I found out that `install-nix-from-closure.sh` automatically adds nixpkgs-unstable channel by default, because of the following:

https://github.com/NixOS/nix/blob/672985531c6b9481f8eb8210a17328dfc2515c9b/scripts/install-nix-from-closure.sh#L132-L135

This channel automatically becomes part of the docker image. This can be fixed easily (see my patch in https://github.com/NixOS/docker/issues/18), but I am raising a question whether this is really desired to have this automatically installed.

I personally think the addition of the channel(s) should happen manually and not automatically.

**Comment by prusnak** [comment]
If adding a nixpkgs-channel is really desired by default, we could at least provide a way how to skip this step via an environment variable.

**Comment by domenkozar** [comment]
@prusnak you're welcome to open a PR :)

**Comment by prusnak** [comment]
PR in https://github.com/NixOS/nix/pull/3588
