### ISSUE TITLE
nix-shell: Broken Backspace

### ISSUE THREAD

**Issue by dsxmachina** [NixOS/nix#3589]
Hello wonderful nix-people :)

I encountered a pretty weird bug, which happens on Ubuntu 18.04 and my ArchLinux.

I installed nix for a single user following these steps (https://nixos.org/nix/manual/#ch-installing-binary) and almost everything works as expected: I can build derivations of my software and drop into a nix-shell for development.

However, inside the nix-shell, i can neither use backspace to delete stuff i have typed nor can i use the left-arrow key.
Whenever backspace is hit, sometimes it does a space, sometimes a larger gap (like a tabstop).

As said, this happens on Ubuntu 18.04 (arm64) and ArchLinux (x64).
Using normal bash as a shell (to start nix-shell) - so nothing fancy here.

Everything else works as expected and I am able to use nix as intended. 
So no Killer-Bug, but it's annoying to retype every command after a small typo.

**Comment by bew** [comment]
Which terminal are you using? (urxvt/kitty/alacritty/xterm/....)

**Comment by dsxmachina** [comment]
I am using urxvt

**Comment by dsxmachina** [comment]
It seems to be a problem related with urxvt.
If i use xterm, everything works fine

**Comment by bew** [comment]
I also have the same problem, arrow keys, Ctrl-u, Ctrl-l keys does not work in urxvt.

This seems to be a terminfo issue, since it can be worked around by using a different TERM entry.
For exemple if you write `export TERM=xterm` in the opened nix-shell, or even before like `TERM=xterm nix-shell ...` the keys will work.

:warning: Beware that using a TERM value that is not the one for your terminal may break some other features of the terminal but for the limited testing I did, it works ok.

FTR the urxvt TERM is `rxvt-unicode-256color`, which points to the file `/usr/share/terminfo/r/rxvt-unicode-256color` (found using `infocmp`)
Maybe a bash limitation of some sort? or something else?

**Comment by zoranbosnjak** [comment]
I have noticed possibly related problem, just as weird. In my case, there is no problem with backspace, but inside *some* nix shell environments, some other keystrokes don't work as expected.

For example, if I hit `Alt Gr - e` which is suppose to give me the `€` sign, the cursor jumps to the start of the string (same as `Home`). For some other keystrokes, like `čšžß...`, nothing happens.

I am using `ubuntu 20.04` with slovenian keyboard layout, nix version 2.3.7.

This is my test `shell.nix` file with 2 environments:

```nix
{ pkgs ? import <nixpkgs> {}}:

let
  inherit (pkgs) haskellPackages;

in
  { env1 = haskellPackages.base-prelude.env;
    env2 = pkgs.stdenv.mkDerivation {name = "env"; buildInputs = [];};
  }
```
Here are the test results:
* `nix-shell -A env1` - it works as expected (I can use all keystrokes normally, just like outside of nix-shell)
* `nix-shell -A env2` - some keystrokes don't work
* `nix-shell -p hello` - some keystrokes don't work

In my case, I am getting the same result, regardless of the terminal (xterm, terminator, plain console - without X...).

@domenkozar do you have any issue with slovenian keyboard layout? Could you please run the same test in your environment? Any idea why haskell shell environment is different (correct) in this case?

**Comment by domenkozar** [comment]
What is the value of `$LOCALE_ARCHIVE` in these environments?

**Comment by zoranbosnjak** [comment]
The value of `$LOCALE_ARCHIVE` is as follows:

* `nix-shell -A env1` it is `/nix/store/1xpr86xg998h5acn4zqrx58xjdjqnnds-glibc-locales-2.31/lib/locale/locale-archive`
* outside of nix-shell it is empty
* `nix-shell -A env2` it is empty
* `nix-shell -p hello` it is empty
