### ISSUE TITLE
No Nix Channels listed with nix-channel when installing on MacOS 

### ISSUE THREAD

**Issue by ssbothwell** [NixOS/nix#3595]
**Describe the bug**

I've installed nix on MacOS 10.15.3 as per [these instructions](https://github.com/NixOS/nix/issues/2925#issuecomment-539570232). Nix seems to be working fine however I have no channels listed when I run `nix-channel --list` or `sudo nix-channel --list` and thus cannot tell what ci.

I nuked my nix installation and reinstalled and had the same result.

**Steps To Reproduce**

1. Install nix on MacOS Catalina.
2. Check nix channels

**Expected behavior**

I would expect a nix-channel to be listed.

**`nix-env --version` output**

```
$ nix-env --version
nix-env (Nix) 2.3.4
```
**Additional context**

```
➜ sudo nix-channel --list
~ on ☁️  us-west-1
➜ nix-channel --list
~ on ☁️  us-west-1
```

```
$ nix-shell -p nix-info --run "nix-info -m"
these paths will be fetched (0.01 MiB download, 0.03 MiB unpacked):
  /nix/store/mzqa3j35q4r8sicp22cdq15h2182dngb-DarwinTools-1
  /nix/store/psk4bsksggsyy3avx28sga5qpzn7q8kz-nix-info
copying path '/nix/store/mzqa3j35q4r8sicp22cdq15h2182dngb-DarwinTools-1' from 'https://cache.nixos.org'...
copying path '/nix/store/psk4bsksggsyy3avx28sga5qpzn7q8kz-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.3.0, macOS 10.15.3`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.4`
 - channels(root): `"nixpkgs-20.09pre226107.62e866e4fd6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

```
➜ cat /nix/var/nix/profiles/per-user/root/channels/manifest.nix
[ { meta = { }; name = "nixpkgs-20.09pre226107.62e866e4fd6"; out = { outPath = "/nix/store/fr4xpxfy7ywdp6ddkdl39yalhkpckp0s-nixpkgs-20.09pre226107.62e866e4fd6"; }; outPath = "/nix/store/fr4xpxfy7ywdp6ddkdl39yalhkpckp0s-nixpkgs-20.09pre226107.62e866e4fd6"; outputs = [ "out" ]; system = "x86_64-darwin"; type = "derivation"; } ]%
```

**Comment by domenkozar** [comment]
```
 - channels(root): `"nixpkgs-20.09pre226107.62e866e4fd6"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

Try running `nix-channel` as root, not via sudo.

**Comment by ssbothwell** [comment]
Ahh thank you, that shows the channel:
```
➜ sudo su
Password:
sh-3.2# nix-channel --list
nixpkgs https://nixos.org/channels/nixpkgs-unstable
sh-3.2#
```
Is this expected behavior on macOS?

**Comment by Anton-Latukha** [comment]
It most cases with Nix tooling it is more consistent to use `sudo -i` for this, as it would properly elevate into `root` and simultaniously load throuh the standartized login process and so the profile modifications Nix currently does for users.
As it is also actively promoted by Nix to not use `root`.

Case of latest Nix multiuser install on Ubuntu 20.04:
```shell
sudo su
nix-channel --list
nix-channel: command not found
echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
# Straigh drop into root - does not work and PATH is not augmented with Nix additions
exit

sudo -i nix-channel --list
nixpkgs https://nixos.org/channels/nixpkgs-unstable
```

I recommend using `sudo -i` to load the env properly and consistently for Nix tooling commands.
