### ISSUE TITLE
question: why operations on nix-env are done using --flag like syntax

### ISSUE THREAD

**Issue by kolokd** [NixOS/nix#3599]
Instead of sub commands like how  `git` or `go` does

why this
```
nix-env --install
```
instead of this
```
nix-env install
```

**Comment by kolokd** [comment]
hi, response

**Comment by edolstra** [comment]
Because the `nix-env` command was roughly modelled after `rpm` (hence `nix-env -e` for uninstalling packages).

**Comment by kolokd** [comment]
we are doomed

**Comment by zimbatm** [comment]
@kolokd nix-env will be replaced by the new `nix` CLI once it's ready and solve this.

**Comment by edolstra** [comment]
BTW this is an issue tracker, not a place for asking questions. Please use Discourse or IRC for that.
