### ISSUE TITLE
flakes: incorrectly rejects valid Git branch/tag names

### ISSUE THREAD

**Issue by emilazy** [NixOS/nix#3612]
**Describe the bug**

Nix on the `flakes` branch incorrectly rejects Git ref names with `/` in them.

**Steps to reproduce**

```
emily@renko ~> nix build --no-link 'github:NixOS/nixpkgs?ref=pull/88692/head'#pkgsMusl.libusb1
error: GitHub URL 'github:NixOS/nixpkgs?ref=pull/88692/head#pkgsMusl.libusb1' contains an invalid branch/tag name
```

**Expected behaviour**

Nix should accept everything the GitHub API/`git fetch` does; https://api.github.com/repos/NixOS/nixpkgs/commits/pull/88692/head works, so this should too.

**Comment by bqv** [comment]
It's fairly obvious why this bug came to be, is the intention to fix it or leave it as a known limitation? As I see it, solving it may end up overcomplicating some grammars but it is slightly unacceptable.

**Comment by jbaum98** [comment]
I think there's been a regression here:
```sh
$ ./result/bin/nix build --no-link 'github:NixOS/nixpkgs?ref=pull/88692/head'#pkgsMusl.libusb1
error: --- BadURL ------------------------------------------------ nix
URL 'github:NixOS/nixpkgs?ref=pull/88692/head#pkgsMusl.libusb1' contains an invalid branch/tag name

$ ./result/bin/nix --version
nix (Nix) 3.0pre20200806_6146447
```
