### ISSUE TITLE
Partial download of fetchurl

### ISSUE THREAD

**Issue by junjihashimoto** [NixOS/nix#3627]
**Is your feature request related to a problem? Please describe.**
When cache size is GB or TB, download becomes slow.
This is because the limitation of hash calculation on single core is the bottleneck of download.
See  https://github.com/minio/sha256-simd.
Single core's hash rate of avx2 is 448.62MB/sec.
Even if we use network-interface of 10Gbps or 100GBps, download does not get faster.

**Describe the solution you'd like**
We need to split both the file and its hash to speed it up.
I want the feature of partial download in fetchurl-function.

**Comment by tomberek** [comment]
A hacky solution i've used to make this better:
```
 fetchurlChunked = { chunksize, chunknum, hashes, url, ... }@args:
    with lib;
    let
      fetchurlArgs = removeAttrs args [ "chunksize" "chunknum" "hashes" ];
      i = range 0 (chunknum - 1);
      d = i:
        let
          min = toString (i * chunksize);
          max =
            if i == chunknum then "" else toString ((i + 1) * chunksize - 1);
        in pkgs.fetchurl ({
          name = baseNameOf url + "-" + (toString i);
          sha256 = builtins.elemAt hashes i;
          curlOpts = "-H Range:bytes=${min}-${max} ";
        } // fetchurlArgs);
    in map d i;
```
