### ISSUE TITLE
Nix installation script for macOS depends on xz, which is no longer available

### ISSUE THREAD

**Issue by jwiegley** [NixOS/nix#3647]
The Nix installation instructs users to run:

```
curl https://nixos.org/nix/install | sh
```

This script uses `xz` to unpack the tarball after downloading, but `xz` is no longer available on freshly installed Catalina systems.

**Comment by cole-h** [comment]
I believe this will be solved when https://github.com/NixOS/nix/pull/3632 makes its way into a release. It has already been merged -- just waiting on 2.3.6 to release, whenever that happens.

**Comment by domenkozar** [comment]
@edolstra plans to release 2.3.6 to address this soon.

**Comment by edolstra** [comment]
Yes, 2.3.6 is out now.
