### ISSUE TITLE
Installer inconsistent with published docs

### ISSUE THREAD

**Issue by dmnd** [NixOS/nix#3665]
**Describe the bug**

Trying a clean install on macOS Catalina.

**Steps To Reproduce**

```
% sh <(curl -L https://nixos.org/nix/install) --daemon

Note: a multi-user installation is possible. See https://nixos.org/nix/manual/#sect-multi-user-installation

Installing on macOS >=10.15 requires relocating the store to an apfs volume.
Use sh <(curl https://nixos.org/nix/install) --darwin-use-unencrypted-nix-store-volume or run the preparation steps manually.
See https://nixos.org/nix/manual/#sect-macos-installation
```

But then when I try to go to https://nixos.org/nix/manual/#sect-macos-installation, it doesn't exist. It seems like those docs exist [in master](https://github.com/NixOS/nix/blob/master/doc/manual/installation/installing-binary.xml#L151) but are not published?

**Expected behavior**

I expected the docs to be published on the web, but they're only present in the manual source.

**Comment by LnL7** [comment]
Caused by https://github.com/NixOS/nixos-homepage/issues/432.

**Comment by iwahbe** [comment]
FYI: when the installer is run with `--darwin-use-unencrypted-nix-store-volume` it gives a warning with the same link:
```
...
Creating mountpoint for /nix...
Creating a Nix Store volume...
warning: boot volume is FileVault-encrypted, but the Nix store volume
         is only encrypted at rest.
         See https://nixos.org/nix/manual/#sect-macos-installation
Will export new APFS Volume "Nix Store" from APFS Container Reference disk1
...
```

**Comment by steshaw** [comment]
The link looks fine now:

https://nixos.org/nix/manual/#sect-multi-user-installation

Perhaps this issue can be closed?

**Comment by abathur** [comment]
Yes; this can be closed.
