### ISSUE TITLE
Document creation of channels

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nix#367]
Currently there is no documentation how to setup custom channel with binary cache. Adding some narrative documentation should help users to start rolling their own channel.

**Comment by sbourlon** [comment]
Did the document popped up? I succeeded to create a channel myself by serving the files `binary-cache-url` and `nixexprs.tar.xz` by nginx running in Docker.

However, I deleted some directories in `pkgs/` like `applications/` and `nix-env` didn't like it. I guess I should update my `pkgs/top-level/all-packages.nix` but it's a lot of work to do manually. So I would be very interested in this document!

**Comment by szakib** [comment]
I am here 3.5 years after the original question and searching for the solution to this problem still yields **nothing on the whole wide internet**. It would be great if you could give an example. I suspect that serving a Nix channel is pretty simple, but I cannot get the details right on both server and client, just keep getting uninformative "invalid channel URL" messages at every try.

**Comment by edolstra** [comment]
Closing because channels will be deprecated. Also, the nix-channel manpage does describe the channel format.
