### ISSUE TITLE
The release process is not clear

### ISSUE THREAD

**Issue by knl** [NixOS/nix#3679]
I could not find any document that describes what goes in a particular release of Nix. I think this would be quite useful for everyone using Nix.

The background is that there were some PRs merged in master, which I was hoping to see in the last release, yet neither is there. Thus, it is not clear to me how something goes from the master branch into any of the releases. In addition, there is no changelog in the repository, outlining the changes in the particular release.

To summarize, it would be good to have a document that describes how releases are done in this project, and what those contributing to Nix could expect.

For reference, Terraform project has: https://github.com/hashicorp/terraform/blob/master/docs/maintainer-etiquette.md (which doesn't spell it out, but implies that all stuff from master ends up in the next release). Rust has something similar (yet, overly verbose): https://rustc-dev-guide.rust-lang.org/walkthrough.html, with tl;dr that anything merged will end up in nightly, and then after a while be promoted to the release.

**Comment by edolstra** [comment]
Releases are done from a release branch (e.g. `2.3-maintenance`), not from master. The last major release was 2.3 which was in september, so unless somebody cherry-picked those PRs to the maintenance branch, they won't be in a release yet.

There is a changelog, see doc/manual/release-notes. However it usually doesn't get updated for point releases since those should only contain bug fixes.

**Comment by knl** [comment]
Thanks @edolstra.

I understand now that only bug fixes go into the maintenance releases. Is it ok that all bug-fixes go there, or is there a criteria these fixes need to satisfy (beside the obvious that they need to be applicable to the code in the maintenance release :))? Who/how do we decide what goes in?

**Comment by edolstra** [comment]
Yes, in principle all bug fixes are fine. If you want to propose a bug fix backport, just open a `git cherry-pick -x` PR against the maintenance branch.
