### ISSUE TITLE
nix copy builds drv files

### ISSUE THREAD

**Issue by dasJ** [NixOS/nix#3696]
**Describe the bug**

`nix copy` is supposed to copy full closures and not build anything.
However, it does build stuff when copying drv files.

**Steps To Reproduce**

1. Create `broken.nix` with
```nix
derivation {
  name = "test";
  system = "x86_64-linux";
  builder = "this will error";
}
```
2. `nix copy $(nix-instantiate broken.nix) --to ssh://a-string-that-does-not-matter`

**Expected behavior**

The file should just be copied.

**`nix-env --version` output**

nix-env (Nix) 2.4pre20200521_00b562c

**Additional context**

cc @ajs124

**Comment by dasJ** [comment]
Doubt anyone will ever change their decision on this "design choice".

**Comment by edolstra** [comment]
FYI, `nix copy` has a flag `--derivation` to copy the derivation rather than its outputs.

**Comment by ajs124** [comment]
```bash
        drvFlag=""
        if [[ "${storePath}" == *\.drv ]]; then
            drvFlag="--derivation"
        fi
        nix store sign --key-file "${key}" $drvFlag "${storePath}" || continue
        nix copy --to "${url}?compression=none" $drvFlag "${storePath}"
```
This is what's needed because of this design decision
