### ISSUE TITLE
zsh/bash/... completion for nix* commands

### ISSUE THREAD

**Issue by chaoflow** [NixOS/nix#37]
It would be great if there would be shell completion for all nix commands, like:

```
% git a<TAB>
add         -- add file contents to index
ai          -- alias for 'add -i'
am          -- apply patches from a mailbox
ap          -- alias for 'add -p'
apply       -- apply patch to files and/or to index
archimport  -- import an Arch repository into git
archive     -- create archive of files from named tree
```

**Comment by iElectric** [comment]
:+1:

**Comment by bjornfor** [comment]
I'd _really_ like to have completion for attributes: "nix-env -iA nixos.TAB_TAB" :-)

**Comment by olejorgenb** [comment]
There is a package for zsh completions now: http://github.com/spwhitt/nix-zsh-completions (`nix-env -iA nix-zsh-completions`)

Also: https://github.com/spwhitt/nix-zsh-completions/pull/3  (WIP on attribute completions)

**Comment by joelmo** [comment]
Before someone do it for bash you should now there is interest redesigning the command interface, https://github.com/NixOS/nix/issues/779.

**Comment by olejorgenb** [comment]
Hopefully not spammy:  A working attribute path completion for zsh is at https://github.com/spwhitt/nix-zsh-completions/pull/4

Paths are completed most places where it makes sense. eg. `nix-env -i --file local.nix -A`, `nix-shell '<nixpkgs>' -A`, etc.

spwihitt haven't responed yet, but I've used it for a while myself without major problems. It would be nice if someone wanted to test it to weed out possible bugs before it's (hopefully) merged.

**Comment by olejorgenb** [comment]
New version of nix-zsh-completions (with attribute path completion) is now in master: https://github.com/NixOS/nixpkgs/pull/21331

**Comment by olejorgenb** [comment]
@hedning has implemented completions for bash too (**including** the new `nix` commands): https://github.com/NixOS/nix/issues/1658#issuecomment-343415285

**Comment by lheckemann** [comment]
This is done now, no? Suggest close.

**Comment by hedning** [comment]
From 18.03 and forward [nix-bash-completions](https://github.com/hedning/nix-bash-completions) will be installed when `programs.bash.enableCompletion` is turned on, so I'd also suggest closing this.

There's a question of how to make completion work out of the box when using Nix on non-NixOS systems, but that's another issue.
