### ISSUE TITLE
Integrate nix-bundle into new Nix command

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nix#3705]
With the new "app" installables in the flakes branch, we have a way to keep track of program entry points. This seems like it would be a great fit for a "bundle" or "pack" command in Nix.

I think lots of inspiration can come from how guix pack works: https://hpc.guix.info/blog/2020/05/faster-relocatable-packs-with-fakechroot/.

guix has three "execution engines":

- unprivileged user namespaces (like in nix-bundle)
- PRoot (ptrace-based)
- Fakechroot (LD_PRELOAD-based)

We may also want to support different bundle formats, like:

- Docker / OCI
- Arx (used for nix-bundle)
- AppImage (uses squashfs)
- VirtualBox image

Most of these would have to link in Nixpkgs somehow, to get the right tools, which may be a little tricky.

**Comment by edolstra** [comment]
A `nix bundle` command can get stuff from Nixpkgs using the `nixpkgsFlakeRef()` function added by @mkenigs to get `bashInteractive` in `nix develop`. (We can also use this to get `git` in `fetchGit`, etc.)

**Comment by zimbatm** [comment]
What if the bundle was just a nix function applied over a derivation?
```
nix bundle nixpkgs.myApp --function nixpkgs.mkDockerImage
```
That would keep most of the logic out of nix and allow us to compose things in the nix code as well.
