### ISSUE TITLE
fork: retry: resource temporarily unavailable

### ISSUE THREAD

**Issue by rodarima** [NixOS/nix#3717]
I just found that systemd has a limit on the number of tasks created by a unit imposed by default in /etc/systemd/system.conf (in our cluster) to:

```
...
#DefaultTasksMax=512
...
```
Therefore, when building large packages (OpenMPI 4.0.3) in parallel leads to the following fork error:

```fork: retry: resource temporarily unavailable```

I didn't found any information about this, but seems to be solved by setting TasksMax to infinity in the nix-daemon service override:

```
[Service]
TasksMax=infinity
```
Maybe worth adding it by default? Or mention it in the manual.

This problem doesn't trigger if the installation is in single user mode (not using the daemon), as the build is not controlled by a systemd unit cgroup, so only ulimits seem to have any effect.

**Comment by RocketPuppy** [comment]
I'm seeing this behavior after running 20.03 for a while uninterrupted, usually after a couple of days. I'm not sure it's related to building packages or even systemd. How would I go about further troubleshooting this?
