### ISSUE TITLE
 nix-instantiate --eval --json gives error: cannot convert a function to JSON

### ISSUE THREAD

**Issue by nixinator** [NixOS/nix#3722]
nix-instantiate --eval --json

gives
error: cannot convert a thunk to JSON

or

error: cannot convert a thunk to JSON

**Steps To Reproduce**
```
nix-instantiate --eval --json  -E '
# This imports the nix package collection,
# so we can access the `pkgs` and `stdenv` variables
with import <nixpkgs> {};
stdenv.mkDerivation {
  name = "my-environment";

  buildInputs = [
    pkgs.cowsay
  ];
}'
```

error: cannot convert a thunk to JSON

with other nix code you get 

error: cannot convert a function to JSON

**Expected behavior**

output a json formatted derivation.

**`nix-env --version` output**

nix-env (Nix) 2.3.6
and
nix-env (Nix) 2.3.4

**Additional context**

nix-instantiate --eval --xml  ... seems to out XML.

has this been relaced with the new nix eval ?????

**Comment by matthewbauer** [comment]
you can do:

```
nix show-derivation $(nix-instantiate -E 'with import <nixpkgs> {};
stdenv.mkDerivation {
  name = "my-environment";

  buildInputs = [
    pkgs.cowsay
  ];
}')
```

for json

**Comment by nixinator** [comment]
Yep, that seems to the trick.  | jq looks very nice.

nix-instantiate --eval --json , does it need to be removed? or print..

'have you tried 'nix show-derivation' instead ... have a nice day'

**Comment by nixinator** [comment]
Maybe this will go away when the older nix-* commands go away, and are replace with the newer 'nix' command.

**Comment by UlyssesZh** [comment]
When `result` is a thunk, one can use `builtins.deepSeq result result` to convert it to a set. Another workaround is to use `builtins.toJSON` in the expression and `--eval --raw` in the command line because `builtins.toJSON` accepts a thunk.

**Comment by UlyssesZh** [comment]
Just stumbled upon this. Why close? This should still be considered a bug.
