### ISSUE TITLE
nix-store --import and nix copy run out of memory

### ISSUE THREAD

**Issue by ivantomac** [NixOS/nix#3735]
**Describe the bug**
I've previously raised this in the nixpkgs repository: https://github.com/NixOS/nixpkgs/issues/82645
I'm happy to close the other ticket if this one is more appropriate and it occurred to me it might be since the problem is with nix.

I have a number of computers in the network, most have between 8 and 16GB RAM. I have the same NixOS setup on all of them, or try to, and usually download/install packages on one, then copy them across to the other ones.

I was using `nix-copy-closure` to copy the nix store between different computers and that worked initially. Then I started getting out of memory errors. First on a 2GB netbook and later on computers with 8GB and even 16GB of RAM.
I switched to using `nix copy` and later `nix-store --export`. Neither fixed the problem.

Well the export goes ok, specifically `nix-store --export $(nix-store -qR /run/current-system)`. The resulting closure is about 73GB in size.
When I try to import it on a 8 core/16 thread Ryzen with 16GB RAM, it runs out of memory. Current workaround is to run `nix-copy-closure` to copy the remaining missing paths.

**Steps To Reproduce**
1. On the source machine I run:
`nix-store --export $(nix-store -qR /run/current-system) > system.closure`
2. And then on the target machine:
`nix-store --import < system.closure`

**Expected behavior**
I expect the closure to be imported without any errors if the computer meets some minimum requirements for running nix.

**Actual behavior**
```
$ nix-store --import < system.closure 
error: out of memory
```

**`nix-env --version` output**
```
$ nix-env --version
nix-env (Nix) 2.3.5
```

**Additional context**
I suspect nix is choking on large packages. Specifically things like Xilinx, Altera and Lattice FPGA development kits.
And on a 2GB netbook it was choking well before I installed any large packages. I'd like to be able to use NixOS on it but right now I can't because of this problem.

**Comment by domenkozar** [comment]
See #1681 #358
