### ISSUE TITLE
[flakes] How to use nix run with nixpkgs git checkout

### ISSUE THREAD

**Issue by Mic92** [NixOS/nix#3745]
**Describe the bug**

In the old nix I was able to do this:

```
 $ nix run nixpkgs.sieve-connect -c sieve-connect
```

Now it seems impossible to get nixpkgs imported from a git checkout.

```
╭─[~/git/nixpkgs]─[master]
╰─ % nix run -I nixpkgs=$pwd --expr 'with import <nixpkgs> {}; sieve-connect' sieve-connect
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I), at (string):1:13

╭─[~/git/nixpkgs]─[master]
╰─ % nix run  --expr 'with import ./. {}; sieve-connect' sieve-connect
error: access to path '/home/joerg/git/nixpkgs' is forbidden in restricted mode

╭─[~/git/nixpkgs]─[master]
╰─ % nix run --impure --expr 'with import ./. {}; sieve-connect' sieve-connect
error: attribute 'sieve-connect' in selection path 'sieve-connect' not found

╭─[~/git/nixpkgs]─[master]
╰─ % nix run --impure --expr 'with import ./. {}; pkgs.sieve-connect' sieve-connect
error: attribute 'sieve-connect' in selection path 'sieve-connect' not found
```

The only thing that worked was

```
$ nix run 'nixpkgs#sieve-connect' sieve-connect
```

However this option does not allow to test nixpkgs. 

**Expected behavior**

A way to load nix expression locally.
I think some other commands such as `nix eval` suffer from the same problem.

**`nix-env --version` output**

**Additional context**

**Comment by Kloenk** [comment]
Maybe I misunderstand. You should be able to just run this to use the local checkout of nixpkgs

~~~
nix run .#sieve-connect -c sieve-connect
~~~

(I think nix run got renamed to nix shell.)

**Comment by Mic92** [comment]
Ok. `nix shell -f '<nixpkgs>' sieve-connect -c sieve-connect` does what I want.

**Comment by Mic92** [comment]
The following says:

```
$ nix run .#sieve-connect sieve-connect
error: flake 'git+file:///home/joerg/git/nixpkgs' does not provide attribute 'sieve-connect'
```

I assume it requires something specified in flakes.
