### ISSUE TITLE
experimental Nix feature 'nix-command' is disabled

### ISSUE THREAD

**Issue by Fresheyeball** [NixOS/nix#3753]
**Describe the bug**

When using current `master` (below at time of reporting)

```
  nix-src = pkgs.fetchFromGitHub
   { owner = "NixOS";
     repo = "nix";
     rev = "b7ccf7ae2af3d7eaf3696358ecbbce5a2bcfe652";
     sha256 = "1l9z5g7qrc849n3xclm3fz54wawk2vh917cfa09wd41n008iajh2";
   };
```

```
nix.package = (import "${nix-src}/release.nix" {
    nix = nix-src;
    nixpkgs = <nixpkgs>;
    officialRelease = true;
  }).build.x86_64-linux;
```

Some commands 

- nix repl
- nix eval
- nixos-rebuild
- ?

fail or print an error 

```
error: --- Error ------------------------------------------------------------------------------------------------------------------------------------------- nix
experimental Nix feature 'nix-command' is disabled; use '--experimental-features nix-command' to override
```

**Steps To Reproduce**

Use above nix expression on NixOS, observe that this error shows up.

**Expected behavior**

Things work without printing this error.

**`nix-env --version` output**

```
nix-env (Nix) 2.4
```

**Comment by zimbatm** [comment]
yes, that's not a bug. The Nix 2.0 CLI is currently experimental and now protected by a feature-flag.

**Comment by DavHau** [comment]
I'm running into this problem when trying to provide nixFlakes via reproducible dev shell.
It's quite inconvenient for every developer having to modify their nix config to be able to use this shell.

I could patch nix to not require that flag, but this requires a rebuild.

Is there a way to set nix options temporarily inside a dev shell?

There is a `NIX_CONF_DIR` variable, but using it, I'd overwrite all the users settings I guess which also could break things.
I could make a wrapper to always prepend `--option ... ...` to all nix commands, but I'm not sure if the options argument is allowed for all nix commands.

**Comment by zimbatm** [comment]
One option is to write a nix.conf in a temporary file, and then point the NIX_USER_CONF_FILES environment variable to it. NIX_USER_CONF_FILES is only supported in Nix 3.0 and will be ignored in older versions of Nix.

**Comment by gunar** [comment]
> Hi, try `nix-env -qa` to see available packages. `nix search` is experimental.

Source: https://github.com/NixOS/nix/issues/6118#issuecomment-1044540548
