### ISSUE TITLE
nixFlakes/nix-copy-closure -s: InvalidPath, SysError, Broken pipe

### ISSUE THREAD

**Issue by ajs124** [NixOS/nix#3755]
**Describe the bug**

After the most recent update to nixFlakes in nixpkgs (https://github.com/NixOS/nixpkgs/commit/348503b6345947082ff8be933dda7ebeddbb2762) `nix-copy-closure -s` is broken.

```
error: --- InvalidPath --- nix-store                                                                                                                           
path '/nix/store/ndn6snwn7yqcsfr5s4z2wsbsyjwyyp0c-qemu-user-aarch64-3.1.0.drv' is not a valid store path                                                       
error (ignored): error: --- SysError ------------------------------------------------------------------------------------------------------------------- nix-copy-closure
writing to file: Broken pipe                                                                                                                                   
error: --- Error ---------------------------------------------------------------------------------------------------------------------- nix-copy-closure       
unexpected end-of-file                                                                                                                                         
```

`nix-copy-closure` without `-s` still works. We _would_ use `nix copy` if it weren't for #3696.

**Steps To Reproduce**

1. Use nixFlakes from nixpkgs (release-20.03)
2. Have a script that does `nix-copy-closure -s`
3. Observe it broke with the most recent update

**Expected behavior**

This is a regression, I expect everything to work like it did before.

**`nix-env --version` output**
nix-env (Nix) 2.4pre20200622_334e26b

**Additional context**

There seem to be other issues with this (pre)release, like sqlite being busy being an error instead of a warning. I haven't checked if any of this is fixed on master.

cc @dasj

**Comment by dasJ** [comment]
It looks like this was broken by this commit: https://github.com/NixOS/nix/commit/fd86dd93dd44a826235feb0fd82aabcdaa79a65b cc @edolstra
