### ISSUE TITLE
[Flakes] nix does not work in shallow repositories

### ISSUE THREAD

**Issue by dasJ** [NixOS/nix#3756]
**Describe the bug**

Nix commands do not work in shallow checkouts for no apparent reason.
Nix should not care about the type of directory it's run in. I also don't want to delete .git since I need to blame the source code.

**Steps To Reproduce**

1. `git clone --depth 1 -b flakes https://github.com/NixOS/nix`
2. `cd nix`
3. `nix run`

**Expected behavior**

nix should just work instead of complaining about the repository:
```
$ nix run
error: '/tmp/nix' is a shallow Git repository, but a non-shallow repository is needed
```

**`nix-env --version` output**

`nix-env (Nix) 2.4pre20200521_00b562c`

**Comment by zimbatm** [comment]
This is an issue for CI usage because checkout time will grow linearily with the number of commits. GitHub Actions for example checks out the code with a depth of 1 by default.
