### ISSUE TITLE
Behavior of `builtins.toString` has changed

### ISSUE THREAD

**Issue by leotaku** [NixOS/nix#3771]
**Describe the bug**

I have noticed a change in behavior from the `builtins.toString` built-in function. Passing a relative path to `builtins.toString` used to return a string pointing to the contents of the path copied into the Nix store, but now simply returns the absolute path as a string.

*Previously*
```
nix-repl> builtins.toString ./example.txt
"/nix/store/5sxgi1fxahyw6cb8709114mvxxpb5x5n-source/example.txt"
```

*Now*
```
nix-repl> builtins.toString ./example.txt
"/home/example-user/example.txt"
```

**Steps To Reproduce**

1. Install Nix from a recent unstable channel
2. Install Nix from a recent stable channel
3. Run the mentioned commands and observe the difference
 
**Expected behavior**

I would expect the behavior to stay consistent between both versions of Nix.

**`nix-env --version` output**

`nix (Nix) 2.3.6` (in both cases)

**Additional context**

Maybe this behavior is expected and has been documented, but it seemed unusual to me, especially as the difference in behavior can be observed in executables with the same version.

**Comment by zimbatm** [comment]
What was the previous version? As far as I remember, `toString` would not insert the path into the store.

If you want to insert something in the store, `"${./example.txt}"` is a better option.

**Comment by FRidh** [comment]
Checked with Nix 2.0.4 (18.03), 2.1.3 (18.09) and 2.3.3 (19.09) and did not get a store path. I also cannot remember that it ever did.

**Comment by leotaku** [comment]
@zimbatm @FRidh That is interesting. I now am not entirely sure what checkout I got the Nix version that returns a store path from. When using the `channel:nixos-XX.X` checkouts I also cannot reproduce my problem. However, I do definitely remember having used `builtins.toString` to get local paths into the store for a really long time.

**Comment by leotaku** [comment]
Closing this issue, as, even after some git bisecting, I am no longer able to reproduce the described bug. I now th
Sorry for any disruption caused.

**Comment by leotaku** [comment]
Closing this issue, as, even after some git bisecting, I am no longer able to reproduce the described bug. I now think that some peculiarities of my local setup (symbolic links) have caused me to interpret perfectly correct behavior as a bug.

Sorry for any disruption caused.

**Comment by lalishansh** [comment]
#7327 
Hi @zimbatm @FRidh @leotaku @mbbx6spp @lilyball ji,
Previously i was using `pathType = types.coercedTo types.path (p: builtins.toString p) types.str;` in order to get absolute path to file in my nix-dotfiles, i've recently trying to upgrade so found out, this old way (now feels like a hack) dosen't work now and  i'm unable to make symlinks to orignal files, do you know how i can get absolute paths from files (types.path) ?

basically i am trying to do
```
users.users.ilal = {
# BLAH-BLAH-BLAH
    path.".config/hypr/hyprland.conf".link = ./hyprland.conf;
};
```
and ` "${./hyprland.conf}" ` now returns `/nix/store/xxxxxxxxxxxxxxxx-hyprland.conf`
