### ISSUE TITLE
Feature request: detect infinite overlay loops

### ISSUE THREAD

**Issue by danbst** [NixOS/nix#3772]
**Is your feature request related to a problem? Please describe.**

I had following overlay:
```
self: super:
  let pkgsLatest = import (builtins.fetchTarball "channel:nixpkgs-unstable") { };
in {
  package = pkgsLatest.package;
}
```
However, trying to install `package` resulted into OOM. The problem is that overlays are read during `import <nixpkgs>{}`, which in turn causes recursive call to this same overlay, this same package, and thus goes into recursion with high memory usage. It gets killed by OOM eventually.

The problem was pretty obscure to diagnose...

**Describe the solution you'd like**

Same as infinite recursion is detected during regular evaluation, I'd like nixpkgs import when it was already imported 1 layer above to be detectable and would fail fast.

**Describe alternatives you've considered**

There is a fix (namely, specify `{ overlays = []; }` in import line). Another fix is not to use overlays at all or at least not to shadow-name overlay packages. Or not to use import of derivation.

**Comment by FRidh** [comment]
The import by itself is fine, it's just calling with these arguments that is a problem. 

How is the infinite recursion detected? Does it attempt to evaluate several times? If so, then I imagine it would detect the infinite recursion here as well, if you had enough memory.

**Comment by danbst** [comment]
> How is the infinite recursion detected?

It is not detected, that's the problem. It continues to reimport same nixpkgs until dies of OOM. The "infinitre recursion detection" I've mentioned is a separate mechanism when no import from derivation is used.

I imagine, it should be possible to detect, that we are importing same file with same args as was done in outer evaluation. But it also may require recursive Nix to be able to do this.

**Comment by FRidh** [comment]
> It is not detected, that's the problem.

I was referring to 

> Same as infinite recursion is detected during regular evaluation

How is that detected?

**Comment by edolstra** [comment]
I don't think it's feasible to detect this, since every instance of `import (builtins.fetchTarball "channel:nixpkgs-unstable") { }` is a different value. So black hole detection (used to detect values that depend on themselves) does not apply here. Nix doesn't memoise function calls so it does not detect that the function is called with the same arguments.

**Comment by danbst** [comment]
Closing, as according to @edolstra this is technically challenging.

**Comment by interruptinuse** [comment]
> goes into recursion with high memory usage. It gets killed by OOM eventually

> There is a fix (namely, specify `{ overlays = []; }` in import line). 

Thanks, saved my bacon here!
