### ISSUE TITLE
flakes:  `nix flake update` without arguments does not update

### ISSUE THREAD

**Issue by FRidh** [NixOS/nix#3781]
**Describe the bug**
When running `nix flake update` I would expect Nix to update all inputs, however, nothing happens.

It does function when forcing with  `--recreate-lock-file` or when updating an individual update with `--update-input`.

**`nix-env --version` output**

Nix at 6ff9aa8df7ce8266147f74c65e2cc529a1e72ce0.

**Comment by colemickens** [comment]
Big +1 from me. From my `nixup` script:

```bash

  # flakes (TODO: no really, what does this do?)
  nix --experimental-features 'nix-command flakes' --pure-eval \
    flake update --no-registries

  # TODO: Why does this ever have an effect? Needs to allow for more aggression
  nix --experimental-features 'nix-command flakes' --pure-eval \
    flake update --no-registries \
      --update-input master --update-input stable ...
```

**Comment by edolstra** [comment]
We should probably just remove `nix flake update` since it doesn't do anything that other commands don't. I.e. `nix flake update --update-input nixpkgs; nix build` is equivalent to `nix build --update-input nixpkgs`.

**Comment by FRidh** [comment]
Does `nix build` *only* update `nixpkgs` or update all inputs? Considering also https://github.com/NixOS/nix/issues/3779 I have seen `nix build` do an update, but now, I can not get `nix build` to update anything by itself, unless explicitly using any of these flags.

**Comment by colemickens** [comment]
I was hoping that `nix flake update` would remain and would do the same as `nix flake update --update-input [input]` where `--update-input [input]` is specified for every input to the flake.

**Comment by edolstra** [comment]
Yes, we could have `nix flake update` be equivalent to `--recreate-lock-file`.

**Comment by zimbatm** [comment]
that was also my expectation when first using `nix flake update`; that it would update all of the sources.

**Comment by colemickens** [comment]
Just to check my understanding, I came here to ask for a `nix flake update --update-all-inputs`, but it seems like maybe `nix flake update --recreate-lock-file` does this?

Can someone confirm, `--recreate-lock-file` explicitly invalidates the cache, and/or aggressively checks each flake input for updates? (I feel like I've seen it be recreated before and still use cached values from somewher else, so I'm not sure.) Thanks!

**Comment by edolstra** [comment]
Yes, `--recreate-lock-file` will update everything. 

`nix flake update` implies `--refresh` so it will check cached inputs. This is in fact the *only* difference between `nix flake update` and other `nix` commands.

**Comment by Kha** [comment]
> `nix flake update` implies `--refresh` so it will check cached inputs. This is in fact the _only_ difference between `nix flake update` and other `nix` commands.

Should this be mentioned in the updated manpage? I.e. "This is equivalent to passing `--recreate-lock-file --refresh` to any command that operates on a flake." Perhaps `--recreate-lock-file` should even imply `--refresh`?

**Comment by FRidh** [comment]
While I very much like that by default all inputs are now updated, I do think there still needs to be the possibility to update specific inputs. You don't always want to integrate all updates at the same time.

**Comment by edolstra** [comment]
Updating specific inputs can be done using `nix flake lock --update-input ...`.

**Comment by regnat** [comment]
> Updating specific inputs can be done using nix flake lock --update-input ....

Wouldn't it make sense to merge `nix flake update` into `nix flake lock` ? It looks lake the former is just a special-case of the latter.

Or maybe just make it explicit that `nix flake update` is an alias for `nix flake lock --recreate-lock-file`

**Comment by edolstra** [comment]
> Wouldn't it make sense to merge nix flake update into nix flake lock ?

No, because that's exactly what this issue was about. It used to be one command before 453c3a603f4e6fa3f8c706e73f9869bc7f76c640.

> Or maybe just make it explicit that nix flake update is an alias for nix flake lock --recreate-lock-file

The manpage does say that: "This is equivalent to passing --recreate-lock-file to any command that operates on a flake."

**Comment by regnat** [comment]
> No, because that's exactly what this issue was about. It used to be one command before 453c3a6.

Oh yes, I didn't realise that `nix flake lock` was created as part of this commit. What I had in mind was something along the lines of

- `nix flake update` : same as current `nix flake update`
- `nix flake update --no-recreate-lock-file` (or maybe `--no-update`): same as current `nix flake lock`
- `nix flake update --update-input foo` : same as current `nix flake lock --update-input foo`

(or replacing `nix flake update` by `nix flake lock` everywhere, either commands should work fine)

> > Or maybe just make it explicit that nix flake update is an alias for nix flake lock --recreate-lock-file
> 
> The manpage does say that: "This is equivalent to passing --recreate-lock-file to any command that operates on a flake."

Yes, my comment was about the `nix flake lock` part more than `--recreate-lock-file`: The functionality of `nix flake lock --update-input foo` is very useful but also hard to discover (like @FRidh 's comment shows). I often found myself running `nix build --update-input foo` just to update the lockfile because I'd no idea that `nix flake lock` existed

**Comment by colemickens** [comment]
I had no idea `nix flake lock` was a thing.
