### ISSUE TITLE
flakes: support downloading files (as opposed to github, git and tarball types)

### ISSUE THREAD

**Issue by johnae** [NixOS/nix#3785]
**Is your feature request related to a problem? Please describe.**
I've sometimes depended on binary packages fetched from a remote. With flakes, this isn't possible to do within the inputs, eg. I can't do something like:

```nix
inputs.rust-analyzer = {
  type = "file";
  url = "https://github.com/rust-analyzer/rust-analyzer/releases/download/2020-06-15/rust-analyzer-linux";
  flake = false;
};
```

**Describe the solution you'd like**
I would like it if there was a way to specify an input of type file.

**Describe alternatives you've considered**
The alternative I'm currently using is to specify the hash, url etc directly within the derivation. However, this means I cannot update it using the `nix flake` commands and I have to deal with any such packages differently from everything else.

**Additional context**
I believe this is useful in both the context above with rust-analyzer when you don't want to build it yourself, but there may be situations where you can't build the software yourself (eg. proprietary software for example, or maybe downloading rpm:s) but would still like to manage them the same as all other dependencies.

**Comment by bqv** [comment]
See also #3920

**Comment by andyrichardson** [comment]
Would love to see this implemented! Is there a particular reason we couldn't see this added?

> Flakes are meant as a replacement for channels and things like ad-hoc invocations of `builtins.fetchgit`

☝️  this is from the docs - sounds like this feature addition compliments the purpose of flakes. 

Here's my particular use case if it helps:

```
inputs.gitlens = {
  type = "file";
  url = "https://github.com/eamodio/vscode-gitlens/releases/download/v11.1.3/gitlens-11.1.3.vsix";
  flake = false;
};
```

**Comment by bqv** [comment]
That sounds somewhat overcomplicating things. I'm having more than enough trouble getting @edolstra to comment on my PR as it is

**Comment by andyrichardson** [comment]
> That sounds somewhat overcomplicating things

I guess my point is that fetching files from absolute URLs pins a given dependency, possibly defeating the point of flakes altogether.

So maybe this initial proposition doesn't make a whole lot of sense in the long run.

**Comment by johnae** [comment]
So it is already possible to download compressed tar files (or zip-files) from arbitrary url:s so there's no real difference between that use case and any other type of file really afaict.

**Comment by bqv** [comment]
> > That sounds somewhat overcomplicating things
> 
> I guess my point is that fetching files from absolute URLs pins a given dependency, possibly defeating the point of flakes altogether.
> 
> So maybe this initial proposition doesn't make a whole lot of sense in the long run.

The main point of my solving this issue was to be able to add the capability to apply patches to flake inputs, which would require (I feel) the patches to be flake inputs too. That's an entirely valid usecase, no?

**Comment by shimunn** [comment]
> Something like `github-release:eamodio/vscode-gitlens?assets=gitlens-*.vsix`would solve this problem but would require nix to:
> 
>     * Determine what the latest tag/release is (if not specified)
> 
>     * Somehow grok files which contain version information in their name (which is common practice) such as `binary-v1.2.0.zip`

Couldn't that be solved by allowing flakes to update their own inputs? E. g. flakes get an new output attribute `updateInput` which is called for each input and either returns lockfile data or nothing in which case the default update mechanism takes over.
