### ISSUE TITLE
"Attempts" to identify logs

### ISSUE THREAD

**Issue by Ericson2314** [NixOS/nix#3813]
**Is your feature request related to a problem? Please describe.**

Yes, it's nice to have more than one log for a derivation at a time.

**Describe the solution you'd like**

I would like to teach Nix that derivations can have multiple "attempts".

Attempts would have unique identifiers. We should us UUIDs, so that different store's attempts will not collide. Logs are associated with attempts. When a build succeeds, in addition to recording mapping the derivation to the produced store path for each output, we also include the attempt that produced that output. (BTW, different outputs can come from different attempts if one deletes, builds, and substitutes carefully.)

`nix log` would take an attempt ID as an alternative to giving it a "installable" which does not uniquely identify a build. It can be backwards compatible, but with enough `-vvvv` alert the user that there are multiple logs available. We might also give it a `--list` to show all attempts for the installabe.

This will give us much better diagnostic information, and perhaps also allow removing some logic from Hydra as Nix itself would now provide it.

**Describe alternatives you've considered**

Leave it to hydra, other CIs, and other "aftermarket" tools to all re-implement this.

**Additional context**

For #3812 we can print out the attempt identifier with failing builds, so the user can easy look it up with `nix log`.

**Comment by matthewbauer** [comment]
I think UUID is overkill here. Instead, we can just add an attemptCount field to ValidPathInfo of the drv that increments with each build. `nix log` can then take a `--attempt` arg that defaults to the latest. Old logs would get moved from /nix/var/nix/logs/drvs/<hash>-<name>.drv.bz2 to /nix/var/nix/logs/drvs/<hash>-<name>.N.drv.bz2.

**Comment by Ericson2314** [comment]
Mmm but we fetch logs from substituters, so I want to not mix up remote and local steps.

**Comment by matthewbauer** [comment]
You'd have to disambiguate by store url when `--attempt` is specified, in that case. We would also have to make sure that attemptCount doesn't get carried over when you copy to a binary cache.

How would you lookup the UUID in the binary cache when none is provided? queryPathInfo would work for successful builds, but not for failing ones. That info should probably go in the derivation path instead, since that will always exist, and it avoids any issues of multiple outputs having different derivers. If we went that route, it would be nice to have a more deterministic identifier. For instance, a hash of `/etc/machine-id` + `<storePath>` + attempt count. That way CI could know what identifier to ask for ahead of time.

**Comment by Ericson2314** [comment]
> We would also have to make sure that attemptCount doesn't get carried over when you copy to a binary cache.

This is the sort of thing that UUIDs avoid. There is plenty of off-the-shelf stuff (and sqlite should also support) so I don't think UUIDs would be much more work. Only bummer is SQLite has AUTOINCREMENT but not corresponding new UUID support like postgresql does.

> How would you lookup the UUID in the binary cache when none is provided? queryPathInfo would work for successful builds, but not for failing ones. 

I don't think one can look up failing logs in binary caches today?

> That info should probably go in the derivation path instead, since that will always exist, and it avoids any issues of multiple outputs having different derivers. If we went that route, it would be nice to have a more deterministic identifier. For instance, a hash of `/etc/machine-id` + `<storePath>` + attempt count. That way CI could know what identifier to ask for ahead of time.

We can also index attempts by derivation path, output path, or both. Regardless of the key, instead of having auto-incremented numbers we can just provide a list of attempt UUIDs (e.g. with "directory" route).

With your plan, if a instituted itself substituted a build, it needs to either not provide the original log, or renumber it. That's no good.

In general, we should remember that substitutors and signers not being 1-1 is a good thing; we care who endorses data more than the final hop on how it got to us.

---------

It just occurred to me we can also hash logs, or logs + metadata (timestamps, machine-id, etc.) as identifiers. They don't need to be "fresh" as UUIDs attempt to do because we really don't care about collisions (nothing is mutated).

**Comment by matthewbauer** [comment]
> > How would you lookup the UUID in the binary cache when none is provided? queryPathInfo would work for successful builds, but not for failing ones.
> 
> I don't think one can look up failing logs in binary caches today?

I don't think this has ever been a requirement. For instance, try:

```
$ nix log /nix/store/jc85f51gz6kaypmld60h8spdly5fb02p-busybox-1.31.1-armv7a-unknown-linux-androideabi.drv
```

**Comment by Ericson2314** [comment]
Oh, neat. Well, we can keep any route we need for compat.

**Comment by edolstra** [comment]
Not really in favor of this. It adds a lot of complexity that isn't really worth it IMHO.
