### ISSUE TITLE
 "boost::bad_format_string" exception when using a flake to build a python package

### ISSUE THREAD

**Issue by Staff-d** [NixOS/nix#3815]
I've created a small, nonsensical python library to test the new, experimental flakes. 
It fails to build as soon as I enable a pylint, or in fact, any other tool like `pytest-cov` that requires an `addopts` entry in the `setup.cfg`. I'd love to fix this bug myself but the error message is really generic. 

**To Reproduce**
1. Checkout the "bug-report" branch from my [project]( https://github.com/Staff-d/flakey-lib/tree/bug-report)
2. Execute `nix --experimental-features 'nix-command flakes' build` in the root folder
3. Observe the following error message `error: boost::bad_format_string: format-string is ill-formed`
4. Remove the `tools:pytest` section from the [setup.cfg](https://github.com/Staff-d/flakey-lib/blob/bug-report/flakey_lib/setup.cfg#L4) and execute `nix build` again. It succeeds.

**Expected behavior**
I expect nix-build to work even when a `tools` section is present in the setup.cfg.

**Notify maintainers**
@edolstra 

**Metadata**
`nix-env --version`       
nix-env (Nix) 2.4pre20200622_334e26b

`nix-shell -p nix-info --run "nix-info -m"`
these paths will be fetched (0.00 MiB download, 0.00 MiB unpacked):
  /nix/store/pb3ldd73g4izhvd0k4bj76if9zws2a72-nix-info
copying path '/nix/store/pb3ldd73g4izhvd0k4bj76if9zws2a72-nix-info' from 'https://cache.nixos.org'...
 - system: `"x86_64-linux"`
 - host os: `Linux 4.15.0-106-generic, Linux Mint, 19.1 (Tessa)`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20200622_334e26b`
 - channels(sebastian): `"nixpkgs-20.09pre216190.6b6f9d769a5"`
 - nixpkgs: `/home/sebastian/.nix-defexpr/channels/nixpkgs`

I initially created a bug report over at [nixpkgs](https://github.com/NixOS/nixpkgs/issues/93133), but it probably makes more sense to report it here.

**Comment by edolstra** [comment]
I couldn't reproduce this on the current flakes branch:
```
$ nix build github:Staff-d/flakey-lib/bug-report
error: --- Error ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ nix
error: --- Error --- nix-daemon
builder for '/nix/store/z5a99gana712m562fbn9yvi5ycva56qq-python3.7-FlakeyLib-0.1.drv' failed with exit code 1; last 10 log lines:
  setup.py .                                                               [ 20%]
  algorithms/__init__.py .                                                 [ 40%]
  algorithms/fancy_algorithm.py F                                          [ 60%]
  test/test_fancy_algo.py .s                                               [100%]
  
  =================================== FAILURES ===================================
  ____________________ [pylint] algorithms/fancy_algorithm.py ____________________
  C:  4, 0: Final newline missing (missing-final-newline)
  W:  3,20: Redefining built-in 'input' (redefined-builtin)
  ==================== 1 failed, 3 passed, 1 skipped in 0.28s ====================
```

**Comment by Staff-d** [comment]
I can confirm that it works on the "flakes" branch. Many thanks :slightly_smiling_face:
