### ISSUE TITLE
Contribution to this project 

### ISSUE THREAD

**Issue by asdf8dfafjk** [NixOS/nix#3825]
Hello, thank for the Nix package manager, it has made me much more productive.  I have checked out this repository multiple times and made small printf changes  to get a sense of code, however even the smallest changes take a lot of time to recompile (I use: `nix-build --verbose ./release.nix -A build.x86_64-linux`) and the printf's cause the builds to fail. I have professional C++ experience but making incremental changes to get a sense of project isn't possible due to the above 2 points. 

I have a few things in mind- 

1) Mentioning the individual sizes of downloaded "packages".
2) Perhaps augment the existing sqlite db (I believe currently used only for garbage collection) or create a new one that stores a list of all files from all packages. Most file managers (and even `ls`) fail to enumerate files. Having them in `db` might make it much easier to quickly enumerate things. 

I explored `lib-store.cc` and I have an idea of what needs to be done conceptually and in code for both the above but compilation issues made me lose interest.

**Comment by knedlsepp** [comment]
Have you considered using the interactive build environment described here: https://github.com/NixOS/nix#development-environment?

**Comment by asdf8dfafjk** [comment]
I will try that next time.
