### ISSUE TITLE
Untrusted user can override setting

### ISSUE THREAD

**Issue by wmertens** [NixOS/nix#3835]
**Describe the bug**

I was trying to use make-content-addressable and I put it in my /etc/nix/nix.conf under experimental-features.

Then I saw I could also use ~/.config/nix/nix.conf

And then I saw the setting needed to be `nix-command` and not `make-content-addressable`.

I fixed it in my local nix.conf, and it worked, even though I got a message that it was being ignored

**Steps To Reproduce**

1. Change an existing setting in ~/.config/nix/nix.conf. Perhaps this only works for experimental-features
2. run `nix`, it now uses your overridden setting

Using current master

**Comment by edolstra** [comment]
These are client-side settings so the user is allowed to override them.

**Comment by wmertens** [comment]
In that case, the error should not be shown, right? So then that's the bug

Wout.
