### ISSUE TITLE
Filesystems are remounted a whole lot more often

### ISSUE THREAD

**Issue by dasJ** [NixOS/nix#3836]
**Describe the bug**

We use XFS and XFS (currently) only supports timestamps until 2038.
For this reason, every time the kernel mounts (or remounts) that filesystem, we get dmesg message.
In previous nix versions, this happened once per built path, but since flakes are a thing, that happens a lot more often (probably for each path that is being copied?).

I don't see any reason why the filesystem should be remounted more often than it needs to. Remounting takes CPU time that could be used otherwise.

**Steps To Reproduce**

1. Run nix on xfs
2. Observe a surprising number of remounts when someting is where most store paths are already there.

**Expected behavior**

The store should only be remounted once for every built path.

**`nix-env --version` output**

nix-env (Nix) 2.4pre20200622_334e26b

**Additional context**

cc @ajs124

**Comment by edolstra** [comment]
I'm not an XFS user so I won't be able to look into this, but it seems unlikely flakes have anything to do with this. Remounting happens in the daemon, not in the client at evaluation time.

**Comment by dasJ** [comment]
Alright :shrug:

**Comment by Kloenk** [comment]
I'm running nix flakes on xfs on my systems, and yes the messages appear, but as far as I can tell only once per daemon connection. So works as expected.

**Comment by dasJ** [comment]
@Kloenk I think (maybe I remember it wrong) those messages were not so frequent in previous nix versions.
Does the namespace really need to be remounted per daemon connection instead of only when needed? I don't think all daemon connections need to write to the store

**Comment by Kloenk** [comment]
The current remount step is in the constructor of LocalStore. I don't see a good way of detecting if write is needed.

What I could think of is mounting it rw for the daemon itself, and the clone threads with the CLONE_FS option.
