### ISSUE TITLE
macOS version check broken in Big Sur beta 3.

### ISSUE THREAD

**Issue by ryanbooker** [NixOS/nix#3852]
Big Sur beta 3 changes the version from 10.15.6 (or 10.16? Whatever it was yesterday. :)) to 11.0.

looks like it should be something like:
```
# macOS support for 10.12.6 or higher
if [ "$(uname -s)" = "Darwin" ]; then
    macos_major=$(sw_vers -productVersion | cut -d '.' -f 1)
    macos_minor=$(sw_vers -productVersion | cut -d '.' -f 2)
    macos_patch=$(sw_vers -productVersion | cut -d '.' -f 3)
    if [ "$macos_major" -lt 10 ] || { [ "$macos_major" -eq 10 ] && [ "$macos_minor" -lt 12 ]; } || { [ "$macos_major" -eq 10 ] && [ "$macos_minor" -eq 12 ] && [ "$macos_patch" -lt 6 ]; }; then
        echo "$0: macOS $(sw_vers -productVersion) is not supported, upgrade to 10.12.6 or higher"
        exit 1
    fi
fi
```

**Comment by zimbatm** [comment]
>  If the calling environment sets the variable SYSTEM_VERSION_COMPAT=1 then Big Sur will return 10.16 as its version number; with that absent or set to 0, the version returned will be 11.0. 
source: https://eclecticlight.co/2020/07/21/big-sur-is-both-10-16-and-11-0-its-official/

Might be useful in that context

**Comment by ryanbooker** [comment]
The current check is only checking the minor and patch versions (and calling them major and minor), assuming macOS would be 10 forever. :)

**Comment by ryanbooker** [comment]
`SYSTEM_VERSION_COMPAT=1` work around no longer does anything in Beta 5.
