### ISSUE TITLE
macOS installer "failed to configure synthetic.conf"

### ISSUE THREAD

**Issue by steshaw** [NixOS/nix#3861]
**Describe the bug**

I'm installing Nix on a new MacBook. The installer fails with "error: failed to configure synthetic.conf;". Since I'm on Catalina, I'm I use `--darwin-use-unencrypted-nix-store-volume`. I also added `--daemon`.

```sh-session
$ sh <(curl -L https://nixos.org/nix/install) --darwin-use-unencrypted-nix-store-volume --daemon
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2490  100  2490    0     0   5608      0 --:--:-- --:--:-- --:--:--  5608
downloading Nix 2.3.7 binary tarball for x86_64-darwin from 'https://releases.nixos.org/nix/nix-2.3.7/nix-2.3.7-x86_64-darwin.tar.xz' to '/var/folders/07/kd3h10nj14s1trgx6t99q4t00000gn/T/nix-binary-tarball-unpack.XXXXXXXXXX.sGOBFs35'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 26.4M  100 26.4M    0     0  2692k      0  0:00:10  0:00:10 --:--:-- 1656k
Note: a multi-user installation is possible. See https://nixos.org/nix/manual/#sect-multi-user-installation
Creating volume and mountpoint /nix.

     ------------------------------------------------------------------ 
    | This installer will create a volume for the nix store and        |
    | configure it to mount at /nix.  Follow these steps to uninstall. |
     ------------------------------------------------------------------ 

  1. Remove the entry from fstab using 'sudo vifs'
  2. Destroy the data volume using 'diskutil apfs deleteVolume'
  3. Remove the 'nix' line from /etc/synthetic.conf or the file

Configuring /etc/synthetic.conf...
Password:
nix
error: failed to configure synthetic.conf;
       please report this @ https://github.com/nixos/nix/issues
```

**Steps To Reproduce**

1. On new MacBook.
2. Run `sh <(curl -L https://nixos.org/nix/install) --darwin-use-unencrypted-nix-store-volume --daemon`

**Expected behavior**

Installs successfully.

**`nix-env --version` output**

```sh-session
$ nix-env --version
bash: nix-env: command not found
```

**Additional context**

macOS version 10.15.6 (19G73)

I retried the install with the same result. The contents of `/etc/synthetic.conf` are:

```sh-session
$ sudo cat /etc/synthetic.conf 
Password:
nix
nix
nix
```

**Comment by lilyball** [comment]
What is the output of `type grep`? The install script uses the status code from `grep -q "^nix$" /etc/synthetic.conf 2>/dev/null` to determine whether `/etc/synthetic.conf` has the `nix` line in it.

**Comment by steshaw** [comment]
Hi @lilyball, thanks for getting back to me.

```sh-session
$ type grep
grep is hashed (/usr/bin/grep)
```

here's the clincher though:

```sh-session
$ grep -q "^nix$" /etc/synthetic.conf 2>/dev/null && echo yep || echo nah
nah
```

and

```
$ grep "^nix$" /etc/synthetic.conf
grep: /etc/synthetic.conf: Permission denied
```

So, I'm getting caught because my umask was 077 when I ran the installer. I've since switched back to 022 but, of course, the installer still fails.

I found these related open issues:

- https://github.com/NixOS/nix/issues/2377
- https://github.com/NixOS/nix/issues/1560

and a these closed issues:

- https://github.com/NixOS/nix/issues/2190
- https://github.com/NixOS/nix/issues/1582

### Resolution

I was able to resolve the issue changing the permission of `/etc/synthetic.conf` and re-running the installer. The installer prompted me to delete my old Nix files as usual. After deleting those, the second run of the installer completed successfully!

```
$ chmod 644 /etc/synthetic.conf
```

Thanks again.

Now that I have installed Nix, is it possible to configure my umask back to 077 or must I run with 022 for smooth operation?

**Comment by lilyball** [comment]
It sounds like the install script should override the `umask` before making any modifications.

As for whether your umask will affect anything, I'm really not sure. Since you used `--daemon`, unprivileged commands (e.g. `nix-env -iA foo`) will ask the daemon to make the changes, so your local shell's umask shouldn't affect it. But I think commands executed with `sudo` may just manipulate the store directly (and in particular `nix-channel --update` requires `sudo` here), and I'm not sure if nix will reset the umask itself. Your best bet is to test it and see if anything breaks, especially since you still have a fresh install and therefore wiping and reinstalling isn't too onerous if you end up in a state where permissions are screwy.

**Comment by steshaw** [comment]
Agreed, it'd be better if the installer changed the umask (it should at least bail with an error if the umask isn't 022). In those open issues there seems to be a lack of agreement and so that's probably why no progress has been made.

Thanks for the tips. I may reconfigure back to a umask of 077 and see what I run into :smile: .

**Comment by dabrahams** [comment]
If it's considered too fishy to hide in the installer, the umask set/reset could be explicit in the macos installation instructions.
