### ISSUE TITLE
Set `IN_NIX_SHELL` or similar for `nix shell`

### ISSUE THREAD

**Issue by Ma27** [NixOS/nix#3862]
**Is your feature request related to a problem? Please describe.**

The `IN_NIX_SHELL` env-var is used by e.g. [`nix-zsh-completions`](https://raw.githubusercontent.com/spwhitt/nix-zsh-completions/master/nix-zsh-completions.plugin.zsh) to optionally add a `[nix-shell]` indicator to the prompt. I'd like to have such an indicator as well when using `nix shell` for clarity.

**Describe the solution you'd like**
The simplest solution would be to set `IN_NIX_SHELL` for `nix shell` as well.

**Describe alternatives you've considered**
I don't think that are any implications re/stdenv as this only applies in an interactive build-shell. However we may want to use a different var-name here for clarity.

**Additional context**
n/a

**Comment by Kloenk** [comment]
I wrote my own zsh shortcut, which sets the PROMPT for me. https://github.com/Kloenk/nix/blob/master/configuration/common/zsh/default.nix#L6-L19

This could be an alternative to handle it in nix

**Comment by Ericson2314** [comment]
If we do this, we shouldn't have it effect evaluation, even with `--impure`. I have been bitten by nix code that snooped that environment variable too many times.

**Comment by Ma27** [comment]
> If we do this, we shouldn't have it effect evaluation, even with --impure. I have been bitten by nix code that snooped that environment variable too many times.

Good to know.

I actually like the approach @Kloenk has demonstrated. We could probably add the derivation-names into an env-var in `nix shell` to allow e.g. shell plugins to work with this.

@edolstra wdyt?

**Comment by FRidh** [comment]
`IN_NIX_SHELL` is used with `nix-shell` which is a shell that recreates the build environment. `nix-shell` does not do this. What behaviour should `IN_NIX_SHELL` indicate? Maybe it should only be set in `nix develop`?

**Comment by Ma27** [comment]
That's currently the case. I'm asking whether we want something similar for nix shell.

**Comment by mkaito** [comment]
You can check if there's a nix store path on your `$PATH`, which seems to serve as a reasonably reliable proxy check. Here's what I did for zsh:

```sh
VIM_PROMPT="❯"
NIX_PROMPT="%F{green}λ%f "
PROMPT='${MY_IN_NIX_SHELL:+${NIX_PROMPT}}%(?.%F{magenta}.%F{red})${VIM_PROMPT}%f '

precmd_in_nix_shell() {
  if echo "$PATH" | grep -qc '/nix/store'; then
    export MY_IN_NIX_SHELL=bananas
  fi
}
add-zsh-hook precmd precmd_in_nix_shell
```

**Comment by aaronjanse** [comment]
Here's what I'm using to list the packages enabled by nix-shell:

```bash
NIXSHELL=$(echo $PATH | tr ':' '\n' | grep '/nix/store' | sed 's#^/nix/store/[a-z0-9]\+-##' | sed 's#-[^-]\+$##' | xargs -n2 -d'\n')

if [ "$NIXSHELL"  ]; then
	echo -n '%{%F{cyan}%}' # cyan
	echo -n "$NIXSHELL "
	echo -n '%{%f%}'
fi
```

Which, combined with the rest of my prompt results in:

```
ajanse $ hello
zsh: command not found: hello
ajanse $ nix shell nixpkgs#hello
ajanse hello $ hello
Hello, world!
ajanse hello $
```

It's not perfect, and it would be nice to see an environment variable so we can do this without hacky /nix/store path parsing (that likely breaks often).

**Comment by roberth** [comment]
> If we do this, we shouldn't have it effect evaluation, even with `--impure`. I have been bitten by nix code that snooped that environment variable too many times.

@Ericson2314 did you see https://github.com/NixOS/nix/pull/3168 which adds an `inNixShell` auto-call parameter? I guess I should start promoting it after 1 year of it not being released but people using nixUnstable :confused: would've backported if I knew.

**Comment by fgaz** [comment]
> IN_NIX_SHELL is used with nix-shell which is a shell that recreates the build environment. nix shell does not do this. What behaviour should IN_NIX_SHELL indicate? Maybe it should only be set in nix develop?

it could have different values, like the current `pure`/`impure`

**Comment by fgaz** [comment]
If this gets implemented it'd be nice to have #2020 too

**Comment by nrdxp** [comment]
Not sure if this deserves its own issue, but definitely related to this is the fact that `IN_NIX_SHELL` is set to 1 on a `nix develop` instantiation, but considering the new nix command is pure by default, it should probably be set to `pure` instead, like when passing the old `nix-shell --pure`. It should only be `1` if the `--impure` flag is unset.

This should probably also exstend to `nix print-dev-env` since this is how most direnv users enter a flake's shell atm.

**Comment by edolstra** [comment]
> IN_NIX_SHELL is used with nix-shell which is a shell that recreates the build environment. nix shell does not do this. What behaviour should IN_NIX_SHELL indicate? Maybe it should only be set in nix develop?

Yeah, I think `IN_NIX_SHELL` should only be set in `nix develop`. `nix shell` only adds packages to `$PATH` so I don't think it really matches the expectations for `IN_NIX_SHELL` (which is that you're in a stdenv build environment).

**Comment by pinpox** [comment]
> I don't think it really matches the expectations for `IN_NIX_SHELL`

While correct from a technical standpoint, I'm not sure I agree from a user's perspective. Assuming that "you are in a nix shell"  (and `IN_NIX_SHELL` will be set) when you run `nix shell` seems logical based on the name of the command and could at least be a likely source of confusion.

**Comment by FRidh** [comment]
It's somewhat confusing but is it really that much of an issue? Maybe `nix develop` should also listen to `IN_NIX_DEVELOP`. Would that be better? Of course, `IN_NIX_SHELL` should still be supported for compatibility reasons. I don't see how this gets any better.

**Comment by balsoft** [comment]
> I don't think it really matches the expectations for `IN_NIX_SHELL`

Maybe keep `IN_NIX_SHELL` for `nix develop`, and add `IN_NIX3_SHELL` for `nix shell`? I think it's genuinely useful to have a way to tell whether we're in a temporary `nix shell` with some packages.

**Comment by fgaz** [comment]
I agree with @balsoft. It'd be nice to have _any_ way to tell that a shell is in use even if that method isn't `$IN_NIX_SHELL`

**Comment by tv42** [comment]
My expectation as a user: Me "being in nix shell" == "exit will return me out of it, back to previous thing".

`nix shell` does *not* "only add packages to $PATH", it starts a subshell.

**Comment by siraben** [comment]
Any updates on this? A user I was helping transition to flakes has ran into this surprising behavior. A hack to detect `/nix/store` in PATH is not satisfactory.

**Comment by aadibajpai** [comment]
echoing other users, but I recently started using nix and this was a major source of confusion since I could be 3 subshells deep with `nix shell` but have no way of knowing the state of my current shell. Setting IN_NIX_SHELL (or some other var) for nix shell as well would be very useful since `nix shell` does put the user in a nix provisioned shell with the specified packages.

**Comment by vincentbernat** [comment]
Another argument to be able to signal we are in a nix shell is to allow the shell to not pollute the environment when not impure. I am normalizing paths in my shell and I was opting out doing that in a pure environment. I cannot do that anymore.

**Comment by jjant** [comment]
Any updates on this?

**Comment by hraban** [comment]
I have a hacky solution to this which solves my immediate problem of "am I in my top-level login shell, or in a spawned subshell?" without any further Nix integration, by adding this to my `.bashrc`:

```bash
# When I’m in a child shell (direnv, nix develop, etc) display a lil ↳. Use -eq
# not == because ps output includes whitespace.
if [[ "$(ps -o uid= $PPID)" -eq "$UID" ]]; then
	PS1=' \[\033[1;32m\]↳\[\033[0m\] '"$PS1"
fi
```

It prepends a ` ↳ ` to my prompt when I'm in a `nix develop` or `nix shell`. `nix-shell -p ...` overrides the entire PS1 so that's already fine by me.

It doesn't give me much info, but at least I know if I can `exit` this prompt and return to some top level shell.

Maybe this is useful to someone 🙏

**Comment by Lucretiel** [comment]
Just wanted to jump in as a [starship](https://starship.rs/) prompt user. Starship ships a [nix-shell](https://starship.rs/config/#nix-shell) module, which adds a note to your prompt when you're in a nix shell, and I was sad to discover that it doesn't work with `nix shell`. Starship used `IN_NIX_SHELL` for this, and there doesn't seem to be a good signal for it when using `nix shell`.

**Comment by jjant** [comment]
@Lucretiel You can set the `heuristic` option to `true` for "best effort" `nix shell` recognition (I know because [I implemented it](https://github.com/starship/starship/pull/4724), heh).

**Comment by mayersj1** [comment]
The "best effort" is nice but there are so many false positives by simply checking to see if '/nix/store' is in the PATH statement.  I use kitty as my terminal and kitty adds itself to the path: there is an entry of /nix/store now in the path.  

I don't understand the reluctance to modify 'nix shell' to work the same as 'nix-shell'.

**Comment by viperML** [comment]
I finally solved this with some ELF hacking:

```c
#include "stdlib.h"

static void before_main(void) __attribute__((constructor));

static void before_main(void)
{
  setenv("IN_NIX_SHELL", "impure", 1);
}
```

Then build it as a shared library, and link it to nix with patchelf (or LD_PRELOAD it).

I have made this hack into a flake, to make it easy to apply: https://github.com/viperML/in-nix

**Comment by Congee** [comment]
Inspired by hooking the entrypoint main, I chose to patch the source code because I'm on macOS.

`nix.package = pkgs.nix.overrideAttrs (old: { patches = old.patches ++ [ ./0001-setenv-IN_NIX_SHELL-to-impure.patch ]; });`

<details>
<summary>0001-setenv-IN_NIX_SHELL-to-impure.patch </summary>

```diff
From 5071dfca61e916676c19b1fc878b50c6c5baf17a Mon Sep 17 00:00:00 2001
From: Congee <congee@redacted.re>
Date: Thu, 26 Sep 2024 15:18:56 -0400
Subject: [PATCH] setenv IN_NIX_SHELL to impure

---
 src/nix/main.cc | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/src/nix/main.cc b/src/nix/main.cc
index 7a9516d5e..c7c615202 100644
--- a/src/nix/main.cc
+++ b/src/nix/main.cc
@@ -553,8 +553,10 @@ void mainWrapped(int argc, char * * argv)
 
 }
 
+#include <stdlib.h>
 int main(int argc, char * * argv)
 {
+    setenv("IN_NIX_SHELL", "impure", 1);
     // Increase the default stack size for the evaluator and for
     // libstdc++'s std::regex.
     nix::setStackSize(64 * 1024 * 1024);
-- 
2.46.0
```
</details>

**Comment by Bvngee** [comment]
I've been debugging this for a while today and am incredibly disappointed to come to the conclusion in this issue. ELF hacking and grepping PATH for store paths are NOT suitable methods to determine if you're in a nix shell. Nix shells are not invisible; they put you in a subshell, as mentioned before. Users deserve to know when their PATH is being modified; there is no reason to conceal that information. **There absolutely should be a way for users to deduce the state of their shell.**

Furthermore, `IN_NIX_SHELL` referring to something _other_ than whether or not you're "in a nix shell" is just criminally bad user experience. You can't expect everyday users to know that `IN_NIX_SHELL` actually refers to when you're in an stdenv build environment and not the `nix shell` command. Even worse, it `does` got set for nix-shell but not for nix shell! You can't argue that that's understandable in any way from a not-purely-technical standpoint.
