### ISSUE TITLE
Difference between nix flake new and nix flake init?

### ISSUE THREAD

**Issue by Mic92** [NixOS/nix#3863]
It seems that the only difference is that one takes an argument.
How about adding an optional argument to `nix flake init` which is used instead of the current dir?
It seems a bit redundant to have to subcommands that do more or less the same.

See https://nixos.wiki/wiki/Nix_command/flake_init vs. https://nixos.wiki/wiki/Nix_command/flake_new

**Comment by edolstra** [comment]
It's the same as `cargo new` and `cargo init`. The first creates a new directory and initialises it, the second only initialises an existing directory.
