### ISSUE TITLE
`nix search` should show me how old the cache is

### ISSUE THREAD

**Issue by lilyball** [NixOS/nix#3865]
**Is your feature request related to a problem? Please describe.**
When I run `nix search` it always gives me a warning about how it's using cached results. That's fine, but it doesn't tell me how old the cache is.

**Describe the solution you'd like**
It would be great if it could include the cache age (could be the absolute date of the cache, but ideally it would be how old the cache is, e.g. "5 hours old", "107 days old", etc).

**Comment by edolstra** [comment]
Closing this since we removed the JSON cache. The new evaluation cache is only created for pure/hermetic evaluations so it can never get out of date.
