### ISSUE TITLE
`nix search` should take -f flag into account for the cache

### ISSUE THREAD

**Issue by lilyball** [NixOS/nix#3866]
**Is your feature request related to a problem? Please describe.**
If I run `nix search -f …` it applies an existing cache even if the cache wasn't made for the given file. If I use `nix search -u -f …` it overwrites the shared cache, which means subsequent `nix search` commands will use that cache even though it doesn't apply.

**Describe the solution you'd like**
By default, using `-f` should imply `--no-cache`. Using `-f `with `-u` should use a separate cache file keyed on the realpath of the file argument.

**Comment by edolstra** [comment]
Closing since with the new evaluation cache, we never cache results when using `-f` (since it's not hermetic).
