### ISSUE TITLE
`nix search` should detect when the cache is out of date and update it automatically

### ISSUE THREAD

**Issue by lilyball** [NixOS/nix#3867]
**Is your feature request related to a problem? Please describe.**
`nix search` uses a cache to speed up searching, but it gets out of date very quickly, and any time it's used it prints a warning about how it's using the cache. There's no information as to whether the cache is actually out of date or not.

**Describe the solution you'd like**
Typical usage of `nix search` is with configured channels. The current revision of each channel can be hashed to produce an identifier that can be embedded in the config and then tested to see if it's changed.

The four scenarios this simplistic approach doesn't handle:

* Using `-f` to specify an alternative. The file in question could be hashed, but that won't take into account anything it imports. We could just fall back to current functionality for `-f` (also see #3866 which establishes a separate cache for `-f`).
* When `NIX_PATH` contains something other than a channel. If it's a git checkout, `nix search` could detect this and use the currently-checked-out commit (this will ignore local modifications but I think that's okay). If it's something else, it could fall back to current functionality.
* `packageOverrides`. `nix search` could include a hash of `~/config/nixpkgs/config.nix` in the identifier. Probably a good idea anyway as various config options could enable/disable packages.
* Overlays. `nix search` could just hash the entire directory tree for the overlays since it's unlikely to be especially large, or it could just declare that overlays aren't considered and that if the user updates their overlays they should explicitly pass `-u` to `nix search`.

**Describe alternatives you've considered**
For `-f`, `nix search` could instrument the Nix evaluation such that it records every imported path and use that to build a tree of files to consult for the check. This seems rather complicated though, especially since it would need to recognize when a `<nixpkgs>` reference is used (or just always assume the `NIX_PATH` affects evaluation).

**Comment by edolstra** [comment]
Closing since the new evaluation cache can never get out of date thanks to hermetic evaluation.
