### ISSUE TITLE
`nix search` uses config dir to store temp files, doesn't clean them up

### ISSUE THREAD

**Issue by lilyball** [NixOS/nix#3870]
**Describe the bug**

I just checked my `~/.config/nix` dir and I have a number of empty temporary `package-search.json.tmp.###` files, presumably from interrupted `nix search` invocations.

I expect `nix search -u` opens a temporary file as output, writes to it, and then when it's done it closes the file and moves it over the cache. This would be great, except the fact that they're empty suggests to me that it's actually buffering all the data in-memory. This may be because the JSON output contains no newlines, so if the file is line-buffered the buffer won't be flushed until it's closed.

Besides being empty, the other problem is just that they're there at all. Nothing is cleaning them up. Some are from today, some are from a couple of weeks ago.

Ideally these files would be written to `$TMPDIR` instead, so that way they'll at least be cleaned up on reboot; I'm not sure offhand what the right behavior to do if `$TMPDIR` is on a different filesystem though, as I'm assuming this is relying on file moving to be atomic in order to overwrite the current cache (macOS has an API specifically to ask for a temporary directory appropriate for a given path, but I don't know how to solve this generically). Alternatively, `nix search` could learn to delete any `package-search.json.tmp.###` files it finds if the trailing pid doesn't exist anymore, and perhaps ideally would also learn to clean up its tmpfile if it's interrupted prior to exiting.

**Steps To Reproduce**

1. `ls ~/.config/nix`

**Expected behavior**

There shouldn't be any temporary files hanging out here.

**`nix-env --version` output**

nix-env (Nix) 2.3.7

**Comment by edolstra** [comment]
Closing this since `package-search.json` has been removed on master.
