### ISSUE TITLE
nix copy --no-check-sigs fails for trusted user

### ISSUE THREAD

**Issue by MartinPotier** [NixOS/nix#3873]
**Describe the bug**

`nix copy --no-check-sigs` fails for trusted user.

My trusted user:

```
$ id -un
user
$ id -u
1572600074
```

This user is coming from LDAP, it is not a system user.
If nix uses `/etc/passwd` to check trusted users, then I understand why this is failing, and maybe this should be fixed.

**Steps To Reproduce**

1. add `user` in trusted users in `/etc/nix/nix.conf`
2. restart nix-daemon
3. invoke `nix copy --nix copy --no-check-sigs --from s3://<cache> <path>`
4. observe `error: cannot add path '<path>' because it lacks a valid signature`

**Expected behavior**

This should succeed.
In fact, it succeeds as root, and it also succeeds if I set `trusted-users = *`.

This is run with nix 2.3.7

nix-env (Nix) 2.3.7

**Additional context**

This is nix-daemon (multi-user), installed on top of “CentOS Linux release 8.1.1911 (Core)”.

**Comment by MartinPotier** [comment]
A bit more on this. `getent passwd user` returns the user information properly, but `getent passwd` will not list it (because enumeration is turned off in sssd configuration for perf reasons). I wonder if this could be the cause of this problem?

**Comment by MartinPotier** [comment]
Here's an extract of the nix-daemon log, first with my user set in `trusted-users` and then with `*` set in `trusted-users`:

```
Jul 30 13:36:04 solekukka.relex.fi nix-daemon[94413]: accepted connection from pid 124395, user 1572600074
Jul 30 13:36:37 solekukka.relex.fi nix-daemon[94413]: accepted connection from pid 124549, user 1572600074
Jul 30 13:46:49 solekukka.relex.fi systemd[1]: Stopping Nix Daemon...
Jul 30 13:46:49 solekukka.relex.fi systemd[1]: Stopped Nix Daemon.
Jul 30 13:47:15 solekukka.relex.fi systemd[1]: Started Nix Daemon.
Jul 30 13:47:15 solekukka.relex.fi nix-daemon[137951]: accepted connection from pid 137931, user 1572600074 (trusted)
```

The second one is clearly (and correctly) marked as trusted

**Comment by MartinPotier** [comment]
I believe the problem is in https://github.com/NixOS/nix/blob/master/src/nix-daemon/nix-daemon.cc#L198

```
            struct passwd * pw = peer.uidKnown ? getpwuid(peer.uid) : 0;
```

I wonder if this procedure `getpwuid` works as expected. I'll try and dig more on that. It seems clear that the peer.uid is correct because it is shown in the nix-daemon logs correctly. So, I'm assuming that it is the user name comparison that is failing to happen.

**Comment by MartinPotier** [comment]
Interestingly, `getpwuid` is also used in a util function called `getUserName`. `getUserName` is used eg in the function that sets up `/nix/var/nix/profiles/per-user/<username>/`.

I was curious so I checked on my host:

```
[user@host ~]$ ls /nix/var/nix/profiles/per-user/
1572600074  root
```

Well, it would seem that `pw->pw_name` is set to the user id! What the hell is going on here… So, nix is probably doing its job right after all, or `getpwuid` has an unexpected behavior.

**Comment by MartinPotier** [comment]
Alright, when I set `trusted-users = 1572600074`, I can run my original command with success.

```
Jul 30 14:04:03 solekukka.relex.fi nix-daemon[148669]: accepted connection from pid 148241, user 1572600074 (trusted)
```

**Comment by MartinPotier** [comment]
@edolstra do you have any more info on this `getpwuid` and its surprising behaviour? Is it behaving as you would expect, or shall it be corrected somehow. I could do a PR with some guidance, but bear in mind that I have almost no C++ knowledge (but I did C).

**Comment by MartinPotier** [comment]
Alright, this seems to be a low-level linux function… On the problematic host, `getent passwd username` yields the passwd db entry, so I'm wondering on which side this problem sits. Maybe I should write a small C program to test the behaviour of this function.

**Comment by edolstra** [comment]
Can you give more precise reproduction instructions? In particular,in `nix copy --no-check-sigs <cache> <path>` it might matter a lot what `<cache>` is. Also, do you mean `--to` or `--from`?

**Comment by MartinPotier** [comment]
So, I wrote this little pgm:

```C
#include <pwd.h>
#include <stdio.h>

int main () {
  struct passwd * pw = getpwuid(1572600074);
  printf("User id: %d\nUser name: %s", 1572600074, &pw->pw_name);
  return 0;
}
```

Which I then ran on the target host, giving this output:

```
User id: 1572600074
User name: (null)
```

**Comment by MartinPotier** [comment]
This actually looks familiar https://stackoverflow.com/questions/18570177/getpwuid-returns-null-for-ldap-user so, I'd think it's not a nix bug.

**Comment by MartinPotier** [comment]
But, documenting, or emitting a warning in nix about username not found could be night and day for finding out the root cause of this type of problem :)

**Comment by MartinPotier** [comment]
Potentially, it could come from a missing shared library (libnss_sss.so), or some incompatibility between the shipped shared library and the running daemon?

**Comment by MartinPotier** [comment]
Ok, I think I've encountered something related to this problem:

```
[user@server ~]$ ls /nix/var/nix/profiles/per-user/
1572600074  1572751003  22400792  root
```

Users set by IPA are not represented by name, but by their user ID.

**Comment by chreekat** [comment]
@MartinPotier , I couldn't reproduce, and since getpwuid is not re-entrant, I'm not terribly surprised! I do think we should look at how Nix fetches username (but I also think we're way off topic for this issue... should we open a new one if we can find a repro?)

**Comment by MartinPotier** [comment]
Closing this issue, since it cannot be reproduced.

**Comment by rihardsk** [comment]
@MartinPotier i've just run into this issue. I think this might be caused by the same underlying issue as https://github.com/NixOS/nix/issues/3356 (don't mind the mention of NFS in the title, the salient bit is that an Active Directory user was being used).

When debugging the linked issue, i too noticed that `getpwuid` results are different for LDAP users https://github.com/NixOS/nix/issues/3356#issuecomment-703578751. I observed that `getpwuid` failed to return a username only when using nixpkgs' gcc on a system with SSSD/Active Directory
