### ISSUE TITLE
I can't specify a flake rev in the flake.nix file?

### ISSUE THREAD

**Issue by colemickens** [NixOS/nix#3878]
**Describe the bug**

I can't tell if this is intentional, a missing feature, or if I'm using the flake url syntax wrong.

This tweag article says:

>But it’s easy to ask Nix to build a specific revision:
>$ nix shell github:edolstra/dwarffs/cd7955af31698c571c30b7a0f78e59fd624d0229

Yet, that syntax doesn't work in a flake.nix:

`URL 'github:nixos/nixpkgs/nixpkgs/38880a5ec2dcef30599105bfbf55dc2f287dc70e' is invalid`

```
$ nix --version
nix (Nix) 2.4pre20200721_ff314f1
```

**Comment by colemickens** [comment]
What is going on? Now I push a branch up and I can't refer to it either? Is there some overly aggressive caching going on?

**Comment by edolstra** [comment]
Yes, this is correct. With `github` URLs, you cannot specify both a ref (`nixpkgs`) *and* a revision. BTW I don't think `nixpkgs` is an existing branch. This works: `github:NixOS/nixpkgs/38880a5ec2dcef30599105bfbf55dc2f287dc70e`.

**Comment by colemickens** [comment]
Sorry, I don't know what I was thinking or thought I had written there. I'm not even sure what that would mean. :S
