### ISSUE TITLE
Get rid of json.hh and just use nlohmann/json

### ISSUE THREAD

**Issue by Ericson2314** [NixOS/nix#3884]
~~I suspect the answer is that we don't need both.~~ *edit* confirmed below. I would like to get rid of json.hh and just use nlohmann. In particular, nlohmnan has infrastructure for marshaling in both directions, while json.hh only has the `fromJSON` derivation, and I think we should get in the habit of always implementing both directions even if we just need one, to sanity check our schemas make sense.

CC @matthewbauer

**Comment by Ericson2314** [comment]
Also, I opened https://github.com/nlohmann/json/discussions/2335. we could also adapt that approach to `json.hh`, so it's isn't strictly relevant to this discussion. However, my larger point is writing lots of cannonical round trips to avoid ad-hoc JSON logic, and that issue will make that much more feasible with `StorePath`, `Hash`, and other non-default-constructable types no longer being such a headache.

**Comment by edolstra** [comment]
We don't need both. `json.hh` just predates our use of nlohmann/json.

**Comment by Ericson2314** [comment]
Great! I will look into systematizing the json stuff. CC @Kloenk.

**Comment by tobim** [comment]
Done in #7313?

**Comment by cole-h** [comment]
Seems like it, thanks!
