### ISSUE TITLE
Allow fetching derivations from a substituter

### ISSUE THREAD

**Issue by nomeata** [NixOS/nix#3887]
I regularly run into this problem:

 * I am building something locally that expect to be available in one of the substituters I am using.
 * I get a cache miss. So somehow my local derivation is different than the one on the cache. I need to investigate.
 * I run `nix-instantiate` locally to get my derivation path, and check CI logs to get the derivation produced remotely.

Now I’d like to use `nix diff` on these two derivations. But for that, I need to fetch the remote one first. It seems that this is not possible:

 * `nix-store --realize /nix/store/….drv` tries to be smart: Instead of fetching the derivation from the substituter (as it would do with any other `/nix/store` path that I pass to `nix-store --realize`), it tries to download the _output_ of the derivation, for which it needs the derivation, which I don't have…
 * `nix-copy-closure` can download derivations and output paths alike, but only works via ssh, not the substituter protocol.

I would love to have either (or both) of these tools to support download derivations from a nix cache. Would that be possible?

**Comment by Ericson2314** [comment]
Yeah I think a lot of commands are a bit too clever with drv files. I'd like to have derivations that produce drv files :O, after which we'll I think we'll be somewhat forced to be less magical. There were some other issues on this I'd like to link, but I am having trouble finding them.

**Comment by roberth** [comment]
In my experience with Nix <= 2.3.*, `nix-store -r` will report that it `doesn't know how to build /nix/store/.....drv` but then continues to do it anyway. Hercules CI relied on this behavior in the beginning.

**Comment by nomeata** [comment]
Hmm, can’t reproduce that with nix 2.3.4:
```
~ $ nix-store -r /nix/store/36bxxxdr0-all-jobs.drv
don't know how to build these paths:
  /nix/store/36bxxxdr0-all-jobs.drv
cannot build missing derivation '/nix/store/36bxxxdr0-all-jobs.drv'
error: build of '/nix/store/36bxxxjdr0-all-jobs.drv' failed
~ $ LANG=C ls /nix/store/36xxxjdr0-all-jobs.drv
ls: cannot access '/nix/store/36bxxxjdr0-all-jobs.drv': No such file or directory
```

**Comment by nomeata** [comment]
Fairly sure, but hard to check :-D Let me ask those with access.

**Comment by Ericson2314** [comment]
Now that #7600 is merged, I think this is fixed with the new CLI! Let me know if it is not, @nomeata.
