### ISSUE TITLE
load nix.sh from ~/.profile and update XDG_DATA_DIRS 

### ISSUE THREAD

**Issue by jnoortheen** [NixOS/nix#3910]
**Is your feature request related to a problem? Please describe.**
gui applications installed with nix do not appear in linux DE's launcher. The problem is answered [here](https://unix.stackexchange.com/a/311645) 

**Describe the solution you'd like**
this is added by nix upon install. 
```sh
if [ -e ~/.nix-profile/etc/profile.d/nix.sh ]
then 
	source ~/.nix-profile/etc/profile.d/nix.sh
fi # added by Nix installer
```

it is better to be put in `~/.profile` so that gui apps will pickup the path variable changes. Also adding Nix's data folder to `XDG_DATA_DIRS` like mentioned in the answer will make things easier for newcomers.
```
export XDG_DATA_DIRS=$HOME/.nix-profile/share:"${XDG_DATA_DIRS:-/usr/local/share/:/usr/share/}"
```

**Comment by matthewbauer** [comment]
`/etc/profile` and `$HOME/.profile` are not always loaded by the shell. Bash only loads /etc/bashrc and ~/.bashrc (although some systems source profile from those for you).

XDG_DATA_DIRS isn't added for fear of breaking the host system: https://github.com/NixOS/nix/pull/2443#issuecomment-423912395. It's not too hard to just add it yourself though.
