### ISSUE TITLE
json output for nix build

### ISSUE THREAD

**Issue by Kloenk** [NixOS/nix#3936]
**Is your feature request related to a problem? Please describe.**
I'm trying to work with `nix build --dry-run`, I read somewhere that there should be a `--json` flag for json output, but it seems missing.

**Describe the solution you'd like**
`--json` flag for `nix build`, returning an array for and a count for `--dry-run` and the output path for normal build.

**Describe alternatives you've considered**
returning the output path to stdout with nix build

**Additional context**

**Comment by Kloenk** [comment]
Would also like it if errors would be printed as json, for `nix eval --json` as example.

**Comment by itshaydendev** [comment]
Not that I would be able to do anything with this in the slightest (:joy:) but I'm curious as to what the use case for this would be

**Comment by Kloenk** [comment]
> Not that I would be able to do anything with this in the slightest (:joy:) but I'm curious as to what the use case for this would be

nix-build provides things like $(nix-build '<nixpkgs>' -A hello) this feature is missing on nix build

**Comment by edolstra** [comment]
Closed by 8abb80a478116b10bf37162c71f602262de412a9.
