### ISSUE TITLE
nix-channel --help => sh: nroff: command not found

### ISSUE THREAD

**Issue by hloeffler** [NixOS/nix#3937]
**Describe the bug**

running `nix-channel --help` gives strange output:
```
sh: nroff: command not found
```

**Steps To Reproduce**

```
# run
nix-channel --help
```

**Expected behavior**

no strange output

**`nix-env --version` output**
```
nix-env (Nix) 2.3.6
```

**Additional context**

**Comment by Kloenk** [comment]
Is it on nixos? are other manpages working (`man man` for example)?

**Comment by hloeffler** [comment]
@Kloenk Yes on nixos:
```
nixos-version 
20.03.2790.b4dac6714d7 (Markhor)

man man
man: no manual entry for 'man'
```

**Comment by hloeffler** [comment]
my fault,
i tried do build a package, and after removing it and running: nix-env -q its all good again :/
