### ISSUE TITLE
Invalid operation error

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#3943]
```
$ nix develop --override-input nixpkgs github:NixOS/nixpkgs/master
error: --- Error ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ nix
error: --- Error --- nix-daemon
invalid operation 6568
```

**Comment by Kloenk** [comment]
also: 
~~~
nix search kloenk hello
error (ignored): error: --- SysError ------------------------------------------------------------------------------------------------------------------------------- nix
writing to file: Broken pipe
error (ignored): error: --- Error ---------------------------------------------------------------------------------------------------------------------------------- nix
error: --- Error --- nix-daemon
invalid operation 96
error: --- SysError ------------------------------------------------------------------------------------------------------------------------------- nix
writing to file: Broken pipe
(use '--show-trace' to show detailed location information)
~~~
(kloenk is my flake, which reexports nixpkgs)

**Comment by B4dM4n** [comment]
I also experienced this error for a while now. Retrying the same command again helps to work around this for me.

With `printf` debugging every operation sent in `src/libstore/remote-store.cc` (B4dM4n/nix@a88714cb37df942b9a3c7d0af6fe251473f4651d), I could track down [RemoteStore::addToStore](https://github.com/NixOS/nix/blob/1c8b550e34414d0f4cb0fa20322a2dfe06ce2de0/src/libstore/remote-store.cc#L491) raising this error.

```log
...
RemoteStore::addTempRoot
RemoteStore::isValidPathUncached /nix/store/j4l4mi33hh65k6a22qc8251iglahz9sv-source
RemoteStore::queryPathInfoUncached
RemoteStore::addToStore
error (ignored): error: --- SysError --- nix
writing to file: Broken pipe
error (ignored): error: --- Error --- nix
error: --- Error --- nix-daemon
invalid operation 96
error: --- SysError --- nix
writing to file: Broken pipe
```

My current guess is, that `to.flush()` in [RemoteStore::Connection::processStderr](https://github.com/NixOS/nix/blob/1c8b550e34414d0f4cb0fa20322a2dfe06ce2de0/src/libstore/remote-store.cc#L883)
called from `stderrThread` races with a regular write from the `FramedSink`, which results in random bytes being sent to the daemon.

I'm currently testing if a short sleep (`1ms`) before `copyNAR(source, sink)` gives the `stderrThread` enough time to complete the flush to work around the error (B4dM4n/nix@520f22acd69a9341ea0c017c65722c9e4cc720b1).

**Comment by Ericson2314** [comment]
Thanks for opening this! I'll be curious if the problem with the remote builders and fixed output derivations is related.
