### ISSUE TITLE
flakes: allow un-cached evaluation with arguments or getEnv

### ISSUE THREAD

**Issue by nmattia** [NixOS/nix#3967]
I would like a special mode of evaluation where some builtins like `getEnv`, or CLI arguments, are available.

**Example**

I often use environment variables for quick tweaks in my build, as well as CLI arguments:

``` nix
{
  inputs.nixpkgs.url =
    if isNull builtins.getEnv "MY_NIXPKGS" then
      "github:NixOS/nixpkgs" else "path:" + builtins.getEnv "MY_NIXPKGS";

  outputs = { self, nixpkgs }:
    {
      packages.x86_64-linux.devShell.x86_64-linux =
        nixpkgs.outputs.legacyPackages.x86_64-linux.hello;
    };
}
```

_(note: the above fails because `inputs.nixpkgs.url` is a thunk, but let's assume something similar)_

In those cases I don't care about a cached evaluation, but I care about not having to edit the Nix code. This workflow seems to be [quite popular](https://github.com/nmattia/niv/issues/197).

It makes sense not to disable caching as soon as `getEnv` is encountered; rather a CLI flag that makes `getEnv` return something else than `""` would be nice, even if this bypasses evaluation caching.

**Comment by edolstra** [comment]
You can pass `--impure` to get access to environment variables and external source files (so e.g. `~/.config/nixpkgs` works).

**Comment by edolstra** [comment]
BTW you can use `--override-input nixpkgs /path/to/my/nixpkgs` in the example above.

**Comment by nmattia** [comment]
That's great, thanks! And in this case (`--impure`) the evaluation is not cached, correct?

**Comment by edolstra** [comment]
Yes, that's correct.
