### ISSUE TITLE
Package for Ubuntu 14.10

### ISSUE THREAD

**Issue by foomanchute** [NixOS/nix#397]
Can we please have a nix package for the latest version of Ubuntu, 14.10? It's a popular distro, the latest release is the most widely used, and it is sort of ironic to have to install a package manager, the authors of which presumably understand the value of packaging, without using a package.

I have tried to guess at the changes in release.nix but unfortunately dev-shell, which is specified in the "Hacking" instructions on the wiki to run bootstrap, seems to require an existing nix-shell, so I cannot try them. Maybe I misunderstand what bootstrapping means.

**Comment by rrnewton** [comment]
Ah, this looks neat -- but where to download the `.deb`s that are produced by that process?

**Comment by domenkozar** [comment]
http://nixos.org/releases/nix/nix-1.11.2/
