### ISSUE TITLE
nix flakes + fetchGit needs different input

### ISSUE THREAD

**Issue by tfc** [NixOS/nix#3987]
**Describe the bug**

I switched my system to nix with flakes and suddenly i have strange effects in `builtins.fetchGit` with git repos.

using `git@host:org/repo.git` does not work any longer, but `ssh://git@host/org/repo.git` does work. Is htis intended?

**Steps To Reproduce**

```
nix-repl> builtins.fetchGit { ref = "master"; rev = "15e516d23f8b9d213c83e15f5d73fc7dc37ea22a"; url = "git@github.com:tfc/cmake_cpp_example.git"; }
error: --- BadURL ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ nix
'file://git@github.com:tfc/cmake_cpp_example.git' is not a valid URL
```

**Expected behavior**

fetchgit should just work with the given inputs.

**`nix-env --version` output**

```
$ nix-env --version
nix-env (Nix) 2.4pre20200721_ff314f1
```

**Additional context**

The input in the example is as `niv` generates the parameters. Not sure if niv needs to change that in the future or if this change in nix is not intended. https://github.com/nmattia/niv/issues/276

**Comment by cole-h** [comment]
Sounds like https://github.com/NixOS/nix/issues/3503, to me.

**Comment by tfc** [comment]
true. i close this as it's a duplicate, sry.
