### ISSUE TITLE
New error format breaks tools like flycheck

### ISSUE THREAD

**Issue by endgame** [NixOS/nix#3990]
**Describe the bug**

https://github.com/flycheck/flycheck/issues/1823

**Steps To Reproduce**

As per linked issue.

**Expected behavior**

Some command-line flag that makes the error output easily parseable for downstream tools.

**`nix-env --version` output**

nix-env (Nix) 2.4pre20200721_ff314f1

**Additional context**

Strictly speaking, this isn't a Nix bug, but it's a Nix change that has caused downstream breakage. It would be really great to have a way to report errors in an easily-parsed format.

**Comment by endgame** [comment]
Fixed on flycheck's side.

**Comment by andir** [comment]
@endgame can you leave a reference to the fix? Other tools might also run into it.

**Comment by endgame** [comment]
You could find it linked in the flycheck bug in OP, but in the interests of reducing pointer chasing, here you go: https://github.com/flycheck/flycheck/pull/1826
