### ISSUE TITLE
Are experimental-features restricted or not?

### ISSUE THREAD

**Issue by endgame** [NixOS/nix#3992]
**Describe the bug**

Contradictory reports from `nix`.

**Steps To Reproduce**

Prerequisites:

* Not be a trusted user
* Not have `experimental-features = nix-command flakes` in `nix.conf`

Procedure:

```
$ nix build
error: --- Error ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix
experimental Nix feature 'nix-command' is disabled; use '--experimental-features nix-command' to override
```

But if I run with `--experimental-features`:
```
$ nix build --experimental-features 'nix-command flakes'
warning: ignoring the user-specified setting 'experimental-features', because it is a restricted setting and you are not a trusted user
- other build output snipped -
```

**Expected behavior**

`nix` should either reject the option or not display the warning.

**`nix-env --version` output**

```$ nix-env --version
nix-env (Nix) 2.4pre20200721_ff314f1```

**Comment by matthewbauer** [comment]
I think some experimental-features should require trusted user, like `ca-derivations` and `ca-references`, but `nix-command` and `flakes` don't really need to (they don't touch the store).

**Comment by endgame** [comment]
Sounds reasonable, but the warning message should be suppressed if a non-trusted user requests such a feature.
