### ISSUE TITLE
Error in text output by installation script

### ISSUE THREAD

**Issue by mvanwaveren** [NixOS/nix#3997]
**Describe the bug**

There is an error in the text output by the installation script. The text is currently:

"Okay, maybe you would like to talk to the team.

We'd love to help if you need it.

If you can, open an issue at https://github.com/nixos/nix/issues

Or, feel free to contact the team,
 - on IRC #nixos on irc.freenode.net
 - on twitter @nixos_org"

**Steps To Reproduce**

Launch the installer with "./install --daemon"
Type "y", and then "n".

**Expected behavior**

The line with
 - on IRC #nixos on irc.freenode.net
should be
 - on IRC #nixos on webchat.freenode.net

**Comment by Kloenk** [comment]
Isn't irc.freenode.net the irc address and webchat.freenode.net a web frontend, which connects to irc.freenode.net?

**Comment by mvanwaveren** [comment]
Yes, you are right. This issue does not need fixing then. I will close the issue.
