### ISSUE TITLE
Nix installation removes user from login screen at Ubuntu 20.04

### ISSUE THREAD

**Issue by khssnv** [NixOS/nix#3999]
**Describe the bug**

After Nix installation on Ubuntu 20.04 as described in "Quick install" section [https://nixos.org/download.html](https://nixos.org/download.html), user installed Nix disappears from login screen options.

**Steps To Reproduce**

1. Install Ubuntu 20.04, create user a with sudo
2. Reboot and check you can login the desktop as user created
2. Install Nix with `curl -L https://nixos.org/nix/install | sh` for the user created
3. Reboot
4. Now there is no user created in login screen

**Expected behavior**

Nix installation does not remove user from login screen options list.

**Additional context**

It does not deletes a user, but in `/var/lib/AccountsService/$USER` it sets `SystemAccount=` to `true` and if you set it back to `false` it rewrites it after reboot again. It looks a bit weird. If one could share where to dig in, I can try to fix that or at least provide more information.

Also there is no such an issue on Ubuntu 18.04.

**Setup**
```console
# uname -a
Linux myhostname 5.4.0-45-generic #49-Ubuntu SMP Wed Aug 26 13:38:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
```

**Comment by khssnv** [comment]
Closing because can't reproduce it today.

**Comment by zimbatm** [comment]
Did the user contain "nix" in its name? It's possible that there is a bug as Nix hides all the nixbld.* users that it creates.
