### ISSUE TITLE
yellow color is almost unreadable on light terminals

### ISSUE THREAD

**Issue by jorsn** [NixOS/nix#4013]
**Describe the bug**

The yellow color of nix output is almost unreadable on light terminals. Example:

![https://nextcloud.jorsn.eu/apps/files_sharing/publicpreview/E4dk9dKxjM8kz5E?x=1280&y=510&a=true&file=nix-yellow.jpg&scalingup=0](https://nextcloud.jorsn.eu/apps/files_sharing/publicpreview/E4dk9dKxjM8kz5E?x=1280&y=510&a=true&file=nix-yellow.jpg&scalingup=0)

**Steps To Reproduce**

1. Open a light terminal, e.g. `xterm -bg white -fg black`.
2. Run `nix <some nonsense>` so that nix produces an error message.

**Expected behavior**

I can read the output without effort.

**Comment by lucc** [comment]
@jorsn could it be that this is the colour setting of your terminal? So the "readability" is not the fault of nix but your terminal settings.

It seems to me that nix uses the ansi escape sequences for the predefined terminal colours. I used tmux to pipe the output including escape sequences to hexdump:
1. run `nix foo` inside tmux
2. run `tmux capturep -pe | hexdump -C` outside of tmux (you might need `-t ...` if you have more panes)

```
00001060  6f 0a 1b 5b 31 6d 1b 5b  33 31 6d 65 72 72 6f 72  |o..[1m.[31merror|
00001070  3a 1b 5b 33 34 6d 20 2d  2d 2d 20 55 73 61 67 65  |:.[34m --- Usage|
00001080  45 72 72 6f 72 20 2d 2d  2d 2d 2d 2d 2d 2d 2d 2d  |Error ----------|
00001090  2d 2d 2d 2d 2d 2d 2d 2d  2d 2d 2d 2d 2d 2d 2d 2d  |----------------|
*
000010d0  2d 2d 2d 2d 2d 2d 2d 2d  2d 2d 2d 2d 2d 2d 20 6e  |-------------- n|
000010e0  69 78 0a 1b 5b 30 6d 1b  5b 33 39 6d 1b 5b 34 39  |ix..[0m.[39m.[49|
000010f0  6d 27 1b 5b 31 6d 1b 5b  33 33 6d 66 6f 6f 1b 5b  |m'.[1m.[33mfoo.[|
00001100  30 6d 1b 5b 33 39 6d 1b  5b 34 39 6d 27 20 69 73  |0m.[39m.[49m' is|
00001110  20 6e 6f 74 20 61 20 72  65 63 6f 67 6e 69 73 65  | not a recognise|
00001120  64 20 63 6f 6d 6d 61 6e  64 0a 54 72 79 20 27 2f  |d command.Try '/|
00001130  6e 69 78 2f 73 74 6f 72  65 2f 30 6d 33 70 66 66  |nix/store/0m3pff|
00001140  70 70 6c 38 67 7a 79 34  77 68 39 62 71 71 71 37  |ppl8gzy4wh9bqqq7|
00001150  32 6e 6c 77 71 63 39 70  37 31 2d 6e 69 78 2d 32  |2nlwqc9p71-nix-2|
00001160  2e 34 70 72 65 32 30 32  30 31 32 30 31 5f 35 61  |.4pre20201201_5a|
00001170  36 64 64 62 33 2f 62 69  6e 2f 6e 69 78 20 2d 2d  |6ddb3/bin/nix --|
00001180  68 65 6c 70 27 20 66 6f  72 20 6d 6f 72 65 20 69  |help' for more i|
00001190  6e 66 6f 72 6d 61 74 69  6f 6e 2e 0a 1b 5b 33 36  |nformation...[36|
```
The escape sequence 33 is for the predefined yellow of your terminal.

**Comment by jorsn** [comment]
An easier way to find the colors: https://github.com/NixOS/nix/search?q=ANSI_YELLOW

At least in xterm, rxvt, termite, konsole, xfce-terminal, in the default settings for white background bold ANSI_YELLOW is not readable. This is because they always display bold font (escape code 1) also bright, which is not in line with the current [linux man page](https://man7.org/linux/man-pages/man4/console_codes.4.html), but is in line with [ECMA-48](https://www.ecma-international.org/publications-and-standards/standards/ecma-48/). The latter does also not define special bright colors like the man page, and indeed not every terminal supports them, e.g. the emacs terminal.

So I'd say, this color rendition is common and in the spectrum of relevant standards and conventions, and therefore Nix should be compatible with it.

**Comment by lucc** [comment]
I would just which terminal emulators would chose more sensible defaults. The standards says they might chose "bright" but does it tell them which colour to use exactly? I did not find such a comment.

**Comment by jorsn** [comment]
I think, bright yellow (my private opinion: every yellow deserving the name) is always unreadable on white background. Show me any other terminal to prove me wrong. On every terminal supporting the distinction between non-bold yellow and non-bold bright yellow, bright yellow is code 93.

Also, I'v never had any such problem with any other program than nix (in vim you can choose color schemes). I am not willing to carefully select a terminal emulator *only* because of nix output, and you absolutely cannot expect a newcomer to do it. If you cannot read Nix's error messages/string printing, that's a show-stopper if you are not already hooked. And the problem exists for some common terminals, so it is relevant.

The easiest solution of the problem would be to just set

```c++
 #define ANSI_YELLOW "\e[33m"
```

Then, there would probably be no problem with any terminal.

**Comment by ldesgoui** [comment]
I hate to challenge this issue as I understand I may come off as rude, that is not my intent

> Open a light terminal, e.g. xterm -bg white -fg black

> At least in xterm, rxvt, termite, konsole, xfce-terminal, in the default settings for white background bold ANSI_YELLOW is not readable.

From what I quoted, it seems like you're using color schemes that were designed with a dark background in mind, but with the background color overridden to white, I think that the jarring (lack of) contrast between some colors is absolutely to be expected.
The majority of the complete color themes with white background I could find have their yellows shift to gold/orange, and the contrast is completely fine.

**Comment by jorsn** [comment]
I don't find technical arguments rude. :) But I don't have to agree either.

> The majority of the complete color themes with white background I could find have their yellows shift to gold/orange, and the contrast is completely fine.

Also bright yellow?

Some people don't even know that different color schemes even exist if everything just works. Then they stumble over Nix or Nethack which are the only programs I ever encountered where not everything works any more.
