### ISSUE TITLE
nix-copy-closure doesn't substitute when using "upstream cache" feature

### ISSUE THREAD

**Issue by roberth** [NixOS/nix#4016]
**Describe the bug**

`nix-copy-closure --use-substitutes` doesn't seem to "switch" binary caches when a dependency of a path in one substituter is only present in another substituter.

This problem is exposed by Cachix's "upstream cache" feature, which omits paths from the cache when they are in `cache.nixos.org` (or potentially other caches in the future)

This is causing significant bandwidth issues when deploying a significant number of machines from a single host.

**Steps To Reproduce**

1. Push a closure to cachix cache with the upstream cache feature enabled. The starting set of the closure must only be on cachix and a dependency must only be on cache.nixos.org, the current machine and _not_ on the destination machine.
2. `nix-copy-closure` to the destination machine
3. the log will show `warning: build of '/nix/store/...', [...] failed` and then lines like `copying path '...' to 'ssh://...'`

**Expected behavior**

All paths are fetched by substitution using both substituters, not just the one that starts the closure.

**`nix-env --version` output**

```nix-env (Nix) 2.3.7```

**Additional context**

 - @domenkozar have you seen this behavior before?

 - Disabling upstream cache avoids the problem

**Comment by domenkozar** [comment]
I'm not sure what's going on, but looking at the source `queryPathInfo` https://github.com/NixOS/nix/blob/df5c69a94ef20c70bcff1602d9f00af5d32ab4e3/src/libstore/store-api.cc#L547 receives `maybeSubstitute` that is never used.

**Comment by domenkozar** [comment]
Relevant code: https://github.com/NixOS/nix/blob/2.3-maintenance/src/nix-store/nix-store.cc#L839

**Comment by domenkozar** [comment]
Looking at the code it seems like substitution failed on the machine, it could be related that binary cache wasn't setup properly. 

@roberth  Did you try substituting such path directly on the target machine?

**Comment by roberth** [comment]
The target host did seem to be configured correctly iirc, but I haven't had the opportunity to investigate this properly since. I'll close this for now.
