### ISSUE TITLE
Cannot raise maximum number of open file descriptors inside of nix build environment

### ISSUE THREAD

**Issue by xavierzwirtz** [NixOS/nix#4018]
**Is your feature request related to a problem? Please describe.**
I am attempting to transfer files to a windows virtual machine running via qemu, using virtiofsd. Small amounts of files transfer fine, however large amounts run into issues with "Too many open files". I believe this is caused by `ulimit -n` being set to 4096 inside of a nix build environment. Attempting to raise the limit via `ulimit -n 40960` fails with `ulimit: open files: cannot modify limit: Operation not permitted`.

**Describe the solution you'd like**
Provide a method for setting `ulimit -n` inside of a nix build environment.

**Describe alternatives you've considered**
I could also be using virtiofsd wrong, but from my research so far, not a way to have it clean up its file descriptors preemptively / reuse them.

**Comment by edolstra** [comment]
This shouldn't be possible for security reasons. However you should be able to raise the limit on the `nix-daemon` systemd service by setting
```
systemd.services.nix-daemon.serviceConfig.LimitNOFILE = 40960;
```
