### ISSUE TITLE
Multi-user installation fails on macOS Mojave

### ISSUE THREAD

**Issue by atcruice** [NixOS/nix#4020]
**Describe the bug**

Multi-user installation fails on macOS Mojave 10.14.6
`error: the build users group 'nixbld' has no members`

**Steps To Reproduce**

1. `$ sh <(curl -L https://nixos.org/nix/install) --daemon`
2. follow the installation instructions (accepting `sudo` etc.)
3. during `installing a bootstrapping Nix in to the default Profile`
4. `error: the build users group 'nixbld' has no members`

**Expected behavior**

Successful installation

**`nix-env --version` output**

_not applicable, unsuccessful installation_

**Additional context**

Indeed the nixbld group has no members
```
$ dscacheutil -q group -a name nixbld
name: nixbld
password: *
gid: 30000
```

They are all in the staff group:
```
$ dscacheutil -q group -a name staff
name: staff
password: *
gid: 20
users: root nixbld30 nixbld29 nixbld1 nixbld14 nixbld16 nixbld3 nixbld32 nixbld12 nixbld7 nixbld5 nixbld10 nixbld2 nixbld17 nixbld31 nixbld15 nixbld28 nixbld11 nixbld4 nixbld6 nixbld13 nixbld22 nixbld8 nixbld20 nixbld24 nixbld19 nixbld26 nixbld21 nixbld9 nixbld23 nixbld27 nixbld18 nixbld25 _serialnumberd 
```

Full output, [nix_install_failure.txt](https://github.com/NixOS/nix/files/5228754/nix_install_failure.txt)

**Comment by abathur** [comment]
I'm not sure why the group issue here and I don't have access to a multi-user install atm, but in case it saves anyone time: it looks like the build users already existed on the system. 

Here's a snippet from that part of the log:
```
Ready to continue?
[y/n] y


~~> Setting up the build group nixbld
            Exists:	Yes

~~> Setting up the build user nixbld1
            Exists:	Yes
            Hidden:	Yes
    Home Directory:	/var/empty
              Note:	Nix build user 1
   Logins Disabled:	Yes
  Member of nixbld:	Yes
    PrimaryGroupID:	30000

~~> Setting up the build user nixbld2
            Exists:	Yes
            Hidden:	Yes
    Home Directory:	/var/empty
              Note:	Nix build user 2
   Logins Disabled:	Yes
  Member of nixbld:	Yes
    PrimaryGroupID:	30000
```

These sections would indicate `Created` instead of `Exists`  (and include the sudo print for creation commands) if the users were being created.

**Comment by atcruice** [comment]
> These sections would indicate Created instead of Exists (and include the sudo print for creation commands) if the users were being created.

That's likely. I attempted the installation more than once (same failure). The full log I attached was the last attempt.

**Comment by bradparker** [comment]
For some more context I asked Alex to run the checks the install script runs on Darwin:

```
~ $ if dseditgroup -o checkmember -m nixbld1 nixbld > /dev/null 2>&1; then echo "Yep"; else echo "Nope"; fi
Yep
~ $ if dseditgroup -o checkmember -m root nixbld > /dev/null 2>&1; then echo "Yep"; else echo "Nope"; fi
Nope
```

So that check does indeed think that `nixbld1` is in `nixbld` which it isn't.

**Comment by atcruice** [comment]
Other development activity required I update to macOS Big Sur. After removing the faulty `nixbld` group and members:
```
$ dscl . -list /Users | grep nix | xargs -I % sudo dscl . -delete /Users/%
$ dscl . -delete /Groups/nixbld
```
and manually preparing the unencrypted volume, https://nixos.org/manual/nix/stable/#sect-macos-installation-recommended-notes. I was able to successfully install using:
```
$ sh <(curl -L https://nixos.org/nix/install) --daemon --darwin-use-unencrypted-nix-store-volume
```
