### ISSUE TITLE
NarInfo negative binary cache lookups should be only in-memory

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nix#4028]
So quite common scenario as a new Nix user is:

- `nix-build` .. oh this builds a huge thing, let's rather use another system and just pull from the cache
- CTRL-C
- git push
- ... wait for the build
- `nix-build` ... still building?!

The user is confused at this point that they did something wrong or that the binary cache is misbehaving, potentially losing hours investigating what's going on.

The problem is that their negative cache now has invalid/outdated entries that willt expire in an hour.

My understanding is that Nix needs negative cache within one session as it does narinfo lookups a few times, but positive cache should persist on disk while negative should be there only for the duration of the process.

**Comment by domenkozar** [comment]
This is another source of pain for beginners:

1) They don't know how binary caching works yet
2) They cache something
3) Run command, see that it's not picking up from the cache
4) Push more things to the cache
5) Run command, it's still not picking up from the cache

Figuring out what's going on requires either asking for help or losing hours to find the right bug report.

**Comment by domenkozar** [comment]
Had a short conversation yesterday with @edolstra and @alyssais.

@edolstra  raised two occasions where the negative cache is helpful:

a) `nix-build --dry-run && nix-build` which will speed up the second invocation for all the store paths that are missing in substituters

b) `nix-env -qa --status` that will display for all packages in nixpkgs if the package exists in official binary cache

I'd like to point out that according to pareto principle, those two cases do not outweight the false positives that is especially common to get when using non official binary cache.

I'd like to add that any experienced Nix developer I know has hit the false negative case and lost hours of time, mostly defaulting to impostor syndrome that they must have configured something wrong.

It's even worse for beginners are they have no idea what is going on without asking for help - there's really no other way to discover what is Nix doing besides maybe reading source and searching for similar issues on github.

if anything, we should focus on speeding up the binary cache protocol instead of implementing performance optimizations that make Nix less appealing due to it's hard nature to understand what's going on.

I'd propose to remove disk negative caching and keep the in-memory implementation.

That is going to be a huge win for beginners and marignal loss for experienced users. 

I'm fine with keeping a sane TTL default to 0 so that those that wish to use it, can.

**Comment by domenkozar** [comment]
Oh and #4462 make this even worse in case of misconfiguration.

**Comment by edolstra** [comment]
It's not clear to me why a user would lose hours of time and I don't see the "huge win for beginners". With Nix it's always possible that there is no available substitute. The fact that Nix has cached a negative lookup means there *legitimately* was a moment in time when there were no substitutes and it would have to build from source. The caching just extends that period by 1 hour at most. The best way to avoid unavailable substitutes is to ensure that a user only gets updated Nix expressions after the binary cache is up to date (hence the `nixos-*` branches in the nixpkgs repo).

Anyway the `--refresh` option now sets the binary cache TTLs to 0, so that should help a bit in this situation.

**Comment by edolstra** [comment]
It would be good if a binary cache could set its own preferred TTLs in the `nix-cache-info` file.

**Comment by domenkozar** [comment]
> It's not clear to me why a user would lose hours of time and I don't see the "huge win for beginners".

That's a good question. The beginner doesn't know Nix does negative caching, so they know the binary has been pushed to binary cache (e.g. by looking at some CI logs), but it's not substituting on their machine. So they will start with assumptions: something is wrong with their machine configuration, something is wrong the way CI pushes, there's a problem with the binary cache, etc.

>  With Nix it's always possible that there is no available substitute. The fact that Nix has cached a negative lookup means there legitimately was a moment in time when there were no substitutes and it would have to build from source. The caching just extends that period by 1 hour at most.

Yes, however that behavior is unexpected as the user is never told (and for a good reason too, as it would be too much information).

> The best way to avoid unavailable substitutes is to ensure that a user only gets updated Nix expressions after the binary cache is up to date (hence the nixos-* branches in the nixpkgs repo).

Unfortunately that's not possible from the binary cache point of view, nor from Nix tooling side. It's up to however is using them, so it's going to happen.

> It would be good if a binary cache could set its own preferred TTLs in the nix-cache-info file.

I thought about that and hoped we'd go for a simpler solution than adding more flags, but setting the default to 0 and setting TTL to 1h for cache.nixos.org is something that would go a long way.

**Comment by domenkozar** [comment]
Opened https://github.com/NixOS/nix/issues/4478

**Comment by brianmcgee** [comment]
Yeah, got burnt by this earlier in this week, exactly as @domenkozar described.

> I'd like to add that any experienced Nix developer I know has hit the false negative case and lost hours of time, mostly defaulting to impostor syndrome that they must have configured something wrong.

**Comment by DavHau** [comment]
I have also wasted hours on this in the past and I believe most admins will when setting up their own cache.
In my case I haven't set up signing correctly from the beginning and some nix clients cached verification failures for 30 days (if I remember correctly).
Even assuming the admin knows exactly how nix works, this is an extremely inconvenient scenario, as fixing this requires access to all clients.

It seems to me this problem is severe enough to justify a quick fix of some sort before waiting for the final design fix to be implemented.

**Comment by simonzkl** [comment]
I also just ran into this and wasted half an hour or so. I worked around it with `--option narinfo-cache-negative-ttl 0`.

**Comment by Narsil** [comment]
Coming here for the same reason, wasted a few hours on this. Extremely large build that I needed to do on a larger machine. The build takes 4 hours, pushed the build, got on my low machine, and couldn't pull. I was very confused why my machine wouldn't pick it up.

**Comment by waltmck** [comment]
I just wasted an hour or so on this before finding this issue after setting up my project with cachix (I assumed I had done something wrong). I completely agree with everything @domenkozar wrote.
