### ISSUE TITLE
Mixing usage of class and struct

### ISSUE THREAD

**Issue by mkenigs** [NixOS/nix#4029]
Mixing usage of class and struct generates warnings for clang builds. Example here: https://github.com/mkenigs/nix/runs/1073275637?check_suite_focus=true
```
 src/libfetchers/fetchers.hh:26:12: warning: class 'InputScheme' was previously declared as a struct [-Wmismatched-tags]
    friend class InputScheme;
           ^
src/libfetchers/fetchers.hh:22:8: note: previous use is here
struct InputScheme;
       ^
```

**Comment by Ericson2314** [comment]
I think @regnat just fixed these?

**Comment by mkenigs** [comment]
Oh yeah forgot to rebase the branch I was on :facepalm:

**Comment by mkenigs** [comment]
Although still is there any reason for inconsistent style, even if no compiler warnings? Like here: https://github.com/NixOS/nix/blob/649d3aaf2481b928120b6ce77d68b1b7c68f69e6/src/libstore/build.cc#L90-L91

**Comment by Ericson2314** [comment]
Well they default `private`/`public` dfiferently, which can be a useful shorthand.
