### ISSUE TITLE
nix-build --add-drv-link broken in nix-1.8pre

### ISSUE THREAD

**Issue by oconnorr** [NixOS/nix#403]
$ nix-build --version
nix-build (Nix) 1.8pre3866_6062b12
$ nix-build '<nixpkgs>' -A pkgs.gitAndTools.gitFull --add-drv-link
error: not an absolute path: ‘./derivation’

This works fine in nix-1.7

**Comment by edolstra** [comment]
Closing since the `--add-drv-link` flag has been removed from `nix-build`.
