### ISSUE TITLE
Add an OpenPGP signature for every tarball on nixos.org

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nix#404]
Add an OpenPGP signature for every tarball on nixos.org and instructions explaining how to verify them.  Allow to download the tarballs directly instead of piping a script to 'sh' (as done with Nix).  Sign the signing key itself and put it on the keyservers.

via IRC by "nkar"

**Comment by iElectric** [comment]
It might be worth checking out http://theupdateframework.com/

**Comment by domenkozar** [comment]
http://nixos.org/nix/download.html now contains gpg keys.
