### ISSUE TITLE
flake input url doesn't support branches with slashes

### ISSUE THREAD

**Issue by felschr** [NixOS/nix#4061]
**Describe the bug**

It seems that branches with slashes in them (e.g. `feat/flake`) aren't supported in input urls.
Neither of these work:
`"github:Myhlamaeus/pre-commit-hooks.nix/feat/flake"`
`"github:Myhlamaeus/pre-commit-hooks.nix?ref=feat/flake"`

**Steps To Reproduce**

Reference a git branch with a `/` in a flake.nix, for example:
```nix
inputs.pre-commit-hooks.url = "github:Myhlamaeus/pre-commit-hooks.nix/feat/flake";
```

**Expected behavior**
Flake should be downloaded.

**`nix-env --version` output**
nix-env (Nix) 3.0pre20200829_f156513

**Comment by felschr** [comment]
Related: https://github.com/nixos/nix/issues/3612

**Comment by Ma27** [comment]
@felschr would you mind testing #4115 :)

**Comment by edolstra** [comment]
I don't think the first one should be supported since it's pretty ambiguous.

It's better in this case to use the attrset notation:
```
inputs.pre-commit-hooks = {
  type = "github";
  owner = "Myhlamaeus";
  repo = "pre-commit-hooks.nix";
  ref = "feat/flake";
};
```

**Comment by AluisioASG** [comment]
It could be supported for the `?ref=` case though, no?

**Comment by wucke13** [comment]
So I just got:

````
$ nix run 'github:petabyteboy/nixpkgs?ref=feature/seshat2#element-desktop'
URL 'github:petabyteboy/nixpkgs?ref=feature/seshat2#element-desktop' contains an invalid branch/tag name
````

using `nix (Nix) 3.0pre20200829_f156513`. Is this a bug or is it just not supposed to work? I'm not entirely sure, reading the comments in this issue...

**Comment by Ma27** [comment]
Shouldn't this be solved with #4115 merged?

**Comment by wucke13** [comment]
Yes totally, I had an old nix3 laying in my users profile. Sorry for the noise. As far as I'm concerned, we should close this issue, it's definitely working.

**Comment by Silver-Golden** [comment]
@Ma27 I know this is an old issue but do you happen remember the logic behind parsing the ref from both the url and ``?ref=``?

Parsing it from the url causes issues for Gitlab, which has folders, there is a ticket over here: #8433
