### ISSUE TITLE
After N retries on a binary cache, be able to configure fallback behavior

### ISSUE THREAD

**Issue by jappeace** [NixOS/nix#4066]
**Is your feature request related to a problem? Please describe.**

In our CI system for some reasons we sometimes don't have access to the binary cache, either because it's offline or because random network glitches occur.
The binary cache is preferable, but it shouldn't be a requirement.

**Describe the solution you'd like**
Not having access to a binary cache doesn't mean we should give up or loop indefinitely. we should be able to configure fallback behavior to building locally for example. Which is good for a CI system.
For example:
```
nix.cacheRetries = 5;
nix.cacheUnavailableBehavior = crash | buildLocal;
```

**Describe alternatives you've considered**
We can work around this by setting a long build timeout, kill the process and rebuild without binary caches available at all.

**Additional context**

I googled around a bit and saw this also being an issue here:
https://github.com/NixOS/nix/issues/1236

**Comment by edolstra** [comment]
The `--fallback` option does this. It's not the default because we don't want a (temporary) network issue to lead to massively greater resource consumption. For instance, instead of downloading glibc from the binary cache, Nix could end up building all of stdenv, which could take hours.

**Comment by jappeace** [comment]
Thanks, that works for me.
