### ISSUE TITLE
builtins.storeDir is not documented

### ISSUE THREAD

**Issue by doronbehar** [NixOS/nix#4082]
**Describe the bug**

https://nixos.org/manual/nix/unstable/expressions/builtin-constants.html#built-in-constants doesn't mention `storeDir`.

**Comment by doronbehar** [comment]
Still an issue.

**Comment by doronbehar** [comment]
Updated link where I'd expect to find the builtins documented is:

https://nixos.org/manual/nix/unstable/expressions/builtin-constants.html?highlight=builtins#built-in-constants

**Comment by glittershark** [comment]
still relevant

**Comment by infinisil** [comment]
This was fixed in https://github.com/NixOS/nix/pull/8330 :)

https://nixos.org/manual/nix/stable/language/builtin-constants.html#builtins-storeDir
