### ISSUE TITLE
Deferring store-adding primops

### ISSUE THREAD

**Issue by Ericson2314** [NixOS/nix#4095]
**Is your feature request related to a problem? Please describe.**

Currently, primops like `builtins.cleanSource` fail when given a store path, and the `builtins.fetch*` primops also download at eval time. It would be nice to use `builtins.cleanSource` on store paths, and use `builtins.fetch*` at build time too.

**Describe the solution you'd like**
We can properly do these things at build time too. We could add a new `deferred = <bool>` attribute to control this. `false` is the default for backwards compatibility.

When any of the primops are given `deferred = true`, instead of doing anything at eval time, they become CA derivations with built-in builders (c.f. `<nix/fetchurl>`). If they have enough metadata, they are fixed CA. Otherwise, they are still disallowed, but once we implement non-determistic floating CA derivations (https://github.com/NixOS/nix/issues/520), we can allow them too.

 In particular, when `builtins.cleanSource` is given `deferred = true`, it can safely consume store paths as those just become an `inputSrcs`/`inputDrvs` entry. This one doesn't need internet access, so we can implement with (pure) floating CA derivations right away.

**Describe alternatives you've considered**
There is the expression level tricks in the nixpkgs lib to fuse together chained `builtins.cleanSource`. But this is quite brittle.

**Additional context**
See #4087 ?

CC @regnat

**Comment by Ericson2314** [comment]
This relates to the types of problems "Lazy Trees" are trying to solve.

**Comment by roberth** [comment]
Deferring `cleanSource` would require keeping the evaluator alive, or closure serialization of some sort, which is tricky in the first place and I don't feel like we can do it in a future proof, compatible, reproducible way. An effort comparable to rewriting the evaluator from scratch in my estimation.

Deferring `fetch*` is easier, relying on a stable fetcher implementation, something we've already committed to by having fetchers in the evaluator that require no narHash. No arbitrary evaluation closure. This is discussed in #9077

**Comment by Ericson2314** [comment]
Yeah it would have to be something defunctionalized for `cleanSource`, perhaps could look like (a subset of) `lib.fileset`.
