### ISSUE TITLE
Support for decentralization

### ISSUE THREAD

**Issue by iljah** [NixOS/nix#41]
Currently nix expressions can only refer to paths on the file system. It would be interesting if nix would also support fetching expressions from arbitrary (web) sources. With digital signatures it would be as secure as it currently is. Could the format be as simple as
aria2 = callPackage http://www.nixos.org/.../aria2 { };
in all-packages.nix instead of
aria2 = callPackage ../tools/networking/aria2 { };
?

0install is an example of how useful this is at least (http://0install.net/comparison.html).

**Comment by domenkozar** [comment]
Now that we have `builtins.fetchTarball` and `builtins.fetchurl` this is implemented.
