### ISSUE TITLE
'nix develop' ignores .bashrc, preventing variables from being set

### ISSUE THREAD

**Issue by lopsided98** [NixOS/nix#4104]
The `nix develop` constructs a script that is passed to bash using the `--rcfile` option. This prevents `.bashrc` from being sourced. Ostensibly, this shouldn't be too much of a problem because Nix's `rcfile` script attempts to the inherit most of the variables from the parent shell.

The problem is that my `.bashrc` doesn't export any of the variables used to control Bash's behavior, for example `PS1` and `HISTFILESIZE`, so Nix never sees them and they don't appear inside the `nix develop`.

I could fix this by exporting the relevant variables, but there is really no reason that child processes should inherit them under normal circumstances, and not sourcing `.bashrc` is bound to cause annoyances for people with more advanced setups. For one, aliases will not be available.

**Comment by guskovd** [comment]
I believe these are illogical fixes
If someone wants to source ~ / .bashrc, he can describe it explicitly in `shellHook`
