### ISSUE TITLE
asString attribute instead of outPath

### ISSUE THREAD

**Issue by roberth** [NixOS/nix#4109]
**Is your feature request related to a problem? Please describe.**

Ad-hoc behavior in the Nix language makes it harder to learn and reduces its utility.

**Describe the solution you'd like**

I'd like `${a}` to evaluate to `a.asString or a.outPath or throw .....`. Support for the `outPath` attribute will be for backward compatibility.

This way, when someone uses `nix repl` for learning, they can find the `asString` attribute, make a (correct) assumption and use `asString` as a search keyword in the docs to confirm what they just learned.

**Describe alternatives you've considered**

Don't support attribute sets at all in string interpolations. This disproportionally impacts readability of the Nix DSL.

**Additional context**

**Comment by regnat** [comment]
Unless I'm mistaken this is nearly what the `__toString` attribute does (see https://nixos.org/manual/nix/stable/#builtin-toString).

```
nix-repl> "${{ __toString = self: "foo"; }}" 
"foo"
```

 (the only difference I see is that `__toString` is a function to allow for something more elaborate than printing a fixed string)

**Comment by edolstra** [comment]
I don't understand the motivation. What about the lack of this makes the language harder to learn? It seems the opposite to me: adding more language features makes the language harder to learn.

**Comment by roberth** [comment]
@edolstra It replaces an ad-hoc language feature by one that is easier to understand.

**Comment by roberth** [comment]
@regnat Thanks! I wasn't aware of that. It seems like we could use `__toString = _: ` instead of `outPath`, making a language feature obsolete.

**Comment by roberth** [comment]
Nix is ready for this. `__toString` could already be used in Nixpkgs. Closing.
