### ISSUE TITLE
`nix run` complains about missing derivation

### ISSUE THREAD

**Issue by rickynils** [NixOS/nix#4111]
**Describe the bug**

I have a `flake.nix` with one package named `shell` and `defaultApp` pointing to that package.

Sometimes, I see the following error:

```
$ nix --version
nix (Nix) 3.0pre20200829_f156513

$ nix run
cannot build missing derivation '/nix/store/7g3s9lgl3m34vkgv5mjaakny68fhhmch-shell.drv'
```

But then I can do:

```
$ nix build .#shell
# Builds package successfully

$ nix run
# Runs the default app
```

I suspect this has something to do with garbage collection (I haven't verified that any garbage collection has been performed, but it is possible since I run GC regularly on the system where I've seen this error).

The question is, why does `nix build` work and not `nix run`?

**Comment by edolstra** [comment]
This seems to work fine now.
