### ISSUE TITLE
Error running "nix build" on latest master

### ISSUE THREAD

**Issue by joefiorini** [NixOS/nix#4113]
**Describe the bug**

I get a failure running `nix build` using code on latest master. The error is:

> got an invalid tag bit for std::optional: 0x36

**Steps To Reproduce**

1. Build nix from latest master (ad143c5 as of opening this issue)
2. Run the binary built from that nix with `nix --experimental-features "nix-command flakes" build --out-link result nixpkgs#hello`
3. Wait while it downloads the code and runs the build
4. See error mentioned above & note the lack of a "result" symlink

**Expected behavior**

I expected it to build without any errors and also to create a symlink to the result

**`nix-env --version` output**

```
bash-4.4$ nix --version
nix (Nix) 3.0pre20201005_51c2992
```

**Additional context**

Error is thrown in:

https://github.com/NixOS/nix/blob/master/src/libstore/worker-protocol.hh#L147

What is the "tag" it's looking for here? My C++ is not strong enough to figure out where this is getting called from.

```
bash-4.4$ cat /etc/os-release 
NAME="void"
ID="void"
DISTRIB_ID="void"
PRETTY_NAME="void"
```

```
bash-4.4$ uname -a
Linux planter-dev 5.8.12_1 #1 SMP Sat Sep 26 18:03:25 UTC 2020 x86_64 GNU/Linux
```

```
bash-4.4$ /lib64/libc.so.6 
GNU C Library (GNU libc) stable release version 2.30.
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 9.1.0.
libc ABIs: UNIQUE IFUNC ABSOLUTE
For bug reporting instructions, please see:
<http://www.gnu.org/software/libc/bugs.html>.
```

**Comment by edolstra** [comment]
@Ericson2314 Maybe this is related to #3895?

**Comment by Ericson2314** [comment]
The generic `std::optional` instance is older than that, but I think I might just remove it, as I thought we were only using the specialized ones which don't use tag bits anyways.

**Comment by Ericson2314** [comment]
I'm reproing this in any event; feel free to assign to me.

**Comment by Ericson2314** [comment]
I had to remove my `~/.cache/nix/fetcher-cache-v1.sqlite` due to poisoning from breaking changes that aren't yet merged, but once I did that this worked fine.

I'll try my original plan of removing those instances anyways, so you can try reproing with that PR.

**Comment by Ericson2314** [comment]
@joefiorini OK try https://github.com/NixOS/nix/pull/4120
