### ISSUE TITLE
Can't install jetbrains products on darwin because nixpkgs.jetbrains.jdk not available on x86_64-darwin

### ISSUE THREAD

**Issue by brennantaylor** [NixOS/nix#4123]
**Describe the bug**

Anything depending on `nixpkgs.jetbrains.jdk` fails on OSX because there is no OSX support.

20.03 seems to have it, 20.09 does not.

**Steps To Reproduce**

1. `nix-env -i jetbrains.idea-community`

**Expected behavior**

Package to be installed.

**`nix-env --version` output**

nix-env (Nix) 2.3.7

**Additional context**

I confirmed by checking the unstable channel

https://search.nixos.org/packages?show=jetbrains.jdk&query=jetbrains.jdk&from=0&size=30&sort=relevance&channel=unstable#disabled

You can see that the darwin platform is missing.

**Comment by Kloenk** [comment]
This seems like a nixpkgs issue.

**Comment by brennantaylor** [comment]
I'm so sorry. I'm new to the whole thing. Shall I report it over here https://github.com/NixOS/nixpkgs ?

**Comment by brennantaylor** [comment]
It looks like they already have issues filed for this, sorry for the noise. https://github.com/NixOS/nixpkgs/issues/84263
