### ISSUE TITLE
Restore the ability to build with clang on linux

### ISSUE THREAD

**Issue by regnat** [NixOS/nix#4129]
**Is your feature request related to a problem? Please describe.**

Before the migration to a flake, the `shell.nix` file took a `useClang` argument that allowed to easily use `clangStdenv` rather than the default one. This argument doesn't exist anymore, and to the best of my knowledge, the only way to use clang is to patch the `flake.nix` file

**Describe the solution you'd like**

Restore a simple way to use clang rather than gcc for the build

**Additional context**

I guess adding back use `useClang` argument isn't possible (https://github.com/NixOS/nix/issues/3843#issuecomment-661710951). Maybe it's possible to just add a new set of platforms (something like `x86_64-linux-clang` and friends) to the flake, but I'm not aware of anything on the nixpkgs side to handle that

**Comment by fzakaria** [comment]
@regnat would love to see this as a switch back + documentation in the _Hacking Docs_.

I recently made local modifications to support Clang, that were fairly straightforward. I am not familiar enough with Flakes though to make it generic.
https://gist.github.com/fzakaria/00dafaec3b3f0864d136470bf6579099

Can flakes also add additional "build modes" ?
For instance, I did some work to add sanitiziers with Clang and they needed some modifications to the LDFLAGS (i.e. removing `-z,-def` and adding `-fno-omit-stack`.
https://gist.github.com/fzakaria/eab8d14695549ddefdf9ba09038016ad
