### ISSUE TITLE
nix-env doesn't auto-create per-user profile?

### ISSUE THREAD

**Issue by wmertens** [NixOS/nix#414]
If your nix-env was originally set up by https://github.com/NixOS/nix/blob/master/scripts/nix-profile.sh.in#L5-L9 then your `~/.nix-profile` will point to `/nix/var/nix/profiles/default`.

If you then use `nix-env -i ...` and you don't have write access to that directory, it will fail to update your environment instead of creating a new environment under `/nix/var/nix/profiles/per-user/$USER/`.

It will also not give you any indication of what's happening, all you get is `error: opening lock file ‘/nix/var/nix/profiles/default.lock’: Permission denied`

Is this expected behavior? If so, what would be the best way to improve the error message?

**Comment by wmertens** [comment]
@edolstra any thoughts on this? Would you accept a PR as described above?

**Comment by kirelagin** [comment]
It would be totally nice to have a more verbose error message as suggested.
Also is it possible to create this default profile from the installation script / `make install`?

**Comment by benley** [comment]
The way NixOS handles it is to create the profile directory from the system login script.  Compare the nix-profile.sh linked above (which is the one from the deb) with this bit of the nixos shell module: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/shell.nix#L23-L62

It handles non-root users rather differently. It seems to me that the deb setup is incorrect except in the case of single-user nix installs - which is what the packages claim to support, after all.

On my ubuntu systems I've replaced /etc/profile.d/nix.sh with a tweaked version that seems to be working well for me: https://gist.github.com/benley/e4a91e8425993e7d6668

**Comment by wmertens** [comment]
@benley thanks for the pointers, I made a PR for a better nix-only version.

**Comment by robinbb** [comment]
+1

**Comment by bgamari** [comment]
The error in the case that a user lacks a writeable profile is still awful:
```
error: opening lock file '/nix/var/nix/profiles/default.lock': Permission denied
```
It would be great if this could be a bit more descriptive, as suggested by @wmertens.

**Comment by markasoftware** [comment]
I just installed NixOS 18.04, upgraded to 19.03, then added a user via `users.users` in `configuration.nix`. They had no `.nix-profile` and `nix-env -iA nixos.hello` didn't automatically create it.

**Comment by mbrgm** [comment]
@markasoftware Were you able to fix this?

**Comment by markasoftware** [comment]
@mbrgm Yes, actually, although I can't guarantee my problem was the same as yours! I discovered that the problem was in how I was switching users. After adding the new user to `configuration.nix` and running `nixos-rebuild switch`, I was switching to the user by running `su my-user-name`. However, the correct form is `su - my-user-name`. I had always thought the `-` was just to protect against usernames that looked like options, but it actually changes the behavior of `su` substantially and makes it set certain important environment variables which `nixos-env` needs to operate correctly.
