### ISSUE TITLE
nixpkgs-review: Skip packages that require manual downloading files

### ISSUE THREAD

**Issue by piegamesde** [NixOS/nix#4148]
**Disclaimer:** not sure if this is a bug or a feature request and where it belongs to.

**Describe the bug**

`nixpkgs-review` is a great tool, but it suffers from quite a lot of false positives. One reason for them is obviously broken packages not marked as broken, but those are a `nixpkgs` issue. The other reason, which I am concerned about, is packages that build (and thus are not marked as `broken`), but require some manual intervention in the build process. This may be:

- Providing a license key (for nonfree packages)
- Providing a binary
- Manually doing some other things.

**Steps To Reproduce**

See https://github.com/NixOS/nixpkgs/pull/91790. Of the 24 packages that fail to build, 8 failed because of the problem mentioned above. See `citrix_workspace`, `worldofgoo`, `sqldeveloper` and `quartus-prime-lite` as some examples.

**Expected behavior**

`nixpkgs-review` should recognize these packages and skip them, as it does for broken packages.

**`nix-env --version` output**

nix-env (Nix) 2.3.7

**Comment by cole-h** [comment]
`nixpkgs-review` isn't actually a part of Nix. Its source is located here: https://github.com/Mic92/nixpkgs-review -- you'd probably be better served filing this issue in that repo.

**Comment by piegamesde** [comment]
Thanks. I looked for a separate repository in NixOS but didn't look for repositories with other owners. Will reopen there.
