### ISSUE TITLE
nix-shell does also prepend ~/.nix-profile/bin to path -> shadows nix-shell env

### ISSUE THREAD

**Issue by blaggacao** [NixOS/nix#4152]
**Describe the bug**

- `nix-shell`
- `env | grep PATH`
- `PATH=/home/blaggacao/.nix-profile/bin:/home/blaggacao/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/nix/store/57pilyyns1gvdyw7rxjkpkca1ya667sf-aedir.k8s-env/bin ...`
- Every one of `/home/blaggacao/.nix-profile/bin:/home/blaggacao/.nix-profile/bin:/nix/var/nix/profiles/default/bin`
  - will ***shadow*** my desired custom environment `/nix/store/57pilyyns1gvdyw7rxjkpkca1ya667sf-aedir.k8s-env/bin`

**Steps To Reproduce**

I'm not sure what preconditions have to be met.
But I assume the rc loaders need to interfere:
`~/.nix-profile/etc/profile.d/nix.sh`

I also think those RC loaders are the actual culprit in the sense they don't consider being invoked by nix-shell, in which case, they should not prepend their paths (but append on the nix-shell's own paths).

**Expected behavior**

When entering a development shell, I don't expect to be silently shadowed by my local profile. For example, if the devshell pins `nix` it has no effect on my machine.

**`nix-env --version` output**

```console
$ nix-env --version
nix-env (Nix) 2.3.7
```

**Additional context**

https://github.com/numtide/devshell/issues/26 has the discussion and more details

**Comment by nh2** [comment]
Possibly related: #3321

**Comment by blaggacao** [comment]
@nh2 I think the discussion in discourse brought about an inertia about it's context when linking here. This bug was opened during the debugging journey there, but is unrelated. so #3321 is not related, in this case.

**Comment by graham33** [comment]
I'm also seeing this issue.  Is it really the expected behaviour that `~/.nix-profile/bin` is added at the front of the PATH in nix-shell?

**Comment by graham33** [comment]
FWIW, my issue was just a mistake on my part.  I'm using zsh and had added the line that sources `~/.nix-profile/etc/profile.d/nix.sh` to my `.zshrc` rather than `.zprofile`.

**Comment by blaggacao** [comment]
This issue seems to be with `numtide/devshell` which reloads any packages `./etc/profile.d`, which in case of the `nix` package has this effect.

**Comment by blaggacao** [comment]
See: https://github.com/numtide/devshell/pull/123
