### ISSUE TITLE
Traces should show local closure

### ISSUE THREAD

**Issue by cab404** [NixOS/nix#4164]
**Is your feature request related to a problem? Please describe.**
Debugging list mappings is tedious. e.g `map (s: **code that fails on 45 **)  [ 2 4 45 6 2 1] `. Currently there is no way to know that error occured on 45 without changing code.

**Describe the solution you'd like**
Since Nix is mostly pure, we can add function closure logging. — for lambda functions that would be declaration site, and other values logged literally.
That might pose problems with sets and lists (as their values are lazy), but that can be resolved by logging only already resolved parameters.

e.g
```
trace: while evaluating 'fold''
at: (55:15) in file: /nix/var/nix/profiles/per-user/root/channels/nixos/lib/lists.nix

    54|       len = length list;
    55|       fold' = n:
      |               ^
    56|         if n == len
local closure (depth=2):
  n = 5; 
  len = 10;
```

With longer parameters that could make trace more cluttered, so that feature should be optional

**Describe alternatives you've considered**
Making some sort of debugger for nix code with "double click parameter to evaluate" structure.

**Comment by roberth** [comment]
We have a debugger now, so it should be possible to get this info, but we don't have good documentation for it, and it doesn't address situations where it is difficult or impossible to interact with the evaluator, such as in packaged scripts/tools, or in CI.
Release note: https://nixos.org/manual/nix/unstable/release-notes/rl-2.9.html
