### ISSUE TITLE
Lazy `typeOf` and Friends

### ISSUE THREAD

**Issue by theNerd247** [NixOS/nix#4179]
Expressions such as:

```nix
let 
  f = x: if builtins.isString x.a then { a = 2; b = "foo"; } else { a = 2; b = "bar"; };
in
  pkgs.lib.fix f
```
evaluate to an infinite recursion error. This is due to `typeOf` being strict in its argument; in this case forcing `x` to evaluate. 

Such expressions would be easier to write if `typeOf` did not have to internally evaluate the given expression but could derive it from some internal type system (I'm not sure if such type system already exists?). I'm aware that `if` statements could pose a problem as their return type would be dependent on the value of the predicate (in such case maybe throw an error?) 

PS: The above code might be resolved once #4090 is?

**Comment by edolstra** [comment]
This isn't possible (AFAIK) without a static type system. We have to evaluate an expression to get its type. So I don't see a way to do this.
