### ISSUE TITLE
Nix flake autocomplete is broken

### ISSUE THREAD

**Issue by arianvp** [NixOS/nix#4185]
**Describe the bug**

Autocomplete just hangs forever

**Steps To Reproduce**
`nix build .#<TAB>`

**Expected behavior**

List of packages; but instead the terminal hangs forever 

**`nix (Nix) 3.0pre20201020_e0ca98`**

**Additional context**

**Comment by edolstra** [comment]
Can't reproduce, this works for me.

**Comment by regnat** [comment]
If your client and the globally installed Nix are out-of-sync, it might be linked to 

> This is a breaking change for the existing bash completion script (which can cause some minor issues if one updates the Nix client but not the script), but afaik it hasn't made it to any release yet, so it shouldn't be a major issue.

(from https://github.com/NixOS/nix/pull/4128).

It'll be a bit surprising because I'd expect bash to output some garbage completion in that case rather than nothing, but bash being bash, maybe it just goes crazy

**Comment by arianvp** [comment]
This could very well be my global bash completion conflicting. Let me check to be sure; but otherwise we can close this

**Comment by arianvp** [comment]
Can't reproduce anymore either.
