### ISSUE TITLE
Handle corrupt manifests more gracefully

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#42]
- Maybe Nix should warn about corrupt manifests rather than die.
- Maybe corrupt SQLite caches should be deleted/recreated automatically.

**Comment by ctheune** [comment]
I think we just met a very specific instance of this. We upgraded our hydra which now hands out nars using xz. Our clients' binary cache database still contain the information from narinfos that were generated with the old hydra telling them they should expect bz2 compressed data.

I haven't seen any obvious part of the code that would be able to validate this automatically. For now we'll likely just scrap our binary cache databases once, but from a usability perspective those upgrades should manage themselves. Happy to help if you point me in the right direction.

**Comment by copumpkin** [comment]
I thought manifests were dead?

**Comment by edolstra** [comment]
Indeed.

**Comment by ctheune** [comment]
For clarification and people who may stumble over this in the future: I guess I wasn't aware that narinfo != manifest, right?

**Comment by domenkozar** [comment]
@ctheune correct, manifest were for binary diffing so you didn't need to download the whole store path on "upgrade".
