### ISSUE TITLE
Why is restrict-eval a restricted setting?

### ISSUE THREAD

**Issue by spacefrogg** [NixOS/nix#4205]
**Is your feature request related to a problem? Please describe.**
I use restrict-eval to locally model the behaviour of hydra and to spot inconsistent assumptions I have about sources that need to be accessed during eval time. It is rather inconvenient to become a trusted user just to further restrict the actions of a nix-build command. Is there a compelling reason this option in handled like it is now?

**Describe the solution you'd like**
If the only thing this option does, is make nix fail earlier, I would like it to be a normal option.

**Describe alternatives you've considered**
Using sudo was the best middle ground between the need for privileges and avoiding to add myself to the list of trusted users. Still inconvenient.

**Comment by Ericson2314** [comment]
I wonder if the fact that all settings are currently part of libstore has something to do with this. If we had libnixeval settings, Nix could no more sure they don't affect the daemon (or any other store).

**Comment by dtzWill** [comment]
Maybe it is intended to (only?) allow trusted users to /disable/ it, so a global setting for this is enforced.

Maybe it could be changed to allow enabling without being trusted?

**Comment by 7c6f434c** [comment]
>Maybe it is intended to (only?) allow trusted users to /disable/ it, so a global setting for this is enforced.

Isn't it eval-only option, so changing NIX_CONF_DIR as an untrusted user should still disable it?

**Comment by edolstra** [comment]
`restrict-eval` is not restricted, AFAIK it works fine if you're not a trusted user.

> I wonder if the fact that all settings are currently part of libstore has something to do with this

This setting is in fact defined in libexpr. But it still gets sent to the daemon which is why you get a (spurious) warning.
