### ISSUE TITLE
`pure-eval` and `allow-unsafe-native-code-during-evaluation` can be enabled simultaneously

### ISSUE THREAD

**Issue by Ninlives** [NixOS/nix#4212]
I don't know whether it is a bug, a security vulnerability or by design, but you can do this in nix:
```sh
λ µ Scratch . nix repl --option allow-unsafe-native-code-during-evaluation true --option pure-eval true
Welcome to Nix version 2.3.8. Type :? for help.

nix-repl> builtins.exec [ "./getEnv.sh" "TERM" ]
"xterm-kitty"

nix-repl>  
```
I don't think this is what we want when `pure-eval` is enabled.

**Comment by bqv** [comment]
I'm quite happy with this situation, to be honest

**Comment by edolstra** [comment]
Yeah, I think this is fine. If the user enables unsafe code execution it's their responsibility to ensure it doesn't affect purity.
