### ISSUE TITLE
post-build-hook broken when using remote builders

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nix#4245]
**Describe the bug**
I tested latest nixUnstable today (Nix 2.4pre20201102_550e11f) and found that it prints an error and aborts when using `post-build-hook` and remote builders:

```
$ nix-build -A manybuilds.doit.n-0 ./test.nix -j0
this derivation will be built:
  /nix/store/rmxra1sj889xa6hra4y336ainlhzw8j5-slow-build-n-0.drv
building '/nix/store/rmxra1sj889xa6hra4y336ainlhzw8j5-slow-build-n-0.drv' on 'ssh://nix-remote-build@builder.example'...
++ sleep 2
++ touch /nix/store/nafrahq03qsv5r91hw7frs5bzjp5877f-slow-build-n-0
++ set +x
post-build-hook: Signing paths: /nix/store/nafrahq03qsv5r91hw7frs5bzjp5877f-slow-build-n-0
copying 1 paths...
copying path '/nix/store/nafrahq03qsv5r91hw7frs5bzjp5877f-slow-build-n-0' from 'ssh://nix-remote-build@builder.example'...
running post-build-hook '/etc/nix/post-build-hook.sh'...
error: --- Error --------------------------------------- nix-build
map::at
```

Both the remote and local machine has a `post-build-hook`. The remote build hook runs, but the local one does not.

This is a regression as it worked in Nix from april (I've been at https://github.com/NixOS/nix/pull/3166).

**Steps To Reproduce**

1. Configure a remote builder in `/etc/nix/machines` (e.g. `nix-remote-build@builder.example x86_64-linux /root/.ssh/id_ed25519  2  100`).
2. Add a post-build-hook script in `/etc/nix/post-build-hook.sh` with something simple like `echo post-build-hook running now`.
2. Add `post-build-hook = /etc/nix/post-build-hook.sh` to `/etc/nix/nix.conf` and restart nix-daemon.
3. Run `nix-build -j0 -A something`
4. See the local post-build-hook die with error `map::at`.

**Expected behavior**
I expect Nix to not error out and abort the build after the first derivation has been built (and the local `post-build-hook` has failed to start).

**Additional context**
The remote machine runs nix-daemon v2.3.7, which might have something to do with it. Adding `--builders ''` flag to `nix-build` avoids the issue.

**Comment by bjornfor** [comment]
I tested this again, now with nixUnstable (nix-2.4pre20201118_79aa7d9) everywhere: local client + daemon, remote (client and) daemon. Same error:

```
$ nix-build [...]
[...]
running post-build-hook '/etc/nix/post-build-hook.sh'...
error: --- Error ------------------------------------------------------------------------- nix-build
map::at
```

**Comment by regnat** [comment]
This comes from a hidden state in the build loop that's not properly updated when remote building is used.

#4326 should fix that if you can try it.

**Comment by bjornfor** [comment]
@regnat: Thanks for the patch! Unfortunately it doesn't seem to work (or another regression happend on master in the meantime):

```
$ nix-build ./test.nix 
these 2 derivations will be built:
  /nix/store/bm5xa30nacvzxmpr85plvd9vclj371v2-pkg-0.drv
  /nix/store/h59k7mvzc7hp4bgnrkz6rbgqq5dccd2k-pkg-1.drv
this path will be fetched (0.01 MiB download, 0.04 MiB unpacked):
  /nix/store/n3idfcibsmvxa1nmx2jrs0bvpxjcr31s-stdenv-linux
copying path '/nix/store/n3idfcibsmvxa1nmx2jrs0bvpxjcr31s-stdenv-linux' from 'https://cache.nixos.org'...
building '/nix/store/bm5xa30nacvzxmpr85plvd9vclj371v2-pkg-0.drv' on 'ssh://nix@buildserver'...
building '/nix/store/h59k7mvzc7hp4bgnrkz6rbgqq5dccd2k-pkg-1.drv' on 'ssh://nix@buildserver'...
copying path '/nix/store/n3idfcibsmvxa1nmx2jrs0bvpxjcr31s-stdenv-linux' from 'https://cache.nixos.org'...
error: --- Error --- build-remote
build of '/nix/store/bm5xa30nacvzxmpr85plvd9vclj371v2-pkg-0.drv' on 'ssh://nix@buildserver' failed: error: --- InvalidPath --- nix-daemon
path '/nix/store/bm5xa30nacvzxmpr85plvd9vclj371v2-pkg-0.drv' is not a valid store path
error: --- Error --- nix-daemon
builder for '/nix/store/bm5xa30nacvzxmpr85plvd9vclj371v2-pkg-0.drv' failed with exit code 1; last 1 log lines:
  copying path '/nix/store/n3idfcibsmvxa1nmx2jrs0bvpxjcr31s-stdenv-linux' from 'https://cache.nixos.org'...
error: --- Error --------------------------------------------------------------------------------------------------------- nix-build
build of '/nix/store/bm5xa30nacvzxmpr85plvd9vclj371v2-pkg-0.drv', '/nix/store/h59k7mvzc7hp4bgnrkz6rbgqq5dccd2k-pkg-1.drv' failed
$ 
$ cat test.nix
let
  pkgs = import ./default.nix {};
in
{
  p0 = pkgs.runCommand "pkg-0" {} "echo success >$out";
  p1 = pkgs.runCommand "pkg-1" {} "echo success >$out";
}
```

This time it doesn't say anything about the post-build-hook even.

**Comment by regnat** [comment]
Ek, I think my fix has broken the remote build-hook − because it now assumes that the drv file is present, which isn't the case on the remote builders. I'll try to come up with a more robust fix − and a proper testcase − later today

**Comment by bjornfor** [comment]
Thanks! I can confirm that it works now, I tested nix commit 29fbc3cf31cb318931893b2113b6e394137ec153.
