### ISSUE TITLE
nix-store -q -u and nix-store -q --deriver are not mutually inverse

### ISSUE THREAD

**Issue by kirelagin** [NixOS/nix#4259]
While trying to figure out #4258, I stumbled upon a slightly weird state of the database. As a recap of that issue, we are doing a build using haskell.nix (a lot of IFD) and provide a binary cache; in that case the cache had missing signatures and the substitution failure got cached.

The path in question is `/nix/store/ncj6d5wjlw2akq64rvdi5mmzfrb7x2qa-hpack-exe-hpack-0.34.1`.

```text
# Nix claims that it knows nothing about the path
$ nix path-info /nix/store/ncj6d5wjlw2akq64rvdi5mmzfrb7x2qa-hpack-exe-hpack-0.34.1
error: path '/nix/store/ncj6d5wjlw2akq64rvdi5mmzfrb7x2qa-hpack-exe-hpack-0.34.1' is not valid

$ nix-store -q --referrers /nix/store/ncj6d5wjlw2akq64rvdi5mmzfrb7x2qa-hpack-exe-hpack-0.34.1

$ nix-store -q -R /nix/store/ncj6d5wjlw2akq64rvdi5mmzfrb7x2qa-hpack-exe-hpack-0.34.1
error: path '/nix/store/ncj6d5wjlw2akq64rvdi5mmzfrb7x2qa-hpack-exe-hpack-0.34.1' is not valid
```

However, in the database:

```text
sqlite> select * from derivationoutputs where path='/nix/store/ncj6d5wjlw2akq64rvdi5mmzfrb7x2qa-hpack-exe-hpack-0.34.1';
60628|out|/nix/store/ncj6d5wjlw2akq64rvdi5mmzfrb7x2qa-hpack-exe-hpack-0.34.1

sqlite> select * from validpaths where id=60628;
60628|/nix/store/r42mr0dhm3ayif5r1631nil5a7mkhiyg-hpack-exe-hpack-0.34.1.drv|sha256:b87259fe49544d2b5cb19c8acaad09a322aaeede69b57c70e7db4ca38643140b|1604196422||6280|||text:sha256:1g4zijd5l4lgc3x1k6kf6pq6dxz5684qmmk7nlk1g652giljphrk
s
```

```text
# Still refuses to show me the deriver...
$ nix-store -q --deriver /nix/store/ncj6d5wjlw2akq64rvdi5mmzfrb7x2qa-hpack-exe-hpack-0.34.1
error: path '/nix/store/ncj6d5wjlw2akq64rvdi5mmzfrb7x2qa-hpack-exe-hpack-0.34.1' is not valid

# even though the deriver is there and valid.
$ nix path-info /nix/store/r42mr0dhm3ayif5r1631nil5a7mkhiyg-hpack-exe-hpack-0.34.1.drv
/nix/store/r42mr0dhm3ayif5r1631nil5a7mkhiyg-hpack-exe-hpack-0.34.1.drv

$ nix-store -q -u /nix/store/r42mr0dhm3ayif5r1631nil5a7mkhiyg-hpack-exe-hpack-0.34.1.drv
/nix/store/ncj6d5wjlw2akq64rvdi5mmzfrb7x2qa-hpack-exe-hpack-0.34.1
```

-----

I would expect `nix-store -q -u` and `nix-store -q --deriver` to always be the inverses of each other, however in this case one of them sees the connection and the other one doesn’t.

I realise that this issue report is probably not particularly useful, since I am not quite sure how to reproduce this, but stil...

**Comment by kirelagin** [comment]
When I am trying to reproduce this with a simple expression, as soon as I instantiate it, the output path becomes valid (even though it doesn’t exist in the store) and the command work as expected. My suspicion is that this is because either this path is the result of IFD or some effect of the failed substitution, and so, even though the deriver is there and valid, the output path does not get marked as valid, and thus `nix-store -q --deriver` fails without even trying to lookup the deriver, even though if it tried, it would find it.

**Comment by kirelagin** [comment]
Also, as seen in the other issue I linked, even though Nix believes the path is not valid, `nix build` tries to build it without any problems (and fails due to cached signature failure).

**Comment by edolstra** [comment]
This is by design. The deriver is only (possibly) defined for valid paths. `nix-store -q --deriver` does not scan the `DerivationOutputs` table for derivations that *could* produce the path.
