### ISSUE TITLE
Documentation for nix-store does not give criteria for signing key names

### ISSUE THREAD

**Issue by ttuegel** [NixOS/nix#4273]
The documentation for [`nix-store --generate-binary-cache-key`](https://github.com/NixOS/nix/blob/master/doc/manual/src/command-ref/nix-store.md#operation---generate-binary-cache-key) describes key names thus:

> A key name, such as cache.example.org-1, that is used to look up keys on the client when it verifies signatures. It can be anything, but it’s suggested to use the host name of your cache (e.g. cache.example.org) with a suffix denoting the number of the key (to be incremented every time you need to revoke a key).

Actually, the part before the suffix **must** be the host name used by the client to connect to the cache server. I found this out the hard way when I tried to move my cache to a new host while reusing the secret key. :grinning: The client will complain,

```
warning: substituter '...' does not have a valid signature for path '...'
```

This restriction doesn't seem to apply if the client connects directly by IP address.

If this restriction is intentional, then I think the documentation should be updated. If the restriction is not intentional, then I guess this is a bug report. :sweat_smile:

**Comment by ttuegel** [comment]
Actually, I was only able to get this working intermittently, even with the correct host name. The only reliable solution for me was to specify the IP address of the binary cache from the client. Signature validation seems to be tied to host names in some undocumented way, but it wasn't the way I originally thought. :thinking:

**Comment by andir** [comment]
On 14:17 22.11.20, Thomas Tuegel wrote:
> Actually, I was only able to get this working intermittently, even with the correct host name. The only reliable solution for me was to specify the IP address of the binary cache from the client. Signature validation seems to be tied to host names in some undocumented way, but it wasn't the way I originally thought. :thinking: 

I've a binary cache where the keys name has no correlation with the
hostname where I am serving it from yet it has been working for years.

**Comment by regnat** [comment]
That sounds stange. If nothing else, the function that checks the signature of a path isn't aware of where this path comes from (it just blindly loops through all the accepted public keys and looks whether one matches the signature). So I guess there's something else going on (maybe the old cache was trusted − `?trusted=true` − and the second not?)

**Comment by ttuegel** [comment]
The old cache wasn't trusted. At this point, I have fallen back on using IP addresses because it only works intermittently, even with the right hostname. 😕

It was suggested elsewhere to me that this could be the fault of using `nix-serve`. I don't know why that would be, but I don't have a better idea. I'll close this issue until/unless I can reproduce the issue with a static cache.
