### ISSUE TITLE
`nix-env --query` should show unfree packages by default

### ISSUE THREAD

**Issue by Havvy** [NixOS/nix#432]
While installing unfree packages with the setting `allowUnfree` set to false should throw an error message, querying for packages should show unfree packages as long as `allowUnfree` defaults to false.

Multiple users have come to IRC (myself included) asking why they cannot find the names of specific unfree packages (such as Sublime Text) using nix-env. E.g., `nix-env -qa | grep subl` returns no results by default. This is because Sublime Text is unfree, and therefore hidden from the query by default, with no easy way of finding out this is the case. We are then told about the setting, but those who do not frequent IRC or are just trying out the OS might give up at that point, losing out on a user.

There are (at least) two possible solutions to this.

The first solution is to make `allowUnfree` true by default. While there are users who do not want to ever install proprietary software, they are also smart enough to figure out how to turn this setting on if they want it. By making it true by default, you enforce their ideology on all users. For analogy, imagine if NixOS decided that for whatever reason, it favored KDE applications over GDK applications and added an `allowGDK` setting set to false by default.

The second solution is to make `--query` ignore the `allowUnfree` flag. This would make it so that the user would see the package in the list, but if `allowUnfree` is false, the user would get a clear error message when trying to install. This solution would let you have your ideological purity while placating me.

**Comment by edolstra** [comment]
This is intended behaviour. See http://lists.science.uu.nl/pipermail/nix-dev/2014-April/012916.html for more info. Summary: Nixpkgs is intended as a free software distribution, so users should be able to use it without having to worry about accidentally pulling in unfree packages.

Your second solution would be pretty nice, but not entirely trivial, because nix-env doesn't know anything about `allowUnfree`. Maybe we can implement it in Nixpkgs by making the `allowUnfree` check lazier (so that it doesn't get triggered during `nix-env -qa`).

**Comment by vcunat** [comment]
The check could be moved to a place only needed for instantiating the package derivation. Letting nix-env list unfree packages (by default) does make sense. (That's a nixpkgs issue.)

**Comment by vcunat** [comment]
I'll submit a nixpkgs PR later, after some testing.

**Comment by edolstra** [comment]
Note that simply showing the packages can be interpreted as promoting non-free software, which is something we may not want to do.

**Comment by vcunat** [comment]
Yes, I'm aware it's a borderline decision.

**Comment by vcunat** [comment]
Let's close this in favor of https://github.com/NixOS/nixpkgs/pull/5628.

**Comment by Havvy** [comment]
Sure, since the work is going on there, closing in favor that.
