### ISSUE TITLE
--out-path does not work with --json

### ISSUE THREAD

**Issue by poscat0x04** [NixOS/nix#4323]
**Describe the bug**

the flag `--out-path` has no effects on the output when `--json` is set.

**Steps To Reproduce**

1. run `nix-env -f "<nixpkgs>" -qa --json
2. run `nix-env -f "<nixpkgs>" -qa --json --out-path

**Expected behavior**

**`nix-env --version` output**

nix-env (Nix) 2.4pre20201201_5a6ddb3

**Comment by joepie91** [comment]
Also experiencing this issue. Works fine with `--xml`, but not with `--json`.

**Comment by joepie91** [comment]
Still relevant.

**Comment by joepie91** [comment]
This is no longer a problem in `nix-env (Nix) 2.11.1`.

**Comment by ncfavier** [comment]
This was fixed by https://github.com/NixOS/nix/pull/5878
