### ISSUE TITLE
--meta is always enabled when --json is set

### ISSUE THREAD

**Issue by poscat0x04** [NixOS/nix#4324]
**Describe the bug**

nix-env will always print meta information even if `--meta` is not set when `--json` is set

If you have a problem with a specific package or NixOS,
you probably want to file an issue at https://github.com/NixOS/nixpkgs/issues. 

**Steps To Reproduce**

1. run `nix-env -f "<nixpkgs>" -qa --json
2. run `nix-env -f "<nixpkgs>" -qa --json --meta

**Expected behavior**

**`nix-env --version` output**

nix-env (Nix) 2.4pre20201201_5a6ddb3

**Comment by poscat0x04** [comment]
this issue still exists

**Comment by Artturin** [comment]
Can't repro
