### ISSUE TITLE
The MacOS CI is broken

### ISSUE THREAD

**Issue by regnat** [NixOS/nix#4339]
The macOS CI has been consistently timing out for the last few days. See for example https://github.com/NixOS/nix/runs/1508687449 or https://github.com/NixOS/nix/runs/1516773113

Looking at the commit log, this seems to have been introduced by https://github.com/NixOS/nix/pull/4321.
I don't have an OSX machine handy to debug, but at a glance that could be due to Nix now trying to reach https://cache.nixos.org during the tests, which timeouts inside the darwin sandbox.
/cc @matthewbauer

**Comment by edolstra** [comment]
Yes, this is caused by always using cache.nixos.org. Before #4321, the test suite automatically didn't use cache.nixos.org because it uses a different store prefix.
