### ISSUE TITLE
Make CA derivations work with recursive Nix

### ISSUE THREAD

**Issue by regnat** [NixOS/nix#4353]
Currently running `nix` with `--experimental-features` ca-derivations in recursive-nix will most probably error out because the `queryRealisation` and `registerDrvOutput` methods are forbidden. We should implement a proper access-control to allow it when it's safe to do so

**Comment by liaowang11** [comment]
@regnat Is this related to below error? I’m using flake fro nixos configuration with ca-derivations experimental feature turned on. Have to turn off this feature manually to build my system now.
```
error: creating statement '                                                                                                        
                       insert or replace into Realisations (drvPath, outputName, outputPath, signatures)                           
                       values (?, ?, (select id from ValidPaths where path = ?), ?)                                                
                       ;                                                                                                           
                   ': SQL logic error (in '/nix/var/nix/db/db.sqlite')
```

**Comment by regnat** [comment]
@liaowang11 No, I don't think it's related. Looking at your error, I think it's due to the fact that the db schema for ca-derivations has changed and there's no migration script for it
