### ISSUE TITLE
opening lock file '/nix/store/*.lock': Permission denied

### ISSUE THREAD

**Issue by ihsanturk** [NixOS/nix#4356]
**Describe the bug**
I am locked out.

```sh
$ nix search x
opening lock file '/nix/store/k7053q8cbnyplysc319n1n1fgbkxidzd-flake-registry.json.lock': Permission denied

$ home-manager switch
error: ---SysError-----------------------------------------
opening lock file '/nix/store/lk55al9bjqqwc6nyfvkjhzdhkv81qw4n-builder.pl.lock': Permission denied

$ darwin-rebuild switch
building the system configuration...
error: ---SysError-----------------------------------------
opening lock file '/nix/store/5d171b5s2pbmsva05hrni9dp3jas6qz3-source.drv.lock': Permission denied
(use '--show-trace' to show detailed location information)
```

**Steps To Reproduce**
Sorry, I don't know how to reproduce this problem.

**`nix-env --version` output**
nix-env (Nix) 3.0pre20200829_f156513

**Additional context**

```sh
My $NIX_PATH is;

darwin-config=/Users/ihsan/.nixpkgs/darwin-configuration.nix:darwin-config=/Users/ihsan/.nixpkgs/darwin-configuration.nix:darwin=/Users/ihsan/.nix-defexpr/channels/darwin:/Users/ihsan/.nix-defexpr/channels:/nix/var/nix/profiles/per-user/root/channels
```

```sh
$ nix-channel --list
darwin https://github.com/LnL7/nix-darwin/archive/master.tar.gz
home-manager https://github.com/nix-community/home-manager/archive/master.tar.gz
nixpkgs https://github.com/nixos/nixpkgs/archive/master.tar.gz
```

**Comment by zimbatm** [comment]
What is the output for `ls -la /nix/store/`? Is the nix-daemon running or is it a single-user installation?

**Comment by ihsanturk** [comment]
I recall I did a single-user installation <sup>(please tell if there are any ways to check)</sup>. 

`nix-daemon` isn't running.
```sh
$ pgrep nix-daemon
(nothing here)
```

```sh
$ ls -la /nix/store | wc -l
10307
```

I am putting only a part of the result here.
```sh
$ ls -la /nix/store
.
..
...
.r--r--r--  3.0k ihsan  1 Jan  1970 zyn4rias48mh37qgr1s2s6qwi105jk5q-getopt-1.1.6.tar.gz.drv
.r--r--r--  2.2k ihsan  1 Jan  1970 zyrxz497ngmgrjmwqh488krabgxvrgfi-perl5.32.0-Capture-Tiny-0.48.drv
.r--r--r--  3.0k root   1 Jan  1970 zyycz7m88nlli83jrap6yzpnd902nfjx-hspec-meta-2.6.0.tar.gz.drv
.r--r--r--  4.6k ihsan  1 Jan  1970 zza9xckq0ymcky0hm554ypk8lqipl292-apple-framework-CoreAudio.drv
.r--r--r--  2.2k root   1 Jan  1970 zzbfgnd4p6472y8zy21lfadb2q9pfgfg-m-cli-0.2.5.drv
.r--r--r--  3.0k ihsan  1 Jan  1970 zzbrrnqdpgf9hi9mrb29y4lx8cqa2vrk-pandoc-2.10.1.tar.gz.drv
.r--r--r--  3.6k ihsan  1 Jan  1970 zzd0bkxxa0p8qz1zz3lhy31hkrn15sfw-source.drv
.r--r--r--  1.7k ihsan  1 Jan  1970 zzdhb63hsasgmfigxlzb9ir40jnlxrln-libimagequant-2.12.6.drv
.r--r--r--  3.7k ihsan  1 Jan  1970 zzhk1san2c1sj03s45zz64hl5vy2wllg-source.drv
.r--r--r--  7.9k ihsan  1 Jan  1970 zznf33qnjq1d6yv3ypq5wy5lpp2gyfyb-activation-script.drv
.r--r--r--  4.1k ihsan  1 Jan  1970 zznzfpnansj47945x8xf9fsc2wkr5vpw-libxml2-2.9.10.drv
.r--r--r--  3.0k ihsan  1 Jan  1970 zzp56qrnclwmwiss8idjr7zdhj7xhbab-help2man-1.47.16.tar.xz.drv
.r--r--r--  3.7k ihsan  1 Jan  1970 zzqkhf4bycc3z2rajy7gik1p4ldf0vd6-python3.8-blinker-1.4.drv
.r--r--r--   11k ihsan  1 Jan  1970 zzv5kh4r3aya6zgav84ymj2j2wb6322p-reflex-dom-pandoc-0.6.0.0.drv
.r--r--r--  1.6k ihsan  1 Jan  1970 zzw9rqrbfdfrh083pqkvq5w64sfk80gs-c-ares-1.15.0.drv

```

**Comment by ihsanturk** [comment]
I think I solved with `sudo chown -R ihsan:staff /nix/store`. Thanks for the hint @zimbatm.

**Comment by guilhermedd** [comment]
I have the same error, but `sudo chown -R MY_NAME /nix` does not seem to work. 
This is what appears to me:
`diel@Diel-PC:~/Bolsa/Bolsa_Pybatsim/pybatsim$ sudo nix-shell default.nix -A example-shell
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «string»:1:9:

            1| (import <nixpkgs> {}).bashInteractive
             |         ^
will use bash from your environment
these 2 derivations will be built:
  /nix/store/rsxf32pzkrwyg5wf8m6m50vbwync2pgs-python3.10-pybatsim-core-4.0.0-alpha+5414b272-local.drv
  /nix/store/2jii9grs10s551gksm6phaywvlp2lrlv-python3.10-pybatsim-example-entry-point-local.drv
error: opening lock file '/nix/store/3qrdi6rpmcnn74qrsnybsqgipbdsxxfy-python3.10-pybatsim-core-4.0.0-alpha+5414b272-local.lock': Permission denied`
Can anyone please help me!

**Comment by kazikwisha** [comment]
@guilhermedd .Try  `sudo chown -R YOUR_NAME:GROUP /n` . group can be `nixbld`. If that doesn't work put your NIX_PATH in `~/.bash_profile` ,instead of `~/.profile`

e.g ` export NIX_PATH=${NIX_PATH:+$NIX_PATH:}$HOME/.nix-defexpr/channels:/nix/var/nix/profiles/per-user/root/channels `.Then log out and try again
