### ISSUE TITLE
Flake inputs: git submodules/recursive checkout

### ISSUE THREAD

**Issue by SomeoneSerge** [NixOS/nix#4357]
**Is your feature request related to a problem? Please describe.**

Can't just add git url to inputs to fetch sources with submodules. 

**Describe the solution you'd like**

A `recursive: bool` field in flake inputs available when url refers to a git repo

**Describe alternatives you've considered**

Not using flake.lock or flake inputs, but instead using `fetchFromGitHub`

**Additional context**

**Comment by ruler501** [comment]
It would also be good if it copied over submodules when building devShell for a local flake. A project I'm working on needs to reference files in a git submodule to make its devShell, but the flake for it doesn't work currently since `nix develop` does not see files in submodules.

**Comment by ruler501** [comment]
It took me a while to parse through how `nix develop` fetches the files. I would propose to change `src/nix/command.hh:138` like this
```diff
-    std::string _installable{"."};
+    std::string _installable{".?submodules=1"};
```
That would allow you to not have it be unconditional for all locally referenced repos.
It would also be good if we could add it to the github scheme, but looking at the code that seems very non-trivial and people can always fall back to the git reference instead.

**Comment by con-f-use** [comment]
By the way, to add insult to injury, nix doesn't even tell that it's because you're using something from a submodule. It just says something like:

```
error: getting status of '/nix/store/qjj8lgnp70m9842n2qr4bljb3hrd04dh-source/mysubmodule': No such file or directory
```

For context, that is if "mysubmodule" is a submodule of my current flake project managed in git and I'm using a file from that project somewhere.
