### ISSUE TITLE
`nix develop --pure` is not valid (nor is `nix shell --pure`)

### ISSUE THREAD

**Issue by colemickens** [NixOS/nix#4359]
**Is your feature request related to a problem? Please describe.**

I use `nix-shell shell.nix --pure` to test and make sure my jobs will work in an extremely stripped down CI environment where only Nix is available.

I don't know how to replicate this with the nix 2.0 cli for flakes workflows. (I didn't notice this until now because I largely have to use a `shell.nix` anyway as the initial bridge from stable `nix` -> `nixUnstable`.)

**Describe the solution you'd like**
There's a `--pure` mode to use with `nix shell` and `nix develop`.

**Comment by cole-h** [comment]
What about `-i` (`--ignore-environment`)? Haven't done a lot of testing, but that might be (similar to) what you're looking for.

**Comment by colemickens** [comment]
It has slightly different behavior, but does look like what I wanted. Thanks!

**Comment by tomberek** [comment]
In case this helps anyone. ``--ignore-environment` is more hermetic than `--pure` and may have unexpected effects in conjunction with profile and rcfile's.
On NixOS one may have to add `--keep __ETC_PROFILE_DONE` or add `--norc` to the bash call. 

```
nix shell --ignore-environment nixpkgs#hello --command $SHELL --norc
nix shell --ignore-environment nixpkgs#hello --keep __ETC_PROFILE_DONE
```

while we're at it we can simulate the behavior of `nix-shell --pure` with something like this. The `_DONE` is to retain variables related to sourcing/re-sourcing profile and rc
```
nix shell --ignore-environment $( (printenv | grep _DONE |cut -f1 -d= ; printf "%s\n" HOME USER LOGNAME DISPLAY TERM IN_NIX_SHELL NIX_SHELL_PRESERVE_PROMPT TZ PAGER NIX_BUILD_SHELL SHLVL ;)|sed 's/^/--keep /')  nixpkgs#hello
```
https://github.com/NixOS/nix/blob/27444d40cf726129334899a42d68d69f73baa988/src/nix-build/nix-build.cc#L107-L109

**Comment by eclairevoyant** [comment]
This no longer works; if you run `nix shell -i nixpkgs#hello`, `hello` is no longer available as a command in the new shell.

**Comment by llakala** [comment]
I'd like to see this reopened, or a new issue created, given that the above workaround no longer works.
