### ISSUE TITLE
Retry on transient http errors

### ISSUE THREAD

**Issue by ruuda** [NixOS/nix#4362]
**Is your feature request related to a problem? Please describe.**

Nix downloads from http servers. Those servers can return non-success responses that indicate a transient problem. The one I ran into in particular is a 429 Too Many Requests served by Cachix, but I suppose 5xx statuses also occur occasionally. I don’t remember from the top of my head if I ever encountered those. This is the last output from `nix build`:

```
unable to download 'https://«redacted».cachix.org/nar/4799cf10ffa71f669e00ee4c51e353e510f0022f0e079eb617e7dc3de89de720.nar.xz': HTTP error 429
cannot build derivation '/nix/store/34236fzgmjh63rlir57ajkqq2s290iir-python3-3.7.7-env.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/2j3115sl0720f1a85gwj4xivyqj0khiz-«redacted»-default.drv': 1 dependencies couldn't be built
[0 built (1 failed), 546 copied (1 failed) (4480.8 MiB), 544.5 MiB DL]
error: build of '/nix/store/2j3115sl0720f1a85gwj4xivyqj0khiz-«redacted»-default.drv' failed
```

For a human this is no big deal, and you restart your command, but for unsupervised automation, having Nix fail because of a transient http error is annoying.

**Describe the solution you'd like**
On a transient http error (429, 500, 502, 503, 504, and [Cloudflare’s custom 520–524](https://support.cloudflare.com/hc/en-us/articles/115003011431-Troubleshooting-Cloudflare-5XX-errors)), retry with exponential backoff and jitter. If the reponse includes a [`Retry-After`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) header, it would be nice to respect it as well.

**Describe alternatives you've considered**
* Putting a retry around every `nix` call, though this is difficult, because I’m not sure if it is possible to tell from the exit code whether Nix failed due to an http error, and even then, not all http errors are appropriate for retrying on.
* Ask Cachix to relax their rate limiting, but that would only postpone the problem, and all Nix caches would benefit from having Nix do the retries.

**Additional context**

This issue might be related: https://github.com/NixOS/nix/issues/1395

cc @domenkozar, while I think this issue is best addressed in Nix itself, you might find this interesting as well.

**Comment by domenkozar** [comment]
There was a bunch of such errors yesterday for a period of an hour as I deployed rate limiting too low. That should be addressed now.

As for Nix, the errors should already be retried if you have somewhat recent Nix. What's the output of `nix-env --version` on that machine?

**Comment by ruuda** [comment]
> There was a bunch of such errors yesterday for a period of an hour as I deployed rate limiting too low. That should be addressed now.

Thanks for the quick fix!

> What's the output of nix-env --version on that machine?

```
nix-env (Nix) 2.3.3
```
Is there a more detailed changelog somewhere than [the one in the manual](https://nixos.org/manual/nix/stable/#ssec-relnotes-2.3)?

**Comment by domenkozar** [comment]
Sadly no, but https://github.com/NixOS/nix/commit/ed25fdd66e35840e1c73f283bba0671747005572 was added on 18th Feb, so I think you need 2.3.4 at least. I'd recommend upgrading to 2.3.9 since that contains almost a year of crucial fixes :)

**Comment by ruuda** [comment]
[ed25fdd66e35840e1c73f283bba0671747005572 is an ancestor of 2.3.3](https://github.com/NixOS/nix/compare/ed25fdd66e35840e1c73f283bba0671747005572...2.3.3), so it should have been in there. Maybe it did actually retry, but it failed after multiple attempts? Is there a way to configure the number of attempts?

**Comment by domenkozar** [comment]
Oh you also need https://github.com/NixOS/nix/commit/e914cfb06fd64710cb6b030b5b2c8e222745c7fb that fixes a common bug when Nix was not retrying.
