### ISSUE TITLE
scheme argument is broken for s3 store on nixUnstable

### ISSUE THREAD

**Issue by misuzu** [NixOS/nix#4365]
**Describe the bug**

I want to set up binary cache as specified in https://nixos.org/manual/nix/unstable/package-management/s3-substituter.html but `nix copy` refuses to work without https when using `nixUnstable` package.

**Steps To Reproduce**

1. Start minio
```nix
{
  services.minio = {
    enable = true;
    accessKey = "accessKey";
    secretKey = "secretKey";
  };
  systemd.services.minio.serviceConfig.StateDirectory = "minio";
}
```
2. Go to http://127.0.0.1:9000/ and create `test` bucket
3. Copy `hello` package to `test` bucket
```bash
$ export AWS_ACCESS_KEY_ID="accessKey"
$ export AWS_SECRET_ACCESS_KEY="secretKey"
$ nix build /nix/store/v5sv61sszx301i0x6xysaqzla09nksnd-hello-2.10
$ nix copy /nix/store/v5sv61sszx301i0x6xysaqzla09nksnd-hello-2.10 --to 's3://test?scheme=http&endpoint=127.0.0.1:9000'
AWS error '' (Unable to connect to endpoint with address : 127.0.0.1), will retry in 0 ms
AWS error '' (Unable to connect to endpoint with address : 127.0.0.1), will retry in 50 ms
AWS error '' (Unable to connect to endpoint with address : 127.0.0.1), will retry in 100 ms
AWS error '' (Unable to connect to endpoint with address : 127.0.0.1), will retry in 200 ms
AWS error '' (Unable to connect to endpoint with address : 127.0.0.1), will retry in 400 ms
AWS error '' (Unable to connect to endpoint with address : 127.0.0.1), will retry in 800 ms
AWS error '' (Unable to connect to endpoint with address : 127.0.0.1), will retry in 1600 ms
AWS error '' (Unable to connect to endpoint with address : 127.0.0.1), will retry in 3200 ms
AWS error '' (Unable to connect to endpoint with address : 127.0.0.1), will retry in 6400 ms
AWS error '' (Unable to connect to endpoint with address : 127.0.0.1), will retry in 12800 ms
error: --- Error --- nix
AWS error fetching 'nix-cache-info': Unable to connect to endpoint with address : 127.0.0.1
```

**Expected behavior**

The old version of nix is working fine
```bash
$ nix shell nixpkgs#nix -c nix copy /nix/store/v5sv61sszx301i0x6xysaqzla09nksnd-hello-2.10 --to 's3://test?scheme=http&endpoint=127.0.0.1:9000'
warning: unknown setting 'experimental-features'
```

**`nix-env --version` output**

```bash
$ nix-env --version
nix-env (Nix) 2.4pre20201201_5a6ddb3
$ nix shell nixpkgs#nix -c nix-env --version
warning: unknown setting 'experimental-features'
nix-env (Nix) 2.3.9
```

**Additional context**

**Comment by purefn** [comment]
I just bitten by this too. Any known workarounds - other than downgrading, that is?

**Comment by misuzu** [comment]
I'm using custom scripts with `${pkgs.nix}/bin/nix copy` inside.

**Comment by gkleen** [comment]
FWIW I debugged a little and found that [here](https://github.com/NixOS/nix/blob/1ec4efa6c82fb6d90887c21aa7c7c6f3c644dd65/src/libstore/s3-binary-cache-store.cc#L129) the `scheme` parameter is set to `s3`.
There seems to be some confusion between the `scheme` query parameter and the `scheme` url fragment (i.e. `s3://…`).

**Comment by DieracDelta** [comment]
What's the difference between the query parameter and url fragment?

At the time I was hoping for some sort of documentation on how to use s3 with `nix`. It turns out one can also just push and pull over http (and presumably https but I didn't bother to test) and this works just fine with a s3 object store: `nix flake archive --to 'http://$IP/$BUCKET .` to push and `substituters = http://$IP/$BUCKET` in the `nix.conf` file to pull.
