### ISSUE TITLE
nix sign-paths via daemon is broken on nixUnstable

### ISSUE THREAD

**Issue by misuzu** [NixOS/nix#4367]
**Describe the bug**

Signing paths via nix-daemon was working with https://github.com/NixOS/nixpkgs/commit/6625284c397b44bc9518a5a1567c1b5aae455c08 but with https://github.com/NixOS/nixpkgs/commit/8ee7c2505f9e7019aa69c8a6313e5f2d32a69f27 it's broken.
This issue is most likely introduced somewhere between versions `pre20201102_550e11f` and `pre20201118_79aa7d9`.

If you have a problem with a specific package or NixOS,
you probably want to file an issue at https://github.com/NixOS/nixpkgs/issues. 

**Steps To Reproduce**
1. Generate signing key and sign `hello` package using `nixUnstable`
```bash
$ nix-store --generate-binary-cache-key cache.example.com-1 signing-key.sec signing-key.pub
$ nix build /nix/store/v5sv61sszx301i0x6xysaqzla09nksnd-hello-2.10
$ sudo NIX_REMOTE=daemon nix sign-paths -r -k signing-key.sec /nix/store/v5sv61sszx301i0x6xysaqzla09nksnd-hello-2.10
```
2. Observe hang

**Expected behavior**

Signing must not hang.

**`nix-env --version` output**

```bash
$ nix-env --version
nix-env (Nix) 2.4pre20201201_5a6ddb3
```

**Additional context**

My current workaround:

```nix
{
  nixpkgs.overlays = [
    (self: super:
    {
      nixFlakes = super.nixFlakes.overrideAttrs (old: rec {
        name = "nix-2.4${suffix}";
        suffix = "pre20201102_550e11f";

        src = super.fetchFromGitHub {
          owner = "NixOS";
          repo = "nix";
          rev = "550e11f077ae508abde5a33998a9d4029880e7b2";
          sha256 = "186grfxsfqg7r92wgwbma66xc7p3iywn43ff7s59m4g6bvb0qgcl";
        };
      });
    })
  ];
}
```

**Comment by terlar** [comment]
I also experience this issue, really got me scratching my head (since I had not used signing before).

It would probably make sense to add signing tests that uses the `nix sign-paths` as well to here:
https://github.com/NixOS/nix/blob/master/tests/signing.sh

A slight work-around (for newly built stuff) that I found was to build and sign in one go, that worked:
```
nix build -L --secret-key-files "$PWD/cache-private-key.pem" .#defaultPackage.x86_64-linux
```
