### ISSUE TITLE
nix-env `--set` operation isn't documented

### ISSUE THREAD

**Issue by timbertson** [NixOS/nix#437]
I'm not sure if this is intentional or not, but I found it while peeking at the `nixops` code, and it seems like a useful thing for any sort of remote deployment scenario that builds locally and uses nix-copy-closure.

**Comment by armijnhemel** [comment]
Is this still a problem?

http://nixos.org/nix/manual/#operation-set-flag

**Comment by timbertson** [comment]
Nope, looks good!
