### ISSUE TITLE
nix-env --uninstall does nothing for some package

### ISSUE THREAD

**Issue by damhiya** [NixOS/nix#4386]
**Describe the bug**
When I install `libc++-7.1.0` package with `nix-env -iA nixos.libcxx`, `nix-env --uninstall libc++` does nothing.
The workaround for this problem is uninstall all the packages with `nix-env --uninstall '*'`.
It successfully uninstalls all things including `libc++-7.1.0` although it's pretty annoying to reinstall all other packages.
I know that installing library in this way is discouraged, but this seems to be bug anyway.

I don't know any other packages that causes this problem so I'm not sure whether the problem caused by `nix-env` or caused by the package.

**Steps To Reproduce**
1. Install `libc++-7.1.0` with `nix-env -iA nixos.libcxx`
2. Try to uninstall the package with `nix-env --uninstall libc++`
3. Nothing happens

**Expected behavior**
`nix-env --uninstall libc++` should uninstall the package.

**`nix-env --version` output**
`nix-env (Nix) 2.3.9`

**Additional context**
none

**Comment by bjornfor** [comment]
I'm pretty sure this is due to the pattern given to nix-env is a regex, so you'd need to use `nix-env --uninstall libc\+\+` to match the `libc++` package name. (I've made the same mistake.)

**Comment by damhiya** [comment]
> I'm pretty sure this is due to the pattern given to nix-env is a regex, so you'd need to use `nix-env --uninstall libc\+\+` to match the `libc++` package name. (I've made the same mistake.)

Oh, you're right. More accurately, `nix-env --uninstall 'libc\+\+'` or `nix-env --uninstall libc\\+\\+` worked for me (in bash)
