### ISSUE TITLE
Support bash completion for regex (escape character)

### ISSUE THREAD

**Issue by damhiya** [NixOS/nix#4388]
**Is your feature request related to a problem? Please describe.**
As described in [this issue](https://github.com/NixOS/nix/issues/4386#issue-771675387), I can't uninstall package such as `libc++` with `nix-env --uninstall libc++`
Instead, I have to add escape character like `nix-env --uninstall 'libc\+\+` or `nix-env --uninstall libc\\+\\+` to get desired result.

However, current bash completion suggests `libc++`, so It's hard to notice that it requires escape character to match correct package.

**Describe the solution you'd like**
I think it could be very helpful if bash completion suggests appropriate regex (like `'libc\+\+`) instead of raw package name (`libc++`) since `nix-env` takes regex.

**Describe alternatives you've considered**

**Additional context**

**Comment by bjornfor** [comment]
I think this repo only has completion for the new nix command. For the old/main/stable commands the completion comes from nix-bash-completions (another repo).
