### ISSUE TITLE
nixUnstable doesn't build with gcc10

### ISSUE THREAD

**Issue by luc65r** [NixOS/nix#4393]
**Describe the bug**

nixUnstable doesn't build with gcc10.
Build output: https://termbin.com/ak42o

**Steps To Reproduce**

1. get this pr https://github.com/NixOS/nixpkgs/pull/89793
2. `nix-build -A nixUnstable`

**Expected behavior**

It should build

**`nix-env --version` output**
`nix-env (Nix) 2.4pre20201201_5a6ddb3`
**Additional context**

**Comment by r-burns** [comment]
Can confirm, easy to repro here by swapping in gcc10Stdenv.

```diff
diff --git a/flake.nix b/flake.nix
index 9addccd63..f6b6a8474 100644
--- a/flake.nix
+++ b/flake.nix
@@ -115,7 +115,7 @@
       # 'nix.perl-bindings' packages.
       overlay = final: prev: {
 
-        nix = with final; with commonDeps pkgs; (stdenv.mkDerivation {
+        nix = with final; with commonDeps pkgs; (gcc10Stdenv.mkDerivation {
           name = "nix-${version}";
           inherit version;
```

**Comment by matthewbauer** [comment]
https://github.com/NixOS/nix/pull/4334/commits/0c6ceaa04610413be2f0582a44ada1824f485bef should fix this

**Comment by FRidh** [comment]
gcc 10 is now in staging-next.
