### ISSUE TITLE
builtins.length reports incorrect values

### ISSUE THREAD

**Issue by voobscout** [NixOS/nix#4398]
```nix
with builtins;
rec {
  list               = map toString [ 0 1 2 3 4 ];
  list_size          = assert length list == 5; length list; # We start counting from 1.
  list_first_element = assert elemAt list 1 == head list; head list; # Why does this fail?
}
```

**Comment by grahamc** [comment]
We start counting at 0, but there are still five elements. There is a value in positions 0 through 4, which means there are 5 positions.

**Comment by bhipple** [comment]
Nix lists are 0 indexed, as with Python, C/C++, Java, Haskell, etc.:

```console
$ python -c 'x = [0,1,2,3,4]; print(len(x)); print(x[1])'
5
1
```

There are a couple programming languages that use 1-based list indexing, such as Julia and Matlab, but most of them are 0-based.
