### ISSUE TITLE
Can't `nix eval --expr ./.#flake.output`, told that access to [the flake dir] is forbidden 

### ISSUE THREAD

**Issue by colemickens** [NixOS/nix#4401]
**Describe the bug**

I can't `nix eval` something that I can `nix build` and I need to be able to nix eval it.

```
❯ nix build "./.#i3status-rust"
# starts building...

❯ nix eval --raw --expr "./.#i3status-rust"
error: --- RestrictedPathError --------------------------------------------------------- nix
access to path '/home/cole/code/nixpkgs-wayland' is forbidden in restricted mode

❯ nix eval --raw --expr "$(pwd)#i3status-rust"
error: --- RestrictedPathError --------------------------------------------------------- nix
access to path '/home/cole/code/nixpkgs-wayland' is forbidden in restricted mode
```

**Expected behavior**

I expect to be able to eval somehow in the current dir with flakes.

**`nix-env --version` output**
```
❯ nix --version                                 
nix (Nix) 2.4pre20201201_5a6ddb3
```

**Additional context**

**Comment by Kha** [comment]
Try without `--expr`? These flake references are not valid Nix syntax but only valid on the cmdline.

**Comment by edolstra** [comment]
Try `--file` instead of `--expr`. The latter takes an expression rather than a filename (as in `nix eval --expr "1 + 2"`).
