### ISSUE TITLE
Non-interactive progress indication in Nix 2

### ISSUE THREAD

**Issue by zarybnicky** [NixOS/nix#4402]
With `nix-command` enabled, running Nix in non-interactive environments (without a tty, only stdout, like in CI/CD environments) doesn't show nearly anything as it's all being hidden by the recent work to try and create an interactive progress bar. Even with `-L -v`, the only two options that seem relevant, there is nearly no output compared to `nix-build` and other Nix 1 commands. The only alternative seems to be to use `-vv` or `-vvv` which however show too much information, compared to Nix 1, especially evaluation progress.

I would expect there to be a mechanism for detecting interactive/non-interactive output (tty/file), and for the output to be very close to the original `nix-build` (`copying path...`, `building...`) if the output is non-interactive. Without a way to recover the old behavior which was informative in both interactive and non-interactive environments, the new output format seems like a step backwards.

**Comment by NobbZ** [comment]
Even worse, I had a job failing recently when downloading exceeded ~10 minutes.

As there was no newline, there also never was a flush of output stream and the CI system has not seen any output and therefore canceled the job.

An option that would do a `\n` where currently a `\r` is done would already be great (if my assumption about how progress currently updates is correct).

**Comment by zseri** [comment]
When using `nixos-rebuild --show-trace -L -v switch` (with `nixFlakes`), it outputs many useful lines, but fails to handle the output of `ninja` properly, which just results in nothing being output, until ninja terminates, or prints warning messages...

**Comment by NobbZ** [comment]
Still relevant

**Comment by regnat** [comment]
It’s possible to get (most of) the old-style progress messages with `-v`, and the build logs by using `--log-format bar-with-logs` or `--log-format raw-with-logs`.

Maybe these should be made the default when Nix runs in a non-interactive mode :thinking:

**Comment by balsoft** [comment]
Fixed in #5918
