### ISSUE TITLE
Building of configuration via GitHub action fails with unexpected end-of-file

### ISSUE THREAD

**Issue by terlar** [NixOS/nix#4410]
**Describe the bug**

When I build my flake NixOS configuration via GitHub Actions `cachix/install-nix-action@v12`, the build consistently fails with:
```
2020-12-30T12:27:22.7686691Z killing all processes running under uid '30001'                                                                                
2020-12-30T12:27:22.7694587Z closing daemon connection because of an exception                                                                              
2020-12-30T12:27:22.7695262Z error: --- EndOfFile --- nix                                                                                                   
2020-12-30T12:27:22.7695822Z unexpected end-of-file                                                                                                         
2020-12-30T12:27:22.7696288Z download thread shutting down 
```

However if I build the same locally it works without problems.

GitHub Action uses `nix-2.4pre20201221_9fab14a` (via https://github.com/numtide/nix-flakes-installer).
Locally I use `nix (Nix) 2.4pre20201201_5a6ddb3`.

**Steps To Reproduce**

It is not very clear how to give the best instructions since it is on GitHub Actions. But I think it should be possible to:
1. Fork my repository
2. Trigger the Build workflow

**Expected behavior**

The build should work without issues.

**Additional context**

I had a working build once before:
- https://github.com/terlar/nix-config/actions/runs/451719533
I updated flake dependencies and it failed:
- https://github.com/terlar/nix-config/actions/runs/452474185

This is the diff between these builds:
https://github.com/terlar/nix-config/compare/709ab85c4cd86108ac21bf83c6f49ace75d8e088...a3c66fe3d7b0bb6d7123e5c13163a1323cca73a6

The only change between these two commits is updated `emacs-config` and `emacs-overlay` which successfully have built in the same way on another GitHub action for my repo (https://github.com/terlar/emacs-config/actions/runs/452454100). So I suspect something might go wrong with fetching cache or similar? But the error message leaves much to be desired even in super verbose mode. 

Seeing the error mentions download thread shutting down, could the issue be when it tries to fetch data from the cache?

Full build log available, but it is quite huge (I ran `nix build -vvvv`). If you have any suggestion where to put such a file I can upload it, it is 38MB gzipped.

**Comment by zimbatm** [comment]
Also seeing the same thing. I think it happens more often on CI because this error happens in the download thread and the CI disk cache is empty.

**Comment by terlar** [comment]
Yeah, it also seems to be related to cache as I got another passing build when I updated nixpkgs and most of my previous cache was invalidated. If I reran that same job that passed again, then it failed (now I had pushed the cache to cachix.) I’m quite certain that I could make it pass by removing my custom cachix cache from the substituters, but I haven’t tried that yet.

**Comment by terlar** [comment]
I don't see this issue for my GitHub Action anymore, so I guess I don't have a way to reproduce it. Not sure what changed. It hasn't failed for 2 weeks now. I did not change any part of the GitHub Action, so still the same version of Nix. But the first successful build was an update of my flake.lock file, so if something as part of that fixed it?

https://github.com/terlar/nix-config/commit/61475acddff600b93cb12360c08f679ee5ff03e2
