### ISSUE TITLE
`nix-instantiate --eval --strict -A` broken with __functor

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nix#4415]
```
> nix-instantiate --eval --strict -E '{ __functor = _: v: v; foo = {}; }.foo'
{ }
> echo '{ __functor = _: v: v; foo = {}; }' > abc.nix
> nix-instantiate --eval --strict abc.nix -A foo
error: the expression selected by the selection path 'foo' should be a set but is a function
```

I expect the last one to understand `__functor` and return `{}`.

**Comment by edolstra** [comment]
This is fundamentally ambiguous because `nix-instantiate` auto-calls functions (and thus also functors), so it's not clear whether the `foo` attribute should refer to the output or input of the functor. So the current behaviour is not really wrong.
