### ISSUE TITLE
nix flakes: provide alternative to nix-env -qa --json

### ISSUE THREAD

**Issue by andir** [NixOS/nix#4417]
**Is your feature request related to a problem? Please describe.**
`nix flake` should provide an equivalent of `nix-env -qa --json` for all those consumer of structured package data. Right now there appears to be only a human readable version (`nix flake show`) that is lacking any kind of metadata of a package (`license`, `knownVulnerabilities`, …).

**Describe the solution you'd like**
`nix flake show --json` should output the same / something similar to `nix-env -qa --json`.

**Describe alternatives you've considered**
I could just stick with `nix-env` forever but that is likely not a good idea?

**Additional context**
We have tooling that analyzes nixpkgs for security vulernabilties based on structured output of package sets. In order to continuing this effort we should not make it much harder to retrieve the package set as some structured data format.

**Comment by tomberek** [comment]
Perhaps? https://github.com/NixOS/nix/pull/5151 I'm not aware of a specific set of desired information to be included in the output.

**Comment by edolstra** [comment]
Closed via #5151.
