### ISSUE TITLE
Removing a user does not remove its profile

### ISSUE THREAD

**Issue by symphorien** [NixOS/nix#4419]
After a (unix) user is removed and nix gc is run, its profile still exists.

**Steps To Reproduce**

1. Create a new user foo
2. Login as foo, and install something `nix-env -f '<nixpkgs>' -iA hello`
3. Logout and remove foo: `userdel foo; rm -rf /home/foo`
4. Run the gc: `sudo nix-collect-garbage`
5. check that the profile of foo still exists: 
```
$  nix-store --gc --print-roots | grep foo
/nix/var/nix/gcroots/per-user/foo/current-home -> /nix/store/l3x3vch2p1bb0jhapjcpcs426zflb403-home-manager-generation
/nix/var/nix/profiles/per-user/foo/channels-1-link -> /nix/store/cwg2vrprgzwfjvknr6ynaz18m5mamk9z-user-environment
/nix/var/nix/profiles/per-user/foo/home-manager-5-link -> /nix/store/l3x3vch2p1bb0jhapjcpcs426zflb403-home-manager-generation
/nix/var/nix/profiles/per-user/foo/profile-7-link -> /nix/store/d55jkbf1lnwmvrkbxnbl3c1dvpcpanrk-user-environment
```

**Expected behavior**

foo's profile is removed, and corresponding store path are marked as dead.

**`nix-env --version` output**

nix-env (Nix) 2.3.9

**Additional context**

nixos 20.09, but probably applies to any multi-user install.

**Comment by edolstra** [comment]
This is not something Nix can fix since it doesn't have a way to plug into `userdel`. On NixOS, we could set `USERDEL_CMD` in `/etc/login.defs` to remove the user's profile.

A proper fix would be to move per-user profiles and gcroots to the user's home directory.

**Comment by symphorien** [comment]
I agree that it's impractical to hook into userdel, however the logic could be implemented in nix-collect-garbage:
just like nix-collect-garbage checks that indirect roots still exist, it could check that all per-user profiles still correspond to an existing user.

**Comment by adi-g15** [comment]
@symphorien how did you delete the user's profiles/gcroots ?
Did `USERDEL_CMD` work, I dont want my current user to be removed so didn't try that.

**Comment by symphorien** [comment]
I don't remember for sure, but I probably just removed the entries in /nix/var/nix/

**Comment by SuperSandro2000** [comment]
Just delete the user entries under ``/nix/var/nix/gcroots/per-user/$NAME`` and ``/nix/var/nix/profiles/per-user/$NAME`` and then run ``nix-collect-garbage``.

**Comment by adi-g15** [comment]
Thanks 🙏. I successfully deleted those entries.

<details>
<summary>For anyone wanting to know the reason it works</summary>
This is what I understood after reading the nix manual on garbage collection. The garbage collector considers the paths under `nix/var/nix/gcroots` and `/nix/var/nix/profiles` are considered as gcroots and so anything reachable from those directories isn't deleted by garbage collector, but by deleting the old user's specific gcroots the user-specific files/packages become unreferenced and can now be deleted by the garbage collector.
</details>
