### ISSUE TITLE
nix flakes: nix profile install always fails with "claims to be content-addressed but isn't" "because it lacks a valid signature"

### ISSUE THREAD

**Issue by arianvp** [NixOS/nix#4425]
**Describe the bug**

`nix profile install` isn't working for me

**Steps To Reproduce**

```
$ nix profile install nixpkgs#stdenv
warning: path '/nix/store/lnkmn9zqkrf3a9bk310lfb4yq95m4hml-profile' claims to be content-addressed but isn't
error: --- Error ----------------------------------------------------------------------------------------------------------------------------------------- nix
cannot add path '/nix/store/lnkmn9zqkrf3a9bk310lfb4yq95m4hml-profile' because it lacks a valid signatur
```
**Expected behavior**

the package installs in my profile

**`nix-env --version` output**
```
$ nix --version
nix (Nix) 2.4pre20201201_5a6ddb3
```

**Additional context**

**Comment by matthewbauer** [comment]
This is caused by having Nix 2.3 daemon, but Nix 2.4 client.

**Comment by arianvp** [comment]
Interesting. I installed it on NixOS through nix.package which i assumed would restart the nix daemon...

Maybe a bug in the nix module?

I'll test if I can still reproduce now that I have rebooted the machine.

**Comment by arianvp** [comment]
Ok I restarted `nix-daemon` and that got me further. It still fails though but with a different error:

```
$ nix profile install nixpkgs#stdenv
error: --- Error --------------------------------------------------------------------------------------------------------- nix
experimental Nix feature 'ca-references' is disabled; use '--experimental-features ca-references' to override
```
