### ISSUE TITLE
nix bundle'd executables do not work, fail with nix-user-chroot: No such file or directory

### ISSUE THREAD

**Issue by arianvp** [NixOS/nix#4426]
**Describe the bug**

I used `nix bundle` to build a standalone executable; however the executable doesn't work

**Steps To Reproduce**
```
$ nix bundle nixpkgs#hello
$ ldd hello
	not a dynamic executable
$ ./hello world
./nix/store/m6mcsf66rn5hc6s8n8yfb8rknxzvcwqh-startup: line 2: ./nix/store/j0rfffzsih095w4nvl6cp0zbmdiaycfs-nix-user-chroot-2c52b5f/bin/nix-user-chroot: No such file or directory
```

**Expected behavior**
the `hello` executable starts up as expected

**`nix-env --version` output**

```
nix (Nix) 2.4pre20201201_5a6ddb3
```

**Additional context**

**Comment by edolstra** [comment]
Probably better to open an issue in the https://github.com/matthewbauer/nix-bundle repo.
