### ISSUE TITLE
Nix flake stuck with `opening file '//builtin/derivation.nix': No such file or directory`

### ISSUE THREAD

**Issue by oxalica** [NixOS/nix#4430]
**Describe the bug**

I'm calling `mkDerivation` in `nixosConfiguration` but forget to pass attribute `version`, like
`pkgs.stdenv.mkDerivation { pname = "hello"; }`.
When building, nix just gets stuck after showing `opening file '//builtin/derivation.nix': No such file or directory`, using no CPU or disks, and doesn't respond to Control-C or `kill`.
I finally used `kill -9` to actually kill it.

Here's a minimal reproduction:
https://gist.github.com/oxalica/1bc8473fd23ff8e47404d90a6f5dd0f3

**Steps To Reproduce**

1. Checkout `flake.{nix,lock}` from the gist above.
2. `nixos-rebuild build --flake .#foo`
3. See the error output, and nix will stuck here without exiting.
    ```
    building the system configuration...
    error: --- SysError -------------------------------------------------------------------------- nix
    opening file '//builtin/derivation.nix': No such file or directory
    ```

**Expected behavior**
Show meaningful error message and correctly exit.

**`nix-env --version` output**
`nix-env (Nix) 2.4pre20201201_5a6ddb3`

**Additional context**

In `nix repl '<nixpkgs>'`, it produces the same confusing message. But it pointed out `required attribute 'name' missing` at least, and doesn't stuck.
```
nix-repl> stdenv.mkDerivation { pname = "foo"; }
error: --- SysError -------------------------------------------------------------------------- nix
opening file '//builtin/derivation.nix': No such file or directory
error: --- EvalError ------------------------------------------------------------------------- nix
at: (9:12) in file: //builtin/derivation.nix

required attribute 'name' missing
«derivation 
nix-repl> 
```

**Comment by edolstra** [comment]
I think this is fixed by 724b7f4fb660212a97ba6482208c299158720c5b. I get:

```
$ nix build ~/flake#nixosConfigurations.foo.config.system.build.toplevel 
error: --- EvalError ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ nix
at: (9:12) in file: //builtin/derivation.nix

required attribute 'name' missing
(use '--show-trace' to show detailed location information)
```
