### ISSUE TITLE
Flake: `inputs.<name>.patches = []`

### ISSUE THREAD

**Issue by blaggacao** [NixOS/nix#4433]
**Is your feature request related to a problem? Please describe.**
I'm very frustrated to have to aggregate two (2) PRs on `input-output-hk/haskell.nix` manually and on a fork.
- _manually_ is cumbersome, but if I was expected to go the extra mile I could do. (egoistic argument) &mdash; also consider the flake's diff's terseness when "healing" as PRs get merged.
- _on a fork_ is malign since a consumer of my flake can not easily infer that the quality of my fork is that of a work around for patch aggregation. (social argument of conserving public good faith)

**Describe the solution you'd like**
```nix
# proposal-ish - please read while gracefully complementing & subsanating
{
  inputs.foo.patches = [ # in order merged
     "abgc6h" # same remote, short form
     "refs/pull/991/head" # same remote - pull request, short form
     "github:qux/bar/master?path=path/to/reified/patch" # a **reified** patch on remote, short form
     "self:path/to/patch" # open question: proxy **reified** local patches through self?
     "./path/to/patch" # or break the classical source tree encapsulation of inputs (what would flake.lock record here?)
    { # long form (just like normal inputs)
       type = "github";
       org = "foo";
       repo = "bar";
       rev = "abgckh";
    }
  ];
}
# evaluation fails, if merge fails
# flake.lock pins patches (especially refs) as if they where regular inputs
```

How to resolve merge conflicts or a broken aggregate remains the user's problem. In that case user needs to step down from these facilities and fork (and just use plain `git` alongside).

**Describe alternatives you've considered**
- Fork &mdash; it's a) cumbersome and b) misleading &mdash; see above
- some nixery (whichery with nix) in the _output_ body which is completely out of consideration because it would additionally impart:
  - cumber
  - initelligable - ness
  - semantically poor (patches to input's source trees are _inputs_ themselves, sic!) - ness

**Additional context**
- Similar request https://github.com/NixOS/nix/issues/3920 (on wrong issue template) &mdash; I opened this here to be concise and clear.
- https://discourse.nixos.org/t/flake-patch-inputs/10854
- My gut tells me the commonality threshold is reached so in order to offload those user's facilities to `nix` (cost-benefit-positive)
- It positively impacts the terseness of flakes (see semantic gain above)
- In case conflict resolution is required on a fork, a branch naming convention of say `aggregate-whatever` can increase semantic terseness beyond the limitations of this proposal (so do suggest a convention it in the docs)

**Comment by garbas** [comment]
closing this issue in favor of #3920
