### ISSUE TITLE
Static nix complains about missing build-remote

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#4448]
E.g.

```
executing '/nix/store/jny43bzhwpl8g5w4a4znzs8npv3mwplh-nix-2.4pre20210113_4e9cec7-x86_64-unknown-linux-musl/libexec/nix/build-remote': No such file or directory
```

This could be fixed by removing the build hook mechanism (#1221) or including `build-remote` in the `nix` binary and having it `exec` itself with `argv[0]` set to `build-remote`.

**Comment by roberth** [comment]
> or including `build-remote` in the `nix` binary and having it `exec` itself with `argv[0]` set to `build-remote`.

Done in https://github.com/NixOS/nix/pull/6709
