### ISSUE TITLE
naming of multiple-outputs

### ISSUE THREAD

**Issue by vcunat** [NixOS/nix#445]
Currently the whole name is suffixed by the output name, e.g. we're getting ``boost-1.57.0-lib``. That is very unfriendly with nix-env. An easy improvement would be to make it ``boost-lib-1.57.0``.

This is one of key issues needed for integrating massive multiple-output usage in nixpkgs. Currently I don't see a direct/simple better way for nix-env to handle these than the above. ([my multiout report](https://gist.github.com/vcunat/6139ee17ae1dec684fd3#comment-1318994))

Any thoughts? Should I try to create a patch or will someone who knows the codebase do it?

**Comment by shlevy** [comment]
I'm happy to do the patch, just not sure if it's the best idea . Curious to hear from @edolstra

**Comment by vcunat** [comment]
Do you have some particular disadvantages in mind (what might get worse)?

**Comment by shlevy** [comment]
Mostly it's just that the logic for deciding what's a name and what's a version has always felt very ad-hoc to me, and of course it's a minor backwards-compat break. But not a strong objection.

**Comment by edolstra** [comment]
Well, making it part of the package name means that `nix-env -u boost` will no longer update the `lib` output. Not sure if that's the behaviour we want...

BTW it wouldn't really be a minor change since it changes the hashing scheme (e.g. NixOS system configurations would get different hashes due to the Linux kernel and other multiple-outputs packages).

**Comment by vcunat** [comment]
I assumed the package store path by itself determines the "name" nix-env sees, but I see it doesn't. I also thought I even tried that nix-env only installs ``$out``, but I see it's not so (at least now), and it seems to force to install all outputs (even with ``nix-env -iA boost.out``, unless I supply a store path directly).

Forcing all outputs is a good default, at least for the transitional period, as people were getting all without multiple outputs. That also simplifies ``nix-env -u`` semantics, which seems better than I thought.

Currently I don't see a direct/simple better way for nix-env to handle these than **what is now**. I'm sorry for the noise caused by me not digging deep enough.
