### ISSUE TITLE
Allow performing shallow clones with builtins.fetchGit

### ISSUE THREAD

**Issue by chrisxzr** [NixOS/nix#4455]
**Is your feature request related to a problem? Please describe.**
builtins.fetchGit provides no way to perform a shallow clone, which makes it much more space-efficient to clone large repositories (specifically nixpkgs) where you only want a specific revision.

**Describe the solution you'd like**
Add an option to builtins.fetchGit to specify the depth when fetching.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by JojOatXGME** [comment]
*GitHub Actions* even made `--depth 1` the default.[<sup>1</sup>] I think `--depth 1` might be a sane default for *Nix* as well considering its field of application. I guess most builds don't want to look at previous commits. Anyway, I'm not that experienced with *Nix* and making it the default would cause problems with backward compatibility.

[<sup>1</sup>]:
<https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches>
"actions/checkout: Action for checking out a repo"

**Comment by edolstra** [comment]
`builtins.fetchTree` supports shallow fetches:
```nix
builtins.fetchTree { type = "git"; url = "..."; ref = "..."; shallow = true; }
```

**Comment by yajo** [comment]
[This matrix chat](https://matrix.to/#/!PbtOpdWBSRFbEZRLIf:numtide.com/$undrdhwquhO4gAed4I2fd319F-wNKcsmz9RuiQqsBjU?via=nixos.org&via=matrix.org&via=nixos.dev) might be interesting for this problem.

Summarizing:


Method | builtins.fetchTree | builtins.fetchGit | nixpkgs.fetchgit
-- | -- | -- | --
Requires flakes enabled | yes | no | no
Requires a hash | no | no | yes (when pure)
Works with ssh agent (and remotes) | yes | yes | no

So, sadly, there's no solution that ticks all the boxes. 😕 

Besides, this is very unexpected:

```nix
# nix repl
Welcome to Nix 2.8.0pre20220318_00a6dab. Type :? for help.

nix-repl> builtins ? fetchTree
true

nix-repl> builtins.fetchTree{shallow=true;type="git";url="https://github.com/OCA/server-tools";ref="15.0";rev="47d914f73f116882b5fb04e77d64559a7697e5f6";}
error: experimental Nix feature 'flakes' is disabled; use '--extra-experimental-features flakes' to override
```

`builtins.fetchTree` is available even when not enabled.

**Comment by aviallon** [comment]
> [This matrix chat](https://matrix.to/#/!PbtOpdWBSRFbEZRLIf:numtide.com/$undrdhwquhO4gAed4I2fd319F-wNKcsmz9RuiQqsBjU?via=nixos.org&via=matrix.org&via=nixos.dev) might be interesting for this problem.
> 
> Summarizing:
> 
> Method	builtins.fetchTree	builtins.fetchGit	nixpkgs.fetchgit
> Requires flakes enabled	yes	no	no
> Requires a hash	no	no	yes (when pure)
> Works with ssh agent (and remotes)	yes	yes	no
> So, sadly, there's no solution that ticks all the boxes. confused
> 
> Besides, this is very unexpected:
> 
> ```nix
> # nix repl
> Welcome to Nix 2.8.0pre20220318_00a6dab. Type :? for help.
> 
> nix-repl> builtins ? fetchTree
> true
> 
> nix-repl> builtins.fetchTree{shallow=true;type="git";url="https://github.com/OCA/server-tools";ref="15.0";rev="47d914f73f116882b5fb04e77d64559a7697e5f6";}
> error: experimental Nix feature 'flakes' is disabled; use '--extra-experimental-features flakes' to override
> ```
> 
> `builtins.fetchTree` is available even when not enabled.

The issue, also, is that it requires an experimental feature to be enabled... there doesn't seem to be any mid-term way to have shallow clones yet.

**Comment by yajo** [comment]
Yes, and besides there's https://github.com/NixOS/nix/issues/5119.

**Comment by ZoomRmc** [comment]
The issue is closed but it's not solved still.

ref: #9376 (unfortunately, drafted and stalled), #9402
