### ISSUE TITLE
short form of fetchGit assumes master branch exists

### ISSUE THREAD

**Issue by abathur** [NixOS/nix#4456]
**Describe the bug**

The ~short `fetchGit url` form assumes master branch exists, and errors with `fatal: couldn't find remote ref refs/heads/master` if it doesn't.

**Steps To Reproduce**

1. `nix-shell -E 'fetchGit https://github.com/abathur/lilgit'`

**Expected behavior**

If it's tractable to look up the HEAD in the remote repo and fetch it, that seems better. But it wouldn't shock me if that's not tractable. :)

**`nix-env --version` output**
nix-env (Nix) 2.4pre20201205_a5d85d0

**Comment by SuperSandro2000** [comment]
Switch the master in https://github.com/NixOS/nix/blob/master/src/libfetchers/git.cc#L288 for HEAD?

**Comment by abathur** [comment]
> Switch the master in https://github.com/NixOS/nix/blob/master/src/libfetchers/git.cc#L288 for HEAD?

I think that's part of it. At least, the proposed fix in #4638 appears to do this.

**Comment by GuillaumeDesforges** [comment]
This issue blocks building with `haskell.nix` when some Haskell dependency is pulled from git and there is no `master` branch.

**Comment by abathur** [comment]
:)

**Comment by GuillaumeDesforges** [comment]
#4638 is still active indeed

**Comment by GuillaumeDesforges** [comment]
Congrats @orbekk on fixing this! :tada:

**Comment by orbekk** [comment]
@GuillaumeDesforges Thank you =)
