### ISSUE TITLE
one-by-one whitelist of non-free packages

### ISSUE THREAD

**Issue by wolftune** [NixOS/nix#447]
I appreciate that Nix blacklists non-free packages by default, but it's really unfortunate to have a single action to remove that blacklist. Anyone who isn't 100% hard-core software freedom person will choose to remove the blacklist and then all packages will seem similar.

People need to be conscious of their use of non-free packages even if they choose to use them. Please support one-by-one whitelisting of non-free packages so that I can choose to install a non-free package but still be warned / blocked about any other non-free packages in the future.

**Comment by wmertens** [comment]
See https://github.com/NixOS/nixpkgs/pull/5892 - this is a Nixpkgs issue,
not Nix. If you agree please close this issue :)

**Comment by wolftune** [comment]
Agreed, this is nixpkgs issue, but it is not identical to that other one. I don't want to whitelist a whole license, I want to whitelist package by package.

**Comment by wmertens** [comment]
You can use allowUnfreePredicate but it's not straightforward.

**Comment by wolftune** [comment]
Since you understand the item better now, just checking: you still feel this is nixpkgs and not nix issue though, yes?

**Comment by wmertens** [comment]
yup
