### ISSUE TITLE
please re-add manpage for nix-generate-patches

### ISSUE THREAD

**Issue by darealshinji** [NixOS/nix#448]
Please revert https://github.com/NixOS/nix/commit/751ae181a1ca006f2a62bd1e68b463f8f2023a8b and https://github.com/NixOS/nix/commit/e90e7b5e0adb5f11f5679db7784b30d946ea6b2e.

Why was it removed? As long as is it's listed in `doc/manual/command-ref/utilities.xml` and `doc/manual/local.mk` it'll build without any problems for me.

**Comment by domenkozar** [comment]
This is the very old way of doing binary cache with manifest. It's going away in next Nix releases, so I'm closing.
