### ISSUE TITLE
Link-local address store broke recently

### ISSUE THREAD

**Issue by maisiliym** [NixOS/nix#4490]
Link-local used to work in storl uri's. Ex
`nix copy --to ssh://root@fe80::818c:da4d:8975:415c%enp0s25 ./result`
Which is a quick way to force-push nix drvs in-extremis.

Recently (sometime in the last 2-3 months, which was the last time nix was updated), this feature broke, and now returns the error 
`don't know how to open Nix store 'ssh://root@fe80::818c:da4d:8975:415c%enp0s25'`

Variants were tried with square brackets, to no avail.

Edit: Nix built from rev 1acbb61696c118712417bcd1c59021cc84650e16 (11 days old rev)

**Comment by ajs124** [comment]
#4319 might be related

**Comment by maisiliym** [comment]
The problem is most probably with the `%{ifname}` suffix.

**Comment by blaggacao** [comment]
#4643 has additional context / links to the RFCs.

**Comment by Ma27** [comment]
To me it seems like the regex that is used on master for interpreting URIs simply doesn't take scoped IPv6 addresses into account. I'd guess that modifying the regexes in https://github.com/NixOS/nix/pull/4319/files#diff-67a0911f0f3d21c8fb70849de2cac67df46f0066d5fa548f827a4a3e6cc9a6e4R11-R12 accordingly should fix the problem.
