### ISSUE TITLE
nix run with different binary name

### ISSUE THREAD

**Issue by ihsanturk** [NixOS/nix#4498]
Some programs don't match with their executable names, e.g. 
- `ripgrep -> rg`
- `neovim -> nvim`

```sh
$ nix run nixpkgs#ripgrep
unable to execute '/nix/store/flwx9dk03037cfbqhkvlb9dv85k88gbq-ripgrep-12.1.1/bin/ripgrep': No such file or directory
```

It would be nice to detect their executable names automatically or get the specified name from a user input in arguments. Alternative solution would be to go into a `nix shell nixpkgs#ripgrep` and run the program in there but that would be a two step procedure. I would really prefer one of these commands instead of a subshell:
```
nix run nixpkgs#rg
```
or
```
nix run nixpkgs#ripgrep --exe rg
```

**Additional context**

My nix --version is: `nix (Nix) 2.4pre20201201_5a6ddb3`

**Comment by cole-h** [comment]
Would also be helpful for packages like `coreutils` that provide many different binaries.

**Comment by colemickens** [comment]
Kinda related: I still get confused when choosing between `nix run` and `nix shell`. I tend to stick with `nix shell` because I know it's the more flexible option that can do what I need. (Also `nix run` doesn't seem to allow specifying args in the flake.nix. If it did, that would be more interesting.)

**Comment by Kha** [comment]
I've noticed this issue as well. One could claim that this is what the `apps` flake attribute is for, but I dislike that it is anti-modular, requiring keeping `packages` and `apps` in sync (or maybe nixpkgs or flake-utils just needs to introduce a nice convention for deriving `apps` from `packages`, outsourcing the issue from Nix itself).

> `nix run nixpkgs#ripgrep --exe rg`

You can use `nix shell nixpkgs#ripgrep -c rg`.

> (Also `nix run` doesn't seem to allow specifying args in the flake.nix. If it did, that would be more interesting.)

Cmdline args are currently ignored anyway: #3949

**Comment by ihsanturk** [comment]
```sh
nix shell nixpkgs#ripgrep -c rg -w hello
```
Works for me. Thanks!

**Comment by garbas** [comment]
2 solutions to this problem:
- improve the error message that you should rather run `nix shell` with a `--command` flag and also show possible binaries of a package
- add a meta field to the derivation
