### ISSUE TITLE
Rename common flake commands

### ISSUE THREAD

**Issue by garbas** [NixOS/nix#4502]
Common flake commands shouldn't be inside `nix flake` subcommand.

I suggest renaming the following:
 - `nix flake init` -> `nix init`
 - `nix flake new` -> `nix new`

/cc @edolstra

**Comment by cole-h** [comment]
I disagree, solely because flakes are still experimental.

**Comment by davidak** [comment]
Wouldn't that mess up consistency?

But when this is accepted, i think `nix install` would also be OK.

**Comment by garbas** [comment]
duplicate of #4989 4989
