### ISSUE TITLE
Warn when `nix init` and `nix new` override files

### ISSUE THREAD

**Issue by garbas** [NixOS/nix#4506]
If you re-run `nix init` or `nix new` the command will happily copy new files over old ones.

I propose to change this behavior do two things:

1. Ask if user wants to overwrite a file
2. Create a backup of and old file (copy the file to `<filename>.old`) regardless if user agrees to overwrite it. We must not be known as a tool that loses work.

**Comment by bjornfor** [comment]
> Ask if user wants to overwrite a file

And disable the prompt if the user passed e.g. `--force`?

**Comment by garbas** [comment]
@bjornfor :100: there should be a global `--no-interactive` flag that would disable all interactivness and make it suitable that commands are used by other scripts.

**Comment by anka-213** [comment]
If the file is already in version control and unmodified from the checked in version, then I don't think there is any reason to keep a backup.

**Comment by edolstra** [comment]
Closing this since it's an error now if a file already exists.
