### ISSUE TITLE
Installation instructions should not encourage piping into sh

### ISSUE THREAD

**Issue by eduarrrd** [NixOS/nix#451]
If the transfer is interrupted an undefined shell script is executed.

Edit: more(?) eloquently said: http://www.seancassidy.me/dont-pipe-to-your-shell.html

**Comment by shlevy** [comment]
Does https://github.com/NixOS/nixos-homepage/commit/063b8703457de6689bc716218c3263a82aa67650 not fix this?

**Comment by eduarrrd** [comment]
@shlevy Probably yes (that depends on the failure mode). Still I believe that piping to the shell is dangerous behavior.
What would make sense IMHO would be

1. Download (potentially into tmpdir)
2. Verify hash or, even better, verify signature
3. Run

"Trust but verify" shouldn't hurt especially for something that will demand root rights on execution ...

**Comment by wmertens** [comment]
but a one-liner is a lot cuter to explain. People that worry about this
sort of thing will do what you describe by themselves.

**Comment by eduarrrd** [comment]
That's true. But sensible/safe defaults should still be set. Imagine what could have happened if the statement "people who care do the right thing" (I know you didn't say that) was more universal:
* Why not set up root as the default user and solve any permission problems that way? People who care will create user with limited rights and figure out the necessary adjustments to make it run.
* Why set up firewalls if it's easier to connect to your devices and use external services without them? If you think you're in a hostile environment and care about that you already know what to do.
* Why do auto-updating if there's a chance of something breaking? People who want updates will know how to get them or set up auto-updating themselves.
* ...

Of course those are exaggerated examples that would never happen (oh no, they did (yes, it was windows everytime, I know)). I'm just trying to make a point even if the consequences of "not piping into a shell" are not quite phenomenal.

**Comment by wmertens** [comment]
Please come up with a succinct (one line) way to install Nix that you deem
safe and put it in a PR, I'm sure that it will be considered.

You want to change
https://github.com/NixOS/nixos-homepage/blob/master/nix/index.tt#L22

**Comment by edolstra** [comment]
What verification should users be doing? Note that we serve the script and the binary tarball over https, so `curl` will already verify that the files haven't been tampered with en route... (Would be nice to have gpg signatures though.)

Also, IIRC, the installer script doesn't *require* root. It only needs it if /nix doesn't already exist.

**Comment by domenkozar** [comment]
If you trust the hash on nixos.org, you trust also the tarball. Or trust neither. Downloading from internet is dangerous but really one-liner won't go away. For reference see https://www.domenkozar.com/2015/09/27/friends-sometimes-let-friends-curl-to-shell/

We would like however to improve the trust issue if there's a real solution to it. Please reopen with a concrete suggestion.
