### ISSUE TITLE
nix-channel --update failure "src/libfetchers/tarball.cc:67" "Assertion `request.expectedETag == res.etag' failed."

### ISSUE THREAD

**Issue by 06kellyjac** [NixOS/nix#4512]
**Describe the bug**

Trying to update my nix channels

```
λ sudo nix-channel --update --show-trace
nix-channel: src/libfetchers/tarball.cc:67: nix::fetchers::DownloadFileResult nix::fetchers::downloadFile(nix::ref<nix::Store>, const string&, const string&, bool, const Headers&): Assertion `request.expectedETag == res.etag' failed.
zsh: IOT instruction  sudo nix-channel --update --show-trace
```

**Steps To Reproduce**

1. `sudo nix-channel --update`
2. error

**Expected behavior**

Channel should update successfully

**`nix-env --version` output**

```
λ nix-env --version
nix-env (Nix) 2.4pre20201201_5a6ddb3
```

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.4, NixOS, 21.03pre261422.1a57d96edd1 (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201201_5a6ddb3`
 - channels(root): `"home-manager, nixos-21.03pre265130.f217c0ea7c1, nixos-hardware"`
 - channels(user): `""`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Additional context**

**Comment by ajs124** [comment]
This might be a duplicate of  #4469

**Comment by 06kellyjac** [comment]
Looks like it, thanks @ajs124
