### ISSUE TITLE
Depencency error (probably something else but I don't know what)

### ISSUE THREAD

**Issue by cdfa** [NixOS/nix#4516]
**Describe the bug**

So I'm still quite new to nix and I may be misunderstanding something, but I'm having issues with garbage collection. I was using nix-du to find what root I should delete to free up some space, because there were no more dead paths. However, nix-du said there were a lot of dead parts and I have been discussing this with the developer in [this issue](https://github.com/symphorien/nix-du/issues/5) (also contains useful data to diagnose the issue). In the end, we conclude that there is an hnix path that is the root of a lot of paths nix-du thinks are dead (it has no parents in the graph nix-du gets from nix), but nix also says it belongs to a root that points a drv, but this makes no sense because a drv can not depend on the realised outputs (how could it be built if it would?). 

**Steps To Reproduce**

1. [This](https://github.com/cdfa/react-turn-reveal/) is the repo of which the nix.shell file got me into this situation. Nixpkgs version and some other dependencies built from GitHub are managed with niv.
2. I think [nix-direnv](https://github.com/nix-community/nix-direnv) turns it into a GC root
3. hnix-0.9.1 is a root in the nix graph (see the thread for the data), but belongs to the root from above:
```
$ nix-store --query --roots /nix/store/0l5nkm5v7l3s6fwvhc8p07c3ckl78nyz-hnix-0.9.1/
/home/cdfa/Projects/ll-node-package-example/.direnv/drv -> /nix/store/i5v9rz4abd3akwl1rjm1a3xrjqbhyab5-nix-shell.drv
$ nix-store --query --referers /nix/store/0l5nkm5v7l3s6fwvhc8p07c3ckl78nyz-hnix-0.9.1/
/nix/store/0l5nkm5v7l3s6fwvhc8p07c3ckl78nyz-hnix-0.9.1
```

**Expected behavior**

Nix and nix-du agree on which paths are dead and alive.

**`nix-env --version` output** nix-env (Nix) 2.3.8

**Comment by regnat** [comment]
> nix also says it belongs to a root that points a drv, but this makes no sense because a drv can not depend on the realised outputs (how could it be built if it would?).

There's a [keep-outputs](https://nixos.org/manual/nix/stable/#conf-keep-outputs) option that causes the gc (and `nix-store --query --roots`) to see a dependency from the derivations to their outputs. Do you happen to have it set by any chance? (`nix show-config | grep keep-outputs`)

**Comment by cdfa** [comment]
Ahh, I think that was it! keep-ouputs was indeed set to true. I guess that's something nix-du should take into account. Thanks a lot!
