### ISSUE TITLE
nix repl: multi-line input doesn't work after enabling flake command

### ISSUE THREAD

**Issue by ShamrockLee** [NixOS/nix#4518]
**Describe the bug**

After enabling flake on NixOS, `nix repl` no longer accepts multi-line inputs.
```
$ nix-shell -p nixFlakes --run "nix repl"
Welcome to Nix version 2.4pre20200721_ff314f1. Type :? for help.

nix-repl> ''
error: --- ParseError -------------------------------------------------------------- nix
at: (1:1) from string

     1| ''
      | ^
     2| 

syntax error, unexpected end of file, expecting IND_STR or DOLLAR_CURLY or IND_STRING_CLOSE

nix-repl> {
error: --- ParseError -------------------------------------------------------------- nix
at: (1:2) from string

     1| {
      |  ^
     2| 

syntax error, unexpected end of file

nix-repl> 
```

**Steps To Reproduce**
1. Enable nix flake
    * On NixOS
        1. Set up a working NixOS
        2. Activate nix flake in configuration.nix

        ```Nix
        { pkgs, ... }: {
          nix = {
            package = pkgs.nixFlakes;
            extraOptions = ''
              experimental-features = nix-command flakes
            '';
           };
        }
        ```

        3. `nixos-rebuild switch` or `nixos-rebuild boot`
    * On `nix-shell`
        1. nix-shell -p nixFlake --run "nix repl"
2. Type multi-line nix expressions such as
    ```Nix
    {
      a = 1;
    }
    ```
    or
    ```Nix
    ''
      This is the first line.
      This is the second line.
    ''
3. See error

**Expected behavior**

```
$ nix repl
Welcome to Nix version 2.3.7. Type :? for help.

nix-repl> {  
            a = 1;
            b = "bla";
          }
{ a = 1; b = "bla"; }

nix-repl> ''
            first line 
            second line
          ''
"first line\nsecond line\n"

```

**`nix-env --version` output**
```
$ /nix/var/nix/profiles/system-26-link/sw/bin/nix-env --version 
nix-env (Nix) 2.4pre20200721_ff314f1
```

**Additional context**

**Comment by regnat** [comment]
Looks like it has been fixed in master: https://github.com/NixOS/nix/commit/550e11f077ae508abde5a33998a9d4029880e7b2

(fwiw I don't think it's related to flakes at all, just happens to be in the nix version that `nixFlakes` points to)
