### ISSUE TITLE
normal allowed-users should be able to use  --substituters 

### ISSUE THREAD

**Issue by georgyo** [NixOS/nix#4520]
**Describe the bug**

When an not-trusted allowed-user trys to pass `--substituters` to a command it will bounce it with an error message of ```warning: ignoring untrusted substituter 'file:///tmp/nixstore'```

I believe this is an incorrect error and  should be allowed because
 - Nix will not accept unsigned packages, so even an untrusted substituter would now allow invalid or malicious subtitutions to be entered into the nix store.
 - Both `nix copy` and `nix-copy-closure` works with untrusted users. This means a user can still use any untrusted subsituter they want, but now have to do it run two command instead of.

Given that `nix copy` and `nix-copy-closure` show that a user can load signed packages from any substituter they want, there is no reason why passing `--substituters` to a command should reject untrusted substituters. The packages will either be signed and accepted or unsigned and rejected regardless of the subsituter.

**Steps To Reproduce**

```
# Nix 2.3
% nix run  --substituters "file:///tmp/nixstore https://cache.nixos.org/" /nix/store/ryihq763zni75rwg0xpn469mcak97rqv-nix-2.4pre20201205_a5d85d0 -c nix
warning: ignoring untrusted substituter 'file:///tmp/nixstore'
...
```

```
# Nix 2.4/3.x
% nix shell  --substituters "file:///tmp/nixstore https://cache.nixos.org/" /nix/store/ryihq763zni75rwg0xpn469mcak97rqv-nix-2.4pre20201205_a5d85d0 -c nix
warning: ignoring untrusted substituter 'file:///tmp/nixstore'
...
```

```
# All versions of nix
% nix-env --substituters "file:///tmp/nixstore https://cache.nixos.org/" -i /nix/store/ryihq763zni75rwg0xpn469mcak97rqv-nix-2.4pre20201205_a5d85d0
installing 'nix-2.4pre20201205_a5d85d0'
warning: ignoring untrusted substituter 'file:///tmp/nixstore'
...
```

```
# All versions of nix
nix copy --to file:///tmp/nixstore /nix/store/ryihq763zni75rwg0xpn469mcak97rqv-nix-2.4pre20201205_a5d85d0; echo $?
0
# This works even if the store path has already been GCed and needs to be re-imported.
nix copy --from file:///tmp/nixstore /nix/store/ryihq763zni75rwg0xpn469mcak97rqv-nix-2.4pre20201205_a5d85d0; echo $?
0
```

**Comment by edolstra** [comment]
The use of `substituters` allows all sort of shenanigans, like connecting to arbitrary SSH hosts or creating arbitrary paths in the file system. (E.g. run `nix build --substituters 'file:///fnord'` and watch the daemon create `/fnord` owned by root.) So it shouldn't be allowed by unprivileged users.

**Comment by bjornfor** [comment]
> E.g. run nix build --substituters 'file:///fnord' and watch the daemon create /fnord owned by root.

I was under the impression that --substituters was a read-only towards the nix-store. Why would the nix-daemon _create_ that path?

**Comment by georgyo** [comment]
@edolstra That sounds like a bug. Specifying something to **read** from a directory should never create the directory if it does not exist. 

But the number of edge cases I have not thought of do show me that for my use case I should just work around the limitation. 

The real flaw in my logic was that `nix copy` makes the requests as the user talking to the nix-daemon. However `--substituters` makes the requests happen as the nix-daemon user; in most cases root. Which means all permission boundaries are out the window.
