### ISSUE TITLE
Source link reported wrong for steam-run

### ISSUE THREAD

**Issue by davidak** [NixOS/nix#4527]
**Describe the bug**

When clicking on Source in steam-run package, https://github.com/NixOS/nixpkgs/blob/nixos-20.09/pkgs/build-support/trivial-builders.nix#L7 opens. But that is not the actual code.

**Steps to reproduce**

https://search.nixos.org/packages?channel=20.09&show=steam-run&from=0&size=50&sort=relevance&query=steam-run

**Expected behavior**

the correct link would be https://github.com/NixOS/nixpkgs/blob/f3d651ea9d4dab74cfca169e0294929015fc9ca6/pkgs/games/steam/fhsenv.nix#L269

**`nix-env --version` output**

**Additional context**

Ref.: https://github.com/NixOS/nixos-search/issues/281

**Comment by zimbatm** [comment]
This can be fixed in nixpkgs by adding a `meta.description` to the package. `nix edit` and friends use that key with `builtins.unsafeGetAttrPos` to locate the file where the package is described.

Unfortunately, this heuristic is the best we have for the moment.

**Comment by Atemu** [comment]
Can this be closed? I don't think it's an actionable task and rather something we should fix in Nixpkgs (if it hasn't already).
