### ISSUE TITLE
Illegal combination of CLONE_NEWPID and CLONE_PARENT build.cc

### ISSUE THREAD

**Issue by shlevy** [NixOS/nix#453]
bd0f362d introduced a call to `clone(2)` that specifies both `CLONE_NEWPID` and `CLONE_PARENT` (https://github.com/NixOS/nix/blob/bd0f362d/src/libstore/build.cc#L1946-L1947). From the man page section on `CLONE_NEWPID`:

> This flag can't be specified in conjunction with CLONE_THREAD or CLONE_PARENT.

**Comment by shlevy** [comment]
@edolstra ping

**Comment by edolstra** [comment]
Does this actually cause a problem? It works for me on Linux 3.14.27.

**Comment by shlevy** [comment]
@MarcWeber hit EINVAL, http://nixos.org/irc/logs/log.20150122 (search Invalid argument)

**Comment by edolstra** [comment]
Looks like this was allowed recently: https://github.com/torvalds/linux/commit/1f7f4dde5c945f41a7abc2285be43d918029ecc5

**Comment by edolstra** [comment]
This is Linux >= 3.13 btw.

**Comment by shlevy** [comment]
Should we disable chroot <3.13 then?

**Comment by edolstra** [comment]
Probably, though I don't know how to easily check the kernel version.

Might be easier to print a message like "you need Linux >= 3.13" if we get EINVAL from `clone()`.

**Comment by edolstra** [comment]
The patch in https://github.com/torvalds/linux/commit/1f7f4dde5c945f41a7abc2285be43d918029ecc5 is also part of recent 3.12.* kernels BTW.
