### ISSUE TITLE
Package search api

### ISSUE THREAD

**Issue by janat08** [NixOS/nix#4538]
Is there package search api? I'm looking to make electron app (gui) for searching packages.

**Comment by zimbatm** [comment]
This is more related to nixpkgs than Nix. Look at how https://search.nixos.org/packages is implemented.

**Comment by janat08** [comment]
Didn't think of that, but is there a way to get all package data, so that the search is local?

**Comment by matthewbauer** [comment]
You can try the `nix search` command which mostly handles this for you. For instance, to get nixpkgs data:

```
$ nix search --json nixpkgs > out.json
```

(it's a big file)
