### ISSUE TITLE
BUG: nix-shell requires bogus -p argument to make --expr work

### ISSUE THREAD

**Issue by cstrahan** [NixOS/nix#454]
Here's an example:

This works:

    ~/.nixpkgs/vim-plugins (master) λ nix-shell -E '(import <nixpkgs> {}).ruby' -p bash
    
    [nix-shell:~/.nixpkgs/vim-plugins]$ irb
    irb(main):001:0> exit
    
    [nix-shell:~/.nixpkgs/vim-plugins]$ exit
    exit

But this does not:

    ~/.nixpkgs/vim-plugins (master) λ nix-shell -E '(import <nixpkgs> {}).ruby'
    
    [nix-shell:~/.nixpkgs/vim-plugins]$ irb
    The program ‘irb’ is currently not installed. You can install it by typing:
      nix-env -i ruby

**Comment by edolstra** [comment]
This is actually intended behaviour! `nix-shell` gives you a shell containing the build environment of the specified derivation, not the output of the derivation. So `nix-shell -E '...ruby'` won't give you ruby but an environment for building ruby.

`nix-shell -p` is the exception in that it gives you the actual packages. `-p ruby` really just syntactic sugar for:
```
$ nix-shell -E 'with import <nixpkgs> {}; runCommand "dummy" { buildInputs = [ ruby ]; } ""'
```

**Comment by cstrahan** [comment]
> `nix-shell` gives you a shell containing the build environment of the specified derivation, not the output of the derivation.

I understood that, but it appears I misunderstood how `-E` was intended to work: I figured that should be treated as another build input, not as the derivation from which the build environment would be derived (i.e. I didn't see it as an alternative to `shell.nix`). It's a little confusing that it more-or-less behaves as I suggest *when given a `-p` flag*, but doesn't otherwise.

Right now, the current behavior is:

* If no `-p` is given, the expression given by `-E` is the derivation from which the build environment is derived
* If `-p` *is* given, the expression given by `-E` is now a build input instead, and the derivation is now:

```Nix
with import <nixpkgs> { };
runCommand "shell" {
  buildInputs = [ /*... insert both -p and -E exprs here ...*/ ];
} "";
```

That's some really subtle/surprising interplay between those two flags. I'm suggesting that `-E` should stick to being one or the other - either the build input or the derivation itself. Now that I think of it as an alternative to defaulting to `shell.nix`/`default.nix`, I think the latter is the way to go (which, I believe, is what you were just stating, too). If we go that direction, what do we do about `-p` and `-E` being used together? These are questions I think we ought to further consider. The current behavior isn't intuitive.

Given the way `nix-shell` is currently written, it appears I can do what I want by just using a full expression with something like: `-p "(expr)"`.

**Comment by edolstra** [comment]
We should probably just give an error message if `-p` and `-E` are both given.

We can also automatically add parentheses in the generated `buildInputs`, so you can type `nix-shell -p "expr"` instead of `"(expr").

**Comment by cstrahan** [comment]
:+1:
