### ISSUE TITLE
nix develop fails for some packages.

### ISSUE THREAD

**Issue by ishan9299** [NixOS/nix#4540]
**Describe the bug**
When using `nix develop nixpkgs#glfw` the command shows an error :-
```
nix develop nixpkgs#glfw
error: shell environment '/nix/store/q8qj5aq573dmawml12r50qx54fs4dgnw-glfw-3.3.2-env' has unexpected line 'cmakeFlags='-DBUILD_SHARED_LIBS=ON -DCMAKE_C_FLAGS=-D_GLFW_G'
```
But this works when using `nix-shell`
```
nix-shell '<nixpkgs>' -A glfw
```

If you have a problem with a specific package or NixOS,
you probably want to file an issue at https://github.com/NixOS/nixpkgs/issues. 

**Expected behavior**

nix develop should not fail to create a build environment for the package. Since `nix-shell` doesn't fail.

**`nix --version` output**
nix (Nix) 2.4pre20210207_fd6eaa1

**Comment by matthewbauer** [comment]
Here's a smaller repro for it:

```
(import (builtins.fetchTarball "https://github.com/nixos/nixpkgs/archive/master.tar.gz") {}).stdenv.mkDerivation {
  name = "test";
  a = [ "''" ];
}
```

the single quotes inside a list appear to be the culprit. In bash, it looks like this:

```
a=''\'''\'''
```
