### ISSUE TITLE
There are too many fetchers and we should consolidate them

### ISSUE THREAD

**Issue by andir** [NixOS/nix#4545]
**Describe the bug**

Right now we have many ways to fetch source dependencies. Some that come to mind are:
* `builtins.fetchTree`
* `builtins.fetchurl`
* `builtins.fetchTarball`
* flake dependencies (which are a different syntax for `fetchTree`?)
* fixed output derivations (including `<nix/fetchurl.nix>`)
* `-I nixpkgs=channel:nixos-unstable`

All of these fetch code in some way or another some support omitting the content hash and some do not.

**Expected behavior**

We should be able to point a user to one canonical way to fetch dependencies and make the experience writing and understanding nix expressions easier. We might not be able deprecate old fetcher (as that would break compatibility with old code) we could probably strip down on the amount of examples out there and the different methods that are being used in the documentation.

Another idea is to clearly show the different options in a table with all the ups and downs of each (some allow omitting the content hash which has implications, some run during eval, some only during built time, some lead to IFD when imported from, ...).

Ideally we would only have one or maybe two (to allow omitting missing content hashes?) options of fetching sources in the Nix language as "advertised" fetchers.

**Comment by Ericson2314** [comment]
/me hopes for the point when when al fetching is via IPFS. That'll dedup it!

**Comment by zimbatm** [comment]
Flakes uses `fetchTree` under the hood, but has its own [URL-parsing logic implemented on top](https://github.com/nixos/nix/blob/b7bfc7ee52dd425e0156f369eb4c05a62358f912/src/libexpr/flake/flakeref.cc#L69). There is also `buitins.getFlake` that fetches and returns an instance of the flake.

It would be cool if nixpkgs could use the same syntax so that it's easy to switch from eval-time to build-time fetches.

**Comment by edolstra** [comment]
`fetchTree` *is* the consolidation of the other fetchers (`fetchTarball`, `fetchGit`, `fetchMercurial`, ...). The only thing it doesn't replace is `fetchurl` since it fetches trees, not flat files.

The `-I` flag is obsolete in the new CLI and doesn't work unless you use `--impure`.
