### ISSUE TITLE
Inconsistency with respect to manual

### ISSUE THREAD

**Issue by dschrempf** [NixOS/nix#4547]
Hello! I noticed the following statement in the relase notes of Nix 2.0 (https://nixos.org/manual/nix/stable/#ssec-relnotes-2.0)

> Unlike the legacy commands, it has a consistent way to refer to packages and package-like arguments (like store paths). For example, the following commands all copy the GNU Hello package to a remote machine:
> nix copy --to ssh://machine nixpkgs.hello
> nix copy --to ssh://machine /nix/store/0i2jd68mp5g6h2sa5k9c85rb80sn8hi9-hello-2.10

However, I this statement seems to be untrue with respect to `nix cat-store`.
```
 + nix cat-store nixpkgs.vlc
error: path 'nixpkgs.vlc' is not in the Nix store
```
But
```
 + nix cat-store /nix/store/53ffcmqqw5j44v76nymavpy1snc9ps2w-vlc-3.0.12/bin/vlc
#! /nix/store/cwnwyy82wrq53820z6yg7869z8dl5s7g-bash-4.4-p23/bin/bash -e
export QT_PLUGIN_PATH='/nix/store/5cpqcr7n7hf4v9nkjnm70v4is8dd8xp2-qtbase-5.15.2-bin/lib/qt-5.15.2/plugins'${QT_PLUGIN_PATH:+':'}$QT_PLUGIN_PATH
...
```
(Also `nixos.vlc` does not work).

I use 
```
nix (Nix) 2.3.10
```

**Comment by edolstra** [comment]
This is because the installable notation (e.g. `nixpkgs#vlc`) doesn't allow specifying a path inside a store path (like `bin/vlc`). So we have to restrict the argument to absolute paths.

**Comment by dschrempf** [comment]
Thank you!

I also noticed that there was a discrepancy between my two queries. One was for the `vlc` directory and the other for the `vlc` binary.
