### ISSUE TITLE
redundant `passwd` in nixos install manual; inconsistency vs `nixos-install` behavior

### ISSUE THREAD

**Issue by nathan-at-least** [NixOS/nix#4555]
**Describe the bug**

During a nixos install, running `nixos-install` prompts for the root password. The [manual §2.3 Installing Step 7](https://nixos.org/manual/nixos/stable/index.html#sec-installation-installing) then says to log in as `root` and run `passwd`. Why though?

We just set the root password during `nixos-install`, and then verified that works because we just logged in as root.

**Steps To Reproduce**

Follow the installation manual (without the "unattended" variant of `nixos-install --no-root-passwd`). Get to step 7.

**Expected behavior**

Step 7 would omit changing the password with `passwd`, or if there's some rationale for doing this, it needs to be clearly explained.

**`nix-env --version` output**

`nix-env (Nix) 2.3.10`

**Additional context**

Fresh install on baremetal.

**Comment by edolstra** [comment]
Could you reopen this issue in the `nixpkgs` repo please? That's where `nixos-install` lives.
