### ISSUE TITLE
flakes: multiarch outputs for nixosConfigurations

### ISSUE THREAD

**Issue by nrdxp** [NixOS/nix#4556]
Since NixOS is supported officially on both 32 and 64 bit systems, and aarch support is coming along well enough to be usable, I think it would be pertanent to provide system outputs for `nixosConfigurations`, in the same way that `packages` and `devShell` do it.

##### Context
nrdxp/nixflk#125

**Comment by edolstra** [comment]
Not sure about this. Any specific system is always a particular architecture, which is why `nixosConfigurations` is not split up by architecture.

**Comment by nrdxp** [comment]
I see your point, but it would still help users of the flake understand from the api, instead of having to open the configuration, which system a particular machine is set for. 

I can easily work around the issue if not, I just didn't see anyone mention this yet, so I figured we should at least discuss the possibility.

**Comment by FRidh** [comment]
Maybe `nix flake show` could show the architecture.

**Comment by YellowOnion** [comment]
> Not sure about this. Any specific system is always a particular architecture, which is why `nixosConfigurations` is not split up by architecture.

Microsoft & Apple have x86 emulators build in to their ARM OS's, I wouldn't be surprised if some big company with their entire business model is based of huge library of legacy x86 software wanted to do x86 emulation on Linux soon, and we might need to have both on the same system for that-big-companies massive library of x86 software.
