### ISSUE TITLE
phases aren't correctly updated

### ISSUE THREAD

**Issue by berdario** [NixOS/nix#456]
According to the [wiki](https://nixos.org/wiki/Create_and_debug_nix_packages#Using_nix-shell_for_package_development), it should be possible to inspect the phases that are executed during a build.

But if I try to open a shell (with nix-shell or nix-buil --run-env), when running e.g. `type installPhase` I get shown the default code, and not the one that I overrode in the nix expression

**Comment by vcunat** [comment]
That's most likely some misunderstanding in what nix expression is run by nix-shell. More details about how you run it will be needed if anyone is to uncover what's the problem in this particular case. (I rarely use nix-shell myself, so perhaps other will know better.)

**Comment by lethalman** [comment]
You probably want `eval "$installPhase"` or such, because the default installPhase is a function. Your override adds an "installPhase" variable, not a function. See https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/generic/setup.sh#L818

**Comment by berdario** [comment]
Thanks, [I updated the wiki](https://nixos.org/w/index.php?title=Create_and_debug_nix_packages&diff=prev&oldid=23843)

**Comment by lethalman** [comment]
Thanks to you!
