### ISSUE TITLE
`nix develop --expr` complains that `builtins.getFlake "nixpkgs"` is mutable without `--impure`

### ISSUE THREAD

**Issue by cole-h** [NixOS/nix#4600]
**Describe the bug**

When running `nix develop --expr 'with import (builtins.getFlake "nixpkgs") { }; mkShell { buildInputs = [ ]; }'`, it errors out with `error: cannot call 'getFlake' on mutable flake reference 'self', at (string):1:14 (use --impure to override)`. According to https://github.com/NixOS/nix/issues/2849, a mutable flake reference is one that "doesn't include a Git revision or content hash", yet running `builtins.getFlake "nixpkgs"` in `nix repl` shows that it has both a `narHash` and `rev`.

**Steps To Reproduce**

1. Run `nix develop --expr 'with import (builtins.getFlake "nixpkgs") { }; mkShell { buildInputs = [ ]; }'`
2. See error

**Expected behavior**

I'd expect to not need the `--impure` flag when the flake is adequately locked. (I have it pinned in the registry with `nix.registry.nixpkgs = { from = { id = "nixpkgs"; type = "indirect"; }; flake = inputs.nixpkgs; };` -- is this not enough?)

**`nix-env --version` output**
nix-env (Nix) 2.4pre20210301_e64cf8e

**Comment by L-as** [comment]
This doesn't work at all anymore, even with the `--impure` flag.

**Comment by cole-h** [comment]
I've confirmed the `--impure` flag does work again as of 2.9.1 (may have been earlier, but I only just recently re-tested).

**Comment by drupol** [comment]
It works fine here:

`nix develop --expr 'with import (builtins.getFlake "nixpkgs") { }; mkShellNoCC { buildInputs = [ (php.withExtensions({enabled, all}: enabled ++ [ all.xsl ] )) ];  }' --impure`

**Comment by L-as** [comment]
Close?
