### ISSUE TITLE
Be able to run `nix build` / `nix develop` from anywhere in the project

### ISSUE THREAD

**Issue by garbas** [NixOS/nix#4612]
## Proposal

Allow to enter development environment or even build a project by being anywhere inside the project tree.

## Reasoning

It is already true that even old commands `nix-shell` and `nix-build` by default target local project. By local I mean project within the repository from where you run the command. With new command line, `nix`, we can make this even better.

I would like to propose to extend the default functionality and allow users to enter development shell or build a project from anywhere they are in the project tree.=

When a user would not provide any argument, we would lookup the root of the project by scanning all parent directories until we find `flake.nix` in any of them. After that we would use that flake to run the command against.

Such a change in default would not confuse existing users, but adds interesting new possibilities when developing with Nix.

**Comment by RCoeurjoly** [comment]
If a flake repository is always a git repository, then it is easy.
But I tried running nix build in a regular Linux directory and it builds without problems, so I don't think it is a good idea to ¨lookup the root of the project by scanning all parent directories until we find flake.nix in any of them¨

**Comment by Radvendii** [comment]
@RCoeurjoly why not?
