### ISSUE TITLE
`nix flake list-inputs` + `nix flake info` = `nix flake metadata`

### ISSUE THREAD

**Issue by garbas** [NixOS/nix#4613]
## Proposal 

I propose to merge `nix flake list-inputs` and `nix flake info` output into new `nix flake metadata` command.

## Reasoning

I was recently confused which command to use to inspect the flake that I just wrote. First there was bunch of commands that I would actually expect them to be one command. And also the name `info` and `show` confused me since I had no idea what they will show or what information they will give me.

I propose to move away from `show` and `info` commands in general since they are a little to general even when used in a context of a flake. While metadata word is also quite general it becomes more clear when used with the context with `nix flake metadata`. You now that you will see the metadata of a flake.

Of course I might be wrong with the `metadata` name, but I think it is an improvement, over existing state. If you disagree or have a better name please trash me gently :)

## Bonus

I would add information which *type of outputs* does the flake provide. Here I don't mean to evaluate the outputs. This would answer questions such as: Does this flake provides an overlay?

**Comment by blaggacao** [comment]
This currently breaks https://github.com/NixOS/nixpkgs/blob/e30d87f22237fe25618136eb9f818ecefaeb02a9/nixos/modules/installer/tools/nixos-install.sh#L128
