### ISSUE TITLE
Make auto-optimise-store true by default

### ISSUE THREAD

**Issue by wmertens** [NixOS/nix#462]
I have the feeling that it is now safe to have `auto-optimise-store=true`. I know that there were failures in the past with it, but I've run with it enabled for months without issues.

This is a cheap optimization that will make Nix users (and Hydra) happier. With the improvements in Nix 1.8 it's also quite fast.

**Comment by wmertens** [comment]
From https://www.mail-archive.com/search?l=nix-dev%40lists.science.uu.nl&q=subject:%22%5C%5BNix%5C-dev%5C%5D+Please+test+Nix+store+auto%5C-optimise%22&o=newest&f=1 it seems that in general it's a good idea, but some people with slower harddisks (not ssd) may want to disable it.

@edolstra can this be made the default?

**Comment by vcunat** [comment]
I guess it would be too confusing to have the default depend on whether ``/nix/store`` is on SSD.

**Comment by wmertens** [comment]
Hmm.

Perhaps we should just strongly recommend setting this option.

There are still optimizations on the table, like calculating the hashes
while copying and maybe keeping the hashes and inodes in a database.

**Comment by edolstra** [comment]
Closing this since auto-optimisation can cause significant slowdowns (6c4ac299173e3b9772c96bef1e6463b22dcd0227).
