### ISSUE TITLE
GNU grep fails to build due to sjis-mb test

### ISSUE THREAD

**Issue by xplat** [NixOS/nix#464]
> $ nix-build -K [...]/nixpkgs/pkgs/top-level/all-packages.nix -A gnugrep
> these derivations will be built:
>   /home/james/nix/store/0iizqb550crxq4qsqin7bl7zagwddm3a-gnugrep-2.20.drv
> building path(s) ‘/home/james/nix/store/bfnr3ylfyshpvisf64dbcphs3zk5x3g6-gnugrep-2.20’
> building /home/james/nix/store/bfnr3ylfyshpvisf64dbcphs3zk5x3g6-gnugrep-2.20
> unpacking sources
> unpacking source archive /home/james/nix/store/h3f6mz32s1gj6f1pgw484mwy4y52g490-grep-2.20.tar.xz
> source root is grep-2.20
> patching sources
> configuring
> [...]
> building sjis-mb.log
> FAIL: sjis-mb
> [...]
> \============================================================================
> Testsuite summary for GNU grep 2.20
> \============================================================================
> # TOTAL: 80
> # PASS:  72
> # SKIP:  7
> # XFAIL: 0
> # FAIL:  1
> # XPASS: 0
> # ERROR: 0
> \============================================================================
> See tests/test-suite.log
> Please report to bug-grep@gnu.org
> \============================================================================
> make[3]: **\* [test-suite.log] Error 1
> make[3]: Leaving directory `/tmp/nix-build-gnugrep-2.20.drv-0/grep-2.20/tests'
> make[2]: *** [check-TESTS] Error 2
> make[2]: Leaving directory`/tmp/nix-build-gnugrep-2.20.drv-0/grep-2.20/tests'
> make[1]: **\* [check-am] Error 2
> make[1]: Leaving directory `/tmp/nix-build-gnugrep-2.20.drv-0/grep-2.20/tests'
> make: **\* [check-recursive] Error 1
> note: keeping build directory ‘/tmp/nix-build-gnugrep-2.20.drv-0’
> builder for ‘/home/james/nix/store/0iizqb550crxq4qsqin7bl7zagwddm3a-gnugrep-2.20.drv’ failed with exit code 2
> error: build of ‘/home/james/nix/store/0iizqb550crxq4qsqin7bl7zagwddm3a-gnugrep-2.20.drv’ failed

(sorry about the spurious backslashes in the log, but if i leave them out some of the log appears as headers.)

According to [this commit message](http://osdir.com/ml/grep-commit-gnu/2014-11/msg00014.html) this test will always fail if it's not skipped.  I've verified the nonworking subtests are in the copy nix tries to build.  Apparently it's skipped for most nix users but grep is seeing through the nix environment to notice I have this locale enabled and running the test.

I guess you could either adopt the upstream fix above or try to do something to make grep see a standard set of locales regardless of who builds it.

**Comment by vcunat** [comment]
(Side note: the issue belongs to https://github.com/NixOS/nixpkgs/issues instead.)
I locally tried updating grep to 2.21, which includes a fix for this (according to git log). I'm still waiting with this, as there's a grep CVE where the fix http://git.savannah.gnu.org/cgit/grep.git/commit/?id=83a95bd8c causes some regressions. I just reported that upstream.
