### ISSUE TITLE
Options common for multiple commands, documented in `nix --help` are not documented in `nix <cmd> --help`, causing them to not be discoverable

### ISSUE THREAD

**Issue by doronbehar** [NixOS/nix#4647]
**Describe the bug**

Example: `--print-build-logs` is not documented in `nix build --help` but it is documented in `nix --help`. This makes it unrecoverable.

**Steps To Reproduce**

1. `nix build --help`
2. Search for that option mentioned.

**Expected behavior**

That it'd be documented

**`nix-env --version` output**

nix-env (Nix) 2.4pre20210308_1c0e3e4

**Additional context**

I reported this [here](https://github.com/NixOS/nix/issues/1904#issuecomment-739158144) after it took me an hour or say to find this option myself when I eventually found it via that issue. I think another user on Discourse didn't know about this option: https://discourse.nixos.org/t/nixflake-doesnt-update/11986/ .

**Comment by danieldk** [comment]
It is documented in `man nix`/`nix --help`, because it is an option that is used by several `nix` commands. I agree that it is not very discover-able though ;).

**Comment by doronbehar** [comment]
> It is documented in `man nix`/`nix --help`, because it is an option that is used by several `nix` commands. I agree that it is not very discover-able though ;).

@danieldk would it be possible to include that bit of documentation for every command that accepts `-L`?

**Comment by hexagonal-sun** [comment]
> > It is documented in `man nix`/`nix --help`, because it is an option that is used by several `nix` commands. I agree that it is not very discover-able though ;).
> 
> @danieldk would it be possible to include that bit of documentation for every command that accepts `-L`?

Agreed, I've found several **really** useful flags by doing `nix --help` which aren't documented in the subcommands where they are used.

**Comment by danieldk** [comment]
> @danieldk would it be possible to include that bit of documentation for every command that accepts `-L`?

I don't know. Like you, I was just looking for this option a while back and found it documented there.

**Comment by doronbehar** [comment]
Still an issue.

**Comment by doronbehar** [comment]
This seems fixed now.

**Comment by doronbehar** [comment]
With Nix 2.13.2
