### ISSUE TITLE
nix show-derivation --store does not work with chroots

### ISSUE THREAD

**Issue by bhipple** [NixOS/nix#4668]
**Describe the bug**

When using a chroot `--store`, `nix show-derivation` behaves as such:

1. Build the `drv` inside the chroot and return its abspath
2. Leave the chroot
3. Attempt to read and pretty-print the `drv` at the returned abspath **in the chroot**

This fails if the `drv` file is not at that filesystem path already, which it usually won't be if we're using a `--store`.  Either (1) should return the "real" path of the file or (3) should be done in the chroot.

**Steps To Reproduce**

1. Change a derivation file to ensure it's not in a cache somewhere.  E.g., here I changed `ripgrep` to `ripppgrep`.
2. Run `nix show-derivation -f . --store ~/chroot-nix ripgrep` (or any other attr not in a binary cache)

This will fail like so:

```console
$ nix show-derivation -f . --store ~/chroot-nix ripgrep
{
  "/nix/store/rk4a961nxwa6cbssmx10707xw3qgyd5j-ripppgrep-12.1.1.drv": {}
error: opening file '/nix/store/rk4a961nxwa6cbssmx10707xw3qgyd5j-ripppgrep-12.1.1.drv': No such file or directory
}
```

The actual `drv` file is over at `~/chroot-nix/nix/store/rk4a961nxwa6cbssmx10707xw3qgyd5j-ripppgrep-12.1.1.drv`.

**Expected behavior**

Drv prints as normal. 

**Additional context**

Using nix 2.3.10

**Comment by edolstra** [comment]
This works on nix master.
