### ISSUE TITLE
Should a flake's `self.rev` return something useful in modified repos?

### ISSUE THREAD

**Issue by dhess** [NixOS/nix#4682]
What's the thinking on why a flake's `self.rev` won't evaluate in a dirty repo? IMO, it would be a lot nicer to work with `self.rev` in Nix expressions if it returned `<rev>-dirty` (or similar) in this situation.

I do understand the argument that it's better to fail in this situation than to return `<rev>-dirty`, but then it seems a bit inconsistent that you *can* get a modified repo's last-modified via `self.lastModified` or `self.lastModifiedDate`.

**Comment by shlevy** [comment]
:+1:, I want to use `rev` and `revCount` to modify my package's version and would be happy with a `dirty` bool (even a `dirtyRev` and `dirtyRevCount` if needed).

**Comment by dhess** [comment]
Sigh. Still relevant.

(The stale bot is a pox.)

**Comment by tgunnoe** [comment]
Still relevant to me as well. I would think self.rev would always be available, so either `self.rev` and/or `self.rev-dirty`. I'm not sure why it doesn't appear when the rev is dirty, when I am just looking to add the commit hash of the last commit to a package output in my repository (along with `self.lastModified`)

**Comment by con-f-use** [comment]
I'd like to have some way to get a `dirtyRev`, too.

**Comment by voronind-com** [comment]
So no `count`? :(

**Comment by voronind-com** [comment]
No `dirtyRevCount`?

**Comment by vorburger** [comment]
FTR: This was fixed with #5385; it's noteworthy that it's not `dirtyRevision` (as the PR description states) but `dirtyRev` and `dirtyShortRev` (as its title says). https://discourse.nixos.org/t/flakes-accessing-selfs-revision/11237/8 suggests to use it as: `toString (self.shortRev or self.dirtyShortRev or self.lastModified or "unknown")`.
