### ISSUE TITLE
flakes problems related to `#` and zsh

### ISSUE THREAD

**Issue by timsears** [NixOS/nix#4686]
nix flakes' `#` does not play nice with zsh when extendedGlob is enabled.

Here's a simple example...
~~~
> setopt extendedGlob                                                         
> nix profile install nixpkgs#hello            
Found existing alias for "nix". You should use: "n"
zsh: no matches found: nixpkgs#hello
~~~

Here's a workaround. 
~~~
> unsetopt extendedGlob    
> nix profile install nixpkgs#hello  
~~~
...works

Any command that uses the `#` in the command is likely affected.

Many people will have extended glob enable automatically if they use zsh configuration frameworks such as oh-my-zsh.

Took a long time for me to realize this was a zsh issue more than a nix flakes issue. Might suggest that the resource path not include a `#` going forward.

This issue can be closed, but parking it here so people can find it when they search.

**Comment by Patryk27** [comment]
As an easier workaround, wrapping in quotes or apostrophes - `nix something 'nixpkgs#hello'` - should work, too.

**Comment by socksy** [comment]
Another work around is to add:
```zsh
alias nix="noglob nix"
```
in your `.zshrc`

**Comment by otavio** [comment]
> Another work around is to add:
> 
> ```shell
> alias nix="noglob nix"
> ```
> 
> in your `.zshrc`

This couldn't be done automatically?

**Comment by ZucchiniZe** [comment]
> Another work around is to add:
>
> `alias nix="noglob nix"`
>
> in your `.zshrc`

For reference here's what I have put int my `configuration.nix` to fix this problem

```nix
  programs.zsh = {
    enable = true;
    shellAliases = {
      nix = "noglob nix";
    };
  };
```
