### ISSUE TITLE
Nix failes to compile with musl libc

### ISSUE THREAD

**Issue by jprjr** [NixOS/nix#469]
I tried compiling nix from source on Alpine Linux, which uses musl libc.

It looks like there's two problems in affinity.cc that's causing the compile to fail: the `sched_getcpu` function is glibc-specific, and there's an error about `memset `not being defined.

I added `#include <string.h>` into affinity.cc and that seemed to fix the memset problem (though I don't know if that's really the correct fix or not).

**Comment by gitfoxi** [comment]
I am exactly where you were in February. Did you figure it out?

**Comment by gitfoxi** [comment]
This got me over that hurdle:

    #undef HAVE_SCHED_SETAFFINITY

**Comment by gitfoxi** [comment]
Also had to add `-lcrypto` to the link because of who knows? Anyway, I now have nix working under apline linux. (Well, now I have to bootstrap. That's going to be the real adventure.)

**Comment by dkubb** [comment]
@gitfoxi do you have a script or Dockerfile that shows the process you went through to build nix on top of alpine linux?

**Comment by dkubb** [comment]
@gitfoxi @jprjr I ended up working through it myself and made a Dockerfile that shows how I compile nix with musl libc:

  https://github.com/dkubb/dockerfiles/blob/master/alpine-nix/Dockerfile

I'm curious to know if our processes differ at all, and if you have any suggestions on how I can improve the process please let me know.

**Comment by nathan7** [comment]
I've got an Alpine package for Nix here: https://code.nathan7.eu/nathan7/alpine-nix
(and to bring us full circle: [apk-tools for Nix](https://code.nathan7.eu/nathan7/nix-alpine))

**Comment by nathan7** [comment]
note that this *actually* being fixed is pending the next stable musl release, but that places the ball firmly in their court
