### ISSUE TITLE
Make --print-build-logs a configurable default

### ISSUE THREAD

**Issue by Atemu** [NixOS/nix#4695]
**Is your feature request related to a problem? Please describe.**

I'm really used to the whole build log scrolling past like it does with `nix-*` commands and have to pass `-L` every time I run the equivalent `nix` commands. 

**Describe the solution you'd like**

I'd like there to be a documented(!) configuration option to make nix `print-build-logs` by default.

**Describe alternatives you've considered**

Make `print-build-logs` the global default.

**Additional context**

It'd also be useful to have a negative of the flag should the user want to disable the default they've set for a certain command.

**Comment by edolstra** [comment]
I don't think this should be default, but the `progress-bar` branch makes it possible to enable build logs interactively (b361065fa5d1741a88fcf87da99396e35e6cb5da).

**Comment by lf-** [comment]
I don't agree. If you don't want to make it the default, that's fine, but please add a configuration option. I am going to have to write a shell hack in my setup to always pass `-L`, which is gross and does not apply to all the contexts I want.
