### ISSUE TITLE
2.3.10: fetchTarball uses toybox's tar implementation and fails

### ISSUE THREAD

**Issue by RasmusRendal** [NixOS/nix#4696]
**Describe the bug**
When trying to enter a nix-shell using fetchTarball and having toybox installed, I get the following error:
```
tar: Unknown option 'strip-components' (see "tar --help")
error: program 'tar' failed with exit code 1
```

**Steps To Reproduce**

1. Have toybox installed in your nix configuration, or home manager
2. Save the example (below) to shell.nix in some directory
3. run `nix-shell`

```nix
let
  unstable = import (fetchTarball https://nixos.org/channels/nixos-unstable/nixexprs.tar.xz) { };
in
  unstable.mkShell {
    buildInputs = with unstable; [ unstable.gcc ];

  }
```

**Expected behavior**

I expect the tar to extract using GNU tar, which has strip-components

**`nix-env --version output**

`nix-env (Nix) 2.3.10`

**Additional context**
[Moved from nixpkgs](https://github.com/NixOS/nixpkgs/issues/118651) by advice of hmenke.
Hmenke pointed out the following part of the source:
https://github.com/NixOS/nix/blob/2.3.10/src/libstore/download.cc#L913-L914

**Comment by edolstra** [comment]
This is fixed on master since we're not using `tar` anymore.
