### ISSUE TITLE
nix run on a flake in the nix store without a flake.lock requires --no-write-lock-file

### ISSUE THREAD

**Issue by berbiche** [NixOS/nix#4699]
**Describe the bug**

Hi, I'm not sure whether this is really a bug, it's more of a UX issue.

As part of https://github.com/nix-community/home-manager/pull/1913, we want to be able to run the `home-manager` binary with nix 2.4 commands without needing to install Home Manager through the documented channel installation.
Home Manager does not currently pin its flake inputs and as such, the commands `nix run`, `nix shell`, etc. do not work unless `--no-write-lock-file` is used.

**Steps To Reproduce**

1. `nix run github:nix-community/home-manager/pull/1913/head` or `nix run github:nix-community/home-manager/?rev=e27d64a20bbfb825fe478f36a102b19f7d48fd66`

**Expected behavior**

What I believe is happening is that nix tries to write the lock file to the store and fails, requiring the use of `--no-write-lock-file`.

Ideally, if a flake does not have a flake.lock and lives in the store, nix should not try to write a lock file.

**`nix-env --version` output**
```
nix-env (Nix) 2.4pre20210326_dd77f71
```

**Additional context**

**Comment by FRidh** [comment]
I think it is good here to be explicit. When there is no lock file, evaluation is not hermetic, more specifically, the inputs to the flake depend on when it is run. Likely you are not aware of this when you use the flake.

**Comment by berbiche** [comment]
> I think it is good here to be explicit. When there is no lock file, evaluation is not hermetic, more specifically, the inputs to the flake depend on when it is run. Likely you are not aware of this when you use the flake so you should really acknowledge no lock file is used or created.

I agree on the implicit vs explicit behavior, nonetheless I believe the user will always want to use `--no-write-lock-file` in such cases (though maybe rare).

What if a message was printed when this implicit behavior was used?
To me this is an example of a case of "just do what I mean".

**Comment by i077** [comment]
The error message could be something along the lines of
```
warning: No flake.lock present, use 'nix flake lock' to create
```
(unless the flake is in the nix store, in which case we could just say `No flake.lock present`)

But then how should nix handle the case where flake.lock exists, but some inputs are missing? We could use the locked entries, then fetch the missing entries without explicitly updating the lock file. I guess we could then emit the warning
```
warning: Input 'foo` is missing from flake.lock, use 'nix flake lock' to create this entry
```
But I feel like this behavior may be a bit confusing for the end user.

**Comment by FRidh** [comment]
> I agree on the implicit vs explicit behavior, nonetheless I believe the user will always want to use --no-write-lock-file in such cases (though maybe rare).

Hermetic evaluation is a crucial aspect of flakes. Having non-hermetic evaluation in some conditions goes against what can be expected as user.

> What if a message was printed when this implicit behavior was used?
> To me this is an example of a case of "just do what I mean".

A warning is helpful but still, it means the behavior of a command varies, in this case it depends on filesystem permissions. Let's say as a user I always want hermetic evaluation. Should I now do another test first? If so, how?

**Comment by berbiche** [comment]
> Hermetic evaluation is a crucial aspect of flakes. Having non-hermetic evaluation in some conditions goes against what can be expected as user.

Indeed, it would be bad to lose this property because of implicit behavior.

> Let's say as a user I always want hermetic evaluation. Should I now do another test first? If so, how?

It will never be possible for the use-case described here (under the assumption that the nix store will always be read-only).

Considering the requested changes this issue should be relabeled as a feature request.

**Comment by berbiche** [comment]
Works as intended
