### ISSUE TITLE
Binary Cache options aren't parsed properly if its URL has a scheme

### ISSUE THREAD

**Issue by sternenseemann** [NixOS/nix#4717]
**Describe the bug**

* `cache.nixos.org?priority=50` works as expected
* `http://cache.nixos.org?priority=50` results in `warning: unknown setting 'priority'` being printed.

This is a significant problem when using a binary cache which is only available via HTTPS since if no URL scheme is given, Nix seems to assume plain HTTP. If it encounters a redirect (for example from the assumed HTTP version to the HTTPS URL of the binary cache) it fail with `warning: don't know how to open Nix store 'cache.tvl.su'` (whereas `https://cache.tvl.su` would work, but not with options).

**Expected behavior**

Binary Cache options should be parsed for all kinds of binary cache specifications. Alternatively there could be an alternative for specifying these kinds of options for binary caches which doesn't rely on parsing an URL (since this seems to be inherently prone to these kinds of problems). 

**`nix-env --version` output**

```
nix (Nix) 2.3.10
```

**Comment by regnat** [comment]
This seems to be fixed on 2.4
