### ISSUE TITLE
program 'tar' failed with exit code 1

### ISSUE THREAD

**Issue by deliciouslytyped** [NixOS/nix#4718]
Messing up the associativity on `(import (((import ../nix/sources.nix).nixos-hardware) + "/microsoft/surface/default.nix"))` yielded this error:

```
while evaluating 'builtins_fetchTarball' at /configs/nix/sources.nix:129:27, called from /configs/nix/sources.nix:23:9:
program 'tar' failed with exit code 1
```

This may only happens if the source is not yet in the store and fetching fails due to no network access - but that may be completely coincidental.

I didn't record enough context to be able to say any more than this right now, and I can't seem to reproduce it momentarily either.

The error message is pretty useless and it would be nice to get something that would help more with figuring the issue out.

I haven't been able to check yet if any of nix's increased verbosity modes helps.

**Comment by edolstra** [comment]
This has been fixed on master (it no longer depends on tar).
