### ISSUE TITLE
nix search without a term should error

### ISSUE THREAD

**Issue by SuperSandro2000** [NixOS/nix#4739]
**Is your feature request related to a problem? Please describe.**
When you run ``nix search`` without any query it lists you all packages and freezes your terminal for multiple seconds until the Ctrl + C comes through.

**Describe the solution you'd like**
It should error instead and force the user to provide a query.

**Describe alternatives you've considered**
Writing shell script around the problem myself.

**Additional context**
If that functionality is desired it could be moved to a flag.

**Comment by regnat** [comment]
Related: https://github.com/NixOS/nix/issues/3553
