### ISSUE TITLE
nix profile crashes with parse error at line 1, column 1

### ISSUE THREAD

**Issue by suhr** [NixOS/nix#4742]
**Describe the bug**

```
% nix profile upgrade '.*'
error: [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
```

**Steps To Reproduce**

1. It seems like something was corrupted after a sudden reboot, but nix does not tell what exactly
2. `nix profile upgrade '.*'`

**Expected behavior**

Nix should at least tell which file is corrupted.

**Additional context**

Deleting `~/.cache/nix` does *not* fix the issue.

Nix version: 2.4pre20210326_dd77f71

**Comment by suhr** [comment]
Switching to the old profile, cleaning and then trying to upgrade again fixes the issue. Still, the error message could be better.

**Comment by edolstra** [comment]
Maybe `~/.nix-profile/manifest.json` got corrupted?

**Comment by suhr** [comment]
It probably was.
