### ISSUE TITLE
Native support for plist read/write?

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#475]
I'd be happy to implement it if you'd be interested in merging it in. I'd probably create a couple of primops for going back and forth, much like we have for XML and JSON. This would greatly facilitate better integration with configuration on Mac OS (which is my secret evil plan; sssh don't tell anyone!)

I'd probably go with an open-source plist implementation rather than the Mac-specific one.

**Comment by edolstra** [comment]
Isn't this something that can be done more easily inside a builder (e.g. by converting a JSON representation to a plist)?

**Comment by shlevy** [comment]
Seems like this is working around lack of recursive nix... the only time there are reasonably going to be plists available to nix to read are after a package tarball is unpacked, which is too late for most nix use.

**Comment by copumpkin** [comment]
Oh, I had other use cases too, but that one would be nice too!

**Comment by shlevy** [comment]
What use cases?

**Comment by copumpkin** [comment]
Mac OS configuration, NixOS-style, which would involve generating .plist files from Nix values.

**Comment by shlevy** [comment]
Why not just do that in a derivation?

**Comment by copumpkin** [comment]
Seems pretty painful to pass nested maps through a shell script in a derivation. Or are you still talking about going via JSON (which isn't ridiculous)?

**Comment by shlevy** [comment]
You could also do the mapping in nix (e.g. do a mapAttrsToList to make a list of strings you concat together to get the plist file) but yeah as long as we have one way to pass structured data to a drv I'm not sure we need two.

**Comment by copumpkin** [comment]
Fair enough. So you're saying JSON (plus a utility I'd need to write to convert from JSON to plist) for writing JSON, and recursive nix to read it?

**Comment by shlevy** [comment]
Yeah, that seems like the better option here, given the use cases presented. If there are other ones we're missing thouhg please point them out!

**Comment by copumpkin** [comment]
No, that makes sense. I'll close this :smile:

**Comment by wmertens** [comment]
Btw plutil supports plist <> json conversion.

**Comment by copumpkin** [comment]
Yeah, but `plutil` isn't open :(

**Comment by copumpkin** [comment]
Looks like gnustep has a whole load of plist processing code in it though, so I can probably make a trivial wrapper around that. I already packaged up much of their source anyway, and just need to push that to nixpkgs.
