### ISSUE TITLE
nix search package version

### ISSUE THREAD

**Issue by piegamesde** [NixOS/nix#4789]
**Is your feature request related to a problem? Please describe.**
If I want to know the version of a package through the search, I either have to use the JSON raw output or use search.nixos.org. I'd expect to have a better way to get detailed package information through `nix search`.

**Describe the solution you'd like**
I haven't thought much about how to solve this, and I don't have any specific solutions in mind. The search site works fine, so why not copy that.

**Describe alternatives you've considered**
None

**Comment by regnat** [comment]
`nix search` does show the version on master:

```console
$ nix search nixpkgs hello
* legacyPackages.x86_64-linux.gnome3.iagno (3.36.4)
  Computer version of the game Reversi, more popularly called Othello

* legacyPackages.x86_64-linux.hello (2.10)
  A program that produces a familiar, friendly greeting
...
```

**Comment by piegamesde** [comment]
Nix 2.4 has been released. Apart from the fact that the search results are called "legacyPackages" for some reason, it works fine.
