### ISSUE TITLE
Sandbox Creation does not seem to be thread safe

### ISSUE THREAD

**Issue by jonringer** [NixOS/nix#4810]
**Describe the bug**
Getting a bunch of failures around `No such file or directory` or `command not found` when doing large reviews (~64 jobs per review, around 100-300 rebuilds occurring at once across the machine).

example failure:
```
error: builder for '/nix/store/mfc91mbaz6lszlsrnbpcpknc3mmsq22f-libsass-3.6.4.drv' failed with exit code 1;
       last 10 log lines:
       > autoreconfPhase
       > autoreconf: export WARNINGS=
       > autoreconf: Entering directory '.'
       > autoreconf: configure.ac: not using Gettext
       > autoreconf: running: aclocal --force
       > aclocal: error: aclocal: file '/nix/store/cdgg8qx77yyz8drn9hc345z64wa08cln-libtool-2.4.6/share/aclocal/ltversion.m4' does not exist
       > autoreconf: error: aclocal failed with exit status: 1
       > /nix/store/3p1g8k49hsi905pwib58ffhlzkgrcd8y-stdenv-linux/setup: line 95: /dev/null: No such file or directory
       > /nix/store/3p1g8k49hsi905pwib58ffhlzkgrcd8y-stdenv-linux/setup: line 76: /dev/null: No such file or directory
       > /nix/store/3p1g8k49hsi905pwib58ffhlzkgrcd8y-stdenv-linux/setup: line 78: /dev/null: No such file or directory
       For full logs, run 'nix log /nix/store/mfc91mbaz6lszlsrnbpcpknc3mmsq22f-libsass-3.6.4.drv'.
```
however, running this build individually allows for it to complete successfully:
```
$ nix-build /nix/store/mfc91mbaz6lszlsrnbpcpknc3mmsq22f-libsass-3.6.4.drv
....
checking for references to /build/ in /nix/store/ay0b6pbhy5a11kcba8rcdjk85b3pwg6v-libsass-3.6.4...
/nix/store/ay0b6pbhy5a11kcba8rcdjk85b3pwg6v-libsass-3.6.4
```

**Steps To Reproduce**

1. Get a CPU with a stupid amount of threads >=64
2. Review 2 staging PR with `--cores 64` (e.g. `nixpkgs-review pr 122920`)
3. See failures streaming in

**Expected behavior**

Package related failures, not nix-build failures

**`nix-env --version` output**
```
$ nix-env --version
nix-env (Nix) 2.4pre20210503_6d2553a
```
**Additional context**

Seems like other things aren't being mounted as well, a compilation of other failures, these packages succeed when running few builds:
```
       > ./configure: line 77: cat: command not found
       > ./configure: line 84: rm: command not found
       > g++: fatal error: cannot execute 'as': execvp: No such file or directory
       > /nix/store/3p1g8k49hsi905pwib58ffhlzkgrcd8y-stdenv-linux/setup: line 78: /dev/null: No such file or directory
```

Nix related configuration:
```
  nix.autoOptimiseStore = true;
  nix.useSandbox = true;
  nix.nrBuildUsers = 450;
  nix.daemonIONiceLevel = 5;
  nix.daemonNiceLevel = 15;
  nix.buildCores = 32;
  nix.maxJobs = 64;
  nix.package = pkgs.nixUnstable;
```

**Comment by Mindavi** [comment]
I've seen this before as well, though in my case I sometimes was just running 2 `nix-build` or `nix build` commands at the same time. Mixing the new and old CLI seems to make this occur more often, though I don't have a good reproducer of any kind. I typically just restart the build, but with that much builds going on at the same time it's annoying if you need to restart it.

**Comment by jonringer** [comment]
For ZHF, I'm just rolling back from `nixUnstable` to `nix`. I'm mostly just invoking `nixpkgs-review` anyway.

However, I'm concerned about hydra failures. May not be much of an issue if the builds are "distributed" to remote hosts which are only running a few builds at once.

**Comment by jonringer** [comment]
Seeing this in hydra builds now as well https://logs.nix.ci/?key=nixos/nixpkgs.120344&attempt_id=258b2958-bce5-428b-a7e4-59ffa219853c

**Comment by Mindavi** [comment]
I can't say that I have seen this lately.

**Comment by jonringer** [comment]
me neither. Going to close. Assuming that the boehmgc / coroutine fixes have also fixed this.
