### ISSUE TITLE
`nix copy` derivations

### ISSUE THREAD

**Issue by grahamc** [NixOS/nix#4814]
**Is your feature request related to a problem? Please describe.**

I use `nix-copy-closure` often to move .drv's between hosts to support different build and distribution patterns. If you try to use `nix copy` on a .drv today, it tries to build it first -- this defeats the purpose of my use case.

**Describe the solution you'd like**

Ideally `nix copy` would not try to build the drv first in any case, but if that is weird maybe a `--derivation` option or something would be fine.

**Describe alternatives you've considered**
n/a

**Additional context**
I have a lot of workflows built around copying .drv's around, this feels very important to me. I very highly value the ability to transfer derivation files around between stores.

**Comment by dasJ** [comment]
Is this a duplicate of #3696?

**Comment by grahamc** [comment]
Incredible, I even suggested a flag which already exists. Whoops... :flushed: :grin:
