### ISSUE TITLE
"experimental feature 'ca-derivations' is disabled" even though it is enabled

### ISSUE THREAD

**Issue by NobbZ** [NixOS/nix#4841]
Please see #4784. The proposed fix of `nixos-rebuild` does *not* fix my problem there, as I did not even use `nixos-rebuild` in the original post.

Though despite having pointed that out in https://github.com/NixOS/nix/issues/4784#issuecomment-841881064, the issue hasn't been re-openend.

**Comment by kanashimia** [comment]
Do you use nix from the `nixFlakes` attribute right?
I think this is because of the https://github.com/NixOS/nixpkgs/pull/120141
It has been reverted since https://github.com/NixOS/nixpkgs/pull/123898
Can you test if the issue still persists with newest nixpkgs?

**Comment by NobbZ** [comment]
After the problem occuring the first time, I used `nix` from `nixos/nix/master` as you can see in the following 2 linked parts of my flake:

* https://github.com/NobbZ/nixos-config/blob/master/nixos/modules/flake.nix#L5
* https://github.com/NobbZ/nixos-config/blob/master/flake.nix#L6

I assume that is unwrapped.

Also this problem only exists on one of 3 systems I have.

All 3 are using the same version of `nix`.

**Comment by NobbZ** [comment]
Still I am preparing that system to try with todays `nix`. This will take until tomorrow probably…

**Comment by NobbZ** [comment]
I checked, and it still behaves the same:

```text
$ nix build .#advcp  # this is a random derivation I put `__contentAddressed = true` in
warning: Git tree '/home/nmelzer/Projects/nixos-config' is dirty
error: experimental Nix feature 'ca-derivations' is disabled; use '--experimental-features ca-derivations' to override
$ nix show-config | rg exper
experimental-features = nix-command flakes ca-derivations
$ nix --version
nix (Nix) 2.4pre20210604_8e6ee1b
```

PS: I also found out, that `root` indeed had a `~/.config/nix/nix.conf` which was overwriting the `/etc/nix/nix.conf` value for `experimental-features`. After I deleted it, I can indeed build as `root` even CA-derivations. My user is still complaining, despite the fact that `nix show-config` picks it up correctly…

**Comment by NobbZ** [comment]
Having removed `root`s user setting ultimatively fixed the issue for the regular user as well, though a restart was required (well, perhaps restarting the demon had worked already, but I had to do a reboot anyway).

**Comment by euonymos** [comment]
I bumped into the same issue on 2.11.1, adding `ca-derivation` to the global config and restarting the daemon helped. But using --extra-experimental-features argument didn't work.
