### ISSUE TITLE
nix package queries consume a lot of memory and CPU

### ISSUE THREAD

**Issue by AlphaBack** [NixOS/nix#4843]
**Describe the bug**

When I query the nix online package, nix consumes about 1.7GB of memory and 100% CPU.
It seems others have reported similar  problems.
#38635

My computer environment situation:
```bash
nix-shell -p nix-info --run "nix-info -m"           
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.9-1-default, openSUSE Tumbleweed, noversion`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.11`
 - channels(root): `"nixpkgs-21.05pre290801.7013a0f2791"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Steps To Reproduce**

1. when use `nix-env -qa ".*firefox.*"` or install comand
2. Seeing the memory grow until about 1.7GB, during which time the CPU is at high load

**Expected behavior**

Memory usage is as small as possible, preferably under 100MB

**`nix-env --version` output**
```
nix-env --version
nix-env (Nix) 2.3.11
```

**Additional context**

Recently discovered that the problem that has been plaguing gamers for several years with long loading times in GTA Online is parsing a JSON file, which contains a list of all the possible items and upgrades you can buy in GTA Online.
See [How I cut GTA Online loading times by 70%](https://nee.lv/2021/02/28/How-I-cut-GTA-Online-loading-times-by-70/) for detail.
The `package-search.json` file is a json file containing the nix package, is the same bad method used in parsing this file?

**Comment by vcunat** [comment]
That's quite a FAQ, I think.  It's more of a misunderstanding and design choice.  Anyway, let's close this in favor of https://github.com/NixOS/nix/issues/501  (and there's that [nixpkgs ticket](https://github.com/NixOS/nixpkgs/issues/38635) you mentioned, too)
