### ISSUE TITLE
Decreased evaluation performance in newer versions

### ISSUE THREAD

**Issue by erikarvstedt** [NixOS/nix#4847]
Evaluating NixOS configurations takes 10-40% more time with Nix unstable compared to the latest stable version (2.3.11).

The performance differences are most pronounced when running `nix` in VMs (see the timings below).
But I'm still getting 10-20% longer runtimes on bare metal (AMD Ryzen 1700, Intel i5-10210U).

This issue has kept me from converting my configs to flakes; It'd be great to see this resolved.

#### Update
This repo contains the latest benchmarks: [erikarvstedt/nix-performance-benchmark](https://github.com/erikarvstedt/nix-performance-benchmark).
**Summary:** In Nix 2.6, evaluating a system derivation via `nix-instantiate` is about 1.5x faster compared to `nix eval` ([full results](https://github.com/erikarvstedt/nix-performance-benchmark/blob/master/README.md)).
Most of time difference is due to time spent in syscalls.

#### Reproduce (old, archived benchmark)
```bash
### Fetch nix

nix=$(nix-build --no-out-link - <<'EOF'
let
  nixpkgs = builtins.fetchTarball {
    # unstable (2021-05-24)
    url = "https://github.com/NixOS/nixpkgs/archive/900115a4f7fdd9189e7803ca781a65be663f2c89.tar.gz";
    sha256 = "11551nawxjbgya8sq1p6ghkbws9qz9fbfq3wqawm3zh8ayr4l13j";
  };
  pkgs = import nixpkgs { config = {}; overlays = []; };
in
  pkgs.runCommand "nix" {} ''
    mkdir $out
    ln -s ${pkgs.nix}/bin/nix $out/old
    ln -s ${pkgs.nixUnstable}/bin/nix $out/new
  ''
EOF
)

$nix/old --version # 2.3.11
$nix/new --version # 2.4pre20210503_6d2553a

### Benchmark 1
# A simple NixOS system

read -d '' src1 <<'EOF' || :
let
  nixpkgs = builtins.fetchTarball {
    # unstable (2021-05-24)
    url = "https://github.com/NixOS/nixpkgs/archive/900115a4f7fdd9189e7803ca781a65be663f2c89.tar.gz";
    sha256 = "11551nawxjbgya8sq1p6ghkbws9qz9fbfq3wqawm3zh8ayr4l13j";
  };
in
(import "${nixpkgs}/nixos" {
  configuration = { pkgs, lib, ... }: with lib; {
    services.xserver.enable = true;
  };
}).vm.outPath
EOF
time $nix/old eval "($src1)" >/dev/null
# real 0m3.248s (times were measured after some warmup runs)
time $nix/new eval --experimental-features nix-command --impure --expr "$src1" >/dev/null
# real 0m4.026s
# => 24% increase

### Benchmark 2
# nix-bitcoin VM test. The performance differences are larger here.
# To avoid confusion: This benchmark is not for demonstrating the increased perf differences in VMs. 
# For that, you'd have to run the benchmarks in a VM.

read -d '' src2 <<'EOF' || :
let
  nix-bitcoin = builtins.fetchTarball {
    url = "https://github.com/fort-nix/nix-bitcoin/archive/v0.0.46.tar.gz";
    sha256 = "1br1fjlidnrn39qif0pfi9bpdgmiv5pzhy0n9y0z6ic4zm21jcf7";
  };
in
  ((import "${nix-bitcoin}/test/tests.nix" {}).default).vm.outPath
EOF
time $nix/old eval "($src2)" >/dev/null
# real 0m2.755s
time $nix/new eval --experimental-features nix-command --impure --expr "$src2" >/dev/null
# real 0m3.773s
# => 37% increase
```

**Comment by regnat** [comment]
Waw that’s a pretty big increase. And I can indeed confirm it:

| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `nix-2.4pre20210503_6d2553a/bin/nix eval --impure --file ./bench.nix` | 6.803 ± 0.106 | 6.717 | 7.084 | 1.24 ± 0.02 |
| `nix-2.3.11/bin/nix-instantiate --eval ./bench.nix` | 5.501 ± 0.009 | 5.490 | 5.515 | 1.00 |

**Comment by Ericson2314** [comment]
So it turns out `std::visit` can be by reference; I was wrong. I've been meaning to do a big PR changing those. I think that will help some things.

**Comment by regnat** [comment]
Interestingly a large part of the slowdown happens in the frontend: `nix-instantiate --eval` is faster both on master and on 2.3 (`nix-instantiiate` on master is still slower than on 2.3, but the difference is actually much smaller)

| Command | Mean [s] | Min [s] | Max [s] | Relative |
|:---|---:|---:|---:|---:|
| `$NEWNIX/bin/nix eval --impure --expr '(import ./bench.nix)'` | 6.812 ± 0.035 | 6.787 | 6.837 | 1.23 ± 0.01 |
| `$OLDNIX/bin/nix eval '(import ./bench.nix)'` | 5.926 ± 0.014 | 5.916 | 5.936 | 1.07 ± 0.01 |
| `$NEWNIX/bin/nix-instantiate --eval ./bench.nix` | 5.902 ± 0.124 | 5.814 | 5.989 | 1.06 ± 0.02 |
| `$OLDNIX/bin/nix-instantiate --eval ./bench.nix` | 5.550 ± 0.040 | 5.522 | 5.578 | 1.00 |

**Comment by asymmetric** [comment]
@regnat how are you producing those tables? And what does `bench.nix` contain?

**Comment by erikarvstedt** [comment]
I've updated my benchmarks. You can reproduce them with this flake-based repo: [erikarvstedt/nix-performance-benchmark](https://github.com/erikarvstedt/nix-performance-benchmark).

Summary:
- In Nix 2.6, evaluation via `nix-instantiate` is still about 1.5x faster than `nix eval` ([full results](https://github.com/erikarvstedt/nix-performance-benchmark/blob/master/README.md)).
  Most of time difference is due to time spent in syscalls.
  @pennae, would you be interested in looking into this?
- `nix-instantiate` on Nix 2.6 is 1.17x faster compared to Nix 2.4 and 1.08x faster compared to Nix 2.3, likely due to @pennae's great perf-related work.

**Comment by pennae** [comment]
we've run the same minimal system eval test through our benchmarks (which use a dummy store), and we've seen at most 5% difference between `nix eval` and `nix-instantiate`. the difference you're seeing may be down to store path handling, and we don't know enough about that to go chasing.

**Comment by pennae** [comment]
ran some benchmark with `nix build`/`nix-build` instead of eval out of curiosity, and the performance difference mostly disappears for those.

**Comment by erikarvstedt** [comment]
Case solved:
The reason for the increased runtime is that `nix eval` always instantiates all store derivations referenced in the output. 
This doesn't happen with `nix-instantiate --eval`, except when passing the extra argument `--read-write-mode`.

I couldn't yet find a way to work around this issue. Using `builtins.unsafeDiscardStringContext mySystem.drvPath` doesn't prevent the instantiations.
Also, I've noticed that the client sends the full contents of all `.drv` files in the derivation closure to the nix daemon, even if all these derivations already exist in the store.
Optimizing this might be a way to improve incremental build performance. I'll address these topics in separate issues.

Thanks, @pennae, for the helpful pointers!
