### ISSUE TITLE
Speed up `nix-env -i`

### ISSUE THREAD

**Issue by danbst** [NixOS/nix#485]
Currently when you run

`nix-env -i chromium`

it waits for a long time. What about try `nixos.pkgs.chromium` as hotcheck, and if that fails, do the full search?

Issue moved from https://github.com/NixOS/nixpkgs/issues/6594

**Comment by copumpkin** [comment]
I've wondered before if we could bundle a small "inverted index" of nixpkgs in channel releases. Is that weird? Then `nix-env` would just query the index (sorted text file, sqlite file, who knows) and run the relevant attribute.

**Comment by copumpkin** [comment]
Actually, it looks like there's already a `programs.sqlite` used for suggestions when you try to run something that doesn't exist. The database could probably just be expanded to support nix-env.

**Comment by shlevy** [comment]
IMO we should deprecate `nix-env -i` without `-A`. We already have a mechanism for efficient lookups by name in nix!

**Comment by cocreature** [comment]
I completely agree. In addition to being slow it's also just one more thing that confuses new users (it did confuse me).

**Comment by bennofs** [comment]
We just have to make sure that the default attributes make sense. For example, installing the attribute bash right now gives you a non-interactive bash, which is very confusing.

**Comment by vcunat** [comment]
Also, our version replace/update semantics depends on name equality, and attributes tend to be structured (``recurseIntoAttrs`` doesn't work there), etc.

**Comment by danbst** [comment]
@shlevy 
> IMO we should deprecate nix-env -i without -A. We already have a mechanism for efficient lookups by name in nix!

What is the a reason that packages are not top-level in `nix-env`? With nix you have to write `pkgs.chromium` and with nixos - `nixos.pkgs.chromium` ?

**Comment by edolstra** [comment]
Closing since `nix-env` will eventually be replaced by a `nix` command based on attribute names. Also, there is `nix search` now.

**Comment by BlackGlory** [comment]
Unfortunately, `nix search` is also slow, the manual is still using `nix-env -i`, and it is 2020.

**Comment by edolstra** [comment]
`nix search` is pretty fast with the evaluation cache:
```
$ time nix search nixpkgs firefox > /dev/null
warning: flake 'path:/nix/store/pczrv7nyb0cfjrmrg21lg710rihryyvy-source?lastModified=1591553018&narHash=sha256-B8uBh5QDSJF6sYvJbSzdF17kl6wzXwxzuMV8RAHVWxs=&rev=f8463ef8002037d339dfe5e2bbccb09eca7d13ad' has deprecated attribute 'edition'

real    0m0.590s
user    0m0.566s
sys     0m0.022s
```

**Comment by BlackGlory** [comment]
The first run of `nix search` consumes a lot of memory, which is also unacceptable on low memory servers.

**Comment by zyansheep** [comment]
`nix search <>` is fast, `nix-env` -i <> is slow. Any update on switching `nix-env` to `nix install` or something like that?

**Comment by edolstra** [comment]
There is `nix profile install` but it's marked experimental.
