### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by CowPeas** [NixOS/nix#4856]
OS is ubuntu 20.04. I have just installed Nix multi-user using the instructions on https://cardanoupdates.com/docs/57dd6ad3-2b7b-46cb-968e-96972ee5a168 . After installation none of the nix commands work. What am I doing wrong ?
This is an example of output I get "nix-store: command not found"

**Comment by abathur** [comment]
I'll outline the basics of what could be going on and what you might need to look into, but first: this kind of problem may need some iterative troubleshooting, and you may have an easier time getting quick iterative help via chat (unfortunately we've been disrupted by the trouble at Freenode, and I'm not sure there are "official" instructions yet; there are unofficial ones at https://discourse.nixos.org/t/join-us-on-matrix-at-nix-nixos-org-migrating-from-freenode/13166) or the forum (https://discourse.nixos.org).

1. If Nix installed successfully, confirm whether the commands work if you open a new terminal tab/window. If so, everything is fine--you might have just missed the installer telling you that you'd need to open a new shell or restart the existing one.
2. If the above didn't work, Nix's shell setup file isn't getting sourced in the process of loading your shell. 
    - I think the installer only supports bash, zsh, and any other shell that will source all files from `/etc/profile.d/*`. (If you use zsh, though: there have been some fixes to the zsh ~profile/rc setup and I'm unsure if they are all released).
    - If you've modified your shell rc/profile files, or installed any other programs that do, it's possible that Nix did correctly add itself to your files, but that something else in them aborts the loading process before it reaches Nix.

**Comment by CowPeas** [comment]
Thank you. I just removed all files related to nix, then re-installed Nix this time paying close attention to the files and it worked. The problem am now getting is setting up the cardano locally but I guess that may be a problem for another forum. Thanks again.
