### ISSUE TITLE
Nix path set with -I on nix repl is not transitiv

### ISSUE THREAD

**Issue by Kloenk** [NixOS/nix#4869]
**Describe the bug**
The NIX_PATH set with `-I` on `nix repl` is not forwarded to sub shells and :s calls.

**Steps To Reproduce**

1. make sure NIX_PATH is empty
2. start nix repl with `nix repl --sandbox --restrict-eval '<nixpkgs>' -I nixpkgs=channel:nixos-unstable`
3. start sub shell (e.g. `:s hello`)
4. nix repl errors

**Expected behavior**
`<nixpkgs>` should be set for :s and the resulting sub shell as NIX_PATH.

**`nix-env --version` output**
2.4pre20210525_dirty

**Comment by domenkozar** [comment]
Duplicates https://github.com/NixOS/nix/issues/1294
