### ISSUE TITLE
`~/.nix-defexpr` documentation

### ISSUE THREAD

**Issue by kirelagin** [NixOS/nix#487]
It is not really clear from `man nix-env` how `~/.nix-defexpr` is used. It is obvious what happens if it contains only `.nix`-files but it is somewhat hard to guess how subdirectories are handled (the truth is that the whole tree is traversed and all the expressions in it are combined into a top-level set).

Potentally confusing points are:
- If a directory is a valid expression (i.e. has `default.nix`) its expression will be added to the set, otherwise it will be traversed recursively.
- Names of intermidiate directories are completely ignored (i.e. do not take any part in attrpaths).
- `manifest.nix` is recursively ignored.

**Comment by copumpkin** [comment]
:+1:

**Comment by obadz** [comment]
@kirelagin, thanks for documenting this here. I found `~/.nix-defexpr`'s behavior uterly confusing and hoping it disappears in the new UI.

**Comment by chris-martin** [comment]
I'm still very confused about this. I always run `nix-env` with `-f '<nixpkgs>'` to sidestep the issue. I wish there were an environment variable for it.

**Comment by kamilchm** [comment]
One thing I learned today - `ln -s <nixpkgs> ~/.nix-defexpr` and I don't need to use `-f ` after that.

**Comment by BadDecisionsAlex** [comment]
The world may never know.

**Comment by jcrben** [comment]
Prolly could be closed now given https://github.com/NixOS/nix/pull/2945
