### ISSUE TITLE
`nix-shell` fails with "derivation '[/nix/store/[...]lowdown-0.8.4.drv' does not have wanted outputs 'bin,dev'"

### ISSUE THREAD

**Issue by Pamplemousse** [NixOS/nix#4872]
**Describe the bug**

Following [the manual](https://hydra.nixos.org/build/136801108/download/1/manual/contributing/hacking.html), I tried to run `nix-shell` to get the tools for `nix` development, but the command failed.

**Steps To Reproduce**

```bash
$ nix-shell
these 2 paths will be fetched (0.50 MiB download, 2.09 MiB unpacked):
  /nix/store/65gsy5sn6p368aqd0h38i1k5lpq9asfs-perl5.32.1-DBI-1.643
  /nix/store/8i4nq39i6r0ybi00i8v4cvx731h5mzc1-perl5.32.1-DBD-SQLite-1.66
error: derivation '/nix/store/y30pxp1m2vw56y6lzrqfvlxrzdr1qndh-lowdown-0.8.4.drv' does not have wanted outputs 'bin,dev'
```

**Expected behavior**

I expected to get a shell.

**`nix-env --version` output**

```bash
$ nix --version
nix (Nix) 2.4pre20210503_6d2553a
```

**Additional context**

`nix develop` works fine.

**Comment by matthewbauer** [comment]
This should be fixed by https://github.com/NixOS/nix/commit/8c7e043de2f673bc355d83f1e873baa93f30be62. To fix it, you'll need to upgrade the daemon to a Nix with that commit.

Is 2.4pre20210503_6d2553a the version from nixUnstable?

**Comment by Pamplemousse** [comment]
> Is 2.4pre20210503_6d2553a the version from nixUnstable?

I would say so as I have `nix.package = pkgs.nixUnstable;` in my `configuration.nix`;
Also, I am using the `nixos-unstable` channel.
