### ISSUE TITLE
Allow empty config `flake-registry = ""`, to disable default global flakes

### ISSUE THREAD

**Issue by bew** [NixOS/nix#4874]
**Is your feature request related to a problem? Please describe.**
For my Nix install, I **don't** want any global flake registries, as these are non-deterministic global states.

**Describe the solution you'd like**
To make the flake registry idempotent and not use any global state, I would like:
:point_right: The possibility to set `flake-registry = ""` in `nix.conf`, to skip the load of global flakes.

**Describe alternatives you've considered**
Creating a custom file containing `{}`, and pointing the config option to it.

The main downside being that the `nix.conf` file is not standalone anymore, and depends on a non-Nix-managed file.

**Comment by caseyhoward** [comment]
I ended up doing this:

```nix
let
  emptyFlakeRegistry = pkgs.writeText "flake-registry.json" (builtins.toJSON { flakes = []; version = 2; });
in
{
  nix = {
    extraOptions = ''
      flake-registry = ${emptyFlakeRegistry}
    '';
  };
}
```

This solves the non-Nix managed file problem and it gets rid of any warnings since the JSON is the correct format.

**Comment by wmertens** [comment]
you can also assign the flake used to build the system to the global flake with `nix.registry.nixpkgs.flake = self.inputs.nixpkgs;`. 

I do that and I also provide a nixpkgs path:

```nix
        {
          nix.nixPath = [
            # Point to a stable path so system updates immediately update
            "nixpkgs=/run/current-system/nixpkgs"
            # Allow using nixos-option to query current config
            "nixos-config=/run/current-system/flake/configuration.nix"
          ];
          system.extraSystemBuilderCmds = ''
            ln -s ${nixpkgs.outPath} $out/nixpkgs
            ln -s ${self.outPath} $out/flake
          '';
          nix.registry.nixpkgs.flake = self.inputs.nixpkgs;
        }
```

**Comment by bew** [comment]
Thanks but that only works on NixOS doesn't it?

**Comment by wmertens** [comment]
ah yes indeed. In that situation I'd expect to be able to choose what goes into the global registry declaratively.

**Comment by berbiche** [comment]
> Thanks but that only works on NixOS doesn't it?

Home Manager recently added a Nix registry module (a copy of the NixOS one).

**Comment by bew** [comment]
> Home Manager recently added a Nix registry module

If you're talking about the module configured under `nix.registry`, it allows to declaratively setup the _user_ registry (cf [this line](https://github.com/nix-community/home-manager/blob/838d40d61a91e3807836545c4b420572ab2d62eb/modules/misc/nix.nix#L80)), but cannot be used to reconfigure the _global_ registry AFAIK.

**Comment by adrian-gierakowski** [comment]
> ```nix
> system.extraSystemBuilderCmds
> ```

@wmertens how would I do that if I'm not using a flake to build the system? Thanks!
