### ISSUE TITLE
Manual says "substitute" defaults to "false"

### ISSUE THREAD

**Issue by t184256** [NixOS/nix#4887]
Unstable manual says `substitute` defaults to `false`:

```
substitute

If set to true (default), Nix will use binary substitutes if available. This option can be disabled to force building from source.

Default: false
```

https://nixos.org/manual/nix/unstable/command-ref/conf-file.html

**Comment by VwCSXg** [comment]
This is fixed: https://nixos.org/manual/nix/unstable/command-ref/conf-file.html#conf-substitute
