### ISSUE TITLE
Failure to build nvidia-settings package when specifying --store

### ISSUE THREAD

**Issue by liamwhite** [NixOS/nix#4912]
First occurred to me in the context of nixos-install, when specifying allowUnfree and adding nvidia to xorg video drivers. See also https://github.com/NixOS/nixpkgs/issues/126141

Reproduced in a fresh VM with the following:
- nix-store --store /mnt --import < weird-nvidia-drv-export
- nix-store --store /mnt -r /nix/store/sy1bsk9crlill0psxaalfrfb7bdzqfpw-nvidia-settings-460.73.01.drv
[weird-nvidia-drv-export.zip](https://github.com/NixOS/nix/files/6643471/weird-nvidia-drv-export.zip) (zipped because of github's asinine limitations on file uploads)

![Screenshot from 2021-06-13 03-38-24](https://user-images.githubusercontent.com/9658600/121799215-d4f3af80-cbf8-11eb-844a-daeb9db1f665.png)

VM invocation:
- qemu-system-x86_64 -enable-kvm -boot d -cdrom ~/Downloads/nixos-gnome-21.05.956.81b3481d79a-x86_64-linux.iso -m 8192 -smp 16

**Expected behavior**

Should not fail to getattr() [-ENOENT] on a path it supposedly just copied from the binary cache

**`nix-env --version` output**

nix-env (Nix) 2.3.12

**Comment by balsoft** [comment]
Does not reproduce with `nix (Nix) 2.4pre20210604_8e6ee1b` (the derivation realises successfully)

**Comment by liamwhite** [comment]
Fixed by https://github.com/NixOS/nix/commit/89fba5c8473b8f8b2133698f1e1b9b14535c0bc0
