### ISSUE TITLE
nix-daemon based install fails on Fedora 34 due to SELinux 

### ISSUE THREAD

**Issue by houstdav000** [NixOS/nix#4913]
**Describe the bug**

When you try the multi-user install in Fedora 34, it quickly fails. As expected, `journalctl` reveals this to be an SELinux issue.

**Steps To Reproduce**

1. Create Fedora 34 machine
2. Try to install Nix with `sh <(curl -L https://nixos.org/nix/install) --daemon`
3. Choose to do a multi-user install
4. Put in the `sudo` password

**Expected behavior**

An errorless installation.

**`nix-env --version` output**

N/A since setup fails.

**Additional context**

I'm not going to paste the whole mess of it, but basically I get the message:

```text
I am executing:

    $ sudo systemctl link /nix/var/nix/profiles/default/lib/systemd/system/nix-daemon.service

to set up the nix-daemon service

Failed to link unit: Access denied
```

Checking `journalctl` showed this:

```text
SELinux is preventing systemd from read access on the lnk_file default.
```

This is probably just an extra config thing necessary for if SELinux is present, but I'm not sure.

**Comment by domenkozar** [comment]
Duplicates https://github.com/NixOS/nix/issues/2374
