### ISSUE TITLE
Warn me if my settings don't make sense

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#495]
Sometimes I'll have a typo in `foo` when writing `--option foo` on the command line and nix will happily proceed and do something I didn't want. It would be nice if all options passed through a fixed struct rather than being `.get`-able at runtime, so we can statically determine if sensible options have been passed in. An alternate approach is to just record whether an option gets read during execution and warning the user if certain options were unused. I think clang and other llvm tools do something similar to the latter.

**Comment by AmineChikhaoui** [comment]
👍 
Also recently I used --option signed-binary-caches instead of require-sigs, the first was silently ignored and the daemon raised invalid signature exception while the second works perfectly. So in this case it seems one of the options was deprecated in favor of another so a warning would be nice.

**Comment by AmineChikhaoui** [comment]
Also what's the point of having both ?
```
[amine@nixos:~]$ nix show-config | grep sig
require-sigs = true
signed-binary-caches = *
```

**Comment by copumpkin** [comment]
I think as of 1.12 it should warn you about bad settings. I personally would have preferred errors but I'll take warnings 😄

**Comment by AmineChikhaoui** [comment]
Actually I was using nix 1.12 but there was no warnings :/

**Comment by copumpkin** [comment]
Strange, I swear I've seen them before. Maybe because it recognizes the setting but doesn't do something with it? Try putting an obvious typo in. The warning code might need some tweaking for deprecated settings like this.

**Comment by AmineChikhaoui** [comment]
```
[root@machine:~]# nix copy /nix/store/003d9libxs124zgm7ryfl4l6r31md2wb-nixops-machines --from "<path/to/binary/cache>" --option blabla true
[0 copied (0.0 MiB)]
error: cannot add path '/nix/store/003d9libxs124zgm7ryfl4l6r31md2wb-nixops-machines' because it lacks a valid signature
```

**Comment by copumpkin** [comment]
Pretty sure this is addressed now 😄thanks @edolstra!
