### ISSUE TITLE
How to keep build dir & build dependencies?

### ISSUE THREAD

**Issue by Silex** [NixOS/nix#4950]
Hello,

I have the following working package installation:

``` shell
nix-env -iA emacs-26-3 -f https://github.com/silex/nix-emacs-ci/archive/master.tar.gz
```

This works fine, however my goal is now to keep the build dir and the build tools (make etc). I tried using `nix-build` with `-K` but that only works for *failed* builds.

Thus I modified https://github.com/Silex/nix-emacs-ci/blob/test/emacs.nix and added `postFixup = "cp -a $(pwd) /tmp/mybuilddir";`, which works in the sense I have the build dir but I'm missing all the tools/build libs etc.

I guess I could `nix-env -iA ${buildInputs}` or something but there has to be a better way :sweat_smile:

**Comment by Silex** [comment]
Hum, I realised I could do a new recipe and what I'm trying to do is a bit against nix principles.

Feel free to close this, and if you can point me to what would be the simplest to achieve what I want (sometimes install a package, sometimes put in in "dev mode" with all `buildInputs` installed and the build dir accessible to fiddle with it) I'm all ears :wink:

**Comment by bjornfor** [comment]
Did you try using `nix-shell` on that derivation/package?

**Comment by Silex** [comment]
@bjornfor: no, I'm a nix newbie. Also this is meant to be used in a docker image so the effects of nix-shell needs to be permanent (the command has to exit).
