### ISSUE TITLE
Ability to change permissions of user home directory

### ISSUE THREAD

**Issue by Armoken** [NixOS/nix#5001]
I am trying to setup minidlna server  which run from minidlna user and can't read directories with media content from my user's home directory due to 700 permissions on it.

I think that option users.user.<name>.homeDirectoryPermissions wich require integer or string chmod value will be enough comfortable.

**Comment by bjornfor** [comment]
Hi, sorry, wrong repo. Please resubmit this in the nixpkgs issue tracker. (This is the package manager repo.)

**Comment by Armoken** [comment]
@bjornfor Excuse me! Ok.

**Comment by keithy** [comment]
Not the wrong repo. The enforced users permissions is on his home directory.
