### ISSUE TITLE
No documentation on how to use nix to reproduce a system _including_ versions

### ISSUE THREAD

**Issue by konobi** [NixOS/nix#504]
This may be an aspect of nix that I've missed, but it's unclear how to take the nix configuration files and "<something>" to have a way to recreate an install again and again with the same versioning.

Can we get some documentation around that, either in the manual or on the wiki.

thanks!

**Comment by lethalman** [comment]
If you want to make sure the software versions are the same, just use the same nixpkgs commit.

**Comment by edolstra** [comment]
This will be addressed by flakes, closing.
