### ISSUE TITLE
Nix upgraded ca-schema, but not itself

### ISSUE THREAD

**Issue by Mindavi** [NixOS/nix#5044]
**Describe the bug**

I get this error:

`error: current Nix store ca-schema is version 2, but I only support 1`

It appears that the ca database schema has been updated to a new version, but nix itself was not updated.

**Steps To Reproduce**

1. Rebuild system with `nixos-rebuild switch`.
2. The build fails due to system-config-printer being broken.
3. Rebuild system again
4. Observe that the schema was updated, but since the rebuild failed, nix was not updated.

**Expected behavior**

I guess the schema upgrade should be run at a later moment? It should at least not break this.

**`nix-env --version` output**

nix-env (Nix) 2.4pre20210601_5985b8b

**Additional context**

`nixos-rebuild` was failing due to https://github.com/NixOS/nixpkgs/issues/130969.

The nix daemon also appears to be broken:

```
# shell
rick@nixos-asus:~/nixpkgs$ nix-shell -p nixUnstable
error: cannot open connection to remote store 'daemon': error: reading from file: Connection reset by peer
(use '--show-trace' to show detailed location information)

# journalctl
nix-daemon[1984]: accepted connection from pid 3542, user rick
nix-daemon[3552]: unexpected Nix daemon error: error: current Nix store ca-schema is version 2, but I only support 1
```

Is there any way to work around this by getting a newer nix version installed somehow?

**Comment by roberth** [comment]
> **`nix-env --version` output**
> 
> nix-env (Nix) 2.4pre20210601_5985b8b

`nixUnstable` in `nixos-unstable` is newer. I don't think forward compatibility is a goal for experimental features, so you'll want to make sure to use consistent versions of `nixUnstable` in `nix-shell`s etc.

If you're on NixOS `21.05`, `nixUnstable` `2.4pre20210707_02dd6bb` has reached channel `nixos-21.05-small` but it's not in ` nixos-21.05` yet.

**Comment by Mindavi** [comment]
I think nixos-rebuild starts with getting a newer version of nix. So it got that, executed it (and upgraded the store), then the build failed. However, the store was still updated to the newer scheme.

**Comment by roberth** [comment]
Can you rebuild with ca-derivations turned off?

**Comment by Mindavi** [comment]
How can I convince nix to disable it? Can I override the config with a config file in ~/nix/nix.conf? The daemon is not very happy, so I'll have to fix that to rebuild somehow.

**Comment by roberth** [comment]
I should have asked whether you've turned it on in the first place. You can check with `nix show-config | grep experim; sudo nix show-config | grep experim`. If that shows ca derivations, you should be able to remove it from your NixOS configuration. The `sudo` is relevant because the feature applies to the daemon.

I would expect this schema check to be behind the feature flag as well. If it's not, that's a bug.

**Comment by Mindavi** [comment]
It is enabled, I'm not sure how to disable it though, because I can't nixos-rebuild, and reverting doesn't help as far as I understand.

**Comment by roberth** [comment]
You could replace `/etc/nix/nix.conf` by a regular file as a temporary measure that will let you disable it.

**Comment by Mindavi** [comment]
Thanks! I was already looking at that file, but (of course) couldn't edit is as-is. Replacing it with a file without ca-derivations fixes it. I'm happy it's a simple solution in the end :). Thanks again :tada:
