### ISSUE TITLE
SCP-style URLs in `builtins.fetchGit` still broken

### ISSUE THREAD

**Issue by considerate** [NixOS/nix#5061]
**Describe the bug**

Evaluating builtins.fetchGit with a git SCP-like URL causes the error:
`error: 'file://git@github.com:NixOS/nix.git' is not a valid URL`

This was originally reported in #3503 and fixed in https://github.com/NixOS/nix/pull/4978 but the version 02dd6bb610e55a009cd7a4c83639698d3a7acaa2 of nix which contains this PR still results in the broken behavior.

**Steps To Reproduce**

create test.nix with this content:
```
builtins.fetchGit {
  url = "git@github.com:NixOS/nix.git";
  ref = "master";
  rev = "02dd6bb610e55a009cd7a4c83639698d3a7acaa2";
}
```

Run `nix-build test.nix`

**Expected behavior**

The nix repo should be downloaded and a symlink should be created.

**`nix-env --version` output**

```
nix-env (Nix) 2.4pre20210707_02dd6bb
```

**Comment by regnat** [comment]
Indeed, it looks like #4978 only fixed `builtins.fetchGit "git@…"` and not `builtins.fetchGit { url = "git@…"; }`:

```
nix-repl> builtins.fetchGit "git@github.com:NixOS/nix.git"
{ lastModified = 1627468261; lastModifiedDate = "20210728103101"; narHash = "sha256-rpPXcGhgCUo9fCF6aqez8ZaU4vlhvwM3NaDhSO9XWLg="; outPath = "/nix/store/fgnma6ppv68lchgim8wp1l8mlczjdmzm-source"; rev = "7816ef6c5123ef0f11b8b86439dd6b934c1e5426"; revCount = 10533; shortRev = "7816ef6"; submodules = false; }

nix-repl> builtins.fetchGit { url = "git@github.com:NixOS/nix.git"; }
error: 'file://git@github.com:NixOS/nix.git' is not a valid URL
```

**Comment by considerate** [comment]
I think it might be due to this call: https://github.com/NixOS/nix/blob/ec2c6bd47041bda1f30e66ee48de662ddcd07378/src/libexpr/primops/fetchTree.cc#L106

`addURI` calls `fixURI` regardless of the type of the tree.

**Comment by considerate** [comment]
On a somewhat unrelated note, this case seems to be redundant/inaccessible:

https://github.com/NixOS/nix/blob/ec2c6bd47041bda1f30e66ee48de662ddcd07378/src/libexpr/primops/fetchTree.cc#L112

The first case already hits if the type is `nString`.
