### ISSUE TITLE
macOS Installer doesn't handle a .zshrc file that doesn't end with a newline

### ISSUE THREAD

**Issue by hborders** [NixOS/nix#5068]
**Describe the bug**

The installer appends the nix source imports directly to the end of the `.zshrc` file. When I run the installer on macOS 11.4 with a `.zshrc` file that doesn't end with a newline, the installer creates a `zsh` syntax error because my file ends with a `fi`, so my last line starts with:
```
fiif [
```

If you have a problem with a specific package or NixOS,
you probably want to file an issue at https://github.com/NixOS/nixpkgs/issues. 

**Steps To Reproduce**

1. Create a macOS EC2 instance with the macOS 11.4 image: `ami-0b3c31b0c66a46614`
1. Ensure your `~/.zshrc` file doesn't end in a newline
1. Run the installer in single-user mode: 
```
sh <(curl -L https://nixos.org/nix/install) --darwin-use-unencrypted-nix-store-volume
```
1. Open a new terminal session
1. See error

**Expected behavior**

The installer handles `.zshrc` files that don't end in a newline. I realize that well-behaved unix text files should end with a newline, but the AWS EC2 image doesn't. Adding a newline before appending the source loading is a small price to pay.

**Comment by abathur** [comment]
I think this is the same case described in #4990 and according to https://github.com/NixOS/nix/issues/4990#issuecomment-875485742 there's a fix in master already that isn't backported to 2.3. If you try the numtide installer I mentioned in https://github.com/NixOS/nix/issues/4779#issuecomment-889293071, can you confirm that you don't see this behavior?

**Comment by hborders** [comment]
Yes, this does look the same as #4990. I'll close this.
