### ISSUE TITLE
Building nix master branch fails on ubuntu 14.10 with a SODIUM_LIBS error

### ISSUE THREAD

**Issue by krafczyk** [NixOS/nix#507]
Once issue #506 is fixed, The build fails with the following output:

  LD     src/nix-store/nix-store
g++: error: @SODIUM_LIBS@: No such file or directory
mk/lib.mk:103: recipe for target 'src/nix-store/nix-store' failed
make: **\* [src/nix-store/nix-store] Error 1

**Comment by krafczyk** [comment]
installing libsodium from here: https://github.com/jedisct1/libsodium
did not fix the issue.

**Comment by edolstra** [comment]
Hm, it builds fine on Ubuntu 14.10 in our build farm: http://hydra.nixos.org/job/nix/master/deb_ubuntu1410x86_64/all

**Comment by domenkozar** [comment]
@krafczyk can you provide a http://sscce.org/? Specifically which installation path you chose.

**Comment by edolstra** [comment]
Closing on account of age.
