### ISSUE TITLE
Allow fetching remote build logs with ssh-ng://

### ISSUE THREAD

**Issue by symphorien** [NixOS/nix#5079]
**Describe the solution you'd like**
`nix-build foo.drv --store ssh-ng://host` and then one of `nix log foo.drv --store ssh-ng://host` or `nix log foo.drv --option substituters ssh-ng://host` should show the build log of foo.drv

**Describe alternatives you've considered**
maybe add an option to copy build logs with `nix copy` ?

**Additional context**
If I grepped the code correctly, the operation `getBuildLog` is only implemented for local stores and http substituters.

**Comment by Ericson2314** [comment]
CC @matthewbauer since #5014
