### ISSUE TITLE
Support linking a channel directly to a remote tarball of nix expressions

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#508]
I know that I can make a local git clone and manually repoint all my commands with `-I nixpkgs /path/to/my/nixpkgs` (or change my `NIX_PATH`) but that's error-prone and seems a little brittle when my goal is to have my system's primary source be a ref of a git repo. 

Is this already possible? Am I doing something wrong? My main motivation is that it's a multi-step process to set up a custom channel and I don't have the resources to do that right now. At the same time, lots of things seem to assume channels, so it feels like I'm working against the grain to get my nixos-rebuild to point somewhere else.

**Comment by edolstra** [comment]
I'd rather not make Nix depend on Git, since it's a pretty big dependency. 

However, in the case of a GitHub repository, it might be possible to use `https://github.com/<repo>/archive/master.tar.gz` to get the channel Nix expressions.

**Comment by copumpkin** [comment]
Good point! So you'd be open to letting nix-channel point to an arbitrary tarball URL of expressions? That seems fairly easy for me to implement.

**Comment by edolstra** [comment]
Yes. The main question is how to distinguish it from a "normal" channel URL, but I guess you can just check whether it ends with .tar.*.

**Comment by cstrahan** [comment]
> I'd rather not make Nix depend on Git, since it's a pretty big dependency.

FWIW, [libgit2](https://libgit2.github.com/) is fairly minimal and might be worth considering.
