### ISSUE TITLE
nix run without flakes no longer accepts ``-c`` argument

### ISSUE THREAD

**Issue by SuperSandro2000** [NixOS/nix#5081]
**Describe the bug**

``nix run`` with flakes disabled no longer takes the ``-c`` argument.

**Steps To Reproduce**

```ShellSession
$ nix run -f https://github.com/jtojnar/nixpkgs-hammering/archive/master.tar.gz -c nixpkgs-hammer
error: unrecognised flag '-c'
Try '$HOME/.nix-profile/bin/nix --help' for more information
```

**Expected behavior**

It should just work like in stable or older unstable versions

**`nix-env --version` output**

```ShellSession
$ nix-env --version
nix-env (Nix) 2.4pre20210707_02dd6bb
```

**Additional context**

**Comment by edolstra** [comment]
The old `nix run` has been renamed to `nix shell`. `nix run` is now a command that runs an "app", which is a specification of a program to execute (e.g. `nix run nixpkgs#gimp`). This should work:

```
# nix shell -f https://github.com/jtojnar/nixpkgs-hammering/archive/master.tar.gz -c nixpkgs-hammer
```

**Comment by milahu** [comment]
> The old `nix run` has been renamed to `nix shell`.

d6b4047c2fd8c197bf7a9f0f9a2f1cfb214e2e89 &rarr; nix 2.4 and later have `nix shell`
