### ISSUE TITLE
{placeholder out} returns a path without the /nix/store prefix

### ISSUE THREAD

**Issue by teto** [NixOS/nix#5083]
**Describe the bug**

with nix (Nix) 2.4pre20210707_02dd6bb ` {placeholder "out"}`  generates `/1rz4g4znpzjwh1xymhjpm42vipw92pr73vdgl6xs1hycac8kf2n9/bin/helm` without the /nix/store prefix. I find it awkward. 
 What's even weirder is that with the same nix version, same flake.nix/lock, `nix develop` starts on my computer (nixos) but fails on my colleague's (nix on ubuntu). 

**Steps To Reproduce**

run `nix develop` on the following flake.nix:
```
{
  description = "To deploy saas infra";

  inputs = {
    # flake-compat = { url = "github:edolstra/flake-compat"; flake = false; };
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachSystem [ "x86_64-linux" ] (system: let
      pkgs = import nixpkgs { inherit system; };
  in {
    devShell = let

      myHelm = with pkgs; wrapHelm kubernetes-helm {
        plugins = with kubernetes-helmPlugins; [
          helm-s3 # broken on unstable
        ];
      };

      myPythonEnv = with pkgs; python3.withPackages(p: with p;[
        boto3
        psycopg2
        openshift # custom
        kubernetes
      ]);
    in
    pkgs.stdenv.mkDerivation {

      name = "saas";

      buildInputs = with pkgs; [
        ansible
        jq
        myPythonEnv
        eksctl
        envsubst
        docker-compose
        myHelm
        kustomize
        # ansible-lint  # broken on unstable

        # for frontend install
        nodejs
        nodePackages.npm
      ];

    };

  });
}


```

once inside the `nix develop` shell if you can run `which helm` that returns a path, I guess:
`nix show-derivation /nix/store/z1627qk94md3164bllcbbh9ngpc4d9aw-helm-3.6.1/bin/helm` which outputs:
```
      "buildCommand": "mkdir -p $out\nfor i in $(cat $pathsPath); do\n  /nix/store/v8m4lb5a6skw17jz1y0gxkz91khwia9d-lndir-1.0.3/bin/lndir -silent $i $out\ndone\nrm $out/bin/helm\nmakeWrapper '/nix/store/gygbpy58vkpyn7n1sac25pdnccb5fmgy-helm-3.6.1/bin/helm' '/1rz4g4znpzjwh1xymhjpm42vipw92pr73vdgl6xs1hycac8kf2n9/bin/helm' '--argv0' '$0' '--set' 'HELM_PLUGINS' '/nix/store/ww87hcqy8zpxcmw8nimaqpryfayllj2p-helm-plugins'  \n\n",
```
note the ` '/1rz4g4znpzjwh1xymhjpm42vipw92pr73vdgl6xs1hycac8kf2n9/bin/helm' ` which looks fishy ?

**Comment by cole-h** [comment]
`placeholder "out"` will just generate a hash of that string (if you run it in `nix repl`, you'll see it will always return `/1rz4g4znpzjwh1xymhjpm42vipw92pr73vdgl6xs1hycac8kf2n9`). The derivation builder will replace it with what `$out` really is, once it knows itself what it will be.

If there is a bug, it's not `placeholder "out"` misbehaving -- it's doing exactly what it should be:

https://github.com/NixOS/nix/blob/47e96bb533f8cacc171bec9b688b134de31a48a9/src/libexpr/primops.cc#L1236-L1246

**Comment by teto** [comment]
thanks for the answer, I was actually not sure how to use "placeholder". I've a local fix for the helm wrapper derivation that I will submit.
