### ISSUE TITLE
Store path length limit?

### ISSUE THREAD

**Issue by dhess** [NixOS/nix#5086]
What's the technical reason for the 211-character store path length limit?

https://github.com/NixOS/nix/blob/7c90552879da4d1df99b50c85e94201981e60123/src/libstore/path.cc#L9

I'm using [npmlock2nix](https://github.com/tweag/npmlock2nix) to package a React app, and I'm running into this limitation:

```
error: store path 'w0p04i8klrmla412sxk0539dpx45c408-qpl7imy79n9sd9a2h6s7armj9vqaal70-rk74xqfkqgc282lxhym3vwd9ww35iv7n-9sp1q8q5p3r6h2qm4g74ycp1f7b44zv7-9ikdajp8imc685n5vmiib3f9lny2ygz0-0xnc8c7z7rzxp1hf0vfdjwhhvwd19q3b-helper-builder-binary-assignment-operator-visitor-7.14.5.tgz' has a name longer than 211 characters
```

**Comment by edolstra** [comment]
The 211-character limit is motivated in this commit 693e68e09c9a17ca72b074bd2e575bf435647b45.

**Comment by dhess** [comment]
Wow, I'm surprised ext4's limit is so short.

In any case, I will close this as it seems unlikely to change. I'll take it up with the npmlock2nix maintainers.
