### ISSUE TITLE
Nix 2.3.15 Sandbox Domain Resolution Failures

### ISSUE THREAD

**Issue by kittywitch** [NixOS/nix#5089]
**Describe the bug**

Since the update to 2.3.15, nix build is no longer able to resolve domain lookups with sandboxing:

```
warning: unable to download 'http://tarballs.nixos.org/sha256/73d3baf18cf0a197976af2794a848893c35e7d42cee0ff364c89d2e476ebdaa6': Couldn't resolve host name (6); retrying in 300 ms
warning: unable to download 'http://tarballs.nixos.org/sha256/74d97de74c1d4d5cc146182dbbf9cdc3f383ba4c5d1492edbdb14351549a9d64': Couldn't resolve host name (6); retrying in 351 ms
warning: unable to download 'http://tarballs.nixos.org/sha256/73d3baf18cf0a197976af2794a848893c35e7d42cee0ff364c89d2e476ebdaa6': Couldn't resolve host name (6); retrying in 658 ms
warning: unable to download 'http://tarballs.nixos.org/sha256/74d97de74c1d4d5cc146182dbbf9cdc3f383ba4c5d1492edbdb14351549a9d64': Couldn't resolve host name (6); retrying in 518 ms
warning: unable to download 'http://tarballs.nixos.org/sha256/74d97de74c1d4d5cc146182dbbf9cdc3f383ba4c5d1492edbdb14351549a9d64': Couldn't resolve host name (6); retrying in 1366 ms
warning: unable to download 'http://tarballs.nixos.org/sha256/73d3baf18cf0a197976af2794a848893c35e7d42cee0ff364c89d2e476ebdaa6': Couldn't resolve host name (6); retrying in 1155 ms
warning: unable to download 'http://tarballs.nixos.org/sha256/73d3baf18cf0a197976af2794a848893c35e7d42cee0ff364c89d2e476ebdaa6': Couldn't resolve host name (6); retrying in 2750 ms
warning: unable to download 'http://tarballs.nixos.org/sha256/74d97de74c1d4d5cc146182dbbf9cdc3f383ba4c5d1492edbdb14351549a9d64': Couldn't resolve host name (6); retrying in 2416 ms
warning: unable to download 'https://addons.mozilla.org/firefox/downloads/file/3782413/new_tab_override-15.1.1-fx.xpi': Couldn't resolve host name (6); retrying in 298 ms
warning: unable to download 'https://www.rarlab.com/rar/unrarsrc-5.9.2.tar.gz': Couldn't resolve host name (6); retrying in 341 ms
warning: unable to download 'https://addons.mozilla.org/firefox/downloads/file/3782413/new_tab_override-15.1.1-fx.xpi': Couldn't resolve host name (6); retrying in 546 ms
warning: unable to download 'https://www.rarlab.com/rar/unrarsrc-5.9.2.tar.gz': Couldn't resolve host name (6); retrying in 590 ms
warning: unable to download 'https://addons.mozilla.org/firefox/downloads/file/3782413/new_tab_override-15.1.1-fx.xpi': Couldn't resolve host name (6); retrying in 1310 ms
warning: unable to download 'https://www.rarlab.com/rar/unrarsrc-5.9.2.tar.gz': Couldn't resolve host name (6); retrying in 1052 ms
warning: unable to download 'https://addons.mozilla.org/firefox/downloads/file/3782413/new_tab_override-15.1.1-fx.xpi': Couldn't resolve host name (6); retrying in 2534 ms
warning: unable to download 'https://www.rarlab.com/rar/unrarsrc-5.9.2.tar.gz': Couldn't resolve host name (6); retrying in 2033 ms
```

**Steps To Reproduce**

1. Use Nix 2.3.15
2. Use the stock nsswitch.conf from NixOS (presumably with resolved enabled)

**Expected behavior**

Domain lookups to work.

**`nix-env --version` output**

```
❯ nix-env --version
nix-env (Nix) 2.3.15
```

**Additional context**

I tried building without the sandbox, which made it able to resolve domain lookups. This indicates the sandbox cannot actually resolve things as a result of e8711461794ffec203911cc7b6cc4c1319e8f74d. On top of this, at the suggestion of @arcnmx, I removed `[!UNAVAIL=return]` from the host nsswitch.conf and built something differently (for which downloads weren't cached) with sandbox on. ~~It was able to do resolution again.~~ It did not adequately fix the problem.

resolv.conf is currently: `nameserver 1.1.1.1` for testing purposes, however:

I use `useLocalResolver` with resolvconf, for dnscrypt-proxy purposes normally.

I was suggested `--extra-sandbox-paths /var/run/nscd/socket=/var/run/nscd/socket` and this actually makes it work perfectly. This would suggest that the behavior at hand is indeed caused by the removal of nscd socket passthrough and the alternative workaround in the PR not sufficiently working. 

I will be using `nix.sandboxPaths = [ "/var/run/nscd/socket" ];` as a workaround for the time being.

**Comment by arcnmx** [comment]
To give a bit more context from troubleshooting, I believe this is specifically an issue with the builtin fetchers (`<nix/fetchurl.nix>` and/or builtins.fetchurl?) being executed from within the sandbox, but somehow using the host nsswitch.conf.

Despite ec0087df0a2da5c68363b3f4509d4545deed97a0, I can only assume it's because the builtin builders fork off from a previously initialized libnss? It happened to work fine previously due to the nscd socket being included in the sandbox, so removing it exposed the bug?

**Comment by edolstra** [comment]
There is indeed some special magic to initialize NSS for the builtin builders, see `preloadNSS()` in `src/libstore/build/local-derivation-goal.cc`.

**Comment by domenkozar** [comment]
Could be related to https://github.com/NixOS/nix/commit/1c51a169fb7d3e32cb8c4684353e57020f9d2019 ?

**Comment by domenkozar** [comment]
This is quite a serious regression, any kind of building of FOD on Linux breaks.

**Comment by u1f408** [comment]
I'm also affected by this, ran into the issue immediately after a new installation of NixOS. Can confirm that the workarounds at the bottom of https://github.com/NixOS/nix/issues/5089#issue-959828283 work as intended (and if it wasn't for that, I wouldn't have a working machine)

**Comment by andir** [comment]
It looks like hydra has the same / a similar bug: https://matrix.to/#/!RROtHmAaQIkiJzJZZE:nixos.org/$A6A7yD7kb7lxqC-Q--z547eVwXS5edaMBciUy37eCfA?via=nixos.org&via=matrix.org&via=fairydust.space

**Comment by davidak** [comment]
I had the issue when running this:

```
nix run \
  --option extra-substituters 'https://nixpkgs-update.cachix.org/' \
  --option trusted-public-keys 'nixpkgs-update.cachix.org-1:6y6Z2JdoL3APdu6/+Iy8eZX2ajf09e4EE9SnxSML1W8=' \
  -f https://github.com/ryantm/nixpkgs-update/archive/master.tar.gz \
  -c nixpkgs-update --help
```

```
warning: unable to download 'https://ftpmirror.gnu.org/bash/bash-4.4.tar.gz': Couldn't resolve host name (6); retrying in 2720 ms
warning: unable to download 'https://ftpmirror.gnu.org/bash/bash-4.4-patches/bash44-002': Couldn't resolve host name (6); retrying in 2434 ms
warning: unable to download 'http://tarballs.nixos.org/sha256/7020a0183e17a7233e665b979c78c184ea369cfaf3e8b4b11f5547ecb7c13c53': Couldn't resolve host name (6); retrying in 2004 ms
...
```

my system can resolve them

```
[davidak@gaming:~/code/nixpkgs]$ host tarballs.nixos.org
tarballs.nixos.org is an alias for d3am6xf9zisc71.cloudfront.net.
d3am6xf9zisc71.cloudfront.net has address 143.204.98.115
d3am6xf9zisc71.cloudfront.net has address 143.204.98.118
d3am6xf9zisc71.cloudfront.net has address 143.204.98.110
d3am6xf9zisc71.cloudfront.net has address 143.204.98.9
d3am6xf9zisc71.cloudfront.net has IPv6 address 2600:9000:2156:3200:19:770e:af40:93a1
d3am6xf9zisc71.cloudfront.net has IPv6 address 2600:9000:2156:a800:19:770e:af40:93a1
d3am6xf9zisc71.cloudfront.net has IPv6 address 2600:9000:2156:ea00:19:770e:af40:93a1
d3am6xf9zisc71.cloudfront.net has IPv6 address 2600:9000:2156:e600:19:770e:af40:93a1
d3am6xf9zisc71.cloudfront.net has IPv6 address 2600:9000:2156:dc00:19:770e:af40:93a1
d3am6xf9zisc71.cloudfront.net has IPv6 address 2600:9000:2156:ce00:19:770e:af40:93a1
d3am6xf9zisc71.cloudfront.net has IPv6 address 2600:9000:2156:7400:19:770e:af40:93a1
d3am6xf9zisc71.cloudfront.net has IPv6 address 2600:9000:2156:6200:19:770e:af40:93a1

[davidak@gaming:~/code/nixpkgs]$ host ftpmirror.gnu.org
ftpmirror.gnu.org is an alias for ftpmirror.savannah.gnu.org.
ftpmirror.savannah.gnu.org has address 209.51.188.200
ftpmirror.savannah.gnu.org has IPv6 address 2001:470:142:5::200
```

did not had the issue with nixos-rebuild or nix-env

**Comment by baloo** [comment]
I've unable to reproduce the issue myself, all my machines are running with local resolvers.

So I wrote a nix test:
```
# nixpkgs/nixos/tests/nix-fetch.nix
import ./make-test-python.nix ({ lib, ... } : {
  name = "nixos-generate-config";
  meta.maintainers = with lib.maintainers; [ baloo ];

  nodes = {
    http_dns = { lib, pkgs, config, ... }: {
      networking.firewall.enable = false;
      networking.interfaces.eth1.ipv6.addresses = lib.mkForce [
        { address = "fd21::1"; prefixLength = 64; }
      ];
      networking.interfaces.eth1.ipv4.addresses = lib.mkForce [
        { address = "192.168.0.1"; prefixLength = 24; }
      ];

      services.unbound = {
        enable = true;
        enableRootTrustAnchor = false;
        settings = {
          server = {
            interface = [ "192.168.0.1" "fd21::1" "::1" "127.0.0.1" ];
            access-control = [ "192.168.0.0/24 allow" "fd21::/64 allow" "::1 allow" "127.0.0.0/8 allow" ];
            local-data = [
              ''"example.net. IN A 192.168.0.1"''
              ''"example.net. IN AAAA fd21::1"''
            ];
          };
        };
      };

      services.nginx = {
        enable = true;
        virtualHosts."example.net" = {
          root = pkgs.runCommand "testdir" {} ''
            mkdir "$out"
            echo hello world > "$out/index.html"
          '';
        };
      };
    };

    # client consumes a remote resolver
    client = { lib, nodes, pkgs, ... }: {
      networking.useDHCP = false;
      networking.nameservers = [
        (lib.head nodes.http_dns.config.networking.interfaces.eth1.ipv6.addresses).address
        (lib.head nodes.http_dns.config.networking.interfaces.eth1.ipv4.addresses).address
      ];
      networking.interfaces.eth1.ipv6.addresses = [
        { address = "fd21::10"; prefixLength = 64; }
      ];
      networking.interfaces.eth1.ipv4.addresses = [
        { address = "192.168.0.10"; prefixLength = 24; }
      ];

      #nix.sandboxPaths = [ "/var/run/nscd/socket" ];
      nix.package = pkgs.nixUnstable;
    };
  };

  testScript = { nodes, ... }: ''
    http_dns.wait_for_unit("nginx")
    http_dns.wait_for_open_port(80)
    http_dns.wait_for_unit("unbound")
    http_dns.wait_for_open_port(53)

    client.start()
    client.wait_for_unit('multi-user.target')

    with subtest("can fetch data from a remote server outside sandbox"):
        client.succeed("curl -vvv http://example.net/index.html >&2")

    with subtest("nix-build can lookup dns and fetch data"):
        client.succeed("""
          nix-build -E '
            builtins.derivation {
              src = builtins.fetchurl {
                url = "http://example.net/index.html";
                sha256 = "0ix4jahrkll5zg01wandq78jw3ab30q4nscph67rniqg5x7r0j59";
              };
              name = "trivial";
              system = "${builtins.currentSystem}";
              builder = "/bin/sh";
              allowSubstitutes = false;
              preferLocalBuild = true;
              args = ["-c" "echo success > $out; exit 0"];
            }'
          """)
  '';
})
```

I'm unable to reproduce the issue there either. If someone has a better idea how to reproduce this...

**Comment by expede** [comment]
I'm still debugging, but wanted to report in that I'm also seeing this.

* macOS 11.5.2
* Only when installed without Rosetta (i.e. darwin-aarch64)

DNS resolution for these URLs works outside of Nix. For example, on a fresh install, there's a bunch of these:

```
$ nix-shell -p nix-info --run "nix-info -m"
[...]
warning: unable to download 'http://tarballs.nixos.org/sha256/bed128fe32c7cdb540ab54b3b7e615ac5adb7322472e52733575aa31a61843ec': Couldn't resolve host name (6); retrying in 289 ms
```

```
$ nslookup tarballs.nixos.org
Server:		192.168.0.1
Address:	192.168.0.1#53

Non-authoritative answer:
tarballs.nixos.org	canonical name = dualstack.v2.shared.global.fastly.net.
Name:	dualstack.v2.shared.global.fastly.net
Address: 151.101.54.217


$ curl http://tarballs.nixos.org/sha256/bed128fe32c7cdb540ab54b3b7e615ac5adb7322472e52733575aa31a61843ec > ~/Desktop/tmp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     3  100     3    0     0      7      0 --:--:-- --:--:-- --:--:--     7
```

**Comment by zhaofengli** [comment]
This problem only seems to affect `<nix/fetchurl.nix>` which uses the internal `builtin:fetchurl` builder. To reproduce:

```bash
nix-build -E 'import <nix/fetchurl.nix> { url = "http://example.com"; sha256 = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="; }'
```

It looks like [our hack to pull in NSS](https://github.com/NixOS/nix/blob/90b2dd570cbd8313a8cf45b3cf66ddef2bb06e07/src/libstore/build/local-derivation-goal.cc#L357) [1] before sandbox is set up doesn't work anymore. When we do the `getaddrinfo`, glibc opens a socket to nscd and doesn't load the libnss_ libraries. Afterwards, inside the sandbox, glibc tries to load libnss_dns which fails. [A strace](https://gist.github.com/zhaofengli/e3c51186768971bb40495c83c383f2e0) is available here (search for `this.pre-initializes.the.dns.resolvers` and `libnss_dns`).

@baloo reports that it does work if the Nix store is in the same filesystem as `/`, loading libnss_dns works from within the sandbox. It shouldn't work and this looks like a separate bug.

cc @Mindavi @tomberek

[1] For 2.3.15, it's [here](https://github.com/NixOS/nix/blob/9d9dbe6ed05854e03811c361a3380e09183f4f4a/src/libstore/build.cc#L1899).

**Comment by cw789** [comment]
If it helps I also encountered this occurs if you use `import <nix/fetchurl.nix>` and a HTTP 302 redirect is given back.
Possibly after the redirection URL has changed?

**Comment by baloo** [comment]
When nix is configured with:
```
boot.binfmt.emulatedSystems = [ "aarch64-linux" ];
```

the glibc gets injected in the sandbox, and that fixes the `libnss_dns.so` loading

**Comment by tomberek** [comment]
For testing:
```
# reproduce:
nix build github:baloo/nixpkgs/baloo/tests/nix-fetch#nixosTests.nix-fetch -L
# fixed:
nix build github:baloo/nixpkgs/baloo/nix/sandbox-dns-lookup#nixosTests.nix-fetch -L
```

**Comment by Mindavi** [comment]
The patch seems to resolve it for me. I hope this also solves the 'unexpected end-of-file' errors I keep getting in hydra, but we'll see :).

**Comment by vcunat** [comment]
It would be nice to get this deployed to Hydra.nixos.org within several days, as it's currently [blocking](https://hydra.nixos.org/eval/1702813) builds on staging branch (fortunately not on current `staging-next` branch).

**Comment by Ma27** [comment]
@edolstra any chance to get a Nix 2.3 release for that? :) 
cc @NixOS/infra for `hydra.nixos.org`.

**Comment by vcunat** [comment]
At least the immediate staging build-blocker was easy to work around: https://github.com/NixOS/nixpkgs/commit/28b6a91047

**Comment by baloo** [comment]
an alternative is to merge https://github.com/NixOS/nixpkgs/pull/137197 over at nixpkgs, but I can't do that myself.

**Comment by vcunat** [comment]
That wouldn't help the situation on Hydra (in case you meant that).
