### ISSUE TITLE
Remove 1777 permission on /nix/var/nix/{profiles,gcroots}/per-user

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#509]
The 1777 permission is a potential security risk. (For instance, it allows a user to create a directory with the same name as another user.)

Alternatives:
- Create the per-user directories when a user is created, or during login using a PAM module.
- Move the per-user directories to the user's home directory. E.g. /nix/var/nix/profiles/per-user/alice would become /home/alice/.config/nix/profiles or something like that.

**Comment by vcunat** [comment]
$HOME seems a suitable place for per-user data, although it may bring problems due to GC needing some access to user homes to find roots.
