### ISSUE TITLE
bug: nixos could be user friendly but still isn't.

### ISSUE THREAD

**Issue by gilescope** [NixOS/nix#5091]
Reproduction:
1 set: `hardware.pulseaudio.support32bit = true` in configuration.nix
2. Run `nixos-rebuild build`
This is the output:
```
building Nix...
error: The option `hardware.pulseaudio.support32bit' does not exist. Definition values:
       - In `/etc/nixos/configuration.nix': true
(use '--show-trace' to show detailed location information)
building the system configuration...
warning: unknown setting 'experimental-features'
error: The option `hardware.pulseaudio.support32bit' does not exist. Definition values:
- In `/etc/nixos/configuration.nix': true
(use '--show-trace' to show detailed location information)
```

The bug is that it doesn't mention that hardware.pulseaudio has a member called support32Bit which from soundex matching seems pretty similar. We would have double the number of nix users if it just suggested a vaguely likely property that was nearby as one that you might like to try. 

Bonus points for having them aligned on the screen like this so the error stands out:

```
error: The option `hardware.pulseaudio.support32bit' does not exist.
however an option `hardware.pulseaudio.support32Bit' exists. Maybe try that?
```

I don't know nix well so I don't know if there's enough metadata to check all the members in an object but for adoption of a config based OS, being able to give nice errors about misconfigurations is _essential_ to happy users.

For prior art of happy users see `cargo` which tries hard to help the user when they are only human and make mistakes.

How can we make this happen and have happy users?

**Comment by gilescope** [comment]
(In the '90s I would raise this as a feature, but in the '20s it's a bug.)

**Comment by cole-h** [comment]
This is the repo for the `nix` tool itself, which has little to do with the NixOS modules system. Nixpkgs and NixOS are located at https://github.com/NixOS/nixpkgs/, so you should file this issue there instead.

**Comment by gilescope** [comment]
I think this needs fixing at the heart. Here's a nix flake:

```
{
  inputs = { nixpkgs.url = "github:nixos/nixpkgs"; };

  outputs = { self, nixpkgs }:
    let pkgs = nixpkgs.legacyPackages.x86_64-linux;
    in {
      packages.x86_64-linux.hello = pkgs.Hello;

      devShell.x86_64-linux =
        pkgs.mkShell { buildInputs = [ self.packages.x86_64-linux.hello pkgs.cowsay ]; };
   };
}
```
And then the output is:
```
error: attribute 'Hello' missing

       at /nix/store/z80x2y2vv7crixflh9hmi89sz5qdzhvb-source/flake.nix:7:37:

            6|     in {
            7|       packages.x86_64-linux.hello = pkgs.Hello;
             |                                     ^
            8|
(use '--show-trace' to show detailed location information)
```

No mention that `hello` is possibly something that you might have wanted. The lazy evaluation nature of nix makes this tough to solve in the general case. But it doesn't need to be solved for all cases - an 80:20 of places where people often make mistakes would make a big difference.

**Comment by gilescope** [comment]
There's got to be a way that _somehow_ we can rummage around and give the user a little more information once we know that we've hit an unrecoverable error. Do we cache the package names locally?

**Comment by gilescope** [comment]
Here for example we seem to have a missing attribute error in an attribute set:

https://github.com/NixOS/nix/blob/293220bed5a75efc963e33c183787e87e55e28d9/src/libexpr/attr-set.hh#L81

Might it be reasonable to explore checking the attribute set for similar attributes to the missing one and embellishing the error message with a possible suggestion?

**Comment by milahu** [comment]
good idea : )

similar:

```
$ git clonee
git: 'clonee' is not a git command. See 'git --help'.

The most similar command is
        clone
```

this also should be part of the nix IDE (text editor with auto-completion):
when i type `hardware.pulseaudio.supp`, the IDE should suggest the attribute `support32Bit`

> bug: nixos could be user friendly but still isn't.

title is misleading, how about:
feature: autofix typo errors, suggest similar names ("did you mean ...?")

**Comment by gilescope** [comment]
Went down a few rabbit holes. Lots of edit distance algos around.

**Comment by grahamc** [comment]
A recent patch to Nix, which I believe is now released, recommends similar attribute names.

**Comment by gilescope** [comment]
Yeah thanks devs, this has got better - I and I am sure many other nix
users really appreciate it!
