### ISSUE TITLE
segfault in nix build

### ISSUE THREAD

**Issue by pnmadelaine** [NixOS/nix#5120]
**Describe the bug**

When specifying `pname` without `version` in a derivation, `nix build` segfaults instead of displaying the expected error message.

**Steps To Reproduce**

Copy this flake and run `nix build .`:

```
{
  inputs = {
    nixpkgs.url = "nixpkgs/nixos-21.05";
  };

  outputs = inputs@{ self, nixpkgs }:
  let
    system = "x86_64-linux";
    pkgs = nixpkgs.legacyPackages.${system};
  in {
    defaultPackage.${system} = pkgs.stdenv.mkDerivation {
      pname = "";
      #version = "";
    };
  };
}
```

**Expected behavior**

`nix build` should output `error: attribute 'name' missing for call to 'derivationStrict'`.
This is what `nix-build` does when building this expression:

```
{ pkgs ? import <nixpkgs> {} }:

pkgs.stdenv.mkDerivation {
  pname = "";
}
```

**`nix-env --version` output**

`nix-env (Nix) 2.4pre20210707_02dd6bb`

**Comment by zseri** [comment]
I think this issue should be closed because it is clearly a duplicate.

**Comment by pnmadelaine** [comment]
Duplicate of #5113
