### ISSUE TITLE
Some of the targets are installed into `$(prefix)` during the build phase

### ISSUE THREAD

**Issue by pszubiak** [NixOS/nix#5140]
**Describe the bug**

Some targets are installed into `$(prefix)` during the build phase

While building Nix from the master branch, some targets like `libnixutil.so` are installed into `$(prefix)` during the build phase. If the build user doesn't have permission to write into `$(prefix)` the build fails.

It doesn't happen on the 2.3-maintenance branch, or if the build is configured with the `--disable-doc-gen` option on the master branch.

**Steps To Reproduce**

1. Checkout Nix master branch
2. `./bootstrap.sh`
3. `./configure --prefix=/usr`
4. `make`
```
  GEN    Makefile.config
  GEN    src/libexpr/parser-tab.cc
  GEN    src/libexpr/lexer-tab.cc
  CXX    src/build-remote/build-remote.o
  CXX    src/nix-build/nix-build.o
  CXX    src/nix-channel/nix-channel.o
  CXX    src/nix-collect-garbage/nix-collect-garbage.o
  CXX    src/nix-copy-closure/nix-copy-closure.o
  ...
  CXX    src/libutil/util.o
  CXX    src/libutil/xml-writer.o
  LD     /usr/lib64/libnixutil.so
/opt/rh/gcc-toolset-9/root/usr/bin/ld: cannot open output file /usr/lib64/libnixutil.so: Permission denied
collect2: error: ld returned 1 exit status
make: *** [mk/lib.mk:117: /usr/lib64/libnixutil.so] Error 1
```
**Expected behavior**

Targets aren't installed `$(prefix)` during the build

**Comment by fedepell** [comment]
My feeling is that in `doc/manual/local.mk` many targets depend on `$(bindir)/nix`, but `$(bindir)/nix` points to the installed one (ie. `/usr/bin/nix`) which then triggers also all the installation of libraries (as per your case).

They should instead point to the one in the build directory (so `src/nix/nix` or a non hardcoded one) I believe. (and if you change all occourences of `$(bindir)/nix` to `src/nix/nix` in doc/manual/local.mk` it should compile nicely, but maybe "harcoding" `src/nix/nix` is ugly)

**Comment by fedepell** [comment]
[nix-5140-diff.txt](https://github.com/NixOS/nix/files/6993642/nix-5140-diff.txt)
