### ISSUE TITLE
error: build of ‘/nix/store/[...]-nix-1.9pre4088_1711679.drv’ failed

### ISSUE THREAD

**Issue by phfrohring** [NixOS/nix#516]
![screen shot 2015-04-19 at 16 15 40](https://cloud.githubusercontent.com/assets/10885649/7219756/6028d98a-e6af-11e4-8a50-8373231045d5.png)

```
$ cd nixpkgs; git remote -v
origin  https://github.com/NixOS/nixpkgs.git (fetch)

$ git rev-parse HEAD
b7b661f05fb0c3545a5760f0c1509482fe2cc0bb

$ nix-env -u
[... lots of stuff ...]
error: cannot download nix-1.9pre4088_1711679.tar.xz from any mirror
builder for ‘/nix/store/5krkszc8s8f4nd6q2pzlpv3r1fjk6k6f-nix-1.9pre4088_1711679.tar.xz.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/83xf4p243jmcasfaijqccr2f4jas0kvc-nix-1.9pre4088_1711679.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/83xf4p243jmcasfaijqccr2f4jas0kvc-nix-1.9pre4088_1711679.drv’ failed
```

**Comment by spwhitt** [comment]
There seem to be two parts to this bug. The first is that `nix-env -u` is mistakenly upgrading the `nix` package to the `nixUnstable` package, which is bad. I've opened #521 to address this problem. The second is that `nixUnstable` fails to install on `darwin`. I'm not entirely sure what causes this.

**Comment by copumpkin** [comment]
It sounds like for the second issue, the tarball literally isn't downloadable?

**Comment by edolstra** [comment]
Closing on account of age.
