### ISSUE TITLE
Restrict "path" inputs in flakes

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#5168]
Currently you can do wacky stuff like declaring an input `foo.url = path:../`, which will cause Nix to start copying the entire Nix store. We need to specify what absolute/relative paths are allowed in flake inputs. Some possibilities:

* Don't allow paths at all.
* Only allow paths from flakes accessed via a `path:` (or other local) URL. This way e.g. a `github` flake can't read local paths.
* Only allow relative paths to other flakes in the same repository.

**Comment by nrdxp** [comment]
> * Only allow relative paths to other flakes in the same repository.

My vote would be for this.

**Comment by L-as** [comment]
Isn't this problem bigger than flake inputs? Often in my flakes, I will add an extra `..`, for example `../../somefile.nix` instead of `../somefile.nix`, then Nix will complain that `/nix/store/somefile.nix` doesn't exist.

**Comment by nrdxp** [comment]
Yes but that's what it's supposed to do, error out whe attempting to access resources outside of the flake directory. Before this, the path inputs were a way to subvert this protection.

**Comment by roberth** [comment]
Maybe @L-as is thinking about path expressions rather than path flake refs.
If we weren't to trust our dependency flakes, this could be considered a security issue perhaps? Or was something like restricted mode reintroduced? I'm ok with trusting dependency flakes though, so if that's the threat model that's fine with me, certainly for 2.4.

**Comment by edolstra** [comment]
The more general problem is that libfetchers doesn't respect `allowed-uris`. This is not a big problem if the flake is locked, but could be a problem e.g. in CI systems that allow unlocked flakes (since then you can have an input like `inputs.foo.url = path:///home/bla/.ssh` to exfiltrate SSH keys...).
