### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#517]
I'm on 4d652875bdd87c3f1aa08111c63c0719f1ee0c1a (master as of right now).

If I run `make installcheck` in the `dev-shell`, I get:

```
FAIL: tests/binary-cache.sh
FAIL: tests/pass-as-file.sh
2 out of 43 tests failed 
```

with lots of other noise in between. I initially thought that was because of a change I was making and then realized it happened independently of my change. I'm confused because it doesn't seem to be failing in the same way on hydra.

**Comment by edolstra** [comment]
Closing on account of age.
