### ISSUE TITLE
`builtins.getFlake` doesn't work with `--impure` anymore

### ISSUE THREAD

**Issue by L-as** [NixOS/nix#5205]
**Describe the bug**

```
$ nix eval --impure --expr '(builtins.getFlake "nixpkgs").description'
error: 'flake:nixpkgs' is an indirect flake reference, but registry lookups are not allowed
```

**Expected behavior**

It should not err. This used to work.

**`nix (Nix) 2.4pre20210802_47e96bb`**

**Comment by ncfavier** [comment]
I think I've found [the bug](https://github.com/NixOS/nix/commit/3e57e3480b372ed9c5dffc1025eae5773b8691e7#diff-d4441d6156ea52c005e1517d6da41bdf989cff029b61d5f3e9f662a51861f5f2R649). Will open a PR shortly.

**Comment by ncfavier** [comment]
To anyone encountering this issue: a workaround is, funnily enough, to use `--no-use-registries` (although that may break other things).
