### ISSUE TITLE
devShells trying to access the wrong path by default

### ISSUE THREAD

**Issue by happysalada** [NixOS/nix#5206]
**Describe the bug**

when using `nix develop .#name` the [doc](https://nixos.org/manual/nix/unstable/command-ref/new-cli/nix3-develop.html) says that it will try the `devShells.<system>.<name>` 

however when testing this, the error message given is
```
 nix develop .#test
warning: Git tree '/Users/raphael/Projects/gillithekid/union' is dirty
error: flake 'git+file:///Users/raphael/Projects/gillithekid/union' does not provide attribute 'devShells.x86_64-darwintest', 'packages.x86_64-darwin.test', 'legacyPackages.x86_64-darwin.test' or 'test'
```
There is a `.` missing in `devShells.x86_64-darwintest` (before test).
my flake provides a `devShells.x86_64-darwin.test` so I suspect the default path being tried is missing the `.` as well.

**Steps To Reproduce**

1. Make a flake with a `devShells.${system}.test` output
2. try `nix develop .#test`
3. See error message

**Expected behavior**

Try the correct path by default

**Additional context**

In the context of summer of nix, somebody is asking about the `devShells` feature, and I'm trying to provide an example.

**Comment by regnat** [comment]
This should have been fixed by https://github.com/NixOS/nix/pull/5156 . Can you confirm?

**Comment by happysalada** [comment]
Thank you, let me test this and come back to you.

**Comment by happysalada** [comment]
it's fixed, do you want to close this right now, or wait until nixpkgs can be updated with the version that fixes is ?
(right now update on nixpkgs is stuck because of a failing darwin build, there was a PR here, but it didn't go well. So basically, nixpkgs is waiting to have a deployable version of nix)
