### ISSUE TITLE
Store attribute name when installing with nix-env

### ISSUE THREAD

**Issue by spwhitt** [NixOS/nix#521]
`nix-env -u` often upgrades packages to incorrect or unintuitive versions. With the current state of `nixpkgs`, `nix` is upgraded to `nixUnstable`, and `nixops` is upgraded to `nixopsUnstable`. There are certainly other examples. We could fix these problems individually, but it seems evident that package names and version numbers are an unreliable criteria and that alternate methods should be considered.

Given that we're deprecating `nix-env -i` (in favor of `nix-env -iA`) anyway, I wonder if `nix-env` could simply remember the attribute name which was used to install a package, then upgrade the package by re-evaluating that attribute and upgrading if the version number is higher.

Alternately, we could introduce a convention of tagging packages with a UUID, and `nix-env` would upgrade only to packages with the same UUID. However, I don't like this approach as much as the previous one because it requires more manual work and has more potential for bugs.

**Comment by wmertens** [comment]
Can you change the title of this issue to "store attribute name when installing with nix-env"?

I am a fan of storing the attribute name used for installing a package, but keep in mind that this is not a 100% solution. nix-env doesn't have to use the same branch of nixpkgs (or even nixpkgs itself) so even using the original attribute name will not always do what you want. It's still way better than the current approach though.

**Comment by copumpkin** [comment]
Have people generate a UUID for every human notion of package that goes into nixpkgs? :smile:

**Comment by edolstra** [comment]
Closing since `nix profile` (the flake-based replacement for `nix-env`) does store attribute names.
