### ISSUE TITLE
`builtins.eval`: like `import` but from strings

### ISSUE THREAD

**Issue by kvtb** [NixOS/nix#5211]
It would be nice to expose `state.parseExprFromString` as `builtins.eval`, similar to `builtins.import` but accepting string instead of file name.
One use case is pre-process importing files in Nix,  replacing `builtins.import path` with  `builtins.eval (f (builtins.readFile path))`
Another is working with files which might be modified during evaluation, avoiding caching of `builtins.import` 
Third is to keep configuration in Nix format , avoiding Json, Toml,  etc which are contaminating Nix ecosystem too (no wonder, Nix can do `builtins.fromJSON` and `builtins.fromTOML`)

**Comment by L-as** [comment]
`builtins.eval = x: import (builtins.toFile "source" x)`?
