### ISSUE TITLE
`builtins.hashFile` and `builtins.hashString` do not discard string context

### ISSUE THREAD

**Issue by kvtb** [NixOS/nix#5213]
```
nix-repl> builtins.hasContext (builtins.hashFile "sha256" (builtins.fetchurl "https://github.com/NixOS/nixpkgs/archive/release-21.05.tar.gz")) 
true

nix-repl> builtins.hasContext (builtins.hashString "sha256" (builtins.fetchurl "https://github.com/NixOS/nixpkgs/archive/release-21.05.tar.gz"))
true
```

Looking at the comments, they should discard string context, but it restored just on the next lines, in `coerceToPath` and `forceString` (should it be `forceStringNoCtx`?)

https://github.com/NixOS/nix/blob/2a8017092025a7c108ca1a829a8b4f0bcf7ee2c0/src/libexpr/primops.cc#L1363-L1364

https://github.com/NixOS/nix/blob/2a8017092025a7c108ca1a829a8b4f0bcf7ee2c0/src/libexpr/primops.cc#L3038-L3039

cc @shlevy @Ericson2314 @JohnAZoidberg

**Comment by edolstra** [comment]
Fixed in c6fa7775de413a799b9a137dceced5dcf0f5e6ed.
