### ISSUE TITLE
Are old entries of `/nix/var/nix/db/db.sqlite` garbage collected?

### ISSUE THREAD

**Issue by kvtb** [NixOS/nix#5221]
**Is your feature request related to a problem? Please describe.**

I am interesting, are old entries of `/nix/var/nix/db/db.sqlite` garbage collected?

On my machine `/nix/var/nix/db/db.sqlite` is already 4GB big and it looks like it has all the history from the beginning

**Comment by kvtb** [comment]
I am not sure what do you called "versioned", but 'sqlite3 /nix/var/nix/db/db.sqlite .dump" showed information about entries in nix store which have been garbage collected months ago.

**Comment by SuperSandro2000** [comment]
My db.sqlite went form 1.6 GB to 31MB after being vacummed which only took 4 seconds. This should be enabled automatically.

**Comment by bhipple** [comment]
It used to, but it was disabled 7 years ago:
https://github.com/NixOS/nix/commit/8299aaf07988a3ca7ecda3526b7e25a885550db5

Perhaps we should have a `nix-collect-garbage --vacuum` flag to opt-in, if it isn't safe to run all the time?
