### ISSUE TITLE
Support dynamic generation of the remote build machine list

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#523]
My use case is to enable dynamic scaling of the build machines. I'm thinking for example of an EC2 autoscaling group full of NixOS build boxes.

At first glance, it looks like it would be quite simple: build-remote.pl looks for its configuration file in `NIX_REMOTE_SYSTEMS` or `@sysconfdir@/nix/machines`. It just reads a list of machines from the file at that path, so we'd could amend that to optionally call a provided script and treat its stdout as the list. All the other logic would stay the same, I think. I'd probably add an option to the NixOS module to support configuring that script.

If that makes sense, I think I could easily make a PR for it.

**Comment by copumpkin** [comment]
Mostly just looking for someone credible to say "yes, that makes sense and I see no major issues with what you're saying" so I can go do it. Or for someone to say "nope, you're missing big problem XYZ and the problem is more complicated than you think" :smile:

Can anyone do that?

**Comment by edolstra** [comment]
I don't really see why `build-remote` should have to invoke a script. Your machine provisioner can just update `/etc/nix/machines` (it should be a mutable file in this scenario, not a symlink to a file in the Nix store), and then future invocations of `build-remote` will use the new machines.

**Comment by copumpkin** [comment]
It just seemed indirect to have something sitting in the background updating a file that nix reads, instead of having the script which can compute the machines on demand in any way the user sees fit. If anything, I'd make the script the primary mechanism (since it doesn't require a separate process updating the file) and then have the default be a script that reads `/etc/nix/machines`. Perhaps the effort outweighs the benefit though? I agree that it would be pretty simple for me to set up a NixOS service that updates the file on some schedule. I'm assuming that none of this messes with the NixOS read-only filesystems we get by default?

**Comment by vcunat** [comment]
No, IIRC only /nix/store is mounted read only. I quite often update the file by hand; reaction is quick, as the file is read again on realizing each derivation.

**Comment by edolstra** [comment]
Closing since Nix (and Hydra) do support dynamic machine lists. Calling a script to generate the machine list every time would be pretty inefficient so it's better to let the provisioners update the list.
