### ISSUE TITLE
The command line parser is sensitive to the order of the keys

### ISSUE THREAD

**Issue by puchneiner** [NixOS/nix#5230]
**Describe the bug**
**Steps To Reproduce**

a small self-explanatory test case
```
$ nix -vvvvvv --version
nix (Nix) 2.3.15
Features: gc, signed-caches
Configuration file: /etc/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix

$ nix --version -vvvvvv
nix (Nix) 2.3.15
```
A more complicated example of when such behavior leads to an unpleasant embarrassment will be left out of the equation. I think a simple example is enough to show that there is a problem

**Expected behavior**

The same output

**`nix-env --version` output**

nix-env (Nix) 2.3.15

**Comment by edolstra** [comment]
This is fixed on master (f33878b6562c746d5865a86e64f02c75feaf5b3e).
