### ISSUE TITLE
programs which launch `man $programname`, show man for the globally installed version

### ISSUE THREAD

**Issue by kvtb** [NixOS/nix#5231]
**Describe the bug**

There are programs, like `git`, and well `nix` itself, which being run as `git ls-remote --help` launch "man git-ls-remote".
And that `man`  always shows the manual for the globally installed version, not the manual from `$package/share/`

**Steps To Reproduce**

```
nix-build -E '(import <nixpkgs> {}).nixUnstable'

result/bin/nix --help
```

**Expected behavior**

Expected to see `man` for particular package, not for the global one
If I have 2+ versions of a program I expect to be able to see both `man`s

**Comment by abathur** [comment]
I think https://github.com/NixOS/nix/pull/1873 is a good place to start pulling on this thread. It sounds like they tried to do what is described here in the process of that PR and ran into some trouble with it.

**Comment by L-as** [comment]
I don't think this issue is relevant for Nix itself.

**Comment by kvtb** [comment]
> I don't think this issue is relevant for Nix itself.

It is relevant as launching `man $prog` on `$prog --help` is an anti-pattern in settings like NixOS, which allow to have multiple instances of the same packages.
It is a pity that Nix itself uses it.

**Comment by L-as** [comment]
You can set the path for the pages in Nixpkgs. There isn't much you can do about it in Nix itself

**Comment by abathur** [comment]
@L-as While I agree that there isn't a nix-level solution to examples the OP gave like git, `nix --help` literally does the thing the reporter is describing.
