### ISSUE TITLE
java/swt missing attribute 'arch'

### ISSUE THREAD

**Issue by bukzor** [NixOS/nix#526]
It's hard for me to tell whose bug this is, but I'm starting here.

```
$ nix-env -qas
error: attribute ‘arch’ missing, at "/nix/store/64h75lld2arbmnq0pz7bqr15q05f3bv8-nixpkgs-15.05pre59184.e07ea5c/nixpkgs/pkgs/development/libraries/java/swt/default.nix":25:100
(use ‘--show-trace’ to show detailed location information)

$ nix-env --version
nix-env (Nix) 1.8

$ uname -a
Darwin myMBP.lan 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64 i386 MacBookPro10,1 Darwin
```

**Comment by copumpkin** [comment]
This seems like a nixpkgs issue. Only pointing that out because the viewership on this repo's issue tracker is way lower, so the chances of someone noticing your issue and fixing it are pretty low over here.

**Comment by armijnhemel** [comment]
First of all: yes, this seems to be a nixpkgs issue. Second, there seem to have been fixes for building this package on Darwin.
