### ISSUE TITLE
can `nix-hash` by default print all possible hashes in all possible forms?

### ISSUE THREAD

**Issue by kvtb** [NixOS/nix#5274]
**Is your feature request related to a problem? Please describe.**

It is often happen that `nix-hash` used interactively prints the hash in unexpected form, `sha256` when `sha512` is expected, `base32` when `base16` is expected, `--recursive` when `--flat` is expected.

That forces to alter the command line and run it again, sometimes more than once.

It takes time, both of the user and the computer.

Remembering available command like flags and their defaults is difficult, especially because `nix-hash` and `nix hash-path` have different defaults

**Describe the solution you'd like**
Could `nix-hash` when run without command like flags (which fully specify what the user want to get) print the matrix of all possible hashes of the file/path in all their printable forms ?

Also, printing out the nar size would be a nice addition.

Examples:
```
# nix-hash $path
md5-flat: <base16> <base32> <sri>
sha1-flat: <base16> <base32> <sri>
sha256-flat: <base16> <base32> <sri>
sha512-flat: <base16> <base32> <sri>

narsize: <narsize>
md5: <base16> <base32> <sri>
sha1: <base16> <base32> <sri>
sha256: <base16> <base32> <sri>
sha512: <base16> <base32> <sri>
```

```
# nix-hash --recursive $path
narsize: <narsize>
md5: <base16> <base32> <sri>
sha1: <base16> <base32> <sri>
sha256: <base16> <base32> <sri>
sha512: <base16> <base32> <sri>
```

```
# nix-hash --recursive --type sha256 $path
narsize: <narsize>
sha256: <base16> <base32> <sri>
```

```
# nix-hash --recursive --base32 $path
narsize: <narsize>
md5: <base32>
sha1: <base32>
sha256: <base32>
sha512: <base32>
```

And the legacy form when the expected result is fully described for not to break bash scripts:
```
# nix-hash --recursive --base32 --type sha256 $path
<base32>
```

**Comment by edolstra** [comment]
I don't think this is a good idea. In Nixpkgs you should almost always use `sha256` in SRI format, so that's what `nix hash {file,path}` print by default. Printing non-standard hashes/formats is just confusing in general.
