### ISSUE TITLE
paths with 2+ derivers

### ISSUE THREAD

**Issue by kvtb** [NixOS/nix#5275]
**Describe the bug**

Not exactly the bug, just a source of inconsistency.

Nix codebase assumes that a path has at most 1 deriver.
https://github.com/NixOS/nix/blob/c000cec27fcb16548606830410be265eb082f777/src/libstore/path-info.hh#L28-L31

It is not true for fixed-output derivations (and probably for CA too, I did not play with CA yet)

For example `fetchurl $url` and `pkgsCross.whatever.fetchurl $url` would produce the same output path, but they have different derivers.

This false assumption is propagated to many Nix commands, for example what build log will `nix log` display ?
The path might have more than 1 build log.

It also affects `nix-copy-closure` and garbage collection. In a minor, not critical way. The main problem of peeking a random deriver when a path has 2+ of them is making difficult to reason about what a particular command will do exactly:

How many .drv files will remain after GC run with `--option keep-derivations true` if there are 2+ of them ?

Which one of the derivers will be rebuilt on `nix-store --repair-path`, and why only one, not all of them ?

**Comment by regnat** [comment]
Yes, that’s indeed a known issue (but thanks for writing it down explicitly as I don’t think it’s mentioned anywhere public). It’s indeed an issue for FO derivations (though it’s relatively minor), and will become much more annoying with the advent of CA.

I’d say that the right solution is to progressively get away from commands that assume a single deriver, and as much as possible make a difference between manipulating a store path and a derivation (kind-of like what I describe in https://www.tweag.io/blog/2021-02-17-derivation-outputs-and-output-paths/)

**Comment by kvtb** [comment]
Apparently, it is not only FO and CA
New FO's deriver propagates from `src` (for example on `curl`'s upgrade) to the derivation which use `src`, resulting in that derivation to have 2+ derivers too.

**Comment by kvtb** [comment]
I just tried to patch GC a little to retain built inputs on the workstation (because GC removes them as garbage, but I usually need them soon after GC and have to rebuild), and it appeared not so easy because of this issue :(

**Comment by kvtb** [comment]
Even worse, `deriver` in `ValidPaths` should not be trusted at all:

It is actual working laptop, without CA or experimental features, just NixOS-stable with Nix-stable:
```
$ sqlite3 -readonly ./db.sqlite "select deriver from ValidPaths where path = '/nix/store/iy1yfyym9m74c9h7ai6f0yx8qzq9yy1l-libcap-ng-0.7.9'"
/nix/store/s1jyj4n4s1xngqcs4qvgyaig8m1i74f7-libcap-ng-0.7.9.drv
```
^^^- this path GC'ed long ago

```
$ sqlite3 -readonly ./db.sqlite "select path from ValidPaths where id in (select drv from DerivationOutputs where path = '/nix/store/iy1yfyym9m74c9h7ai6f0yx8qzq9yy1l-libcap-ng-0.7.9')"
/nix/store/p3ir3p71b7n56awmrpcrb6y8g8xwvlg9-libcap-ng-0.7.9.drv
/nix/store/1068g57q9vjflx96x7nia4c2sazvlppr-libcap-ng-0.7.9.drv
/nix/store/f0wn0ppxckc51iv7y4kb9z60z9s10g8b-libcap-ng-0.7.9.drv
/nix/store/33mxsxp18g762d74wlcbsrzic92zjacy-libcap-ng-0.7.9.drv
```
^^^- these paths exist

**Comment by edolstra** [comment]
The deriver field simply records the specific derivation used to build the outputs. This is used in conjunction with `gc-keep-derivations` to keep track of the provenance of store paths. It cannot record all possible derivers, because there are an infinite number of them.

**Comment by kvtb** [comment]
> The deriver field simply records the specific derivation used to build the outputs. This is used in conjunction with `gc-keep-derivations` to keep track of the provenance of store paths. It cannot record all possible derivers, because there are an infinite number of them.

Not only in GC (although it is strange that `ValidPaths.deriver` was GC'd, because `gc-keep-derivations` is `true` by default)
Also `nix log`, also `nix-store --repair-path`, etc

**Comment by kvtb** [comment]
> > The deriver field simply records the specific derivation used to build the outputs. This is used in conjunction with `gc-keep-derivations` to keep track of the provenance of store paths. It cannot record all possible derivers, because there are an infinite number of them.
> 
> Not only in GC (although it is strange that `ValidPaths.deriver` was GC'd, because `gc-keep-derivations` is `true` by default)
> Also `nix log`, also `nix-store --repair-path`, etc

Ah, GC does not preserve `ValidPaths.deriver` with `gc-keep-derivations`
It preserves all the infinite number of derives from `DerivationOutputs` table

But `nix log`, `nix-store --repair-path`, ... rely on that `ValidPaths.deriver`, which is not preserved.

And it is not a bug? ok
