### ISSUE TITLE
Failed update system if using custom buildMachines

### ISSUE THREAD

**Issue by Izorkin** [NixOS/nix#5288]
**Describe the bug**
Failed update system if using custom buildMachines

**Steps To Reproduce**
Me using this configuration:
```
  nix = {
    distributedBuilds = true;
    buildMachines = [
      {
        hostName = "aarch64.nixos.community";
        maxJobs = 64;
        sshKey = "/root/.ssh/id_ed2551_aarch64";
        sshUser = "izorkin";
        system = "aarch64-linux";
        supportedFeatures = [ "big-parallel" ];
      }
    ];
  };
```

Error update system:
```
...
Failed to find a machine for remote build!
derivation: xmycamdgf2rx7gdhffg022z7pqfv8zkz-curl-7.79.0.drv
required (system, features): (x86_64-linux, )
1 available machines:
(systems, maxjobs, supportedFeatures, mandatoryFeatures)
(aarch64-linux, 64, big-parallel, )
...
Failed to find a machine for remote build!
derivation: dlfvvg65bg8zchn4l2015jylh2fvlbgp-git-2.33.0.drv
required (system, features): (x86_64-linux, )
1 available machines:
(systems, maxjobs, supportedFeatures, mandatoryFeatures)
(aarch64-linux, 64, big-parallel, )
...
```

Checking with this nix versions: `2.4pre20210917_37cc50f` and `2.4pre20210908_3c56f62`

Temporary solution - remove file `/etc/nix/machines`.

**Comment by matthewbauer** [comment]
Does it actually fail, or is it just being overly verbose? I have seen this message before, but I think the local machine will start running it after it's checked all the remote machines.

**Comment by Izorkin** [comment]
The build hangs at this point.

**Comment by lrworth** [comment]
This happens on macOS as well, and for my project ends up failing with something like

```
error: opening directory '/nix/store/m20qs1s93lb9qys6lvlx2vabs0i0m5ad-xml-types-lib-xml-types-0.3.8-haddock-config': Too many open files
```

**Comment by talyz** [comment]
I haven't had this hang a build yet, but it's annoying enough that this warning is printed for every derivation it tries to build, making up a significant portion of the total output for any larger build.

**Comment by roberth** [comment]
Looks like it's been a while, and I'm sorry that this didn't get a response. We've implemented cross-version checks for remote building and we've formed the Nix team to help with issues sooner.

Please open a new issue if you encounter something like this again.
