### ISSUE TITLE
`nix profile install <flake>` fails on macOS with multi-user installation

### ISSUE THREAD

**Issue by jayesh-bhoot** [NixOS/nix#5296]
**Describe the bug**

`nix profile install --experimental-features "nix-command flakes" nixpkgs#hello` fails with the following error:

```
warning: path '/nix/store/pj976m7ww6dhyhg4pjzyk42ia2c5m8bh-profile' claims to be content-addressed but isn't
error: cannot add path '/nix/store/pj976m7ww6dhyhg4pjzyk42ia2c5m8bh-profile' because it lacks a valid signature
```

I experimented a bit. I found that the above command:

- works on single-user installation of Nix on Intel Mac Mini running macOS 10.16
- does not work on multi-user installation of Nix on Intel Mini running macOS 10.16
- does not work on multi-user installation of Nix on Silicon Macbook Pro M1 running macOS 10.16

**It seems that regardless of whether or not the Mac is silicon-based, `nix profile install <flake>` does not work for a multi-user Nix installation**.

I don't know what makes the profile path claim itself to be content-addressable.  I have read this https://www.tweag.io/blog/2020-09-10-nix-cas/, and I understand the difference between content-addressable, and input-addressable. But I have no clue how to fix the problem.

I have a feeling that if I fix the source of the warning, the error will also go away.

**Steps To Reproduce**

1. Ensure you are running multiuser installation of nix
2. Upgrade to nix2.4: `nix-env -iA nixpkgs.nixUnstable`
3. Run `nix profile install --experimental-features "nix-command flakes" nixpkgs#hello` to see the above error.

**Expected behavior**

The `hello` derivation should be installed in the profile.

**`nix-env --version` output**

```
=> nix --version
nix (Nix) 2.4pre20210908_3c56f62

=> nix-env --version
nix-env (Nix) 2.4pre20210908_3c56f62

=> nix-daemon --version
nix-daemon (Nix) 2.4pre20210908_3c56f62

=> nix-shell -p nix-info --run "nix-info -m" # for Intel Mac Mini running Big Sur 
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4pre20210908_3c56f62`
 - channels(root): `"nixpkgs-21.11pre318361.a3a23d9599b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by jayesh-bhoot** [comment]
https://github.com/NixOS/nix/issues/4425 describes an identical problem, but has been closed long ago.

**Comment by jayesh-bhoot** [comment]
After a few experiments, I have rewrote the description of the issue. The key point seems to be that **regardless of whether or not the Mac is silicon-based, `nix profile install <flake>` does not work for a multi-user Nix installation.**

**Comment by Kha** [comment]
> #4425 described an identical problem, but was closed with no clear solution.

What do you mean by that? It was closed by a commit fixing the issue, and your Nix version is older than that commit. Try updating it and seeing if the issue persists.

**Comment by jayesh-bhoot** [comment]
> > #4425 described an identical problem, but was closed with no clear solution.
> 
> What do you mean by that? It was closed by a commit fixing the issue, and your Nix version is older than that commit. Try updating it and seeing if the issue persists.

I overlooked that.

How do I install a `nix` version later than the one available through `nix-env -iA nixpkgs.unstable`?

**Comment by jayesh-bhoot** [comment]
Hmm.

https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=nixUnstable shows the version of `nixUnstable` as `2.4pre20210922_bcd73eb`.

But my version stays at `2.4pre20210908_3c56f62` even after I ran `sudo -i sh -c 'nix-channel --update && nix-env -iA nixpkgs.nixUnstable && launchctl remove org.nixos.nix-daemon && launchctl load /Library/LaunchDaemons/org.nixos.nix-daemon.plist'`, in order to update the nix channel.
