### ISSUE TITLE
Wrong line number shown in syntax error message

### ISSUE THREAD

**Issue by oxalica** [NixOS/nix#5300]
**Describe the bug**

Error message shows on wrong line.

**Steps To Reproduce**

1. Create `test.nix` with content:
```nix
{
  imports = [
    ./foo.nix
    ./bar.nix
    ./baz.nix
  ];
  foo = then; # Keyword `then` triggers a syntax error.
  # Some
  # More
  # Comments
  # After
}
```

2. Run `nix-instantiate --parse ./test.nix`

3. See the error message shows an error on line 10 `# Comments` instead of line 7 `foo = then;`.
```
error: syntax error, unexpected THEN

       at /home/oxa/repo/fork/nix/test.nix:10:9:

            9|   # More
           10|   # Comments
             |         ^
           11|   # After
```

4. Comment out three paths in array of `imports` gives correct error location of `then`. The issue seems related to paths.

**Expected behavior**

```
error: syntax error, unexpected THEN

       at /home/oxa/repo/fork/nix/test.nix:7:9:

            6|   ];
            7|   foo = then; # Keyword `then` triggers a syntax error.
             |         ^
            8|   # Some
```

**`nix-env --version` output**

I'm on current master.
nix (Nix) 2.4pre20210927_9c766a4

**Comment by domenkozar** [comment]
Cc @Radvendii

**Comment by Radvendii** [comment]
Yep, my change makes it read the character after the path twice. Working on a fix.
