### ISSUE TITLE
Nix flakes always thinks worktree is dirty in github actions pull request builds

### ISSUE THREAD

**Issue by arianvp** [NixOS/nix#5302]
**Describe the bug**

Nix flakes keeps saying my tree is dirty; eventhough I'm in a clean detached HEAD

**Steps To Reproduce**

https://github.com/arianvp/webauthn-oidc/blob/master/.github/workflows/build.yml#L33-L36

```
Run git status
  git status
  git diff-index HEAD
  nix build --print-build-logs --log-format raw .#
  nix build --print-build-logs --log-format raw --rebuild # Build again to check reproducibility
  shell: /bin/bash -e {0}
HEAD detached at pull/3/merge
nothing to commit, working tree clean
warning: Git tree '/home/runner/work/webauthn-oidc/webauthn-oidc' is dirty
warning: Git tree '/home/runner/work/webauthn-oidc/webauthn-oidc' is dirty
```

**Expected behavior**

The work tree is considered not dirty

**`nix-env --version` output**

**Additional context**

**Comment by regnat** [comment]
I’m not sure why this happens, but as a workaround you can use `nix build .\?rev=$(git rev-parse HEAD)` to force it to use the version from the index

**Comment by TransLunarInjection** [comment]
Probably related to #4140
