### ISSUE TITLE
nix tools use ascii instead of unicode apostrophe

### ISSUE THREAD

**Issue by charles-cooper** [NixOS/nix#532]
Hi all,
Is it at all possible to refactor nix tools in general so that instead of outputting unicode stuff like
instantiated ‘entropy-0.3.6.tar.gz’ -> ‘/nix/store/r7nsxd6k5ig8z6748rl49yzsc74pi89a-entropy-0.3.6.tar.gz.drv’
(unicode `‘’`, i.e. `0x2018, 0x2019`)
to use ascii `'`, i.e. `0x27`
This would make it easier to write tools which parse nix output, and also make it slightly easier to copy / paste terminal output :)
I can find the relevant code and patch it but I was wondering specifically if this will cause breaking changes in the toolchain

**Comment by vcunat** [comment]
Yes, from what I've seen so far, similar unicode usage is more trouble than worth.

**Comment by patricksjackson** [comment]
This can be closed. It was completed in #1495.
