### ISSUE TITLE
`nix store gc` fails to delete self-referred path: executing SQLite statement 'delete from ValidPaths where path = '...';': constraint failed

### ISSUE THREAD

**Issue by trofi** [NixOS/nix#5320]
**Describe the bug**

My nix store is in state that does not allow removing seemingly unused stored path:

```
$ nix store gc
0 store paths deleted, 0.00 MiB freed
error: executing SQLite statement 'delete from ValidPaths where path = '/nix/store/2pklamh9d8x964wbawway71rks402bxr-gcc-11.1.0-lib';': constraint failed (in '/nix/var/nix/db/db.sqlite')
```

**`nix-env --version` output**

nix-env (Nix) 2.4pre20210922_bcd73eb

Attaching full vacuumed `db.sqlite`: 
[db.sqlite.gz](https://github.com/NixOS/nix/files/7271172/db.sqlite.gz)

**Comment by trofi** [comment]
This system saw a few derivations built with `config.contentAddressedByDefault = true;`. I wonder if we lack a few deletes against `Realisations` table (or similar):

```
$ sqlite3 db.sqlite

sqlite> pragma foreign_keys=1;
sqlite> delete from ValidPaths where path = '/nix/store/2pklamh9d8x964wbawway71rks402bxr-gcc-11.1.0-lib';
Error: FOREIGN KEY constraint failed

sqlite> EXPLAIN delete from ValidPaths where path = '/nix/store/2pklamh9d8x964wbawway71rks402bxr-gcc-11.1.0-lib';

...
0     Init           0     1     0                    0   Start at 1; Start: .abort (AFTER DELETE ON ValidPaths)
...
0     Init           0     1     0                    0   Start at 1; Start: .abort (AFTER DELETE ON Realisations)
```

I noticed that `ValidPaths` has -predelete trigger to handle self-references:

```
CREATE TRIGGER DeleteSelfRefs before delete on ValidPaths
  begin
    delete from Refs where referrer = old.id and reference = old.id;
  end;
```

Should `RealisationsRefs` have something similar? Or my db is really corrupted? CC @regnat

**Comment by trofi** [comment]
I tracked it down to a single `RealisationsRefs` self-reference:

```
INSERT INTO ValidPaths VALUES(880618,'/nix/store/2pklamh9d8x964wbawway71rks402bxr-gcc-11.1.0-lib',...);

INSERT INTO Refs VALUES(880618,879284);
INSERT INTO Refs VALUES(880618,880618); -- direct self-ref

INSERT INTO Realisations VALUES(17737,'...','lib',880618,'');
INSERT INTO Realisations VALUES(7683,'...','lib',880618,'');

INSERT INTO RealisationsRefs VALUES(17737,7683); -- indirect self-ref (both are 880618)
```

**Comment by regnat** [comment]
> Should RealisationsRefs have something similar?

Hum, it might be. Though it’s really strange that this didn’t hit earlier :thinking:

**Comment by trofi** [comment]
I still was not able to craft artificial example, but I suspect it has something to do with bootstrapping packages from the previous (identical versions) of themselves.

Here is my untested hypothesis:

For derivations with identical definition but slightly different build inputs (that don't affect the result):

```
drv1: { buildInputs=[]; content = ''echo ${placeholder "out"} > $out''; }
drv2: { buildInputs=[drv1]; content = ''echo ${placeholder "out"} > $out''; }
```
These both should generate identical CA path. But could it be that derived references are: 
````
realization(drv1)->realization(drv1) -- self-ref

realization(drv2)->realization(drv2) -- self-ref
realization(drv2)->realization(drv1) -- just because both have the same path
```

Could it be?

If that is the case maybe we could just avoid adding `realization(drv2)->realization(drv1)` reference and rely on `realization(drv2)->realization(drv2)`.

**Comment by regnat** [comment]
Your example as-it-is wouldn’t work because `drv1` and `drv2` would actually get two different output paths (because the path also include the set of runtime dependencies, and they have a different one). But maybe there’s something to dig here indeed. I’ll try to have a look when I find some time as it’s really puzzling (and maybe we could also add an SQL constraint to ensure that we don’t write this kind of self-ref)

**Comment by trofi** [comment]
> Your example as-it-is wouldn’t work because `drv1` and `drv2` would actually get two different output paths (because the path also include the set of runtime dependencies, and they have a different one). But maybe there’s something to dig here indeed. I’ll try to have a look when I find some time as it’s really puzzling (and maybe we could also add an SQL constraint to ensure that we don’t write this kind of self-ref)

For both `drv1` and `drv2` there should be no runtime deps aside from their internal references as they literally contain only "$out" in the output.

I think I managed to write the test case: https://github.com/NixOS/nix/pull/5329

```
$ make installcheck
...
ran test tests/selfref-gc.sh... [PASS]
ran test tests/ca/selfref-gc.sh... [FAIL]
...
    deleting '/tmp/nix-shell.ab2Glx/nix-test/tests/ca/selfref-gc/store/iqciq1mpg5hc7p6a52fp2bjxbyc9av0v-selfref-gc'
    deleting '/tmp/nix-shell.ab2Glx/nix-test/tests/ca/selfref-gc/store/zh0kwpnirw3qbv6dl1ckr1y0kd5aw6ax-selfref-gc.drv'
    error: executing SQLite statement 'delete from ValidPaths where path = '/tmp/nix-shell.ab2Glx/nix-test/tests/ca/selfref-gc/store/fsjq0k146r85lsh01l0icl30rnhv7z72-selfref-gc';': constraint failed (in '/tmp/nix-shell.ab2Glx/nix-test/tests/ca/selfref-gc/var/nix/db/db.sqlite')
```

Looks similar?

**Comment by regnat** [comment]
Oh yes indeed. I tried to replicate it but made a mistake when writing the expression, which prevented the bug from happening. But your test-case does highlight it very well.

**Comment by regnat** [comment]
Just opened #5479 (based on your test, thanks for that :) ) that should fix it
