### ISSUE TITLE
nix store verify --sigs-needed doesn't seem to actually work for cases >1

### ISSUE THREAD

**Issue by arianvp** [NixOS/nix#5326]
**Describe the bug**

No matter what number I pass to `--sigs-needed`, if there is just 1 signature the command always succeeds.

**Steps To Reproduce**

```
nix store verify --sigs-needed 20 --store https://cache.nixos.org /nix/store/qd3g8rk5hx5zkb70idjh6fa12sh6bipg-mailcap-2.1.53
```
**Expected behavior**
This should fail as there aren't 20 signatures on this object but just one:
```
nix path-info --store https://cache.nixos.org /nix/store/qd3g8rk5hx5zkb70idjh6fa12sh6bipg-mailcap-2.1.53 --json | jq .
[
  {
    "path": "/nix/store/qd3g8rk5hx5zkb70idjh6fa12sh6bipg-mailcap-2.1.53",
    "narHash": "sha256-6JPj2tZgoTEZ8hNEi9ZZhElBNm9SRTSXifMmCicwiLo=",
    "narSize": 112048,
    "references": [],
    "ca": "fixed:r:sha256:1fl860khl9pki6bk8iajdwv42jc4b7b8ni0ky8ck38b0svdf74z8",
    "deriver": "/nix/store/pyhgq6mxymaij5kd8sgywfq1gk3gx8ss-mailcap-2.1.53.drv",
    "signatures": [
      "cache.nixos.org-1:eCGQFDWEOJpDZu744HOjy6GZY8AFIJo7IfwRqggor2ogud5czzZluImzhtEq3lwuXHN18mguoRnwingIjvODCg=="
    ],
    "url": "nar/02d1vws9b6hlds9r75y9vhn4wqz24219j8xvg0a4qdqjiz0rrwbs.nar.xz",
    "downloadHash": "sha256-evGcwY8SN0wUeLsjmYIg4mNOLNzJl5OTbhSalTTfoQk=",
    "downloadSize": 24804
  }
]
```

**`nix-env --version` output**

**Additional context**

**Comment by regnat** [comment]
The path you’ve chosen in your example is content-addressed (see the `ca` field in the `nix path-info` output). These paths are always trusted regardless of their signatures because they are self-verified. So that’s why the command succeeds despite the path not having enough signatures. Using with another non-ca path works fine:

```console
$ nix store verify --sigs-needed 20 --store https://cache.nixos.org /nix/store/bhv855cc7a44yz6r5pm4vga9qx66zw91-hello-2.10
path '/nix/store/bhv855cc7a44yz6r5pm4vga9qx66zw91-hello-2.10' is untrusted
```

**Comment by arianvp** [comment]
I thought content-addressing was an experimental feature that I had to explicitly opt into with `--experimental-features 'ca-references ca-derivations` . I don't have these flags enabled.  Is this expected behaviour?

**Comment by andir** [comment]
> I thought content-addressing was an experimental feature that I had to explicitly opt into with `--experimental-features 'ca-references ca-derivations` . I don't have these flags enabled.  Is this expected behaviour?

Fixed output derivations are already (since forever?) content addressed.

**Comment by regnat** [comment]
content-addresed derivations are an experimental feature, but content-addressed paths have been there forever (the output of FO-derivations are content-addressed, as well as drv files or anything that’s added to the store at eval-time)

**Comment by arianvp** [comment]
I see! Thanks! I'll close this then as it's clearly expected behaviour
