### ISSUE TITLE
Filter out markdown links in help output

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#5337]
**Describe the bug**

`nix help` currently prints output like this:

```
    Main commands:

    · nix build ./nix3-build.md - build a derivation or fetch a store path 
    · nix develop ./nix3-develop.md - run a bash shell that provides the build environment of a derivation 
...
```

The strings `./nix3-build.md` etc. are not very useful so it would be nice to filter them out.

**Comment by fricklerhandwerk** [comment]
Fixed by https://github.com/NixOS/nix/pull/6968
