### ISSUE TITLE
nix build => "cannot add path 'path' because it lacks a valid signature"

### ISSUE THREAD

**Issue by colemickens** [NixOS/nix#5343]
**Describe the bug**

```
❯ nix \
  --experimental-features 'nix-command flakes' \
  build \
    --option extra-binary-caches 'https://cache.nixos.org https://colemickens.cachix.org https://nixpkgs-wayland.cachix.org https://arm.cachix.org https://thefloweringash-armv7.cachix.org' \
    --option trusted-public-keys 'cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= colemickens.cachix.org-1:bNrJ6FfMREB4bd4BOjEN85Niu8VcPdQe4F4KxVsb/I4= nixpkgs-wayland.cachix.org-1:3lwxaILxMRkVhehr5StQprHdEo4IrE8sRho9R9HOLYA= arm.cachix.org-1:5BZ2kjoL1q6nWhlnrbAl+G7ThY7+HaBRD9PZzqZkbnM= thefloweringash-armv7.cachix.org-1:v+5yzBD2odFKeXbmC+OPWVqx4WVoIVO6UXgnSAWFtso=' \
    --option build-cores 0 \
    --option narinfo-cache-negative-ttl 0 \
    --builders-use-substitutes \
    --store ssh-ng://opc@132.226.31.59 \
    --eval-store auto \
      .#bundles.aarch64-linux
warning: Git tree '/home/cole/code/nixcfg' is dirty

trace: Building with crossSystem?: aarch64-linux != aarch64-linux → we're not.
error: cannot add path '/nix/store/9gzllmgssd217gfh743zxf7jbq4lvdqi-lingering-users' because it lacks a valid signature

```

What do I do in this case? I ran `nix build` but got a signature error? Is this a side-effect of `--eval-store auto`? 

```
❯ nix --version
nix (Nix) 2.4pre20210922_bcd73eb
```

**Comment by regnat** [comment]
> Is this a side-effect of --eval-store auto?

It looks like it could be, but it’s a bit hard to tell from there. Can you maybe retry with `-v` or `-vv` to have a bit more context around the failure?
Also, is the remote build user a trusted user?

**Comment by colemickens** [comment]
Hm, @regnat I guess I'm not sure. The remote store machine in this case has a single-user nix install on it. The user thats SSHing is the user that installed nix and should have access to it. (aka, `opc` is *the* trusted user).

Here's the `-vv` log: https://gist.github.com/colemickens/e6bdaf728aabc79896e768a83ca5a4f3

**Comment by colemickens** [comment]
So I basically can't use `--eval-store auto` due to this behavior. Meaning I have to completely resort back to building drvs, pushing them, manually copying outputs back, etc.

How are other users of `--eval-store auto` not hitting this? Are folks signing paths on all their machines?

**Comment by colemickens** [comment]
Actually, it's looking a lot like my builders were configuring trusted users *after* the daemon had already started. Going to close this for now.
