### ISSUE TITLE
fetchGit failes with non default ssh port

### ISSUE THREAD

**Issue by ck3d** [NixOS/nix#5376]
Since https://github.com/NixOS/nix/pull/4978 was merged, fetchGit do not respect a ssh port.

**Steps To Reproduce**

With current Nix 2.4pre20211006_53e4794:
```
nix-repl> builtins.fetchGit { url = "ssh://git@github.com:22/NixOS/nix.git"; }
fetching Git repository 'ssh://git@github.com/22/NixOS/nix.git'fatal: remote error:
  22/NixOS/nix is not a valid repository name
  Visit https://support.github.com/ for help
error: program 'git' failed with exit code 128
```

With old Nix 2.4pre20210922_bcd73eb:
```
nix-repl> builtins.fetchGit { url = "ssh://git@github.com:22/NixOS/nix.git"; }
{ lastModified = 1634049780; lastModifiedDate = "20211012144300"; narHash = "sha256-NYjt6jTZyt35hJJfjQsVPB4w7iaN/z40Vzp0k1q1cKA="; outPath = "/nix/store/k302z97m35fl3cnycrgq814kfb490f48-source"; rev = "5176b072ed55d1528cb36e0c865e4fcffbc6a7a1"; revCount = 10824; shortRev = "5176b07"; submodules = true; }
```

**Expected behavior**

fetchGit shall respect the given ssh port as it does for Nix 2.4pre20210922_bcd73eb.

**Comment by markuskowa** [comment]
it would be great if this could be fixed before the 2.4 release.

**Comment by ck3d** [comment]
This issue was fixed in master, but it is still relevant for 2.4

**Comment by terlar** [comment]
Yeah, it would be nice if this could be added to the official 2.4 release. We start to have first-time users of Nix run into this at work and it is making the road a bit bumpy.

**Comment by ck3d** [comment]
Fix was back ported in https://github.com/NixOS/nix/pull/5655
