### ISSUE TITLE
`nix develop` fails when using --command + path to flake

### ISSUE THREAD

**Issue by winterqt** [NixOS/nix#5397]
**Describe the bug**

`nix develop` fails when using --command + path to flake:

```bash
# works
$ nix develop /path/to/flake
# fails with "path: <pwd> is not a flake"
$ nix develop -c ... /path/to/flake
```

**Expected behavior**

For the command to succeed.

**`nix-env --version` output**

```
nix-env (Nix) 2.4pre20210922_bcd73eb
```

**Comment by Kha** [comment]
`-c` eats all remaining arguments, so it should always come last
