### ISSUE TITLE
--repeat not working

### ISSUE THREAD

**Issue by Artturin** [NixOS/nix#5408]
**Describe the bug**
`nix build "nixpkgs#hello" --rebuild --option repeat 5`
doesn't repeat the build 5 times even though the bar shows `[1/0/1 built] building hello-2.10 (round 1/6) (configurePhase)`

**Steps To Reproduce**

`nix build "nixpkgs#hello" --rebuild --option repeat 5`

**Expected behavior**

the build should repeat 5 times

**`nix-env --version` output**
`nix-env (Nix) 2.5pre20211007_844dd90`

@trofi i see that you use the repeat option a lot

**Comment by trofi** [comment]
Does it work for you on CA-enabled system? `nix build --no-link -f. lv -L --repeat 10` on `contentAddressedByDefault = true;` does nothing for me.

**Comment by Artturin** [comment]
the option was removed in https://github.com/NixOS/nix/pull/7099
