### ISSUE TITLE
Installer adds invalid line `-e ` to ~/.profile, leading to `-bash: -e: command not found` at login

### ISSUE THREAD

**Issue by andersk** [NixOS/nix#5458]
On Ubuntu 20.04:

```console
ubuntu@test:~$ curl -L https://nixos.org/nix/install | sh
modifying /home/ubuntu/.profile...

Installation finished!  To ensure that the necessary environment
variables are set, either log in again, or type

  . /home/ubuntu/.nix-profile/etc/profile.d/nix.sh

in your shell.
ubuntu@test:~$ logout
```

Then, upon logging in again:

```console
-bash: -e: command not found
ubuntu@test:~$ tail -n2 .profile
-e 
if [ -e /home/ubuntu/.nix-profile/etc/profile.d/nix.sh ]; then . /home/ubuntu/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
```

This is because the installer uses `echo -e`, which is not supported by Ubuntu’s `/bin/sh` (`dash`).

**Comment by abathur** [comment]
Just leaving breadcrumbs: 

The installer tests added this Spring can and should catch face-palms like this, but it escaped notice because they currently just test daemon/multi-user installs. 

See also https://discourse.nixos.org/t/installer-test-suite-small-project-s-high-leverage-help-wanted/13662 :)

**Comment by andersk** [comment]
Ideally we should also clean up all the ShellCheck warnings and run ShellCheck in CI.

**Comment by abathur** [comment]
I agree shellcheck is a good goal. 

Touching the installer is a lot less stressful now that there are _some_ tests, but I'm still be squeamish about someone going to broadly satisfy all shellcheck nags without the safety-net of an installer test suite that covers enough cases to be fairly sure nothing in the main install scenarios was _depending_ on SC-warned behavior?
