### ISSUE TITLE
Document builtins.fetchTree

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#5463]
It's experimental but it still should be documented.

**Comment by kamadorueda** [comment]
@edolstra I started documenting fetchTree at https://github.com/NixOS/nix/pull/5556, initially for the git backend 

I would like to help documenting the remaining backends, too

**Comment by elikoga** [comment]
Can rework my WIP PR to the state of #5556

**Comment by thufschmitt** [comment]
Fixed by https://github.com/NixOS/nix/pull/8509
