### ISSUE TITLE
Unable to install Nix

### ISSUE THREAD

**Issue by Bradley-Heather** [NixOS/nix#5468]
**Describe the bug**
Unable to install Nix on MacOS Catalina

**Terminal Output**

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/ex /etc/synthetic.conf

to add Nix to /etc/synthetic.conf

---- oh no! --------------------------------------------------------------------
Jeeze, something went wrong. If you can take all the output and open
an issue, we'd love to fix the problem so nobody else has this issue.

:(

What should my next step be? Thanks!!

**Comment by abathur** [comment]
There's likely something unexpected about your environment, but it may take a few rounds of picking at it...

- Is this a first-time install, or a reinstall? 
- Normal mac hardware? VM?
- Do you already have an /etc/synthetic.conf? if so, what's in it, and what does `ls -la /etc/synthetic.conf` say?
- What was the install command?

**Comment by Bradley-Heather** [comment]
Thanks for getting back to me!
- its a reinstall
- normal mac hardware
- i did have a /etc/synthetic.conf. It only had nix in it. I removed it and tried again and it still didn't work.
- I tried installing with Daemon and without. Using the `curl -L https://nixos.org/nix/install | sh` command.

**Comment by abathur** [comment]
It may be easier to iterate on this in real-time, if you can join the macOS room on the [NixOS Matrix](https://matrix.to/#/#community:nixos.org).

In either case, running the command that fails directly may help clarify what's going on (ideally in bash):

```bash
/usr/bin/sudo /usr/bin/ex /etc/synthetic.conf <<EOF
:a
nix
.
:x
EOF
```

**Comment by Bradley-Heather** [comment]
Thanks, I've joined the room.

It seems that that is not where the failure lies as I can run that command and it executes fine.

**Comment by abathur** [comment]
After quite the slog today, we finally shook the problem loose: 

Something in the vim startup/plugin files on this system causes /usr/bin/ex (which the installer uses to edit a few files) to quietly exit with an error code, despite successfully editing the file. 

The error code halts the installer, but the correctly-edited file sends us off on a goose-chase for problems between this line and the next printing statement. I'll address in a PR soon.

**Comment by borkdude** [comment]
I had exactly the same problem.

**Comment by soulomoon** [comment]
I have the same problem, have a clean vim configuration and rename ~/.vim/plugin help in my situation.

**Comment by jj0b** [comment]
I also ran into this, and I got around it by temporarily renaming my ~/.vim directory.
