### ISSUE TITLE
Can `nix-push` be given a -j option?

### ISSUE THREAD

**Issue by acowley** [NixOS/nix#548]
I do not know Perl, so can not easily add this myself, but I would find a parallelized `nix-push` somewhat useful as performance seems gated on `xz`'s CPU usage.

**Comment by vcunat** [comment]
@edolstra: are you sure ``xz -9`` is a good default? The man page says:
> Specifically, it's not a good idea to blindly use -9 for everything like it often is with gzip(1) and bzip2(1).

Note that xz itself supports multi-threaded encoding (of a single large archive), controlled via the `-T` option.

**Comment by edolstra** [comment]
@vcunat Where do you see `-9`? `corepkgs/nar.nix` has:
```
compressor="| ${xz} -7"
```

**Comment by vcunat** [comment]
@edolstra: manual page, i.e. ``doc/manual/command-ref/nix-push.xml``.

**Comment by edolstra** [comment]
Thanks, fixed.
