### ISSUE TITLE
`nix repl`'s `:e` command breaks stdout for editors

### ISSUE THREAD

**Issue by trofi** [NixOS/nix#5487]
The following command launches tty editor:
```
$ EDITOR=nano nix edit -f. nano
```

The following command shows no output for editor:
```
$ EDITOR=nano nix repl .
nix-repl> :e nano
# no editor output
```

I suspect `nix repl` does not restore some terminal state on `:e` and confuses editors.

**`nix-env --version` output**
nix-env (Nix) 2.5pre20211007_844dd90

/cc @edolstra

**Comment by cole-h** [comment]
I've also seen this with `kakoune`, but it just causes kakoune to exit because "stdout is not a tty": https://github.com/mawww/kakoune/blob/a70dbda54c16f327d6f6e7fa5573e3751f7fda47/src/terminal_ui.cc#L458.
