### ISSUE TITLE
Possibly incorrect home directory path for nix.conf

### ISSUE THREAD

**Issue by frontsideair** [NixOS/nix#5496]
I have a fresh install of Nix on my Mac and I tried to add the experimental flags, but the local config path here seems to be wrong. I found the correct one on [NixOS Wiki](https://nixos.wiki/wiki/Nix_command). 

https://github.com/NixOS/nix/blob/c4bd6a15c2171153021691776cc657872c42338c/doc/manual/src/command-ref/conf-file-prefix.md?plain=1#L18

To be sure, I checked `NIX_USER_CONF_FILES`, `XDG_CONFIG_DIRS` and `XDG_CONFIG_HOME` and they are all unset. I wonder if it's really a mistake, but since the manual and the wiki seems to be in conflict about this, I decided to report.

**Comment by ilkecan** [comment]
With https://github.com/NixOS/nix/pull/5493 merged, I think this can be closed.
