### ISSUE TITLE
Binary distributions on FreeBSD 9 fail to complete nix-final-setup.

### ISSUE THREAD

**Issue by steakknife** [NixOS/nix#55]

**Comment by domenkozar** [comment]
@steakknife I wonder if this is still a problem on FreeBSD.

**Comment by armijnhemel** [comment]
FreeBSD 9.x is no longer supported by the FreeBSD project. Is this still a problem on a current, supported FreeBSD?

**Comment by gilligan** [comment]
This seems dead and the author hasn't been active on this for years - i'd suggest to close this one.

**Comment by armijnhemel** [comment]
> This seems dead and the author hasn't been active on this for years - i'd suggest to close this one.

Agreed
