### ISSUE TITLE
Feature request: Ability to disable channels

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nix#551]
Hi,

I want a feature request: I want to be able to have channels in my channel configuration which are disabled. This way, I won't need to re-type the URLs each time I re-add a channel.

Purpose: I want to be able to build my system with a stable channel as well.

Maybe there is another way to do this, but I think this would be the obvious way.

**Comment by vcunat** [comment]
There is ``nix-channel --update [names...]``, so you only need to re-type the names you've chosen (e.g. nixos).

**Comment by matthiasbeyer** [comment]
But when I do a `nixos-rebuild switch` I cannot say "Use the 14.04 channel for building my system, not the unstable one", that's what I meant!

**Comment by vcunat** [comment]
You can provide ``-I``, but that's not very comfortable with channels (I often use ``-I .`` in nixpkgs tree managed by git). 

I see  ``nixos-rebuild`` isn't too user-friendly with multiple nixos channels, AFAIK. That could be improved.

**Comment by edolstra** [comment]
With Nix 1.9, you can say:
```
$ nixos-rebuild switch -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-14.12.tar.gz
```
to use a specific version of NixOS. In other words, it allows not using channels at all.

**Comment by matthiasbeyer** [comment]
@edolstra :+1:
