### ISSUE TITLE
Readonly nix store mount breaks reflinks

### ISSUE THREAD

**Issue by Atemu** [NixOS/nix#5513]
**Describe the bug**

If you have a problem with a specific package or NixOS,
you probably want to file an issue at https://github.com/NixOS/nixpkgs/issues. 

**Steps To Reproduce**

1. Have a reflink capable fs like btrfs
2. Have your `$TMPDIR` in the same mount as /nix so that things can theoretically be reflinked (i.e. `TMPDIR=/nix/var/nix/tmp/` where /nix is a sinlgle mount)
3. Try to copy a large file from the build dir to $out with `cp --reflink=always` for efficiency
4. `Invalid cross-device link`

**Expected behavior**

You should be able to reflink copy to the Nix store and back; its immutability should be achieved without a separate mount.

**`nix-env --version` output**

**Additional context**

Not being able to reflink across multiple mounts of the same FS is a kernel VFS limitation that is unlikely to be fixed any time soon.

The immutable xattr could be a good candidate. I kind of wonder why it wasn't chosen in the first place.

**Comment by regnat** [comment]
> The immutable xattr could be a good candidate. I kind of wonder why it wasn't chosen in the first place.

Maybe that’s also possible with xattrs, but one very compelling argument for a read-only bind-mount is that thanks to mount namespaces we can remount the store rw inside the Nix process when needed, while keeping it read-only for the rest of the system.

**Comment by edolstra** [comment]
We used to set the immutable bit but we got rid of it because it caused problems (b9c2b4d5b4cd5d52a950e6dd90eb2e2e79891fa0).

**Comment by Atemu** [comment]
At least for btrfs, this has been fixed in Linux. Modern kernels can now reflink across VFS boundaries as long as it's the same filesystem.

**Comment by Ericson2314** [comment]
@Atemu I am reopening this issue because even if no code changes are needed on Nix's side anymore, it would still be very nice to have a NixOS VM Integration test ensuring this works.

**Comment by Kha** [comment]
In case anyone else is curious, the fix apparently landed in Linux 5.18

**Comment by Ericson2314** [comment]
@Kha Thanks. Do you have a link to any sort of release notes? Or something else you read?

**Comment by Atemu** [comment]
@Ericson2314 https://lore.kernel.org/linux-btrfs/cover.1645194730.git.josef@toxicpanda.com/T/#mf251325026fe2e15ed5119856bf654ba4f0d298b

**Comment by Ericson2314** [comment]
Thanks @Atemu. So yeah, would I love to see is a basic NixOS test reproducing this, and linking the above mailing list message.
