### ISSUE TITLE
macOS 2.4 install failure on synthetic.conf

### ISSUE THREAD

**Issue by sudocurse** [NixOS/nix#5530]
My MacOS (11.5.2) install fails on synthetic.conf:

```
sh <(curl -L https://nixos.org/nix/install) --no-channel-add
```

```
---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/ex /etc/synthetic.conf

to add Nix to /etc/synthetic.conf


---- oh no! --------------------------------------------------------------------
```
Here's a verbose re-run:

```
+ echo 'to add Nix to /etc/synthetic.conf'
to add Nix to /etc/synthetic.conf
+ echo ''

+ return 0
+ sudo /usr/bin/ex /etc/synthetic.conf
+ finish_fail
+ finish_cleanup
+ rm -rf /var/folders/h8/4c7q_p5j19gfs4899q28251w0000gn/T/tmp.4QtmIXIXFl
+ failure
```

Here's [where it fails](https://github.com/NixOS/nix/blob/3f447bcd5f42f0503dcc0a5dd96737b11ec5dd14/scripts/create-darwin-volume.sh#L634). I'm not sure what error is causing `ex` to fail, but `/etc/synthetic.conf` does exist after this:
```
➤ cat /etc/synthetic.conf
nix
```

**Comment by abathur** [comment]
This sounds like https://github.com/NixOS/nix/issues/5468, which already has an open PR in #5489

**Comment by sudocurse** [comment]
You're right! thanks

**Comment by abathur** [comment]
Does this mean you were able to move the vimrc/plugin files out of the way and install? I'm not sure how practical that is.

In case it isn't, I've re-started my own CI job for #5489; if it completes, it'll generate a test installer that you can try. It'll take a little bit, though. At least an hour.
