### ISSUE TITLE
Easy way to import global registry flakes in repl, similar to channels

### ISSUE THREAD

**Issue by mkg20001** [NixOS/nix#5548]
**Is your feature request related to a problem? Please describe.**
When using channels one can simply invoke the nixpkgs channel using `<nixpkgs>`

One can then for example do `:l <nixpkgs>` in repl and play arround with it

Currently there exists no such mechanism in nix for global registry flakes

**Describe the solution you'd like**
There should be - at the very least for the repl shell - a way to just invoke a flake from the global registry

Something like `$nixpkgs`, to then do `:l $nixpkgs`. possibly the classic way of getting a package with # could be supported aswell, being able to `:b $nixpkgs#htop`

**Describe alternatives you've considered**
`builtins.getFlake("nixpkgs")` but that feels more like a hack

**Additional context**

**Comment by regnat** [comment]
I think you want `:lf`:

```console
$ nix repl
Welcome to Nix 2.5pre20211105_3d6ee22. Type :? for help.

nix-repl> :lf nixpkgs
Added 14 variables.

nix-repl> legacyPackages.x86_64-linux.hello
«derivation /nix/store/andpy37l2jn0hig5p21v62gfm8n3xzwf-hello-2.10.drv»
```

**Comment by regnat** [comment]
Closing this. Feel free to reopen if the solution isn’t good-enough for your use-case

**Comment by lilyball** [comment]
`:lf` is useful but having to then do `legacyPackages.${builtins.currentSystem}` (or whatever your platform is) is annoying. I feel like there really should be some equivalent to the convenience of using `<nixpkgs>`. The other problem with `:lf` is you can't invoke the repl this way like you can with `nix repl '<nixpkgs>'`.

This can also be annoying if you're not sure what the outputs of a flake are. Without knowing the outputs already, it can be hard to know what the attribute path is that replicates using `name#package`.

It would be nice if there was a convenience that was basically equivalent to the following except without errors

```
:lf flakename
:a apps.${builtins.currentSystem}
:a packages.${builtins.currentSystem}
:a legacyPackages.${builtins.currentSystem}
```

Possibly even something where if there's a `defaultApp` or `defaultPackage` it adds that under an attribute synthesized like `lib.getName drv.name`, though this feels more questionable.

And separately, it would be nice if I could write something like `nix repl --load nixpkgs` (or `nix repl -l nixpkgs`) that implicitly runs this new `:lf nixpkgs` variant.

**Comment by mkg20001** [comment]
Another thing is writing a nix file quick-and-dirty

Sometimes one just wants to hack something together quickly and then having to do getFlake() and some magic feels burdensome. My proposed $nixpkgs (or whatever it could be) could allow hacking things together like so `with (import $nixpkgs {}); stdenv.mkDerivation` (where it's `$nixpkgs` instead of `<nixpkgs>`, which now refers to the global registry flake, similar as `:lf`). (This should be something for impure mode only)

**Comment by RuRo** [comment]
For anyone coming to this issue from google, I found that the most "elegant" solution is to set
```nix
nix.nixPath = [ "nixpkgs=${inputs.nixpkgs}" ];
```
in your system config, where `inputs` are the system flake inputs passed via `specialArgs`.

After that you can refer to the system version of `nixpkgs` as `<nixpkgs>` even without any channels configured. Also, legacy package stuff like the ability to do `nix-shell -p netcat` just works.

**Comment by mkg20001** [comment]
What I'm doing is this

```nix
            nix.nixPath = [
              "nixos-config=/etc/nixos/configuration.nix"
            ] ++ (mapAttrsToList
              (key: value: "${key}=${value.to.path}")
              (filterAttrs (key: value: value ? to.path) config.nix.registry));
```

plus

```nix
  nix.registry.nixpkgs.flake = inputs.nixpkgs;
```

This takes all the flakes that are in the registry and adds them as if they were channels. This makes sense if you have other flakes, such as nixos-hardware, that you also want to `:l` import

**Comment by mkg20001** [comment]
@RuRo in that particular case I use it like that so the other part that adds it to nixpath is given a path, plus that makes it resolve even while offline even when it's not cached anywhere.

I see your problem. I've resolved it by just doing inputs.nixpkgs = "github:nixos/nixpkgs/nixpkgs-unstable"; on every project. Don't have any better idea.
