### ISSUE TITLE
install script does not source

### ISSUE THREAD

**Issue by MasseGuillaume** [NixOS/nix#555]
given a fresh new system (mac)
when I install nix with `curl https://nixos.org/nix/install | sh` in the terminal
I cannot immediately use it. I need to open a new terminal so ~/.bash_profile or equivalent is ran

**Comment by edolstra** [comment]
What does "cannot immediately use it" mean?

**Comment by MasseGuillaume** [comment]
open a terminal
```
$ curl https://nixos.org/nix/install | sh
$ nix-env
command not found
```

**Comment by edolstra** [comment]
I don't see how we can fix this, given that a child process cannot change the environment of its parent.

**Comment by MasseGuillaume** [comment]
```
Process A: curl https://nixos.org/nix/install | sh
fork on linux/darwin
curl, unzip and run install (Process B)
      Process B [Child of A] (darwin):
         all the heavy lifting
         creates `$NIX_LINK/etc/profile.d/nix.sh`
// source --^
```

**Comment by domenkozar** [comment]
@MasseGuillaume could you provide a minimal example how it would work? Child process in shell can't change environment in parent unless explicitly told so.

**Comment by Ericson2314** [comment]
`. /dev/stdin` might work in some situations.
http://stackoverflow.com/questions/1279953/how-to-execute-the-output-of-a-command-within-the-current-shell

**Comment by mcandre** [comment]
I also get `nix-env: not found`, when trying to build a Docker image with NixOS and a few packages.

Am I doing something wrong?

```
FROM nixos/nix
RUN nix-channel --update && \
    nix-env -i gcc && \
    nix-env --switch-profile musl && \
    nix-env -i musl && \
    nix-env --switch-profile klibc && \
    nix-env -i klibc && \
    nix-env --switch-profile uclibc && \
    nix-env -i uclibc && \
    nix-env --switch-profile default
```

**Comment by lovebdsobuj** [comment]
Hi **@ all**,

After following this step `curl https://nixos.org/nix/install | sh`.

Just Logout and Come back (Login).

Then open terminal and type `nix-env` 

It should work.

**Comment by MasseGuillaume** [comment]
@lovebdsobuj if you are using it as part of an automated script login in and out is not possible.

**Comment by copumpkin** [comment]
The only thing I can think to do here is to tell people what to do if they want to use Nix immediately. Basically in the usual "we're done" message, we print something like the following:

> Nix has been added to your .profile file. To use it, launch a new shell. If you would like to use Nix in the current shell, run `source ~/.nix-profile/etc/profile.d/nix.sh` to get the Nix environment variables set up properly.

An alternative would be something like changing the incantation on the website to something like

```bash
source <(curl https://nixos.org/nix/install)
```

That gets gnarly though, because we now need to be sensitive to the host shell. The initial install script would need to become some sort of polyglot bash/sh/zsh/fish/tcsh hybrid, or we'd have to complicate the instructions and tell people to get different scripts based on their shell.

**Comment by Anton-Latukha** [comment]
fish is no no.

fish must be completely separated in scripting.

People! People,
...
I use fish for 6-7 years now...

People! People, ... fish ... is not ... POSIX compliant.

Fish does not support sh. End of ultimate point.

sh does not supportfFish.

In the first line of the scripts you always see `#!/bin/sh`, `#!/bin/bash`, you know why?
Do you know how many scripts rely on sh or bash (zsh here goes also)? ~99.5%

Fish shell was promoted as 'interactive' by their team until recently. That means "not for usage in scripts". They removed those descriptions from main page and Arch Wiki, but manual: `This is the documentation for fish, the friendly interactive shell.` still there.
Fanclub of fish removed info that they are not sh/POSIX compatible everywhere. Probably they are just try to fuzz people who doesn't knew simple stuff in somehow moving all ecosystem to fish.

They removed that mentions, do you want proof?
Please show me your `echo "$ENV"`, `echo "$?"`. `false 2>&1 /dev/null` in fish.
Now in any other shell you got.
That is why all Linux scripts on fish not work. Somehow they forgot to mention that now.

I've seen legitimate tries here in NixOS society in PRs, issues to write #!/bin/sh scripts that supports sh and fish. While it is not possible. Fish scripts must be written separately. But somewhere you would probably need to use sh secretly anyway, as you need to hit that one of 99.5% script.

Just like you can not program C++/Haskell file that compiles with and GCC and GHC separately.
If someone can write something useful with that requirements - I want to see that.
And after that people even further want to make that program after compilation work the same. As compiled from C++, or from Haskell.

**Comment by mcandre** [comment]
The install script should be written in pure POSIX sh, or bash. These options are brittle, but the other options are even moreso.

**Comment by peti** [comment]
:+1:

Suggesting `source $HOME/.nix-profile/etc/profile.d/nix.sh` prominently in the install instructions seems like a good idea. Users have opened plenty of tickets here that boil down to them trying to execute Nix commands without having a proper environment.

**Comment by revskill10** [comment]
Thanks @peti , this should be the way to source nix-env after installation.

**Comment by Arlen22** [comment]
> 👍
> 
> Suggesting `source $HOME/.nix-profile/etc/profile.d/nix.sh` prominently in the install instructions seems like a good idea. Users have opened plenty of tickets here that boil down to them trying to execute Nix commands without having a proper environment.

I highly recommend this. I saw this unconsciously as I was closing my terminal window, but I couldn't find the message anywhere in the docs to see what the command was. It should be somewhere in the installation instructions for sure.

**Comment by ashtonbaker** [comment]
This might be a dumb question, but am I supposed to add `source $HOME/.nix-profile/etc/profile.d/nix.sh` to my `.bashrc` or something? That's fine if so, but the recommendation in the installation process, as well as the discussion here seems to imply that everything will work after doing the command once, but I seem to need to do it for every new terminal window.

**Comment by edolstra** [comment]
Closing because this is not something we can fix (except by symlinking `nix-*` into a directory already in `$PATH`, but I don't think we want to pollute the host OS like that).
