### ISSUE TITLE
nix-env cache

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#556]
Nix-env does a lot of operations that require a nearly full scan of your nixpkgs. It seems like at least when your nixpkgs is in the store (as is the case with channels) it's fairly safe to preprocess it into a sqlite db so we can run all the usual nix-env queries super quickly. I'm wary that our newcomers think nix is slow because all tutorials say `nix-env -i` which will literally take 10+ seconds before responding on a spinning disk.

**Comment by lethalman** [comment]
What happens when you modify config.nix? What if you modify ~/.nix-defexpr? And all that stuff. I'd rather modify the tutorials to use `-A`.

**Comment by copumpkin** [comment]
I'm fine with using `-A`, but I don't think other things (upgrades, queries) work as well with it, so it still seems worth figuring out a way to make the common use cases faster for newcomers.

**Comment by adevress** [comment]
+1 with this.

This is particularly annoying when using listing ( nix-env -qa ) where it can takes up to several minutes before printing anything.

**Comment by edolstra** [comment]
See #306. The best solution is probably to use `nix-pack` to automatically rewrite the Nixpkgs channel into a more efficient representation.

**Comment by edolstra** [comment]
Either that or the zip file approach (https://github.com/edolstra/nix/commits/zip-support). That would have the advantage of working nicely with `fetchTarball`.

**Comment by edolstra** [comment]
Closing, the flakes branch adds an evaluation cache.
