### ISSUE TITLE
nix-shell can fail with "argument list too long" when there are many buildInputs

### ISSUE THREAD

**Issue by JackKelly-Bellroy** [NixOS/nix#5593]
**Describe the bug**

In https://github.com/input-output-hk/haskell.nix/issues/1297 , I describe a situation where a derivation had 1699 `buildInput`s, and running `nix-shell` caused "argument list too long".

**Steps To Reproduce**

Save the following as `shell.nix`:

```
{ nixpkgs ? import <nixpkgs> {} }:

let
  replicate = n: x: if n == 0 then [] else [x] ++ (replicate (n - 1) x);
in
nixpkgs.mkShell {
  # 4000 was enough on my machine, you may want to raise it on yours
  buildInputs = replicate 4000 nixpkgs.hello;
}
```

Run `nix-shell` or `nix develop -f shell.nix`, observe error.

**Expected behavior**

Enter the shell without complaint

**`nix-env --version` output**

```
$ nix-env --version
nix-env (Nix) 2.4pre20211006_53e4794
```

**Additional context**

In the `haskell.nix` bug, I noticed that many of the derivations were duplicates, and worked around this using `pkgs.lib.unique` and `overrideattrs`. This is O(n^2), and perhaps it would be better to fix nix-shell and fix it for everyone? That is, would it be faster to cull duplicates from within `nix-shell` itself?

Another possible might be to write large command lines to temporary files, and pass them to the shell that way.

**Comment by roberth** [comment]
> This is O(n^2)

If you can derive a string key, such as the name or outPath, you can use that with `lib.genAttrs` to dedup it in O(n log n).

> That is, would it be faster to cull duplicates from within nix-shell itself?

This changes the semantics significantly. Why would it only dedup a certain attribute? `nix-shell` logic is already complicated enough.

> Another possible might be to write large command lines to temporary files, and pass them to the shell that way.

This seems like something for structuredAttrs.

> large command lines

That's probably how unixes report it, because they have a limited set of errno numbers to work with. I would guess that it's the combination of environment and args that exceeds some limit, or perhaps an individual limit for each but reported the same way.

**Comment by JackKelly-Bellroy** [comment]
I'm getting the sense that there probably isn't anything for Nix to do here, then? If that's right then we should probably close this issue. However, I have a couple of questions:

> If you can derive a string key, such as the name or outPath, you can use that with `lib.genAttrs` to dedup it in O(n log n).

Sorry, I don't quite follow. Can you elaborate?

> This seems like something for structuredAttrs.

As in, nix-shell should use structuredAttrs? Should there be an issue for that instead?

**Comment by roberth** [comment]
> Can you elaborate?

Oops, not `genAttrs` but `listToAttrs`. If that's still O(n) it'd be a Nix bug.

    dedupByStringKey = keyFun: list:
      lib.attrValues (lib.listToAttrs (map (item: { name = keyFun item; value = item; }) list))

> As in, nix-shell should use structuredAttrs? Should there be an issue for that instead?

Whether or not to use structuredAttrs is a choice made by the derivation. I do not know how Nix 2.3 deals with this situation, but Nix 2.4 should support shells with structuredAttrs.
You can enable structuredAttrs on a derivation by setting `__structuredAttrs = true;` in the derivation arguments.

**Comment by JackKelly-Bellroy** [comment]
Okay, great. Seems like Nix has all the tools to deal with this, and there isn't any real bug.
