### ISSUE TITLE
add --print option to nix build to print the store path

### ISSUE THREAD

**Issue by Artturin** [NixOS/nix#5601]
like nix-build does
would be nice if it did it without printing the logs

currently i have a shell function that does it for me

```bash
function printStorePath {
  nix build --no-link "$@" && nix eval --raw "$@"
}
```
`manpath=$(printStorePath nixpkgs#gnumake.man)/share/man man make`

**Comment by tomberek** [comment]
Similar to 2622 and 1930.

**Comment by L-as** [comment]
#2622 #1930
