### ISSUE TITLE
`nix repl` is available without the `nix-command` experimental feature

### ISSUE THREAD

**Issue by samueldr** [NixOS/nix#5604]
**Describe the bug**

`nix repl` is available without the `nix-command` experimental feature.

**Steps To Reproduce**

```
[nix-shell:.../channels/nixpkgs]$ nix repl
Welcome to Nix 2.4. Type :? for help.


[nix-shell:.../channels/nixpkgs]$ nix build
error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override
```
**Expected behavior**

It is unclear whether any commands under the new `nix` command should work without the flag enabled.

**`nix-env --version` output**

```
[nix-shell:.../channels/nixpkgs]$ nix-env --version
nix-env (Nix) 2.4

[nix-shell:.../channels/nixpkgs]$ type nix-env
nix-env is /nix/store/ag01yxbp4z0bksh7qc67xc31rgk91yaa-nix-2.4/bin/nix-env
```

**Comment by andir** [comment]
This seems to be related to https://github.com/NixOS/nix/issues/3516 which was closed but not really fixed.

**Comment by samueldr** [comment]
Resolution here:

 - https://github.com/NixOS/nix/pull/5684#issuecomment-1614545325
