### ISSUE TITLE
"nix build" does not correctly handle configuration

### ISSUE THREAD

**Issue by CrystalGamma** [NixOS/nix#5611]
My nix.conf (generated by the NixOS module) does not contain settings for "experimental-features" (which is documented to default to "nix-command") or "restrict-eval" (which is documented to default to false).
Yet, since the latest update (which AFAICT upgraded Nix to 2.4) a few days ago, invoking `nix build '(import ./nixos {}).system' -o ~/result-sys` errors out claiming that the nix-command feature was disabled.
If I explicitly pass `--extra-experimental-features nix-command` it errors out complaining that the Nix expression is not a valid URL (of course it's not, and Nix 2.3 correctly detected that it's indeed supposed to be a Nix expression.
If I work around that by passing `--expr` before the expression, it errors out complaining that accessing ./nixos is not allowed in restricted evaluation mode, but as mentioned above, restrict-eval is not supposed to be active in the first place.
Passing `--option restrict-eval false` as first option has no effect.

The classical nix-build command works as usual, it doesn't have this issue.

**Steps To Reproduce**

Run any of `nix build '(import ./nixos {}).system' -o ~/result-sys`, `nix build '(import ./nixos {}).system' -o ~/result-sys --extra-experimental-features nix-command`, `nix build --expr '(import ./nixos {}).system' -o ~/result-sys --extra-experimental-features nix-command` or `nix build --option restrict-eval false --expr '(import ./nixos {}).system' -o ~/result-sys --extra-experimental-features nix-command` on a NixOS system (with nix-command not disabled and restrict-eval not enabled by default) in a nixpkgs source tree.

**Expected behavior**

Any of these commands to build the system derivation without error.

**`nix-env --version` output**

nix (Nix) 2.4

**Comment by Kha** [comment]
> "experimental-features" (which is documented to default to "nix-command"

That is a documentation bug, it should be empty.

> but as mentioned above, restrict-eval is not supposed to be active in the first place

`nix build` is now *always* pure unless you explicitly pass `--impure`. I believe `restrict-eval` is basically not relevant for the new `nix` CLI.

**Comment by CrystalGamma** [comment]
> > but as mentioned above, restrict-eval is not supposed to be active in the first place
> 
> `nix build` is now _always_ pure unless you explicitly pass `--impure`. I believe `restrict-eval` is basically not relevant for the new `nix` CLI.

That's not at all obvious from the error message "error: access to path […] is forbidden in restricted mode".
In fact, by using the term "restricted mode", it gives the impression that the option is supposed to have an effect.
I would say this is a documentation issue of a kind as well.

Thanks for the hint that `--impure` is supposed to be used.
I have a lot of local changes to nixpkgs (I should really get more of them upstreamed, but I'm lazy), so pure evaluation is hardly an option for me right now.

**Comment by regnat** [comment]
> That's not at all obvious from the error message "error: access to path […] is forbidden in restricted mode".
> In fact, by using the term "restricted mode", it gives the impression that the option is supposed to have an effect

That’s indeed unfortunate. Esp. given that using the search path gives the right error:
```console
$ nix build --expr '(import <nixpkgs> {}).hello'
error: cannot look up '<nixpkgs>' in pure evaluation mode (use '--impure' to override)
```
