### ISSUE TITLE
Values in nixConfig flake parameter cannot be boolean

### ISSUE THREAD

**Issue by guibou** [NixOS/nix#5621]
**Describe the bug**

Setting a boolean value in `nixConfig` leads to garbage in the error and the value is not taken into account.

```
do you want to allow configuration setting 'allow-dirty' to be set to '0x562215f7b5e0' (y/N)? y
do you want to permanently mark this value as trusted (y/N)? y
error: Boolean setting 'allow-dirty' has invalid value '0x562215f7b5e0'
```

**Steps To Reproduce**

1. `flake.nix` file with at least a `nixConfig` entry:

```nix
{
    nixConfig.allow-dirty = false;
}
```

Then run `nix develop`.

**Expected behavior**

I'd like the configuration option to be taken into account. I tried with `allow-dirty`, but also other options, such as `allow-import-from-derivation` and I cannot see any effect.

**`nix-env --version` output**

`nix-env (Nix) 2.4`

**Comment by yorickvP** [comment]
This is a bug. For now, you can do `nixConfig.allow-dirty = "true";`.
