### ISSUE TITLE
No source release archive for 2.4?

### ISSUE THREAD

**Issue by t184256** [NixOS/nix#5622]
I want to build Nix without first building all the deps needed for bootstrapping from git.
Where's the 2.4 source release archive? https://releases.nixos.org/?prefix=nix/nix-2.4/ only has binary archives.

**Comment by abathur** [comment]
https://github.com/NixOS/nix/blame/2.4/doc/manual/src/release-notes/rl-2.4.md#L325-L326

**Comment by t184256** [comment]
That's rather unfortunate, may I inquire why?

**Comment by abathur** [comment]
I am not in the know; just dot-connecting since I remembered seeing it.

The explanation is a little short on detail, but I did manage to find this: #3410

**Comment by t184256** [comment]
Oh no, I'll have to package not just autoconf, but also bison and flex too now? What a bummer. =(

**Comment by edolstra** [comment]
Another reason was that it was quite annoying for `nix-shell` / `nix develop` to have the dependencies split between two different derivations (the tarball build and the main build).
