### ISSUE TITLE
Builtin lexical list comparison

### ISSUE THREAD

**Issue by Infinisil** [NixOS/nix#5627]
**Is your feature request related to a problem? Please describe.**
Currently lists aren't comparable:
```
nix-repl> [] < []
error: cannot compare a list with a list
```

**Describe the solution you'd like**
Be able to compare lists using lexicographic ordering, where shorter lists are ordered before longer ones, and otherwise the elements are compared in order:
```
nix-repl> [] < []
false
nix-repl> [] < [ 0 ]
true
nix-repl> [ 0 ] < [ 1 ]
true
```

**Describe alternatives you've considered**
This can be implemented in Nix itself, but it's clunky and not very efficient:
```nix
{
  lexicalLessThan = a: b:
    let
      alen = lib.length a;
      compareElements = index:
        if index == alen then false
        else if lib.elemAt a index == lib.elemAt b index then compareElements (index + 1)
        else lib.elemAt a index < lib.elemAt b index;
    in
    if alen == lib.length b then compareElements 0
    else alen < lib.length b;
}
```

**Additional context**
Implementing this is backwards compatible, but probably the `builtins.langVersion` should be increased for this change to be detectable.

**Comment by regnat** [comment]
I’m curious what the use-case for this is (esp. since as you say it’s implementable as a library).
The main reason I generally encounter for wanting some ordering on this kind of not-obviously-ordered data-structures is to have them as keys in (ordered) maps, but I don’t think you’ll want to implement a custom map in Nix anyways ;)

**Comment by Infinisil** [comment]
The PR is WIP, but it can be used for https://github.com/NixOS/nixpkgs/pull/147077. I'll document how this is used there

**Comment by Infinisil** [comment]
Now done with https://github.com/NixOS/nix/pull/5631!
