### ISSUE TITLE
Override or remove the runtime references of a path

### ISSUE THREAD

**Issue by ncfavier** [NixOS/nix#5633]
**Is your feature request related to a problem? Please describe.**

Say you build a NixOS live ISO image. The resulting image will incur a false runtime dependency on all the paths that were used in creating it, because they're now embedded in the image and thus Nix detects their hashes. (False because those paths are references to the store embedded in the ISO itself, not to the local Nix store.)

This is a problem because when I build that ISO from a different machine and it's cached, I just want to download the image from the cache, not its build closure.

Is there a way to forcibly remove or change the runtime references of a store path?

**Describe the solution you'd like**

I'm not sure.

**Describe alternatives you've considered**

The current (horrible) hack I'm using is something like this:
```nix
pkgs.runCommand "nixos.iso" {} ''
  ${pkgs.fortune}/bin/rot < ${pkgs.runCommand "avkbf.vfb" {} ''
    ${pkgs.fortune}/bin/rot < ${iso.config.system.build.isoImage}/iso/* > "$out"
  ''} > "$out"
''
```

It works because `rot` is involutive and mangles all the hashes, so Nix forgets about the references in the intermediary step. The final `nixos.iso` still has a reference to `glibc` for some reason, but this is acceptable.

**Comment by ajs124** [comment]
> Is there a way to forcibly remove or change the runtime references of a store path?

https://github.com/NixOS/nixpkgs/tree/master/pkgs/build-support/remove-references-to
https://github.com/NixOS/nixpkgs/tree/master/pkgs/build-support/nuke-references
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/activation/top-level.nix#L251

**Comment by ncfavier** [comment]
Thanks for your reply. I don't think these do what I want, since they actually modify the path. I want to keep the image intact, only convince Nix it has no references.

**Comment by ajs124** [comment]
`builtins.unsafeDiscardStringContext`?

**Comment by ncfavier** [comment]
This works on Nix strings, not actual store paths.

**Comment by matthewbauer** [comment]
You can compress the image with the "compressImage" option in make-iso9660-image.nix.

But once you have an ISO, why do you need to copy it in a Nix store path? I would just use it as an ordinary file at that point, it's self-contained.

**Comment by ncfavier** [comment]
> You can compress the image with the "isoImage.compressImage" option.

I tried that, but zstd leaves some paths intact. Even then, relying on that isn't a much better hack than the `rot` thing.

> But once you have an ISO, why do you need to copy it in a Nix store path? I would just use it as an ordinary file at that point, it's self-contained.

Well, for example I might build the ISO in some CI environment, push it to Cachix, and then later when I build it on my laptop I only want to fetch the ISO and not its build dependencies. Or sometimes it's the other way around.

**Comment by tomprince** [comment]
This also impacts the nixos initrd image from time-to-time. I've been updating nixos weekly, and looking at the `nix store diff-closures` output. I've noticed at least a few times where initrd pulls in extra packages to the closure.

**Comment by ncfavier** [comment]
Made a PR to fix this: https://github.com/NixOS/nix/pull/7087

I'm going to ping @tilpner and @symphorien because I stumbled upon [bitflip](https://github.com/tilpner/nur-packages/tree/master/pkgs/bitflip) today, which solves the same problem as my `fortune` hack above.
