### ISSUE TITLE
nix-env -qaP gives empty result set when no channels are selected

### ISSUE THREAD

**Issue by anderspapitto** [NixOS/nix#565]
I have a nixos setup on which I've stopped using any channels (in either root or user profiles). Instead I have nixpkgs checkout out at /etc/nixos/nixpkgs via nixos-checkout, and I manually match my commit to the unstable channel to benefit from the binary cache.

In such a scenario, everything works perfectly - nix-env -i, nix-repl, nixos-rebuild, etc. - except for nix-env -qaP, which returns no results. Possibly this is intended behavior (it depends on what is meant by "active Nix expression" in the man page), but nevertheless I find it inconsistent that I can do

$ nix-env -qaP # returns no results
$ nix-env -i hello # successfully installs the "hello" package

**Comment by edolstra** [comment]
It's weird that `nix-env -i` succeeds, since `nix-env` is not supposed to use `/etc/nixos/nixpkgs`. Unless you have it symlinked from `~/.nix-defexpr`?

**Comment by vcunat** [comment]
I successfully use a similar setup for years, but I've got custom ``~/.nix-defexpr`` contents.

**Comment by anderspapitto** [comment]
@edolstra, I wasn't aware of having anything custom in ~/.nix-defexpr, but I reset that directory (by deleting it and then opening a new login shell), after which I see expected behavior (no results from qaP, but -i also tells me there's nothing available)

**Comment by anderspapitto** [comment]
@edolstra, I wasn't aware of having anything custom in ~/.nix-defexpr, but I reset that directory (by deleting it and then opening a new login shell), after which I see expected behavior (no results from qaP, but -i also tells me there's nothing available)
