### ISSUE TITLE
Header and linker issues when installing nix in home (on another distribution)

### ISSUE THREAD

**Issue by lihop** [NixOS/nix#566]
I was following [this guide](https://nixos.org/wiki/How_to_install_nix_in_home_%28on_another_distribution%29) from the wiki on how to install nix in home on another distribution, when I came across a couple of issues regarding `bsdiff-4.3`.

I'm following the manual approach, which involves installing nix dependencies (sqlite3, bzip2, etc.) in $HOME and then compiling nix from source. As a result, many of the library and header files are in non-standard locations. It is also worth mentioning that this is being done on a system on which I do not have root access.

[Here](https://gist.github.com/lihop/ab11c683e4a0eda8878f) is a shell script I wrote which essentially just carries out the commands specified in the guide (plus a couple of ugly hacks, which are described below).

When the script followed the guide exactly, it produced the following error message:

```
  CC     src/bsdiff-4.3/bsdiff.o
src/bsdiff-4.3/bsdiff.c:33:19: fatal error: bzlib.h: No such file or directory
 #include <bzlib.h>
                   ^
compilation terminated.
make: *** [src/bsdiff-4.3/bsdiff.o] Error 1
```

So I hard coded the path to `bzlib.h` in `bsdiff.c` and `bspatch.c`:

```
 grep -r "<bzlib.h>" ./src/bsdiff-4.3/ | awk -F\: '{print $1}' \
   | xargs sed -i 's <bzlib.h> "../../../include/bzlib.h" g'      
```

Running the script again produced a new error message (related to #295):

```
  LD     src/libstore/libnixstore.so
/usr/bin/ld: cannot find -lsqlite3
/usr/bin/ld: cannot find -lbz2
collect2: error: ld returned 1 exit status
make: *** [src/libstore/libnixstore.so] Error 1
  CC     src/bsdiff-4.3/bsdiff.o
  LD     /home/cosc/student/lih18/nix-boot/...
/usr/bin/ld: cannot find -lbz2
collect2: error: ld returned 1 exit status
make: *** [/home/cosc/student/lih18/nix-boot/libexec/nix/bsdiff] Error 1

```

The solution was to hard code the path to `libbz2.so.1.0` in `src/bsdiff-4.3/local.mk`:

```
  grep -r "\-lbz2" ./src/bsdiff-4.3/ | awk -F\: '{print $1}' \
    | xargs sed -i "s -lbz2 $BOOTSTRAP_DIR/lib/libbz2.so.1.0 g"
```

Now the script builds nix without complaint.

This solution (hard coding paths) seems a bit ugly though, especially considering that other source files use/link to the headers/libraries in non-standard locations just fine. It would be nice to install nix in home on another distribution by following the guide on the wiki, without having to hard code any paths in any of the source files.

Perhaps someone here has a better solution?

**Comment by ttuegel** [comment]
It looks like the `configure` script has stopped respecting `LDFLAGS` and `CPPFLAGS`.

**Comment by shuhaowu** [comment]
+1

**Comment by shuhaowu** [comment]
Spoke too soon, I think the correct workaround:

If you add `export LD_LIBRARY_PATH="$NIX_BOOT/lib:$LD_LIBRARY_PATH"` before your script, it should work (`$NIX_BOOT` is where ~/nix-boot)

**Comment by mettatw** [comment]
Another possible workaround is manually patching Makefile after configure, to make it respect `$*FLAGS` again... (tried on 1.11.4)

```bash
./configure .....

sed -ri 's@^GLOBAL_CXXFLAGS \+= .*all$@& '"$CXXFLAGS"'@' Makefile
echo "GLOBAL_CFLAGS += $CFLAGS" >> Makefile
echo "GLOBAL_LDFLAGS += $LDFLAGS" >> Makefile

make
```

**Comment by veprbl** [comment]
pkgconfig should provide correct paths to the found libraries. The fix will be similar to https://github.com/NixOS/nix/commit/78b00bbd8a993c403bb3712bddfd3815f7301b01

**Comment by mettatw** [comment]
@veprbl that is definitely a better idea :D

There seems to be no pkgconfig file for bzip2, but `-L$NIXBOOT/lib` for liblzma from pkgconfig would work for it

**Comment by veprbl** [comment]
I have very little experience with autoconf, but I see that nix is now using AC_CHECK_LIB and AC_CHECK_HEADERS to locate the libraries, which don't seem to provide the paths. And judging by documentation alone, we could get that information if we switch to AC_LIB_LINKFLAGS.

**Comment by edolstra** [comment]
Closing since Nix no longer contains bsdiff.
