### ISSUE TITLE
Broken conversion of release notes for version 2.4 to HTML

### ISSUE THREAD

**Issue by smancill** [NixOS/nix#5682]
#### Describe the bug

Some code sections of the release notes for nix 2.4 are converted to `<blockquote>...</blockquote>` instead of `<code>...</code>`, which results in `-f '<nixpkgs>'` wrongly appearing as `-f ''`.

#### Steps To Reproduce

- Go to the release notes page: https://nixos.org/manual/nix/stable/release-notes/rl-2.4.html#incompatible-changes
- Several code examples are converted from Markdown to `<blockquote>`.
- Some examples are broken because `<nixpkgs>` is taken as an HTML tag, so it disappears.

#### Expected behavior

The code examples should appear as code and `<nixpkgs>` should not disappear.

#### Additional context

<img width="1219" alt="Captura de Pantalla 2021-11-29 a la(s) 00 59 12" src="https://user-images.githubusercontent.com/238528/143807339-62361bb7-7caf-4b77-b1de-f97bf69df14c.png">

Also, it looks ok when opening the Markdown file on GitHub.

**Comment by regnat** [comment]
Indeed. It has been fixed on master by 6a93e186f4838c13701b4f4551ddaa240ea1cf72, but it’s probably worth backporting it to the `2.4-maintenance` branch so that the doc gets updated at the next point release.
