### ISSUE TITLE
Using Nix to install Nix does the wrong thing in a prefix environment

### ISSUE THREAD

**Issue by gitfoxi** [NixOS/nix#569]
To build a prefix environment you have to go build nix with --prefix and some other configurations described in the manual. After the environment is up, you might think, why not start by using Nix to build Nix? It does the wrong thing. Rather than inheriting the configuration it builds a Nix that thinks there's a /nix.

(Originally posted to NixOS/nixpkgs/#8533, @domenkozar tells me it goes here.)

**Comment by adamnovak** [comment]
What's the workaround for this? I am trying to build a new nix in my prefix environment right now (so I can read the new nixpkgs).

**Comment by gitfoxi** [comment]
You can use environment variables to set the locations. http://nixos.org/nix/manual/#sec-common-env

**Comment by edolstra** [comment]
This can be done using `--store` at runtime or `--with-store-dir` at compile time.
