### ISSUE TITLE
allow empty string interpolations 

### ISSUE THREAD

**Issue by milahu** [NixOS/nix#5693]
i use string interpolations to add "noop" comments to strings
noop = dont change the derivation

```nix
"a${/* comment in string */}b" # syntax error, unexpected '}'
''a${/* comment in string */""}b'' # ok
```

ideally both should work

**Comment by Radvendii** [comment]
I'm going to close this since it's been stale for 2 years and it's not clear this is a good idea in the first place (see #5822). Feel free to reopen if you feel strongly and want to continue the discussion.
