### ISSUE TITLE
OUT_PATHS empty on post-build-hook when set in `NIX_CONFIG`

### ISSUE THREAD

**Issue by nrdxp** [NixOS/nix#5694]
**Describe the bug**

I have a simple script to upload artifacts to cache after a build:
```bash
set -x

echo $OUT_PATHS

[[ $DIRENV_IN_ENVRC = 1 ]] && exit
[[ $NO_CACHE_UPLOAD = 1 ]] && exit
[[ -z $OUT_PATHS ]] && exit

export IFS=' '

echo "Signing paths" $OUT_PATHS
nix store sign --key-file secrets/nix-secret-key-file $OUT_PATHS
echo "Uploading paths" $OUT_PATHS
exec nix copy --to 'redacted' $OUT_PATHS
```
I placed the first `echo` statement at the top for debugging. The script always fails to upload anything because `OUT_PATHS` is always empty. 

**Steps To Reproduce**

1. Take the script above
2. set it as a post build hook
3. run `nix build -L nixpkgs#hello`, add a `--rebuild` flag if the package has already been built (since hook only runs after a local build)
4. notice how the echo statement echos nothing

**Expected behavior**

`man nix.conf` says `OUT_PATHS` should contain a space separated list of built paths.

**`nix-env --version` output**

I tried this on the latest nix unstable as well as stable nix 2.4

**Additional context**

I am setting the post-build-hook in a flake `devShell` via the `NIX_CONFIG` variable. This is done because the cache in question is local to this particular flake and it's environment. Not sure if that may somehow be part of the issue.

**Comment by regnat** [comment]
That’s strange, it seems to be working on master (it’s not actually properly tested, but after a manual check, it seems to be properly passed to the build hook). Did the same setup use to work with nix 2.3?

> I am setting the post-build-hook in a flake devShell via the NIX_CONFIG variable

Could it be somehow related to some shell quoting issue?
Also note that if you’re running in multi-user mode and you’re not a trusted user, then this won’t be passed to the daemon

**Comment by nrdxp** [comment]
I may have found the underlying issue here. Haven't had time to test it, but I found out during testing of #5546 that the build hook works if set via `nixConfig` in a flake. I always did a call to `env` from within the hook to debug aws credentials there and I noticed that the options set in `nixConfig` are passed in via the `NIX_CONFIG` var. Since I was setting this same var in the `devShell` originally (since #5546 is not yet merged), perhaps these two are in conflict somehow?

In any case this only seems to be an issue when set in a `devShell` env via `NIX_CONFIG` as far as I can tell so far.

**Comment by regnat** [comment]
I’ve been trying to replicate this, but I couldn’t manage to. Do you have a public repro available by any chance?

**Comment by nrdxp** [comment]
Thanks for having a look. I don't have anything public that I committed since I never got it working, but I'll see if I can maybe create a minimum reproducible flake. If not, then maybe we'll have to close unless I can find a reliable reproduction path

**Comment by nrdxp** [comment]
I'm gonna close for now, as I never got any further at a root cause here, but I did realize that this started happening around the same time that our shared devshell was reimplemented with numtide/devshell, so my guess is that it may just be an issue there.

**Comment by arobertn** [comment]
We started seeing this issue with the release of Nix 2.8.0 in Github CI where we use cachix/install-nix-action with post-build-hook configured in `extra_nix_config`. It is a private repo unfortunately, with complex Nix derivations to boot, so I'm not sure how to help on the reproduction front yet.
