### ISSUE TITLE
Add test for sched_getcpu

### ISSUE THREAD

**Issue by gitfoxi** [NixOS/nix#570]
musl-libc has `sched_setaffinity` but not `sched_getcpu`. I'm not sure why. The quick fix is to add:

```
AC_CHECK_FUNCS([sched_getcpu])
```

to `configure.ac` and replace all:

```
#if HAVE_SCHED_SETAFFINITY
```

with:

```
#if HAVE_SCHED_SETAFFINITY && HAVE_SCHED_GETCPU
```

in `src/libutil/affinity.cc`.

The slow fix is to figure out why musl-libc doesn't have sched_getcpu and what do they expect you to use instead?

**Comment by edolstra** [comment]
Closing since musl apparently has `sched_getcpu` nowadays.
