### ISSUE TITLE
Maybe add -lcrypto to src/libexpr/local.mk

### ISSUE THREAD

**Issue by gitfoxi** [NixOS/nix#571]
Not sure why, but it fixes a build issue for me.

```
libexpr_LDFLAGS = -ldl -lcurl -lcrypto
```

**Comment by copumpkin** [comment]
Probably worth explaining what the build issue is, on what platform, and anything else that might help people evaluate your suggestion :smile:

**Comment by gitfoxi** [comment]
I forget exactly but it was some random Linux; there was a link failure mentioning some symbol found in libcrypto referenced by libcurl (on that random Linux which was probably Alpine-64). Another fix may be using the pkg-config of libcurl which should always tell you how to link it.

**Comment by edolstra** [comment]
Closing, can't reproduce.
