### ISSUE TITLE
invalid operation 43 after accidentally downgrading

### ISSUE THREAD

**Issue by wmertens** [NixOS/nix#5712]
I had a flake setup on 21.11 with nixUnstable and I switched it to regular nix in the mistaken idea that nix would be v2.4, but it was v2.3.

After that I couldn't evaluate my config any more so I manually activated the previous version.

Then I used unstable again (and later specifically set nix to nix_2_4) but nixos-rebuild always fails. The command that fails is this:

```
++ nix build 'git+file:///etc/nixos?ref=main&rev=57bdf2493cf1ff1b54d26f9421713debe6e1e323#nixosConfigurations."wmertens-nixos".config.system.build.toplevel'
error: invalid operation 43
```

I can work around it because it prints the system .drv and I can manually build that with `nix-build` and manually activate it, but nixos-rebuild always fails.

What is this error 43?

**Comment by edolstra** [comment]
43 = wopQueryRealisation (which is CA related). It would probably be safe for `RemoteStore::queryRealisationUncached()` to return no realisations if the daemon is too old. @regnat

**Comment by regnat** [comment]
> 43 = wopQueryRealisation (which is CA related). It would probably be safe for `RemoteStore::queryRealisationUncached()` to return no realisations if the daemon is too old. @regnat

Indeed, that certainly shouldn’t happen.

@wmertens do you have the `ca-derivations` xp feature enabled? Or does it happen even without it?

**Comment by wmertens** [comment]
@regnat yes it's enabled, my config is here https://github.com/wmertens/nixos-config-lenovo-c940/blob/57bdf2493cf1ff1b54d26f9421713debe6e1e323/configuration.nix#L39-L46
