### ISSUE TITLE
Cannot build nixUnstable 2.5pre20211126

### ISSUE THREAD

**Issue by winterqt** [NixOS/nix#5738]
### Describe the bug

I cannot build nixUnstable 2.5pre20211126 on my aarch64-darwin machine.

### Steps To Reproduce

1. Attempt to build `nixUnstable` 2.5pre20211126 in latest `nixpkgs-unstable`

### Expected behavior

For it to build.

**`nix-env --version` output**

```console
 - system: `"aarch64-darwin"`
 - host os: `Darwin 21.1.0, macOS 12.0.1`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.5pre20211007_844dd90`
 - channels(winter): `""`
 - channels(root): `""`
 - nixpkgs: `/nix/store/ypirn5v82ry7q8j8s089cx246w1k4gg3-source`
```

### Additional context

```
  GEN    doc/manual/nix.json
  GEN    doc/manual/conf-file.json
libc++abi: libc++abi: terminating with uncaught exception of type nix::SysError: error: getting status of /System/Library/LaunchDaemons/com.apple.oahd.plist: Operation not permittedterminating with uncaught exception of type nix::SysError: error: getting status of /System/Library/LaunchDaemons/com.apple.oahd.plist: Operation not permitted

/nix/store/wr5w17nxl5y1lrw7rp3dcjf4w51xj8yx-bash-5.1-p8/bin/bash: line 1: 27545 Abort trap: 6           env -i HOME=/dummy NIX_CONF_DIR=/dummy NIX_SSL_CERT_FILE=/dummy/no-ca-bundle.crt NIX_STATE_DIR=/dummy /nix/store/8y8qnipjn9yfrwj0jyygiarq9kx311xz-nix-2.5pre20211126_55275fc/bin/nix __dump-args > doc/manual/nix.json.tmp
/nix/store/wr5w17nxl5y1lrw7rp3dcjf4w51xj8yx-bash-5.1-p8/bin/bash: line 1: 27546 Abort trap: 6           env -i HOME=/dummy NIX_CONF_DIR=/dummy NIX_SSL_CERT_FILE=/dummy/no-ca-bundle.crt NIX_STATE_DIR=/dummy /nix/store/8y8qnipjn9yfrwj0jyygiarq9kx311xz-nix-2.5pre20211126_55275fc/bin/nix show-config --json --experimental-features nix-command > doc/manual/conf-file.json.tmp
make: *** [doc/manual/local.mk:59: doc/manual/conf-file.json] Error 134
make: *** Waiting for unfinished jobs....
make: *** [doc/manual/local.mk:55: doc/manual/nix.json] Error 134
```

**Comment by Artturin** [comment]
looks like a separate issue from https://github.com/NixOS/nix/issues/5687

**Comment by winterqt** [comment]
Wouldn't be surprised if it's related to sandbox, since it's trying to stat(?) a file in `/System`.

**Comment by abathur** [comment]
Remembered seeing this path lately: #5388 #5628

I guess there's been some churn, here. Maybe we're seeing macOS version differences? Or maybe seeing the presence/absence of a security permission such as full-disk access? Do you have the path `/System/Library/LaunchDaemons/com.apple.oahd.plist`?

**Comment by winterqt** [comment]
> Do you have the path `/System/Library/LaunchDaemons/com.apple.oahd.plist`?

Yes.

> Edit: guess it's also worth confirming that whatever commit `2.5pre20211126` is at is late enough to include the sandbox fix in #5628.

It is: https://github.com/NixOS/nix/blob/55275fcc5966cfad80fb6dc77b8d8939a2f1b8e0/src/libstore/sandbox-defaults.sb#L104

**Comment by abathur** [comment]
I didn't pay enough attention the first time through, but now I see that the [paths it's checking](https://github.com/yvt/nix/blob/a9d9e5555118025032eabd9612e03473a97ebff8/src/libstore/globals.cc#L151-L152) aren't in the sandbox definition at all. I'm having a hard time imagining that they're essential here just because of how far we've gotten without this coming up, but it seems like it would explain the error. @matthewbauer?

**Comment by Artturin** [comment]
Does this still happen? Leave a comment if it does and I'll reopen

**Comment by winterqt** [comment]
Yup, still happens as of 2.10.3.
