### ISSUE TITLE
nix-collect-garbage needs to be run twice to collect all garbage

### ISSUE THREAD

**Issue by danbst** [NixOS/nix#575]
I've encountered strange issue two times on nixos-unstable channel

The first time I could not run `nix-collect-garbage -d`
But I could run `nix-collect-garbage && nix-collect-garbage -d` 

The second time I could not run `nix-collect-garbage -d`
But I could not also run `nix-collect-garbage && nix-collect-garbage -d` 
Only `nix-collect-garbage && nix-collect-garbage -d && nix-collect-garbage && nix-collect-garbage -d `  was working.

I use `nixos-rebuild test` most of the times (sometimes `switch` to fixup the work)

https://gist.github.com/danbst/792b7990d5f572dba6d6

**Comment by bennofs** [comment]
I also get a similar error when just running nix-collected-garbage -d:

```
....
removing generation 37
error: getting status of ‘/nix/var/nix/profiles/per-user/benno/profile-1295-link’: No such file or directory
```
