### ISSUE TITLE
Docker hub: Provide tag for the latest `2.3.x` Nix release

### ISSUE THREAD

**Issue by erikarvstedt** [NixOS/nix#5780]
Now that [nixos/nix](https://hub.docker.com/r/nixos/nix/) has switched to version `2.5.0`, please provide a tag for the latest `2.3.x` release (The default in NixOS stable).

**Comment by garbas** [comment]
This is now done.

**Comment by tomprince** [comment]
Is the `Dockerfile` that was used to build that available anywhere? I assume it is based on https://github.com/NixOS/docker but I don't see a tag or commit with 2.3.16 there.

**Comment by erikarvstedt** [comment]
https://hub.docker.com/r/nixos/nix/ still points to https://github.com/NixOS/docker

**Comment by garbas** [comment]
> Is the `Dockerfile` that was used to build that available anywhere? I assume it is based on https://github.com/NixOS/docker but I don't see a tag or commit with 2.3.16 there.

I already archive the `nixos/docker` repository and manually build and pushed the latest 2.3 bugfix version. Automated builds were not working anyway for some months now. Build and pushing manually was anyway the only option.

Feel free to take that `Dockerfile` from `nixos/docker` repository and bump the Nix version there. There are also 2 other options if you want to extend the latest image:
- use Dockerfile like before `FROM nixos/nix:latest ...` and build new image using `docker build` 
- use dockerTools and extend docker image and build it using `nix-build`

> https://hub.docker.com/r/nixos/nix/ still points to https://github.com/NixOS/docker as the `Source Repository`.

As far as I can tell there is no way to change `Source Repository` in Docker Hub. If you maybe know how I'd love to know :) I think I'll just pull all the docker images from `nixos/nix` and recreate the docker hub repository.

**Comment by tomprince** [comment]
> > Is the `Dockerfile` that was used to build that available anywhere? I assume it is based on https://github.com/NixOS/docker but I don't see a tag or commit with 2.3.16 there.
> 
> I already archive the `nixos/docker` repository and manually build and pushed the latest 2.3 bugfix version. Automated builds were not working anyway for some months now. Build and pushing manually was anyway the only option.

It would be nice if you could push the change to that repository (I think you can unarchive and rearchive the repository to do that.

> > https://hub.docker.com/r/nixos/nix/ still points to https://github.com/NixOS/docker as the `Source Repository`.
> 
> As far as I can tell there is no way to change `Source Repository` in Docker Hub. If you maybe know how I'd love to know :) I think I'll just pull all the docker images from `nixos/nix` and recreate the docker hub repository.

Please contact docker support for doing that, since recreating it would lose (at a minimum) all push dates of tags from the repository.
