### ISSUE TITLE
nixos/nix Docker Hub page links to wrong repo

### ISSUE THREAD

**Issue by l0b0** [NixOS/nix#5796]
**Describe the bug**

It links to https://github.com/NixOS/docker, which is archived and refers to a non-specific part of the nixos/nix repo.

**Expected behavior**

It should link to the relevant repo/folder

**Comment by jtojnar** [comment]
Still an issue: https://hub.docker.com/r/nixos/nix/

**Comment by garbas** [comment]
Closing this one since there is nothing we can do (sadly). There is no way to change this link.

If somebody comes across this issue and this is now possible please ping me.

**Comment by jtojnar** [comment]
Would it be at least possible to turn NIXOS/NIX into a link in https://github.com/NixOS/docker readme?
