### ISSUE TITLE
`nix eval` broken with flakes enabled

### ISSUE THREAD

**Issue by psydvl** [NixOS/nix#5800]
### Describe the bug
`nix eval --raw nixpkgs.package` outputs not what expected when you enable flakes

### Steps To Reproduce
With __nixos__:
1. enable flakes
	1. add to your configuration.nix or [use other way](https://nixos.wiki/wiki/Flakes#Installing_flakes)
		``` nix
		{
		#...
			nix = {
				package = nixFlakes;
				extraOptions = ''
					experimental-features = nix-command flakes
				'';
			};
		#... outer brackets added due syntax highlight expectation 
		}
		```
	2. rebuild nixos
2. execute, for example, `nix eval --raw nixos.wget`

### Result behavior
``` console
$ nix eval --raw nixos.wget
error: getting status of '/home/nixi/nixos.wget': No such file or directory
```
or even
``` console
$ pushd $DIR & nix eval --raw nixos.wget
error: getting status of '$DIR/nixos.wget': No such file or directory
```

### Expected behavior
``` console
$ nix eval --raw nixos.wget
/nix/store/8llg6cf1xpkfd0g27vmakl93s25q8ysr-wget-1.21.2
```

### Additional context
Possibly related:
https://github.com/NixOS/nixpkgs/issues/97176
https://github.com/NixOS/nix/issues/5731

### Metadata
**`nix-env --version` output**
``` console
$ nix-env --version
nix-env (Nix) 2.4
```
```console
$ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.3-zen1, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4`
 - channels(root): `"nixos-21.11.334247.573095944e7, nixos-unstable-22.05pre338578.a2e281f5770"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by johnae** [comment]
Flakes changes the way you reference a derivation. Not saying this issue is wrong but when using flakes I'd do this:

```sh
❯ nix eval --raw nixpkgs#wget
/nix/store/684mr0w6v9vxhvrdi0kxrkdf1ncdsry6-wget-1.21.2
```

**Comment by psydvl** [comment]
@johnae, thank you! 
Am I so inattentive or did `nix eval --help` and https://nixos.wiki/wiki/Nix_command/eval just update?
