### ISSUE TITLE
nixos-rebuild offline

### ISSUE THREAD

**Issue by piegamesde** [NixOS/nix#5802]
**Is your feature request related to a problem? Please describe.**
There are a lot of issues around building nix derivations in offline mode, when no dependencies need to be fetched: #1985 #2715 #1195.

As far as I can tell, all the fixes are only concerned with `nix-build` and `nix build`. None of them seem to mention `nixos-rebuild`, so I'm opening this issue.

**Describe the solution you'd like**
If the internet connection fails, but none is actually needed, then the build should not fail.

**Describe alternatives you've considered**
A `nixos-rebuild --offline` flag

**Additional context**
Workaround: `nixos-rebuild switch --option substitute false` [source](https://discourse.nixos.org/t/rebuild-nixos-offline/3679/4?u=piegames)

**Comment by regnat** [comment]
`nixos-rebuild` isn’t part of Nix itself, but of nixpkgs. I can’t move the issue, but you should try reopening it there

**Comment by piegamesde** [comment]
Thanks for the notice. Moved to https://github.com/NixOS/nixpkgs/issues/151548.
