### ISSUE TITLE
doesn't catch infinite recursion involving overlays

### ISSUE THREAD

**Issue by zseri** [NixOS/nix#5817]
**Describe the bug**
I managed to trigger a non-detected/catch'ed infinite recursion (or maybe just an infinite evaluation loop) in Nix, which leads to unbounded memory usage growth (until it is killed). It doesn't display any error message or such while doing so.

**Steps To Reproduce**
Clone/checkout my nixos-configs repo at commit https://github.com/zseri/nixos-configs/commit/88b7c26d804435edd6e17ce69b5b19d996e3e97b

run `nix build --keep-going -v -L -j1 --cores 1 --show-trace .#nixosConfigurations.plutow.config.system.build.toplevel`

**Expected behavior**
Nix should terminate with "possible infinite recursion" error.

**`nix-env --version` output**
nix-env (Nix) 2.5pre20211202_3f3561f

**Additional context**
```
experimental-features = nix-command ca-derivations flakes
```

[core dump](https://ytrizja.de/misc/f04e14f202934675fc42350de4560d74eb6f84659a7cafb1a462db3e7ee75bdf.core.lz4) (retrieved using `kill -ABRT nix` + coredumpctl)

**Comment by roberth** [comment]
Note that it is possible for each iteration of an infinite recursion to produce a lot of work and data structures that can not be released until done.
A Nix stack trace on ^C interrupt will be invaluable for debugging any runaway computation.

**Comment by zseri** [comment]
I checked my linked commit, and it appears to be already fixed in
nix-env (Nix) 2.6.0pre20211223_af553b2
