### ISSUE TITLE
2.5 repl takes 10x longer to start that 2.4 repl

### ISSUE THREAD

**Issue by pennae** [NixOS/nix#5823]
upgraded from nix 2.4 to 2.5 today, and noticed that `nix repl '<nixpkgs>'` takes 10 times longer to get to prompt now.

**Steps To Reproduce**

```
~ % nix shell nixpkgs#nix_2_4 nixpkgs#hyperfine -c bash -c 'nix --version; hyperfine "nix repl \<nixpkgs\>"'
nix (Nix) 2.4
Benchmark 1: nix repl \<nixpkgs\>
  Time (mean ± σ):     359.3 ms ±  17.0 ms    [User: 297.4 ms, System: 46.6 ms]
  Range (min … max):   345.2 ms … 405.1 ms    10 runs
 
~ % nix shell nixpkgs#nix_2_5 nixpkgs#hyperfine -c bash -c 'nix --version; hyperfine "nix repl \<nixpkgs\>"'
nix (Nix) 2.5.1
Benchmark 1: nix repl \<nixpkgs\>
  Time (mean ± σ):      3.958 s ±  0.087 s    [User: 3.853 s, System: 0.059 s]
  Range (min … max):    3.912 s …  4.201 s    10 runs
```

**Comment by pennae** [comment]
bisected to ab35cbd675610a52513f746051e98d0a50815bc1 which causes the bulk of the slowdown, and 81e7c40264520b387358917987d101f5f5ae4705 which independently adds another 20% slowdown

**Comment by yorickvP** [comment]
The change to [src/nix/repl.cc](https://github.com/NixOS/nix/commit/ab35cbd675610a52513f746051e98d0a50815bc1#diff-f7dd98230f8db4771d167dd1921af118cb3828ad25e6d9a0ec9be3c88c1b0ff1) changes the initialization from `n log n` to `n * n log n`, where `n = 15500` or thereabouts. `NixRepl::addAttrsToScope` should probably be changed to just call `sort` once.
