### ISSUE TITLE
[Documentation] New operators introduced without explanation

### ISSUE THREAD

**Issue by TheodorRene** [NixOS/nix#5845]
Browsing the Nix manual from https://nixos.org/manual/nix/stable where I met an obstacle I believe should be made clearer.
In https://nixos.org/manual/nix/stable/expressions/language-constructs.html#assertions there is a new operator introduced that is not very common in other programming languages. The logical implication or "->" in Nix.  I think https://nixos.org/manual/nix/stable/expressions/language-operators.html should be linked or a help text should show the truth table. It stumped me and will probably stump others.

**Comment by thufschmitt** [comment]
“New” is a bit of an overstatement (https://github.com/NixOS/nix/commit/fa18f1f184ba89b3dfe592e77a276da42d326f42 ) :stuck_out_tongue: , unless by new you mean that it’s new compared to what the other languages offer.

But at any rate, feel free to open a PR to add a link to the operator table or just a one-liner description, that might make things clearer (I must confess I didn’t even remember the existence of this operator)

**Comment by TheodorRene** [comment]
> “New” is a bit of an overstatement ([fa18f1f](https://github.com/NixOS/nix/commit/fa18f1f184ba89b3dfe592e77a276da42d326f42) ) stuck_out_tongue , unless by new you mean that it’s new compared to what the other languages offer.

New as in not introduced previously in the guide and new as it might be unfamiliar to most. As you mentioned, not many languages implement it.
