### ISSUE TITLE
Can't remove /nix

### ISSUE THREAD

**Issue by daweth** [NixOS/nix#5847]
**Describe the bug**
I am simply trying to remove nix files so I can reinstall it. However it keeps giving me the error `rm: /nix: Read-only file system`

**Steps To Reproduce**

`sudo rm -rf /etc/nix /nix /var/root/.nix-profile /var/root/.nix-defexpr /var/root/.nix-channels`

**Expected behavior**

I expected Nix to be removed 

**`nix-env --version` output**

`zsh: command not found: nix-env`

**Additional context**

Using M1 Max and MacOS latest version

**Comment by abathur** [comment]
Starting with 2.4, the darwin installer should prompt you for permission to remove these (but it'll still need you to remove the shell init backups).

In any case, I think [toonn's gist](https://gist.github.com/toonn/94a38643d8fa5c9e06100cdfa81ba163#uninstalling) has up-to-date uninstall instructions.

**Comment by daweth** [comment]
The gist resolved it. Thanks @abathur
