### ISSUE TITLE
[Question] Significance of nix.sh and nix-daemon.sh when building from source on linux

### ISSUE THREAD

**Issue by AulonSal** [NixOS/nix#5848]
I could not find any explicit documentation on which script(s) a multi-user nix install on a linux system running systemd is supposed to source to configure environment variables.

Building from source generates two scripts to be sourced:
- https://github.com/NixOS/nix/blob/2.5.1/scripts/nix-profile-daemon.sh.in -> generates `etc/profile.d/nix-daemon.sh`
- https://github.com/NixOS/nix/blob/2.5.1/scripts/nix-profile.sh.in -> generates `etc/profile.d/nix.sh`

**Which of the above is/are supposed to be sourced by a multi-user nix install?**

## Context:
[Arch Linux](https://archlinux.org) has its own [[nix] package](https://archlinux.org/packages/community/x86_64/nix) which installs nix in a multi-user configuration, and configures the system to source both the scripts generated.

I believe that only the script generated from `nix-profile-daemon.sh.in` should be sourced by such an installation, and opened a [bug report on the Arch bug tracker](https://bugs.archlinux.org/task/73120) explaining my rationale, Arch-devs asked me to seek clarification from upstream as to the intent of these scripts.

**Comment by abathur** [comment]
Yes--only the first script for multi-user.

Here's where the installer would usually add these: 

https://github.com/NixOS/nix/blob/b4f250417ab64f237c8b51439fe1f427193ab23b/scripts/install-multi-user.sh#L744-L781

And here are the relevant variables: https://github.com/NixOS/nix/blob/b4f250417ab64f237c8b51439fe1f427193ab23b/scripts/install-multi-user.sh#L36-L38

**Comment by AulonSal** [comment]
Thank you for the detailed explanation.
