### ISSUE TITLE
Could Nix work without root privileges?

### ISSUE THREAD

**Issue by danse** [NixOS/nix#585]
I really appreciate when software works without the need to use root privileges, i think that it might be quite important in several contexts. I just installed Nix and it asked my root password just in order to write content into `/nix`. Would it be possible to use a default folder in a different position so that i do not need to provide root credentials? It could be `~/.nix`, or `~/nix`, or use the current working directory, or ask for the installation directory as an option overriding the default

**Comment by lethalman** [comment]
It should be possible to run nix in a different directory, I believe there are some docs available about that somewhere, however you will not be able to use the binary cache of nixos.org .

There are also several alternatives like using lightweight user chroots ecc., but are not very usable in most cases. My last attempt is this: https://github.com/lethalman/nix-user-chroot , you will be able to install nix and install software ecc., but some things (like creating a pty) don't work yet.

**Comment by danse** [comment]
Alright i see that [manually creating the installation directory is documented](http://nixos.org/nix/manual/#chap-installation) in the manual as a way to avoid giving the passwords. Fair enough, this closes the issue, sorry for shooting it too early, keep up the good work!

**Comment by lethalman** [comment]
@danse ah yes, didn't think that would be enough for you :)

**Comment by danse** [comment]
If i do not have to give my root password, i feel better! Thanks anyway for the tips! :)

**Comment by danse** [comment]
Also related https://github.com/NixOS/nix/issues/16

**Comment by darthdeus** [comment]
This might be a silly question, and a few years too late, but I can't find this in the manual. Why wouldn't you be able to use binary cache?

**Comment by edolstra** [comment]
Because Unix binaries are not relocatable in general. So if they're built for `/nix/store` you can't put them somewhere else.

Having said that, Nix does have support for non-root operation using mount namespaces, e.g. `nix run --store ~/my-nix ...`).

**Comment by fakedrake** [comment]
any news on documentation about this?

**Comment by fakedrake** [comment]
> This might be a silly question, and a few years too late, but I can't find this in the manual. Why wouldn't you be able to use binary cache?

Some software needs hardcoded absolute paths for configuration files or other artefacts that are generated at compile time (typically with `configire --prefix=...`). As far as I can tell the glorious nix maintainers patch said packages to look at the right places for each artifact rather than requiring single prefix path. But these right places are still hardcoded and assumed to be subpaths of `/nix/store`.
