### ISSUE TITLE
Still seeing `warning: dumping very large path (> 256 MiB); this may run out of memory` when fixed output derivation is large

### ISSUE THREAD

**Issue by benpye** [NixOS/nix#5854]
**Describe the bug**

Whilst #4030 has fixed this issue in many cases, it seems we still dump the path from the store when building a recursive mode fixed output derivation.

**Steps To Reproduce**

Building the `xilinx-ise` package from https://github.com/benpye/nix-fpga-tools/tree/fixed-output-derivation should reproduce this issue. As per the readme, the input archive first needs to be added to the store.

Note, the hash is likely wrong for the fixed output derivation so I don't expect this to build successfully however this issue occurs prior to that point. I did not have the patience to wait for it to finish and fail as even with 32GB it was swapping heavily.

**Expected behavior**

Whilst this pushes the limit of what a reasonable size store path is - in this case it is ~21196320400 bytes - it would be nice if this worked to avoid rebuilds of the intermediate `xilinx-ise-unwrapped` package. 

**`nix-env --version` output**
```
nix-env (Nix) 2.5.0pre20211206_d1aaa7e
```

**Additional context**

This is an attempt to package a large proprietary software package and as such the store paths end up being very large. Whilst we can now add the input archive to the store without much issue, with this limitation I'm not sure there is an easy way to avoid excessive rebuilds.

Related issues: #1184

**Comment by tpwrules** [comment]
Is this fixed by #6925?

**Comment by benpye** [comment]
Sorry for the slow response, but this does appear to be fixed! It still takes a little while, but completes within a practical period of time at least.
