### ISSUE TITLE
nixos.org/nix/ no longer exists

### ISSUE THREAD

**Issue by juhp** [NixOS/nix#5860]
I just wanted to note that the https://nixos.org/nix/ webpage no longer exists: well it redirects to https://nixos.org .

Maybe https://github.com/NixOS/nix should be considered the homepage now for nix?

For example https://nixos.org/nix is linked on https://github.com/NixOS/nix as the homepage.

**Comment by 7c6f434c** [comment]
>I just wanted to note that the https://nixos.org/nix/ webpage no longer exists: well it redirects to https://nixos.org .
>
>Maybe https://github.com/NixOS/nix should be considered the homepage now for nix?
>
>For example https://nixos.org/nix is linked on https://github.com/NixOS/nix as the homepage.

Given that the Nix manual is at https://nixos.org/nix/manual a simple landing page could be still nice to have…

**Comment by edolstra** [comment]
Thanks, I've changed it to https://nixos.org/.
