### ISSUE TITLE
readFile adds newline

### ISSUE THREAD

**Issue by ip1981** [NixOS/nix#587]
`readFile` adds newline, it should not.

E. g. 
```
foo<EOF>
```
becomes

```
foo\n<EOF>
```

**Comment by edolstra** [comment]
I am not seeing this behavior:
```
$ echo -n foo > bar
$ nix-instantiate --eval -E 'builtins.readFile ./bar'
"foo"
```

**Comment by ip1981** [comment]
Ah, sorry. That was our another function in the chain :-)

**Comment by steve-chavez** [comment]
I also got hit by this and turned out it was VIM's doing. It adds a newline at the end by default.

See https://stackoverflow.com/questions/1050640/vim-disable-automatic-newline-at-end-of-file for a fix.
