### ISSUE TITLE
flakes: consistency with URL/URI

### ISSUE THREAD

**Issue by tomberek** [NixOS/nix#5872]
Some JSON outputs refer to things as uri vs url
```
src/nix/flake-metadata.md:* `original` and `originalUrl`: The flake reference specified by the
src/nix/flake.cc:            j["originalUrl"] = flake.originalRef.to_string();
src/nix/profile.cc:                        parseFlakeRef(e["originalUri"]),
src/nix/profile.cc:                obj["originalUri"] = element.source->originalRef.to_string();
src/nix/profile.md:      "originalUri": "flake:nixpkgs",
src/nix/profile.md:* `originalUri`: The [flake reference](./nix3-flake.md) specified by
src/nix/profile.md:* `uri`: The immutable flake reference to which `originalUri`
```

This was noticed when trying to use the same logic with a manifest.json and `nix flake metadata`

I have no strong opinion at the moment exactly which way to go, but would prefer to have consistency. I started to turn things into URI (https://github.com/tomberek/nix/commit/c59cac1261ceb551e553aab69d950d2688955d24), but thought it might be better to bring this up as an issue instead a PR.

**Comment by tomberek** [comment]
@edolstra We can work on this; which direction should we go in and rename everything?

**Comment by balsoft** [comment]
I would prefer URL, since (I think) it is always a URL and never a non-URL URI.

**Comment by tomberek** [comment]
We'll go with URL.

**Comment by tomberek** [comment]
Plan:
- Update format to use URL
- Allow old format and with read if old version exists, no error
- No deprecation warning at this point. (this will start a "how long do we deprecate things" conversation)
