### ISSUE TITLE
Stabilize flakes

### ISSUE THREAD

**Issue by garbas** [NixOS/nix#5881]
This is a meta to follow what needs to be done before we stabilize flakes.

**Comment by sstubbs** [comment]
really looking forward to being able to use flakes without fear of them changing.

**Comment by opeik** [comment]
Is there a list of things to be done? I'd offer to help but I'm not sure where to start...

**Comment by patricksjackson** [comment]
@opeik There's been some progress on a plan for the plan: https://github.com/NixOS/rfcs/pull/136

**Comment by fricklerhandwerk** [comment]
Closed by the existence of https://github.com/NixOS/nix/milestone/27
