### ISSUE TITLE
intermittent installer test failures starting around 3-4 weeks ago

### ISSUE THREAD

**Issue by abathur** [NixOS/nix#5886]
I noticed today that installer tests have been intermittently failing recently. I'm not sure if it's an issue with Nix or an issue with Cachix, but it looks like both ubuntu and macOS installer can fail, each with one of two patterns. Scanning through https://github.com/NixOS/nix/actions/workflows/test.yml?query=branch%3Amaster I found:

- one pattern is a 404 from cachix; the earliest I found is [test 4598](https://github.com/NixOS/nix/actions/runs/1574426794) (24 days ago)
- the other pattern is a sha256 mismatch that may be related? seems to first appear in [test 4648](https://github.com/NixOS/nix/actions/runs/1589378427) (21 days ago)

I didn't do a deep dive (sample size of 1 for each), but the push-to-cachix phase of the successes and failures did seem to differ a good bit:
- clean https://github.com/NixOS/nix/runs/4695172775?check_suite_focus=true#step:11:4
- 404 https://github.com/NixOS/nix/runs/4703599948?check_suite_focus=true#step:11:4
- hash mismatch https://github.com/NixOS/nix/runs/4553572870?check_suite_focus=true#step:11:4

cc @domenkozar

**Comment by domenkozar** [comment]
I will take a look tomorrow, thanks for the investigation!

**Comment by abathur** [comment]
I think this still exists. The CI runs I linked have had their logs garbage collected, but I still see:
- hash collisions as recent as today and yesterday:  https://github.com/NixOS/nix/runs/5833702806?check_suite_focus=true#step:4:89 https://github.com/NixOS/nix/runs/5819222632?check_suite_focus=true#step:4:91
- a 404 as recent as this run 5d ago: https://github.com/NixOS/nix/runs/5768394652?check_suite_focus=true#step:4:328

**Comment by edolstra** [comment]
The hash mismatch is also due to a 404. E.g. in https://github.com/NixOS/nix/runs/5833702806?check_suite_focus=true#step:4:89, downloading https://nixos-nix-install-tests.cachix.org/serve/pp6vry7kd9mjz5w873q1hri6qwla3kvv/nix-2.8.0pre20220405_f98d76f-x86_64-linux.tar.xz returns `404 - Not Found` which does have the reported hash (2d857a3660e0240bac3ae9f98e2287f46eb6aebf724775fe130af2a6c7dfc3c4). We should use `curl --fail`...
