### ISSUE TITLE
document primops scoping

### ISSUE THREAD

**Issue by fogti** [NixOS/nix#5889]
**Is your feature request related to a problem? Please describe.**
Certain `builtins` like `toString`, `import`, `map` and such are available in the global scope, while others like `listToAttrs` are only available by accessing via `builtins.`.

[afaik List via sterni](https://tpaste.us/41nr)

**Describe the solution you'd like**
Which are available via which way should be documented.

**Describe alternatives you've considered**
None.

**Additional context**
Noticed as part of participation in Nix rewrite efforts (e.g. https://riir-nix.github.io/, Tvix, etc.)

**Comment by zseri** [comment]
afaik still relevant.

**Comment by oxalica** [comment]
Same as #7290 I think?

**Comment by zseri** [comment]
yes

**Comment by fricklerhandwerk** [comment]
Closing this in favor of #7290
