### ISSUE TITLE
Add additional prefix to version parser

### ISSUE THREAD

**Issue by jagajaga** [NixOS/nix#589]
Hello! Is there a way to add to `nix` additional parser like we have today for `pre` in a version part of a name of pkg?
Indeed it's going to be great to add prefix `git`, because we have lot's of pkg with that.

**Comment by edolstra** [comment]
Any reason why those packages can't use the `-pre` convention?

**Comment by jagajaga** [comment]
There are no reasons but "`pre` what"? :) If pkg is not going to have a release it's a little bit confusing moment, no?

**Comment by edolstra** [comment]
What exactly are you asking for? What should Nix do with a Git commit hash in a version string? Those should be avoided in any case because they can't be compared (Nix won't be able to tell if a commit hash is older or newer than another hash).

**Comment by jagajaga** [comment]
I'm asking just for a word `git`. We now have names like `foobar-git-2015-05-19`. So I'm asking for a parcer that can omit the word `git`. Because now `foobar` and `foobar-git` are different pkgs.

**Comment by edolstra** [comment]
Why not just call it `foobar-20150519`? There's no need to bother the user with what version control system the package happens to use.

**Comment by jagajaga** [comment]
@edolstra you are right. Thank you.
