### ISSUE TITLE
nix-store manual: `--indirect` not documented

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nix#5891]
The `--indirect` flag was documented before, it is not anymore.

**Comment by edolstra** [comment]
This is because it no longer does anything, see 00d25e84577659ccf0bc360c61c47b6cd25d1c26.

**Comment by Profpatsch** [comment]
That’s cool, but I think it’s missing from the release notes. Was that for 2.4 or 2.5?

**Comment by edolstra** [comment]
That was in 2.4.
