### ISSUE TITLE
docker: add git to the nix image

### ISSUE THREAD

**Issue by Fuuzetsu** [NixOS/nix#5896]
This is just the same as https://github.com/NixOS/docker/issues/33 ; notably this was finally added in the original repository but was then subsequently lost again when that was made deprecated.

**Comment by Yajo** [comment]
I'm using the workaround of executing this before any other nix command:

```sh
nix-channel --add https://nixos.org/channels/nixos-21.11 nixpkgs # optional; only if you don't want nixpkgs-unstable as it comes by default
nix-channel --update
nix-env -iA nixpkgs.git
```

**Comment by Fuuzetsu** [comment]
This workaround works but adds 30 seconds to every run.
