### ISSUE TITLE
Command to update selected flake inputs without any other change

### ISSUE THREAD

**Issue by lilyball** [NixOS/nix#5901]
**Is your feature request related to a problem? Please describe.**
If I have multiple flake inputs but don't want to update them all, it's a bit confusing as to how to do that. The answer right now is "use the `--update-input` flag to any nix command that operates on flakes", but this requires using some command to do it. The obvious answer is "use `nix flake update`", but this is the only command that actually cannot do this as it updates all of the inputs.

The use-case here is when I want to update one or more inputs without e.g. building, because I need to update my local flake for the changes too. I can currently say something like `nix flake metadata --update-input home-manager` but that produces unwanted noise when all I actually want to see is the info on the updated input.

**Describe the solution you'd like**
I want to be able to say something like `nix flake update . home-manager` to mean "only update the `home-manager` input", or `nix flake update . home-manager nixpkgs` to mean "update both `home-manager` and `nixpkgs` but nothing else".

**Describe alternatives you've considered**
This could also be a flag like `nix flake update --only home-manager`, but that makes it more awkward to list multiple inputs.

**Comment by bew** [comment]
Duplicate of https://github.com/NixOS/nix/issues/5110 ?

**Comment by lilyball** [comment]
Looks like yes, I missed seeing that before, thanks.
