### ISSUE TITLE
nix-env should do best effort to evaluate rather than failing

### ISSUE THREAD

**Issue by fzakaria** [NixOS/nix#5921]
**Describe the bug**
I am seeing that `nix-env` is failing to completely evaluate `nixpkgs` when given `--json --out-path` due to `NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1`

You should be able to evaluate the whole `nixpkgs` or at least give a flag to `nix-env` to allow it to "best-effort" continue evaluation.

**Steps To Reproduce**

```
❯ NIXPKGS_ALLOW_BROKEN=1 NIXPKGS_ALLOW_INSECURE=1 NIXPKGS_ALLOW_UNFREE=1 ./nix/result/bin/nix-env -qaP --json --out-path > /tmp/out
warning: name collision in input Nix expressions, skipping '/home/fzakaria/.nix-defexpr/channels_root/nixpkgs'
error: Package ‘linux-4.14.165-172’ in /nix/store/gjjzmwrj1irv4hh1dv8l0c9iz4a3pbr0-nixpkgs-21.11pre332093.7fad01d9d5a/nixpkgs/pkgs/os-specific/linux/kernel/linux-hardkernel-4.14.nix:4 is not supported on ‘x86_64-linux’, refusing to evaluate.

       a) To temporarily allow packages that are unsupported for this system, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnsupportedSystem = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnsupportedSystem = true; }
       to ~/.config/nixpkgs/config.nix.
(use '--show-trace' to show detailed location information)

```

**NOTE:** Adding `NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1` does not help because then you get stuck at an assert
```
❯ NIXPKGS_ALLOW_BROKEN=1 NIXPKGS_ALLOW_INSECURE=1 NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1 NIXPKGS_ALLOW_UNFREE=1 ./nix/result/bin/nix-env -qaP --json --out-path > /tmp/out
warning: name collision in input Nix expressions, skipping '/home/fzakaria/.nix-defexpr/channels_root/nixpkgs'
error: assertion '((stdenv).targetPlatform != (stdenv).hostPlatform)' failed

       at /nix/store/gjjzmwrj1irv4hh1dv8l0c9iz4a3pbr0-nixpkgs-21.11pre332093.7fad01d9d5a/nixpkgs/pkgs/top-level/all-packages.nix:11663:25:

        11662|   # built with, and use, that cross-compiled libc.
        11663|   gccCrossStageStatic = assert stdenv.targetPlatform != stdenv.hostPlatform; let
             |                         ^
        11664|     libcCross1 = binutilsNoLibc.libc;
(use '--show-trace' to show detailed location information)
```

**Expected behavior**

I would expect to generate as much JSON as possible for everything that can evaluate.

**`nix-env --version` output**

```
nix-env --version
nix-env (Nix) 2.6.0pre20220114_34f2eeb
```

**Comment by fzakaria** [comment]
If someone points me to where I may try and add a `try/catch` to swallow these errors during evaluation, I can work on a PR to contribute a flag to suppress failures.

**Comment by fzakaria** [comment]
To be honest, I don't even know why the system itself matters for evaluation of the out-path.

`nix-env` is doing equivalent of a dry-run here in calculating all the attributes; I would expect that to work irrespective of the platform. Nevertheless having a way to trample over failures may be useful.

**Comment by sternenseemann** [comment]
This is a regression, works with 2.3.16 at least.

**Comment by fzakaria** [comment]
Previous versions didn't include the output path that has a relatively new
addition to the JSON.

It could be related to that.

**Comment by sternenseemann** [comment]
Seems like it. `nix-env` already has a mechanism of skipping the failing entries for the non-JSON output which should be ported to the JSON output then.

**Comment by fzakaria** [comment]
I am not at my laptop right now, but if you throw me a hyperlink to the
source file with the example I can port it over in a PR 🙇‍♂️

**Comment by edolstra** [comment]
In fact it's also broken without the `--json` flag. Marking this as a critical regression.
