### ISSUE TITLE
Re-binding variables appears broken in REPL

### ISSUE THREAD

**Issue by pveierland** [NixOS/nix#5925]
**Describe the bug**

Binding to an already bound variable within `nix repl` does not appear to work.

**Steps To Reproduce**

```
> nix repl
Welcome to Nix 2.5.0pre20211206_d1aaa7e. Type :? for help.
nix-repl> a=1
nix-repl> a=2
nix-repl> a
1
```

**Expected behavior**

```
> nix repl
Welcome to Nix 2.5.0pre20211206_d1aaa7e. Type :? for help.
nix-repl> a=1
nix-repl> a=2
nix-repl> a
2
```

**`nix-env --version` output**

`nix-env (Nix) 2.5.0pre20211206_d1aaa7e`

**Comment by thufschmitt** [comment]
Should be fixed by https://github.com/NixOS/nix/pull/5752 . Can you try with a newer commit see whether you still experience the bug

**Comment by pveierland** [comment]
Thank you - I should have checked that first. Confirmed now that the issue is fixed:

```
Welcome to Nix 2.6.0pre20220114_34f2eeb. Type :? for help.
nix-repl> a=1
nix-repl> a=2
nix-repl> a
2
```
