### ISSUE TITLE
Can't build latest master

### ISSUE THREAD

**Issue by miuirussia** [NixOS/nix#5933]
Commit fc2443a67caa139fdfb0fa0fccf3d777d736ffe9 not building on macOS 12.1:

```
error: output '/nix/store/68gji95zdmgsfl2qi4hzvhvc53n9bjjb-nix-2.6.0pre20220117_fc2443a' is not allowed to refer to the following paths:
/nix/store/k65kkdxs8d87y3sipsvq711ayxb8xfv8-boost-1.77.0
```

**Comment by thufschmitt** [comment]
Strange. The error is from https://github.com/NixOS/nix/pull/5915 , but I don’t see what can have re-introduced the reference in the meantime. Maybe there’s some non-determinism playing, but that would be very surprising (and sad)

**Comment by miuirussia** [comment]
Changed nixpkgs from latest nixpkgs-unstable variant to nix's flake and it builded
