### ISSUE TITLE
Expose the daemon's version over the API

### ISSUE THREAD

**Issue by grahamc** [NixOS/nix#5952]
**Is your feature request related to a problem? Please describe.**

When looking at a machine running Nix I'd like to know what version of the daemon is running without having to spelunk.

**Describe the solution you'd like**

I'd like to be able to run `nix daemon-version` or something like that and get back the version of the daemon. Maybe some additional data, too, like key configuration options (sandbox, multi user, etc.)

**Describe alternatives you've considered**

Right now it is a bit of a nightmare. `pgrep -af`, `$(systemctl show nix-daemon.service|grep ExecStart=|grep -Po "(?<=path=).*?(?= )") --version`, other options. It is really frustrating to ask users to do these hacky things.

**Additional context**
I want to make this bug report template easy to fill out, and generally make it easy to support people using Nix: https://github.com/NixOS/hydra/pull/1127/files/46b8f7cce82c4bdc94491c58003eb487a83654c3#diff-185833cb26d7ac66a4d39042fd576a820c2c2c6d05ad18973bb9c7dce77267c5R26

**Comment by thufschmitt** [comment]
Yeah, that sounds sensible. Maybe `nix store ping` could print some informations with `-v` (or `--json`). Something like

```console
$ NIX_REMOTE=daemon nix store ping -v
type: daemon
version: 2.5.0
url: daemon
$ NIX_REMOTE=local nix store ping -v
type: local
version: 2.5.0
url: local
$ NIX_REMOTE=https://cache.nixos.org nix store ping -v
type: Http binary cache
url: https://cache.nixos.org
```
