### ISSUE TITLE
Improve logging when running fetchUrl

### ISSUE THREAD

**Issue by busti** [NixOS/nix#5968]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when ... rebuilding my system causes a download of a large file from an external source. 
The main candidate for me is usually any JetBrains IDE because I add some custom packages to their paths. This usually results in the following terminal output:  
![image](https://user-images.githubusercontent.com/3575167/150706369-a8c33e24-367b-48ae-b349-a946a6e20b0f.png)

As the time of writing this, I have been staring at this exact line for about 30 minutes without any indication of progress.  
I do not know if it failed, it might just be really slow. The problem is that I do not know how slow, if I knew I would probably get up to prepare some food, but it might finish every second, so I don't.  

**Describe the solution you'd like**
This looks very similar to the output of curl.  
When running in interactive mode, update the lowest line of this log to show progress. The current download bandwidth, remaining time, data already downloaded and whatnot updated every second or so would be really helpful. 
But heck, I'd be happy with any indication of progress at all. Even a dot added to the last line every minute or even a single line every five minutes.

**Describe alternatives you've considered**
Running curl manually and then adding the file to the store manually works, but it's equally frustrating.

**Comment by thufschmitt** [comment]
There’s actually several different `fetchurls`, but the one you’re referring to seems to be `nixpkgs.fetchurl`, which is a nixpkgs function. So maybe re-open this in [the nixpkgs issue tracker](https://github.com/nixos/nixpkgs/issues)
