### ISSUE TITLE
Support arbitrary fetching of files as Flake inputs

### ISSUE THREAD

**Issue by MatthewCroughan** [NixOS/nix#5979]
**Is your feature request related to a problem? Please describe.**
I want to make a flake that fetches people's keys from Github. It looks like this, but I cannot because fetching arbitrary files is not supported via flake inputs:
```nix
{
  inputs.matthewcroughanKeys = {
    url = "https://github.com/matthewcroughan.keys";
    flake = false;
  };
  outputs = { self, matthewcroughanKeys }: {
    myKey = matthewcroughanKeys.outPath;
  };
}
```

**Describe the solution you'd like**
I want flake inputs to support fetching arbitrary files and locking their hash in the `flake.lock`

**Describe alternatives you've considered**
Using a sha256 rather than `nix flake update` to manually fetch keys, maintaining a long list of sha256s for each person. Or aggregating the hashes of many keys in a set of fetchurl calls.

**Additional context**
https://discourse.nixos.org/t/fetching-ssh-public-keys/12076

**Comment by tomberek** [comment]
Other use cases:
- fetch a patch and locking it automatically in a TOFU way via flake.lock
- fetch a remote resource and purposefully error out if it changes

One can currently point to a local path using `path:./somefile` so being unable to do this for remote seems to be an accidental restriction. Ugly hack: https://github.com/tomberek/system-arg/blob/master/systemFile/flake.nix#L4  (my intention is not specifically about the system parameter, but it is an example)

**Comment by tomberek** [comment]
This seems to be working: https://github.com/tomberek/nix/tree/fetcher_url It should behave the same as the tarball fetcher, but with opposite boolean logic:

> In URL form, the schema must be http://, https:// or file:// URLs and the extension must NOT be .zip, .tar, .tar.gz, .tar.xz, .tar.bz2 or .tar.zst.

**Comment by Kranzes** [comment]
When fetching keys from github, won't the hash change each time a key is added/removed, since it doesn't have a commit/rev?

**Comment by tomberek** [comment]
> When fetching keys from github, won't the hash change each time a key is added/removed, since it doesn't have a commit/rev?

That particular example will have that annoyance, so it may not be the best use-case or motivating example. But generally being able to fetch a file instead of only trees is potentially useful.

**Comment by Kranzes** [comment]
I agree, I am currently doing [this](https://github.com/Kranzes/robotnix-personal/blob/64e60ed0339495380c5d662ec587d535a9a45e15/flake.nix#L42), which I'd rather not do to *just* fetch the hosts file.

**Comment by nmattia** [comment]
Another use case (where the file won't change) is fecthing a single file from a big repo (for instance the [`git-completion.bash` file](https://github.com/git/git/blob/e6ebfd0e8cbbd10878070c8a356b5ad1b3ca464e/contrib/completion/git-completion.bash) from the git repo).

**Comment by tgunnoe** [comment]
I had to work around this issue, so I think it would be useful.  In my case, `https://github.com/ethereum/solc-bin/` tracks binaries of 4gb+ total for repo size, but I only needed a few of them totaling in size of 80mb or so.  (Who in the world puts binaries in git anyways?!?) It happens.

**Comment by drupol** [comment]
Just for the record, I succeeded to download one single file from Github through a Nix flake inputs, see this commit: https://github.com/loophp/nix-phpstan/commit/c3cf779d5f2b32310eac339413d9337cccf78315

**Comment by MatthewCroughan** [comment]
@drupol Yes, this issue is closed by https://github.com/NixOS/nix/pull/6548 by the looks of it.
