### ISSUE TITLE
Conflicts with system provided nlohman-json

### ISSUE THREAD

**Issue by grawlinson** [NixOS/nix#5981]
**Describe the bug**

Nix 2.6 has a couple of files that conflict with system provided nlohman-json, which will cause issues with every Linux distribution.

This was introduced in this [PR](https://github.com/NixOS/nix/pull/5536) and this [commit](https://github.com/NixOS/nix/commit/307977963ca953ad11003bcd4c95f7d2308012f1).

**Steps To Reproduce**

Attempt to install Nix 2.6 and any distribution provided nlohman-json.

**Expected behavior**

A better solution.

**Additional context**

This breaks any addition of Nix 2.6+ to any Linux distribution.

**Comment by edolstra** [comment]
What does it break exactly? As long as you don't add the Nix headers to your compiler search path, I don't see how it breaks anything.

**Comment by grawlinson** [comment]
It installs the headers in the exact same location as system provided packages do, causing a file conflict.

**Comment by roberth** [comment]
We could either stop vendoring it, or move the header files so they can't collide; perhaps to `<nix/nlohmann/json_fwd.hpp>`.

What was the reason for vendoring? I could[n't](https://github.com/NixOS/nix/pull/4691#issuecomment-813586728) find it.

I'm happy with either solution as long as I can include the correct json header versions in my Haskell bindings.

**Comment by edolstra** [comment]
> It installs the headers in the exact same location as system provided packages do, causing a file conflict.

How did you install Nix? I don't think our installer installs header files in any system locations.

**Comment by grawlinson** [comment]
I'm one of the package maintainers for Nix in Arch Linux, and the header files popped up while testing this version.

**Comment by alerque** [comment]
(Arch Linux package co-maintainer here).

The offending files are turning up when running `make install`. This is installing two files that do not belong being placed by nix. If you guys want to vendor some files that's fine, but at least put them in some namespace that won't create obvious conflicts with system provided files.

```
/usr/include/nlohmann/json.hpp
/usr/include/nlohmann/json.hpp
```

These two files need to be not installed by nix's install process, they will conflict with any system that happens to have nlohmann-json installed.
