### ISSUE TITLE
Interrupting Nix during a download causes it to hang

### ISSUE THREAD

**Issue by thufschmitt** [NixOS/nix#5985]
**Describe the bug**

If Nix gets interrupted while something is being downloaded, it will output `error (ignored): basic_string::_M_construct null not valid` and hang until SIGKILL-ed.

**Steps To Reproduce**

```console
$ nix build nixpkgs\#firefox --store $PWD&
$ sleep 2 # Just to make sure that it’s properly started
$ kill %nix
error (ignored): basic_string::_M_construct null not valid
# Nix is now stuck until
$ kill -9 %nix
```

**Expected behavior**

Should properly stop

**`nix-env --version` output**

```console
$ nix-env --version 
nix-env (Nix) 2.6.0
```

**Additional context**

Wasn’t present on `2.6.0pre20211214_18e4851` (but I didn’t bisect it any further)

**Comment by aakropotkin** [comment]
Encountered this yesterday on a "fresh" RHEL 7.4 VM.
As a temporary workaround we just cleared substitutors ( in `~/.config/nix/nix.conf` ); but obviously this means "building the world" which is painful.

**Comment by DavHau** [comment]
Running into this issue constantly on nix 2.6.0.
Restarting the nix-daemon does not help. But this does:
`pgrep nix | sudo xargs kill -9`

**Comment by aakropotkin** [comment]
> Running into this issue constantly on nix 2.6.0. Restarting the nix-daemon does not help. But this does: `pgrep nix | sudo xargs kill -9`

Out of curiosity what's your system info?

I want to narrow down to see if this bug effects all systems, or if it's those with "older" builds of `libstdc++` which pre-date C++ ABI 11 ( basically anything built on GCC 4.x or earlier ).

**Comment by SuperSandro2000** [comment]
> Restarting the nix-daemon

see https://github.com/NixOS/nix/pull/6008 for details

> I want to narrow down to see if this bug effects all systems, or if it's those with "older" builds of libstdc++ which pre-date C++ ABI 11 ( basically anything built on GCC 4.x or earlier ).

Nix should always be build against the gcc in nixpkgs.

**Comment by aakropotkin** [comment]
While this is true; if the user has for example 
LD_LIBRARY_PATH="/usr/lib64:/usr/lib:/etc/profiles/per-user/$USER/lib" ( 
this obviously is poor profile management, but it happens a lot in the 
wild ) then `/usr/lib64/libstdc++.so.6' will be loaded instead of the 
`libstdc++.so.6' intended by the `nix' binary's `RUNPATH' entry.

On older systems which have builds of `libstdc++.so.6' which were built 
using GCC <= 4.x, you will encounter C++ ABI 11 conflicts with a number 
of C++ STL objects - critically `std::string' vs. `std::basic_string'. 
It's uncommon for this to really be an issue unless someone passes 
`std::string foo( "hi" ); void * rsl = external_library_call( (void *) 
foo ); std::string bar = (std::string) rsl;' which is definitely rare.

Rereading the error message again though I think it's just that someone 
tried to construct an empty string in a way that might upset GNU Unique 
Object allocations.

I've been dealing with this category of issue a lot at work recently so 
I might just be projecting onto Nix when it's unwarranted though. But if 
we did find that this bug only shows up with older `libstdc++.so.6' 
linking then it might be worth looking into. There's a few spots in 
`nix/src/libstore/' that play with `void *' and `std::string' quite a 
bit, but I didn't dig enough to find a specific spot that might cause 
issues.

**Comment by SuperSandro2000** [comment]
@aakropotkin I don't think this can be the case because nix-daemon does not link against `libstdc++.so.6` but the full path in the nix store. 

You can do it the other way around. For example apt can be tricked into loading libstdc++.so.6 from nix:

```ShellSession
$ LD_LIBRARY_PATH=/nix/store/x17b1wq871r4ycrxyy1n85ja09dxq3ih-gcc-10.3.0-lib/lib ldd /usr/bin/apt
/usr/bin/apt: /nix/store/x17b1wq871r4ycrxyy1n85ja09dxq3ih-gcc-10.3.0-lib/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libapt-private.so.0.0)
/usr/bin/apt: /nix/store/x17b1wq871r4ycrxyy1n85ja09dxq3ih-gcc-10.3.0-lib/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libapt-pkg.so.6.0)
        linux-vdso.so.1 (0x00007fff6d552000)
        libapt-private.so.0.0 => /lib/x86_64-linux-gnu/libapt-private.so.0.0 (0x00007a9696f6b000)
        libapt-pkg.so.6.0 => /lib/x86_64-linux-gnu/libapt-pkg.so.6.0 (0x00007a9696dad000)
        libstdc++.so.6 => /nix/store/x17b1wq871r4ycrxyy1n85ja09dxq3ih-gcc-10.3.0-lib/lib/libstdc++.so.6 (0x00007a9696bd8000)
        libgcc_s.so.1 => /nix/store/x17b1wq871r4ycrxyy1n85ja09dxq3ih-gcc-10.3.0-lib/lib/libgcc_s.so.1 (0x00007a9696bbe000)
....
        libcap.so.2 => /lib/x86_64-linux-gnu/libcap.so.2 (0x00007a969653c000)
        libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007a9696512000)
```

```ShellSession
$ LD_LIBRARY_PATH=/usr/lib64:/usr/lib:/nix/store/x17b1wq871r4ycrxyy1n85ja09dxq3ih-gcc-10.3.0-lib/lib ldd ~/.nix-profile/bin/nix-daemon
        linux-vdso.so.1 (0x00007fff9d5fb000)
        libsodium.so.23 => /nix/store/wz576i102yj4qrhlyda3nyxlad8b8s5m-libsodium-1.0.18/lib/libsodium.so.23 (0x000075e4504ab000)
....
        libnixcmd.so => /nix/store/8xvmp3j8nmh1i9qab27js1j21yyk2m73-nix-2.7pre20220127_558c4ee/lib/libnixcmd.so (0x000075e44f891000)
        libstdc++.so.6 => /nix/store/x17b1wq871r4ycrxyy1n85ja09dxq3ih-gcc-10.3.0-lib/lib/libstdc++.so.6 (0x000075e44f6bc000)
        libm.so.6 => /nix/store/jcb7fny2k03pfbdqk1hcnh12bxgax6vf-glibc-2.33-108/lib/libm.so.6 (0x000075e44f57b000)
....
        libresolv.so.2 => /nix/store/jcb7fny2k03pfbdqk1hcnh12bxgax6vf-glibc-2.33-108/lib/libresolv.so.2 (0x000075e44de5b000)
        libattr.so.1 => /nix/store/r6890i9cglxmjh4iwjwvpr84bxjkba5a-attr-2.5.1/lib/libattr.so.1 (0x000075e44de53000)
```

**Comment by aakropotkin** [comment]
Good catch. In this case it seems like it's really the symbol versions 
against `GLIBCXX_*' that likely protect Nix from accidentally loading 
`libstdc++.so.6' with builds that predate GCC's Dual ABI support for 
C++11 ABI. In retrospect my concerns about Dual ABI issues are from 
experiences with much older binary distributions of `nix' which sat in 
that nasty grey area of `libstdc++.so.6' versioning where symbol 
versioning would only protect you if you used a smaller selection of 
interfaces.

Well I guess we can rule out that theory. My next guess is going to be a 
run of the mill "un-handled `nullptr' edge case" with `std::string' 
objects, likely surrounding the `libstore' migration towards 
`std::string_view'. Whats strange to me though is that I would expect 
reports of this bug to be widespread in that case. My usual hunch for 
popular tools like this is that C++ STL crashes that sneak past 
test-suites into releases are generally nasty ABI issues that only occur 
on older `libstdc++' builds; but maybe there's another interaction 
causing this. Possibly an authorization issue trying to fetch the binary 
cache that doesn't get caught? In my case the crash occurred on RHEL VMs 
in a VPN with untold network security at play. I haven't tried to 
reproduce it on any other machine yet.
