### ISSUE TITLE
Document `nixConfig` attribute in `flake.nix`

### ISSUE THREAD

**Issue by lilyball** [NixOS/nix#5988]
**Describe the bug**

Nix flakes [support a `nixConfig` attribute](https://github.com/NixOS/nix/pull/4189) but this is not documented anywhere. The only references in the manual I can find at the moment are a brief mention in [nix develop](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-develop.html?highlight=nixConfig#description) and a mention in the [Nix 2.6 release notes](https://nixos.org/manual/nix/stable/release-notes/rl-2.6.html?highlight=nixConfig#release-26-2022-01-24), but neither reference explains what it is.

This should be documented in `nix help flake`.

**Nix version**

Tested locally with Nix 2.5.1 using `nix help flake`, and the manual links above were checked with Nix 2.6.0.

**Comment by con-f-use** [comment]
Sorry for the necro. Just as a small remark,  maybe the allowed options for `nixConfig` should also be marked somehow in the [documentation of `nix.conf`](https://nixos.org/manual/nix/stable/command-ref/conf-file.html).

**Comment by eclairevoyant** [comment]
@con-f-use nixConfig is documented here: https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-flake.html#flake-format

**Comment by con-f-use** [comment]
Yes, I know, what I meant is maybe these 

 - [bash-prompt](https://nixos.org/manual/nix/stable/command-ref/conf-file.html#conf-bash-prompt)
 - [bash-prompt-prefix](https://nixos.org/manual/nix/stable/command-ref/conf-file.html#conf-bash-prompt-prefix)
 -  [bash-prompt-suffix](https://nixos.org/manual/nix/stable/command-ref/conf-file.html#conf-bash-prompt-suffix)
 -  [flake-registry](https://nixos.org/manual/nix/stable/command-ref/conf-file.html#conf-flake-registry)
 -  [commit-lockfile-summary](https://nixos.org/manual/nix/stable/command-ref/conf-file.html#conf-commit-lockfile-summary)
 
 Mentioned in the [flake page](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-flake.html#flake-format), should also be mentioned as being automatically allowed with flakes on the [nix.conf doc page](https://nixos.org/manual/nix/stable/command-ref/conf-file.html)
