### ISSUE TITLE
How to build a variant of a package

### ISSUE THREAD

**Issue by hotpxl** [NixOS/nix#600]
Hi,

I want to build Emacs using nix. Often there is a GTK version and a QT version of Emacs. How can I specify the variant I want to install? Is there any way I can inspect the variant I'm using after I installed it?

**Comment by vcunat** [comment]
There's nothing in nix itself. Some packages expose variants in some ways (in nixpkgs), e.g. the `emacs24` attribute has parameters `withGTK2`, `withGTK3` etc. with some defaults. Sometimes there are also special reconfigured attributes, e.g. `emacs24-nox` in this case. Some packages even reflect that in the actual resulting package name.

**Comment by hotpxl** [comment]
So how can I modify the parameters like `withGTK3` when installing? Also for the attribute, I can't find the `emacs24-nox` package? Is it in channel nixpkgs?

**Comment by joachifm** [comment]
@hotpxl, see https://nixos.org/nixos/manual/sec-package-management.html#sec-customising-packages

**Comment by vcunat** [comment]
By coincidence, there's the emacs example, but that particular one is outdated and won't work (on today's master at least).

**Comment by hotpxl** [comment]
Thanks. I customized my Emacs. For anyone looking into this post, I edited `.nixpkgs/config.nix` file much like what [this post](https://nixos.org/wiki/How_to_install_nix_in_home_(on_another_distribution)#Installing_Nix) did.
