### ISSUE TITLE
regression: string handling bug triggered via `nix profile remove`

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nix#6017]
**Describe the bug**

The bug I'm encountering is that presently when I run `nix profile remove` on anything (including items not installed), I get the following error: 

```
error: getting status of '/nix/store/2jq0a1260qidl0qf8f1rcshny2wc79rh-libreoffice-7.2.5.2/shareicons': No such file or directory
```

Of course this file does not actually exist, although there is a `/...-7.2.5.2/share/icons` (slash between).

I have an strace of what happens during this if that's useful (I thought maybe it was something weird following a bad link or something...).  Valgrind seems clear, just usual Nix stuff :).  It does follow a link from `/nix/store/j56jnpmqrlxky4g89v1n636cqlgq10nb-libreoffice-7.2.5.2/share` to `/nix/store/2jq0a1260qidl0qf8f1rcshny2wc79rh-libreoffice-7.2.5.2` or so, if that helps figure out where this is going wrong.

I noticed v2.5.1 doesn't have this problem, so used `git bisect run` to figure out when this started occurring with this little script: 
```shell
#!/bin/sh

set -e

rm asdf  || true
nix-build -o asdf

./asdf/bin/nix profile remove nopers
```

Which points to 44c92a1667ce829518178a77a9de0a53609d284f as 'the first bad commit' (which given the nature of what it changes, seems not unlikely :)).

**Steps To Reproduce**

Installing the package in question into a test profile (hence #6016, sorry) doesn't seem to trigger the issue.

So, unfortunately I'm not sure how to reproduce this at the moment.

Happy to help test things if that's useful, of course :+1: .

**Expected behavior**

`nix profile remove` doesn't error out on a non-existent file :).

**`nix-env --version` output**

`nix-env (Nix) 2.7.0pre20220124_0a70b37`

**Comment by dtzWill** [comment]
(cc @pennae)

**Comment by pennae** [comment]
looks like the `+ 1` in https://github.com/NixOS/nix/commit/44c92a1667ce829518178a77a9de0a53609d284f#diff-af80a21f1b9aa83aff38aa57e13dfd46b073b1efe80409fdd094bb73270fd52aR150 is wrong, the old code would have the path remainder start with a `/` where the now one deletes that `/` by taking the substring starting one later. can't make a PR right now but maybe you can confirm this helps?

**Comment by dtzWill** [comment]
Oh good! That was what I suspected as well, I'll test it in a few (out on an errand currently :)).  I'll make a PR if it helps, thanks!

**Comment by andersk** [comment]
Simple reproduction recipe:

```console
$ docker run --rm -it nixos/nix:2.6.0
bash-4.4# nix-env -i -E 'f: with f.nixpkgs {}; buildEnv { name="my-env"; paths=[bison]; }'
[…]
building '/nix/store/yxv9nwrrlrg77i5g3g61xcj835cgb20y-my-env.drv'...
created 3 symlinks in user environment
building '/nix/store/2d9w0mh8mw0ba6mgq0h0627al7wnclbp-user-environment.drv'...
error: getting status of '/nix/store/3hi4ybpvmvpynm55wn78n6056kf26wsb-bison-3.7.6/sharelocale': No such file or directory
error: builder for '/nix/store/2d9w0mh8mw0ba6mgq0h0627al7wnclbp-user-environment.drv' failed with exit code 1
```
