### ISSUE TITLE
Alsamixer not working in nixos-unstable

### ISSUE THREAD

**Issue by engblom** [NixOS/nix#6023]
Some recent changes broke alsamixer in nixos-unstable:

$ alsamixer 
ALSA lib control.c:1464:(snd_ctl_open_conf) Unknown field libs
cannot open mixer: Invalid argument

**`nix-env --version` output**

nix-env (Nix) 2.5.1

**Comment by cole-h** [comment]
This doesn't seem related to the Nix package manager itself (what this repository is used for) and more with the way its packaged -- would you mind reporting this to https://github.com/NixOS/nixpkgs/issues instead?

**Comment by engblom** [comment]
The bug is now reported at the right place.

**Comment by SrTobi** [comment]
For everyone who found this, the new issue is here: https://github.com/NixOS/nixpkgs/issues/157442
