### ISSUE TITLE
Add "-h" as a shorthand flag for "--help" to cli tools

### ISSUE THREAD

**Issue by Moredread** [NixOS/nix#6024]
**Is your feature request related to a problem? Please describe.**
"nix" and other CLI tools don't have the "-h" shorthand alias for "--help". This trips me up more often than I like to admit. :)

I think this hints to a possible pain point esp. for new users that trying to learn to work with the CLI tools.

**Describe the solution you'd like**

Add "-h" as a shorthand alias to all tools where it is not used yet.

An alternative or additional feature would be to print the help or a shorter version with just subcommands if tools are called without any flags or subcommands, similarly as what "restic" does, e.g.

```
# nix run 'nixpkgs#restic'

restic is a backup program which allows saving multiple revisions of files and
directories in an encrypted repository stored on different backends.

Usage:
  restic [command]

Available Commands:
  backup        Create a new backup of files and/or directories
  cache         Operate on local cache directories
(...)
```

**Comment by Kha** [comment]
See https://github.com/NixOS/nix/pull/3760
