### ISSUE TITLE
nix search does not show Node packages

### ISSUE THREAD

**Issue by AmeerTaweel** [NixOS/nix#6030]
**Description**

Running `nix search nixpkgs QUERY` does not show Node packages. However, they show up on the [package search web tool](https://search.nixos.org/packages).

**Steps To Reproduce**

1. Go to [package search web tool](https://search.nixos.org/packages).
2. Search for `vue-language-server`. (Any Node package will do the job, but let's use this as an example)
3. You will find the packages `nodePackages.vue-language-server` and `nodePackages_latest.vue-language-server`.
4. Run `nix search nixpkgs vue-language-server` in your terminal.
5. You will **NOT** find the packages `nodePackages.vue-language-server` and `nodePackages_latest.vue-language-server`.

**Expected behavior**

When running `nix search nixpkgs vue-language-server`, I should find `nodePackages.vue-language-server` and `nodePackages_latest.vue-language-server`. This would change for different queries, but the idea is that I should see the Node packages in my search results in the command line.

**`nix-env --version` output**

`nix-env (Nix) 2.7.0pre20220124_0a70b37`

**Comment by matthewbauer** [comment]
It's not ideal, but if you know it's a node package, you can do:

```
nix search nixpkgs#nodePackages vue-language-server

**Comment by SuperSandro2000** [comment]
This is the wrong repo for this. The problem is likely https://github.com/NixOS/nixpkgs/commit/4c60ee3da1e3a9c2441ebeb1c755049555624924#diff-ab5748dc9567516fefba8344056b51ec1866adeace380f46e58a7af3d619ea22R7155.

**Comment by AmeerTaweel** [comment]
@SuperSandro2000 Thanks. I will open an issue there, and close this.
