### ISSUE TITLE
Consider enabling `auto-optimise-store = true` by default

### ISSUE THREAD

**Issue by trofi** [NixOS/nix#6033]
Are there any downsides in enabling `auto-optimise-store = true` by default?

If there are any subtleties is it worth adding a hint on them in `man nix.conf`?

**Comment by edolstra** [comment]
It was disabled in 6c4ac299173e3b9772c96bef1e6463b22dcd0227 because it caused too much I/O overhead. But it might be okay now.

**Comment by trofi** [comment]
Ah, the option trades writing a new directory to `/nix/store` versus adding new files (or modifying metadata) to `/nix/store/.links`.

It makes sense for the second to be a lot slower on filesystems that don't scale well to too many files (`ext3` used to behave poorly, don't know for others). For me the entries count is a 10x difference:

```
$ ls /nix/store/ | wc -l
287516
$ ls /nix/store/.links | wc -l
3929201
```

I'd say both numbers are too high :) Other filesystem-heavy applications like `git` and `ccache` use fixed depth trees to somewhat mitigate it. Even `/nix/var/log/nix/drvs` uses it.

Would it make sense to apply similar hack to `/nix/store/.links` and store links not as `/nix/store/.links/<hash>` but `/nix/store/.links/<ha>/<sh>`?

**Comment by edolstra** [comment]
> Would it make sense to apply similar hack to /nix/store/.links and store links not as /nix/store/.links/<hash> but /nix/store/.links/<ha>/<sh>?

Yes, but only if it's still useful on modern filesystems.

**Comment by rapenne-s** [comment]
> It was disabled in [6c4ac29](https://github.com/NixOS/nix/commit/6c4ac299173e3b9772c96bef1e6463b22dcd0227) because it caused too much I/O overhead. But it might be okay now.

The commit message about performance is vague. Do you remember how much slower it was? Is it common to run `nix-store --import` on regular basis?

I suggest turning on a setting that benefits 99% of users with a "normal" workflow makes more sense than disabling it by default because it reduces the speed of a niche use case.

What operations in the store would you recommend to measure I/O load of this setting for real world use case?

# Setup

I'm currently thinking at this procedure.

## Hardware

Using a regular 4 core system with a good amount of memory. Trying again with lower memory using `mem=2G` as a kernel parameter to limit the memory to 2 GB.

A disk/partition of 30 GB could be used, I don't see a point using a smaller disk. I don't think bigger disks would hit other issues. Maybe the test would deserve some time to try on multiple filesystems like xfs, ext4, btrfs, zfs

## Software

A network/disk cache filled with the packages that will be used in the benchmark must be prepared to not measure download latency.

Prepare a list of package to try.

## Procedure

1. Get a clean NixOS installation
2. Measure the time it takes for `nix-shell` for each package to get you to a working shell, this could be done using the delta between `date && nix-shell -p $package --run date`

**Comment by takeda** [comment]
Also before enabling it, this bug probably should be resolved: https://github.com/NixOS/nix/issues/7273

Not sure if it is OS X specific, but it is fairly consistent, I reinstalled Nix for second time and got the issue again.

**Comment by trofi** [comment]
Yeah. Another limitation I did not realize is `ext4` hardlink limit: it's `65000` which is not too much of file duplication for a builder machine.

**Comment by jmesmon** [comment]
> Yeah. Another limitation I did not realize is `ext4` hardlink limit: it's `65000` which is not too much of file duplication for a builder machine.

The ext4 hardlink limit should have been removed since the `dir_nlink` feature was added to ext4 back in 2008. Or do we require accurate hardlink numbers for some reason? (which would break using `dir_nlink`)

**Comment by trofi** [comment]
That's a good point. I only wrote it because somebody complained recently in matrix that optimizer failed for them due to exceeding link count. Perhaps it was and ext3?

**Comment by SuperSandro2000** [comment]
Wer shouldn't enable this by default since it slows down every build by a nine significant amount and names downloading from remote builders a lot slower.

**Comment by rapenne-s** [comment]
I agree, at least, a saner default would be to run it once in a while. NixOS has a setting for a systemd service doing this on a regular basis.

**Comment by mohe2015** [comment]
Was this ever done? I don't understand why this got closed. Is there a matching issue in nixpkgs that superseded this?

**Comment by rapenne-s** [comment]
No, it wasn't done. An issue with the auto optimise is that everytime nix builds something, it runs the optimisation, which takes a long time and lots of I/O. It's better to schedule it once a day/week but not for every change to the nix store

**Comment by trofi** [comment]
I closed it because there is no obvious consensus around everyone that it's an obviously correct thing to do (which was a big surprise to me).

**Comment by D3vil0p3r** [comment]
If the user implements:
```nix
nix.optimise.automatic = true;
```
at which time it runs the optimise?

And: if the user implements:
```nix
nix.optimise.automatic = true;
nix.optimise.dates = [ "03:45" ]; # Optional; allows customizing optimisation schedule
```
and the user computer is never up at 03:45, it means that the optimise is never run OR the optimise is run once the computer is again up?

**Comment by teohz** [comment]
@D3vil0p3r 
> If the user implements:
> 
> ```nix
> nix.optimise.automatic = true;
> ```
> 
> at which time it runs the optimise?
> 
> And: if the user implements:
> 
> ```nix
> nix.optimise.automatic = true;
> nix.optimise.dates = [ "03:45" ]; # Optional; allows customizing optimisation schedule
> ```
> 
> and the user computer is never up at 03:45, it means that the optimise is never run OR the optimise is run once the computer is again up?

Seems the default is **03:45**:
```
{
  options = {
    nix.optimise = {
      automatic = lib.mkOption {
        default = false;
<...cut/>
      dates = lib.mkOption {
        default = ["03:45"];
```
https://github.com/NixOS/nixpkgs/blob/592047fc9e4f7b74a4dc85d1b9f5243dfe4899e3/nixos/modules/services/misc/nix-optimise.nix

it uses systemd, so IIRC when pc is suspender the timer will run next time the is on:
_"Timers use the centralized systemd management services. If the system is off during the expected execution time, the timer is executed once the system is running again."_

**Comment by trofi** [comment]
At least `btrfs` does not implement online deduplication. That means it requires more disk space unless you run a dedupe all the time.

Offline deduplication requires external tools to do it with various caveats:
- keeping an index of blocks or files to deduplicate takes more storage (and/or IO)
- extent deduplication requires more disk space than a hard link and it takes more metadata to store
- extent deduplication on block level causes fragmentation
- defragmentation is tricky as it breaks sharing
- read-only mount of `/nix/store` is awkward to workaround for external deduper to run

These caveats could all be worked around given enough time and experience.

**Comment by xieve** [comment]
> `auto-optimise-store` is essentially superseded by filesystem deduplication (implemented for example in zfs ~and btrfs~). Enabling this option when filesystem deduplication is used would hurt performance for no benefit.

According to the ZFS manual, deduplication is a rather niche feature with heavy performance impact and very high RAM requirements. As such, I would disagree with this statement. 

Imo, periodic optimisation makes sense for machines with high uptime, such as servers, but not so much for desktops. On a desktop machine, I want to have control over such processes to execute them in appropriate situations. I think specifically for NixOS, it would make sense to run optimisation on system rebuild, but not other build processes. Does anyone have a solution for that?

**Comment by Malix-Labs** [comment]
Is `nix.optimise.automatic` set to `true` by default at least?

`auto-optimise-store = true` could lead to issue but I think `nix.optimise.automatic` not being set to `true` by default could cause more issue than on `false` by default

**Comment by MrQubo** [comment]
@xieve 

> I think specifically for NixOS, it would make sense to run optimisation on system rebuild, but not other build processes. Does anyone have a solution for that?

I think you can just run `nix-store --optimise` after the system rebuild? At least for local system rebuild.

**Comment by MrQubo** [comment]
Did someone made a comparison between nix's dedup and zfs dedup in terms of size redution and cpu/disk usage?

**Comment by griffi-gh** [comment]
would it be more reasonable to execute optimization in a detached process instead? so it doesn't slow down builds as much

**Comment by Malix-Labs** [comment]
also see [`nh clean`](https://github.com/nix-community/nh#nh-clean)
