### ISSUE TITLE
git+file flakes that are dirty don't provide any revision information

### ISSUE THREAD

**Issue by lilyball** [NixOS/nix#6034]
**Describe the bug**

If I load a `git+file://` flake and its worktree is clean, the resulting flake has revision information. But if the worktree is dirty then the resulting flake has no revision information at all. It still contains `narHash`/`lastModified`/`lastModifiedDate` which distinguishes it from a `path:` flake.

The problem is this doesn't give me much help if I build a configuration from a dirty tree and my resulting `config.systemConfiguration` property is now missing. I can't ask my system "what were you built from?" because it doesn't know.

One possible solution is to retain `rev` and `shortRev` and just tack on the string `"-dirty"` onto it. This would mean things like `system.configurationRevision = self.rev` would automatically pick this up, and NixOS's `system.nixos.versionSuffix` would end with something like `.af996ab-dirty` instead of just `.dirty`. This would be very convenient, though it's possible this might break some use-cases (e.g. trying to perform a git operation using `rev`).

Another solution is to replace `rev` and `shortRev` with `dirtyRev` and `dirtyShortRev` if the repo is dirty. This way I could write e.g. `system.configurationRevision = self.rev or "${self.dirtyRev}-dirty"`, and nixpkgs would also want to update its definition of `system.nixos.versionSuffix`.

**`nix --version` output**

nix (Nix) 2.5.1

**Comment by Enzime** [comment]
I implemented a PR #5385

**Comment by lilyball** [comment]
I'm closing this in favor of issue #4682, which is less opinionated but is already referenced by PR #5385.
