### ISSUE TITLE
nix 2.6 repl :a doesn't override bindings

### ISSUE THREAD

**Issue by pennae** [NixOS/nix#6041]
**Describe the bug**

```
:a { a = 1; }
:a { a = 2; }
a
```
produces different results between 2.5.1 and 2.6. 2.5.1 responds `2` (as we would expect), 2.6 responds `1`. seems this was introduced in https://github.com/NixOS/nix/pull/5835/commits/a4ab0a74d97c7c31df69f04870fa56cde89701a3 because `std::unique` keeps the *first* value of a run, but we want to keep the value with the greatest displacement.

this also affects `:l`:

```
Welcome to Nix 2.6.0. Type :? for help.

nix-repl> pkgs = 1

nix-repl> :l <nixpkgs> 
Added 15729 variables.

nix-repl> pkgs
1
```

**Comment by yorickvP** [comment]
Hmm, I swear I tested this.

**Comment by pennae** [comment]
it may well have worked for you. `std::sort` isn't stable, you could've been lucky and always had the newest version of a name at the beginning of a run during testing
