### ISSUE TITLE
`nix copy` refuses to copy a removed path 

### ISSUE THREAD

**Issue by neosimsim** [NixOS/nix#6056]
I use `nix copy` to populate an AWS S3 bucket.

```
nix sign-paths -r --key-file cache.private -f . foo
nix copy --to 's3://foo-cache' -f . foo
```
Which works exacty once. Then to update the signtature I removed the nar from AWS

```
aws s3 rm s3://sonnen-vpp-nix-cache/nar/7061wpm4f3bsv7bdvlav0cnaisnvrk4l.narinfo
aws s3 rm s3://sonnen-vpp-nix-cache/nar/0qs4rb34rr6xzggnxrhayp632bwcib1326ra5c5a9606va85hd9x.nar.xz
```

But now all I get from

```
nix copy --to 's3://foo-cache' -f . foo
```

is 

```
copying 0 paths...
```

I woud expect `nix copy` to copy the nar again.

```
nix-env --version
(Nix) 2.6.0
```

**Comment by ajs124** [comment]
This is probably some kind of caching artifact. Did you try deleting `~/.cache/nix` and/or `/root/.cache/nix`?

**Comment by edolstra** [comment]
Specifically deleting `~/.cache/nix/binary-cache-v6.sqlite`. Alternatively `--refresh` might work, but it might also assume that binary cache entries are infinitely cacheable.

**Comment by neosimsim** [comment]
Thank you very much :heart: 
I only tried to remove `/root/.cacho/nix/binary-cache-v6.sqlite`. Removing `~/.cache/nix/binary-cache-v6.sqlite` did the job.  `--refresh` did work, too.

**Comment by neosimsim** [comment]
I'm still happy with `--refresh`, which fixes this issue for me.
