### ISSUE TITLE
Automatically evaluate `default.nix` along with `shell.nix`

### ISSUE THREAD

**Issue by abhillman** [NixOS/nix#6082]
Supposing I have a set of dependencies `D` that I need for building my application (e.g. compiler) and dependencies `D` + `W` that I want on a developer workstation (e.g. compiler and emacs). It would be really cool to be able to define `D` in `default.nix` and `W` in `shell.nix`, without needing to repeat dependencies `D` in `shell.nix`.

**Comment by cole-h** [comment]
Would `inputsFrom` help for your use case? https://nixos.org/manual/nixpkgs/stable/#sec-pkgs-mkShell-usage

**Comment by roberth** [comment]
Alternatively, you could derive your `shell.nix` shell from your `default.nix`, ie something like

```nix
args@{...}:
let
  mypkg = import ./default.nix args;
in
  mypkg.overrideAttrs(o: {
    shellHook = ''
      echo "Welcome to shell.nix"
    '';
    buildInputs = [ libsW ];
    nativeBuildInputs [ commandsW ];
  })
```
