### ISSUE TITLE
--max-freed option disappeared from nix-collect-garbage

### ISSUE THREAD

**Issue by peti** [NixOS/nix#609]
`nix-collect-garbage` used to have an option called `--max-freed`, but it appears to be gone in the latest release.

`nix-store --gc` on the other hand, still has that option and it works fine. 

Is that intentional?

**Comment by edolstra** [comment]
I don't think this is intentional.

**Comment by peti** [comment]
I suppose this means that https://github.com/NixOS/nixpkgs/commit/ab6c8643d451b04884e938cd7ed2186663d32a96 can be reverted once the new Nix version appears in the Nixpkgs `master ` branch.
