### ISSUE TITLE
Removal of default argument in `forceValue` breaks PackageKit builds.

### ISSUE THREAD

**Issue by aakropotkin** [NixOS/nix#6096]
https://github.com/NixOS/nix/blob/4d67ecbbb2a00b22b1b23073f5853bcb5b100b75/src/libexpr/eval.hh#L228

Previously PackageKit relied on `const Pos & pos = noPos` by making calls using a single argument. When PackageKit is built using Nix 2.7.0 compilation failures occur.

I have created patch which simply add `noPos` explicitly to PackageKit, and have submitted a PR to their project. https://github.com/PackageKit/PackageKit/pull/530

If/when this patch is merged the package definition in `nixpkgs` may need to be updated as well - I will create a PR for Nixpkgs when that time comes.

**Comment by NickCao** [comment]
This also breaks the build of `hydra-eval-jobs`, ref https://github.com/NixOS/nixpkgs/pull/158455

**Comment by NickCao** [comment]
More in favor of fixing these downstream though, as there's also other breaking changes like the string_view ones.

**Comment by aakropotkin** [comment]
The change was merged by PackageKit last night. I'm creating a PR for `nixpkgs` now which updates the `src` to the latest patched `rev`.
