### ISSUE TITLE
Install fails due to missing recursive flag on copy command

### ISSUE THREAD

**Issue by selfagency** [NixOS/nix#6097]
**Describe the bug**

```
I am executing:

    $ sudo cp /etc/bashrc /etc/bashrc.backup-before-nix

to back up your current /etc/bashrc to /etc/bashrc.backup-before-nix

cp: -r not specified; omitting directory '/etc/bashrc'
```

**Steps To Reproduce**

Run `sh <(curl -L https://nixos.org/nix/install) --daemon` on Debian Buster

**Expected behavior**

Nix should properly install?

**`nix-env --version` output**

**Additional context**

**Comment by abathur** [comment]
Why would /etc/bashrc be a directory?

**Comment by selfagency** [comment]
Don't look at me, I didn't write the install script!

**Comment by abathur** [comment]
Not sure. I haven't heard of this, but the world's a big place, and Shell is wild, so I wouldn't really be shocked.

It may be worth pulling on if you see the same again (or if someone else running Debian on DO or elsewhere sees the same).
