### ISSUE TITLE
nix-prefetch-url says "curl: (48) An unknown option was passed in to libcurl"

### ISSUE THREAD

**Issue by falsifian** [NixOS/nix#61]
$ nix-prefetch-url 'http://releases.mozilla.org/pub/mozilla.org/firefox/releases/16.0.1/source/firefox-16.0.1.source.tar.bz2'
curl: (48) An unknown option was passed in to libcurl
/run/current-system/sw/bin/nix-prefetch-url: download of ‘http://releases.mozilla.org/pub/mozilla.org/firefox/releases/16.0.1/source/firefox-16.0.1.source.tar.bz2’ failed

If I run the same command as root, with a different set of environment variables, it seems to work, so it's probably something in my environment or in my path.  Let me know if you have ideas for further debugging.

Version: I ran nix-channel --update and nixos-rebuild recently (a few hours into October 12, UTC).  The store path is /nix/store/427fx3ca6fgydyby0bkh9bvqgrnbvgdv-nix-1.1/bin/nix-prefetch-url

**Comment by domenkozar** [comment]
This works for me on NixOS under a normal user, is it still and issue?

**Comment by vcunat** [comment]
Same for me. It probably got fixed at some point during those three years.

**Comment by falsifian** [comment]
Same here. Closing.
