### ISSUE TITLE
nix flake - git operations depend on git 2.X installed

### ISSUE THREAD

**Issue by AleksanderGondek** [NixOS/nix#6109]
When dealing with git  dependencies, the flake attempts to use git command not available in old git versions. 
I believe that the same operation outcome, may be achieved without relying on the new `-C` switch. 

**Steps To Reproduce**

1. Ensure that the `git` available in PATH is in version 1.x
2. Clone any repository using nix flakes
3. cd into the repository and run some operation via flake (i.e. nix shell, nix flake update)
4. See error: "unkown option -C"

Culprit: [link](https://github.com/NixOS/nix/blob/aa5b83d93ce1b7bb67bf81ceda7ebf7706b1efa0/src/libfetchers/git.cc#L24)

**Expected behavior**

**`nix-env --version` output**
* `nix-env (Nix) 2.5.0pre20211206_d1aaa7e`
* `nix-env (Nix) 2.6`

**Additional context**

The behaviour is quite annoying when dealing with older OSes, where git is not in v 2.x, nor is it possible to easily update it. One has to run nix from nix (nix-shell -p git) to work around this issue.

**Comment by andersk** [comment]
`git -C` was added in Git 1.8.5 (2013-11-27), not 2.x.

**Comment by AleksanderGondek** [comment]
Now I feel like an absolute dummy. Sorry!
