### ISSUE TITLE
with useChroot = true, switch-to-configuration dies accessing /proc/1/exe

### ISSUE THREAD

**Issue by anderspapitto** [NixOS/nix#611]
When I had useChroot = true, `nixos-rebuild switch` would die on line 326 (`my $prevSystemd = abs_path("/proc/1/exe") or die;`)

I'm not sure if this always happened, or if specific changes were needed to trigger it (such as changing systemd service definitions/existence).

I am running NixOS, on nixpkgs untsable, commit 2c933ad3db8bd168709a967c27cfa5c3457a9006

**Comment by edolstra** [comment]
Closing as this is not a Nix issue. https://github.com/NixOS/nixpkgs/issues/10261
