### ISSUE TITLE
fresh install: doesn't seem to work

### ISSUE THREAD

**Issue by permezel** [NixOS/nix#6118]
**Describe the bug**

I am (desirous of being) a naïve user.  I installed per the WEB page.  I now want to see if there are actually any packages available.  I don't want to spend all night reading man pages or WEB pages or figuring out what a `repl` is.  I want to install a package.

**Steps To Reproduce**

1. Install
2. run `nix search nixpkgs *`

```
sloth% nix search nixpkgs *   
error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override
```

**Expected behavior**

I would expect some packages to be listed.  Not some obscure error message which causes me to waste more time trying to figure out what is going on.

**`nix-env --version` output**

sloth% nix-env --version
nix-env (Nix) 2.6.1

**Additional context**
If I try to run the `upgrade-nix` command, it also fails.

```
sloth% nix upgrade-nix       
replacing old 'nix-2.6.1'
installing 'nix-2.6.0'
error: opening lock file '/nix/var/nix/profiles/default.lock': Permission denied
error: program '/nix/store/jm5i3ilfj1zg99b8jzqim90sbdfbfmdv-nix-2.6.1/bin/nix-env' failed with exit code 1
```

Perhaps I am supposed to run this via `sudo`?  A bit curious that it wants to upgrade from 2.6.1 to 2.6.0.  I usually have my version numbers going the other way, but I can see the advantage of this: 0.0.0...0 is a perfect ideal, and you can approach it asymptotically.

**Comment by permezel** [comment]
Had to use:
```
sloth% nix --extra-experimental-features nix-command --extra-experimental-features flakes search nixpkgs
```
to get it to work.

Every `nix` command I have tried so far has pestered me thus.

**Comment by edolstra** [comment]
Hi, try `nix-env -qa` to see available packages. `nix search` is experimental.
