### ISSUE TITLE
oh no! `sudo /usr/sbin/vifs` failed to mount

### ISSUE THREAD

**Issue by permezel** [NixOS/nix#6122]
**Describe the bug**

Fresh install fails to add disk to `fstab`.

**Steps To Reproduce**

1. sh <(curl -L https://nixos.org/nix/install) --daemon
2. type 'y' several times as required
4. See error:
```
Volume on disk1s7 failed to mount
Perhaps the operation is not allowed by the invoking user (kDAReturnNotPrivileged)
```

**Expected behavior**

Expecting a nice clean successful install.

**`nix-env --version` output**
```
[nimda@lust ~]$ nix-env --version
zsh: command not found: nix-env
```

**Additional context**

Seems to be a permissions issue.

Running as my admin account `nimda` as I run with separation of privilege.  IE: logged in me, but `su - nimda` in a `Terminal.app` window.

```console
[nimda@lust ~]$ sh <(curl -L https://nixos.org/nix/install) --daemon
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  4046  100  4046    0     0  20464      0 --:--:-- --:--:-- --:--:-- 20464
downloading Nix 2.6.1 binary tarball for x86_64-darwin from 'https://releases.nixos.org/nix/nix-2.6.1/nix-2.6.1-x86_64-darwin.tar.xz' to '/var/folders/1s/ds6rtcr14dj89s6lpttb8ql80000gn/T/nix-binary-tarball-unpack.XXXXXXXXXX.5PPHOySI'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23.1M  100 23.1M    0     0  5588k      0  0:00:04  0:00:04 --:--:-- 5690k
Switching to the Multi-user Installer
Welcome to the Multi-User Nix Installation

This installation tool will set up your computer with the Nix package
manager. This will happen in a few stages:

1. Make sure your computer doesn't already have Nix. If it does, I
   will show you instructions on how to clean up your old install.

2. Show you what I am going to install and where. Then I will ask
   if you are ready to continue.

3. Create the system users and groups that the Nix daemon uses to run
   builds.

4. Perform the basic installation of the Nix files daemon.

5. Configure your shell to import special Nix Profile files, so you
   can use Nix.

6. Start the Nix daemon.

Would you like to see a more detailed list of what I will do?
[y/n] y


I will:

 - make sure your computer doesn't already have Nix files
   (if it does, I will tell you how to clean them up.)
 - create local users (see the list above for the users I'll make)
 - create a local group (nixbld)
 - install Nix in to /nix
 - create a configuration file in /etc/nix
 - set up the "default profile" by creating some Nix-related files in
   /var/root
 - back up /etc/bashrc to /etc/bashrc.backup-before-nix
 - update /etc/bashrc to include some Nix configuration
 - back up /etc/zshrc to /etc/zshrc.backup-before-nix
 - update /etc/zshrc to include some Nix configuration
 - create a Nix volume and a LaunchDaemon to mount it
 - create a LaunchDaemon (at /Library/LaunchDaemons/org.nixos.nix-daemon.plist) for nix-daemon

Ready to continue?
[y/n] y


---- let's talk about sudo -----------------------------------------------------
This script is going to call sudo a lot. Every time I do, it'll
output exactly what it'll do, and why.

Just like this:

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo echo

to demonstrate how our sudo prompts look


This might look scary, but everything can be undone by running just a
few commands. I used to ask you to confirm each time sudo ran, but it
was too many times. Instead, I'll just ask you this one time:

Can I use sudo?
[y/n] y

Yay! Thanks! Let's get going!

~~> Fixing any leftover Nix volume state
Before I try to install, I'll check for any existing Nix volume config
and ask for your permission to remove it (so that the installer can
start fresh). I'll also ask for permission to fix any issues I spot.

~~> Checking for artifacts of previous installs
Before I try to install, I'll check for signs Nix already is or has
been installed on this system.

---- Nix config report ---------------------------------------------------------
        Temp Dir:	/tmp/tmp.ZL0KDCMhnL
        Nix Root:	/nix
     Build Users:	32
  Build Group ID:	30000
Build Group Name:	nixbld

build users:
    Username:	UID
     _nixbld1:	301
     _nixbld2:	302
     _nixbld3:	303
     _nixbld4:	304
     _nixbld5:	305
     _nixbld6:	306
     _nixbld7:	307
     _nixbld8:	308
     _nixbld9:	309
     _nixbld10:	310
     _nixbld11:	311
     _nixbld12:	312
     _nixbld13:	313
     _nixbld14:	314
     _nixbld15:	315
     _nixbld16:	316
     _nixbld17:	317
     _nixbld18:	318
     _nixbld19:	319
     _nixbld20:	320
     _nixbld21:	321
     _nixbld22:	322
     _nixbld23:	323
     _nixbld24:	324
     _nixbld25:	325
     _nixbld26:	326
     _nixbld27:	327
     _nixbld28:	328
     _nixbld29:	329
     _nixbld30:	330
     _nixbld31:	331
     _nixbld32:	332

Ready to continue?
[y/n] y


---- Preparing a Nix volume ----------------------------------------------------
    Nix traditionally stores its data in the root directory /nix, but
    macOS now (starting in 10.15 Catalina) has a read-only root directory.
    To support Nix, I will create a volume and configure macOS to mount it
    at /nix.

~~> Configuring /etc/synthetic.conf to make a mount-point at /nix

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/ex --noplugin /etc/synthetic.conf

to add Nix to /etc/synthetic.conf

Password:

~~> Creating a Nix volume

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/diskutil apfs addVolume disk1 APFS Nix Store -nomount

to create a new APFS volume 'Nix Store' on disk1


---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/diskutil unmount force disk1s7

to ensure the Nix volume is not mounted

disk1s7 was already unmounted

~~> Configuring /etc/fstab to specify volume mount options

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/vifs

to add nix to fstab

Volume on disk1s7 failed to mount
Perhaps the operation is not allowed by the invoking user (kDAReturnNotPrivileged)

---- oh no! --------------------------------------------------------------------
Jeeze, something went wrong. If you can take all the output and open
an issue, we'd love to fix the problem so nobody else has this issue.

:(

We'd love to help if you need it.

You can open an issue at https://github.com/nixos/nix/issues

Or feel free to contact the team:
 - Matrix: #nix:nixos.org
 - IRC: in #nixos on irc.libera.chat
 - twitter: @nixos_org
 - forum: https://discourse.nixos.org
[nimda@lust ~]$ nix-env --version
zsh: command not found: nix-env
```

```console
/dev/disk1 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +999.7 GB   disk1
                                 Physical Store disk0s2
   1:                APFS Volume ⁨Macintosh HD — Data⁩     638.3 GB   disk1s1
   2:                APFS Volume ⁨Preboot⁩                 668.4 MB   disk1s2
   3:                APFS Volume ⁨Recovery⁩                1.1 GB     disk1s3
   4:                APFS Volume ⁨VM⁩                      4.3 GB     disk1s4
   5:                APFS Volume ⁨Macintosh HD⁩            23.6 GB    disk1s5
   6:              APFS Snapshot ⁨com.apple.os.update-...⁩ 23.6 GB    disk1s5s1
   7:                APFS Volume ⁨Nix Store⁩               20.5 KB    disk1s7
```

```console
[nimda@lust ~]$ cat /etc/fstab
#
# Warning - this file should only be modified with vifs(8)
#
# Failure to do so is unsupported and may be destructive.
#
UUID=B502F760-3208-48C7-B9E6-B516A160AB34 /nix apfs rw,noauto,nobrowse,suid,owners
```

```console
[nimda@lust ~]$ diskutil mount /dev/disk1s7
Volume on disk1s7 failed to mount
Perhaps the operation is not allowed by the invoking user (kDAReturnNotPrivileged)
[nimda@lust ~]$ sudo diskutil mount /dev/disk1s7
Password:
Volume Nix Store on /dev/disk1s7 mounted
```

**Comment by abathur** [comment]
vifs is a red herring, but the diskutil mount is probably about right

Are you using filevault? If so, it's presumably occurring at https://github.com/NixOS/nix/blob/9bc03adbba5334663901c1136203bc07e4776be9/scripts/create-darwin-volume.sh#L693

Should be an easy-enough fix as long as adding sudo there doesn't cause any problems of its own. Is this an Intel mac? M1?

**Comment by abathur** [comment]
Opened a PR with a tentative fix on the assumption that you'll say yes re: filevault. 

Are you still in a position to test it? (If the CI runs clean, it'll produce an installer you could use for an Intel mac, but not for M1/arm. In theory this takes about an hour and a half, but these builds have been having some flakiness issues and I may have to re-try it a few times...)

**Comment by permezel** [comment]
> Are you using filevault? If so, it's presumably occurring at https://github.com/NixOS/nix/blob/9bc03adbba5334663901c1136203bc07e4776be9/scripts/create-darwin-volume.sh#L693

I am using FileVault.

> 
> 
> 
> Should be an easy-enough fix as long as adding sudo there doesn't cause any problems of its own. Is this an Intel mac? M1?

Intel.  Ancient TrashCan-pro.

**Comment by permezel** [comment]
> Are you still in a position to test it? (If the CI runs clean, it'll produce an installer you could use for an Intel mac, but not for M1/arm. In theory this takes about an hour and a half, but these builds have been having some flakiness issues and I may have to re-try it a few times...)

Sure.  I'll blow away the /nix (not much has been added) and try it.

> 
> 
> 
> Edit: CI did [run clean](https://github.com/abathur/nix/actions/runs/1867881446); should be able to test with something to the effect of `sh <(curl -L https://abathur-nix-install-tests.cachix.org/serve/f52xdlqa47c2lc9q01achjm0xxnb9w3v/install) --tarball-url-prefix https://abathur-nix-install-tests.cachix.org/serve`

I'll head into the other room after the coffee kicks in and try.

**Comment by permezel** [comment]
Worked.  Took me most of this time to get my "remove" script working.

Here's my current take on an macOS remove script.  Still not complete, but sufficient: [remo](https://gist.github.com/permezel/48253aa4432c88d9475467f1ac9f1316).

**Comment by abathur** [comment]
Thanks. Good sign. Did/can you check this part under the same user? 

> If you get through an install with that, I'm also curious about whether you are able to run the credential-fetch-and-unlockVolume pipeline that gets built into the launchdaemon at `/Library/LaunchDaemons/org.nixos.darwin-store.plist` under the same user, or if you also see problems with it as well (and, if so, if adding sudo to the `/usr/sbin/diskutil unlockVolume` is sufficient).

**Comment by permezel** [comment]
> Thanks. Good sign. Did/can you check this part under the same user?
> 

If you are asking if I can reboot and log in as the same, non-admin user, and /nix is mounted, the answer is `yes`.
Otherwise, I will need som clarification, or _explicification_ (new word for 2022).

**Comment by abathur** [comment]
Read `/Library/LaunchDaemons/org.nixos.darwin-store.plist` for the populated version of this pipeline: https://github.com/NixOS/nix/blob/caf51729450d4c57d48ddbef8e855e9bf65f8792/scripts/create-darwin-volume.sh#L288 and try to run it as this user.

You might have to forcibly unmount and lock it before it'll run the unlockVolume? I'm not really sure and don't currently have a filevaulted device to test it on.

**Comment by permezel** [comment]
Given that I managed to perform the install, logged in as `${non-admin}`, but in a `su - ${admin-user}` session, and it worked (I did the suggested `nix-whatever` command in a new window), this  suggests there were no issues with the mount, no?  Subsequent reboots are not the issue here.

I'm not sure why the /nix volume is encrypted iff / is encrypted.  The container disk is not encrypted, and each contained volume can select whatever formats are desired.  Anyone installing /nix should be able to select encrypted or non-.    Off the top of my head, I see no particular reason to encrypt /nix, but this is a personal issue.  Someone might install all sorts of nefarious s/w and wish it to be protected at rest.

You may eventually run into issues where someone turns on/off FileVault and then wonders why the enc status of /nix did not follow (I am not suggesting it should) but then the issue becomes: how to individually toggle the /nix enc status.  I would suggest trying to make the plist command entry be agnostic: IE, work regardless of the enc-ness, thereby insulating from issues if someone does figure out how to toggle the enc-ness of /nix.

BTW: I did try to force the unmount but need to figure out how to unload the daemon first.

**Comment by abathur** [comment]
Ok. Thanks for giving it a try. 

The concern isn't actually that it works from the mounter--that should have permission--it's that there's also one more condition (when someone comes with an existing encrypted volume) that the installer will run the equivalent command, and I'm not sure whether that one needs sudo.

https://github.com/NixOS/nix/blob/caf51729450d4c57d48ddbef8e855e9bf65f8792/scripts/create-darwin-volume.sh#L255

**Comment by permezel** [comment]
```console
[nimda@lust ~]$ ls -l /nix
total 0
[nimda@lust ~]$ /usr/bin/security find-generic-password -s '92AE0D6B-4F58-44F1-BEF9-78C41381A5B1' -w | /usr/sbin/diskutil apfs unlockVolume '92AE0D6B-4F58-44F1-BEF9-78C41381A5B1' -mountpoint '/nix' -stdinpassphrase

Unlocking any cryptographic user on APFS Volume disk1s7
Error unlocking APFS Volume: Insufficient privileges (-69863)
```

```console
[nimda@lust ~]$ /usr/bin/security find-generic-password -s '92AE0D6B-4F58-44F1-BEF9-78C41381A5B1' -w | sudo /usr/sbin/diskutil apfs unlockVolume '92AE0D6B-4F58-44F1-BEF9-78C41381A5B1' -mountpoint '/nix' -stdinpassphrase

Unlocking any cryptographic user on APFS Volume disk1s7
Unlocked and mounted APFS Volume
[nimda@lust ~]$ ls -l /nix
total 0
drwxrwxr-t  2068 root  nixbld  66176 Feb 22 15:12 store
drwxr-xr-x     4 root  nixbld    128 Feb 22 12:25 var
```
