### ISSUE TITLE
nix profile install: packages have the same priority (when trying to re-install)

### ISSUE THREAD

**Issue by nmattia** [NixOS/nix#6143]
**Describe the bug**

Looks like there is no way to re-install a package with the `nix profile install` command. It fails with the following error:

```
$ nix profile install
error: packages '/nix/store/d0wb2gam2pyksz2dsjx6sa83761jrrgi-hello-2.12/bin/hello' and '/nix/store/61n15131n3b9mn7ajvddbyfnv2b3pgjd-hello-2.12/bin/hello' have the same priority 5
; use 'nix-env --set-flag priority NUMBER INSTALLED_PKGNAME' to change the priority of one of the conflicting packages (0 being the highest priority)
```

I'm not sure how `nix-env` dealt with this.

(note: the 'nix-env' command suggested in the error message doesn't work because it complains that the profile was installed with "nix profile"; also this wouldn't really solve the issue)

**Steps To Reproduce**

``` bash
$ nix flake init
$ nix profile install
# now edit `flake.nix` to change the "hello" derivation, for instance:
$ cat flake.nix
... hello.overrideAttrs (_: {
      postBuild = "echo hello";

    });
$ $ nix profile install
error: packages '/nix/store/d0wb2gam2pyksz2dsjx6sa83761jrrgi-hello-2.12/bin/hello' and '/nix/store/61n15131n3b9mn7ajvddbyfnv2b3pgjd-hello-2.12/bin/hello' have the same priority 5
; use 'nix-env --set-flag priority NUMBER INSTALLED_PKGNAME' to change the priority of one of the conflicting packages (0 being the highest priority)
```

**Expected behavior**

The `hello` package should be replaced.

**`nix-env --version` output**

```
$ nix-env --version
nix-env (Nix) 2.6.0
```

**Additional context**

Running `nix profile upgrade` doesn't do anything. For now the workaround is to `nix profile remove` everything before `nix profile install`ing.

---

EDIT: I just realized that `nix profile upgrade` can take a number. When giving it the same number of the flake used to install `hello`, I get the same error as `nix profile install`:

```
$ nix profile list | grep hello
6 path:/private/var/folders/tx/d4435y0s3dqbytdf1f09s8740000gn/T/tmp.YFCSpO8v#defaultPackage.aarch64-darwin path:/private/var/folders/tx/d4435y0s3dqbytdf1f09s8740000gn/T/tmp.YFCSp
O8v?narHash=sha256-JyMfoXbdBn9JlHIPJOPupn0K0zSuniX7bSFf1XQKY5I=#defaultPackage.aarch64-darwin /nix/store/61n15131n3b9mn7ajvddbyfnv2b3pgjd-hello-2.12
$ nix profile upgrade 6
error: packages '/nix/store/d0wb2gam2pyksz2dsjx6sa83761jrrgi-hello-2.12/bin/hello' and '/nix/store/61n15131n3b9mn7ajvddbyfnv2b3pgjd-hello-2.12/bin/hello' have the same priority 5
; use 'nix-env --set-flag priority NUMBER INSTALLED_PKGNAME' to change the priority of one of the conflicting packages (0 being the highest priority)
```

**Comment by blaggacao** [comment]
I suspect: https://github.com/NixOS/nix/blob/caf51729450d4c57d48ddbef8e855e9bf65f8792/src/nix/profile.cc#L40

**Comment by jrpear** [comment]
I have this same issue when trying to install `wine` and `wine64` with the file `.../bin/function_grep.pl` using `nix profile install`.

**Comment by AndersonTorres** [comment]
Bump :/

**Comment by sullyj3** [comment]
If I'm understanding this right, I think this issue is about to afflict home-manager users trying out the new `nix profile` compatibility

**Comment by elikoga** [comment]
bumping for self reference, might try at implementing
