### ISSUE TITLE
`outputs.__functor` breaks `nix` CLI's target resolver

### ISSUE THREAD

**Issue by blaggacao** [NixOS/nix#6152]
- latest master

**Wrong**
```
nix repl> nix-repl> outputs.
outputs.__functor
outputs.foo

$ nix eval --json .#foo
error: the expression selected by the selection path 'packages.x86_64-linux.foo' should be a set but is a function
```

**Expected**
```
nix repl> nix-repl> outputs.
outputs.foo
$ nix eval --json .#foo
{"x86_64-linux":{ ... }}
```

**Observation**

- the presence of `outputs.__functor` breaks the `nix` CLI target resolver.

/cc @tomberek @cleverca22

**Comment by tomberek** [comment]
Duplicate? https://github.com/NixOS/nix/issues/4415

**Comment by tomberek** [comment]
Caused by a call to autoCallFunction and the subsequent detection of a "__functor" attribute:

Trace:
https://github.com/NixOS/nix/blob/94992a919636fb9df4c7441dacbde08592e4494d/src/libcmd/installables.cc#L614
https://github.com/NixOS/nix/blob/bd383d1b6f91c4fe7ac21c52771e92027f649fa0/src/libexpr/attr-path.cc#L59
https://github.com/NixOS/nix/blob/bd383d1b6f91c4fe7ac21c52771e92027f649fa0/src/libexpr/eval.cc#L1513

**Comment by disassembler** [comment]
@tomberek @edolstra I think this is a major blocker for nix 2.7. can we get this fixed before that release?

**Comment by cleverca22** [comment]
reproduced without involving flakes
```
[clever@amd-nixos:~]$ cat autocall.nix ; nix-instantiate --eval  --argstr arg2 bar --argstr arg1 foo autocall.nix -A attr1.attr2 --argstr arg3 baz
{ arg1 }: {
  attr1 = {
    __functor = self: arg2: {
      attr2 = { arg3 }: "${arg1}${arg2}${arg3}";
    };
    attr2 = "functor not followed ${arg1}";
  };
}
error: the expression selected by the selection path 'attr1.attr2' should be a set but is a function
```

based on https://gist.github.com/cleverca22/240c21dab528666c85a95c4edfdeae58

**Comment by edolstra** [comment]
@disassembler Hm, why is it a blocker? It's not a regression right?

**Comment by blaggacao** [comment]
@edolstra fair question and the answer is dynamic & social, not technical.

- In good faith, we built momentum for a direction of tooling that makes use of `.__functor` at the top level for capturing (optional) variadic arguments.
- Now there is no way back, only forward.
- Out of this situation a fix arose
- `nix2.7`, thanks to balsoft's follows fix will be the first practically _usable_ `nix` version and our realistic chance at improving onboarding and DevX, which both are critical to the success of `nix` in the broader picture.
