### ISSUE TITLE
Header Changes in v2. 7 break PackageKit ( Part II ) 

### ISSUE THREAD

**Issue by aakropotkin** [NixOS/nix#6176]
Hey I wanted to recommend a bump to a new major release for some of the latest 2.7pre changes. I patched PackageKit last week after a default argument was dropped for one public interface in Nix's `libexpr`, but since then it looks like more breaking changes to public headers was pushed. 

The call is ultimately up to you of course, but you may want to make Nix 2.7pre into Nix 3.0 when the time comes to release since many of the new changes to public interfaces aren't backwards compatible.

Again, versioning is an opinionated topic, and ultimately you're calling the shots - I just wanted to raise visibility.

I'll probably make new PRs for PackageKit and Nixpkgs again to get builds succeeding again in the next few days.

For clarity : I'm not a PackageKit maintainer; I just depend on it for some reason and since I follow Nix on `main` in my flakes I get hit earlier than most folks ( not complaining, I do it to help contribute ).

**Comment by thufschmitt** [comment]
Duh, I didn’t even know there was a Nix backend for PackageKit 

> one public interface in Nix's libexpr

Afaik, the only public interface to Nix is the CLI (not that I wouldn’t like to have a more machine-friendly interface. But it’s a non-trivial amount of work). The C++ headers are provided for convenience because some ppl want to use them, but without any guaranty of stability. Not sure what that means for PackageKit though

**Comment by edolstra** [comment]
That's correct, there is no stable C++ API at the moment.

**Comment by thufschmitt** [comment]
> Just as a practical matter "GNOME 3 won't build on NixOS with v2. 7pre" might be relevant to this conversation

Indeed, just noticed that while trying to rebuild my system :)

It’s a bit unfortunate that packagekit in nixpkgs uncontitionnally builds with Nix support given that it’s relying on some unstable stuff. We should probably re-make this optional (and off by default)

Fwiw, I worked around it for the time being by overriding it to use `nixStable`
