### ISSUE TITLE
TeXLive installation fails on M1 Mac

### ISSUE THREAD

**Issue by xave** [NixOS/nix#6180]
**Describe the bug**

Running the command ```nix-env -iA nixpkgs.texlive.combined.scheme-full``` fails with errors on M1 Mac. See log.
If you have a problem with a specific package or NixOS,
you probably want to file an issue at https://github.com/NixOS/nixpkgs/issues. 

**Steps To Reproduce**

1. Run nix-env -iA nixpkgs.texlive.combined.scheme-full2. 
2. Failure.

*Expected Behavior*
A successful installation of the package.

**`nix-env --version` output**
nix-env (Nix) 2.6.1

**Additional context**
[texlive-nix-log.txt](https://github.com/NixOS/nix/files/8155234/texlive-nix-log.txt)

none

**Comment by Kranzes** [comment]
This is related to nixpkgs, not nix. Please close this issue and create one in the nixpkgs repository.
