### ISSUE TITLE
Implicit dependency on man

### ISSUE THREAD

**Issue by t184256** [NixOS/nix#6186]
**Describe the bug**

Nix does an `execlp` on `man`, creating an implicit dependency on `man`:

https://github.com/NixOS/nix/blob/d974d2ad59d1cc8aee63e2a18124e58c1084ff65/src/libmain/shared.cc#L361

**Steps To Reproduce**

(real-life bug report: https://github.com/t184256/nix-on-droid/issues/177)

1. Do not have `man`
2. `nix-store --help`
3. `command 'man nix-store' failed: No such file or directory.`

**Expected behavior**

Either nix explicitly depends on its dependencies or maybe doesn't use `man` at all for rendering `--help`. Ain't it what it pulls lowdown for?

**`nix-env --version` output**

nix-env (Nix) 2.3.16

**Additional context**

**Comment by edolstra** [comment]
This is fixed in the new CLI, whose `--help` uses lowdown without `man`.

**Comment by t184256** [comment]
And the old CLI will go away, so we don't mind? OK.
