### ISSUE TITLE
nix GC taking several hours typically

### ISSUE THREAD

**Issue by PAI5REECHO** [NixOS/nix#6207]
**Describe the bug**

Garbage collection typically takes several hours despite having only a few hundred packages installed from my `configuration.nix`. `neofetch` reports `Packages: 4527 (nix-system), 2 (nix-user), 2 (nix-default)`

**Steps To Reproduce**
```
# time nix store gc --dry-run
(will update once complete)
```

![flamegraph](https://user-images.githubusercontent.com/96688573/156940895-07131d08-8ad6-45f4-a6b8-8486cbff1c5c.svg)

**Expected behavior**
Quicker garbage collection time and more feedback regarding progress of GC operation.

**`nix-env --version` output**
`nix-env (Nix) 2.5.0pre20211206_d1aaa7e`

**Comment by edolstra** [comment]
Looks like you have CA derivations enabled? It's spending a lot of time in `queryPartialDerivationOutputMap()` reading derivations. Maybe that could be memoized, or we could store the static output hashes in the database so we don't need to read the derivations at all. @thufschmitt

**Comment by thufschmitt** [comment]
Indeed. I guess that having `keep-outputs` + ca-derivations can require the GC to read every derivation in the store, which is very costly.

> Maybe that could be memoized, or we could store the static output hashes in the database so we don't need to read the derivations at all

As far as I know, that’s already partially memoized (could probably be improved, but maybe not enough), but caching the hashes in the DB might be the best long-term solution (I’m generally a bit worried about putting too much stuff in the db as it’s the hardest part to change, but since that’s just a cache I don’t think it would be a big issue)

**Comment by thufschmitt** [comment]
Although "several hours" is quite insanely high, even considering the need to read all the derivation files. Is your store particularly big (regardless of how many packages are actually “installed”)?

**Comment by SuperSandro2000** [comment]
or is your store installed on a really slow hard drive or mounted over nfs or similar?

**Comment by PAI5REECHO** [comment]
> Looks like you have CA derivations enabled?

> having `keep-outputs` + ca-derivations

Correct.
```
keep-outputs = true
keep-derivations = true
experimental-features = nix-command flakes ca-derivations recursive-nix
```
> Is your store particularly big (regardless of how many packages are actually “installed”)?

I'm not sure what metrics to check here. It's around ~100 GB I think

> or is your store installed on a really slow hard drive or mounted over nfs or similar?

No, it's located on a BTRFS mount point on a local SSD

**Comment by PAI5REECHO** [comment]
I've gone ahead and disabled `keep-outputs`, `keep-derivations` & `ca-derivations`, my GC times are now much better

**Comment by SuperSandro2000** [comment]
My store is 51GB with the same settings but on an ext4 drive. I regularly collect garbage and the last run took 126s which collected 65MB. Maybe you need to run it more often?

**Comment by thufschmitt** [comment]
I’ve been trying to reproduce this, but without any success. `queryPartialderivationOutputMap` only takes a handful of the total GC time (which is slow overall) rather slow.

I’ve tried adding a cache for the hash modulo (to remove the need for reading the derivations), but it only affected the total gc time by a few % (between 1 and 3)

**Comment by trofi** [comment]
@PAI5REECHO I wonder if I experience the same problem as you. Could you try https://github.com/NixOS/nix/pull/6281 on your system and check if it gets better?

**Comment by PAI5REECHO** [comment]
@trofi I'll give it a try later today
@thufschmitt I'll try to arrange a simplified version of my `configuration.nix` that works in a `nixos/nix` Docker container to reproduce this problem

**Comment by PAI5REECHO** [comment]
Seems much better on latest master commit
```
# time nix store gc
1974 store paths deleted, 11329.68 MiB freed

________________________________________________________
Executed in  303.44 secs    fish           external
   usr time  135.05 secs  429.00 micros  135.05 secs
   sys time   66.53 secs    0.00 micros   66.53 secs

# nix --version
nix (Nix) 2.8.0pre20220318_8ad485e
# time nix store gc
0 store paths deleted, 0.00 MiB freed

________________________________________________________
Executed in  182.80 secs    fish           external
   usr time  131.22 secs   11.51 millis  131.21 secs
   sys time   24.91 secs    2.06 millis   24.91 secs
```

**Comment by trofi** [comment]
Woohoo! 5 minutes is still quite a bit, but the profile looks somewhat balanced: OS I/O is not too far away from amount of time spent by filesystem ops (`__do_system_newlstat` tower on the right).

1 minute of `sys` sounds like a lot, but maybe your reachable closure is that big.

**Comment by PAI5REECHO** [comment]
I think the GC efficiency has been thoroughly addressed for now so I'm going to close this. Performance will probably get incrementally better over time as we approach v3.

**Comment by kvtb** [comment]
IO is typically quite slow, e.g. erasing millions files in `/nix/store/trash` when each file requires `unlink()` syscall.

Technically, CoW filesystems (btrfs, zfs, ...) can have optimized `rm -rf`, but I never seen it implemented.
Probably, Nix GC is the usecase with needs this.

**Comment by thufschmitt** [comment]
@kvtb : @roberth mentioned in https://github.com/NixOS/nix/issues/9581#issuecomment-1852409306 that we might be able to improve on that with some pipelining. Probably worth looking at (I guess everything happens in [_deletePath](https://github.com/NixOS/nix/blob/7f5ed330e40d0aa2a2f907b2d4157329ff953cd2/src/libutil/file-system.cc#L340))
