### ISSUE TITLE
Installation flaky on osx

### ISSUE THREAD

**Issue by Globegitter** [NixOS/nix#622]
It seems that on OS X (10.10) the nix installation script is flaky sometimes and while everything seems fine at first the command `nix-env -qaf ~/path/to/packages.nix` then does not work. On different (fresh) machines in our company we had different experiences. Sometimes everything would work perfectly the first time we install, on another machine everything worked fine after a second install and on another machine after a third re-install.

And there is no difference in the environment, etc of the machines. Running `nix-env -qaf ~/Projects/core/nix/packages.nix -vvvvv` leads to 

``` sh
adding path ‘/nix/store/kyizilshqhd28v1yap4ibnpvz5y62ism-nix-1.9/share/nix/corepkgs’ to the search path
evaluating file ‘/nix/store/kyizilshqhd28v1yap4ibnpvz5y62ism-nix-1.9/share/nix/corepkgs/derivation.nix’
evaluating file ‘/Users/path/to/packages.nix’
evaluating attribute ‘arc’
evaluating attribute ‘checkstyleWrapper’
evaluating attribute ‘git’
evaluating attribute ‘nodejs’
evaluating attribute ‘pep8’
evaluating attribute ‘plz’
evaluating attribute ‘pylint’
evaluating attribute ‘sass’
evaluating attribute ‘scssLint’
evaluating attribute ‘unzip’
evaluating attribute ‘yapf’
evaluating attribute ‘zip’
evaluation statistics:
time elapsed: 0.007431
size of a value: 24
size of an attr: 24
environments allocated: 2 (80 bytes
)
  list elements: 1 (8 bytes)
  list concatenations: 0
  values allocated: 127 (3048 bytes)
  sets allocated: 5 (3472 bytes)
  right-biased unions: 0
  values copied in right-biased unions: 0
  symbols in symbol table: 194
  size of symbol table: 1817
  number of thunks: 30
  number of thunks avoided: 24
  number of attr lookups: 0
  number of primop calls: 24
  number of function calls: 1
  total allocations: 6608 bytes
  current Boehm heap size: 33619968 bytes
  total Boehm heap allocations: 13408 bytes
```

Where-as the only real difference (apart from the missing installs) I can see between the log outputs on a working machine and a non-working one is that  there is one line missing: `adding path ‘/home/user/.nix-defexpr/channels/nixpkgs’ to the search path`. 

The environment variables are set and all the same on working and non-working machines, so I can not figure out what makes the installation suddenly work and what not.

**Comment by Anton-Latukha** [comment]
@Globegitter 

macOS install script got a big upgrade recently (Jul 14, 2017) by grahamc: https://github.com/NixOS/nix/commits/master/scripts/install-darwin-multi-user.sh.

Probably you can close or update this bugreport.
