### ISSUE TITLE
Unusual quote characters break echo on macs

### ISSUE THREAD

**Issue by dhobbs** [NixOS/nix#623]
When I tried to install Nix I saw the following message (at which point I bailed out of the install, as I couldn't see what it wanted to run as root):

`performing a single-user installation of Nix... directory /nix does not exist; creating it by running ‘�� using sudo`

It looks like the unusual quote characters were added in https://github.com/NixOS/nix/commit/11849a320e4f522b97fcdf09ff0940496880475b

**Comment by matthewbauer** [comment]
This should be fixed by 3889415bf8c2f44d8a42824d68e501504b709460

**Comment by domenkozar** [comment]
Indeed.
