### ISSUE TITLE
fetchurl should sanity-check url when retrieving from the binary cache

### ISSUE THREAD

**Issue by anderspapitto** [NixOS/nix#624]
Currently, if you take a nix description containing

```
fetchurl {
  url = "url-one";
  sha256 = "1234";
};
```

and modify it to read

```
fetchurl {
  url = "url-two";
  sha256 = "1234";
};
```

(forgetting to change the hash), then a rebuild will silently produce an incorrect system - the change is a no-op.

This could be avoided if the cache server, instead of immediately serving out the file for "1234", maintained a list of urls known to produce that hash, and checked for the correct hash the first time any new url is seen. Then a nice error message could be produced, like

You asked for the contents of "url-two", with hash "1234". I have a file with hash "1234", but "url-two" does not produce this hash. The known urls which do produce this hash are ["url-one", "some-mirror-of-url-one"].

**Comment by vcunat** [comment]
Maintaining a list of URLs known to produce a file certainly isn't a good way. The file might be created by `nix-copy-closure` or some other way, and yet we would want to reuse it.

I believe the whole point of `fetchurl` is *not* to take any action if you only use a different url, which is exactly what you did. Note that if the basename of the URL changes, it *will* re-download (or the explicit `name` changes).
