### ISSUE TITLE
"warning" label disrupts alignment in output of "flake show"

### ISSUE THREAD

**Issue by limeytexan** [NixOS/nix#6240]
When displaying attributes of the `legacyPackages` output,
the `nix flake show` command (without the `--legacy` argument)
displays "warning:" identifiers that disrupt the columnar alignment
of the vertical lines.

```
$ nix-env --version
nix-env (Nix) 2.3.15

$ nix flake show nixpkgs
github:NixOS/nixpkgs/e9545762b032559c27d8ec9141ed63ceca1aa1ac
├───checks
│   └───x86_64-linux
│       └───tarball: derivation 'nixpkgs-tarball-22.05pre20220310.e954576'
├───htmlDocs: unknown
├───legacyPackages
warning: │   ├───aarch64-darwin: omitted (use '--legacy' to show)
warning: │   ├───aarch64-linux: omitted (use '--legacy' to show)
warning: │   ├───armv6l-linux: omitted (use '--legacy' to show)
warning: │   ├───armv7l-linux: omitted (use '--legacy' to show)
warning: │   ├───i686-linux: omitted (use '--legacy' to show)
warning: │   ├───mipsel-linux: omitted (use '--legacy' to show)
warning: │   ├───x86_64-darwin: omitted (use '--legacy' to show)
warning: │   └───x86_64-linux: omitted (use '--legacy' to show)
├───lib: unknown
└───nixosModules
    └───notDetected: NixOS module
```

In considering ways to get the columns to line up I find myself wondering
whether these lines warrant a warning label at all, particularly as "omitted"
is already highlighted with [ANSI_WARNING](https://github.com/NixOS/nix/blob/ad7c99ef20dff74a65d6c8ac2a2c42f538e0a1dd/src/nix/flake.cc#L1050).

One easy fix for this would be to simply replace `logger->warn(fmt())` with
`logger->cout()`, but a side-effect of this would be to shift these lines from
STDERR to STDOUT. We could similarly replace with `logger->writeToStderr()`
but would it be a problem to shift those lines to STDOUT, and if so what is
the rationale for wanting those lines to appear on STDERR?

Happy to submit a PR for this once we pin down the desired behaviour.

**Comment by thufschmitt** [comment]
> what is the rationale for wanting those lines to appear on STDERR?

I think the idea is that without `--legacy` the command should not print anything under `legacyPackages`, but merely warn about their existence and the fact that they can be printed with `--legacy`. So it makes sense not to have them in the output.
But granted, the output as-it-is is quite messy. What we could do would be to not print these at all, but rather eventually add a warning like `warning: some legacy outputs have been omitted. Use '--legacy' to show them` (or something like that).

**Comment by tomberek** [comment]
Another consideration here is what to do in the `--json` case. Right now you get partial JSON and partial colored/structured warning on stderr.
