### ISSUE TITLE
Why not use CLONE_NEWUSER for builders?

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#625]
Seems like use of that mostly patches up most issues people have with escaping from namespaces, and allows the namespace creator to be run with lower power. Unless I'm misunderstanding!

**Comment by lethalman** [comment]
Why should you use it? It's useful for entering a chroot without root privileges, hence I don't see much of a use for builders.

Instead, it would be very interesting for nix-shell to enforce more purity. Like nix-shell --chroot will enter a nix-build like chroot without root privileges.

**Comment by copumpkin** [comment]
@lethalman I thought that most of the residual concerns around "containers are insecure" were obviated by CLONE_NEWUSER from an unprivileged account, since it allows the nix daemon to create the builder namespaces without being root. It might still need root for other things, of course. May be unnecessary, but also doesn't seem particularly harmful.

**Comment by lethalman** [comment]
@copumpkin yes, if nix-daemon setuids before doing the chroot and uses CLONE_NEWUSER with proper uid/gid mappings, that's a some more security.

**Comment by Ericson2314** [comment]
If this allows the nix daemon to be run without root or sacrificing (key) features, that's great!

I want to run nix at school (multi user mode so people besides myself can benefit), and its essential that nothing uses root so the sysadmins don't have reason to be worried.

**Comment by Ericson2314** [comment]
The nix-shell stuff would also be nice. IIUC since nix-shell essentially sets one up as if they were a builder, implementing this for builds should give it to us for shells, and vice versa?

**Comment by lethalman** [comment]
@Ericson2314 yes, if nix-build is able to use CLONE_NEWUSER, then nix-shell can take advantage of the same (or almost) isolation level.

**Comment by orenbenkiki** [comment]
I would dearly love to see #324 supported out of the box, so :+1: - are there any downsides?

**Comment by fhaust** [comment]
I second that. Especially in a distributed environment I think it is unreasonable to ask the admins to run the nix-daemons on every single machine.

**Comment by aszlig** [comment]
I have worked on this a [while ago](https://gist.github.com/aszlig/1dccb5dc09e6235843fa), but can't find the WIP code right now. Will dig it up and push it once I'm home by the end of the week, if that helps.

**Comment by copumpkin** [comment]
Awesome! Please do

**Comment by edolstra** [comment]
Nix now runs builds in a user namespace (with a uid of 0 inside the namespace). This allows the build to do privileged stuff like setting up virtual Ethernet devices for testing. However you can't run commands like systemd-nspawn yet because the uid/gid mapping contains only 1 user.

**Comment by copumpkin** [comment]
Lovely, thank you! Very nice to come back from vacation and find things like this

**Comment by deepfire** [comment]
Is it possible to extend this functionality to nix-shell?

**Comment by copumpkin** [comment]
@edolstra I've actually been thinking more about this and I don't think builds should run as uid 0 inside the user namespace. Given the way namespaces have been retrofitted onto the existing kernel code, many security experts (including Spengler from grsecurity, who disabled unprivileged users launching user namespaces entirely due to this fear) say that running as uid 0 even inside a user namespace exposes far more kernel code pathways to unprivileged code than they feel comfortable recommending. Once everything is hardened better, it might make sense to re-evaluate, but for now I think it's a bit safer (from a 0-day or general safety of build host perspective) to run builds as a non-root mapped user inside a user namespace. We might still be able to grant specific capabilities to the non-root user if we deem them to be safe.

cc @aszlig

**Comment by aszlig** [comment]
@copumpkin: This should no longer be the case since 3a4bd320c2c4043a4b1f73406030e9afc0677b59. In current `master`, the build [user](https://github.com/NixOS/nix/blob/169edf94072c92f9a6148838c50c92350c5bc183/src/libstore/build.cc#L1841)/[group](https://github.com/NixOS/nix/blob/169edf94072c92f9a6148838c50c92350c5bc183/src/libstore/build.cc#L1849) within the [user namespace](https://github.com/NixOS/nix/blob/169edf94072c92f9a6148838c50c92350c5bc183/src/libstore/build.cc#L2074-L2091) should be [1000/100](https://github.com/NixOS/nix/blob/169edf94072c92f9a6148838c50c92350c5bc183/src/libstore/build.cc#L807-L808) by default.

**Comment by copumpkin** [comment]
Oh, awesome, thanks! What's the status on allowing chown inside builders?
