### ISSUE TITLE
Replace flakes system-specific arguments in favor of different schema/evaluation model

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [NixOS/nix#6256]
I propose nix flakes evaluation and flake.nix file format schema change.
Idea is to get rid of `$system` argument since the current approach seems to create quite a few issues such as:
1. Poor cross-compilation support.
2. `nix flake show`/`nix flake check` failing due to IFD.
3. `flake.nix` file structure complexity. (New users don't seem to comprehend flakes format well, I think in the long run format should be simplified as much as possible)

I would expect the result to be something along the lines of this:
```nix
{
    inputs.nixpkgs = github:NixOS/nixpkgs;

    # All optional
    meta = {
        description = "Cute little flake";
        supportedSystems = ["x86_64-linux"]; # Just metatada, does not impact evaluation at all
    };


    # attrsetWithFlakeArguments is expected to have arguments such as `hostSystem` and `targetSystem` which are expected to be passed via CLI/autodetect
    outputs = { self, attrsetWithFlakeArguments, nixpkgs}: {

        packages = let
            pkgs = import nixpkgs { xyz = attrsetWithFlakeArguments; };
        in {
            inherit (pkgs) coreutils;
        };
    };
}
```

> Not all attributes are system-specific, what about those?

This structure does not discriminate between system-specific arguments, this way we make everything into system-specific output.

Pros:
- While `nixosConfiguration` output currently is not system-specific - it always is system-specific due to it depending on nixpkgs.
- We can change the module's functionality based on architecture. For example 'fan control module' uses different packages depending if the module is being used on macOS or Linux
- Users can not define custom logic during packages.$system evaluation, thus evaluation speed is always consistent.
- No more nasty system-specific and modules/configurations attributes merging

> How does this change `nix flake show`/`nix flake check`

These commands would evaluate for only current system unless it is specified otherwise

**Comment by edolstra** [comment]
Duplicate (largely) of #3843.

**Comment by roberth** [comment]
Sorry to comment on a closed issue. Not sure if this response fits the discussion in #3843 well.

> * While `nixosConfiguration` output currently is not system-specific - it always is system-specific due to it depending on nixpkgs.

I think we should keep a non-system-specific section, which means that we don't merge the `system` parameter into the inputs (as you somewhat implied maybe?).

> ```nix
> {
>   inputs.nixpkgs = github:NixOS/nixpkgs;
> 
>   # All optional
>   meta = {
>     description = "Cute little flake";
>     supportedSystems = ["x86_64-linux"]; # Just metatada, does not impact evaluation at all
>   };
> 
> 
>   # attrsetWithFlakeArguments is expected to have arguments such as `hostSystem` and `targetSystem` which are expected to be passed via CLI/autodetect
>   outputs = absoluteArgs@{ self, attrsetWithFlakeArguments, nixpkgs}: {
> 
>     nixosConfigurations.my-machine = nixpkgs.nixosSystem { system = "aarch64-darwin";
>        modules = [ { environment.systemPackages = [ (self.perSystem "aarch64-darwin").hello ]; } ];
>     };
>
>     perSystem = { system, self, attrsetWithFlakeArguments, nixpkgs }: {
>        packages.hello = nixpkgs.hello.overrideAttrs(o: {
>          greeting = "Hello Nixpkgs version ${absoluteArgs.nixpkgs.sourceInfo.rev}"; });
>     };
>   };
> }
> ```

**Comment by gytis-ivaskevicius** [comment]
So the way I see it making the most sense is the whole flake itself being evaluated with system argument since it not only allows us to have support cross-compiling but also fixes existing issues such as noted above. Also, may I add a case when developers just don't care about let's say `aarch64-linux` thus making it impossible to use on these systems. 

`nixosModules`/`overlays` - being non system specific are totally fair enough but I think that it's poor design to have `nixosConfigurations` being non system-specific since it **IS** system-specific. In fact, I ran into it a while ago when I was going to run one of my existing `nixosConfigurations` on `aarch64` system.

**Comment by roberth** [comment]
> don't care about let's say aarch64-linux thus making it impossible to use on these systems.

I believe this has been brought up in the other thread.

> `nixosConfigurations` being non system-specific since it **IS** system-specific.

I now realize that I've chosen confusing terminology. There's an inversion going on: if an attrset is non-specific, that means that the attributes have to _specify_ it. Sadly, my inner wordsmith has left me at this hour.

Anyway, the way I've been using the `nixosConfigurations` attributes is to represents specific machines in the real world, relating 1:1.
If it is generic and deployable to different machines, isn't it best represented by a `nixosModules` attribute?
`nixosConfigurations` as-is is actually great for remote deployments.
