### ISSUE TITLE
Spaces before colon matter when they shouldn't

### ISSUE THREAD

**Issue by 21stce** [NixOS/nix#6269]
**Describe the bug**

I'd expect that the command syntax is similar to that of e.g. `ghci`, but in `ghci` spaces don't matter, whereas in Nix version 2.3.16 they do. 

The screenshot should say enough. 

![image](https://user-images.githubusercontent.com/100212538/158636974-2a496b06-759b-4ada-b46a-704a0c2717a5.png)

**Comment by Artturin** [comment]
the code that handles that: https://github.com/NixOS/nix/blob/fe1ad9613561ea78b6d97cf82c03d2dd77e43f69/src/nix/repl.cc#L405
