### ISSUE TITLE
Wrong owner locked in flake.lock

### ISSUE THREAD

**Issue by nmattia** [NixOS/nix#6271]
**Describe the bug**

I've updated the `nixpkgs` input in one of my projects to use my nixpkgs fork:

```nix
# flake.nix
{ 
  inputs.nixpkgs.url = "github:nixos/nixpkgs?owner=nmattia&rev=1b141cd5e6e5309e88e57fe7b4e4808898633f6b";
  ...
}
```

but `nix flake lock` seems to have stored the incorrect owner:

```
$ nix flake metadata --json | jq .locks.nodes.nixpkgs
{
  "locked": {
    "lastModified": 1647467163,
    "narHash": "sha256-gHBeM/F0fFZSnW9EZ5F6m41DMtGW3Eb2IB+qh59oyRE=",
    "owner": "nixos",
    "repo": "nixpkgs",
    "rev": "1b141cd5e6e5309e88e57fe7b4e4808898633f6b",
    "type": "github"
  },
  "original": {
    "owner": "nixos",
    "repo": "nixpkgs",
    "rev": "1b141cd5e6e5309e88e57fe7b4e4808898633f6b",
    "type": "github"
  }
}
```

What's really surprising here is that the rev (`1b141cd5e6e5309e88e57fe7b4e4808898633f6b`) is the one specified in my fork; and to clarify, [it exists on my fork](https://github.com/nmattia/nixpkgs/commit/1b141cd5e6e5309e88e57fe7b4e4808898633f6b), but [does not exist in `nixos/nixpkgs`](https://github.com/nixos/nixpkgs/commit/1b141cd5e6e5309e88e57fe7b4e4808898633f6b). But somehow Nix managed to use the correct commit in spite of it pretending it's using the wrong repo (owner). When building, it does use the correct commit from my fork. 

**Expected behavior**

I would expect nix to lock/store the correct owner in the lockfile.

**`nix-env --version` output**

```
nix-env (Nix) 2.6.0
```

---

EDIT: **I just realized my terribly silly mistake.** It should be like this:

```diff
 - inputs.nixpkgs.url = "github:nixos/nixpkgs?owner=nmattia&rev=1b141cd5e6e5309e88e57fe7b4e4808898633f6b";
 + inputs.nixpkgs.url = "github:nmattia/nixpkgs?rev=1b141cd5e6e5309e88e57fe7b4e4808898633f6b";
```

still, odd that `nix build` found the correct commit.

**Comment by cole-h** [comment]
`nix build` finds that commit on the main Nixpkgs repo because, on GitHub, all forks are stored in a way where all commits are accessible from the original repository.

**Comment by nmattia** [comment]
Ah, I see. Thanks!
