### ISSUE TITLE
Document options available to pass as "URL parameters" to binary cache URL:s

### ISSUE THREAD

**Issue by terlar** [NixOS/nix#6279]
**Is your feature request related to a problem? Please describe.**
There are a bunch of useful parameters that you can pass to the binary cache URL:s in order to affect the Nix command.

For example (compression and secret-key...):
https://github.com/NixOS/nix/blob/master/src/libstore/binary-cache-store.hh#L19-L30

**Describe the solution you'd like**
I would like some documentation for the URL parameters available to be given to binary cache stores.

Similar to how it has been documented for [S3 substituter](https://nixos.org/manual/nix/unstable/package-management/s3-substituter.html).

**Describe alternatives you've considered**
Reading the source code and tests provided for nix.

**Additional context**

**Comment by thufschmitt** [comment]
See https://github.com/NixOS/nix/issues/5467. It never made it to the documentation, but there’s a `nix describe-stores` commands that generates a markdown description of all the stores and their options.
