### ISSUE TITLE
nix-prefetch-url curl “failed writing body”

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nix#628]
nix-prefetch-url http://archive.ubuntu.com/ubuntu/pool/main/t/texlive-extra/texlive-extra_2014.20141024.orig.tar.xz

at ~60%:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 62  943M   62  586M    0     0  3894k      0  0:04:08  0:02:34  0:01:34 3923kcurl: (23) Failed writing body (591 != 1448)
/run/current-system/sw/bin/nix-prefetch-url: download of ‘http://archive.ubuntu.com/ubuntu/pool/main/t/texlive-extra/texlive-extra_2014.20141024.orig.tar.xz’ failed
```

Tried two times, same error.

**Comment by Profpatsch** [comment]
Maybe relevant: https://stackoverflow.com/questions/16703647/why-curl-return-and-error-23-failed-writing-body#16712206

**Comment by ianfarmer** [comment]
Looks like nix-prefetch-url is creating a temporary file on a temporary file system that doesn't have enough space.

According to this:
https://github.com/NixOS/nix/blob/bdc4a0b54d54146448061dd9a248212f98a9f801/perl/lib/Nix/Utils.pm#L45

the file will be written under `$TMPDIR`, `$XDG_RUNTIME_DIR`, or `/tmp`. On my system, TMPDIR is not set and XDG_RUNTIME_DIR points to `/run/user/$UID`, which is a tmpfs filesystem that is only 795M.

A workaround is to set TMPDIR or XDG_RUNTIME_DIR to /tmp or somewhere that has enough space.

**Comment by Profpatsch** [comment]
It might be that my system was full at the time. Since it happened with nobody else in the meantime, I’m going to close this.

**Comment by dundir** [comment]
Was getting this error on Ubuntu 16.10 when using sudo, running as root solved the issue.
