### ISSUE TITLE
Darwin binary tarball size regression

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#631]
The Nix 1.10 x86_64-darwin tarball is way more bloated than the Nix 1.9 tarball:
```
http://hydra.nixos.org/build/23017488/download/1/nix-1.9-x86_64-darwin.tar.bz2 => 27.04 MB
http://hydra.nixos.org/build/25489764/download/1/nix-1.10-x86_64-darwin.tar.bz2 => 218.38 MB
```
Decompressed size is 766 MB! In fact it's now significantly larger than the Linux tarballs. This is primarily caused by the inclusion of a copy of llvm (278 MB), CLTools_Executables_OSX109 (208 MB) and clang (173 MB). (It's worth noting that CLTools_Executables contains a copy clang and Perl...)

**Comment by copumpkin** [comment]
Wow, I missed this. @pikajude, any idea what's up?

I'm surprised we even get CLTools_Executables with the pure darwin stdenv...

**Comment by copumpkin** [comment]
Ah, 15.09 didn't use pure-darwin yet by default, so it was using the slightly purer darwin interim stdenv that is now gone.

**Comment by edolstra** [comment]
Now down to ~30 MB: http://hydra.nixos.org/job/nix/master/binaryTarball.x86_64-darwin#tabs-charts :-)

**Comment by copumpkin** [comment]
Yay!
