### ISSUE TITLE
Flakes UX: nix run: unusable with `--store "{remote}"`

### ISSUE THREAD

**Issue by colemickens** [NixOS/nix#6317]
**Describe the bug**

I am trying to remove my devenv-driven bash scripts by instead wrapping these scripts into derivations and exposing them via nix run.

What I'd like to do is this:
```shell
nix run '.#flash-blueline-boot' \
  --eval-store auto \
  --store 'ssh-ng://colemickens@aarch64.nixos.community' \
  --override-input mobile-nixos "${HOME}/code/mobile-nixos"
```

But what I get is:
```
ls: cannot access '/nix/store/9cr0zplqxzpwcl6blmlz5dpclh3z3mbh-flash-blueline.sh': No such file or directory
```

Despite:
```
❯ ssh colemickens@aarch64.nixos.community \
  "ls -al /nix/store/9cr0zplqxzpwcl6blmlz5dpclh3z3mbh-flash-blueline.sh"
-r-xr-xr-x 1 root root 292 Jan  1  1970 /nix/store/9cr0zplqxzpwcl6blmlz5dpclh3z3mbh-flash-blueline.sh
```

This mirrors behavior of using `--store` in other scenarios where the remote built store path is not copied back.

With `nix build` I can understand it, but not `nix run`.

#### nix version
```
nix (Nix) 2.8.0pre20220322_d5d4d98
```

**Comment by thufschmitt** [comment]
Just a side remark, but you probably don’t want to have `nix run` always copy back to the local store. For example with `--store /some/dir` you probably just want to run the thing from your chrooted store.

Maybe that could be solved by https://github.com/NixOS/nix/issues/5025 : If we’re able to differentiate the build store and the one used to store the final outputs, then you could do:

```console
nix run '.#flash-blueline-boot' \
  --eval-store auto \
  --build-store 'ssh-ng://colemickens@aarch64.nixos.community' \
  --store auto \ # Would probably be the default
  --override-input mobile-nixos "${HOME}/code/mobile-nixos"
```

**Comment by edolstra** [comment]
`nix run` does not support remote execution, and probably won't because the store abstraction doesn't support executing arbitrary commands on a store. It should probably give a nicer error message if the store is not a LocalFSStore.

**Comment by colemickens** [comment]
Huh, I missed all the replies here. I agree with @thufschmitt's assessment and appreciate the error message that was committed. Thank you!
