### ISSUE TITLE
No stable interface for copying to binary caches

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nix#6322]
There is, as far as I can tell, currently no way to populate a binary cache (flat file or S3) that can be relied on to work until further notice, since `nix-push` was removed in 6e51af80231b2a35ba3f5edffa7e235b239955a0 and `nix copy` is an unstable interface.

**Comment by edolstra** [comment]
I'll close this issue since there is not much actionable specific to `nix copy` beyond stabilizing the `nix` command.
