### ISSUE TITLE
Nixlang: how do you find all uses of a declaration?

### ISSUE THREAD

**Issue by a-m-joseph** [NixOS/nix#6325]
@Artturin [asked me](https://discourse.nixos.org/t/nixlang-how-do-you-find-all-uses-of-a-declaration/18369/2) to post a link to [this discourse thread](https://discourse.nixos.org/t/nixlang-how-do-you-find-all-uses-of-a-declaration/18369) here.

In nixlang, how exactly does one go about figuring out all the places in a codebase that reference a given identifier?

There is a longer form of the question in the discourse thread, along with some probably-totally-insane speculation about having `stdenv` be written in Haskell (which will probably cost me a lot of reputation points...)

**Is your feature request related to a problem? Please describe.**

When refactoring code in nixlang, I can't figure out "what code in this codebase references this identifier"?  In most other languages (Haskell, Coq, ML, C/C++) you can answer this question by removing the declaration and reading the compiler errors.

**Describe the solution you'd like**

A way to figure out, automatically and reliably, all the places from which a given identifier is used in a large codebase like nixpkgs.

**Describe alternatives you've considered**

The only alternative I know of is for me to keep making dumb mistakes like [this one](https://github.com/NixOS/nixpkgs/pull/165733).  I'm pretty good at making dumb mistakes.

**Additional context**

See the Discourse issue, which has a more detailed explanation.

I'm not sure which is the right place to discuss this -- here or the Discourse thread.

**Comment by vcunat** [comment]
I don't think there's anything actionable on Nix language side here.

**Comment by a-m-joseph** [comment]
Ok.
