### ISSUE TITLE
bikeshed: Nix package manager cli output and options are rather ugly. How can we fix this?

### ISSUE THREAD

**Issue by lowfatcomputing** [NixOS/nix#634]
Nix is the most compelling package manager design I have ever seen however aesthetically I think it needs improvement:
- output is extremely verbose and not easy to follow at a glance
- lack of consistency/orthogonality -- different options with overlapping semantics among commands and options
- grep is needed for searching packages (or an alias with grep)
- maybe some color etc would be nice.

I don't think it's healthy for a project to be overly concerned with backwards compatibility. It is doubtful that there are many legacy nix/nixos systems out there. However, for the sake of existing tutorials, one just has to make changes incrementally and be clear about when change is happening or has happened.

I've also posted this here (check out the comments): https://www.reddit.com/r/NixOS/comments/3jr6ye/bikeshed_nix_package_manager_cli_output_and/

**Comment by michaelsproul** [comment]
Related: https://github.com/NixOS/nix/issues/561

**Comment by vcunat** [comment]
> output is extremely verbose

I simply use `-Q` almost always and then inspect non-interleaved logs by `nix-store -l /path/to/my.drv`

I believe there's a bit more concern for backward compatibility than you anticipate. Nix is being used for over a decade now. It might be easier to completely re-design the UI into a separate tool (and some were linked in the reddit discussion already).

**Comment by davidak** [comment]
For changing the color you can use ANSI escape codes.

http://stackoverflow.com/a/5947802/2611995

Example: `printf "Nix: \033[0;31mError \033[0m25"` ('Error' is red)

**Comment by edolstra** [comment]
Closing in favor of #779 for UI improvement discussion.

Regarding grep, nix-env supports regular expressions in package matches.
