### ISSUE TITLE
Include arm64 docker images in hub.docker.com/r/nixos/nix

### ISSUE THREAD

**Issue by 3noch** [NixOS/nix#6340]
We have amd64 images but not arm64 ones. Could we easily build and push those as well?

**Comment by 3noch** [comment]
You could try this approach: https://github.com/lopsided98/nix-ros-overlay/issues/93

**Comment by garbas** [comment]
@3noch We do have arm64 images, but only for releases (those are built by hydra). For master we only build amd64. I tried using qemu for arm builds but that drove the time up, which I think is not desirable for master building.

**Comment by 3noch** [comment]
@garbas I missed that. Thank you. That's good enough I'd say.
