### ISSUE TITLE
[flakes / tryFetchGit] spaces not supported - error: "/home/user/project with space in name" is not a valid url

### ISSUE THREAD

**Issue by liketechnik** [NixOS/nix#6394]
**Describe the bug**

Spaces in flake urls are not supported, leading to issues for local flakes that are located under a path containing spaces.

**Steps To Reproduce**

1. Create temporary project directory and initialise a git repo: `mkdir "/tmp/project name with space" && cd "/tmp/project name with space" && git init`
2. Create a `flake.nix` file (content does not matter):
```nix
{
  description = "demo broken flake with space in url";
  inputs.nixpkgs.url = "github:NixOs/nixpkgs";
  inputs.flake-utils.url = "github:numtide/flake-utils";
  inputs.flake-compat = {
    url = "github:edolstra/flake-compat";
    flake = false;
  };
  outputs = { self, nixpkgs, flake-utils, flake-compat, ... }@inputs:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs {
          inherit system;
        };
      in rec {
        devShell = pkgs.mkShell {
          buildInputs = [ ];
          nativeBuildInputs = (with pkgs; [
          ]);
        };
      }
    );
}
```
3. Add `flake.nix` to repo so nix finds it: `git add flake.nix`
4. Try to enter the development environment for the repo/flake: `nix develop` and observe following error:
```shell
error: 'file:///tmp/project name with space' is not a valid URL
```

**Expected behavior**

Get the development shell for the flake.

**`nix-env --version` output**

nix-env (Nix) 2.4

**Additional context**

- I found out the issue lies withing fetchGit by using a [flake-compat](https://github.com/edolstra/flake-compat) `nix.shell` file and running `nix-shell --show-trace`:
```shell
error: 'file:///tmp/project name with space' is not a valid URL

       … while evaluating 'tryFetchGit'

       at /nix/store/4gl05i14khqxwd5c1c1pfy18401x7l52-source/default.nix:93:19:

           92|     # tree is a valid git repository.
           93|     tryFetchGit = src:
             |                   ^
           94|       if isGit && !isShallow

       … from call site

       at /nix/store/4gl05i14khqxwd5c1c1pfy18401x7l52-source/default.nix:105:42:

          104|     { lastModified = 0; lastModifiedDate = formatSecondsSinceEpoch 0; }
          105|       // (if src ? outPath then src else tryFetchGit src);
             |                                          ^
          106|

       … while evaluating anonymous lambda

       at /nix/store/4gl05i14khqxwd5c1c1pfy18401x7l52-source/default.nix:134:13:

          133|     builtins.mapAttrs
          134|       (key: node:
             |             ^
          135|         let

       … from call site

       … while evaluating the attribute 'defaultNix'

       at /nix/store/4gl05i14khqxwd5c1c1pfy18401x7l52-source/default.nix:191:5:

          190|   rec {
          191|     defaultNix =
             |     ^
          192|       result
```
- the error occurs only if the flake is located in a git repository, it does work if the directory is *not* managed with git

**Comment by liketechnik** [comment]
I'd be happy to try implementing a fix for this myself (though it may take a little longer since I can't invest too much time here :/), but I have absolutely no idea where to get started.

Maybe this is something totally out of scope if I never worked on nix before, but can somebody point me at resources about the inner structure of nix' implementation or where to get started about this? Or should I rather just visit the matrix room and ask for help over there?

**Comment by nomeata** [comment]
Is there a work-around? I was just trying to switch a `shell.nix`/`direnv`/`use nix` directory to `flake.nix`/`dir env`/`use flake`, and it seems I’m stuck on this

**Comment by blm768** [comment]
I've been able to work around this with a bind-mount in the past (into a directory with no spaces). Annoying, but it does seem to work.
