### ISSUE TITLE
Allow to choose system when running nix flake check

### ISSUE THREAD

**Issue by yajo** [NixOS/nix#6398]
**Is your feature request related to a problem? Please describe.**
Trying to set up tests for a flake, if I use flake-utils to provide multiarch, `nix flake check` will fail always with similar messages:

    error: a 'aarch64-darwin' with features {} is required to build '/nix/store/whaiyx9z56sw98nppklhiz8zw2pn4wqi-mrchefMealShallowRepo.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, kvm, nixos-test}

**Describe the solution you'd like**
Some flag like `nix flake check --current-system`.

**Describe alternatives you've considered**
Not providing multiarch.

**Comment by TLATER** [comment]
Kind of a duplicate of #4265, arguably `nix flake check` *should* evaluate multiarch if you're specifying that your outputs should run on other architectures so I'm not sure this should be done if that bug is fixed in a different way.

**Comment by yajo** [comment]
Indeed, as I have an IFD in my code. Closing as duplicate.
