### ISSUE TITLE
rebuilding RPM on Fedora 22 fails due to missing dependency

### ISSUE THREAD

**Issue by armijnhemel** [NixOS/nix#640]
I tried rebuilding the 1.10 source rpm for Fedora 21 on Fedora 22 and got the following error, which can be fixed by adding libcurl-devel as a dependency:

checking for LIBCURL... no
configure: error: Package requirements (libcurl) were not met:

No package 'libcurl' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LIBCURL_CFLAGS
and LIBCURL_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
error: Bad exit status from /var/tmp/rpm-tmp.0OVaYS (%build)

**Comment by bhipple** [comment]
This issue can probably be closed, since nix is now only released on Fedora 25 these days:
https://github.com/NixOS/nix/blob/master/release.nix#L206-L207

**Comment by armijnhemel** [comment]
And Fedora 25 is already EOL. I will try on Fedora 27 and see if that works ;-)
