### ISSUE TITLE
`nix store copy-log` doesn't seem to work at all

### ISSUE THREAD

**Issue by alyssais** [NixOS/nix#6403]
**Describe the bug**

I haven't been able to get `nix store copy-log` to work at all, and haven't found any record of anybody else doing so either.

**Steps To Reproduce**

1. `nix --extra-experimental-features nix-command log -f '<nixpkgs>' coreutils` (to make sure the local is available in the local store)
2. `nix --extra-experimental-features nix-command store copy-log -f '<nixpkgs>' coreutils --to file:///tmp/test-store`

> error: build log for '/nix/store/1w8hfs1zsi3h3lxiasmqy04xlmijix9v-coreutils-9.0.drv' is not available

**Expected behavior**

The log to be copied to the other store.

**`nix-env --version` output**

nix-env (Nix) 2.7.0

**Additional context**

n/a

**Comment by yorickvP** [comment]
`nix log` doesn't actually copy the log to the local store, it just downloads it from cache.nixos.org and shows it. 
Manually copying over the log from cache.nixos.org does work.
```
$ nix store copy-log /nix/store/lpzmq7kyr0vb76ihldr8ag7qn0a11f45-coreutils-9.0.drv --from https://cache.nixos.org
$ nix store copy-log /nix/store/lpzmq7kyr0vb76ihldr8ag7qn0a11f45-coreutils-9.0.drv --to file:///tmp/test-store
```

**Comment by edolstra** [comment]
Right, or if you want to copy in one step:
```
# nix store copy-log nixpkgs#hello --eval-store auto --from https://cache.nixos.org/ --to file:///tmp/test-store
```
