### ISSUE TITLE
nix profile upgrade '.*' fails

### ISSUE THREAD

**Issue by suhr** [NixOS/nix#6409]
**Describe the bug**

```
/home/suhr> nix profile upgrade '.*'
nix: src/libutil/util.cc:109: nix::Path nix::canonPath(nix::PathView, bool): Assertion `path != ""' failed.
```

**`nix-env --version` output**

```
/home/suhr> nix --version
nix (Nix) 2.8.0pre20220411_f7276bc
```

**Comment by srid** [comment]
I don't remember doing anything to my machine (macOS), but Nix started failing all of a sudden:

```
❯ nix
Assertion failed: (path != ""), function canonPath, file src/libutil/util.cc, line 113.
zsh: abort      nix
```

```
❯ ls -l $(which nix)
lrwxr-xr-x 62 root 31 Dec  1969 /run/current-system/sw/bin/nix -> /nix/store/i40bwvqvls2ylshs20gi83jbxagdw39l-nix-2.11.0/bin/nix
```

```
❯ sw_vers 
ProductName:            macOS
ProductVersion:         13.0
BuildVersion:           22A380
```

```
❯ nix-info
Assertion failed: (path != ""), function canonPath, file src/libutil/util.cc, line 113.
system: 0, multi-user?: no, Assertion failed: (path != ""), function canonPath, file src/libutil/util.cc, line 113.
version: 0, Assertion failed: (path != ""), function canonPath, file src/libutil/util.cc, line 113.
```

None of the older versions work either:

```
❯ /nix/store/znz4lvmda2qc0fk75pcl7hmdlknxll0c-nix-2.9.1/bin/nix
Assertion failed: (path != ""), function canonPath, file src/libutil/util.cc, line 109.
zsh: abort      /nix/store/znz4lvmda2qc0fk75pcl7hmdlknxll0c-nix-2.9.1/bin/nix
```

**Comment by arianvp** [comment]
I'm getting this error daily now on MacOS. in all nix commands. sometimes it's there. Sometimes it's not. it's really frustrating

**Comment by maschwenk** [comment]
Getting the same on Mac OS 12.6.1 after following the uninstallation steps here https://nixos.org/manual/nix/stable/installation/installing-binary.html#uninstalling

**Comment by maschwenk** [comment]
@arianvp @srid does it work when you use `Terminal.app`

**Comment by srid** [comment]
Yes, this happens only in VSCode's built terminal.

>  fixing the executable location for the direnv extension. 

Did you change it to use absolute path in user settings? @maschwenk

**Comment by maschwenk** [comment]
@srid yeah I just made it the result of `which direnv`, which was `/opt/homebrew/bin/direnv` for me

**Comment by arianvp** [comment]
Yeh seems to be an interaction of the direnv extension in vscode for me too. Odd

**Comment by maschwenk** [comment]
I don't totally understand why this suddenly popped up either 🤷🏼

**Comment by domenkozar** [comment]
Someone should wire up https://github.com/jeremy-rifkin/libassert and we'll get a reasonable assert to debug this.

**Comment by roberth** [comment]
Doesn't the assertion's `abort` call dump core to be loaded into gdb? That should contain all the info we need.

@domenkozar libassert looks interesting, but it's not guaranteed to be a good fit. It looks like it may blow up the code size. If we instead make debugging with a debugger easier, we get roughly the same benefits without increasing code size or other performance related concerns.

**Comment by shyim** [comment]
I found how to trigger it.

```
NIX_STORE= nix-shell -p go
```

**Comment by domenkozar** [comment]
Seems like we need to fix two bugs here, one direnv integration not setting wrong NIX_STORE and Nix not crashing on it.

Most likely cause at https://github.com/NixOS/nix/blob/master/src/libstore/globals.cc#L33, but not sure how it doesn't fallback to NIX_STORE_DIR variable.

**Comment by figsoda** [comment]
This line in direnv vscode extension might be causing the issue: https://github.com/direnv/direnv-vscode/blob/383b4adce10a27dc3b64df52df8c33b063e69dd1/src/extension.ts#L175

It was added after this issue was opened, but the issues seemed to hav gotten a lot more comments after the line was added, so I'm guessing the original issue was caused by something else, but this line causes the issue for the more recent ones

**Comment by pwm** [comment]
Just ran into this today and @zimbatm suggested to try to unset `NIX_STORE` which worked. In the vscode terminal do:
```
set -e NIX_STORE
direnv reload
```

**Comment by badly-drawn-wizards** [comment]
> Just ran into this today and @zimbatm suggested to try to unset `NIX_STORE` which worked. In the vscode terminal do:
> 
> ```
> set -e NIX_STORE
> direnv reload
> ```

This crashes the vscode terminal for me.
