### ISSUE TITLE
No /.config/nixpkgs/ Directory? 

### ISSUE THREAD

**Issue by BasicNoob** [NixOS/nix#6412]
I just installed Nix on my Pop_OS 21.10 system but cant find the `~/.config/nixpkgs/overlays.nix` directory for me to apply a patch.

Did I miss a step or something?

**Comment by hmenke** [comment]
Yes, you are missing that you have to create these yourself. By default there are no overlays. Please consult the documentation for details:

https://nixos.org/manual/nixpkgs/stable/#sec-overlays-lookup

**Comment by thufschmitt** [comment]
Closing, feel free to reopen if there’s anything to be done on our side
