### ISSUE TITLE
The installer_test CI job is flaky

### ISSUE THREAD

**Issue by thufschmitt** [NixOS/nix#6432]
Every once in a while, the `installer_test` job fail on master with a 404 error on the installer url (see for example https://github.com/NixOS/nix/runs/6098304154)

Looking at the CI run, it seems that the `installer` job doesn’t populate the cache as it should − cachix reports [Nothing to push - all store paths are already on Cachix.](https://github.com/NixOS/nix/runs/6097654042?check_suite_focus=true#step:11:4), which apparently isn’t the case (the installer that just got built during this job isn’t on cachix).
Since the `installer_test` job tries to fetch the installer from cachix, it then fails.

Note that this doesn’t happen deterministically, some jobs run just fine (https://github.com/NixOS/nix/runs/6091800418 for example)

@domenkozar any idea what can go wrong here?

**Comment by thufschmitt** [comment]
Oh indeed, dunno how I missed it. Sorry about that

**Comment by domenkozar** [comment]
Thanks for the clue, I think I know what's going on. Will verify later today.
