### ISSUE TITLE
Can't reach graphical user interface on nix unstable

### ISSUE THREAD

**Issue by BloomnDoom** [NixOS/nix#6491]
I'm on KDE with NetworkManager and GRUB, trying to get nixos-unstable drops me into a tty instead of the GUI

1. Upgrade to unstable channel by running `nix-channel --add https://nixos.org/channels/nixos-unstable nixos` and then `nixos-rebuild switch --upgrade` 
2. After the update is over, the restart button on KDE does not work.
3. Manually rebooting drops me into a tty
4. Trying to start sddm by `systemctl enable sddm.service` gives the error that `Unit sddm.service not found`

Nix env version : 2.8.0

Letting the system go to sleep after the update but before rebooting shows this instead of the login screen when woken up

![image](https://user-images.githubusercontent.com/104047347/166859177-adb8b1c1-0940-4a0b-b44e-a0d6bcecd87b.png)

**Comment by thufschmitt** [comment]
That part is handled by https://github.com/nixos/nixpkgs , this repo is only for Nix-the-package-manager, so you’d better reopen the issue there.

(Sorry, I’d like to just transfer it, but I don’t have the rights to do so)

**Comment by BloomnDoom** [comment]
Ah i'll do that, thanks!
