### ISSUE TITLE
nix-env -u --leq fails on Mac OS X 10.10

### ISSUE THREAD

**Issue by retrry** [NixOS/nix#651]
```
checking for a sed that does not truncate output... /nix/store/9xigs7k6brr6695p6l035w4g31yrhkjb-gnused-4.2.2/bin/sed
checking build system type... x86_64-apple-darwin14.5.0
checking host system type... x86_64-apple-darwin14.5.0
checking for the canonical Nix system name... x86_64-darwin
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/private/var/folders/j7/4_0kh_7n6574vdxv_q0b4_1h0000gn/T/nix-build-nix-1.10.drv-0/nix-1.10':
configure: error: C compiler cannot create executables
See `config.log' for more details
builder for ‘/nix/store/gm2kl5pp77c7bp9bsipfr9n6g3g793as-nix-1.10.drv’ failed with exit code 77
error: build of ‘/nix/store/gm2kl5pp77c7bp9bsipfr9n6g3g793as-nix-1.10.drv’ failed
```

I found an issue similar to this: #382 
Maybe it is connected that just a few days ago I got XCode 7.0 update?

**Comment by retrry** [comment]
This error was fixed for me and for one other guy on reddit[1] by moving from nix-channel to own cloned nixpkgs repo, so maybe it is just a bad revision, that is available for installer atm? If that is the case should this bug be closed?

[1] https://www.reddit.com/r/NixOS/comments/3mkdr1/nix_fails_to_compile_packages_on_osx/cvfuz4l

**Comment by mpscholten** [comment]
> so maybe it is just a bad revision

We could test this by checking out the commit of nixpkgs which is bundled with the latest nix release, right?

> Maybe it is connected that just a few days ago I got XCode 7.0 update?

Because using `stdenvDarwinPure` also fails and ([if the wiki entry is correct](https://nixos.org/wiki/Nix_on_OS_X)) the pure standard env does not depends on XCode, I guess it's not because of the new XCode release.

BTW: I'm the guy from the reddit post above.

**Comment by retrry** [comment]
@mpscholten I've tested this, by removing everything connected to Nix from my OS X installation and I installed it again. This time before doing anything - I did nix-channel --update (at first it gave me error: unable to check ‘https://nixos.org/channels/nixpkgs-unstable’, so I've removed nixpkgs channel and added http one instead https so it could update) and after that I could install everything :)
From my install log it seems that the installation script just fails to update nixpkgs channel and that is the cause for failures:
```
$ curl https://nixos.org/nix/install | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1332  100  1332    0     0   1468      0 --:--:-- --:--:-- --:--:--  1468
unpacking Nix binary tarball for x86_64-darwin from `https://nixos.org/releases/nix/nix-1.10/nix-1.10-x86_64-darwin.tar.bz2'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 27.4M  100 27.4M    0     0  1771k      0  0:00:15  0:00:15 --:--:-- 2117k
performing a single-user installation of Nix...
directory /nix does not exist; creating it by running ‘?? using sudo
copying Nix to /nix/store........................
initialising Nix database...
creating /Users/retrry/.nix-profile
installing ‘nix-1.10’
building path(s) ‘/nix/store/bfhj0nrjnfwhph4fxzz12zlsanj5bvrm-user-environment’
created 7 symlinks in user environment
installing ‘cacert-20140715’
building path(s) ‘/nix/store/dv9in93k3xgyyj8wcrg6nzhnf3f4qqyf-user-environment’
created 9 symlinks in user environment
/nix/store/1rn8whr57nnkcfaqf3v0d741prfcd8ky-nix-1.10/bin/nix-channel: unable to check ‘https://nixos.org/channels/nixpkgs-unstable’
```

**Comment by retrry** [comment]
Anyway, it works now so I'm closing the issue.

**Comment by mpscholten** [comment]
I guess this is also the cause if #650. Shouldn't we update the installer to include the http channel then?

**Comment by andrewrynhard** [comment]
This is still happening. Perhaps this should still be open? A clean install process would be nice.
