### ISSUE TITLE
"Unrecognized archive format" for GitHub flakes since 7a3d5b2ff0e39ae0d7b393f454671a08da56776b

### ISSUE THREAD

**Issue by NobbZ** [NixOS/nix#6527]
**Describe the bug**

Since 7a3d5b2ff0e39ae0d7b393f454671a08da56776b the following error occurs on any nix command that needs to fetch from GitHub:

```
$ ./result/bin/nix run --option tarball-ttl 0 github:nixos/nixpkgs/master#hello
error: failed to open archive: Unrecognized archive format
(use '--show-trace' to show detailed location information)
```

**Steps To Reproduce**

1. Build any commit that includes the one mentioned above
2. `./result/bin/nix run --option tarball-ttl 0 github:nixos/nixpkgs#hello`
3. See error

**Expected behavior**

Archive would be downloaded correctly and the containing flake gets evaluated.

**`nix-env --version` output**

```
$ nix-env --version
nix-env (Nix) 2.9.0pre20220510_eb957ad
```

**Additional context**

**Comment by NobbZ** [comment]
I think I see where it comes from, the second chunk around lines 250 introduced a wrong URL template it seems, trying to fix locally, will create a PR if it fixes the issue.

**Comment by LucianU** [comment]
I'm seeing this issue on a fresh install of Nix.

```
lucian@machine:~$ nix-env --version
nix-env (Nix) 2.9.2
```

**Comment by jamesreprise** [comment]
Also experienced this on a fresh install of NixOS 22.11. Was able to fix it by creating a '.nix-channels' file in my home directory with the following contents:
```
https://nixos.org/channels/nixos-22.11 nixos
https://nixos.org/channels/nixos-22.11 nixpkgs
```

Initially I got the following error:
```
[james@primetime:~]# nix-shell -p git
error: failed to open archive: Unrecognized archive format
(use '--show-trace' to show detailed location information)
```
`--show-trace` wasn't much help, I got the following:
```
[james@primetime:~]# nix-shell -p git --show-trace
error: failed to open archive: Unrecognized archive format

       … while realising the context of a path

       at «string»:1:18:

            1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (git) ]; } ""
             |                  ^

       … while evaluating anonymous lambda

       at «string»:1:1:

            1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (git) ]; } ""
             | ^

       … from call site
```

Still unclear why this happened. My $NIX_PATH does contain a `nixpkgs=...` but this doesn't seem to change anything.
