### ISSUE TITLE
GitHub flake URI scheme refuses valid branch identifiers

### ISSUE THREAD

**Issue by schuelermine** [NixOS/nix#6534]
**Describe the bug**

Some branch identifiers accepted w/o warning by Git are rejected when given as refs for the GitHub flake URI scheme, whether after the second slash or as a query parameter.

Specifically, `blender--desktop+proper-overlay` is rejected but accepted by both Git and GitHub.

**Steps To Reproduce**

1. Create a GitHub repository
2. Create a branch named `blender--desktop+proper-overlay`
3. Create a flake
4. Create an input whose URI references your GitHub repository at the branch `blender--desktop+proper-overlay`, e.g.:
    `"github:maxmFusilQooper/myFantasticDinosaur/blender--desktop+proper-overlay"`

**Expected behavior**

The repository at that branch is pulled in and used for Flake evaluation.

**`nix-env --version` output**

```
nix-env (Nix) 2.9.0pre20220505_f4102de
```

**Additional context**

The repository was https://github.com/schuelermine/nix-warez, a fork of https://github.com/edolstra/nix-warrez.

The error message was:

```
error: URL 'github:schuelermine/nix-warez?ref=blender--desktop%2Bproper-overlay&dir=blender' contains an invalid branch/tag name
```

**Comment by schuelermine** [comment]
Note that using `%2B` to URL-encode the `+` does *not* resolve the issue.

**Comment by thufschmitt** [comment]
Indeed, the [pattern used to check for that](https://github.com/NixOS/nix/blob/51d13c43c135bd337153eb19293458fd5441eb06/src/libutil/url-parts.hh#L26) seems to be too restrictive (the actual syntax allowed is described [here](https://git-scm.com/docs/git-check-ref-format))

**Comment by teto** [comment]
happened to me when I tried to reference https://github.com/NixOS/nixpkgs/pull/272350 from my flake

**Comment by thufschmitt** [comment]
@teto (or anyone else), would you care trying to update the regex linked from https://github.com/NixOS/nix/issues/6534#issuecomment-1129809605 to see whether that fixes the issue?
