### ISSUE TITLE
Flake template: UX flow for conflicts with existing files

### ISSUE THREAD

**Issue by tennox** [NixOS/nix#6542]
**Is your feature request related to a problem? Please describe.**
When want to initialize an existing project with a nix flake template, and it contains a file that exists already (common example: `.gitignore`), I might see the message:
```
error: refusing to overwrite existing file '/project/.gitignore'
```
but have to manually open the template's git page/source, and examine the file(s).
Also, other template files will not be copied after encountering the first error.

**Describe the solution you'd like**
For `.gitignore`, appending would be great, for other cases probably not - so a decent first step might be to add to [the console message](https://github.com/NixOS/nix/blob/master/src/nix/flake.cc#L761) a link to the file - e.g.:
```
error: refusing to overwrite existing file '/project/.gitignore' - please merge manually with: /nix/store/ascsd-template/.gitignore
```
And the script should continue copying the other files

**Describe alternatives you've considered**
- do it manually every time
- add the possibility to add a script which runs after template adding (overkill for this, but maybe good for other issues, e.g. https://github.com/NixOS/nix/issues/4017)

**Comment by thufschmitt** [comment]
That sounds like a good and cheap idea indeed :)

**Comment by tennox** [comment]
@thufschmitt Thanks a bunch!
While this works well, I just realized that the script will stop on the first conflicting file - so for this idea to work it would still need to continue copying the other template files.
