### ISSUE TITLE
Nix shouldn't bundle md5/sha1/sha256 from OpenSSL

### ISSUE THREAD

**Issue by Mathnerd314** [NixOS/nix#655]
Instead, it should use the functions that OpenSSL provides:
https://www.openssl.org/docs/manmaster/crypto/EVP_md2.html

Also Nix can support SHA224, SHA384, and SHA512, plus SHA-3 if/when it is implemented in OpenSSL.

**Comment by edolstra** [comment]
Note that we already use the functions from OpenSSL if Nix is linked against OpenSSL. See https://github.com/NixOS/nix/blob/master/src/libutil/local.mk#L9.

**Comment by vcunat** [comment]
I see it linked against openssl by default in nixos/nixpkgs.

**Comment by Mathnerd314** [comment]
Interesting. Is there any reason for OpenSSL to be optional instead of required?

**Comment by Mathnerd314** [comment]
OpenSSL is required now: https://github.com/NixOS/nix/commit/a6ca68a70c3bc0b2e6abad70346c99642a896f9f
And looking around there's no bundled hash algorithms anymore. So this is resolved.
