### ISSUE TITLE
Keeping system up to date should not require huge downloads and heavy rebuilds almost every week

### ISSUE THREAD

**Issue by alexeymuranov** [NixOS/nix#6559]
**Is your feature request related to a problem? Please describe.**
Executing `nixos-rebuild boot --upgrade` often causes gigabytes of download and space and time consuming rebuild, which should be followed by time consuming garbage collection. For me, this looks like a substantial disadvantage compared to other distros, and a serious usability problem on older hardware.

**Describe the solution you'd like**
I do not know if a solution is possible, or if such deep rebuilds when routinely updating NixOS are inevitable by design.

I wish a NixOS system could be divided into interacting components which could be quickly and independently updated.

**Describe alternatives you've considered**
I wonder if I am using NixOS incorrectly.

**Additional context**
After 6 years of using NixOS as my main OS, i think i am going to switch to a Debian based OS because of this problem. I wonder if this issue could be among main obstacles to general adoption of NixOS.

**Comment by voobscout** [comment]
Unfortunately, there's a misconception about nixos as a single system personal distro. Unsure as to why though.
The reality of it is that as a user and consequently a maintainer of your own nix code, you'd need all the underlying infrastructure - hydra build farm and binary cache. This fact of life is usually discovered very quickly by the user.
The upside is alot more sanity with your own configs/systems.
The trade-off is the increased maintenance and the need for a build farm.

Here, for myself, I chose sanity at the expense of time/effort.

The people of nix/nixos are kind enough to 'eat their own dogfood', so taking a look at how they build and operate their machinery is a great way to understand the scope of your own requirements.

Imho, this should have been in docu, like the big red sign "DON'T PANIC!" - ie. once you want to customize, modify and add your own packages/code, please take a look at our efforts in that area. While this seems like a very obvious thing to do, some folks seem to miss it.

Somehow, declarative over any type of convergent config, including containerized shennanigans, seems to win the argument rather decisively.

I'm unsure if I use nix/nixos/nixpkgs correctly either, I just mimicked some parts of those projects infrastructure and for maintaining a few dozen personal/family/friends/embedded devices, while keeping relatively sane and almost mono-languaged code base, it has been worth it for me.

2cents.(tm)

**Comment by edolstra** [comment]
> The reality of it is that as a user and consequently a maintainer of your own nix code, you'd need all the underlying infrastructure - hydra build farm and binary cache. This fact of life is usually discovered very quickly by the user.

FWIW, I don't run my own Hydra build farm and binary cache. So I don't think this is a correct statement.

Closing this since there is not much actionable here. The disk space / rebuild requirements are pretty inherent to Nix, e.g. a glibc update in Nixpkgs will cause a rebuild/redownload of everything that depends on it, and there is not much we can do about that.
