### ISSUE TITLE
Rename chroot builds to a more neutral term

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#656]
While it is true that Linux builds use `chroot`, they also make extensive use of Linux namespaces and other isolation mechanisms.

We also recently added support for isolated builds to Darwin, and although work is still in progress to enable the pure Darwin stdenv to work properly, the functionality is already in Nix and doesn't use `chroot` at all.

Given that build isolation/security/auditability is IMO a major selling point of Nix vs. other tools, I think we should pick a better name that doesn't evoke the widespread knee-jerk "but `chroot` is insecure" reaction, and that also fits the actual process better.

Some proposals:
* container builds: feels a little forced, but allows us to ride some of the hype around containers these days; less accurate for Darwin, but not super misleading
* sandboxed builds: simple, neutral
* isolated builds: even more neutral
* jailed builds: evoke good connotations from BSD jails, make it clear that the measure is intended for security

We would also maintain a deprecated alias for the Nix configuration option for a while after renaming it.

See https://github.com/NixOS/nix/issues/179#issuecomment-144057307 for more context.

@vcunat @edolstra @lethalman @benley

**Comment by vcunat** [comment]
I'll try to create a PR.

**Comment by vcunat** [comment]
I think I've got it, but I want to re-read it later to decrease the chance of introducing mistakes. https://github.com/NixOS/nix/compare/master...vcunat:p/sandbox-rename?expand=1

**Comment by edolstra** [comment]
@vcunat No need to rename internal identifiers - that just increases code churn unnecessarily.

**Comment by vcunat** [comment]
I thought it would make the code clearer, but I can undo those parts easily.

**Comment by vcunat** [comment]
I finished re-reading it anyway, in case you wanted to keep internal and external terminology consistent. A minimal version, only renaming user-facing stuff: https://github.com/NixOS/nix/compare/master...vcunat:p/sandbox-rename-minimal?expand=1
