### ISSUE TITLE
nix-mode.el confuses '/*' as comments on multiline strings

### ISSUE THREAD

**Issue by utdemir** [NixOS/nix#662]
When you put a `/*` inside of a multiline string, it assumes the rest of the code is comment.

```
stdenv.mkDerivation {
  name = "foo";
  src = ./.;
  buildPhase = ''
    # copy everything from bar
    cp -rv {bar}/* .

    #do something else 

    this_isnt_a_comment
  '';
}
```

![screenshot](http://s18.postimg.org/i83xvn8nd/Screen_Shot_2015_10_13_at_11_39_33.png)

**Comment by edolstra** [comment]
Yes, this is a long-standing annoyance, but fixing it exceeds my elisp skillz.
