### ISSUE TITLE
shebang size limit and custom install location

### ISSUE THREAD

**Issue by roblabla** [NixOS/nix#664]
I recently attempted installing nix in a custom install location (/Volumes/LIBFTBLABLA/mac/nix/store). The problem is, several of nix's script have huge shebang lines which break the 512 character limit mac enforces on the shebang, leading to the shebang being ignored and the script malfunctioning. The scripts in question reside in https://github.com/NixOS/nix/tree/master/scripts.

I have made a temporary patch to fix my imminent problem, which can be found at https://gist.github.com/anonymous/3ec0e019763e9ec04ce0 . It simply embeds the offending scripts into a bash script, thus not being limited by the shebang. I am using it locally, and it seems to be working fine.

`clever` on irc suggested a better solution : 

```
<clever> roblabla: maybe a directory containing all of the modules (as symlinks) so you only need one -I ?
<clever> roblabla: should be trivial, create a derivation that takes an array of perl deps, and returns a directory filled with symlinks
<clever> so your replacing a list of store paths with 1 store path
<clever> nix does the same thing to keep PATH sane
<clever> roblabla: you may be able to just reuse the same function that builds system-path
```

**Comment by vcunat** [comment]
Related: https://github.com/NixOS/nixpkgs/issues/10854 and linked stuff.

**Comment by domenkozar** [comment]
Related https://github.com/shlevy/long-shebang

**Comment by edolstra** [comment]
This issue will go away as part of #341.

**Comment by vcunat** [comment]
... but I don't think it will help much, as the same nixpkgs issue will remain.
