### ISSUE TITLE
error: the string '...' is not allowed to refer to a store path

### ISSUE THREAD

**Issue by yu-re-ka** [NixOS/nix#6647]
**Describe the bug**

I'm getting an eval error for an expression that used to evaluate and I don't exactly know why

**Steps To Reproduce**

```
$ git clone https://git.neulandlabor.de/Yuka/c3h-nixfiles/
$ cd c3h-nixfiles
$ git checkout f8686374176d7875846a0ee71a2c2890ef7d4a85
$ nix-instantiate "<nixpkgs/nixos>" -A config.system.build.toplevel -I "$(nix-build nix/sources-dir.nix --no-out-link)" -I "nixos-config=$PWD/hosts/nuc/configuration.nix"
error: the string 'nixos-system-nuc-22.05pre-git' is not allowed to refer to a store path (such as '')
```

**Expected behavior**

This should evaluate, or throw a more helpful error. It did evaluate with 2.3, and users expect their old Nix expressions that used only stable features to evaluate with new versions of Nix.

**`nix-env --version` output**

nix-env (Nix) 2.9.0

**Additional context**

The same expression was already failing to build in the initial 2.4 release, which got fixed in 2.5: #5410
Overall this is the behaviour with different Nix versions:

nix 2.3: ✅ 
nix 2.4: `error: store path '/nix/store/dbfkhagz0s9246jgahm913vypi0sv6qf-sources' is not allowed to have references`
nix 2.5: ✅ 
nix 2.6-2.8: `error: the string 'nixos-system-nuc-22.05pre-git' is not allowed to refer to a store path (such as '/nix/store/8x56z90r0h9iwgba93hy2iws4z9rkrgl-nixpkgs-src')`
nix 2.9: `error: the string 'nixos-system-nuc-22.05pre-git' is not allowed to refer to a store path (such as '')`

I tried to come up with a simpler example to reproduce it, but I don't understand the underlying issue enough. It would be great if this could be added as a test so that future Nix versions don't break the behavior again.

**Comment by thufschmitt** [comment]
I'm not sure what is the right behavior here, but at a glance the issue comes from the fact that your `nixpkgs` is itself a derivation output (the output of the `runCommand` call in `nix/sources-dir.nix`), and that's causing some troubles.

**Comment by yorickvP** [comment]
Small testcase:
```nix
let
  nixpkgs = fetchTarball {
    url = channel:nixos-22.05;
  };

  pkgs = import nixpkgs { overlays = []; };

  a = pkgs.runCommand "a" {} "echo foo > $out";
  b = pkgs.runCommand "b" {} "ln -s ${a} $out";
  x = builtins.readFile b;
in
{ "foo\n" = "bar";}.${x}
```

note that it works if you replace `ln -s` with `cp`, so this seems like a nix bug

**Comment by yu-re-ka** [comment]
bisected to https://github.com/NixOS/nix/commit/c66865dff1747ecd55915ef8c549dc1a088ff168

**Comment by yorickvP** [comment]
I'm not really sure what to do about this. Propagating the context across readFile makes sense - https://gist.github.com/yorickvP/bad13c33a23b7fbd196b609acaaad5d2 - , and so does disallowing context in fromTOML and fromJSON.

Allowing context in things like `compareVersions` and attribute `.${}` potentially makes sense, though, we could change that.

**Comment by hyperfekt** [comment]
Can we not allow context in fromTOML and fromJSON by attaching it to all strings contained in the resulting value?

**Comment by thufschmitt** [comment]
> Can we not allow context in fromTOML and fromJSON by attaching it to all strings with a path the attached context represents?

In theory that would be lossy ‑ because you'd need to also attach the context to the other type of values, which isn't possible in Nix.
Maybe in practice that could be worth having though. Not sure

**Comment by ncfavier** [comment]
I'll cross-post my question https://github.com/NixOS/nixpkgs/issues/175125#issuecomment-1303220143 in here: does it make sense for a string to have context for a path that does not appear in the string?
