### ISSUE TITLE
nix-shell: Search parent directories for default.nix/shell.nix

### ISSUE THREAD

**Issue by the-kenny** [NixOS/nix#665]
It would be very nice if `nix-shell` would search for `default.nix` or `shell.nix` like git searches for `.git`. This would allow users to run `nix-shell` from every directory in a project without having to specify the path. 

My specific use case is `M-x compile` in Emacs: I want to set it to something along the lines of `nix-shell --command 'cargo build'`, but running this from a file in the `src/` directory fails because `default.nix` is in the root-directory of the project.

**Comment by Ericson2314** [comment]
I'm for this, and probably for making all tools that look for a file in the current directory do this for consistency. One can still do `nix-<tool> ./` to recover the old behavior (useful in scripts).

**Comment by erikryb** [comment]
What is the status of this? I'm very for this. Also, it would be convenient if there is an option that makes nix-shell update its config every time the directory changes. That way one could seamlessly change between projects without having to run nix-shell again.

**Comment by the-kenny** [comment]
Erik Rybakken <notifications@github.com> writes:

> What is the status of this? I'm very for this. Also, it would be convenient if there is an option that makes nix-shell update its config every time the directory changes. That way one could seamlessly change between projects without having to run nix-shell again.

To me, direnv[1] is the perfect solution for this: With a .envrc
containing 'use nix' it will evaluate shell.nix in the current or some
parent directory and apply all environment variables generated by it,
generating the same effect as nix-shell without spawning a new shell.

[1]: https://github.com/direnv/direnv

**Comment by erikryb** [comment]
Awesome, this is exactly what I imagined. Thanks!

**Comment by tomberek** [comment]
Implemented with flakes (better would be to have this for all files.....): https://github.com/NixOS/nix/commit/b6cc0a704d8c1432e230ff65d4b74ea7114a730b otherwise lorri/direnv approach this functionality.
