### ISSUE TITLE
sourcehut flake input stopped working

### ISSUE THREAD

**Issue by wahjava** [NixOS/nix#6650]
**Describe the bug**

Input of type `sourcehut` git repository stopped working lately, while equivalent `git+https` works fine.

**Steps To Reproduce**

```
❯ mkdir /tmp/f
❯ cd /tmp/f
❯ cat >/tmp/f/flake.nix <<EOF
{
  inputs = { ff-overlay = { url = "sourcehut:~abbe/ff-overlay/mainline"; }; };
  outputs = { inputs, ... }: { };
}
EOF
❯ nix flake lock --recreate-lock-file --show-trace
error: in 'sourcehut:~abbe/ff-overlay/mainline', couldn't find ref 'mainline'

       … while fetching the input 'sourcehut:~abbe/ff-overlay/mainline'

       … while updating the flake input 'ff-overlay'

       … while updating the lock file of flake 'path:/tmp/f?lastModified=1654934958&narHash=sha256-d5my7Tnc39FLi6C1X1dqJrPEq9KshYoXm6p2QyY8OqM='

❯ curl -s https://git.sr.ht/\~abbe/ff-overlay/info/refs
7e6763635ec34443d04a640f3a0f41d45161914e	refs/heads/mainline

❯ git clone https://git.sr.ht/\~abbe/ff-overlay
Cloning into 'ff-overlay'...
remote: Enumerating objects: 482, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 482 (delta 10), reused 0 (delta 0), pack-reused 464
Receiving objects: 100% (482/482), 184.70 KiB | 327.00 KiB/s, done.
Resolving deltas: 100% (306/306), done.
❯ git -C ff-overlay rev-parse HEAD
7e6763635ec34443d04a640f3a0f41d45161914e
❯ git -C ff-overlay branch |more
* mainline
```

**Expected behavior**

Flake lock file should have been updated

**`nix-env --version` output**

```
❯ nix-env --version
nix-env (Nix) 2.9.0
```

**Additional context**

**Comment by thufschmitt** [comment]
@misterio77 any idea what might be happening here?

**Comment by wahjava** [comment]
`HEAD` and commitid works, but not the branch name.

**Comment by Misterio77** [comment]
Hey folks!

Since https://github.com/NixOS/nix/commit/345a8ee0cb56775c57c3b7da99b0726290241e18, I was using regex to match both heads and tags. But I'm not sure if, as of later commits, `ref_uri` is still being treated as a regex pattern?

**Comment by wahjava** [comment]
> Hey folks!
> 
> Since [345a8ee](https://github.com/NixOS/nix/commit/345a8ee0cb56775c57c3b7da99b0726290241e18), I was using regex to match both heads and tags. But I'm not sure if, as of later commits, `ref_uri` is still being treated as a regex pattern?

Could it be that you needed [some special flag for extended regexp match](https://en.cppreference.com/w/cpp/regex/basic_regex) ?

**Comment by Misterio77** [comment]
Nope. It seems 9bf296c970bf33b7ed53d7e2d8fbe44197482518 just [replaced regex matching with ==](https://github.com/NixOS/nix/commit/9bf296c970bf33b7ed53d7e2d8fbe44197482518#diff-be2f63dc22d73bd86ee70820979ee54ff2bb5cef76e3bbb53a673fddfd2a1b5cR402). 

The test didn't catch it because it sadly just covered HEAD resolving, but not branches or tags. Opening up a fix right now.
