### ISSUE TITLE
error: expected a string but got a thunk when importing a flake input

### ISSUE THREAD

**Issue by yajo** [NixOS/nix#6659]
**Is your feature request related to a problem? Please describe.**
While developing https://gitlab.com/moduon/devsecops/precommix, [I wanted a way to force the flake to get a specific input version depending on how the Copier template is updated](https://gitlab.com/moduon/devsecops/precommix/-/commit/7edafd76f56648b480739fa09c0e9256992012ac).

**Describe the solution you'd like**
I thought it would be pretty simple to add a `.precommix.nix` file, updated by the Copier template, and then just add to the flake:

```nix
inputs.precommix.url = import ./.precommix.nix;
```

However, if you put such import in a flake input, you get this error:

    error: expected a string but got a thunk at /nix/store/jymd3dfmwvv0k7f2nbrqgf4pp9w6ax4s-source/flake.nix:10:3

**Describe alternatives you've considered**
Not sure... using `builtins.getFlake`?

**Additional context**
Precommix combines the best parts of pre-commit and nix.

To make sure we get full reproducibility, I want to share the same commit between the `.pre-commit-config.yaml` file and `flake.lock` when updating the template.

To manage template I use https://copier.readthedocs.io/ because it supports smart updates.

**Comment by dasJ** [comment]
Seems like a duplicate of #4945

**Comment by yajo** [comment]
Indeed.
