### ISSUE TITLE
Possible to impurely read $HOME in flakes by using `~`-paths

### ISSUE THREAD

**Issue by sersorrel** [NixOS/nix#6684]
**Describe the bug**

The nix language supports using paths that start with `~/`, which are relative to the user's home directory. It looks like this is implemented by using the $HOME environment variable:

```console
$ HOME=/tmp nix eval --expr '~/foo'
/tmp/foo
```

However, this functionality isn't disabled when evaluating a flake, meaning that flakes can produce different results depending on what $HOME is set to at evaluation time.

**Steps To Reproduce**

flake.nix:

```
{
  description = "A very basic flake";
  outputs = { self, nixpkgs }: {
    devShells.x86_64-linux.default = nixpkgs.legacyPackages.x86_64-linux.mkShell {
      shellHook = ''
        echo my path is: ${toString ./.}
        echo your home directory is: ${toString ~/.}
      '';
    };
  };
}
```

If I run `nix develop` as two different users, the flake prints different home directories:

```console
$ nix develop
my path is: /nix/store/c6c50m39qyfb94iix44352a8pj3yz22d-source
your home directory is: /home/ash
```

```console
$ sudo nix develop
[sudo] password for ash:
my path is: /nix/store/c6c50m39qyfb94iix44352a8pj3yz22d-source
your home directory is: /root
```

**Expected behavior**

Since `nix eval --expr 'builtins.getEnv "HOME"'` produces the empty string unless `--impure` is used, I would expect `~`-paths to be disallowed in flakes.

**`nix-env --version` output**
```
nix-env (Nix) 2.8.1
```

**Additional context**

I had a brief look through public flakes on github that might be affected by this (with the query `path:flake.nix " ~/"` in github code search), and I could only find one, kmein/niveum:

https://github.com/kmein/niveum/blob/db7cb8c74c5157b48c8ca9f95f4885f811284357/flake.nix#L96

This is a very similar example to what led me to realise this fact in the first place – I was running `sudo nixos-rebuild` and was confused why something using a `~/`-path wasn't working as I expected, until I realised that probably it was evaluating to `/root/...` rather than `/home/ash/...`.

**Comment by martin-braun** [comment]
@thufschmitt I'd like to keep my HM configuration pure, but the only way to find my HM repo is using `~/.config/home-manager` which makes the config impure, rightfully. How could I resolve a path without pointing to the store using Nix Flakes?

I want `config.lib.file.mkOutOfStoreSymlink ./home/.config/weechat;` to point to my repo, not the store. The resulting target should not become write-protected, the resulting source should not be within the store, but within my repo. 

Is this possible without breaking purity?

**Comment by thufschmitt** [comment]
> How could I resolve a path without pointing to the store using Nix Flakes?

In the specific HM case, you should be able to use `config.home.homeDirectory` which is set by home-manager and points to your home-dir (if I understood your issue properly)

**Comment by ncfavier** [comment]
Obviously you cannot purely depend on the flake's location on your filesystem, which may change across evaluations or not exist at all (consider `nix build github:me/myconfig`)
