### ISSUE TITLE
Docker Hub page links to old repo

### ISSUE THREAD

**Issue by WhyNotHugo** [NixOS/nix#6705]
**Describe the bug**

https://hub.docker.com/r/nixos/nix/

On the right, this links to https://github.com/NixOS/docker, which is deprecated in favour of this repo.

**Expected behavior**

Link should point to this repo.

**Additional context**

It's likely that the link needs to be fixed on Docker's website, no via the image itself.

**Comment by abathur** [comment]
I think this must've been fixed over the past year. I don't see any such link, at least. Happy to reopen if I'm mistaken.
