### ISSUE TITLE
Nix can't install

### ISSUE THREAD

**Issue by bobrolov** [NixOS/nix#6726]
**Describe the bug**

I tried install nixos via sh <(curl -L https://nixos.org/nix/install)
os: MacOS Monterey 12.4

**Steps To Reproduce**

1. terminal: sh <(curl -L https://nixos.org/nix/install)
all yes, input pwd for sudo

**Expected behavior**

nix installed

**Actual behavior**

output:
---- oh no! --------------------------------------------------------------------
Jeeze, something went wrong. If you can take all the output and open
an issue, we'd love to fix the problem so nobody else has this issue.

:(
[install_out.txt](https://github.com/NixOS/nix/files/8986087/install_out.txt)

**Comment by abathur** [comment]
You'll have to follow the uninstall instructions before reinstalling it: https://nixos.org/manual/nix/stable/installation/installing-binary.html#macos

**Comment by addy** [comment]
Oops, my bad. Logged one #6744

**Comment by bobrolov** [comment]
> You'll have to follow the uninstall instructions before reinstalling it: https://nixos.org/manual/nix/stable/installation/installing-binary.html#macos

Fully uninstalling for macos and clean new install working well! Thanks!
