### ISSUE TITLE
fetchTree is not documented

### ISSUE THREAD

**Issue by symphorien** [NixOS/nix#6728]
the nix manual only mentions fetchTree in release notes.

**Comment by elikoga** [comment]
Looking into this: `nix __dump-builtins` doesn't do the right thing apparently

**Comment by elikoga** [comment]
Found the fixme: https://github.com/NixOS/nix/blob/6cb41288ac8df00328865f4c66c324452e5a961c/src/libexpr/primops/fetchTree.cc#L185

**Comment by elikoga** [comment]
Seems like this is a dupe of #5463
