### ISSUE TITLE
System dependent `narHash` in flake.lock

### ISSUE THREAD

**Issue by lovesegfault** [NixOS/nix#6731]
**Describe the bug**

I've been noticing an odd behavior where if I update my `flake.lock` on my `aarch64-darwin` host, I get a different `narHash` than if I do it on an `x86_64-linux` one.

**Steps To Reproduce**

1. `git clone https://github.com/lovesegfault/nix-config`
2. `cd nix-config`
3. `git checkout 5dad1c5138074c57fe32ba8979267be6c969858a`
4. `nix flake lock --recreate-lock-file`
5. Depending on host:
  * aarch64-darwin
    ```
    warning: updating lock file '/Users/bemeurer/src/nix-config/flake.lock':
    • Updated input 'nixpkgs':
        'github:NixOS/nixpkgs/c3d95a02e904e1ef9bb78c59d36eadc15e3428b7' (2022-06-26)
      → 'github:NixOS/nixpkgs/c3d95a02e904e1ef9bb78c59d36eadc15e3428b7' (2022-06-26)
    ```

  * x86_64-linux
    [no change]

  * aarch64-linux
    [no change]

**Expected behavior**

The narHash shouldn't change since it's already correct.

**`nix-env --version` output**
```
nix-env (Nix) 2.9.1
```

**Comment by tomberek** [comment]
My first guess would be something like case-sensitive filesystem or git operations on OSX vs linux.

**Comment by lovesegfault** [comment]
Ah, yes:

https://github.com/NixOS/nixpkgs/issues/179272

https://github.com/NixOS/nix/issues/1885
