### ISSUE TITLE
building `lazy-options.json` fails (`NIX_STORE_DIR` usage broken?)

### ISSUE THREAD

**Issue by zseri** [NixOS/nix#6732]
**Describe the bug**
```
building '/nix/store/ycczkwghxnz66qcvk244n22igy5crq9a-lazy-options.json.drv'...
lazy-options.json> warning: '/nix' does not exist, so Nix will use '/homeless-shelter/.local/share/nix/root' as a chroot store
lazy-options.json> error: creating directory '/homeless-shelter': Permission denied
lazy-options.json> Cacheable portion of option doc build failed.
lazy-options.json> Usually this means that an option attribute that ends up in documentation (eg `default` or `description`) depends on the restricted module arguments `config` or `pkgs`.
lazy-options.json> Rebuild your configuration with `--show-trace` to find the offending location. Remove the references to restricted arguments (eg by escaping their antiquotations or adding a `defaultText`) or disable the sandboxed build for the failing module by setting `meta.buildDocsInSandbox = false`.
```

The error seems to be related to the newly-introduced inference of a chroot store, which in this case seems errornous, because a presumably correct store location is given via `NIX_STORE_DIR` environment variable, set to `$TMPDIR/store`.

**Steps To Reproduce**

unknown; https://github.com/zseri/nixos-configs/commit/5366dea15f392b366e04284ec701b7f8424a05c6

**Expected behavior**

The error shouldn't happen, that is, building `lazy-options.json` should succeed.

**`nix-env --version` output**
nix-env (Nix) 2.10.0pre20220615_63df0fd

**Additional context**

**Comment by edolstra** [comment]
Fix: use `--store` or `NIX_REMOTE` to set the store to `local?store=$TMPDIR/store&state=$TMPDIR/state` and remove `NIX_STORE_DIR` and `NIX_STATE_DIR`.

**Comment by zseri** [comment]
that still seems like a hack to me tbh, because I would usually assume for these to be equivalent...

**Comment by edolstra** [comment]
The hack is environment variables like `NIX_STATE_DIR` and `NIX_STORE_DIR`, which should be considered deprecated. `--store` is more general and should be preferred.
