### ISSUE TITLE
installer: add --flakes flag to enable experimental flakes

### ISSUE THREAD

**Issue by wmertens** [NixOS/nix#6734]
**Is your feature request related to a problem? Please describe.**

I'm trying to simplify Nix installation for my team, and it would be easier if enabling flakes can be done in the installer by adding `--flakes` to the command line.

**Describe the solution you'd like**

Make this command work:

```
$ sh <(curl -L https://nixos.org/nix/install) --daemon --flakes
```

It would work like the regular installer, but it would also add this to `/etc/nix/nix.conf`:

```
experimental-features = nix-command flakes
```

**Describe alternatives you've considered**

Ask everyone to edit the nix.conf as root

**Comment by abathur** [comment]
There is already a generic mechanism that likely supports this:

https://github.com/NixOS/nix/blob/6cb41288ac8df00328865f4c66c324452e5a961c/scripts/install-multi-user.sh#L34

https://github.com/NixOS/nix/blob/6cb41288ac8df00328865f4c66c324452e5a961c/scripts/install-multi-user.sh#L859-L866

**Comment by wmertens** [comment]
Ah excellent. Hmmm, it's not very discoverable and a bit awkward, but most people would just be copy/pasting the command so that's ok.

I consider this enough, thanks.

**Comment by abathur** [comment]
> it's not very discoverable and a bit awkward

@wmertens I led you minorly astray by just grepping the multi-user installer for references to nix.conf; there is also a `--nix-extra-conf-file` flag:
https://github.com/NixOS/nix/blob/6cb41288ac8df00328865f4c66c324452e5a961c/scripts/install-nix-from-closure.sh#L87-L90

It looks like install-nix-action uses it as well:
https://github.com/cachix/install-nix-action/blob/451e61183802597c1febd6ca3cf18aa163f93a06/install-nix.sh#L33
