### ISSUE TITLE
Cannot install Nix on Mac OS X (10.10.5 or 10.11.1) - dyld error 

### ISSUE THREAD

**Issue by aaronlevin** [NixOS/nix#675]
I reported this in [`NixOS/nixpkgs`](https://github.com/NixOS/nixpkgs/issues/10765) but wasn't sure if it should also be reported here.

I cannot install Nix on either `10.10.5` or `10.11.1`. I get the following error (I have xcode 7.1 installed):

```
☭  curl https://nixos.org/nix/install | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1332  100  1332    0     0   4204      0 --:--:-- --:--:-- --:--:--  4201
unpacking Nix binary tarball for x86_64-darwin from `https://nixos.org/releases/nix/nix-1.10/nix-1.10-x86_64-darwin.tar.bz2'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 27.4M  100 27.4M    0     0  3099k      0  0:00:09  0:00:09 --:--:-- 2463k
performing a single-user installation of Nix...
copying Nix to /nix/store........................
initialising Nix database...
installing ‘nix-1.10’
building path(s) ‘/nix/store/bfhj0nrjnfwhph4fxzz12zlsanj5bvrm-user-environment’
dyld: Library not loaded: /usr/lib/libSystem.B.dylib
  Referenced from: /nix/store/kp4f6acmkhslpsy6zc9v2x7jzn9417b5-perl-5.20.1/bin/perl
  Reason: no suitable image found.  Did find:
    /usr/lib/libSystem.B.dylib: stat() failed with errno=1
    /usr/lib/libSystem.B.dylib: stat() failed with errno=1
builder for ‘/nix/store/7q0nhsk3iji0ghpq80gdnv9r7xdji9r4-user-environment.drv’ failed due to signal 5 (Trace/BPT trap: 5)
error: build of ‘/nix/store/7q0nhsk3iji0ghpq80gdnv9r7xdji9r4-user-environment.drv’ failed
nix-binary-tarball-unpack/nix-1.10-x86_64-darwin/install: unable to install Nix into your default profile
```

The issue persists even though I have that library in my system.

```
☭ ls -al /usr/lib/libSystem.B.dylib
-rwxr-xr-x  1 root  wheel  52464 Aug  5 05:44 /usr/lib/libSystem.B.dylib
```

**Comment by aaronlevin** [comment]
Attempted with the larger download (`ix-1.10-x86_64-darwin-big.tar.bz2`) and it also failed with the same failure.

**Comment by copumpkin** [comment]
Is `build-use-chroot` turned on by default? I think we need to rebuild the Nix tarball with the pure Darwin environment before that will work out of the box.

cc @pikajude

**Comment by copumpkin** [comment]
(it definitely sounds like a sandbox error, given that it's complaining about a file that does exist)

**Comment by aaronlevin** [comment]
@copumpkin is there anyway I could test that?

**Comment by copumpkin** [comment]
Try putting 

```
build-use-chroot = false
```

in `/etc/nix/nix.conf`.

**Comment by copumpkin** [comment]
You might have to create the path and file if you're doing a new install, but I think the "installer" will pay attention to it if it's there.

**Comment by aaronlevin** [comment]
@copumpkin oh, this was all my fault. I had `build-use-chroot = true` from a previous install. putting it to `false` fixed that. Ugh, sorry.

**Comment by copumpkin** [comment]
No problem. I think the better answer is to build a new Darwin Nix distro in a pure Darwin environment :smile:

**Comment by aaronlevin** [comment]
@copumpkin I'm confused about the state of things, though. I thought `build-use-chroot = true` meant I was using the new pure darwin environment? (I'm not very knowledgeable about what chroot does and the darwin-related issues).

**Comment by pikajude** [comment]
@aaronlevin Long story short: nix-1.10 is missing sandbox permissions required to build user environments. If you're using the nix standalone installer, you need to install nix-1.11.

**Comment by copumpkin** [comment]
@pikajude now I'm confused! I don't see why the sandbox would come into play to build user environments. `nix-build` (constrained by sandbox) makes the environments in the Nix store, and `nix-env` (unconstrained) links them into `~/.nix-profile`, right?

**Comment by copumpkin** [comment]
@aaronlevin pure-darwin environment is fully specified in `nixpkgs`, and just means that we've done the work to make all the packages work without assuming anything (mostly) outside the Nix store. `build-use-chroot` is an additional layer on top of (and enabled by) the purity that actively prevents Nix builds from reaching outside. It's mostly handy to get better guarantees and to catch builds that are otherwise unruly and reach into your system to try to "helpfully" discover dependencies you might have lying around (I'm looking at you, CMake).

**Comment by aaronlevin** [comment]
@copumpkin ah, ok. that was a helpful explanation. thanks!

**Comment by pikajude** [comment]
@copumpkin `nix-build` builds the environment; `nix-env` symlinks its contents into ~/.nix-profile. User environments are generated by `${nix}/share/nix/corepkgs/buildenv.nix`, which is independent from the stdenv.

**Comment by copumpkin** [comment]
@pikajude yeah, was just confused by 

> nix-1.10 is missing sandbox permissions required to build user environments

since it didn't seem like the sandbox would be a major factor in user environment creation.
