### ISSUE TITLE
Statically built nix on Alpine Linux

### ISSUE THREAD

**Issue by sidkshatriya** [NixOS/nix#6751]
I'm interested in a fully static distribution of the nix package manager. I'd like to use it on Alpine Linux which is a musl libc based Linux distribution.

Via internet search, I found that nix *is* available as a static build. See this comment:
https://discourse.nixos.org/t/building-a-statically-linked-nix-for-hpc-environments/10865/16

_But I'm hoping for not only the nix package manager but a fully static executable that would install nix on Alpine for me._

Essentially I want the static equivalent of what I would get if I downloaded the nix package manager from:
https://nixos.org/download.html

**Questions**
* Is this something that is possible?
* Are there issues with running nix on a fully musl based distribution like Alpine? I would hope there should be no problem given that each nix package would then bring in whatever glibc etc. that it needs.

Note that Alpine does have a nix package manager port available but it is quite [old](https://pkgs.alpinelinux.org/package/edge/testing/x86_64/nix) (2.3.x)

**Comment by sidkshatriya** [comment]
I also did find @DavHau 's https://github.com/DavHau/nix-portable 

However that solution adds some stuff. For instance, I am OK with creating `/nix/store` and so forth on the Alpine Linux installation.

**Comment by Artturin** [comment]
> Note that Alpine does have a nix package manager port available but it is quite [old](https://pkgs.alpinelinux.org/package/edge/testing/x86_64/nix) (2.3.x)

@jirutka you're listed as the maintainer for nix in sports, could you try updating it? feel free to create an issue in this repo if you require assistance.

**Comment by sidkshatriya** [comment]
@edolstra Sorry for the direct ping but your suggestions / pointers on the above will be invaluable to me !

**Comment by edolstra** [comment]
Yeah, there is a self-contained statically linked binary, which you can currently get by doing:
```
# nix build nix#nix-static
```
The binary in `./result/bin/nix` should be what you want. It's currently not provided on the download page because it had some problems until recently. We should add it for the next release.

**Comment by sidkshatriya** [comment]
I was trying to run the `nix` executable as root. 

**Once I shifted to some normal user, the segfaults stopped**. It is probably a bug in nix in root mode but for now I was able to make progress.

However, I don't know how to get nix fully "setup". For instance, I created `/nix`. Then: 

```bash
$ ./nix-channel --update
unpacking channels...
error: executing '/nix/store/ach9nz5iw6ic8nfd1bhfa20m0cpn5d7n-nix-2.10.0pre20220629_b7eb4ac-x86_64-unknown-linux-musl/bin/nix-env': No such file or directory
error: program '/nix/store/ach9nz5iw6ic8nfd1bhfa20m0cpn5d7n-nix-2.10.0pre20220629_b7eb4ac-x86_64-unknown-linux-musl/bin/nix-env' failed with exit code 1
```

So I proceed to put all the files from nix-static build in `/nix/store/ach9nz5iw6ic8nfd1bhfa20m0cpn5d7n-nix-2.10.0pre20220629_b7eb4ac-x86_64-unknown-linux-musl/`. 

**This helps but the "setup" is still incomplete.**

```bash
/nix/store/ach9nz5iw6ic8nfd1bhfa20m0cpn5d7n-nix-2.10.0pre20220629_b7eb4ac-x86_64-unknown-linux-musl/bin$ ./nix-channel --update
unpacking channels...
error: opening lock file '/nix/var/nix/profiles/per-user/abc123/channels.lock': No such file or directory
error: program '/nix/store/ach9nz5iw6ic8nfd1bhfa20m0cpn5d7n-nix-2.10.0pre20220629_b7eb4ac-x86_64-unknown-linux-musl/bin/nix-env' failed with exit code 1
```

Then I did, `$ mkdir -p /nix/var/nix/profiles/per-user/ `. **This allows the previous command to work but then my nix profiles etc. are not setup**

**What command do I run so that I have a clean installation of nix? starting with the static nix files?**

**Comment by sidkshatriya** [comment]
I explored this some more and got this working on Alpine Linux. I just looked at the nix installer script to understand what steps need to be accomplished to get nix setup fully. See https://github.com/NixOS/nix/blob/master/scripts/install.in

Also, the normal nix (non-static version) seems to work just fine on Alpine -- one does _not_ need nix static at all I believe (this is because all executables point to the glibc that they need). 

Once I bootstrapped using nix-static I went ahead and installed nix (non-static) via the usual `nix-env -iA nixpkgs.nix`.

I suspect just using the nix installer from https://nixos.org/download.html (thus avoiding all the above complications of bootstrapping via nix-static) should be fine on Alpine but I haven't tested that yet.

**Comment by sidkshatriya** [comment]
Today I verified that the normal nix installer (single user) works on Alpine Linux also.

So, while static nix works on Alpine (i.e. the nix obtained via `nix build nix#nix-static`, it is a bit unwieldy because it is not bundled with an installer), it's just better to use dynamically linked nix because that comes along with its full closure anyways.

**Comment by jirutka** [comment]
> @jirutka you're listed as the maintainer for nix in aports, could you try updating it? feel free to create an issue in this repo if you require assistance.

@Artturin, I’ve just upgraded the [nix](https://pkgs.alpinelinux.org/packages?name=nix) package to 2.9.2.
Tbh, I don’t use nix and I’m getting quite disgusted from its implementation (it’s bloated), so if someone would like to step in as an maintainer of that package in Alpine, I’d appreciate it.

**Comment by sidkshatriya** [comment]
@jirutka Thanks so much for updating nix to 2.9.2 on Alpine -- Thank you!
