### ISSUE TITLE
A question on source position management in nix

### ISSUE THREAD

**Issue by herberteuler** [NixOS/nix#6754]
I noticed today that [`std::upper_bound` is used to find an `Origin` object given an index](https://github.com/NixOS/nix/blob/b7eb4ac1692e289912f3988c0e28bb2c778a4f7a/src/libexpr/nixexpr.hh#L105):

```
    Pos operator[](PosIdx p) const
    {
        if (p.id == 0 || p.id > offsets.size())
            return {};
        const auto idx = p.id - 1;
        /* we want the last key <= idx, so we'll take prev(first key > idx).
           this is guaranteed to never rewind origin.begin because the first
           key is always 0. */
        const auto pastOrigin = std::upper_bound(
            origins.begin(), origins.end(), Origin(idx),
            [] (const auto & a, const auto & b) { return a.idx < b.idx; });
        const auto origin = *std::prev(pastOrigin);
        const auto offset = offsets[idx];
        return {origin.file, origin.origin, offset.line, offset.column};
    }
```

But given how `origins` is updated, it seems direct access should be possible here.

All entries in `origins` are [added through calls to `add()`](https://github.com/NixOS/nix/blob/b7eb4ac1692e289912f3988c0e28bb2c778a4f7a/src/libexpr/nixexpr.hh#L92):

```
    PosIdx add(const Origin & origin, uint32_t line, uint32_t column)
    {
        const auto idx = offsets.add({line, column}).second;
        if (origins.empty() || origins.back().idx != origin.idx) {
            origin.idx = idx;
            origins.push_back(origin);
        }
        return PosIdx(idx + 1);
    }
```

And for a `ChunkedVector`, the `idx` retrieved above is [always increased](https://github.com/NixOS/nix/blob/b7eb4ac1692e289912f3988c0e28bb2c778a4f7a/src/libutil/chunked-vector.hh#L45), which means the offsets in the objects of `origins` and their offsets within the vector are a one-to-one mapping:

```
    std::pair<T &, uint32_t> add(T value)
    {
        const auto idx = size_++;
        auto & chunk = [&] () -> auto & {
            if (auto & back = chunks.back(); back.size() < ChunkSize)
                return back;
            return addChunk();
        }();
        auto & result = chunk.emplace_back(std::move(value));
        return {result, idx};
    }
```

What do I miss? Could we possibly change to direct access to optimize position retrievals?

**Comment by pennae** [comment]
the important line here is
```
if (origins.empty() || origins.back().idx != origin.idx) {
//                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
one origin services many positions. a run of positions added with `add` using the same origin for each call will only add a single origin to save memory, and in the added origin it'll store the index of the *first* position that used this origin. as such we can't linearly index into the `origins` vector but have to do a binary search to find the largest-not-greater index.

**Comment by herberteuler** [comment]
> the important line here is
> 
> ```
> if (origins.empty() || origins.back().idx != origin.idx) {
> //                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ```

Oh, somehow I misinterpreted either `origins.back().idx` or `origin.idx` as the `idx` retrieved above that line of code, which caused my confusion. I apologize for taking both your time.
