### ISSUE TITLE
too small limit on max number of groups per user

### ISSUE THREAD

**Issue by krgn** [NixOS/nix#676]
Currently, it is not possible to part of more than 10 groups without causing trouble for yourself. I, for one, am in

```users wheel disk audio lp video networkmanager systemd-journal vboxusers nixbld```

and that exhausts that limit already. The relevant bit of code is in

https://github.com/NixOS/nix/blob/master/src/libstore/build.cc#L551

As suggested by @the-kenny on IRC it should be upped to 256, and maybe conditionally bumped to NGROUPS_MAX if the previous invocation fails.

**Comment by edolstra** [comment]
This looks like a configuration error to me. `nixbld*` users should not be a member of those groups (typically, they should only be a member of the `nixbld` group). Conversely, non-nixbld* users should not be a member of the `nixbld` group.

**Comment by krgn** [comment]
Right, its starting to dawn on me (every time I build all my sessions get closed ;)).

How can I build packages as a regular user though using nix-build then?

**Comment by edolstra** [comment]
If you have the nix-daemon running and `$NIX_REMOTE` set to daemon, then building as a regular user should just work.

**Comment by krgn** [comment]
Thank you, it must have had to with that. Its working now.
