### ISSUE TITLE
MacOS Montery M1 Pro install script says it installed successfully but no nix-commands work

### ISSUE THREAD

**Issue by robert-wloch-iits** [NixOS/nix#6760]
**Describe the bug**

When I do as the official Nix-Docu says at [https://nixos.org/download.html#nix-install-macos](https://nixos.org/download.html#nix-install-macos)
`sh <(curl -L https://nixos.org/nix/install)`
At the end the script says it should work in a new shell but the nix shell commands are not found.

I’ve seen that the script modified /etc/zshrc where it added the following:
```shell
# Nix
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
# End Nix
```
But even after reboot that configuration is not pulled or it does not work. I suspected that my `~/.zshrc` is the only configuration which is pulled by Zsh.
So, I add the five lines to my `~/.zshrc` file but after sourcing it Zsh still doesn’t know the nix-commands.
Even a manual sourcing of `. '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'` does not work.

**Steps To Reproduce**

1. Go to [https://nixos.org/download.html#nix-install-macos](https://nixos.org/download.html#nix-install-macos) and do as it says
2. Open iTerm and run the command `sh <(curl -L https://nixos.org/nix/install)` in a zsh.
3. Note at the end the script says:

> Alright! We're done!
> Try it! Open a new terminal, and type:
> 
>   $ nix-shell -p nix-info --run "nix-info -m"

4. Open a new zsh terminal in iTerm
5. Run `nix-shell -p nix-info --run "nix-info -m"`
6. Observe: `zsh: command not found: nix-shell`

**Expected behavior**

Reproduction step 5 works. `nix-shell` is known to zsh.

**`nix-env --version` output**
Does not work as it is a nix command.

**Additional context**
I'm using iTerm which internally uses MacOS' zsh.
I've tried to install single-user with `--no-daemon` but the script doesn't allow that anymore on MacOS.

Interestingly, the your documentation is contradicting. On [https://nixos.org/download.html#nix-install-macos](https://nixos.org/download.html#nix-install-macos) the command to execute is `sh <(curl -L https://nixos.org/nix/install)`.
When reading the [Quickstart guide](https://nixos.org/manual/nix/stable/quick-start.html) the command is `bash <(curl -L https://nixos.org/nix/install)`.
Both of those commands seem to work and produce the same result as described in "Steps To Reproduce".
**However**, given that zsh is the preferred shell on Montery, the command `zsh <(curl -L https://nixos.org/nix/install)` fails with 

> ❯ zsh <(curl -L https://nixos.org/nix/install)
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100  4053  100  4053    0     0  16636      0 --:--:-- --:--:-- --:--:-- 16636
> oops: you do not have 'tar' installed, which I need to unpack the binary tarball
> cleanup:1: command not found: rm
>

**Comment by thufschmitt** [comment]
> Even a manual sourcing of . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' does not work.

Does it succeeds but doesn't do anything, or does it just fail?

Some entrypoints for debugging that:
- The main thing the script does is setting `$PATH` to contain `/nix/var/nix/profiles/default/bin` (and `$HOME/.nix-profile/bin` but that's not really important here). Is that the case?
- Do `/nix/var/nix/profiles/default/bin` contain some Nix executables? They would probably be symlinks, are they pointing to something that exists? And can you run them manually?

> nterestingly, the your documentation is contradicting. On https://nixos.org/download.html#nix-install-macos the command > to execute is sh <(curl -L https://nixos.org/nix/install).
> When reading the [Quickstart guide](https://nixos.org/manual/nix/stable/quick-start.html) the command is bash <(curl -L > https://nixos.org/nix/install).
> Both of those commands seem to work and produce the same result as described in "Steps To Reproduce".
> However, given that zsh is the preferred shell on Montery, the command zsh <(curl -L https://nixos.org/nix/install) fails with

Indeed, it should probably be `bash`everytime.
`zsh` won't work indeed, it's a different shell and the script is written for bash (the fact that the bas version on MacOS is prehistoric shouldn't really matter, the script has been written to work with it)

**Comment by abathur** [comment]
@robert-wloch-iits Something in your shell profiles might be terminating early.

I have a hard time keeping all of the platform/shell variation straight in my head, but you might be able to figure out if so and where by running `zsh -x` and comparing what it shows running to your rc scripts.

There's also a section in `man zsh` titled `STARTUP/SHUTDOWN FILES` (at least, for the stock macOS zsh?) that lays out which startup files exist and when they run.
