### ISSUE TITLE
Recursive ingestion of folders

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#680]
I'm not sure if this would break other things, but currently if I write `./somefolder` in a Nix expression, the folder will be copied to the store and my expression will expand to the store path.

I'm wondering if a similar primitive could exist that performed "reverse `buildEnv`", and built a symlink tree out of each folder recursively. This would allow for far better sharing when ingesting larger folders.

**Comment by the-kenny** [comment]
I think an important aspect in this approach is some intelligence on the nix-side: I don't want to keep the full tree of ```/doc```, ```/share```, ```/bin``` etc. if I just reference one path in ```bin```. Nix should automatically detect "deep" access into that tree and do what I'd call "auto-multiple-outputs".

Maybe another approach is to use heuristics to automatically generate such symlink-trees in a "sane" way:

- Automatically detect root-paths like ```share```, ```bin```, ```etc```.
- Split where a subdirectory has more than ```n``` files
etc.

**Comment by Ericson2314** [comment]
I thought of that once. An issue complicating such automatic pruning is referencing a binary which then looks at some path relative to itself.

**Comment by edolstra** [comment]
Closing since it's unlikely to be implemented. However, you already get deduplication when using `auto-optimise-store = true`.

**Comment by Ericson2314** [comment]
I actually have a WIP RFC that relates to this.
