### ISSUE TITLE
`nix flake check`  is running checks for all systems in `checks`

### ISSUE THREAD

**Issue by thiagokokada** [NixOS/nix#6806]
**Describe the bug**

`nix flake check` is running eval(?)`checks.<system>.<name>` for all systems instead of just the current system as the documentation suggests:

```
Evaluation checks

    The following flake output attributes must be derivations:

      · checks.system.name
      · defaultPackage.system
      · devShell.system
      · devShells.system.name
      · nixosConfigurations.name.config.system.build.toplevel
      · packages.system.name
```

For example, adding `checks.x86_64-darwin.hm-macos = self.outputs.homeConfigurations.hm-macos.activationPackage` is sufficient to break `nix flake check` in `x86_64-linux` with the following error:

```
$ nix flake check
error: a 'x86_64-darwin' with features {} is required to build '/nix/store/md98zl0n4wggkl394x03kipglmyjls58-java-home.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, kvm, nixos-test}
(use '--show-trace' to show detailed location information)
```

Using `--no-build` flag makes no difference, so I think the issue here is the eval? I also tried to create a minimal repro `flake.nix`, but my attempts didn't work, so I am not sure what is happening here.

**Steps To Reproduce**

0. My nix configs repo adding the checks for NixOS/Home-Manager/nix-darwin: https://github.com/thiagokokada/nix-configs/pull/276
1. `nix flake check github:thiagokokada/nix-configs/add-checks`

**Expected behavior**

`nix flake check` should only build and eval `checks.<current system>`.

**`nix-env --version` output**

```
nix-env (Nix) 2.8.1
```

**Additional context**

N/A

**Comment by thiagokokada** [comment]
https://github.com/NixOS/nixpkgs/pull/180872

Looks like a duplicate of the bug above. Closing it.

**Comment by peterbecich** [comment]
Working on this: https://github.com/NixOS/nix/pull/7759
