### ISSUE TITLE
API to other languages

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#681]
If I wanted to write a python module that gives me `toJSON` of evaluating a Nix expression, how hard would that be? I'd like to use Nix as a configuration language for something else. I've seen that there's a `libexpr`, but I don't know whether we consider the API to be stable.

**Comment by vcunat** [comment]
I'd think it was never called stable mainly because there were no other (known) users of the API so far...

**Comment by edolstra** [comment]
It's used by Hydra. But it's not stable (if I change the Nix API, I just update Hydra as well).

However, what's the exact use case here? Doesn't `nix-instantiate --json` give you want you need?

**Comment by copumpkin** [comment]
`nix-instantiate --json` would be fine, but I was hoping to avoid subprocessing out. In one case (with a unikernel), I can't use subprocesses, but more broadly it feels messier than a "real API". That's probably not a very compelling case, right? :smile:

**Comment by vcunat** [comment]
You also have `nix-repl`. Running commands and interaction via I/O pseudo-files is also an API, isn't it? Only, to be better usable you might prefer to have a (general) wrapper around those in your target language.

**Comment by edolstra** [comment]
Oh, nix-repl is another user of the API :-)

**Comment by copumpkin** [comment]
@vcunat my point was that in at least one case, I'd need a direct C API since I'm not on a system with multiple processes

**Comment by edolstra** [comment]
Well, as nix-repl shows, using it from another package via the C++ API works fine, but there may be breakage when you upgrade to a new major version of Nix.

**Comment by copumpkin** [comment]
Yeah, I'll just go with that, thanks :smile:

**Comment by copumpkin** [comment]
Not sure if you want to solidify that API at some point in the future and keep it stable. If you don't, feel free to close this. I'd obviously prefer to keep it open, but I don't want to put more burden on you either.

**Comment by Ericson2314** [comment]
@copumpkin do you want a nix-expr API or a nix API? [Also, unikernals...I am very curious now!]. My hunch would be that a simple interpreter for nix would be better to re-implement considering that will be lower impact on build systems, platform assumptions, etc, and double as conformance tests for the C++ original to boot.

**Comment by copumpkin** [comment]
I'd want nix-expr as an independent library. Mostly to evaluate it to JSON, but there's lots of other cool things you could do in terms of linting, automatic refactoring, and building other sorts of tools for manipulating Nix source. Perhaps hnix is a better base for writing such code manipulation libraries (I'd rather manipulate ASTs in Haskell), but the JSON evaluation seems fine for nix-expr :smile:

**Comment by Ericson2314** [comment]
I suppose a simple `String -> String` or `FilePath -> String` function in the C++ original (spitting out JSON) would be a fine fallback where there is no language-specific implementation written.

FYI besides hnix, there is also @peti's https://hackage.haskell.org/package/language-nix, though I am a bit confused how one uses it :).

**Comment by copumpkin** [comment]
The stability of the API might become more important now that https://github.com/hercules-ci/hercules is a thing. cc @domenkozar expipiplus1

**Comment by expipiplus1** [comment]
It's not quite a thing yet, @copumpkin!

hnix is very nice for anything we're likely to do in the short term, although for now we're just dealing with nix via the cli programs and some `NIX_BUILD_HOOK` trickery (@grahamc's inspiration)

**Comment by peti** [comment]
Closing this ticket since there hasn't been any substantive activity for 2+ years.
