### ISSUE TITLE
Use nix-installed libsodium?

### ISSUE THREAD

**Issue by lukasepple** [NixOS/nix#683]
On ArchLinux libsodium seems to have gone too far ahead leaving me with:

```
Can't load '/usr/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi/auto/Nix/Store/Store.so' for module Nix::Store: libsodium.so.13: Kann die Shared-Object-Datei nicht öffnen: Datei oder Verzeichnis nicht gefunden at /usr/share/perl5/core_perl/XSLoader.pm line 70.
 at /usr/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi/Nix/Store.pm line 38.
Compilation failed in require at /usr/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi/Nix/Manifest.pm line 13.
BEGIN failed--compilation aborted at /usr/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi/Nix/Manifest.pm line 13.
Compilation failed in require at /usr/bin/nix-channel line 8.
BEGIN failed--compilation aborted at /usr/bin/nix-channel line 8.
```

```
$ locate libsodium.so
/nix/store/xdvadkvgmkrv8dnjcqv6rlxapzgra3bd-libsodium-1.0.3/lib/libsodium.so
/nix/store/xdvadkvgmkrv8dnjcqv6rlxapzgra3bd-libsodium-1.0.3/lib/libsodium.so.13
/nix/store/xdvadkvgmkrv8dnjcqv6rlxapzgra3bd-libsodium-1.0.3/lib/libsodium.so.13.2.0
/usr/lib/libsodium.so
/usr/lib/libsodium.so.17
/usr/lib/libsodium.so.17.0.0
```

Fix for me is to call every nix command like this:

```
LD_PRELOAD="/nix/store/xdvadkvgmkrv8dnjcqv6rlxapzgra3bd-libsodium-1.0.3/lib/libsodium.so.13" nix-channel --update
```

**Comment by edolstra** [comment]
How did you install Nix? Not sure we can do anything about Arch system dependencies.

**Comment by lukasepple** [comment]
I had installed it with the official bash script. Problem was created by a system upgrade today.

**Comment by lethalman** [comment]
@lukasepple echo $LD_LIBRARY_PATH . Arch linux usually uses that evil variable, pretty sure that's  your problem.

**Comment by lukasepple** [comment]
mh, `/usr/lib` is in there, should work actually. The problem seems to be that nix just does not like `libsodium.so.17`.

**Comment by edolstra** [comment]
The mention of `/usr/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi/Nix/Store.pm` suggests Nix was *not* installed via the official bash script, because that script only installs stuff in `/nix/store`.

**Comment by lukasepple** [comment]
Okay, I have figured it out.

Turns out, you're right: I have used the AUR version of nix.

Recompiling did the fix.

Thanks for your help.

**Comment by womfoo** [comment]
we're was FD es b
. KB
