### ISSUE TITLE
Untrusted Substituer after macOS Update

### ISSUE THREAD

**Issue by mpscholten** [NixOS/nix#6852]
**Describe the bug**

After macOS update the binary caches are not working anymore.

**Steps To Reproduce**

1. Update macOS
2. Figure out that nix commands don't work anymore
3. Reinstall nix
4. After reinstall, run `nix-shell` in a project
5. Get an error `warning: ignoring untrusted substituter`:
    <img width="620" alt="image" src="https://user-images.githubusercontent.com/2072185/182166998-c2e60ac4-4f6d-4038-bafa-3737388c587f.png">
    Now nix tries to rebuild the world.

    To fix this I usually end up at https://github.com/cachix/cachix/issues/26#issuecomment-395516170 and run those commands to fix the problem.

**Expected behavior**

It would be great if nix would work automatically after a macOS update. If that's not possible it would be great to either automatically fix the untrusted substituter problem or to print a more helpful error message that tells me what to do to fix the issue.

**`nix-env --version` output**

```
nix-env (Nix) 2.10.3
```

**Additional context**

macOS version after update is macOS Monterey 12.5

**Comment by abathur** [comment]
> 1. Update macOS
> 2. Figure out that nix commands don't work anymore
> 3. Reinstall nix

You don't have to reinstall. The update is overwriting the shell hook, but you can just replace it. See #3616 for more.

**Comment by mpscholten** [comment]
Oh, thanks 👍  This makes sense.

Fixing #3616 would also make this issue mostly disappear, so I'm closing this one in favor of #3616.
