### ISSUE TITLE
install: Core dump in installer

### ISSUE THREAD

**Issue by hunger** [NixOS/nix#686]
This is the output after the download finished:

performing a single-user installation of Nix...
copying Nix to /nix/store...........................
initialising Nix database...
replacing old ‘nix-1.10’
installing ‘nix-1.10’
perl: loadlocale.c:130: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_COLLATE) / sizeof (_nl_value_type_LC_COLLATE[0]))' failed.
perl: loadlocale.c:130: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_COLLATE) / sizeof (_nl_value_type_LC_COLLATE[0]))' failed.
nix-binary-tarball-unpack/nix-1.10-x86_64-linux/install: line 84: 22051 Aborted                 (core dumped) $nix/bin/nix-channel --add https://nixos.org/channels/nixpkgs-unstable

Starting the installer with LC_ALL=C works around this issue.

**Comment by edolstra** [comment]
Dupe of #599.
