### ISSUE TITLE
''nix flake check'' requires modules be in a form unamenable to deduplication

### ISSUE THREAD

**Issue by charles-dyfis-net** [NixOS/nix#6866]
**Describe the bug**

If two or more modules included into a single system `import` the same dependent module from a flake, these two separate imports will conflict with each other, because `nix flake check` requires that a flake's `nixosModules` be functions, not locations of files from which functions can be imported; and only the latter form can be deduplicated.

**Steps To Reproduce**

See https://gist.github.com/charles-dyfis-net/7b7c68575fbd5fcb68b9160f6f189bc8, setting up a system definition wherein a module is imported twice. In that test case the extra imports are next to each other; in a more realistic case they would be indirect (f/e, requiring two different modules, each of which independently requires the common module).

Within those two, there are two separate tests to be performed:

- Checking if the container build succeeds: `nixos-container create flake-test --flake '.#doubleImportTest'`
- Checking if `nix flake check` succeeds: `nix flake check`

One or the other of these will succeed, but not both:

 - If the following line is uncommented:
   ```
   testModule = ./module.nix;
   ```
  ...then `nix flake check` fails, but the NixOS system build succeeds.

 - If the above line is commented out, and the following line is uncommented in its place:
   ```
   testModule = import ./module.nix;
   ```
   ...then the NixOS system build fails due to the duplicate imports that cannot be deduplicated.

**Expected behavior**

Whichever mechanism for importing modules `nix flake check` encourages should allow the full set of common use cases, including those where a module is imported via multiple paths.

**`nix-env --version` output**

nix-env (Nix) 2.9.1

**Additional context**

N/A.

**Comment by thufschmitt** [comment]
It's not ideal, but you can have

```nix
testModule = { imports = [ ./module.nix ]; };
```

which will work both for `check` and building the system configuration.

**Comment by roberth** [comment]
> It's not ideal, but you can have
> 
> ```nix
> testModule = { imports = [ ./module.nix ]; };
> ```
> 
> which will work both for `check` and building the system configuration.

This form is bad for error messages, because the location information is lost. Errors will be reported in "anonymous module" or worse.

**Comment by ncfavier** [comment]
https://github.com/NixOS/nix/pull/7356

**Comment by ncfavier** [comment]
https://github.com/NixOS/nix/pull/7559
