### ISSUE TITLE
TOFU for build-remote

### ISSUE THREAD

**Issue by shlevy** [NixOS/nix#6868]
The default build-remote mechanism fails if the remote host is not in known_hosts. A TOFU approach (e.g. with `StrictHostKeyChecking` set to `accept-new`) would be a much better experience (especially in light of #6867)

**Comment by roberth** [comment]
Still will allow bad security configuration to go undetected, and it's particularly bad for clients in ephemeral environments.
Defaults should be secure.
Closing, acknowledging
- #6867
