### ISSUE TITLE
`nix flake update X` fails if X is local path input

### ISSUE THREAD

**Issue by tinybeachthor** [NixOS/nix#6873]
**Describe the bug**

Cannot update a single flake input if it's a local path.

`flake.nix`:
```
{
  inputs = {
    dream2nix.url = "/home/martin/dream2nix";
    ...
  };
  ...
}
```

**Steps To Reproduce**

1. Have a flake with local path input
2. run `nix flake update dream2nix` to update only the local path input

```
error: cannot find flake 'flake:dream2nix' in the flake registries
```

**Expected behavior**

Expected the input to update.

**`nix-env --version` output**
```
nix-env (Nix) 2.8.1
```

**Additional context**

`nix flake update` correctly updates all inputs.

**Comment by thufschmitt** [comment]
That seems to be an instance of #5110 : `nix flake update dream2nix` will try to update the `dream2nix` flake and not the `dream2nix` input of the current flake

**Comment by tinybeachthor** [comment]
@thufschmitt you're right, my bad

`nix flake lock --update-input dream2nix` works fine
