### ISSUE TITLE
libSystem.so requested on NixOS

### ISSUE THREAD

**Issue by abbradar** [NixOS/nix#688]
When I'm trying to run `nix-env -e '*'` on `master` or `nixUnstable` from `nixpkgs`, it reports this:
```
 nix git:(master) ✗ result/bin/nix-env -e '*'
building path(s) ‘/nix/store/w4i5afc8sp7n3rn45h8x2sck7zz2ji2w-user-environment’
error: derivation '/nix/store/0rr1w7i86fnqsr5rhkny0g4abfvs8y28-user-environment.drv' requested impure path ‘/usr/lib/libSystem.dylib’, but it was not in allowed-impure-host-deps (‘/bin/usr/bin’)
 nix git:(master) ✗ 
```
Same story is with `nix-channel --update`. `nixStable` works fine.

**Comment by shlevy** [comment]
@pikajude Any idea?

**Comment by abbradar** [comment]
Just to clarify, this is on NixOS (if I remember correctly, `libSystem.so` is something OS X'ish). Also, when I add `/usr/lib/system` and `/usr/lib/libSystem.dylib` there's another error:
```
error: while setting up the build environment: getting attributes of
path ‘/usr/lib/libSystem.dylib’: No such file or directory
```

**Comment by joachifm** [comment]
I have experienced the same problem (on `nixos-unstable`),  reverting the latest `nixUnstable` bump fixed it for me.

**Comment by zimbatm** [comment]
What happens if you `sudo touch /usr/lib/libSystem.dylib` ?

**Comment by pikajude** [comment]
Revert your nix version. The newest nix adds libSystem as an impure dependency for the user environment derivation, but it does it on every OS, not Darwin, which probably should have been noticed in code review
