### ISSUE TITLE
urlencode builtin

### ISSUE THREAD

**Issue by RaitoBezarius** [NixOS/nix#6903]
**Is your feature request related to a problem? Please describe.**

I would like to compute the urlencoded value of a string in Nix to generate at evaluation time valid Notmuch queries strings: https://neomutt.org/feature/notmuch#3-2-%C2%A0items

But, it seems like Nix current builtins are not powerful enough to do it concisely.

**Describe the solution you'd like**

`builtins.urlencode x` or `lib.urlencode` (in Nixpkgs) built upon some unknown primitive that would be more acceptable in `builtins` (?).

**Describe alternatives you've considered**

- IFDs, not super desirable for my very simple usecase ;
- Very smart Nix string manipulation : quite complicated for maintenance

**Comment by RaitoBezarius** [comment]
Well, I can have a prototype with
```nix
{ lib }:
lib.replaceChars
  [ "!"    "#"   "$"   "&"   "'"   "("   ")"   "*"   "+"   ","   "/"   ":"   ";"   "="   "?"   "@"   "["    "]"  " "  "%"    "."   "<"    ">" "\\" "^" "_" "`" "{" "|" "}" "~"]
  [ "%21" "%23" "%24" "%26" "%27" "%28" "%29" "%2A" "%2B" "%2C" "%2F" "%3A" "%3B" "%3D" "%3F" "%40" "%5B" "%5D" "%20" "%25" "%2E" "%3C" "%3E" "%5C" "%5E" "%5F" "%60" "%7B" "%7C" "%7D" "%7E" ]
```
Unsure if it's a good idea to write this way though.

**Comment by fricklerhandwerk** [comment]
@RaitoBezarius a PR against NixOS/nixpkgs is much more likely to get attention. Adding features to the language is always a tough call.

**Comment by ncfavier** [comment]
Someone made a PR: https://github.com/NixOS/nixpkgs/pull/219235

**Comment by fricklerhandwerk** [comment]
Closing it then, feel free to reopen if it still appears necessary.
