### ISSUE TITLE
nixos nix trace: warning

### ISSUE THREAD

**Issue by PlumpMath** [NixOS/nix#6915]
It seems to come out because of the flake.nix file on the nixpkgs side, but I don't know the exact reason.

trace: warning: The option `nix.trustedUsers' defined in `/nix/store/24b6dia1p4qvwcy7pdgbw8l2xzdg4w2n-source/flake.nix' has been renamed to `nix.settings.trusted-users'.

**Comment by roberth** [comment]
This is most likely an issue in your NixOS configuration, or possibly in a third-party module you're importing.
Look for any use of `trustedUsers` in your flake and your modules and rename them accordingly.

If those instructions didn't work for you use the flags `--impure --show-trace` and environment variable `NIX_ABORT_ON_WARN=1`. The trace may reveal more information about where and why the warning occurs.

**Comment by PlumpMath** [comment]
> Look for any use of trustedUsers in your flake and your modules and rename them accordingly.

I'm not sure what it means, but it's roughly your suggestion that there is something wrong with my config, so maybe someday nix compiler post an exact log like the rust compiler to see where and what is causing this error?  Yesterday too, the notice build log that was changed to about an update in nix-darwin appeared, but it was also roughly vague there…  I hope it will be replaced with a log of which line of code is cross-conflicted as soon as possible, or which the like past issue exactly how changed.

**Comment by PlumpMath** [comment]
> has been renamed to `nix.settings.trusted-users'.

Oh stupid... I solved it.
