### ISSUE TITLE
`builtins.getFlake` succeeds despite reference not being locked, without using `--impure` flag

### ISSUE THREAD

**Issue by pinn3** [NixOS/nix#6920]
**Describe the bug**

It shouldn't be allowed, if I understand the following documentation correctly:
https://github.com/NixOS/nix/blob/53833dfb40ddfc978f47f5c180a73bc7e0400320/src/libexpr/flake/flake.cc#L755-L761

**Steps To Reproduce**

1. Create a file called `example.nix` with content
   ```nix
   (builtins.getFlake "github:edolstra/dwarffs").defaultPackage.x86_64-linux
   ```
3. Run `nix build -f example.nix`
4. See that the build succeeded without any issues, and that a result link was produced

**Expected behavior**

Not sure if an error should have been thrown, but the build shouldn't have succeeded

**`nix-env --version` output**

```console
$ nix-env --version
nix-env (Nix) 2.10.3
```

**Comment by Kha** [comment]
`-f` implies `--impure` https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-build.html#options

**Comment by pinn3** [comment]
Ahh completely missed that part. Thank you!
