### ISSUE TITLE
Installing MacOS 12.5.1 breaks nix

### ISSUE THREAD

**Issue by gracicot** [NixOS/nix#6927]
**Describe the bug**

When upgrading to MacOS 12.5.1, all nix commands stops working.

**Steps To Reproduce**

1. Have a MacOS 12.4 installation
2. Install nix
3. Upgrade to MacOS 12.5
4. Try `nix-env --version`

**Expected behavior**

The output should be something like `nix-env (Nix) 2.10.3`

**Actual Behavior**

The following error is being output: `zsh: command not found: nix-env`

**Additional context**

I was able to fix the problem by typing this command:
```sh
sudo -i sh -c  "echo \"\n# Nix\nif [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then\n. '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'\nfi\n# End Nix\" >> /etc/zshrc"
```

This adds the launching of the nix daemon inside `/etc/zshrc`

**Comment by abathur** [comment]
Duplicate of https://github.com/NixOS/nix/issues/3616.

To clarify for later travellers: no, the update doesn't "break" Nix. The OS updates overwrite /etc/zshrc, to which Nix adds a shell hook that adds its executables to your PATH. This shell hook does not launch the nix daemon.

**Comment by gracicot** [comment]
Thank you! I will close this issue, as the other one covers the problems I got entirely.
