### ISSUE TITLE
vim-go in neovim doesn't work anymore

### ISSUE THREAD

**Issue by halturin** [NixOS/nix#6928]
**Describe the bug**

I'm using neovim with vim-go plugin, and now it has become unusable. simple shortcut ctrl-] doesn't go to the term definition as I expected. At the same time, it does work with manually running `GoDecls`.

PS: I'm on 'unstable' channel.

**`nix-env (Nix) 2.10.3`**

**Comment by bjornfor** [comment]
Hi, this repo is for the Nix package manager itself, whereas what you have here looks like a bug in packages from nixpkgs. Please re-submit here: https://github.com/nixos/nixpkgs/issues.
