### ISSUE TITLE
Different `sourceInfo` when using `git+` flake reference vs. `github`

### ISSUE THREAD

**Issue by b-bondurant** [NixOS/nix#6929]
**Describe the bug**

When using a `github:...` flake reference the `sourceInfo.revCount` and `.submodules` attributes are missing, but they're present for the same flake when using a `git+...` reference.

**Steps To Reproduce**

```
$ nix repl
Welcome to Nix 2.10.3. Type :? for help.

nix-repl> :lf git+https://github.com/NixOS/nix.git 
Added 16 variables.

nix-repl> sourceInfo                               
{ lastModified = 1660904554; lastModifiedDate = "20220819102234"; narHash = "sha256-/kO7GUG7h+VqHR5SWgPUfF8pB87gjRjk9CcIUGn/pSU="; outPath = "/nix/store/xnjnyjnpfmxlwy83v7jfwzb32wy2kmad-source"; rev = "d5e979ab87ab894fde132799dac242780b28bc05"; revCount = 12646; shortRev = "d5e979a"; submodules = false; }

nix-repl> :r                                       

nix-repl> :lf github:NixOS/nix                     
Added 14 variables.

nix-repl> sourceInfo           
{ lastModified = 1660904554; lastModifiedDate = "20220819102234"; narHash = "sha256-/kO7GUG7h+VqHR5SWgPUfF8pB87gjRjk9CcIUGn/pSU="; outPath = "/nix/store/xnjnyjnpfmxlwy83v7jfwzb32wy2kmad-source"; rev = "d5e979ab87ab894fde132799dac242780b28bc05"; shortRev = "d5e979a"; }
```

**Expected behavior**

Same `sourceInfo` for same flake.

**`nix-env --version` output**

```
$ nix-env --version
nix-env (Nix) 2.10.3
```

**Comment by edolstra** [comment]
We can't support `revCount` because GitHub doesn't provide that information.

It might be possible to support submodules, but it would complicate the github fetcher a lot. So it's best to use the `git` fetcher for that.

**Comment by b-bondurant** [comment]
Ah, yeah, I see now that most of my confusion is my own fault for assuming the same fetcher was being used under the hood, which the documentation clearly states isn't the case.

Might not be a bad idea to add the `sourceInfo` differences to the documentation though.
