### ISSUE TITLE
Progress bar flickers when evaluating derivations

### ISSUE THREAD

**Issue by cole-h** [NixOS/nix#6931]
**Describe the bug**

When building my configuration with a recent `nix` built from master, I see the following:

https://user-images.githubusercontent.com/28582702/185722036-7dd2786e-d65a-47e0-aec9-c8046f77253c.mp4

**Steps To Reproduce**

1. Evaluate any flake
4. See flickering

**Expected behavior**

I would expect this to either not appear for this normal level or verbosity, or to not overwrite the progress bar.

**`nix-env --version` output**

nix-env (Nix) 2.10.0pre20220819_d5e979a

**Additional context**

I imagine it may be related to this commit: https://github.com/NixOS/nix/commit/3d4489b623deaceef720da7d884a41452f928db6

**Comment by NobbZ** [comment]
I can only reproduce this flickering through `nixos-rebuild`! It does not seem to happen on direct `nix` usage!

**Comment by NobbZ** [comment]
Scratch that comment. The "direct `nix` usage"s I tried just went by quicker than the flicker effect needs to happen.

Anything that requires more work to be done than just pulling a hadfull of bytes from the cache causes the flickering for me as well.

**Comment by edolstra** [comment]
> I can only reproduce this flickering through nixos-rebuild! It does not seem to happen on direct nix usage!

So it was actually triggered by the `-L` flag, which `nixos-rebuild` passes by default.

**Comment by cole-h** [comment]
Woot, thanks!

**Comment by c2vi** [comment]
If you use `--log-format bar-with-logs` instead of the `-L` flag this flickering is still occurring.

flickers:
```
nix run nixpkgs/1e3deb3d8a86a870d925760db1a5adecc64d329d#nix -- build nixpkgs/1e3deb3d8a86a870d925760db1a5adecc64d329d#bash --rebuild --log-format bar-with-logs
```

doesn't flicker:
```
nix run nixpkgs/1e3deb3d8a86a870d925760db1a5adecc64d329d#nix -- build nixpkgs/1e3deb3d8a86a870d925760db1a5adecc64d329d#bash --rebuild -L
```
