### ISSUE TITLE
Android "Spawning emulator instances" section missing details

### ISSUE THREAD

**Issue by l0b0** [NixOS/nix#6935]
It has taken a long time (and two bug reports so far, https://github.com/NixOS/nixpkgs/issues/187853 and https://github.com/NixOS/nixpkgs/issues/187854) to get to what might almost be a working configuration to run an Android app. It would be very useful if the documentation was expanded to support users who are not Android developers.

The only part which is easy is this:

```
pkgs.androidenv.emulateApp {
  app = ./foo.apk;
}
```

Issues I've run into so far beyond that:

1. I want to run a Google Play app, not my own. After a lot of searching I ended up with this hack:

   ```
   app = pkgs.fetchurl {
     url = "https://storage.evozi.com/apk/dl/16/09/10/securecomputing.devices.android.controller_84500.apk";
     sha256 = "6a0040b05e9baa1007986df57c4a4309503d289da63a22e02fbc9a4940eacb87";
   };
   ```
   I'm not sure if it's even possible to download APKs directly from Google, but it would certainly be better for security. Maybe a `pkgs.fetchGooglePlayApk` or something?
2. I'm not sure why `name` is mandatory, or what it should be. I've just used an arbitrary string, but it would be best if it was not necessary. If `stdenv.mkDerivation` needs one, how about generating one from the APK?
3. Why is `app` optional? Could it be made mandatory instead? It seems an `emulateApp` which doesn't run an emulator isn't ideal…
4. The `platformVersion` default of "16" is unhelpful. It corresponds to Android 4.1, Jelly Bean, from 2012. Should this value be made mandatory instead, to avoid surprising behaviour? Also, it would be good if the docs linked to some official mapping from platform version to human readable versions, especially now that they have diverged so far (Android 11 is platform version 30).
5. Ditto for the ABI version.
6. Figuring out `package` and `activity` looks like it should be automatically doable via `apkanalyzer manifest print ${app}`, but I'm not sure how those values need to be mangled before use. I ended up having to install the app on my phone and querying `adb shell dumpsys package securecomputing.devices.android.controller` to figure out these values, and I'm still not sure if they're right (because of the blocking issues above). Automating them would be great.

Ping @svanderburg as the original author of this code.

**Comment by cole-h** [comment]
Should this have been filed against the Nixpkgs repo and not the Nix repo (the tool)?

**Comment by l0b0** [comment]
Probably. Is an admin able to move it?

**Comment by l0b0** [comment]
Moved to https://github.com/NixOS/nixpkgs/issues/189064
