### ISSUE TITLE
Make persistent nix-shells canon

### ISSUE THREAD

**Issue by FlorentBecker** [NixOS/nix#694]
https://nixos.org/wiki/Development_Environments#Making_a_Persistent_nix-shell_Environment has instructions for creating a persistent nix-shell, but they rely on "undocumented behaviour in nix-shell". A "--make-script" option should be added to nix-shell, which instead of running the resulting shell, creates a script which to run said shell, and records the script as a gc root.

**Comment by tripokey** [comment]
NixOS wiki is shutdown. Alternative link for persistent nix-shell environment: https://mailman.science.uu.nl/pipermail/nix-dev/2016-November/022176.html

**Comment by phunehehe** [comment]
I simply add the nix-shell environment to my user environment, something like this:

```
buildEnv {
  name = "my-env";
  paths = [
    (import /path/to/shell.nix {})
  ];
}
```

The environment is then installed into my user profile, so it is persistent across GCs. An added benefit is that when updating nixpkgs I know right away whether any of my nix-shell environments fails to build.

**Comment by dtzWill** [comment]
Neat! Minor "downside" is that environments are upgraded together; I think often one wants shell environments to be persistent but also unchanged unless explicitly updated.

Not that your approach has to be everything to everyone and make them toast too, just clarifying for folks who might try it :).

As you say in many circumstances upgrading it (and dealing with fallout forcibly) can be rather beneficial too :).

**Comment by edolstra** [comment]
Closing since `nix dev-shell` has `--profile` option, e.g.
```
nix dev-shell --profile ./profile
```
to build/update the profile and
```
nix dev-shell ./profile
```
to enter it without having to re-evaluate/rebuild anything.
