### ISSUE TITLE
Hydra build hangs after step finishes or fails with nix 2.11.0

### ISSUE THREAD

**Issue by blurgyy** [NixOS/nix#6981]
**Describe the bug**

The latest `hydra_unstable` tests on https://hydra.nixos.org have failed (as shown here: https://hydra.nixos.org/job/nixos/trunk-combined/nixos.tests.hydra.hydra_unstable.x86_64-linux), the [log](https://hydra.nixos.org/build/189257529/nixlog/23) shows it has reached timed out.

The failure was first reported in [evaluation 1778508](https://hydra.nixos.org/eval/1778508?full=1#tabs-now-fail) (on `nixpkgs/f3b7d6414b06eb493ed7f258a6938be440b7cdaf`), the last known successful test was from evaluation 1778837 (on `nixpkgs/a63021a330d8d33d862a8e29924b42d73037dd37`), nix was upgraded from `2.10.3` to `2.11.0` between the two commits.

It can also be reproduced with a hydra instance on an aarch64-linux machine with latest `nixpkgs/nixos-unstable-small`, other jobs also hang at very trivial steps (like downloading a zip file, etc.), and hydra still shows step status as "Buliding" on the web interface, while the corresponding log shows it has finished.  When hydra hangs, there seems to be a process `nix-store --builders --serve --write` hanging even after the step finishes or fails.  After I switch to a profile with nix version `2.10.3`, the problem is gone.

**Steps To Reproduce**

1. Upgrade to latest nixpkgs/nixos-unstable-small and enable hydra
2. Create a new project and a new jobset (for example, create the new jobset with `nixos/tests/hydra` in input `nixpkgs`
3. Wait for a build step to finish/fail, and observe hydra hangs at the step, showing status as "Building".

**Expected behavior**

After a step finishes/fails, hydra reports its build status immediately.

**`nix-env --version` output**

```
nix-env (Nix) 2.11.0
```

**Additional context**

Possibly related:
- https://github.com/NixOS/hydra/issues/366
- https://github.com/NixOS/nix/issues/2560
- https://github.com/NixOS/nix/issues/2260

**Comment by fricklerhandwerk** [comment]
@grahamc please transfer this to NixOS/hydra

**Comment by blurgyy** [comment]
Closing as it can now be avoided without using overlays.
