### ISSUE TITLE
restrict-eval should not apply to fixed-output derivations

### ISSUE THREAD

**Issue by jcumming** [NixOS/nix#699]
Although somewhat unportable, I use fetchurl { url = file:///.... } and fetchhg against NFS mounted repositories. 

I think for a fixed-output derivation this is probably okay.

**Comment by edolstra** [comment]
Try `fetchurl { url = "file:///..."; }` (i.e. with quotes). Without the quotes, Nix will copy the file to the store at eval time.

**Comment by jcumming** [comment]
I will try that.
