### ISSUE TITLE
notes from 'debugging nix expressions' unconference

### ISSUE THREAD

**Issue by jcumming** [NixOS/nix#701]
Although 'how to debug' is a rather large topic, we came up with a few simple things that might help:
- document traceToXML, or another pretty-printer for dumping a textual representation of an attrset
- annotate attr assignments with file and lineno

**Comment by vcunat** [comment]
We also have PR #612 (I wasn't at this NixCon discussion). A few times I've got an empty trace with --show-trace (no location).

**Comment by jcumming** [comment]
I'm planning on creating a 'Debugging nix expressions' section in section 15. Nix Expression Language.

**Comment by vcunat** [comment]
Sounds a good idea.

**Comment by sseefried** [comment]
@jcumming Any more work done on 'Debugging nix expressions'?

**Comment by jcumming** [comment]
Oh. Wow!

I've learned a bit in these few years. Lemme revisit.

**Comment by sseefried** [comment]
I'm a newbie to Nix and I'm finding it difficult to find my way around
Nixpkgs (in the Haskell expressions)

**Comment by jcumming** [comment]
I usually start exploring nixpkgs at `pkgs/top-level/all-packages.nix`. 

The haskell packages are some of the more impressive wizardry in nixpkgs, and somewhat beyond my expertise. Depending on if you're looking for a haskell package, want to update a haskell package, or `annex` an entire module repository (like hackage), I might be able to help you or point you in the direction of a wiser sage. 

I'd recommend coming over to the irc channel, we're friendly!

**Comment by sseefried** [comment]
Sure I'll try the IRC channel. Is that #nixos? What's your username on
there?

**Comment by peti** [comment]
Closing because there hasn't been any substantive activity in the last 2 years.
