### ISSUE TITLE
Parallel copy regression?

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#7019]
**Describe the bug**

All builds on packet builders on hydra.nixos.org started hanging recently. Unfortunately I cannot log in to them to see where they are hanging, but trying to reproduce the hang from the command line produced some weird failures, e.g.
```
# nix build --extra-experimental-features nix-command -j0 --builders 'ssh://root@feb44263.packethost.net?base64-ssh-public-host-key=...&ssh-key=...' --expr 'with import <nixpkgs> {}; runCommand "foo" {} "echo bar; mkdir $out"' --impure -L 
foo> error: sized: unexpected end-of-file
error: unexpected end-of-file
error: builder for '/nix/store/91p9v43ylijycnq32994m40613jrjdr7-foo.drv' failed with exit code 1
```
which appears to happen in `copyPaths()` (called by `build-remote`).

On a hunch I reverted the recent parallel copy changes on a branch (https://github.com/edolstra/nix/commits/hydra-temp) and deployed that to hydra.nixos.org. With that, the packet builders seem to be fine (see https://hydra.nixos.org/machines).

@vcunat @grahamc @thufschmitt 

**Expected behavior**

**`nix-env --version` output**

`nix (Nix) 2.11.0`

TODO: figure out what Nix version is on the packet builders.

**Comment by thufschmitt** [comment]
Not reproduced in a long time. Can close
