### ISSUE TITLE
Unable to install on mac studio m1

### ISSUE THREAD

**Issue by HadrienMP** [NixOS/nix#7024]
I tried to install nix on a new mac studio here are the specs:
- macOS Monterey
- Version 12.4
- Mac Studio (2022)
- Apple M1 Max
- Memory 32 GB

And it failed with the following logs https://gitlab.com/-/snippets/2406410

**Comment by abathur** [comment]
You'll have to follow the uninstall instructions before reinstalling it: https://nixos.org/manual/nix/stable/installation/installing-binary.html#macos

**Comment by HadrienMP** [comment]
It seems to work indeed! I must have been confused and not understand what happened at some point
