### ISSUE TITLE
Support flake references in NIX_PATH

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#7026]
Allow flake references in `NIX_PATH` and `-I`, e.g.
```
NIX_PATH=nixpkgs=flake:nixpkgs
```
(similar to the `channel:...` syntax).

This allows the legacy CLI to handle `<nixpkgs>` references on an otherwise fully flakified system, without having to rely on channels. In particular, it allows `<nixpkgs>` to refer to the version of Nixpkgs used to build the current system. Currently you can put something like
```
nix.nixPath = [ "nixpkgs=${nixpkgs}" ];
```
in the NixOS system configuration, but that requires `${nixpkgs}` to be materialized in the Nix store (breaking the use of e.g. zip file accessors in #6530). Also, we may want to pin nixpkgs without making it part of the system closures and making it un-GC-able.

**Comment by klarkc** [comment]
Just say this should be documented somewhere beyond this PR.
