### ISSUE TITLE
Documentation: relation between nix-shell, the store and the garbage collector

### ISSUE THREAD

**Issue by rapenne-s** [NixOS/nix#7042]
Hello

This one should explain how the nix-daemon is used in the process, a rough idea how the garbage collector works and what's happening when using nix-shell.

I'm not 100% sure how to represent the substituter and local lookup, nor if nix-daemon is requested 

```mermaid
flowchart TB
    nixshell([nix-shell]) -->|lookup| nix-store
    nixshell([nix-shell]) -->|fallback to if missing locally| nix-daemon([nix-daemon])
    nix-daemon -->|store into| nix-store[(nixstore)]
    nix-daemon --->|build it if not available in a substituter| substituters([substituters server i.e. cache.nixos.org])
    nix-store -->|derivations can be linked to prevent GC| .links[(.links)]
     
    nix-collect-garbage([nix-collect-garbage]) -->|clean derivation not registered in .links| nix-store
```

**Comment by GuillaumeDesforges** [comment]
Could the "nix-collect-garbage" and "nix-shell" be on the same horizontal line? To clearly signify they are both "entrypoints" at the same "level".

**Comment by GuillaumeDesforges** [comment]
Is it intended to be an issue instead of a PR?

**Comment by rapenne-s** [comment]
> Is it intended to be an issue instead of a PR?

I plan to make a PR at the end, but I don't know under which format we can add diagrams (ascii certainly?) and where to add them in the code :cold_sweat:

**Comment by rapenne-s** [comment]
> Could the "nix-collect-garbage" and "nix-shell" be on the same horizontal line? To clearly signify they are both "entrypoints" at the same "level".

this is doable but looks like spaghettis :/

```mermaid
flowchart TB
    nixshell([nix-shell]) -->|lookup| nix-store
    nixshell([nix-shell]) -->|fallback to if missing locally| nix-daemon([nix-daemon])
    nix-daemon -->|store into| nix-store[(nixstore)]
    nix-daemon --->|build it if not available in a substituter| substituters([substituters server i.e. cache.nixos.org])
    nix-store -->|derivations can be linked to prevent GC| .links[(.links)]
     
    nix-collect-garbage([nix-collect-garbage]) --->|clean derivation not registered in .links| nix-store
```

**Comment by rapenne-s** [comment]
Maybe we should focus on the content first, and then I could draw it the result in ASCII by hand or with some software. I think mermaid is handy, but it's really limited when you want something in the exact shape you have in mind.
