### ISSUE TITLE
cant use or reinstall nix-shell after macos sercurity update 12.5.1 (21G83)

### ISSUE THREAD

**Issue by tyoc213** [NixOS/nix#7049]
**Describe the bug**

I had been using nix-shell on a air M1 for some time now, but after security update of 2 days a go `nix-shell` wasnt found "found" on the terminal... not on path... then I tried to reinstall (removed previous traces of install on text files configuration files) and got this

https://gist.github.com/tyoc213/0c7eee5eb1b75c009a2dca93fd7fe5bd (if you want I can paste output here to stop 1 click follow, but I guess is better this way?) 

**Expected behavior**

Be able to use `nix-shell` again

**`nix-env --version` output**

```
~ % nix-env --version
zsh: command not found: nix-env
```

**Additional context**

Guess updating to `12.6` will also be bad....???

**Comment by abathur** [comment]
For future reference: you don't have to reinstall after the update. The update is overwriting the shell hook, but you can just replace it. See #3616 for more.

At this point you'll have to follow the uninstall instructions before reinstalling it: https://nixos.org/manual/nix/stable/installation/installing-binary.html#macos

**Comment by tyoc213** [comment]
Oh, but it didnt work after update... (Im blaming update as I dont know what other important thing happened this days)... but it just stopped working, that is why I tried reinstall.

Thanks will try those instructions as the ones from the install script didnt work out (like restore previous shell config files and so on)

**Comment by abathur** [comment]
> Oh, but it didnt work after update... (Im blaming update as I dont know what other important thing happened this days)... but it just stopped working, that is why I tried reinstall.

It stopped working because it wasn't on your PATH. It wasn't on your PATH because the macOS updates have been overwriting /etc/zshrc, which is where the installer puts the shell hook that adds Nix's directories to your PATH. It doesn't _break_ Nix. It just removes if from the PATH for zsh users.

**Comment by tyoc213** [comment]
resintalled worked, thx! (still could not do `nix-shell -p julia`)
