### ISSUE TITLE
Command 'security' missing on OSX in a pure shell

### ISSUE THREAD

**Issue by YPares** [NixOS/nix#705]
@copumpkin When trying to build on OSX in a pure shell a (Haskell) program that launches a sub-process, I get the following error:

```
security: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

This tells me the `security` command is missing. But when building the same program in a non-pure shell it works alright, and shows that it indeed calls the /usr/bin/security executable, either to find or read certificates.

Sorry if I'm being too vague but, does this ring any bell? Do you think it is normal, and if so, which OSX-specific package(s) should I add so that `security` might be found?

**Comment by copumpkin** [comment]
This probably belongs in nixpkgs, and is related to https://github.com/NixOS/nixpkgs/issues/3629

I don't know what the current status of anything is, but the basic point is that you need to depend on it explicitly, and `/usr/bin/security` shouldn't be accessible by design.

**Comment by YPares** [comment]
@copumpkin Thanks. Indeed in a `nix-shell --pure -p darwin.security_tool`it works.
However I'm getting a warning due to GHC now:
`Warning: unable to set locale to UTF-8 encoding; GHC may fail with 'invalid character'`
I remember it caused me some trouble on Linux which was fixed by adding glibcLocales to the buildInputs. But this packages doesn't exist on OSX, is there an equivalent?

**Comment by copumpkin** [comment]
I don't really know, sorry. Perhaps ask in ##nix-darwin on freenode IRC, or on the nixpkgs issue tracker? I don't think anyone really looks at this issue tracker, and I'm unplugged enough from the darwin work these days that I don't know much about the current state of anything on it.

**Comment by pikajude** [comment]
This bug should not happen on pure-darwin since we build security-tool ourselves. What packages are in your environment, and what commit SHA256 is your nixpkgs on?

**Comment by peti** [comment]
This is a Nixpkgs issue, really.
