### ISSUE TITLE
Rename `#! nix-shell` to `#! nix`

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/nix#7061]
Of the many things `nix-shell` does, ["entering an environment" and "wrapping an interpreted script"](https://github.com/NixOS/nix.dev/pull/325/files#diff-c4f181e06dd86e21e16eee183ffc9ef31d6e77489d5382edfdab0de00678ebb9R3-R12) have absolutely nothing to do with each other.

In particular, the shebang feature is not limited to shell scripts.

It would greatly ease telling a story around Nix features (and making it discoverable) if independent features would have distinguishable names.

## Alternatives

I imagine making it work for `nix` would require doing something involved to the top-level `nix` command.

Therefore, a cheap alternative would be to introduce a dedicated alias such as `nix-interpreter` or `nix-script`.

**Comment by thufschmitt** [comment]
Linked: #5189

**Comment by iFreilicht** [comment]
This was fixed by #8327, right?

**Comment by fricklerhandwerk** [comment]
Not exactly fixed as described in the issue, but we now have a `#! nix`, which is good.
