### ISSUE TITLE
/etc/bash.bashrc.backup-before-nix contains NIX information 

### ISSUE THREAD

**Issue by VanessaPC** [NixOS/nix#7069]
**Describe the bug**

According to the instructions I am getting on failure I get: 

2. Ensure /etc/bashrc.backup-before-nix does not have anything
   Nix-related in it. If it does, something is probably quite
   wrong. Please open an issue or get in touch immediately.

However,the files contains this lines 

```
# Nix
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
# End Nix
```

**Steps To Reproduce**

**Expected behavior**

**`nix-env --version` output**

**Additional context**

**Comment by abathur** [comment]
It's a sign nix was installed before the backups were taken, so you may need to clean it up manually.

I'd try:
1. Run `grep "End Nix" /etc/*` and manually remove those lines from any matching files that don't have the backup-before-nix extension.
2. Remove all of the files with the backup-before-nix extension.
3. Follow the remaining appropriate macOS/Linux uninstall instructions before reinstalling it: https://nixos.org/manual/nix/stable/installation/installing-binary.html#uninstalling

**Comment by VanessaPC** [comment]
Thank you. 

I did that, as well as uninstalling from mac, it then worked.
