### ISSUE TITLE
Instanciating nix-shell takes a lot of time, and fills up storage

### ISSUE THREAD

**Issue by mmequignon** [NixOS/nix#7094]
**Describe the bug**

I created a little script with a real simple `default.nix`
```nix
with import <nixpkgs> {};
with python3Packages;
 
buildPythonPackage rec {
  name = "1fichier_client";
  src = ./.;
  propagatedBuildInputs = [aiohttp];
}
```
I wrote it on my computer and pushed this on my server once my script was done.
Everything's fine on my computer. Instanciating the shell takes like 5 seconds.
However, on the server, it takes a few minutes (more than 5), and it fills up the storage (by around 75GB).

The differences between the 2 computers I tried to run this on are:
* the nixos verions 21.11 for my computer, 20.03 on the server
* the nix versions: 2.3.16 on my computer, 2.11.0 on the server

**Steps To Reproduce**

1. Run `nix-shell` with the aforementioned `default.nix`

**Expected behavior**

Instanciating the shell should take around a few seconds as on my computer.
It shouldn't fill up the storage.

**`nix-env --version` output**

`nix-env (Nix) 2.11.0`

**Additional context**

If I run `nix-shell` multiple times in a row (without garbage collect or whatever between each run), nothing changes.
After 2-3 runs, storage is full, and it still takes 75GB of storage.

**Comment by bjornfor** [comment]
Hi, I'm pretty sure that your local directory (`src = ./.;`) on the server is the reason Nix is consuming many gigabytes of data, so not really a Nix bug. Try cleaning up the source dir, and perhaps also use `lib.cleanSource` or `builtins.fetchGit` to filter out unwanted files from the source.)

**Comment by mmequignon** [comment]
> Hi, I'm pretty sure that your local directory (`src = ./.;`) on the server is the reason Nix is consuming many gigabytes of data, so not really a Nix bug. Try cleaning up the source dir, and perhaps also use `lib.cleanSource` or `builtins.fetchGit` to filter out unwanted files from the source.)

Oh, right… Sorry about that
