### ISSUE TITLE
Nix install broken by MacOS upgrade

### ISSUE THREAD

**Issue by paultiplady** [NixOS/nix#7100]
**Describe the bug**

After upgrading MacOS to 11.7 (from the previous newest version of Big Sur), Nix isn't working on my system. It seems the PATH is no longer getting populated. IIRC there were some modifications to `/etc/zshrc` that the installer makes; these are no longer present.

**Steps To Reproduce**

? Upgrade MacOS Big Sur?

**Expected behavior**

Nix install survives upgrades in MacOS.

**`nix-env --version` output**

Broken, but I have these in my store:

```
/nix/store/lgfywm4iis538xvil3cc1q6s1lymnqs7-nix-2.3.16/bin/nix-env
/nix/store/2pfjz9b22k9997gh7cb0hjk1qa4lxrvy-nix-2.11.0/bin/nix-env
```

**Additional context**

```
ls -l /etc/zsh*
-r--r--r--  1 root  wheel  3094 Jan  1  2020 /etc/zshrc
-r--r--r--  1 root  wheel  3094 Sep 14 17:39 /etc/zshrc.backup-before-nix
-rw-r--r--  1 root  wheel  9296 Jan  1  2020 /etc/zshrc_Apple_Terminal
```

It looks like the upgrade has perhaps just replaced `/etc/zshrc` with the original OS-provided zshrc?

**Comment by paultiplady** [comment]
Confirming that after reinstalling Nix, the `/etc/zshrc` now contains:

```
# Nix
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
# End Nix
```

So this was the problem. It seems that overwriting `/etc/zshrc` is not a safe/durable way of installing Nix on MacOS?

**Comment by abathur** [comment]
Correct. The update is overwriting the shell hook, but you can just replace it. See #3616 for more.

**Comment by paultiplady** [comment]
My bad -- this is clearly a dupe of that one. Not sure how I missed that when I searched. Thanks!
