### ISSUE TITLE
nix-shell command line option to print target derivation to stdout

### ISSUE THREAD

**Issue by vizanto** [NixOS/nix#711]
This is a feature request :-)

Yesterday I tried to send quite a big development environment over USB stick to another machine (using `nix-export`).

`nix-instantiate` produced an entirely different derivation with many dependencies missing to run `nix-shell`.  The first machine had spent a few hours building all the dependencies from source, that's why I wanted to export the closure to the target machine.

Finally I discovered `nix-shell -vv`  which prints the final derivation usable for `nix-store --export`, just before entering the shell.

Please add an option to nix-shell, so I can do something like:

``` sh
➭ nix-store --export --query --requisites --include-outputs \
  $(nix-shell --print-derivation) | xz > /Volumes/USB/shell.closure.xz
```

**Comment by jefdaj** [comment]
This feature request includes the best way I know, so I made it into a script.

```
#!/usr/bin/env bash
# usage: nix-export-shell-closure.sh [targetdir]

[[ -z "$1" ]] && target="$PWD" || target="$1"
outname="$(basename "$target")-shell.nix.xz"
cd "$target"
derivation="$(nix-shell -vv --command exit 2>&1 | tail -n1 | cut -d"'" -f4)"
echo "exporting $derivation to $outname"
nix-store --export $(nix-store --query --requisites --include-outputs "$derivation") |
  xz > "$outname"
```

And for completeness, the matching import script.

```
#!/usr/bin/env bash
# usage: nix-import-closure.sh file.nix.xz

echo "importing $1"
xzcat "$1" | nix-store --import
```

**Comment by edolstra** [comment]
Closing since this can already be scripted.

**Comment by vizanto** [comment]
> Closing since this can already be scripted.

As long as `nix-shell -vv` never changes 😨
