### ISSUE TITLE
Nix parsers merges multiple attribute set literals for the same key incorrectly depending on definition order

### ISSUE THREAD

**Issue by sternenseemann** [NixOS/nix#7115]
**Describe the bug**

The Nix parser not only merges nested keys in attribute set literals, but also keys defined multiple times to be an attribute set literals:

```nix
{
  set.a = 1;
  set.b = 2;
}

==

{
 set = { a = 1; };
 set = { b = 2; };
}
``` 

This *should* also work involving dynamic keys, but doesn't always:

```nix
{
  set.a = 1;
  set."${"b" + ""}" = 2;
}

!=

# This doesn't work as expected
{
 set = { a = 1; };
 set = { "${"b" + ""}" = 2; };
}

```

If you reverse the order of the attributes from the example, it curiously works:

```nix
{
  set.a = 1;
  set."${"b" + ""}" = 2;
}

==

# Defining the dynamic key first works as expected
{
 set = { "${"b" + ""}" = 2; };
 set = { a = 1; };
}
```

A similar issue doesn't occur when reversing the order of nested key syntax, so this bug seems to be exclusive to attribute set literal merging.

It seems likely that this bug is related to #7111, another ordering dependent bug in the attribute set literal merging code.

**Expected behavior**

All expressions above should evaluate to

```nix
{
  set = {
    a = 1;
    b = 2;
  };
}
```

**`nix-env --version` output**

Tested with 2.11.0 and 2.3.16.

**Comment by Ericson2314** [comment]
@sternenseemann I remember these problems from before, but curiously I cannot reproduce now? I am trying in `nix repl` with 2.11 and 2.13.

**Comment by sternenseemann** [comment]
I can reproduce the problem with Nix 2.15.1 (maybe you used attrpaths instead of attribute set literals which is required to trigger the bug):

```console
[nix-shell:~]$ nix-instantiate --version
nix-instantiate (Nix) 2.15.1

[nix-shell:~]$ cat tmp.nix
[
  { x.y = 3; x.${"z" + ""} = 2; }
  { x.${"z" + ""} = 2; x.y = 3; }
  { x = { y = 3; }; x = { ${"z" + ""} = 2; }; }
  { x = { ${"z" + ""} = 2; }; x = { y = 3; }; }
]

[nix-shell:~]$ nix-instantiate --eval --strict tmp.nix 
[ { x = { y = 3; z = 2; }; } { x = { y = 3; z = 2; }; } { x = { y = 3; }; } { x = { y = 3; z = 2; }; } ]

[nix-shell:~]$ nix-instantiate --parse tmp.nix 
[ ({ x = { y = 3; "${("z" + "")}" = 2; }; }) ({ x = { y = 3; "${("z" + "")}" = 2; }; }) ({ x = { y = 3; }; }) ({ x = { y = 3; "${("z" + "")}" = 2; }; }) ]
```

Furthermore, the `nix-instantiate --parse` proves that it is a parser bug, so we `ExprAttrs::eval` seems fine (which is a relief, possibly?).

**Comment by ncfavier** [comment]
It looks like the merging logic [here](https://github.com/NixOS/nix/blob/6db66ebfc55769edd0c6bc70fcbd76246d4d26e0/src/libexpr/parser.y#L133-L139) only merges static attributes, leaving dynamic attributes alone (which explains the ordering sensitivity).

**Comment by ncfavier** [comment]
https://github.com/NixOS/nix/pull/8664

**Comment by ncfavier** [comment]
> Couldn't reproduce

🤨

```
$ nix eval --expr '{
 set = { a = 1; };
 set = { "${"b" + ""}" = 2; };
}'
{ set = { a = 1; }; }
```

> OK-ish

I sure hope not.

> deterministic and could be well defined

Parsing `"hello"` as the number 42 is deterministic and could be well-defined.
