### ISSUE TITLE
What do -I and --arg/--argstr do in nix-build

### ISSUE THREAD

**Issue by andrewbaxter** [NixOS/nix#7119]
## Problem

All the nix-build examples do `-I nixos-config=your-system.nix`, and there's nary an explanation of that particular flag.

`nix-build` says the arguments not listed are passed to `nix-store --realize` or `nix-instantiate`, but neither of those list `-I` as a possible flag either.

I only see `nixos-config` as a parameter here <https://github.com/NixOS/nixpkgs/blob/master/nixos/default.nix>, but experimenting with it I couldn't use `-I` to fill other parameters.

Similarly, I thought `--arg` filled in an argument in the function expression that the first file passed to `nix-build` contains, but when I tried it (`--argstr`) I got `cannot evaluate a function that has an argument without a value ('avariable')`.  The `nix-build` documentation says `--arg` (and I assume `--argstr`?) are passed to `nix-instantiate` which _does_ list (the first) as flags, but there's no explanation for those flags either AFAICT.

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open documentation issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/src
[open documentation issues and pull requests]: https://github.com/NixOS/nix/labels/documentation

## Proposal

I don't know enough to write the documentation myself.

To be clear though, it would be great if the documentation included these things since they seem like core usage.  I'd like to be able to read the documentation and be able to troubleshoot the issues I'm encountering on my own.

**Comment by andrewbaxter** [comment]
My guess for `-I` is that it somehow plugs into the import search system and short circuits lookups for `nixos-config` with the path you provide.  I'm not sure why this indirect method is used over the more direct `--arg` though in this case.

**Comment by fricklerhandwerk** [comment]
@andrewbaxter Yes, this is an annoying problem. Thanks for opening the issue. Right now `-I` and `--arg` are documented as [Common Options](https://nixos.org/manual/nix/stable/command-ref/opt-common.html), which apply to "most" Nix commands. I agree they _should_ instead be listed for each command they apply to.

For `--argstr`, it appears you got the idea right, but how did you invoke it on the command line? Please show a full example of what failed to work as you expected.

**Comment by andrewbaxter** [comment]
Thanks! Yeah, I ended up working around whatever problem I had with `--argstr` or doing something different, but I'd still be interested in docs in case I run into a similar problem again.  IIRC it had something to do with confusion over `-I` taking an `A=B` format but `--argstr` requires space separated key and value.

> Common Options

Ah okay, that looks like just what I wanted.  Even if it's not listed or documented on the individual command pages I think a mention or link to the common options would be great.  I didn't see the common options section in the sidebar and it for whatever reason didn't come up while searching, but the same text is used in the man pages/help text which don't have the context of the sidebar either.

**Comment by andrewbaxter** [comment]
Ah, thanks! To be clear, once I saw the common options page the `-I` usage was clear.
