### ISSUE TITLE
NAR hash does not match between Ubuntu and macOS

### ISSUE THREAD

**Issue by aiotter** [NixOS/nix#7125]
**Describe the bug**
The NAR hash of flake input `{ url = "https://linuxjm.osdn.jp/man-pages-ja-20220815.tar.gz"; flake = false; }` does not match between Ubuntu and macOS.
The NAR hash is:

- `sha256-UZy0/j1pUfq1jw+CCqaqaEsqpeWy/sF2Jua3kdLHPMc=` on Ubuntu.
- `sha256-GPxfGzDo9RhQlk67uhfrdhm1VOcyCrFfDOa5gAmxvd8=` on macOS.

You can see this at [GitHub Actions](https://github.com/aiotter/man-pages-ja/actions/runs/3167369129/jobs/5157811642) of [this repo](https://github.com/aiotter/man-pages-ja/tree/7f7f64f5cb7352be2b03d64a0fb4db5f53e185e9).

**Steps To Reproduce**
You can refer to [GitHub Actions workflow](https://github.com/aiotter/man-pages-ja/blob/7f7f64f5cb7352be2b03d64a0fb4db5f53e185e9/.github/workflows/cache.yml).

On `x86_64-darwin`:
```bash
$ nix hash path $(nix eval --expr 'builtins.fetchTarball { url = "https://linuxjm.osdn.jp/man-pages-ja-20220815.tar.gz"; }' --impure --raw)
sha256-GPxfGzDo9RhQlk67uhfrdhm1VOcyCrFfDOa5gAmxvd8=
```

If anyone with any other platforms can help me, can you report the result of the command on your system? I'll add it here.

**Expected behavior**
NAR hash must be always the same.

**`nix-env --version` output**
The machine which I used to create the flake is `nix-env (Nix) 2.11.0` (`x86_64-darwin`).

**Additional context**
There is another version for this flake which uses git repository as a source, which also have different NAR hashes between systems.
On [this flake](), the [NAR hash from flake.lock](https://github.com/aiotter/systems/blob/7268ff51e76f4bbc091e429307f16fb9f9384867/flakes/man-pages-ja/flake.lock#L22) is `sha256-0alIk+A6mkSKWtJFDfEACt+LN78jyXrlw7Kb6cbXL9o=`, however, on Ubuntu it is `sha256-qiGCSkOaZ5ixt8O6307/UjcAzFK2VHyKrTeuEfc0Udo=` according to [GitHub Actions' output](https://github.com/aiotter/systems/actions/runs/3153901853/jobs/5130902270#step:5:37).

**Comment by abathur** [comment]
Iirc these are usually case-insensitivity issues. See if there are two files that are differently-cased versions of the same name?

**Comment by aiotter** [comment]
Do you mean there being differently-cased two files with the same filename on *the same directory*?
I don't see any errors while extracting the tarball on macOS, the system which regards differently-cased filename as the same filename. Do you have any good means to check if there are such files in the tarball?

**Comment by abathur** [comment]
I haven't had to troubleshoot one of these, so I'm not really sure what people do (nor am I certain this is it--I just know I've seen discussions about this before). If you have access to both, I guess you could run `find` on the unpacked directory of each platform and diff the outputs to find the culprit?

**Comment by aiotter** [comment]
Thanks, I have confirmed there is two file with same name but differently cased.

- man-pages-ja-20220815/manual/LDP_man-pages/man2/_exit.2
- man-pages-ja-20220815/manual/LDP_man-pages/man2/_Exit.2

- man-pages-ja-20220815/manual/LDP_man-pages/man3/NAN.3
- man-pages-ja-20220815/manual/LDP_man-pages/man3/nan.3

So the NAR hash being different because the result of unarchive is different.
As `flake.lock` is created automatically, this problem seems difficult to solve. We cannot set multiple NAR hashes for one source.

**Comment by aiotter** [comment]
Specifying `type = "file"` to store archive itself without extracting it solved the problem. Thanks!
