### ISSUE TITLE
Single/multi user installation nix.fish produces bad MANPATH

### ISSUE THREAD

**Issue by stelcodes** [NixOS/nix#7131]
**Describe the bug**

When installing Nix it installs a nix.fish script which produces a bad MANPATH environment variable. In the bash version, MANPATH is set only if it is currently not set, but in the fish version, it is always set and causes the default man location /opt/local/share/man to be excluded from the man path.

**Steps To Reproduce**

1. Install single or multi-user Nix with fish shell installed
2. Try runnning `man <executable>` for anything not installed by Nix
3. See that `man` produces an error message like `dirname: missing operand ...`

**Expected behavior**
- Default man pages for packages installed by "legacy" package managers (like `dnf`) work.

**`nix-env --version` output**
`nix-env (Nix) 2.11.1`

**Additional context**

**Comment by SuperSandro2000** [comment]
You don't need to create an issue if you open a PR that fixes it right after it.
