### ISSUE TITLE
nix-env -e dumps core

### ISSUE THREAD

**Issue by gleber** [NixOS/nix#715]
When nix-env -e is used in a [script](https://github.com/gleber/dotfiles/blob/master/uninstall.sh) it will crash dump:

$ file core
core: ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style, from '/home/gleber/.nix-profile/bin/nix-env -f <nixpkgs> -e nodejs-keybase 

If I run it manually it works without issues. I have core at hand, but it seems that nix-env is stripped and `gdb` doesn't really show much.

**Comment by gleber** [comment]
I've just found that it does not abort if replace:

     nix-env -f '\<nixpkgs\>' -e "$pkg" # 2>&1 | grep -q "uninstalling"

with just

    nix-env -f '\<nixpkgs\>' -e "$pkg"

**Comment by gleber** [comment]
It looks like nix-env does not handle well when it's stderr/stdout is abruptly closed (what's what `grep -q` does if it finds a match)

**Comment by tomberek** [comment]
Closing as stale. Re-open if needed.
