### ISSUE TITLE
nix build is failing with: 'nix __build-remote' is not a recognised command

### ISSUE THREAD

**Issue by Gerschtli** [NixOS/nix#7193]
**Describe the bug**

When running nix build to evaluate a NixOS system config in an aarch64 container, it fails with

```
error: 'nix __build-remote' is not a recognised command
Try '/nix/store/0lrf6danhdqjsrhala134ak8vn0b9ghj-nix-2.11.1/bin/nix --help' for more information.

error: unexpected EOF reading a line
         … while reading the response from the build hook
```

The output of `nix show-config | grep build-hook` is
```
build-hook = /nix/store/0lrf6danhdqjsrhala134ak8vn0b9ghj-nix-2.11.1/bin/nix __build-remote
```

The command `__build-remote` does not exist.

**Steps To Reproduce**

The only environment where I can reproduce this behaviour is in my github action where I install nix in an aarch64 container, see https://github.com/Gerschtli/nix-config/actions/runs/3280828039/jobs/5402088955.

**Expected behavior**

No error should occur and the build should succeed.

**`nix-env --version` output**

nix-env (Nix) 2.11.1

**Additional context**

Related change: https://github.com/NixOS/nix/pull/6709

**Comment by flybayer** [comment]
I'm getting this locally on M1 mac :(

Any way to pin nix version with nixpacks?

**Comment by Gerschtli** [comment]
That would be a question to the nixpacks developers, this is the repository of the nix package manager itself :)

**Comment by flybayer** [comment]
oh oops 😅

**Comment by thufschmitt** [comment]
Indeed, there's a logic to make `nix __build-remote` behave in a special way, ([here](https://github.com/NixOS/nix/blob/899878f77a1b29b337aca409ec3f7a420e574a6a/src/nix/main.cc#L273)), but it's broken (`argv[0]` should be `argv[1]`). I'm quite astonished that this could pass the tests (and not be noticed for four months :scream: ). I imagine there's a reason why it generally magically works despite the logic error
