### ISSUE TITLE
sh not called in "curl https://nixos.org/nix/install"

### ISSUE THREAD

**Issue by martinvahi** [NixOS/nix#720]
The first 4 lines of the x.txt after the command 

    curl https://nixos.org/nix/install > x.txt

are

    <an empty line>
    #!/bin/sh
    
    # This script installs the Nix package manager on your system by

That is to say, the very first line is empty in stead of starting with the **#!** and in stead of the more robust 

    #!/usr/bin/env sh

the **sh** is called by a far less robust 

    #!/bin/sh

The problem is that different Linux distributions can have the various shell binaries/startup-scripts at different paths, which are looked up by the de facto standardized **/usr/bin/env**, but the **#!/bin/sh** might not work on all Linux distributions.

**Comment by lethalman** [comment]
/bin/sh is perfectly fine compared to other programs, because glibc relies on /bin/sh.

**Comment by martinvahi** [comment]
If You say so. I would leave this issue open and make the change, but it's Your decision.

**Comment by Ericson2314** [comment]
Well, I'd say the nixpkgs maintainers know more about non-standard location than anyone, and even they cannot get rid of `/bin/sh`.

What about the blank line?

**Comment by vcunat** [comment]
Yeah, the blank line seems not portable to me (and useless anyway).

**Comment by lethalman** [comment]
Don't know if the blank line is a problem, but I haven't heard anybody complaining yet about having problems. In principle it may give troubles on systems other than linux.
