### ISSUE TITLE
Optional flake inputs

### ISSUE THREAD

**Issue by RyanGibb** [NixOS/nix#7205]
E.g.
```
inputs.foo = {
  url = "...";
  optional = true;
};
```

Use case: I have a private flake input that prevents someone else building the project. However this forms only a small part of the larger project. It would be good for anyone to be able to build the rest without having to access the private input.

**Comment by jakehamilton** [comment]
This might be a good thing to put through the [RFC process](https://github.com/nixos/rfcs). It certainly has a lot of edges that would need to be ironed out.

Though, for your use case today it may make sense to set the input to an empty repository by default and then use `--override-input foo=...` to map things to use your private data.

**Comment by RyanGibb** [comment]
> This might be a good thing to put through the [RFC process](https://github.com/nixos/rfcs). It certainly has a lot of edges that would need to be ironed out.

That sounds like a great idea. Thanks for the suggestion.

> Though, for your use case today it may make sense to set the input to an empty repository by default and then use --override-input foo=... to map things to use your private data.

Interesting. Is there a standard way to point to an empty repository (e.g. `input = 'null'`)?

**Comment by jakehamilton** [comment]
@RyanGibb I don't believe there's a built-in way. However, you could do something like use a subdirectory of your flake or push up an super bare flake repo. I would probably opt for the second so you can do something like:

```nix
{
  inputs = {
    secret-stuff.url = "github:ryangibb/empty";
  };
}
```

That would probably be the cleanest way given the current constraints. Would still be worth bringing up in an RFC if you're interested. I know that I've thought about trying to use private modules in my public flake, but haven't actually tried due to current limitations.

**Comment by RyanGibb** [comment]
Thanks, @jakehamilton ! I'll have a go at creating an RFC

**Comment by RyanGibb** [comment]
So I've tried overriding an empty flake input, but it doesn't seem to work:
```
nix build --override-input cv "git+ssh://git@github.com/RyanGibb/cv.git?ref=main"
warning: Git tree '/home/ryan/projects/gibbr.org' is dirty
warning: not writing modified lock file of flake 'git+file:///home/ryan/projects/gibbr.org':
• Updated input 'cv':
    'path:/nix/store/qlzcbb316lz7b8yygs67zbi8x9w0d4nk-source/flake.nix?lastModified=1&narHash=sha256-TIEAoFhFsRyU0zX8sD6cyMgr3lujKfVnb23wKQSKuKU=' (1970-01-01)
  → 'git+ssh://git@github.com/RyanGibb/cv.git?ref=main&rev=a21b3ad535c7f7ceb5b768c0ccc71d9438fa290e' (2022-10-22)
error: attribute 'defaultPackage' missing

       at /nix/store/y02x767n7ixyfg8d9hcqwifymq9j98zl-source/flake.nix:31:20:

           30|               ${pkgs.rsync}/bin/rsync -a --exclude '*.md' --exclude 'result' --exclude '.*' . $out
           31|               cp ${cv.defaultPackage.${system}}/*.pdf $out/resources/cv.pdf
             |                    ^
           32|             '';
(use '--show-trace' to show detailed location information)
```

**Comment by RyanGibb** [comment]
But both of these succeed:
```
$ nix build "git+ssh://git@github.com/RyanGibb/cv.git?ref=main"
$ nix build "git+ssh://git@github.com/RyanGibb/cv.git?ref=main#defaultPackage.x86_64-linux"
```

**Comment by SuperSandro2000** [comment]
Instead of hacking something into flake inputs, could this easily be handled in nix code that the part that requires private code is optional?

**Comment by RyanGibb** [comment]
I suppose we could possibly write a derivation that is optional, but then we lose the advantages flakes give us for composing projects, like updating the git revision easily.

**Comment by RyanGibb** [comment]
Ah-ha!

This was failing because I had `inputs.cv.flake = false;`.

**Comment by RyanGibb** [comment]
Okay this commit adds this for the repo that takes the private repo as an input: https://github.com/RyanGibb/gibbr.org/commit/86403e25363a391a1033bbdb7e83c16044268a2e

And this commit overrides the private input when deploying it on a NixOS system: https://github.com/RyanGibb/nixos/commit/9d13ca8e5437a64351d124ed6a94b60b8d39c2e1

**Comment by RyanGibb** [comment]
> People that do not have access to the private repo can't update it but it should otherwise work because flakes should be downloaded lazy.

Oh I see, let me try this.

**Comment by RyanGibb** [comment]
The only thing is, how can we pass a flag to enable using the private repo?

At the moment I'm checking whether or not the private repo flake contains a `defaultPackage` to determine whether it's empty or not.

**Comment by RyanGibb** [comment]
https://github.com/NixOS/nix/issues/2861 made me realised we can effectively pass an argument by targeting a different derivation: https://github.com/RyanGibb/gibbr.org/commit/a899ee6ca403ce6f71cfbcb20a647bde79652bef.

I think this closes the issue. Thanks @SuperSandro2000!
