### ISSUE TITLE
Make `-L`/`--print-build-logs` configurable in a config file.

### ISSUE THREAD

**Issue by NorfairKing** [NixOS/nix#7237]
**Is your feature request related to a problem? Please describe.**

I have to type `-L` after every command.

**Describe the solution you'd like**

Have the nix config file accept `print-build-logs`

**Describe alternatives you've considered**

`alias nix='nix -L'`

**Comment by Artturin** [comment]
Dupe of https://github.com/NixOS/nix/issues/5858
