### ISSUE TITLE
Show the full log for a build failure, but only on build failure

### ISSUE THREAD

**Issue by Gabriella439** [NixOS/nix#7238]
The request is to have an option for the `nix build` command to display the full log for a failed build while **not** displaying logs for successful builds.

Specifically, the following alternatives are not exactly what I'm looking for:

- Non-solution 0: Use `--print-build-logs`

  This prints all build logs for both successes and failures.  I'm only interested in logs for failed builds.  Logs for successful builds are not interesting to me and only dilute the output of interest (the log for the failed build).

- Non-solution 1: Use `nix log` on the same installable that `nix build` just attempted to build

  This does not work if a dependency fails to build.  This only works if the top-level build product for the installable failed to build.

- Non-solution 2: Run `nix log` on the `.drv` file for the failed build

  Unfortunately, there's not a good programmatic way to extract the path to the `.drv` that failed when a dependency failed to build.  The `.drv` file is present in error message (i.e. `"For full logs, run 'nix log /nix/store/….drv'."`), but parsing the error message to extract that path is undesirable.

- Non-solution 3: The default `nix build` experience

  The current default user-experience for `nix build` is almost exactly what I want *except that it truncates the logs for the build failure*.  If there were an option to behave in the exact same way as it is currently does without truncating the failed build log then that would be perfect.

A similar idea to add a `--show-log-on-failure` option was proposed in https://github.com/NixOS/nix/issues/1904#issuecomment-368346511 but that suggestion went nowhere.

**Describe the solution you'd like**

I'm not picky about the user experience for this.  For example, this could be a command-line option or Nix configuration setting or it could be a special-case of a more powerful system for customizing output.  I only want this to be possible in some way, and I don't mind if it's not ergonomic.

I can think of several ways to potentially solve this, all of which would be fine with me:

- Possible solution 0: Add a `--no-truncate-failure` or `--log-lines=N` option

  … so that `nix build` displays the full log (or up to N lines) of the build failure when a build fails

- Possible solution 1: Provide a way to programmatically retrieve the `.drv` for the dependency that failed to build

  … so that I can `nix log` that `.drv` file

- Possible solution 2: Make `nix log` more intelligent so that it can display the logs for a dependency build failure for the given installable

If I had to pick a solution, I'd suggest "possible solution 0", again because the current user experience for `nix build` is already *sooo* close to what I want modulo the log truncation.

**Comment by ncfavier** [comment]
You can already do `nix build --option log-lines N`, although there doesn't seem to be a way to say ∞.

**Comment by Gabriella439** [comment]
Whoops!  I'm so embarrassed that I didn't check for that option 😅.  I just assumed it didn't exist

That's good enough for me, so I'll mark this closed.

**Comment by arianvp** [comment]
This doesn't address the original ask, which still seems valuable. I don't know upfront how many logs a derivation is printing; so `--log-lines N` is unhelpful.
