### ISSUE TITLE
Allow specifying the ssh port in the config file for build-remote.pl

### ISSUE THREAD

**Issue by basvandijk** [NixOS/nix#724]
I would like to use the `nix.buildMachines` NixOS option but my build machine has SSH listening on a non standard port. So it would be nice if the config file for the build hook `build-remote.pl` could specify the SSH port. 

I'm not sure what syntax is best. Either:

```
nix@mcflurry.labs.cs.uu.nl  -p 223  powerpc-darwin  /home/nix/.ssh/id_quarterpounder_auto  2
nix@scratchy.labs.cs.uu.nl          i686-linux      /home/nix/.ssh/id_scratchy_auto        8 1 kvm
nix@itchy.labs.cs.uu.nl     -p 2233 i686-linux      /home/nix/.ssh/id_scratchy_auto        8 2
nix@poochie.labs.cs.uu.nl           i686-linux      /home/nix/.ssh/id_scratchy_auto        8 2 kvm perf
```

or:

```
nix@mcflurry.labs.cs.uu.nl:223 powerpc-darwin  /home/nix/.ssh/id_quarterpounder_auto  2
nix@scratchy.labs.cs.uu.nl     i686-linux      /home/nix/.ssh/id_scratchy_auto        8 1 kvm
nix@itchy.labs.cs.uu.nl:2233   i686-linux      /home/nix/.ssh/id_scratchy_auto        8 2
nix@poochie.labs.cs.uu.nl      i686-linux      /home/nix/.ssh/id_scratchy_auto        8 2 kvm perf
```

I guess the former is more SSH-like.

**Comment by cstrahan** [comment]
@edolstra What is your preference between the two proposals by @basvandijk? I can take this on, if we can decide on one or the other.

It would be nice to have this for Darwin, so Linux derivations can be built locally in a VM.

/cc @copumpkin

**Comment by edolstra** [comment]
The way I specify ports and other SSH configuration for Hydra build machines is to put it in ~/.ssh/config or /etc/ssh/ssh_config. Example: https://github.com/NixOS/nixos-org-configurations/blob/master/delft/lucifer.nix#L149

**Comment by basvandijk** [comment]
@edolstra Thanks I also used that approach earlier this week when I needed to set ssh-substituter-hosts to our private hydra machine.

For me this is actually good enough. It would be nice however if the port could be specified directly.

Feel free to close this issue.

**Comment by domenkozar** [comment]
I did the same, but it would be nice to document that somewhere.

**Comment by hacker1024** [comment]
> The way I specify ports and other SSH configuration for Hydra build machines is to put it in ~/.ssh/config or /etc/ssh/ssh_config. Example: https://github.com/NixOS/nixos-org-configurations/blob/master/delft/lucifer.nix#L149

This link is dead; the example last appeared [here](https://github.com/NixOS/nixos-org-configurations/blob/5ecc52ceb7ef78901f08b5ba408f031944a082d2/delft/hydra.nix#L70-L127).

**Comment by n0099** [comment]
Fixed in https://github.com/NixOS/nix/issues/7044
