### ISSUE TITLE
CUDA kernel/userspace interface issue due to cuda.so.1

### ISSUE THREAD

**Issue by twhitehead** [NixOS/nix#725]
We are running Nix as a package manager alongside CentOS 6.  It is working good except for the fact that CUDA packages aren't working.  For example, `caffe` (from nixpkgs tag 15.09) gives

> $ caffe device_query --gpu=0
> I1201 12:09:52.707620 25856 caffe.cpp:73] Querying device ID = 0
> F1201 12:09:52.790141 25856 common.cpp:131] Check failed: error == cudaSuccess (35 vs. 0) CUDA driver version is insufficient for CUDA runtime version

Using `strace` I discovered the problem is that the `cudatoolkit` libraries are trying to load a *libcuda.so.1* library (although it is not declared as an official a shared library dependency by any of the ELF objects).  Digging reveals this is a kernel/user-space shimmy library shipped with the CUDA kernel driver and that it is tightly tied to the specific version of that CUDA kernel driver.

> $ readlink -f /usr/lib64/libcuda.so
> /usr/lib64/nvidia/libcuda.so.352.55

Using LD_PRELOAD to load this into the NIX binary results in it working as expected

> $ LD_PRELOAD=/usr/lib64/libcuda.so caffe device_query --gpu=0
> I1201 12:18:10.561049 25949 caffe.cpp:73] Querying device ID = 0
> I1201 12:18:10.568706 25949 common.cpp:157] Device id:                     0
> I1201 12:18:10.568722 25949 common.cpp:158] Major revision number:         3
> I1201 12:18:10.568725 25949 common.cpp:159] Minor revision number:         5
> I1201 12:18:10.568730 25949 common.cpp:160] Name:                          Tesla K20m
> ...

How should Nix properly handle this?  The *libcuda.so.1* could be put in the Nix store, but it turns out that quickly creates a fragile situation where any update to the host NVIDIA driver version instantly breaks all installed Nix CUDA binaries as, if *libcuda.so.1* does not perfectly match the kernel NVIDIA driver version, CUDA executable fail and the kernel spits messages of the form

> NVRM: API mismatch: the client has the version 352.55, but
> NVRM: this kernel module has the version 352.39.  Please
> NVRM: make sure that this kernel module and all NVIDIA driver
> NVRM: components have the same version.
> NVRM: nvidia_frontend_ioctl: minor 255, module->ioctl failed, error -22

To me this suggests that, as Nix uses the host kernel, it should also use the host provided version of this library.  The logic here being that *libcuda.so.1* is so tightly tied to the kernel it should really be considered part of the kernel interface (provided by the host) and not userspace (provided by Nix).

What do people think, and how might this best be done?

Thanks!  -Tyson

**Comment by copumpkin** [comment]
I don't have an answer for you, but you might have better luck cross-posting this question to the nixpkgs tracker, which far more people look at :smile:

**Comment by twhitehead** [comment]
Thank copumpkin.  I hadn't realized I had opened this ticket against nix.  It was suppose to be against against nixpkgs as you suggest.  I would likely have been waiting a long time for answers if you hadn't pointed this out for me.  I'm closing this issue out and opening another against nixpkgs.

**Comment by copumpkin** [comment]
Cool, thanks :smile: it confuses people quite often. We should probably add a contributing.md to this repo so we can add a warning.
