### ISSUE TITLE
Installing nix script does not work for sysbox container runtime

### ISSUE THREAD

**Issue by sandangel** [NixOS/nix#7253]
**Describe the bug**

We are using this container run time for adding kubernetes pods as github runners.

https://github.com/nestybox/sysbox

For the image, we just use ubuntu. When try installing nix, we got this error:

```sh
  performing a single-user installation of Nix...
  directory /nix does not exist; creating it by running 'mkdir -m 0755 /nix && chown runner /nix' using sudo
  
  copying Nix to /nix/store...
  installing 'nix-2.11.1'
  error: mounting /proc: Invalid argument
  (use '--show-trace' to show detailed location information)
  /tmp/nix-binary-tarball-unpack.kqOzK4m4m1/unpack/nix-2.11.1-x86_64-linux/install: unable to install Nix into your default profile
```

**Steps To Reproduce**

1.  Install on a linux machine: https://github.com/nestybox/sysbox#installation
2. docker run --runtime=sysbox-runc -it ubuntu:latest
3. install nix `sh <(curl -L https://nixos.org/nix/install) --daemon`

**Expected behavior**

Should be no error

**`nix-env --version` output**

**Additional context**

**Comment by SuperSandro2000** [comment]
> ```shell
>   error: mounting /proc: Invalid argument
> ```

is sysbox not mounting all proc paths nix wants?

**Comment by sandangel** [comment]
I'm not sure which /proc path nix want, if you can show me I can check internally.

**Comment by SuperSandro2000** [comment]
Did a quick search and at least the following:

https://github.com/NixOS/nix/blob/0f64bf445a229c4f5ce19dc19a552f58701ca1ca/src/libstore/gc.cc#L352
https://github.com/NixOS/nix/blob/eafa2721ca8996ff55897033243ac56ca1c8196c/src/nix/run.cc#L261-L263
https://github.com/NixOS/nix/blob/8196d4f4e94407396b4ba37bd89c91ad0d4062f0/src/libstore/build/local-derivation-goal.cc#L805
https://github.com/NixOS/nix/blob/8196d4f4e94407396b4ba37bd89c91ad0d4062f0/src/libstore/build/local-derivation-goal.cc#L867
https://github.com/NixOS/nix/blob/9dadb5481cdf848c409e6a7e4953acf4861923a5/src/libutil/util.cc#L730
https://github.com/NixOS/nix/blob/9dadb5481cdf848c409e6a7e4953acf4861923a5/src/libutil/util.cc#L613

**Comment by sandangel** [comment]
thanks. I will ask my team

**Comment by sandangel** [comment]
this works after disablinh sandbox. thanks
