### ISSUE TITLE
Mark the test CI jobs as required

### ISSUE THREAD

**Issue by thufschmitt** [NixOS/nix#7309]
This is required for “auto-merge” to be useful (since otherwise it will just wait for the CI to finish and merge regardless of the result).

For that:

- Go to https://github.com/nixos/nix/settings/branches
- Edit the protection rule for the `master` branch
- Under “Protect matching branches” >> “Require status checks to pass before merging” add the `installer_test` `tests (macos-latest)` and `tests (ubuntu-latest)` as required status checks (using the search box to find them)

![image](https://user-images.githubusercontent.com/7226587/202151960-ea7d32fd-7b41-4efa-8857-ee7a8939d40c.png)

I'd gladly do it myself, but I don't have the rights for it

**Comment by edolstra** [comment]
Done!
