### ISSUE TITLE
sha512 and netrc

### ISSUE THREAD

**Issue by Teekuningas** [NixOS/nix#7311]
Hello,

It seems pkgs.fetchurl supports sha512 but does not support --netrc-file option, at least not in a trivial way.

And it seems builtins.fetchurl supports --netrc-file option but does not support sha512.

Is there any way builtins.fetchurl could support sha512, as for example npm uses it as the integrity checksum? 

Thanks,
Tk

**Comment by Teekuningas** [comment]
Thanks. I remember this involved sandbox-paths and netrc getting copied to /nix/store, unlike with builtins.fetchurl. I might be wrong.

The main alternative I consider is to just prefetch packages, and get their sha256. It just feels unnecessary waste of resources..

**Comment by aakropotkin** [comment]
Builtin fetchurl does support sha512... if you look under the hood : https://github.com/aakropotkin/laika/blob/main/src/fetchurlDrv/fetchurlDrvUnwrapped.nix

**Comment by Teekuningas** [comment]
How do you use it?
```
nix-repl> builtins.fetchurl { url = "https://upload.wikimedia.org/wikipedia/commons/2/28/Nix_snowflake.svg"; sha256="1wn57n3lrk3zqvyrv6xxscnz2x6diddaagjwv769hc2q9g8swj7p"; }
"/nix/store/z0kkg4azsd7pjy4kj2qdiza8wbd9zf6n-Nix_snowflake.svg"

nix-repl> builtins.fetchurl { url = "https://upload.wikimedia.org/wikipedia/commons/2/28/Nix_snowflake.svg"; sha512="2652df6va9wdmrp71jl58x2k366pa3pcfgqanqll330nvjhfsz0r9k66l9wwrmxj8pb4i4b1p17z09q655fcjqf8hjg1ji9nhl0iby3"; }
error: unsupported argument 'sha512' to 'fetchurl'

nix-repl> :b pkgs.fetchurl { url = "https://upload.wikimedia.org/wikipedia/commons/2/28/Nix_snowflake.svg"; sha512="2652df6va9wdmrp71jl58x2k366pa3pcfgqanqll330nvjhfsz0r9k66l9wwrmxj8pb4i4b1p17z09q655fcjqf8hjg1ji9nhl0iby3"; }
This derivation produced the following outputs:
  out -> /nix/store/5y3b2nxlhkbysvbvzy3qvb8msvicl60n-Nix_snowflake.svg
```

**Comment by aakropotkin** [comment]
> How do you use it?
> ```
> nix-repl> builtins.fetchurl { url = "https://upload.wikimedia.org/wikipedia/commons/2/28/Nix_snowflake.svg"; sha256="1wn57n3lrk3zqvyrv6xxscnz2x6diddaagjwv769hc2q9g8swj7p"; }
> "/nix/store/z0kkg4azsd7pjy4kj2qdiza8wbd9zf6n-Nix_snowflake.svg"
> 
> nix-repl> builtins.fetchurl { url = "https://upload.wikimedia.org/wikipedia/commons/2/28/Nix_snowflake.svg"; sha512="2652df6va9wdmrp71jl58x2k366pa3pcfgqanqll330nvjhfsz0r9k66l9wwrmxj8pb4i4b1p17z09q655fcjqf8hjg1ji9nhl0iby3"; }
> error: unsupported argument 'sha512' to 'fetchurl'
> 
> nix-repl> :b pkgs.fetchurl { url = "https://upload.wikimedia.org/wikipedia/commons/2/28/Nix_snowflake.svg"; sha512="2652df6va9wdmrp71jl58x2k366pa3pcfgqanqll330nvjhfsz0r9k66l9wwrmxj8pb4i4b1p17z09q655fcjqf8hjg1ji9nhl0iby3"; }
> This derivation produced the following outputs:
>   out -> /nix/store/5y3b2nxlhkbysvbvzy3qvb8msvicl60n-Nix_snowflake.svg
> ```

You have to write a derivation that uses `builtin:fetchurl` set as its builder. That is the actual implementation of the `builtins.fetchurl` function.

The file I linked provides a function that can be used like the builtin for convenience.

```
let
  laika = builtins.getFlake "github:aakropotkin/laika";
in laika.lib.libfetch.fetchurlDrv { sha512 = "..."; url = "..."; unpack = true; }
```

**Comment by Teekuningas** [comment]
Ohh, you can do that. It works yes, I am able to specify sha512 and --netrc-file works too. Thanks!

I'll close.

**Comment by aakropotkin** [comment]
No sweat. I needed the exact same thing to fetch GitHub Packages from their NPM registry. We've been using this for ~6 months and it's been reliable.

**Comment by Teekuningas** [comment]
Another way?

```
nix-repl> :b import <nix/fetchurl.nix> { url = "https://upload.wikimedia.org/wikipedia/commons/2/28/Nix_snowflake.svg"; sha512="2652df6va9wdmrp71jl58x2k366pa3pcfgqanqll330nvjhfsz0r9k66l9wwrmxj8pb4i4b1p17z09q655fcjqf8hjg1ji9nhl0iby3"; }           

This derivation produced the following outputs:
  out -> /nix/store/5y3b2nxlhkbysvbvzy3qvb8msvicl60n-Nix_snowflake.svg
```

**Comment by aakropotkin** [comment]
> Another way?
> 
> ```
> nix-repl> :b import <nix/fetchurl.nix> { url = "https://upload.wikimedia.org/wikipedia/commons/2/28/Nix_snowflake.svg"; sha512="2652df6va9wdmrp71jl58x2k366pa3pcfgqanqll330nvjhfsz0r9k66l9wwrmxj8pb4i4b1p17z09q655fcjqf8hjg1ji9nhl0iby3"; }           
> 
> This derivation produced the following outputs:
>   out -> /nix/store/5y3b2nxlhkbysvbvzy3qvb8msvicl60n-Nix_snowflake.svg
> ```

Yeah this also works. The distinction is that the builtin has no dependencies which CI runtimes may care about, and the builtin's slightly faster execution can make a difference at scale.

If you're building on a machine you use regularly, and only fetching a few tarballs the builtin isn't really bringing anything new to the table. But if you need to build in throwaway VMs and don't want to risk building CURL, OpenSSL, coreutils, and the rest of `stdenv`just to fetch a tarball this is useful. Or if you need to fetch a few thousand tarballs ( especially from a throwaway VM ), the builtin is a major optimization.

These languages that the kids are into these days like Node, Go, and Rust can't seem to do much of anything without installing a few thousand <1 Mb "modules" first, and if you're using Nixpkgs' `fetchurl` you're wasting an enormous amount of time spinning up sandboxes. You could bundle them at the expense of refetching in bundles if any of them change, but if you use the builtin none of that's an issue anymore.

**Comment by Teekuningas** [comment]
But isn't <nix/fetchurl.nix> also using the builtin:fetchurl? As it is this: https://github.com/NixOS/nix/blob/master/src/libexpr/fetchurl.nix

Laika definitely seems a useful abstraction.

**Comment by edolstra** [comment]
There may be some (understable) confusion here between `builtins.fetchurl` and `builtin:fetchurl`.

* `builtins.fetchurl` happens at evaluation time in the context of the user. It doesn't support `sha512`.
* `<nix/fetchurl.nix>` (which is a function that produces a derivation with the magic `builtin:fetchurl` builder) happens at build time. It *does* support `sha512`.
