### ISSUE TITLE
Improve `readDir` performance

### ISSUE THREAD

**Issue by roberth** [NixOS/nix#7314]
**Is your feature request related to a problem? Please describe.**

`builtins.readDir` currently performs stat calls for each directory entry. This is bad enough that @aakropotkin works around `readDir` with a generated file. A fast `readDir` may allow Nixpkgs to replace `all-packages.nix` over time; a project that the Nixpkgs Architecture Team is researching.

**Describe the solution you'd like**

Implementation 1, posix compatible:
Fill the attrset with thunks that call `pathType` https://github.com/NixOS/nix/issues/3096

Implementation 2, linux optimized:
Use [`getdents` or `getdents64`](https://man7.org/linux/man-pages/man2/getdents.2.html)

**Describe alternatives you've considered**

Avoid `readDir` on large directories, generate a list of files. The `readDir` function is not crucial for the architecture team proposal.

**Additional context**

https://github.com/nixpkgs-architecture/auto-called-packages/issues/17#issue-1450633492

**Comment by edolstra** [comment]
I'm a bit skeptical about `auto-called-packages`. It inherently makes any Nix evaluation take time linear in the size of Nixpkgs, rather than the size of the packages used by the derivation you're building. A full traversal would be deadly on non-SSD drives (and even on SSD it takes >2 seconds on a cold cache), but maybe we don't need to care about that anymore.

Having said that, `readDirectory` is supposed to avoid `stat` calls by returning a `type` hint (which may be `DT_UNKNOWN` depending on the filesystem/OS).

**Comment by roberth** [comment]
> It inherently makes any Nix evaluation take time linear in the size of Nixpkgs

Technically this is already the case, but with a small constant factor.
We won't be scanning recursively, but if performance suffers, we will use a generated list in a file instead.

> Having said that, `readDirectory` is supposed to avoid `stat` calls by returning a `type` hint (which may be `DT_UNKNOWN` depending on the filesystem/OS).

It seems that we've overlooked this. "Implementation 2" seems to be already implemented then. The `.type` thunk optimization could still be implemented.

**Comment by Ericson2314** [comment]
Yeah it is already linear time today. And even if Nixpkgs continues to not use it, it should still be better if we can make it better. Finally, if we ever do https://github.com/NixOS/nix/issues/4090 we can simply stat paths (or the lazy trees equivalent) when attributes are accessed, fully lazy again!

**Comment by edolstra** [comment]
Other than the size of `all-packages.nix`, how is it linear? Doing `nix-build -A hello` will only read the Nix files for `hello` and its dependencies. It's not doing a traversal of the entire Nixpkgs tree.

**Comment by Ericson2314** [comment]
#7447 does the first part of this.

**Comment by Ericson2314** [comment]
https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/unix/sysv/linux/readdir64.c;h=7952da5c27555e44f3970629f8cfd39cb42425f3;hb=HEAD#l42 shows that glibc 
and https://git.musl-libc.org/cgit/musl/tree/src/dirent/readdir.c shows that musl already does chunking internally so I don't think the second part is necessary on Linux.

We didn't get into empirical benchmarking that much today, but @gropotkin did say things seemed plenty fast on Linux in general, and the problem might be macOS only. We'll do more exploring over this I suppose next time.
