### ISSUE TITLE
Suggestion to make `nix flake init` automatically call `nix flake update`

### ISSUE THREAD

**Issue by peterbecich** [NixOS/nix#7316]
**Is your feature request related to a problem? Please describe.**
`nix flake update` solved an issue for me easily. It had not realized the Flake created by `nix flake init` was out-of-date.

To be specific, this was a Nix Flake template for https://github.com/purs-nix/purs-nix created this way:
```
nix flake init -t github:purs-nix/purs-nix
```
The template created by this command was out-of-date, and `nix flake update` fixed it.

**Describe the solution you'd like**

`nix flake init` automatically calls `update`.

Or perhaps a flag `nix flake init --update`

**Describe alternatives you've considered**
Perhaps the current design is intentional for a reason I'm unaware of?

**Additional context**

**Comment by edolstra** [comment]
I don't think `nix flake init` should do that. The template presumably has been tested with the included lock file, while upgrading the dependencies may produce a flake that doesn't work.
