### ISSUE TITLE
Inconsistency between `nix print-dev-env` and `nix print-dev-env --json`

### ISSUE THREAD

**Issue by Strum355** [NixOS/nix#7322]
**Describe the bug**

The variables in the output from `nix print-dev-env --json` don't match those from `nix print-dev-env`, even basic ones such as `out`. Example snippets:

```json
{
	...
	"variables": {
		"out": {
			"type": "exported",
			"value": "/nix/store/fb8pj0p3x81v4328y0lqj03psxnc4jzx-sourcegraph-dev-env"
		},
		"outputBin": {
			"type": "var",
			"value": "out"
		},
		"outputDev": {
			"type": "var",
			"value": "out"
		},
	...
}
```

vs

```bash
...
out='/home/<user>/<directory>/outputs/out'
export out
outputBin='out'
outputDev='out'
...
```

It also extends to variables such as `HOME` (set to `/homeless-shelter` in the JSON output, but not overwritten in the bash script output, and `PATH` that is prepended to the inherited `PATH`, but not prepended in the JSON output.

The case for `PATH` is slightly more complex, see the minimized example of what Im observing from the bash script:

```bash
BANANA=${BANANA:-}
nix_saved_BANANA="$BANANA"
# ...
BANANA='changed'
export BANANA
# ...
BANANA="$BANANA:$nix_saved_BANANA"
```

```
[noah@archlinux]$ export BANANA=asdf
[noah@archlinux]$ echo $BANANA
asdf
[noah@archlinux]$ source test.sh
[noah@archlinux]$ echo $BANANA
changed:asdf
```

The last line in the above script is not materialized in the JSON output (although I understand this may be a bit more complex, but replicating the script via the JSON output requires knowing what other variables this applies to, from what I've observed it also affects `XDG_DATA_DIRS`.

**Steps To Reproduce**

1. Take a basic `flake.nix` such as found in https://github.com/sourcegraph/sourcegraph/blob/main/flake.nix
2. Compare the output from `nix print-dev-env --json ` and `nix print-dev-env`

**Expected behavior**

Output should more closely match each other where possible

**`nix-env --version` output**

`nix-env (Nix) 2.11.1`

**Additional context**

Arch Linux, not NixOS

**Comment by edolstra** [comment]
`--json` is intended for use by other programs, so it does not try to do user-friendly things like redirecting output variables to writable locations or extend `$PATH`. It's up to the consumer of `--json` to do that.
