### ISSUE TITLE
Release 2.12

### ISSUE THREAD

**Issue by roberth** [NixOS/nix#7371]
**Is your feature request related to a problem? Please describe.**
[I'm always frustrated when] fixes are merged but not released.

**Describe the solution you'd like**
Release Nix 2.12.0.
Apply and release backports.

**Describe alternatives you've considered**
Treat Nix master as a rolling release and cut releases in Nixpkgs instead.

**Additional context**

Releases were supposed to be 6-weekly, but 13 weeks have passed since 2.11.0.

**Comment by edolstra** [comment]
Yeah we slipped a bit. I'll pick a new date for the 2.12 milestone.

**Comment by roberth** [comment]
Is the 6-week cadence too short?
Releasing should be easy. Should we automate more?

**Comment by fricklerhandwerk** [comment]
Discussed on Nix team meeting 2022-12-02:

  - @thufschmitt: can we delegate cutting the release so two people can deal with it?
      - @edolstra: in theory. it would require giving multiple people the credentials, that's work.
  - @roberth: can we set up a CI pipeline where people who have access to some branch can trigger it?
      - @edolstra: yes, but that's also work
      - @fricklerhandwerk: that would be time well-invested, since there will be many more releases in the future
  - @Ericson2314: proposal: delegate this to someone to encode the process, and @edolstra just decides
  - @edolstra: happy to be the release manager at the moment
  - @thufschmitt: could the process be documented?
      - @edolstra: yes, will do
  - @infinisil: could we have a co-release manager to share the knowledge?
      - @edolstra: yes, that's possible
      - ideally @edolstra would just accept a PR from that person
        - @tomberek: that's how it works in Nixpkgs
            - @edolstra: releasing Nixpkgs is a big job, but for Nix it's just running a script
                - @tomberek: running the script is trivial, what matters is defining what one wants in the release to be confident what should be in production, and all the process around it
  - agreement: @roberth will join @edolstra to cut the release
