### ISSUE TITLE
Document available system features

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/nix#7380]
## Problem

There is no place in the manual where all system features are listed and described.

[Remote Builds](https://nixos.org/manual/nix/unstable/advanced-topics/distributed-builds.html) only contains examples.

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open documentation issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/src
[open documentation issues and pull requests]: https://github.com/NixOS/nix/labels/documentation

## Proposal

Make a clearly visible list in the [system features](https://github.com/NixOS/nix/blob/ca42068bdc26108cfbd9f7db8af03730bc66d13a/src/libstore/globals.hh#L638-L650) documentation and describe what each of them does.

Existing features:
- `kvm`
- `uid-range`

**Comment by thufschmitt** [comment]
Agreed.

Most system-features are just user-defined, but the ones that Nix understands or sets automatically should be documented.

From my memory and a quick grepping of the codebase, there is:
- `nixos-test`, `benchmark`, `big-parallel` which are always set by default (https://github.com/NixOS/nix/blob/ca42068bdc26108cfbd9f7db8af03730bc66d13a/src/libstore/globals.cc#L131)
- `uid-range` set by default for Linux (https://github.com/NixOS/nix/blob/ca42068bdc26108cfbd9f7db8af03730bc66d13a/src/libstore/globals.cc#L134)
- `kvm` set for Linuxes with `/dev/kvm` available (https://github.com/NixOS/nix/blob/ca42068bdc26108cfbd9f7db8af03730bc66d13a/src/libstore/globals.cc#L137-L140), and causes `/dev/kvm` to be mounted inside the sandbox
- `ca-derivations`, which is set by default when the corresponding experimental feature is enabled (https://github.com/NixOS/nix/blob/ca42068bdc26108cfbd9f7db8af03730bc66d13a/src/libstore/store-api.cc#L448-L452) and required by CA derivations
- `recursive-nix` which are by default set when the corresponding experimental feature is enabled (https://github.com/NixOS/nix/blob/ca42068bdc26108cfbd9f7db8af03730bc66d13a/src/libstore/store-api.cc#L448-L452) and triggers the logic required for recursive Nix to work

**Comment by fricklerhandwerk** [comment]
All of these should be listed in the `system features` part and also mentioned in the respective experimental feature, and cross-linked.

**Comment by doronbehar** [comment]
It'd also be nice to document the format of `/etc/nix/machines` - Here on a non NixOS machine, I had to use `nixos-rebuild build && cat /etc/nix/machines` on a NixOS with `nix.buildMachines` NixOS module option to see what's it's format is like...

I also saw `?system-features=...` argument passed to `ssh://` URIs in `tests/` directory in this repo - another undocumented interface. Even though I read the examples there, it didn't work for me, but at least now I got it working thanks to `/etc/nix/machines`.

**Comment by doronbehar** [comment]
Also related:

https://github.com/NixOS/nix/issues/4117

**Comment by doronbehar** [comment]
I made a big reformat to the Wiki page on distributed builds, if anyone is interested to review:

https://nixos.wiki/wiki/Distributed_build

**Comment by fricklerhandwerk** [comment]
It's too cumbersome to review Wiki changes, as one cannot even comment on them but only make more changes. I'd very much appreciate if you made PRs to nix.dev instead – more information on distributed builds would indeed be great, it's a very important feature. A good start would be moving the Nix manual page to nix.dev, see https://github.com/NixOS/nix/issues/7769 for details.

**Comment by doronbehar** [comment]
Having so many places for documentations is a mess... (also mentioned on https://github.com/NixOS/nixos-homepage/pull/1062 ). Were you thinking of some kind of tutorial to add there? I'm a bit reluctant towards duplicating documentation on nix.dev and on nix' manual...

**Comment by fricklerhandwerk** [comment]
> Were you thinking of some kind of tutorial to add there?

The Wiki page is something in between a guide and tutorial. So whatever you make of it, it should go to nix.dev. The docs team does not maintain the Wiki.

The [distributed builds](https://nixos.org/manual/nix/unstable/advanced-topics/distributed-builds.html) page should probably not exist. The `builders` setting links to it, but all the information should be right there on the settings documentation. Moving it and rewording it to look less like a novel would certainly help – I'd appreciate a PR with review time.
