### ISSUE TITLE
Ubuntu 14.04 package broken

### ISSUE THREAD

**Issue by aragnon** [NixOS/nix#744]
`nix-env -i irssi` results in some output showing that everything works followed by:

```
error: opening lock file ‘/nix/var/nix/nix/profiles/default.lock’: No such file or directory
```

Additionally it would be nice to have something like `grep -R default.lock .`   actually find something in the source code, because now I have no idea where this is coming from.

**Comment by mboes** [comment]
This is likely a permission issue: https://nixos.org/wiki/Error_Messages.

**Comment by edolstra** [comment]
Closing since we don't distribute deb packages anymore.
