### ISSUE TITLE
Install script misses bash as a dependency

### ISSUE THREAD

**Issue by phunehehe** [NixOS/nix#747]
http://nixos.org/nix/install checks for `bzcat`, `curl` and `tar`, but `bash` is not there and is required to run the script in the downloaded tarball.
I think the script also wants `sudo`, but that looks optional (one can create /nix beforehand), so it's not a problem.

**Comment by phunehehe** [comment]
Looks like the script in the tarball is here https://github.com/NixOS/nix/blob/master/scripts/install-nix-from-closure.sh
And the install script is here https://github.com/NixOS/nixos-homepage/blob/master/nix/install.in

**Comment by edolstra** [comment]
Fixed via https://github.com/NixOS/nixos-homepage/pull/68.

**Comment by phunehehe** [comment]
whee
