### ISSUE TITLE
Signed channels

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#748]
I realize that there was some discussion about this a while ago (I can't find the thread) and the main point was that for nixpkgs, signed channels are unlikely to be useful given that nobody can certify that all of nixpkgs is legitimate. I agree with that.

However, I'm thinking about private Nix deployments that have their own reviewed/signed channels containing a reviewed subset of nixpkgs and possibly separate channels representing internal codebases, which should be trivial to sign. In those cases, signed channels make sense, right?

Does that seem like a legitimate use case? Would it be possible to reuse the existing signing machinery for that?

**Comment by fkz** [comment]
:+1:

**Comment by edolstra** [comment]
Closing since channels are on the way out, but we'll need to address this issue for flakes (#2849).

**Comment by deliciouslytyped** [comment]
Are they though?
