### ISSUE TITLE
Semantically meaningful ways to communicate our intent

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#749]
I realize we can use `builtins.trace` to implement warnings, but that doesn't tell Nix that we want them to be warnings. We can also use a wrapper function around `assert`/`throw` to emit a custom error message when an assertion fails, but Nix still won't know that we're attaching the message to the failed assertion.

This means that if Nix ever evolved a slightly more user-friendly front-end, it would be hard for us to collect all "warnings" during evaluation (i.e., deprecated aliases, other potential gotchas) and print them out in an orderly fashion (e.g., in Hydra), and all the assorted uses of `assert`/`throw`.

I'm thinking it would be nice to add a couple of simple (for now) builtins that provide semantically meaningful feedback of that sort. Something like `builtins.warn`, which would behave like trace at first, but could eventually be made to collect warnings (and potentially allow us to suppress certain types of them) in a structured fashion. `builtins.expect`/`builtins.assume` might allow us to give slightly more color (along with string messages) to assertions we make, while also giving us potential structure going forward.

cc @garbas, eternal advocate for user-friendliness, and @edolstra for obvious reasons

**Comment by copumpkin** [comment]
Doubly cool might be if  `builtins.warn` and friends accepted an attrset and `toJSON`'d it before running, pulling out some sort of canonical human-readable string from it by default. This would allow us to come up with structured messages (deprecations might have a field telling you what to use instead, etc.)

**Comment by vcunat** [comment]
> Something like builtins.warn, which would behave like trace at first, but could eventually be made to collect warnings

That sounds like it should be implement(ed/able) purely in nixpkgs in the start (`lib.warn`).

A quick thought: IMO great flexibility could be easily provided if we allowed `throw`-ing any type and allowed catching as well. Then we could use attrmaps to encode any kinds of errors/warnings and also handle them within nix-written code...

**Comment by copumpkin** [comment]
#1000

**Comment by Profpatsch** [comment]
I think it’s a very important feature to have.
https://github.com/NixOS/nixpkgs/pull/19315 also depends on it.

**Comment by nmattia** [comment]
Hi, I would find this very useful. Is there a plan, and is there anything we can do to help?

**Comment by garbas** [comment]
@nmattia As far as I'm aware there is no plan. You can use helpers in `nixpkgs`: `lib.warn` and `lib.info`

**Comment by Profpatsch** [comment]
I’d still like to see this. Using `trace` for warnings is not possible due to how hydra works.

**Comment by Infinisil** [comment]
This is related to #4914

**Comment by roberth** [comment]
`builtins.warn` is due to be released as part of Nix 2.24 this week.
(And perhaps vaguely related, we are also improving `assert v1 == v2` reporting: https://github.com/NixOS/nix/pull/11043)

The other builtins don't have names that are as explicit, but I'd say
- `builtins.trace` maps to "info"
- `builtins.traceVerbose` maps to "debug"

This seems fairly feature complete as for the printing verbosity levels.

> `builtins.expect`/`builtins.assume` might allow

Are these supposed to mimic `assert`? I don't think I understand the added value or the end goal. Could they be implemented with the `builtins` primitives?

Perhaps this could best be rephrased as a new issue? This thread doesn't seem all that related to these operations anyway; best to focus on one thing.
