### ISSUE TITLE
`nix why-depends --derivation` gives false negatives on Nix 2.12

### ISSUE THREAD

**Issue by raphaelr** [NixOS/nix#7496]
**Describe the bug**

The `why-depends` command on Nix 2.12 claims that two derivations do not depend on each other, when in reality they do (and  Nix 2.11 shows the dependency correctly).

**Steps To Reproduce**

In a nixpkgs checkout:
```
$ git checkout nixos-unstable
Already on 'nixos-unstable'

$ git rev-parse HEAD
04f574a1c0fde90b51bf68198e2297ca4e7cccf4

$ nix run -f . nixVersions.nix_2_11 -- why-depends --derivation -f . hello stdenv
/nix/store/7vf0d0j7majv1ch1xymdylyql80cn5fp-hello-2.12.1.drv
└───/nix/store/ap9g09fxbicj836zm88d56dn3ff4clxl-stdenv-linux.drv

$ nix run -f . nixVersions.nix_2_12 -- why-depends --derivation -f . hello stdenv
'hello' does not depend on 'stdenv'
```

Runtime dependencies are correctly detected. For example, `why-depends -f hello glibc.out` gives the correct result in both Nix versions.

**Expected behavior**

`why-depends --derivation` should correctly determine if and how two derivations depend on each other.

**`nix-env --version` output**

nix-env (Nix) 2.12.0

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by cole-h** [comment]
I bisected this to https://github.com/NixOS/nix/pull/7337 (b13fd4c58e81b2b2b0d72caa5ce80de861622610) -- cc @Radvendii @thufschmitt 

```
b13fd4c58e81b2b2b0d72caa5ce80de861622610 is the first bad commit
commit b13fd4c58e81b2b2b0d72caa5ce80de861622610
Author: Taeer Bar-Yam <taeer.bar-yam@tweag.io>
Date:   Wed Nov 23 11:39:50 2022 -0500

    Fix why-depends for CA derivations

    why-depends assumed that we knew the output path of the second argument.
    For CA derivations, we might not know until it's built. One way to solve
    this would be to build the second installable to get the output path.

    In this case we don't need to, though. If the first installable (A)
    depends on the second (B), then getting the store path of A will
    necessitate having the store path B. The contrapositive is, if the store
    path of B is not known (i.e. it's a CA derivation which hasn't been
    built), then A does not depend on B.

 src/nix/why-depends.cc | 28 ++++++++++++++++++++++------
 1 file changed, 22 insertions(+), 6 deletions(-)
```

**Comment by thufschmitt** [comment]
Ooops, this is our fault indeed.

Fix incoming
