### ISSUE TITLE
unable to check ‘https://nixos.org/channels/nixpkgs-unstable’ on OS X 10.11.2 

### ISSUE THREAD

**Issue by Treeant34** [NixOS/nix#750]
Tried installing Nix twice on a Vanilla OS X 10.11.2 (VMWare Fusion 8) using the shell command (curl https://nixos.org/nix/install | sh) and keep getting the same error (unable to check ‘https://nixos.org/channels/nixpkgs-unstable’).

I'm a total Nix Newb not sure how to install this.

I have not installed XCode as the page here (https://nixos.org/wiki/Nix_on_OS_X) seems to indicate it is no longer required in the compatibility table).

Any help would be appreciated...

Last login: Sun Dec 27 16:58:51 on console
Eds-Mac:~ forqmang$ curl https://nixos.org/nix/install | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1404  100  1404    0     0   1614      0 --:--:-- --:--:-- --:--:--  1613
unpacking Nix binary tarball for x86_64-darwin from `https://nixos.org/releases/nix/nix-1.10/nix-1.10-x86_64-darwin.tar.bz2'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 27.4M  100 27.4M    0     0  1077k      0  0:00:26  0:00:26 --:--:-- 1238k
performing a single-user installation of Nix...
directory /nix does not exist; creating it by running ‘?? using sudo

WARNING: Improper use of the sudo command could lead to data loss
or the deletion of important system files. Please double-check your
typing when using sudo. Type "man sudo" for more information.

To proceed, enter your password, or type Ctrl-C to abort.

Password:
copying Nix to /nix/store........................
initialising Nix database...
creating /Users/forqmang/.nix-profile
installing ‘nix-1.10’
building path(s) ‘/nix/store/bfhj0nrjnfwhph4fxzz12zlsanj5bvrm-user-environment’
created 7 symlinks in user environment
installing ‘cacert-20140715’
building path(s) ‘/nix/store/dv9in93k3xgyyj8wcrg6nzhnf3f4qqyf-user-environment’
created 9 symlinks in user environment
/nix/store/1rn8whr57nnkcfaqf3v0d741prfcd8ky-nix-1.10/bin/nix-channel: unable to check ‘https://nixos.org/channels/nixpkgs-unstable’
Eds-Mac:~ forqmang$

**Comment by domenkozar** [comment]
Duplicates https://github.com/NixOS/nix/issues/728
