### ISSUE TITLE
flake.nix uses outdated 22.05 nixos release for tests

### ISSUE THREAD

**Issue by trofi** [NixOS/nix#7506]
This causes a few issues:
1. It masks the fact that submodule tests fail to run on modern git
2. It brings binutils/gold failures in CI that were fixed in binutils upstream. Example ICE in `ld.gold`: https://github.com/NixOS/nix/actions/runs/3691026206/jobs/6248648814

I think it comes from:

```
$ fgrep 22.05 flake.nix
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-22.05-small";
```

I did not manage to bump it to `22.11` as git submodule tests look non-trivial. Fun fact: in `nixpkgs` git tests are skipped as `git` is not added to `nativeBuildInputs`.

I can propose a PR with disable submodule tests. WDYT?

**Comment by cole-h** [comment]
Is this still an issue now that https://github.com/NixOS/nix/pull/7367 has merged?

**Comment by trofi** [comment]
Ah, nice! Looks good enough. There are a few minor warnings in use of outdated options but they can be handled separately:

```
$ nix flake check
trace: warning: The option `nix.useSandbox' defined in `makeTest parameters' has been renamed to `nix.settings.sandbox'.
trace: warning: The option `nix.useSandbox' defined in `makeTest parameters' has been renamed to `nix.settings.sandbox'.
...
```

Thank you!

**Comment by trofi** [comment]
Sent https://github.com/NixOS/nix/pull/7507 to follow up.
