### ISSUE TITLE
Unmatched closing braces cause 'start-condition stack underflow'

### ISSUE THREAD

**Issue by dezgeg** [NixOS/nix#751]
Simply `nix-instantiate --eval -E '}'` results in:
````
start-condition stack underflow
````

This comes from the generated `flex` lexer.

**Comment by copumpkin** [comment]
@fkz @dezgeg this was reverted because it broke the release on python-packages.nix :frowning:

**Comment by fkz** [comment]
oh :frowning: I'll look into it!

**Comment by fkz** [comment]
hm, trying to reproduce this locally, in which commit of nixpkgs does this fail?

**Comment by fkz** [comment]
ok, could reproduce this locally now. Should really have better tested it.
