### ISSUE TITLE
`nix-store --add-fixed` on a large path runs OOM

### ISSUE THREAD

**Issue by Atemu** [NixOS/nix#7519]
**Describe the bug**

I'm using `nix-prefetch-git` to fetch a very large repository (checkout size > RAM) which internally uses `nix-store --add-fixed --recursive "$hashType" "$tmpFile"`. However, near the end, it errors out with `error: out of memory`.

However, the system has 16GB of swap and none of it is used. In fact, the daemon errors out itself without anything getting killed by the kernel.

**Steps To Reproduce**

1. Have a large directory
2. Dump with `nix-store --add-fixed --recursive`
3. Run "OOM"

**Expected behavior**

`nix-store --add-fixed` should use all the memory available, including swap.

Ideally though, it shouldn't even need that much memory to begin with. We need to copy the entire path to the nix store anyways, so it should just copy over the files to a tempdir, make it "immutable", recursively hash it in constant memory and add it.

**`nix-env --version` output**

```
nix-env (Nix) 2.11.1
```

**Additional context**

https://github.com/NixOS/nix/issues/2019

https://github.com/NixOS/nix/issues/1117

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by tpwrules** [comment]
I was sort of under the impression this was fixed recently? Is your daemon out of date? Did it not get fixed for this case?

**Comment by Atemu** [comment]
My nix-daemon is `/nix/store/gzd5wpvq9b5q5l3hvwpihgrhcrrllgi0-nix-2.11.1/bin/nix` which is the current stable version of Nix in 22.11.

**Comment by tpwrules** [comment]
Here is what I was thinking of: https://github.com/NixOS/nix/pull/6925

I guess this only fixes the problem for fixed-output derivations.

Does it every print "warning: dumping very large path"?

**Comment by Atemu** [comment]
Yes. As mentioned, the path is > RAM.

```
Updating files: 100% (25981/25981), done.
Switched to a new branch 'fetchgit'
removing `.git'...
warning: unknown setting 'experimental-features'
warning: dumping very large path (> 256 MiB); this may run out of memory
error: out of memory
```

cc @pennae

**Comment by tpwrules** [comment]
Who is saying `warning: unknown setting 'experimental-features'`? IIRC that is only from Nix 2.3 and before.

Does `nix-prefetch-git` somehow involve an older Nix without the bug fixed?

**Comment by Atemu** [comment]
That's odd. `nix-prefetch-git` executes `nix-store` at this step:

```
$ nix-store --version
nix-store (Nix) 2.11.1
```

However, stopping the `nix-store` task and looking at its exe in /proc reveals that it's actually running `/nix/store/68a4al6chfnzcqwnyndavwx4aylxi0lm-nix-2.3.16/bin/nix`.
I've got my system set up such that `nix` is nix2 and nix3 is `nixFlakes`. However, all the `nix-` commands point at `nixFlakes` rather than `nix`, so `nix` shouldn't ever get executed by anything here. I'm confused.

Why would `nix-store` be `nix`?

***

30min pass

***

I was in a nix-shell with nixpkgs = nixos-21.11. The nix-prefetch-git prepended that Nixpkgs' stable Nix which was nix_2_3.

**Comment by tpwrules** [comment]
Can you please confirm that this actually works properly with a modern Nix? I want to be sure this problem is gone.

**Comment by Atemu** [comment]
After a bit of fiddling to get the project to work with newer Nixpkgs, I can confirm that the newer Nix adds the path in constant memory. Hooray! Doesn't even print the warning.
