### ISSUE TITLE
`nix copy` support to exclude paths which are already in `cache.nixos.org`

### ISSUE THREAD

**Issue by mlyxshi** [NixOS/nix#7527]
**Is your feature request related to a problem? Please describe.**

Currently, `nix copy` will copy whole closure. For many users who self-host cache server, it is unnecessary to upload paths that have been cached in `cache.nixos.org` to a self-host server. This default behavior wastes time and storage, especially when `nix copy` a `nixosConfiguration` to self-host cache server.

**Describe the solution you'd like**

I use `traefik` to reverse proxy `minio` server. Therefore, I make a router rule which will forward `GET http://MYHOST/BUCKET/HASH.narinfo` to a proxy server as a workaround. This proxy will  GET http://cache.nixos.org/HASH.narinfo first. If status code is 200(already in official cache), it just pipes `cache.nixos.org` response to client so that `nix copy` will not upload this path.  If status code is 404, it pipes `MYHOST` response to client.

Test Result
1. `nix copy` whole closure
Full log: https://github.com/mlyxshi/flake/actions/runs/3798651110/jobs/6460501893
Time: 16min 58s
Storage: 383.5MiB
<img width="1374" alt="image" src="https://user-images.githubusercontent.com/16594754/209912211-0ed6fda1-9c8e-4676-9942-ae049b250bdc.png">
<img width="1502" alt="image" src="https://user-images.githubusercontent.com/16594754/209912363-64450dc1-0303-46ee-b414-bfb792d96280.png">

2. `nix copy`  exclude paths which are already in `cache.nixos.org`
Full log: https://github.com/mlyxshi/flake/actions/runs/3798783525/jobs/6460750038
Time: 27s
Storage: 23.6MiB
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/16594754/209913325-fac462d1-d710-44f0-a872-1e618afe48b2.png">
<img width="1524" alt="image" src="https://user-images.githubusercontent.com/16594754/209913653-9e2ac88c-d5cf-46ee-bd88-eb5723ece952.png">

All in all, `nix copy` add a flag that supports to exclude paths already in `cache.nixos.org` will benefit a lot for self-hosted users. Although, I have found a workaround, It would be more convenient to have official support and the implementation is not complex

**Describe alternatives you've considered**

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by SuperSandro2000** [comment]
Essentially you are asking to substitute paths from cache.nixos.org instead of copying them?
Because currently it is not possible by design to have missing dependencies of a store entry and would be considered inconsistent and broken.

**Comment by mlyxshi** [comment]
> Essentially you are asking to substitute paths from cache.nixos.org instead of copying them

`nix copy`  support   `--substitute-on-destination` on `SSH stores`.  Actually, it's not related to this feature request. More specific, the feature request is related to HTTP cache server and s3 cache server.  The logic is that at the beginning of `nix copy`, nix will calculate which paths need to be uploaded base on the result of `GET http://CACHEHOST/HASH.narinfo`.  I think user experience can be improved by also considering the result of  `GET http://cache.nixos.org/HASH.narinfo`. In real-life scenario, every machine has substituter `cache.nixos.org`. Therefore, I think it is unnecessary to upload the path which are already in `cache.nixos.org`

>have missing dependencies of a store entry and would be considered inconsistent and broken.
I have tested that     
```
nix-env --store /mnt -p /mnt/nix/var/nix/profiles/system --set $closure \
--extra-trusted-public-keys "cache.mlyxshi.com:qbWevQEhY/rV6wa21Jaivh+Lw2AArTFwCB2J6ll4xOI=" \
--extra-substituters "https://cache.mlyxshi.com" 
```
can install and boot the entire system with no errors

**Comment by mlyxshi** [comment]
implemented https://github.com/zhaofengli/attic

**Comment by arianvp** [comment]
I'd love this to be implemented in Nix natively...

**Comment by donn** [comment]
I don't think attic is a valid substitute for this feature given that it requires a server, whereas caches can be as simple as an S3 bucket with CloudFront in front of them…

**Comment by xokdvium** [comment]
A sane solution (that doesn't require nuking the closure property) is to have something like:

```
s3://my-cache?endpoint=blahblah&upstream-cache=https://cache.nixos.org
```

Basically an overlay substituter, where paths are first looked up in the upper overlay and afterwards in the lower one.

**Comment by donn** [comment]
Would be cool. If you're proposing to tackle this, multiple upstream cache support from the beginning would be cool, something like `s3://my-cache?endpoint=blahblah&upstream-caches[]=https://cache.nixos.org`

**Comment by xokdvium** [comment]
> multiple upstream cache support from the beginning would be cool

Not sure this needs explicit support, since one could then just chain multiple instances together? Might be somewhat annoying due to pct encoding, but oh well. Not sure it's that common of a use-case to warrant the syntactic sugar.

**Comment by donn** [comment]
Fair, you're likely more familiar with the challenges of implementing this so if it's too difficult there's no need.

**Comment by xokdvium** [comment]
We do already have a local-overlay-store as a working example of a similar pattern.

The only challenge I can think of is correctly separating the narinfo disk cache entries for separate overlaid binary caches. It would require some untangling, but should otherwise be smooth sailing.

As noted by @arianvp, it would be nice to have this support built into the nix clients to avoid standing up your own passthru infra unnecessarily.

I nice benefit I can think of in this approach is that `nix copy --to` would just work, since paths in an upstream cache would already be considered valid and would be skipped during the upload.

**Comment by donn** [comment]
I can recall I used multiple upstream caches [in my hacky script](https://github.com/fossi-foundation/nix-eda/blob/ebee72ea782641c04291dfa4cdcb560d22047bab/.github/actions/nix_sign_cache_s3/nix_copy_s3.py) to check the target cache itself to save time on `nix copy` if the narinfo already exists, but not needing to copy the full closure is going to save a lot of time anyway
