### ISSUE TITLE
Nix downloads hang occasionally on Mac OS

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#755]
At first I thought it was some weirdness with cloudfront, but I've seen it happen repeatedly on my brand new Mac VM that I use for testing things so I figured I'd flag it here.

The general symptom is that I'll see my nar downloads going by smoothly (or whatever the initial download is from the Nix installer) and then one of them still suddenly hang at a random percentage, with the speed dropping to 0. It never seems to get unstuck.

When I take the exact URL it's hitting and `curl` it manually, the download has never stalled. For example, I could try and have nix redownload the same nar file over and over again (ctrl-c when it hangs, try again, it hangs again on same nar), `curl` the nar file three times successfully in another shell on the same machine, and still get the download to hang when Nix does it.

My sense is that there's something odd about the pipe chain that Nix `curl`s the file into, possibly with its `nix-store` incantation at the end of it, and that's stalling the pipeline (that's a thing, right?) and blocking the download.

**Comment by copumpkin** [comment]
It's also pretty consistent. I'm basically stuck on an `llvm-3.7` nar in my VM right now. If someone can give me the exact pipe invocation, I can try looking deeper. I think it's `curl | xz | nix-store` but I don't know what parameters are being passed to `nix-store`.

**Comment by copumpkin** [comment]
So given the above, the following invocation hangs pretty consistently for me on Mac OS:

```
curl --fail --location https://cache.nixos.org/nar/1wdmz6nclcp44h48909bqxwivyrq4ls26klp9wgbv3bpvy11xi23.nar.xz | /nix/store/w0d2s2brwh992m9ild8ha6awpgfprd5c-xz-5.2.2/bin/xz -d | nix-store --restore /nix/store/jkca4zpg432maas8vr9ags8g042vm03d-llvm-3.7.0
```

**Comment by copumpkin** [comment]
Furthermore, this hangs too, with no disk or nix-store involved at all:

```
curl --fail --location https://cache.nixos.org/nar/1wdmz6nclcp44h48909bqxwivyrq4ls26klp9wgbv3bpvy11xi23.nar.xz | /nix/store/w0d2s2brwh992m9ild8ha6awpgfprd5c-xz-5.2.2/bin/xz -d > /dev/null
```

:weary:

**Comment by copumpkin** [comment]
I've also tried tinkering with MTU and window scaling to no avail. It seems to be something to do with the fact that I'm piping `curl` into `xz` that causes the problem.

**Comment by vcunat** [comment]
Your command works fine for me on NixOS. I tried several times (with relative `xz` invocation instead of your path, of course).
```
$ curl --version
curl 7.45.0 (x86_64-pc-linux-gnu) libcurl/7.45.0 OpenSSL/1.0.1p zlib/1.2.8 libssh2/1.6.0
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 
$ xz --version
xz (XZ Utils) 5.2.2
liblzma 5.2.2
```

**Comment by copumpkin** [comment]
Yeah, it works for me on other systems too, but on this one system it hangs consistently.

**Comment by vcunat** [comment]
You do use curl from nixpkgs, right? (on a similar version)

**Comment by copumpkin** [comment]
In the test above, I wasn't, but it happens with the `nixpkgs` curl too (that's what triggered me to look into this, because my .nar fetching code was hanging)

**Comment by copumpkin** [comment]
I turned off VMWare's NAT and switched it to bridged networking and the issue seemed to go away. It still seems like it shouldn't be possible for the NAT to hang a userspace program like that, but I doubt it's really Nix's fault in any real way.
