### ISSUE TITLE
`NIX_CONFIG` variable ignores -extra options

### ISSUE THREAD

**Issue by nrdxp** [NixOS/nix#7560]
**Describe the bug**

The `NIX_CONFIG` environmental variable can be used to set valid nix.conf values directly in the environment, which is awesome, but the values preprended with `extra-` don't work as they do in regular config files.

**Steps To Reproduce**

run `NIX_CONFIG='extra-substituters = https://example.com' nix show-config`

**Expected behavior**

It should work as it does elsewhere.

**`nix-env --version` output**

nix (Nix) 2.12.1

**Comment by dermetfan** [comment]
Works for me on `2.11.1`:

```
❯ NIX_CONFIG='extra-substituters = https://example.com' nix show-config --json | jq -r .substituters.value[]
https://cache.nixos.org/
https://example.com
```

**Comment by nrdxp** [comment]
that's strange because I explicitly tried 2.11.1 to make sure it wasn't a regression :thinking: 

I'll have to try again

**Comment by ryan4yin** [comment]
Seems related to https://github.com/NixOS/nix/issues/9487
