### ISSUE TITLE
Separate setting for substitution parallelism

### ISSUE THREAD

**Issue by urbas** [NixOS/nix#7563]
**Is your feature request related to a problem? Please describe.**

Right now the parallelism factor of substitution (i.e. the number of parallel package downloads from a binary cache) seems to be controlled by [the `max-jobs` setting](https://nixos.org/manual/nix/unstable/command-ref/conf-file.html#conf-max-jobs).

Most of the time this is okay. However, there is an important use case to set  `max-jobs` to `0` in order to prevent the local host from doing any builds (remote hosts will do the builds instead). Unfortunately, as a consequence of `max-jobs = 0` substitutions are done in a single thread. This significantly slows down downloads of packages from binary caches (from S3, for example).

**Describe the solution you'd like**

I would like to propose a separate setting for the number of maximum parallel substitutions.

**Describe alternatives you've considered**

Unfortunately, I could not find an alternative.

**Comment by bjornfor** [comment]
Duplicate of https://github.com/NixOS/nix/issues/3379?

**Comment by urbas** [comment]
Oh my, I missed that. Thanks for the find!
