### ISSUE TITLE
`fileTransferSettings.httpConnections` doesn't make a difference in performance

### ISSUE THREAD

**Issue by nrdxp** [NixOS/nix#7575]
**Describe the bug**

I assume that the reason for using a thread-pool set to the number of http connections is to increase the performance of cache querying in general, however, after some benchmarks while working on #7526, I realized that the performance is identical no matter how many threads are configured.

In other words, we might as well use a straight loop here:
https://github.com/NixOS/nix/blob/1c98daf6e8bdf771ed3b17c947384fef4ed8d006/src/libstore/misc.cc#L105

An initial `strace` reveals there are some locks that are preventing the queries from actually taking place in parallel, so a better solution perhaps would be to do as the comment says and make this async.

**Steps To Reproduce**

1. Build a derivation you do not have locally
2. set `NIX_CONFIG=binary-caches-parallel-connection=$n` for various values of `n`.
3. Do some basic benchmarks of how long the queries actually take with `time`
4. delete the substituted path from the store and run the build again with `narinfo-cache-(negative|positive)-ttl set to 0 so that the queries will be reran
5. No matter what value you select for `n` the time will end up being about the same

If you want to streamline the benchmarks you can use my branch from #7526 to simply query caches without performing any substitutes.

**Expected behavior**

Using a thread pool adds complexity, the payoff is supposed to be increased speed, but that is just not the case from what I have gathered so far. As of now we are paying the cost of the extra complexity for apparently no reason.

**`nix-env --version` output**

`nix (Nix) 2.12.1`

**Additional context**
#7526 would benefit greatly from being able to _actually_ query in parallel, or perhaps async would suffice

**Comment by Kha** [comment]
Why would you expect querying a single derivation to benefit from parallel queries? The use case is querying many derivation in parallel as documented in #5118.

**Comment by Kha** [comment]
> When did I say this was concerning only a single derivation?

Seemed to be implied to me here:

> delete the substituted path from the store

At the very least you're not making it easy to reproduce your result. I don't have a trivially reproducible setup either, but here are 1865 derivations queried at two binary caches on my machine:
```
$ time nix build --dry-run --option binary-caches-parallel-connections 1000 --narinfo-cache-negative-ttl 0 >& /dev/null
nix build --dry-run --option binary-caches-parallel-connections 1000  0 >&  2,44s user 0,84s system 79% cpu 4,108 total
$ time nix build --dry-run --option binary-caches-parallel-connections 10 --narinfo-cache-negative-ttl 0 >& /dev/null
nix build --dry-run --option binary-caches-parallel-connections 10  0 >&  4,54s user 2,34s system 10% cpu 1:03,07 total
```

**Comment by nrdxp** [comment]
There isn't an easy way to reproduce with the default commands unfortunately, which is why I just modified the code for my tests. Probably also why nobody has discovered this yet.

**Comment by Kha** [comment]
I just posted the log of a real-life 15x speedup (and I was too impatient to wait for `httpConnections=1`), so I think the issue is in your code or use case.

**Comment by nrdxp** [comment]
Could be, my PR used `Store::queryMissing` initially, but I changed that in favour of reimplenting the logic to avoid considering the local store. I believe I benchmarked both implementations but perhaps I am misremembering and it was just my codepath after all. I'll confirm it later tonight hopefully.

**Comment by nrdxp** [comment]
Your speedup could be because it is querying less paths though, since some may already exist locally after the first build.

**Comment by nrdxp** [comment]
I must be misremembering then, I'll take your work and close this for now until I have time to check later.

**Comment by nrdxp** [comment]
Looks like you were right and it was only my implementation. Not sure where I went wrong but it doesn't matter, I ended up getting much better performance with `Store:querySubstitutablePaths`:
https://github.com/NixOS/nix/pull/7526#issuecomment-1379475640
