### ISSUE TITLE
Implement floats

### ISSUE THREAD

**Issue by ctheune** [NixOS/nix#760]
I started implementing them in https://github.com/ctheune/nix/tree/ctheune-floats
but I'd like to keep track of what needs to be done:
- [X] have someone more experienced review my patch
- [x] test coverage (floats themselves, xml, json, type compatibility with integers)
- [x] documentation
- [ ] review lexer regexp for edge cases or simplification
- [x] syntax edge case for "123.bar" which behaved differently previously and fails with a stupid error at the moment

**Comment by edolstra** [comment]
Could you make a pull request? That will make it easier to review.

**Comment by zimbatm** [comment]
Issue can be closed, floats are now implemented
