### ISSUE TITLE
I can't merge a critical backport

### ISSUE THREAD

**Issue by roberth** [NixOS/nix#7623]
**Describe the bug**

I can't merge a critical backport because CI doesn't run.
I have push permission, but I am not an admin.

This happened while attempting to fix the release. 
I was not able to trigger the Hydra job because of this, delaying the hotfix.

The backport:
 -  #7622

**Steps To Reproduce**

1. Make a backport using the label
2. There's nothing I can click. PR state from my viewpoint is:
![Screenshot_2023-01-18_02-42-57](https://user-images.githubusercontent.com/496447/213060700-0562b1f3-efa7-4604-84a6-41bf14f3a96f.png)
3. My attempt to trigger the CI failed
```
$ git push
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 187 bytes | 187.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
remote: error: GH006: Protected branch update failed for refs/heads/backport-7621-to-2.13-maintenance.
remote: error: Changes must be made through a pull request. Required status check "installer_test" is expected.
To https://github.com/NixOS/nix.git
 ! [remote rejected]     backport-7621-to-2.13-maintenance -> backport-7621-to-2.13-maintenance (protected branch hook declined)
error: failed to push some refs to 'https://github.com/NixOS/nix.git'

```

**Expected behavior**

`install_test` triggers, runs, completes, and I can merge it.

**`nix-env --version` output**

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by roberth** [comment]
@domenkozar Do you have an idea why `installer_test` might not report a status?

**Comment by zowoq** [comment]
A github action can't start another action unless it uses the non-default token.

Closing and reopening the PR is the simplest workaround.

**Comment by abathur** [comment]
If all of the checks need to run clean, you may be able to goose it by getting cachix set up for the installer tests. I'll edit w/ a link momentarily.

**Comment by thufschmitt** [comment]
Yes, that's an issue with the backport bot (don't have a pointer handy, but it's a known issue, and not trivial to fix IIRC, something like what @zowoq mentions).

It's strange that the backport branch is protected though, I think I unstuck this a couple time by force-pushing to it :thinking:

**Comment by edolstra** [comment]
I've removed the requirement for the installer test to pass on maintenance branches.
