### ISSUE TITLE
Error: `Invalid outputs specifier` since 2.13.0

### ISSUE THREAD

**Issue by DavHau** [NixOS/nix#7624]
**Describe the bug**

Since version 2.13.0 underscores seem to not be allowed anymore in output specifiers. This breaks compatibility between nix versions.
[This commit](https://github.com/NixOS/nix/commit/ce2f91d356438297fd795bd3edb8f9f4536db7da) introduced the error message which I'm seeing [here](https://github.com/holochain/holonix/actions/runs/3944584583/jobs/6750650168#step:4:543)

**Comment by abathur** [comment]
2.13.0, yeah?

**Comment by roberth** [comment]
Fixes have been released in 2.13.1 and 2.13.2.
