### ISSUE TITLE
Property-based testing

### ISSUE THREAD

**Issue by Ericson2314** [NixOS/nix#7633]
To get the most value out of our unit tests, I think we need to be able to write some property based tests. #7624 is something that slipped through the cracks. @edolstra's fix pointed out the relationship with `checkName` --- an excellent point and one that I hadn't thought of when working on `OutputSpec` (and causing the bug). It would be great to have a property test explicitly relating the two.

I did some quick searching and https://github.com/emil-e/rapidcheck/blob/master/doc/gtest.md looks like something that works with googletest. I guess we can try that?

CC @roberth

**Comment by roberth** [comment]
Lowering the barrier to write good tests is always a good thing. That includes property tests.

**Comment by Ericson2314** [comment]
#7639 adds property a test.

**Comment by Ericson2314** [comment]
Since ecd3e4ebd777dca694d0c60431641f054ec2d1ce we have a few, so I'll close this as complete!
