### ISSUE TITLE
pre-commit, editorconfig, nixpkgs-fmt?

### ISSUE THREAD

**Issue by roberth** [NixOS/nix#7634]
**Is your feature request related to a problem? Please describe.**

Saw some unproductive comments about formatting today. Nothing too bad, but we could prevent this.

**Describe the solution you'd like**

- `nixpkgs-fmt`
- `pre-commit-hooks.nix` configuration that installs the hook in `shellHook`
- `.git-blame-ignore-revs` file, now also supported by GitHub web app

**Describe alternatives you've considered**

Carry on.

**Additional context**

I think we can just vote among the Nix Team and I'll be happy either way.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by edolstra** [comment]
See #6721 for C++ formatting.

**Comment by roberth** [comment]
We could start by excluding existing files from the C++ formatter, in order not to hinder existing PRs with unnecessary conflicts.
