### ISSUE TITLE
Release notes automation

### ISSUE THREAD

**Issue by roberth** [NixOS/nix#7665]
**Is your feature request related to a problem? Please describe.**

Goals
 - Automate more of the release process
 - Avoid merge conflicts in the release notes
 - Improve the release notes of patch releases

By automating more of the release process, we move towards a situation where a release can be triggered by any maintainer, freeing up Eelco's time to work on important things.

Release notes automation can merge multiple files into a single release notes file, thereby avoiding the ubiquitous conflicts that would otherwise disincentivize the writing of release notes in the PR that introduces the change. Arguably the PR should document itself, and the pull request template already asks for this.

Currently, we don't document what's in our patch releases, but this is quite relevant to users. I suppose doing this wasn't considered worthwhile, but it would help users quite a bit; especially those experiencing the bugs or doing the packaging in Nixpkgs.

**Describe the solution you'd like**

 - contributors add a new file to a specific directory in each pr
 - at release time,
     - for a patch release, the release script appends the files in that directory to the existing rl-${version} file
     - for a non-patch release, the release script creates a new file with all the items from those files
     - after the concatenation / write step, it removes the original files, as their contents have been processed. This is helpful because it makes the patch release automation work.

**Describe alternatives you've considered**

Keep burdening Eelco (minor releases) and users (patch releases) with the task of digging through commit logs.

We might want to do a final review of release notes, but moving this work forward as suggested above should be more productive anyway.

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by edolstra** [comment]
Right now the only effort on my part is to do some proofreading/editing of the release notes and re-ordering them in order of descending relevance. We can't really automate that. So this automation would be primarily useful in avoiding some PR merge conflicts.

**Comment by roberth** [comment]
Automated backports re-create the `rl-next.md` file, as I try to correct for in #8393.
If release note entries were in their own files, this wouldn't lead to conflicts, and it would be feasible to apply the same automation to point releases.

**Comment by roberth** [comment]
> Right now the only effort on my part is to do some proofreading/editing of the release notes

The proofreading would be best to do in the PRs themselves, although I do see value in a final review.
Relevance could be perhaps be indicated with levels like _critical, prominent, regular, minor_. That would produce a reasonable ordering. We could use the markdown yaml header for this.

It would be nice to use the same tooling that Nixpkgs does. Currently it has none, so hopefully something can be found, or written, or improved, to serve at least both projects.

**Comment by fricklerhandwerk** [comment]
Related: @alejandrosame is doing something very similar for the upcoming NixOS release and may have relevant opinions.

**Comment by roberth** [comment]
Concretely what I would write is something that takes its input in the form of files like:

`rl-next/fetchTree-stable.md`:
```markdown
---
relevance: high
---

`builtins.fetchTree` is now stable.

Experimental feature not required bla bla.
```

and then a script could round up everything in `rl-next`, sort it by relevance, put it in bullet points, write it to `rl-<version>.md` and delete the files.

We could think of more advanced features, such as categorization or something, or figuring out which issues were solved through the github api.
I would refrain from using commit messages, because those have a different audience.

Maybe move away from bullet points and have a title + paragraph(s)? Would help with glancing the changes.

**Comment by fricklerhandwerk** [comment]
> Maybe move away from bullet points and have a header + paragraph(s)? Would help with glancing the changes.

It would primarily reduce the transformation to sorted concatenation, and more simple is more good. :+1: 

> I would refrain from using commit messages, because those have a different audience.

We could in principle use commit messages, but only those of tags. Merge commit messages will be full of "fixed typo" sorts of things. But commit messages are not reviewable, therefore on these grounds alone let's not. :+1: 



> We could think of more advanced features, such as categorization or something, or figuring out which issues were solved through the github api.

Let's not overthink this. :-1:

**Comment by roberth** [comment]
`changelog-d` is mostly used by Cabal and does the things we need it for.
I'm proposing to add a more standard input format at @fgaz' codeberg repo: https://codeberg.org/fgaz/changelog-d/issues/3

**Comment by fgaz** [comment]
Oops, I forgot about this mention :sweat_smile: 

I'll reply to the upstream issue soon
