### ISSUE TITLE
nix-build: caret (`^`) doesn't work as advertised

### ISSUE THREAD

**Issue by nrdxp** [NixOS/nix#7682]
**Describe the bug**

In the description of the release notes for 2.13, it was said that you could now use the carrot (`^`) operator to specify which output to build on a drv the same way you can on a flake uri, however this does not seem to work in practice, at least on the latest point release 2.13.2.

**Steps To Reproduce**

1. Grab Nix from `2.13-maintenance`
2. Pick any derivation
3. Confirm it builds `nix-build /nix/store/*-foo.drv`
4. Now try again explicitly with the (`^`): `nix-build /nix/store/*-foo.drv^out`
5. It will give an error

**Expected behavior**

That it works as advertised.

**Comment by edolstra** [comment]
@Ericson2314 Might this be caused by the `OutputSpec` changes?

**Comment by Ericson2314** [comment]
@nrdxp's "steps to reproduce" uses `nix-build`, but this feature is only for the new CLI. Perhaps we just amend the commit message to make that more clear.

BTW @nrdxp you can do `nix-store -r /nix/store/*-foo.drv!out` which has worked for ages.

**Comment by nrdxp** [comment]
@Ericson2314, thanks I figured that out just a bit ago by searching the git log. The main source of confusion is the release thread on discourse which reads:
> Allow explicitly selecting outputs in a store derivation installable, just like we can do with other sorts of installables. For example,
>
> `# nix-build /nix/store/gzaflydcr6sb3567hap9q6srzx8ggdgg-glibc-2.33-78.drv^dev`

**Comment by Ericson2314** [comment]
Ah! My bad, Will fix the change log.
