### ISSUE TITLE
Nix 1.2 fails to build paths on nixos, sometimes

### ISSUE THREAD

**Issue by viric** [NixOS/nix#77]
It happened in this run: http://sprunge.us/edJH

It clearly reads the nix files from nixos and nixpkgs repositories, and yet fails to realise paths: "don't know how to build these paths"

After an hour, the list of paths not realisable got smaller. After some hours, it went on building.

It can be something with the binary channel and its caching.

**Comment by Ericson2314** [comment]
- @edolstra I think we don't need https://github.com/NixOS/nix/commit/299141ecbd08bae17013226dbeae71e842b4fdd7, it is optimizing a fairly obscure use-case. As long as it does some sort of fallback (e.g. more building), it is fine.

> After an hour, the list of paths not realisable got smaller. After some hours, it went on building.

Actually, this is fine.
