### ISSUE TITLE
Nix Installer cp error

### ISSUE THREAD

**Issue by DylanDoesProgramming664** [NixOS/nix#7724]
## Platform

- [x] Linux: Fedora 37
- [ ] macOS
- [ ] WSL

## Output

<details><summary>Output</summary>

```log

(cp: cannot create regular file '/nix/store/lsr79q5xqd9dv97wn87x12kzax8s8i1s-nix-2.13.2/bin/nix': Text file busy)

```

</details>

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by abathur** [comment]
Do you already have Nix installed? Maybe a daemon install? 

https://stackoverflow.com/questions/16764946/what-generates-the-text-file-busy-message-in-unix suggests this message is specific to trying to edit a running executable.

If so, it may help to follow the uninstall steps before trying to install again? https://nixos.org/manual/nix/stable/installation/installing-binary.html#linux
