### ISSUE TITLE
Bad file descriptor on installation with sudo

### ISSUE THREAD

**Issue by tacastillo** [NixOS/nix#7728]
## Platform

- [ ] Linux:
- [X] macOS Monterey 12.6.2 on a Rosetta terminal
- [ ] WSL

## Additional information

I may have painted myself in a corner here.

I was trying to install Nix on a new local machine via the `sh` command, forgot to `sudo` it, and control+C'd out of it at some point after putting in my password a handful of times. I tried running with `sudo` and I'm getting a:

```
sh: /dev/fd/11: Bad file descriptor
```

on all attempts with `sudo`. Restarted my laptop and no luck.

Does anyone have an off-the-cuff recommendation for fixing this, or am I SOL and have to type my password in X number of times for each of they 32 build users? 😅

Thank you!

## Output

<details><summary>Output</summary>

```log

sh: /dev/fd/11: Bad file descriptor

```

</details>

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by abathur** [comment]
You shouldn't need to sudo the outer invocation. 

Is your `timestamp_timeout` set to 0? (https://www.sudo.ws/docs/man/sudoers.man/)

Is your sudo is something other than sudo? (what does `type -a sudo` report?

**Comment by tacastillo** [comment]
Huh, I thought those default to 5 minutes, but you're right! Mine was set to 0.

After patching up that user error(courtesy of you!), I got it working. It's a new laptop, so I guess nix was the first thing that I've installed that needed multiple sudo commands. Fun!

Anyway! Closing this out. Thank you for your help!

**Comment by abathur** [comment]
I think the default is 5 minutes, but it's possible macOS has changed the default settings. What model did you get?

I'll ask on Matrix to see if anyone else with recent devices can weigh in.

**Comment by andrewhamon** [comment]
```
sudo cat /etc/sudoers | grep time || echo "not found"
not found
```

```
uname -a
Darwin andrewhamon-NNF39W2LMJ-mbp 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64 arm Darwin
```

Don't see any config about this in my sudoers.
