### ISSUE TITLE
UX issue: group all the flake updates together

### ISSUE THREAD

**Issue by zimbatm** [NixOS/nix#7741]
**Describe the bug**

A user learns about `nix flake update`. Then they want to update only a specific input and have to learn about a different command: `nix flake lock --update-input`.

**Expected behavior**

`nix flake update` to update the whole lockfile

`nix flake update --input nixpkgs` to just update the nixpkgs input of the flake.

**`nix-env --version` output**

```
nix-env (Nix) 2.12.0
```

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by cole-h** [comment]
I think this is related to (if not a duplicate of) https://github.com/NixOS/nix/issues/5110.

**Comment by zimbatm** [comment]
Thanks!
