### ISSUE TITLE
add travis hook/hydra test to pull requests

### ISSUE THREAD

**Issue by fkz** [NixOS/nix#775]
to make this really useful, we probably want something like #763 to get a nicer travis log also.

**Comment by vcunat** [comment]
IIRC @edolstra mentioned this during the NixCon sprint, but I don't know what's the status.

**Comment by edolstra** [comment]
Yeah, I haven't had time to work on it since the sprint so it's not finished yet.

**Comment by fkz** [comment]
I tried adding a travis hook a while ago, but wasn't succesful (see https://github.com/NixOS/nix/compare/master...fkz:travis). 
For some reason I still don't understand, in the tests the compiled nix version is called instead of the one just build although the PATH seems to be set correctly. (so since the release of 1.11.1 the tests even succeed :smile: ).

**Comment by fkz** [comment]
(if somebody wants to investigate: https://travis-ci.org/fkz/nix/builds/103449418. I added some debug output, so in line 2262 the path seems to be correct, but `type nix-build` in line 2301 outputs the wrong path `/home/travis/.nix-profile/bin/nix-build`

**Comment by domenkozar** [comment]
See https://github.com/NixOS/hydra/issues/95

**Comment by edolstra** [comment]
Closing for https://github.com/NixOS/rfcs/pull/56.
