### ISSUE TITLE
Unable to install multi-user nix as user on macOS 13.2

### ISSUE THREAD

**Issue by jonBoone** [NixOS/nix#7779]
## Platform

- [ ] Linux: 
- [X] macOS -- 13.2
- [ ] WSL

## Output

<details><summary>Output</summary>

```log

./nix-install.sh --yes 
downloading Nix 2.13.2 binary tarball for x86_64-darwin from 'https://releases.nixos.org/nix/nix-2.13.2/nix-2.13.2-x86_64-darwin.tar.xz' to '/var/folders/p0/wxvc6fn96cvbjtrhwqf8s37c0000gp/T/nix-binary-tarball-unpack.XXXXXXXXXX.w76llzzW'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23.8M  100 23.8M    0     0  20.2M      0  0:00:01  0:00:01 --:--:-- 20.3M
Switching to the Multi-user Installer
Welcome to the Multi-User Nix Installation

This installation tool will set up your computer with the Nix package
manager. This will happen in a few stages:

1. Make sure your computer doesn't already have Nix. If it does, I
   will show you instructions on how to clean up your old install.

2. Show you what I am going to install and where. Then I will ask
   if you are ready to continue.

3. Create the system users and groups that the Nix daemon uses to run
   builds.

4. Perform the basic installation of the Nix files daemon.

5. Configure your shell to import special Nix Profile files, so you
   can use Nix.

6. Start the Nix daemon.

Would you like to see a more detailed list of what I will do?
No TTY, assuming you would say yes :)

I will:

 - make sure your computer doesn't already have Nix files
   (if it does, I will tell you how to clean them up.)
 - create local users (see the list above for the users I'll make)
 - create a local group (nixbld)
 - install Nix in to /nix
 - create a configuration file in /etc/nix
 - set up the "default profile" by creating some Nix-related files in
   /var/root
 - back up /etc/bashrc to /etc/bashrc.backup-before-nix
 - update /etc/bashrc to include some Nix configuration
 - back up /etc/zshrc to /etc/zshrc.backup-before-nix
 - update /etc/zshrc to include some Nix configuration
 - back up /etc/bash.bashrc to /etc/bash.bashrc.backup-before-nix
 - update /etc/bash.bashrc to include some Nix configuration
 - create a Nix volume and a LaunchDaemon to mount it
 - create a LaunchDaemon (at /Library/LaunchDaemons/org.nixos.nix-daemon.plist) for nix-daemon

Ready to continue?
No TTY, assuming you would say yes :)

---- let's talk about sudo -----------------------------------------------------
This script is going to call sudo a lot. Normally, it would show you
exactly what commands it is running and why. However, the script is
run in a headless fashion, like this:

  $ curl -L https://nixos.org/nix/install | sh

or maybe in a CI pipeline. Because of that, I'm going to skip the
verbose output in the interest of brevity.

If you would like to
see the output, try like this:

  $ curl -L -o install-nix https://nixos.org/nix/install
  $ sh ./install-nix


~~> Fixing any leftover Nix volume state
Before I try to install, I'll check for any existing Nix volume config
and ask for your permission to remove it (so that the installer can
start fresh). I'll also ask for permission to fix any issues I spot.

~~> Checking for artifacts of previous installs
Before I try to install, I'll check for signs Nix already is or has
been installed on this system.

---- Nix config report ---------------------------------------------------------
        Temp Dir:       /var/folders/p0/wxvc6fn96cvbjtrhwqf8s37c0000gp/T/tmp.tdEwGJvd
        Nix Root:       /nix
     Build Users:       32
  Build Group ID:       30000
Build Group Name:       nixbld

build users:
    Username:   UID
     _nixbld1:  301
     _nixbld2:  302
     _nixbld3:  303
     _nixbld4:  304
     _nixbld5:  305
     _nixbld6:  306
     _nixbld7:  307
     _nixbld8:  308
     _nixbld9:  309
     _nixbld10: 310
     _nixbld11: 311
     _nixbld12: 312
     _nixbld13: 313
     _nixbld14: 314
     _nixbld15: 315
     _nixbld16: 316
     _nixbld17: 317
     _nixbld18: 318
     _nixbld19: 319
     _nixbld20: 320
     _nixbld21: 321
     _nixbld22: 322
     _nixbld23: 323
     _nixbld24: 324
     _nixbld25: 325
     _nixbld26: 326
     _nixbld27: 327
     _nixbld28: 328
     _nixbld29: 329
     _nixbld30: 330
     _nixbld31: 331
     _nixbld32: 332

Ready to continue?
No TTY, assuming you would say yes :)

---- Preparing a Nix volume ----------------------------------------------------
    Nix traditionally stores its data in the root directory /nix, but
    macOS now (starting in 10.15 Catalina) has a read-only root directory.
    To support Nix, I will create a volume and configure macOS to mount it
    at /nix.

~~> Configuring /etc/synthetic.conf to make a mount-point at /nix
Password:

---- oh no! --------------------------------------------------------------------
error: failed to configure synthetic.conf

We'd love to help if you need it.

You can open an issue at
https://github.com/NixOS/nix/issues/new?labels=installer&template=installer.md

Or get in touch with the community: https://nixos.org/community
```

/etc/synthetic.conf was successfully created:
```
> ls -la /etc/synthetic.conf 
-rw-------  1 root  wheel  4 Feb  7 15:58 /etc/synthetic.conf
```

and it contains the correct information:
```
> sudo cat /etc/synthetic.conf
nix
```

Is this a permissions problem?  The function `test_synthetic_conf_mountable()` is failing, as evidenced by the error message "error: failed to configure synthetic.conf" (create-darwin-volume.sh:663).  Reading the definition of `test_synthetic_conf_mountable` (create-darwin-volume.sh:220-222), I'm thinking the grep is running as UID=502 and the test fails because of the 600 permissions on /etc/synthetic.conf, which is owned by UID=0.  In this case, I'm also not a member of group `wheel`, so even if the permissions allowed group read access, the test would continue to fail.
</details>

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by jonBoone** [comment]
I'm not how to add another label, but I think the `macos` label should be added this.

**Comment by abathur** [comment]
Not at a computer atm, but I suspect the file may have already existed? Does it work if you rm it and reinstall?

**Comment by jonBoone** [comment]
No, it does not.

— jb

**Comment by abathur** [comment]
Well, you're probably right about it being a permission issue, but I do suspect there's something in your environment causing it.

Now that I'm home, here's mine:

```console
$ ls -la /etc/synthetic.conf 
-rw-r--r-- 1 root wheel 37 Oct 11  2020 /etc/synthetic.conf
```

And here are reports from 2 others on Matrix:
User 1:
> ```
> $  ls -al /etc/synthetic.conf
> -rw-r--r-- 1 root wheel 24 May 29  2022 /etc/synthetic.conf
> ```

User 2:
> Just to provide another data point, am on 13.2.
> 
> ```
> $ ls -al /etc/synthetic.conf
> .rw-r--r-- 24 root 12 Sep  2021 /etc/synthetic.conf
> ```
> 

IIRC, the default permissions here come down to the `umask 0022` that the installer script sets, and this hasn't been touched since September 2020:
https://github.com/NixOS/nix/blob/ec788964e91e0bf17eae5aac6b5dc0ab79c18c11/scripts/install-nix-from-closure.sh#L5

Since you say you've tried removing synthetic.conf, my next guess is to see if /etc/sudoers is setting a more restrictive umask?

**Comment by abathur** [comment]
User 2 mentioned above has also since confirmed that they get `-rw-r--r--` when installing fresh in a 13.2 VM:

**Comment by jonBoone** [comment]
When I execute `sudo umask -S && umask`, I get back:
```
u=rwx,g=,o=
077
```
which is to what `/etc/synthetic.conf` permissions result.

I confirmed that nothing in /etc/sudo* references the `umask` command:
```
> sudo grep -Ri umask /etc/sudo* 
>
```

It does seem that `umask 0022` is set in both `install-nix-from-closure.sh` and `install.in`, though I'm not sure which is used when I run the install script.

My initial problem installing occurred when invoking the installer like this:
```
sh <(curl -L https://nixos.org/nix/install)
```

In order to make debugging the issue easier, I downloaded the script and invoked it from the local copy:
```
curl -L https://nixos.org/nix/install -o install.sh
mv install.sh nix-install.sh
chmod +x nix-install.sh
sudo ./nix-install.sh
```

Both scenarios fail at the same point, which is testing to see if `/etc/synthetic.conf` has been successfully modified.

Based on your previous responses, it appears that the proper mask (0022) isn't being set in my case....

**Comment by abathur** [comment]
Drat. At least we're on the right track. Is that umask set in any of your shell init scripts (for both bash and your user shell, if you aren't using bash)?

We're out beyond what I know about umask (and I don't have much time to play these this morning), so I'll braindump a few paranoid thoughts that come to mind without a good sense of what's actually plausible here.

1. The outer argument-parsing script (install-nix-from-closure) sets the `umask 0022` and then for a multi-user install will `exec` the multi-user script (which has a bash shebang). I assume the umask should follow along through the exec, but I guess it's possible that it doesn't? (And perhaps it can revert to the umask set when bash gets invoked?)
2. The shebang of the exec'd multi-user install script is `#!/usr/bin/env bash`, so I guess it's possible there's a bash on your path that is actually a wrapper script that sets a umask before invoking some other bash? I guess if there's a wrapper it could also be affecting things if it invokes bash in some way that would cause it to read your profile/rc files.
3. It looks like macOS has a way to use launchctl to set a umask for apps (https://support.apple.com/en-us/HT201684). I have no clue if that would apply in this case, but I guess it could be interfering if set?
4. If this is an org device, I guess it's possible that there's some device profile enforcing a different umask?

**Comment by jonBoone** [comment]
I understand now what is happening.  I have a modular shell dotfile setup that leverages certain common environment settings, one of which is to set the umask to 0077.  This is invoked with every shell invocation of /bin/sh, /bin/bash or /bin/zsh.  Due to the assertive nature of the line in question `umask 0077`, this will override any already set umask setting.  I will make this conditional on being invoked as a login-shell session, which I anticipate will correct the problem.  After I update the configuration, I'll update this issue.

**Comment by jonBoone** [comment]
While I typically restrict my shell usage on macOS to `/bin/zsh`, I recognize that many others (like nix) still use `/bin/bash`.  To make matters more complicated, it's unclear whether `/bin/bash` or `/bin/dash` is invoked to implement the POSIX shell support intended when using `/bin/sh`.  To give myself time to sort these things out, I went ahead and commented out the `env` script that sets the umask to `0077` to allow for installation of nix properly with great succcess!!!

Here's the final few lines of the invocation (`sh <(curl -L https://nixos.org/nix/install) --yes`)...

```
~~> Setting up the default profile
installing 'nix-2.13.2'
building '/nix/store/kbr12hx48bb2l9sh75kx9xh91b2kvyiy-user-environment.drv'...
installing 'nss-cacert-3.83'
building '/nix/store/50xiqybwd5yplhkkamgr87scgywzalq9-user-environment.drv'...
unpacking channels...

~~> Setting up the nix-daemon LaunchDaemon
Alright! We're done!
Try it! Open a new terminal, and type:

  $ nix-shell -p nix-info --run "nix-info -m"

Thank you for using this installer. If you have any feedback or need
help, don't hesitate:

You can open an issue at
https://github.com/NixOS/nix/issues/new?labels=installer&template=installer.md

Or get in touch with the community: https://nixos.org/community

---- Reminders -----------------------------------------------------------------
[ 1 ]
Nix won't work in active shell sessions until you restart them.
```

**Comment by abathur** [comment]
> To make matters more complicated, it's unclear whether /bin/bash or /bin/dash is invoked to implement the POSIX shell support intended when using /bin/sh.

I'm not on Ventura yet so I'm not sure, but `/bin/sh --version` should print a bash version if it's still bash, or perhaps fail w/ something like `0: Illegal option --` if it's been changed to dash.

**Comment by jonBoone** [comment]
Yep, you're correct:
```
> ls -l /private/var/select/sh
lrwxr-xr-x  1 root  wheel  9 Jan 13 19:57 /private/var/select/sh -> /bin/bash
```

I suppose I could just configure support `/bin/sh` as if it were implemented by `/bin/bash` (which I'm supporting anyway) -- and when (if?) it changes to `/bin/dash` in the future, I can handle the breakage then....
