### ISSUE TITLE
`nix` command line flag completions are broken

### ISSUE THREAD

**Issue by PJungkamp** [NixOS/nix#7792]
**Describe the bug**

The `nix shell` command shell flag completions are currently broken due to the completions code assuming the `description` field of a `Flag` is a single line.

**Steps To Reproduce**

1. On a shell with tab completions, type 
```sh
nix shell --<tab>
```
2. No completions show up and the shell logs an error like:
```
nix: src/libutil/args.cc:32: void nix::Completions::add(std::string, std::string): Assertion `description.find('\n') == std::string::npos' failed.
```

**Expected behavior**

Commandline completions work.

**`nix-env --version` output**

**Additional context**

Another way to easily trigger the error:
```sh
NIX_GET_COMPLETIONS=2 nix shell -
```

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by PJungkamp** [comment]
Would it make sense to distinguish between a `shortDescription` and `longDescription` for a `Flag`?
Or should the short description be inferred from the long one?

Any thoughts on this?

**Comment by edolstra** [comment]
>  Or should the short description be inferred from the long one?

This might be the most practical. E.g. detect that the description is longer than one line and if so, emit only the first line and add `[...]`.

**Comment by PJungkamp** [comment]
https://github.com/NixOS/nix/blob/1a0b293eb2aa68253717583b72d326a038181b35/src/libutil/args.cc#L30-L37

Basically:
1. Remove the `assert`
2. Truncate the string so it ends before a `\n` (or with a `.`)
3. Add an ellipsis ` [...]`

I'll check it out when I'm back on my nix machine.

**Comment by PJungkamp** [comment]
A fix has been merged. Is there an estimate for the time when the next minor release hits unstable?

**Comment by arcnmx** [comment]
Could this be backported to 2.13, which is [the latest stable nix on nixpkgs atm](https://github.com/NixOS/nixpkgs/blob/3fd093ef5b1ecac98c38b69b8819070b53c218bf/pkgs/tools/package-management/nix/default.nix#L185)?
