### ISSUE TITLE
API docs

### ISSUE THREAD

**Issue by Ericson2314** [NixOS/nix#7814]
It would be good for have API docs generated from comments in the C++ source.

Even though the internal Nix library APIs are unstable and therefore not intended for large scale outside consumption, contributers to Nix itself would still benefit.

Also, in conjunction with stable bindings to other languages, we've discussed stabilizing parts of the C++ interfaces. This would naturally be good for that.

**Comment by roberth** [comment]
Managing expectations around these docs is going to be key. A lot of what they document is internal and subject to change, but that does not mean that we shouldn't improve their documentation.

**Comment by fricklerhandwerk** [comment]
Triaged in the Nix team meeting 2023-02-17:

  - agreement that we want this
  - to discuss tooling and how to proceed

**Comment by Ericson2314** [comment]
For the record, https://hydra.nixos.org/build/224134462#tabs-summary is an example.
