### ISSUE TITLE
Remove `--print-build-logs` from various commands

### ISSUE THREAD

**Issue by roberth** [NixOS/nix#7820]
**Describe the bug**

This flag applies to many commands, but not some, such as `nix store gc`

EDIT: We may choose to keep ignoring the flag if we decide that's ok, but that should be part of the larger discussion about global flags; can be out of scope for this issue. The main problem is with the help text / docs.

**Steps To Reproduce**

`nix ... --help`

**Expected behavior**

Show relevant options.

**`nix-env --version` output**

**Additional context**

 - #7608 
 - #5638 

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by edolstra** [comment]
I'm not convinced we should do this. `-L` belongs to the flags for configuring progress indication / logging, and those flags are all global. And probably `print-build-logs` should be a `nix.conf` setting anyway.

**Comment by fricklerhandwerk** [comment]
I'm more concerned with how the feature integrates with overall behavior, and whether it's easy to explain when it actually applies. Probably we need more careful display of the flag such that it only shows for the relevant commands, and also better documentation on how it works. I'd rather first focus on architecture documentation and show what derivations are, what builders do, and then on can easily say that this flag just enables capturing a build process's `stdout` and `stderr`.

**Comment by roberth** [comment]
The problem isn't resolved until the irrelevant options is removed from the command documentation.

We may choose to keep ignoring the flag if we decide that's ok, but that should be part of the larger discussion about global flags; can be out of scope for this issue.
