### ISSUE TITLE
`nix describe-stores --json` format is not extensible

### ISSUE THREAD

**Issue by roberth** [NixOS/nix#7824]
**Describe the bug**

This json output makes the fatal mistake of putting a dictionary inside a dictionary. This is not extensible; we'll have to break the format.

Definitions
 - dictionary: a map from names to things that all have the same type (C++ `std::map`)
 - record: a fixed set of attributes each with their own type (C++ `struct`)

**Steps To Reproduce**

Try to add a non-setting field to the store description object, e.g. the URI scheme. You can't, because it will be interpreted as an option.

**Expected behavior**

**`nix-env --version` output**

**Additional context**

We need JSON guidelines.
 - #7823 

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by thufschmitt** [comment]
Closing since the mentioned command doesn't exist any more and #7823 adds guidelines for the future
