### ISSUE TITLE
`nix add-derivation`

### ISSUE THREAD

**Issue by Ericson2314** [NixOS/nix#7828]
**Is your feature request related to a problem? Please describe.**

1. No good "plumbing command" to create a derivation without expression language.
2. Lack of an inverse for `show-derivation` means we cannot express the "roundtrip" property that is a good correctness criterion for these things.

**Describe the solution you'd like**
A new `nix add-derivation` command that does the expect thing.

**Describe alternatives you've considered**
Exposing `addTextToStore` as a CLI, which perhaps we should also do, but it shouldn't be the only option. We don't really want to further entrench the current derivation format.

**Additional context**
A nice companion to https://github.com/NixOS/rfcs/pull/134

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by Ericson2314** [comment]
@fgaz Thanks for the :+1:. And with this, I think a Cabal Nix backend could just shell out to Nix, avoids the instability that can arise from an FFI.

**Comment by fricklerhandwerk** [comment]
Triaged in the Nix team meeting 2023-02-17:

- @edolstra: should consider a different name and what the interface should be
    - e.g. Nickel may want to ingest an entire graph of derivations at once
- @edolstra: another consideration the new CLI downplays the concept of a store derivation
    - this idea locks us into having that concept
    - @fricklerhandwerk: representation in the store doesn't matter, but don't see how one would not have the equivalent of store derivations. the important part is having an interface that allows users to ignore the implementation

**Comment by Ericson2314** [comment]
#7903 based on a comment from @roberth suggestion we should go for a more hierarchical name instead. I agree.

**Comment by Ericson2314** [comment]
https://github.com/NixOS/nix/pull/7887 Fixed it!
