### ISSUE TITLE
MacOS Ventura 13.2.1 restores `/etc/zshrc` to its defaults and thus nukes nix working in the terminal

### ISSUE THREAD

**Issue by aliceisjustplaying** [NixOS/nix#7841]
...until I manually put it back. In my case I put it in `~/.zshrc` to avoid this in the future but maybe there are alternative solutions/steps that nix could take that can prevent this issue in the future?

**Comment by abathur** [comment]
#3616

**Comment by aliceisjustplaying** [comment]
Right, thanks. Didn't find it when searching for some reason.
