### ISSUE TITLE
Packages included in pkgs.mkShell are not in PATH

### ISSUE THREAD

**Issue by peperunas** [NixOS/nix#7861]
**Describe the bug**

I cannot execute any command shipped with the packages passed to `pkgs.mkShell` on my systems.

This is the flake I'm taking as reference:

```nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs {
          inherit system;
          config.allowUnfree = true;
        };

        shellWithPkgs = packages: pkgs.mkShell {
          inherit packages;
        };
      in
      {
        devShells.default = shellWithPkgs [ pkgs.hello ];
      });
}
```

**Steps To Reproduce**

1. nix develop

**Expected behavior**

You should be able to run `hello` in the spawned shell. Instead, I get:

```
$ hello: command not found
```

**`nix-env --version` output**
`nix-env (Nix) 2.11.1`

**Comment by roberth** [comment]
Works with `nativeBuildInputs` instead of `packages`; also works with `nix-shell` and

```nix
(builtins.getFlake (toString ./.)).devShells.${builtins.currentSystem}.default
```

Did not find a smoking gun.

**Comment by peperunas** [comment]
Cannot reproduce it, I believe it was a system error on my end.

I am sorry for the inconvenience.
