### ISSUE TITLE
SEGV in debugger

### ISSUE THREAD

**Issue by Et7f3** [NixOS/nix#7879]
**Describe the bug**

it seems that I managed to hide `builtins` and auto completion cause a crash.

If you have a problem with a specific package or NixOS,
you probably want to file an issue at https://github.com/NixOS/nixpkgs/issues. 

**Steps To Reproduce**

copy this in a file

```expect
#! /usr/bin/env nix-shell
#! nix-shell -i expect --pure -p expect

# typo my bad
spawn nix --extra-experimental-features nix-command eval --expr builtins.throws --debugger

# Can't remember this builtins name
send "builtins.getElem 0 0\n"

# Ok return to previous context
send :q\n

# tabs to trigger autocompletion
send "builtins.\t"

# interact is used to drain stdout/err of nix
interact
puts "\n[wait]"
```
chmod u+x this file and execute it

**Expected behavior**

Not a segv

**`nix-env --version` output** 2.13.1 and master

**Additional context**

I try to debug another SEGV (and I caught this one)

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by yorickvP** [comment]
Related: #7134.
