### ISSUE TITLE
Supplementary GIDs is limited to 10

### ISSUE THREAD

**Issue by abuibrahim** [NixOS/nix#788]
Would it be possible to increase this limit to at least 20, or better yet remove the limitation altogether? On my setup I am a member of 17 groups.

https://github.com/NixOS/nix/blob/master/src/libstore/build.cc#L531

**Comment by vcunat** [comment]
That's fine for regular users but why have so many groups for *build* users?

**Comment by abuibrahim** [comment]
This affect my regular account for some reason:

$ nix-env --version
nix-env (Nix) 1.10
$ nix-env -u
building path(s) ‘/nix/store/5fcl7mww2qqc06z9mpvrifksv7x2370p-user-environment’
error: failed to get list of supplementary groups for ‘ruslan’

**Comment by vcunat** [comment]
Nix chooses users from `build-users-group` set in `/etc/nix/nix.conf` (in standard system-wide installation). It's meant that this group is only for nix build users and those are only used for that purpose.

**Comment by abuibrahim** [comment]
Oh, my bad. I had my regular user account added to the nixbld group.
Will close this issue then.
Thanks for prompt response!

**Comment by vcunat** [comment]
:-)
