### ISSUE TITLE
500 line incomprehensible error message

### ISSUE THREAD

**Issue by davidak** [NixOS/nix#7899]
**Describe the bug**

https://gist.github.com/davidak/abd943cd44ff88f0fd9d6bff3183194a

**Steps To Reproduce**

`nix eval -f '<nixpkgs>' p3x-onenote --argstr system i686-linux --show-trace`

strange thing is this actually works without issue

`nix-build '<nixpkgs>' -A p3x-onenote --argstr system i686-linux --show-trace`

evaluation fails but building works?

**Expected behavior**

Short and clear error message i can act on.

**`nix-env --version` output** nix-env (Nix) 2.11.1

**Additional context**

Similar issue like https://github.com/NixOS/nix/issues/7898.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by SuperSandro2000** [comment]
This is a dupe of #7898

**Comment by davidak** [comment]
Closing in favor of https://github.com/NixOS/nix/issues/7900.
