### ISSUE TITLE
`nix shell` does not insert `PATH` items in command line order

### ISSUE THREAD

**Issue by roberth** [NixOS/nix#7905]
**Describe the bug**

`nix shell` does not insert `PATH` items in command line order. Instead, it traverses them left to right *prepending* each, resulting in a reversal.

**Steps To Reproduce**

Apologies for the whacky example.

1. Use my nixpkgs branch with a customized hello package. (will link; doesn't matter much)
2. `nix shell .#hello .#salve-mundi`
3. `hello`

It invokes the latter package, printing `SALVE MUNDI`

**Expected behavior**

Prepend them to the existing `PATH` but in the same order as specified on the command line.

**`nix-env --version` output**

`master` 92611e6e4c1c5c712ca7d5f9a258640662d006df

**Additional context**

- #7701 

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by cole-h** [comment]
I took a stab at this in https://github.com/NixOS/nix/pull/9648.
