### ISSUE TITLE
dev-shell missing perl paths

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nix#791]
```shell
$ ./dev-shell
$ ./bootstrap.sh
$ ./configure
…
checking for LIBCURL... yes
checking for SODIUM... yes
checking for LIBLZMA... yes
checking whether DBD::SQLite works... no
configure: error: in `/home/philip/code/nix/nix':
configure: error: The Perl modules DBI and/or DBD::SQLite are missing.
See `config.log' for more details
```

On a side note: Why isn’t it possible to use the package manager to build the package manager? `nix-shell` should be all that is necessary if done right, imo.

**Comment by Profpatsch** [comment]
After some trial and error I have found out that a variable `$configureFlags` is set, so

    ./configure $configureFlags

does the trick.

Is that the intended usage, though?

**Comment by edolstra** [comment]
Yes it is. See http://nixos.org/nix/manual/#chap-hacking.
