### ISSUE TITLE
NIX_PATH downloads are not lazy

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#792]
E.g., seen during a NixOps deploy while `nixos.org` was down:
```
webserver.......> error: command ‘['ssh', '-oControlPath=/tmp/nixops-ssh-tmpArC7nc/master-socket', '-p', '22', '-i', '/tmp/nixops-tmpCrcRWH/id_nixops-webserver', '-p', '22', '-i', '/tmp/nixops-tmpCrcRWH/id_nixops-webserver', '-x', 'root@54.217.220.47', '--', 'NIX_REMOTE=daemon nix-env -p /nix/var/nix/profiles/system --set "/nix/store/gj2v1ql7xa93wjzqq929i18cl3b7rrzx-nixos-15.09.git.5fd87e1M"']’ failed on machine ‘webserver’ (exit code 1)
```
I.e., `nix-env --set` failed because `NIX_PATH` contained `https://nixos.org/channels/nixos-15.09-small/nixexprs.tar.xz` which couldn't be downloaded at that time. But it shouldn't be downloaded to begin with.

**Comment by domenkozar** [comment]
Also see https://github.com/NixOS/nixops/issues/405

**Comment by domenkozar** [comment]
@edolstra could we get this prioritized for next release? It's quite annoying bug for users with less Nix experience.
