### ISSUE TITLE
nix env not loading in C libraries

### ISSUE THREAD

**Issue by Peter015** [NixOS/nix#7926]
### Bug Description:
I am working on a lisp project that uses libraries that have C dependencies in the fish shell & emacs. When I load in the package it works, but at runtime, the libraries fail. These are the way that the libraries are loaded:
shell.nix:
```nix
pkgs.mkShell {
  buildInputs = with pkgs; [
    # CLibs for lisp dependencies
    libressl
    tree-sitter
    libev
    # Lisp tools. Libs install with quicklisp and asdf
    lispPackages.quicklisp
    sbcl
    # typescript and node
    nodejs
    nodePackages.typescript
    nodePackages.ts-node
  ];
}
```
flake.nix:
```nix
{
  description = "Nix Flake for pastebin";
  
  inputs = {
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem
      (system:
        let pkgs = nixpkgs.legacyPackages.${system}; in
        {
          devShells.default = import ./shell.nix { inherit pkgs; };
        }
      );
}
```
and then "use flake" in .envrc. When I check the $NIX_LDFLAGS, this is the output:
```
-rpath /home/peterz/Projects/common-lisp/pastebin/outputs/out/lib64 -rpath /home/peterz/Projects/common-lisp/pastebin/outputs/out/lib  -L/nix/store/0hb1nk2lrq4i4myih8s323r8rlrmzy4y-libressl-3.6.2/lib -L/nix/store/n9j9x1bzczhpmf7krlqmv93r30yrrjal-tree-sitter-0.20.7/lib -L/nix/store/izxbn97vypvvf5qdaw22flddrd93nvrx-libev-4.33/lib -L/nix/store/nzxhm7b91pbjq7m8j5a1dwvpy2ib5pql-gettext-0.21/lib -L/nix/store/0hb1nk2lrq4i4myih8s323r8rlrmzy4y-libressl-3.6.2/lib -L/nix/store/n9j9x1bzczhpmf7krlqmv93r30yrrjal-tree-sitter-0.20.7/lib -L/nix/store/izxbn97vypvvf5qdaw22flddrd93nvrx-libev-4.33/lib -L/nix/store/nzxhm7b91pbjq7m8j5a1dwvpy2ib5pql-gettext-0.21/lib
```
This mostly looks good, except for the lack of spaces in the path, so I think that might be the issue. When I set the LD_LIBRARY_PATH variable in my .profile it works, but this is annoying because I have to do that every time I add or change a dependency, or if there is an update. 

I am using nixos unstable, fish shell version 3.6.0 and emacs-gtk 28.2. This bug also occurs in bash.

**Comment by fricklerhandwerk** [comment]
This is almost certainly not a Nix bug, but either a user issue or some Nixpkgs `stdenv` quirk. Please [ask for help on Discourse](https://discourse.nixos.org/c/learn/9). If it turns out to be a bug, feel free to re-open the issue, I can transfer it to Nixpkgs if needed.
