### ISSUE TITLE
New profile location breaks home-manager

### ISSUE THREAD

**Issue by ncfavier** [NixOS/nix#7930]
**Describe the bug**

Nix 2.14 (presumably https://github.com/NixOS/nix/pull/5226) breaks the home-manager tests: https://github.com/nix-community/home-manager/actions/runs/4301868239/jobs/7499628919#step:8:260

(We're pinned on 2.13 for now, so no emergency)

The relevant code where home-manager seems to assume things about the default profile location is https://github.com/nix-community/home-manager/blob/master/modules/lib-bash/activation-init.sh

Does home-manager need to change, and if so, would those changes be compatible with older versions of Nix?

(I've spent exactly 0 seconds thinking about this, I'm just reporting the problem. 😴)

cc @fricklerhandwerk 

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by thufschmitt** [comment]
Thanks for opening that.

Also see https://github.com/nix-community/home-manager/issues/2544 (which offers what I think is the best solution to that on the HM side) and https://github.com/NixOS/nixpkgs/pull/218858 .

I'm also working on a patch to provide some best-effort backwards-compatibility, but it's probably not going to be 100% reliable if people decide to tweak things a bit

**Comment by thufschmitt** [comment]
Closing since home-manager isn't impacted by this any more

**Comment by flokli** [comment]
My home-manager still/again seems to be impacted, ran into this when trying to start the home-manager-flokli.service on a new NixOS box.

What's the recommended way forward here? Should I just `mkdir /nix/var/nix/{gcroots,profiles}/per-user/flokli` from now on, or how is this supposed to work on a new system?

**Comment by thufschmitt** [comment]
@flokli what's your home-manager/Nix version? And what's the exact error you see?

**Comment by flokli** [comment]
This was home-manager `fae8af43e201a8929ce45a5ea46192bbd1ffff18`, and Nix `2.17.0`.

I didn't set any experimental xdg options in Nix.

The log messages were:

```
Aug 30 11:55:58 x1 systemd[1]: Starting Home Manager environment for flokli...
Aug 30 11:55:58 x1 hm-activate-flokli[11783]: Starting Home Manager activation
Aug 30 11:55:58 x1 hm-activate-flokli[11783]: Sanity checking Nix
Aug 30 11:55:58 x1 hm-activate-flokli[11783]: Sanity checking oldGenNum and oldGenPath
Aug 30 11:55:58 x1 hm-activate-flokli[11783]: This is a live run
Aug 30 11:55:58 x1 hm-activate-flokli[11783]: Using Nix version: nix-env (Nix) 2.17.0
Aug 30 11:55:58 x1 hm-activate-flokli[11783]: Activation variables:
Aug 30 11:55:58 x1 hm-activate-flokli[11783]:   oldGenNum=231
Aug 30 11:55:58 x1 hm-activate-flokli[11783]:   oldGenPath=/nix/store/05ypwxsrlzbl4kzaj1jnj7abab6p8344-home-manager-generation
Aug 30 11:55:58 x1 hm-activate-flokli[11783]:   newGenPath=/nix/store/rrah84zn1q9z4sf31la52vmilqrpmn73-home-manager-generation
Aug 30 11:55:58 x1 hm-activate-flokli[11783]:   newGenNum=232
Aug 30 11:55:58 x1 hm-activate-flokli[11783]:   genProfilePath=/home/flokli/.local/state/nix/profiles/home-manager
Aug 30 11:55:58 x1 hm-activate-flokli[11783]:   newGenGcPath=/home/flokli/.local/state/home-manager/gcroots/current-home
Aug 30 11:55:58 x1 hm-activate-flokli[11783]:   legacyGenGcPath=/nix/var/nix/gcroots/per-user/flokli/current-home
Aug 30 11:55:58 x1 hm-activate-flokli[11783]: Activating checkFilesChanged
Aug 30 11:55:58 x1 hm-activate-flokli[11783]: Activating checkLinkTargets
Aug 30 11:55:58 x1 hm-activate-flokli[11783]: Activating writeBoundary
Aug 30 11:55:58 x1 hm-activate-flokli[11783]: Activating installPackages
Aug 30 11:55:58 x1 hm-activate-flokli[12120]: installing 'home-manager-path'
Aug 30 11:55:58 x1 hm-activate-flokli[12120]: building '/nix/store/gn83jb0dqdc6i519cjqsqsi9rfmbjdq7-user-environment.drv'...
Aug 30 11:55:58 x1 hm-activate-flokli[12120]: error: opening lock file '/nix/var/nix/profiles/per-user/flokli/profile.lock': No such file or directory
Aug 30 11:55:58 x1 hm-activate-flokli[11783]: Oops, Nix failed to install your new Home Manager profile!
Aug 30 11:55:58 x1 hm-activate-flokli[11783]: Perhaps there is a conflict with a package that was installed using
Aug 30 11:55:58 x1 hm-activate-flokli[11783]: "nix-env -i"? Try running
Aug 30 11:55:58 x1 hm-activate-flokli[11783]:     nix-env -q
Aug 30 11:55:58 x1 hm-activate-flokli[11783]: and if there is a conflicting package you can remove it with
Aug 30 11:55:58 x1 hm-activate-flokli[11783]:     nix-env -e {package name}
Aug 30 11:55:58 x1 hm-activate-flokli[11783]: Then try activating your Home Manager configuration again.
Aug 30 11:55:58 x1 systemd[1]: home-manager-flokli.service: Main process exited, code=exited, status=1/FAILURE
Aug 30 11:55:58 x1 systemd[1]: home-manager-flokli.service: Failed with result 'exit-code'.
Aug 30 11:55:58 x1 systemd[1]: Failed to start Home Manager environment for flokli.
```
