### ISSUE TITLE
response-body preview on HTTP errors is garbage when using `github`

### ISSUE THREAD

**Issue by NobbZ** [NixOS/nix#7938]
**Describe the bug**

When trying to remote-access a flake on GitHub an error message is printed with an unreadable blob as "request body", this is probably due to compression

**Steps To Reproduce**

1. run `nix flake info github:a/b`
2. See 404 error:
   ```text
   warning: 'nix flake info' is a deprecated alias for 'nix flake metadata'
   error:
          … while fetching the input 'github:a/b'

          error: unable to download 'https://api.github.com/repos/a/b/commits/HEAD': HTTP error 404

          response body:

          5�1
   k��Y�;X�H�o▒�o>K�271��q�Ŀ���3{▒k)��L��A`{)y��-��%q�G�<�c{?+�k���
   ```

**Expected behavior**

the response body shows an actual JSON-blob, as it is shown by `curl` the URL above.

**`nix-env --version` output**

```
$ nix --version
nix (Nix) 2.14.0pre20230228_d5af43c
```

**Additional context**

* The `gitlab` equivalent works as expected.
* using `curl -v` I can't see any hints for compression
* bisection already started with 1.14.0 bad and 1.13.0 good

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by NobbZ** [comment]
Bisection resulted in f20d3726dd9031a4ec311c77f30caa7cc493138b being the first bad commit.

\cc @Mic92 as the commit Author
and @thufschmitt as co-author.

**Comment by NobbZ** [comment]
I can partially reproduce the output of `nix` by adding the injected "`Accept-Encoding`" header introduced by this commit:

```
$ curl https://api.github.com/repos/a/b/commits/HEAD -H "Accept-Encoding: zstd, br, gzip, deflate, bzip2, xz"|cat
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   113  100   113    0     0    232      0 --:--:-- --:--:-- --:--:--   232
51
kY;XHoo>K271q
```

Replacing `cat` with `gunzip` produces the expected result.

So my assumtion is, that something here does request a compressed payload, but then does not adhere to the `content-encoding` in the response.

**Comment by thufschmitt** [comment]
Indeed, the error is directly fed the raw content of the http response ([here](https://github.com/NixOS/nix/blob/85dbf9de8e30d07139d983ee4066332c477ee0f9/src/libstore/filetransfer.cc#L167)), which isn't exactly what we want :)

I've opened #7940 , which should fix this
