### ISSUE TITLE
SSL certificate problem when running git in pure shell

### ISSUE THREAD

**Issue by YPares** [NixOS/nix#795]
When running:
`$ nix-shell -p git --pure`
And inside the shell, running:
`$ git clone https://github.com/YPares/Config.git`

I get:
`fatal: unable to access 'https://github.com/YPares/Config.git/': SSL certificate problem: unable to get local issuer certificate`

It happens whatever the repo I try to clone, and also when I try to clone something from bitbucket.

However:
`GIT_SSL_NO_VERIFY=true git clone https://github.com/YPares/Config.git`
makes it work in a pure shell.

I don't have this problem in a non-pure shell (even if it's also the `git` from the nix store which is called).

It happens with git 2.7.0 (latest channel update) and git 2.6

**Comment by witkamp** [comment]
The pure shell will not have the following variables set because they are not part of the nix expression.
````
GIT_SSL_CAINFO=/etc/ssl/certs/ca-certificates.crt
SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
````
Here is an excerpt from the man page
````
       --pure
           If this flag is specified, the environment is almost entirely cleared before the
           interactive shell is started, so you get an environment that more closely
           corresponds to the “real” Nix build. A few variables, in particular HOME, USER
           and DISPLAY, are retained. Note that ~/.bashrc and (depending on your Bash
           installation) /etc/bashrc are still sourced, so any variables set there will
           affect the interactive shell.
````

**Comment by YPares** [comment]
Apparently it's a duplicate of this issue: https://github.com/NixOS/nixpkgs/issues/3382
I'm closing this one.
