### ISSUE TITLE
Inputs to pager gets overwritten in help pages

### ISSUE THREAD

**Issue by poscat0x04** [NixOS/nix#7950]
**Describe the bug**

Inputs to the pager, for example, search commands (`/something`) gets overwritten in help pages.
This is very inconvenient for people trying to search the help page.

**Steps To Reproduce**

1. `nix --help`
2. input `/bla`
3. observe that what you typed in disappears immediately

**Expected behavior**

**`nix-env --version` output**

nix (Nix) 2.11.1

**Comment by edolstra** [comment]
We've backported the fix to 2.11 (#7033).
