### ISSUE TITLE
nix

### ISSUE THREAD

**Issue by vlad2523** [NixOS/nix#7952]
## Platform

- [x] Linux: 
- [ ] macOS
- [ ] WSL

## Output

<details><summary>Output</summary>

```log

<!-- paste console output here and remove this comment -->

```

</details>

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by superherointj** [comment]
@vlad2523 This looks empty to me. Did you forget to paste anything? What is the goal here?
