### ISSUE TITLE
`nix profile`s upgrade and remove have counter-intuitive argument

### ISSUE THREAD

**Issue by bobvanderlinden** [NixOS/nix#7960]
Using upgrade and remove is counter intuitive. The following example shows what a user will likely presume to work:

```console
$ nix profile install github:cachix/devenv/latest
$ nix profile upgrade github:cachix/devenv/latest
warning: 'github:cachix/devenv/latest' does not match any packages
warning: Use 'nix profile list' to see the current profile.
$ nix profile remove devenv
warning: 'devenv' does not match any packages
warning: Use 'nix profile list' to see the current profile.
```

- The installable used in `install` is not applicable to `remove` nor `upgrade`.
- The output shows warnings, but are actually errors. Nothing has changed to the profile.
- `nix profile list` is suggested, but it isn't clear that you need to pick the _index_ from that list.
- The name of the installable (`devenv`) is not applicable to `remove` nor `upgrade`. Ideally the `NAME` is deferred from the flake patterns (`github:OWNER/NAME/VERSION`, `github:OWNER/REPO/VERSION#NAME`, `nixpkgs#NAME`, `github:OWNER/NAME/VERSION#default`).

**Comment by edrex** [comment]
To ease my own pain here, I wrote a little interactive fzf wrapper script around the `upgrade` and `remove` subcommands:
https://github.com/edrex/nixcfg/blob/main/cmd/nix-profile
