### ISSUE TITLE
`nix profile` counter-intuitively uses regexp to match packages

### ISSUE THREAD

**Issue by bobvanderlinden** [NixOS/nix#7962]
`nix profile` remove and upgrade accept an regexp argument to be able to match specific (or ranges of) packages. This usually results in confusion. Some common errors that people can run into:

Forgetting quotation in most shells:

```console
$ nix profile remove .*vim.*
fish: No matches for wildcard '.*vim.*'. See `help wildcards-globbing`.
nix profile remove .*vim.*
                   ^~~~~~^
```

```console
$ nix profile remove .*vim.*
zsh: no matches found: .*vim.*
```

Using wildcards instead of regexp result in confusing error message:

```console
$ nix profile remove '*vim*'
error: Mismatched '(' and ')' in regular expression
```

Which `(` and `)`?

Forgetting regexp and wildcards altogether:

```console
$ nix profile remove vim
warning: 'vim' does not match any packages
warning: Use 'nix profile list' to see the current profile.
```

This makes it seem like `vim` was not installed at all, but it just wasn't matched by the regexp `vim`, because it should match `flake:nixpkgs#legacyPackages.x86_64-linux.vim`.

I'm thinking `nix profile` should only optionally accept regexp and it should be very explicit about it. For instance `--regex "your regex"`. It shouldn't be the default to match packages.

**Comment by thufschmitt** [comment]
That is indeed quite bad as an interface. Just jotting an extra possible point in the design space (no idea whether it's a _good_ one, but it's the first that came to my mind while reading this): keep a regex, but don't require it to be a full match. That way `nix profile remove vim` would be equivalent to `nix profile remove '.*vim.*'` and would correctly match

**Comment by iFreilicht** [comment]
@thufschmitt I really like this idea! It makes the interface much nicer without losing any power. I thought about potential edge cases, but the ones I came up with (i.e. removing `gitlab`, which is also a flake type) aren't actually a problem, as the regex only matches against the attribute path, so `legacyPackages.aarch64-darwin.vim`.

Seems this is a no-brainer with low-risk. I'll take a stab at implementing it!

**Comment by sullyj3** [comment]
Another issue is that it's not clear what regex dialect is used (is this documented anywhere?), so I have no way of finding out [how to use word boundaries](https://discourse.nixos.org/t/nix-search-regex-word-boundaries/23059), for example.

**Comment by iFreilicht** [comment]
@sullyj3 Nix is using the C++ std::regex library, so it follows ECMAScript regex syntax. 

However there is one exception [`builtins.regex`](https://nixos.org/manual/nix/unstable/language/builtins.html#builtins-match) specifically uses POSIX extended regex. I'm not sure, but I assume this was chosen to be consistent with tools like `grep` as those are used in builder scripts.

This is a good point, though, we should document in general what regex syntax is used for all commands that accept them.

**Comment by sullyj3** [comment]
@iFreilicht Cheers! According to that page, the dialect does support `\b` for word boundary, any idea what I'm doing wrong here?
```bash
⮞ nix search nixpkgs '\brip'
error: Invalid escape in regular expression
```

**Comment by sullyj3** [comment]
Hmm, still no joy:
```bash
⮞ nix search nixpkgs '[[:<:]]rip'
error: Invalid character class.
```

Possibly it's not supported by whatever library is being used?

**Comment by iFreilicht** [comment]
That is the right place to look in, and it seems you're right :/ Sorry about that. What's your usecase for using a word-boundary in a search anyway? Maybe there's a different solution to your problem?

**Comment by sullyj3** [comment]
I was searching for the [`rip` package](https://github.com/nivekuil/rip), and `nix search nixpkgs rip` gives a flood of irrelevant results.
```
[...]
* legacyPackages.x86_64-linux.weechatScripts.weechat-grep (0.8.5)
  Search in Weechat buffers and logs (for Weechat 0.3.*)

* legacyPackages.x86_64-linux.weechatScripts.weechat-matrix (0.3.0)
  A Python plugin for Weechat that lets Weechat communicate over the Matrix protocol

* legacyPackages.x86_64-linux.weechatScripts.weechat-matrix-bridge (2018-11-19)
  A WeeChat script in Lua that implements the matrix.org chat protocol

* legacyPackages.x86_64-linux.weechatScripts.weechat-notify-send (0.9)
  A WeeChat script that sends highlight and message notifications through notify-send

* legacyPackages.x86_64-linux.weechatScripts.weechat-otr (1.9.2)
  WeeChat script for Off-the-Record messaging

* legacyPackages.x86_64-linux.weechatScripts.zncplayback (0.2.1)
  Add support for the ZNC Playback module
[...]
```
From grepping a cloned copy of nixpkgs it does seem like it's not in there, but that's beside the point.

**Comment by sullyj3** [comment]
Unfortunately piping `nix search` into grep or ripgrep doesn't work correctly as a workaround either, as nix's output seems to be colored regardless of whether it's connected to a pipe or a terminal.

**Comment by sullyj3** [comment]
This is getting a bit off topic apologies. I'll just note that #3047 seems relevant

**Comment by iFreilicht** [comment]
No worries, but maybe you could collect these in a new issue similar to this one? We are aware that `nix search` is not very useful in its current form, but I didn't see an issue that really tracks what the current problems are. If you have any ideas on how to improve the terrible matching right now (maybe by only searching the package name by default, stuff like that), you can absolutely create feature requests as well. We can then have an extended discussion there :)

For more brain-storming kind of threads, you might also want to post on the [Nix Forums](https://discourse.nixos.org/), either in the #Development or #Help categories. You might find existing threads on the usability problems with nix search there as well.

Thank you for taking the time to dig into this!

**Comment by sullyj3** [comment]
Sure, I'll have a crack later this week.

**Comment by bobvanderlinden** [comment]
Regexes are still used in `nix profile`s remove/upgrade, but we have profile entry names now. It now matches regex on those. Using `'.*'` might still be confusing, but at least the main use-case (`nix profile remove vim`) works now 🥳.

I think I'll close this. If there are still remaining cases, please open a new issue and feel free to mention https://github.com/NixOS/nix/issues/7966, I'll add it to the list 👍
