### ISSUE TITLE
osx not able to install using script multi user mode

### ISSUE THREAD

**Issue by ehrktia** [NixOS/nix#7969]
## Platform

- [ ] Linux: 
- [x] macOS
- [ ] WSL

## Additional information

ran the script `curl -L https://nixos.org/nix/install | sh`

## Output

no error 
but the scripts is creating users endless i.e - in total **33 hidden users**

is this really required to have **33** users???

Any option to configure the user numbers during the installation?

```log
~~> Setting up the build user _nixbld16
Password:
           Created:     Yes
Password:
            Hidden:     Yes
Password:
    Home Directory:     /var/empty
Password:
sudo: a password is required

```

Any option to control the number of users created during installation would be highly helpful.

</details>

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by abathur** [comment]
https://github.com/NixOS/nix/blob/0507462c0626d19b59b78e490b7b203df29e7bb0/scripts/install-multi-user.sh#L23-L25
