### ISSUE TITLE
`nix develop` does not set `SHELL` correctly

### ISSUE THREAD

**Issue by bobvanderlinden** [NixOS/nix#7971]
**Describe the bug**

`nix develop` keeps the `SHELL` variable from the calling environment. Even if `--ignore-environment` is used.

When you're using a shell like `fish`, the build within `nix develop` will run into errors regarding bash/fish incompatibilities.

**Steps To Reproduce**

```console
$ echo $SHELL
/run/current-system/sw/bin/fish
$ nix develop --ignore-environment github:nixos/nixpkgs/nixpkgs-unstable#hello
$ echo $SHELL
/run/current-system/sw/bin/fish
```

**Expected behavior**

The `SHELL` environment variable should be set to the shell that is intended to run using `nix build`.

**Comment by Ericson2314** [comment]
Discussed in the Nix team meeting:

- whether or not we want this to be the "arbitrary dev env" or "debug the derivation" one, it should be at least consistent.
  - So long as we force `bash` / force the builder shell, `SHELL` should match.
  - If we allow arbitrary user shells, only then would we have arbitrary `SHELL` to match.
- idea approved, but not high priority

**Comment by Ericson2314** [comment]
This is good for external contributors to do, however!

**Comment by bobvanderlinden** [comment]
I have created https://github.com/NixOS/nix/pull/8043, which seems to be fixing the issue.
