### ISSUE TITLE
Global Channels and per-user profiles

### ISSUE THREAD

**Issue by Ericson2314** [NixOS/nix#7984]
**Describe the bug**

I ran into trouble installing (a) Nix and then (b) home-manager on my friend's macOS machine. A bunch of similar issues have been reported, but I think this one is slightly different.

The problem is this:

https://github.com/NixOS/nix/blob/19c1a4699b2a19e38c9d3953e75c029b4faee2ce/src/libexpr/eval.cc#L2494-L2495

these two lines neglect the fact that with the XDG profile dirs, these will instead be in `~root/.local/state/profiles/channels`.

**Steps To Reproduce**

1. Install Nix 2.14.1 on macOS in multi-user mode
3. Try to do anything involving `<nixpkgs>`
4. get errors because there is no `nixpkgs` key defined via the Nix Path.

**Expected behavior**

Global channels are usable with the default (no env var set) Nix path.

**`nix-env --version` output**

nix-env (Nix) 2.14.1

**Additional context**

A simple fix would be to get the the default Nix path to try to look in `~root/.local/state/nix/profiles/channels` too, but I don't think that is the right solution. "per user" profiles (channels or otherwise) should be *just for that user*, which is why it is safe and correct to move them to `~/.local/state/nix/profiles`. If channels are to be shared system wide, they are not a per-user concept, even a root user concept. Indeed, root-specific channels *should* be secret channels just for the root user.

We have precedent of this: the default profile which has long been `$nixStateDir/profiles/default` not `$nixStateDir/profiles/per-user/root` precisely for the same reason. We should simply reuse that same solution and have `nixStateDir + profiles/default` or similar. Neither of these are effected by the XDG stuff because they are not per user, and this is correct.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by fricklerhandwerk** [comment]
Discussed in the Nix team meeting:

- @thufschmitt: was pushing for merging that, but it was really hard to have a proper compatibility layer due to how things are set up
    - wondering what's the right thing to do:
        - fix up quickly
        - revert and think it through
        - ignore backwards compatibility
- @Ericson2314: it's almost there, should change the installer to use the new directories
    - @thufschmitt: not enough to change the installer, need proper backwards compatibility for existing setups
- @fricklerhandwerk: would veto on ignoring home manager concerns, should rather rethink this
    - @thufschmitt: could help HM fixing forward, seems like an easy change
    - @Ericson2314: reverting would be demoralising
 - @edolstra: this one feels more useful than the XDG one to me 
     - if we revert this, would it break people who already rely on the change?
      - @Ericson2314: probably yes
      - @thufschmitt: will think about a fix forward
          - @Ericson2314: flip the default instead of doing more compat
- no decision

**Comment by corneliusroemer** [comment]
I ran into exactly this issue as described, see https://stackoverflow.com/questions/75657834/fresh-install-of-nix-fails-on-m1-mac-error-attribute-nixpkgs-in-selection-pa

Can I suggest a quick fix @fricklerhandwerk? The most affected people by this seem to be people who install for the first time. They will usually use recommended `curl -L https://nixos.org/nix/install | sh`, this is mentioned everywhere as _the_ way to install.

So why don't you change that install script to download 2.13 until you have figured out a way forward with 2.14?

**Comment by fricklerhandwerk** [comment]
Yes, we talked about versioned installers recently, and I'm in favor of this. Need to prioritise it on the team though. @Ericson2314 do we have an issue for that?

**Comment by Ericson2314** [comment]
@fricklerhandwerk An issue for what, rolling back the default installer? I agree that is a good stop-gap.

**Comment by corneliusroemer** [comment]
Possibly related? https://github.com/NixOS/nix/issues/7992

**Comment by edolstra** [comment]
We've reverted the installer to 2.13.1 for now.

**Comment by Ericson2314** [comment]
Discussed in the Nix team Meeting:

- @ericson2314: users should be able to pick up system channels, while ~root is not accessible
- @theophane: global channels location is more public so we should be wary of using it, maybe keep `/nix/var/nix/profile/per-user/root/channels`?
- @ericson2314: Worried about having that path as a special case where the directories no longer "mean" what they did before
- @thufschmitt: Could have a new path, and then the old path as a symlink to it
- @ericson3214: Sounds great!
- Assigned to @thufschmitt

**Comment by Ericson2314** [comment]
https://github.com/NixOS/nix/pull/8073 fixed this.

**Comment by Ericson2314** [comment]
https://github.com/NixOS/nix/pull/8147 builds on this, but is just icing on the cake.
