### ISSUE TITLE
SQLite busy reporting is broken

### ISSUE THREAD

**Issue by roberth** [NixOS/nix#7998]
**Describe the bug**

These warnings are annoying and happen even on systems that don't have excessive load or a DoS attack on the sqlite dbs.

`handleSQLiteBusy` shouldn't use a global. Instead, `retrySQLite` should track the time, so that we only warn when there's real resource starvation happening.

**Steps To Reproduce**

Run a nix process for longer than 10s on a system with another concurrent nix process(?)

You'll get warnerrors like

```
warning: error: SQLite database '.../.cache/nix/eval-cache-v4/ddde80e82adeb67a94c9bf7944f4b67b3be48de38fe4449746af9d38100b6d6b.sqlite' is busy
```

**Expected behavior**

Only warn when the db is really unavailable for a long time.

**`nix-env --version` output**

Expected in Nix as recent as 2.14, 2.15pre at time of writing.

**Additional context**

It also causes flaky tests.

 - https://github.com/NixOS/nix/pull/7888#issuecomment-1458978354
   - https://github.com/NixOS/nix/actions/runs/4358175686/jobs/7619878059

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by jkarni** [comment]
This should be closed by https://github.com/NixOS/nix/pull/8199 I believe?
