### ISSUE TITLE
Failed to "Creating the Nix build user (#1), _nixbld1"

### ISSUE THREAD

**Issue by TorstenRobitzki** [NixOS/nix#8016]
## Platform

- [ ] Linux: 
- [X ] macOS
- [ ] WSL

## Additional information

I tried to install Nix on my MacBook (macOS Version 13.2.1).

## Output

<details><summary>Output</summary>

```log

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o create -r Nix build group for nix-daemon -i 30000 nixbld

Create the Nix build group, nixbld

            Created:	Yes

~~> Setting up the build user _nixbld1

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/_nixbld1 UniqueID 301

Creating the Nix build user (#1), _nixbld1

<main> attribute status: eDSRecordAlreadyExists
<dscl_cmd> DS Error: -14135 (eDSRecordAlreadyExists)

---- oh no! --------------------------------------------------------------------
Oh no, something went wrong. If you can take all the output and open
an issue, we'd love to fix the problem so nobody else has this issue.

:(

We'd love to help if you need it.

You can open an issue at
https://github.com/NixOS/nix/issues/new?labels=installer&template=installer.md

Or get in touch with the community: https://nixos.org/community

```

</details>

Looks like the installation script did a lot of changes before it failed. At the beginning of the script, there was a promise, that every change can be undone quite easily. What do I have to do now, to revert the changes done?

Update: I've remove that user (_nixbld1 [it was the only one created]) und rerun the installation script, with the very same result. Looks like the script is creating the user and then somehow stumbles over it (maybe tries to create it a second time?).

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by abathur** [comment]
Same issue as #6153. 

You'll have to follow the uninstall instructions to clean up first: https://nixos.org/manual/nix/stable/installation/installing-binary.html#macos

There's more context in the linked issue, but you'll either need to clear out whatever is holding the uid, or modify the installer to use a new one.

**Comment by TorstenRobitzki** [comment]
Yes, it seems to be exactly the same issue. I have already a user with the ID 301
