### ISSUE TITLE
emacs syntax highlighting is a little off. 

### ISSUE THREAD

**Issue by fxfactorial** [NixOS/nix#803]
I'm working on a new nix package and noticed this syntax highlighting breakage:

aka, line 49  
<img width="614" alt="screen shot 2016-02-15 at 2 25 27 pm" src="https://cloud.githubusercontent.com/assets/3036816/13061968/1d5f1284-d3f0-11e5-882e-261ddb042543.png">

**Comment by Ericson2314** [comment]
Duplicate: https://github.com/NixOS/nix/issues/632

**Comment by Ericson2314** [comment]
This can be closed because of #870
