### ISSUE TITLE
What is "restricted evaluation mode"?

### ISSUE THREAD

**Issue by toraritte** [NixOS/nix#8088]
## Problem

Both [`fetchurl`](https://nixos.org/manual/nix/stable/language/builtins.html#builtins-fetchurl) and [`fetchTarball`](https://nixos.org/manual/nix/stable/language/builtins.html#builtins-fetchTarball) entries in the Nix manual refer to "restricted evaluation mode", which is a link pointing to https://nixos.org/manual/nix/stable/command-ref/conf-file.html. The only place it is mentioned there is the [`allowed-urls`](https://nixos.org/manual/nix/stable/command-ref/conf-file.html#conf-allowed-uris) option, but it doesn't explain it anywhere. The [ [Release 2.0 (2018-02-22)](https://nixos.org/manual/nix/stable/release-notes/rl-2.0.html#release-20-2018-02-22) page also mentions "restricted evaluation mode", but it also doesn't help much.

Found these 2 issues when googling:

* https://github.com/NixOS/nix/issues/1701 (open; no PRs or other issues mention this)
* https://github.com/NixOS/nix/issues/1888 (closed)

  It seems there was a `restrict-eval` option to [`nix-instantiate`](https://nixos.org/manual/nix/stable/command-ref/nix-instantiate.html), but it has been removed since.

Is this mode still relevant? If yes, where can I read more about it? (Someplace other than the source code, that is.)

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open documentation issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/src
[open documentation issues and pull requests]: https://github.com/NixOS/nix/labels/documentation

**Comment by dermetfan** [comment]
Seems this can be closed as there is an explanation of the `restrict-eval` setting in the `nix.conf` docs: https://nixos.org/manual/nix/stable/command-ref/conf-file.html#conf-restrict-eval
