### ISSUE TITLE
nix-store: `error: no operation specified` when operation is not the first parameter (with `--add-root`)

### ISSUE THREAD

**Issue by samueldr** [NixOS/nix#8089]
**Describe the bug**

The `nix-store` command does not work as documented.

I have not investigated deeper than this one specific example.

**Steps To Reproduce**

```
 $ nix-store --add-root --realise [...]
error: no operation specified
Try 'nix-store --help' for more information.

 $ nix-store --realise --add-root [...]
```

**Expected behavior**

To be usable in the same order as documented in the manpage

```
       • --add-root path

         Causes the result of a realisation (--realise and --force-realise) to
         be  registered  as a root of the garbage collector. path will be cre‐
         ated as a symlink  to  the  resulting  store  path.  In  addition,  a
         uniquely  named  symlink  to path will be created in /nix/var/nix/gc‐
         roots/auto/. For instance,

       $ nix-store --add-root /home/eelco/bla/result -r ...
```

**`nix-env --version` output**

```
~ $ nix-env --version
nix-env (Nix) 2.13.3
```

**Additional context**

**Comment by balsoft** [comment]
When calling `nix-store --add-root --realise <...>`, you are trying to add a GC root at a `--realise` _path_. So, `--realise` is interpreted as an argument to `--add-root` and not as a flag. Also, the documentation is correct, since it does provide an argument to `--add-path` (`/home/eelco/bla/result`).

**Comment by samueldr** [comment]
Oh, dang it. I must have been a bit more tired than I expected. It's quite obvious now that my `--realise` arg was not in the same order as the man page.

Sorry for the noise.
