### ISSUE TITLE
Refer to common options to Nix commands consistently

### ISSUE THREAD

**Issue by toraritte** [NixOS/nix#8093]
## Problem

The [`nix-shell` man page](https://nixos.org/manual/nix/stable/command-ref/nix-shell.html) shows `--arg` and `--argstr` in the synopsis that are not mentioned later, and there is an example using the `-I` option that is not in the synopsis. Found these options a while later in the [common options](https://nixos.org/manual/nix/stable/command-ref/opt-common.html) section though, but this was a confusing experience.

After checking the man pages in the [main commands](https://nixos.org/manual/nix/stable/command-ref/main-commands.html) section, `--arg` and `--argstr` are part of the synopses, but not there are options that pop up in the examples that are never explained (another example is the [`nix-build` man page](https://nixos.org/manual/nix/stable/command-ref/nix-build.html) using `-E` in an example).

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open documentation issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/src
[open documentation issues and pull requests]: https://github.com/NixOS/nix/labels/documentation

## Proposal

Either mention all options that are available to a command or link to the [common options](https://nixos.org/manual/nix/stable/command-ref/opt-common.html) section in a note.

(As for `--arg` and `--argstr`, I found [infinisil's examples on the forum](https://discourse.nixos.org/t/what-is-the-point-of-using-nix-shell-with-a-function/8473/4) easier to grasp; probably because it directly answered my question about how to provide a package set as an argument to a `shell.nix` file starting with `{ pkgs ? import <nixpkgs> {}}: ...`.)

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by fricklerhandwerk** [comment]
This is fixed. Common options and environment variables are displayed on every command page.
