### ISSUE TITLE
Rewrite substituters to Store subclasses

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#810]
Cf. BinaryCacheStore currently in Hydra, but propably should be moved to the Nix repo: https://github.com/NixOS/hydra/blob/binary-cache/src/hydra-queue-runner/binary-cache-store.hh

This would allow applying many Nix commands to binary caches, e.g.:

```
$ NIX_REMOTE=https://cache.nixos.org nix-store -qR /nix/store/bh5491qh0ppqb1r8qkw4lrylzh0qydx8-coreutils-8.24
```

Commands like nix-push and nix-copy-closure would become syntactic sugar, e.g.

```
# nix-push
$ nix-store --export $PATH | NIX_REMOTE=file:///tmp/my-binary-cache nix-store --import

# nix-copy-closure --to machine
$ nix-store --export $PATH | NIX_REMOTE=ssh://machine nix-store --import
```

**Comment by edolstra** [comment]
Or with S3BinaryCacheStore, `nix-instantiate` or `hydra-eval-jobs` could put .drvs directly in an S3 bucket:
```
$ NIX_REMOTE=s3://my-binary-cache nix-instantiate -A hello
```

**Comment by shlevy** [comment]
This is already in master, right?

**Comment by domenkozar** [comment]
This is in master, @edolstra let me know if I'm mistaken.
