### ISSUE TITLE
`nix-build` suggests `nix log` (experimental CLI) to view logs

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nix#8118]
**Describe the bug**

`nix-build` will, when a build fails, suggest to run `nix log ...`, which is an experimental CLI.

**Steps To Reproduce**

1. Run `nix-build` on something that fails.
2. `nix-build` will say `...For full logs, run 'nix log /nix/store/hash-name.drv'`.
3. And `nix log /nix/store/hash-name.drv` will fail with `error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override`

**Expected behavior**

The CLI shouldn't suggest to run experimental commands, especially there are stable alternatives (`nix-store -l`).

**`nix-env --version` ->2.11.1** (default Nix in NixOS 22.11)

**Additional context**

https://github.com/NixOS/nix/issues/7701 (CLI stabilization effort)

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by Ericson2314** [comment]
@bjornfor If you want to make a PR with the message conditional one whether `nix-comand` is enabled, that sounds good to me!

**Comment by reivilibre** [comment]
I'm on NixOS 25.05 with Nix 2.28.4 and still having this problem, despite it sounding like it should be fixed.

For other readers: the workaround is to use `nix-store -l` to read logs

**Comment by bjornfor** [comment]
> I'm on NixOS 25.05 with Nix 2.28.4 and still having this problem, despite it sounding like it should be fixed.

Weird. (It works for me, just tested now on NixOS 25.05 with Nix 2.28.5.) Maybe some Nix gurus will know of an edge case where the Nix settings aren't handled correctly?
