### ISSUE TITLE
It’s easy to miss that nix-channel has different contexts

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nix#813]
(copied over from nixpkgs, https://github.com/NixOS/nixpkgs/issues/7113#issuecomment-186664610)
It took me a few hours of head scratching to find out, that nix-channel needs to be called as root to change the system channel. In hindsight that’s obvious, but it seems easy to miss.

I’m aware that this is a nix thing, but it mostly is of concern to NixOS I guess.

How about a message “switched to / added channel foo for user bar”? Since it’s an instant command I think it makes sense to break the rule of silence for that.

**Comment by retrry** [comment]
I had the same problem, when I started using NixOS. Couldn't understand why my nixos-rebuild wasn't updating my system.

**Comment by domenkozar** [comment]
Good thing is, channels are going away with new cli.

**Comment by copumpkin** [comment]
I have yet to see a viable replacement proposal! Curious what will replace them :)

**Comment by 0xABAB** [comment]
Why isn't channel configuration part of `configuration.nix`? It is configuration afterall.

**Comment by eqyiel** [comment]
> Good thing is, channels are going away with new cli.

@domenkozar is this still happening?

**Comment by edolstra** [comment]
Channels will be replaced by flakes, so I'll close this.
