### ISSUE TITLE
nix-build , connot find binary path "No such file or directory" when use shell to build source code

### ISSUE THREAD

**Issue by zongxin1993** [NixOS/nix#8132]
**Describe the bug**

1. I want to use nix-build to build a source code, the code compilation relies on a binary.
2. I use [buildFHSUserEnv] and [mkShell]( builder to try,but "No such file or directory" .

**Steps To Reproduce**

shell script :
![image](https://user-images.githubusercontent.com/36766561/228807722-18433615-6c09-4515-8645-7374d41a244c.png)

nix file:
![image](https://user-images.githubusercontent.com/36766561/228807514-0a911054-63c8-466c-90bc-13b5e4694669.png)

nix-build cmd ：nix-build -K -E 'with import <nixpkgs> {}; callPackage ./Vector.nix {}'

**Expected behavior**

![image](https://user-images.githubusercontent.com/36766561/228809183-949a2f74-fb0c-431f-874b-f50c06f7276f.png)

I tried absolute and relative paths，but they have the same result.
I confirm that this application can operate normally.

**Additional context**

**Priorities**

**Comment by zongxin1993** [comment]
Now, I know why the issue, The binary used must be generated by nix.

**Comment by SuperSandro2000** [comment]
> Why can't I use pre compiled？

Because they are precompiled for another linux distro, that is not NixOS.

> buildFHSUserEnv

I don't think that works inside the nix sandbox.

> No such file or directory

Getting a stray despite that the file exists usually means that the interpreter or shebang does not exist. This can be fixed by using patchelf or patchShebang.
