### ISSUE TITLE
`--installroot` like DNF and Zypper offer

### ISSUE THREAD

**Issue by polarathene** [NixOS/nix#8136]
**Describe the solution you'd like**

A feature like `yum` / `dnf` / `zypper` option `--installroot`, which can create a rootfs with minimal packages and filesystem at given location (instead of the systems actual root `/`).

An example of this [can be seen here in a `Dockerfile`](https://github.com/drwetter/testssl.sh/blob/82fbd8076e7f99dd385c3e9cd259f6bdca936c95/Dockerfile#L10-L15) (_I know nix has a similar feature for producing a docker image among other artifacts, `--installroot` is not specific to Docker_). It is rather straightforward and simple, and was easy to discover.

This avoids anything else on the main install that isn't necessary being included in the install root location (_such as the package manager itself_). The `nixos/nix` docker image by comparison is 550MB+ (somehow 750MB+ at runtime), before installing any packages.

**Describe alternatives you've considered**

- Using the package managers that support the feature.
- Similar nix features (_briefly looked over, there is a lot of noise in docs trying to identify / search for equivalent functionality, as a new user I'd probably need to understand more about nix upfront_)

**Additional context**

Perhaps this already exists in some form. I haven't tried the [Docker image build feature](https://nixos.org/guides/building-and-running-docker-images.html), but I guess that the tarball has the rootfs internally? (_I did [try to experiment with nix via the official docker image](https://www.reddit.com/r/NixOS/comments/127dzuz/why_is_the_minimal_official_docker_nix_image_over/), but got very confused_)

It'd be nice not having to rely on Docker to do that. Or if you do have Docker, and wanted to not rely on nix on the host system, using the nix docker image and mounting a volume could work with the `--installroot` feature, but would be a bit awkward with the docker feature as that'd require Docker-in-Docker to work?

**Comment by SuperSandro2000** [comment]
Nix does not need such workaround because we can build the docker image upfront. See https://github.com/NixOS/nix/blob/master/docker.nix for an example.

> This avoids anything else on the main install that isn't necessary being included in the install root location (_such as the package manager itself_).

You can do that with nix, too. Just exclude nix from the docker image but than obviously no packages can be installed.

> The `nixos/nix` docker image by comparison is 550MB+ (somehow 750MB+ at runtime), before installing any packages.

That's because the downloaded image is uncompressed.
Also the image is meant for CIs thats why it includes the source of nixpkgs it was build with and quite some packages https://github.com/NixOS/nix/blob/master/docker.nix#L14-L31 . A minimal image would not make that much sense for CI if the first task is, to download all the things that where left out. There is probably some improvement there but it would take some digging into it. If you have very specific needs than you are better off building your own docker image that does exactly what you want with nix rather than building on top of the nix Docker image.

**Comment by polarathene** [comment]
> Nix does not need such workaround because we can build the docker image upfront.

> There is probably some improvement there but it would take some digging into it. If you have very specific needs than you are better off building your own docker image that does exactly what you want with nix rather than building on top of the nix Docker image.

This is kind of the point of why I mentioned the `--installroot` method? It works wherever the package manager is available, it's agnostic to Docker which was a benefit that I brought up.

You cannot use nix to build a docker image as easily within a Dockerfile, that'd require Docker-in-Docker + extra dance of getting the final output. Thus you must avoid the Dockerfile with nix and install nix locally.. While I could do that for my own projects, others I contribute to like the `testssl.sh` one I linked before, is not likely to accept that. They're comfortable with `Dockerfile` as are many other developers that would build a Docker image from that, rather than being expected to use nix.

If nix supported `--install-root`, it'd be usable not only in Docker.

---

> That's because the downloaded image is uncompressed.

It's ~180MB compressed on DockerHub for transfer over the network, ~550MB on disk uncompressed.

On my ArchLinux host (with XFS) at runtime `/nix/store` is 644M, but on a Fedora 37 VPS as host (with BTRFS) at runtime `/nix/store` is 744M.

> Also the image is meant for CIs thats why it includes the source of nixpkgs it was build with and quite some packages https://github.com/NixOS/nix/blob/master/docker.nix#L14-L31 
> A minimal image would not make that much sense for CI if the first task is, to download all the things that where left out.

I'm not saying to provide a minimal image, just that it was not expected given the [dependencies listed in the nix docs describing how the image was built](https://nixos.org/manual/nix/stable/installation/installing-docker.html) (_and which `nix-env -q` confirms_):

> The Docker image is also not based on any other image and includes minimal set of runtime dependencies that are required to use Nix:
> 
> ```
> pkgs.nix
> pkgs.bashInteractive
> pkgs.coreutils-full
> pkgs.gnutar
> pkgs.gzip
> pkgs.gnugrep
> pkgs.which
> pkgs.curl
> pkgs.less
> pkgs.wget
> pkgs.man
> pkgs.cacert.out
> pkgs.findutils
> ```

That doesn't mention `git`, which AFAIK was the only dependency I could track to being related to python from `/nix/store` top-level directories. None of the other packages seemed to require python (_based on what I tried following the docs to inspect_). Yet when the `git` package was removed, old generations cleaned up and running the GC, `/nix/store` didn't free up any space (running container).

It was fine if I added packages and removed them afterwards, those would cleanup properly. Perhaps some data is missing?

That said, you've also said that it contains a bunch more for CI usage, so even though I don't have access to gcc or python when running the container, it's there in some manner only accessible to nix? (_sorry the nix docs have a tonne going on to wade through, the docs link regarding the official docker image I provided makes no mention of this, and the [DockerHub README](https://hub.docker.com/r/nixos/nix/dockerfile/) makes no mention about it, instead showing some random outdated alpine example with nix instead of using the `nixos/nix` image?_)

So my confusion probably comes from that, as the info about the image is misleading to someone familiar with Docker but new to Nix.

**Comment by polarathene** [comment]
Closing as value of `--installroot` does not make sense to Nix maintainers.

For docker, it might be of value to you to consider in future to allow doing small image builds all within a Docker build instead of requiring `nix` installed outside of Docker, it would make nix more accessible to experiment with and expose to that community if it can better substitute the usage from other package managers due to the value nix offers elsewhere in package management.

That'd still make the CI image itself fine, as shown in the `testssl.sh` linked example with Zypper, the final image (that gets published to DockerHub) is the desired output. No package manager or other content not necessary to run the project. It ends up being about 60MB (vs 100MB+ base image), a good portion of that is bloat from some packages offering less granularity (`hexdump` + `xxd` needed). I've also used this with 1-2GB CI images to build software that publish 100MB or lower images for users as their final stage.

**Comment by SuperSandro2000** [comment]
> You cannot use nix to build a docker image as easily within a Dockerfile, that'd require Docker-in-Docker +

nix is usually building tarball that you can import into docker, it is not using docker itself.

> Yet when the `git` package was removed, old generations cleaned up and running the GC, `/nix/store` didn't free up any space (running container).

This is how docker works. You cannot regain space by deleting files which where present in previous layers. This is the same with apt.

> No package manager or other content not necessary to run the project.

You can easily build a docker image with nix that does not contain the nix package manager, you just need to write that by yourself.

**Comment by polarathene** [comment]
> nix is usually building tarball that you can import into docker, it is not using docker itself.

My point was that I cannot use `nix` within a Dockerfile to create a minimal system at `/rootfs` like Yum, DNF and Zypper can with `--installroot` correct?

You are saying that I have to use a docker specific feature of nix to build a tarball that is imported into Docker as an image? That contains all the image layers and such?

Or can nix do the equivalent of `--installroot` somehow? Ignore anything Docker related. Is there an agnostic way to create a minimal system at a target location as if it was the filesystem root, and if you don't install `nix` as part of the packages, you get an install with no package manager?

**Comment by polarathene** [comment]
> You can easily build a docker image with nix that does not contain the nix package manager, you just need to write that by yourself.

Okay. I feel that we're going in circles here :)

```Dockerfile
# Initial image with package manager, creates a minimal version without it at /rootfs
FROM opensuse/leap:15.4 AS builder
# The cache is excluded from image layer via cache mount:
RUN --mount=type=cache,target="${CACHE_ZYPPER}",sharing=locked <<EOF
  ZYPPER_OPTIONS=(
    --releasever 15.4
    --installroot /rootfs
    --cache-dir /tmp/cache
  )

  # Sync package repos to get latest updates:
  zypper ${ZYPPER_OPTIONS[@]} --gpg-auto-import-keys refresh

  # Install the packages needed for the project to run:
  zypper ${ZYPPER_OPTIONS[@]} --non-interactive install --download-in-advance --no-recommends \
    bash procps grep gawk sed coreutils busybox-util-linux busybox-vi ldns libidn2-0 socat openssl curl 
EOF


# The final image, only what is needed to run the system with the necessary packages:
FROM scratch
COPY --link --from=builder /rootfs /


# Project specific stuff for the final image:
WORKDIR /home/testssl
RUN --mount=type=bind,from=busybox:latest,source=/bin,target=/bin <<EOF
  /bin/adduser -D -s /bin/bash testssl
  /bin/ln -s /home/testssl/testssl.sh /usr/local/bin/
EOF
# Copy over build context (after filtered by .dockerignore): bin/ etc/ testssl.sh
COPY --chown=testssl:testssl . /home/testssl/
USER testssl
ENTRYPOINT ["testssl.sh"]
CMD ["--help"]
```

If we strip away the noise from that further and just focus on the feature being discussed:

```Dockerfile
FROM opensuse/leap:15.4 AS builder
RUN zypper --non-interactive --releasever 15.4 --installroot /rootfs install \
         bash procps grep gawk sed coreutils busybox-util-linux busybox-vi ldns libidn2-0 socat openssl curl 

FROM scratch
COPY --link --from=builder /rootfs /
```

**I want to highlight how simple that is**. `nix` is not capable of anything like that within a `Dockerfile` is it?

I can do it with `nix` on the host if I want to build a Docker image, but what if I want the same `--installroot` functionality, not a docker image? `--installroot` is agnostic, it does not have anything to do with Docker and I believe was implemented before Docker, it just happened to be a useful feature when building docker images.

Even if I could do this with `nixos/nix`, it would require much more verbose config or steps to achieve? (_especially if your `docker.nix` is anything to go by when it comes to setting up the final image files to copy over, user/group to add and switch to, etc, and this is a simple `Dockerfile` example_).

**Comment by polarathene** [comment]
What I'd like to have is something like:

```Dockerfile
FROM nixos/nix AS builder
# Whatever the appropriate command would be:
RUN nix-env -i --installroot /rootfs \
         bash procps grep gawk sed coreutils busybox-util-linux busybox-vi ldns libidn2-0 socat openssl curl 

FROM scratch
COPY --link --from=builder /rootfs /
```

That would be a great way to make `nix` easier to gain exposure to an audience that'd welcome it if it were that simple to adopt `nix` by new users that fit it into their existing workflows / projects, minimal friction. If they like it, gradually transitioning to adopting nix more broadly for it's many other benefits would be approachable.

I'm kind of surprised that this request was dismissed when the impression I got from `nix` was this is something it should excel at?

It's cool that it can make a OCI image tarball with all the layers and such, but this `--installroot` feature should be even simpler to support since it's agnostic to containers?

**Comment by max-privatevoid** [comment]
You can already do this with `--store`. There's also `nix copy`, which allows you to do the build entirely on the host store, then copy only the runtime closure of the final package to a different place.

https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-copy.html

**Comment by polarathene** [comment]
> You can already do this with `--store`.

This requires `nix` on the final output to be usable right?

I only see `--store` lumped with many other options in the nix docs for various commands and it's vague how to interpret it's purpose / usage. It may be explained better elsewhere but is a bit difficult to search for (_I found [this discussion](https://github.com/NixOS/nix/issues/1971#issuecomment-372542326) though_).

```console
# --store not usable in container by default due to default capabilities (to perform a bind mount?):
$ nix --extra-experimental-features nix-command shell --store /rootfs /nix/store/h25nv98kj46dbsryhdl83lwsb4zyfjzm-ripgrep-13.0.0
error: setting up a private mount namespace: Operation not permitted

# Launches a shell with the `rg` command in scope from a separate store location (via `nix copy`):
nix --extra-experimental-features nix-command shell --eval-store /rootfs /nix/store/h25nv98kj46dbsryhdl83lwsb4zyfjzm-ripgrep-13.0.0

# Alternatively:
nix-shell --packages /rootfs/nix/store/h25nv98kj46dbsryhdl83lwsb4zyfjzm-ripgrep-13.0.0
```

---

> There's also `nix copy`, which allows you to do the build entirely on the host store, then copy only the runtime closure of the final package to a different place.

I've tried that. Apart from larger size, is anything else needed beyond copying over the closure from the store and having nix?

### `nixos/nix`

```bash
nix-env --install ripgrep
nix --extra-experimental-features nix-command copy --to /rootfs $(nix-store --query $(which rg)) --no-check-sigs

# Alternative that seems to copy entire store over (wasn't clear how you meant to use `--store`):
nix-env --store /rootfs --install ripgrep
```

Overview of `/rootfs` from `nix copy` via `dust`:

```
 48M └─┬ rootfs                                                 │█████████████████████ │ 100%
 48M   └─┬ nix                                                  │█████████████████████ │ 100%
 40M     ├─┬ store                                              │░░░██████████████████ │  83%
 30M     │ ├─┬ 4nlgxhb09sdr51nc9hdm8az5b08vzkgx-glibc-2.35-163  │░░░▒▒▒▒██████████████ │  63%
 16M     │ │ ├─┬ share                                          │░░░▒▒▒▒▓▓▓▓▓▓████████ │  34%
 16M     │ │ │ └─┬ i18n                                         │░░░▒▒▒▒▓▓▓▓▓▓████████ │  34%
 12M     │ │ │   ├─┬ locales                                    │░░░▒▒▒▒▓▓▓▓▓▓▓▓██████ │  27%
4.3M     │ │ │   │ ├── cns11643_stroke                          │░░░▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓██ │   9%
3.2M     │ │ │   │ ├── iso14651_t1_common                       │░░░▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓██ │   7%
1.1M     │ │ │   │ ├── iso14651_t1_pinyin                       │░░░▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓█ │   2%
608K     │ │ │   │ └── translit_hangul                          │░░░▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓█ │   1%
3.3M     │ │ │   └─┬ charmaps                                   │░░░▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓██ │   7%
632K     │ │ │     └── GB18030.gz                               │░░░▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓█ │   1%
 13M     │ │ └─┬ lib                                            │░░░▒▒▒▒▓▓▓▓▓▓▓▓██████ │  29%
8.0M     │ │   ├── gconv                                        │░░░▒▒▒▒▓▓▓▓▓▓▓▓▓▓████ │  17%
2.3M     │ │   ├── libc.so.6                                    │░░░▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓█ │   5%
1.0M     │ │   ├── libmvec.so.1                                 │░░░▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓█ │   2%
980K     │ │   └── libm.so.6                                    │░░░▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓█ │   2%
5.7M     │ ├─┬ h25nv98kj46dbsryhdl83lwsb4zyfjzm-ripgrep-13.0.0  │░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒███ │  12%
5.5M     │ │ └─┬ bin                                            │░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒███ │  12%
5.5M     │ │   └── rg                                           │░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒███ │  12%
1.8M     │ ├─┬ cjdm2inq3madwqpnnddi59vv5yd89m52-pcre2-10.40     │░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█ │   4%
1.8M     │ │ └─┬ lib                                            │░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█ │   4%
648K     │ │   ├── libpcre2-8.so.0.11.0                         │░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█ │   1%
588K     │ │   ├── libpcre2-16.so.0.11.0                        │░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█ │   1%
564K     │ │   └── libpcre2-32.so.0.11.0                        │░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█ │   1%
1.7M     │ └─┬ 34xlpp3j3vy7ksn09zh44f1c04w77khf-libunistring-1.0│░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█ │   4%
1.7M     │   └─┬ lib                                            │░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█ │   4%
1.7M     │     └── libunistring.so.2.2.0                        │░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒█ │   4%
8.1M     └─┬ var                                                │░░░░░░░░░░░░░░░░░████ │  17%
8.1M       └─┬ nix                                              │░░░░░░░░░░░░░░░░░████ │  17%
8.1M         └─┬ db                                             │░░░░░░░░░░░░░░░░░████ │  17%
8.0M           └── reserved                                     │░░░░░░░░░░░░░░░░░████ │  17%
```

Looks like if I also use `nix copy` to also add `nix` that size bumps up to `107M`, but that'd only be in the store, requiring more setup to get nix functional from the `/rootfs` content alone.

Probably better to have a minimal environment with nix already, and just copy over the store? How much more weight would that be though, especially when you're only using it to get the runtime environment operational.

---

### `opensuse/leap:15.4`

Nix seems to be capable to build docker images, VMs, bundle appimage, `.deb`, `.rpm`, etc, but no equivalent to an agnostic tree export like `--installroot` shows below?

```bash
zypper --releasever 15.4 --installroot /rootfs install ripgrep
```

```
  14M └─┬ rootfs          │███████████████████████████████████████████████████████████ │ 100%
 8.0M   ├─┬ usr           │                         ██████████████████████████████████ │  56%
 4.4M   │ ├─┬ bin         │                         ░░░░░░░░░░░░░░░███████████████████ │  31%
 3.9M   │ │ └── rg        │                         ░░░░░░░░░░░░░░░▒▒█████████████████ │  28%
 2.7M   │ ├─┬ share       │                         ░░░░░░░░░░░░░░░░░░░░░░████████████ │  19%
 1.0M   │ │ ├── locale    │                         ░░░░░░░░░░░░░░░░░░░░░░▒▒▒▒▒▒▒█████ │   7%
1000K   │ │ ├── man       │                         ░░░░░░░░░░░░░░░░░░░░░░▒▒▒▒▒▒▒█████ │   7%
 520K   │ │ └── help      │                         ░░░░░░░░░░░░░░░░░░░░░░▒▒▒▒▒▒▒▒▒███ │   4%
 684K   │ └─┬ lib         │                         ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░███ │   5%
 564K   │   └─┬ sysimage  │                         ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░███ │   4%
 560K   │     └── rpm     │                         ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░███ │   4%
 4.8M   ├─┬ lib64         │                                      █████████████████████ │  34%
 2.2M   │ ├── libc-2.31.so│                                      ░░░░░░░░░░░██████████ │  16%
 1.4M   │ └── libm-2.31.so│                                      ░░░░░░░░░░░░░░░██████ │  10%
 956K   └─┬ sbin          │                                                       ████ │   7%
 952K     └── ldconfig    │                                                       ████ │   7%
```

---

`--installroot` is nice that way.

Perhaps that doesn't align well with how nix works, it's just something I thought it'd excel at without such limitations. No worries :+1:
