### ISSUE TITLE
add nix-repl to release.nix

### ISSUE THREAD

**Issue by garbas** [NixOS/nix#814]
would it make sense to also ship `nix-repl` (in release.nix)?

many people who i  teach nix find it weird that nix doesn't come with repl OTB, like do haskell(ghc), python, ruby, ...

**Comment by CMCDragonkai** [comment]
+1 nix-repl is very useful for exploring the nixpkgs ecosystem

**Comment by copumpkin** [comment]
:+1: I could swear we had a ticket elsewhere for this, but I can't find it now.

**Comment by peti** [comment]
The repl is now  a part of Nix itself.
