### ISSUE TITLE
Mark experimental configuration settings programmatically

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/nix#8162]
## Problem

Descriptions of experimental settings need the information on "experimentality" baked into the documentation, but this is double book keeping.

Example: https://github.com/NixOS/nix/blob/d93c1514ebcf71390c8a8070759487e5a40dcc6f/src/libstore/globals.hh#L351-L359

Given we merge https://github.com/NixOS/nix/pull/7798, that information can be displayed automatically, and removed without maintainer intervention if the feature becomes stable. It would also allow more convenient control over presentation, ensuring it will be consistent.

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/src
[open documentation issues and pull requests]: https://github.com/NixOS/nix/labels/documentation

## Proposal

- merge https://github.com/NixOS/nix/pull/7798
- adapt the [rendering helper for settings](https://github.com/NixOS/nix/blob/d93c1514ebcf71390c8a8070759487e5a40dcc6f/doc/manual/utils.nix#L42-L59) and the code outputting the structured data it works on accordingly

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open documentation issues and pull requests] for possible duplicates

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by Ericson2314** [comment]
Whoever does this, please feel free to talk to me!

- In aa663b7e89d3d02248d37ee9f68b52770b247018 (already merged) I added the basic infrastructure to track this info on settings
- https://github.com/NixOS/nix/pull/7798 is now adapted so experimental features have `xp-feature-${name}` anchors, ready to be linked from elsewhere.

Between those too, this ought to be fairly straight-forward.
