### ISSUE TITLE
Can't use nix on Void

### ISSUE THREAD

**Issue by niels0n** [NixOS/nix#8245]
After I installed nix through Void's package manager, I added the unstable channel, updated it and then installed some software through nix-env.
Whenever I try to run them (no matter which, it happens on all the packages I installed) I get `error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory`.
So I uninstalled nix and tried to install it through the official installation script, but I get the same error during the installation (`/nix/store/556bgbl9z8jm7030g1b31d0cblf09036-nix-2.15.0/bin/nix-store: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory
/tmp/nix-binary-tarball-unpack.YZaVNx9ZYV/unpack/nix-2.15.0-x86_64-linux/install: unable to register valid paths`).
Note that I do have libX11 installed, I tried with libX11-devel too but nothing changes. I had nix on a previous Void installation and this worked fine without any additional tweak.  I really can't understand where the problem is.

**Steps To Reproduce**

1. Install nix, enable nix-daemon, add and update channel
2. Install some software
3. Run any nix-software
4. See error `error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory`

**Expected behavior**

Software runs fine, like on my previous installation.

nix-env (Nix) 2.11.0

**Comment by Kha** [comment]
The nix binary certainly does not depend on libX11 (which you can check with `ldd`), so you likely have a problematic `LD_PRELOAD` setting or similar https://github.com/NixOS/nix/issues/1726#issuecomment-351093690

**Comment by niels0n** [comment]
Okay, I read theissue you linked and setting LD_PRELOAD=/usr/lib did work for launching a software but then it began throws me other libraries-related errors.
Could you help me to fix my LD_PRELOAD? I never used it so I'm really not understanding how it worked on previous installation andit's not working here, since I have never touched anything related to this before...

**Comment by Kha** [comment]
You should not have `LD_PRELOAD` set at all unless you know exactly what you are doing. You can use `unset LD_PRELOAD` to fix it in your current shell, but for a permanent fix you will have to find out where it comes from and deactivate it there.

**Comment by niels0n** [comment]
Yeah, with `unset LD_PRELOAD` it works...that's odd.
Do you have any idea where could I start to find out where's the problem?
I'd really appreciate a suggestion since I have no idea

**Comment by Kha** [comment]
I've never encountered this issue myself, but it is likely from some shell setup code either in your home or in `/etc`. You could try running an interactive login shell with debug tracing as in `bash -ilx` and see whether it mentions `LD_PRELOAD` and ideally even the file it was sourced from.

**Comment by niels0n** [comment]
Okay I'll try to understand, thank you so much anyway.
