### ISSUE TITLE
nix print-dev-env expects shellHook to exist

### ISSUE THREAD

**Issue by dsilvasc** [NixOS/nix#8253]
**Describe the bug**

If you have a problem with a specific package or NixOS,
you probably want to file an issue at https://github.com/NixOS/nixpkgs/issues. 

`nix print-dev-env` prints shell code that ends with `eval "$shellHook"`.  If the flake installable has no `shellHook` defined, then sourcing or evaluating that shell code fails with `shellHook: unbound variable`.

`nix-direnv` does this in https://github.com/nix-community/nix-direnv/blob/0dbdee467917aa9cfea0776ceff54210ec5f77f7/direnvrc#L207-L209

**Steps To Reproduce**

1. create a flake with an output package without a shellHook
2. install direnv and nix-direnv
3. add `use flake` to the `.envrc` in the same directory as `flake.nix`.
4. `direnv allow`
5. See error

**Expected behavior**

No error.

**`nix-env --version` output**

```
nix-env (Nix) 2.12.0
```

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by rvl** [comment]
This is a dup of issue #7951 and should be fixed by PR #9930.
