### ISSUE TITLE
Undeprecate `isNull`

### ISSUE THREAD

**Issue by infinisil** [NixOS/nix#8264]
In the manual, [`isNull` is marked as deprecated](https://nixos.org/manual/nix/stable/language/builtins.html?highlight=isNull#builtins-isNull) since 3837fb233cccc8f65629749f07820afba04952a0 (2006) by @edolstra:

> This function is deprecated; just write `e == null` instead.

For consistency reasons, I don't think this function should be deprecated, because currently there's a `builtins.is*` function for every value returned from `builtins.typeOf`:

```nix
builtins.typeOf 0
-> "int"
builtins.isInt 0
-> true

builtins.typeOf {}
-> "set"
builtins.isAttrs {} # An unrelated naming inconsistency here
-> true

builtins.typeOf (x: x)
-> "lambda"
builtins.isFunction (x: x) # An unrelated naming inconsistency here
-> true

builtins.typeOf null      
-> "null"
builtins.isNull null
-> true
```

It also doesn't cost anything to keep the function there, the implementation is trivial.

In addition it does cost something to deprecate this, Nixpkgs already went through the effort of trying to get rid of `isNull` in https://github.com/NixOS/nixpkgs/pull/219747, yet there's [already new uses committed](https://github.com/search?q=repo%3ANixOS%2Fnixpkgs+isNull+language%3ANix&type=code&l=Nix).

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by SuperSandro2000** [comment]
isNull is the only of those functions which can be replaced with a single boolean condition and using ``!isNull`` can be rather confusing, eg ``lib.mkIf (!(isNull cfg.sshKeyFile))``

**Comment by roberth** [comment]
I think you're both right.
How about we demote it to a recommendation:

Keep it simple; write `e == null` instead. `isNull` is ok to use as an argument to higher order functions.

**Comment by infinisil** [comment]
Opened a PR to undeprecate it: https://github.com/NixOS/nix/pull/9645
