### ISSUE TITLE
emacs nix-mode: pasting stuff indents wrong

### ISSUE THREAD

**Issue by Profpatsch** [NixOS/nix#828]
Every time I try to insert a block of code with nix-mode enabled, it indents each consecutive line by two spaces, and it’s driving me crazy.

```nix
  isso = rec {
      port = "8080";
          config = ''
                [server]
                      listen = http://localhost:${port}
                          '';
```

whaaaaa

**Comment by domenkozar** [comment]
cc @ttuegel @rycee @pSub (contributors to the nix-mode.el).

**Comment by Profpatsch** [comment]
I’d fix it myself, if I had any clue what causes it.

**Comment by Ericson2314** [comment]
In light of @domenkozar's doing its work manually, can we get the mention bot for this repo? I really like it in nixpkgs.

**Comment by rqcy** [comment]
For reference: calling `indent-region` causes the same problem.

**Comment by rqcy** [comment]
I might have found a good hint.

Normally in Emacs, RET inserts new line without indenting it and C-j inserts new line with proper indentation. It seems to be the other way around in nix-mode.

**Comment by rycee** [comment]
Are you using Emacs in a terminal or the GUI version? For me pasting works OK in the (GTK) GUI but when running Emacs in a terminal (gnome-terminal) it does indeed show the "staggered indent" issue. Disabling `electric-indent-mode` makes the indentation look OK in the terminal as well.

**Comment by jb55** [comment]
This fixes it for spacemacs users:

```elisp
(defun dotspacemacs/user-config ()
  (setq spacemacs-indent-sensitive-modes (add-to-list 'spacemacs-indent-sensitive-modes 'nix-mode)))
```

**Comment by Profpatsch** [comment]
> This fixes it for spacemacs users:

Nice, so it was an interference from emacs. We should include it in the nix/nixos layer.

**Comment by Profpatsch** [comment]
Patch is upstream.

**Comment by Ericson2314** [comment]
I'm still interested in what's https://github.com/NixOS/nix/issues/828#issuecomment-240699341 spacemacs is about. Is this list quite big, or is this a hack to tell spacemacs to back of fragile modes?

**Comment by jb55** [comment]
> @Ericson2314: Is this list quite big?

```
(nix-mode coffee-mode elm-mode haml-mode haskell-mode slim-mode makefile-mode makefile-bsdmake-mode makefile-gmake-mode makefile-imake-mode python-mode yaml-mode)
```

>  or is this a hack to tell spacemacs to back off fragile modes?

looks like it

**Comment by Profpatsch** [comment]
Yeah, it looks like spacemacs overrides the default emacs behaviour to make it work better with vim-style editing. If a mode does something special that sometimes interferes.

There is also a todo to put the definition of the list into the actual modules, my patch does that for nixos.
