### ISSUE TITLE
nix-env: NIXPKGS_CONFIG environment variable is missing from man page

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nix#829]
https://nixos.org/wiki/Nix_Modifying_Packages -

> When Nix evaluates the NixPkgs Nix expression, it will also evaluate the file located at the `~/.nixpkgs/config.nix` path and combine it with the default NixPkgs expression. If we want to use a different file, specify a file path in the `NIXPKGS_CONFIG` environment variable and Nix will instead use that one.

This indeed seems to be true, but `NIXPKGS_CONFIG` is not mentioned at all in the man page for `nix-env`.

**Comment by vrthra** [comment]
This seems to have been removed see [this](https://marc.info/?l=nix-dev&m=139641579914113&w=3)

**Comment by Ericson2314** [comment]
Nope definitely still around https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/impure.nix#L13

**Comment by vrthra** [comment]
That is interesting. I hope it does not go away, it is really important to have this facility where home directory is exported in heterogenous environments.

**Comment by chris-martin** [comment]
Yeah, I don't know how I'd use nix without it.

**Comment by Ericson2314** [comment]
I don't think anyone planning on removing it. I separated it from other stuff both for clarity and because on servers (or anything where nobody logs on), it might be counterproductive. Note that you can already call nixpkgs with a config argument directly, though none of the tools make that very ergonomic.

**Comment by toraritte** [comment]
Related: https://github.com/NixOS/nixpkgs/issues/28085 (@michaelpj also linked [where it is defined](https://github.com/NixOS/nixpkgs/blob/dd050270c78a0e214ed7cb9e25bae43b45406473/nixos/modules/programs/environment.nix#L20))

**Comment by edolstra** [comment]
This is more of a Nixpkgs feature than a Nix feature so it should be documented in the Nixpkgs manual. 

It's also worth noting that access to environment variables doesn't work in pure evaluation mode (which is the default in the `nix` command on the flakes branch) so use of `NIXPKGS_CONFIG` should probably be considered deprecated.
