### ISSUE TITLE
Could nix-daemon listen to a tcp socket and nix-env use it?

### ISSUE THREAD

**Issue by bzizou** [NixOS/nix#830]
I'm using NIX on an HPC cluster, in a multiusers context. We have 2 login nodes on which users can log alternatively thanks to a round-robin DNS declaration. Home directories and /nix are shared with an NFS mount.  My users can only do nix-env operations on the login node that is running the NIX daemon.
It would be very useful if the users could do nix-env operations from both login nodes and in my mind it would be sufficient that the nix-daemon could be able to listen on a TCP socket instead of a Unix socket. The NIX_REMOTE variable could contain something like "<remote_host>:<port>" instead of the keyword "daemon" to tell to nix-env which socket to use.
Is it doable? (unfortunately, I'm not a C++ developer...)

OR something I didn't try: is it safe to run 2 nix-daemon, one on each login host?

**Comment by edolstra** [comment]
In itself this is pretty easy to implement, but it opens up the much harder problem of authentication and possibly encryption.

**Comment by bzizou** [comment]
Great! I'll try that with socat and tell you if it works. Thanx!

**Comment by bzizou** [comment]
It works! Thanks!
For the record, here's my simple solution (with no ssl, on a trusted local network)
- On the host which is running nix-daemon (and sharing /nix over NFS):
  - stop nix-daemon
  - delete the directory /nix/var/nix/daemon-socket:    `rm -rf  /nix/var/nix/daemon-socket`
  - create a symlink /nix/var/nix/daemon-socket to something local :    `mkdir /var/run/nix && ln -s /var/run/nix /nix/var/nix/daemon-socket`
  - start nix-daemon
  - start socat listening to forward the socket: 

  `socat TCP-LISTEN:4325,bind=172.28.0.2,reuseaddr,fork,range=172.28.0.0/24 UNIX-CLIENT:/var/run/nix/socket`
- On the other host:

  `mkdir /var/run/nix`
  `socat unix-listen:/var/run/nix/socket,mode=666,fork tcp-connect:172.28.0.2:4325`

**Comment by Ericson2314** [comment]
https://github.com/NixOS/nix/pull/5265 would help with this.
