### ISSUE TITLE
Cross compilation of Rust not working on macOS

### ISSUE THREAD

**Issue by alper** [NixOS/nix#8302]
I found [this quote](https://nix.dev/tutorials/cross-compilation):

> The nixpkgs package collection has world-class support for cross compilation

So I'm trying with a very simple crane cross compilation example as found here to compile from my `aarch64-apple-darwin` to `aarch64-unknown-linux-gnu`: https://crane.dev/examples/cross-rust-overlay.html

But it won't work. Removing all cross-compilation bits from the flake, makes it build correctly.

The general consensus seems to be that cross-compilation is a bad idea and I should get a compatible target VM to compile in, but then what's the point of Nix? If I'm getting a VM anyway, I can just rustup the right version of rust in there and be done.

Here's the feature request:

I want one flake that with those hash selectors can build:

default: the Rust project to run on my M1 Macbook
docker-local: the same Rust project built to a container that runs on my machine
docker-cloud: the same Rust project built to a container that runs on a public cloud

If this is impossible, I'd like some clarity on that.

**Comment by alper** [comment]
The detailed issue at Crane: https://github.com/ipetkov/crane/issues/320

**Comment by SuperSandro2000** [comment]
@fricklerhandwerk please move to nixpkgs

**Comment by alyssais** [comment]
> please move to nixpkgs

This isn't a Nixpkgs issue.  It's a flakes feature request, although the lede is buried.

> The general consensus seems to be that cross-compilation is a bad idea

FWIW: this is far from the general consensus, and we have good support for cross-compilation in Nixpkgs.  I suspect some of your issue getting it to work comes from not using Nixpkgs, because now to get help you need to find somebody knowledgeable about both cross-compilation and crane.  You might find it easier to get started using Nixpkgs' own Rust stuff, which generally handles cross-compilation well, although I'm not sure about Darwin->Linux specifically.

**Comment by SuperSandro2000** [comment]
> The general consensus seems to be that cross-compilation is a bad idea and I should get a compatible target VM to compile in, but then what's the point of Nix?

Yes, if you can compile native, that is easier to use but you cannot always do that where cross compilation comes into play. Nix can do that rather clean compared to eg Debian.

> If I'm getting a VM anyway, I can just rustup the right version of rust in there and be done.

Sure

> Here's the feature request:

You can already do that easily, so this is not a feature request but a help request which is better questioned on https//discourse.nixos.org/ or the matrix chat.

**Comment by alyssais** [comment]
> > Here's the feature request:
> 
> You can already do that easily, so this is not a feature request but a help request which is better questioned on https://discourse.nixos.org/ or the matrix chat.

They already have a Discourse [thread](https://discourse.nixos.org/t/cross-compile-rust-from-m1/27879/5), fwiw.
