### ISSUE TITLE
AST library to let nix frontend reusable (for format, lsp, tooling, ... etc)

### ISSUE THREAD

**Issue by inclyc** [NixOS/nix#8304]
## Rationale

**Nix** language is becoming more and more popular and we need formatting & linting for source code quality. However, looks like many external projects that manipulate nix source code re-implemented Nix language frontend again (e.g. [rnix](https://github.com/nix-community/rnix-lsp/blob/master/src/parse.rs) [nil](https://github.com/oxalica/nil/blob/main/crates/syntax/src/parser.rs)). 

As mentioned above, many language services of nix are based on writing a set of "frontends". It might be a problem as far as I'm concerned about:

1. If we change the syntax (e.g. add more language features), language services are not updated simultaneously.
2. Currently, language services may "think" some nix code are correct, but cannot parsed by `nix` commands (due to different implementations).
3. Diagnostics & error handling: if we add some feature to LSP codes that diagnoses nix source code nicely, can we give the same result in the command line?

## The solution might resolve this issue

We can provide a library external projects could reuse the nix AST. Currently, the C/C++ frontend `clang` achieved this by providing a abstraction called `ASTFrontendAction`. Plugins & standalone tools are implementations of `FrontendAction`s that manipulate ASTs. Can we do the same thing in nix? `nix` command itself can be an "official" `ASTConsumer` that produce derivations, etc.

CC list:

nix code owner: @edolstra 
rnix-lsp contributors: @jD91mZM2 @Ma27
nil owner: @oxalica
nixpkgs-fmt maintainer: @zimbatm

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by oxalica** [comment]
This seems not possible for current nix code.

Nix bundles parsing and lowering together, you cannot get the exact same tree: spaces and comments are lost, many syntax is desugared, even name resolution is eagerly done during parsing and you'll get parse errors instead of an individual name-resolution errors. You can play with `nix-instantiate --parse` to parse and print the reconstructed code.

```
$ nix-instantiate --parse --expr '<nixpkgs>'
(__findFile __nixPath "nixpkgs")

$ nix-instantiate --parse --expr '1 >= 2'
(! (__lessThan 1 2))

$ nix-instantiate --parse --expr '{ a.b = 1; a.c = 2; }'
{ a = { b = 1; c = 2; }; }

$ nix-instantiate --parse --expr 'let a = 1; in b'
error: undefined variable 'b'

       at «string»:1:15:

            1| let a = 1; in b
             |               ^
```

These "features" simplifies nix implementation and could speed up evaluation. But they are incompatible with scenarios like AST-editting (preserve untouched texts) or language servers (accept incomplete code at best effort). It may be hard to balance the two very different goals in a single frontend library.

**Comment by inclyc** [comment]
> Nix bundles parsing and lowering together, you cannot get the exact same tree: spaces and comments are lost, many syntax is desugared, even name resolution is eagerly done during parsing and you'll get parse errors instead of an individual name-resolution errors.

FWIW, clang removes spaces and comments, but preserve the source location to do source-editing. It's a common thing to remove unnecessary information while constructing AST and do name-resolution. I think this does not conflict with the goal?

> It may be hard to balance the two very different goals in a single frontend library.

In compiler/engineering practice, is error handling an overhead to do parsing? Looks like currently we have generated parser in NixOS/nix evaluator, maybe it's hard to write error handling logic.

**Comment by inclyc** [comment]
> language servers and AST-editting want to keep comments as-is.

Why do we need to preserve comments instead of source locations of AST nodes? IIRC clangd does not care about comments.
