### ISSUE TITLE
The documentation for plain path flakerefs (`/foo` or `./foo`) isn't correct

### ISSUE THREAD

**Issue by thufschmitt** [NixOS/nix#8308]
## Problem

The documentation on Flakes treats the flakeref `/foo/bar` as just a shorthand for `path:/foo/bar` ([here](https://nixos.org/manual/nix/unstable/command-ref/new-cli/nix3-flake.html#types)). This is however wrong for a number of (important) reasons:

- The plain path syntax has a mechanism (similar to `git`) to search upwards for the actual flake root. So if we have the following directory tree:
    ```
    /foo
      |_ flake.nix
      |_ bar/
    ```
    Then the flakeref `/foo/bar` will be equivalent to `/foo` (which is the path containing the `flake.nix` file).

- The plain path syntax also auto-detects `git` repositories, so that if `/foo/bar` is part of a git worktree, then it will be interpreted as a `git+file:` url and not a `path:` one (with also some magic to detect shallow git repositories and handle them properly).
- Once https://github.com/NixOS/nix/pull/6614 gets merged, they will also behave differently with respect to percent encoding  (`./foo bar` vs `path:./foo%20bar`)

## Checklist

- [ ] checked [latest Nix manual] \([source])
- [ ] checked [open documentation issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/src
[open documentation issues and pull requests]: https://github.com/NixOS/nix/labels/documentation

## Proposal

Document these in their own subsection that properly details their semantic

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by iFreilicht** [comment]
Wasn't this fixed by #9237?

**Comment by thufschmitt** [comment]
It is fixed indeed

![image](https://github.com/NixOS/nix/assets/7226587/9248dd76-7f4e-4307-87ae-2411b1a1332b)

Thanks for noticing that :)
