### ISSUE TITLE
Remove nix-install-package

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#831]
This command is not very useful anymore:

```
$ nix-install-package --url http://blabla
```

is not really easier than

```
$ nix-env -i /nix/store/blabla --option binary-caches http://...
```

**Comment by vcunat** [comment]
Currently our Hydra instance still generates `nix-install-package` links, so that should be converted first.

**Comment by bjornfor** [comment]
Hm, the second command looks longer and more difficult to remember. (Probably doesn't matter now, the new Nix UI will probably clean things up a bit :-))

**Comment by vcunat** [comment]
@bjornfor: normally you shouldn't need to specify the `--option binary-caches ...` part. (I mean the case when you have a setup that uses cache.nixos.org and you want to pull things from there, e.g. those built by hydra.nixos.org.)

**Comment by domenkozar** [comment]
Essentially this needs:

- new instructions for Hydra ([there's a Hydra bug saying some problems with it](https://github.com/NixOS/hydra/issues/268))

- deprecation/removal of nix-install-package
