### ISSUE TITLE
#8018 broke SSH usage with `ControlMaster` and `ControlPersist`

### ISSUE THREAD

**Issue by max-privatevoid** [NixOS/nix#8329]
**Describe the bug**

#8018 introduced a clever trick with `LocalCommand` to check if an SSH connection has been established. When using `ControlMaster`, `LocalCommand` is only executed on the initial connection, so Nix gets stuck on every further connection to the same host that occurs while the original connection is still open.

**Steps To Reproduce**

1. Have an `ssh_config` with something like this in it
```
Host *
  ControlMaster auto
  ControlPath ~/.ssh/muxctl:%h:%p:%r
  ControlPersist 15m
```
2. Run a copy command: `nix copy nixpkgs#hello --to ssh-ng://vegas`, it finishes successfully
3. Run the same command again, and observe: It's stuck forever

This also works with `ssh://`.

**Expected behavior**

Nix should be able to deal with `ControlMaster`. Maybe make it consider the `started` message optional and also make `nix-daemon --stdio` send a different readiness message to indicate that the remote daemon process is now running?

**`nix-env --version` output**

```
nix-env (Nix) 2.16.0pre20230512_916da45
```

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by balsoft** [comment]
I think the cleanest solution would be to make Nix always use a ControlMaster, and have the first connection to any given host be `ssh <host> echo started`, and after that run the daemon using a separate command. This would probably require some refactoring.

**Comment by balsoft** [comment]
Hm, indeed if the shell is not allowed to run this is a problem.
