### ISSUE TITLE
Default arguments not applied to as-patterns

### ISSUE THREAD

**Issue by endgame** [NixOS/nix#8344]
```
nix-repl> let f = args@{foo ? "hello"}:args; in f {}
{ }
```

I would have expected it to return `{ foo = "hello"; }`, is this intentional?

```
$ nix --version
nix (Nix) 2.16.0pre20230516_8976769
```

**Comment by thufschmitt** [comment]
Yes it is (documented [here](https://nixos.org/manual/nix/stable/language/constructs.html#:~:text=The%20args%40%20expression%20is%20bound%20to%20the%20argument%20passed%20to%20the%20function)). I'm not sure why it's that way (although I can see why it can make sense), but it's probably not something that we'll change now.
