### ISSUE TITLE
evaluation stalls sometimes

### ISSUE THREAD

**Issue by NobbZ** [NixOS/nix#8345]
**Describe the bug**

`nix build`, `nix shell`, tab-completion for ZSH, `nix run`, etc stale. Most of these stale with the last line being printed like this:

```text
$ nix shell nixpkgs\#gnome.simple-scan -c simple-scan
evaluating derivation 'flake:nixpkgs#gnome.simple-scan'
```

The output seems to be getting updated/redrawn, as selecting is not possible, and a `^C` printed when I hit Ctrl-C to cancel disappears quickly.

Also using Ctrl-C can not cancel the evaluation. A `kill -9` is required.

**Steps To Reproduce**

Not clear, but seems to be related to evaluation of things not in the store. I can **not** describe it better.

**Expected behavior**

Evaluation and cancelling it properly succeed.

**`nix-env --version` output**

works without any problems: `nix (Nix) 2.16.0pre20230513_29db89f`

Problem occured with:
* 454e27345125736a2c44282e4b31a8f325b754e7
* f8a6a9e47314acebea2d72c0ec195360eb58bbec

**Additional context**

As I have no clear reproducer, I have not yet been able to properly bisect the issue. I reported commits from the lockfiles that have the problem in question.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by thufschmitt** [comment]
The symptoms look like what happens when Nix is dumping a big path into the store. Could that be the case in your example?

**Comment by NobbZ** [comment]
No. Same command at same location (always flake based) worked with the older base point.

Though I today found, that my nix version still was built with a patch I experimented with, but forgot to remove it when I didn't need it anymore.

As I so far have been unable to reproduce the issue with a nix built from repo directly, and the problem didn't occur again since I removed that patch, I will wait for another 2 days (and updates) before closing or giving further information.

**Comment by roberth** [comment]
I've noticed that nix may redraw excessively, at least on a slightly older version like 2.11. Multiple megabytes of progress bar output for a fairly simple, fairly short lived command. You could run nix in `script` to record all bytes printed to the terminal. A newer version did not _seem_ to suffer from the problem, but that might have been a coincidence as far as I know; possible other factors could include not having to download or build certain things again.

**Comment by NobbZ** [comment]
I didn't have the problem again after removing the experimental patch of mine.

I think we can close this issue.

Thanks for your inputs everyone!
