### ISSUE TITLE
A config that lets you list certain system wide packages that will prevent you from accidentally uninstalling them

### ISSUE THREAD

**Issue by dnkmmr69420** [NixOS/nix#8367]
**Is your feature request related to a problem? Please describe.**
There are times I almost broke nix by typing things like `sudo nix profile remove '.*'` and `sudo nix profile remove 0`. There should be a part of `/etc/nix/nix.conf` where you can list packages that you are unable to uninstall unless you remove them from the config. There should be something like that in `~/.config/nix/nix.conf` but for user wide packages instead

**Describe the solution you'd like**
The solution was described above

**Describe alternatives you've considered**
Nix could be packaged as an RPM and be hosted on copr

**Additional context**
This should happen because it is easy to accidently uninstall something important such as nix itself. This is also for the nix package manager on non NixOS systems.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by Ericson2314** [comment]
https://github.com/NixOS/nix/issues/8361#issuecomment-1551995895 mirrored my thought. There are two layers to this:

1. Deleting profiles / profile generations
2. Removing store paths from the store

Both could perhaps have some sort of extra "please keep" safety mechanism that you described, but they are quite different.

Also, arguably the simplest and best solution is to simply not make the installer insist and wiping out the old installation first! :/

**Comment by dnkmmr69420** [comment]
I am gonna close this since I discovered that profiles can be anyware on nix
