### ISSUE TITLE
nix-channel is flaky and fails if native curl version is too old

### ISSUE THREAD

**Issue by adevress** [NixOS/nix#837]
nix-channel uses the native curl tool instead of the "nix packaged/included" curl for its operations.

This is flaky, and cause side effects if the native curl version is too old for nix-channel.

This is for instance the case on RHEL6 where curl do not support the formating option  ( -write_out ) "filename_effective" and cause any channel update to fail.

It would be more reliable if nix-channel uses the nix's curl or directly nix fetchTarball for this purpose.

> curl: unknown --write-out variable: 'filename_effective'
> Use of uninitialized value $filename in concatenation (.) or string at /home/didi/channel line 119.
> Use of uninitialized value $filename in pattern match (m//) at /home/didi/channel line 119.

**Comment by domenkozar** [comment]
cc @edolstra

**Comment by edolstra** [comment]
Presumably this problem will go away once nix-channel is rewritten in C++.

**Comment by domenkozar** [comment]
cc @shlevy

**Comment by adevress** [comment]
@edolstra  @domenkozar I am a C++ dev.

I can help you with that guys if you can brief me on what's your current roadmap and plan for this.

**Comment by domenkozar** [comment]
@adevress best to read through https://github.com/NixOS/nix/issues/341 and sync up with @shlevy what's best to tackle next.

**Comment by edolstra** [comment]
Closing since we're not calling external curl anymore.
