### ISSUE TITLE
Lazy evaluation of `replaceStrings` replacements

### ISSUE THREAD

**Issue by nagy** [NixOS/nix#8372]
**Is your feature request related to a problem? Please describe.**
This is not a problem, it is an optimization opportunity. When using `builtins.replaceStrings` , the replacement should only be evaluated when the replacee exists in the string. Sometimes the replacement can be very expensive to calculate and if it is not used at all, then there is no need to calculate/evaluate it. Currently:

```
nix-repl> builtins.replaceStrings ["abc"] [ (throw "evaluated")] "foobar"
error: evaluated
```

**Describe the solution you'd like**
The above should look like this:

```
nix-repl> builtins.replaceStrings ["abc"] [ (throw "evaluated")] "foobar"
"foobar"
```

**Describe alternatives you've considered**
None.

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by roberth** [comment]
You could do this in `prim_replaceStrings`

```diff
-    std::vector<std::pair<std::string, NixStringContext>> to;
+    Value * * to;
```

`to` can be initialized with `listElems()` but needs type and size checking. Use `forceString` in the loop.
