### ISSUE TITLE
"interpretation of store paths arguments" warning gives ! syntax, seems to mean ^ syntax

### ISSUE THREAD

**Issue by elaforge** [NixOS/nix#8378]
In nix 2.15.0, if I do `nix derivation show /nix/store/xyz.drv`, I get a warning like "interpretation of store paths arguments ending in `.drv` recently changed.  If this command is now failing tray again with '/nix/store/xyz.drv!*"

The grammar is a bit wonky ("store path arguments" I think), but the recommended `!*` syntax seems incorrect.  From reading release notes it seems to have changed to `^*`.  If I use the ! syntax as recommended, I get one of those "does not contain a flake" and then "no such file or directory", whereas `^*` works as intended with no warning.

Has the old DerivedPath `!` syntax been changed globally?  Is it also changed in the wire protocol?  Or is there a difference between `^` and `!`?  If it was recently changed, there may be many other places in code and documents that use the old ! syntax.

**Comment by Ericson2314** [comment]
There was a cherry pick to the 2.15 branch to change the message. Did we not cut another 2.15.x release?

The ! Syntax has *not* been changed globally. That would indeed be invasive :). The old CLI and both protocols have not been affected by this change.

**Comment by elaforge** [comment]
Maybe not!  I just got this from the OS X nix I got from the multiuser install at https://nixos.org/download.html

**Comment by Ericson2314** [comment]
OK thanks for letting me know. @NixOS/nix-team what do we do to release a 2.15.1?

**Comment by fricklerhandwerk** [comment]
@Ericson2314 Follow (and if needed update/clarify) the [release procedure](https://github.com/NixOS/nix/blob/master/maintainers/release-process.md).

**Comment by elaforge** [comment]
On this subject, is there an intent to globally move from ! to ^?  Or do they mean different things and ^ is clarifying a conflation?  Otherwise, is ^ better than ! due to.. some reason?  Is there a document or RFC around?  The release notes mention it but don't have any explanation.  Also, I take it `^*` is the official syntax for "all the output paths".  I noticed from the source that `!*` is used in the internal protocol to e.g. ask queryMissing for all outputs, but of course that's different from UI, and is also different from the UI notion of an "installable."

I ask because I'm implementing non-default output addressing, and I could use any character, but I'd rather use whatever is consistent with what nix is using going forward.  Also just curious about nix's design decisions going forward.

**Comment by roberth** [comment]
I'm not actually clear on that either, though I would like to add that for anything that's not just a derivation store path, you're better of using attribute notation (e.g. `pkg.bin`), which uses actual attributes in the language, which gives a bit more flexibility on the expression author's end to start making use of RFC 92 dynamic derivations (when implemented) or use a separate derivation for the documentation of the package.

**Comment by elaforge** [comment]
Inside the nix language, indeed outputs are addressed with dot and there is no operator ! or ^ or *.   Outside nix, dots are already used in store path names, so they would be ambiguous, e.g. someone requests to build /nix/store/$hash-a.drv.drv.drv.  Inside the nix language it's actually ambiguous too, but nix merges everything into the drv namespace, so outputs probably just overwrite any other fields with the same name.

RFC 92 is interesting, but not sure how it's related.  It's suggesting ! to address outs, which I assume will be updated to ^.  I assume but don't know, that's what I'm asking here!

**Comment by roberth** [comment]
> It's suggesting ! to address outs

We don't update RFCs. They're point-in-time process document things, which is fine, but almost all of them _should_ be made completely obsolete by proper documentation, which for non-trivial Nix features should be a design document if not an actual implementation.

**Comment by fricklerhandwerk** [comment]
This was [backported to 2.15.1](https://github.com/NixOS/nix/pull/8221). [Diff between 2.15.0 and 2.15.1](https://github.com/NixOS/nix/commit/80afafdbd4c94a91e77d8b224cb6eccd5c7b1950)
