### ISSUE TITLE
pre-commit hook

### ISSUE THREAD

**Issue by Freed-Wu** [NixOS/nix#8380]
**Describe the solution you'd like**

Can this project provide a `.pre-commit-hooks.yaml` for [pre-commit](https://pre-commit.com/) to allow user `nix flake check`?

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by SuperSandro2000** [comment]
Shouldn't pre-commit-hooks be fast running commands? ``nix flake check`` can take a few minutes to execute.
