### ISSUE TITLE
Nix can't build anymore since `e31d9b910dcebd77028f5d4351e2cc7205baa321` due to failing tests

### ISSUE THREAD

**Issue by NobbZ** [NixOS/nix#8382]
**Describe the bug**

`nix build` within the repository doesn't work anymore as there are tests failing.

Relevant looking output of the failing test (tests/build-remote-content-addressed-fixed.sh):

```text
     copying 2 paths...
     copying path '/nix/store/ln0ic0h43m76ij1pk5aag2mgdircv5m4-busybox' to 'ssh://localhost'...
     copying path '/nix/store/r04gjyz6sxxv6q6lwmc4r7cpqcsg4xcy-builder-build-remote-input-1.sh' to 'ssh://localhost'...
     error: build of '/nix/store/fgz87hm3y3b4zj1s7mg1cbbdmf1dnda1-build-remote-input-1.drv' on 'ssh://localhost?remote-store=/build/nix-test/tests/build-remote-content-addressed-fixed/machine1?system-features=foo' failed: error:
                   … while setting up the build environment

                   error: getting attributes of path '/etc/ssl/certs/ca-certificates.crt': No such file or directory
     error: builder for '/nix/store/fgz87hm3y3b4zj1s7mg1cbbdmf1dnda1-build-remote-input-1.drv' failed with exit code 1
     error: 1 dependencies of derivation '/nix/store/sjn8jv77yar3g9xnj8pkgsbws2vvxkai-build-remote.drv' failed to build
```

Result of bisection:

```
e31d9b910dcebd77028f5d4351e2cc7205baa321 is the first bad commit
commit e31d9b910dcebd77028f5d4351e2cc7205baa321
Merge: b1c34c0ee a7d2a3d08
Author: Eelco Dolstra <edolstra@gmail.com>
Date:   Fri May 19 13:05:16 2023 +0200

    Merge pull request #7312 from layus/fixed-output-system-cert

    Allow system certs access to fixed-output derivations

 src/libstore/build/local-derivation-goal.cc | 2 ++
 1 file changed, 2 insertions(+)
bisect found first bad commit
```

**Steps To Reproduce**

1. Clone this repository
3. checkout any commit on `master` after e31d9b910dcebd77028f5d4351e2cc7205baa321
4. `nix build`
5. See error

**Expected behavior**

Nix builds itself successfully.

**`nix-env --version` output**

`nix (Nix) 2.16.0pre20230518_b1c34c0`

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by NobbZ** [comment]
Started the bisection 4 hours before posting, thanks!

**Comment by Ericson2314** [comment]
Sorry we didn't open an issue before to save you the effort!

**Comment by NobbZ** [comment]
Sorry if this came a bit snarky :smile: 

It was mostly unattended, and I didn't really mind the effort. I even briefly skimmed open Issues and PRs, but at that time, I didn't correlate a PR with "ssl cert file" in its title to a failing test with "SSL cert not found" in its failing message :man_facepalming:, which is really more my fault than yours. You can assume, I hadn't found the issue either :sweat_smile:
