### ISSUE TITLE
setting TMPDIR have no effect 

### ISSUE THREAD

**Issue by joelmo** [NixOS/nix#839]
Trying with setting `TMPDIR=/var/tmp nix-build <nixpkgs> -A wine`. The only directory stored under /var/tmp is a temporary directory with a link to the .drv file.

**Comment by joelmo** [comment]
But this works if I am logged in as sudo, if this is how it should work maybe add a note about this in the docs?

**Comment by edolstra** [comment]
If you're building through the Nix daemon, then the user's `TMPDIR` won't have an effect on the daemon, which (IMHO) is to be expected.

**Comment by joelmo** [comment]
I agree, can you look at https://github.com/NixOS/nix/pull/841. Closing this.
