### ISSUE TITLE
RISC-V Building nix on Archlinux failed

### ISSUE THREAD

**Issue by HougeLangley** [NixOS/nix#8394]
**Describe the bug**

If you have a problem with a specific package or NixOS,
you probably want to file an issue at https://github.com/NixOS/nixpkgs/issues. 

**Steps To Reproduce**

1. I try to build nix on archlinux, yay -S nix-git
2. Building
3. This is [aur](https://aur.archlinux.org/packages/nix-git)
4. See error and full build log

[full-build-log.txt](https://github.com/NixOS/nix/files/11557148/full-build-log.txt)

**Comment by HougeLangley** [comment]
![2023-05-25_01-18](https://github.com/NixOS/nix/assets/1161594/aaa9f988-0a5d-4a96-a185-52b06ab3a5a7)

**Comment by HougeLangley** [comment]
Thanks, I will try

**Comment by NaN-git** [comment]
@thufschmitt This problem occurs on x86_64, too. The issue seems to be that `GTEST_LIBS` is not set correctly. `--disable-tests` is of course another workaround.

**Comment by thufschmitt** [comment]
@NaN-git do you think that's an issue with the Arch packaging or with the Nix build itself?

**Comment by NaN-git** [comment]
@thufschmitt This isn't an issue of the Nix build and it's rather an issue of the PKGBUILD. Actually, `GTEST_LIBS` is set correctly and when the line `CXXFLAGS='-D_GLIBCXX_USE_CXX11_ABI=0'` is removed from the PKGBUILD, then the build succeeds on x86_64.
