### ISSUE TITLE
Missing includes (args.hh)

### ISSUE THREAD

**Issue by ysangkok** [NixOS/nix#840]
I tried compiling on VS2010, and I had these problems:
- args.hh needs to include `<vector>`
- args.hh needs to include `<algorithm>` for max
- args.hh needs to include `<cassert>` for assert
- args.hh needs to include `<cctype>` for toupper

There are more issues like this, but first I want to know if VS2010 compatbility is something which should work.

**Comment by edolstra** [comment]
I don't think anybody has ever built Nix on VS before. Note that Nix is unlikely to work in a (non-Cygwin) Windows environment.

**Comment by ysangkok** [comment]
I know, of course there are many issues. I am just playing around. But since these issues are independent of a port to Windows, I reported them here, since there could be problems with other compilers for POSIX platforms.
