### ISSUE TITLE
[Help] : error os-x installer failed to copy store files to nix root [installation]

### ISSUE THREAD

**Issue by ehrktia** [NixOS/nix#8401]
## Platform

- [ ] Linux: 
- [x] macOS
- [ ] WSL

## Additional information

running the installer using `./scripts/install-multiuser.sh' 

## Output

```
---- oh no! --------------------------------------------------------------------
Oh no, something went wrong. If you can take all the output and open
an issue, we'd love to fix the problem so nobody else has this issue.

:(

We'd love to help if you need it.

You can open an issue at
https://github.com/NixOS/nix/issues/new?labels=installer&template=installer.md

Or get in touch with the community: https://nixos.org/community
```

failed at 

https://github.com/NixOS/nix/blob/c44750982d7a271c8444819377ab972af8946e5d/scripts/install-multi-user.sh#L808

```log

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo cp -RPp ./store/* /nix/store/

to copy the basic Nix files to the new store at /nix/store

Password:
cp: ./store/*: No such file or directory



```

</details>

- not able to locate where the ./store directory being created in script used for installation
- installation fails with not able to copy files as the `./store` is missing

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by abathur** [comment]
It sounds like you're DIYing something that isn't in the official instructions, so you're going to need to be extremely clear about what you're doing to have much chance of getting good help.

How did you get this script? What instructions are you following?

**Comment by ehrktia** [comment]
@abathur thanks for response , sorry was issue with my local machine it did work fine finally using the official installer
