### ISSUE TITLE
How to build drvs with `nix build` is unclear

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nix#8402]
**Describe the bug**
```
[root@ip-172-16-1-87:~]# nix build /nix/store/jyr290jp30k2bchwpgqh9frdfnxi843a-vm-test-run-gnome.drv
warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/jyr290jp30k2bchwpgqh9frdfnxi843a-vm-test-
run-gnome.drv!*'

[root@ip-172-16-1-87:~]# nix build /nix/store/jyr290jp30k2bchwpgqh9frdfnxi843a-vm-test-run-gnome.drv\!*
path '/nix/store/jyr290jp30k2bchwpgqh9frdfnxi843a-vm-test-run-gnome.drv!*' does not contain a 'flake.nix', searching up
error: getting status of '/nix/store/jyr290jp30k2bchwpgqh9frdfnxi843a-vm-test-run-gnome.drv!*': No such file or directory
```

**Steps To Reproduce**

1. Obtain a drv which has not yet been built
2. Run `nix build` on it

**Expected behavior**

drv is built, or the suggestion provided by the error message works

**`nix-env --version` output**
nix (Nix) 2.15.0

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by Ericson2314** [comment]
With 2.15.1 the message should use the correct `^`.

**Comment by Ericson2314** [comment]
With 2.15.1 the message should use the correct `^`.
