### ISSUE TITLE
Infinite recursion while attempting to load

### ISSUE THREAD

**Issue by AleCandido** [NixOS/nix#8404]
### Describe the bug
When trying to load in the REPL, an infinite recursion is triggered (I used the REPL just as the easiest way I know to load).

### Steps To Reproduce
On a fresh new installation of Nix on MacOS:
```
nix repl '<nixpkgs>'
```

### Expected behavior
Load `nixpkgs`, as described in https://nixos.wiki/wiki/Nix_command/repl

### Additional context
```console
~ % nix repl '<nixpkgs>'
warning: future versions of Nix will require using `--file` to load a file
Welcome to Nix 2.15.0. Type :? for help.

error:
       … in the left operand of the update (//) operator

         at /nix/store/sq0gp79s1kjhf6ilxfkxsqxasi5znh1c-nixpkgs/nixpkgs/lib/fixed-points.nix:69:64:

           68|   #
           69|   extends = f: rattrs: self: let super = rattrs self; in super // f self super;
             |                                                                ^
           70|

       … in the left operand of the update (//) operator

         at /nix/store/sq0gp79s1kjhf6ilxfkxsqxasi5znh1c-nixpkgs/nixpkgs/lib/fixed-points.nix:69:64:

           68|   #
           69|   extends = f: rattrs: self: let super = rattrs self; in super // f self super;
             |                                                                ^
           70|

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: infinite recursion encountered

       at «none»:0: (source not available)
```

### Metadata

```console
~ % nix-shell -p nix-info --run "nix-info -m"
error:
       … <borked>

         at «none»:0: (source not available)

       … in the left operand of the update (//) operator

         at /nix/store/sq0gp79s1kjhf6ilxfkxsqxasi5znh1c-nixpkgs/nixpkgs/lib/fixed-points.nix:69:64:

           68|   #
           69|   extends = f: rattrs: self: let super = rattrs self; in super // f self super;
             |                                                                ^
           70|

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: infinite recursion encountered

       at «none»:0: (source not available)
```

Maybe this is the wrong repo, since in this command `nixpkgs` is not even involved...

---

I already raised the issue in https://github.com/NixOS/nixpkgs/issues/232785, but most likely this is a more suitable place (it would've been fine to just *transfer* the issue, but unfortunately I can't do it on my side).

**Comment by cole-h** [comment]
Could you show the output of what happens with `--show-trace`? What is your `$NIX_PATH`? Do you have any files in `~/.config/nixpkgs`? What about `~/.config/nix`?

Looking at your Nixpkgs issue, I saw you installed Nix with the official installer. I installed Nix the same way in a fresh Ubuntu 22.04 VM and was unable to reproduce. I also notice that your repl says Nix 2.15.0, but 2.15.1 has already been released (for 3 days now).

![image](https://github.com/NixOS/nix/assets/28582702/8322d29a-92d9-4c36-971e-f6ae06107f41)

**Comment by AleCandido** [comment]
Ok, I installed the 2.15.1, and the problem is still there:
https://pastebin.com/eQ8dcvKN

I used the second command (`nix-shell -p nix-info --run "nix-info -m"`) just because, to the best of my understanding, this should be purely nix related, and `nixpkgs` should not be involved.

I tried to move the `.config/nix` folder, in order not to have any at all, but the problem persists.

**Comment by cole-h** [comment]
No, Nixpkgs is still involved even with that command (where is it getting `nix-info` from? Nixpkgs).

What happens if you run `nix-shell --pure -p nix nix-info --run "nix-info -m"`?

I'd still like to know if you have any files in `~/.config/nixpkgs` and what their contents are, because I can't reproduce this (not even on an Intel Mac that I have access to):

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 22.1.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.15.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

(for whatever reason, `nix-info` detects the macOS version wrong -- this mac is running 13.0.1)

**Comment by roberth** [comment]
To run `nix-info`, you could fetch it from `cache.nixos.org` using

x86_64-darwin: `nix-store -r /nix/store/vmfirixgqn3j8c3bsqgbxb51b314294h-nix-info`
aarch64-darwin: `nix-store -r /nix/store/l35qi8ycgi26b62wzxzpfgm1i7a6za0s-nix-info`

You can then run the executable from the bin directory in the store path.
(Normally, don't trust store paths from strangers)

**Comment by AleCandido** [comment]
Sorry, it turned out to be a problem with overlays. I haven't fully understood yet, but removing the `overlays` folder in `nixpkgs/` made it disappear.

Thanks @cole-h (and also @roberth), and sorry for the noise and the late reply.
