### ISSUE TITLE
`__contentAddressed` and `__impure` improperly elided from derivation

### ISSUE THREAD

**Issue by puckipedia** [NixOS/nix#8405]
**Describe the bug**

When `__contentAddressed` or `__impure` are configured in a Nix derivation, but set to `false`, their key is elided from the Nix derivation's environment. This means that, while they evaluate fine on a pre-introduction Nix version (e.g. 2.3), the generated derivation's environment doesn't match.

**Steps To Reproduce**

1. Evaluate `derivation { name = "name"; builder = "builder"; system = "x86_64-linux"; __contentAddressed = false; __impure = false; }` on Nix 2.3 and a newer version of Nix

**Expected behavior**

The derivation hashes being the same.

**`nix-env --version` output**

```
nix-env (Nix) 2.13.3
nix-env (Nix) 2.3.16
```

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by edolstra** [comment]
Well, the output paths wouldn't be the same anyway.

Probably `__contentAddressed` and `__impure` should have been implemented as required system features to ensure that you get an error on Nix versions that don't support them.

**Comment by puckipedia** [comment]
I don't mind that it behaves differently if set to `true` (and the values breaking when you put anything but `true` or `false` is a bit iffy and backwards-incompatible) - but the issue here is very explicitly (it's in the first sentence!) about the values being set to `false`.

**Comment by puckipedia** [comment]
Huh. Only just noticed it's just `nodejs` in nixpkgs, and instead of fixing it here it was worked around https://github.com/NixOS/nixpkgs/pull/229547 (missing `__impure`!)

**Comment by yajo** [comment]
Hello folks. This fix produced a reproducibility issue that you can see in https://github.com/NixOS/nix/issues/8507. Could somebody please take a look there, so we can see how to fix that? Thanks!
