### ISSUE TITLE
Move perl files to own repo

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nix#843]
Right now if you want to write a perl script that depends on the Nix perl scripts you can do something like this:

```perl
#! /usr/bin/env nix-shell
#! nix-shell -i perl -p perl nix
use Nix::Manifest;
```

The issue is that the nix perl modules don't depend on all of the things the perl scripts use, so you need to propagate them there. If we can move them into their own "perlPackages.nix" package then we can add all of the dependencies.

**Comment by vcunat** [comment]
Note that nix is currently phasing out perl dependency #341.
