### ISSUE TITLE
Upload manuals to releases.nixos.org again

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#8451]
**Describe the bug**

We stopped uploading manuals to releases.nixos.org some time after 2.3 (e.g. https://releases.nixos.org/nix/nix-2.3/manual/index.html). It would be useful to be able to link to old versions of the manual.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by pvgoran** [comment]
Is there something similar for NixOS manuals? I'm trying to find old versions of the said manual.
