### ISSUE TITLE
It's no longer possible to define unneeded functions as `_`.

### ISSUE THREAD

**Issue by azahi** [NixOS/nix#8471]
**Describe the bug**

Starting with 3.14 it's no longer possible to have `_` to denote "don't care" functions like, for example `genList _ 10`. Here's a real-life example:
```nix
pow = base: exponent: builtins.foldl' (x: _: x * base) 1 (builtins.genList _ exponent)
```

For some reason I only can reproduce this while evaluating my NixOS configuration on 3.14. Trying to define this function in REPL errors out with `error: undefined variable '_'` across all versions.

The offending trace part of `nixos-rebuild build` is:
```
       … from call site

         at /nix/store/fq51zwrip7bnd6hn39kmrjabccnp5hm5-source/modules/nixos/common/kernel.nix:12:39:

           11|       # "fs.file-max" = pow 2 17;
           12|       "fs.inotify.max_user_watches" = pow 2 19;
             |                                       ^
           13|       "fs.suid_dumpable" = 0;

       … while calling 'pow'

         at /nix/store/fq51zwrip7bnd6hn39kmrjabccnp5hm5-source/lib/default.nix:12:15:

           11|
           12|   pow = base: exponent:
             |               ^
           13|     assert (builtins.isInt base) && (builtins.isInt exponent);

       error: value is a set while a function was expected
```
Full trace of `nixos-rebuild build` is [here](https://gist.github.com/azahi/779f8dbc1014d9ec96e7e7443d5a3a1c).

If I switch `_` with `(_: _)`, evaluation succeeds.

**Steps To Reproduce**

1. Use the latest Nix version.
2. Have something like this in your configuration:
```nix
boot.kernel.sysctl = let
  pow = base: exponent:
    builtins.foldl' (x: _: x * base) 1 (builtins.genList _ exponent);
  in {
    "fs.inotify.max_user_watches" = pow 2 19;
  };
```
3. Try to do `nixos-rebuild switch` and encounter an error.
4. Switch to 3.13 (via `config.nix.package`) and try to do `nixos-rebuild switch` again and see that it doesn't error out.

**Expected behavior**

I'm not exactly sure if this is a regression or not, so I guess this is not exactly a bug. Anyway this kinda breaks compatibility.

**Additional context**

```
nix-env (Nix) 2.14.1
```

I'm on `nixpkgs-unstable` which at the time of error was at `af21c31b2a1ec5d361ed8050edd0303c31306397`.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by roberth** [comment]
I don't think `_` ever had a special meaning except as a convention for unreferenced names.

In other words, you'd have to introduce a `_` binding yourself (e.g. with `let`, or by defining a function) if you'd want to use it, but I would recommend against that, because it breaks the convention that variables named `_` are unused.

Maybe you've confused Nix with another language that has `_` for "holes", like Haskell?

```
$ nix run nix/2.4 repl
Welcome to Nix 2.4. Type :? for help.

nix-repl> map _ []
error: undefined variable '_'

       at «string»:1:5:

            1| map _ []
             |     ^
            2|

nix-repl> pow = base: exponent: builtins.foldl' (x: _: x * base) 1 (builtins.genList _ exponent)
error: undefined variable '_'

       at «string»:1:71:

            1|  base: exponent: builtins.foldl' (x: _: x * base) 1 (builtins.genList _ exponent)
             |                                                                       ^
            2|

```

If you know of a Nix version that evaluates your expression, please let us know because that would be a severe bug.
