### ISSUE TITLE
2.15: nix-copy-closure hangs if ControlPath provided for SSH

### ISSUE THREAD

**Issue by nyarly** [NixOS/nix#8480]
**Describe the bug**

c.f. https://github.com/NixOS/nixops/issues/1557

When NixOps sets `NIX_SSHOPTS` to include `-oControlPath=...`, `nix-copy-closure` hangs.

**Steps To Reproduce**

1. Update to Nix 2.15
2. `nixops deploy -d ...`
3. Observe: "copying closure..." which never proceeds.

**Expected behavior**

Files to copy between stores.

**`nix-env --version` output**

nix-env (Nix) 2.15.0

**Additional context**

When stuck in this mode, I noticed that `strace` attached to the nix-copy-closure process reported
```
read(7,
```

and on the remote side, strace attached to the corresponding `nix-store` process reported
```
read(0,
```

The remote side was 2.3 initially, and I was able to use `nix-copy-closure` _without_ an SSH ControlPath to update to 2.15. Neither worked with 2.15 on the local side; downgrading to 2.14 corrected the issue.

**Comment by thufschmitt** [comment]
That looks like an instance of https://github.com/NixOS/nix/issues/8329. Can you try with the client at 2.16 (or anything after https://github.com/NixOS/nix/pull/8349) ?

**Comment by misuzu** [comment]
Same issue, but with remote builders. Downgrade to 2.13 or upgrade to 2.16 fixes the issue for me.

**Comment by corngood** [comment]
This seems to be the same issue as https://github.com/NixOS/nixops/issues/1557, and it's still broken for me on master as of 041486b11674e0480ad85f63d262c33a09276ef1.

**Comment by nyarly** [comment]
Downgrading to 2.13 fixed it for me; I've got some other issues around that deployment environment, so I may be able try with 2.16. Did notice that moving to 23.05 marks Python 2.7 as insecure, which is a problem for NixOps 1.7.

**Comment by roberth** [comment]
> 23.05 marks Python 2.7 as insecure, which is a problem for NixOps 1.7.

NixOps 1.7 is effectively end-of-life. 2.0 has not been released yet, although I plan to spend some time to move it towards a release candidate. If you know someone who's interested in a healthy NixOps, there's an opencollective [project for NixOps 2](https://opencollective.com/nix-deployments/projects/nixops-2) or they could fund the broader [collective](https://opencollective.com/nix-deployments) goals.

**Comment by nyarly** [comment]
@roberth I'm interested in a healthy NixOps, and your comment is well taken.

**Comment by domenkozar** [comment]
@edolstra this should be a blocker for 2.17 since it breaks nix-copy-closure.

**Comment by jaseg** [comment]
I ran into what looks like this issue trying to set up a new machine with nixos-anywhere in May 2026. I'm using their example configuration with the stateVersion set to 25.11. I have `ControlMaster` set for the target machine in my local SSH config, and removing that config line fixes the hang.
