### ISSUE TITLE
Describe path flakerefs correctly

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/nix#8482]
## Problem

Flakerefs that are paths seem to behave in an undocumented way. Thees needs to be fixed before we can extend the behavior to accommodate https://github.com/NixOS/nix/pull/6614

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by thufschmitt** [comment]
Expanding a bit on the difference between the docs and the implementation:

- `path:/some/path` behaves as documented in https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-flake.html#types
- `/some/path` or `./some/path` is a convenience shortcut that has a more complex behavior:
  1. It detects whether the target is part of a git repo or not and switches between a `path:` or `git+file:` type accordingly
  2. If  `/some/path` doesn't contain a `flake.nix` file, it will search upwards in the file system hierarchy until it stumbles across either
    1. A directory containing a `flake.nix` file,
    2. The Git repository root,
    3. The filesystem root (`/`), or
    4. A folder on a different mount point
