### ISSUE TITLE
Leading and trailing whitespace in the `bash-prompt` settings are stripped

### ISSUE THREAD

**Issue by polykernel** [NixOS/nix#8487]
**Describe the bug**

When parsing a nix config file, every key-value pair is tokenized in the same way. This is fine for most settings whose the expected input does not contain separator tokens(i.e whitespace characters) and are not sensitive to whitespace. However for settings such as `bash-prompt`, normalizing the value fragment of each key-value pair(by stripping leading and trailing whitespaces) affect the prompt strings that end up being set. As a consequence, it is impossible to set a prompt string with leading and/or trailing whitespaces.

**Steps To Reproduce**

1. Set `NIX_CONFIG="bash-prompt =   [\u@\h:\w]\$ "`
2. Run `nix show-config --json | jq '."bash-prompt"'`
3. Observe the trailing whitespaces in the value of `bash-prompt` are stripped.

**Expected behavior**

Trailing whitespaces in settings such as `bash-prompt` are preserved when parsing.

**`nix-env --version` output**

`nix-env (Nix) 2.16.1`

**Additional context**

I realize that this bug is specific to the `bash-prompt` and related settings due to the semantics of prompt strings and is not of high priority, but I hope the issue can still be addressed as it hints at a deficiency in the current parsing model when differing semantics interpretation of values between settings occur.

A possible fix could be to delay tokenization and pass the entire line after the key-value separator to the corresponding Setting identified by key. The Setting knows its expected input format and can perform tokenization pertaining to its needs.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by cole-h** [comment]
If you want spaces, you can use `\040`.

e.g. with `bash-prompt-prefix = (nix:$name)\040`, `nix develop nixpkgs#hello` shows the following prompt:

```
(nix:hello-2.12.1-env) bash-5.2$  
```

**Comment by polykernel** [comment]
Ah, I didn't think about octal escape sequences. The value stored by Nix in this case is still uninterpreted but one can always use a stringstream to get an interpreted representation if necessary so this is a not a problem.
