### ISSUE TITLE
fetchTarball cannot be used concurrently

### ISSUE THREAD

**Issue by gilligan** [NixOS/nix#849]
Given the following default.nix:

``` nix
with import (builtins.fetchTarball "https://github.com/NixOS/nixpkgs/tarball/27af419541a50c33d2bf0762c8740552794e5b1a") {}; {
  test = stdenv.mkDerivation {
    name = "test";
  };
}
```

Invoking : `$ nix-shell & nix-shell` will fail with:

```
error: creating symlink from ‘/Users/tpflug/.cache/nix/tarballs/.new_mm46xaz0wdh58q4smch92sw1r3q6gqys-27af419541a50c33d2bf0762c8740552794e5b1a-unpacked’ to ‘/nix/store/grx24c2nc5
8a8gr4s7jq0a7rr8nn4zs6-27af419541a50c33d2bf0762c8740552794e5b1a’: File exists
```

This happens since both nix-shells try to symlink the tarball not expecting that it might already be there. A possible fix would be to just use a symlink if it already exists with the expected name. 

Obviously you would not start two nix-shells like in this minimal test case but for me it happens in a setup where some `nix-shell --command` are being executed in parallel. 

Would there be any reason to _not_ use an expected symlink if it is already there ?

---

_Edit_: Apparently various people on irc cannot reproduce this which is quite odd to me since I can reliably reproduce this on darwin and also nixos

```
gilligan@monoid:/tmp/test » nix-shell & nix-shell
[1] 2053
error: creating symlink from ‘/home/gilligan/.cache/nix/tarballs/.new_mm46xaz0wdh58q4smch92sw1r3q6gqys-27af419541a50c33d2bf0762c8740552794e5b1a-unpacked’ to ‘/nix/store/grx24c2nc58a8gr4s7jq0a7rr8nn4zs6-27af419541a50c33d2bf0762c8740552794e5b1a’: File exists
[1]  + 2053 exit 1     nix-shell

[nix-shell:/tmp/test]$ : 1468915534:0;nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"16.09pre85931.125ffff"

[nix-shell:/tmp/test]$ nix-env --version
nix-env (Nix) 1.11.2

[nix-shell:/tmp/test]$ 
```

---

_Edit 2_: This does not _always_ happen but if I try a couple of times (like 3 or 4 times) it will definitely happen. A matter of when the symlink is created and when `createSymlink` / `replaceSymlink` is called in the individual process (as described below).

**Comment by gilligan** [comment]
This seems to be fixed in nix `1.11.2`- I cannot reproduce it anymore.

**Comment by gilligan** [comment]
It seems like I a experiencing this issue again.I am not sure why it seemed to be gone before but it is very easy to reproduce using the above `default.nix` : 

```
$ nix-shell --run "echo 'hello'" & nix-shell "echo 'hello'"
$ nix-shell --run "echo 'hello'" & nix-shell "echo 'hello'"
$ nix-shell --run "echo 'hello'" & nix-shell "echo 'hello'"
```

Just run that a couple of times and you will get the error described above. This happens on both, OSX and NixOS. We run into this issue because we have a nixos server running jenkins which uses `nix-shell` in a couple of places.

Any ideas about this one? It is quite a blocker for us.

**Comment by gilligan** [comment]
I am looking at `Downloader::downloadCached` wondering if the problem is in there, but my C++ is failing me:

https://github.com/NixOS/nix/blob/master/src/libstore/download.cc#L224

**Comment by gilligan** [comment]
If I set `tarball-ttl` to 0 the problem is gone.

**Comment by gilligan** [comment]
I tried to dig a bit into this. It definitely happens inside [replaceSymlink](https://github.com/NixOS/nix/blob/master/src/libutil/util.cc#L453) when it calls [createSymlink](https://github.com/NixOS/nix/blob/master/src/libutil/util.cc#L442).

**Comment by gilligan** [comment]
@domenkozar do you have an idea what to do about this? I know where it happens but i don't know what the right approach to fix this would be.

**Comment by gilligan** [comment]
*bump* this does a pretty huge impact here - Could I get any feedback on this from anyone?

**Comment by copumpkin** [comment]
Ping @edolstra

**Comment by viric** [comment]
why is the 'tmp' symlink required? If it were not, it would just be a matter of ignoring "File exist" case.

**Comment by viric** [comment]
Ah the tmp is required because this path is reached specifically when the original symlink exists, and has to be overwritten.

So the easy change is to put a random part into the tmp filename.

**Comment by domenkozar** [comment]
@cleverca22 point out the root of this issue here: https://github.com/input-output-hk/stack2nix/issues/15#issuecomment-313819908

**Comment by edolstra** [comment]
Thanks, will have a look.

**Comment by domenkozar** [comment]
Thanks @edolstra :) Could we also cherry-pick to maintenance branch?

**Comment by edolstra** [comment]
@domenkozar Done.
