### ISSUE TITLE
Remove dead code for `createSymlink` and `replaceSymlink`

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/nix#8495]
# Problem

`filesystem.cc` is the only place where [`createSymlink()` is used with three arguments](https://github.com/NixOS/nix/blob/041486b11674e0480ad85f63d262c33a09276ef1/src/libutil/filesystem.cc#L89): in the definition of `replaceSymlink()` with three parameters that *is not used at all*.

# Proposal

Remove this third `mtime` parameter and delete the code that handled it.

# Context

https://github.com/NixOS/nix/pull/7048 deals with timestamps, but there are occurrences that we can avoid handling altogether because they are dead code anyway.

**Comment by salpelter** [comment]
Hi, trying to make my first commit here.
I updated the code and doubt I messed anything up, it should be correct.  But the pull request template asks me to explain the motivation behind the change as well as the context. I'm not sure what to do, should I just copy things mentioned in this issue? I don't know what else I can say, really.
Anyway, please correct me if I'm doing _anything_ wrong, help would be very much appreciated!

**Comment by fricklerhandwerk** [comment]
Hey @salpelter, thanks a lot for taking time. I know first hand that contributing to Nix can be scary, so it's great that you're reaching out.

The motivation section in the PR template is for us maintainers to see at a glance what this is about. In this case, a copy of the problem statement will do. Generally, a sentence or brief paragraph is very helpful to get into context. Linking the underlying issue for reference helps.

**Comment by salpelter** [comment]
Thank you for a quick reply, @fricklerhandwerk! I'll do that soon.
How long do you think it is gonna take for the reviewers to get to this kind or pull request? I'm just curious if it'll work out well, since I have no firm idea of what I'm doing (yet).

**Comment by fricklerhandwerk** [comment]
We usually triage PRs every Friday, and since @Ericson2314 and me found this together, it is likely to get merged either instantly if it's obviously correct or... it goes its usual labyrinthine ways.

**Comment by salpelter** [comment]
I created a pull request. At first, I thought it would appear here as well, but now that I've thought about it, it makes sense why it didn't.
Is there anything else I should do right now besides waiting?

**Comment by fricklerhandwerk** [comment]
Thanks, just wait for reviews and address comments as you go. That may be more work for you than you expect. If your PR doesn't feel ready, make it a draft so maintainers can filter it out.

Note that keeping a PR open for a long time can introduce even more work to get it merged, if it runs into conflicts with the master branch. Following up with incorporating feedback quickly helps in part, but sometimes things just get stuck on the maintainers' end due to lack of time.
