### ISSUE TITLE
Make a separate manual page for store implementations

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/nix#8496]
## Problem

Currently store parameters are documented in the man page for a [special-purpose command](https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-help-stores.html).

## Proposal

Add a section in the manual with a page per store implementation listing all parameters. It could go under the Protocols section. Add anchors to all parameters so they can be linked to directly.

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by Mash707** [comment]
Hii @fricklerhandwerk I am new to open source and would like to contribute to this issue. From my Understanding we have create a new page for each store implementation , club them under a section and this section should be under Protocols section.

**Comment by fricklerhandwerk** [comment]
Thanks for your support! @Ericson2314 just recently opened a PR: https://github.com/NixOS/nix/issues/8781

You could definitely help with figuring out where to put the information such that it's both available on the command line and on the web as conveniently and easy to discover as possible. See the discussion on the PR for details.

**Comment by fricklerhandwerk** [comment]
Closed by https://github.com/NixOS/nix/pull/9504
