### ISSUE TITLE
Mismatch doc/code "binary-caches-files"

### ISSUE THREAD

**Issue by viric** [NixOS/nix#850]
The perl script expects "binary-cache-files", and the documentation advises "binary-caches-files".

**Comment by shlevy** [comment]
@edolstra This is removed in favor of binary cache store, right?

**Comment by domenkozar** [comment]
```
$ git grep binary-cache-files

$ git grep binary-caches-files
doc/manual/command-ref/conf-file.xml:  <varlistentry><term><literal>binary-caches-files</literal></term>
doc/manual/command-ref/conf-file.xml:    <option>binary-caches-files</option>.  When used by unprivileged
```

Seems like this was removed indeed. How should we handle that? Raise an error if it's set to instruct what to do instead?

**Comment by shlevy** [comment]
My guess is that @edolstra plans a significant doc overhaul once the current master is closer to ready for merge. No idea what migration paths will be

**Comment by edolstra** [comment]
Closing since this option no longer exists.
