### ISSUE TITLE
Remove no-doc primop constructor

### ISSUE THREAD

**Issue by Ericson2314** [NixOS/nix#8515]
In 8ec1ba02109eee7e8dfd89f3fbbf060497940469 it is written:

> Note that we keep the old constructor even if it is no longer used by
> Nix code, because it is used in `tests/plugins/plugintest.cc`, which
> suggests that it might be used by some external plugin.

I don't think we have any promise of plugin ABI compat. And I would like to make sure no undocumented ones sneak in again :). Therefore best to remove it after all.

**Comment by Ericson2314** [comment]
@wentasah would you like to do this?

**Comment by wentasah** [comment]
Yes, I'll do it. I've the commit ready.

**Comment by wentasah** [comment]
See #8516.
