### ISSUE TITLE
nix-shell should preserve SSL_CERT_FILE

### ISSUE THREAD

**Issue by cstrahan** [NixOS/nix#853]
It appears that the stdenv in Nixpkgs has changed such that `$SSL_CERT_FILE` is set to `/no-cert-file.crt`. `nix-shell` ought to preserve the environment variable so that programs that need SSL (e.g. `git`) don't break. If the environment variable didn't exist prior to invoking `nix-shell`, the environment variable should be unset before executing the given command.

**Comment by fkz** [comment]
see also nixos/nixpkgs#13744

**Comment by peti** [comment]
Is that not accomplished by https://github.com/NixOS/nixpkgs/commit/39609a0c9414b398330e42f872e7358e30e133dd?

**Comment by vcunat** [comment]
It doesn't preserve it being unset :-) But anyway, that's not a problem in nix-shell itself (i.e. its repo). We could modify the stdenv instead to e.g. be responsive to `$IN_NIX_SHELL`...

**Comment by cstrahan** [comment]
@peti I'm on NixOS/nixpkgs@0bf8a1a (which includes that commit), and it still happens:

    $ echo $SSL_CERT_FILE


    $ nix-shell -p stdenv --run 'bash -c "echo $SSL_CERT_FILE"'
    /no-cert-file.crt

**Comment by fkz** [comment]
@cstrahan Yes, this is known. This is a duplicate of NixOS/nixpkgs#13744, see the discussion there

**Comment by peti** [comment]
OK, I think this bug report and that it should be fixed. IMHO, https://github.com/NixOS/nixpkgs/issues/13744 is the right place to pursue this issue, though, since the behavior in question is caused by the stdenv generic builder and not by Nix itself.

**Comment by cstrahan** [comment]
> IMHO, NixOS/nixpkgs#13744 is the right place to pursue this issue, though, since the behavior in question is caused by the stdenv generic builder and not by Nix itself.

That sounds fair. I thought we might need to just filter out a set of bad environment variables within `nix-shell`, but it does seem that the right thing to do is tweak the stdenv to behave correctly under `nix-shell`.
