### ISSUE TITLE
Test running Nix inside chroots, namespaces, etc.

### ISSUE THREAD

**Issue by Ericson2314** [NixOS/nix#8546]
See #8483 for example of a bug fix that lacks a test. See #5033 for a fix whose test doesn't work in CI. I am sure there are other examples.

This is somewhat tricky, but I think we can do it with `unshare`. If not, we can do it with VM tests.

**Comment by roberth** [comment]
Another bugfix involving namespaces
 - https://github.com/NixOS/nix/pull/8578

**Comment by Ericson2314** [comment]
Fixed by #8696
