### ISSUE TITLE
ccacheStdenv is broken on darwin

### ISSUE THREAD

**Issue by iFreilicht** [NixOS/nix#8557]
**Describe the bug**

When trying to compile nix following the [hacking guide](https://nixos.org/manual/nix/unstable/contributing/hacking.html), the `./configure` call fails.

**Steps To Reproduce**

```
zsh$ git clone https://github.com/NixOS/nix
zsh$ cd nix
zsh$ nix develop .#native-ccacheStdenvPackages
bash$ ./bootstrap.sh
[...]
bash$ ./configure $configureFlags --prefix=$(pwd)/outputs/out
checking for a sed that does not truncate output... /nix/store/v6ihvpa7b1mj58sbimfqyrg205mrd7xv-gnused-4.8/bin/sed
checking build system type... aarch64-apple-darwin22.5.0
checking host system type... aarch64-apple-darwin22.5.0
checking for the canonical Nix system name... aarch64-darwin
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/Users/feuh/repos/nix':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

See the attached [config.log](https://github.com/NixOS/nix/files/11800587/config.log).

**Expected behavior**

I would expect the `./configure` call to succeed. It does in a normal `nix develop` shell.

**`nix-env --version` output**

**Additional context**

This is on `aarch64-darwin`, on current master (6a74e88f).

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by Artturin** [comment]
Going to assume https://github.com/NixOS/nixpkgs/pull/178280 fixed this and you didn't have a nixpkgs which included that fix
