### ISSUE TITLE
Permissions for gcroots folders changed

### ISSUE THREAD

**Issue by jakubgs** [NixOS/nix#8564]
**Describe the bug**

Somewhere between `2.13.4` and `2.14.1` something about how files in `/nix/var/nix/gcroots/per-user` are created changed.

When I'm on `2.13.4` in a multi-user setup I can use for example `nix-instantiate` in create paths under `gcroots`:
```
 > nix-instantiate --attr shells.default --add-root /nix/var/nix/gcroots/per-user/${USER}/status-mobile default.nix 
/nix/var/nix/gcroots/per-user/jakubgs/status-mobile
```
But when I do it on `2.14.0` it fails:
```
 > nix-instantiate --attr shells.default --add-root /nix/var/nix/gcroots/per-user/${USER}/status-mobile default.nix 
error: creating directory '/nix/var/nix/gcroots/per-user/jakubgs': Permission denied
```
Why is that?

**Steps To Reproduce**

1. Install Nix 2.14 or newer in multi-user mode
2. Use `nix-instantiate` with `--add-root` flag
3. See failure due to `Permission denied`

**Expected behavior**

I'd expect this to work as before.

**Additional context**

Our research issue and Discourse post:

* https://github.com/status-im/status-mobile/issues/16344
* https://discourse.nixos.org/t/upgraded-to-nix-2-14-1-and-profiles-are-not-being-created/29455/2

**Comment by jakubgs** [comment]
I have tested `2.16.1` release and it fails the same way:
```
jakubgs@ubuntuvm:~/status-mobile % nix-instantiate --attr shells.default --add-root /nix/var/nix/gcroots/per-user/${USER}/status-mobile/shells.default default.nix
error: creating directory '/nix/var/nix/gcroots/per-user/jakubgs': Permission denied       

jakubgs@ubuntuvm:~/status-mobile % nix-instantiate --version
nix-instantiate (Nix) 2.16.1
```
So that version is also affected.

**Comment by jakubgs** [comment]
I can confirm this error still appears when using `2.19.2`:
```
error: creating directory '/nix/var/nix/gcroots/per-user/joe': Permission denied
```

**Comment by thufschmitt** [comment]
@jakubgs sorry, I somehow just saw this issue right now.

I suspect this is due to the profile migration that happened between 2.13 and 2.14. The `gcroots/per-user/{user}` doesn't exist any more – the `per-user` directories were problematic, and we had to get rid of them.

You can either create it manually or use any another directory to store the gc root (`~/.local/share/nix/gcroots` would be my first choice if you have no reason to put it in another place)

**Comment by jakubgs** [comment]
Oh, I wasn't aware I could configure where `gcroots` are located. How can I do it? I don't see any config value in docs:

- https://nixos.org/manual/nix/stable/command-ref/conf-file
- https://nixos.org/manual/nix/stable/package-management/garbage-collection
- https://nixos.org/manual/nix/stable/package-management/garbage-collector-roots

Is `~/.local/share/nix/gcroots` one of the locations supported by default without any need for configuration?

**Comment by jakubgs** [comment]
Oh, I see, so using `nix-store --add-gcroot` creates a symlink under `/nix/var/nix/gcroots/auto`. So I can pass any location to `--add-gcroot` that doesn't have to be under `/nix/var/nix/gcroots` for the symlink to appear under `auto` subfolder.

Is that right?

**Comment by thufschmitt** [comment]
> Oh, I see, so using `nix-store --add-gcroot` creates a symlink under `/nix/var/nix/gcroots/auto`. So I can pass any location to `--add-gcroot` that doesn't have to be under `/nix/var/nix/gcroots` for the symlink to appear under `auto` subfolder.

Yes. It's possible to create gcroots anywhere on the system (like the `result` symlink that `nix-build` creates by default). The old `gcroots/per-user` directory was essentially a leftover of the old (pre 2005) mechanism that didn't allow that

**Comment by jakubgs** [comment]
I see, thanks for explaining. This means we can simply create our symlinks using `nix-store --add-gcroot` within our repository folder under `.nix-gcroots`, and avoid this permissions issue entirely. And that's what I've done as part of our Nix upgrade:

* https://github.com/status-im/status-mobile/pull/18742

Appreciate your help. I'm closing this.
