### ISSUE TITLE
Acknowledge contributors using a script

### ISSUE THREAD

**Issue by roberth** [NixOS/nix#8593]
**Is your feature request related to a problem? Please describe.**

The release notes used to acknowledge all contributors of a release.

I think this served two purposes
 - Give credit where credit is due
 - Promote collaboration

**Describe the solution you'd like**

Add a script to run as part of the release process. It gathers the contributor names and github handles from the git history and formats them as markdown to be added to the release notes.

By automating this, we don't regress in release overhead, while working toward team goals.

> The highlighted features and other improvements and fixes are brought to you by the Nix team and the following contributors:

**Describe alternatives you've considered**

- Defer this to a more general tool, #7665 

- Do it by hand at the cost of release overhead. That'd be bad.

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by roberth** [comment]
@lf- now also asks for something like this, https://github.com/NixOS/nix/pull/10779#issuecomment-2133899758

**Comment by lf-** [comment]
Sort of. Our release notes credit the contributors on the feature itself, but an overall list would be nice as well. Also our release notes generator is some simple Python in-tree rather than an out of tree haskell thing.
