### ISSUE TITLE
nixos issues

### ISSUE THREAD

**Issue by radicaltravie** [NixOS/nix#8597]
## Platform

- [ ] Linux: 
- [ ] macOS
- [ ] WSL

## Output

<details><summary>Output</summary>

```log

<!-- paste console output here and remove this comment -->

```

</details>

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by cole-h** [comment]
Please fill out the issue template with enough information for us to figure out what problem you're running into.

Closing for now. If you have more information, please feel free to add it here as a comment or by editing the main post and we can reopen the issue to investigate the troubles you're having.
