### ISSUE TITLE
`--dry-run` logic isn't implemented for ca-derivations

### ISSUE THREAD

**Issue by pwaller** [NixOS/nix#8615]
**Describe the bug**

`nix-build --dry-run` incorrectly reports that it will build CA derivations, when it will actually substitute them if the build is run.

This is also true of the initial output of `nix-build` when not doing a dry run.

**Steps To Reproduce**

1. Build a CA derivation
2. Copy it to a cache
3. Delete it from the local store
4. Run `nix-build --dry-run`, observe that it says it will build the derivation
5. It does not build it, it fetches it from the substituter

**Expected behavior**

nix-build should report the set of things which require building.

Because it does not do this, it can be quite awkward to use; I'm using it for quite a large system (tens of thousands of derivations), where it is important to me know if the derivations can come from the cache in advance of trying to build it.

I can work around this a little bit by doing `--max-jobs 0`, but this makes the resolution logic very slow/single threaded, so there is a significant performance degredation with that approach.

**`nix-env --version` output**

`nix (Nix) 2.17.0` (git main)

**Additional context**

What I see is that `mustBuildDrv` is being called for the CA derviations here:

https://github.com/NixOS/nix/blob/a0c617348b636d4a6f239450a61e029719e2c832/src/libstore/misc.cc#L208

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by thufschmitt** [comment]
It's generally not possible to know for sure in advance that a given derivation will be rebuilt since early-cutoff might happen during the build, so I decided not to bother too much about `--dry-run`. But we can indeed do better, and a PR would be welcome :).

I think the approach of fe8e91337a321099b9b7d2202b17caf129342fb4 is conceptually the right one (although hopefully we can make it less invasive).

**Comment by pwaller** [comment]
I appreciate you can't tell what might need rebuilding if you get a "CA match" in the process of building one of the derivations.

But I would like to share my scenario and the consequences of the issue, since it may not be obvious. I'm working on sending a fix (as you've seen), but I'll need a little help to get it right.

I have tens of thousands of expensive-to-build CA derivations, which are then used in the process of creating a signle derivation ("The Output") as output. There is no runtime dependency of The Output on the CA inputs. Right now, I keep The Output in a local cache permenantly, and the expensive-to-build CA derivations eventually fall out of the cache, since they are not needed so long as The Output exists.

The consequence of this is that The Output *should* 1) always be a cache hit 2) only require one test-for-presence in the private substituter and we're done. Requesting The Output should efficiently report to the user it will fetch exactly one derivation.

What happens currently though is that the `queryMissing` machinery doesn't recognize it has "The Output" in the cache because it doesn't look for realisations. Therefore, it ends up querying all the substituters (including cache.nixos.org) for the tens of thousands of expensive-to-build CA derivations. For one thing, this generates significant unwanted traffic to the cache. For another thing, they will always be cache misses, so generates all of this unwanted traffic to all of the caches.

It also is alarming to a user, because they get tens-of-thousands-of-lines of `these 23456 derivations will be built:` output (ruining their console history apart from anything else), when they expect a single cache hit. It is also extremely slow since under the hood nix is generating tens of thousands of roundtrips to each of the caches.

I hope that gives a glimpse of the importance and urgency to me of fixing this.
