### ISSUE TITLE
Can't install nixos on Fedora

### ISSUE THREAD

**Issue by Hamda345** [NixOS/nix#8639]
## Platform

- [ X ]  Linux : Fedora 38 
- [ ] macOS
- [ ] WSL

## Additional information

 
Can't install NixOs with SELinux enabled

## Output

<details><summary>Output</summary>

```log

<!-- paste console output here and remove this comment -->

```

</details>

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by SuperSandro2000** [comment]
You must fill out the template, otherwise we cannot provide any help.

**Comment by Artturin** [comment]
https://github.com/NixOS/nix/issues/2374
