### ISSUE TITLE
nix copy massively overreports amount of copied data

### ISSUE THREAD

**Issue by fogti** [NixOS/nix#8643]
**Describe the bug**

Nix copy grossly overreports the amount of data transferred... (maybe off by a factor off 1024^n or such??)
```
copying path '/nix/store/g4jb6k46f2phyybbmkw3j0pfdn4y1psi-gnupg-2.4.0' from 'ssh-ng://fogti@192.168.0.5'...
copying path '/nix/store/gz4ca3pj051m8zsxgc9p93ixydzy2m3y-libusb-1.0.26-dev' from 'ssh-ng://fogti@192.168.0.5'...
copying path '/nix/store/rxj4sm6g9xmgxx06rc1kd7fkamncgg4r-libmtp-1.1.21' from 'ssh-ng://fogti@192.168.0.5'...
copying path '/nix/store/yj19gp44ag1aaza9g2xl2n17f49jxwr0-gusb-0.3.10' from 'ssh-ng://fogti@192.168.0.5'...
[4/1326/1705 copied (3293970.7/3287771.4 MiB)] copying path '/nix/store/yj19gp44ag1aaza9g2xl2n17f49jxwr0-gusb-0.3.10' from 'ssh-ng://fogti@192.168.0.5'
```

**Steps To Reproduce**

1. copy a large closure where some paths are fetched via ssh-ng and some from a substitutors
2. observe that the amount of copied data doesn't match up

**Expected behavior**

Amount of copied data should be rather accurate.

**`nix-env --version` output**

I think nix-env (Nix) 2.16.0pre20230518_b1c34c0
(but it might be off a bit, this error occurs occasionally...)

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by phaer** [comment]
Could be a duplicate of https://github.com/NixOS/nix/issues/8108 ?

**Comment by fogti** [comment]
yep.
