### ISSUE TITLE
Help!!! Me

### ISSUE THREAD

**Issue by iAob19** [NixOS/nix#8645]
## Platform

- [ ] Linux: 
- [x] macOS
- [ ] WSL

## Output

<details><summary>Output</summary>

```log

<!-- paste console output here and remove this comment -->

```

</details>

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by Ericson2314** [comment]
Ask for help on discourse.nixos.org not here.
