### ISSUE TITLE
dev-shell appears to be broken

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#865]
~~Not sure if it works on Linux, but~~ if I fire up `dev-shell` I get a valid shell. Running `configure` then produces this output:

```
checking whether DBD::SQLite works... no
configure: error: in `/Users/copumpkin/Sandbox/nix':
configure: error: The Perl modules DBI and/or DBD::SQLite are missing.
See `config.log' for more details
```

Edit: it's broken on NixOS, too

**Comment by maurer** [comment]
I can replicate on NixOS, so this is not just a Darwin issue.

**Comment by copumpkin** [comment]
Aha, PEBKAC: I needed to run `configurePhase` instead of `configure`. Sorry for the noise!
