### ISSUE TITLE
Issue with go packages that use latest version of github.com/shoenig/go-m1cpu

### ISSUE THREAD

**Issue by CorbanR** [NixOS/nix#8651]
**Describe the bug**
There appears to be an issue with packages that use the later versions of `github.com/shoenig/go-m1cpu`. I don't think the issue is with `github.com/shoenig/go-m1cpu` directly. See https://github.com/shoenig/go-m1cpu/issues/5

So far the error can be seen in both `nomad` and `rclone`. See the example error below.(Ran `nix-build -E 'with import <nixpkgs> { }; callPackage ./default.nix { }'` from inside `nomad` folder on `master` branch.

```
 nix-build -E 'with import <nixpkgs> { }; callPackage ./default.nix { }'
this derivation will be built:
  /nix/store/psdaf1j3fk5z7z7pqxi53rzpkdd3aj0y-nomad-1.5.6.drv
these 2 paths will be fetched (57.67 MiB download, 158.16 MiB unpacked):
  /nix/store/w617m8r5pcp96g50k4lwzai4ddjpj5b3-nomad-1.2.16
  /nix/store/rv50wv3wbfafbdvllzkj7bd51s3i39fv-nomad-1.3.9
copying path '/nix/store/rv50wv3wbfafbdvllzkj7bd51s3i39fv-nomad-1.3.9' from 'https://cache.nixos.org'...
copying path '/nix/store/w617m8r5pcp96g50k4lwzai4ddjpj5b3-nomad-1.2.16' from 'https://cache.nixos.org'...
building '/nix/store/psdaf1j3fk5z7z7pqxi53rzpkdd3aj0y-nomad-1.5.6.drv'...
unpacking sources
unpacking source archive /nix/store/p0c06jzmy24wkhg5q2ydpipdkck9gyvp-source
source root is source
patching sources
updateAutotoolsGnuConfigScriptsPhase
configuring
building
Building subPackage ./.
# github.com/shoenig/go-m1cpu
vendor/github.com/shoenig/go-m1cpu/cpu.go:65:33: error: use of undeclared identifier 'kIOMainPortDefault'; did you mean 'kIOMasterPortDefault'?
   IOServiceGetMatchingServices(kIOMainPortDefault, matching, &iter);
                                ^~~~~~~~~~~~~~~~~~
                                kIOMasterPortDefault
/nix/store/fqlxrzgpr6hrkbrb060g6njfn5yr7b1y-apple-framework-IOKit-11.0.0/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:103:19: note: 'kIOMasterPortDefault' declared here
const mach_port_t kIOMasterPortDefault;
                  ^
1 error generated.
error: builder for '/nix/store/psdaf1j3fk5z7z7pqxi53rzpkdd3aj0y-nomad-1.5.6.drv' failed with exit code 1;
       last 10 log lines:
       > Building subPackage ./.
       > # github.com/shoenig/go-m1cpu
       > vendor/github.com/shoenig/go-m1cpu/cpu.go:65:33: error: use of undeclared identifier 'kIOMainPortDefault'; did you mean 'kIOMasterPortDefault'?
       >    IOServiceGetMatchingServices(kIOMainPortDefault, matching, &iter);
       >                                 ^~~~~~~~~~~~~~~~~~
       >                                 kIOMasterPortDefault
       > /nix/store/fqlxrzgpr6hrkbrb060g6njfn5yr7b1y-apple-framework-IOKit-11.0.0/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:103:19: note: 'kIOMasterPortDefault' declared here
       > const mach_port_t kIOMasterPortDefault;
       >                   ^
       > 1 error generated.
       For full logs, run 'nix log /nix/store/psdaf1j3fk5z7z7pqxi53rzpkdd3aj0y-nomad-1.5.6.drv'.
```

So far I get the same issue on both `Rclone` and `Nomad` packages. This seems like a relatively new issue as both `Rclone` and `Nomad` have recently updated the `github.com/shoenig/go-m1cpu package`

I believe this issue is related to `nix` and NOT the `go-m1cpu` as i'm able to checkout both `rclone` and `nomad` source repositories and run `go build` successfully. 

**Steps To Reproduce**

1. Try building latest version of `nomad` or `rclone` on an m2 mac using the latest nix derivation located at `pkgs/applications/networking/sync/rclone/` and `pkgs/applications/networking/cluster/nomad/` 
2. Example command `nix-build -E 'with import <nixpkgs> { }; callPackage ./default.nix { }'`

**Expected behavior**

Packages build correctly

**`nix-env --version` output**
`nix-env (Nix) 2.15.1`

**Additional context**
OSX 13.4.1, M2

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by abathur** [comment]
This sounds like a nixpkgs issue (not a nix one).

**Comment by cole-h** [comment]
Yes, please file this issue against Nixpkgs instead: https://github.com/NixOS/nixpkgs/issues
