### ISSUE TITLE
Nix installable resolution is actually impure for supposedly pure attributes like `nixosConfigurations`

### ISSUE THREAD

**Issue by roberth** [NixOS/nix#8665]
**Describe the bug**

Let me be clear. We usually don't want to ignore the context of a Nix CLI invocation. `nix run` should not require users to specify their platform.

However, in some cases we do want to ignore the CLI context. For instance, `nixosConfigurations` is _not_ behind a system attribute set, because a machine configuration should be built in *one* way only. Reproducibly.

It would seem that the documented schema enforces this. No system attribute means one way to do it, but this is actually not the case, and users are finding out. I'll try not to proliferate the bad idea, but it involves installable resolution. So I'll jump to the solution instead.

**Steps To Reproduce**

Intentionally omitted.

**Expected behavior**

Nix implements a flag so that `currentSystem` is not used during installable resolution. I believe this comes down to treating the fragment as a literal attribute path without *any* lookup trickery.
`nixos-rebuild` passes this flag.

**`nix-env --version` output**

**Additional context**

Even `nixpkgs.buildPlatform` would be a massive impurity not to be overlooked by a flake's git history.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by gytis-ivaskevicius** [comment]
If the proposal is to change `nixosConfigurations` schema (like doing `nixosConfigurations.<system>.<hostname>`) then I'd appreciate it if this was to be implemented as well https://github.com/NixOS/nix/issues/6257

**Comment by blaggacao** [comment]
**More Context on `home-manager`**

Home Manager users are [fundamentally system-portable](https://github.com/nix-community/home-manager/issues/2161). Advancement here could trigger evolution there.

**Comment by roberth** [comment]
This doesn't change the schema. The schema can be discussed at #6257.
