### ISSUE TITLE
Cycle detection in `nix repl` output doesn't match `nix-instantiate`

### ISSUE THREAD

**Issue by sternenseemann** [NixOS/nix#8672]
**Describe the bug**

```console
[nix-shell:~]$ nix repl 
Welcome to Nix 2.15.1. Type :? for help.
nix-repl> :p let x = { inherit x; }; in x
{ x = { x = «repeated»; }; }
[nix-shell:~]$ nix-instantiate --eval --strict -E 'let x = { inherit x; }; in x'
{ x = «repeated»; }
```

**Expected behavior**

`nix-instantiate` and `nix repl` print cycles the same way for the same expression.

**Comment by iFreilicht** [comment]
Very good find! The source code for these two is very similar, and there's even a comment in `repl.cc`:

```
// FIXME: lot of cut&paste from Nix's eval.cc.
```

So definitely something that's intended to be fixed. I assume the direction will be to keep the behaviour of `nix-instantiate` and change that of `nix repl`, as the latter doesn't need to have such a stable interface. I'll have a look at this tomorrow, might be a relatively easy fix.

**Comment by iFreilicht** [comment]
Ok so after looking at it a little bit, I saw there were no tests for the current repl behavior, so I added some in #8840. I also found this to actually cause even more confusion than I thought initially:

```
nix-repl> :p let x = { y = { a = 1; }; inherit x; }; in  x
{ x = { x = «repeated»; y = { a = 1; }; }; y = «repeated»; }
```

vs.

```
nix-instantiate --eval --strict -E 'let x = { y = { a = 1; }; inherit x; }; in  x'
{ x = «repeated»; y = { a = 1; }; }
```

It would be very nice to get the latter in the repl, especially when inspecting derivations, but it's not as trivial of a change as I thought:

The two scenarios have different evaluation strategies right now. `repl` is very ad-hoc and only evaluates what will be printed, which is especially useful when a value is printed without `:p`, while `instantiate` of deeply evaluates the entire set at once and only prints it afterwards, which might not be feasible in the repl for some cases, but means that it knows that `x` is `«repeated»` one recursion step earlier.

The way the repl works right now also has the nice side-effect of progressive output, where printing large sets will yield output pretty much immediately and continue to yield more as the attributes of the set are recursively evaluated. With the `nix-instantiate` approach, this is not possible. You have to wait until everything is evaluated before you can start producing any output.

Right now it seems impossible to me to have both features, immediate cycle detection and progressive output, in one command.

**Comment by iFreilicht** [comment]
Maybe there's a way to start with progressive output, and then replace that with the fully evaluated one? Potentially the progressive output could scroll through on a single line like build output does with `nix build` right now.
