### ISSUE TITLE
`include` directive in nix.conf has no effect

### ISSUE THREAD

**Issue by amarshall** [NixOS/nix#8719]
**Describe the bug**

The `include` directive in nix.conf has no effect in 2.16.1 (also tested in current master 453c4be93cb10b417a7140d9f8b7185f9785b7a6, same result)

**Steps To Reproduce**

```
# /etc/nix/nix.conf
substituters = https://cache.nixos.org/
include nix.local.conf
```
```
# /etc/nix/nix.local.conf
extra-substituters = http://foo.example
```

**Expected behavior**

Results of `nix show-config`:

- Expected to include: `substituters = https://cache.nixos.org/ http://foo.example`
- Actually includes: `substituters = https://cache.nixos.org/`

**`nix-env --version` output**

nix-env (Nix) 2.16.1

**Additional context**

The issue does not occur on Nix 2.15.1. There is no `{~,~root}/.config/nix/nix.conf`.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by bouk** [comment]
Ah this is because the change made it so the `include` file is applied *before* the contents of `nix.conf`, because it now builds up the `parsedContents` vector. Should be an easy fix

**Comment by Ericson2314** [comment]
That's right, thanks @bouk.

**Comment by bouk** [comment]
Opened a PR at https://github.com/NixOS/nix/pull/9233
