### ISSUE TITLE
Improve the last line of error message

### ISSUE THREAD

**Issue by Freed-Wu** [NixOS/nix#8729]
## Current Behaviour

```
For full logs, run 'nix log /nix/store/sj3mfkqx5if8sxm8p2hw4cqcsh8349p9-intel-oneapi-compiler-dpcpp-cpp-runtime-2023.1.0.drv'.
```

## Expected Behaviour

```
For full logs, run:
  nix log /nix/store/sj3mfkqx5if8sxm8p2hw4cqcsh8349p9-intel-oneapi-compiler-dpcpp-cpp-runtime-2023.1.0.drv
```

It will be easier to copy correct code, because original behavior is easy to copy wrong code `'nix log /nix/store/XXX.drv'.` or `'nix log /nix/store/XXX.drv'` or `'nix log /nix/store/XXX.drv`.

**Comment by iFreilicht** [comment]
Additionally, copying in some shell emulators would now work with a triple-click, where this defaults to selecting the whole line from the first to the last non-whitespace character.

**Comment by Freed-Wu** [comment]
https://github.com/NixOS/nix/blob/master/src/libstore/build/derivation-goal.cc#L997 fix it.
