### ISSUE TITLE
Recursive overlays

### ISSUE THREAD

**Issue by musjj** [NixOS/nix#8743]
**Is your feature request related to a problem? Please describe.**
Some packages are nested, e.g. `vimPlugins`, `mpvScripts`. Overlaying custom packages to these sets is a bit annoying, because you need to manually extend them.

**Describe the solution you'd like**
These package sets are already marked as such (with `recurseIntoAttr`), so it would be nice if they can be automatically merged recursively.

This way, you can just index your custom packages like this:

`pkgs.nix`
```nix
{ pkgs ? (import <nixpkgs>) { } }: {
  some = package;
  more = packages;
  mpvScripts = pkgs.lib.recurseIntoAttr {
    foo = pkgs.callPackage ./bar.nix
  };
}
```

And now you can just drop it straight into your overlays:

`configuration.nix`
```nix
nixpkgs.overlays = [ 
  final: prev: import ./pkgs.nix
];
```

**Describe alternatives you've considered**
For now, if you want to extend the packages inside these sets, you need to treat it specially with `.extend`:

```nix
_: prev: {
  vimPlugins = prev.vimPlugins.extend (_: _: {
    foo = bar;
  });
}
```

or for plain attribute sets, with `//`:

```nix
_: prev: {
  mpvScripts = prev.mpvScripts // {
    foo = bar;
  });
}
```

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by Ericson2314** [comment]
This looks like a Nixpkgs issue. I don't have permission to transfer it to that repository however (I don't think?).

**Comment by musjj** [comment]
I'll move it there, then. That repository doesn't have a feature request template, so I though this repository would be a better fit.
