### ISSUE TITLE
Can't use `nix copy` from macOS to Linux without installing zsh first

### ISSUE THREAD

**Issue by tfc** [NixOS/nix#8750]
**Describe the bug**

After discovering https://github.com/NixOS/nix/issues/8745, i realized that i can't use `nix copy` on macOS generally, if zsh is not installed to `~/.nix-profile/bin/zsh`:

```sh
macos ~ $ nix copy --to ssh://host $(nix build nixpkgs#hello --print-out-paths)                                                                                                     
Couldn't execute /Users/user/.nix-profile/bin/zsh -c "echo started": No such file or directory
# hangs forever, so i do ctrl+c

error: interrupted by the user
macos ~ $ nix copy --to ssh-ng://host $(nix build nixpkgs#hello --print-out-paths)                                                                                                     
Couldn't execute /Users/user/.nix-profile/bin/zsh -c "echo started": No such file or directory
# hangs forever, so i do ctrl+c
error: interrupted by the user

macos ~ $ nix profile install nixpkgs#zsh

macos ~ $ nix copy --to ssh://host $(nix build nixpkgs#hello --print-out-paths)   
# now it works!
```

**Expected behavior**

I would expect `nix copy` to work without having to install a specific shell to my user env (as it is already installed globally).

**`nix-env --version` output**

```sh
λ ~/ nix-env --version                                                                                                                                                                              
nix-env (Nix) 2.15.0
```

**Comment by abathur** [comment]
I don't think Nix is trying to run zsh.

I'm not familiar with the code, but here's where the failing statement comes from:

https://github.com/NixOS/nix/blob/2d1d81114d72ace89ce08cd3bc93f4eb27a2975d/src/libstore/ssh.cc#L41

Nix is just passing a flag to ssh, and the [ssh documentation for the option](https://man.openbsd.org/ssh_config.5#LocalCommand) says:

> Specifies a command to execute on the local machine after successfully connecting to the server. The command string extends to the end of the line, and is executed with the user's shell.

This suggests that your user's shell is set to `/Users/user/.nix-profile/bin/zsh`. This might not be causing problems in ~normal use if your terminal application is configured to run some specific shell that does exist. You could confirm this by running:

```bash
dscl . -read /Users/$USER UserShell
```
