### ISSUE TITLE
Can't download Holochain scaffold via nix on Manjaro Linux

### ISSUE THREAD

**Issue by sophyphreak** [NixOS/nix#8797]
## Platform

- [ X ] Linux: Manjaro Linux
- [ ] macOS
- [ ] WSL

## Additional information

I'm trying to get the development environment for Holochain working on this computer. Installation works fine on my friend's Ubuntu environment and in my WSL2 Ubuntu environment on Windows. I've tried this on two computers with Manjaro, and both get the same error message.

I'm following these instructions: https://developer.holochain.org/quick-start/

## Output

<details><summary>Output</summary>

```log

nix run --refresh -j0 -v github:holochain/holochain#hc-scaffold -- --version                                                                                                                
zsh: no matches found: github:holochain/holochain#hc-scaffold

```

</details>

## Priorities

Working in the Holochain developer environment

**Comment by knedlsepp** [comment]
This is due to the use of the character `#`, which needs to be escapes in `zsh`: `\#`. See also: https://github.com/NixOS/nix/issues/4686

**Comment by sophyphreak** [comment]
> This is due to the use of the character `#`, which needs to be escapes in `zsh`: `\#`. See also: #4686

Hey, thanks! That fixed it!
