### ISSUE TITLE
Useless and incorrect error message

### ISSUE THREAD

**Issue by 0xABAB** [NixOS/nix#882]
This is what I get:
```
trace: warning: passing a comma-separated string for filesystem options is deprecated; use a list of strings instead. This will become a hard error in 16.09.
```

I am *not* specifying a comma-separated string *anywhere* in my configuration, yet I get this message, which is likely caused by some NFS configuration, which in turn is a NixOS module, which means that it is ridiculous that I as a user get to see this in a released version of NixOS. 

Additionally, existential error messages are the sign of people who want to waste my time at work. How much work was it really to output the string to stderr, such that at least there was a shred of evidence that something was really wrong? It might even have saved you this bug report. 

For future reference, I would like to never ever see new commits going into this project which give existential error messages not involving end user input. If you do not agree on this (which I cannot imagine any skilled engineer to do), can you please explain why?

**Comment by copumpkin** [comment]
I'd file this bug against nixpkgs, as far fewer people look at the bugtracker in here, and the code generating that error message lives over there.

I considered giving you an "existential" pointer to nixpkgs, but here's the actual reference https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/tasks/filesystems.nix#L51 😄 

See also https://github.com/NixOS/nixpkgs/pull/10518 and cc @aneeshusa

**Comment by aneeshusa** [comment]
@0xABAB if you re-open this issue against the nixpkgs repo, I'd be happy to take a look.

Please include the output of `nixos-version`, as well as from running `nixos-rebuild` with the `--show-trace` flag when you re-open.
