### ISSUE TITLE
build fails on my machines, but not [for] others: `martinvonz/jj`

### ISSUE THREAD

**Issue by colemickens** [NixOS/nix#8843]
**Describe the bug**

Hi,

All of the sudden, on various machines of mine, I'm unable to build `jj`, due to test failures:

```
❯ nix build github:martinvonz/jj/32d622863a773e4826a35e2a6da0f696f68f06df -L &> /tmp/log                                                                   
```

and then looking at the relevant snippet of log:

```
jujutsu-unstable> --- STDERR:              jj-lib::test_bad_locking test_bad_locking_children::git_backend ---                                             
jujutsu-unstable> thread 'test_bad_locking_children::git_backend' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 5, kind: Uncategoriz
ed, message: "Input/output error" }', lib/tests/test_bad_locking.rs:48:54  
```

Some sort of generic `Input/output error`...

However, other users on the `jj` repo report they're able to build it. (https://github.com/martinvonz/jj/issues/2103). And sure enough, if I pin a revision from last week that I know was building... it does not build for me.

Did something happen with the nix sandbox (I do use unstable), possibly?

```
❯ nix --version
nix (Nix) 2.17.0
```

**Comment by tomberek** [comment]
Worked on mine. Perhaps number of cores? Look at the locking mechanism used in the test?

**Comment by colemickens** [comment]
```
nu─▶  $env.NIX_BUILD_CORES = 1
nu─▶  nix build -L github:martinvonz/jj --option 'cores' '1' -j1 
```

got it to build, surely a flakey-tests issue, not a nix issue. Closing. Thanks!
