### ISSUE TITLE
Minor incorrectness in documentation of multiline string

### ISSUE THREAD

**Issue by federkamm** [NixOS/nix#8851]
## Problem

`https://github.com/NixOS/nix/blob/master/doc/manual/src/language/index.md` says in `Overview` that the multiline string

```
''
  multi
   line
    string
''
```

would evaluate to `"multi\n line\n string"`, but that's wrong.

## Proposal

It evaluates to `"multi\n line\n  string\n"` (note two spaces before `string` and a trailing `\n`). (Checked with nix 2.17.0, nix-command `nix repl`.)

## Checklist

- [X] checked [latest Nix manual] \([source])
- [X] checked [open documentation issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/src
[open documentation issues and pull requests]: https://github.com/NixOS/nix/labels/documentation

## Priorities

No priority but easy to fix.

**Comment by fricklerhandwerk** [comment]
This is in fact [correct in the source](https://github.com/NixOS/nix/blob/3ce793d3e90ec409b94872805ddef1ebb9c20422/doc/manual/src/language/index.md#L86), but something in mdBook processing seems to swallow the second space character. Workaround in #9012
