### ISSUE TITLE
error: '/home/user/.nix-profile' is not a symlink

### ISSUE THREAD

**Issue by GeekOfTheWild** [NixOS/nix#8855]
I have recently installed NixOS, but am unable to install packages using nix-env and unable to add home-manager using nix-shell wich gives the following error: error: '/home/geekofthewild/.nix-profile' is not a symlink. I've tried nix-env --switch-profile /nix/var/nix/profiles/default, but that says error: filesystem error: cannot rename: Is a directory [/home/uesr/.1_.nix-profile] [/home/user/.nix-profile]. I installed NixOS using Calamares. Any idea on how this could be fixed?
Thanks in advance

**Comment by GeekOfTheWild** [comment]
So I've managed to fix this (although in quite a hacky way) by copying my root's ~/.nix-profile to /home/user, and then running sudo chmod 777 /nix/var/nix/profiles/  which I know I should not be doing but it's the only things I could get to work

**Comment by RayyanNafees** [comment]
Still an issue with latest NixOS WSL 
![image](https://github.com/user-attachments/assets/9f499f41-59df-4ea8-92a7-a631564f498d)
