### ISSUE TITLE
NIX_PATH and -I ignored by nix-env

### ISSUE THREAD

**Issue by FRidh** [NixOS/nix#886]
The `-I` option is ignored when used with `nix-env`, and so is $NIX_PATH. Both do work fine with `nix-shell`.

Example:
```
freddy@fr-laptop:~/Code/libraries/nixpkgs$ nix-env -i offlineimap -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-15.09.tar.gz
downloading ‘https://github.com/NixOS/nixpkgs-channels/archive/nixos-15.09.tar.gz’... [12285/13143 KiB, 1498.3 KiB/s]
unpacking ‘https://github.com/NixOS/nixpkgs-channels/archive/nixos-15.09.tar.gz’...
warning: name collision in input Nix expressions, skipping ‘/home/freddy/.nix-defexpr/channels_root/nixos’
replacing old ‘offlineimap-6.7.0’
installing ‘offlineimap-6.7.0’
```
whereas in 15.09 we have 6.5.7
https://github.com/NixOS/nixpkgs/blob/release-15.09/pkgs/tools/networking/offlineimap/default.nix
Using attribute (`-A`) instead makes no difference.
```
$ nixos-version
16.09.git.470ad74 (Flounder)
```

**Comment by edolstra** [comment]
That's because `nix-env` by default uses `~/.nix-defexpr` as the installation source. If you want to use `<nixpkgs>`, you have to state that explicitly:
```
$ nix-env -f '<nixpkgs>' -i bla -I nixpkgs=http://foo
```
Of course, then it's shorter to do
```
$ nix-env -f http://foo -i bla
```
