### ISSUE TITLE
Debian packages do not exist for the stable Nix release

### ISSUE THREAD

**Issue by mversweyveld** [NixOS/nix#887]
At our company we're using Nix on an Ubuntu infrastructure, and would like to install it via the provided debian packages.  However, there do not seem to be released debian packages available for the latest stable Nix (1.11.2).

Browsing through the Hydra UI, I would expect to find the latest stable Debian packages here:

http://hydra.nixos.org/release/nix/nix-1.11.2

But all the download links yield "404 Not Found".

Alternatively, the "Getting Nix" page provides this link: http://nixos.org/releases/nix/

But the archived releases, e.g. http://nixos.org/releases/nix/nix-1.11.2/ do not include debian packages at all.

**Comment by ehmry** [comment]
I don't think there is enough interest in mantaining Debian packages, once Nix is installed it can update itself through channels.

**Comment by edolstra** [comment]
The Hydra "releases" feature is broken since Hydra started building directly to S3. (The old releases never got copied to S3.)

Related: https://github.com/NixOS/hydra/issues/282

**Comment by vcunat** [comment]
So, until that's fixed, one should use links like this?
http://hydra.nixos.org/job/nix/maintenance/deb_ubuntu1404x86_64/latest

**Comment by edolstra** [comment]
I've mirrored the files from the Hydra releases to `http://nixos.org/releases/nix/`, e.g. http://nixos.org/releases/nix/nix-1.11.2/deb_ubuntu1504x86_64/nix_1.11.2-1_amd64.deb. Note however that the Debian/Fedora packages are not well tested, which is why we don't advertise them anymore.

**Comment by goodwillcoding** [comment]
@edolstra I know you closed the issue but I am wonder if you have an answer to the other part. Are the packages also supposed to be available here: http://hydra.nixos.org/release/nix/nix-1.11.2 ? It appears they are cleaned out? Should that have a different behavior? 

I know it is more of a hydra question but I thought I'd ask it in the thread.

**Comment by edolstra** [comment]
They were available there, but they didn't get copied to cache.nixos.org when we switched to the new S3-based queue runner. I guess it would be better to delete the releases from Hydra to prevent confusion.

**Comment by Telofy** [comment]
Thanks for asking and answering! Can someone who’s in the know update [this wiki page](https://nixos.org/wiki/Installing_Nix_on_Debian), please? It was the first thing I found trying to install it.

**Comment by vcunat** [comment]
That's a bit hard, as the wiki is read-only now; short explanation: https://github.com/NixOS/nixpkgs/milestone/8. It would be nice if we had a big banner in the wiki explaining the situation.

**Comment by Telofy** [comment]
Oh, okay. Good luck with that!
