### ISSUE TITLE
Start a Flakes milestone list

### ISSUE THREAD

**Issue by roberth** [NixOS/nix#8870]
**Is your feature request related to a problem? Please describe.**

The community wants to know when flakes are done. Some want to know how to contribute. Others just wonder what it will take to stabilize the feature.

**Describe the solution you'd like**

We should communicate better why flakes aren't stable yet.

Manage expectations.
The list won't be complete at first.
Not all issues may be fixable (although we'd need some damn good reasons to reject problems, subjectively).

**Describe alternatives you've considered**

- Don't lead and let the community down.
- Explicitly postpone this for after we finish CLI stabilization. This would be incomprehensible to most community members, it would be bad communication, and bad planning.

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by zmitchell** [comment]
Strongly in favor of this, communicating progress can help the community feel less like flake stabilization is only going to happen some day in an idealistic future

**Comment by edolstra** [comment]
Related: https://github.com/NixOS/nix/issues/5881

**Comment by roberth** [comment]
@grahamc 

> Any timeline on the Nix team identifying the core issues at stake?

First off, I believe this is not _just_ up to the team, although the team has knowledge about such issues. The team _is_ responsible for making some decisions that lead to the stabilization, as we have a responsibility not to merge features with significant, known, solvable flaws as non-experimental. We strive to make such decisions on technical merit, as is appropriate for a mature¹ infrastructure project like Nix.

We don't have a timeline, as [accepted RFC 136](https://github.com/NixOS/rfcs/blob/master/rfcs/0136-stabilize-incrementally.md) prioritizes the stabilization of `nix-command` aka new cli aka `nix (3)` (not to be confused with Nix 3.0, which would (imo) imply a (significant) breaking change to a non-experimental feature for which we don't seem to have an appropriate reason for that yet).

We're an underfunded² OSS maintenance team, not a commercial development team with a budget to deliver a feature. We can right this ship with others' help, but we can not give a timeline for efforts we don't control.

If a timeline magically appears, it will be for CLI stabilization, as suggested by the RFC. Don't expect a timeline. Instead consider what _you_ can do.

That all said, you can expect us to make a _start_ on the list soon. I would have started a list on Monday, but I couldn't partake in the meeting due to unforeseeable circumstances. I consider this to be part of improving our communications more so than actual planning, as discussed.

¹: Mature in the sense of its existence and role in the ecosystem. Matur<i>ing</i> in the sense of development standards. We are still recovering from a long lasting lack of leadership in this area, which is unfortunate and perhaps surprising.

²: Regarding maintenance, we've barely kept the PR backlog stable at around 300 PRs over the past ~year. That is in fact a major accomplishment, because the new PRs certainly haven't stopped coming, and it is a major improvement over the state of maintenance before the team was formed. It wouldn't be appropriate to discuss the team's state of activities as a comment side note, so I will leave you with the partial info.

**Comment by grahamc** [comment]
So happy to see a milestone created: https://github.com/NixOS/nix/milestone/27

Since this ticket is to start a flakes milestone list, perhaps this ticket is ✅ ?

**Comment by fricklerhandwerk** [comment]
Closed by the existence of https://github.com/NixOS/nix/milestone/27
