### ISSUE TITLE
`nix profile install` errors with "directory not found"

### ISSUE THREAD

**Issue by hybras** [NixOS/nix#8872]
### Describe the bug

I get the following message with any usage of `nix profile install`

```
error: opening directory '/nix/var/nix/profiles/per-user/$USER': No such file or directory
```

Manually resolving the above (creating the dir) yields this:

```
error: creating symlink from '/nix/var/nix/profiles/per-user/$USER/profile-1-link.tmp-2725-1812569790' to '/nix/store/h584yr8z74c8s7czpswk2bgqhd526mv9-profile': Permission denied
```

If you have a problem with a specific package or NixOS,
you probably want to file an issue at https://github.com/NixOS/nixpkgs/issues. 

### Steps To Reproduce

`nix profile install nixpkgs#nix-direnv` (or anything from nixpkgs)

 ### Expected behavior

Package installs and is availible on my path.

**`nix-env --version` output**: 2.17.0

### Additional context

* Installed using determinate systems installer

* Using flakes and new nix cli.
* Other commands like `nix develop` and `nix run` work
* Macos ventura 13.5.1, m1

**Comment by abathur** [comment]
Sounds like this might be:
- https://github.com/DeterminateSystems/nix-installer/issues/477

**Comment by hybras** [comment]
Thank you, will follow that issue instead
