### ISSUE TITLE
`nix flake check` should log what it checks

### ISSUE THREAD

**Issue by 9999years** [NixOS/nix#8882]
As of Nix 2.17.0, when I run `nix flake check`, the output doesn't tell me what was checked:

```ShellSession
$ nix flake check
warning: The check omitted these incompatible systems: aarch64-linux, x86_64-darwin, x86_64-linux
Use '--all-systems' to check all.
```

I can add `--print-build-logs`, which is helpful if some checks haven't been run, but once everything is cached this adds no additional output.

`--verbose` doesn't help much either:

```ShellSession
$ nix flake check --verbose
evaluating flake...
running flake checks...
warning: The check omitted these incompatible systems: aarch64-linux, x86_64-darwin, x86_64-linux
Use '--all-systems' to check all.
```

`--debug` includes a ton of data, but it's so dense and cluttered that it's not really useful for this.

I'd like the output to show each check that was performed, like this:

```
$ nix flake check
✔ checks.aarch64-darwin.my-check is a derivation: /nix/store/kiiw4mx4p8cfmr5f9ci07xnwyp19wk9s-my-check
✔ devShells.aarch64-darwin.default is a derivation: /nix/store/kiiw4mx4p8cfmr5f9ci07xnwyp19wk9s-shell
✔ overlays.default is an overlay
✗ overlays.default argument names are not `final` and `prev`
```

**Comment by tomberek** [comment]
Addressed by #8893.
