### ISSUE TITLE
Can't install on steam deck

### ISSUE THREAD

**Issue by jurassicjordan** [NixOS/nix#8884]
## Platform

- [X ] Linux: Archlinux SteamOS
- [ ] macOS
- [ ] WSL

## Additional information

Attempting to install spits out an error

## Output

<details><summary>Output</summary>

```log

I am executing:

    $ sudo HOME=/root /nix/store/3wqasl97rjiza3vd7fxjnvli2w9l30mk-nix-2.17.0/bin/nix-env -i /nix/store/3wqasl97rjiza3vd7fxjnvli2w9l30mk-nix-2.17.0

to install a bootstrapping Nix in to the default profile

installing 'nix-2.17.0'
error: the user 'nixbld01' in the group 'nixbld' does not exist

---- oh no! --------------------------------------------------------------------
Oh no, something went wrong. If you can take all the output and open
an issue, we'd love to fix the problem so nobody else has this issue.

:(

We'd love to help if you need it.

You can open an issue at
https://github.com/NixOS/nix/issues/new?labels=installer&template=installer.md

Or get in touch with the community: https://nixos.o

```

</details>

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by abathur** [comment]
AFAIK the official installer doesn't support this yet. (I believe the unofficial third-party installer that DeterminateSystems maintains has support for it, if you want to try that approach.)

Tentatively closing in favor of https://github.com/NixOS/nix/issues/7173, but I'm happy to reopen it if you feel like the state of discussion in that issue implies this should be working now? (I admit I'm not really in the loop on this...)
