### ISSUE TITLE
Request for .deb for Xenial (Ubuntu 16.04) 

### ISSUE THREAD

**Issue by karltk** [NixOS/nix#891]
Build page:
https://hydra.nixos.org/job/nix/master/release#tabs-constituents

Latest Ubuntu targeted:
`deb_ubuntu1504x86_64`

Using that package on Xenial gives:
`$ nix-build <anything>`
/usr/bin/perl: symbol lookup error: /usr/lib/perl5/site_perl/5.20.2/x86_64-linux-gnu-thread-multi/auto/Nix/Store/Store.so: undefined symbol: Perl_xs_apiversion_bootcheck
`$ perl --version`
This is perl 5, version 22, subversion 1 (v5.22.1) built for x86_64-linux-gnu-thread-multi

**Comment by domenkozar** [comment]
On it.

**Comment by domenkozar** [comment]
Added images in https://github.com/NixOS/nixpkgs/commit/8a3b70791c4b643822eb5feb3f9e23ec5e56b863

**Comment by domenkozar** [comment]
I have the following change:

```nix
diff --git a/release.nix b/release.nix
index 79df103..fe6621f 100644
--- a/release.nix
+++ b/release.nix
@@ -199,6 +199,10 @@ let
     deb_ubuntu1410x86_64 = makeDeb_x86_64 (diskImageFuns: diskImageFuns.ubuntu1410x86_64) [];
     deb_ubuntu1504i386 = makeDeb_i686 (diskImageFuns: diskImageFuns.ubuntu1504i386) [ "libsodium-dev" ];
     deb_ubuntu1504x86_64 = makeDeb_x86_64 (diskImageFuns: diskImageFuns.ubuntu1504x86_64) [ "libsodium-dev" ];
+    deb_ubuntu1510i386 = makeDeb_i686 (diskImageFuns: diskImageFuns.ubuntu1510i386) [ "libsodium-dev" ];
+    deb_ubuntu1510x86_64 = makeDeb_x86_64 (diskImageFuns: diskImageFuns.ubuntu1510x86_64) [ "libsodium-dev" ];
+    deb_ubuntu1604i386 = makeDeb_i686 (diskImageFuns: diskImageFuns.ubuntu1604i386) [ "libsodium-dev" ];
+    deb_ubuntu1604x86_64 = makeDeb_x86_64 (diskImageFuns: diskImageFuns.ubuntu1604x86_64) [ "libsodium-dev" ];

```

but I'm getting an error:

```
$ nix-build -A deb_ubuntu1604x86_64 release.nix -I ~/dev
Preparing to unpack .../nix_1.12pre1234-abcdef-1_amd64.deb ...
Unpacking nix (1.12pre1234-abcdef-1) ...
dpkg: dependency problems prevent configuration of nix:
 nix depends on libsodium13; however:
  Package libsodium13 is not installed.

dpkg: error processing package nix (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 nix
[  182.740216] reboot: Power down
```

cc @edolstra

**Comment by domenkozar** [comment]
I see now, libsodium got upgraded. Working on the fix.

**Comment by karltk** [comment]
Yeah, there's both libsodium13 and libsodium18. I guess you get libsodium18 by default if you depend on libsodium-dev. I supposed you could depend on libsodium13-dev, or adjust nix to work against libsodium18.

**Comment by vcunat** [comment]
On nixpkgs master, nix is built against libsodium.18.so, so I think we only need to change the dependency specification.

**Comment by vcunat** [comment]
It will probably have to be conditional, as some Debian/Ubuntu versions only have 13 and others only 18.

**Comment by copumpkin** [comment]
Our distro packages are linked against host versions of libraries? Why not just have the .deb download the nix closure and go from there?

**Comment by domenkozar** [comment]
See https://github.com/NixOS/nix/pull/892

**Comment by domenkozar** [comment]
This can be closed now. We don't have "maintainer" branch for Nix so really you can only build the deb manually.

We should probably open an issue to have a maintenance branch updated.

**Comment by vcunat** [comment]
> We don't have "maintainer" branch for Nix

I don't understand what you mean. There's https://hydra.nixos.org/jobset/nix/maintenance pulling from `1.11-maintenance` branch, so I assume we want to pick #892 into it.

**Comment by domenkozar** [comment]
Done: http://hydra.nixos.org/eval/1275755

**Comment by bjornfor** [comment]
I followed that link to get the Ubuntu 16.04 .deb package. I found this URL, but it's dead: http://hydra.nixos.org/build/36401064/download/1/nix_1.11.2-1_amd64.deb

**Comment by domenkozar** [comment]
Yes, since Hydra now pushes everything to S3 those files aren't available.

Use `nix-store -r /nix/store/zbkc1c66p0mlp3603zpjrg8ajxfz8nnj-nix-deb-ubuntu-16.04-xenial-amd64-1.11.2/`

**Comment by domenkozar** [comment]
Note that this is somewhat unfortunate that you have to use nix to install Nix :(

**Comment by kvz** [comment]
> Note that this is somewhat unfortunate that you have to use nix to install Nix :(

Running into this now. I'm new to Nix and like the idea a lot. I'd like to buy into part of the ecosystem now to get a feel, but it would require me to run the installer script on Ubuntu Xenial as there don't appear to be any official versioned debs. I think this means I could get a new version of Nix with every new server I provision, which kind of defeats the purpose of using Nix as there may be surprises at execution time then. 

Or perhaps there's another way to go about this? Or unintended Nix upgrades are perfectly harmless?

**Comment by vcunat** [comment]
@kvz: http://hydra.nixos.org/job/nix/maintenance/deb_ubuntu1604x86_64/latest

**Comment by vcunat** [comment]
BTW, have I missed some reason why such packages aren't linked from http://nixos.org/nix/download.html ?

**Comment by kvz** [comment]
Revisiting Nix, and having trouble again finding a good build. Clicking the link posted 

>http://hydra.nixos.org/job/nix/maintenance/deb_ubuntu1604x86_64/latest

now results in a 

> File /nix/store/4fqblvlmkwf7jdq8jh69c4rs8j31vi0r-nix-deb-ubuntu-16.04-xenial-amd64-1.11.7/debs/nix_1.11.7-1_amd64.deb has disappeared.

Checking the wiki at https://nixos.org/wiki/Installing_Nix_on_Debian states it's outdated, and indeed, gives a 404.

Checking http://nixos.org/nix/download.html has no ubuntu/debian builds, nor does http://nixos.org/releases/nix/nix-1.11.7/ it seems. 

Delving through https://hydra.nixos.org, it's easy for a noob like me to get lost and confused about what an appropriate debian/ubuntu package would be.

This likely is one of the first steps newcomers would take, and it's rather hard 😄

**Comment by edolstra** [comment]
We don't currently provide Deb/RPM packages, sorry. Hydra does build them for portability testing, but they're not available for download because they're not well tested. The supported installation method is to download the binary tarball, see http://nixos.org/nix/download.html.

**Comment by kvz** [comment]
Okay, thanks for the quick response!
