### ISSUE TITLE
Build conflict after trying to install different versions of java

### ISSUE THREAD

**Issue by dhasial** [NixOS/nix#8910]
**Describe the bug**

Tried to install different versions of java from nixpkgs-unstable, got build conflict instead. I may well just be misunderstanding something.

**Steps To Reproduce**

1. Install nix via arch's `pacman`
2. Add unstable channel
3. Do `nix-env -iA nixpkgs.graalvm17-ce` successfully.
4. Then attempt to install two other java versions with `nix-env -iA nixpkgs.jdk17 nixpkgs.jdk8`
5. Get  [the following output](https://gist.github.com/dhasial/d32abfe973e21d14ec9a3310f59a7c09) (except for the unrelated error on the top two lines)

This occurs regardless of what order I try to install `nixpkgs.jdk17` `nixpkgs.jdk8` in.

**Expected behavior**

Expect to be able to install different versions of packages which contain what would ordinarily be conflicting files.

**`nix-env (Nix) 2.17.0` output**

**Comment by Artturin** [comment]
Open a nixpkgs issue.
