### ISSUE TITLE
Freshly installed system takes too long to shutdown on virtualbox

### ISSUE THREAD

**Issue by anakimluke** [NixOS/nix#8926]
**Describe the bug**

An installation of nixos with a desktop manager on virtualbox has an unexpected delay when shutting down/rebooting.

**Steps To Reproduce**

1. Create a virtualbox machine and follow installation instruction manual normally.
2. When the time comes to edit the configuration.nix file, uncomment the line `boot.loader.grub.device = "/dev/sda";` and the line `services.xserver.enable = true;`.
3. Add the line `services.xserver.desktopManager.xfce.enable = true;`
4. Continue the installation process.
5. When it is finished, remove the nixos iso from the machine and reboot.
6. When lightdm pops up, login as root.
7. Reboot.
8. Notice the message `A stop job is running for Session 2 of User root (10s / 1min 29s)`, and how the system will only continue to showdown after the timer has finished.

**Expected behavior**

Expected for the system to shutdown immediately, without waiting 1min and 30s.

**`nix-env --version` output**

`nix-env (Nix) 2.13.5`

**Additional context**

Inspecting the log with `journalctl -p5` I was able to find that the stop job was related to the VBoxClient process.
This problem is not present using `pkill -9 VBoxClient` before rebooting.  

This problem is not present when rebooting from lightdm without loging in into xfce.
The problem is still present when using gdm with plasma5.

**Comment by bjornfor** [comment]
This bug should be fixed against nixpkgs, not nix.
