### ISSUE TITLE
nix-env manual page doesn't describe -A or other short options

### ISSUE THREAD

**Issue by diekhans** [NixOS/nix#8960]
## Problem

`nix-env -iA` is frequently mentioned as how to install packages, but this is not in the manual page  -A is not documented at all, nor are any of the single character options.
Using --help is of no help ;-)

## Checklist

- [ x checked [latest Nix manual] \([source])
- [ x] checked [open documentation issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/src
[open documentation issues and pull requests]: https://github.com/NixOS/nix/labels/documentation

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by elikoga** [comment]
https://nixos.org/manual/nix/unstable/command-ref/nix-env/install

> If --attr (-A) is specified, the arguments are attribute paths that select attributes from the top-level Nix expression. This is faster than using derivation names and unambiguous. To find out the attribute paths of available packages, use nix-env --query --available --attr-path .

**Comment by diekhans** [comment]
oh nice, somehow I didn't fine that!

thanks
