### ISSUE TITLE
Unclear how unittest finer-grained options work

### ISSUE THREAD

**Issue by bobvanderlinden** [NixOS/nix#8971]
## Problem

The documentation in `testing.md` says the following:

> You can run the whole testsuite with `make check`, or the tests for a specific component with `make libfoo-tests_RUN`. Finer-grained filtering is also possible using the [--gtest_filter](https://google.github.io/googletest/advanced.html#running-a-subset-of-the-tests) command-line option.

However, `--gtest_filter` is meant only for the googletest executable. Not for `make`.

```
make libfoo-tests_RUN --gtest_filter
```

will thus fail.

I tried to dig into `programs.mk` to figure out how to pass along arguments to the gtest executable, but I was not able to find it. I'm now planning to manually call the executable if I can find it :sweat_smile:

## Proposal

The documentation should say something about passing along the command-line arguments to the executable through `make`.

## Checklist

- [ ] checked [latest Nix manual] \([source])
- [ ] checked [open documentation issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/src
[open documentation issues and pull requests]: https://github.com/NixOS/nix/labels/documentation

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by cole-h** [comment]
I actually documented this recently in https://github.com/NixOS/nix/pull/8883. Long story short: use `GTEST_FILTER=filter` instead of `--gtest_filter filter`

**Comment by bobvanderlinden** [comment]
Oh that is indeed very recent! I was on a branch apparently older than that. Thanks for documenting!
