### ISSUE TITLE
Firing too many connections for binary cache

### ISSUE THREAD

**Issue by sorpaas** [NixOS/nix#898]
I frequently get banned by my ISP for exceeding its "rate limit". The case happens when I try to install some packages with a huge amount of dependencies, for example `texlive.combined.scheme-full`. Nix tries to check whether binary caches exist for all of them in the beginning, which as a result fires around 800+ HTTP requests in less than one second. Can we limit the HTTP requests fired at the same time?

**Comment by edolstra** [comment]
What version? Nix 1.11 only uses 25 parallel HTTP connections by default (c0d4173263a3077905643d5a044e982fc830f7ff). If that's still too much, you can set the option `binary-caches-parallel-connections`.

**Comment by domenkozar** [comment]
@sorpaas ping

**Comment by edolstra** [comment]
Using http/2 we're using way fewer connections, so closing.
