### ISSUE TITLE
nix-* command not found after install

### ISSUE THREAD

**Issue by hanweikung** [NixOS/nix#8999]
## Platform

- [x] Linux: Ubuntu 20.04
- [ ] macOS
- [ ] WSL

## Additional information

After the multi-user installation, I found I had to go to my `/etc/bashrc` and `/etc/bash.bashrc` and removed the following lines:
```bash
# Nix
if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
  . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
fi
# End Nix
```
so that the Nix commands can be successfully found (through `/etc/profile.d/nix.sh`).

Can anyone explain why those lines had to be removed to make Nix work?

## Output

```log
nix-shell: command not found
```

</details>

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by abathur** [comment]
Something in your init files may be overwriting PATH after the bashrc copy runs. 

The shell hook has an ~include-guard that will bail out if `__ETC_PROFILE_NIX_SOURCED` is already defined. If the path got overset after the first run, the second run would be a no-op.

**Comment by hanweikung** [comment]
> verwriting PATH after the bashrc copy

Thank you for your comments. 

It turned out `/etc/profile.d/cuda.sh` overwrote PATH. Removing this shell script solved the issue.
