### ISSUE TITLE
"nix-env --install --prebuilt-only" masks installation problems

### ISSUE THREAD

**Issue by OptiverTimAll** [NixOS/nix#901]
## Steps to reproduce:
- Set up Nix to the point where you can install packages
- Install a non-existent package by filesytem path:
  
  ```
   $ nix-env --install --prebuilt-only /nix/store/gibberish
  ```
## Expected result:

Some kind of "no such package" error message and a non-zero exit-code, like when run without `--prebuilt-only`:

```
$ nix-env --install /nix/store/gibberish
Installing ‘gibberish’
Don't know how to build these paths:
  /nix/store/gibberish
Error: basic_string::basic_string: __pos (which is 44) > this->size() (which is 20)
$ echo $?
1
```
## Actual result:

No error-message, zero-exit code:

```
$ nix-env --install --prebuilt-only /nix/store/gibberish
$ echo $?
0
```

**Comment by vcunat** [comment]
I would consider even the behavior of ``$ nix-env --install /nix/store/gibberish`` a bug.

**Comment by domenkozar** [comment]
@vcunat what kind of bug?

**Comment by vcunat** [comment]
@domenkozar: apparently we use `std::string` badly, causing that error which probably isn't really related to the issue title.

**Comment by uri-canva** [comment]
Seems fixed:

```
$ nix-env --install --prebuilt-only /nix/store/gibberish
error: path '/nix/store/gibberish' is not in the Nix store
```
