### ISSUE TITLE
Provide $ nix options command for https://search.nixos.org/options

### ISSUE THREAD

**Issue by izelnakri** [NixOS/nix#9023]
**Is your feature request related to a problem? Please describe.**
:doc command inside `$ nix repl` is a very useful tool, not well utilized currently, nix repl tab completion is also very useful for debugging but limited in documentation capability. New `$ nix options` command would be a boon in terms of productivity, learning & documentation, I see this is a great compliment to future enhancements of `$ nix repl` `:doc` feature. 

**Describe the solution you'd like**

**Describe alternatives you've considered**
- nix repl `:doc`
- Official search tool that is not in the cli: https://search.nixos.org/options

Example:

```bash
$ nix options services.postgresql
=> services.postgresql - All systemd related options of the nixpkgs.postgresql package
services.postgresql.settings - systemd settings attrset of postgresql
services.postgresql.recoveryConfig - xxxxxxxxxxxxxxxxxxxxxxxxxxx
services.postgresql.port - The port on which PostgreSQL listens. Default: 5432 Declared in: nixos/modules/services/databases/postgresql.nix#22 (maybe make certain declared additional info like Declared in, Type hidden under a -v flag)
services.postgresql.package - PostgreSQL package to use. Example: pkgs.postgresql_11 Declared in: nixos/modules/services/databases/postgresql.nix#23
services.postgresql.ensureUsers.*.name - Name of the user to ensure. Type: String Declared in nixos/modules/services/databases/postgresql.nix
services.postgresql.ensureUsers.*.ensurePermissions - xxxxxxxxxxxxxxxxxxxxxxxxxxx
services.postgresql.ensureUsers.*.ensureClauses.superuser - xxxxxxxxxxxxxxxxxxxxxxxxxxx
services.postgresql.ensureUsers.*.ensureClauses.replication - xxxxxxxxxxxxxxxxxxxxxxxxxxx
services.postgresql.ensureUsers.*.ensureClauses.login - xxxxxxxxxxxxxxxxxxxxxxxxxxx

# Maybe show these in `tree` format

$ nix options <home-manager>.account.options

-> similar output for home-manager channel or flake
```

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by Artturin** [comment]
A thing like this should not be in nix but a separate tool to avoid a layer violation.
