### ISSUE TITLE
nix - command not found

### ISSUE THREAD

**Issue by pdeva** [NixOS/nix#9035]
## Platform

- [ x] Linux: Debian 12 
- [ ] macOS
- [ ] WSL

```
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```
## Additional information
Installed multi-user nix and restarted terminal. it says command not found when running as my user.
if i `sudo` myself to `root` then `nix` does work however

## Output

<details><summary>Output</summary>

```log

bash: nix: command not found
```

</details>

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by abathur** [comment]
Nix not being on PATH generally points to your shell init files either hard-setting a PATH that doesn't include Nix after Nix's shell hook ran (often from one of the user-specific init files in ~/), or perhaps having an early return condition in the relevant init file that is keeping the shell hook from running at all.

If `env | grep` NIX shows a few variables, that's a good sign the shell hook is at least running and you can focus on looking for what might be overwriting PATH.

**Comment by pdeva** [comment]
ok i uninstalled and re-installed in single user mode and it works now
