### ISSUE TITLE
Add name argument to builtins.fetchTarball and builtins.fetchgit

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nix#904]
Current behavior:
- `builtins.fetchTarball` currently names the derivation after the url (words after last slash in the url)
- `builtins.fetchgit` currently always names the derivation `git-export`
- Hydra `nix-prefetch-git` currently names the derivation `git-export` (and has an old standing bug in that script of stripping anything that prefixes on `.git` instead of just `.git` folder, so `.gitignore` would also be deleted
- nixpkgs `nix-prefetch-git` currently names the derivation after url and rev name

All in all, this leads to a lot of frustration since hashes of those derivations will differ. I'll try to fix the Hydra part (and look into since when nix-prefetch-git is crazy).

Mainly, I would hope that `fetchTarball` and `fetchgit` can be used interchangeably and it's currently not possible due to different hardcoded names. 

cc @ocharles as he mentioned this recently on IRC
cc @edolstra

**Comment by domenkozar** [comment]
Just to be clear about my motivation: I'd like to build my derivation on Hydra and locally using some git as source and currently it's not possible to match Hydra's produced hash using `nix-prefetch-git` as it's GitPlugin.

**Comment by domenkozar** [comment]
Wrote a script to get all hashes for an example repo:

```
builtins.fetchTarball: "/nix/store/g43i2h7hh43zr146g9wbq2cs5wjj9dac-master"
builtins.fetchgit: "/nix/store/fws69vhxrmxjgp83dh9xc86zlclp8k2j-git-export"
Nixpkgs nix-prefetch-git: path is /nix/store/dxawz07sxcd6m25r982qwljxfz128bak-snabb
Hydra nix-prefetch-git: path is /nix/store/nvn3q89lawxa1ar7x9ywhglnnki3y0dd-git-export
```

The script (assumes recent Nix at `result`):

```
fetchTarball=$(nix-instantiate -E 'builtins.fetchTarball https://github.com/snabbco/snabb/tarball/master' --eval)
fetchgit=$(./result/bin/nix-instantiate -E 'builtins.fetchgit https://github.com/snabbco/snabb.git' --eval)
nixprefetchgit=$(nix-prefetch-git https://github.com/snabbco/snabb.git |& grep 'path is')
hydranixprefetchgit=$($(nix-build -E '(import "${builtins.fetchTarball https://github.com/NixOS/hydra/tarball/dc790c5f7eacda1c819ae222bf87674781ae1124}/release.nix" {}).build')/bin/nix-prefetch-git https://github.com/snabbco/snabb.git |& grep 'path is')

echo "builtins.fetchTarball: $fetchTarball"
echo "builtins.fetchgit: $fetchgit"
echo "Nixpkgs nix-prefetch-git: $nixprefetchgit"
echo "Hydra nix-prefetch-git: $hydranixprefetchgit"
```

**Comment by domenkozar** [comment]
Started with nixpkgs: https://github.com/NixOS/nixpkgs/pull/15469

Next up: Hydra should use nixpkgs `nix-prefetch-url`

**Comment by domenkozar** [comment]
I can remove the differences in inputs between what's used as the source, but I really don't see a solution to naming of these derivations without providing a way to name them (or just using the same name everywhere).

**Comment by expipiplus1** [comment]
How does this impact fetching from local directories, for example `src = ./.`? Would the solution involve some function like `namePath = name: path: ...`?

I'm bumping into NixOS/hydra#172 and it would be super to be able to implement some kind of workaround until this can be fixed properly. I'd be more than happy to have a crack at this if someone points me in the right direction :)

**Comment by domenkozar** [comment]
`20:02:48            nh2 | and ./. has a bug that the parent directory name goes into the derivation, making it less reproducible`
