### ISSUE TITLE
Getting to the bottom of "xz: (stdin): File format not recognized"  errors

### ISSUE THREAD

**Issue by rrnewton** [NixOS/nix#906]
## Observed Behavior

I find that in some (mis)installations of nix, package downloads fail, but it's hard to see where/why.

```
    *** Downloading ‘https://cache.nixos.org/nar/0hhcyvgk0x1smrzpy4dhl72ca8i3lg4yqab6hznnsha5s0c0qyr9.nar.xz’ to ‘/nix/store/gcbqx5fdcgwchjzjjvjmxxjgr8xagh29-bash-4.3-p42-doc’...
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
    curl: (60) SSL certificate problem: unable to get local issuer certificate
    More details here: http://curl.haxx.se/docs/sslcerts.html

    curl performs SSL certificate verification by default, using a "bundle"
     of Certificate Authority (CA) public keys (CA certs). If the default
     bundle file isn't adequate, you can specify an alternate file
     using the --cacert option.
    If this HTTPS server uses a certificate signed by a CA represented in
     the bundle, the certificate verification probably failed due to a
     problem with the certificate (it might be expired, or the name might
     not match the domain name in the URL).
    If you'd like to turn off curl's verification of the certificate, use
     the -k (or --insecure) option.
    /nix/store/hs8lf8v9qqfs9m3jqmm97nqg7wg9dqjw-xz-5.2.1/bin/xz: (stdin): File format not recognized
    error: unexpected end-of-file
```

In particular, installing on a fresh Ubuntu from source does not run into this problem, whereas installing with `curl https://nixos.org/nix/install | sh` can create an installation with these problems.  But I don't know why there would be a connection.

## Other examples

It looks like these errors have cropped up for various people:

* https://travis-ci.org/NixOS/nixpkgs/builds/114575165
* https://github.com/NixOS/nixpkgs/issues/2285
* https://gist.github.com/shajra/12d862220ab7cb9782d2a934d4cb489a

In the last example, the "unexpected end of file" error follows the certificate problem.  But in the first two it doesn't.

## To Reproduce:

[This repository](https://github.com/iu-parfunc/nix-install-scripts/commit/b17fd5611a07cda5d3d5fd86285d95ab9c850cc9) contains scripts and Dockerfiles to build nix on ubuntu.  Prebuilt images are available on [dockerhub here](https://hub.docker.com/r/rrnewton/nix-install-scripts/).

The version that's built using the installer script produces the error described above:

```
$ docker run -it rrnewton/nix-install-scripts:on-ubuntu-single-1.11.2 nix-env -i python
....
/nix/store/hs8lf8v9qqfs9m3jqmm97nqg7wg9dqjw-xz-5.2.1/bin/xz: (stdin): File format not recognized
error: unexpected end-of-file
```

Whereas it works just fine in an alternate image -- one where nix is built from source:

```
$ docker run -it rrnewton/nix-install-scripts:on-ubuntu-from-source-1.11.2 nix-env -i python
....
created 6 symlinks in user environment
```

**Comment by rrnewton** [comment]
If it is really just a certificates problem (and the other 2/4 places linked above where the error occurs are due to something else), then I'm not sure why it is happening. The install script within the binary tarball does do a bit of work to set up cacert:

```bash
   cacert="/nix/store/4fh4nwd11frn1a3rifrdv6kdifrxrfwn-nss-cacert-3.21"
...
   $nix/bin/nix-env -i "$cacert"
    export SSL_CERT_FILE="$HOME/.nix-profile/etc/ssl/certs/ca-bundle.crt"
```

So even though the installer runs this setup must be lost somehow.  Indeed, `~/.nix-profile/etc/ssl` is missing.

**Comment by rrnewton** [comment]
Related discussion in https://github.com/NixOS/nixpkgs/issues/3382.

**Comment by rrnewton** [comment]
Yep, manually running this fixes the problem inside the docker image:

```
nix-env -i /nix/store/4fh4nwd11frn1a3rifrdv6kdifrxrfwn-nss-cacert-3.21/etc/ssl/certs/ca-bundle.crt
```

But I still don't see why the same command in the install script didn't take!

**Comment by joachifm** [comment]
Yes, this looks like a simple issue with the certificate bundle. The error at https://travis-ci.org/NixOS/nixpkgs/builds/114575165 is due to the server returning HTTP code 500. In all cases, the xz error is somewhat of a red herring, it merely indicates that the archive was truncated or empty.

**Comment by rrnewton** [comment]
Ok, thanks.  I still don't exactly understand what the intended route is between the install script and setting this up properly.  We'll just put in manual hacks for our Dockerfiles and custom install scripts (which aim at multi-user installs across a bunch of machines running other distros).

Closing for now.
