### ISSUE TITLE
Unable to build Nix on `aarch64-linux` using `binfmt.emulatedSystems`

### ISSUE THREAD

**Issue by Slabity** [NixOS/nix#9074]
**Describe the bug**

When attempting to build `pkgs.nixUnstable` for an `aarch64-linux` system using a host configured with `boot.binfmt.emulatedSystems = [ "aarch64-linux" ];`, the build fails with the following error:

```
    ERROR:../plugins/core.c:221:qemu_plugin_vcpu_init_hook: assertion failed: (success)
    Bail out! ERROR:../plugins/core.c:221:qemu_plugin_vcpu_init_hook: assertion failed: (success)
    **
    ERROR:../accel/tcg/cpu-exec.c:532:cpu_exec_longjmp_cleanup: assertion failed: (cpu == current_cpu)
    Bail out! ERROR:../accel/tcg/cpu-exec.c:532:cpu_exec_longjmp_cleanup: assertion failed: (cpu == current_cpu)
    error: cannot open connection to remote store 'daemon': error: reading from file: Connection reset by peer
    null
    ++(remote-store.sh:15) onError
    ++(/build/source/tests/common/vars-and-functions.sh:237) set +x
    remote-store.sh: test failed at:
      main in remote-store.sh:15
```

According to what was discussed on the Matrix chatroom, this *appears* to be an issue with the test suite (and not the actual build itself). The assertion `cpu = current_cpu` is being falsely triggered when emulating the architecture.

**Steps To Reproduce**

Here is a simple flake that can reproduce this issue. As a note, I was trying to build an SD card image for `aarch64-linux` with `pkgs.nixUnstable`:

```
{
  description = "Personal flakes for my systems";

  inputs = {
    # Note I'm using `nixpkgs-unstable` here because `nixos-unstable` has it cached
    # and won't actually trigger a build
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
  };

  outputs = { self, ... }@inputs:
  {
    nixosConfigurations = with inputs; {
      simpleAarchSystem = nixpkgs.lib.nixosSystem {
        system = "aarch64-linux";
        modules = [
          "${nixpkgs}/nixos/modules/installer/sd-card/sd-image-aarch64.nix"
          {
            nix = {
              package = nixpkgs.legacyPackages.aarch64-linux.nixUnstable;
              extraOptions = ''
                experimental-features = nix-command flakes
              '';
            };
          }
        ];
      };
    };
  };
}
```

**Ensuring you are on a system *emulating* `aarch64-linux` using the above `binfmt` config**, this can be built using the following command:

```
nix build .#nixosConfigurations.simpleAarchSystem.config.system.build.sdImage
```

**Expected behavior**

Tests should run successfully.

**`nix-env --version` output**
`nix-env (Nix) 2.18.0`

**Additional context**

- According to @ElvishJerricco on the Matrix chatroom, this also occurs when building version 2.17.0 as well.

- I have *not* tested this with other architectures, but I'd expect the tests to fail with that as well.

- Running the flake above uses `nixpkgs-unstable` and not `nixos-unstable` because it is cached on the latter and the build won't be triggered.

**Comment by roberth** [comment]
This seems to be a problem within `qemu`.

Building the `nix` package does not require `qemu`. We don't call it in our tests suite and the assertion error clearly originates from `qemu` itself. This suggests that the problem is internal to `qemu`. I don't see anything we could do about it.
Furthermore `qemu` user process emulation is known to be buggy.

I'll be happy to reopen this if I'm wrong, but until then there doesn't seem to be anything we can do.
