### ISSUE TITLE
Export nix-env/*.o as a library

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nix#914]
I've been working on PackageKit support for Nix and it will need some "nix-env" functionality to work correctly. All of these are available in nix-env so maybe it would make sense to export them as libnixenv?

Here are the functions I've needed:

``` c
DrvInfos queryInstalled(EvalState & state, const Path & userEnv);
bool createUserEnv(EvalState & state, DrvInfos & elems,
    const Path & profile, bool keepDerivations,
    const string & lockToken);
bool isNixExpr(const Path & path, const struct stat & st);
void loadSourceExpr(EvalState & state, const Path & path, Value & v);
void getAllExprs(EvalState & state, const Path & path, StringSet & strings, Value & v);
```

Right now I've just taken what's in HEAD but it would be nice to have the version of these function compatible with Nix for bug fixes, etc.

**Comment by matthewbauer** [comment]
related: #107

**Comment by edolstra** [comment]
We'll probably need to move most nix-env stuff into a separate library to support the new `nix` command.

**Comment by matthewbauer** [comment]
@edolstra 
Is there any way to speed up "getDerivations"? Right now I'm having to cache the list of drvs which leads to really slow startup times for packagekit.
