### ISSUE TITLE
Nix fails to download build artifacts due to SSL connect error on MacOS

### ISSUE THREAD

**Issue by lambda674** [NixOS/nix#9140]
**Describe the bug**

Certain build artifacts that nix downloads with curl cause an SSL error. This is probably another issue of nix not correctly using my workplace's SSL certificate.

**This issue seems to be unique to other SSL errors because only certain things that nix downloads cause SSL errors**. 

For example, other people get errors running `nix shell nixpkgs#python310` or `nix-shell -p nix-info --run "nix-info -m"`. These works fine for me. I only get this error when trying to install my nix-darwin and home-manager configs. 

Example artifacts that I get this error for are `https://github.com/koekeishiya/yabai/releases/download/v5.0.6/yabai-v5.0.6.tar.gz` or `https://git.sr.ht/~rycee/nmd/archive/824a380546b5d0d0eb701ff8cd5dbafb360750ff.tar.gz`. Here are the outputs:

```
% home-manager switch --flake .#<name>
warning: error: unable to download 'https://git.sr.ht/~rycee/nmd/archive/824a380546b5d0d0eb701ff8cd5dbafb360750ff.tar.gz': SSL connect error (35); retrying in 316 ms
...
```

```
% darwin-rebuild switch --flake .#work
...
trying https://github.com/koekeishiya/yabai/releases/download/v5.0.6/yabai-v5.0.6.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M  0     0    0     0    0     0      0      0>
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) OpenSSL/3.0.9: error:0A000152:SSL routines::unsafe legacy renegotiation disabled
error: cannot download source from any mirror
```

Nix is probably using the wrong SSL certificate because I can successfully download these files myself with curl:

```
% curl -vvv https://git.sr.ht/~rycee/nmd/archive/824a380546b5d0d0eb701ff8cd5dbafb360750ff.tar.gz
*   Trying 173.195.146.142:443...
* Connected to git.sr.ht (173.195.146.142) port 443 (#0)
* ALPN: offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=git.sr.ht
*  start date: Aug 25 00:00:07 2023 GMT
*  expire date: Nov 23 00:00:06 2023 GMT
*  subjectAltName: host "git.sr.ht" matched cert's "git.sr.ht"
*  issuer: <hide for privacy>
*  SSL certificate verify ok.
...
```

**What I have tried**:

Setting `NIX_SSL_CERT_FILE`:
```
NIX_SSL_CERT_FILE=/etc/ssl/cert.pem home-manager switch --flake .#<name>
```

Setting `ssl-cert-file` in `nix.conf`:
```
ssl-cert-file = /etc/ssl/cert.pem
```

Setting `NIX_SSL_CERT_FILE` env variable with launchd:
```
launchctl setenv NIX_SSL_CERT_FILE /etc/ssl/cert.pem
```

I do notice that my plist file at `/Library/LaunchDaemons/org.nixos.nix-daemon.plist` has an incorrect value set:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>EnvironmentVariables</key>
        <dict>
                <key>NIX_SSL_CERT_FILE</key>
                <string>/etc/ssl/certs/ca-certificates.crt</string>
                <key>OBJC_DISABLE_INITIALIZE_FORK_SAFETY</key>
                <string>YES</string>
        </dict>
        <key>KeepAlive</key>
        <true/>
        <key>Label</key>
        <string>org.nixos.nix-daemon</string>
        <key>LowPriorityIO</key>
        <false/>
        <key>ProcessType</key>
        <string>Standard</string>
        <key>ProgramArguments</key>
        <array>
                <string>/bin/sh</string>
                <string>-c</string>
                <string>/bin/wait4path /nix/store/qciiwwkfblrbgjxmbjbw8l856sf1syy8-nix-2.17.0/bin/nix-daemon &amp;&amp; exec /nix/store/qciiwwkfblrbgjxmbjbw8l856sf1syy8-nix-2.17.0/bin/nix-daemon</string>
        </array>
        <key>SoftResourceLimits</key>
        <dict>
                <key>NumberOfFiles</key>
                <integer>4096</integer>
        </dict>
</dict>
</plist>
```

If `-vvvvv` is passed to the nix command, it would be helpful if it passed `-vvv(vv)` to curl and logged the output.

**Expected behavior**

`% home-manager switch --flake .#<name>` shouldn't result in a SSL error.

**`nix-env --version` output**

```
% nix-shell -p nix-info --run "nix-info -m"
 - system: `"aarch64-darwin"`
 - host os: `Darwin 22.6.0, macOS 13.5`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.0`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs
 ```

**Comment by abathur** [comment]
When you say:

> I do notice that my plist file at /Library/LaunchDaemons/org.nixos.nix-daemon.plist has an incorrect value set

I'm guessing you mean that you don't see the value set in this repo, yeah? I'm not personally familiar with troubleshooting this, but I suspect something else (perhaps nix-darwin?) may be generating your daemon plist and including the value. If it is what's causing trouble, the fix may be troubleshooting it on that end?

I'll ask in the macOS channel on Matrix to see if anyone's seen this.

**Comment by mklca** [comment]
I hit this issue after purging and re-installing Nix on Mac OS 13.6.

The initial `/Library/LaunchDaemons/org.nixos.nix-daemon.plist` **did not** specify any value for `NIX_SSL_CERT_FILE`. Also, the permissions on this file were set to `0000` (*i.e*, `ugo=`), which seems strange since `org.nixos.darwin-store.plist` has otherwise sensible `0644` (*i.e*, `u=rw,go=r`) permissions.

I was able to resolve the issue in the following way:

1. Set the permissions of `/Library/LaunchDaemons/org.nixos.nix-daemon.plist`:

       sudo chmod u=rw,go=r /Library/LaunchDaemons/org.nixos.nix-daemon.plist

2. Set `NIX_SSL_CERT_FILE` in `/Library/LaunchDaemons/org.nixos.nix-daemon.plist` by changing

    ```xml
        <key>EnvironmentVariables</key>
        <dict>
                <key>OBJC_DISABLE_INITIALIZE_FORK_SAFETY</key>
                <string>YES</string>
        </dict> 
    ```

   to this

   ```xml
        <key>EnvironmentVariables</key>
        <dict>
                <key>NIX_SSL_CERT_FILE</key>
                <string>/nix/var/nix/profiles/default/etc/ssl/certs/ca-bundle.crt</string>
                <key>OBJC_DISABLE_INITIALIZE_FORK_SAFETY</key>
                <string>YES</string>
        </dict> 
    ```

3. Reboot. Unloading and reloading `org.nixos.nix-daemon.plist` didn't seem to work.

After rebooting, `nix-shell -p nix-info --run "nix-info -m"` works as expected without dumping the SSL error seen after the initial install.

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 22.6.0, macOS 10.16`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.18.1`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

**Comment by abathur** [comment]
Did you have nix-darwin installed? (I've seen some issues caused by state it manages that hasn't been cleaned up.)

**Comment by lambda674** [comment]
@abathur 
> I'm guessing you mean that you don't see the value set in this repo, yeah?

I should have been more specific. In that file, `NIX_SSL_CERT_FILE` is set to `/etc/ssl/certs/ca-certificates.crt`, which is the wrong value.

I agree that it seems likely that the issue itself is coming from nix-darwin. However, specifically for this file you can see it's called `org.nixos.nix-daemon.plist`. If it sets up the nix daemon, from my understanding it should be from nix itself.

**Comment by lambda674** [comment]
@mklca 

Thanks for sharing this solution. This looked very promising for me, and I also noticed the weird file permissions. Unfortunately I'm still having the same issue though.

**Comment by abathur** [comment]
You can see the copy Nix would install at https://github.com/NixOS/nix/blob/master/misc/launchd/org.nixos.nix-daemon.plist.in.

I don't recall the reasons, but nix-darwin has its own nix-daemon module: https://github.com/LnL7/nix-darwin/blob/8b6ea26d5d2e8359d06278364f41fbc4b903b28a/modules/services/nix-daemon.nix#L46-L72

**Comment by lambda674** [comment]
Oh wow you're right, I didn't think that would be true.

If this does seem to be causing the issue, I'll definitely move to that repo. To me it doesn't seem like it though, because I followed the steps above where I manually updated `NIX_SSL_CERT_FILE` in there and it didn't fix the issue.

**Comment by nuttycom** [comment]
I don't even appear to _have_ a `/Library/LaunchDaemons/org.nixos.nix-daemon.plist` - any other ideas as to how it might be possible to start to fix this? Seems like my `nix` install is completely hosed by it.

**Comment by lambda674** [comment]
I finally got this to work by updating to nix 2.20.1.

**Comment by aagatequinix** [comment]
I just installed 2.20.1 and have run into the exact same error?

`warning: error: unable to download 'https://nixos.org/channels/nixpkgs-unstable': SSL peer certificate or SSH remote key was not OK (60); retrying in 2084 ms
error: unable to download 'https://nixos.org/channels/nixpkgs-unstable': SSL peer certificate or SSH remote key was not OK (60)
`

`aaglenn@hostname ~ % uname -a`
`Darwin hostname 22.6.0 Darwin Kernel Version 22.6.0: Sun Dec 17 22:13:25 PST 2023; root:xnu-8796.141.3.703.2~2/RELEASE_ARM64_T6020 arm64
aaglenn@hostname ~ % which nix-channel
/nix/var/nix/profiles/default/bin/nix-channel
`

`aaglenn@hostname ~ % sudo -i echo $PATH`
`/Users/aaglenn/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/CyberArk EPM.app/Contents/Helpers:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
`

`aaglenn@hostname ~ % sudo -i nix-channel --update nixpkgs`
`-sh: nix-channel: command not found
`

my driving reason to run Nix on macOS was to not have to fiddle or understand as many shell and installer scripts so I loathe to start bashing things with my neolithic unix tools like chown and plist files. what is the actual issue & fix?
