### ISSUE TITLE
Segmentation fault when flake inputs follow each other

### ISSUE THREAD

**Issue by vkryachko** [NixOS/nix#9144]
**Describe the bug**

Segmentation fault when flake inputs follow each other

**Steps To Reproduce**

```nix
{
  inputs = {
    nixpkgs.follows = "dream2nix/nixpkgs";
    dream2nix = {
      url = "github:nix-community/dream2nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };
  outputs = {...}: {};
}
```

**Expected behavior**

A dependency cycle reported by nix

**`nix-env --version` output**
nix-env (Nix) 2.18.1

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by thufschmitt** [comment]
Triaged with @nixo/nix-team on 2023-10-13. We can reproduce, but don't have the bandwidth to fix it in the short term. Anyone is welcome (encouraged even) to contribute a fix

**Comment by vkryachko** [comment]
Fair enough, created a fix pr https://github.com/NixOS/nix/pull/9169. ptal
