### ISSUE TITLE
Documentation for building Nix from source is wrong

### ISSUE THREAD

**Issue by rmst** [NixOS/nix#9164]
## Problem
The referenced scripts in https://nixos.org/manual/nix/stable/installation/building-source that should be in this repo don't exist.

Additionally when following the link in this repo's Readme for building from source (i.e. https://nixos.org/manual/nix/unstable/contributing/hacking.html) there is no way explained to build nix without nix.

## Proposal

Provide instruction to build nix without nix

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open documentation issues and pull requests] for possible duplicates

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by roberth** [comment]
Could you try with the "unstable" docs? https://nixos.org/manual/nix/unstable/installation/building-source

**Comment by rmst** [comment]
Thanks for the answer! I guess I got caught in a build process change then. I tried with the unstable docs and master inside of a Debian (bullseye) docker and kept installing missing dependencies including

```bash
apt install autoconf autoconf-archive jq libboost-all-dev libssl-dev libarchive-dev libsqlite3-dev libcurl4-openssl-dev
```

but then ran into 

```bash
configure: error: Nix requires libeditline; it was found neither via pkg-config nor its normal header.
```

for which I didn't find an Debian (bullseye) package so I gave up.

I had hoped that as a package manager nix would only require sth super basic like gcc and then it could bootstrap itself from that but I guess people are still trying to get that to work https://www.youtube.com/watch?v=Gm8yrvbgY-Y

**Comment by roberth** [comment]
> I guess people are still trying to get that to work https://www.youtube.com/watch?v=Gm8yrvbgY-Y

That's an effort for bootstrapping everything within Nixpkgs I believe, not necessarily bootstrapping without Nix, but I could be wrong.

> `libeditline`

I wonder why Debian doesn't have that. Are we supposed to fall back to readline? It's not even in the requested packages list, where it would been ages ago, so maybe it's a policy thing for them. Odd.

Ideally we could make it optional anyway. We're not too reliant on it I think, except in `nix repl` perhaps, but that's not essential for bootstrapping Nix from source. Presumably you want to use it to build a full-featured Nix afterwards anyway, in Nix.

**Comment by rmst** [comment]
Debian 10 still had a package called `libeditline-dev` but Debian 11 (bullseye) doesn't have it. Maybe it's part of some other package now but idk. 

In the video the presenter seems to be building Nix from source first. He also complains about excessive dependencies, e.g. he says that libssl is only pulled in because it computes SHA2 faster than libsodium.

I guess what I'd hope for is a super minimal version of Nix without external deps which then is able to run basic Nix expressions which are then used to build a more fully featured version of Nix but I'm new to Nix so maybe this doesn't make sense for one reason or another and surely this would be a lot of work even if it did
