### ISSUE TITLE
nix-repl crashes with 'start-condition stack underflow'

### ISSUE THREAD

**Issue by dredozubov** [NixOS/nix#917]
I can reproduce it like this:
```
% nix-repl
Welcome to Nix version 1.10. Type :? for help.

nix-repl> <nixpkgs> + /pkgs.nix}
start-condition stack underflow
```

**Comment by groxxda** [comment]
Can not reproduce with Nix 1.11.2:
```
Welcome to Nix version 1.11.2. Type :? for help.

nix-repl> <nixpkgs> + /pkgs.nix}
error: syntax error, unexpected '}', expecting $end, at (string):1:2
```

So probably already fixed

**Comment by copumpkin** [comment]
Yeah, I think there was briefly an issue with the parser, but a patch release was made to 1.10. If you reinstall Nix (even from the public source) do you still get it?

**Comment by dredozubov** [comment]
I'm currently on a brief vacation, I will be able to check that next week.

**Comment by domenkozar** [comment]
Best to report this to https://github.com/edolstra/nix-repl/issues

**Comment by dredozubov** [comment]
Can't reproduce with 1.11.2, closing.

@domenkozar thanks for the tip
