### ISSUE TITLE
"Bubblewrap" in nix-shell

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/nix#924]
I recently found [this project](https://github.com/projectatomic/bubblewrap). It might be useful to take some of the kernel functionality it's using and put it in nix-shell. Related to #625, #179.

**Comment by copumpkin** [comment]
Which functionality do you have in mind? Isn't bubblewrap just using the usual namespace + cgroup + capabilities stuff?

**Comment by copumpkin** [comment]
Also, it looks like https://github.com/NixOS/nix/commit/a24f2c9b8413ebc8b1776ab3f770c69e4a03007b is moving in this direction.

**Comment by matthewbauer** [comment]
okay nevermind then.

**Comment by copumpkin** [comment]
I wasn't trying to be dismissive! Just wasn't sure what the difference was from other similar tools, and it wasn't clear from your ticket. If you think I'm missing something please reopen 😄

**Comment by matthewbauer** [comment]
No that fine! I didn't realize that "nix run" was already in the works. I didn't realize that Bubblewrap is basically just doing kernel container things. It's fairly similar to "runc".
