### ISSUE TITLE
Tag 2.3.17 from `2.3-maintenance` branch

### ISSUE THREAD

**Issue by flokli** [NixOS/nix#9244]
**Is your feature request related to a problem? Please describe.**
I'd like to bump Nix 2.3 in nixpkgs to a version containing https://github.com/NixOS/nix/pull/9221, and ideally be able to distinguish server-side that zstd decompression is supported. Ideally, this would happen by having a new tag and version, which gets communicated i the user-agent. 

**Describe the solution you'd like**
`git tag 2.3.17 12ac3f6f2`

**Describe alternatives you've considered**
`fetchpatch`'ing a set of patches, but then zstd support wouldn't be discoverable.

**Additional context**
https://discourse.nixos.org/t/switch-cache-nixos-org-to-zstd-to-fix-slow-nixos-updates-nix-downloads/23961/45

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by bjornfor** [comment]
Can we please also include https://github.com/NixOS/nix/pull/9245? Without it Nix 2.3 multi-user/daemon installs don't work on non-NixOS.

**Comment by roberth** [comment]
Tagged https://github.com/NixOS/nix/releases/tag/2.3.17

**Comment by flokli** [comment]
This still hasn't made its way to "https://nixos.org/releases/nix/nix-${version}/nix-${version}.tar.xz" (and maybe we also want to some release notes, at least in the github UI).

**Comment by flokli** [comment]
(It seems I can't reopen this issue, but I would if I could)

**Comment by cole-h** [comment]
> This still hasn't made its way to "[https://nixos.org/releases/nix/nix-${version}/nix-${version}.tar.xz](https://nixos.org/releases/nix/nix-$%7Bversion%7D/nix-$%7Bversion%7D.tar.xz)" (and maybe we also want to some release notes, at least in the github UI).

It looks like it has now: https://releases.nixos.org/?prefix=nix/nix-2.3.17

**Comment by flokli** [comment]
I opened https://github.com/NixOS/nixpkgs/issues/265916 about bumping the version in nixpkgs, let's move the discussion over to there.
