### ISSUE TITLE
Published hacking guide did not update; still shows outdated `bootstrap.sh` instructions

### ISSUE THREAD

**Issue by bburdette** [NixOS/nix#9248]
**Describe the bug**

Hacking guide is out of date

**Steps To Reproduce**

0. Update my nix repo, merge with master.
1. Notice bootstrap.sh is gone
2. Make doesn't work
3. Go to [hacking guide ](https://nixos.org/manual/nix/unstable/contributing/hacking.html)
4. Wat do?

**Expected behavior**

What should you type in order to get make to work, do tests, etc?

**Additional context**

Looks like it got nuked in commit 2f0b508c29f1c8eedc1f93c1a2dc31e8eb60de9a, but the hacking guide was missed.

@Ericson2314

**Comment by Ericson2314** [comment]
@bburdette It is updated:
```bash
$ git grep bootstrap.sh
scripts/install-multi-user.sh:# - https://github.com/LnL7/nix-darwin/blob/8c29d0985d74b4a990238497c47a2542a5616b3c/bootstrap.sh
```
I think just Hydra didn't update the document on the website yet because Hydra can fall behind:

**Comment by bburdette** [comment]
I have no idea what that has to do with the hacking guide, but I'll take your word for it!  I ended up executing 

> autoreconfPhase

And then 

> configurePhase

**Comment by Ericson2314** [comment]
@bburdette the hacking guide's source is in the Nix repo. The `git grep` I did shows the thing you read is now gone. The updated source to the hacking guide indeed says to use `autoreconfPhase` and `configurePhase`.

**Comment by bburdette** [comment]
Looks like it finally updated!  Closing.
