### ISSUE TITLE
Capabilities of the build machine leak into the manpage

### ISSUE THREAD

**Issue by raboof** [NixOS/nix#9251]
**Describe the bug**

On nix 2.17.1, the `nix3-help-stores` manpage contains:

```
       •  system-features

          Optional  features  that  the  system this store builds on implements
          (like “kvm”).

          Default: benchmark big-parallel kvm nixos-test uid-range
```

However, the `Default:` line shows the features the system that produced the manpage implements, which might not be same as the features the system this store builds on implements.

This is not only slightly confusing, but means this output is not reproducible, impacting for example the reproducibility of the minimal installation ISO.

This also affects the `doc` output

**Steps To Reproduce**

`nix-build '<nixpkgs>' -A nix.man --check` on a machine that supports different features than Hydra.

**Expected behavior**

`--check` succeeds

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by cole-h** [comment]
> Could someone with write access to the repo add this issue to the ['Reproducible Builds' GitHub project](https://github.com/orgs/NixOS/projects/30), with state 'Minimal ISO runtime'?

Done! (FWIW: this only required triage, not write)
