### ISSUE TITLE
`nix copy` writes to `--from`

### ISSUE THREAD

**Issue by kolloch** [NixOS/nix#9286]
**Describe the bug**

If I use `nix copy` to copy some closure from a source (`--from`), it should never attempt to write to that source.

```
nix copy --from https://cache.nixos.org/ github:nix-community/crate2nix
error:
       … while fetching the input 'github:nix-community/crate2nix'

       error: while uploading to HTTP binary cache at 'https://cache.nixos.org': error: unable to upload 'https://cache.nixos.org/nar/04ncylccj8zy0byimlnpglsi6sfgcldl58pybz10jjhw23zr3mgf.nar.xz': HTTP error 404

              response body:

              404
```

The bug also affects e.g. s3 stores.

Worst case: You DO have write access and upload secret or generally unwanted artifacts.

**Steps To Reproduce**

`nix copy --from https://cache.nixos.org/ github:nix-community/crate2nix`

**Expected behavior**

1. Either an error if the store path does not exist
2. or better start building the missing parts locally (because it would allow me to work around auth issues).

**`nix-env --version` output**

`nix-env (Nix) 2.17.1`

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by Aleksanaa** [comment]
Should be a duplicate of https://github.com/NixOS/nix/issues/2637

**Comment by kolloch** [comment]
Indeed seems to be a duplicate of https://github.com/NixOS/nix/issues/2637. Thanks for noticing, @Aleksanaa!
