### ISSUE TITLE
Nix evaluation gets killed by OOM

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nix#931]
To reproduce:

```
$ git clone -b refactor/matrix https://github.com/snabblab/snabblab-nixos.git
$ cd snabblab-nixos
$ nix-build jobsets/snabb-matrix.nix --arg snabb 42 -A benchmarks
nix-instantiate killed by signal 9
```

This eats 4G of ram and then gets killed. If I put `hydraJob` to scrub derivations at `overrideDerivation` it helps, but then I can't use any of the attributes later on.

**Comment by domenkozar** [comment]
With the following patch it takes ~10min to evaluate and 2.5G of ram:

```
diff --git a/lib/misc.nix b/lib/misc.nix
index 945691b..7b15070 100644
--- a/lib/misc.nix
+++ b/lib/misc.nix
@@ -113,7 +113,7 @@ rec {
   # buildNTimes: Derivation -> Int -> [Derivation]
   buildNTimes = drv: n:
     let
-      repeatDrv = i: drv.override { numRepeat = i; };
+      repeatDrv = i: lib.hydraJob (drv.override { numRepeat = i; });
     in map repeatDrv (lib.range 1 n);
 
    # take a list of derivations and make an attribute set of out their names
```

**Comment by vcunat** [comment]
So the real issue is being memory-inefficient for some kinds of nix expressions, right?

**Comment by domenkozar** [comment]
So it seems. Overrides are really inefficient :)

**Comment by domenkozar** [comment]
@nbp gave me a neat idea to build the builder once, and then do `derivation { name = …; builder = "${drv}/builder"; }`.

`$(which time) -v nix-instantiate --eval --strict -E 'builtins.genList (i: derivation { name = toString i; builder = "foo"; system = "boo"; }) 4000'`

says it takes 18MB of ram.

**Comment by bjornfor** [comment]
@domenkozar: Off-topic -- if you use ```$(which time)``` a lot, you might want to try ```\time``` instead. Fewer keystrokes :-D
