### ISSUE TITLE
nix —help shows span tags on the CLI!

### ISSUE THREAD

**Issue by ShashankaNataraj** [NixOS/nix#9331]
**Describe the bug**

`nix —help` shows span tags on the CLI under the `Options` section.

**Steps To Reproduce**

1. `nix —help` on the CLI
2. Scroll down to the `Options` section
3. See `<span>` tags on the Logging-related options and subsequent sections

**Expected behavior**

Would expect to see human readable help text instead of HTML span tags

**`nix-env --version` output**

`nix-env (Nix) 2.18.1`

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by fricklerhandwerk** [comment]
Closed by #9334
