### ISSUE TITLE
Out of tree building

### ISSUE THREAD

**Issue by Ericson2314** [NixOS/nix#9342]
**Is your feature request related to a problem? Please describe.**

Having build files sit next to source files means we can only build for one platform at a time. This makes it hard to develop while testing a few different build configurations at once, e.g. with cross compilation.

This will make it easier to develop windows functionality while not breaking unix functionality.

(Unpack phase during an official build is also wasteful, but this is minor.)

**Describe the solution you'd like**

Eventually the switch to Meson #3160 would get us this for free. But stuff can be done in the meantime with the configure script and makefile.

**Describe alternatives you've considered**

Just wait for Meson.

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by Pamplemousse** [comment]
Also:
As far as I remember, when testing different compilation flags as well (for example when enabling sanitizers for libraries for fuzzing), this lead to a lot of recompilation.

**Comment by Ericson2314** [comment]
This is now done, see the manual: https://nixos.org/manual/nix/stable/contributing/hacking#building-for-multiple-platforms-at-once
