### ISSUE TITLE
`nix fmt` formats files in .git, leading to a corrupted repository

### ISSUE THREAD

**Issue by whentze** [NixOS/nix#9359]
**Describe the bug**

If you make a git branch/tag whose name ends in .nix, git creates files like `.git/refs/heads/add-stuff-to-default.nix` that don't contain nix code but end up being "formatted" by `nix fmt` anyway. This leads to a corrupted git repository and very confusing messages like:
```
$ git log
fatal: your current branch appears to be broken
$ git checkout
fatal: You are on a branch yet to be born
$ git stash save
You do not have the initial commit yet
```

**Steps To Reproduce**

1. Make a flake and add a formatter
2. `git switch -C add-stuff-to-default.nix`
3. `nix fmt`
4. everything gets really fucky

**Expected behavior**

I think `nix fmt` should entirely ignore `.git`. Perhaps it should also skip gitignored stuff, but I'm not sure.

**`nix-env --version` output**

`nix-env (Nix) 2.13.6`

**Comment by roberth** [comment]
`nix fmt` is almost `nix run`.

If this is the kind of bug report we can expect from this feature, with formatters having varying behaviors when it comes to files and directories, this would be another reason to remove `nix fmt`.

With something like `nix run`, there would be no expectations that the formatter magically behaves correctly; just that it gets invoked. (Also: [`nix dev`](https://github.com/NixOS/nix/issues/6241))

**Comment by roberth** [comment]
> It would also be good to have flags to `nix fmt`, and

We'd have scope creep until we've duplicated `treefmt`, but worse.

**Comment by whentze** [comment]
> If this is the kind of bug report we can expect from this feature, with formatters having varying behaviors when it comes to files and directories, this would be another reason to remove nix fmt.

Huh, interesting. I had somehow assumed that `nix fmt`, like other flake-based commands, would work on the flake tree, which does not have `.git`, I think.

**Comment by acid-bong** [comment]
Is your formatter nixfmt by any chance? It has this annoying issue that it doesn't ignore `.git/` and gitignored paths (like `.direnv/`). Alejandra and nixpkgs-fmt don't have that

**Comment by roberth** [comment]
This [doesn't](https://github.com/NixOS/nix/issues/9359#issuecomment-1816788525) seem actionable on the `nix` side of things, except for trimming the docs:
- #11613
