### ISSUE TITLE
Allow using substitutes when building remotely

### ISSUE THREAD

**Issue by k0001** [NixOS/nix#937]
Currently, when building a package remotely with `build-remote.pl`, if the remote host is missing some dependencies, these will be sent over the network from the local host. However, when the connection between the local and the remote hosts is slow, it would be preferable to download as many of those dependencies as possible from `nixos.org` using the substitutes approach. 

To achieve this, I think it should suffice to change `build-remote.pl` so that it passes, optionally, the `--use-substitutes` flag to `nix-copy-closure` (well, `Nix::CopyClosure::copyToOpen` actually). Please correct me if I am wrong, as I am not familiar with the code base here.

I wonder what is the best way to enable/disable this feature so that the caller of `nix-build` can decide whether to use substitutes in the remote end or not. 

I am happy to try and implement this.

**Comment by Ericson2314** [comment]
I'm thinking more generally, when a node builds derivations on behalf of a client, it should use the binary caches of the client + client itself, and *not* necessarily trust the derivations unless it also happens to also trust's their closures.

We might need intensional store for that though.

**Comment by k0001** [comment]
I've implemented this and it seems to work just fine: https://github.com/k0001/nix/commit/f98af9374e74d0a70dfb60881e08f8b875400aed - Now I don't need to wait for hours until dependencies are uploaded to the remote build server!

I've made the change on top of the 1.11 maintenance branch, as that is what I am using locally. I can send a pull request on top of `master` if you agree that this is the way to go.

**Comment by vcunat** [comment]
It seems nice to me to add that option. Note: that perl script is being migrated to C++ #341, but your change is so simple anyway...

**Comment by k0001** [comment]
Bump.

**Comment by domenkozar** [comment]
@k0001 sorry for closing your PR. I know it's really demotivating to close perfectly valid PR, but we're rewriting perl stuff to C++ so you'll have to implement this again (or ask @shlevy to help you out).

**Comment by shlevy** [comment]
@k0001 we just want `NIX_REMOTE_BUILD_SUBSTUTITUES=1` to mean use substitutes? I can add that.

**Comment by shlevy** [comment]
incorporated into #981

**Comment by k0001** [comment]
@domenkozar no worries! I understand perfectly. It is no use making this change in Perl if it won't ever be shipped.  

@shlevy thank you for going ahead with this change yourself!
