### ISSUE TITLE
nix-store O_RDWR

### ISSUE THREAD

**Issue by federicosacerdoti** [NixOS/nix#94]
In version 1.3 nix-store -qR attempts to open the db.sqlite in O_RDWR mode, even if --readonly is given. This was not the behavior in 1.1. Is this intended?

It prevents normal operation for me as db.sqlite is not writable by users, who need to be able to query dependencies.

Thanks,
FDS

**Comment by nh2** [comment]
I've put more info on this topic into #2196

**Comment by gilligan** [comment]
I think we can safely close this one because #2196 has much more info on this matter.
