### ISSUE TITLE
unbound XDG_DATA_DIRS reference

### ISSUE THREAD

**Issue by NedAnd1** [NixOS/nix#9414]
## Platform

- [X] Linux: Fedora
- [ ] macOS
- [ ] WSL

## Additional information
@iFreilicht @edolstra Due to PR #9312 and its check for `"$XDG_DATA_DIRS"` instead of `"${XDG_DATA_DIRS-}"` the nix-profile script breaks in our bash environments with the error "unbound variable" for the latest nix release of 2.19.0

## Output

<details><summary>Output</summary>

```log
+ XDG_STATE_HOME=/root/.local/state
+ source /root/.nix-profile/etc/profile.d/nix.sh
++ '[' -n /root ']'
++ '[' -n root ']'
++ NIX_LINK=/root/.nix-profile
++ '[' -n /root/.local/state ']'
++ NIX_LINK_NEW=/root/.local/state/nix/profile
++ '[' -e /root/.local/state/nix/profile ']'
++ '[' -t 2 ']'
++ export 'NIX_PROFILES=/nix/var/nix/profiles/default /root/.nix-profile'
++ NIX_PROFILES='/nix/var/nix/profiles/default /root/.nix-profile'
/root/.nix-profile/etc/profile.d/nix.sh: line 36: XDG_DATA_DIRS: unbound variable
```

</details>

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by iFreilicht** [comment]
Oh that's not good. Did you already check that changing it back to `"${XDG_DATA_DIRS-}"` fixes the issue?

**Comment by NedAnd1** [comment]
It would; please see PR #7920 for a similar fix which prevented an unbound variable reference in bash.

**Comment by NedAnd1** [comment]
Testing the script with some variation of `set -u` would prevent future instances of this from happening.

**Comment by iFreilicht** [comment]
I created #9425 to fix this as quickly as possible.

> Testing the script with some variation of set -u would prevent future instances of this from happening.

That would also require setting up an environment where those variables are actually unset, correct? Or am I misinterpreting [the bash manual](https://www.gnu.org/software/bash/manual/bash.html#The-Set-Builtin) here?

**Comment by NedAnd1** [comment]
> That would also require setting up an environment where those variables are actually unset, correct? Or am I misinterpreting [the bash manual](https://www.gnu.org/software/bash/manual/bash.html#The-Set-Builtin) here?

Yep, [unsetting](https://www.gnu.org/software/bash/manual/bash.html#index-unset) these variables could be part of the regression test proposed by issue #9315
