### ISSUE TITLE
`nix flake update --commit-lock-file` does not let you enter SSH key passphrase

### ISSUE THREAD

**Issue by Guanran928** [NixOS/nix#9421]
**Describe the bug**

`nix flake update --commit-lock-file` does not work with SSH key Git signing **with passphrase**

**Steps To Reproduce**

1. Setup Git signing with SSH key with passphease
2. Run `nix flake update --commit-lock-file`
3. Stuck
![image](https://github.com/NixOS/nix/assets/68757440/744a3923-99dd-46b6-8c69-e8a93078b18b)

**Expected behavior**

`nix flake update --commit-lock-file` let you enter SSH key password

**`nix-env --version` output**

```
~ > nix-env --version
nix-env (Nix) 2.18.1
```

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by thufschmitt** [comment]
@Guanran928 do you mean that it _specifically_ doesn't work with `nix flake update --commit-lock-file` or with any command that tries to fetch from a private repo?

**Comment by Guanran928** [comment]
> @Guanran928 do you mean that it _specifically_ doesn't work with `nix flake update --commit-lock-file` or with any command that tries to fetch from a private repo?


This isn't related to private repos, and this is why I specifically put `--commit-lock-file` in there.

I think it is stuck while signing the git commit, normally a prompt would pop-up, and without `--commit-lock-file` everything is just fine.
![image](https://github.com/NixOS/nix/assets/68757440/25811deb-3a08-468c-8d98-3ad847792604)

**Comment by thufschmitt** [comment]
Aaah, this is about _commit_ signing, sorry, I missed that.

I've opened #9445 which should fix it. Can you try it and confirm?

Do you also think you can provide a self-contained repro for adding a test?
