### ISSUE TITLE
Automatically link macOS applications to ~/Applications

### ISSUE THREAD

**Issue by mpscholten** [NixOS/nix#956]
(previously: https://github.com/NixOS/nixpkgs/issues/16455)

Currently, when installing macOS GUI applications like iTerm2 or Sequel Pro, you always have to manually symlink the applications from `~/.nix-profile/Applications` to `~/Applications`. This is bad user experience. E.g. homebrew cask can automatically do this for me.

Maybe we can find a way to do this automatically if the host OS is macOS. Let me know what you think about this idea :)

**Comment by joelmo** [comment]
Maybe this could be supported by nix-env, running a hook script placed under the nix-support folder.

**Comment by mpscholten** [comment]
Great suggestion :) Is there already a simple hook system in nix-env? Otherwise I'd try to build a very simple prototype for this in the next days.

**Comment by joelmo** [comment]
I can't see any such system in nix-env. I think it should be safe to make one as long as the system can be disabled.

**Comment by veprbl** [comment]
Can't you:

    mv ~/.nix-profile/Applications/* ~/Applications/
    rmdir ~/.nix-profile/Applications
    ln -s ~/Applications ~/.nix-profile/Applications

**Comment by mpscholten** [comment]
On the next `nix-env -i` the whole `~/.nix-profile` will be rebuilt thus loosing the `~/Applications` symlink. So that's not going to work.

**Comment by Sean1708** [comment]
Just FYI guys, this is [far more complicated than you might expect](https://github.com/caskroom/homebrew-cask/issues/13201) and I would strongly suggest reading that thread and all the links in it in their entirety before making a change like this.

**Comment by matthewbauer** [comment]
So I've been using a script to do this available here: https://raw.githubusercontent.com/matthewbauer/macNixOS/master/link-apps.sh.

## Proposal

Add a "post-create-profile-hook" as an option to Nix.

Users specify a script or executable to run after nix has successfully completed "createUserEnv". This script could look through $HOME/.nix-profile and do things to make the created derivations discoverable by the operating system. This hook should not be used to modify the profile in any way.

This hook is designed for non-NixOS systems that need to do some extra things after the "$HOME/.nix-profile" is created. The main use case is to link up Mac app bundles into ~/Applications/ but the idea is to make it generic enough that it could be used on any non-NixOS operating system.

This should be fairly easy to implement. It would work similarly configuration-wise to the "preBuildHook". The actual script execution would probably be done immediately after https://github.com/NixOS/nix/blob/master/src/nix-env/user-env.cc#L148 (line 148 in src/nix-env/user-env.cc).

**Comment by mpscholten** [comment]
Great suggestion. If it's easier to implement we could also just hard code the hook for now (so the user cannot change the hook). Then it just would be something like `system("<path to nix installation>/scripts/post-create-profile-hook")` in the `user-env.cc`.

Just got the idea for another very cool use case: We could also use the hook to automatically create `/etc/paths.d/nix` on macOS if it not exists. This way the nix profile is added to the PATH automatically. This way installing nix on macOS, is really just the `curl ... | bash` and nothing more (currently you still have to manually add the nix profile to the path).

Also thanks for sharing your script. I was already using a similar script, but it was never removing the old dead symlinks. Going to replace my script with yours 👍

**Comment by matthewbauer** [comment]
> Just got the idea for another very cool use case: We could also use the hook to automatically create ```/etc/paths.d/nix``` on macOS if it not exists. This way the nix profile is added to the PATH automatically. This way installing nix on macOS, is really just the ```curl ... | bash``` and nothing more (currently you still have to manually add the nix profile to the path).

I think that would be better as just an install step - there's no reason to rerun that each time it regenerates the profile. We can set /etc/paths.d/nix to /nix/var/profiles/default in a custom installer.

**Comment by NightMachinary** [comment]
Any updates?

**Comment by gpanders** [comment]
I am also interested in a way to do this. Are there any updates? The linked issues also seem to be unresolved/stale.

**Comment by Atemu** [comment]
There is a solution at the bottom of this: https://github.com/nix-community/home-manager/issues/1341

**Comment by MorganGeek** [comment]
> There is a solution at the bottom of this: [nix-community/home-manager#1341](https://github.com/nix-community/home-manager/issues/1341)

Thanks @Atemu, I have a newbie question : how to use your solution in practice? I'm not using home-manager yet, and I'm totally new to Nix.

**Comment by Atemu** [comment]
@MorganGeek just add the file to your `imports`. If you need help with that, make a post in the Discourse and ping me.

**Comment by cherryblossom000** [comment]
This issue is still relevant. I would love to stop using Homebrew, but currently still use it for installing casks/macOS applications.

**Comment by fricklerhandwerk** [comment]
I think the general problem can and should be addressed by external tools wrapping Nix, such as [done here with `home-manager`](https://github.com/nix-community/home-manager/issues/1341#issuecomment-1190875080).

@edolstra @domenkozar objections to closing this issue?

**Comment by hraban** [comment]
If anything, I would advise aliases rather than symlinks. Spotlight picks up aliases. I use something like this (warning: untested):

```sh
# Install all nix top level graphical apps
if [[ -d ~/.nix-profile/Applications ]]; then
	(cd ~/.nix-profile/Applications;
	for f in *.app ; do
		mkdir -p ~/Applications/
		rm -f "$HOME/Applications/$f"
		# Mac aliases don’t work on symlinks
		f="$(readlink -f "$f")"
		# Use Mac aliases because Spotlight doesn’t like symlinks
		osascript -e "tell app \"Finder\" to make new alias file at POSIX file \"$HOME/Applications\" to POSIX file \"$f\"" ; done
	done
	)
fi
```

That being said: it's not without drawbacks. If possible, it's strongly advised to find a way to cp -r the entire .app folder, as homebrew does. Homebrew used to use links, and eventually changed course. Background: "https://github.com/Homebrew/homebrew-cask/issues/3083".

That said, I use an alias for Emacs.app, and it's fine. The nixpkgs build of emacs breaks when you cp it to ~/Applications :/ (but that's a bug report for another time)

- https://apple.stackexchange.com/questions/95906/does-spotlight-normally-index-links-in-applications
- https://apple.stackexchange.com/questions/23653/can-i-make-a-symlink-to-a-app-folder-in-applications-directory-show-up-in-spo

**Comment by fricklerhandwerk** [comment]
Discussed in Nix team meeting 2023-01-06:

- @fricklerhandwerk: as written above I think this should be closed as `wontfix`, it is outside of Nix's responsibilities. should be done by Nixpkgs, nix-darwin, home-manager.
    - @thufschmitt: we could do it if there was a lightweight Nix-y way
- agreement, won't fix

**Comment by jost-s** [comment]
@fricklerhandwerk The issue was moved here from the Nixpkgs repo with the rationale that Nixpkgs doesn't have enough write permissions and that it's very similar to managing ~/.nix-profile
https://github.com/NixOS/nixpkgs/issues/16455#issuecomment-229785576

So where should it go from here, you think? Not every Nix user under macOS uses nix-darwin, so probably home-manager?

**Comment by fricklerhandwerk** [comment]
Either should do in principle. But conversely one can use nix-darwin without Home Manager, so probably both have to support that.
