### ISSUE TITLE
`nix copy --substitute-on-destination` has no effect

### ISSUE THREAD

**Issue by SharzyL** [NixOS/nix#9591]
**Describe the bug**

When using `nix copy somePath --to ssh-ng://some-remote --substitute-on-destination`, `somePath` is still copied from local store instead of fetching from a substitute.

**Steps To Reproduce**

Pick some path in cache.nixos.org, e.g. `/nix/store/y7abhs9glxfcg7lgcdc8i4ml5wg5ly92-go-1.21.4`, copy it to a remot host
```console
# nix copy /nix/store/y7abhs9glxfcg7lgcdc8i4ml5wg5ly92-go-1.21.4 --to ssh-ng://some-remote --substitute-on-destination
[0 copied (16.4/204.4 MiB)] copying path '/nix/store/qn3ggz5sf3hkjs2c797xf7nan3amdxmp-glibc-2.38-27' to 'ssh-ng://some-remote'
```

**Expected behavior**

We should see something like
```console
 fetching '/nix/store/qn3ggz5sf3hkjs2c797xf7nan3amdxmp-glibc-2.38-27' from https://cache.nixos.org
```

**`nix-env --version` output**
2.18.1

**Additional context**

I traced down the call stack of `nix copy`:

https://github.com/NixOS/nix/blob/5c917c32048ef185ea0eec352c3505485aa3212c/src/nix/copy.cc#L57-L58

calls `copyPaths(…, const RealisedPath::Set & paths, …)`

https://github.com/NixOS/nix/blob/5c917c32048ef185ea0eec352c3505485aa3212c/src/libstore/store-api.cc#L1048

calls `copyPaths(…, const StorePathSet & storePaths, …)`

https://github.com/NixOS/nix/blob/5c917c32048ef185ea0eec352c3505485aa3212c/src/libstore/store-api.cc#L1093

calls `queryValidPaths`

https://github.com/NixOS/nix/blob/5c917c32048ef185ea0eec352c3505485aa3212c/src/libstore/store-api.cc#L843

which simply ignores the arg `SubstituteFlag maybeSubstitute`

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by thufschmitt** [comment]
Thanks for diving into the cause already @SharzyL :)

There's one extra step in the call stack, because `queryValidPaths` [is actually overridden by the `RemoteStore` implementation](https://github.com/NixOS/nix/blob/e687e867542153bd6d0e816a8c56e4ad8c54d958/src/libstore/remote-store.cc#L216-L233) (that backs the `ssh://` store), which sends the “substitute” bit to the remote daemon, which itself [uses it to substitute if needed](https://github.com/NixOS/nix/blob/e687e867542153bd6d0e816a8c56e4ad8c54d958/src/libstore/daemon.cc#L292-L299).

That being said, I think I can indeed reproduce it not substituting, so my explanation doesn't hold for some reason.

Fwiw, using `ssh://` instead of `ssh-ng://` works

**Comment by SharzyL** [comment]
Thanks for your reply! I had ignored the fact that `queryValidPaths` is overriden.

As is shown in `RemoteStore::queryValidPaths`, the arg `maybeSubstitute` is still ignored, and only the bit from settings is used:

https://github.com/NixOS/nix/blob/e687e867542153bd6d0e816a8c56e4ad8c54d958/src/libstore/remote-store.cc#L228

Now that `ssh://` works, is it using another `Store::queryValidPaths` implementation?

**Comment by thufschmitt** [comment]
> As is shown in RemoteStore::queryValidPaths, the arg maybeSubstitute is still ignored, and only the bit from settings is used:

Duh, I read it too fast indeed :grimacing: 

> Now that ssh:// works, is it using another Store::queryValidPaths implementation?

Yes, `ssh://` is using a different protocol altogether, and its implementation does handle the flag properly

https://github.com/NixOS/nix/blob/e687e867542153bd6d0e816a8c56e4ad8c54d958/src/libstore/legacy-ssh-store.cc#L327-L340

**Comment by SharzyL** [comment]
#8744 seems to be related. I agree with @TravisWhitaker that `builder-use-substitute` should not imply using substitute for `nix copy`. I am working on a fix for this.
