### ISSUE TITLE
Fix failing NixOS tests on master

### ISSUE THREAD

**Issue by Ericson2314** [NixOS/nix#9596]
We will need to bump to a commit containing the https://github.com/NixOS/nixpkgs/pull/271423 backport (easy) but also containing the two PRs we rely on today which, while based on master commits, had to be merged to staging branches.

@vcunat (thanks!) says there will be another `staging-next-23.05` -> `release-23.05` in a week or so, after which we'll be good on that.

Once this is done, Hydra should be all green again, and it will be easier to land https://github.com/NixOS/nix/pull/9535 safely.

**Comment by vcunat** [comment]
I expect this is the PR which you might want to watch to merge: https://github.com/NixOS/nixpkgs/pull/273936

**Comment by Ericson2314** [comment]
Thanks @vcunat!
