### ISSUE TITLE
Store paths in db should not be validated for leading `.`

### ISSUE THREAD

**Issue by roberth** [NixOS/nix#9624]
I've already had paths with dots in my store and this change breaks basic commands such as `nix-collect-garbage` or `nix-store --delete`, so I can't even reliably get rid of those paths from my store now (other than downgrading nix).

I think at the very least this change shouldn't break basic commands like those.

_Originally posted by @jaen in https://github.com/NixOS/nix/issues/9095#issuecomment-1858316222_

**Comment by jaen** [comment]
Also, before I forget again – I think that may not only be "store paths in db" that this breaks on.

In one attempt to fix this before downgrading I removed the offending path from `/nix/store` by re-mounting R/W and then removing the references to it from the SQLite DB – yes, I know that's a nuclear option, but didn't have any better ideas – and while previously it helped me to get rid of obstinate store paths I couldn't remove any other way, in this case it was still failing, so I would assume that this mean it might also validate store paths inside the derivations the same way?

Not sure how good of a guess that is, but it might make sense to verify other path usage, than just in the db as well.

**Comment by nrdxp** [comment]
Hit this as well [here](https://github.com/NixOS/nix/issues/5176#issuecomment-1881731802). In order to at least get past garbage collection I applied the following patch on top of nix 2.19:
```diff
diff --git a/src/libstore/path.cc b/src/libstore/path.cc
index ec3e53232..c1e2392bd 100644
--- a/src/libstore/path.cc
+++ b/src/libstore/path.cc
@@ -11,8 +11,6 @@ static void checkName(std::string_view path, std::string_view name)
     if (name.size() > StorePath::MaxPathLen)
         throw BadStorePath("store path '%s' has a name longer than %d characters",
             path, StorePath::MaxPathLen);
-    if (name[0] == '.')
-        throw BadStorePath("store path '%s' starts with illegal character '.'", path);
     // See nameRegexStr for the definition
     for (auto c : name)
         if (!((c >= '0' && c <= '9')
```
and ran a `sudo nix-collect-garbage` with the results, and it at least got rid of the invalid paths for me.

**Comment by SuperSandro2000** [comment]
I think [this hydra failure](https://hydra.nixos.org/build/246116030/nixlog/6) could be related to this as well.

**Comment by douglaz** [comment]
> Hit this as well [here](https://github.com/NixOS/nix/issues/5176#issuecomment-1881731802). In order to at least get past garbage collection I applied the following patch on top of nix 2.19:
> 
> ```diff
> diff --git a/src/libstore/path.cc b/src/libstore/path.cc
> index ec3e53232..c1e2392bd 100644
> --- a/src/libstore/path.cc
> +++ b/src/libstore/path.cc
> @@ -11,8 +11,6 @@ static void checkName(std::string_view path, std::string_view name)
>      if (name.size() > StorePath::MaxPathLen)
>          throw BadStorePath("store path '%s' has a name longer than %d characters",
>              path, StorePath::MaxPathLen);
> -    if (name[0] == '.')
> -        throw BadStorePath("store path '%s' starts with illegal character '.'", path);
>      // See nameRegexStr for the definition
>      for (auto c : name)
>          if (!((c >= '0' && c <= '9')
> ```
> 
> and ran a `sudo nix-collect-garbage` with the resulting binary; it at least got rid of the invalid paths for me.

This didn't work for me. Still getting:
```
$ sudo nix-collect-garbage
finding garbage collector roots...
deleting garbage...
0 store paths deleted, 0.00 MiB freed
error: store path '4xmh7gqm7kr95dilbq1g6s1dhdf4xdg5-.cargo' starts with illegal character '.'
```

**Comment by roberth** [comment]
We have decided to support leading `.` from now on, because of opportunity cost and #912.
- Closed by https://github.com/NixOS/nix/pull/9867
