### ISSUE TITLE
gcc fails to build on OS X

### ISSUE THREAD

**Issue by rprechelt** [NixOS/nix#965]
I know there has been a couple of gcc issues raised recently but I still can't get any of the following packages to build: 

    nixpkgs-gcc
    nixpkgs-gcc6
    gcc-wrapper-6.1.0
    gcc-wrapper-5.3.0

Attempted with either `nix-env -iA nixpkgs.gcc*` or `nix-env -i gcc-wrapper-*`. 

This is the error received when attempting to build `nixpkgs-gcc`. 

    make: *** [bootstrap] Error 2
    builder for ‘/nix/store/4b1m5271ks3hzw9c7db2f195r93zsz6g-gcc-5.3.0.drv’ failed with exit code 2
    cannot build derivation ‘/nix/store/im9lrvna49ryyvcv6kd9m1pja825qp10-gcc-wrapper-5.3.0.drv’: 1 dependencies couldn't be built
    error: build of ‘/nix/store/im9lrvna49ryyvcv6kd9m1pja825qp10-gcc-wrapper-5.3.0.drv’ failed

This is a completely fresh install of OS X El Capitan (`nix `was the first thing that I installed, closely followed by my `gcc` attempt), and with a fresh install of `nix`.

**Comment by rprechelt** [comment]
Attempting `nix-env -iA nixpkgs.gcc6` results in the following error:
```
ld: library not found for -lc
collect2: error: ld returned 1 exit status
Makefile:945: recipe for target 'libgcc_s.dylib' failed
make[3]: *** [libgcc_s.dylib] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/private/var/folders/mt/c_dppb2s51bbvm3yy67mns080000gn/T/nix-build-gcc-6.1.0.drv-0/build/x86_64-apple-darwin15.5.0/libgcc'
```

**Comment by vcunat** [comment]
This should be closed in favor of https://github.com/NixOS/nixpkgs/issues/16806 (I can't do it)

**Comment by copumpkin** [comment]
#1008
