### ISSUE TITLE
btrfs swap file (in an encypted system if that matters) cant hibernate

### ISSUE THREAD

**Issue by beh-10257** [NixOS/nix#9660]
**Describe the bug**
systemctl can't find the file to hibernate to
so yeah no hibernation

**Expected behavior**

hibernation working

nix-env (Nix) 2.18.1

**Additional context**
https://discourse.nixos.org/t/btrfs-swap-not-enough-swap-space-for-hibernation/36805
my whole filesystem is encrypted excluding the boot partition

![image](https://github.com/NixOS/nix/assets/77834479/f2806506-eb80-41d4-b833-5323dc98c2b7)
this shows that the swap actually works
![image](https://github.com/NixOS/nix/assets/77834479/65ea4dc1-59a3-490d-bce1-a06a1213d506)
this shows specifically the errors

[my journalctl -b 0 --system](https://github.com/NixOS/nix/files/13759989/broken_hibernation.log)

**Comment by cole-h** [comment]
This sounds less like a Nix (the package manager) issue and more like a NixOS (the operating system built upon Nix-the-package-manager) issue. For NixOS issues, please report them to https://github.com/NixOS/nixpkgs/issues/.
