### ISSUE TITLE
Can't build nix on Ubuntu 16.04

### ISSUE THREAD

**Issue by popey** [NixOS/nix#967]
Tried form tip of git and from a 1.11.2 release tarball. Both end the same way:-

$ make
  GEN    Makefile.config
  GEN    doc/manual/version.txt
  GEN    doc/manual/manual.xmli
  GEN    doc/manual/manual.is-valid
I/O error : Attempt to load network entity http://docbook.org/xml/5.0/rng/docbook.rng
warning: failed to load external entity "http://docbook.org/xml/5.0/rng/docbook.rng"
Relax-NG parser error : xmlRelaxNGParse: could not load http://docbook.org/xml/5.0/rng/docbook.rng
Relax-NG schema http://docbook.org/xml/5.0/rng/docbook.rng failed to compile
-:1: parser error : Document is empty
doc/manual/local.mk:29: recipe for target 'doc/manual/manual.is-valid' failed
make: **\* [doc/manual/manual.is-valid] Error 1

Full output:-

alan@gort:~/Development/nix/nix-1.11.2$ ./bootstrap.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: configure.ac: not using Automake
autoreconf: Leaving directory`.'
alan@gort:~/Development/nix/nix-1.11.2$ ./configure --prefix=/usr/local
checking for a sed that does not truncate output... /bin/sed
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for the canonical Nix system name... x86_64-linux
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking for struct dirent.d_type... yes
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for pubsetbuf... yes
checking for statvfs... yes
checking for lutimes... yes
checking whether it is possible to create a link to a symlink... yes
checking how to run the C++ preprocessor... g++ -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking locale usability... yes
checking locale presence... yes
checking for locale... yes
checking how to run the C preprocessor... gcc -E
checking err.h usability... yes
checking err.h presence... yes
checking for err.h... yes
checking for curl... /usr/bin/curl
checking for bash... /bin/bash
checking for patch... /usr/bin/patch
checking for xmllint... /usr/bin/xmllint
checking for xsltproc... /usr/bin/xsltproc
checking for flex... /usr/bin/flex
checking for bison... /usr/bin/bison
checking for perl... /usr/bin/perl
checking for sed... /bin/sed
checking for tar... /bin/tar
checking for bzip2... /bin/bzip2
checking for gzip... /bin/gzip
checking for xz... /usr/bin/xz
checking for dot... no
checking for dblatex... no
checking for pv... pv
checking whether Perl is recent enough... yes
checking for the Perl installation prefix... ${exec_prefix}/lib/perl5/site_perl/5.22.1/x86_64-linux-gnu-thread-multi
checking for cat... /bin/cat
checking for tr... /usr/bin/tr
checking for openssl... /usr/bin/openssl
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for OPENSSL... yes
checking for BZ2_bzWriteOpen in -lbz2... yes
checking bzlib.h usability... yes
checking bzlib.h presence... yes
checking for bzlib.h... yes
checking for SQLITE3... yes
checking for LIBCURL... yes
checking for SODIUM... yes
checking for LIBLZMA... yes
checking whether DBD::SQLite works... yes
checking whether WWW::Curl works... yes
checking for otool... no
checking that otool works... not needed
checking whether to build the Perl bindings... yes
checking for setresuid... yes
checking for setreuid... yes
checking for lchown... yes
checking for strsignal... yes
checking for posix_fallocate... yes
checking for nanosleep... yes
checking for sysconf... yes
checking if you have a recent GNU tar... yes
configure: creating ./config.status
config.status: creating config.h
alan@gort:~/Development/nix/nix-1.11.2$ make
  GEN    Makefile.config
  GEN    doc/manual/version.txt
  GEN    doc/manual/manual.xmli
  GEN    doc/manual/manual.is-valid
I/O error : Attempt to load network entity http://docbook.org/xml/5.0/rng/docbook.rng
warning: failed to load external entity "http://docbook.org/xml/5.0/rng/docbook.rng"
Relax-NG parser error : xmlRelaxNGParse: could not load http://docbook.org/xml/5.0/rng/docbook.rng
Relax-NG schema http://docbook.org/xml/5.0/rng/docbook.rng failed to compile
-:1: parser error : Document is empty
doc/manual/local.mk:29: recipe for target 'doc/manual/manual.is-valid' failed
make: **\* [doc/manual/manual.is-valid] Error 1
alan@gort:~/Development/nix/nix-1.11.2$

**Comment by veprbl** [comment]
Dirty workaround would be to remove occurrences ```--nonet``` from doc/manual/local.mk

**Comment by vcunat** [comment]
Why not use our debs directly, at least as a work-around? https://github.com/NixOS/nix/pull/892#issuecomment-231095884

**Comment by armijnhemel** [comment]
Can this one be closed, because #1066 has been merged?

**Comment by popey** [comment]
I just tried nix-1.11.9 snapshot, and tried the option referenced in #1066 but maybe I'm holding it wrong?

alan@gort:~/Development/nix/nix-1.11.9$ ./configure --prefix=/usr/local --disable-doc-gen
configure: WARNING: unrecognized options: --disable-doc-gen

**Comment by armijnhemel** [comment]
It seems that this fix was not applied to the 1.11-maintenance branch, just to master. Adding @edolstra

**Comment by nh2** [comment]
> I/O error : Attempt to load network entity http://docbook.org/xml/5.0/rng/docbook.rng

@popey Try

```
sudo apt-get install docbook-xsl-ns
```

to fix that one, worked for me on Ubuntu 16.04. See https://github.com/NixOS/nix/issues/506#issuecomment-507899124

**Comment by nh2** [comment]
PR to fix it #2979
