### ISSUE TITLE
(FIXED) if this error accours, you need to shutdown your mac and hold the start button on the next boot

### ISSUE THREAD

**Issue by fschlegelone** [NixOS/nix#9678]
## Platform

- [ ] Linux: 
- [ ] macOS
- [ ] WSL

## Output

<details><summary>Output</summary>

```log

<!-- paste console output here and remove this comment -->

```

</details>

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by abathur** [comment]
There's no information included here about the context of the error message. I'm fairly confident that Nix and it's installer do not directly emit it, so there's nothing actionable on the Nix side without more context.

Happy to reopen if you update.

**Comment by fschlegelone** [comment]
sorry mb.
