### ISSUE TITLE
Hacking guide for `nix-shell` is outdated

### ISSUE THREAD

**Issue by RaitoBezarius** [NixOS/nix#9680]
## Problem

`autoreconfPhase` does not work in `nix-shell`, the configure phase fails with
```
❯ ./configure $configureFlags --prefix=$(pwd)/outputs/out
configure: error: invalid feature name: `build --enable-unit-tests --enable-functional-tests --disable-internal-api-docs --enable-doc-gen --enable-install-unit-tests --with-check-bin-dir'
```

## Proposal

I don't know.

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open documentation issues and pull requests] for possible duplicates: at least, with what GH search gives me.

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/src
[open documentation issues and pull requests]: https://github.com/NixOS/nix/labels/documentation

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by cole-h** [comment]
I was able to run this just fine:

```
$ nix-shell
nix-shell$ autoreconfPhase
nix-shell$ ./configure $configureFlags --prefix=$(pwd)/out
```

Your prompt makes me think you're using a non-bash shell... and I've seen the same issue with fish:

```
bash$ nix-shell --run autoreconfPhase
bash$ nix-shell --run fish
fish$ ./configure $configureFlags --prefix=$(pwd)/out
configure: error: invalid feature name: `build --enable-unit-tests --enable-functional-tests --disable-internal-api-docs --enable-doc-gen --enable-install-unit-tests --with-check-bin-dir'
```

So maybe it's some shell quoting issue in non-bash shells?

For my nix hacking needs, I've taken to doing the following:

```
$ nix develop .#native-clangStdenvPackages
nix develop$ autoreconfPhase
nix develop$ ./configure $configureFlags --prefix=$(pwd)/out
# exit nix develop
$ nix develop .#native-clangStdenvPackages -c fish 
```

and after that point, everything works for me (clang stdenv so I can use `bear` for LSP support in my editor).

**Comment by RaitoBezarius** [comment]
Indeed, I'm using `zsh`. I see.

**Comment by fricklerhandwerk** [comment]
It's just `nix-shell` living in the wrong place. Sorry.
