### ISSUE TITLE
Segfault when running any nix command

### ISSUE THREAD

**Issue by tilmanmixyz** [NixOS/nix#9685]
**Describe the bug**
When running any `nix` command, no matter if with the experimental feature `nix-command` enabled or an old command like `nix-env --version`, the command core dumps/segfaults.

**Steps To Reproduce**

1. run the `nix` command

**Expected behavior**
Running the command and not segfaulting

**`nix-env --version` output**
 can not be run because it segfault as well, but the input in my systems flake.lock is the newest commit in nixpkgs-unstable
and running pkgs.nixUnstable, but im gessing nix 2.19.2

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

![segfault](https://github.com/NixOS/nix/assets/130175796/b1d9fbdf-723b-44af-82eb-39facdea0bf8)

**Comment by tilmanmixyz** [comment]
Nevermind, it is not reproducible on a fresh virtual machine, so probably an issiue on my local config.
Which sucks because i now can't change anything.

**Comment by teidova** [comment]
Having the same issue.

**Comment by awtterpip** [comment]
@teidova im having the same issue, did you find the cause?

**Comment by teidova** [comment]
Still occured on a fresh install, loading an older config solved it tho.

**Comment by YellowOnion** [comment]
Probably best to open another issue if OP isn't going to open this, might be worth posting more info, like output of `ldd $(which nix)`, gdb stack trace, common hardware.
