### ISSUE TITLE
"Did you mean ..." when typing wrong package name

### ISSUE THREAD

**Issue by mpscholten** [NixOS/nix#972]
Currently when typing the wrong package name, e.g. `nix-env -i cabal` instead of `nix-env -i cabal-install` you will get `error: selector ‘cabal’ matches no derivations`. That's not really helpful.

Maybe `nix-env` could check for possible package with a similar name, and then output something like `error: selector ‘cabal’ matches no derivations. Did you mean ‘cabal-install‘?`

**Comment by copumpkin** [comment]
Let's do this on attribute paths too. Attribute names are so last year :)
