### ISSUE TITLE
Parser: `or` in `attr`

### ISSUE THREAD

**Issue by simonvandel** [NixOS/nix#975]
Looking at https://github.com/NixOS/nix/blob/06068b353d7867d0e0299d4285e9b1a46195144c/src/libexpr/parser.y#L484-L487

I was wondering why an `attr` could be the `or` keyword.

Is this intentional? What is the use case?

**Comment by simonvandel** [comment]
From https://github.com/NixOS/nix/blob/06068b353d7867d0e0299d4285e9b1a46195144c/src/libexpr/parser.y#L358-L360

it looks like it is for backwards compatibility.
Is this correct?

**Comment by vcunat** [comment]
We (still) do have `lib.or` and `lib.and` functions in nixpkgs.

**Comment by simonvandel** [comment]
So if I understand it correctly, the `or` keyword is not really needed as or can be defined as a library function? It is just there for backwords compatibility.

I was just wondering why the `or` keyword was defined in the grammar at that location.

**Comment by shlevy** [comment]
The `or` keyword is something completely different than `lib.or`.
