### ISSUE TITLE
Failed downloads cause nix-build to halt despite --keep-going (xz: (stdin): File format not recognized)

### ISSUE THREAD

**Issue by obadz** [NixOS/nix#977]
I regularly (about 20 times per day when I'm doing some nix-intensive work) get this kind of error when trying to fetch a package from the cache:

```
curl: (22) The requested URL returned error: 500 Internal Server Error

/nix/store/4pssr3p6h2gqym3lxls3kfvr9r7xzdl9-xz-5.2.2-bin/bin/xz: (stdin): File format not recognized
error: unexpected end-of-file
fetching path ‘/nix/store/nmmk8739ivi3i63mljlwx5jizhy59lb0-bzip2-1.0.6.0.1-man’...
download of ‘https://cache.nixos.org/nar/181dad6drbxlyy63clylgsk50nf778sqy1hwam6cyjyb4brg9ndl.nar.xz’ failed: No such file or directory
could not download ‘/nix/store/ac2ik8ajndx4rz0mr90f18fb46z89d8x-SDL-1.2.15’ from any binary cache
fetching path ‘/nix/store/ac2ik8ajndx4rz0mr90f18fb46z89d8x-SDL-1.2.15’ failed with exit code 1
fetching path ‘/nix/store/70r977zrqlzx2a9l4spyzbv4b6ybwvlw-ca-certificates.crt’...
killing process 19932
killing process 19926
killing process 19921
killing process 19951
```

Given `--keep-going`, I would expect `nix-build` to continue and build everything that it can, without this particular derivation.

Better yet, `nix-build` could continue running and retry the failed download, maybe 20 seconds later, up to 3 times?

Instead `nix-build` halts abruptly and kills every build that might be running at the time. In other words: a very commonly concurring and spurious network error can potentially lead to a very expensive build being interrupted and having to be started again from scratch.

**Comment by copumpkin** [comment]
For the curious, here's an instance of the 500 from CloudFront:

```
HTTP/1.1 500 Internal Server Error
Content-Type: application/xml
Connection: keep-alive
Date: Tue, 19 Jul 2016 12:00:39 GMT
Server: AmazonS3
Age: 72
X-Cache: Error from cloudfront
Via: 1.1 fb63ddec72f5ddb885466333fe83d86e.cloudfront.net (CloudFront)
X-Amz-Cf-Id: yQjBBI1nhG6rVXOpwbIg0v-nltJ1NMQTYaj1uzQMLD2UZNa0QDvXHg==
```

**Comment by copumpkin** [comment]
In my case, it offered the `--fallback` option and kept going though.

**Comment by obadz** [comment]
@copumpkin, yes `--fallback` does work but then the failing build will happen locally from source. I wish to avoid that.
