### ISSUE TITLE
Installer dies if no /etc/tmpfiles.d/ present

### ISSUE THREAD

**Issue by mmorini** [NixOS/nix#9777]
## Platform

- [X] Linux: Intel Clear Linux OS
- [ ] macOS
- [ ] WSL

## Additional information

By construction, being "stateless" ICL tends to miss system directories normally present in more mainstream distros.

## Output

<details><summary>Output</summary>

```log
...
```

</details>
Sorry, missed the exact output error, but I think the problem here is sort of obvious. Creating a root-owned /etc/tmpfiles.d/ directory fixes the issue. It's probably a matter of including this step in the installer.

**Comment by grahamc** [comment]
I don’t usually comment on these because I don’t want to spam or solicit, but can you test the determinate nix installer in that environment? I wonder if it would work, I’ve not talked to Clear users yet. Ref: https://install.determinate.systems

On Mon, Jan 15, 2024, at 12:32 PM, Matteo Morini wrote:
> 
> 
> Platform
> 
>  • Linux: Intel Clear Linux OS
>  • macOS
>  • WSL
> Additional information
> 
> By construction, being "stateless" ICL tends to miss system directories normally present in more mainstream distros.
> 
> Output
> 
> Output
> `...
`

**Comment by abathur** [comment]
There's an earlier thread where another user who ran into this picked at it a bit:
- #7990

That should help rule out some approaches. I also left some questions in that thread that didn't get answered, if you still have the ability to pick at them.

**Comment by mmorini** [comment]
Folks, I apologize profusely for not doing my homework; I hadn't realized this is a duplicate of https://github.com/NixOS/nix/issues/7990 - I propose we close this issue and rehash the proper one.

**Comment by mmorini** [comment]
Happily complying
