### ISSUE TITLE
gitlab-container-registry has a changed hash and fails to download

### ISSUE THREAD

**Issue by exi** [NixOS/nix#9789]
**Describe the bug**

Cannot install gitlab-container-registry because of a hash mismatch after download

**Steps To Reproduce**

```
$ nix shell nixpkgs#gitlab-container-registry
error: hash mismatch in fixed-output derivation '/nix/store/3ncs0hhnjq99yag26y4f3bpsnj1f1qr3-source.drv':
         specified: sha256-vQ5bP2S1McZxD+Mjw0y/+GB8ntv8nQynM1cIWtUK7pU=
            got:    sha256-egslb+8+RsDjpL5xQpdCU3QwFH59grRCkODQnAkZe/0=
error: 1 dependencies of derivation '/nix/store/34bzhawdqc57f68ffdj59ckh0yqcb6ws-gitlab-container-registry-3.88.0.drv' failed to build
```

**Expected behavior**

It should just work/install correctly 

```
$ nix-env --version
nix-env (Nix) 2.18.
```

**Comment by cole-h** [comment]
This sounds less like a Nix (the package manager) issue and more like a Nixpkgs (the package set and related tooling built upon Nix-the-package-manager) issue. For Nixpkgs issues, please report them to https://github.com/NixOS/nixpkgs/issues/.
