### ISSUE TITLE
2.18.2 release

### ISSUE THREAD

**Issue by roberth** [NixOS/nix#9826]
**Is your feature request related to a problem? Please describe.**

https://github.com/NixOS/nix/pull/9366 was merged in November, but still hasn't made its way to users.

**Describe the solution you'd like**

Release 2.18.2.

**Additional context**

- https://github.com/NixOS/nixpkgs/pull/282401#issuecomment-1902747509

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by edolstra** [comment]
That's because the 2.18 branch is broken: https://hydra.nixos.org/eval/1803781
