### ISSUE TITLE
macOS

### ISSUE THREAD

**Issue by FabienDuval-dev** [NixOS/nix#9845]
## Platform

- [ ] Linux: 
- [x] macOS
- [ ] WSL

## Output

<details><summary>Output</summary>

```log

<!-- paste console output here and remove this comment -->

```

</details>

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by cole-h** [comment]
It's impossible to help you with your issue if you don't write a descriptive title and include the console output, as the template suggests. Feel free to reopen if you can make this more descriptive / actionable!
