### ISSUE TITLE
Using remote flakes to build a local app

### ISSUE THREAD

**Issue by lfdominguez** [NixOS/nix#9862]
**Is your feature request related to a problem? Please describe.**
I want to organize all projects build in a dedicated repo, vs need to copy and maintain the same flake.nix for all my projects. So I need to have a git repository with the generic nix files that allow to build the projects, for example:
```nix
full_pom_content = builtins.readFile ./pom.xml;
before_properties_content = builtins.elemAt (builtins.split "<properties>" full_pom_content) 0;

binary_name = builtins.elemAt (builtins.match ".*<artifactId>(.+)</artifactId>.*" before_properties_content) 0;
binary_version = builtins.elemAt (builtins.match ".*<version>(.+)</version>.*" before_properties_content) 0;
```
This gets the 'name' and 'version' of a common maven project using its `pom.xml` file. The problem is when I try to use this flake over a local directory that doesn't have the flake.nix, for example, the project is on `Work/Java/App`:
```sh
# cd Work/Java/App
# nix build <my_repo>#jhipster.java_17.no_nodejs
==> Fail with: (...)pom.xml: No such file or directory
```
Of course, because the `readfile` is getting the path where the flakes are, not my current project directory.

I have 20+ java projects that I want to convert the build system to Nix, so the current approach is to copy the flake.nix over each project? So in any build script change, then need to change every file?

**Describe the solution you'd like**
I will like that build has some flag to tell that merge the flake path with my local path, or add a custom variable with my local path that allow to read without use `--impure`.

**Describe alternatives you've considered**
`--impure` not allowed

**Additional context**
![image](https://github.com/NixOS/nix/assets/5604131/585fdc4b-0a85-485f-bf80-c2dba2de4c80)

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by thufschmitt** [comment]
If `--impure` is acceptable, then `builtins.readEnv "PWD"` should get you there.

A slightly less invasive but more reliable solution might be to have a thin wrapper in all your projects that just calls to some centrally defined library code, passing the current path as parameter.

Could be something like a `default.nix` file like the below (or the flake equivalent, but that's too boilerplate-y to inline here):

```nix
(import (builtins.getFlake "<my repo>")).buildJavaPackages { system = builtins.currentSystem; root = ./.; }
```

**Comment by lfdominguez** [comment]
> If `--impure` is acceptable, then `builtins.readEnv "PWD"` should get you there.
> 
> A slightly less invasive but more reliable solution might be to have a thin wrapper in all your projects that just calls to some centrally defined library code, passing the current path as parameter.
> 
> Could be something like a `default.nix` file like the below (or the flake equivalent, but that's too boilerplate-y to inline here):
> 
> ```nix
> (import (builtins.getFlake "<my repo>")).buildJavaPackages { system = builtins.currentSystem; root = ./.; }
> ```

Humm taking this into account, then on my CI script I can create a `flake.nix` on the repo and import the real flake repo and then inside this new flake get the `src` and pass to that flake.... thanks
