### ISSUE TITLE
`nix repl` ignores file argument

### ISSUE THREAD

**Issue by roberth** [NixOS/nix#9868]
**Describe the bug**

```
$ nix run nix -- repl repl.nix --show-trace
Welcome to Nix 2.20.0pre20240127_4025409. Type :? for help.

path '/home/user/src/hercules-ci-agent/repl.nix' does not contain a 'flake.nix', searching up
warning: Git tree '/home/user/h/hercules-ci-agent' is dirty
Loading installable 'git+file:///home/user/h/hercules-ci-agent#'...
Added 16 variables.
```

I forgot to specify `--file`, but that doesn't mean that the command should just do something else!

**Steps To Reproduce**

1. Try to load a file without specifying `--file`.

**Expected behavior**

Fail with one of

- Registry entry `repl.nix` does not exist (or whichever file it was)
- `repl.nix` is a file, not a flake

Note that we shouldn't mix local lookups and global lookups, because that's a vulnerability if the working directory is not trusted.

**`nix-env --version` output**

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by thufschmitt** [comment]
Just to confirm: This only happens with the `repl-flake` (or `flake`) feature enabled, right?
