### ISSUE TITLE
Log output spammed with repeated "Ignoring setting '...' because experimental-feature '...' is not enabled" when building remotely

### ISSUE THREAD

**Issue by Ma27** [NixOS/nix#9889]
**Describe the bug**

When running builds on a remote machine using `ssh-ng`, I get the following warnings for each build that's scheduled on a remote machine:

```
warning: Ignoring setting 'auto-allocate-uids' because experimental feature 'auto-allocate-uids' is not enabled
warning: Ignoring setting 'impure-env' because experimental feature 'configurable-impure-env' is not enabled
```

This means a lot of visual overhead, especially in case of many small builds (e.g. crates being put into store-paths with [`crane`](https://github.com/ipetkov/crane)).

Also, why does this appear in the first place? I didn't configure anything like that (config files below, perhaps I'm missing something).

**Steps To Reproduce**

0. Define a single remote builder that's using `ssh-ng` in your `nix.conf`
1. Modify `pkgs.hello` & `pkgs.sl` so that it needs to be rebuilt on a recent `nixpkgs` checkout (e.g. by adding a `postPatch = "#noop";`).
2. Run `nix build -f . hello sl -j0 -L`

**Expected behavior**

The warning should appear once at most.when running `nix build`.

**`nix-env --version` output**

`nix-env (Nix) 2.19.3`

**Additional context**

###### /etc/nix/nix.conf

```
allow-import-from-derivation = false
allowed-uris = github: gitlab: git+https://git.mbosch.me git+https://git.sr.ht https://github.com git+https://github.com https://git.sr.ht
allowed-users = *
auto-optimise-store = false
builders = @/etc/nix/builder-configs/darwin-main;@/etc/nix/builder-configs/roflmayr
builders-use-substitutes = true
cores = 4
experimental-features = nix-command flakes
extra-allowed-users = nixseparatedebuginfod
extra-sandbox-paths = 
log-lines = 0
max-jobs = auto
require-sigs = true
sandbox = true
sandbox-fallback = false
substituters = https://cache.nixos.org/ https://hydra.ist.nicht-so.sexy
system-features = nixos-test benchmark big-parallel kvm
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.ist.nicht-so.sexy-1:E+AwZnzYPdycs1IkHrlG0eJeBleAW/ukX10lcjTc2RQ=
trusted-substituters = 
trusted-users = root @wheel
use-xdg-base-directories = true
keep-derivations = true
keep-outputs = true
system-features = big-parallel builtin nixos-test local kvm benchmark
```

###### ~/.config/nix/nix.conf

```
# WARNING: this file is generated from the nix.settings option in
# your Home Manager configuration at $XDG_CONFIG_HOME/nix/nix.conf.
# Do not edit it!
use-xdg-base-directories = true
!include /home/ma27/.local/share/secrets/nix.conf-gh
# Allow adding additional stuff manually for temporary testing.
!include /home/ma27/.config/nix/manual.conf
```

`nix.conf-gh` contains a single line with `extra-access-tokens`; `manual.conf` doesn't exist.

###### /etc/nix/nix.conf of the remote builder

```
allowed-uris = github: gitlab: git+https://git.mbosch.me git+https://git.sr.ht https://github.com git+https://github.com
allowed-users = *
auto-optimise-store = false
builders = 
builders-use-substitutes = true
cores = 10
experimental-features = nix-command flakes
extra-sandbox-paths = /bin/sh=/nix/store/7dpxg7ki7g8ynkdwcqf493p2x8divb4i-bash-5.2-p15/bin/sh
log-lines = 0
max-jobs = auto
require-sigs = true
sandbox = true
sandbox-fallback = false
substituters = https://cache.nixos.org/ https://hydra.ist.nicht-so.sexy
system-features = nixos-test benchmark big-parallel kvm
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.ist.nicht-so.sexy-1:E+AwZnzYPdycs1IkHrlG0eJeBleAW/ukX10lcjTc2RQ=
trusted-substituters = 
trusted-users = root @wheel
keep-outputs = true
system-features = big-parallel builtin nixos-test local kvm benchmark
```

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by YuMingLiao** [comment]
I have these two warnings too when I update to nix 2.19.1 and use my repl. After I delete `impure-derivations` in `experimental-feautres` in my `nix.conf`, they are gone.

**Comment by teto** [comment]
got the warnings as well after upgrading to 2.19, which shows a wall of the same warnings. I dont see it anywhere in my config so it may  be a default that triggers the issue :'(

**Comment by jakubgs** [comment]
I can confirm that these warnings appear in `2.19.2` for no good reason. None of my config files include `auto-allocate-uids` nor `impure-env`, so this does seem like a bug.

If I add `configurable-impure-env` to `experimental-features` it does prevent this warning:
```
warning: Ignoring setting 'impure-env' because experimental feature 'configurable-impure-env' is not enabled
```
And if I add `auto-allocate-uids` to `experimental-features` it does prevent this warning:
```
warning: Ignoring setting 'auto-allocate-uids' because experimental feature 'auto-allocate-uids' is not enabled
```
But I don't want to enable those experimental features, so this is not an actual solution.

**Comment by jakubgs** [comment]
I can also confirm this happens on `2.20.1` as well.
