### ISSUE TITLE
Implement resolve-system-dependencies in c++

### ISSUE THREAD

**Issue by shlevy** [NixOS/nix#989]
This is needed for the `perl-to-c++` work, but I don't have access to a darwin box to actually run it. @pikajude can you take this one? I'll help out however I can.

**Comment by shlevy** [comment]
(note that non-darwin can be perl-free without this due to 3c68a661f28ffb52efbca10146a059003ff579a7)

**Comment by shlevy** [comment]
@pikajude ping

**Comment by domenkozar** [comment]
@shlevy don't we need to port the rest of the scripts to C++?

**Comment by shlevy** [comment]
Yes, this is just about the resolve-system-dependencies one which I can't do because I don't have a darwin box.

**Comment by domenkozar** [comment]
@shlevy if you don't manage to get help from @pikajude, I'm sure you could get access to `mac-5` from the build slaves to implement this.

**Comment by pikajude** [comment]
Hi everyone, sorry I just saw the emails for this thread (Github sends me a lot of emails). I'll try to work on this today

**Comment by domenkozar** [comment]
Note that it's worth fixing https://github.com/NixOS/nix/pull/941 while rewriting this.

**Comment by shlevy** [comment]
@pikajude status on this? It's the last thing in the perl removal...

**Comment by pikajude** [comment]
I'll have very limited time over the next few days. I'll try to get this knocked out but it may not be done till next week

**Comment by shlevy** [comment]
Thanks! No rush, just wanted to know if I should pick it up.

**Comment by domenkozar** [comment]
This has been merged to master in https://github.com/NixOS/nix/pull/1030
