### ISSUE TITLE
`nix-collect-garbage -d` Broke my nix installation.

### ISSUE THREAD

**Issue by abhillman** [NixOS/nix#9898]
**Describe the bug**

`nix-collect-garbage -d` Broke my nix installation -- i.e. `nix` not on my path anymore.

**Steps To Reproduce**

macOS Sonoma

**Comment by abhillman** [comment]
I can't reproduce in a VM, so I will close. It's possible this happened after upgrading to macOS 14.3 from 14.2. If I can repro with that path, I will create a ticket.

![output](https://github.com/NixOS/nix/assets/1097794/1333782d-af52-477e-8156-849c89f552ea)

**Comment by cole-h** [comment]
Sounds like you ran into https://github.com/NixOS/nix/issues/3616, if it happened after an update.
