### ISSUE TITLE
Use <nixpkgs> buildEnv for nix-env

### ISSUE THREAD

**Issue by shlevy** [NixOS/nix#990]
As far as I know, there is no user of nix-env (aside from the nix tests themselves) that doesn't depend on nixpkgs in some way. Rather than maintaining two versions (one of which will soon have to be in C++!), nix-env can just use the `nixpkgs` buildEnv directly. This will also make it easier to improve nix-env.

**Comment by shlevy** [comment]
@edolstra

**Comment by shlevy** [comment]
@edolstra ping this is blocking the perl conversion

**Comment by edolstra** [comment]
No, I don't think `nix-env` should depend on Nixpkgs.
