### ISSUE TITLE
nix-env -i downloads much slower than nix-prefetch-url

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nix#991]
I was updating a package when I noticed that ```nix-env -iA package-name``` took forever to download the sources - about 200KB/s. Just for the fun of it, I tried ```nix-prefetch-url -A package-name.src``` and that downloaded about 20 times faster. It's not caching as I removed the source from the package store and could replicate the results.

- nix-env (Nix) 1.11.2
- 16.09pre-git (Flounder)

**Comment by edolstra** [comment]
Without an actual URL this is impossible to reproduce.

**Comment by peterhoeg** [comment]
@edolstra , sure, no problem:

1) checkout the ```dropbox``` branch on nixpkgs
2) run ```time nix-prefetch-url -A dropbox.src```. For me:
```nix-prefetch-url -A dropbox.src  0.56s user 0.37s system 4% cpu 21.316 total```
3) remove it again from the store
4) run ```time nix-env -f . -i dropbox```. As of right now for me, downloading that same 65MB file is still going on. About 85% done after 4 minutes.

**Comment by edolstra** [comment]
This is because `dl-web.dropbox.com` provides HTTP 2, which fetchurl's curl uses, but apparently their HTTP 2 server is much slower than 1.1:
```
$ time curl --http1.1 -L https://dl-web.dropbox.com/u/17/dropbox-lnx.x86_64-3.20.1.tar.gz > /dev/null
...
real    0m8.883s

$ $ time curl --http2 -L https://dl-web.dropbox.com/u/17/dropbox-lnx.x86_64-3.20.1.tar.gz > /dev/null
...
real    5m55.478s
```

Unfortunately there is not much that we can do about this.
