### ISSUE TITLE
More outdated build instructions

### ISSUE THREAD

**Issue by siddharthist** [NixOS/nix#992]
Looks like this page is outdated:
 * https://github.com/NixOS/nix/blob/69f28eb3358be3aff7420317b663b7d6a110a3ec/doc/manual/installation/building-source.xml

It also mentions the 
```
./configure
make
make install
```
workflow, which, as I understand it, this project doesn't use.

Should we remove it? Anybody have ideas on what the most current instructions actually should be?

**Comment by edolstra** [comment]
No, Nix absolutely does use Autoconf and make.

**Comment by siddharthist** [comment]
@edolstra So on issue https://github.com/NixOS/nix/issues/987, @copumpkin mentioned that those instructions weren't up to date and that I should use the ones in `hacking`. Is that not correct? If these instructions should work, should I reopen that issue (where they didn't work for me)?

**Comment by domenkozar** [comment]
@siddharthist be sure to include a http://sscce.org/, something anyone can follow and reproduce.

**Comment by siddharthist** [comment]
@domenkozar I did in #987 :smile: 

So I've gotten conflicting feedback here:
 1. On #987, @copumpkin told me that those instructions were (probably) outdated
 2. In #988, @edolstra merged my PR that removed them
 3. In this issue, @edolstra has told me that those same instructions, in a different file, are valid.

So this is what I'm left wondering about:
 1. Are those instructions (`autoconf`, `configure`, `make`, `make install`) supposed to work?
    i. If so, should I just reopen #987, where I posted a log of them not working for me?
    ii. If not, can we reopen this issue?

**Comment by copumpkin** [comment]
@siddharthist keep in mind what I wrote on that other ticket

> 1. Run bootstrap.sh
> 2. Run the equivalent of configurePhase, which should be ./configure passing it a modified version of [this blurb](https://github.com/NixOS/nix/blob/master/release.nix#L83-L90) to point at the correct paths on your system.
> 3. Run make, etc.

If you peek inside bootstrap.sh and the blurb I linked to, it's clearly just using standard autoconf building blocks, but requires a few parameters. Not saying the documentation shouldn't clarify, but there's no doubt that the project is using autoconf.

**Comment by siddharthist** [comment]
@copumpkin Thanks for your continued help. I see that the project is definitely using autoconf. 

It seems that I cannot run `configure` without some mandatory flags (maybe those in that blurb). Am I correct in saying that the instructions linked to at the top of this ticket shouldn't be removed, but modified to reflect that there are mandatory flags when using `configure`?

It seems that running `
