### ISSUE TITLE
nix-env should respect <nixpkgs>

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nix#993]
Extracted from https://github.com/NixOS/nix/issues/968:

If one has no channels, `NIX_PATH=nixpkgs=http://nixos.org/channels/nixos-16.03/nixexprs.tar.xz` should still provide packages to nix-env.

**Comment by danbst** [comment]
linking https://github.com/NixOS/nix/issues/886 and https://github.com/NixOS/nixpkgs/issues/352

**Comment by danbst** [comment]
Also, linking part of NixUI proposal
> nix-channel and ~/.nix-defexpr are gone. We'll use $NIX_PATH (or user environment specific 
> overrides configured via nix set-path) to look up packages. Since $NIX_PATH supports 
> URLs nowadays, this removes the need for channels: you can just set $NIX_PATH to e.g. 
> https://nixos.org/channels/nixos-15.09/nixexprs.tar.xz and stay up to date automatically.

**Comment by edolstra** [comment]
Indeed this is now implemented (d74236d1f2c3bca4fcc8cb1574fb962e813f69d3). We probably shouldn't mess with legacy `nix-env` semantics though.

**Comment by CMCDragonkai** [comment]
@edolstra Was this only implemented for the new nix tool and not the current `nix-env`? That is I have 1.11.15.

**Comment by edolstra** [comment]
@CMCDragonkai Yeah, only the new interface.

**Comment by uri-canva** [comment]
I just tested `export NIX_PATH=nixpkgs=$HOME/github/NixOS/nixpkgs` with `nix-env (Nix) 2.0` and it worked, it picked up my local changes to the packages.

Is this intentional or is it a bug? https://github.com/NixOS/nix/issues/993#issuecomment-339406869 makes it sound like the behaviour of `nix-env` with regards to `NIX_PATH` was not going to change.

**Comment by edolstra** [comment]
As far as I know the behaviour hasn't changed.

**Comment by CMCDragonkai** [comment]
@edolstra I'm wondering why the nix 2.0 doesn't have a nix-env replacement such that it respects the `NIX_PATH`?

**Comment by edolstra** [comment]
@CMCDragonkai Just that I haven't implemented it yet (mainly because it's TBD what to do wrt declarative vs. imperative package management and channels). There are some notes at https://gist.github.com/edolstra/efcadfd240c2d8906348.
