### ISSUE TITLE
`nix repl` prints error messages when input is not a TTY

### ISSUE THREAD

**Issue by 9999years** [NixOS/nix#9941]
**Describe the bug**

For testing, I sometimes want to feed input to the `nix repl` from a file so I can run it as part of a script. Unfortunately, when I try this, I get a bunch of error messages.

**Steps To Reproduce**

```
$ echo builtins.nixVersion | nix repl
Welcome to Nix 2.18.1. Type :? for help.

Failed tcsetattr(TCSADRAIN): Inappropriate ioctl for device
"2.18.1"

Failed tcsetattr(TCSADRAIN): Inappropriate ioctl for device
```

**Expected behavior**

```
$ echo builtins.nixVersion | nix repl
Welcome to Nix 2.18.1. Type :? for help.

nix-repl> "2.18.1"
```

**`nix-env --version` output**

```
$ nix-env --version
nix-env (Nix) 2.18.1
```

It fails on the latest `master` too.

**Additional context**

I've reproduced this bug on Linux and macOS.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by edolstra** [comment]
Well, it's a REPL, so it's intended to be run with a TTY. For non-TTY use cases, `nix eval` is better.

**Comment by lf-** [comment]
> Well, it's a REPL, so it's intended to be run with a TTY. For non-TTY use cases, `nix eval` is better.

Hi Eelco, I actually ran into this while trying to implement a nicer testing framework for `nix repl` in C++, which would otherwise pointlessly require implementing an entire `pty` simulation. We need to be able to use Nix from a non-tty environment to not make that code unnecessarily ugly.

**Comment by lf-** [comment]
That is to say, this is a completely valid use case, which, *we ourselves* need.

**Comment by 9999years** [comment]
> Well, it's a REPL, so it's intended to be run with a TTY.

Sure, but I can't find another REPL that prints error messages if it's used with a non-interactive STDIN. Python, Ruby, Bash, even `bc(1)` is fine with non-TTY input:

```
$ echo "exit()" | python3 -i
Python 3.11.7 (main, Dec  4 2023, 18:10:11) [Clang 16.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
$ echo quit | irb
Switch to inspect mode.
quit
$ echo exit | bash
$ echo quit | bc
```

As @lf- says, we want this feature so we can write a better test suite for `nix repl` (and for the `--debugger`, see #8610).
