### ISSUE TITLE
`make OPTIMIZE=0` still builds with `-O2`

### ISSUE THREAD

**Issue by thufschmitt** [NixOS/nix#9965]
**Describe the bug**

Setting `OPTIMIZE=0` when calling `make` should disable the optimisations (thus leading to a much faster build).
However, the `Makefile.config` hardcodes a `-O2` which takes precedence, meaning that the variable has barely any effect (switching from `-O3` to `-O2`)

**Steps To Reproduce**

```console
$ nix develop
$ autoreconfPhase
$ configurePhase
$ make src/libutil/git.o OPTIMIZE=0 -n
```

notice that the `CXX` command has `-O0 [lots of stuff] -O2`

**Expected behavior**

Fast build when asked

**Additional context**

It looks like the `-O2` is hardcoded in the configure script (generated by autoconf), but I've no idea how to track that further because autoconf is some dark magic from another astral plane.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by edolstra** [comment]
Isn't `-O0` also overriden by the default hardening flags in Nixpkgs?

**Comment by thufschmitt** [comment]
In the compiler wrapper you mean? That would be sad

**Comment by Mic92** [comment]
I don't think it is overwritten, because I get a warning though that that the _FORTIFY_SOURCE=2 hardening flag does require `-O2`, which is not enabled in debug builds.
