### ISSUE TITLE
rev not found when using default/unspecified git submodule ref

### ISSUE THREAD

**Issue by Princemachiavelli** [NixOS/nix#9979]
**Describe the bug**

Nix >= 2.20.0 can no longer find `rev` in submodule of flake or flake input if not in the `ref` (including just the default HEAD/master `ref` when unspecified).
Instead gives error like:

`error: Cannot find Git revision '5785dcfee699047f4f6e89e71502da6518c0d997' in ref 'master' of repository 'ssh://git@github.com/Princemachiavelli/badsub/git@github.com:Princemachiavelli/submodule_a.git'! Please make sure that the rev exists on the ref you've specified or add allRefs = true; to fetchGit.`

**Steps To Reproduce**

1. Run `nix build 'git+https://github.com/Princemachiavelli/badsub?submodules=1#default'`

**Expected behavior**
Build should succeed and have output containing: `I only exist in branchc`.

Works in: 2.18.1, 2.19.3
Broken in: 2.20.1, nix (Nix) 2.21.0pre20240209_28a988b

A git bisect run says that "d88106df24869104cc6c29c726ddfbbfda9dae10 is the first bad commit".

**submodule config**
The submodule config is what I expect 99% of Git users to have; just the path and url specified but no explicit ref defined.
```
[submodule "submodule_a"]
  path = submodule_a
  url = git@github.com:Princemachiavelli/submodule_a.git
```

**Nix Error Log**
```
evaluating file '<nix/derivation-internal.nix>'
evaluating derivation 'git+ssh://git@github.com/Princemachiavelli/badsub?submodules=1#default'...
resolved HEAD ref 'refs/heads/main' for repo '/home/jhoffer/.cache/nix/gitv3/086s4ywfwwxn7di41a0rzfmdn89ivh91dj11a1z83kxclrpn2ng2'
using cached HEAD ref 'refs/heads/main' for repo 'ssh://git@github.com/Princemachiavelli/badsub'
locking path '/home/jhoffer/.cache/nix/gitv3/086s4ywfwwxn7di41a0rzfmdn89ivh91dj11a1z83kxclrpn2ng2'
lock acquired on '/home/jhoffer/.cache/nix/gitv3/086s4ywfwwxn7di41a0rzfmdn89ivh91dj11a1z83kxclrpn2ng2.lock'
lock released on '/home/jhoffer/.cache/nix/gitv3/086s4ywfwwxn7di41a0rzfmdn89ivh91dj11a1z83kxclrpn2ng2.lock'
using cache entry '{"_what":"gitLastModified","rev":"e08d3ba0cb74a8f68543efe7787e9c147cea3c5f"}' -> '{"lastModified":1707518936}'
using cache entry '{"_what":"gitRevCount","rev":"e08d3ba0cb74a8f68543efe7787e9c147cea3c5f"}' -> '{"revCount":3}'
using revision e08d3ba0cb74a8f68543efe7787e9c147cea3c5f of repo 'ssh://git@github.com/Princemachiavelli/badsub'
Git submodule /submodule_a: git@github.com:Princemachiavelli/submodule_a.git  5785dcfee699047f4f6e89e71502da6518c0d997 -> ssh://git@github.com/Princemachiavelli/badsub/git@github.com:Princemachiavelli/submodule_a.git
fatal: remote error:
  is not a valid repository name
Visit https://support.github.com/ for help
warning: could not read HEAD ref from repo at 'ssh://git@github.com/Princemachiavelli/badsub/git@github.com:Princemachiavelli/submodule_a.git', using 'master'
locking path '/home/jhoffer/.cache/nix/gitv3/07p43rv1xm09m4ph77wgfkz2nhayr7rf0q5y4q6s6p1nb0dkl61z'
lock acquired on '/home/jhoffer/.cache/nix/gitv3/07p43rv1xm09m4ph77wgfkz2nhayr7rf0q5y4q6s6p1nb0dkl61z.lock'
fetching Git repository 'ssh://git@github.com/Princemachiavelli/badsub/git@github.com:Princemachiavelli/submodule_a.git'...
fatal: remote error:
  is not a valid repository name
Visit https://support.github.com/ for help
warning: could not update mtime for file '/home/jhoffer/.cache/nix/gitv3/07p43rv1xm09m4ph77wgfkz2nhayr7rf0q5y4q6s6p1nb0dkl61z/refs/heads/master': No such file or directory
evaluating derivation 'git+ssh://git@github.com/Princemachiavelli/badsub?submodules=1#default'fatal: Refusing to point HEAD outside of refs/
warning: could not update cached head 'master' for 'ssh://git@github.com/Princemachiavelli/badsub/git@github.com:Princemachiavelli/submodule_a.git'
lock released on '/home/jhoffer/.cache/nix/gitv3/07p43rv1xm09m4ph77wgfkz2nhayr7rf0q5y4q6s6p1nb0dkl61z.lock'
error:
       … while fetching the input 'git+ssh://git@github.com/Princemachiavelli/badsub?submodules=1'

       … while fetching the input 'git+ssh://git@github.com/Princemachiavelli/badsub/git@github.com:Princemachiavelli/submodule_a.git?rev=5785dcfee699047f4f6e89e71502da6518c0d997'

       error: Cannot find Git revision '5785dcfee699047f4f6e89e71502da6518c0d997' in ref 'master' of repository 'ssh://git@github.com/Princemachiavelli/badsub/git@github.com:Princemachiavelli/submodule_a.git'! Please make sure that the rev exists on the ref you've specified or add allRefs = true; to fetchGit.
```

**Comment by bouk** [comment]
This problem is actually that the submodule url is resolved relative to the git repo path, which you can see in the log:

`ssh://git@github.com/Princemachiavelli/badsub/git@github.com:Princemachiavelli/submodule_a.git` that's not a valid repo!

I also ran into it with the following: `nix flake prefetch 'git+ssh://git@github.com/miquelmassot/g2o-python.git?submodules=1&ref=tags/v0.0.14'`

**Comment by Princemachiavelli** [comment]
@bouk  Great find! I assumed that weird URL was just a internal string representation of a submodule. I can confirm this fixes the issue.

FYI it looks like my example repo broke when I switched the URLs to the public URLs but that also break the test since the issue only occurs with some submodule URLs... rev `e08d3ba0cb74a8f68543efe7787e9c147cea3c5f` shows the issue correctly but uses the private SSH URL. (At NixCon NA ATM but I'll fix the test repo when I get a chance.)
