### ISSUE TITLE
docker: Unable to pull nix image from ghcr.io

### ISSUE THREAD

**Issue by BOHverkill** [NixOS/nix#9982]
## Platform

- [x] Linux: Arch Linux
- [ ] macOS
- [ ] WSL

## Additional information

I'm unable to pull the nix docker image from the GitHub container registry (`ghcr.io/nixos/nix`), as stated in the [Using Nix within Docker](https://nixos.org/manual/nix/stable/installation/installing-docker#using-nix-within-docker) installation documentation, resulting in an `unauthorized` error. The [Docker Hub](https://hub.docker.com/r/nixos/nix) image is working for me and I made sure that I can pull images from other GitHub container registries.
My guess is that the packages is private, as I'm unable to see the nix docker container in the [GitHub Packages UI of the NixOS organisation](https://github.com/orgs/NixOS/packages?repo_name=nix) and the default visibility of new packages is private (see: [Configuring visibility of packages for an organization](https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility#configuring-visibility-of-packages-for-an-organization)).

## Output

<details><summary>Output</summary>

```log
$ docker pull ghcr.io/nixos/nix
Using default tag: latest
Error response from daemon: Head "https://ghcr.io/v2/nixos/nix/manifests/latest": unauthorized
```

</details>

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by abathur** [comment]
I'm not already up on this, but after picking through history to see if I could figure it out, it looks like there's a missing piece that has fallen through the cracks. 

This was documented (and mostly implemented) in one PR, but the followup hasn't landed:
- #8066
- #9200

**Comment by BOHverkill** [comment]
That's true, but that's only part of the problem, as I'm not able to pull _any_ nix container versions from ghcr.io. According to the changes in https://github.com/NixOS/nix/pull/8066 the CI actions should already push a `master` and version tag (the same as to [Docker Hub](https://hub.docker.com/r/nixos/nix/tags)), which I also not able to pull:

```
$ docker pull ghcr.io/nixos/nix:master
Error response from daemon: Head "https://ghcr.io/v2/nixos/nix/manifests/master": unauthorized
$ docker pull ghcr.io/nixos/nix:2.21.0pre20240209_28a988b
Error response from daemon: Head "https://ghcr.io/v2/nixos/nix/manifests/2.21.0pre20240209_28a988b": unauthorized
```

**Comment by abathur** [comment]
Perhaps @baloo will know if that's expected or not.

**Comment by baloo** [comment]
I've never actually got to test pulling from ghcr.
This came up because hub.docker.com started to enforce strict rate limits that I was hitting. Because the PR took so long I ended using a private mirror as to not have the rate limits and never switched to GHCR myself.

Sorry.

But yeah, from the looks of it, it would seem like the settings are just incorrect:
https://github.com/orgs/nixos/packages/container/nix/settings (if someone with access could check)

**Comment by krad246** [comment]
Also happens to me on my MacBook.

**Comment by zimbatm** [comment]
Fixed. I also reduced the permissions of GitHub Actions. Previously, it had the admin role, and I believe this is too wide. Let me know if that was a mistake:
![image](https://github.com/NixOS/nix/assets/3248/bc91feaa-6f2a-4c1c-886e-a2ead1ce5aa6)

**Comment by baloo** [comment]
@zimbatm the permission change looks fine:
https://github.com/NixOS/nix/actions/runs/7991379973/job/21824017649#step:15:1

As far as I can tell it still upload like expected.
```
$ docker pull ghcr.io/nixos/nix:2.21.0pre20240221_3f5d7af
2.21.0pre20240221_3f5d7af: Pulling from nixos/nix
[...]
Status: Downloaded newer image for ghcr.io/nixos/nix:2.21.0pre20240221_3f5d7af
ghcr.io/nixos/nix:2.21.0pre20240221_3f5d7af
```

Thanks a lot!

**Comment by dotysan** [comment]
Please see #10042 as you've pushed to `ghcr.io/nixos/nix:master` not `ghcr.io/nixos/nix:latest`.
