### ISSUE TITLE
nix-copy-closure lacks support for multiple signatures

### ISSUE THREAD

**Issue by skvl** [NixOS/nix#999]
Hello.

I'm trying to setup binary cache for my self. What I have done already:
1. I have added `nix.sshServe.enable = true` and `nix.sshServe.keys = [ <MY_PUBLIC_SSH_KEY> ]` into *configuration.nix* of my "server".
2. I have added test RSA keys with script (executed on non NixOS system):
```
#! /bin/bash

## README ##
# This is very strict version becase it asks signature password
# for every closure (about 35 times for 'w3m' package)
## ##

REMOTE=$1
USER=$2

openssl genrsa -aes256 -out signing-key.sec 4096
openssl rsa -in signing-key.sec -outform PEM -pubout -out signing-key.pub
cp signing-key.sec /etc/nix/signing-key.sec
chmod 600 /etc/nix/signing-key.sec
scp signing-key.pub $REMOTE:~

## THIS NOT WORKING FOR MULTIPLE PEM SIGNATURES
ssh -tt $REMOTE "sudo bash -c 'echo -----SIGNATURE OF $USER----- >> /etc/nix/signing-key.pub'; 

## AND THIS WORKS
# sudo bash -c 'cat ./signing-key.pub >> /etc/nix/signing-key.pub'"
```
3. I have repeated this for my default user.
4. I have run test deploy:
```
nix-env -i w3m
nix-copy-closure --sign $REMOTE $(type -P w3m)
```

In result I received an error:
> error: program ‘.../bin/openssl’ failed with exit code 1

**Comment by edolstra** [comment]
OpenSSL-based signing has been removed from Nix master (f435f8247553656774dd1b2c88e9de5d59cab203)  so this won't be fixed. However, the next version of Nix generalizes binary cache signatures by storing them in the Nix database, and they'll be propagated and checked by nix-copy-closure.

**Comment by skvl** [comment]
@edolstra thank You for reply. Which options for home binary cache I have?

**Comment by skvl** [comment]
@edolstra without *--sign* flag *nix-copy-closure* results in `lacks a signature`. So this command could not be used?
